### ISSUE TITLE
OSS Gateワークショップ2016-01-30: akito19: pg: 作業ログ

### ISSUE THREAD

**Issue by akito19** [oss-gate/workshop#10]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by akito19** [comment]
* 作業: GitHub上のruby-pgがmirrorだったので、本体のbitbucketにいってみた
* 思ってること: bitbucketの使い勝手がよくわからない

**Comment by akito19** [comment]
* ドキュメント読む http://deveiate.org/code/pg/README_rdoc.html
* Rubyの要件が古そう
 * > Ruby 1.9.3-p392, or 2.0.0-p0.

**Comment by akito19** [comment]
* `gem install pg` でインストールした

**Comment by akito19** [comment]
* ライブラリのサンプルコードを動かすためのディレクトリ、ファイルを作って実行
 * 怒られた

```
akito@kasai:~ $ cd pg
akito@kasai:~/pg $ vim sample.rb
akito@kasai:~/pg $ ruby sample.rb
/Users/akito/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `initialize': fe_sendauth: no password supplied (PG::ConnectionBad)
        from /Users/akito/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `new'
        from /Users/akito/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `connect'
        from sample.rb:6:in `<main>'
```

**Comment by akito19** [comment]
* サンプルコードの内容を手元のdb, テーブル名に合わせてみようとする
 * サンプルコード内の String#% わかんない
  * `%` のドキュメント見てみる
   * sprintf のドキュメント見てみる

**Comment by akito19** [comment]
* 手元DBの内容に合わせてサンプルコードを書き換えて実行
 * DBに接続するパスワードがなくて怒られた

**Comment by akito19** [comment]
```
#!/usr/bin/env ruby

require 'pg'

# Output a table of current connections to the DB
conn = PG.connect( dbname: 'onebox_development' )
conn.exec( "SELECT * FROM services" ) do |result|
  puts "     id | description             | price"
  result.each do |row|
    puts " %7d | %-16s | %4d " %
      row.values_at('id', 'description', 'price')
  end
end
```

**Comment by akito19** [comment]
* connect するときの引数に psql の password を渡してからスクリプトを実行してみる
 * うごいた

connect の引数に渡せるオプションを調べるために pg のレファレンスをみる ( http://deveiate.org/code/pg/PG.html#method-c-connect )

該当部から `PG::connection.new ` のレファレンスでオプションみる

**Comment by akito19** [comment]
* Ruby のrequirementsがふるい
 * or later とかあればわかりやすそう
* ~PGのパスワード未設定が前提~
 * ~wikiにオプションについてのページに飛ぶリンクはあった~
* パスワードを設定していた場合にサンプルコードを実行すると、サンプルのdbがないことを怒られるのではなくてpasswordがないことを怒られる。
 * 未設定が前提のサンプルなので、オプション扱いのpasswordがない内容のエラーよりもdbnameがない内容のエラーが優先されてたほうがべんりそう

**Comment by akito19** [comment]
サンプルコードのインデントずれてる
https://github.com/ged/ruby-pg

bitbucket側は問題ない

**Comment by akito19** [comment]
インデント修正のぷるり https://github.com/ged/ruby-pg/pull/12

**Comment by akito19** [comment]
PG::ConnectionBad を追ってみた結果、gem関係なくPostgreSQLさんサイドがエラーメッセージつくってるぽい？

**Comment by akito19** [comment]
* パスワードがsupplyされていない旨のエラーメッセージが出る前にdbnameが存在していない旨のエラーメッセージが出ていた方がいい
 * サンプルのdbは間違いなく存在しないがパスワードは存在しないとは限らないので不親切感

**Comment by akito19** [comment]
Travis落ちた
→ OpenSSLで直接バージョンを指定していて、それが消されていた

**Comment by kou** [comment]
おつかれさまでした！
