### ISSUE TITLE
OSS Gate Workshop: Osaka: 2018-11-24: kane-sei: Atom: Work log

### ISSUE THREAD

**Issue by kane-sei** [oss-gate/workshop#1000]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kozo2** [comment]
メンターさせてもらいます

**Comment by kane-sei** [comment]
インストール済みatomのバージョン確認
```
atom --version
```

**Comment by kane-sei** [comment]
開発環境を作るのをめざす
ここを読んでこのとおり進めてみる。
https://flight-manual.atom.io/hacking-atom/sections/debugging/

**Comment by kane-sei** [comment]
バージョン確認
```
kanedakiyoshishinoMacBook-ea:~ kanesan$ atom --version
-bash: atom: command not found
```
失敗した。

**Comment by kane-sei** [comment]
インストールが良くないみたいだ。
ここを参考に入れ直し
https://flight-manual.atom.io/getting-started/sections/installing-atom/

**Comment by kane-sei** [comment]
ダウンロード
https://atom.io

**Comment by kane-sei** [comment]
インストール

> Atom follows the standard Mac zip installation process. You can either press the download button from the https://atom.io site or you can go to the Atom releases page to download the atom-mac.zip file explicitly. Once you have that file, you can click on it to extract the application and then drag the new Atom application into your "Applications" folder.

**Comment by kane-sei** [comment]
```
which atom
```

・・・いない

**Comment by kane-sei** [comment]
> To install the atom and apm commands, run "Window: Install Shell Commands" from the Command Palette, which will prompt you for an administrator password.

これをしてみる。

**Comment by kane-sei** [comment]
```
kanedakiyoshishinoMacBook-ea:~ kanesan$ which atom
/usr/local/bin/atom
```
入った。

**Comment by kane-sei** [comment]
```
atom -version
```
・・・エラー出た。
![2018-11-24 14 11 55](https://user-images.githubusercontent.com/45293757/48964814-ff59cf00-eff2-11e8-98e4-00526ff9d008.png)

**Comment by kane-sei** [comment]
もう一度インストールし直し。

**Comment by kane-sei** [comment]
ダウンロード元を変えてみる。
https://github.com/atom/atom/releases/tag/v1.32.2

**Comment by kane-sei** [comment]
```
kanedakiyoshishinoMacBook-ea:~ kanesan$ atom --version
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

コマンド打ち間違えでした。正しいコマンドで解決しました。

**Comment by kane-sei** [comment]
Debbugingページに戻って続行
https://flight-manual.atom.io/hacking-atom/sections/debugging/

**Comment by kane-sei** [comment]
セーフモードで起動
```
atom --safe
```

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by kane-sei** [comment]
https://flight-manual.atom.io/hacking-atom/sections/debugging/

safe-modeの後、手順が複雑化する。
ソースコード修正まで今日進むのは難しそう。

今日の時間的に、先ほどのエラーをバグ報告することに方針変更。

**Comment by kane-sei** [comment]
バグ報告先を探す。
本家：https://atom.io からリンクされている
Github.com/atom
に移動。

**Comment by kozo2** [comment]
https://github.com/oss-gate/workshop/issues/1000#issuecomment-441344994
をフィードバックしましょう。
テンプレートは
https://github.com/atom/atom/tree/master/.github/ISSUE_TEMPLATE
になります。
ちなみにこれはWindowsでも同様でした。
https://github.com/oss-gate/workshop/issues/1004#issuecomment-441345506

**Comment by kane-sei** [comment]
issue templateに、feature requestとbug reportの2種がある。
https://github.com/atom/atom/tree/master/.github/ISSUE_TEMPLATE

でてるメッセージがException〜というプログラムエラーなので、bug reportで報告しよう。

**Comment by kane-sei** [comment]
Github→New Issue→Bug Reportを選択
https://github.com/atom/atom/issues/new?template=bug_report.md

**Comment by kane-sei** [comment]
```
Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
```
と指示されてるので、似た報告を５分ぐらい探したが見つからなかった。

**Comment by kane-sei** [comment]
報告下書き

## Title
appeared program error  by mistaken atom command option.

## Description
The Program error was appeared when I  missed atom command option.


## Steps to Reproduce

[First Step]
atom -version    # not "--version"

### Expected behavior: [What you expect to happen]
A Command option error message is shown.

### Actual behavior: [What actually happens]
The program error dialog appears.
![2018-11-24 14 28 13](https://user-images.githubusercontent.com/45293757/48965464-fe2f9e80-f000-11e8-97dd-09a05b097a82.png)

### Reproduces how often: [What percentage of the time does it reproduce?]
100%

## Versions

You can get this information from copy and pasting the output of atom --version and apm --version from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

OS MacOS 10.13.6

## Additional Information

**Comment by kane-sei** [comment]
kozo2さんに報告下書きをレビューしていただく。

**Comment by kozo2** [comment]
## Title
--versionオプション打ち間違い時にerror dialogが現れる

## Description
端末中で
```
atom --version
```
を
```
atom -version
```
と打ち間違えると下記のエラーダイアログが表示される。
本来は端末中で下記のような応答をすべきと考える。
```
atom -version
invalid option -version
```

**Comment by kozo2** [comment]
## Steps to Reproduce
### [First Step]

atom -version    # not "--version"

### Expected behavior: [What you expect to happen]
```
invalid option -version
```

### Actual behavior: [What actually happens]
The program error dialog appears.

https://user-images.githubusercontent.com/45293757/48965464-fe2f9e80-f000-11e8-97dd-09a05b097a82.png

**Comment by kozo2** [comment]
## Title
Error dialog for version option typo

## Description
When I made a typo `atom -version` for `atom --version` , the following error dialog was displayed.

**Comment by kozo2** [comment]
I think this should be return
```
invalid option -version
```
in the terminal.
(And should not display the error dialog)

**Comment by kane-sei** [comment]
issue作成しました
https://github.com/atom/atom/issues/18488

**Comment by znz** [comment]
振り返りしました。
