### ISSUE TITLE
OSS Gate Workshop: Osaka: 2018-11-24: tksmkw: redmine: Work log

### ISSUE THREAD

**Issue by tksmkw** [oss-gate/workshop#1001]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by znz** [comment]
サポーターです。
よろしくお願いします。

**Comment by tksmkw** [comment]
よろしくお願いします。

**Comment by tksmkw** [comment]
開発したいソフトウェアを決めて、
licenseがオープンソースlicenseかをチェックする。

**Comment by tksmkw** [comment]
redmineで検索したら、日本のページしかヒットしなかった。
公式を追加して、以下を発見
https://www.redmine.org/

**Comment by tksmkw** [comment]
https://www.redmine.org/projects/redmine/wiki/RedmineInstall
に、インストールガイドがある

**Comment by tksmkw** [comment]
https://www.redmine.org/projects/redmine/wiki/Download
から、3.4.6 (2018-06-10):

    redmine-3.4.6.tar.gz (md5: 5f4993446ecf25782f469763c0d32ea1)

をダウンロード

**Comment by tksmkw** [comment]
SQLite 3をDBとして選択。Step2に記載がないため、他のDBをインストールしようとしてしまった。

**Comment by tksmkw** [comment]
databaseの設定をする。
sqlite3の設定は、webページにはない。
database.ymlにあるサンプルを有効にして、mysqlを無効にした。

**Comment by tksmkw** [comment]
gem install bundler をしようとしたら、permission deniedとなる。
su -は、できなかった。
sudo gem ... とするとコマンド成功

**Comment by tksmkw** [comment]
bundle install --without development test
をするときは、redmineを展開したフォルダに移動してから実施する。
途中で、rootパスワードを聞かれるので、入力する。

**Comment by tksmkw** [comment]
bundleをする時に、redmineを展開フォルダに移動すべきということは書いていない。

**Comment by tksmkw** [comment]
Step8は、ユーザの変更とアクセス権の付与
今回は、ユーザを変えないので、このStepは実行しない。
eg.に記載のフォルダも存在する。

**Comment by tksmkw** [comment]
Step9を実施
bundle exec rails server webrick -e production
コンソールで、INFOがでたあと、ブラウザから以下にアクセス
http://localhost:3000/. 
redmineのホームページが見れるようになった。

**Comment by tksmkw** [comment]
login by admin,admin

**Comment by tksmkw** [comment]
adminのパスワード変更を実施
動作が非常に重くなった。
更新された後は問題なし。

**Comment by tksmkw** [comment]
Configurationは、今回は実施していない。

**Comment by kozo2** [comment]
https://github.com/oss-gate/workshop/issues/1001#issuecomment-441344856
が普通わからないはずなので
sqlite3を使う場合は「ここの操作が必要」とフィードバックしてもらいたいです

**Comment by kozo2** [comment]
https://github.com/oss-gate/workshop/issues/1001#issuecomment-441344632
も何かフィードバックできそうであればお願いしたいです。
bundlerがredmine展開下の何かのfileを読んでいるんですかね？

**Comment by tksmkw** [comment]
有難うございます。調べてみます。

**Comment by tksmkw** [comment]
bundlerでは、当該フォルダにあるgemfileを元に一括インストールするので、redmine直下に移動するのが暗黙知となっているようです。

**Comment by kozo2** [comment]
個人的には
https://www.redmine.org/projects/redmine/wiki/RedmineInstall
のMySQLの上にsqlite3の導入・設定方法が入るようなフィードバックを期待したいです

**Comment by tksmkw** [comment]
<フィードバック>
Step 3 - Database connection configuration において、
sqlite3を使用した場合の、Exampleが無い。
sqlite3での設定方法が分からないため、sqlite3以外のDBのセットアップをしようとしてしまう。
sqlite3が最も簡単な方法なので、Exampleを記載した方が良い。
---
Example for a sqlite3 database
production:
  adapter: sqlite3
  database: db/redmine.sqlite3

**Comment by znz** [comment]
http://www.redmine.org/issues/18055 のように [Wiki](http://www.redmine.org/projects/redmine/wiki) に書かれているドキュメントについての話はチケットの Documentation カテゴリで報告すると良さそうです。

**Comment by tksmkw** [comment]
redmineのユーザーを「登録する」から作成した。

**Comment by tksmkw** [comment]
Title: Add sqlite3 case in installation guide STE2, STE3
Message:
I installed redmine with sqlite3 in my pc (mac) for trial.
then I wonder the setup and cofiguration for sqlite3.
So, could you please add sqlite3's case in installation guide as bellow.

Step 2 - Create an empty database and accompanying user
 Insert " if you chose sqlite3, skip this step"
 following "Redmine database user will be named redmine hereafter but it can be changed to anything else."

Step 3 - Database connection configuration
 Insert sqlite3's example as bellow,
"
 Example for a sqlite3 database
 production:
   adapter: sqlite3
   database: db/redmine.sqlite3
 "

**Comment by tksmkw** [comment]
https://www.redmine.org/issues/30023
に、チケット登録しました。

**Comment by yoichi** [comment]
ふりかえり2しました。

**Comment by yoichi** [comment]
フィードバックの応答早速来てますね。やったー！

**Comment by tksmkw** [comment]
feedbackを反映してもらいました！

https://www.redmine.org/projects/redmine/wiki/RedmineInstall/diff?utf8=%E2%9C%93&version=296&version_from=295
