### ISSUE TITLE
 OSS Gate Workshop: Osaka: 2018-11-24: exSOUL: metabase: Work log

### ISSUE THREAD

**Issue by exSOUL** [oss-gate/workshop#1002]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## Created Issue
https://github.com/metabase/metabase/issues/9013

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yoichi** [comment]
サポーターのなかやまです。よろしくおねがいします！

**Comment by exSOUL** [comment]
よろしくおねがいします!

**Comment by exSOUL** [comment]
https://github.com/metabase/metabase#installationを確認する。

**Comment by exSOUL** [comment]
Dockerがあるので以下のコマンドを実行してみる。  
`docker run -d -p 3000:3000 --name metabase metabase/metabase`

**Comment by exSOUL** [comment]
```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
dockerが動いてなかったので起動させる。

**Comment by exSOUL** [comment]
Dockerが少し古かったのでUpdate

**Comment by exSOUL** [comment]
DockerのUpdate後、改めて`docker run -d -p 3000:3000 --name metabase metabase/metabase`
を実行。今回は正常終了した。  
`http://localhost:3000`にアクセスして起動していることを確認。

**Comment by exSOUL** [comment]
README内のリンク[Installation Guides](https://www.metabase.com/docs/latest/operations-guide/start.html#installing-and-running-metabase)を確認してみる。

**Comment by exSOUL** [comment]
https://www.metabase.com/docs/latest/
にSettingとGetting Started があるのでそこを読んでみる。

**Comment by exSOUL** [comment]
初回Install後の画面が
 https://www.metabase.com/docs/latest/setting-up-metabase.html 
↑のガイドの画面だったので、こちらのSettingsを先にやるべきと判断。こちらをやっていく。

**Comment by exSOUL** [comment]
Adminユーザーの登録後、接続するDB選択画面に遷移するが、特に接続するDBもないため、
`I'll add my own data later`を選択。

**Comment by exSOUL** [comment]
次の設問`Allow Metabase to anonymously collect usage events`は、「メタベースが匿名で使用イベントを収集できるようにする」(Google翻訳)とのことなので、
チェックがついた状態(収集に同意)にする。

**Comment by exSOUL** [comment]
上記で最低限の設定が完了。
この次にニュースレターに登録するかのボタンが表示されるが、今回は登録しないでおく。

**Comment by exSOUL** [comment]
これで、https://www.metabase.com/docs/latest/getting-started.html
上記のGetting Startedに進めるようになった。

**Comment by exSOUL** [comment]
ログイン後に表示されるトップページ(The homepage部分の画像)が若干Versionが古いのか、ドキュメントに記載してある画像と若干UIが異なっている。

ドキュメントの画像
![ドキュメントの画像](https://www.metabase.com/docs/latest/images/ActivityFeed.png)  

↓実際の画像    
<img width="1280" alt="2018-11-24 14 13 23" src="https://user-images.githubusercontent.com/844642/48964830-421ba700-eff3-11e8-9403-831bf3d3baad.png">

**Comment by exSOUL** [comment]
ドキュメントに記載してある通りのクエリを発行した結果(Count)がドキュメント記載の`12284`とは異なっていた。  
`16309`だった。
ドキュメント記載の次の、CreatedAt: Day でフィルターしたところ、データのCreatedAtが2014→2016となっていたのでそもそものデータが変わっている模様。

**Comment by exSOUL** [comment]
保存する際のダイアログもドキュメントと少し異なっていた。(添付)  
<img width="605" alt="2018-11-24 14 35 05" src="https://user-images.githubusercontent.com/844642/48964934-3a113680-eff6-11e8-912d-5d8a455aa6a5.png">

**Comment by exSOUL** [comment]
コレクション、という項目が追加されていた。

**Comment by exSOUL** [comment]
保存後のダイアログも変わっている。
いままで: 戻る、ダッシュボードに追加する
いまの: ダッシュボードに追加しますか? はい・いいえ

<img width="450" alt="2018-11-24 14 36 48" src="https://user-images.githubusercontent.com/844642/48964946-82305900-eff6-11e8-8133-35db35c58e1e.png">

**Comment by exSOUL** [comment]
ダッシュボードへの追加、追加後のダッシュボード表示も若干異なっていた。
最新版では、グリッドが表示されるようになっていた。
<img width="1280" alt="2018-11-24 14 39 33" src="https://user-images.githubusercontent.com/844642/48964961-e226ff80-eff6-11e8-8f10-83985494a12f.png">

**Comment by exSOUL** [comment]
保存まえのクエリ(Question)も作成画面のURLで共有できる模様。
例: http://localhost:3000/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MiwiZmlsdGVyIjpbImFuZCIsWyI-IixbImZpZWxkLWlkIiwxM10sNTBdXSwiYWdncmVnYXRpb24iOltbImNvdW50Il1dfSwidHlwZSI6InF1ZXJ5IiwiZGF0YWJhc2UiOjF9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

**Comment by exSOUL** [comment]
herokuにもDeploy
https://exsoul-metabase-oss-gate-osaka.herokuapp.com

**Comment by exSOUL** [comment]
インストールしたバージョンは `v0.31.0`

**Comment by znz** [comment]
振り返りしました。
古くなっているドキュメントは https://github.com/metabase/metabase/blob/master/docs/getting-started.md のようでした。

**Comment by exSOUL** [comment]
https://www.metabase.com/docs/latest/
上記のドキュメントは、以下のGithubにある模様
https://github.com/metabase/metabase/tree/master/docs
https://github.com/metabase/metabase/blob/master/docs/getting-started.md. 
↑など

**Comment by exSOUL** [comment]
https://github.com/metabase/metabase/blob/master/docs/getting-started.md
上記の

1. 画像が古い問題
1. `a new question`に1ステップ増えているよ問題

をISUUEとして上げることにした。

**Comment by exSOUL** [comment]
https://github.com/metabase/metabase/blob/master/docs/contributing.md
docs/配下にcontributing.md があったのでそれを読んでみる。

**Comment by exSOUL** [comment]
ISSUE_TEMPLATE.mdがあったのでこちらを元に作成する。
https://github.com/metabase/metabase/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by exSOUL** [comment]
```md
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------
```

**Comment by exSOUL** [comment]
似たようなIssueを探したところ、以下を発見。
https://github.com/metabase/metabase/issues/2226

スクリーンショットをどうやって最新に保っていこうか、という内容。
しかし、特別解決策などがでているわけではなく、そのまま放置状態となっている模様。

**Comment by exSOUL** [comment]
今回あげようとしているIssueとして、
**`a new question`のステップが増えている**という点はIssueの根拠としてあるかもしれない

**Comment by exSOUL** [comment]
Issue案(日本語)
Title: Documentation "Getting Started"の更新
Body:
Metabaseという素晴らしいソフトウェアを作っていただきありがとうございます。
私は https://www.metabase.com/docs/latest/ を参考にインストールを実行しました。  
その際、少し困ってしまった事がありました。
それは、 https://www.metabase.com/docs/latest/getting-started.html のスクリーンショットが実際のスクリーンショットと異なっていた事です。
特に、Asking a new questionのセクションについては、私はドキュメントに存在しない画面に遭遇しました。
それは、Metrics, Custom, Native query, の3つの中からどれかを選択する画面です。
私はこの画面で迷ってしまいました。(試行錯誤した結果、'Custom'を選択することでドキュメントと同じ画面にたどり着くことができました。)

私は、この「3つの中からいずれかを選択する」画面を「Getting Started」に追加したほうがよいと考えます。
そしてもし可能であれば、スクリーンショットも新しいものにしたほうがよいと考えます。

**Comment by exSOUL** [comment]
Issue案(日本語)
Title: Documentation "Getting Started"の更新
Body:
Metabaseという素晴らしいソフトウェアを作っていただきありがとうございます。
私は https://www.metabase.com/docs/latest/ を参考にインストールを実行しました。 
インストール方法はDockerを選択し、Versionは`v0.31.0`です。
 
その際、少し困ってしまった事がありました。
それは、 https://www.metabase.com/docs/latest/getting-started.html のスクリーンショットが実際のスクリーンショットと異なっていた事です。
特に、Asking a new questionのセクションについては、私はドキュメントに存在しない画面に遭遇しました。
それは、Metrics, Custom, Native query, の3つの中からどれかを選択する画面です。
私はこの画面で迷ってしまいました。(試行錯誤した結果、'Custom'を選択することでドキュメントと同じ画面にたどり着くことができました。)

私は、この「3つの中からいずれかを選択する」画面を「Getting Started」に追加したほうがよいと考えます。
そしてもし可能であれば、スクリーンショットも新しいものにしたほうがよいと考えます。

**Comment by exSOUL** [comment]
Issue案(日本語)
Title: Documentation "Getting Started > Asking a new question"の更新
Body:
Metabaseという素晴らしいソフトウェアを作っていただきありがとうございます。
私は https://www.metabase.com/docs/latest/ を参考にインストールを実行しました。 
インストール方法はDockerを選択し、Versionは`v0.31.0`です。
 
その際、少し困ってしまった事がありました。
それは、https://www.metabase.com/docs/latest/getting-started.html に存在しない画面に遭遇したことであり、Metrics, Custom, Native query, の3つの中からどれかを選択する画面の事です。
私はこの画面で迷ってしまいました。(試行錯誤した結果、'Custom'を選択することでドキュメントと同じ画面にたどり着くことができました。)

私は、この「3つの中からいずれかを選択する」画面を「Getting Started」の「Asking a new question」セクションに追加したほうがよいと考えます。「3つの中からいずれかを選択する」画面のスクリーンショットを添付します。
<img width="1277" alt="2018-11-24 16 07 08" src="https://user-images.githubusercontent.com/844642/48965583-5b2c5400-f003-11e8-9615-91f6115b53d8.png">

そしてもし可能であれば、スクリーンショットも新しいものにしたほうがよいと考えます。

**Comment by exSOUL** [comment]
Issue案(日本語)
Title: "Getting Started"が実際のステップと異なっている
Body:
Metabaseという素晴らしいソフトウェアを作っていただきありがとうございます。
私は https://www.metabase.com/docs/latest/ を参考にインストールを実行しました。 
インストール方法はDockerを選択し、Versionは`v0.31.0`です。
 
その際、困ってしまった事がありました。
それは、https://www.metabase.com/docs/latest/getting-started.html に存在しない画面に遭遇したことであり、Metrics, Custom, Native query, の3つの中からどれかを選択する画面の事です。
私はこの画面で迷ってしまいました。(試行錯誤した結果、'Custom'を選択することでドキュメントと同じ画面にたどり着くことができました。)

私は、この「3つの中からいずれかを選択する」画面を「Getting Started」の「Asking a new question」セクションに追加したほうがよいと考えます。「3つの中からいずれかを選択する」画面のスクリーンショットを添付します。
<img width="1277" alt="2018-11-24 16 07 08" src="https://user-images.githubusercontent.com/844642/48965583-5b2c5400-f003-11e8-9615-91f6115b53d8.png">

そしてもし可能であれば、スクリーンショットも新しいものにしたほうがよいと考えます。

**Comment by exSOUL** [comment]
Issue案(英語)
Title: "Getting Started" steps are missing.
Body:
Thank you for making great software.
I ran the installation with reference to https://www.metabase.com/docs/latest/.
Select Docker as the installation method, Version is `v0.31.0`.
 
At that time, I had a trouble.
It is that I encountered a screen that does not exist in "Getting Started", and it is a screen that selects one from three of Metrics, Custom, Native query.
As a result of trial and error, selecting 'Custom' allowed me to reach the same screen as the document.

I thought that this "to select one from among the three" is better that you need to added to the "Asking a new question" section of the "Getting Started" screen. Attach a screenshot of "Choose one from three" screen.

<img width="1277" alt="2018-11-24 16 07 08" src="https://user-images.githubusercontent.com/844642/48965583-5b2c5400-f003-11e8-9615-91f6115b53d8.png">

**Comment by exSOUL** [comment]
Issue案(英語)
Title: "Getting Started" steps are missing.
Body:
Thank you for making great software.
I ran the installation with reference to https://www.metabase.com/docs/latest/.
Select Docker as the installation method, Version is `v0.31.0`.
 
At that time, I had a trouble.
It is that I encountered a screen that does not exist in "Getting Started", and it is a screen that selects one from three of Metrics, Custom, Native query.
As a result of trial and error, selecting 'Custom' allowed me to reach the same screen as the document.

I think it would be better to add a screen missing in this document to the "Getting Started" "Asking a new question" section. Attach a screenshot of "Choose one from three" screen.

<img width="1277" alt="2018-11-24 16 07 08" src="https://user-images.githubusercontent.com/844642/48965583-5b2c5400-f003-11e8-9615-91f6115b53d8.png">

**Comment by yoichi** [comment]
> It is that I encountered a screen that does not exist in "Getting Started", and it is a screen that selects one from three of Metrics, Custom, Native query.

Next, I followed "Getting Started", and I encountered an undocumented screen with choices: "Metrics", "Custom" and "Native query"

**Comment by exSOUL** [comment]
Issue案(英語)
Title: "Getting Started" steps are missing.
Body:
Thank you for making great software.
I ran the installation with reference to https://www.metabase.com/docs/latest/.
Select Docker as the installation method, Version is `v0.31.0`.
 
At that time, I had a trouble.
Next, I followed "Getting Started", and I encountered an undocumented screen with choices: "Metrics", "Custom" and "Native query".
As a result of trial and error, selecting 'Custom' allowed me to reach the same screen as the document.

I think it would be better to add a screen missing in this document to the "Getting Started" "Asking a new question" section. Attach a screenshot of "Choose one from three" screen.

<img width="1277" alt="2018-11-24 16 07 08" src="https://user-images.githubusercontent.com/844642/48965583-5b2c5400-f003-11e8-9615-91f6115b53d8.png">

**Comment by exSOUL** [comment]
Done!!
https://github.com/metabase/metabase/issues/9013

**Comment by ShinjiEnoki** [comment]
ふりかえり2、よろしくお願いします！

**Comment by exSOUL** [comment]
よろしくおねがいします!!
