### ISSUE TITLE
OSS Gate Workshop: Osaka: 2018-11-24: catforest: MySQLWorkbench: Work log

### ISSUE THREAD

**Issue by catforest** [oss-gate/workshop#1003]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ShinjiEnoki** [comment]
サポーターの榎です
よろしくお願いします！

**Comment by catforest** [comment]
よろしくお願い申し上げます。
MysqlWorkbenchで検索し、https://www.mysql.com/jp/products/workbench/　を開く。
DLボタンから以下のリンクに飛ぶ
https://dev.mysql.com/downloads/workbench/
メイン画面のBrowse Documentationのリンクをクリック

**Comment by catforest** [comment]
日本語ページでLicenseを確認
https://www.mysql.com/jp/products/workbench/features.html
英語ページでリンクをクリックすると、GPLv2（http://www.gnu.org/licenses/old-licenses/gpl-2.0.html）の説明が表示される。
GPLv1はまず使われていないらしい。

**Comment by catforest** [comment]
DBがInstallされていないので、DB installを開始。

**Comment by catforest** [comment]
❯ brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
docker-credential-helper-ecr      mkl-dnn                           youtube-dl
jump                              vsts-cli
laszip                            vtk

~ 25s
❯ brew install mysql
==> Downloading https://homebrew.bintray.com/bottles/mysql-8.0.12.high_sierra.bottle.tar.gz
######################################################################## 100.0%
brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
docker-credential-helper-ecr      mkl-dnn                           youtube-dl
jump                              vsts-cli
laszip                            vtk

~ 25s==> Pouring mysql-8.0.12.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/mysql/8.0.12/bin/mysqld --initialize-insecure --user=uni --basedir=/usr/local/Ce
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql/8.0.12: 255 files, 233.0MB

~ 32s
❯ brew update
Already up-to-date.

~
❯ Updated 2 taps (homebrew/core and homebrew/cask).
fish: Unknown command 'homebrew/core'
in command substitution
	called on standard input

fish: Unknown command 'Updated'

~
❯ ==> Updated Formulae
fish: Unsupported use of '='. To run 'Formulae' with a modified environment, please use 'env == Formulae…'

~
❯ docker-credential-helper-ecr      mkl-dnn                           youtube-dl
fish: Unknown command 'docker-credential-helper-ecr'

~
❯ jump                              vsts-cli
fish: Unknown command 'jump'

~
❯ laszip                            vtk
fish: Unknown command 'laszip'

**Comment by catforest** [comment]
シェル環境をちょうど変更しているところだったため、それに起因するエラーが発生していると思われる。すぐに解決させることは難しい。

**Comment by catforest** [comment]
dockerは動きそうだったため、Dockerを利用しMySQLを動かすことにする。

**Comment by catforest** [comment]
docker pull mysql で、Installしてみる。以下を試す。
docker run --name mysql -e MYSQL_ROOT_PASSWORD=mysql -d -p 3306:3306 mysql

# 接続確認 passwordはmysqlになります。
mysql -h $(boot2docker ip) -uroot -p

**Comment by ShinjiEnoki** [comment]
ここのページを参照中ですね
https://qiita.com/astrsk_hori/items/e3d6c237d68be1a6f548

**Comment by catforest** [comment]
❯ doker ps
fish: Unknown command 'doker'

~
❯ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
28c3e809349a        mysql               "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        0.0.0.0:3306->3306/tcp, 33060/tcp   mysql

~
❯ mysql -h 0.0.0.0 -uroot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.13 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

**Comment by catforest** [comment]
localhost を 0.0.0.0と明示的に指定する（-h option）ことで接続可能だった。

**Comment by catforest** [comment]
以下のようにデータを修正し、アルファベットの表示を確認。
UPDATE `test`.`item` SET `name` = 'abcdefgh', `description` = 'ijklmnopqrstuvwxyz0123456789' WHERE (`id` = '1');
Windowsでは（Versionは不明）、表示がうまくいかないケース（たとえば"g"の下部分がDefaultのFontでは？うまく見えない）があるが、そのような状況は確認されなかった。

**Comment by catforest** [comment]
今回DLしたVersionは8.0.13。

**Comment by catforest** [comment]
Menu > Help > Show License Info では、This software is released under version 2 of the GNU
   General Public License (GPLv2)　という情報が得られる。

**Comment by catforest** [comment]
Menu > Help からはVersionの確認ができなかった。

**Comment by catforest** [comment]
Menu > Helpの各項目（おそらくWebpage）がWorkbenchアプリケーションのタグで表示されるが、Default Browserで表示してもらった方が良い。

**Comment by catforest** [comment]
Menu > Help > Report a Bug からReport登録はできそうだが、Oracle Accountが必要。

**Comment by catforest** [comment]
左端のMysqlworkbenchから、About...にてVersionを確認可能。

**Comment by catforest** [comment]
Blog pageはhttps://mysqlworkbench.org/

**Comment by catforest** [comment]
Bug report投稿は、Browserが開くが、リストはApplication内に表示される。

**Comment by catforest** [comment]
Git のURLは、https://github.com/mysql/mysql-workbench

**Comment by catforest** [comment]
しかしGitHubではIssue投稿を意図的にできないような設定にしてあると思われる。

**Comment by yoichi** [comment]
サポーターのなかやまです。ふりかえり1をしました。

**Comment by catforest** [comment]
今回、報告する内容は、次のものにしたいと思います。「Menu > Help > Help Index をクリックすると一瞬何かが表示されるが、すぐに消えてしまい、内容が確認できない。」

**Comment by catforest** [comment]
bugReport前に、重複するものがないかどうかを調べました。

検索は、https://bugs.mysql.com/search.php
から可能です。Categoryとして「MySQL Workbench」を選択し、「help index」という検索語句で検索を行いました（以下が直リンクになります）。

https://bugs.mysql.com/search.php?search_for=help+index&bug_type%5B%5D=MySQL+Workbench&status%5B%5D=Active&severity=&limit=30&order_by=&cmd=display&phpver=&os=0&os_details=&bug_age=0&cpu_arch=0&cpu_arch_details=&target=&last_updated=0&tags=&similar=&defect_class=all&workaround_viability=all&impact=all&fix_risk=all&fix_effort=all&triageneeded=

**Comment by catforest** [comment]
重複はなかったので、本件を投稿することにしました。また投稿内容として参考になるものがありましたので（https://bugs.mysql.com/bug.php?id=92327）、それを元に文面を作成しようと思います。

**Comment by catforest** [comment]
Help > Report a Bug　を押すタイミングにより、リンク先の表示（MacのVersion等が自動的に取得され表示されている）も異なったが、何が原因でそのような挙動を示しているかよくわからず。

https://bugs.mysql.com/report.php?in[status]=Open&in[php_version]=8.0.13&in[os]=6&in[os_details]=macOS%2010.13.x%20High%20Sierra%20x86_64&in[tags]=WBBugReporter&in[really]=0&in[ldesc]=----[For%20better%20reports,%20please%20attach%20the%20log%20file%20after%20submitting.%20You%20can%20find%20it%20in%20/Users/uni/Library/Application%20Support/MySQL/Workbench/log/wb.log]&login=1

https://bugs.mysql.com/report.php?in%255Bstatus%255D=Open&in%255Bphp_version%255D=8.0.13&in%255Bos%255D=6&in%255Bos_details%255D=macOS+10.13.x+High+Sierra+x86_64&in%255Btags%255D=WBBugReporter&in%255Breally%255D=0&in%255Bldesc%255D=----%255BFor+better+reports,+please+attach+the+log+file+after+submitting.+You+can+find+it+in+/Users/uni/Library/Application+Support/MySQL/Workbench/log/wb.log%255D

**Comment by ShinjiEnoki** [comment]
ここのトップペジにバグ報告をどうするか書いてますね
https://bugs.mysql.com/

**Comment by catforest** [comment]
Help Indexが表示されるはずだが、何かの画面が一瞬見え、そこで処理が停止しているように見える。

**Comment by catforest** [comment]
本来の挙動がどういうものかが良く分からない。他の環境（Windows他）では問題なく動くかもしれない。

**Comment by catforest** [comment]
・概要
・内容
・再現手順
・解消の提案
を書く必要性があります。

**Comment by catforest** [comment]
・概要
ヘルプメニュー下のHelp Indexが動かない。
・内容
Help Indexを利用しようとしたときに、一瞬何かの画面が表示され閉じてしまう。ログファイルを見ると、Errorが記録されている。
"wb.log"内に、
15:45:32 [ERR][      utilities]: Could not open URL (null)
・再現手順
MySQLWorkbenchを立ち上げ、Helpメニューを開きHelp Indexをクリック。
・解消の提案
（無し）

さらに
Version:8.0.13
OS:Mac OS X
Details:macOS 10.13.x High Sierra x86_64
Severity:S7

Severityについては、以下のように定義されています。
S1 (Critical): Represents a complete loss of service, a significant functionality is missing, a system that hangs indefinitely; and there is no available workaround.
S2 (Serious): Represents a severe loss of service, significant functionality is missing; but a workaround is available.
S3 (Non-critical): Represents a minor loss of service, inconvenient usage; but a workaround is available.
S4 (Feature request): There is no loss in service; a cosmetic or enhancement request.
S5 (Performance): There is no loss in service, but performance is not as good as expected.
S6 (Debug Builds): There is no loss in service, a bug shows in debug builds only.
S7 (Test Cases): There is no loss in service, a bug in test files causing the test suite to fail.

**Comment by catforest** [comment]
- Synopsis
"Help Index" menu item under "Help" doesn't work

- Description
When attempting to use the 'Help Index' menu option under 'Help', some window is displayed in an instant and closed immediately. My "wb.log" said as follows;
15:45:32 [ERR][      utilities]: Could not open URL (null)

- How to repeat
Run MySQL Workbench. Open the Help menu. Click 'Help Index'
