### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-12-15: saraki: 　StreamSets Data Collector: Work log

### ISSUE THREAD

**Issue by dogteacher** [oss-gate/workshop#1015]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by dogteacher** [comment]
Buildのターゲット環境は、LinuxおよびMacOSであるが、今回はWindows環境でビルドし、フィードバックを行う

**Comment by dogteacher** [comment]
まず、nodejs（Node 0.10.32+1）を導入します。

**Comment by dogteacher** [comment]
nodejs 入りました。つぎに npmを導入します

**Comment by dogteacher** [comment]
npm も梱包されていたので、済みです。つぎに　bower 1.8.2です

**Comment by dogteacher** [comment]
bower も入りました。次、grunt-cli をいれます。

**Comment by dogteacher** [comment]
grunt-cliも入りました

**Comment by dogteacher** [comment]
maven 3.6 投入しました。

**Comment by dogteacher** [comment]
つぎにgitからソースをcloneします

**Comment by dogteacher** [comment]
And install each of these to your local maven repository

mvn clean install -DskipTests
を実施します

**Comment by dogteacher** [comment]
No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

**Comment by dogteacher** [comment]
JAVA_HOMEを設定しないと認識してくれない　というオチ

**Comment by dogteacher** [comment]
ビルドは成功datacollector-api　もう一個　datacollector-plugin-apiにいきます

**Comment by knokmki612** [comment]
ふりかえりました！
JAVA_HOMEの話を含め、Windows向けの説明として補足が必要かもしれませんね！

**Comment by dogteacher** [comment]
フィードバックを確認
 JIRA
https://issues.streamsets.com/secure/BrowseProjects.jspa?selectedCategory=all
ask
https://ask.streamsets.com/questions/ 
コミュニティで聞く

**Comment by dogteacher** [comment]
その前に　
To begin you first need to sign our Contributor License Agreement.
が必要

**Comment by dogteacher** [comment]
datacollector-edge　のJIRAのissue
SDCE-369
であがっている。
datacollector のissueにはdatacollector-edgeでgolangが必要だから　必要なプロダクトとして
記載したほうがいいという内容とする

**Comment by dogteacher** [comment]
題　BUILD.md　の追加プロダクト願い
Add  GOLANG on BUILD.md

**Comment by dogteacher** [comment]
内容
成果物にdatacollector -edgeをビルドする必要なプロダクトを記載してほしい[etc golang...]

Please list the necessary products to build the artifacts for datacollector-edge [etc golang ...]
relational issue [SDCE-369](https://issues.streamsets.com/browse/SDCE-369)

**Comment by dogteacher** [comment]
issueを登録しました
https://issues.streamsets.com/browse/SDC-10682

**Comment by naruoga** [comment]
おめでとうございます！ 🎉

**Comment by naruoga** [comment]
:+1:
