### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-12-15: yskaksk: ale: work_log

### ISSUE THREAD

**Issue by yskaksk** [oss-gate/workshop#1016]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
aleのJuliaサポートについてで行きましょう！

**Comment by yskaksk** [comment]
ale は明確にjuliaのシンタックスに違反しているファイルに対して、何も警告を出さない

**Comment by yskaksk** [comment]
デバッグ用のコマンド:ALEInfo を実行してもエラーが起きているかどうかわからない

**Comment by yskaksk** [comment]
ale のissueでも動かないと報告されている
https://github.com/w0rp/ale/issues/2066

**Comment by yskaksk** [comment]
julia のLanguageServerのほうのissueでも同じように動かないという報告がされており、「新しいバージョンでは引数が違う」と指摘されている。aleで動作しないのも同じ原因と考えられる。
https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/318

**Comment by knokmki612** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/releases

**Comment by knokmki612** [comment]
> Juliaの作法がよく分かりませんが、[Wiki](https://github.com/JuliaEditorSupport/LanguageServer.jl/wiki/Vim-and-Neovim)を見る分にはJuliaに[Pkg.clone](https://docs.julialang.org/en/v0.6.0/stdlib/pkg/#Base.Pkg.clone)でLanguageServerを導入する際はmaster(デフォルトブランチ)がそのまま入るようですね

これは0.6のドキュメントで、1.0でPkgの仕様が変わったという感じがします

**Comment by yskaksk** [comment]
ale へ報告する内容の整理
- LanguageServer.ServerInstance の仕様が変更された
- aleで現在実装されているスクリプトは古い仕様に対応している
- そのため、現在のaleはjuliaのlintを実行することができない
- LanugageServer自体は、バージョンアップに向けて作業中であり、今後も変更がありうるため対応は待ったほうがよい？

**Comment by knokmki612** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/master/REQUIRE

**Comment by knokmki612** [comment]
0.6のPkgではPkg.checkoutを使うみたいです

https://discourse.julialang.org/t/check-out-tagged-commit-of-unregistered-package/4659/7

**Comment by yskaksk** [comment]
以下を英訳する

```
juliaのLanguageServerの仕様が変更され、LanguageServer.LanguageServerInstance を作成するための引数が増えました。そのため、現在はaleではjuliaのlistを実行することができません。この問題は、引数の変更に対応する形でale_linters/julia/languageserver.vim を書き換えれば解消すると考えられますが、一方でLanugageServer側はメジャーバージョンアップに向け作業中であり、今後も仕様が変更される可能性があります。

どのように対処すべきでしょうか。
```

**Comment by knokmki612** [comment]
> ## LanguageServer.jlの追従
> 
> > LanugageServer自体は、バージョンアップに向けて作業中であり、今後も変更がありうるため対応は待ったほうがよい？
> 
> 以下のようなバージョン毎のサポートが必要になります
> 
> * LauguageServer.jl@v0.4.0 -> Julia 0.7>=
> * LanguageServer.jl@next-release -> Julia =<1.0

こんな感じに場合分け出来そうです

**Comment by yskaksk** [comment]
英語難しい

## Following next release of LanguageServer.jl

LanguageServer.jl has been destructively changed and more arguments are required to create LanguageServerInstance object. 

In ALE, ale_linters/julia/languageserver.vim does not follow this change, hence ALE cannot lint any errors in Julia now.

Guessing that this problem could be resolved by rewriteing ale_linters/julia/languageserver.vim, I hesitate to do so because LanguageServer.jl is being developed for major version-up.

- LauguageServer.jl@v0.4.0-> Julia - 0.7>=
- LanguageServer.jl@next-release-> Julia =<1.0

**Comment by knokmki612** [comment]
ttps://github.com/JuliaEditorSupport/LanguageServer.jl/issues/310 こちらに引数の説明があるので、添えとくと良さそうです
