### ISSUE TITLE
OSS gate Workshop: Fukuoka: 2019-01-15: etilltwice: the_platinum_searcher: worklog

### ISSUE THREAD

**Issue by etilltwice** [oss-gate/workshop#1023]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by etilltwice** [comment]
go getを使ってプログラムをインストールしようとしたら、以下のエラーが発生しました。
```
cd C:\Users\twice\go\src\golang.org\x\text; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
```

**Comment by etilltwice** [comment]
the_platinum_searcherをインストールしようとしたら以下エラーが起きました
```
# cd C:\Users\twice\go\src\golang.org\x\text; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

package golang.org/x/text/encoding/japanese: exit status 1
package golang.org/x/text/transform: cannot find package "golang.org/x/text/transform" in any of:
        C:\Go\src\golang.org\x\text\transform (from $GOROOT)
        C:\Users\twice\go\src\golang.org\x\text\transform (from $GOPATH)
```

**Comment by hsmt** [comment]
なにか、コントリビュートできそうですね！

**Comment by etilltwice** [comment]
vs codeでディレクトリを開いて、パワーシェル上でptを実行しましたが応答がありません。

,,,
pt http
,,, 
上記の通りに入力した際に応答がありませんでした。

...
pt http .\
,,,
上の通りに、ディレクトリー名を指定すると問題なく実行できます

実行したフォルダには5つファイルが入っており、それぞれ「html」「css」「javascript」「音声データ」「画像データ」が入っています。また「javascript」のデータが入ったファイルには「enchant.js」も入っていました。
OS:windows 10 Home
バージョン:1803

**Comment by etilltwice** [comment]
・プラチナサーチャーのバージョン情報の追記
version 2.2.0

・htmlではなかったことの修正
```
PS C:\Users\twice\Desktop\02_19_chijiwaryuichi> pt html

```
