### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: garcons: cakephp/chronos: Work log

### ISSUE THREAD

**Issue by garcons** [oss-gate/workshop#1024]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by monochromegane** [comment]
わいわい！

**Comment by garcons** [comment]
開始する

**Comment by monochromegane** [comment]
ライセンス一覧: https://opensource.org/licenses/alphabetical

**Comment by garcons** [comment]
「chronos」でググるが、全然違うものばっかりヒットするので、「chronos php」でググると良さげ。
GitHubとCakePHPでの利用方法（公式っぽい）Documentが見つかった。が、CakePHPは動かさないので、除外
- GitHub
https://github.com/cakephp/chronos
- CakePHP
https://book.cakephp.org/3.0/ja/chronos.html

**Comment by garcons** [comment]
GitHubでライセンス見る
https://github.com/cakephp/chronos/blob/master/LICENSE

**Comment by garcons** [comment]
↑のページで「MIT License」ってなっているので、ライセンス一覧（https://opensource.org/licenses/alphabetical）から探す。

**Comment by garcons** [comment]
ライセンス一覧にMITがあったので、OSSと判断

**Comment by garcons** [comment]
GitHubのREADMEを見てローカルにインストールしてみる
https://github.com/cakephp/chronos

**Comment by garcons** [comment]
説明読んで見る。
> Chronos aims to be a drop-in replacement for nesbot/carbon. It focuses on providing immutable date/datetime objects. Immutable objects help ensure that datetime objects aren't accidentally modified keeping data more predictable.
Google先生に訳してもらってなんとなく掴む。「carbonに変わるイミュータブルで予期せぬバグが起きにくいよ」らしい。
すげーいいじゃん。

**Comment by garcons** [comment]
インストールからやってみる。
https://github.com/cakephp/chronos#installation

**Comment by monochromegane** [comment]
経過がわかりやすいGreat issueだ!

**Comment by garcons** [comment]
`composer require cakephp/chronos`
を叩く

流石にこのライブラリ落とすような人は大丈夫だけど、
```
mkdir path/to/your/directory
cd path/to/your/directory
```
とか当たり前すぎるけどcomposerとか前提であったがいいかも

**Comment by garcons** [comment]
インストールできたっぽい
```
$ composer require cakephp/chronos
Using version ^1.2 for cakephp/chronos
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing cakephp/chronos (1.2.3): Downloading (100%)         
Writing lock file
Generating autoload files

```

**Comment by garcons** [comment]
GitHubにあるサンプルソースを作って実行してみる。
以下をPrint.phpとして保存。
```
<?php
require 'vendor/autoload.php';

use Cake\Chronos\Chronos;

printf("Now: %s", Chronos::now());
```

**Comment by garcons** [comment]
実行してみる
```
$ php Print.php 
Now: 2019-01-15 11:20:05
```

できた

**Comment by tokibi** [comment]
順調そう

**Comment by garcons** [comment]
と思ったら、今20:20なんだけど。。。

**Comment by garcons** [comment]
```
$ date
2019年 1月15日 火曜日 20時22分43秒 JST
```
UTCなんかな

**Comment by garcons** [comment]
サンプルには
```
// This will lose modifications
$date = new Chronos('2015-10-21 16:29:00');
$date->modify('+2 hours');

// This will keep modifications
$date = new Chronos('2015-10-21 16:29:00');
$date = $date->modify('+2 hours');
```
ってあるけど、イミュータブルであるよ！！て押したいのであれば、それを確認するソースがあってもいいんでない？

**Comment by garcons** [comment]
こうして、イミュータブルを確認した
```
// This will lose modifications
$date = new Chronos('2015-10-21 16:29:00');
$date->modify('+2 hours');

var_dump($date); // '2015-10-21 16:29:00'のまま！

// This will keep modifications
$date = new Chronos('2015-10-21 16:29:00');
$date2 = $date->modify('+2 hours');

var_dump($date === $date2); // false！
var_dump($date); // '2015-10-21 16:29:00'のまま！
var_dump($date2); // '2015-10-21 18:29:00'になった
```

**Comment by garcons** [comment]
つぎ、ミュータブルを見る
https://github.com/cakephp/chronos#getting-mutable-objects

**Comment by monochromegane** [comment]
良い提案〜

**Comment by garcons** [comment]
サンプルはこれ
```
$time = new Chronos('2015-10-21 16:29:00');
$mutable = $time->toMutable();

$date = new Date('2015-10-21');
$mutable = $date->toMutable();
```
new Date()で落ちる。
PHPってDateクラスあったっけ？DateTimeクラスの間違い？

**Comment by monochromegane** [comment]
見つけましたね...!!
既にIssueやPullRequestで同様のフィードバックがないかなども確認しておいても良さそうです

**Comment by garcons** [comment]
`use Cake\Chronos\Date;`
がいる！！
もしくは
`$date = new Cake\Chronos\Date();`
のほうが親切

**Comment by monochromegane** [comment]
来ましたね

**Comment by monochromegane** [comment]
落ちた時のエラーメッセージもメモしておくと良さそうですね~!

**Comment by garcons** [comment]
`Fatal error: Uncaught Error: Class 'Date' not found`
のエラーが出た！

**Comment by garcons** [comment]
こっちもイミュータブルとと同じでミュータブルであることを確認できるサンプルがあるとメリット感あるかも。

**Comment by garcons** [comment]
https://github.com/oss-gate/workshop/issues/1024#issuecomment-454364701
指摘いただいたようにIssueとかPRみてみる。

**Comment by garcons** [comment]
次回、Issueを上げる。
- use してないとエラーになる
https://github.com/oss-gate/workshop/issues/1024#issuecomment-454365147
- イミュータブルとミュータブルのメリットがわかるサンプル
https://github.com/oss-gate/workshop/issues/1024#issuecomment-454362873
