### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: 1984weed: Riot:  Work log

### ISSUE THREAD

**Issue by 1984weed** [oss-gate/workshop#1025]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

# ゴール 

[RIot.js](https://github.com/riot/riot/) のnextバージョンを動かしたい

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 1984weed** [comment]
まずはREADME.mdの通り動かす

https://github.com/riot/riot/tree/master#1-clone-the-repo-and-browse-to-the-riot-folder

**Comment by 1984weed** [comment]
とりあえずビルドできたので動かしてみる

**Comment by 1984weed** [comment]
https://plnkr.co/edit/?p=preview
現行バージョンで動いてるサイトがあるのでコピペして v4で動かす

**Comment by 1984weed** [comment]
いい感じで動かない
```
riot%2Bcompiler.js:60 Uncaught Error: The component named "timer" was never registered
    at panic (riot%2Bcompiler.js:60)
    at mountComponent (riot%2Bcompiler.js:2055)
    at $$.map (riot%2Bcompiler.js:2121)
    at Array.map (<anonymous>)
    at Object.mount (riot%2Bcompiler.js:2121)
    at index.html:20
panic	@	riot%2Bcompiler.js:60
mountComponent	@	riot%2Bcompiler.js:2055
$$.map	@	riot%2Bcompiler.js:2121
mount	@	riot%2Bcompiler.js:2121
(anonymous)	@	index.html:20
```

**Comment by 1984weed** [comment]
おそらくAPI変わってる

**Comment by 1984weed** [comment]
動かないので和訳のミスを見つけてた

https://riot.js.org/ja/guide/#%E3%82%BF%E3%82%B0%E3%81%AE%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88
```
キャメルケースの代わりにアンダースコアを使用してshow_detailsという属性の名前をつける場合は注意してください。ブラウザの仕様ににより、自動的に小文字に変換されます。
```

https://riot.js.org/guide/#nested-tags

```
important Note how we named the show_details attribute using an underscore instead of camel case, which due to browser specification would have been automatically converted to lowercase.
```

原文はキャメルケースじゃなくてスネークケースを使おう的な意味合いなので間違い

**Comment by 1984weed** [comment]
https://github.com/riot/riot.github.io
こちらで管理されてる

**Comment by 1984weed** [comment]
riot v4は動く気がしないので、動かないって旨でissue立てようかなーって考えてます

**Comment by udzura** [comment]
sugoi!!!

**Comment by udzura** [comment]
今日、Issue立てられそうですか？
PRをすでに送られているので、nice to haveぐらいな感じです！

**Comment by 1984weed** [comment]
無理そうというかもうちょっと調査してから立てたい感じです @udzura 🙇

**Comment by 1984weed** [comment]
いややっぱ立てよう
