### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: take2webservice: Scala(tour-of-scala): Work log

### ISSUE THREAD

**Issue by take2webservice** [oss-gate/workshop#1026]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by take2webservice** [comment]
とりあえず公式のgithubを見つける

https://github.com/scala/scala-lang

**Comment by take2webservice** [comment]
とりあえず
README読む

**Comment by take2webservice** [comment]
コントリビュートしたけりゃ、こっちを見ろと書いてあった
https://github.com/scala/docs.scala-lang

サイトはJekyll で作ってるらしい

こっちも読めって書いとる
https://docs.scala-lang.org/contribute.html

**Comment by take2webservice** [comment]
とりあえずcloneして、ローカルで環境立ち上げたので、言語のプルダウンで日本語追加してみる

**Comment by take2webservice** [comment]
_data/language.ymlが言語設定のマスタファイルっぽい
language/_ja にtourの英語ファイル置いたら動くんじゃね？
ファイルはできたけど、dropdownのメニューに日本語追加されん…

**Comment by nagachika** [comment]
dropdow メニューの出したかたは issue とかで訊いてしまってもいいかもですね。
まず日本語翻訳しようと思ってるでーというのを表明しておくのも、作業重複を防ぐ意味でもいいかなと思います。

**Comment by take2webservice** [comment]
git のissueを作る

**Comment by take2webservice** [comment]
issue作った！
https://github.com/scala/docs.scala-lang/issues/1261

**Comment by take2webservice** [comment]
そしてここに今日翻訳した、翻訳内容があります。
実際に邦訳してみて、
- 意訳したほうがいいのか、ある程度固めに直訳したら良いのか？
- オブジェクト指向と関数型言語界隈のワード知識が足りずに翻訳が合っているかが不安
- いかんせん時間がかかる

**Comment by take2webservice** [comment]
git push origin translation-tour-ja をしようとしたら403エラーで怒られました。
どうやら一般的には自分のアカウントにリポジトリをフォークして、そこからプルリクを送るらしいです。

**Comment by take2webservice** [comment]
知人に英語の翻訳内容のチェックをお願いしようとしたんですが
いきなり英語の翻訳済みファイルをコミットするのではなく、
一旦英語の元ファイルでコミットして、そこから日本語訳をしてからコミットした方がgit上でdiffが見やすいという知見を得ました

**Comment by take2webservice** [comment]
というわけでレビュー中
[日本語]
https://github.com/take2webservice/docs.scala-lang/blob/814b7466d398c8b72803e08db9c35622c2701ab5/_ja/tour/tour-of-scala.md

[英語]
https://github.com/take2webservice/docs.scala-lang/blob/814b7466d398c8b72803e08db9c35622c2701ab5/_tour/tour-of-scala.md

**Comment by take2webservice** [comment]
フォークしたリポジトリにissueを作ることができない。
どうやら、リポジトリによるけど許可されていないとダメっぽい。
closeする場合は、親のissueを使ってする必要があるっぽい

**Comment by take2webservice** [comment]
[この後やること]
レビューが終わったら、未翻訳の英語ページのファイルを丸っとjaディレクトリ配下に置くいてコミットする
そんで本系にプルリクだすぞい
