### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: Chanpoyu: Work log

### ISSUE THREAD

**Issue by ChanPoyu** [oss-gate/workshop#1027]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by takumakume** [comment]
コントリビュートするOSSを決めるにあたって、このソフトウェアに何か追加したい！！って思って色々と調べていくと思います。
また、それが大きめのソフトウェアになると、普段使い倒していないと何を追加したら便利なのかとかとても判断が難しいことがあります。
自分がぶち当たってない課題に対してアプローチしていくと、現状の自分では難易度が高いものであることも多いかもしれません。

自分が普段何かの技術に触れていて、「こうだったらもっと便利だな〜」とか思うことがあると思います。
そういった、実際に体験した課題に対して何かアプローチをする方が、最初の第一歩として踏み出しやすい課題になると思います！
言語化してIssueにするのも良いですし、コードとしてアウトプットするのも良いですし！

**Comment by ChanPoyu** [comment]
https://github.com/MetaMask/metamask-extension

**Comment by takumakume** [comment]
普段使っているけど、大きめのソフトウェアでコントリビュートチャンスを悩まれている感じですね〜！
コアの機能になにか加えるのが難しいな〜ということであれば、第一歩として、例えば

「このパターンのこのテストがないから、〇〇が起きるリスクがある。」というように、課題が言語ができることがあれば、テストケースの追加とかでも、ソフトウェアに対して貢献できることもありそうです！

**Comment by takumakume** [comment]
現在、セットアップ手順で詰まっているようだったので
まずは動くようにやっていってる

**Comment by takumakume** [comment]
うづらさん: 解決できたら、その手順をメモしておいて、モヤッとしたところを掘り下げていくと良い

**Comment by takumakume** [comment]
もし、どうしても解決できそうになければ、どういう手順でどういうエラーが発生しているのかをここにまとめてみて、助けを求めてみましょう！

**Comment by takumakume** [comment]
npm周りのバージョン依存の問題で、ドキュメント通りのバージョンを利用することで解決できたとのこと

**Comment by ChanPoyu** [comment]
Metamask

Metamaskのリポジトリーをローカルにクローンする
`git clone https://github.com/MetaMask/metamask-extension.git`
nvm (node version manager) を curl からインストール
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash`
nvmでnodeのバージョンを切り替える
`nvm use`
nvm でnodeV8.13をインストール
`nvm install v8.13`
dependencies をインストール
`npm install`
ここでpythonのバージョンが合わないエラーが
```
Error: Python executable "/Users/chanpoyu/.pyenv/shims/python" is v3.6.4, which is not supported by gyp
```
pyenvでバージョンを切り替える
`pyenv global 2.7.9`
もう一回インストール
```
npm install 
added 672 packages from 791 contributors and audited 217145 packages in 121.582s
found 0 vulnerabilities
```
gulp-cliをグローバルにインストール
`npm install -g gulp-cli`
プロジェクトでビルドする
`gulp build`
エラーが出てきた！
```
Error: ENOENT: no such file or directory, scandir '/Users/chanpoyu/Desktop/Metamask/metamask-extension/node_modules/gulp-sass/node_modules/node-sass/vendor'
```
パッケージの欠損　→  npm のバージョンが
```
npm -v
6.1.0
nvm use
Found '/Users/chanpoyu/Desktop/Metamask/metamask-extension/.nvmrc' with version <v8.13>
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v8.13.0` to unset it.
```
nvm と　npm の互換性に問題がありそうなので以下のコマンドで直してみる
```
nvm use --delete-prefix v8.13.0
Now using node v8.13.0 (npm v6.4.1)
```
dependencies をもう一回インストールし直す
```
npm install 
added 14 packages from 26 contributors, removed 76 packages and audited 217169 packages in 49.416s
found 0 vulnerabilities
```
project rebuild
```
gulp dev
return binding.readdir(pathModule._makeLong(path), options.encoding);
```
またモジュールのエラーが出ました。ググったらnpm 6系によくある問題らしい。　
https://github.com/sass/node-sass/issues/1918以下のコマンドで直してみた
`npm rebuild node-sass`
モジュールのrebuildが無事終わって、gulpをbuildし直す
`gulp build`
ビルドできた。
