### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: taroosg: p5.js: Work log

### ISSUE THREAD

**Issue by taroosg** [oss-gate/workshop#1029]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by takumakume** [comment]
コントリビュートするOSSを決めるにあたって、このソフトウェアに何か追加したい！！って思って色々と調べていくと思います。
また、それが大きめのソフトウェアになると、普段使い倒していないと何を追加したら便利なのかとかとても判断が難しいことがあります。
自分がぶち当たってない課題に対してアプローチしていくと、現状の自分では難易度が高いものであることも多いかもしれません。

自分が普段何かの技術に触れていて、「こうだったらもっと便利だな〜」とか思うことがあると思います。
そういった、実際に体験した課題に対して何かアプローチをする方が、最初の第一歩として踏み出しやすい課題になると思います！
言語化してIssueにするのも良いですし、コードとしてアウトプットするのも良いですし！

**Comment by taroosg** [comment]
ライセンスチェックからスタート．
https://github.com/processing/p5.js/blob/master/license.txt

MITなので問題ないことを確認．

**Comment by taroosg** [comment]
公式サイトにアクセス
https://p5js.org/

ドキュメントが英語スペイン語中国語しか存在しない．

**Comment by taroosg** [comment]
日本語がほしいので日本語化関連のissueがないかどうか調べるとなさそうなので，日本語化しつつ進めてみる．

**Comment by taroosg** [comment]
まずget startedから読みながら動かす．
都度日本語に訳してみる．
https://p5js.org/get-started/

**Comment by taroosg** [comment]
以下，自分で訳すと大変なのでgoogleにがんばってもらう．

**Comment by taroosg** [comment]
Download and File Setupの続き

【原文】
Alternatively, you can link to a p5.js file hosted online. All versions of p5.js are stored in a CDN (Content Delivery Network). You can see a history of these versions here: p5.js CDN. In this case you can change the link to:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.js"></script>`

A sample HTML page might look like this:

`<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
  </body>
</html>`

You can also start with this template from codepen.

【日本語訳】
あるいは、オンラインでホストされているp5.jsファイルにリンクすることもできます。 p5.jsのすべてのバージョンはCDN（Content Delivery Network）に格納されています。 あなたはここにこれらのバージョンの歴史を見ることができます：p5.js CDN（←https://cdnjs.com/libraries/p5.jsへリンク）。 この場合、リンクを次のように変更します。

`<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.js"></script>`

サンプルHTMLページは次のようになります。

`<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body>
  </body>
</html>`

codepen（←https://codepen.io/p5js/pen/wreBKyへリンク）からこのテンプレートから始めることもできます。

**Comment by taroosg** [comment]
html部分がはコメントに出てこないが訳には関係ないのでそのまま進む．

**Comment by takumakume** [comment]
やりたいことが見えたようですね:eyes: 

- 課題: 日本語のドキュメントが存在しないので、日本人の開発や、コントリビュートがしにくい。

であるのならば、その課題を達成できるようにコードを書いていく必要があります。
ただ、google翻訳で実施するならば英文のままでよいのです。なぜなら、ブラウザの機能でできますし、日本語のドキュメントが存在することによってメンテナンスコストが発生するからです。

やるからには、課題をしっかり解決できるように翻訳をするのが良いと思われます！

もし、そのようなバリューが難しいのであれば、もしかしたら別の課題のほうが合っていることもあると思いますし！

もし日本語訳をやるとして進むならば、今ここに書かれていることは、すでにコードとしてコミットできるものだと思うので早速コードに落とし込んで行きましょうか。
具体的には、repositoryをforkして、ブランチを作成してcommitすることです。

**Comment by taroosg** [comment]
【原文】
Environment
You can use the code editor of your choice. Instructions for getting set up with Sublime Text 2 are included below, other good editor options include Brackets, Atom and OpenProcessing. If you are a screen reader user and not using the p5 web editor, you may want to use Notepad++ or Eclipse.

Open Sublime. Go to the File menu and choose Open... and choose the folder that your html and js files are located in. On the left sidebar, you should now see the folder name at the top, with a list of the files contained in the folder directly below.

Click on your sketch.js file and it will open on the right where you can edit it.

【日本語訳】
環境設定
エディタは任意のものをしようすることができます。
例えば，Sublime Text 2でセットアップするための指示は以下に示します．他の選択肢としてはBrackets, 、AtomとOpenProcessingが挙げられます。

あなたがスクリーンリーダーのユーザであり（←視覚に問題があるという意味か？）、p5 Webエディタを使用していない場合は、Notepad ++またはEclipseを使用することをお勧めします。

（以下，Sublimeの例）
Sublimeを開きます。 [ファイル]メニューから[開く]を選択し、htmlファイルとjsファイルが置かれているフォルダを選択します。左側のサイドバーの上部にフォルダ名が表示されます。 sketch.jsファイルをクリックすると、右側に領域で編集できます。

**Comment by taroosg** [comment]
forkしてコードの方も進めるぞ．

**Comment by taroosg** [comment]
fork完了．
ローカルのクローンの設定も行う．

**Comment by taroosg** [comment]
cloneも完了．
https://github.com/processing/p5.js/tree/master/developer_docs
に手順が記載されている．

**Comment by taroosg** [comment]
とりあえずドキュメントのファイルを探す．

**Comment by taroosg** [comment]
実行→エラー出力→issueにメモ→ググる
の順が良さそうとのアドバイスをゲット！
コマンドのログを必ず残そう（明日見てわかるように）

**Comment by taroosg** [comment]
### contributeに関する決まりなど
- https://github.com/taroosg/p5.js/tree/master/developer_docsに記述あり
- 追加したい機能などある場合はまずissueを立てる．
- 直接プルリクを送ることは避けること．

**Comment by taroosg** [comment]
### ドキュメントに関するissue
- [https://github.com/processing/p5.js/issues/2667](https://github.com/processing/p5.js/issues/2667)
- 英文ドキュメント内でのリンクエラーを報告したissue
- issueを立てた開発者とは別の開発者がプルリクを送信し，マージされた．

**Comment by taroosg** [comment]
### ドキュメントに関するissue 2
- [https://github.com/processing/p5.js/issues/2482](https://github.com/processing/p5.js/issues/2482)
- [https://p5js.org/reference/#/p5/createCanvas](https://p5js.org/reference/#/p5/createCanvas)内でのタイプミス
- タイプミスの文章全体を引用し，意味が捉えやすいissue．

**Comment by taroosg** [comment]
### ドキュメントに関するissue 3
- [https://github.com/processing/p5.js/pull/2151](https://github.com/processing/p5.js/pull/2151)
- 関数呼び出しの()不備．
- 同ページ内の他の箇所は正しいことも合わせて指摘．

**Comment by taroosg** [comment]
ラベル付与が推奨されているが，ついていないものが8割なのでラベルによる分類が機能していない．．．

**Comment by taroosg** [comment]
### サポーターからのアドバイス
- すでに立てられているissueの問題に対して検証してみるのも良い．
- 放置されているissueに対してコメントを送っても良さそう．
- 引き続き，openなissueについて一通り目を通す．

**Comment by taroosg** [comment]
### openなissueの検証 1
- [https://github.com/processing/p5.js/issues/950](https://github.com/processing/p5.js/issues/950)
- ttfフォント使用時にレンダリングが重くなる現象
- フォントが404だったので適宜用意したもので試す．
