### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: yauyuirate: geocoder: worklog

### ISSUE THREAD

**Issue by yauyuirate** [oss-gate/workshop#1031]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yauyuirate** [comment]
@monochromegane @tokibi
issueを立てました！

**Comment by monochromegane** [comment]
わいわい！

**Comment by monochromegane** [comment]
ライセンス一覧: https://opensource.org/licenses/alphabetical

**Comment by yauyuirate** [comment]
geocoder MIT License

**Comment by yauyuirate** [comment]
ドキュメントのOverviewの通りに進めるとサンプル通りに緯度と経度が返らない

**Comment by monochromegane** [comment]
コントリビューションチャンス！

**Comment by yauyuirate** [comment]
`g = geocoder.google('Mountain View, CA')`
を
`g = geocoder.osm('Mountain View, CA')`
にすると
`g.latlng`
で緯度と経度が返った

**Comment by monochromegane** [comment]
`.google`の時はどんなエラーが出るのですかね？

**Comment by yauyuirate** [comment]
.googleでは特にエラーは出ず何も表示されません

**Comment by monochromegane** [comment]
なるほどなるほど！

**Comment by monochromegane** [comment]
ちょい先の話になりますが，起票する時は期待する動作，期待と違った動作などをコマンドラインのログレベルで書くと伝わりやすいので，実行ログなどもメモする癖をつけておくと役立ちそうです〜

**Comment by monochromegane** [comment]
原因まではあたりがついていますか？
ついているとするとコードのどの部分でしょうか〜？

**Comment by yauyuirate** [comment]
公式ドキュメントのBingではAPI KEYを引数にした例があったので
.googleで同じようにして試してみます。
`g = geocoder.bing('Mountain View, CA', key='<API KEY>')`

**Comment by monochromegane** [comment]
👍

**Comment by yauyuirate** [comment]
バージョン：Python3.7.0

**Comment by monochromegane** [comment]
素晴らし！

**Comment by tokibi** [comment]
:tada:

**Comment by yauyuirate** [comment]
Issuesに上記と類似の事例がないか確認しました。

**Comment by yauyuirate** [comment]
Pull Requestsも確認しました

**Comment by monochromegane** [comment]
いけそう感

**Comment by yauyuirate** [comment]
ドキュメントのReverse Geocodingを試してみる。

**Comment by yauyuirate** [comment]
geocodingのためのライブラリを提供するプロバイダの情報が古く
READMEの概要のように地名から座標を取得することが出来ない。
原因はGoogleのAPI KEYが必要になるまでの情報が更新されていないことなので
API KEYが不要な代替のプロバイダ(OpenStreetMap)を使った概要にREADMEを修正して
Pull Requestを出す方向性で作業を進める。

**Comment by monochromegane** [comment]
ステキ〜

**Comment by yauyuirate** [comment]
googleと違いosmは地名に州名を付けると取得できる座標がずれる模様

**Comment by yauyuirate** [comment]
州名なしの地名だとgoogleの結果とほぼ同値

**Comment by monochromegane** [comment]
なるほど．まあREADMEの動かしてみることが目的の場合にはそこまで関係なさそう
