### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: nobu-tora: line-bot-sdk-node.js: Work log

### ISSUE THREAD

**Issue by nobu-tora** [oss-gate/workshop#1032]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nagachika** [comment]
よろしくお願いします!!

**Comment by hsmt** [comment]
|ω・`）チラ

**Comment by nobu-tora** [comment]
プロダクトをswiftから line-bot-sdk-node.jsに変更しました。

**Comment by nobu-tora** [comment]
これからドキュメントの通りに動かしていきます。

**Comment by nobu-tora** [comment]
「Flex Messageを使う」を試してみます。
https://developers.line.biz/ja/docs/messaging-api/using-flex-messages/

**Comment by nobu-tora** [comment]
URLに記載されているシミュレーターを起動しました。
https://developers.line.biz/console/fx/

**Comment by nobu-tora** [comment]
「Hello, World!」のメッセージを送ることはできている。

しかしシミュレーターでOKが出ている内容をコピペしても実行されていない。

**Comment by nagachika** [comment]
「Hello, World!」のサンプルは動いてるので、そこから徐々にシミュレーターで動いてる内容要素を追加していって、どこが問題になっているか洗い出すのがよさそうですね。

**Comment by nobu-tora** [comment]
さっそく徐々に調整したらキレイに表示がされました。

**Comment by nobu-tora** [comment]
他にも使ったことのない機能がたくさんあるので動かしてみたいと思います。

**Comment by nobu-tora** [comment]
間違えてしまった理由はどこにJSONデータを入力するのか記載がなかったからです。
冒頭の書き出しから表記があるとより丁寧で使いやすかったです。
https://developers.line.biz/ja/docs/messaging-api/using-flex-messages/
