### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: y-chinen: vscode: Work log

### ISSUE THREAD

**Issue by y-chinen** [oss-gate/workshop#1033]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tommy6073** [comment]
サポーターのtommyです。よろしくお願いします！

**Comment by y-chinen** [comment]
# vscode
https://github.com/Microsoft/vscode

## 環境構築中
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run
* git clone 済み
* node.jsバージョン切替済み(8.15.0)
* yarnの環境確認中(今ここ)
  v1.6.0なので最新版にアップデート

**Comment by tommy6073** [comment]
Pythonのパス通りましたね。

**Comment by y-chinen** [comment]
* pythonをインストーラーからインストールするとPATHが通っていないので、環境変数に追加する必要がある(Windows環境)
* VSCodeが依存するネイティブモジュール用のコンパイラをインストールする
  ここの手順で推奨されている方「オプション1（推奨）：Windowsビルドツールのnpmモジュールを使う」を試している途中

**Comment by y-chinen** [comment]
```
cd vscode
yarn
```

このコマンドを実行後、エラーが出た。

```
yarn install v1.13.0
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.10: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-tsb@2.0.5" has incorrect peer dependency "typescript@^2.0.10".
[4/4] Building fresh packages...
⠁
⠁
⠁
⠁
info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
error An unexpected error occurred: "C:\\xxxxxxx\\vscode\\node_modules\\gc-signals: Cannot read



[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@3.8.0" with binaries:
      - node-gyp
```

この次にコマンドを実行すると、エラー。

```
yarn watch
```

```
yarn run v1.13.0
$ gulp watch --max_old_space_size=4095
[20:59:01] Node flags detected: --max_old_space_size=4095
[20:59:01] Respawned to PID: 2044
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-bom'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xxxxxxx\vscode\build\lib\compilation.js:10:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by y-chinen** [comment]
再度、yarnを実行するとエラーが出ずに実行出来た。
また、yarn watchもエラーが出ずに実行出来た。

OSSは環境構築が手間がかかるが、vscodeは手順書があるので分かりやすい。
明後日に向けて、明日は動作確認後、Extensionなどのドキュメントの日本語化など出来ることを考える。

**Comment by tommy6073** [comment]
環境構築お疲れ様でした！
実際に動かしてみて貢献できそうなところを探していきましょう！

**Comment by y-chinen** [comment]
vscode本体でエラー探すのが難しそうなのと、既存のissueは割り振られていたので方向転換する。
vscodeが起動するところまでは確認出来ました。

vscodeのドキュメント
https://github.com/Microsoft/vscode-docs
forkして、ローカルにcloneした。
これから何かないか探す。

**Comment by y-chinen** [comment]
さらに方向転換。
vscodeのLocalizationにトライしてみようかと思います。
https://github.com/Microsoft/vscode-loc

MLCPというツールを今月から使う事になった様です。
https://qiita.com/YuichiNukiyama/items/aba5f9f3dbc5c82cba7f

また、README.mdの内容が古いまま(Transifexの説明のまま)なので、issueを投げてみようかと思います。

**Comment by y-chinen** [comment]
Issue書きました。
https://github.com/Microsoft/vscode-loc/issues/47

**Comment by tommy6073** [comment]
Issue発行ナイスです！

**Comment by y-chinen** [comment]
MLCPで２つ翻訳をSuggestしてみましたが、提案が反映されないという現象が発生。
