### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: hasimoto1009: todoist-ruby: Work log

### ISSUE THREAD

**Issue by hasimoto1009** [oss-gate/workshop#1034]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

https://github.com/h6y3/todoist-ruby に未対応の[Emails API](https://developer.todoist.com/sync/v7/#emails)を追加する

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hasimoto1009** [comment]
# 作業ログ
READMEを読んでいる

```
What's not implemented
Generally speaking collaboration features are not supported through this API but contributions are welcome and encouraged primarily due to testing limitations and the requirement to have multiple accounts. This includes:
※一般的に言えば、コラボレーション機能はこのAPIではサポートされていませんが、主にテストの制限と複数のアカウントを持つ必要があるため、貢献は歓迎され奨励されています。
```

やりがいがある
使用するrubyのバージョンは2.6で始めていく
gem i 'todoist-ruby' でインストールはできた

pry をインストールした
require 'todoist' #=> true

email loginをしようとしたが,ログインのgoogleアカウントを使用していたのでtokenをトークンを使う方法しかない?

**Comment by hasimoto1009** [comment]
item = @client.misc_quick.add_item("Test quick add content today") でタスクは追加できたのでruby 2.6.0で普通に動く

**Comment by hasimoto1009** [comment]
gem i  rspec(2.6)

**Comment by hasimoto1009** [comment]
git clone git@github.com:h6y3/todoist-ruby.git
cd todoist-ruby
bundle install

**Comment by hasimoto1009** [comment]
```
rspec spec/misc_items_spec.rb
```
が通った

**Comment by hasimoto1009** [comment]
ちなみに developmentのところを読み勧めてる
https://github.com/h6y3/todoist-ruby#development

**Comment by hasimoto1009** [comment]
最新のcommitは3month agoか

**Comment by hasimoto1009** [comment]
crate_new_labelのAPIがないっぽい?もっと調べる必要があるけど、、、
これを作ってみる https://developer.todoist.com/rest/v8/?shell#create-a-new-label

**Comment by hasimoto1009** [comment]
issueを自分が修正してもいいという、あたりまえのことにきがついた。
apiの対応表を作るだけでも良いとのこと

**Comment by hasimoto1009** [comment]
label_new_createは存在してた。EmailsのAPIを作っておくる。
が、時間が足りそうにない、、、

いいことをyamaさんに教えていただいたのでメモ
- init commit から追ってみるとその人のスタイルがわかるのでできるだけ合わせるとよい
- アカウント名でググるとメイン開発者の母国がわかる その人の母国語でこんにちわするといい。

youtubeでスプラトゥーンばっかり見てないでコード読むくせをつけていくぞ。

**Comment by hasimoto1009** [comment]
検索中: 修正中のgemをpryに読み込む

**Comment by udzura** [comment]
> youtubeでスプラトゥーンばっかり見てないで

すいません...

**Comment by hasimoto1009** [comment]
いや、自分がみれんたらたらなだけなので、、、

**Comment by hasimoto1009** [comment]
>  * Rebuild Ruby with Readline support using `--with-readline`
brew install tigとかしたら、これがreadlineがupdateされてしまいましたね、、、
回避策は再インストールだけなんだろうか

**Comment by hasimoto1009** [comment]
rbenv install -f 2.6.0

**Comment by hasimoto1009** [comment]
homebrew に頼らない強い環境を手に入れたい、、、
