### ISSUE TITLE
 OSS Gate Workshop: Fukuoka: 2019-01-15: YamadaKY: VimEditor :Work log

### ISSUE THREAD

**Issue by YamadaKY** [oss-gate/workshop#1035]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tommy6073** [comment]
サポーターのtommyです。よろしくお願いします！

**Comment by YamadaKY** [comment]
よろしくお願いします！

**Comment by YamadaKY** [comment]
すでにフォークしていた vim/vimリポジトリをクローンしました。

**Comment by tommy6073** [comment]
動かしていきましょう！

**Comment by YamadaKY** [comment]
vim/vimリポジトリをウォッチ設定しようとしたが、「とてもたくさんのメールが来て大変だろう」というのでウォッチはやめました

**Comment by YamadaKY** [comment]
となりのビギナーさんのやっているお話を聞いていました

**Comment by YamadaKY** [comment]
リポジトリvimdoc-ja-workingはVim公式の付属ドキュメント日本語化するプロジェクトということがわかりました。

**Comment by YamadaKY** [comment]
上記REAEMEに「ヘルプの翻訳に協力したい」の見出しがあった
ドキュメントの翻訳協力に何か貢献できないか、と思案中

**Comment by YamadaKY** [comment]
となりのビギナーさんは環境構築をがんばっています

**Comment by YamadaKY** [comment]
サポーターさん談：OSSじゃないがっつり商用ソフトだと、不備や不満があってもベンダーが自らやらないかぎりユーザーはガマンしてつかうしかない
その点OSSだったら、ユーザーも開発に貢献できてソフトも改善されて良い

**Comment by YamadaKY** [comment]
まずはドキュメントからそしてあわよくば技術的な開発をと考えています

**Comment by YamadaKY** [comment]
ふりかえり：
使用OSSは決めたもののやることが見つかるかとても心配でしたが、サポーターさん同じ机のビギナーさんの力添えのおかげで明後日の目標ができてほっとしています。
GitHubのイシューとは何なのかがよくわかってうれしかった
サポーターさんビギナーさん明後日もどうぞよろしくお願いします！

**Comment by tommy6073** [comment]
GitHubの使い方など分かってきたようで良かったです！

ドキュメントの追加、変更が目標ですが、ひとまずおかしいところ、気になったところの指摘イシューを立てる、といった低い目標でもいいかもしれませんね。
あとは日本のVimコミュニティの方をTwitterでフォローしてみたりするのもいいかもしれません。

**Comment by YamadaKY** [comment]
ありがとうございます！
１７日に向けての準備：
vim-jp/vimdoc-ja-workingを読んできます！

**Comment by YamadaKY** [comment]
上記をやる予定だったが
VSCodeのVim機能拡張で欲しい機能があったのを思い出し
VSCodeVim/Vimのリポジトリに行きました
欲しい機能をリクエストするのを目標にします

**Comment by nagachika** [comment]
既存issueに類似のものがないか調べるというステップを踏めたのはすごくいいことだと思います。

**Comment by YamadaKY** [comment]
欲しい機能をリクエストする前に
すでに同じような要望がないかを調べました
結果すでにリクエストがあったことがわかり
提案者に同意する旨コメントとグッド親指マークしました

**Comment by nagachika** [comment]
最近は、同意を意味するためにコメントで :+1: とだけ書くのがいっぱい流れたりするのを嫌ってアクションがつけられるようになった、というような経緯があります。追加の情報がない時はアクションに留めておくのがいいかなと思います。
