### ISSUE TITLE
 OSS Gate Workshop: Fukuoka: 2019-01-15: Wairoku: React-native: Work log

### ISSUE THREAD

**Issue by wairoku** [oss-gate/workshop#1036]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${Fukuoka}: ${2019}-${01}-${15}: ${wairoku}: ${React-native}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by wairoku** [comment]
React-nativeの公式サイトのGetting Startedをやってます。
brew install node
brew install watchman
npm install -g react-native-cli

**Comment by wairoku** [comment]
```
react-native init OssProject
```

**Comment by wairoku** [comment]
最初の画面でました！

**Comment by wairoku** [comment]
![image](https://user-images.githubusercontent.com/43041701/51178018-bc3a1f00-1904-11e9-946d-ee26ac6f9b60.png)

**Comment by wairoku** [comment]
今から書くものををQiitaで探します

**Comment by pyama86** [comment]
このあたりどうでしょう〜
https://facebook.github.io/react-native/docs/tutorial

**Comment by wairoku** [comment]
ありがとうございます！

**Comment by wairoku** [comment]
<img width="360" alt="2019-01-15 20 45 04" src="https://user-images.githubusercontent.com/43041701/51178658-91e96100-1906-11e9-97e1-cb18777a33c7.png">

**Comment by wairoku** [comment]
今こんな感じです。

**Comment by pyama86** [comment]
iPhoneXだからベゼルの向こう側にいってるｗ

**Comment by pyama86** [comment]
https://facebook.github.io/react-native/docs/text

**Comment by wairoku** [comment]
今日はiPhone 6sで開いてみました。
テキストは上の真ん中にあります。
![image](https://user-images.githubusercontent.com/43041701/51311550-86c03d80-1a8c-11e9-87c7-c3ef840ca743.png)

**Comment by wairoku** [comment]
そうですねえ
参考になりそうなの探してみます。

**Comment by wairoku** [comment]
Viewタグをつけたらうまくいきました！
![image](https://user-images.githubusercontent.com/43041701/51313429-dc96e480-1a90-11e9-81f5-faf5fac58dce.png)

**Comment by wairoku** [comment]
コードはこんな感じです。
```
<View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Hello World!</Text>
      </View>
```

**Comment by wairoku** [comment]
テキストや画像なども一緒に色々表示させてみます。

**Comment by wairoku** [comment]
When you display Hello world, if you write it as it is, Hello world is displayed at the top of the screen.
![image](https://user-images.githubusercontent.com/43041701/51314979-7b711000-1a94-11e9-8459-f7ef96625b1a.png)

If you write the code below it will be displayed in the center of the screen.
```
<View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
        <Text>Hello World!</Text>
      </View>
```

![image](https://user-images.githubusercontent.com/43041701/51315274-25509c80-1a95-11e9-9fc5-4c9ba2f1dd0c.png)

**Comment by pyama86** [comment]
まず挨拶があったほうが良さそうです。次にどのページの話なのか？が伝わらないかなと思いました。キャプチャ、可能であれば縮小してあげたほうがいいかも？
https://dackdive.hateblo.jp/entry/2015/05/08/110029
