### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: seitaro1991: Vue.js: Work log

### ISSUE THREAD

**Issue by seitaro1991** [oss-gate/workshop#1038]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Fukuoka: 2019-01-15: seitaro1991: Vue.js: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by seitaro1991** [comment]
OSS Gate Workshop: Fukuoka: 2019-01-15: seitaro1991: Vue.js: Work log

index.htmlにvueのコードを書いていく

**Comment by seitaro1991** [comment]
条件分岐とループ処理をやってます

**Comment by pyama86** [comment]
よいですね〜。動いたら見せてください〜

**Comment by seitaro1991** [comment]
動きました！

**Comment by pyama86** [comment]
https://qiita.com/YosukeItabashi/items/5722395218e6e592fd39

**Comment by seitaro1991** [comment]
双方向バインディングについて調べています。

**Comment by pyama86** [comment]
vuejsの真骨頂だ。

**Comment by pyama86** [comment]
# コメント例
今は、双方向バインディングをやってます。
https://jp.vuejs.org/v2/guide/components-registration.html

双方向バインディングはvue.jsの特徴の一つでめっちゃ便利っぽい

![image](https://user-images.githubusercontent.com/8022082/51179857-0ffb3700-190a-11e9-9826-ababd21a7201.png)

**Comment by seitaro1991** [comment]
vue.jsの開発者コミュニティ（https://jp.vuejs.org/v2/guide/join.html）
ページにある「#サポートを受ける」カテゴリの「chat」リンクをクリックしても中々ページが表示されない。URLが間違っているのかも？

**Comment by pyama86** [comment]
https://github.com/vuejs/vuejs.org
こちらが公式サイトのリポジトリみたいですね。
こちらにissueを起票してあげると良さそうです。
また画像などがあるとお互いの意思疎通がやりやすそうですね。

**Comment by seitaro1991** [comment]
issueにスクショを添付して起票する場合、英語に翻訳した画面を添付した方が良いですか？
![image](https://user-images.githubusercontent.com/36176446/51314346-d43fa900-1a92-11e9-95d4-bb141f7cf82e.png)

**Comment by seitaro1991** [comment]
Vue.js の公式サイトのソースコードにissueを立てることができました。
