### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: shoko93: php-mailer: Work log

### ISSUE THREAD

**Issue by shoko93** [oss-gate/workshop#1039]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hsmt** [comment]
Spring-bootいいですね！なにかお困りですかー？

**Comment by shoko93** [comment]
Spring-bootから[PHPMailer](https://github.com/PHPMailer/PHPMailer)に変更
PHPMailer/test/PHPMailerLangTest.phpでエラーを確認

**Comment by shoko93** [comment]
composer installを実行しているが、dependencyのアップデートに時間がかかっている

**Comment by shoko93** [comment]
今日のまとめ

- composer installが私の環境ではなかなかうまくいかなかった（時間がかかりすぎた）ので、composer.jsonを必要最小限（PHPUnit、PHPMailerのみ）に変更したところうまくいった

- PHPMailerLangTest.phpで翻訳が足りていない部分を確認できるということで、PHPUnitを使用して実行してみたがエラーが返ってきた

- testフォルダーには、ライブラリそのもののテスト用スクリプトも含まれていたが、こちらもエラーが発生

- 以前使用した際文字化けした記憶があったので、確かめたところ`$mail -> CharSet = "UTF-8";`を設定しないとメールの件名が文字化けしてしまうことを再確認。ドキュメントのどこかに説明してあるのかもしれないが、UTF-8に対応させることは結構一般的なことだと思うので、READMEに加えた方がわかりやすいと思った

木曜に取り組むこと
- テストがうまくいかない原因をもうちょっと探ってみる

- 使用したことのあるGmail以外のexamplesのコードをいくつか使用してみる

- [Tutorial](https://github.com/PHPMailer/PHPMailer/wiki/Tutorial)を読んで改善できそうな点がないか確認する

**Comment by shoko93** [comment]
READMEで初めて利用する場合のとっかかりとしてexamples/gmail.phpの参照を推奨しているが、これとexamples/contactform.phpを組み合わせてフォームの利用、Gmailの利用を一つにまとめれば、PHPでの開発経験が浅い人でもより簡単に理解し使用することができると思う。

**Comment by shoko93** [comment]
exampleフォルダーにcontactform.phpとsimple_contact_form.phpが存在するが、ファイル名を改善し違いを明確にするか、一つに統一した方が良いと思う。個人的にはcontactform.phpの方がシンプルで理解しやすい。

**Comment by udzura** [comment]
状況の実況いい感じです〜 いくつかモヤっとポイントややりたいことが見えてきているので、一つに絞ってIssue/PRを作ってみることろをゴールにすると良さそうです

**Comment by shoko93** [comment]
自分なりにこういたサンプルの方が初めて利用する方にはわかりやすいんじゃないかというのでexample code改良してみたんですけど、Issueあげるのとプルリク送るのとどちらがいいですかね？

**Comment by yama** [comment]
その場合はいきなりプルリクでもokだと思います。
スクリーンショットを添えてあげるといいかも？

**Comment by yama** [comment]
あ、フォームじゃなくてphpコードなんですね

**Comment by yama** [comment]
https://github.com/shoko93/PHPMailer
ここに別ブランチ切って上げてもらえたら、見てみます

**Comment by yama** [comment]
ブランチ名は最初は適当に「test」とかでいいと思います

**Comment by shoko93** [comment]
PHPMailerのフォルダ内で、自分で作成したサンプルのコードを動かせるようになるまで時間がかかりそうなので、とりあえず別の改善点をIssueとしてあげます。

**Comment by shoko93** [comment]
Issueとしてあげる内容：PHPMailerLangTest.phpを実行するのに苦労した。composer installに時間がかかったため、composer.jsonを簡略化する必要があった。DirectoryIteratorのパスを変更する必要があった。（`$path = __DIR__ . '/../language';`に変更。)

**Comment by shoko93** [comment]
とりあえず、Issueあげてみた
https://github.com/PHPMailer/PHPMailer/issues/1637
