### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-01-15: aoronesy: tensorflow: work_log

### ISSUE THREAD

**Issue by aoronesy** [oss-gate/workshop#1040]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by aoronesy** [comment]
そもそもpythonが入っていないと動かせそうに無いので、インストールしてみる

tensolflowのmac用ビルドページ
https://www.tensorflow.org/install/source?hl=ja

**Comment by aoronesy** [comment]
ビルドページの　
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

brew install python@2  # or python (Python 3)
このコードを打つと　
RYOnoMacBook-puro:~ ryoaoshima$ brew install python@3
-bash: brew: command not found
と表示
Homebrewというものが必要なのでインストール

**Comment by aoronesy** [comment]
ビルドページの　
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
brew install python@3 

今回はpython3でインストール

**Comment by tsubakimoto** [comment]
pythonのバージョン確認

```
python --version
```

**Comment by aoronesy** [comment]
pip install -U --user pip six numpy wheel mock
-bash: pip: command not found

と表示

**Comment by tsubakimoto** [comment]
[Pythonインストール（Mac編） - Qiita](https://qiita.com/ms-rock/items/6e4498a5963f3d9c4a67)

**Comment by tsubakimoto** [comment]
[pypa/pip: The PyPA recommended tool for installing Python packages](https://github.com/pypa/pip)
ここからインストール方法を探ってみてください

**Comment by aoronesy** [comment]
pipのインストール
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py --user

pipのバージョン確認
python -m  pip --version

**Comment by aoronesy** [comment]
python -m pip install -U --user pip six numpy wheel mock
python -m pip install -U --user keras_applications==1.0.6 --no-deps
python -m pip install -U --user keras_preprocessing==1.0.5 --no-deps

流してみる

**Comment by aoronesy** [comment]
python -m pip install -U --user pip six numpy wheel mock


RYOnoMacBook-puro:~ ryoaoshima$ python -m pip install -U --user pip six numpy wheel mock
Requirement already up-to-date: pip in ./Library/Python/2.7/lib/python/site-packages (18.1)
Collecting six
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/e4/97/167eb80dadcf2905b58d66ada6c128d3ec5e8595beb02457b881e7399be3/numpy-1.16.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 677kB/s 
Requirement already up-to-date: wheel in ./Library/Python/2.7/lib/python/site-packages (0.32.3)
Collecting mock
  Downloading https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 7.9MB/s 
Collecting funcsigs>=1; python_version < "3.3" (from mock)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock)
  Downloading https://files.pythonhosted.org/packages/f3/04/fddc1c2dd75b256eda4d360024692231a2c19a0c61ad7f4a162407c1ab58/pbr-5.1.1-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 9.9MB/s 
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: six, numpy, funcsigs, pbr, mock
  The scripts f2py, f2py2 and f2py2.7 are installed in '/Users/ryoaoshima/Library/Python/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pbr is installed in '/Users/ryoaoshima/Library/Python/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed funcsigs-1.0.2 mock-2.0.0 numpy-1.16.0 pbr-5.1.1 six-1.12.0

**Comment by nagachika** [comment]
おっ、TensorFlow!! (コントリビューターです)

**Comment by aoronesy** [comment]
curl https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py -o setup.py

python setup.py --user
RYOnoMacBook-puro:~ ryoaoshima$ curl https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py -o setup.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  158k    0  158k    0     0  61028      0 --:--:--  0:00:02 --:--:-- 61012
RYOnoMacBook-puro:~ ryoaoshima$ 
RYOnoMacBook-puro:~ ryoaoshima$ python setup.py --user
  File "setup.py", line 7
    <!DOCTYPE html>
    ^

とエラーが出てくる。。。

**Comment by tsubakimoto** [comment]
# あとで振り返るためにやっとくといいこと
- 実行したコマンドを残す
- 実行したコマンドのなかで出力されたテキストを残す
- そのコマンドが成功したか失敗したかを残す
- 失敗したら：なにが原因そうかを考える

**Comment by aoronesy** [comment]
バージョン管理システム pyenv  Pythonのバージョン切り替えが行えます。
pyenv-virtualenvはPython環境を管理するためのPyenvプラグインです。
らしいので　インストールしてみる　
参考：https://qiita.com/tom_ato/items/bbdf4574b3ecb0048fa1

**Comment by aoronesy** [comment]
Homebrewでpyenvをインストール
`$ brew install pyenv`

Homebrewでpyenv-virtualenvをインストール
`$ brew install pyenv-virtualenv`

Pythonのバージョン一覧を表示して確認
`$ pyenv install -l`

Python3.6.0をインストールし、Shimsをリフレッシュ
`$ pyenv install 3.6.0`
...
...
`$ pyenv rehash`

**Comment by aoronesy** [comment]
インストールした後もう一度　`$ pyenv install 3.6.0`

python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.0.tar.xz...
-> https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
Installing Python-3.6.0...
python-build: use readline from homebrew
Installed Python-3.6.0 to /Users/ryoaoshima/.pyenv/versions/3.6.0

インストールできた模様・・・？

**Comment by aoronesy** [comment]
参考：https://qiita.com/KazaKago/items/587ac1224afc2c9350f1
Python 3.6.0のTensorFlow用の環境を作成
`$ pyenv virtualenv 3.5.2 TensorFlow`
`$ pyenv rehash`

作成したTensorFlow用の環境へ切り替え
`$ pyenv global TensorFlow`
`$ python -V`
    `Python 3.6.0`
になった！

pyenv-virtualenv　は仮想環境なのかな？

**Comment by aoronesy** [comment]
Successfully installed absl-py-0.6.1 astor-0.7.1 gast-0.2.2 grpcio-1.17.1 h5py-2.9.0 keras-applications-1.0.6 keras-preprocessing-1.0.5 markdown-3.0.1 numpy-1.16.0 protobuf-3.6.1 six-1.12.0 tensorboard-1.12.2 tensorflow-1.12.0 termcolor-1.1.0 werkzeug-0.14.1 wheel-0.32.3

と出ていたので　インストールできているのか・・？

**Comment by aoronesy** [comment]
PyCharmというIDEがいいらしいのでインストールしてみるが
Interpreter　の周りがよくわからない
参考：https://qiita.com/acecrc/items/4bf5f986d950af26044f
の手順でtensorflow の動作確認をターミナル上でしてみる
`$ python`
Python 3.6.5 (default, Apr 26 2018, 00:14:31) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>` import tensorflow as tf`
>>>` hello = tf.constant('Hello World TensorFlow')`
>>>` sess = tf.Session()`
2018-07-12 09:53:54.209491: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
>>> `print(sess.run(hello))`
b'Hello World TensorFlow'
>>> `quit()`

一応手順通り動いた。

**Comment by aoronesy** [comment]
Tensorflowチュートリアルのソースコードを公式ページからコピーする
参考：https://qiita.com/acecrc/items/4bf5f986d950af26044f

`$ mkdir MyTensorflow`
`$ cd MyTensorflow/`
`$ vi tutorial.py`

tutorial.pyに以下を記述　https://www.tensorflow.org/tutorials/?hl=ja

import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

`$ python tutorial.py`
で実行すると
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 1s 0us/step
Epoch 1/5
2019-01-16 01:58:30.276553: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
60000/60000 [==============================] - 6s 106us/step - loss: 0.2036 - acc: 0.9395
Epoch 2/5
60000/60000 [==============================] - 6s 100us/step - loss: 0.0808 - acc: 0.9758
Epoch 3/5
60000/60000 [==============================] - 6s 102us/step - loss: 0.0532 - acc: 0.9835
Epoch 4/5
60000/60000 [==============================] - 6s 95us/step - loss: 0.0360 - acc: 0.9893
Epoch 5/5
60000/60000 [==============================] - 6s 99us/step - loss: 0.0267 - acc: 0.9911
10000/10000 [==============================] - 0s 36us/step

一応手順通りに動いたのでインストールは出来ている見たい

**Comment by tsubakimoto** [comment]
TFのインストールはうまくいったみたいですね！素晴らしい！
もしday2でやることに困っていたらこの辺を参考にしてみてください。

- インストールした手順とドキュメントに差がなかったか
    - もしドキュメントに不備を見つけたらこのリポジトリにIssueを出してみる？
    - [tensorflow/docs: TensorFlow documentation](https://github.com/tensorflow/docs)
- TFのサンプルを動かしてみて、動かない部分があったらIssueを出してみる
    - 例えば [aymericdamien/TensorFlow-Examples: TensorFlow Tutorial and Examples for Beginners with Latest APIs](https://github.com/aymericdamien/TensorFlow-Examples) とか

**Comment by tsubakimoto** [comment]
Colaboratoryっていうツールがあって、さくっと試したいときに良いらしい。
https://colab.research.google.com/notebooks/welcome.ipynb?hl=ja

**Comment by aoronesy** [comment]
TnsorFlow install 

pythonも入っていないのでHomebrewでインストール
HomeBrew
`https://brew.sh/index_ja`
ビルドページのコードからpythonをインストールしてみる
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

`export PATH="/usr/local/bin:/usr/local/sbin:$PATH"`

`brew install python@2  # or python (Python 3)`


ここでpython3系を入れたかったが、間違ってpython2系をインストールしてしまう。。。
とりあえず、先に進む

ビルドページの
`pip install -U --user pip six numpy wheel mock`
を流すと`-bash: pip: command not found`となった

pipが入っていないみたいなのでpipのインストール
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python get-pip.py --user`

インストール出来たのでもう一度ビルドページのpipコマンドを流してみる
`python -m pip install -U --user pip six numpy wheel mock`
`python -m pip install -U --user keras_applications==1.0.6 --no-deps`
`python -m pip install -U --user keras_preprocessing==1.0.5 --no-deps`

が上手く行かなかったので
homebrewからpyenv とpyenv-virtualenvをインストール
(pythonのバージョン管理ツールとの事)
`brew install pyenv`
`brew install pyenv-virtualenv`

Pythonのバージョン一覧を表示して確認
`pyenv install -l`

今回はPython3.6.0をインストール
`pyenv install 3.6.0`

するが

python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.0.tar.xz...
-> https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
Installing Python-3.6.0...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/kr/fzsv3y4x2vb5h7nnyhbrkw600000gn/T/python-build.20190115231008.69622
Results logged to /var/folders/kr/fzsv3y4x2vb5h7nnyhbrkw600000gn/T/python-build.20190115231008.69622.log

Last 10 log lines:
File "/private/var/folders/kr/fzsv3y4x2vb5h7nnyhbrkw600000gn/T/python-build.20190115231008.69622/Python-3.6.0/Lib/ensurepip/main.py", line 4, in 
ensurepip._main()
File "/private/var/folders/kr/fzsv3y4x2vb5h7nnyhbrkw600000gn/T/python-build.20190115231008.69622/Python-3.6.0/Lib/ensurepip/init.py", line 189, in _main
default_pip=args.default_pip,
File "/private/var/folders/kr/fzsv3y4x2vb5h7nnyhbrkw600000gn/T/python-build.20190115231008.69622/Python-3.6.0/Lib/ensurepip/init.py", line 102, in bootstrap
_run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
File "/private/var/folders/kr/fzsv3y4x2vb5h7nnyhbrkw600000gn/T/python-build.20190115231008.69622/Python-3.6.0/Lib/ensurepip/init.py", line 27, in _run_pip
import pip
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1
`
とエラー

参考：https://qiita.com/zreactor/items/c3fd04417e0d61af0afe
xcode-selectの最新バージョン(2354)にMojave用のmacOS SDK headerがデフォルトで入っていないのが原因のよう
マニュアルで以下をインストールする必要があるらしいのでインストール
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

その後もう一度pythonのインストールコマンドでインストール完了

pipのインストールをもう一度してみる
`sudo easy_install pip`
`sudo pip install --upgrade pip`

macOSのGPU版はサポートされなくなったとの事なのでCPU版をインストール
`pip install tensorflow`

TensorFlowのインストール完了
