### ISSUE TITLE
    OSS Gate Workshop: TOKYO: 2019-01-26: ryuchan00(Yamakawa Ryutaro): RSpec: Work log

### ISSUE THREAD

**Issue by ryuchan00** [oss-gate/workshop#1070]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by y-goto** [comment]
よろしくお願いします。

**Comment by ryuchan00** [comment]
よろしくお願いします。 🙇

**Comment by ryuchan00** [comment]
作業ディレクトリを作成して、initializeをした。

```
[11:26] /Users/ryuutarou/workspace (2.5.0)
$ mkdir oss-gate-rspec
[11:27] /Users/ryuutarou/workspace (2.5.0)
$ cd oss-gate-rspec
[11:27] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ rspec --init
  create   .rspec
  create   spec/spec_helper.rb
[11:27] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ ls
spec/
[11:27] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ la
./      ../     .rspec  spec/
```

**Comment by ryuchan00** [comment]
RSpecに指し示されたドキュメントを見てるが、tutorialのようなものは見当たらない。API Documentと書かれているので、個別のmethodの使用方法が記述されている形式だと予想する。これからtutorial探していく。

[RSpec documentation](http://rspec.info/documentation/)

**Comment by ryuchan00** [comment]
RSpecのリポジトリのリンクに指し示されていたRSpec docは情報がtutorialが記載されていなかった。Relishというドキュメントサイト?のリンクが記載されていた。Relishの意味は現時点では不明。特にRSpec特有の用語という感じは受けなかった。これからRelishとは何かを調査していく。

[RSpec documentation](http://rspec.info/documentation/)

[Home - Relish](https://relishapp.com/)

**Comment by ryuchan00** [comment]
Relishのトップページに `cucumber test` という単語が書いてあり意味がわからず混乱している。
cucumber とはきゅうりという意味。cucumberはテストのツールのような印象を受けるが、見通しが悪くて具体的な使用方法がまだつかめていない。

[cucumber/cucumber: Cucumber monorepo - building blocks for Cucumber in various languages](https://github.com/cucumber/cucumber)

**Comment by ryuchan00** [comment]
About Relishを見たけど、正直よくわからない。

> About relish
Relish helps your team get the most from Behaviour Driven Development (BDD). Publish, browse, search, and organize your Cucumber features on the web.

**Comment by ryuchan00** [comment]
RelishのRuby Gemを見つけたけど、ドキュメントがなさすぎてよくわかりません。

[cucumber-ltd/relish-gem: Client gem for http://relishapp.com](https://github.com/cucumber-ltd/relish-gem)

**Comment by ryuchan00** [comment]
Relishは多分、ドキュメントの管理ツールではないかと予想されます。しかし、時間も有限であるため、一度RSpecのGet Startedに戻り、チュートリアルを進めていくことにします。

**Comment by ryuchan00** [comment]
> Prerequisites
Ruby 1.8.7 or higher (2.0+ recommended)

https://relishapp.com/rspec/docs/gettingstarted

このドキュメント自体4年以上前に書かれているので古いと感じる。Ruby1.8.7以上(推奨は2.0以上)は最新のRubyバージョンとはかなり離れているように感じる。

**Comment by ryuchan00** [comment]
[Publisher: RSpec - Relish](https://relishapp.com/rspec/docs/gettingstarted)

RelishのGet Started通りにすると、本来は下記のエラーが出力されるはずである。

```
$ rspec game_spec.rb 
  uninitialized constant Object::Game (NameError)
```

しかし、実際は異なるエラーメッセージが出力される。

```
[12:14] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$  rspec game_spec.rb

An error occurred while loading ./game_spec.rb.
Failure/Error:
  RSpec.describe Game do
    describe "#score" do
      it "returns 0 for an all gutter game" do
        game = Game.new
        20.times { game.roll(0) }
        expect(game.score).to eq(0)
      end
    end
  end

NameError:
  uninitialized constant Game
# ./game_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00024 seconds (files took 0.24345 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

```

**Comment by ryuchan00** [comment]
午後は、引き続きRSpecのチュートリアルを進めていく。

**Comment by ryuchan00** [comment]
RelicshのRSpec ドキュメントに脈略なく `--color` と `--format` オプションが付与されている。これは、failのテストの時は書かれていなかった。

> $ rspec game_spec.rb --color --format doc

**Comment by ryuchan00** [comment]
Gameクラスを追加してテストを走らせた結果、ドキュメント通りにテストがgreenになった。

```
[13:45] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$  rspec game_spec.rb --color --format doc

Game
  #score
    returns 0 for an all gutter game

Finished in 0.0025 seconds (files took 0.22178 seconds to load)
1 example, 0 failures

```

```
[13:48] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ la
./              ../             .rspec          game.rb         game_spec.rb    spec/
```

**Comment by ryuchan00** [comment]
これからは、テストの実行コマンドに `--color` や `--format` のオプションがついているので、それを外した場合にどうなるのか試す。そうすることによって、なぜオプションがついているのかの意図がわかる。

**Comment by ryuchan00** [comment]
--formatに関しては、オプションの説明があった。docと指定しているのは、おそらくdocumantationという形式でテスト結果をアウトプットしていると予想する。

```
    -f, --format FORMATTER             Choose a formatter.
                                         [p]rogress (default - dots)
                                         [d]ocumentation (group and example names)
                                         [h]tml
                                         [j]son
                                         custom formatter class name
```

**Comment by ryuchan00** [comment]
--colorを外してやってみてもカラーはついたままだった。もっと古い環境、もしくはもっと古いRSpecのバージョンだったらカラーがつかないので、--colorをつけていたのかもしれない。聞いてみるのもいいかもしれない。

```
[13:57] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ rspec game_spec.rb --format doc

Game
  #score
    returns 0 for an all gutter game

Finished in 0.00238 seconds (files took 0.19799 seconds to load)
1 example, 0 failures

[13:57] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ rspec game_spec.rb --color --format doc

Game
  #score
    returns 0 for an all gutter game

Finished in 0.00166 seconds (files took 0.15735 seconds to load)
1 example, 0 failures

```

**Comment by ryuchan00** [comment]
--format doc のdocとは、RSpecのdescribeやitなどに書かれたStringを構造化して出力する。

```
[14:09] /Users/ryuutarou/workspace/oss-gate-rspec (2.5.0)
$ rspec game_spec.rb --color --format doc

Game
  #score
    returns 0 for an all gutter game (FAILED - 1)

Failures:

  1) Game#score returns 0 for an all gutter game
     Failure/Error: expect(game.score).to eq(1)

       expected: 1
            got: 0

       (compared using ==)
     # ./game_spec.rb:8:in `block (3 levels) in <top (required)>'

Finished in 0.02692 seconds (files took 0.23546 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./game_spec.rb:5 # Game#score returns 0 for an all gutter game

```

**Comment by ryuchan00** [comment]
気づいた点としては、 --format doc と記述されてはいるが、RSpecのhelpで表示されているのは--format documentationなので、helpとは形式が異なる。これは指摘できそうなのでは

**Comment by ryuchan00** [comment]
Relishのドキュメント元は
[doc-site/GettingStarted.md at master · rspec/doc-site](https://github.com/rspec/doc-site/blob/master/features/GettingStarted.md)
に存在する。最終更新が2014年で、最新のバージョンに全く追従できておらず、ドキュメントの管理の意思があるのか確認する必要がある。

**Comment by ryuchan00** [comment]
課題としてドキュメンテーションのリポジトリが活動していない恐れがある。そのため、まずはrspecリポジトリのissueに更新はどうしてらできるのかということを聞かなくてはならない。

**Comment by ryuchan00** [comment]
やりたいこと：
- RSpecのGet Startedのドキュメントのテストの実行時に`--color`オプションは不要である可能性があるので削除したい
[Publisher: RSpec - Relish](https://relishapp.com/rspec/docs/gettingstarted)

RSpecのGet Startedのドキュメントのテストの実行時に`--format`オプションの引数`doc`はRSpecのhelpには記述されていない。したがって、`documentation`を引数としてあげたい。

**Comment by ryuchan00** [comment]
振り返り

--colorオプションが削除された経緯がわかれば、伝わりやすいドキュメントになる。
