### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-01-26: nkgwnoto: vue: Work log

### ISSUE THREAD

**Issue by nkgwnoto** [oss-gate/workshop#1071]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kyanny** [comment]
よろしくおねがいします！ 👋

**Comment by nkgwnoto** [comment]
https://jp.vuejs.org/v2/guide/installation.html 日本語のページがあった
英語と日本語の切り替えできないかな？

**Comment by nkgwnoto** [comment]
npmでインストールされているか確認する

**Comment by nkgwnoto** [comment]
http://phiary.me/npm-package-version-info-install/　でインストールされているか調べた

**Comment by nkgwnoto** [comment]
npm list --depth=0　をコマンドプロンプトで入力すると
`-- vue@2.5.19　　　と出た

**Comment by nkgwnoto** [comment]
公式ドキュメントにnpmでインストールしたときのアンインストール方法が載っていないのが気になる

**Comment by nkgwnoto** [comment]
http://www.fumiononaka.com/Business/html5/FN1807002.html　
npm uninstall -g vue-cli　これを
npm uninstall -g vue　これに書き換えればアンインストールできる？

**Comment by nkgwnoto** [comment]
npm uninstall -g vue　これをコマンドプロンプトで実行してみると
up to date in 0.047s　と出た

**Comment by nkgwnoto** [comment]
アンインストールコマンドをいれてみたが、変わらなかった。
C:\Users\nakagawa>npm uninstall -g vue
up to date in 0.047s

C:\Users\nakagawa>npm list --depth=0
C:\Users\nakagawa
`-- vue@2.5.19

**Comment by nkgwnoto** [comment]
npm uninstall -g vue-cli を実行してみる

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm uninstall -g vue-cli
removed 239 packages in 4.948s
さっきと違う

**Comment by nkgwnoto** [comment]
https://github.com/vuejs/vue-cli/issues/1241
npm uninstall -g @vue/cli
を実行してみる

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm uninstall -g @vue/cli
up to date in 0.045s

C:\Users\nakagawa>npm list --depth=0
C:\Users\nakagawa
`-- vue@2.5.19
変わらない

**Comment by nkgwnoto** [comment]
http://phiary.me/npm-package-version-info-install/
npm list --depth=0 -g
を実行してみる

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm list --depth=0 -g
C:\Users\nakagawa\AppData\Roaming\npm
`-- (empty)

**Comment by nkgwnoto** [comment]
公式ドキュメントの
npm install vue
を実行してみる

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm install vue
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\nakagawa\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nakagawa\package.json'
npm WARN nakagawa No description
npm WARN nakagawa No repository field.
npm WARN nakagawa No README data
npm WARN nakagawa No license field.

+ vue@2.5.22
updated 1 package and audited 1 package in 1.382s
found 0 vulnerabilities
インストールできた？

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm list --depth=0 -g
C:\Users\nakagawa\AppData\Roaming\npm
`-- (empty)


C:\Users\nakagawa>npm list --depth=0
C:\Users\nakagawa
`-- vue@2.5.22

-g 付きだとインストールされる場所が違うから空
なしだとさっきインストールしたバージョンのvueが表示された

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm uninstall vue-cli
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\nakagawa\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nakagawa\package.json'
npm WARN nakagawa No description
npm WARN nakagawa No repository field.
npm WARN nakagawa No README data
npm WARN nakagawa No license field.

audited 1 package in 0.747s
found 0 vulnerabilities
これでさっきインストールしたvueがアンインストールされた？

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm list --depth=0
C:\Users\nakagawa
`-- vue@2.5.22
アンインストールされてない？
cliのみアンインストールされた？

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm uninstall vue
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\nakagawa\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\nakagawa\package.json'
npm WARN nakagawa No description
npm WARN nakagawa No repository field.
npm WARN nakagawa No README data
npm WARN nakagawa No license field.

removed 1 package in 0.69s
found 0 vulnerabilities

vue自体をアンインストールできた？

**Comment by nkgwnoto** [comment]
C:\Users\nakagawa>npm list --depth=0
C:\Users\nakagawa
`-- (empty)
アンインストールされた！

**Comment by nkgwnoto** [comment]
自分の考え:
vueをアンインストールしようとしたが、公式ドキュメントのインストールコマンドに対応したアンインストールコマンドを見つけられなかった。公式ドキュメントにアンインストールの方法を載せたほうがいいのでは。

**Comment by nkgwnoto** [comment]
https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md
コントリビューションガイドがあったので確認する。

**Comment by nkgwnoto** [comment]
https://new-issue.vuejs.org/?repo=vuejs/vue
このフォームに沿った報告を考える。

**Comment by nkgwnoto** [comment]
feature requestでイシューを投げる

**Comment by nkgwnoto** [comment]
必要な項目
タイトル
どのような問題を解決するか

どのようなAPIの提案か？
→今回はドキュメントに対してのイシューなので、APIに対しての提案はありません。

**Comment by nkgwnoto** [comment]
前提
・公式ドキュメントのInstallationページ(https://vuejs.org/v2/guide/installation.html)に記載されているnpm install vueを実行し、インストールした状態。

・一旦インストールされてない状態に戻し、再度インストールしたかった。

**Comment by nkgwnoto** [comment]
困ったこと
・公式ドキュメントのインストールコマンドに対応したアンインストールコマンドを見つけられなかった。

**Comment by nkgwnoto** [comment]
提案
・公式ドキュメントにアンインストールのコマンドを載せたほうがいいのでは。

**Comment by nkgwnoto** [comment]
タイトル
公式ドキュメントにアンインストールのコマンドを載せて欲しい。

**Comment by nkgwnoto** [comment]
イシュー作った
https://github.com/vuejs/vue/issues/9374
