### ISSUE TITLE
OSS Gateワークショップ2016-01-30: hanzgit: node.js: 作業ログ

### ISSUE THREAD

**Issue by hanzgit** [oss-gate/workshop#11]

**Comment by hanzgit** [comment]
作業メモ：virtual box にcentosをインストール開始。

**Comment by hanzgit** [comment]
作業メモ：インストールが完了しました。パスワードを忘れしまったので注意したい。

**Comment by hanzgit** [comment]
linuxの環境が整ったので、メンターの方の開発を模擬させてもらうためにnode.jsを試してみる。

**Comment by hanzgit** [comment]
node.jsの本家のサイトをみてみる

**Comment by hanzgit** [comment]
インストールドキュメントを探す

**Comment by hanzgit** [comment]
https://nodejs.org/en/docs/

**Comment by hanzgit** [comment]
node.js はjavascripstのscarable network frameworkであることを知る。

**Comment by hanzgit** [comment]
インストール実行。インストール完了した方法がHP上見当たらなかったが、cmdで「node -v」とすれば確認できた。

**Comment by hanzgit** [comment]
動作確認する方法が公式HPにあるとよかったが見当たらなかったので他を探してみる。

**Comment by hanzgit** [comment]
サンプルを動作させてみる。

**Comment by hanzgit** [comment]
公式HPのサンプルをコピーして、node ファイル名.jsで実行。hello worldが無事表示された

https://nodejs.org/en/about/

**Comment by hanzgit** [comment]
ユーザーとしては動作確認できたので、開発者としての動作確認方法を調べる

**Comment by hanzgit** [comment]
動作確認に関する追記。

公式ＨＰの動作確認方法が記載はされていたが、見つかりにくかった。https://nodejs.org/en/about/　
インストールのページに記載されているとわかりやすいと感じた

**Comment by hanzgit** [comment]
以下のページの動作確認方法を参照して公式ＨＰに記載されていることに気付いた。
http://www.pxt.jp/ja/diary/article/265/

**Comment by hanzgit** [comment]
動作確認の方法がわかりにくかったことを報告してみようと思います。

**Comment by hanzgit** [comment]
「1.（自分の考えを）整理した」

・windows7にnode.jsをインストールして動作確認しようとした。

・node.jsのインストール後に動作確認する方法がわかりにくかった。


・「download」→「Installing Node.js via package manager」
　→「windows」に記載があることを予想したが、記載がなかった。

・「about」に記載があることを他の開発者のブログで知ったが、
　前述の場所に記載があるとわかりやすいと感じた。

・実行コマンドも記載があるとわかりやすいと感じた。

**Comment by hanzgit** [comment]
「2.開発者にとってわかりやすくなるように編集」する

**Comment by hanzgit** [comment]
「2.開発者にとってわかりやすくなるように編集」してみました。

For the first time, I tried to install node.js on windwos7
and feel hard to know how to check operation after installation.

I estimate to be described about operation check at
 node.js HP(https://nodejs.org/en/)
  ->[DOWNLOADS](https://nodejs.org/en/download/)
  ->[Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/)
  ->[Windows](https://nodejs.org/en/download/package-manager/#windows)
(but don't be described.)  

I know to be described about operation check at [ABOUT](https://nodejs.org/en/about/)
and feel better to be described at that place([DOWNLOADS]->[Installing Node.js via package manager]->[Windows]).

In addition I feel better to be described about execution command(node filename.js).

**Comment by hanzgit** [comment]
メンターの方々にアドバイスをいただいので更新する。（以下の記載もあるとわかりやすい）

・自分の背景
・自分の場合どう記載するか
・どういう情報がほしかったか
・何をしようとしたか

**Comment by hanzgit** [comment]
アドバイスをもとに更新できた。

I usually use windows7 and have never use node.js in any platform.
In this time I start to use node.js.

For the first time, I tried to install node.js on windwos7
and feel hard to know how to check operation after installation.

I estimate to be described about operation check at
 node.js HP(https://nodejs.org/en/)
  ->[DOWNLOADS](https://nodejs.org/en/download/)
  ->[Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/)
  ->[Windows](https://nodejs.org/en/download/package-manager/#windows)
(but don't be described.)  

Through ohter engineer's blog,
I know to be described about operation check at [ABOUT](https://nodejs.org/en/about/)
and feel better to be described at that place([DOWNLOADS]->[Installing Node.js via package manager]->[Windows]).

In addition I feel better to be described about execution command(node filename.js).

*****example*******

 Windows

 1.Simply download the Windows Installer directly from the nodejs.org web site.

 2. Check operation

 2-1. Create example.js.

 ==example.js==

 const http = require('http');

 const hostname = '127.0.0.1';
 const port = 1337;

 http.createServer((req, res) => {
   res.writeHead(200, { 'Content-Type': 'text/plain' });
   res.end('Hello World\n');
 }).listen(port, hostname, () => {
   console.log(`Server running at http://${hostname}:${port}/`);
 });

 ================

 2-2. Run command prompt

 2-3. Change directory to directory where example.js exists

 2-4. execution command [node example.js]

 2-5. Run Internet Browser at [http://127.0.0.1:1337/]

*****example*******

**Comment by hanzgit** [comment]
I usually use windows7 and have never use node.js in any platform.
In this time I start to use node.js.

For the first time, I tried to install node.js on windwos7
and feel hard to know how to check operation after installation.

I estimate to be described about operation check at
 node.js HP(https://nodejs.org/en/)
  ->[DOWNLOADS](https://nodejs.org/en/download/)
  ->[Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/)
  ->[Windows](https://nodejs.org/en/download/package-manager/#windows)
(but I counldn't find descrption.)  

Through ohter engineer's blog,
I know to be described about operation check at [ABOUT](https://nodejs.org/en/about/)
and feel better to be described at that place([DOWNLOADS]->[Installing Node.js via package manager]->[Windows]).

In addition I feel better to be described about execution command(node filename.js).

*****example*******

(Add describe Under [DOWNLOADS]->[Installing Node.js via package manager]->[Windows] ((https://nodejs.org/en/download/package-manager/#windows)))

 Windows

 1.Simply download the Windows Installer directly from the nodejs.org web site.

 2. Check operation

 2-1. Create example.js.

 ==example.js==

 const http = require('http');

 const hostname = '127.0.0.1';
 const port = 1337;

 http.createServer((req, res) => {
   res.writeHead(200, { 'Content-Type': 'text/plain' });
   res.end('Hello World\n');
 }).listen(port, hostname, () => {
   console.log(`Server running at http://${hostname}:${port}/`);
 });

 ================

 2-2. Run command prompt

 2-3. Change directory to directory where example.js exists

 2-4. execution command [node example.js]

 2-5. Run Internet Browser at [http://127.0.0.1:1337/]

*****example*******

**Comment by hanzgit** [comment]
「3.適切な場所に報告」しました。
https://github.com/nodejs/nodejs.org/issues/495

Issuesの投稿ルールがあるかを確認しましたが、なさそうだったのでそのまま奉公しました。

**Comment by hanzgit** [comment]
ユーザーとしての貢献はひとまず試行できたので、開発者としてを試行できるようにする

**Comment by hanzgit** [comment]
パッケージではなく、開発用にソースをインストールする

**Comment by hanzgit** [comment]
ソースをダウンロードしたがビルド方法のドキュメントが見つからない
https://nodejs.org/dist/v4.2.6/node-v4.2.6.tar.gz

**Comment by hanzgit** [comment]
node.jsを利用する人用のソースとnode.js自体を開発している人用のソースは別に管理されていることを知る
https://github.com/nodejs/node/blob/master/README.md

**Comment by hanzgit** [comment]
どのプラットフォームでビルドしてみるか考える

**Comment by hanzgit** [comment]
centosでビルドを試す

**Comment by hanzgit** [comment]
minimal installしたため、networkが有効化されていないので変更する

**Comment by hanzgit** [comment]
以下のページを参考
http://futurismo.biz/archives/1340

**Comment by hanzgit** [comment]
network有効化完了

**Comment by kou** [comment]
おつかれさまでした！

**Comment by satoryu** [comment]
ドキュメントに確認方法が追加されましたね！ nodejs/nodejs.org#1308 🎉 
Issueを作ったことで、後からそれを見つけた方が直してくださったようです。
