### ISSUE TITLE
3月28(木)-29(金)に東京で夜にワークショップをやる準備をする

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1111]
## やること

- 会場: 永和システムマネジメントさん
- 時間: 19:30-21:30
- 内容: 2日間に分けてワークショップをやる
- 会場係: @swamp09 さん
- 進行役: @swamp09 さん
- このイベントに関する窓口: @knokmki612
- [x] Doorkeeperのイベント作成(2/28までにやる): @knokmki612
- メッセージ作成: @knokmki612
  - [ ] 会場案内(3/21までにやる): @knokmki612 
  - [x] サポーター募集(必要に応じて)(3/14までにやる): @knokmki612

## 気になっていること

- 作成するイベントの数は1？2？
  - [fukuoka](https://oss-gate-fukuoka.connpass.com/event/111602/)を参考にすると2日分のスケジュールを書いて、イベントは1つで良い気がしてきた
- [短縮版のスライド](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario-short.rab)の使い方やakatsukiのワークショップの様子について: @piroor さんにきいてみる

**Comment by knokmki612** [comment]
タイムテーブル

以前の東京ミートアップのものが参考になる
https://oss-gate.doorkeeper.jp/events/55608

**Comment by knokmki612** [comment]
イベントを作った(まだ公開はしていない) https://manage.doorkeeper.jp/groups/oss-gate/events/88180

- タイムテーブルを変更する必要がありそう
- イベント名は「東京ワークショップ」でいいんだろうか、少し変えたほうがいい気もするのでちょっと変えてみた

@swamp09 対象にするOSSを事前にアンケートで書いてもらうのやってみます？

**Comment by swamp09** [comment]
@knokmki612 いいですね、アンケートに書いてもらいましょう。 :+1:

**Comment by knokmki612** [comment]
@swamp09 アンケートの設問を調整してイベント公開しました！

タイムテーブルを自分の判断で書いてみました。現状1日目にフィードバックの方法まで説明する構成にしていますが、進行役をするswamp09さんが良いと思う構成があれば変えていただきたいです！

**Comment by knokmki612** [comment]
参加者募集のメッセージをDoorkeeperで送信しました！

**Comment by knokmki612** [comment]
キャンセル待ち1人だったので、ビギナー1人増枠しました！
