### ISSUE TITLE
OSS Gate Workshop: akatsuki: 2019-02-25: s-luna qmk/qmk_firmware: Work log

### ISSUE THREAD

**Issue by s-luna** [oss-gate/workshop#1115]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by s-luna** [comment]
github https://github.com/qmk/qmk_firmware
webSite https://qmk.fm/
以下でライセンスを確認した。
https://github.com/qmk/qmk_firmware/blob/master/LICENSE

**Comment by s-luna** [comment]
https://github.com/qmk/qmk_firmware/blob/master/readme.md
Documentationからhttps://docs.qmk.fm/#/へ
メニューよりComplete Newbs Guide -> GettingStarted

**Comment by s-luna** [comment]
メニュー -> QMK Basick -> How to Use Github なるものがあった
https://docs.qmk.fm/#/getting_started_github

**Comment by s-luna** [comment]
https://github.com/qmk/qmk_firmware -> fork -> clone
```
& git clone git@github.com:s-luna/qmk_firmware.git
```

**Comment by s-luna** [comment]
And be sure to select "HTTPS", and select the link and copy it:
とありました
```
$ git clone https://github.com/s-luna/qmk_firmware.git
```

**Comment by s-luna** [comment]
https://docs.qmk.fm/#/newbs_getting_started -> set up qmk
ビルド環境をテストするコマンド
```
$ util/qmk_install.sh
```
必要なソフトウェアがあった場合同時にインストールしてくれる模様

**Comment by s-luna** [comment]
brewで必要なソフトウェアのインストールが走るが、とても長い osx-cross/avr/avr-gcc@7

**Comment by s-luna** [comment]
```
$ util/qmk_install.sh
......

==> Installing osx-cross/avr/avr-gcc@7
==> Downloading https://gcc.gnu.org/pub/gcc/releases/gcc-7.3.0/gcc-7.3.0.tar.xz
######################################################################## 100.0%
==> Patching
patching file gcc/graphite.h
==> ../configure --target=avr --prefix=/usr/local/Cellar/avr-gcc@7/7.3.0 --libdir=/usr/local/Cellar/avr-gcc@7/7.3.0/lib/avr-gcc/7 --enable-languages=c,c++ --with-ld=/usr/local/opt/avr-binutils/bin/avr-ld --with-as=/usr/local/opt/avr-binut
==> make
==> make install
==> Downloading https://download.savannah.gnu.org/releases/avr-libc/avr-libc-2.0.0.tar.bz2
==> Downloading from https://quantum-mirror.hu/mirrors/pub/gnusavannah/avr-libc/avr-libc-2.0.0.tar.bz2
######################################################################## 100.0%
==> ./configure --build=i686-apple-darwin18.2.0 --prefix=/usr/local/Cellar/avr-gcc@7/7.3.0 --host=avr
==> make install
==> Caveats
avr-gcc@7 is keg-only, which means it was not symlinked into /usr/local,
because it might interfere with other version of avr-gcc. This is useful if you want to have multiple version of avr-gcc installed on the same machine.

If you need to have avr-gcc@7 first in your PATH run:
  echo 'export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"' >> ~/.bash_profile

For compilers to find avr-gcc@7 you may need to set:
  export LDFLAGS="-L/usr/local/opt/avr-gcc@7/lib"

==> Summary
🍺  /usr/local/Cellar/avr-gcc@7/7.3.0: 1,682 files, 175.2MB, built in 22 minutes 46 seconds
==> Installing gcc-arm-none-eabi from px4/px4
==> Downloading https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-mac.tar.bz2
######################################################################## 100.0%
==> Copying binaries...
🍺  /usr/local/Cellar/gcc-arm-none-eabi/20180627: 5,658 files, 467.4MB, built in 2 minutes 58 seconds
......
==> Installing avrdude
==> Downloading https://homebrew.bintray.com/bottles/avrdude-6.3_1.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring avrdude-6.3_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/avrdude/6.3_1: 14 files, 1.9MB
==> Downloading https://homebrew.bintray.com/bottles/dfu-util-0.9.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring dfu-util-0.9.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/dfu-util/0.9: 11 files, 115.7KB
==> Caveats
==> avr-gcc@7
avr-gcc@7 is keg-only, which means it was not symlinked into /usr/local,
because it might interfere with other version of avr-gcc. This is useful if you want to have multiple version of avr-gcc installed on the same machine.

If you need to have avr-gcc@7 first in your PATH run:
  echo 'export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"' >> ~/.bash_profile

For compilers to find avr-gcc@7 you may need to set:
  export LDFLAGS="-L/usr/local/opt/avr-gcc@7/lib"

Linking /usr/local/Cellar/avr-gcc@7/7.3.0... 20 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"' >> ~/.bash_profile

```
上記を実行中にbrewにてインストールされたソフトウェアからパスの設定のログがいくつか出たので設定する
zshを利用しているので.zshrcに書き込む
```
echo 'export PATH="/usr/local/opt/avr-gcc@7/bin:$PATH"' >> ~/.zshrc
```

**Comment by s-luna** [comment]
.zshrcを再読み込みする(公式に記述なしだが必須だと判断
```
$ source ~/.zshrc
```

**Comment by s-luna** [comment]
osをビルドする
手持ちのキーボードがhelixなのでhelixを選択
```
$ make helix:default
```

**Comment by s-luna** [comment]
gccのパスを追加する必要がなかった

**Comment by s-luna** [comment]
再現手順
OSX Version 10.14.3
https://docs.qmk.fm/#/newbs_getting_started
上記に通りに実行
```
$ util/qmk_install.shd
```
で多くの時間を必要とした
多くの時間を必要とする可能性があるとこが明示されているとよい

**Comment by s-luna** [comment]
再現手順
https://github.com/qmk/qmk_firmware/blob/15a73f4f64a3b2b109e63cf1eeb37c9875c3d870/readme.md
においてDocumentationの修正を提案しようとGitbookにアクセスしたところ404が返ってくる
期待される結果
リンク切れなのか運用されていないのかを明確にし、それに伴った説明に変更される

**Comment by s-luna** [comment]
title
Gitbook page is missing.

message
'gitbook' in 'readme.md' is 404 not found for me.
The referenced document  looks disappeared. 
Is the document alive?

**Comment by s-luna** [comment]
↑Issue出しました
https://github.com/qmk/qmk_firmware/issues/5240

**Comment by piroor** [comment]
初フィードバックおめでとうございます！
