### ISSUE TITLE
OSS Gate Workshop: tokyo: 2019-03-09: solatch: vue: Work log

### ISSUE THREAD

**Issue by solatch** [oss-gate/workshop#1123]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nkgwnoto** [comment]
今日はよろしくお願いします！

**Comment by solatch** [comment]
公式サイトのガイドを開く
https://jp.vuejs.org/v2/guide/
JSFiddle Hello World example を開く
https://jsfiddle.net/chrisvfritz/50wL7mdz/

**Comment by solatch** [comment]
すでにコードが入力されてるけど、これ書き替えるのかな。とりあえず書き換えてみる。

**Comment by solatch** [comment]
jsfiddleに入力内容ってリアルタイムで反映されるんだっけ？あれ？
保存しないと駄目だっけ？

**Comment by solatch** [comment]
左上のRunを押すと反映される

**Comment by solatch** [comment]
引き続きドキュメントを読む

**Comment by solatch** [comment]
Scrimbaでもオンラインで試せるっぽいけど、今回はこのままjsfiddleを使う

**Comment by solatch** [comment]
HTMLに以下を記載
```
<div id="app">
  {{ message }}
</div>
```
jsに以下を記載
```
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
```
Runして、指定した文字列が画面に表示されることを確認

**Comment by solatch** [comment]
messageの値を変えてみて、結果が変わることを確認

**Comment by solatch** [comment]
v-bindのサンプルコードを追加
HTML
```
<div id="app-2">
  <span v-bind:title="message">
    Hover your mouse over me for a few seconds
    to see my dynamically bound title!
  </span>
</div>
```
js
```
var app2 = new Vue({
  el: '#app-2',
  data: {
    message: 'You loaded this page on ' + new Date().toLocaleString()
  }
})
```
Run実行後、マウスオーバーで表示される時刻文字列がリロードごとに変化することを確認

**Comment by solatch** [comment]
vueオブジェクトのmessageの値を変えて、マウスオーバー時のメッセージが変わるのを確認

**Comment by solatch** [comment]
v-if属性のサンプルコードを追加
HTML
```
<div id="app-3">
  <span v-if="seen">Now you see me</span>
</div>
```
js
```
var app3 = new Vue({
  el: '#app-3',
  data: {
    seen: true
  }
})
```
Runして"Now you see me"メッセージが表示されることを確認
→app3.data.seenをfalseにする
　→Runして上記メッセージが表示されなくなることを確認

**Comment by solatch** [comment]
v-ifがfalseの時には、DOM上はどうなっているのか、実行ビューのソースを確認
→spanタグ自体がDOMに存在しない
```
<div id="app-3"><!----></div>
```

**Comment by solatch** [comment]
v-for属性のサンプルコードを追加
HTML
```
<div id="app-4">
  <ol>
    <li v-for="todo in todos">
      {{ todo.text }}
    </li>
  </ol>
</div>
```
js
```
var app4 = new Vue({
  el: '#app-4',
  data: {
    todos: [
      { text: 'Learn JavaScript' },
      { text: 'Learn Vue' },
      { text: 'Build something awesome' }
    ]
  }
})
```
Runを押して、指定した文字列リストが番号付き箇条書きで描画されることを確認

**Comment by solatch** [comment]
F12で開発者ツールを開いたらコンソールにエラーが出ていた
```
_dist-editor.js?update_05_03_2019_1:1 
Uncaught TypeError: Cannot read property 'bind' of undefined
    at Object.<anonymous> (_dist-editor.js?update_05_03_2019_1:1)
    at Array.forEach (<anonymous>)
    at Function.forEach (_dist-editor.js?update_05_03_2019_1:1)
    at Array.each (_dist-editor.js?update_05_03_2019_1:1)
    at Object.routeReservedKey (_dist-editor.js?update_05_03_2019_1:1)
    at Object.<anonymous> (_dist-editor.js?update_05_03_2019_1:1)
    at _dist-editor.js?update_05_03_2019_1:1
    at a (_dist-editor.js?update_05_03_2019_1:1)
```
editorとあるので、おそらくjsfiddleのエラーか？
bindという単語があるので、ちょっと関連があるのかもしれないが…
もう少し読んでみる

**Comment by solatch** [comment]
エラーメッセージのファイルリンクを開き、pretty printでコードを見やすく表示
やはりjsfiddleのエラーっぽいので、ひとまずサンプルに戻る

**Comment by solatch** [comment]
何やろうとしてたんだっけ…
思い出した。開発者ツールのコンソールで`app4.todos.push({ text: 'New item' })`と入力
→エラーが出た。あー確か最初に宣言が必要だった気がする。
```
VM258:1 Uncaught ReferenceError: app4 is not defined
    at <anonymous>:1:1
```

**Comment by solatch** [comment]
コンソールからjsfiddleのオブジェクトにアクセスするための宣言をぐぐってみる
`jsfiddle  chrone developer console`
→コンソールメニューのcontextを"result (fiddle.jshell.net)"を指定すればよい？
https://stackoverflow.com/questions/5655058/inspecting-javascript-on-jsfiddle-net-in-google-chrome
試してみたけどエラーが解消されず

**Comment by solatch** [comment]
HTML上はハイフン付きのidだということに気付いたので、コンソールに`app-4`と入力
→NaNと出た。想定と違うな。
ダメ元で`app-4.todos.push({ text: 'New item' })`と入力してみるもエラー。ですよねー
```
Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by solatch** [comment]
上記URLの書き込みにあった`debugger;`という一文をコンソールに記入してみた。
ら、sourceタブでデバッグウインドウらしきものが起動してしまった。
デバッグで止めたいわけではないので、たぶんこれは違う。

**Comment by solatch** [comment]
そういえば、さっきは直接jsfiddleを変更していたが、よくドキュメントを読み直すと
「ブラウザのJavaScriptコンソールを開いて」と書いてある。
app.messageの値を変えるところから、コンソールでやり直してみる。
`app.message`と入力してEnter -> 'undefined'と出てしまった。あれー

**Comment by solatch** [comment]
このドキュメントでは、サンプルコードの確認手段として
1. jsfiddleを使って確認
1. ローカル環境にindex.htmlを作ってブラウザで確認
1.  Scrimbaを使って確認

の3種類が提示されている。
「ブラウザのJavaScriptコンソールを開いて、値に変更を加える」という確認手段が、
jsfiddleを使った方式では使えない可能性がある？

**Comment by solatch** [comment]
ConsoleのContextをresultにしたときにのみ、`app.message`が`undefined`になる
（それ以外の時は`ncaught ReferenceError: app is not defined`）
ので、おそらくは微妙に参照の仕方が違うのでないか？
xxx.app.messageとか、app.xxx.messageとかならできるのかもしれない？

**Comment by solatch** [comment]
Contextをresultにして`app`と入力してみると
```
<div id="app">
   OSS Gate Tokyo 20190309
</div>
```
と出る。typeofはobject。divエレメントと思われる。
このオブジェクトには、message部分がHTMLに展開されたあとの文字列が格納されている。
つまり、messageという属性をこのオブジェクトは知らないのではないか？
→では、vueインスタンス（同じくappという名前）はどうやって参照するのか？

**Comment by solatch** [comment]
thisオブジェクトの中にいるかもしれないと思って覗いてみたが、トップレベル階層には
それらしきものは見当たらず。
Vueというオブジェクトはあったが、そこにも見当たらなかった。うーん？？

**Comment by solatch** [comment]
フィードバックポイント：
・jsfiddleでチュートリアルを実行したときに、コンソールから値に変更をできるのかどうか不明
・そもそも「コンソール」とは何か？
・「ブラウザのJavaScriptコンソール」ってのは何を指すのかわかりづらい

**Comment by solatch** [comment]
先に、フィードバックの窓口がどこにあるのか調査してみる。

フォーラム
https://forum.vuejs.org/
→日本語で質問できる部屋があるらしい。まずはここで投稿してみようか

チャット（公式）
https://discordapp.com/invite/HBherRA

チャット（日本語向け）
https://vuejs-jp-slackin.herokuapp.com/

**Comment by solatch** [comment]
サポーターさんより
```
jsfiddleにおいての「JavaScriptコンソール」＝左下のJavaScript領域である
```
と教えていただいた。納得いかない。

**Comment by solatch** [comment]
上記を踏まえて、文章を考えてみる。

・環境
Windows10 Pro 64bit
ブラウザ：Google Chrome  72.0.3626.121

・やったこと

公式サイトのガイドの内容をもとに、チュートリアルを実施した。
https://jp.vuejs.org/v2/guide/
エディターは JSFiddle Hello World example を利用した。
https://jsfiddle.net/chrisvfritz/50wL7mdz/

「条件分岐とループ」の章のサンプルコードをJSFiddleに追加
HTML
```
<div id="app-4">
  <ol>
    <li v-for="todo in todos">
      {{ todo.text }}
    </li>
  </ol>
</div>
```
js
```
var app4 = new Vue({
  el: '#app-4',
  data: {
    todos: [
      { text: 'Learn JavaScript' },
      { text: 'Learn Vue' },
      { text: 'Build something awesome' }
    ]
  }
})
```
Runを押して、指定した文字列リストが番号付き箇条書きで描画されることを確認

Chromeの開発者メニューを開き、Consoleタブを選択
JavaScript Contextで「result (fiddle.jshell.net)」を選択して、以下の一文を入力
```
app4.todos.push({ text: 'New item' })
```
すると、コンソールに以下のエラーが出力された。
```
VM258:1 Uncaught ReferenceError: app4 is not defined
    at <anonymous>:1:1
```

・やっていないこと

ローカル環境にindex.htmlを作成してチュートリアルを実施
Scrimbaのレッスンを受けながらチュートリアルを実施

・期待していた内容

コンソールで以下の一文を入力すると、JSFiddleの実行画面が以下のようになる
```
app4.todos.push({ text: 'New item' })
```
実行画面：
```
1. Learn JavaScript
2. Learn Vue
3. Build something awesome
4. New item    <--- これが追加される
```

・困っていること

**Comment by solatch** [comment]
投げる内容は整理できた。
次に、公式フォーラムに、似たような内容が投稿されていないか探してみる。
→なさそう。

そもそも、改善してほしいポイントがはっきりしているので、質問ではなくissueのほうがよいか？

**Comment by solatch** [comment]
サポーターさんに、Vue.jsのドキュメントに関するリポジトリは以下だと教えていただいた。
https://github.com/vuejs/vuejs.org

ここのissueに要望を投げれば、対応してもらえるかもしれない。

**Comment by solatch** [comment]
ガイドの元ドキュメントと思われるmarkdownファイルを発見した。
https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/index.md

日本語訳がおかしいのか、そもそもの原文のニュアンスがおかしいのか確認する。
```
Open your browser's JavaScript console...
```
うーん、原文レベルからブラウザの開発者ツールというニュアンスになってるな。

**Comment by solatch** [comment]
このファイルの更新履歴をのぞいてみた。
https://github.com/vuejs/vuejs.org/commits/master/src/v2/guide/index.md

リンク切れの修正、タグの変更などの軽微なレベルの更新も行われているので、今回のような
記載の明確化要望も通してもらえそうな雰囲気。

**Comment by solatch** [comment]
上で書いた内容は詳細すぎて長いので、大事なところを保ちつつ以下の内容に凝縮する。

1. やりたかったこと
2. 困ったこと
3. こうしたらいいのではないか

**Comment by solatch** [comment]
ドキュメントの「Getting Started」の内容を、JSFiddleで実行しようとした。
https://jp.vuejs.org/v2/guide/

「Conditionals and Loops」の章で、「In the console, enter app4.todos.push({ text: 'New item' }). You should see a new item appended to the list.」と記載されていたので、以下を実行した。
- Chromeの開発者メニューを開き、Consoleタブを選択
- JavaScript Contextで「result (fiddle.jshell.net)」を選択
- `app4.todos.push({ text: 'New item' })`と入力

実行すると、コンソールに以下のエラーが出力された。
```
VM258:1 Uncaught ReferenceError: app4 is not defined
    at <anonymous>:1:1
```

「your browser's JavaScript console」が指す内容を、実行環境ごとに明示したほうがいいのではないか？
-  JSFiddleの場合は画面内のJS入力領域のこと
- ローカル環境で実行する場合はブラウザの開発者ツール内のConsoleタブのこと

**Comment by solatch** [comment]
I executed the contents of "Getting Started" of guide document by using JSFiddle. 
(Browser: Google Chrome)
https://jp.vuejs.org/v2/guide/

In "Conditionals and Loops" section, it was written as 

> In the console, enter app4.todos.push({ text: 'New item' }). You should see a new item appended to the list.

So I did the following steps; 
1. Open the Chrome DevTools, show Console tab
1. input `app4.todos.push({ text: 'New item' })`

Then I saw the following error: 
```
VM258:1 Uncaught ReferenceError: app4 is not defined
    at <anonymous>:1:1
```

**Comment by solatch** [comment]
投★稿
https://github.com/vuejs/vuejs.org/issues/2052
