### ISSUE TITLE
    OSS Gate Workshop: Tokyo: 2019-3-9: k-neda: angular: Work log

### ISSUE THREAD

**Issue by k-neda** [oss-gate/workshop#1127]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by t-msn** [comment]
よろしくお願いします

**Comment by k-neda** [comment]
angularでググるとトップに日本語ドキュメントのページがあった
https://angular.jp/

**Comment by k-neda** [comment]
はじめるをクリックすると入門ページに遷移した

**Comment by k-neda** [comment]
node.jsがインストール済みなことを確認した。
コマンドラインで
node -v
とうってバージョン情報が表示されることを確認した

**Comment by k-neda** [comment]
npm -v
でnpmがインストール済みなのを確認した。

**Comment by k-neda** [comment]
ステップ 1を読んで、Angular CLIをインストールすることにした
(Angula Cliが何なのかを説明した上で、インストールするべきだが、ちょっと翻訳が硬い気がした)

**Comment by k-neda** [comment]
npm install -g @angular/cli

をコマンドラインから入力した。
インストールは正常に行われた。

**Comment by k-neda** [comment]
ステップ 2を読んで

ng new my-app

コマンドをコマンドラインから入力した。

**Comment by k-neda** [comment]
いくつか質問されたが、ドキュメントにしたがってenterを押した。

**Comment by k-neda** [comment]
ステップ 3を読んで
cd my-app
ng serve --open
と入力した。

**Comment by k-neda** [comment]
Welcome to my-app!
のページが開かれた。

**Comment by k-neda** [comment]
ステップ 4をみて
./src/app/app.component.ts
を開いて

my-appをMy First Angular App!に変更した

**Comment by k-neda** [comment]
http://localhost:4200/の変更を確認した。

**Comment by k-neda** [comment]
ドキュメントにしたがって./src/app/app.component.cssを開いた

**Comment by k-neda** [comment]
./src/app/app.component.cssにドキュメントに書かれたスタイルを書き写した。

**Comment by k-neda** [comment]
スタイルが変更されているのを確認した。

**Comment by k-neda** [comment]
チュートリアルのネクストステップから、さらなるチュートリアルとアーキテクチャガイドへのリンクを確認した

**Comment by k-neda** [comment]
（日本語のTour of Heroesチュートリアルの下にあるリストはインデントが崩れている？）

**Comment by k-neda** [comment]
アーキテクチャの方のリンクを開いて
https://angular.jp/guide/architecture
へと飛んだ

**Comment by k-neda** [comment]
（アーキテクチャ概要のリンクテキストははじめにと違って水色のリンクとしてハイライトされていない？）

**Comment by k-neda** [comment]
ハイライトされている部分とされていない部分が混在している？

**Comment by y-goto** [comment]
おつかれさまでした！

後日引き続きワークショップがある場合
---

後日のワークショップで再開する際に、issueタイトルの日付を更新してreopenしてください！

ワークショップ終了後に続きがしたい場合
---

issueはクローズしますが、その後も作業を続けていただいて大丈夫です！

是非このissueを活用なさってください。

今後のイベントの案内
---

現在以下のイベントの開催を予定しています。

  - [OSS Gate東京ワークショップ2019-06-08](https:&#x2F;&#x2F;oss-gate.doorkeeper.jp&#x2F;events&#x2F;86159)
  - [OSS Gate東京ワークショップ2019-04-27](https:&#x2F;&#x2F;oss-gate.doorkeeper.jp&#x2F;events&#x2F;86158)

参加をお待ちしてます！
