### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-03-09: junyanakada: Pelican: Work log

### ISSUE THREAD

**Issue by junyanakada** [oss-gate/workshop#1128]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by t-msn** [comment]
よろしくお願いします

**Comment by junyanakada** [comment]
公式サイト探します。

**Comment by junyanakada** [comment]
pelican python で Google 検索したら出てきました。
https://docs.getpelican.com/en/stable/

GitHub のリンクはサイトの右上にあります。

**Comment by junyanakada** [comment]
ライセンス確認します。(さっきしましたけど)

**Comment by junyanakada** [comment]
GNU Affero General Public License v3.0 でした。
https://github.com/getpelican/pelican/blob/24d6efa9fda4ad45649ddf88c1c596193d589bf8/LICENSE

https://opensource.org/licenses/alphabetical にもあがっているライセンスです。

**Comment by junyanakada** [comment]
ドキュメントの方の Quickstart の手順で動かしてみます。

**Comment by junyanakada** [comment]
でも一応GitHubでREADME も見ておきます。

**Comment by junyanakada** [comment]
README にはインストールについては書いてませんでした。

**Comment by junyanakada** [comment]
Quickstart 手順で始めます。

まず

pip install pelican markdown

**Comment by junyanakada** [comment]
インストールはされたみたいです。

Successfully installed MarkupSafe-1.1.1 blinker-1.4 docutils-0.14 feedgenerator-1.9 jinja2-2.10 markdown-3.0.1 pelican-4.0.1 pygments-2.3.1 python-dateutil-2.8.0 pytz-2018.9 six-1.12.0 unidecode-1.0.23

**Comment by junyanakada** [comment]
pelican-quickstart をやったら色々ファイルができました。

**Comment by junyanakada** [comment]
途中でFTPでアップロードするか？とかS3で？とか質問がありましたが、デフォルトがNOで全部そのままにしました。

**Comment by junyanakada** [comment]
サンプルの article までつくって、これから動かします。
pelican content

**Comment by junyanakada** [comment]
HTML はできたみたいです。

Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.09 seconds.

**Comment by junyanakada** [comment]
output の中にファイルできてます。

**Comment by junyanakada** [comment]
pelican --listen

http://localhost:8000/ にアクセスして表示できました。

**Comment by junyanakada** [comment]
Footnote のところにある tzlocal もためしてみます。

**Comment by junyanakada** [comment]
pelican-quickstart の質問でこんな感じでデフォルトの値が東京になりました。

> What is your time zone? [Asia/Tokyo]

もともとは、

> What is your time zone? [Europe/Paris]

**Comment by t-msn** [comment]
tzlocalがインストールされていれば自動で読み込んでくれそう
https://github.com/getpelican/pelican/commit/c1a5279da9863fdfacade8654437d9d7b73f6b13

**Comment by junyanakada** [comment]
全部デフォルトにするとどうなる？
タイムゾーンは？

**Comment by junyanakada** [comment]
できあがったサイトの記事の日付のところにマウスをもっていくと、ポップアップみたいなやつが出て、 2010-12-03T10:20:00+01:00 になりました。
東京にしたときは  2010-12-03T10:20:00+09:00 でした。

**Comment by junyanakada** [comment]
author を 中田 にしたら作者のページのURLが
http://localhost:8000/author/zhong-tian.html
でした。 中田 を中国語とかでよむと zhong-tian なんですかね。

**Comment by junyanakada** [comment]
個人的にはURLに日本語が入るの気持ち悪いのでありがたいですが、そのまま 中田 をurl に入れられたりはできるのかな？

**Comment by junyanakada** [comment]
とりあえず Settings のところ眺めてみます。
https://docs.getpelican.com/en/stable/settings.html

**Comment by junyanakada** [comment]
そういえばそもそも日本語ドキュメントある？

**Comment by junyanakada** [comment]
https://docs.getpelican.com/ja/stable/settings.html
ここには日本語ドキュメントはないですね。

**Comment by junyanakada** [comment]
フィードバックについてはここに書いてあるみたいです。
https://docs.getpelican.com/en/stable/faq.html
たまたま見つけたのでメモ。

**Comment by junyanakada** [comment]
もしかすると author だけでなくて 記事タイトルみたいなのも漢字をつかうと中国語（？）読みを英字に転写したような URL になるのかな？

**Comment by junyanakada** [comment]
記事のファイルを変えたら
~~~
Title: My First Review 中田です。
~~~

URL は `http://localhost:8000/my-first-review-zhong-tian-desu.html` になりました。
author だけではないことみたいです。

**Comment by junyanakada** [comment]
選択肢として、URL にマルチバイトの文字を使うことができるのか？を調べています。

**Comment by junyanakada** [comment]
Settings のところには設定が見当たりませんでした。
URL にマルチバイト文字をそのままつかう設定ができないの？と言う質問をするかたちにしたいと思います。

**Comment by junyanakada** [comment]
https://docs.getpelican.com/en/stable/contribute.html
Contributing and feedback guidelines

**Comment by junyanakada** [comment]
似たようなところの issue
https://github.com/getpelican/pelican/issues/1951

**Comment by junyanakada** [comment]
このへんも？
https://github.com/getpelican/pelican/issues/1172

**Comment by junyanakada** [comment]
http://localhost:8000/category/nihon.html を
http://localhost:8000/category/%E6%97%A5%E6%9C%AC.html にする設定はないのか？
という話。

**Comment by junyanakada** [comment]
~~~
$ pelican --version
4.0.1
~~~

**Comment by junyanakada** [comment]
`pip install pelican markdown` でインストール。

**Comment by junyanakada** [comment]
私としては例えば、

記事を書くときにカテゴリを日本としたときに
http://localhost:8000/category/nihon.html  となって問題ない。
気になるなら記事をかくときに japan にする。
名前も中国語風が気になるなら nakada にする。

記事を書くときにカテゴリを日本としたときに
http://localhost:8000/category/%E6%97%A5%E6%9C%AC.html になったら直してくれと要求すると思う。

選択肢として、できないか？という話。

**Comment by junyanakada** [comment]
記事ファイルのタイトルをこのようにすると、
```
Title: 中田です。
```

URL が `http://localhost:8000/zhong-tian-desu.html` になる。

`http://localhost:8000/%e4%b8%ad%e7%94%b0%e3%81%a7%e3%81%99%e3%80%82.html` にできる方法はないのか？
