### ISSUE TITLE
「サポートメンター」の正式名称を決める

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#113]
次回開催（9月24日）までには決めたい。

現時点での候補は次の通り。

  * メタメンター
  * メンターメンター
  * ジェネラルメンター・ジェネメン
  * サーヴァントメンター
  * コアメンター
  * オーガナイザー
  * リードメンター

どうやったら決まるのか？から決めないとダメ？そういうのを決めなくても決まる？

**Comment by knokmki612** [comment]
サポートメンターで十分意味が伝わったのでサポートメンターでいいんじゃないかというのと、以前の名前出しの中ではコアメンターが良かったかなと思います。

**Comment by sezemiadmin** [comment]
同じくサポートメンターで良いと思います!!

**Comment by ttwo32** [comment]
私もサポートメンターで良いと思います。:+1:

**Comment by y-goto** [comment]
私もサポートメンターに一票

**Comment by kou** [comment]
では、サポートメンターにしましょうか。
