### ISSUE TITLE
tokyo: 2019-03-09: meixang: prettier: Work log

### ISSUE THREAD

**Issue by meixang** [oss-gate/workshop#1130]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by meixang** [comment]
prettierをやろうと思ったけど今準備できている環境で動かせるPython extension for Visual Studio Codeに対象を変更

**Comment by meixang** [comment]
VS Code を立ち上げて、ExtensionsからPythonを選択。
使い方を調べるためにQuick startを読みはじめる。
Step 1. Install a supported version of Python on your system
まずはPythonをインストールしないといけない。

**Comment by meixang** [comment]
インストールガイド
https://code.visualstudio.com/docs/python/python-tutorial#_prerequisites

python.orgにアクセスする
Python3.7.2のインストーラを実行　Pathを通す

**Comment by meixang** [comment]
Step 2. Install the Python extension for Visual Studio Code.
インストールボタン押すだけ

**Comment by meixang** [comment]
Step 3. Open or create a Python file and start coding!
とりあえず簡単なコードを書いてみる　test.pyファイルを作成

**Comment by meixang** [comment]
実行してみると　警告がでてきた。linter がないですよ。
Optionalの手順にこんなのがあるの気づく。
Step 4. Install a linter to get errors and warnings -- you can further customize linting rules to fit your needs.

VS Code からインストールするか聞かれて、Yesを選択。
インストールできてからもう一度test.pyを実行したら動作することを確認

**Comment by meixang** [comment]
でも今の手順で何したのかイマイチ理解できてなかった。けど動いたからいいやっていうパターン。
ここはポイントなのかな?

**Comment by meixang** [comment]
Install a linter の部分のリンク先を読んでみる。
https://code.visualstudio.com/docs/python/linting

**Comment by meixang** [comment]
Linterって何をしてくれるものなのか？？
コードのエラーを教えてくれるもの。フォーマットを整えるのとは違う。

**Comment by meixang** [comment]
Enable lintersの項で open the Command Palette (Ctrl+Shift+P)の記述を見つける。
コマンドで簡単にON/OFFできるとか、コマンドはこれっていう記述が他にもあったけど使い方がわからなかったのでようやく解決。

**Comment by meixang** [comment]
コマンドに関する記述の時には常に open the Command Palette (Ctrl+Shift+P)が書いてあるくらいが初心者にとってわかりやすいかもしれない。

**Comment by y-goto** [comment]
おつかれさまでした！

後日引き続きワークショップがある場合
---

後日のワークショップで再開する際に、issueタイトルの日付を更新してreopenしてください！

ワークショップ終了後に続きがしたい場合
---

issueはクローズしますが、その後も作業を続けていただいて大丈夫です！

是非このissueを活用なさってください。

今後のイベントの案内
---

現在以下のイベントの開催を予定しています。

  - [OSS Gate東京ワークショップ2019-06-08](https:&#x2F;&#x2F;oss-gate.doorkeeper.jp&#x2F;events&#x2F;86159)
  - [OSS Gate東京ワークショップ2019-04-27](https:&#x2F;&#x2F;oss-gate.doorkeeper.jp&#x2F;events&#x2F;86158)

参加をお待ちしてます！
