### ISSUE TITLE
OSS Gate Workshop: Osaka: 2019-03-09: sceallog: iTerm2: Work log

### ISSUE THREAD

**Issue by sceallog** [oss-gate/workshop#1131]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sceallog** [comment]
iTermをターミナルの代わりに使ってみよう。
まずは、公式サイトへ

**Comment by sceallog** [comment]
iTermで探して見たら出た。
https://iterm2.com　にあった

**Comment by znz** [comment]
サポーターの西山です。
よろしくお願いします。

**Comment by sceallog** [comment]
宜しくお願いします

**Comment by sceallog** [comment]
ホームページの一番下にライセンスが書いてあった。
iTerm2 is licensed under GPL v2. これだそうだ。チェックしよう

**Comment by sceallog** [comment]
https://opensource.org/licenses/GPL-2.0 にライセンスがあったのでOSSだ

**Comment by sceallog** [comment]
既にインストール済みなので、直ぐにドキュメンテーション見よう

**Comment by sceallog** [comment]
https://iterm2.com/documentation.html にあった。
どうしてmacOSのターミナルよりiTerm使った方が良いか見てみよう。

**Comment by sceallog** [comment]
Highlights for New Usersというサイトがあった。まずはここからスタート！

**Comment by sceallog** [comment]
なるほど。ほとんど使い方や入力の仕方の改善だ。ほかには環境のインテグレーションにも改善されたところがあるようだ。

**Comment by sceallog** [comment]
ドキュメンテーションが完璧だ。全て説明などしてくれます。
