### ISSUE TITLE
OSS Gate Workshop: osaka: 2019-03-09: sleep510: Atom: Work log

### ISSUE THREAD

**Issue by sleep510** [oss-gate/workshop#1132]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by sleep510** [comment]
Atonがossライセンスかどうか調べる。

**Comment by sleep510** [comment]
https://atom.io/が公式のサイトっぽい。

**Comment by sleep510** [comment]
Atomのソースコードが見つかった。
https://github.com/atom/atom

**Comment by sleep510** [comment]
license.md にMIT Licenseと記載されていた。

**Comment by sleep510** [comment]
Atomのソースコードを確認した。
javascriptで出来てた。

**Comment by sleep510** [comment]
javascriptがなんの言語で出来ているか確認してみよう。

**Comment by sleep510** [comment]
Atomをセットアップする手順を確認してみよう。

**Comment by sleep510** [comment]
開発者向けのインストール手順見つけにくい。

**Comment by sleep510** [comment]
docsとはドキュメントらしい

**Comment by sleep510** [comment]
srcとはソースコードの略らしい。

**Comment by sleep510** [comment]
https://github.com/atom/atom/tree/master/docsにbuild documentationに開発者向けの手順があった

**Comment by sleep510** [comment]
forkすることで、オープンソースを自分の領域に取り込んで、コードを変えることができることらしい

**Comment by sleep510** [comment]
atomではフィードバックポイントが見つからなかったので別のossを探してみよう

**Comment by sleep510** [comment]
daemonツールがossかどうか確認してみよう。

**Comment by sleep510** [comment]
オープンソースとフリーソフトは違う

**Comment by sleep510** [comment]
daemonpツールはOSSぽくないかも

**Comment by sleep510** [comment]
bcryptがossかどうか確認てみよう

**Comment by sleep510** [comment]
bcryptのイントール手順を調べた。
コマンドでgem install bcryptと入力するらしい。

**Comment by sleep510** [comment]
bcryptをインストール出来ない

**Comment by sleep510** [comment]
xcodeが入っていないからか？
goto-no-MacBook-Air:~ goto$ gem install bcrypt
Building native extensions. This could take a while...
ERROR:  Error installing bcrypt:
	ERROR: Failed to build gem native extension.

    current directory: /Users/goto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bcrypt-3.1.12/ext/mri
/Users/goto/.rbenv/versions/2.5.0/bin/ruby -r ./siteconf20190309-64621-8n6bxb.rb extconf.rb
creating Makefile

current directory: /Users/goto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bcrypt-3.1.12/ext/mri
make "DESTDIR=" clean
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

current directory: /Users/goto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bcrypt-3.1.12/ext/mri
make "DESTDIR="
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

make failed, exit code 1

Gem files will remain installed in /Users/goto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bcrypt-3.1.12 for inspection.
Results logged to /Users/goto/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/bcrypt-3.1.12/gem_make.out
goto-no-MacBook-Air:~ goto$ C

**Comment by ogom** [comment]
bcrypt  は `xcode-select --install` のコマンドを実行する必要があるようです。

**Comment by sleep510** [comment]
README.mdの
An easy way to keep your users' passwords secure.の「users'」の「'」の位置おかしくないか

**Comment by sleep510** [comment]
bcryptはruby2.6にも対応しているようだがHow to install bcryptには以下のように記載してある。
JRuby
RubyInstaller 2.0 – 2.5 builds on Windows with the DevKit
Any 2.0 – 2.5 Ruby on a BSD/OS X/Linux system with a compiler

2.0-2.6に修正すべきではないか。

**Comment by ogom** [comment]
.travis.yml に `2.6` の記載がありますが、README.md には `Any 2.0 – 2.5 Ruby on a ...` の記載です。2.6 もサポート済みと思いますが、README.md に 2.6 もサポートも記載した方がよいとうに思えます。

There is a description of `2.6` in .travis.yml, but README.md states` Any 2.0 - 2.5 Ruby on a ... `. I think that 2.6 is also supported, but it seems that it would be better to include both 2.6 and support in README.md.

**Comment by sleep510** [comment]
タイトルはこんなものか
About the description of 'README.md'

**Comment by ogom** [comment]
タイトルあん

Available on the following Ruby platforms to 2.6 ?

**Comment by sleep510** [comment]
「issue」を初めて投稿しました。
https://github.com/codahale/bcrypt-ruby/issues/193
