### ISSUE TITLE
OSS Gate Workshop: osaka: 2019-03-09: sayfree: rumale: Work log

### ISSUE THREAD

**Issue by sayfree** [oss-gate/workshop#1133]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sayfree** [comment]
ライセンスファイルを確認 -> BSD 2-Clause "Simplified" License

OSS であることを確認
https://opensource.org/licenses/BSD-2-Clause\

**Comment by sayfree** [comment]
インストール
https://github.com/yoshoku/rumale/blob/master/README.md を参照
gem install rumale -> 成功

**Comment by kozo2** [comment]
サポーターの西田です

**Comment by sayfree** [comment]
よろしくおねがいします

**Comment by sayfree** [comment]
Rumale::Dataset.load_libsvm_file('pendigits') を実行
エラーは出なかった

**Comment by sayfree** [comment]
Example1 の
Training of the classifier with Linear SVM and RBF kernel feature map is the following code. の項を実行
transformer.dat と classifier.dat の2ファイルが作成される

**Comment by sayfree** [comment]
Classifying testing data with the trained classifier is the following code.　の項を実行
Accuracy: 98.4% の文字が表示される

**Comment by sayfree** [comment]
Example 2. Cross-validation を実行
5-CV mean log-loss: 0.476 が表示される

**Comment by sayfree** [comment]
Example 3. Pipeline を実行
5-CV mean accuracy: 99.2 % が表示される

**Comment by sayfree** [comment]
README.md のExample 1, 3 には実行結果が書かれているが
Example 2 には実行結果が書かれていない

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by sayfree** [comment]
よろしくおねがいします

**Comment by sayfree** [comment]
READMEにExample 1, 2, 3が書かれていて、そのうち 1, 3 には実行例/実行結果が記載されていますが 2 には記載されておらず、実行した結果との比較ができないため、以下を追記したほうが良いと思います

Execution of the above scripts result in the following.

$ ruby cross_validation.rb
5-CV mean log-loss: 0.476

**Comment by kozo2** [comment]
いいと思います。Pull Request を送るときは

~~~
Execution of the above scripts result in the following.

```
$ ruby cross_validation.rb
5-CV mean log-loss: 0.476
```
~~~

のような```の囲みを入れるといいと思います

**Comment by kozo2** [comment]
コミットメッセージも要ります。
@yoshoku さんは https://gitmoji.carloscuesta.me/ に従った分類をされているので
コミットメッセージとしては
```
:memo: Add script exec
```
とかがいいかもしれません

**Comment by sayfree** [comment]
:memo:

**Comment by sayfree** [comment]
Because I can not compare execution results, I think that it is better to add it to Example 2.

こんな感じでしょうか

**Comment by kozo2** [comment]
軽く
It might be better to add script exec example also for example2.
とかでもいいかもしれません

**Comment by sayfree** [comment]
https://github.com/yoshoku/rumale/pull/3

**Comment by sayfree** [comment]
Ruby のバグ報告
https://bugs.ruby-lang.org/projects/ruby-trunk/issues

**Comment by ShinjiEnoki** [comment]
振り返りよろしくお願いします！
