### ISSUE TITLE
RubyKaigi 2016でOSS Gateを紹介するために使うチラシを作る

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#114]
## 目的

「OSS Gate」という取り組みとその実現方法の1つである「OSS Gateワークショップ」を紹介しやすくすること。
## 背景

[クリアコードはRubyKaigi 2016のスポンサー](http://rubykaigi.org/2016/sponsors/#clear-code)になっており、ブースを出すことができる。そのブースでOSS GateとOSS Gateワークショップを紹介する予定である。そのときにチラシがあると捗りそうならチラシを用意してはどうかと須藤が考えている。

なお、ブースでの説明は須藤がするので、チラシがなくても説明はできる。なので、別に捗り具合は変わらなそうならチラシは用意しなくてもよい。

たとえば、他のことを期待できるなら捗るかもしれない。
- 説明を聞いた後に忘れにくくなる（家に帰ってからOSS Gate・OSS Gateワークショップのことを調べることを忘れにくくなるとか）
- 説明を聞いて興味をもった人が他の人に紹介しやすくなる
- ...
## TODO
- そもそもチラシを用意した方がよいかを検討する
- 用意したほうがよさそうならチラシを作る
  - RubyKaigi 2016の初日は9月8日なのでそこから逆算すると締め切りが決まる
  - 誰がデザインする？
  - 内容はどうする？
## 備考

チラシを作ることになった場合、RubyKaigi 2016だけで使えるものではなく、他のイベントでも使いまわせるものの方がよさそう。 #30 で作ったチラシはOSS Gateワークショップの日付が入っており、そのワークショップが終わった後にも使うのはやや気が引ける。

「OSS Gate」という取り組みとその実現方法の1つである「OSS Gateワークショップ」の両方を紹介する内容でもいいし、どちらか一方にしても構わない気がする。

RubyKaigi 2016は東京ではなく京都で開催される。そのため、東京以外でもOSS Gateをやっていきたいみたいなことを入れてもよいかもしれない。

**Comment by kou** [comment]
https://gitter.im/oss-gate/general?at=57a818aa48422f8b497819b7

> 東京Ruby会議11の際に @sezemiadmin さんが作成して下さったチラシをベースに、 oss-gate/workshop#30 のフィードバックを取り入れつつ、ブース用に修正を入れるのはどうですか？

**Comment by knokmki612** [comment]
> #30 で作ったチラシはOSS Gateワークショップの日付が入っており、そのワークショップが終わった後にも使うのはやや気が引ける。

この点は私もそう思いました。配る時に開催日は補足できそうですし、URLとか検索の文言とかQRコードとか、いくつか導線を用意しておけば良さそうかなと思います。

**Comment by sezemiadmin** [comment]
OSS Gate やワークショップを紹介するという目的からすると、前回のチラシ内容はほとんど使えない気がしてます。。

- 前回との違い
 - 対象
    - 前回: ビギナー向け
    - 今回: ビギナー/メンター/サポートメンター/地域主催者 向け?? or OSS開発に興味がある/参加したことがある人向け??
  - 目的
    - 前回: ワークショップへの参加
    - 今回: OSS Gateとワークショップを知って、何をしてもらいましょうかねぇ。。

**Comment by kou** [comment]
目的のところはどちらかというと次のアクションですかねぃ。

RubyKaigi 2016での次のアクションだと、私のところに説明を聞きに来て！、になっちゃいそうですねぇ。とすると、私がチラシを使って説明する、じゃなくて、会場入口とかにチラシがおいてあって、読んだら詳しいことを聞きたくなる、みたいな方向になっちゃいますよねぇ。でも、そうすると、他で使い回しにくいものになりそう。。。

チラシはいらないんですかねぇ。サイトのURLが書かれた小さい紙だけあればよかったりするのかしら。極端かしら。

**Comment by knokmki612** [comment]
> OSS Gate やワークショップを紹介するという目的からすると、前回のチラシ内容はほとんど使えない気がしてます。。

対象について:
東京Ruby会議11の際のチラシは文言こそビギナーを対象にしていましたが、ブログやツイートの抜粋部なんかは、ビギナー、メンター、進行役それぞれから抜粋してありましたから、潜在的にメンターしたいかたにも興味を持っていただけたのではないでしょうか。

7月30日の回のメンター向けアンケートを見返してみると、参加のきっかけに「東京Ruby会議」を挙げている方が2人いました。@kouさんの紹介とチラシ、どちらの影響かはちょっとわかりませんが。

目的について:
やっぱり参加していただけるところまでいくと良いんでしょうけど、関心を持ってもらう、くらいですかねぇ

**Comment by knokmki612** [comment]
> 目的のところはどちらかというと次のアクションですかねぃ。

次のアクションというのは、OSS Gateを紹介する流れ、という認識で合っていますか？

**Comment by kou** [comment]
> 次のアクションというのは、OSS Gateを紹介する流れ、という認識で合っていますか？

そういうつもりではなくて、「目的」と書いている箇所が意図しているのは「チラシを受け取った人が次にとって欲しいアクション」なんじゃないかと思いました。というつもりでした。

**Comment by sezemiadmin** [comment]
> やっぱり参加していただけるところまでいくと良いんでしょうけど、関心を持ってもらう、くらいですかねぇ  

確かにOSS開発に興味がある、もしくは参加していて、OSS Gateをまだ知らない人にOSS Gateを知ってもらう、という目的で良い気がしてきました

そう考えると、こんな概要でどうでしょう

- 対象
 - OSS Gateを知らない人
   - OSS開発に興味があるけど参加したことがない人
    - OSS開発に参加している人

- 目的
 - OSS Gateを知ってもらって関心をもってもらう
   - https://oss-gate.github.io/ossgate.github.io or https://oss-gate.doorkeeper.jp/ に行く
    - ワークショップへの動線を考えると dookeeper のほうがいい気がする

- 内容案
 - なぜやっているのか
 - どんなことをやっているのか
 - どんな人がやっているのか
 - (どこでやっているのか // 札幌も紹介できるといいなぁ)

**Comment by kou** [comment]
こんな感じでやってみましょうか！一回やってみればフィードバックがあって調整できると思いますし。

**Comment by kou** [comment]
再来週の月曜日までに内容ができていれば、うちの会社のプリンターで印刷して持っていけそうな気がするんですが、間に合いますかねぃ。
（業者に印刷をお願いするならもう少し前じゃないとダメそう？）

**Comment by sezemiadmin** [comment]
いつも使っているプリントパックなら [入稿->当日発送](http://www.printpac.co.jp/pricelist/list.php?product=leaflet&size=4&paper_type=1&paper=1&noki=1_0&changed=&proceed=on) でいけますよ。現地直送にすれば、最遅で開催2日前入稿?? (RubyKaigiの取り決めがあると思いますが) も行ける気が。。

今後のことを考えると、何らか共同で編集できるようにしておいたほうが良いですよね。
何か良いツールがあればと思うのですが。。
[Canva](https://www.canva.com/)とか出来そうなんですが、どうでしょう。。

**Comment by kou** [comment]
すごい！RubyKaigがブース用荷物の送り先を用意しているので、この方法も使えますね！

> 今後のことを考えると、何らか共同で編集できるようにしておいたほうが良いですよね。

そうですね！

> 何か良いツールがあればと思うのですが。。
> Canvaとか出来そうなんですが、どうでしょう。。

できればOSSがいいと思うんですが、今回はそれでもよいと思います！

**Comment by sezemiadmin** [comment]
> できればOSSがいいと思うんですが、今回はそれでもよいと思います！

そうなんですよねぇ。OSSのほうがいいですよね。ちょっと空いたときにでも探しておきます!

**Comment by kou** [comment]
さすがです！

**Comment by sezemiadmin** [comment]
Canvaで作ってみて、須藤さんにメールしてみたのですが、編集するのにCanvaのアカウントが必要でした。。
[(ossgate_flyer)](https://www.canva.com/design/DAB84cEWIO8/share?role=EDITOR&token=9WPYFOmROT1Lw8nXyp11cQ&utm_content=DAB84cEWIO8&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)
![oss gate flyer](https://cloud.githubusercontent.com/assets/13213803/17954673/5d1b2b66-6ab7-11e6-838a-dcd520eddac7.jpg)

**Comment by sezemiadmin** [comment]
誰がやっているか、を伝えたいと思って、[集合写真](https://www.flickr.com/photos/koichiroo/28664470281/)でも良いかなぁとは思ってます。(さすがに大場さんに断りいれないとダメな気がしてきました。。)
あと札幌の話とかも入れれそうなスペースはありますね。
取り急ぎ、荒々しく作ってみました

**Comment by kou** [comment]
おぉ！それっぽいですね！
当日大場さんが撮った写真は、使っていいよと言われているので大丈夫です！

完成したら印刷まわりのことを相談しましょう！

**Comment by sezemiadmin** [comment]
> 当日大場さんが撮った写真は、使っていいよと言われているので大丈夫です！

:+1: 
では、週内に手をあと少し入れて、今の案は完成しておきますね。 (他案も余力あれば)

**Comment by sezemiadmin** [comment]
- 文章を↓のように修正しました

> 参加方法を伝える場としてワークショップを開催しています。開催時期はワークショップの開催情報で確認してください。OSS開発に参加したいけどできていない人、および、そんな人をサポートしたいOSS開発経験者の参加をお待ちしています。

参加方法を伝える場として **"ワークショップ"** を開催しています。
開催内容や時期はdoorkeeper のページをご覧ください。
OSS開発に参加したいけどできていない人、および、そんな人をサポートしたいOSS開発経験者の参加をお待ちしています
(東京だけでなく札幌でも開催されるようになりました!!)

- チラシイメージ // 今のワークショップ風景の写真と集合写真とを用意
  - ワークショップ風景
![flyer_kou](https://cloud.githubusercontent.com/assets/13213803/17962367/72f909f6-6aeb-11e6-959f-3fc585ac17de.jpg)
  - 集合写真 
![flyer_everyone](https://cloud.githubusercontent.com/assets/13213803/17962373/79cfdb9c-6aeb-11e6-823c-56758421bf1f.jpg)

**Comment by kou** [comment]
> 開催内容や時期はdoorkeeper のページをご覧ください。

Doorkeeper（Dを大文字）にすればあとは大丈夫だと思います！

写真はどっちのほうがいいですかねぇ。

**Comment by sezemiadmin** [comment]
> Doorkeeper（Dを大文字）にすればあとは大丈夫だと思います！

ありがとうございます～。変更しました!
![diff](https://cloud.githubusercontent.com/assets/13213803/17990806/27003978-6b74-11e6-9652-71d9cd5e7234.JPG)

発表中心のコミュニティではなく、ワークショップなので、写真でそれを出したほうが良いように思ってきました (どんな人が参加しているかも刺さりそうなのですが、ワークショップを優先したほうが良いという思いです)

**Comment by knokmki612** [comment]
> 発俵中心のコミュニティではなく、ワークショップなので、写真でそれを出したほうが良いように思ってきました

私も実際のワークショップでお二人が交わしている写真の方が、イメージが湧きやすくて良いと思います！

**Comment by ttwo32** [comment]
（どちらもよい写真だと思いますが・・・）私もワークショップを優先した方がイメージが沸きやすくてよいと思います！！

**Comment by kou** [comment]
ではこの案は「ワークショップ風景」版でいきましょう！

来週いっぱいで他の案がでなければ、この案で決定にしましょう！

**Comment by kou** [comment]
「ワークショップ風景」版をプリントパックで印刷・配送するようにしました！

**Comment by sezemiadmin** [comment]
わーー、スイマセンスイマセン、今週にやろうと思っていたのですが、、、ありがとうございます!!

**Comment by kou** [comment]
大丈夫です！チラシ作成ありがとうございます！

**Comment by kou** [comment]
チラシを使ったフィードバックですが、特にこれが困ったということはありませんでした！
が、それは、私があんまりチラシを使って説明をしていなかったからな気もします。。。説明して興味がある人にはチラシを渡す、という使い方をしていました。

200枚印刷して100枚くらいは余ったのかな。次になにか機会がある人に渡すのでそこでも使ってもらいましょう！

**Comment by sezemiadmin** [comment]
Gitterでも挙がってましたが、メンバーが本当に増えました!! ありがとうございます!! お疲れさまでした!! :+1:

**Comment by tdtds** [comment]
このissue、閉じていいですかね? 余ったチラシがどこに何枚あるかみたいな情報があるといいかな。

**Comment by sezemiadmin** [comment]
> 200枚印刷して100枚くらいは余ったのかな。次になにか機会がある人に渡すのでそこでも使ってもらいましょう！

@kou さんのところに100枚ぐらいですかね??

**Comment by kou** [comment]
うは、すっかり忘れていて会社に置いたままだった。。。
明日、ワークショップに行く前に会社に取りに行こう。。。

**Comment by kou** [comment]
会社にあるのを見つけたのでふりかえりのときに持っていきます！
