### ISSUE TITLE
OSS Gate 9/24 （東京）のアンケートURL

### ISSUE THREAD

**Issue by y-goto** [oss-gate/workshop#116]
振り返りの時間で使うアンケートです。

[ビギナー向けアンケート](https://docs.google.com/forms/d/e/1FAIpQLSfNxzlKyt8ApYumO9Gji_eD0VZowfav20IyvMMhdMopps6FDw/viewform)
[メンター向けアンケート](https://docs.google.com/forms/d/e/1FAIpQLSeVkTZ3chcTnM_sD825Ul41eF3dyoGDHOFKq2acl4RBSEpyWA/viewform)
[サポートメンター向けアンケート](https://docs.google.com/forms/d/e/1FAIpQLScIZkkVR2Q6ftzw0MnKQLYOYB61wX9J-H76eRdg2WuL5qqSbA/viewform)

**Comment by kou** [comment]
全部メンター向けアンケートになっている気がします！
「進行はどうでしたか？」みたいな項目を入れるのを忘れていたことに最近気づいたので札幌のやつではいれようと思っています！

**Comment by y-goto** [comment]
あいたたた。これは失礼しました！直しました！
札幌の質問事項。了解です。余裕があれば、こちらでも追加してみます。

**Comment by ycatch** [comment]
レポートを作成しようとしています。
アンケートの集計結果を拝見したいのですが、URLを教えていただけませんか。

よろしくお願いします。

**Comment by ycatch** [comment]
えー。Google Formについて調べてみたところ、
共同編集者として、私を追加していただければ良いんじゃないかと思いますが、如何でしょうか。
https://support.google.com/docs/answer/2917111?hl=ja

yyycatch@gmail.com を追加して頂けないでしょうか。

レポートのほうは、8割方できていて
、あとはアンケートの結果を反映したいと考えています。

お手数をおかけしますが、よろしくお願いします。

**Comment by ycatch** [comment]
えー。Google Formについて調べてみたところ、
共同編集者として、私を追加していただければ良いんじゃないかと思いますが、如何でしょうか。
https://support.google.com/docs/answer/2917111?hl=ja

yyycatch@gmail.com を追加して頂けないでしょうか。

レポートのほうは、8割方できていて
、あとはアンケートの結果を反映したいと考えています。

お手数をおかけしますが、よろしくお願いします。

**Comment by y-goto** [comment]
お手数をおかけしてすみません。
とりあえず、ycatch 様が参照できるように、共同編集者に追加いたしました。
よろしくお願いします。

**Comment by y-goto** [comment]
とはいえ、結果を人に見せたいときに、個人のメールアドレスを逐一追加するのは少々不便ですね。
Googleフォームでもっと楽な方法があればいいのですが…。

**Comment by ycatch** [comment]
y-goto様、ありがとうございました！
回答にアクセスできました。

追加いただくのは、とりあえず今回だけだと思います。。
回答ページをキャプチャして、どこかに貼っておくとかでも良いかも知れませんね。

迅速な対応ありがとうございました。

**Comment by y-goto** [comment]
csv形式でダウンロードして、githubの中においておきました。これならみんな参照できると思います。札幌のディレクトリの隣に東京のディレクトリを作ったので、その中のcsvファイルを参照してください。
