### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-03-12: sgidon: aframevr/aframe: Work log

### ISSUE THREAD

**Issue by sgidon** [oss-gate/workshop#1162]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sgidon** [comment]
afarmeの公式サイトを開いてみます。
https://github.com/aframevr/aframe

さて、OSSかどうかがわからない。どこを見ればいいのか？

**Comment by kumanoryo** [comment]
よろしくお願いします！

**Comment by sgidon** [comment]
右上に「MIT」って書いてあるリンクがあるけど、これかな？
画面キャプチャをissueに貼り付けとかできないでしょうか？

**Comment by monochromegane** [comment]
GitHubだと LICENSE というファイルをプロジェクト直下に置いていますね！
https://github.com/aframevr/aframe/blob/master/LICENSE

そのライセンスが https://opensource.org/licenses/alphabetical に含まれるか確認して見ましょう！

**Comment by sgidon** [comment]
> GitHubだと LICENSE というファイルをプロジェクト直下に置いていますね！
> https://github.com/aframevr/aframe/blob/master/LICENSE
> 
> そのライセンスが https://opensource.org/licenses/alphabetical に含まれるか確認して見ましょう！

ありました！
MIT License (MIT)

これが何を示しているのかがわかりませんが、とりあえずOSSなのですね。

**Comment by sgidon** [comment]
あれ？issueってスレッド別れたりしないのでしょうか？

**Comment by sgidon** [comment]
> あれ？issueってスレッド別れたりしないのでしょうか？

ないようですね。引用を使って紐づけしていく感じですねー。

**Comment by sgidon** [comment]
Examples、Features あたりは[A-Frameドキュメント](https://aframe.io/docs)と同じ感じですね。

**Comment by sgidon** [comment]
Usageいってみまーす。

**Comment by sgidon** [comment]
> Usageいってみまーす。

いくつかあるみたいですね。

1. Hello World的な基本パターン
1. Hello Worldにプラスしたパターン
1. npmで読み込むパターン

3.のnpmで読み込みパターンはやったことがないので試してみます。

**Comment by sgidon** [comment]
> 3.のnpmで読み込みパターンはやったことがないので試してみます。

`npm install --save aframe
# Or yarn add aframe`

`require('aframe')  // e.g., with Browserify or Webpack.`

これだけしかない。
あとはわかるよね的な感じだ。
これでどうしろと。。。

**Comment by pyama86** [comment]
わいわい

**Comment by sgidon** [comment]
> 右上に「MIT」って書いてあるリンクがあるけど、これかな？
> 画面キャプチャをissueに貼り付けとかできないでしょうか？

貼れた！
ファイルをD&Dでできるし、下の「Attach files by dragging & ・・・」からもできる。
クリップボードからの貼り付け（Ctrl+v）もできる。素敵です！！

![image](https://user-images.githubusercontent.com/9334694/54119565-fc1b0f80-4438-11e9-830b-e7f22be944ac.png)

**Comment by sgidon** [comment]
> わいわい

ガヤガヤ

**Comment by sgidon** [comment]
ライセンスは必ず見てね。このソフトウェアをどう使ってほしいのかがわかるらしい。
MIT はお好きに使ってね。ただし無保証ですよって感じのゆるいライセンス。

**Comment by sgidon** [comment]
vscode on coder.com が死んだ・・・

**Comment by sgidon** [comment]
> vscode on coder.com が死んだ・・・

一度落としたら復活。

**Comment by sgidon** [comment]
とりあえず。npm init から初めて見る。
と思ったら、node も npm も入っていなかった。
最初から入れててほしいな。> coder.com

**Comment by sgidon** [comment]
よくわからないけど、

```
apt-get update
apt-get install nodejs
apt-get install npm

```

をやってみた。

```
root@coder:/projects/aframe-sample# which npm
/usr/bin/npm

```

npm 入ったっぽい

**Comment by sgidon** [comment]
aframe関係なくなってきちゃった・・・

**Comment by monochromegane** [comment]
いい良いいいよ〜

**Comment by sgidon** [comment]
いいいいいいっっすか〜

**Comment by sgidon** [comment]
やっとaframeに戻ってきた。
最初の

```
npm install --save aframe
```

をやってみる。

```
root@coder:/projects/aframe-sample# npm install --save aframe
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine aframe@0.9.0: wanted: {"node":">= 4.6.0","npm":"^2.15.9"} (current: {"node":"4.2.6","npm":"3.5.2"})
aframe-sample@1.0.0 /projects/aframe-sample
└─┬ aframe@0.9.0  -> true
  ├── animejs@2.2.0 
  ├─┬ browserify-css@0.8.4 

・・・

  │   └── flatten-vertex-data@1.0.2 
  └─┬ webvr-polyfill@0.10.10 
    └─┬ cardboard-vr-display@1.0.16 
      ├── gl-preserve-state@1.0.0 
      ├── nosleep.js@0.7.0 
      └── webvr-polyfill-dpdb@1.0.15 

npm WARN aframe-sample@1.0.0 No description
npm WARN aframe-sample@1.0.0 No repository field.
root@coder:/projects/aframe-sample# 
```

なんかインストールできたみたい。。。なのかな？
正解がわからないけど、このまま進もう。

**Comment by sgidon** [comment]
また vscode on coder.com死んだ。。。

**Comment by sgidon** [comment]
なにごと？！

![image](https://user-images.githubusercontent.com/9334694/54120971-8fa20f80-443c-11e9-9e54-f24054654787.png)

**Comment by kumanoryo** [comment]
あらー coder.com が正常に稼働してないみたいですね。

**Comment by sgidon** [comment]
もう一度入ったら動いた。
package.json
みたら入っているっぽい

![image](https://user-images.githubusercontent.com/9334694/54121128-f7f0f100-443c-11e9-8b01-2af4cd3f70a5.png)

**Comment by sgidon** [comment]
> あらー coder.com が正常に稼働してないみたいですね。

ちょこちょこ固まりますね〜。
coder.comの問題なのか、ネットワークの問題なのか、様子見てみます。

**Comment by sgidon** [comment]
さて。。。どうしよう。

```
require('aframe')
```

これどこに書けばいいんだろう・・・

**Comment by sgidon** [comment]
```
// e.g., with Browserify or Webpack.
```

出た、、、わけわからんやつだ。
避けて通れないんですかねぇ。

**Comment by sgidon** [comment]
がんばって、[Webpack](https://ics.media/entry/12140)のお勉強をしてみます。

**Comment by sgidon** [comment]
一日目の成果
- Github の issus の使い方
- Github の ライセンスの確認方法
- npm でのプロジェウト構築全然わからない
- coder.com の vscode はよく固まる。

明日はWebpackを勉強してから進める。
OSSへのフィードバックできず、自分の勉強の場になっている。。。

**Comment by sgidon** [comment]
reopenってどうやるんだろう・・・

**Comment by kou** [comment]
あれ、「Reopen and comment」っていうボタンがありませんか？
権限がないとダメなのかな。。。

**Comment by kou** [comment]
「Comment」ボタンの隣です。

**Comment by sgidon** [comment]
でてこないのですよ・・・
![image](https://user-images.githubusercontent.com/9334694/54190898-241d7800-44f8-11e9-9083-58c1841d1399.png)

**Comment by kou** [comment]
うはー
reopenしておきました！

**Comment by sgidon** [comment]
@kou ありがとうございます！

**Comment by sgidon** [comment]
結局 Reopen できなかったのはなぜだろう？権限なし？

**Comment by monochromegane** [comment]
権限ですね！

**Comment by sgidon** [comment]
何はともあれ、Webpackをインストールする。

```
npm install webpack --save-dev
npm install webpack-cli --save-dev
```

そして、パスを通す。

```
export PATH=$PATH:./node_modules/.bin
```

**Comment by sgidon** [comment]
> 権限ですね！

らじゃっす。

**Comment by sgidon** [comment]
A-FrameにPullリクエストとか、恐れ多いよ。

**Comment by pyama86** [comment]
`export PATH=$PATH:./node_modules/.bin`

これ結構珍しい書き方すね。 `./node_modules`だから実行したディレクトリに依存しそ。

**Comment by sgidon** [comment]
> `export PATH=$PATH:./node_modules/.bin`
> 
> これ結構珍しい書き方すね。 `./node_modules`だから実行したディレクトリに依存しそ。

確かに相対だとおかしなことになりそうですね。。。
ここの記事をそのまま実行しています。
[https://qiita.com/soarflat/items/28bf799f7e0335b68186](https://qiita.com/soarflat/items/28bf799f7e0335b68186)

**Comment by kumanoryo** [comment]
> ここの記事をそのまま実行しています。
> https://qiita.com/soarflat/items/28bf799f7e0335b68186

OSSではないですが、このQiitaの記事に修正依頼できますね。

**Comment by monochromegane** [comment]
> A-FrameにPullリクエストとか、恐れ多いよ。

作る人も使う人も一緒に支えあっていければ一番良いと思うので，変に壁を作らずで良いと思います〜
楽しんでやっていきましょう〜

**Comment by sgidon** [comment]
A-Frameのissueに対して追加事象のコメント入れようと思っています。

[https://github.com/aframevr/aframe/issues/4071](https://github.com/aframevr/aframe/issues/4071)

検証環境がver0.9.0 だけでしたので、ver0.8.0, ver0.7.0でも同じ現象が発生したことを
報告しようと思っています。

**Comment by sgidon** [comment]
こっちにリンク貼ったら、issue側に反映されている。
どうしよう！！
![image](https://user-images.githubusercontent.com/9334694/54194012-9f822800-44fe-11e9-8ef8-9e1a9941f068.png)

**Comment by sgidon** [comment]
うーん、こっち側のリンクを消したんですけど、afarme側は消えないっすねぇ〜。

**Comment by sgidon** [comment]
まじ恐ろしい。

**Comment by sgidon** [comment]
> > ここの記事をそのまま実行しています。
> > https://qiita.com/soarflat/items/28bf799f7e0335b68186
> 
> OSSではないですが、このQiitaの記事に `編集をリクエスト` できますね。

大変恐縮ですが・・・相対パスで問題ないでしょうか？
で質問してみます。

**Comment by kumanoryo** [comment]
a-flame見に行ったら本当に参照の表記出てましたねｗ
大丈夫です。見られていきましょう！！

**Comment by sgidon** [comment]
> > > ここの記事をそのまま実行しています。
> > > https://qiita.com/soarflat/items/28bf799f7e0335b68186
> > 
> > 
> > OSSではないですが、このQiitaの記事に `編集をリクエスト` できますね。
> 
> 大変恐縮ですが・・・相対パスで問題ないでしょうか？
> で質問してみます。

と思ってコメント欄みたら、すでに質問と回答が書いてありました・・・
貢献できずｗ

**Comment by sgidon** [comment]
> a-flame見に行ったら本当に参照の表記出てましたねｗ
> 大丈夫です。見られていきましょう！！

かなりパニックになりましたｗ
知らない間にリンクはられているって、、、怖いけど便利ですね。
つながっていきましょうってことですね。

**Comment by sgidon** [comment]
> A-Frameのissueに対して追加事象のコメント入れようと思っています。
> 
> issues : 4071
> 
> 検証環境がver0.9.0 だけでしたので、ver0.8.0, ver0.7.0でも同じ現象が発生したことを
> 報告しようと思っています。

以下、報告内容（日本語版）

-----
私も同じ現象を確認しました。別バージョンでも現象は発生しています。
- A-Frame Version: 0.8.0, 0.7.0

エラーメッセージの違いがありましたので報告いたします。

Ver 0.9.0
```
core:a-node:error Failure loading node:   TypeError: Cannot set property 'bias' of undefined
    at i.updateShadow (light.js:186)
    at i.update (light.js:137)
    at initComponent (component.js:307)
    at i.updateProperties (component.js:279)
    at i.module.exports.Component (component.js:62)
    at new i (component.js:600)
    at HTMLElement.value (a-entity.js:326)
    at HTMLElement.value (a-entity.js:483)
    at HTMLElement.value (a-entity.js:451)
    at a-entity.js:247
```

ver 0.8.0
```
Uncaught (in promise) TypeError: Cannot set property 'bias' of undefined
    at i.updateShadow (light.js:176)
    at i.update (light.js:127)
    at i.updateProperties (component.js:279)
    at i.module.exports.Component (component.js:50)
    at new i (component.js:473)
    at HTMLElement.value (a-entity.js:344)
    at HTMLElement.value (a-entity.js:506)
    at HTMLElement.value (a-entity.js:474)
    at a-entity.js:267
    at a-node.js:129
``` 

ver 0.7.0
```
Uncaught (in promise) TypeError: Cannot set property 'bias' of undefined
    at i.updateShadow (light.js:176)
    at i.update (light.js:127)
    at i.updateProperties (component.js:259)
    at i.module.exports.Component (component.js:50)
    at new i (component.js:449)
    at HTMLElement.value (a-entity.js:391)
    at HTMLElement.value (a-entity.js:558)
    at HTMLElement.<anonymous> (a-entity.js:525)
    at a-entity.js:320
    at a-node.js:117
```

**Comment by sgidon** [comment]
English ver

-----
I also confirmed the same phenomenon. I also confirmed in other versions.
I report the difference in the error message.

- A-Frame Version: 0.8.0, 0.7.0

Ver 0.9.0
```
core:a-node:error Failure loading node:   TypeError: Cannot set property 'bias' of undefined
    at i.updateShadow (light.js:186)
    at i.update (light.js:137)
    at initComponent (component.js:307)
    at i.updateProperties (component.js:279)
    at i.module.exports.Component (component.js:62)
    at new i (component.js:600)
    at HTMLElement.value (a-entity.js:326)
    at HTMLElement.value (a-entity.js:483)
    at HTMLElement.value (a-entity.js:451)
    at a-entity.js:247
```

ver 0.8.0
```
Uncaught (in promise) TypeError: Cannot set property 'bias' of undefined
    at i.updateShadow (light.js:176)
    at i.update (light.js:127)
    at i.updateProperties (component.js:279)
    at i.module.exports.Component (component.js:50)
    at new i (component.js:473)
    at HTMLElement.value (a-entity.js:344)
    at HTMLElement.value (a-entity.js:506)
    at HTMLElement.value (a-entity.js:474)
    at a-entity.js:267
    at a-node.js:129
```

Ver 0.8.0 and ver 0.7.0 were same error messages.

**Comment by sgidon** [comment]
issue commit done!!
対象issueのリンクを貼るのが怖いので報告だけ。

**Comment by monochromegane** [comment]
なんでw

**Comment by sgidon** [comment]
> なんでw

[これです！](https://github.com/oss-gate/workshop/issues/1162#issuecomment-471947701)

**Comment by sgidon** [comment]
貼ってみます。
https://github.com/aframevr/aframe/issues/4071
