### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-03-11: keropiyo: aframevr: Work log

### ISSUE THREAD

**Issue by keropiyo** [oss-gate/workshop#1164]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kumanoryo** [comment]
よろしくお願いします！

**Comment by monochromegane** [comment]
調子はどうですか

**Comment by pyama86** [comment]
わいわい

**Comment by keropiyo** [comment]
https://github.com/aframevr/aframe
Exampleのソースをブラウザで見ると以下が表示される
![example](https://user-images.githubusercontent.com/3609473/54119644-32f12580-4439-11e9-9fa7-76f08d5b62a4.png)

**Comment by monochromegane** [comment]
イイネイイネ

**Comment by keropiyo** [comment]
https://github.com/aframevr/aframe
Exampleの２番目のソースをブラウザで見ると以下が表示される
![example2](https://user-images.githubusercontent.com/3609473/54120194-76985f00-443a-11e9-8c3d-cee6f3ead74e.png)

**Comment by monochromegane** [comment]
順調順調

**Comment by keropiyo** [comment]
```
npm install --save aframe
```
を実行したら以下が表示された。
```
npm WARN saveError ENOENT: no such file or directory, open '/Users/keropiyo/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/keropiyo/package.json'
npm WARN keropiyo No description
npm WARN keropiyo No repository field.
npm WARN keropiyo No README data
npm WARN keropiyo No license field.

+ aframe@0.9.0
added 179 packages from 267 contributors in 15.486s
```

**Comment by hsmt** [comment]
aframevrってなんぞ？

**Comment by keropiyo** [comment]
HTMLに記述できるWebVRを簡単に作れるOSSです。

**Comment by monochromegane** [comment]
日をまたぐと閉じる仕組みがあるらしく，閉じられてしまっていましたね．
2日続くのでreopenしておきます

**Comment by keropiyo** [comment]
まだ報告することがないので、aframevrの報告方針CHANGELOG.mdを読む。

**Comment by keropiyo** [comment]
間違った。CONTRIBUTING.mdでした。

**Comment by keropiyo** [comment]
CONTRIBUTING.mdにaframevrのSlackコミュニティに参加しようとあったので、
https://aframevr-slack.herokuapp.com
にメールアドレスを入れるが、Failed! token_revokedというメッセージでjoinできない。

**Comment by kumanoryo** [comment]
> にメールアドレスを入れるが、Failed! token_revokedというメッセージでjoinできない。

これ報告できますね！
（僕も `Failed! token_revoked` でした）

![image](https://user-images.githubusercontent.com/7764581/54194867-998d4680-4500-11e9-8d25-fd16c96fde91.png)

**Comment by keropiyo** [comment]
I tried to join the aframevr Slack community
 https://aframevr-slack.herokuapp.com
Put an e-mail address in, but failed! 
I can not participate in the message token_revoked.

**Comment by kumanoryo** [comment]
> I can not participate in the message token_revoked.

slackのチャンネルに参加できないのを伝えたいので
I can not participate in the slack channel.
の方が良さげですね。どうでしょうか。

**Comment by keropiyo** [comment]
なるほど！困りごとを明確に伝える方がいいですね！
どんなエラーメッセージが出たかを知りたいのでは？と思うので
I can not join the slack channel with the message "token_revoked".
ではどうでしょうか？

タイトルもそのまま「I can not join the slack channel with the message "token_revoked".」
でどうでしょうか？

**Comment by kumanoryo** [comment]
> どんなエラーメッセージが出たかを知りたいのでは？と思うので

追記アレンジありがとうございます！タイトル含めていいと思います。
あと可能であれば画像も貼るのはどうですかね。

**Comment by keropiyo** [comment]
はい。このようにしてみます。

「I can not join the slack channel with the message "token_revoked".」

I tried to join the aframevr Slack community
https://aframevr-slack.herokuapp.com
Put an e-mail address in, but failed!
I can not join the slack channel with the message "token_revoked".
![failed](https://user-images.githubusercontent.com/3609473/54196039-9fd0f200-4503-11e9-9f9c-77fc86a1c016.png)

**Comment by keropiyo** [comment]
初Issuesしてみました。
https://github.com/aframevr/aframe/issues/4077

**Comment by monochromegane** [comment]
キャプチャもあってわかりやすい！
