### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-03-11: kitkatayama: Parcel: Work log

### ISSUE THREAD

**Issue by kitkatayama** [oss-gate/workshop#1165]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Fukuoka: 2019-03-11: kitkatayama: Parcel: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kitkatayama** [comment]
## OSSであることを確認
* ライセンスはMITなのでオープンソース
* https://github.com/parcel-bundler/parcel/blob/master/LICENSE

**Comment by monochromegane** [comment]
最高

**Comment by kitkatayama** [comment]
## parcel本体ではなく、ドキュメントのほうに貢献したい
* https://parceljs.org/getting_started.html
  * この元になっているのはparcel-bundler/website
    * https://github.com/parcel-bundler/website
→parcel-bundler/websiteを目的のOSSとする

**Comment by kitkatayama** [comment]
## parcel-bundler/websiteを手元でビルドしたい
* Readmeを読む
  * https://github.com/parcel-bundler/website/blob/master/README.md
  * どうにも、下記を実施すればmdをビルドできそう？

    npm install
    npm run build
    npm start

  * ビルド後、 http://localhost:5000/?locale=ja で行けそう

**Comment by kitkatayama** [comment]
## 手元でビルドできない
* PowerShellでもcmdでもできない

![image](https://user-images.githubusercontent.com/9929234/54118898-70ed4a00-4437-11e9-998a-8bfdcd2159be.png)

![image](https://user-images.githubusercontent.com/9929234/54118935-7f3b6600-4437-11e9-94a5-fe391270542f.png)

* コマンドがないので、環境の用意が必要
* nodejsと一緒にnpmが入ってくる
  * https://nodejs.org/ja/
  * 参考: https://qiita.com/taiponrock/items/9001ae194571feb63a5e
* Windows上でのnpmがよくわからないので経験のあるUbuntu環境使いたい
  * WSL使う

**Comment by monochromegane** [comment]
いいネタ出てる

**Comment by pyama86** [comment]
わいわい

**Comment by kitkatayama** [comment]
## WSLのインストール

※Windows 10を使用

1. スタートより Store を検索
1. "Microsoft Store"が出てくるので、クリック
1. Microsoft Storeの起動後、右上の「検索」をクリックし、"Ubuntu"と入力し、エンター
1. アプリ内から Ubuntu 18.04 LTSをクリック
1. インストール（Microsoftアカウントとの関連付けについては、行わないようにした）
1. インストール後、スタートメニューに下記のようにアイコンが表示されるのでクリック 
![image](https://user-images.githubusercontent.com/9929234/54119408-975fb500-4438-11e9-9de9-53dcfe0d8f97.png)
1. 下記の表示が出るので、URLにアクセス
The WSL optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Error: 0x8007007e
Press any key to continue...
1. 以下のPowerShellコマンドを実行後、再起動してWSLを有効にする必要あり
  Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
1. 再起動後、 6. と同様のコマンドをクリックして起動すると、インストールが開始される
![image](https://user-images.githubusercontent.com/9929234/54119559-f9201f00-4438-11e9-94dd-c4a802edcda3.png)
1. ユーザー作成画面が表示されるので、案内のURL( https://aka.ms/wslusers 英語なのできつい)を参考にせず、ユーザーネーム、パスワード、パスワードの再入力を行う
1. WSLのインストール完了
![image](https://user-images.githubusercontent.com/9929234/54119767-76e42a80-4439-11e9-9535-80afba65d92b.png)

**Comment by kitkatayama** [comment]
## WSL上でparcel-bundler/websiteをビルド
1.  作業用ディレクトリ作成
$ mkdir 20190311-oss-gate
→ ~/20190311-oss-gate を作成
1. git確認
$ which git
/usr/bin/git
→gitは標準搭載
1. npm確認
$ which npm
$
→npmは入ってない
1. そもそもWSLで入れたUbuntuはアップデートが必要（セキュリティ観点から）
$ sudo apt update
$ sudo apt upgrade
![image](https://user-images.githubusercontent.com/9929234/54120342-cd059d80-443a-11e9-858e-9503b69aae34.png)

**Comment by kitkatayama** [comment]
## WSL上でparcel-bundler/websiteをビルド(2)

### gitの設定
* parcel-bundler/websiteのgit cloneの前にgit設定
  * 参考URL
    * https://help.github.com/en/articles/setting-your-username-in-git
    * https://help.github.com/en/articles/setting-your-commit-email-address-in-git
1. git設定
  git confit --global user.name "<ユーザー名>"
    ※私の場合は本名 Kazuo KATAYAMA で設定
  git config --global user.email "<コミット用メールアドレス>"
    githubの https://github.com/settings/emails からKeep my email address privateに記載のメールアドレス
1. 確認
  git config user.name
  git config user.email
1. Chromeで https://github.com/parcel-bundler/website にアクセスし、"Clone or download"の緑ボタンをクリック
1. Use SSHをクリック
1. git@github.com:parcel-bundler/website.git をコピー
1. WSLでクローン実行
cd 2019...(省略)
pwd
ls -al (ファイルがないことを確認)
git clone git@github.com:parcel-bundler/website.git
実行後エラー
```
Cloning into 'website'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is <省略>
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
1. ssh公開鍵の登録
* https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
$ cd ~/.ssh/
$ ssh-keygen -t rsa -b 4096 -C "<省略>"

```
Generating public/private rsa key pair.
Enter file in which to save the key (/home/kitkatayama/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/kitkatayama/.ssh/id_rsa.
Your public key has been saved in /home/kitkatayama/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:05G/LZaiOlJyiE1dMksc2s3E5jmjyqaksDK8VQYCl9E 9929234+kitkatayama@users.noreply.github.com
The key's randomart image is:
+---[RSA 4096]----+
<省略>
+----[SHA256]-----+
```

---
今日はここまで

**Comment by kitkatayama** [comment]
## 明日の実施予定
* sshのgithub.comに対するid_rsaを使用するためのconfig作成
* githubの設定から公開鍵登録(read/write権限でいいかな)
* git clone実行
* npmインストール
* リポジトリのビルド
* アクセスして確認
* .mdの日本語リソースを編集
* 再ビルド
* 変更が反映されるか確認

**Comment by kitkatayama** [comment]
## WSL上でparcel-bundler/websiteをビルド(2)

### gitの設定
* parcel-bundler/websiteのgit cloneの前にgit設定
  * 参考URL
    * https://help.github.com/en/articles/setting-your-username-in-git
    * https://help.github.com/en/articles/setting-your-commit-email-address-in-git
1. git設定
  git confit --global user.name "<ユーザー名>"
    ※私の場合は本名 Kazuo KATAYAMA で設定
  git config --global user.email "<コミット用メールアドレス>"
    githubの https://github.com/settings/emails からKeep my email address privateに記載のメールアドレス
1. 確認
  git config user.name
  git config user.email
1. Chromeで https://github.com/parcel-bundler/website にアクセスし、"Clone or download"の緑ボタンをクリック
1. Use SSHをクリック
1. git@github.com:parcel-bundler/website.git をコピー
1. WSLでクローン実行
cd 2019...(省略)
pwd
ls -al (ファイルがないことを確認)
git clone git@github.com:parcel-bundler/website.git
実行後エラー
```
Cloning into 'website'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is <省略>
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
1. ssh公開鍵の登録
* https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
$ cd ~/.ssh/
$ ssh-keygen -t rsa -b 4096 -C "<省略>"

```
Generating public/private rsa key pair.
Enter file in which to save the key (/home/kitkatayama/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/kitkatayama/.ssh/id_rsa.
Your public key has been saved in /home/kitkatayama/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:<省略> <省略>
The key's randomart image is:
+---[RSA 4096]----+
<省略>
+----[SHA256]-----+
```

---
今日はここまで

**Comment by kitkatayama** [comment]
（ログにメールアドレスやらfingerprintやら出ていたので削除して再コメント）

**Comment by monochromegane** [comment]
日をまたぐと閉じる仕組みがあるらしく，閉じられてしまっていましたね．
2日続くのでreopenしておきます

**Comment by kitkatayama** [comment]
かしこまりました、reopenありがとうございます！

**Comment by kitkatayama** [comment]
## WSL上でparcel-bundler/websiteをビルド(3)

### sshのgithub.comに対するid_rsaを使用するためのconfig作成
1. cd ~/.ssh
1. vim config
1. iで挿入モード
1. 以下を張り付け
```
  Host github.com
  User git
  HostName github.com
  IdentityFile ~/.ssh/id_rsa
  IdentitiesOnly yes
```
5. esc, w, q, エンターで保存 
### githubの設定から公開鍵登録(read/write権限でいいかな)
1. cat ~/.ssh/id_rsa.pub
<省略>
1. 表示された公開鍵を、GitHubサイトのSetting->SSH and GPG Keysから登録

### git clone実行
```
$ git clone git@github.com:parcel-bundler/website.git
Cloning into 'website'...
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 3971 (delta 28), reused 51 (delta 19), pack-reused 3901
Receiving objects: 100% (3971/3971), 5.40 MiB | 1.65 MiB/s, done.
Resolving deltas: 100% (1930/1930), done.
```
gitのclone完了

### npmインストール
$ sudo apt install npm
yで操作を承認
<すごい長いログ省略>
$ npm --version
```
3.5.2
```
→入ったっぽい
### リポジトリのビルド、npmを起動
* https://github.com/parcel-bundler/website/blob/master/README.md
```
:~/20190311-oss-gate/$ cd website/
:~/20190311-oss-gate/website$ ls -al
total 9
drwxrwxrwx 1 kitkatayama kitkatayama  512 Mar 12 19:08 .
drwxrwxrwx 1 kitkatayama kitkatayama  512 Mar 12 19:08 ..
-rw-rw-rw- 1 kitkatayama kitkatayama  147 Mar 12 19:08 .editorconfig
drwxrwxrwx 1 kitkatayama kitkatayama  512 Mar 12 19:08 .git
-rw-rw-rw- 1 kitkatayama kitkatayama   92 Mar 12 19:08 .gitignore
-rw-rw-rw- 1 kitkatayama kitkatayama 1069 Mar 12 19:08 LICENSE
-rw-rw-rw- 1 kitkatayama kitkatayama  599 Mar 12 19:08 README.md
-rwxrwxrwx 1 kitkatayama kitkatayama  325 Mar 12 19:08 build.sh
-rw-rw-rw- 1 kitkatayama kitkatayama  319 Mar 12 19:08 now.json
-rw-rw-rw- 1 kitkatayama kitkatayama  741 Mar 12 19:08 package.json
-rw-rw-rw- 1 kitkatayama kitkatayama   75 Mar 12 19:08 prettier.config.js
drwxrwxrwx 1 kitkatayama kitkatayama  512 Mar 12 19:08 src
```


* 下記を実行
```
npm install
npm run build
npm start
```
→エラーなし
### アクセスして確認
* http://localhost:5000/?locale=ja にアクセス

![image](https://user-images.githubusercontent.com/9929234/54193398-4f569600-44fd-11e9-8341-23d81fe6fbc1.png)

## 以下未実行
.mdの日本語リソースを編集
再ビルド
変更が反映されるか確認

**Comment by kitkatayama** [comment]
# Readme.mdのロケール毎のアクセス方法がわかりづらい

```
Changing the displayed language
Change the displayed language using a query string:

E.g.: access the Korean version using the following url: http://localhost:5000/?locale=ko
```
改定案1

* http://localhost:5000/?locale=en English 
* http://localhost:5000/?locale=es Espanol 
* http://localhost:5000/?locale=fr Francais 
* http://localhost:5000/?locale=it Italiano 
* http://localhost:5000/?locale=ja 日本語 
* http://localhost:5000/?locale=ko 한국어
* http://localhost:5000/?locale=pl Polskie
* http://localhost:5000/?locale=pt Portugues 
* http://localhost:5000/?locale=ru Русский 
* http://localhost:5000/?locale=uk Українська
* http://localhost:5000/?locale=zh 简体中文 
* http://localhost:5000/?locale=zh-tw 繁體中文

改定案2


* [English](http://localhost:5000/?locale=en)
* ...and so on

* 実際にこのコメントから全てのリンク開けるのでやりやすい（個人的に）

**Comment by kitkatayama** [comment]
# OSSへのコミット内容整理→開発者にとってわかりやすくなるように編集

## Readme.mdのロケール毎のアクセス方法がわかりづらい

* Readme.mdの例示には、Korean(韓国語)のみのURLしか書いていない
```
Changing the displayed language
Change the displayed language using a query string:

E.g.: access the Korean version using the following url: http://localhost:5000/?locale=ko
```

* ロケールの識別子はsrc/i18nディレクトリを見ないとわからない
  * https://github.com/parcel-bundler/website/tree/master/src/i18n
* ロケール毎に一々手打ちしたくない
* ロケールごとのリンク集が欲しい
* 他の開発者さんはどんなふうに各ロケールを確認しているか気になる（そもそもしていない？から必要ない？）
* 実際にこのコメントから全てのリンク開けるのでやりやすい（個人的に）

### 改定案1

* English: http://localhost:5000/?locale=en 
* Espanol: http://localhost:5000/?locale=es  
* Francais: http://localhost:5000/?locale=fr 
* ... and so on

### 改定案2

* [English](http://localhost:5000/?locale=en)
* [Espanol](http://localhost:5000/?locale=es)
* [Francais](http://localhost:5000/?locale=fr)
* ...and so on

### 改定案3
[en](http://localhost:5000/?locale=en), [es](http://localhost:5000/?locale=es), [fr](http://localhost:5000/?locale=fr), ... and so on

### 改定案4
<details>
  <summary>See other language</summary>

* English:  http://localhost:5000/?locale=en
* Espanol:  http://localhost:5000/?locale=es  
* Francais: http://localhost:5000/?locale=fr  
* .. and so on
</details>

**Comment by kumanoryo** [comment]
個人的には改定案1、かなぁ。

**Comment by kitkatayama** [comment]
# issue発行を想定したコメント（日本語）

タイトル: README.mdに各言語へのquery stringの説明およびリンクが必要

現在、README.mdのChanging the displayed language節は下記のようになっており、koリソース用のアクセスの説明のみ用意されている状態です。

```
### Changing the displayed language

Change the displayed language using a query string:

E.g.: access the Korean version using the following url: http://localhost:5000/?locale=ko
```

ko以外の開発者or翻訳者への利便性のため、下記のように変更したほうが良いのではないかと考えております。

```
### Changing the displayed language

Change the displayed language using a query string:

* English: http://localhost:5000/?locale=en 
* Espanol: http://localhost:5000/?locale=es  
* Francais: http://localhost:5000/?locale=fr 
* and so on (I'll add complete list when send pull request)
```

いかがでしょうか。
以上となります。どうぞよろしくお願いいたします。

**Comment by kitkatayama** [comment]
### issue投げ先
* https://github.com/parcel-bundler/website/issues
* 実績を見る限りissuesでよさそう
* 英語
* 英語

**Comment by kitkatayama** [comment]
# issue発行を想定したコメント（英語）

タイトル: README.mdに各言語へのquery stringの説明およびリンクが必要

Title: Link to query string in README.md

現在、README.mdのChanging the displayed language節は下記のようになっており、koリソース用のURLのみ用意されている状態です。
Currently, there is only URL for ko(Korean) resource under "Changing the displayed language" in README.md.

```
### Changing the displayed language

Change the displayed language using a query string:

E.g.: access the Korean version using the following url: http://localhost:5000/?locale=ko
```

ko以外の開発者か翻訳者への利便性のため、下記のように変更したほうが良いのではないかと考えております。
For convenience to developer or translators, it is better to change as follows imo.

```
### Changing the displayed language

Change the displayed language using a query string:

* English: http://localhost:5000/?locale=en 
* Espanol: http://localhost:5000/?locale=es  
* Francais: http://localhost:5000/?locale=fr 
* and so on (I'll add complete list when send pull request)
```

実際、README.mdにアクセスした際の表示は、このようになることを想定しています。
It will be displayed as follows:

--- 

### Changing the displayed language

Change the displayed language using a query string:

* English: http://localhost:5000/?locale=en 
* Espanol: http://localhost:5000/?locale=es  
* Francais: http://localhost:5000/?locale=fr 
* and so on (I'll add complete list when send pull request)

---

いかがでしょうか。
以上となります。どうぞよろしくお願いいたします。

what do you think?
Regards,

**Comment by kitkatayama** [comment]
### issueしました
https://github.com/parcel-bundler/website/issues/406
