### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-03-11: shirotaro-jp: A-Frame: Work log

### ISSUE THREAD

**Issue by shirotaro-jp** [oss-gate/workshop#1166]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shirotaro-jp** [comment]
テスト

**Comment by monochromegane** [comment]
困ったら書いてくださいね〜

**Comment by kumanoryo** [comment]
よろしくお願いします！

**Comment by shirotaro-jp** [comment]
【公式ページ】https://aframe.io/
【GitHub】https://github.com/aframevr/aframe

aframe/README.mdのUsageを読む。

**Comment by monochromegane** [comment]
OSSかどうかも確認して見てくださいね〜
https://opensource.org/licenses/alphabetical

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/blob/master/LICENSE
を確認。

The MIT License

と記載。
OSSかわからない。

**Comment by pyama86** [comment]
わいわい

**Comment by shirotaro-jp** [comment]
https://opensource.org/licenses/alphabetical
を確認。
MITもOSS。

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/blob/master/README.md
に戻る。

![スクリーンショット 2019-03-11 20 02 59](https://user-images.githubusercontent.com/43288205/54119769-777cc100-4439-11e9-85f1-f61058d762c6.png)
Usageにある上の画像のボタンをそれぞれ押してみる。

左：Glitch
VRが表示されている。
codeも確認できた。

右：repl.it
codeが表示されているが、VR表示はまだ。
[run]を押すとVRが表示された。

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/blob/master/README.md
のUsageのExampleの一つ目のサンプルコードの下
...
With A-Frame's entity-component architecture, we can drop in community components from the ecosystem (e.g., ocean, physics) and plug them into our objects straight from HTML:
...
にあるhttps://aframe.io/docs/0.9.0/core/へのリンクが404errorになっている。

**Comment by monochromegane** [comment]
これはいいネタ！！コントリビューションチャンス！

**Comment by shirotaro-jp** [comment]
![スクリーンショット 2019-03-11 20 02 59](https://user-images.githubusercontent.com/43288205/54119769-777cc100-4439-11e9-85f1-f61058d762c6.png)
Usageにある２番目の上の画像のボタンをそれぞれ押してみる。

左：Glitch
codeのhead部分
```
  <head>
    <title>Entity-Component - Registry</title>
    <meta name="description" content="Entity-Component - Registry">
    <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-animation-component@3.2.1/dist/aframe-animation-component.min.js"></script>
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js"></script>
    <script src="https://unpkg.com/aframe-extras.ocean@%5E3.5.x/dist/aframe-extras.ocean.min.js"></script>
    <script src="https://unpkg.com/aframe-gradient-sky@1.0.4/dist/gradientsky.min.js"></script>
    <script src="https://unpkg.com/aframe-extras.tube@%5E3.5.x/dist/aframe-extras.tube.min.js"></script>
  </head>
```

https://github.com/aframevr/aframe/blob/master/README.md
のUsageのExampleに記載のコードのhead部分
```
 <head>
    <script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js"></script>
    <script src="https://unpkg.com/aframe-extras.ocean@%5E3.5.x/dist/aframe-extras.ocean.min.js"></script>
    <script src="https://unpkg.com/aframe-gradient-sky@1.0.4/dist/gradientsky.min.js"></script>
  </head>
```
〜違い〜
a-frameのバージョンが違う。
背景色が違う。

右：repl.it
１個目と同じものが表示されている。表示したかったものと異なると思われる。

**Comment by monochromegane** [comment]
良さ

**Comment by shirotaro-jp** [comment]
２つめのGlitchのコードについて

”a-frameのバージョンが違う。”ことにより、
”背景色が違う。”らしい。

その他、https://github.com/aframevr/aframe/blob/master/README.md のUsageのExampleに記載のコードのhead部分にあるが、Glitchのcodeのhead部分にない以下の２行がどう作用しているかはわからないまま。
```
    <script src="https://unpkg.com/aframe-animation-component@3.2.1/dist/aframe-animation-component.min.js"></script>

    <script src="https://unpkg.com/aframe-extras.tube@%5E3.5.x/dist/aframe-extras.tube.min.js"></script>
```

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/blob/master/README.md >> Usage >> Example
一つ目のサンプルコードの下のリンク https://aframe.io/docs/0.9.0/core/ が404errorになっていることを報告したい。

正しいリンク先を公式サイトから探してみる。

**Comment by kumanoryo** [comment]
すばらしいです。
仮に正しいリンク先が見つけられなくても「404になってますよ」と報告することで十分な貢献になります！

**Comment by shirotaro-jp** [comment]
１）https://aframe.io/docs/0.9.0/introduction/html-and-primitives.html#example-2
２）https://aframe.io/docs/0.9.0/introduction/entity-component-system.html#community-component-ecosystem
３）https://aframe.io/aframe-registry/
このあたりっぽい。

２）が良さそう。

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/blob/master/README.md >> Usage >> Example
一つ目のサンプルコードの下のリンク https://aframe.io/docs/0.9.0/core/ が404errorになっているます。

変更リンク先として、以下２つのリンク先をご提案します。

- https://aframe.io/docs/0.9.0/introduction/entity-component-system.html#community-component-ecosystem
- https://aframe.io/aframe-registry/

**Comment by monochromegane** [comment]
キーワードを見る限りは https://aframe.io/docs/0.9.0/introduction/entity-component-system.html かなとも思いましたがどうですかねえ

**Comment by shirotaro-jp** [comment]
わたしも https://aframe.io/docs/0.9.0/introduction/entity-component-system.html だと思います。

**Comment by monochromegane** [comment]
PRにしますか！

**Comment by monochromegane** [comment]
CONTRIBUTION.md みたいなのがないか，READMEにCONTRIBUTEの欄がないか確認して
あれば，それに従いましょう

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/blob/master/README.md >> Usage >> Example
The link https://aframe.io/docs/0.0.9/core/ under the first sample code is 404 error.

We suggest the following link destination as change link destination.
https://aframe.io/docs/0.9.0/introduction/entity-component-system.html

**Comment by shirotaro-jp** [comment]
https://github.com/aframevr/aframe/pull/4076
