### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-03-11: Hiroshi Igarashi: Flask: Work log

### ISSUE THREAD

**Issue by 50storm** [oss-gate/workshop#1167]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 50storm** [comment]
test

**Comment by 50storm** [comment]
https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst を読んでます。

**Comment by monochromegane** [comment]
いいね！
まずそれがOSSかどうかも見てみるといいかも？？
https://opensource.org/licenses/alphabetical

**Comment by 50storm** [comment]
サポートと質問は、IRCチャネルを使ってと書いてある。
#pocoo
#python
IRCを利用したことがないので調べる必要ある。

**Comment by kumanoryo** [comment]
よろしくお願いします！

**Comment by 50storm** [comment]
> よろしくお願いします！

よろしくおねがいします！m(__)m

**Comment by 50storm** [comment]
長期的なディスカッションまたは、大きな問題は、flask@python.orgのメーリングリストに入ってとある。

**Comment by monochromegane** [comment]
いきなりコントリビューションするのではなく，まず何を貢献できるか考えるために，そのOSSを使って見ましょう

**Comment by kumanoryo** [comment]
READMEのINSTALLINGから試してみるのはどうですかね。
https://github.com/pallets/flask#installing

**Comment by 50storm** [comment]
Fork Flask to your GitHub account by clicking the Fork button.
の指示に基づき、Forkを実行した。

以下のリポジトリに、flaskのリポジトリができた。
https://github.com/50storm/flask

**Comment by 50storm** [comment]
-------以下の指示に基づきクローンを行う---------
Clone your GitHub fork locally:
git clone https://github.com/{username}/flask
cd flask

-------実行結果----------
i$ git clone https://github.com/50storm/flask.git
Cloning into 'flask'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 16492 (delta 0), reused 5 (delta 0), pack-reused 16487
Receiving objects: 100% (16492/16492), 6.39 MiB | 695.00 KiB/s, done.
Resolving deltas: 100% (11337/11337), done.
$ cd flask/

**Comment by 50storm** [comment]
READMEではなく、Contributingの方を見ていた。。。

**Comment by monochromegane** [comment]
OKOK

**Comment by 50storm** [comment]
----インストール------
Install and update using pip:

pip install -U Flask

------実行結果-----
$ pip install -U Flask
Requirement already up-to-date: Flask in /Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages (1.0.2)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages (from Flask) (0.24)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10 in /Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages (from Flask) (2.10)
Requirement already satisfied, skipping upgrade: click>=5.1 in /Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages (from Flask) (6.7)
Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in /Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages (from Flask) (0.14.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages (from Jinja2>=2.10->Flask) (1.0)
You are using pip version 18.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


pipのバージョンが古いとメッセージが出たが、大丈夫そうです。

**Comment by 50storm** [comment]
A Simple Exampleを試そうと思ったが、情報不足？
------------------------以下が例--------------------------
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello, World!'

$ env FLASK_APP=hello.py flask run
 * Serving Flask app "hello"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
----------------------------------------------------------------

hello.pyをつくてということと、感じ、以下を作る
---------------
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return 'Hello, World!'
--------------------
以下を実行
$ env FLASK_APP=hello.py flask run
 * Serving Flask app "hello.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/flask/cli.py", line 771, in run_command
    threaded=with_threads, ssl_context=cert)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Users/hiroshi/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

エラーとなった。。。

**Comment by monochromegane** [comment]
いいログ

**Comment by monochromegane** [comment]
`OSError: [Errno 48] Address already in use` こういうのが出てるからポート番号が被ってそうですね〜

**Comment by 50storm** [comment]
> `OSError: [Errno 48] Address already in use` こういうのが出てるからポート番号が被ってそうですね〜

ありがとうございます。
自分のPCで開発中で動かしてたwebサーバーとportがかぶってました。

**Comment by 50storm** [comment]
以下で、動きました。
```
$ env FLASK_APP=hello.py flask run
 * Serving Flask app "hello.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Mar/2019 20:25:21] "GET / HTTP/1.1" 200 -
```

**Comment by monochromegane** [comment]
やったね！！！！

**Comment by 50storm** [comment]
> やったね！！！！

ありがとうございます！！(^^)

**Comment by 50storm** [comment]
A Simple Exampleがhello.pyのファイル名がなく、コードだけで少しわかりずらかった。

**Comment by 50storm** [comment]
README.rstファイルにファイル名:hello.pyを追加してあげたいが、rstファイルをブラウザで見る方法を調べないとです。

**Comment by monochromegane** [comment]
日をまたぐと閉じる仕組みがあるらしく，閉じられてしまっていましたね．
2日続くのでreopenしておきます

**Comment by 50storm** [comment]
ステップ１
Dear flask developers,
flask開発者の魅魔様
I'm a new flask user.
私は、flaskのニューユーザーです。

After installing flask according to README.md,I got stuck in "A Simple Example section".
インストールをEADME.mdにしたがっておこなったあと、"A Simple Example section"でつまづきました。

I think it is just because I couldn't see any comment in "A Simple Example section".
ただ単に、"A Simple Example section"に、コメントが何も見当たらなかっただからだと思います。

In order to refine "A Simple Example section", I have just added some comments to "A Simple Example section".
"A Simple Example section"をよくするために、コメントをいくつか"A Simple Example section"に追加しました。
 
you can see the modification below.
変更については、以下で見れます。
https://github.com/50storm/flask/blob/master/README.rst

It would be greatful if you accept my requent.
もし、私のリクエストを受け入れていただけると、嬉しいです。

Sincerely yours.

**Comment by monochromegane** [comment]
いいじゃないっすか！！！！

**Comment by monochromegane** [comment]
良さそうなのでPRで行くぞ〜となりました．
commitが3つ．アカウントが2つに分離していたので，もう一度そこをまとめたやつで進めましょうと話しました．いけるいける

**Comment by 50storm** [comment]
アカウントを１つにして、修正まとめました。

https://github.com/pallets/flask/compare/master...50storm:readme_branch

**Comment by 50storm** [comment]
pull request遅れまあした。
ありがとうございます！
https://github.com/pallets/flask/pull/3121
