### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-03-11: hsmt: baserCMS: Work log

### ISSUE THREAD

**Issue by hsmt** [oss-gate/workshop#1168]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by monochromegane** [comment]
お，なんか見たことがある人だな？？？

**Comment by hsmt** [comment]
https://basercms.net/download/index.html から最新版のバージョン4.1.6をダウンロード。

**Comment by hsmt** [comment]
ダウンロードしている間にライセンスを以下で確認。
https://basercms.net/about/license
MIT License https://osdn.net/projects/opensource/wiki/licenses%2FMIT_license

**Comment by monochromegane** [comment]
頑張ってください！！！！！！

**Comment by hsmt** [comment]
インストール方法はインストールガイドをみながら進める。
http://wiki.basercms.net/インストールガイド

**Comment by hsmt** [comment]
レンタルサーバーを使うことように書かれているけど、MAMPを使うことにする。

**Comment by hsmt** [comment]
開発者向けのインストールガイドがほしいとチーフコミッターに連絡。

**Comment by hsmt** [comment]
WebサーバーはApache、PHPのバージョンは7.1.1で、MAMPを起動。

**Comment by hsmt** [comment]
cd /Applications/MAMP/htdocs/

**Comment by hsmt** [comment]
```
cp -r /Users/masa/Downloads/basercms/app .
cp -r /Users/masa/Downloads/basercms/lib .
cp -r /Users/masa/Downloads/basercms/.htaccess .
```

**Comment by hsmt** [comment]
ブラウザから http://localhost:8888 にアクセス。
英語化されてて、びっくり。
<img width="1350" alt="Screen Shot 2019-03-11 at 20 24 05" src="https://user-images.githubusercontent.com/1287407/54120685-b744a800-443b-11e9-8d78-d983949d3fb6.png">

**Comment by hsmt** [comment]
"database are needed" ではなくて "database is needed" ではないか？と英文チェッカーが。

**Comment by hsmt** [comment]
Start Installation ボタンをクリックして installation [step 2] へ。

パーミッションエラー
```
Write permission to /files folder (707 OR 777 etc. Follow server recommendations if they exist)
Not Writable
You need write permission to /files folder
Write permission to /theme folder (707 OR 777 etc. Follow server recommendations if they exist)
Not Writable
You need write permission to /theme folder
Write permission to /img folder (707 OR 777 etc. Follow server recommendations if they exist)
Not Writable
You need write permission to /img folder
Write permission to /css folder (707 OR 777 etc. Follow server recommendations if they exist)
Not Writable
You need write permission to /css folder
Write permission to /js folder (707 OR 777 etc. Follow server recommendations if they exist)
Not Writable
You need write permission to /js folder

```

**Comment by hsmt** [comment]
`chmod 707 ../htdocs/`

**Comment by hsmt** [comment]
`mkdir css`
これで、いかがなくなったので、ディレクトリを手動で作っていかないといけないみたい。キット。
```
Write permission to /css folder (707 OR 777 etc. Follow server recommendations if they exist)
Not Writable
You need write permission to /css folder
```

**Comment by hsmt** [comment]
```
$ mkdir files
$ mkdir theme
$ mkdir img
$ mkdir js
```
エラーなくなった。

**Comment by hsmt** [comment]
Next Step のボタンをクリック。

**Comment by hsmt** [comment]
インストール成功。

**Comment by hsmt** [comment]
テーマやプラグインの開発のときはローカル環境にインストールする事が多いと思うのですが、ホスティングサーバーにインストールするための手順しかないので、MAMPを使ったときのインストール方法などが記載されていたほうがいいと思う。

**Comment by hsmt** [comment]
issueを立てました。
https://github.com/baserproject/basercms/issues/1001
