### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-03-28: note103: Gibier: Work log

### ISSUE THREAD

**Issue by note103** [oss-gate/workshop#1179]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
よろしくおねがいします！

**Comment by note103** [comment]
## ここまでの経緯

- TokyoGirls.rb で @youchan さんの登壇を見る
  - https://techplay.jp/event/716251
- スライドツールかっこいい、という印象
- ブログにその旨書く
  - Rabbitだと思ってそう書いたら
  - [TokyoGirls.rb Meetup vol.1 に行ってきた - the code to rock](http://note103.hateblo.jp/entry/2019/03/03/093216)
- Gibierだよと教えてもらう（ご本人から）
  - http://b.hatena.ne.jp/entry/4665371582068638145/comment/Youchan
- さっそく試すも、エラー
- 同じことで悩んでいる人がIssueを立てていた。
  - [bundle exec rackup時にNameError · Issue #3 · youchan/gibier](https://github.com/youchan/gibier/issues/3)
- そこでようさんの言うバージョン指定をちょっとアレンジして試したら、エラーが消えた！
  - 以下と同じ
  - https://github.com/youchan/gibier/issues/3#issuecomment-476596595
- けど、今度は `http://localhost:8080/` に飛んでも画面が真っ白
  - イマココ!

**Comment by note103** [comment]
真っ白ページから、[本家のサンプルページ](http://youchan.org/gibier/sample/)と同じサンプルページが出るところまで来ました！

最小限の手順としては、まずGemfileのgibierのバージョンを下げて
`gem 'gibier', '0.8.10'`

以下を追加したところ、
`gem 'opal-haml', '0.4.5', github: 'opal/opal-haml'`

画面が出ました。
![Screenshot from Gyazo](https://gyazo.com/f0b98fdda0df8814bd8ca4d1dfc20e7d/raw)

詳細についてはもう少し詳しくまとめたいところですが、ひとまず要点までです。

**Comment by youchan** [comment]
わー。ありがとうございます。フィードバック楽しみにしてます!

**Comment by note103** [comment]
2日目です!!

ひとまず、昨日はサンプル画面を出すことまででひと区切りしたので、今日はどのバージョンからそのエラーが出るのか、という検証をすることからスタートしたいと思います。

とりあえず、gibier自体のバージョンが `0.8.14`の場合には画面が出てこないですが、 `0.8.10` にすると出てきたので、その間をひとつひとつ試してみます。

**Comment by note103** [comment]
- Gemfile.lockの見方を教えてもらいました。
  - opal-haml のバージョンを確かめるため。

**Comment by note103** [comment]
```
[note103] oss-gate-retry$ bundle install
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/.
You have requested:
  opal ~> 0.10.0

The bundle currently has opal locked at 0.11.4.
Try running `bundle update opal`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
[note103] oss-gate-retry$ bundle update opal
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "opal":
  In Gemfile:
    opal (~> 0.10.0)

    opal-haml was resolved to 0.4.5, which depends on
      opal-sprockets (~> 0.4.1) was resolved to 0.4.3.0.11.0.3.7, which depends on
        opal (~> 0.11.0)
```

**Comment by note103** [comment]
↑昨日、 `opal-haml` のバージョンを下げたきっかけになったエラー文です。

**Comment by note103** [comment]
手元で昨日できた成功画面を再現できず・・どうも、上記の2行をGemfileに追記・編集しただけでは駄目のようで、あらためて検証中です。

**Comment by note103** [comment]
ようさんに新しいGibierのバージョン（0.8.15）をリリースしてもらってサクッと動くようになりました!!

**Comment by note103** [comment]
諸々、試した経緯等については手元にメモを取ったので、あらためてまとめてこちらに入れます。

@knokmki612 さん、 @swamp09 さん、@youchan さん、ありがとうございました！！ 🙌

**Comment by note103** [comment]
アンケートをFork先からプッシュするためのコマンドのメモ。
```
[note103] retrospectives:note103-retrospective$ git push -u origin note103-retrospective 
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 4 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 1.14 KiB | 292.00 KiB/s, done.
Total 10 (delta 7), reused 1 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 4 local objects.
remote: 
remote: Create a pull request for 'note103-retrospective' on GitHub by visiting:
remote:      https://github.com/note103/workshop/pull/new/note103-retrospective
remote: 
To github.com:note103/workshop.git
 * [new branch]      note103-retrospective -> note103-retrospective
Branch 'note103-retrospective' set up to track remote branch 'note103-retrospective' from 'origin'.
```

**Comment by note103** [comment]
## 残りのTodo
- [ ] アンケート回答
- [ ] プルリク終わらす
- [ ] サポータの方々にメンション
- [ ] このイシューのメモ完了させる
- [ ] ブログにまとめる

**Comment by note103** [comment]
2日間の軌跡を時系列にまとめておきます。これを投稿ののち、一旦このIssueはcloseしまして、ブログを書いたらコメントだけ追加しておきたいと思います。

***

## DAY 1

### 準備系

- アイスブレイク、自己紹介等。
- サポータの @knokmki612 さん @swamp09 さんとご挨拶。
- お題の候補を3つほど提示。
  - るびま編集への参加
  - Gibier でハマってるポイントの解消＆フィードバック
  - gerpツールのagでハマってるポイントの解消等
- Gibierが一番主旨に近そう、と思えたのでそれで。
- 担任（？）は @knokmki612 さん。 @swamp09 さんは全体の進行的な割り振り（たぶん）。

### 本番
- @knokmki612 さんに言われるがまま、イシューへGibierに関するここまでの経緯を投稿。
  - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477559353
- 懸案の白い画面が出るところまではサクサク再現。
- @knokmki612 さんから「白い画面で開発ツールのコンソールを見てみよう」とご提案。
  - 画面上で右クリック→検証で開発ツールを見れることを初めて知る。
- ようやくエラーメッセージに対面！
  - それ以前はターミナルでもブラウザでもエラーが出なくて報告自体できない状態だった・・。
- エラーを確認できたので、最悪これをリポジトリのイシューにリポートすれば良いな！ と思えて気が楽に。
- より高い目標として、正常に動かない原因を突き止めて報告、またはさらに高い目標として手元で直せればプルリクなども見据えるおとに。
- ブラウザのコンソールのエラーをあらためて確認。
  - バックグラウンドがどうしたとか・・。（よくわからん）
  - メッセージの量は多いけどほぼ1種類のエラーの模様。
- エラー内の文言でスライド用に生成したディレクトリをgrepしてみよう、と @swamp09 さんからご提案。
  - アイスブレイクでgrepツールのagを使ってるなどの話をしていたらそれをいきなり使うことに。
  - なんとか出来たけどこれが自分で対応できるぎりぎりのレベル。
- server.rb などのコードをしばらく眺める
- eachメソッド、getなども見る。
- スライド用データに問題はなさそう。表示する際の依存モジュールの問題か？
  - この辺りからopal系のモジュールの問題であると絞り始めたような。
- 古いモジュール群で動くはずの以前のGibierを試してみよう、と @swamp09 さん。
- とはいえ、以前のバージョン番号はどこでわかるか？がわからないか私。
- https://rubygems.org/ でgibierで検索！と @swamp09 さん。
  - https://rubygems.org/gems/gibier/versions
- ファーストビューで表示されてる中で一番古い0.8.10を使ってみることに。
- Gemfileで指定。
- 新たなエラーに遭遇。
  - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477961731
  - gibierのバージョンを下げたことにより生じたものか？
- 表示されている `opal-haml` もそこに書かれている `0.4.5` でGemfileに指定してみる。
- その後・・
  - bundle update
  - bundle exec rackup
  - localhost 8080
- 動いた！！！
- ここでちょうどタイムアップ。経過報告をして続きは明日へ・・
  - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477574044

## DAY 2

### 事前に考えていたテーマ
- 昨日はとりあえず一番前の `0.8.10` で試したけど、実際にはバージョンいくつまでなら動くのか突き止めておきたい。
  - それにもとづいてフィードバックしたいので。
  - エラーの内容を厳密に突き止めておくことにより再現性を高めたい。
- わからなかったらわからない、と書けばそれも貢献、と @knokmki612 さんに言われたような・・気がするけどおぼろげ。
  - ちなみに同じことを終盤で @youchan さんからも言って頂きました。

### 本番
- 昨日の作業ディレクトリでGibierのバージョンを `0.8.10` から最新のひとつ前である `0.8.13` にしてみる。
  - 最新の `0.8.14` でダメ＆ `0.8.10` でうまくいったのだから、試していないバージョンの高い方から順に下げていこう、ということに。
  - しかし `0.8.13` でいきなり問題なく動作。
  - 12, 11でも問題なく動く・・
  - もしかして・・と思って昨日はダメだった `0.8.14` でも動く・・。 :thinking:
- ディレクトリを変えてみることに。
  - 今度は `0.8.10` を含めすべてのバージョンで真っ白。
  - 昨日のトライで再現条件だと思っていた `opal` および `opal-haml` も含めて揃えても再現できず。
  - 暗礁・・。
    - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477962390
    - ＊ここでのハマりの原因は後からほぼ把握できたので後述。
- このあたりで @youchan さん到着！
- 颯爽と状況を見て頂いて、どうもお手元の最新バージョンとリポジトリ上の `0.8.14` でいくつかズレがあるとのこと。
- 最新の `0.8.15` を音速リリース。
- 解決（笑）。
- 簡単に問題の原因をいえば Opal との依存問題。 `0.8.14` の状態だと Opal の最新に追随できていなかった。
  - その暫定的な対策として Opal を `~> 0.10.0` にしておく、ということがあったわけだけど、それだけでは解決しなかった、というのが今回の状況。
  - とはいえ、その辺の謎解きをするには時間も体力もなかったので一旦ここまで。
- 状況だけとりあえずイシューに報告。
  - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477972987
- アンケート＆簡単にふり返り。
  - 本当ならここで自分のアンケートも提出予定でしたがけっこう時間かかりそう＆燃え尽きていたので後日出させて頂くことに・・。
- OSS Gate リポジトリからFork & プルリク。
  - フォークしてからプルリク、という作業はもしかしたら初めてだったかも。 @youchan さんからGitコマンドを教えて頂き、とりあえず Draft Pull Request をするところまでなんとか・・。
  - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477980576
- ひとまず終了。おつかれさまでした！＆ありがとうございました！

## DAY 3
- アンケート提出！
  - と思ったら提出場所を間違えたっぽい……？
  - とりあえず修正版を送りました。

## 番外: 後から気づいたこと（2019-03-31）
### gibier 0.8.10で動くまで
- gibier 0.8.10でうまく反映されるための再現条件は以下だと思われる。
  1. gem 'opal', '~> 0.10.0' #<= 0.8.14以下の場合はこれがないと bundle exec rackup が通らない
  2. gem 'opal-sprockets', '~> 0.4.1.0' #<= おそらくこれ次第で真っ白かどうかが決まる
- この際、1を設定した上で `bundle update` すれば2も自動的に追随するので、そこで反映されたはずだけど、DAY 1のときには以下のログからもわかるとおり、
  - https://github.com/oss-gate/workshop/issues/1179#issuecomment-477961731
- `bundle install` および `bundle update opal` しかしてなかったので、その段階では `opal-sprockets` の方は Opal 0.11系に依存する 0.4.3.0.11.0.3.7 が残っていて、スライドが動かなかったと思われる。
- その後に動いたのはたぶん `opal-haml` のバージョンを `0.4.5` に設定したからではなく、それを反映しようとして `bundle update` をしたから。これにより、 `opal-sprockets` が 0.4.1.0.10.4.3.1.0 になったのでは、と。

### gibier 0.8.14で動かなかった理由
- 一方、当初は gibier 0.8.14 で何度も Opalを `~> 0.10.0` に設定した上で `bundle update` していたわけで、これで動かないのはオカシイ！んだけど、これはまた別の理由で、gibierは 0.8.11 以降に `template/project/app/page_base.rb` に以下の一行が加わっていて、
- `require_relative './page_background'`
- どういうわけかこれが以下の記述じゃないと動かなかったみたい。
- `require 'page_background'`
- 逆に、gibier 0.8.10 まではこの記述自体がナイので、Opal を `~> 0.10.0` に設定した上で `bundle update` すればそれでOKだった。
- なので、 DAY 1に関しては、基本的にgibierのバージョンを0.8.10に下げた時点で9割方正解だった。（その後素直に `bundle update` しておけば）
- DAY 2に関しては、gibierを0.8.11にした時点で普通にコケていたはず。その場合の解決法は、appディレクトリに入っている `page_base.rb` のrequire文をちょっと調整すること。
  - ただしちなみに、 gibier 0.8.15 ではこの部分の記述は0.8.14のママで成立しているので、たぶん本質的な問題なのでもなさそう。そこから先は手に余るのでこの件はここまで。

***

なんだか取り留めなくなりましたが、ひとまず覚えているうちに覚えている限りのことを書いておきました。

一旦、こちらでIssue close しておきます。あらためまして、皆様ありがとうございました。

**Comment by note103** [comment]
閉じてから思いましたが、closeするのって勝手にやっちゃってよかったのかな・・？ 🤔 

問題ありましたら適宜お知らせください・・

**Comment by knokmki612** [comment]
> closeするのって勝手にやっちゃってよかったのかな・・？

大丈夫です。いろいろありがとうございます。

**Comment by note103** [comment]
ありがとうございます！ 🙌 了解しました。 😊

**Comment by note103** [comment]
@youchan さん、遅くなりましたが、あらためまして、上記ありがとうございました。

動くまで頑張るより原因の切り分け、なるほどと思いました。ぼくの場合、その2つがごっちゃになったままとりあえずやってみる、という感じになっていたと思います。
今回にかぎらず、ぼくはこういうハマり方（時間のかかり方）が結構多いので、今後はその進め方・方針を思い出せるようにしたいと思います。

アンケートの方にもちらっと書きましたが、OSSへのコントリビュートってもっと別次元の作業のように思っていましたが、今回の経験でそのソフトウェアを使っている時点でコントリビュートの入り口に入っているのかな、という気がしました。
これを機に今後ますます気軽に貢献していければ、と思っています。
