### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: yamashun: elasticsearch-rails: Work log

### ISSUE THREAD

**Issue by yamashun** [oss-gate/workshop#1184]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yamashun** [comment]
普段から使っているので[elasticsearch-rails](https://github.com/elastic/elasticsearch-rails)  にします

**Comment by yamashun** [comment]
最初にgemを見つけたときは、 elasticsearch rails などで検索してqiita の記事から見つけました

**Comment by yamashun** [comment]
https://github.com/elastic/elasticsearch-rails
のページの一番下のLicenseでApache 2 license となっていて以下に含まれることでOSSであること確認
https://opensource.org/licenses/alphabetical

**Comment by yamashun** [comment]
railsで使うためにまずは空のrailsプロジェクトを作成する

**Comment by yamashun** [comment]
以下が表示されinstallできないのでまずはrailsのインストール
```
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails
```

**Comment by yamashun** [comment]
実行後も同じエラーが発生

**Comment by yamashun** [comment]
```
$ type rails
rails is hashed (/usr/bin/rails)
```
パスがおかしいので以下で修正
```
$ sudo gem uninstall rails
$ rbenv rehash
$ type rails
rails is /Users/shunsuke.yamada/.rbenv/shims/rails
```

**Comment by yamashun** [comment]
テンプレート作成のコマンドを再実行
```
$ rails new searchapp --skip --skip-bundle --template https://raw.github.com/elastic/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
```

エラーが発生。
```
ERROR    Cannot connect to Elasticsearch on <http://localhost:9200>

                The application requires an Elasticsearch cluster running, but no cluster has been found on <http://localhost:9200>.
                The easiest way of launching Elasticsearch is by running it with Docker (https://www.docker.com/get-docker):

                docker run --name elasticsearch-rails-searchapp --publish 9200:9200 --env "discovery.type=single-node" --env "cluster.name=elasticsearch-rails" --env "cluster.routing.allocation.disk.threshold_enabled=false" --rm docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
```

**Comment by yamashun** [comment]
`The easiest way of launching Elasticsearch is by running it with Docker (https://www.docker.com/get-docker):`
とあり、dockerで立ち上げることを進めているがローカルにdockerの環境がない人はつまずく。

**Comment by yamashun** [comment]
今回はローカルにElasticsearchの環境があるのでエラーメッセージに従い
`http://localhost:9200` で接続できるように起動

**Comment by yamashun** [comment]
再実行して上のエラーは解消したが別のエラー
```
Fetching bindex 0.7.0
Installing bindex 0.7.0 with native extensions
Errno::EACCES: Permission denied @ dir_s_mkdir - /Users/shunsuke.yamada/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0-static/bindex-0.7.0
An error occurred while installing bindex (0.7.0), and Bundler cannot continue.
Make sure that `gem install bindex -v '0.7.0' --source 'https://rubygems.org/'` succeeds before bundling.
```

**Comment by yamashun** [comment]
sudo つけて実行してインストールが完了して画面が起動
<img width="830" alt="スクリーンショット 2019-04-27 12 27 57" src="https://user-images.githubusercontent.com/9530257/56844237-05c4dd80-68e8-11e9-94ed-a11b2123d3ae.png">

**Comment by yamashun** [comment]
[Elasticsearch::Model](https://github.com/elastic/elasticsearch-rails/tree/master/elasticsearch-model)
のドキュメントにkaminariを使ったページネーションを試す

**Comment by piroor** [comment]
お話を伺った感じでは、2つ目の躓き（rails newが停止する、elasticsearchがローカルで起動していないといけなかった）がフィードバックポイントになると思いました。

現在の状態：elasticsearchが起動していない状態で、使い始めた
期待される結果：rails newすると成功する
実際の結果：rails newするとエラーになる

これを軸にフィードバックできると思います。

**Comment by yamashun** [comment]
## 再現手順
http://localhost:9200でElasticsearchが起動していない状態。
READMEの「Usage」セクションの通りに進める。

`rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb`
でサンプルアプリケーションを起動しようとする。

## 実際の結果
以下のエラーが発生する。

```
ERROR    Cannot connect to Elasticsearch on <http://localhost:9200>

                The application requires an Elasticsearch cluster running, but no cluster has been found on <http://localhost:9200>.
                The easiest way of launching Elasticsearch is by running it with Docker (https://www.docker.com/get-docker):

                docker run --name elasticsearch-rails-searchapp --publish 9200:9200 --env "discovery.type=single-node" --env "cluster.name=elasticsearch-rails" --env "cluster.routing.allocation.disk.threshold_enabled=false" --rm docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
```

## 期待されること
http://localhost:9200でElasticsearchが起動が必要であることを事前にREADMEに記載してほしい。
ドキュメントの通りに進めてエラーにならないこと。

**Comment by yamashun** [comment]
## Steps to reproduce
With Elasticsearch not running on http://localhost:9200, proceed as described in the "Usage" section of the README.
Try to start the sample application with the following command.

```
rails new searchapp --skip --skip-bundle --template https://raw.github.com/elasticsearch/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb
```

## Actual behavior
The following error occurs.

## Expected behavior
Please note in the README ahead of time that Elasticsearch needs to be running on http://localhost:9200.
I will send you an amendment by pull request.

**Comment by yuseitahara** [comment]
丁寧なIssueでとても分かりやすいです!
