### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: shimadama: sorcery: Work log

### ISSUE THREAD

**Issue by shimadama** [oss-gate/workshop#1185]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shimadama** [comment]
[sorcery-example-app](https://github.com/Sorcery/sorcery-example-app)をローカルにインストール

**Comment by shimadama** [comment]
[![Image from Gyazo](https://i.gyazo.com/94034148c7981459f937e756e1bf2d19.png)](https://gyazo.com/94034148c7981459f937e756e1bf2d19)

``` bin/rails db:migrate RAILS_ENV=development```
```
Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
```

**Comment by dasman74** [comment]
フィードバックネタがあってうらやましいです。

**Comment by okuramasafumi** [comment]
そもそも、exampleのRailsバージョンが古い…？

**Comment by okuramasafumi** [comment]
`ActiveRecord::Migration[4.2]`
よりも
`ActiveRecord::Migration[5.2]`
のほうがいいのかもしれませんが、きちんと動作するのかはわかりません。参考まで。

**Comment by shimadama** [comment]
title:
Fixed Directly inheriting from ActiveRecord::Migration is not supported.

```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
```

**Comment by shimadama** [comment]
```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateUsers < ActiveRecord::Migration[4.2]
```

**Comment by shimadama** [comment]
PR:
https://github.com/Sorcery/sorcery-example-app/pull/7

**Comment by shimadama** [comment]
RPの手順(メモ)：
`PRを送るRepositoryをforkする`
`forkしたRepositoryをcloneする`
`branchをきる`
`修正内容をpush`
`github上でPR作成`
