### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: makicamel: Authoreyes: Work log

### ISSUE THREAD

**Issue by makicamel** [oss-gate/workshop#1186]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by makicamel** [comment]
[対象OSS: Authoreyes](https://github.com/tektite-software/authoreyes)

ライセンスの確認
[MITライセンス](https://github.com/tektite-software/authoreyes/blob/master/LICENSE.txt)であることを確認しました。

**Comment by makicamel** [comment]
## Authoeryesとは
- userオブジェクトの持つroleによって権限をわけられるGem

## どうしてこのGemやりたいと思ったかの経緯
### きっかけ
- 仕事でRailsアプリのバージョンアップ案件を担当
- バージョンアップに従い、元々使っていた[declarative_authorization](https://github.com/stffn/declarative_authorization/)というGemからこのAuthoreyes(後継Gem)に変更
- declarative_authorizationはroleのあるuserについてのみroleを確認するような挙動だったけれど、Authoreyesでは全てのuserでroleを確認するような挙動になっていた
- 特定のcontroller以下ではroleの確認をしたくなかったがその時は対応方法がわからず、モンキーパッチで強引に解決した

### 続き
- 改めてコードを読んでみると、controllerで`redirect_if_unauthorized`というメソッドをオーバーライドすればよいということがわかった
- 改めてPiroさんに言って頂いて確認するとReadmeにも書いてあった

> If you want to customize authorization behavior, in your ApplicationController override Authoreyes's `redirect_if_unauthorized` before_action and `set_unauthorized_status_code` after_action. See `lib/authoreyes/helpers/in_controller` for details.

**Comment by makicamel** [comment]
- Readmeのいう通り`in_controller.rb`を読んでみる
- `in_controller.rb`には`redirect_if_unauthorized`(オーバーライドしてって記載されているメソッド)がある
- 元々の動機である`特定のcontroller以下ではroleの確認をしたくない`に関しては、ここまでの情報で実現できる

- ただ、もう少しコードを読んでみたら、`user_roles`オプションが準備されていることがわかった
- `特定のcontroller以下ではuser_rolesに特定のroleを渡す`という挙動も実装されている！
- でも、コードをちゃんと読んでみないとわからない状態

## 考え方のFWについてのお話(Piroさんに教えていただく)
「現状」と「期待される状態」がある
- description: 特定のcontroller以下でのroleの確認の挙動の変更手順
- (steps to reproduce): (今回はReadmeを読むだけ)
- actual result:
  Readmeを読む
 「 `redirect_if_unauthorized `をオーバーライドしたらできるよ、詳細は`in_controller.rb`見てね」と言われる
  `in_controller.rb`を読む
  `redirect_if_unauthorized`→`permitted_to!`→`Engine#permit!`→…のコメント+コードを読んだりして`user_roles`オプションを発見
- expected result:
  Readmeで書いてあったら便利だと思う！

**Comment by makicamel** [comment]
## フィードバックまとめ中メモ

**前提条件**
こういう要件の挙動をしようとしたけどできなかった

**わかったこと**
overrideすればよかった
optionを指定すればできた

**問題点**
- overrideする方法が書いてなかった
- オプションについての記載がなかった
- 説明がないし、コードの上でのコメントにも記載がなかった
*ドキュメントがないのが問題*

---

問題点から記載するとわかりやすい！:star:

---

**結論**
documentがなくてわかりにくかったのでほしいよ
今試しにdocument書いてるから、完成したらPR送るね

みたいな感じでIssueを立ててPRを送ると作者の気持ちに優しい:star:

**Comment by makicamel** [comment]
## フィードバック下書き(日本語)

title:
redirect_if_unauthorizedのoverrideに関してのdocumentがほしい

body:
`redirect_if_unauthorized`のoverrideに関してのdocumentがほしい

特定のcontrollerでauthorizationの挙動をカスタマイズしたいという要件があった。
> If you want to customize authorization behavior, in your ApplicationController override Authoreyes's redirect_if_unauthorized before_action and set_unauthorized_status_code after_action. 

って書いてくれているけど、次の場合どうしたらよいかを理解できるまで時間がかかってしまった。

- ApplicationControllerのような基底クラスではなく、特定のcontrollerで挙動をカスタマイズしたい
-> 特定のcontrollerで`redirect_if_unauthorized`をoverrideすればよい
- 特定のcontrollerで任意のuser_rolesを渡したい
-> `{user_roles: :some_role}`というオプションを渡してあげればよい
(user_rolesオプションに関しては説明がないし、コード上のコメントにも記載がなかった)

今documentを書いているから、完成したらPR送るので見てみてね。

**Comment by makicamel** [comment]
[issue](https://github.com/tektite-software/authoreyes/issues/18)を立てられました！

**Comment by shingonnw** [comment]
非常に詳しく説明されていてよかったと思います。
