### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: Kensaku Okada: QuickTweet - for multiple Twitter™ accounts: Work log

### ISSUE THREAD

**Issue by kensaku-okada** [oss-gate/workshop#1189]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese (but I personally write in English). Thanks. 

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kensaku-okada** [comment]
Since I have multiple Twitter account and want to easily switch them. I found
QuickTweet is an extension for Google's browser, Chrome.

配布ページ
sites.google.com/site/quickloginfortwitter

ライセンスの所在を検索(OSSかどうかの確認)
1
I found a page mentioning the site where users can report any suggestions or bugs, which is a facebook page.
https://www.facebook.com/pages/QuickTweet/483197618365492

2
I searched the local folders and found the following path having the extension's sources. 
C:\Users\kensa\AppData\Local\Google\Chrome\User Data\Default\Extensions\kalepocfmlnefnjlbecpkidgdaigibml\0.0.0.8_0

3
I could not find any repositories or pages showing an OSS license, which indicates this software is not an open source.

4
At the "chrome web store"'s support page (https://chrome.google.com/webstore/detail/quicktweet-for-multiple-t/kalepocfmlnefnjlbecpkidgdaigibml/related), many users complaints that this extension does not work after Twitter changed it UI recently, and even though they report the issue, the developer has not fixed it yet. No OSS licence or codes were found here as well.

5
From the above, I judged

**Comment by kensaku-okada** [comment]
-- Official distribution page
https://chrome.google.com/webstore/detail/multiple-twitter-accounts/gajnifmlijakbfmnhnnjplphnehlkfdh/related

This extension was found at the support page of QuickTweet
(https://chrome.google.com/webstore/detail/quicktweet-for-multiple-t/kalepocfmlnefnjlbecpkidgdaigibml/related

ライセンスの所在を検索(OSSかどうかの確認)

Another 


YUKI "Piro" Hiroshi @piroor

**Comment by kensaku-okada** [comment]
## Problem to solve
To use Gitlab locally, I decided to download and install gitlab following this instruction (https://about.gitlab.com/install/#ubuntu). At the time, I faced the following error.
------------------
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
------------------
which was fixed in a few minutes.

## apt's Official distribution page
https://github.com/Debian/apt (mirror site)
https://salsa.debian.org/apt-team/apt (original site)

**Comment by piroor** [comment]
GitLabをやろうとしたらaptのエラーで詰まった、というように、何かしようとしていて別の事で躓いた、というときに、それを目ざとく捉えて、元々やろうとしていた方の事を脇に置いてその問題の方に取り組む、というのはよくあることだと思います。
今回のaptの事例もフィードバックしていい事で、今後同じ事で躓く人が減るならそれに越した事はないと思います。
UbuntuのLunchpadに投げてみて、本体でやった方がいいと言われたらaptのリポジトリに持っていく、というように段階を踏んでフィードバックをしてみていいと思います。
