### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: shingonnw: rails: Work log

### ISSUE THREAD

**Issue by shingonnw** [oss-gate/workshop#1190]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shingonnw** [comment]
対象oss:rails
日本語サイトからスタートする
https://railsguides.jp/

Rails をはじめようのリンク目次のインストールの
記述にしたがって進めて行く

**Comment by shingonnw** [comment]
rubyのバージョン確認
$ ruby -v
RailsではRubyバージョン2.2.2以降が必須です。

shingo-MBA:~ shingo$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin17]

rubyのバージョンはok

**Comment by shingonnw** [comment]
SQLite3データベースのインストールも必要です。
とあるので確認

$ sqlite3 --version
上を実行することでバージョンを確認できます。

shingo-MBA:~ shingo$ sqlite3 --version
3.19.3 2017-06-27 16:48:08 2b0954060fe10d6de6d479287dd88890f1bef6cc1beca11bc6cdb79f72e2377b

**Comment by shingonnw** [comment]
Mac OS XユーザーはTokaidoをお使いください。(訳注: 具体的なインストール方法についてはRailsチュートリアル 1.2 さっそく動作させるを参照してください。
Railsをとりあえずインストールするのではなく、本格的な開発に使う場合はrbenvなどのツールを整備したりDockerと連携させる必要が生じることもあります)
 
まず、
インストール手順が複数あったので
サポーターに確認。

手順の
Tokaido
を見てみる。

https://github.com/tokaido/tokaidoapp
の最終更新が4年前になっている。

インストール手順として適切か怪しい。
issueポイント？

**Comment by shingonnw** [comment]
英語の本家サイトも確認
https://guides.rubyonrails.org/getting_started.html

A number of tools exist to help you quickly install Ruby and Ruby on Rails on your system. Windows users can use Rails Installer, while macOS users can use Tokaido. For more installation methods for most Operating Systems take a look at ruby-lang.org.

「macOS users can use Tokaido」とある。
https://github.com/tokaido/tokaidoapp
に移動

**Comment by shingonnw** [comment]
tokaidoapp
のREADME.mdに従って進めてみる

Visit https://github.com/tokaido/tokaidoapp/releases/
とあるので移動

**Comment by shingonnw** [comment]
Tokaido 2.2の
In this release:
は以下の通り。

Ruby binary 2.2.2-p95 (latest 2.2 stable)
RubyGems 2.4.6
Ruby On Rails 4.2.1
Redis 3.0.0 client and server binaries
ImageMagick's convert binary
Postgres.app detection
Bug Fixes

バージョンが古い
issueポイント？

**Comment by hide-furusawa** [comment]
TOKAIDOに同じISSUES があるか確認してみる。

この古い手順で、先に進める必要性を考える

**Comment by okuramasafumi** [comment]
TOKAIDO、初めて知りました！

**Comment by shingonnw** [comment]
https://github.com/tokaido/tokaidoapp/releases/download/v2.2/Tokaido.zip
からダウンロードしてインストールしてみる

インストールはできた

open terminalのボタンを押すと
ターミナルが開いた。
多分インストールは成功。

This terminal is now ready to use with Tokaido.

shingo-MBA:~ shingo$ 
shingo-MBA:~ shingo$ rails -v
Rails 4.2.1
shingo-MBA:~ shingo$ 
shingo-MBA:~ shingo$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin12.0]
shingo-MBA:~ shingo$

**Comment by shingonnw** [comment]
インストールはできたが、
バージョンが古いものである。
期待したのは現在の最新バージョンなので
手順として記載するのはどうなのか、
手順としては消すべきではないかという方向で行きたい。

**Comment by shingonnw** [comment]
フィードバック内容

Tokaidoを利用してインストールすると
Rails 4.2.1
でインストールされた。
railsの最新バージョンをインストール出来ると期待したので、
インストール手順の記載を見直して欲しい。

**Comment by shingonnw** [comment]
フィードバック英訳下書き

When installed using "Tokaido", it was installed with Rails 4.2.1.

I expected to be able to install the latest version,
Please review the description of the installation procedure.

**Comment by shingonnw** [comment]
issue タイトル（日本語）
Tokaidoを使うインストール手順は記載するべきではない

英訳タイトル
Installation instructions using Tokaido should not be described

本文
When installed using "Tokaido", it was installed with Rails 4.2.1.

I expected to be able to install the latest version,
Please review the description of the installation procedure.

https://guides.rubyonrails.org/getting_started.html#installing-rails

**Comment by shingonnw** [comment]
実際のissueの内容

Installation instructions using Tokaido should not be described #36118

Expected behavior
When installing Rails with getting started guide, latest version should be installed.

Actual behavior
When installing using "Tokaido", it was installed with Rails 4.2.1.

I expected to be able to install the latest version,
Please review the description of the installation procedure.

**Comment by makicamel** [comment]
「とりあえずRailsはじめる」という時に4.2.1が入ると:smile::joy::star:ではなくなると思うので、
とってもよいと思います！！🎉
