### ISSUE TITLE
OSS Gate Workshop: TOKYO: 2019-04-27: dasman74: Vim: Work log

### ISSUE THREAD

**Issue by dasman74** [oss-gate/workshop#1191]
## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2019-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by dasman74** [comment]
### windowsにvimのインストール
公式サイトでインストール方法を探す
https://www.vim.org/

downloadリンクから
https://www.vim.org/download.php

PC: MS-DOS and MS-Windowsからダウンロード
vim-win32-installer

以下に遷移
https://github.com/vim/vim-win32-installer/releases

64-bit installerを選択

exeをクリック
「Windows によって PC が保護されました」と表示された

詳細情報をクリック
インストールができた。

**Comment by dasman74** [comment]
## CentOS6.xにインストールしてみる。

**Comment by dasman74** [comment]
https://www.vim.org/download.phpでインストール手順がある

**Comment by dasman74** [comment]
github からインストール
```
git clone https://github.com/vim/vim.git
cd vim/src
make
```

**Comment by dasman74** [comment]
makeしたけど失敗した

**Comment by okuramasafumi** [comment]
`make`自体に失敗したのか、`make`はできたけどバイナリが使えないのかは整理したほうが良さそうですね。

**Comment by dasman74** [comment]
make したときのログ　gist
https://gist.github.com/dasman74/cbf416236670230ab11e3f2006e11be1

**Comment by shimadama** [comment]
vim、僕も興味あるので見てます！

**Comment by dasman74** [comment]
# フィードバック
## やったこと
vimの公式サイトからcentosへのインストール手順を確認してインストールしたが、makeで失敗した。
https://www.vim.org/download.php#pc

インストール手順
```
git clone https://github.com/vim/vim.git
cd vim/src
make
```

## make実行時の内容
https://gist.github.com/dasman74/cbf416236670230ab11e3f2006e11be1

```
[vagrant@localhost src]$ make
Makefile:304: auto/config.mk: No such file or directory
rm -f auto/config.cache
...
```

## 環境
windows10にvagrantで用意したCentOS6x

**Comment by dasman74** [comment]
## Downloading Vim公式サイトについて
公式のインストール手順に沿ってCent OSにインストールしたが、makeで失敗した。
https://www.vim.org/download.php

```
git clone https://github.com/vim/vim.git
cd vim/src
make
```
エラー内容
```
[vagrant@localhost src]$ make
Makefile:304: auto/config.mk: No such file or directory
rm -f auto/config.cache
...
```
https://gist.github.com/dasman74/cbf416236670230ab11e3f2006e11be1
しかし、以下のページに`sudo make install`の説明があり、`sudo make install`を実行したらinstallができた。
https://www.vim.org/git.php

```
cd src
make distclean  # if you build Vim before
make
sudo make install
```

要望、vim公式サイトについてissueを起こせるリポジトリが欲しい。


# 英語版

## Download about Vim official site
I installed on Cent OS according to the official installation procedure, but failed with the make command.

https://www.vim.org/download.php

```
git clone https://github.com/vim/vim.git
cd vim/src
make
```
エラー内容
```
[vagrant@localhost src]$ make
Makefile:304: auto/config.mk: No such file or directory
rm -f auto/config.cache
...
```
https://gist.github.com/dasman74/cbf416236670230ab11e3f2006e11be1
However, there is a description of `sudo make install` on the following page, and if I run` sudo make install`  I can install it.
https://www.vim.org/git.php

```
cd src
make distclean  # if you build Vim before
make
sudo make install
```

## Request
I want a repository that can make issues on the vim official site.

**Comment by okuramasafumi** [comment]
https://groups.google.com/forum/#!forum/vim_dev
↑のグループに投げてみるといいかもしれない…

**Comment by dasman74** [comment]
ありがとうございます
