### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: hide-furusawa: Shrine: Work log

### ISSUE THREAD

**Issue by hide-furusawa** [oss-gate/workshop#1192]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by okuramasafumi** [comment]
https://github.com/shrinerb/shrine

**Comment by okuramasafumi** [comment]
https://min.io/
↑これをインストールしないと、S3のアカウントを取得しなくてはいけなくなる。

**Comment by hide-furusawa** [comment]
https://github.com/shrinerb/shrine.git
bundle install
rbenv install -v 2.4.0
gem install bundler
brew install imagemagick

**Comment by hide-furusawa** [comment]
sequel -m db/migrations sqlite://database.sqlite3
→ bundle exec sequel -m db/migrations sqlite://database.sqlite3

**Comment by hide-furusawa** [comment]
S3を擬似的にあげるため、minio
brew minio
minio server ~/minio/

**Comment by hide-furusawa** [comment]
touch .env
S3_ACCESS_KEY_ID="VJ76JK3IL2P66XNDL9CR"
S3_SECRET_ACCESS_KEY="d5RgFUAXOA9OjoxjBob8lDCSOxLmg6ieJ2jip77z"
S3_REGION="ap-northeast-1"
S3_BUCKET="oss gate"

**Comment by shingonnw** [comment]
minioの手順がなかったというところが課題ですかね

**Comment by okuramasafumi** [comment]
ドキュメントが結構抜けがありましたね。

**Comment by hide-furusawa** [comment]
If do not have amazon S3, I want the explanation of procedure.
For example, use minio.
`https: // min.io /`

Here is how to use it.
to install
`brew install minio`

After installation. start minio
`minio server ~/minio/`

AccessKey and SecretKey is displayed in console log
Set to env file.
`AccessKey: xxxxxxxxxxxxxxxxxx 
SecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by hide-furusawa** [comment]
https://github.com/shrinerb/shrine/issues/377

**Comment by hide-furusawa** [comment]
https://github.com/shrinerb/shrine/pull/378
