### ISSUE TITLE
OSS Gateワークショップ 2016-9-24: hi6o: devise: 作業ログ

### ISSUE THREAD

**Issue by takitsuba** [oss-gate/workshop#120]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by hi6o** [comment]
・作業（やること、やっていること、やったこと。）
　扱うOSSをdeviseに決めた
　deviseをインストールする前に、rails5をインストールしようと思う。
・思っていること（そのときどう思っているか。）
　rails5のインストール方法について、ググろう。

**Comment by hi6o** [comment]
・作業
下記のサイトを参考に、rails5をインストールする。
http://qiita.com/gaku3601/items/5a484043f9c803ce9941

・思っていること
とりあえずやってみよう

**Comment by hi6o** [comment]
・作業
rubyの最新版と、railsの最新版をインストール中。
ちょうど終了した

・思っていること
rails newしてみよう。

**Comment by hi6o** [comment]
・作業
rails newした。
gemにdeviseを記載の上、bundle installした。

・思っていること
動くようにしよう。

**Comment by hi6o** [comment]
・作業
deviseのgithub readmeページを見ながら、configの設定をした。
https://github.com/plataformatec/devise

・思ったこと
言われた通りに動かしてみよう。

**Comment by hi6o** [comment]
・作業
readmeページを見ながら、Userモデルを作成

・思ったこと

**Comment by hi6o** [comment]
・作業
routesファイルにroot to: 'home#index'を記載。

・思ったこと
この段階ではまだコントローラーを作成していないため、わかりづらいようにも思う。

**Comment by hi6o** [comment]
・作業
devise viewsの作成

・思ったこと
英語がわかってないな

**Comment by hi6o** [comment]
・作業
rails g devise:controllers users
を実行。

Running via Spring preloader in process 99357
      create  app/controllers/users/confirmations_controller.rb
      create  app/controllers/users/passwords_controller.rb
      create  app/controllers/users/registrations_controller.rb
      create  app/controllers/users/sessions_controller.rb
      create  app/controllers/users/unlocks_controller.rb
      create  app/controllers/users/omniauth_callbacks_controller.rb
===============================================================================

Some setup you must do manually if you haven't yet:

  Ensure you have overridden routes for generated controllers in your routes.rb.
  For example:

    Rails.application.routes.draw do
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
    end

===============================================================================

のメッセージ。

・思ったこと
1と2の順番を逆にしてもいいかも

**Comment by hi6o** [comment]
・作業
Controllerの作成まで実施

・思ったこと

**Comment by hi6o** [comment]
・作業
サインアップ機能の実装までできた。

・思ったこと
deviseについてもだが、railsについてもわかってないな・・・

**Comment by hi6o** [comment]
・作業
サインアップの実装をやる際に、root周りの設定で戸惑った。

・思ったこと
途中でhome#indexなどの記載をしたが、無駄だったように思う。
英語の説明文をもう一度読んでみよう

**Comment by hi6o** [comment]
・作業
readme ページを再度読み直している

・思ったこと
どこまで行けば動くようになるのかわからなかった。
最低限動くようにするのに必要な作業を上にまとめた方がいい？

**Comment by hi6o** [comment]
・作業
readme ページの読み直し

・思ったこと
MODELと[scope]の表記乱れ
bundle installを記載
についてはissueを上げてもいいかもしれない。

**Comment by hi6o** [comment]
・作業
bundle installを記載した方が良い、ということについて、まとめる。

--------
タイトル：READMEのbundleコマンドの表記について

READMEの98行目「Run the bundle command to install it.」の記載について、「Then run ' bundle install'」との記載に変えた方が良いと思いました。

理由
1）同123行目では「Then run 'rake db:migrate'」のように記載している
2）コマンドはグレーアウトした方が目立つため、実行もれが減るのでは。

--------

**Comment by hi6o** [comment]
・作業
プルリクとissueを作成の上投げた。

・思ったこと
引き続き、MODELと[scope]の表記について考える。

**Comment by takitsuba** [comment]
本日pull requestをmergeいただきました。
https://github.com/plataformatec/devise/pull/4307#issuecomment-254923226

ありがとうございました！

**Comment by kou** [comment]
さすがです！
これからもOSSの開発に参加していってください！

ところで11月26日の予定は空いていますか？
[次回のOSS Gateワークショップ](https://oss-gate.doorkeeper.jp/events/50539)はメンターで参加してみませんか？次回もビギナー多数でメンターが足りていないのです。

**Comment by emorima** [comment]
@takitsuba mergeおめでとうございます～! :tada:
