### ISSUE TITLE
OSS Gate広島ワークショップ2019-08-04

### ISSUE THREAD

**Issue by Nyoho** [oss-gate/workshop#1212]
## やること

- 会場: 広島大学東千田キャンパス (教室調整中)
- 時間: 10:30-17:00
- 内容: 1日ワークショップをやる
- 会場係: @Nyoho
- 進行役: @knokmki612
- このイベントに関する窓口: @Nyoho
- [x] https://github.com/oss-gate/retrospective/issues/122#issuecomment-505419681 を監視して @knokmki612 さんの来広を検知する
- [x] Doorkeeperのイベント作成: @knokmki612
- [x] Doorkeeperイベント公開 @Nyoho https://oss-gate.doorkeeper.jp/events/94891
- メッセージ作成: @Nyoho 
  - [ ] 会場案内(?/??までにやる): @Nyoho 
  - [ ] サポーター募集(必要に応じて)(8/??までにやる): @Nyoho 

## 会場設備確認

参考：[ワークショップ会場の提供](https://oss-gate.github.io/sponsors/wanted.html#workshop-space)

- [x] 10人以上座れる机と椅子（参加人数が20人を超えることはほとんどありません）
- [x] プロジェクタと投影できるところ (スクリーンじゃなくとも見えればOKです！)
- [x] WiFi (ゲストアカウント人数分取得済み @Nyoho)
- [x] 電源のコンセント4つ(2つ口が2カ所)
- [ ] 電源タップがないので、各自可能な限り持参することを連絡 (@Nyoho が2本持っていく)
- [x] A棟自由に入れます
- [x] プロジェクタの入出力端子 (RGB) (プロジェクタはないので @Nyoho が持っていく)
- [x] 40インチぐらいのモニタにRGB接続可能

**Comment by knokmki612** [comment]
私の訪広の日程についてですが、7/28〜8/9までのどこかの1週間あたりを今のところ考えています

**Comment by Nyoho** [comment]
了解です!
そうしますとワークショップなら 8/3, 8/4 のどちらかですかね。

**Comment by knokmki612** [comment]
> そうしますとワークショップなら 8/3, 8/4 のどちらかですかね。

そうなりますね！では8/3か8/4のつもりで考えておきますね。次は会場探しになりますかね？

**Comment by Nyoho** [comment]
ですね! 会場は広島大学の東千田キャンパスなら僕が楽に借りられます。

あとは口コミで参加者を募ってみてどちらの日がいいか考えていきます!

**Comment by knokmki612** [comment]
> 会場は広島大学の東千田キャンパスなら僕が楽に借りられます。

あっ個人的にめっちゃ行きやすいです...！

> 口コミで参加者を募ってみてどちらの日がいいか考えていきます!

了解です！

**Comment by knokmki612** [comment]
私の広島の滞在日程は8/1～8/9に確定しました。

**Comment by Nyoho** [comment]
了解です!! 8/3か8/4の調整を加速します!

**Comment by knokmki612** [comment]
イベント作りました！
会場が決まったら会場の入力や、今回初めてワークショップを開催するにあたってなにか書いておきたかったり文言を変えたいところがあったら変えてみてください！

https://oss-gate.doorkeeper.jp/events/94891

**Comment by Nyoho** [comment]
@knokmki612 作成ありがとうございます! こっちで運営をやりそうな人に3,4選択を迫ってます。
一人は両方OK確定です。

**Comment by knokmki612** [comment]
@Nyoho 
私もgitter.im/hiroshimaのルームjoinしてるんですが、今のところ反応なさそうですね。日程を決めてイベント公開してビギナーとサポーターを募集してもいい気がします。
応募して参加してくださるサポーターから運営を一緒にやってくれそうな人を見つけられたらいいですね！

**Comment by knokmki612** [comment]
イベント準備用のissueテンプレートがちょっと前にできたので、そこにあった会場設備確認の欄を足しておきました。

**Comment by Nyoho** [comment]
@knokmki612 設備確認の欄、ありがとうございます!
メッセージでもう一人ゲットしたところでした。
ではえいっと日程を決めてしまいます! 8月4日日曜日で!

**Comment by Nyoho** [comment]
タイトル変更

```diff
-8月(2019)のどこかで広島でワークショップをやる準備をする
+OSS Gate広島ワークショップ2019-08-04
```

**Comment by knokmki612** [comment]
> メッセージでもう一人ゲットしたところでした。

おお！

> ではえいっと日程を決めてしまいます! 8月4日日曜日で!

Doorkeeperのイベント名や会場名もあわせて変更してありますね！さすがです！
Nyohoさんのタイミングで公開お願いします！

**Comment by Nyoho** [comment]
> Nyohoさんのタイミングで公開お願いします！

了解です!

**Comment by Nyoho** [comment]
公開しました。 https://oss-gate.doorkeeper.jp/events/94891

**Comment by knokmki612** [comment]
そういえば進行役を自分に割り当てておくの忘れてたので割り当てておきました！

なんで私がやるかというと、新しくやる地域で開催経験者がひと通りやりつつ、これから開催していく人たちと協力することで色々なところを参考にしてもらうため CC: @kou

**Comment by knokmki612** [comment]
@Nyoho 
ビギナーの参加登録きましたね！やったー！
ビギナー枠の初期値0人なので、イベントの管理ページ->参加者一覧->ビギナーの方のメンバーページに行って、「キャンセル待ちから本申し込みに変更」で繰り上げてください！

今回はサポートメンターも自分がやるつもりなので、現在のサポーター3人から1引いた人数まで繰り上げ可能ですね！

![image](https://user-images.githubusercontent.com/9744580/61714942-f34b2a80-ad96-11e9-86fa-0285ee6bee8d.png)

**Comment by Nyoho** [comment]
進行役、それはとてもありがたいです!
声を掛けて(だぶん)参加してくれる二人は、大阪かどこかのOSS Gateに参加しており経験者ですので、僕がただ一人サポータ完全未経験です。

あとは地元にあるいくつかの勉強会コミュニティにちょっとずつ宣伝していこうと思います。
この辺を参考にして説明文をこれから作文します。

OSS（オープンソースソフトウェア）の開発に参加したいあなたへ：新春特別企画｜gihyo.jp … 技術評論社 https://gihyo.jp/dev/column/newyear/2018/start-oss-development

**Comment by Nyoho** [comment]
「キャンセル待ちから本申し込みに変更」、ぼくにもできました! (こどもかっ)

**Comment by knokmki612** [comment]
> 声を掛けて(だぶん)参加してくれる二人は、大阪かどこかのOSS Gateに参加しており経験者ですので、僕がただ一人サポータ完全未経験

なるほど！そしたらどんな風に協力していくといいのかなー。当日皆さんとお会いしてから考えますかね

**Comment by knokmki612** [comment]
@kou 当日どんなことを私がやるといいのかアドバイスがあったら助かります！

**Comment by Nyoho** [comment]
宣伝文章推敲中です。「これ違うんじゃない?」などご指摘いただければ幸いです。> all

```txt
Subject: ㊗️広島初開催 - OSS Gate広島ワークショップを開催します!

RCC『イマなまっ!』月曜日コメンテータ
ハイパ・メディア・トランスレータ
の Nyoho こと北䑓如法(きただいゆきのり)と申します。

「OSS Gate広島ワークショップ2019-08-04」というワークショップを開催しますので
お知らせいたします。


OSS Gate広島ワークショップ2019-08-04
https://oss-gate.doorkeeper.jp/events/94891 (お申し込みはこちらから)
●日時: 2019年8月4日(日) 10:30 -- 17:00
●場所: 広島大学 東千田キャンパス (部屋調整中) 
●参加費: 無料

OSS Gate、ついに広島初開催!

「OSS Gate」は、OSS (オープンソース・ソフトウェア)の開発に参加する人を継続的に増やす取り組みです。
「OSS Gate ワークショップ」は「OSSの開発に参加する」ことを実際に体験するワークショップです。

この機会に広島でOSS Gateに参加してみませんか?

OSS Gate ワークショップでは、

- OSSの開発に初めて参加する人を「ビギナー」
- 既にOSSの開発に参加していて、ビギナーをサポート人を「サポーター」

とそれぞれ呼び、ビギナーがOSS開発に参加する「門 (gate) をくぐる」ことをサポーターがサポートします。

■ くのきみさん参戦

今回は、東京でOSS Gateワークショップを何度も開催されている、くのきみさん (@knokmki612) もサポーターとして参加されます。

是非ともこの機会に、広島で、
OSS開発に参加してみたいと思っているけど今までしてこんかったのうとか、
OSS開発ってどんなもんなんじゃろうとかいう興味があるとか、
なんかOSSにもうちょっと近づいてみませんか?

■ OSS開発って難しくないん?

OSSの開発に参加すると言っても、
プログラムをゴリゴリ書くだけがOSS開発の参加ではありません。

- あるOSSドキュメント通りに動かそうとしたら1カ所手順が違っているところがあったので、そこを指摘するレポートメールを書いた/GitHubにissueを立てた。
- バグがあることに気付いたので、バグレポートのissueを立てた。
- ドキュメントの日本語訳がついてないところをちょこっと書いてみた。

など、参加の形はいろいろあります!

次に、 https://gihyo.jp/dev/column/newyear/2018/start-oss-development に書いてあった、
OSSの開発に参加することにまつわるグッとくるフレーズを抜き出します。

■ OSS開発に参加する理由は、人それぞれでいい。

■ 体験すれば、気軽になれる。

■ 誰にでも、絶対初めてのときがあった。

■ 他の人と一緒に、やってみる。

■ あとは、あなたが歩き出すだけ。

※句読点は僕(Nyoho)が付けました。『プロフェッショナル 仕事の流儀』っぽくなったと思います。
```

**Comment by knokmki612** [comment]
> - 既にOSSの開発に参加していて、ビギナーをサポート人を「サポーター」

サポート「する」人ですね！

要所のキャッチーな文言が告知らしくていいと思いました！

**Comment by Nyoho** [comment]
おおっと! なおしました!
ありがとうございます!

**Comment by knokmki612** [comment]
あ、あともう1点！

> OSS Gate、ついに広島初開催!

ここは「OSS Gate」だとイベントではなく取り組みを指すので、

> OSS Gate、ついに広島初上陸!

か

> OSS Gateワークショップ、ついに広島初開催!

が適切です！

**Comment by Nyoho** [comment]
ありがとうございます。そうだと思いながらそこ間違えてしまいました!

**Comment by kou** [comment]
> 当日どんなことを私がやるといいのかアドバイスがあったら助かります！

事前（ワークショップの最初でもいいです）に、今回参加するサポーターのみなさんに「次回はみなさんのうちのだれか（1人以上）が進行役になるので、今回は自分が進行役をやるならどこらへんはうまくできそうで、どこらへんはうまくできなそうかもと考えながら参加してね」みたいなことを伝えておくのがよいと思います。

進行しながら、「あ、今、私は○○に気をつけて進行していますよー」というのをはさみながら進行するとよいと思います。そうすれば、「あぁ、ここでは○○に気をつけるのか」というのを実感をもって伝えることができると思います。たとえば、ミニふりかえりのときは多少予定時間より過ぎても急かせないで他のところで調整するようにしているとか、この説明のときは自分の体験談を自分の言葉で話すようにアレンジしているとか。

終わったら（最後のアンケートを見ながらふりかえりのときでもいいと思います）、サポーターのみなさんとできそうだった？聞いておきたいことはある？みたいな話をして、進行役の障害になりそうなことを取り除いてから帰ってくるとよいと思います。

**Comment by kou** [comment]
> OSS（オープンソースソフトウェア）の開発に参加したいあなたへ：新春特別企画｜gihyo.jp … 技術評論社 https://gihyo.jp/dev/column/newyear/2018/start-oss-development

なんか見たことがある気がするなと思ったら私が書いたやつか！

**Comment by nishimotz** [comment]
Doorkeeper 「チャットで相談してください」のリンク先が tokyo になっていますが、
gitter の hiroshima ルームにしてはどうでしょうか？

**Comment by kou** [comment]
管理者にinviteしておいたのでacceptして自分で直してみてください！

**Comment by nishimotz** [comment]
Doorkeeper チャットのリンク先を更新しました！

**Comment by kou** [comment]
さすがです！

**Comment by Nyoho** [comment]
@nishimotz さんありがとうございました!

**Comment by knokmki612** [comment]
@kou 
アドバイスありがとうございます！
前回自分が進行役をした時を思い出して、意識しているところを言語化できるように準備します！

**Comment by Nyoho** [comment]
さきほどビギナー申込を本申し込みに変更しました。
これでビギナー3人! 広島にしては既に上出来なのでは!

**Comment by knokmki612** [comment]
ビギナーの申し込みもう1人増えたのと、問い合わせも来ていますね！今回は参加する人をなるべく多くする方針で、1:1にこだわらないほうがいいのかな…？

**Comment by Nyoho** [comment]
華麗に「本申し込みに変更」をしました。
すごくいい感じですね!

問い合わせは、Doorkeeperのことがわかっておらず、イベントへの問い合わせに紐付いているのか、コミュニティ全体にしか紐付いていないのかわかりませんでした。でもきっとこのイベントへの問い合わせですよね。

**Comment by knokmki612** [comment]
今回のようなグループへの問い合わせはイベントことに送るがないので、管理メンバー全員に届きますね。

もしよければ参加を勧める方向で明日メッセージを書きます！

**Comment by Nyoho** [comment]
なるほど!

僕も素案を書いてみようかと思い、内容を相談しようと思いましたが、このリポジトリ (oss-gate/workshop) はパブリックだと具体的な内容はここには書かない方がいいですよね。

**Comment by knokmki612** [comment]
> 僕も素案を書いてみようかと思い、内容を相談しようと

いいですね！自分は書かずに協力します！gitterでdmできるのでそっちでやりましょう！

**Comment by Nyoho** [comment]
Gitterのdmで相談させていただいて返信しました。

**Comment by Nyoho** [comment]
「キャンセル待ちから本申し込みに変更」やってしもうていいですかね。

**Comment by knokmki612** [comment]
今回は1:2でやることにして繰り上げましょう！

**Comment by Nyoho** [comment]
ラジャ。繰り上げました。

**Comment by knokmki612** [comment]
ここ数日でサポーターが増えましたね！すごい！

**Comment by Nyoho** [comment]
ちょこちょこお誘いをかけました!

**Comment by Nyoho** [comment]
-  WiFi (ゲストアカウント人数分取得済み @Nyoho)
-  電源のコンセント4つ(2つ口が2カ所)
-  電源タップがないので、各自可能な限り持参することを連絡 (@Nyoho が2本持っていく)
-  プロジェクタの入出力端子 (RGB) (プロジェクタはないので @Nyoho が持っていく)
-  40インチぐらいのモニタにRGB接続可能

**Comment by Nyoho** [comment]
初回なので終了後に有志で懇親会開催可能か募ってみてもいいかなあと思っているところですが、そもそも @knokmki612 さんの終了後のご都合はいかがですか?

**Comment by knokmki612** [comment]
@Nyoho 懇親会あれば確実に参加します！

会場設備について質問があります(前日になってすみません…！)

プロジェクターに使う端子はrgbとありますがvgaですかね？持ってきているラップトップで使える出力端子がHDMIだけなので、必要があれば変換アダプタを今日中にどこかで調達しますよ

モニター/プロジェクターを使用するのはスライドなどを表示する私だけの予定で、モニターとプロジェクターはどちらかがあれば大丈夫ですよ！

**Comment by Nyoho** [comment]
@knokmki612 懇親会了解です! とりあえず案内出してみます。
ざっと、これまでの懇親会の人数カウントにはDoorkeeperは使われてなさそうでしたが、これまで人数カウントどうやっておられましたか?

アナログRGBのVGAだと思われます。持参しているプロジェクタにHDMIがありました! 
「mini Display port -> アナログRGB」であれば僕が変換を持っています。

**Comment by nishimotz** [comment]
申込キャンセルされた方から私あてに Twitter DM で連絡をいただきました。
熱中症でダウンされたとのことで、お大事にとお返事しました。

**Comment by Nyoho** [comment]
@nishimotz 承知いたしました。ご対応ありがとうございました。我々も体調に気をつけないといけませんね。
(あとここはpublicなので適当なところで一部伏せ字に編集したりしておいてください)

**Comment by knokmki612** [comment]
熱中症は気をつけます…

@Nyoho 

> 持参しているプロジェクタにHDMIがありました!

おお！ケーブルを持ってきていないので買ったほうがよいでしょうか？

**Comment by knokmki612** [comment]
> これまでの懇親会の人数カウントにはDoorkeeperは使われてなさそうでしたが、これまで人数カウントどうやっておられましたか?

イベント終了時にその場でカウントですね。イベント申込時に懇親会への参加可否はとってないです。

Doorkeeperのフォーム機能でとれるので今後はやっても良いかもしれませんね。

**Comment by knokmki612** [comment]
あと、イベントの最後にアンケートを回答してもらって集計するのですが、その際のアンケートの設問に「懇親会に参加されますか？」みたいなのを追加するのもありかもしれません。

**Comment by Nyoho** [comment]
@knokmki612 
HDMIケーブル、僕が持っていきます。(プロジェクタの袋に入っているかと思ったらなかった(笑))

懇親会、終了後でその場でということ、了解です。

**Comment by knokmki612** [comment]
> HDMIケーブル、僕が持っていきます。

ありがとうございます！会場案内や問い合わせへの返信もありがとうございます！

**Comment by Nyoho** [comment]
開催できました。皆様ありがとうございました! > all
