### ISSUE TITLE
8月のオンラインミートアップの準備

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1218]
## 開催内容

- [イベントページ](https://oss-gate.doorkeeper.jp/events/TODO)
- 会場: オンライン
- 時間: 2019-08-DDT19:30/21:30
- 会場係: なし
- このイベントに関する窓口: @knokmki612 

### イベント中の参加方法

1. まずissueにやることを書く
2. issueにdiscordの招待urlをのせるのでdiscordに入ってもらう
3. イベント用のdiscordのボイスチャンネルとテキストチャンネルに入ってもらう

発声OKな人以外はマイクミュートで良い

## やること

- [x] Doorkeeperのイベントページ作成（開催の1ヶ月前までにやる）： @
- [x] 日程を決める

## 気になっていること

- あったら書く

**Comment by knokmki612** [comment]
#1217 をやったときに @swamp09 さんと8月のミートアップはオンラインにしようという話をしていたので、やりたい

@tdtds 興味持ってもらえそうだったので、もしよかったら参加しませんか？

自分は https://github.com/oss-gate/retrospective/issues/118 を多分やります

**Comment by knokmki612** [comment]
今のところ日程は金曜日以外というところまで決まっていて、私はどの日でも大丈夫です

**Comment by tdtds** [comment]
参加するとしたら職場に居残ってやるので、voice chatとかには参加できそうにないんですよね。text chatや画面共有くらいなら参加できると思います。やるなら同じく https://github.com/oss-gate/retrospective/issues/118 か、tdiaryのドキュメント整備かなー。

**Comment by knokmki612** [comment]
> voice chatとかには参加できそうにない

誰かが話しているのを聞くだけ、という形なら参加できそうですか？参加できなさそうであればボイスチャンネルに入らず参加で大丈夫です

**Comment by tdtds** [comment]
いいっすよ、常時ってわけにはいかないけど。

**Comment by knokmki612** [comment]
ありがとうございます！

@swamp09 @tdtds 
日程の候補を試しに出してみますが、8月の5,7,8のどれかとかでどうでしょう？

**Comment by tdtds** [comment]
今のところどれでもOKです

**Comment by swamp09** [comment]
私もどこでも大丈夫です

**Comment by knokmki612** [comment]
ありがとうございます！8/5に設定してイベントページを公開しました。 https://oss-gate.doorkeeper.jp/events/95365

Discordへの招待はissueじゃなくてDoorkeeperメッセージからやることにしました。参加する人だけに招待が見える形で

そもそもDiscord誰でも入れるようにしたほうがいいのかも分かってないですが、あとから誰でも入れるようにするのは簡単なので、とりあえず参加する人だけ入る方針です

**Comment by tdtds** [comment]
終了したミートアップのissueだったのでcloseしときます。
