### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-07-27: godan: sao-clasp: Work log

### ISSUE THREAD

**Issue by Godan** [oss-gate/workshop#1221]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
よろしくおねがいします！

**Comment by Godan** [comment]
https://github.com/takanakahiko/sao-clasp  とりあえず最新にして動かす

**Comment by Godan** [comment]
ローカルのnpm自体がちょっと古かったのでアップデート

**Comment by Godan** [comment]
`npm test`で落ちるん…

**Comment by Godan** [comment]
```
% (*'-')<3 npm run test                  [~/dev/sao-clasp]+[master]

> sao-clasp@0.3.2 test /Users/shogo.matsushita/dev/sao-clasp
> ava



  1 test failed

  defaults

  /Users/shogo.matsushita/dev/sao-clasp/test/test.js:8

   7: test('defaults', async t => {                  
   8:   const stream = await sao.mockPrompt(template)
   9:                                                

  Rejected promise returned by test. Reason:

  TypeError {
    message: '_sao.default.mockPrompt is not a function',
  }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sao-clasp@0.3.2 test: `ava`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sao-clasp@0.3.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shogo.matsushita/.npm/_logs/2019-07-27T02_33_25_543Z-debug.log
```

**Comment by Godan** [comment]
他のsao-template projectのテストをみる

**Comment by Godan** [comment]
他のはちゃんと動くので 本当に存在しないわけではなさそう

**Comment by Godan** [comment]
https://saojs.org/guide/testing-generators.html#sao-mock-input-answers-references  SAOドキュメントにテスト関係のをみつけたので ちょいとためす

**Comment by Godan** [comment]
sao.mockで生成するほうでやるとエラーっぽい遠方をするようになってきたのでちょっと通る状態まで持っていく
```
% (*'-')<3 yarn run test                                                                                     [~/dev/sao-clasp]+[master]
yarn run v1.12.3
$ ava


  1 test failed

  defaults

  /Users/shogo.matsushita/dev/sao-clasp/test/test.js:11

   10:                                               
   11:   t.true(stream.fileList.includes('index.js'))
   12: })                                            

  Value is not `true`:

  false
```

**Comment by Godan** [comment]
passed!

```
% (*'-')<3 yarn run test                                                                                     [~/dev/sao-clasp]+[master]
yarn run v1.12.3
$ ava


  1 test passed

✨  Done in 2.57s.
```

**Comment by naruoga** [comment]
ここまで行けたのは素晴らしいですね！ テストが通るようになったところで一度PR出すのがいいかと思います :)

**Comment by Godan** [comment]
とりあえずコミットして自分のリポジトリにpushする

**Comment by Godan** [comment]
```
Author: godan <matsushita@godan.xyz>
Date:   Sat Jul 27 13:48:11 2019 +0900

    Fix rewrite test file
```
commit message

**Comment by knokmki612** [comment]
https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by Godan** [comment]
Thx!

**Comment by Godan** [comment]
```
hi, i fix test file.

## Description
テストが昔の書き方みたい。  
落ちていたので、ドキュメントを見て新しい書き方に直しました。
👀 also see:  [Testing Generators | SAO](https://saojs.org/guide/testing-generators.html#sao-mock-input-answers-references)

## Motivation and Context
自分がコントリビューションしようとしたときに最初のテストで落ちてしまったので、その修正です。

```
英語に書き直していく

**Comment by Godan** [comment]
```
hi, i fix test file.

## Description

The test looks like the old writing.
i fixed test file while referring sao documents.

👀 also see:  [Testing Generators | SAO](https://saojs.org/guide/testing-generators.html#sao-mock-input-answers-references)

## Motivation and Context

It was a fix, becauseI fell in the first test when I tried to contribute.

```

**Comment by knokmki612** [comment]
I was motivated by my first run of `npm test` was failed

**Comment by Godan** [comment]
Hi, I fix test file.

## Description

The test looks like the old writing.
I fixed test file while referring sao documents.

👀 also see:  [Testing Generators | SAO](https://saojs.org/guide/testing-generators.html#sao-mock-input-answers-references)

## Motivation and Context

I was motivated by my first run of npm test was failed

**Comment by Godan** [comment]
これでおくりますー

**Comment by Godan** [comment]
sended! 🎉  https://github.com/takanakahiko/sao-clasp/compare/master...Godan:change/test?expand=1
