### ISSUE TITLE
OSS Gate Workshop: tokyo: 2019-07-27: takashi-miyahara: activerecord-import: Work log

### ISSUE THREAD

**Issue by takashi-miyahara** [oss-gate/workshop#1222]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
よろしくおねがいします！

**Comment by takashi-miyahara** [comment]
Licence
https://github.com/zilkey/active_hash/blob/master/LICENSE

**Comment by takashi-miyahara** [comment]
active_hashでググって、3番目に公式と思われるgithubのページを見つけた
https://github.com/zilkey/active_hash

**Comment by takashi-miyahara** [comment]
READMRを読みます
https://github.com/zilkey/active_hash/blob/master/README.md

**Comment by takashi-miyahara** [comment]
このissueが気になっていて、試してみる
https://github.com/zilkey/active_hash/issues/176

**Comment by takashi-miyahara** [comment]
activerecord-importを、Ruby2.6.3、Rails6.0rc2化してみたい
https://github.com/zdennis/activerecord-import/commit/99d49b4b4579e3f93519ed58defe78c47cf9dcaf

**Comment by takashi-miyahara** [comment]
READMEを読みます。
https://github.com/zdennis/activerecord-import/blob/master/README.markdown

**Comment by takashi-miyahara** [comment]
rc2が出ているので、修正PRを送ってみたい。
https://rubygems.org/gems/activerecord

https://github.com/zdennis/activerecord-import/blob/master/gemfiles/6.0.gemfile

**Comment by takashi-miyahara** [comment]
Contributingの仕方を調べる

**Comment by takashi-miyahara** [comment]
テストが失敗している
https://travis-ci.org/zdennis/activerecord-import/jobs/552287397

**Comment by takashi-miyahara** [comment]
原因は、splite3の`1.4.0`をインストールしようとしており、これをまず解消したい。

**Comment by takashi-miyahara** [comment]
以下のようなコードであった。
```Gemfile
sqlite3_version = '1.3.0'
sqlite3_version = '1.4.0' if version >= 5.1

# Database Adapters
platforms :ruby do
  gem "mysql2",                 "~> #{mysql2_version}"
  gem "pg",                     "~> 0.9"
  gem "sqlite3",                "~> #{sqlite3_version}"
  gem "seamless_database_pool", "~> 1.0.20"
end
```

splite3の`1.4.0`がインストールされるようになっていたので、`1.3.6`系をインストールするように修正した。

```Gemfile
# Database Adapters
platforms :ruby do
  gem "mysql2",                 "~> #{mysql2_version}"
  gem "pg",                     "~> 0.9"
  gem "sqlite3",                "~> 1.3.6"
  gem "seamless_database_pool", "~> 1.0.20"
end
```

**Comment by takashi-miyahara** [comment]
PRの下書き

Title
Fix  sqlite3's version to 1.3.6 series

Description
# Why am I getting this PR?
The automatic test seems to have failed.
![image](https://user-images.githubusercontent.com/12161701/61990069-2da51800-b074-11e9-8f0f-1db0d92297ab.png)
https://travis-ci.org/zdennis/activerecord-import/jobs/552287397


The cause is in splite3.
Rails 5.2 does not yet support splite3 1.4 series.
https://github.com/rails/rails/issues/35153
Therefore, I modified it to use sqlite3 1.3.6 series.

Thanks for making your project Open Source! Any feedback is greatly appreciated.

**Comment by knokmki612** [comment]
https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by takashi-miyahara** [comment]
日本語版の下書き

# Description
Rails5.1以上であれば、splite3の`1.4`系をインストールしようとしている。
しかし、現在のRailsではsplite3の`1.4`系をまだサポートしていません。
そのため、splite3のインストールで失敗しています。
![image](https://user-images.githubusercontent.com/12161701/61990198-c0df4d00-b076-11e9-88eb-68ca3a6badf1.png)

# Related Issue
なし

# Motivation and Context
自動テストが失敗しているので、成功するようにします。

# How Has This Been Tested?
自分の手元でインストールして、動作することを確認しました。

**Comment by takashi-miyahara** [comment]
英語版の下書き

title
# Fix sqlite3's version to 1.3.6 series

Description
# Description
If you have Rails 5.1 or higher, you are going to install the `1.4` line of sqlite3.
However, the current Rails does not yet support the sqlite3 `1.4` system.
Therefore, installation of splite3 has failed.
![image](https://user-images.githubusercontent.com/12161701/61990198-c0df4d00-b076-11e9-88eb-68ca3a6badf1.png)
https://travis-ci.org/zdennis/activerecord-import/jobs/552287397

# Related Issue
None

# Motivation and Context
Because the automated test has failed, make it successful.
The way is to install the sqlite3 version `1.3.6`.
rails/rails#35153

# How Has This Been Tested?
I installed it at my own hand and confirmed that it works.

Thanks for making your project Open Source! Any feedback is greatly appreciated.

**Comment by knokmki612** [comment]
> I installed it at my own hand and confirmed that it works.

I tested in my environment as follows and confirmed that it works.

**Comment by takashi-miyahara** [comment]
以下のように修正
I tested in local environment as follows and confirmed that it works.

local environment
OS : macOS 10.14.6
Ruby : 2.5.1p57
Rails : 5.2.3

**Comment by knokmki612** [comment]
when install activerecord-import with rails 5.1, it depends to sqlite3 1.4
but...

**Comment by takashi-miyahara** [comment]
when install activerecord-import with Rails 5.1, it depends to sqlite3 1.4
but Rails does not yet support the sqlite3 1.4 system.
Therefore, installation of splite3 has failed.

**Comment by knokmki612** [comment]
> The way is to install the sqlite3 version 1.3.6.

The solution is...

**Comment by takashi-miyahara** [comment]
英語版の下書き

title
# Fix sqlite3's version to 1.3.6 series

Description
# Description
When install activerecord-import with Rails 5.1, it depends to sqlite3 `1.4`.
But Rails does not yet support the sqlite3 `1.4` system.
Therefore, installation of splite3 has failed.
![image](https://user-images.githubusercontent.com/12161701/61990198-c0df4d00-b076-11e9-88eb-68ca3a6badf1.png)
https://travis-ci.org/zdennis/activerecord-import/jobs/552287397

The solution is to install the sqlite3 version `1.3.6`.
rails/rails#35153

# Motivation and Context
I was worried that the build was an error and fixed it.
https://travis-ci.org/zdennis/activerecord-import

# How Has This Been Tested?
I tested in local environment as follows and confirmed that it works.

local environment
OS : macOS 10.14.6
Ruby : 2.5.1p57
Rails : 5.2.3



Thanks for making your project Open Source! Any feedback is greatly appreciated.

**Comment by takashi-miyahara** [comment]
PRを送ってみた
https://github.com/zdennis/activerecord-import/pull/633

**Comment by takashi-miyahara** [comment]
`trusty`に依存しているかも
```yml
addons:
  postgresql: "9.5"
  apt:
    sources:
      - travis-ci/sqlite3
      - mysql-5.7-trusty
```

**Comment by takashi-miyahara** [comment]
`travis-ci/sqlite3`とう記述方法は廃止されているかも
https://github.com/gradam/django-better-admin-arrayfield/issues/2

**Comment by takashi-miyahara** [comment]
mysqlがインストールされていないのかも
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
The command "sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"" failed and exited with 1 during .
```
