### ISSUE TITLE
OSS Gate Workshoptokyo2019-07-27maika5w2uiWork log

### ISSUE THREAD

**Issue by maika5** [oss-gate/workshop#1224]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mazayo** [comment]
よろしくお願いします

**Comment by maika5** [comment]
* OSSを決める
w2uiのgithubを検索
license.txtを探す→MIT Licenseであることを確認
https://opensource.org/licenses/alphabetical
でMIT LicenseがOSSであることを確認

**Comment by maika5** [comment]
* READMEを読む
https://github.com/vitmalina/w2ui

**Comment by maika5** [comment]
* インストールを行う
browerもしくはnpmがあるか確認。
ないので、brew search w2uiを使う→No formula or cask found for "w2ui".って言われた。

**Comment by maika5** [comment]
* コマンドbowerで検索
https://bower.io/が出てきた。
→インストールにnpmが必要？

**Comment by maika5** [comment]
* npmで検索
https://www.npmjs.com/
→https://www.bulblub.com/2013/04/20/install_nodejs_with_homebrew/

以下のコマンドでインストール
brew install npm

**Comment by maika5** [comment]
npm install w2ui


npm WARN checkPermissions Missing write access to /Library/WebServer/Documents
npm WARN enoent ENOENT: no such file or directory, open '/Library/WebServer/Documents/package.json'
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

npm ERR! path /Library/WebServer/Documents
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Library/WebServer/Documents'
npm ERR!  [Error: EACCES: permission denied, access '/Library/WebServer/Documents'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/Library/WebServer/Documents'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Library/WebServer/Documents'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maika/.npm/_logs/2019-07-27T02_31_27_710Z-debug.log

**Comment by maika5** [comment]
* issueでnpmで検索したが上記のエラーについては見つからない。

**Comment by maika5** [comment]
https://github.com/facebook/reason/issues/1888

**Comment by maika5** [comment]
「Resolving EACCES permissions errors when installing packages globally」
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by maika5** [comment]
上記にそってnpmをreinstall

npm install npm -g

/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.10.2
added 19 packages from 13 contributors, removed 15 packages and updated 45 packages in 6.724s

**Comment by maika5** [comment]
npm install w2ui
npm WARN checkPermissions Missing write access to /Library/WebServer/Documents
npm WARN enoent ENOENT: no such file or directory, open '/Library/WebServer/Documents/package.json'
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

npm ERR! path /Library/WebServer/Documents
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Library/WebServer/Documents'
npm ERR!  [Error: EACCES: permission denied, access '/Library/WebServer/Documents'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/Library/WebServer/Documents'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Library/WebServer/Documents'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maika/.npm/_logs/2019-07-27T02_44_29_930Z-debug.log

**Comment by maika5** [comment]
ディレクトリのオーナの書き換え
https://qiita.com/okohs/items/ced3c3de30af1035242d

**Comment by maika5** [comment]
maika$ npm install w2ui
npm WARN checkPermissions Missing write access to /usr/local
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.

npm ERR! path /usr/local
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/usr/local'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maika/.npm/_logs/2019-07-27T02_53_39_321Z-debug.log

**Comment by maika5** [comment]
* 以下でインストールしたらできた。-gをつけたらできる。
npm install w2ui -g

**Comment by maika5** [comment]
動作確認
http://w2ui.com/web/get-started

Working Exampleの内容を反映確認。
htmlとしてローカルに保存して、ブラウザに表示できるか。

**Comment by swamp09** [comment]
w2uiのリポジトリに、`-g`コマンドをつけてくれたらうれしい、というリクエストを投げられるかも、みたいな話をしました。
npmのリポジトリを見たところ、-gオプションを付けているコマンドが多いので、最近は-gをつけるものなのかもしれない？

**Comment by maika5** [comment]
* READMEにそって「npm install w2ui 」のコマンドでインストールしたところ、エラーが発生した。
* グローバルオプションをつけてインストールをしたところ、インストールすることができた。
* コマンド「npm install w2ui -g」
* 環境：MacOS X（10.14.5）
* エラー内容
npm WARN checkPermissions Missing write access to /usr/local
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.

npm ERR! path /usr/local
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local'
npm ERR! [Error: EACCES: permission denied, access '/usr/local'] {
npm ERR! stack: "Error: EACCES: permission denied, access '/usr/local'",
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/local'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/maika/.npm/_logs/2019-07-27T02_53_39_321Z-debug.log

**Comment by maika5** [comment]
実際に使ったコマンドは文章に入れておく。

**Comment by maika5** [comment]
issueには対応してほしいことや質問を入れる

**Comment by maika5** [comment]
READMEにそって「npm install w2ui 」のコマンドでインストールしたところ、エラーが発生した。
グローバルオプションをつけ、「npm install w2ui -g」のコマンドでインストールをしたところ、インストールすることができた。
MacOS Xの時、他に適切なインストール方法はあるか。
またbrewでインストールできるようにすることはできないか。

* 環境：MacOS X（10.14.5）
エラー内容
npm WARN checkPermissions Missing write access to /usr/local
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.
npm ERR! path /usr/local
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local'
npm ERR! [Error: EACCES: permission denied, access '/usr/local'] {
npm ERR! stack: "Error: EACCES: permission denied, access '/usr/local'",
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/local'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/maika/.npm/_logs/2019-07-27T02_53_39_321Z-debug.log

**Comment by maika5** [comment]
MacOSの時、「npm install w2ui 」のコマンドでインストールに失敗した。

グローバルオプションをつけ、「npm install w2ui -g」のコマンドでインストールをしたところ、インストールすることができた。
MacOS Xの時、他に適切なインストール方法はあるか。
またbrewでインストールできるようにすることはできないか。

環境：MacOS X（10.14.5）
エラー内容
npm WARN checkPermissions Missing write access to /usr/local
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.
npm ERR! path /usr/local
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local'
npm ERR! [Error: EACCES: permission denied, access '/usr/local'] {
npm ERR! stack: "Error: EACCES: permission denied, access '/usr/local'",
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/local'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm ERR! A complete log of this run can be found in:
npm ERR! /Users/maika/.npm/_logs/2019-07-27T02_53_39_321Z-debug.log

**Comment by mazayo** [comment]
title: `npm install w2ui` raises error on Mac osx

But successfully installed with g option `npm install w2ui -g`.
Could anyone tell me how to install it without g option? 
(I also wonder why if I could use brew instead of npm)

**Comment by maika5** [comment]
TITLE: Failed to install using 'npm install w2ui' command in MacOS

I cloud install using global option in npm : 'npm install w2ui -g'.

 is there any other install method In MacOS?
Would it be possible to install w2ui using 'brew' command?

Environment：MacOS（10.14.5）
Error Message：
npm WARN checkPermissions Missing write access to /usr/local
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.
npm ERR! path /usr/local
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local'
npm ERR! [Error: EACCES: permission denied, access '/usr/local'] {
npm ERR! stack: "Error: EACCES: permission denied, access '/usr/local'",
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/local'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm ERR! A complete log of this run can be found in:
npm ERR! /Users/maika/.npm/_logs/2019-07-27T02_53_39_321Z-debug.log

**Comment by maika5** [comment]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Failed to install using npm install w2ui on MacOS.
I cloud install using global option of npm : `npm install w2ui -g`.

* **What is the expected behavior?**
Could anyone tell me how to install with any other way In MacOS?
Would it be possible to install w2ui using brew?

* **Other information**
Environment：MacOS（10.14.5）
Error Message：
```
maika$ npm install w2ui
npm WARN checkPermissions Missing write access to /usr/local
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.
npm ERR! path /usr/local
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local'
npm ERR! [Error: EACCES: permission denied, access '/usr/local'] {
npm ERR! stack: "Error: EACCES: permission denied, access '/usr/local'",
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'access',
npm ERR! path: '/usr/local'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm ERR! A complete log of this run can be found in:
npm ERR! /Users/maika/.npm/_logs/2019-07-27T02_53_39_321Z-debug.log
```
