### ISSUE TITLE
    OSS Gate Workshop: Tokyo: 2019-07-27: hylian231: pynput: Work log

### ISSUE THREAD

**Issue by hylian231** [oss-gate/workshop#1225]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by asonas** [comment]
よろしくお願いします〜

**Comment by hylian231** [comment]
```
tatsuya@LAPTOP-FBHJ4TNA:~/w/py/serpvant$ sudo python3 key_input_test.py
Traceback (most recent call last):
  File "key_input_test.py", line 1, in <module>
    from pynput import mouse
  File "/usr/local/lib/python3.7/dist-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/local/lib/python3.7/dist-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/usr/local/lib/python3.7/dist-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/usr/local/lib/python3.7/dist-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

**Comment by hylian231** [comment]
https://github.com/moses-palmer/pynput

**Comment by hylian231** [comment]
https://pynput.readthedocs.io/en/latest/

**Comment by hylian231** [comment]
X window system が必要であることが分かった
https://pynput.readthedocs.io/en/latest/limitations.html

**Comment by hylian231** [comment]
sudo apt install lxde fonts-umeplus fonts-inconsolata

**Comment by asonas** [comment]
方向転換！
https://pythonhosted.org/PyDrive/ をやってみる

**Comment by hylian231** [comment]
sudo pip3 install PyDrive

**Comment by pocke** [comment]
:eyes:  方針転換大変そうだけど頑張ってください！ WSLでX window動かすのは大変そうですね、うまく動くのかな。。

**Comment by knokmki612** [comment]
vcxsrv使うと動くかもしれませんがどうでしょうね…！

**Comment by hylian231** [comment]
PyDriveのquick startを実行
Authentication　認証情報を作成し、
jsonをダウンロード。

wsl上に同じjsonを作成するため、vimでクリップボードから貼り付ける方法を探す

**Comment by hylian231** [comment]
wslにjson作成後、quickstart.pyを作成し実行するも、
返されたURLにて、エラーが発生

Error: redirect_uri_mismatch
The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/588119618537-98mu73ca1gd0eq9emes7njll0q47jidq.apps.googleusercontent.com?project=588119618537


url がミスマッチとあるが、あっているように思える

**Comment by hylian231** [comment]
I'm trying to install PyDrive.
I did "Quickstart" step by step in the url below.

https://pythonhosted.org/PyDrive/quickstart.html

I went to step5 in 'Authentication'.
I created quickstart.py and ran it.
Then, this program generates the url below.

https://accounts.google.com/o/oauth2/auth?client_id=588119618537-98mu73ca1gd0eq9emes7njll0q47jidq.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code

I went to the url, 
however an error occured below.

```
400. That’s an error.

Error: redirect_uri_mismatch
The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/588119618537-98mu73ca1gd0eq9emes7njll0q47jidq.apps.googleusercontent.com?project=588119618537
```

The error said mismatch the URLs.
I checked ‘Authorized JavaScript origins’ and ‘Authorized redirect URIs’,
but they are both 'http://localhost:8080'.

Could you investigate it?

My enviroments below.
OS: kali linux on windows subsystem for linux

**Comment by hylian231** [comment]
> vcxsrv使うと動くかもしれませんがどうでしょうね…！
ありがとうございます！

**Comment by asonas** [comment]
>> vcxsrv使うと動くかもしれませんがどうでしょうね…！

>ありがとうございます！

@hylian231 よさそうですね！時間も少し余っているのでためしてみましょう！

**Comment by hylian231** [comment]
PyDriveのGithubを発見
issueを投稿します
https://github.com/gsuitedevs/PyDrive/issues

**Comment by hylian231** [comment]
初issue投稿！
https://github.com/gsuitedevs/PyDrive/issues/172

**Comment by hylian231** [comment]
余裕ができたので、pynputに再挑戦！
vcxsrvをインストールして、pynputを動かそうとするも、
最新版は動かず。
紹介記事
https://www.atmarkit.co.jp/ait/articles/1812/06/news040.html
のバージョンをダウンロードしてインストールに成功

wslのターミナルで、さっきは動かなかった以下のコマンドを実行
DISPLAY=:0 python3 -c 'import pynput'
pynputが動いた！
