### ISSUE TITLE
OSS Gateワークショップ 2016-09-24: nyangu: embulk: 作業ログ

### ISSUE THREAD

**Issue by nyangu** [oss-gate/workshop#123]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed
## この issue 作成時点でまずやること
- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です
## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき
## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業：（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````
## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- ビギナーは作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- ビギナーが困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
- ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by nyangu** [comment]
elasticsearchやってみようと思ったけど、規模が大きすぎて何ができそうか全然想像できなかったのでもう少し小規模なossに変更した

**Comment by nyangu** [comment]
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
https://github.com/embulk/embulk#quick-start

**Comment by nyangu** [comment]
* 作業：インストール&実行できた
* 思っていること：とくに詰まるところはなかったが、javaのバージョンあってなかったらどうしようかなとちょっと不安を感じた。

**Comment by nyangu** [comment]
* 作業：プラグインを使ってみる
* 思っていること：ドキュメント通りに進めれば大丈夫だろう

**Comment by nyangu** [comment]
* 作業：インストールしたプラグインを使ってみる
* 思っていること：なんのプラグインなのかよくわからない。ドキュメントにある設定ファイルをコピーして実行してみる。
* 結果：

**Comment by nyangu** [comment]
* 作業：ドキュメントを少しわかりやすくする
* 思っていること：ドキュメントだけなら修正しやすそう。
* 結果：
```

```

**Comment by hiroyuki-sato** [comment]
もし全くembulkを使ったことがなければチュートリアルを試してみるのがいいように思いますよ。

**Comment by nyangu** [comment]
作業：コミットメッセージを考える
思っていること：英語できない。google translateをつかおう
結果：
```
コミットメッセージ：
ドキュメントのQuick Startをexampleを修正しました。
Fix an example in Quick Start.

説明：
ドキュメントの設定ファイルをそのまま使うと実行できない。

```
