### ISSUE TITLE
ビギナーの繰り上げ優先度をアンケートで判別する形式に変更する

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1240]
2019-07-27の東京ワークショップでビギナーの優先枠の運用についてやりとりした

https://github.com/oss-gate/workshop/issues/1214#issuecomment-512989635
https://github.com/oss-gate/workshop/issues/1214#issuecomment-513140695
https://github.com/oss-gate/workshop/issues/1214#issuecomment-512989635
https://github.com/oss-gate/workshop/issues/1214#issuecomment-513425225

以下の手順に変更する

1. 「優先枠」を別で作るのではなく、「サポーター」と「ビギナー」の2枠にする
2. 「ビギナー」の初期の枠の人数を0人にする
3. 優先の条件に該当するかチェックするフォームを設置する
4. 回答で条件を満たしているキャンセル待ちの人を、イベントのメンバープロフィールにある「キャンセル待ちから本申し込みに変更」で昇格させる

参加登録時のフォームの内容は少し揉んだ結果、こんな感じになった

```
任意:
ビギナーで申し込む方へ: 特定の条件を満たす場合、繰り上がり順が優先されます。
次のページにある条件を読んでください。
https://oss-gate.github.io/workshop/beginner-preferential-treatment.html
[ ] 読みました

必須:
ビギナーで申し込む方へ: 今回のワークショップで一緒に参加登録した「サポーター」はいますか？
[] はい
[] いいえ

任意:
「はい」を選んだ方は一緒に参加登録したサポーターのGitHubアカウント名を教えてください。
[kou]

必須:
ビギナーで申し込む方へ: 次回以降のワークショップで「サポーター」の参加登録をしていますか？
[] はい
[] いいえ

任意:
「はい」を選んだ方は「サポーター」で参加登録したイベントのイベント名を教えてください。
[OSS Gate東京ワークショップ2019-09-14]
```

現在受付中の東京ワークショップについても上記の変更をしても良い気がしています

**Comment by knokmki612** [comment]
- [OSS Gate東京ワークショップ2019-09-14](https://oss-gate.doorkeeper.jp/events/90538)
- [OSS Gate東京ワークショップ2019-10-26](https://oss-gate.doorkeeper.jp/events/92468)
- [OSS Gate東京ワークショップ2019-12-14](https://oss-gate.doorkeeper.jp/events/92469)

それぞれ

1. イベントの説明文の変更
2. フォームの追加
3. 「繰り上げ優先度に関わるフォームを追加したから良かったら入力してね」的なメッセージを出す

をやれば大丈夫な感じがします

**Comment by knokmki612** [comment]
2019-09-14のほうは既にビギナーの繰り上げがされているからやっぱりやらないでおいた方が良さそうか

**Comment by kou** [comment]
とりあえず、まぎらわしいのでビギナー優先枠は消しましょうか。

2019-09-14のやつはさらにサポーターが増えたときにだれを優先するかのときから適用しましょう。すでに定員に入っている人たちはそのままで。

**Comment by knokmki612** [comment]
受付中のすべての東京ワークショップから優先枠は消しておきました。

> 2019-09-14のやつはさらにサポーターが増えたときにだれを優先するかのときから適用しましょう。

では、2019-09-14にもフォームを追加しておきますね。

そのあと、「繰り上げ優先度に関わるフォームを追加したから良かったら入力してね」のメッセージを2019-09-14と2019-10-26のキャンセル待ちの人に送りますね。

**Comment by knokmki612** [comment]
繰り上がりの説明のページの文言を修正しました
https://github.com/oss-gate/oss-gate.github.io/pull/97

フォームの追加は済んでメッセージの送信はまだです。

**Comment by knokmki612** [comment]
この方式で数ヶ月運用できていますね！
