### ISSUE TITLE
OSS Gate Workshop: Hiroshima: 2019-08-04: kazari12: vim: Work log

### ISSUE THREAD

**Issue by kazari12** [oss-gate/workshop#1241]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by conao3** [comment]
よろしくお願いします

**Comment by kazari12** [comment]
$ brew install macvim
でインストール
エラーは出ていないっぽいけどアプリケーション一覧に出てこない

**Comment by kazari12** [comment]
コンソーツでmvim でウィンドウが起動した

**Comment by kazari12** [comment]
virtal.vim でライセンス確認
https://github.com/vim-jp/vital.vim

NYSL　ライセンス
http://www.kmonos.net/nysl/index.en.html

本家vim
https://github.com/vim/vim
Copying
Vim is Charityware. You can use and copy it as much as you like, but you are encouraged to make a donation to help orphans in Uganda. Please read the file runtime/doc/uganda.txt for details (do :help uganda inside Vim).

Summary of the license: There are no restrictions on using or distributing an unmodified copy of Vim. Parts of Vim may also be distributed, but the license text must always be included. For modified versions a few restrictions apply. The license is GPL compatible, you may compile Vim with GPL libraries and distribute it.

チャリティーウェア？

**Comment by kazari12** [comment]
とりあえずvimtutorを開いてみる
https://vim-jp.org/vimdoc-ja/usr_01.html#tutor

**Comment by kazari12** [comment]
vital.vim は各ユーザが独自プラグインを使う仕組みのようだ
https://github.com/vim-jp/vital.vim

**Comment by kazari12** [comment]
conf管理する
とりあえずgitupのインストール
brew install gitup
mkdir .dotfiles

**Comment by kazari12** [comment]
$ gitup
gitup: the git-repo-updater

You don't have any bookmarks configured! Get help with 'gitup -h'.

**Comment by kazari12** [comment]
dein.vim をインストールしてみる

**Comment by kazari12** [comment]
https://github.com/Shougo/dein.vim
にしたがってインストール

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
sh ./installer.sh ~/.cache/dein

Edit your .vimrc like this.

vim立ち上げて :call dein#install()

done と表示されたが、何が変わったのか？

**Comment by kazari12** [comment]
:h dein-options でヘルプが見られる

**Comment by kazari12** [comment]
インストールはできたが、使いかたがわからず

**Comment by kazari12** [comment]
自分がユーザとしてつまづいたこと＝未来の誰かがつまづく可能性がある

それを補完してあげる事にも意味はある

**Comment by ksnt** [comment]
少し迷走しているようですが、vimに限らず簡単に貢献できそうなことを探すのがよいのかな、と感じています。

**Comment by kazari12** [comment]
vimを相手にするのは大変だったので、conao3さんのリポジトリにPull-Requestしてマージするプロセスを体験

**Comment by kazari12** [comment]
- 対象
https://github.com/conao3/files/blob/master/README.org

- 自分のリポジトリにコピー
Githubから自分のリポジトリにCloneを作成

- READMEを修正してpush
`git clone https://github.com/kazari12/files.git
vim README.org
git commit -am "add usage commnad"
`

- GithubからPullRequest
- CIがエラーに
自分の変更は関係ないことをコメント
- マージされた
いきなりPR出すのではなく、まずIssueで開発者の意見を聞いてからPRを出すのもアリ
いきなりPR出しても悪くはない
