### ISSUE TITLE
OSS Gate Workshop: Hiroshima: 2019-08-04: slintristeza: redux-starter-kit: Work log

### ISSUE THREAD

**Issue by slintristeza** [oss-gate/workshop#1242]
## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by slintristeza** [comment]
https://github.com/reduxjs/redux-starter-kit

**Comment by Nyoho** [comment]
@slintristeza よろしくお願いしまーす!

**Comment by slintristeza** [comment]
ドキュメントに従い、インストール
`npm install redux-starter-kit`

**Comment by slintristeza** [comment]
ライセンスはMIT
https://github.com/reduxjs/redux-starter-kit/blob/master/LICENSE

**Comment by slintristeza** [comment]
プロジェクトをクローン
`git clone https://github.com/reduxjs/redux-starter-kit.git`

**Comment by slintristeza** [comment]
依存関係のインストール
`yarn`

**Comment by slintristeza** [comment]
https://redux-starter-kit.js.org/introduction/quick-start

**Comment by slintristeza** [comment]
以下のコマンドを実行する前にnpm initを実行
`npm install --save redux-starter-kit`

**Comment by Nyoho** [comment]
codesandbox.io 便利だな https://codesandbox.io/s/github/reduxjs/redux/tree/master/examples/counter-vanilla

**Comment by slintristeza** [comment]
basic-tutorialに進行
カウントアップのアプリを作るらしい
https://redux-starter-kit.js.org/tutorials/basic-tutorial

**Comment by slintristeza** [comment]
日本語のドキュメントがあるといい

**Comment by slintristeza** [comment]
コードの場所
https://github.com/reduxjs/redux/blob/master/examples/counter-vanilla/index.html

**Comment by slintristeza** [comment]
package.jsonとindex.htmlファイルをローカルにコピー。
関連パッケージをインストール
`yarn`
インストール後、実行してみる
`yarn start`

**Comment by Nyoho** [comment]
関連情報  < npm, yarn による zero install 戦略 - from scratch https://yosuke-furukawa.hatenablog.com/entry/2019/06/10/113111

**Comment by slintristeza** [comment]
parcelというWebアプリケーションバンドラー
https://parceljs.org/

**Comment by slintristeza** [comment]
A More Typical Counter Exampleに従い、
index.htmlファイルをES6に書き換える
`
<!DOCTYPE html>
<html>
  <head>
    <title>Redux basic example</title>
    <script src="https://unpkg.com/redux@latest/dist/redux.min.js"></script>
  </head>
  <body>
    <div>
      <p>
        Clicked: <span id="value">0</span> times
        <button id="increment">+</button>
        <button id="decrement">-</button>
        <button id="incrementIfOdd">Increment if odd</button>
        <button id="incrementAsync">Increment async</button>
      </p>
    </div>
    <script>
      const INCREMENT = 'INCREMENT'
      const DECREMENT = 'DECREMENT'

      function increment() {
        return { type: INCREMENT }
      }

      function decrement() {
        return { type: DECREMENT }
      }

      function counter(state = 0, action) {
        switch (action.type) {
          case INCREMENT:
            return state + 1
          case DECREMENT:
            return state - 1
          default:
            return state
        }
      }
      const store = Redux.createStore(counter)
      const valueEl = document.getElementById('value')
      function render() {
        valueEl.innerHTML = store.getState().toString()
      }
      render()
      store.subscribe(render)
      document.getElementById('increment').addEventListener('click', () => {
        store.dispatch(increment())
      })
      document.getElementById('decrement').addEventListener('click', () => {
        store.dispatch(decrement())
      })
      document.getElementById('incrementIfOdd')
        .addEventListener('click', function () {
          if (store.getState() % 2 !== 0) {
            store.dispatch(increment())
          }
        })
      document.getElementById('incrementAsync')
        .addEventListener('click', function () {
          setTimeout(function () {
            store.dispatch(increment())
          }, 1000)
        })
    </script>
  </body>
</html>
`

**Comment by slintristeza** [comment]
Introducing: configureStoreに従い、ソースを変更
```
// Before:
const store = createStore(counter)

// After:
const store = configureStore({
  reducer: counter
})
```

実行すると以下のエラーになる
`Uncaught ReferenceError: configureStore is not defined`

**Comment by slintristeza** [comment]
パッケージの追加
`npm i --save redux-stater-kit`

追加後npm startするとエラー
warning package.json: No license field
$ parcel index.html --open
/bin/sh: parcel: command not found
error Command failed with exit code 127.

**Comment by MSaito** [comment]
振り返りよろしく

**Comment by MSaito** [comment]
わかりました。うまく問題を見つけましたね。

**Comment by slintristeza** [comment]
コードの最終形が下にあり、scriptタグでredux-stater-kitを読み込むことで動作する。
scriptタグを書き換える記述がIntroducing: configureStoreの章の前にあるとソースを試しながらドキュメントを読めるので、親切ではないか。

`<script src="https://unpkg.com/redux-starter-kit@latest/dist/redux-starter-kit.umd.js"></script>`

**Comment by slintristeza** [comment]
# 問題
1. Redux "Counter-Vanilla" Exampleのソースをクローンし、ローカルの環境で動作確認を行いながらチュートリアルを進めていた。
1. A More Typical Counter Exampleの章まではソースを書き換えながら、進めることが出来た。
1. Introducing: configureStoreの章でソースを書き換えても動作しなかった。
エラー内容:Uncaught ReferenceError: configureStore is not defined
1. ドキュメントの最下部にソースの最終形があり、それを実行すると動作した。

# 原因
- ドキュメントがRedux "Counter-Vanilla" Exampleのソースを書き換える前提で作成されていない
- ドキュメントの最終形が最後に提示されることが文中にない

**Comment by slintristeza** [comment]
# PROBLEM
1. The source for Redux "Counter-Vanilla" Example was cloned and the tutorial was run in a local environment.
1. Up to the A More Typical Counter Example section, the source was rewritten.
1. Introducing: configureStore section did not work with source changes.
Error Description: Uncaught ReferenceError: configureStore is not defined
1. At the bottom of the document was the final form of the source, which worked when executed.

# cause
- Starting with Introducing: configureStore in the documentation is not written with the assumption that the Redux "Counter-Vanilla" Example source is rewritten
- The sentence does not indicate that the final version of the document is presented at the end

**Comment by Nyoho** [comment]
@slintristeza さん、せっかくなので推敲してポストしてもいいなあと思ったら是非どうぞ。文面のご相談はここでもGitterのチャットでも!
