### ISSUE TITLE
OSS Gate Workshop: Hiroshima: 2019-08-04: duck-0604: oss-gate.github.io : Work log

### ISSUE THREAD

**Issue by duck-0604** [oss-gate/workshop#1244]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ksnt** [comment]
よろしくおねがいします！

**Comment by duck-0604** [comment]
ライセンスが見つからない、、、。

**Comment by duck-0604** [comment]
検索しても見つからない、、、。

**Comment by duck-0604** [comment]
ローカルで動かしてみる。

**Comment by duck-0604** [comment]
jekyllとは？調べてみる。

**Comment by duck-0604** [comment]
index.htmlは少しわかる。

**Comment by duck-0604** [comment]
https://github.com/oss-gate/oss-gate.github.io/blob/master/workshop/new-to-moderator.md
修正したい箇所を見つけた。
開催地に広島がないため追加したい。

**Comment by duck-0604** [comment]
なんとなく修正のやり方を理解。

**Comment by duck-0604** [comment]
フォークとは？

**Comment by duck-0604** [comment]
フォークとはリポジトリのコピー。
オリジナルに影響を与えることなく自由に変更を加えることができる。

**Comment by duck-0604** [comment]
フォークしてみた。
修正箇所発見。
修正方法もなんとなく理解。

**Comment by duck-0604** [comment]
ブランチというものが必要？
ブランチとは？

**Comment by duck-0604** [comment]
ブランチとは履歴を分岐させて記録していくもの。
分岐させたものは他のブランチの影響を受けないため同じリポジトリ内で複数の変更を加えることができる。

**Comment by ksnt** [comment]
今後の予定: forkしてきたリポジトリをcloneしてローカルでbranchを切ります。

**Comment by duck-0604** [comment]
clone完了。

**Comment by conao3** [comment]
振り返りを担当しました

**Comment by duck-0604** [comment]
ブランチを作成。

**Comment by duck-0604** [comment]
add-hiroshimaという名前のブランチを作成。masterブランチからadd-hiroshimaに切り替えたので修正を加えていく。

**Comment by duck-0604** [comment]
github上のブランチの切り替えに成功。

**Comment by duck-0604** [comment]
add-hiroshima上のOSS GATEの開催地欄に広島を追加した。

**Comment by duck-0604** [comment]
git pull完了。
同期完了。

**Comment by duck-0604** [comment]
pull requestを送った。
メッセージ内容は”開催地欄に広島を追加した”。

**Comment by duck-0604** [comment]
https://github.com/oss-gate/oss-gate.github.io/issues/99
LICENSEファイルがない旨をissueにて報告。

**Comment by duck-0604** [comment]
home brewをgitにてインストール。

**Comment by duck-0604** [comment]
Dockerをインストール。

**Comment by ksnt** [comment]
docker run --rm --volume=$(pwd):/srv/jekyll -it -p 4000:4000 jekyll/jekyll jekyll serve --force_polling

これでサーバーが立ち上がってローカルで実行できるようになります。

**Comment by duck-0604** [comment]
dockerを使用。ローカルで実行した。

**Comment by duck-0604** [comment]
githubのpull request＆issueのURLを貼り付けると自動でリンクされる。

**Comment by mu2in** [comment]
お疲れ様でした。
最後、プルリクエストがマージされるまで走れて良かったです。
