### ISSUE TITLE
OSS Gate Meetup: Online: 2019-08-05

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1255]
## このテンプレートを使う時にやること

以下のテンプレートを埋めてタイトルに設定する

    OSS Gate Meetup: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}

タイトル例

    OSS Gate Meetup: Tokyo: 2019-07-08

## このissueは何のために使うの？

どんな人が来て、何をするかを共有するために使います！

## なんで共有をするの？

以下のような理由があります！

- 雑談するきっかけを作る
- イベント終了後にどんなイベントになったかをふりかえられるようにする

## いつ共有をするの？

当日の始めに、共有する時間をそれぞれ設けます！

## どうやって共有するの？

以下のことを両方やってください！

- 会場で口頭で喋る
- このissueにコメントで書く

## 始めに喋る/書くとよさそうなこと

以下に示す内容のいずれかで大丈夫です！

- 呼んでほしい名前
- 普段やっていること
- 普段利用/開発しているもの
- 当日やること
- フォローアップの人は[続きをするissue](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+Workshop)
- 「よろしくお願いします！」

## 始めの共有ができたあと

共有ができたあともissueにコメントしたかったらしましょう！

- リンクの共有
- 感想
- 色々メモ

**Comment by knokmki612** [comment]
くのきみです！

今日はissueを閉じるBotの動かし方やデプロイのしかたをoss-gate.github.ioに書く https://github.com/oss-gate/retrospective/issues/118 のをやります！

https://github.com/oss-gate/issue-cleaner/issues/12 に書くことをメモっておいたのでそれを元に書きます！

**Comment by tdtds** [comment]
同じく  Circle CIで動いているワークショップのアンケート文法チェッカに関するドキュメントを書きます。 https://github.com/oss-gate/retrospective/issues/118

**Comment by znz** [comment]
https://docs.ruby-lang.org/ja/latest/doc/news=2f2_6_0.html のリンク先を確認して対応できていないところを対応していこうと思います。

**Comment by swamp09** [comment]
rails6 の新機能の zeitwerkというのを手元のRailsアプリケーションで試そうと思います。
https://github.com/fxn/zeitwerk

**Comment by tdtds** [comment]
アンケート用CIを直しました～ https://github.com/oss-gate/workshop/pull/1257

**Comment by knokmki612** [comment]
次のミートアップは東京で2019-09-09にやることになった

**Comment by znz** [comment]
FileUtils まで確認できたので、これから pull request の作成などをしておきます。

**Comment by knokmki612** [comment]
今回オンラインミートアップをやってみて出てきたこと

よかったこと

- 遠隔から参加できるのは大きなメリット
- 遠隔でそれなりに活用してもらえそうな人もいそう
- それなりに雑談もできる

気になること

- 各自が今何をしているのかの把握が難しい
  - 離席
  - ミートアップとは別のことをしている(まあでも雑談には加わって手元では関係ないことをしているのもアリといえばアリかな？)

次東京ミートアップでは東京の会場と遠隔参加の両方を並行してやってみる

理由: 会場側だけでも今何をしているのかお互いに把握できていたほうが良いかなと。今回の感じだと遠隔参加の方の反応を会場側で拾うのはそんなに難しくなさそう

- 会場側の音声はグループディスカッション用のマイクで拾う
- 多分会場側の各自はイヤホン持参の方が良いかもしれない

**Comment by knokmki612** [comment]
@tdtds @znz 
よかったら、後日に今回のミートアップの良かったことと課題かなと思ったことを書いてもらえると参考になります！
おつかれさまでした！

**Comment by tdtds** [comment]
PCにマイクがなかったので(オフィスは無人だたったのに)ボイチャに参加できなかったけど、スマホにDiscordのアプリを入れれば良かったのでは……と気づきました。次の機会があればトライする。
とはいえボイチャしながらコードを追うのは、集中できないので良し悪しですね。

**Comment by knokmki612** [comment]
> ボイチャしながらコードを追うのは、集中できない

会場のミートアップでもそうなんですけど、私も話しながら手を動かすのはできないほうなので、毎回話題振りが多めであまり作業は進まないです()

**Comment by knokmki612** [comment]
> 次のミートアップは東京で2019-09-09にやることになった

私がイベントの作成にもたついてしまったので、今月はスキップして2019-10-07にやることになりました 😅
