### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2019-08-24: hiroya-tokei: python-prompt-toolkit: Work log

### ISSUE THREAD

**Issue by hiroya-tokei** [oss-gate/workshop#1259]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hiroya-tokei** [comment]
公式のGithubのページに沿ってインストールを実施する

https://github.com/prompt-toolkit/python-prompt-toolkit

**Comment by hiroya-tokei** [comment]
既にインストール済みのため、下記実行ログとなった

```
$ pip install prompt_toolkit
Requirement already satisfied: prompt_toolkit in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (2.0.9)
Requirement already satisfied: wcwidth in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from prompt_toolkit) (0.1.7)
Requirement already satisfied: six>=1.9.0 in ./.pyenv/versions/3.7.4/lib/python3.7/site-packages (from prompt_toolkit) (1.12.0)
```

**Comment by hiroya-tokei** [comment]
該当のライブラリがインストール済みであったが、特にアンインストールせずに、公式のreadmeの内容を進める。

**Comment by hiroya-tokei** [comment]
Getting startedの内容を進める

```
from prompt_toolkit import prompt

if __name__ == '__main__':
    answer = prompt('Give me some input: ')
    print('You said: %s' % answer)
```

上記のコードを、python_toolkit_test.pyとして保存する。
保存後、下記コマンドを実行して、動作確認を行う。

```
$ python python_toolkit_test.py
```

**Comment by hiroya-tokei** [comment]
```
$ python python_toolkit_test.py
Give me some input: hello
You said: hello
```
プログラムを実行後、「Give me some input:」と表示されるので、「hello」と入力し、Enterを押す。
すると、「You said: hello」が自動的に表示される。

**Comment by hiroya-tokei** [comment]
その他のサンプルコードは、下記Exapmle内にあるという記述があるので、一旦、リポジトリをクローンする。

https://github.com/prompt-toolkit/python-prompt-toolkit/tree/master/examples

```
$ git clone https://github.com/prompt-toolkit/python-prompt-toolkit.git
```

**Comment by hiroya-tokei** [comment]
dialogsディレクトリの中のサンプルを順番に実行していく

button_dialog.py
checkbox_dialog.py
input_dialog.py
messagebox.py
password_dialog.py
progress_dialog.py
radio_dialog.py
styled_messagebox.py
yes_no_dialog.py

**Comment by masayuki14** [comment]
進行役の森崎です！よろしくおねがいします！

**Comment by kyamaguchi81** [comment]
サポーターの山口です！
よろしくおねがいします！

**Comment by hiroya-tokei** [comment]
森崎さん、山口さん、よろしくお願いします。
🙇

**Comment by hiroya-tokei** [comment]
```
$ python button_dialog.py
```

上記コマンド実行後、下記画像の様な画面になる。

![Uploading dialogs_—_python_button_dialog_py_—_119×35.png…]()

この画面で、「Yes」、「No」、「Maybe...」のいずれかを選択(左右矢印キー)し、Enterを押すと、画面が閉じて、プロンプト画面に戻る。

**Comment by hiroya-tokei** [comment]
同様の手順で、下記サンプルも実行

```
$ python checkbox_dialog.py
```

ただ、下記エラーが発生
```
$ python checkbox_dialog.py
Traceback (most recent call last):
  File "checkbox_dialog.py", line 7, in <module>
    from prompt_toolkit.shortcuts import checkboxlist_dialog, message_dialog
ImportError: cannot import name 'checkboxlist_dialog' from 'prompt_toolkit.shortcuts' (/Users/hiroyaakita/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

**Comment by hiroya-tokei** [comment]
ソースコードの内容を確認して、7行目のインポートでエラーが出ている事が判明。

念の為、インポート部分単体でもエラーが出るかどうかを確認。

```
$ python
Python 3.7.4 (default, Jul 16 2019, 00:43:37) 
[Clang 11.0.0 (clang-1100.0.20.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prompt_toolkit.shortcuts import checkboxlist_dialog, message_dialog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'checkboxlist_dialog' from 'prompt_toolkit.shortcuts' (/Users/hiroyaakita/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

**Comment by hiroya-tokei** [comment]
ひとまず、このファイルは置いておいて、次のサンプルの実行に進む。

**Comment by hiroya-tokei** [comment]
```
$ python input_dialog.py
```

上記コマンド実行後に、下記画像のような画面が表示される。

<img width="1223" alt="dialogs_—_python_input_dialog_py_—_119×35" src="https://user-images.githubusercontent.com/12933477/63633133-f24f3680-c67d-11e9-987b-90a3e6400e8a.png">

文字を入力できるので、文字を入力後、「OK」を選択して、Enterを押す。

**Comment by hiroya-tokei** [comment]
ここで初めて気がついたのだが、「OK」コマンドを実行後にエラーが表示されていた。

```
$ python input_dialog.py
Traceback (most recent call last):
  File "input_dialog.py", line 17, in <module>
    main()
  File "input_dialog.py", line 11, in main
    text='Please type your name:').run()
AttributeError: 'str' object has no attribute 'run'
```

**Comment by hiroya-tokei** [comment]
exampleを実行しているが、想定どおりに動かないきがする。。。
issueを少し見ようかと思ったが、200件以上あったので、どうしようかなーと。

**Comment by hiroya-tokei** [comment]
一応readmeに下記記述があるので、MacOSなので動作しない、ということはなさそう

```
Runs on Linux, OS X, FreeBSD, OpenBSD and Windows systems.
``

**Comment by hiroya-tokei** [comment]
一旦保留にして、次に進む

**Comment by hiroya-tokei** [comment]
下記コマンドを実行する。

```
$ python messagebox.py
```

すると、下記画面が表示される。

<img width="1187" alt="dialogs_—_python_messagebox_py_—_119×35" src="https://user-images.githubusercontent.com/12933477/63633235-e8c6ce00-c67f-11e9-97ce-e63fdae8623f.png">

Enterを押下すると、画面が終了してプロンプトに戻る。

**Comment by masayuki14** [comment]
振り返りお疲れさまでした！

**Comment by hiroya-tokei** [comment]
遅ればせながら、ライセンス情報になります。

BSD 3-Clause "New" or "Revised" License

**Comment by hiroya-tokei** [comment]
サンプルプログラム自体が起動しない場合
https://github.com/oss-gate/workshop/issues/1259#issuecomment-524522470

GUI系のサンプルの実行後に、エラーが表示されている
https://github.com/oss-gate/workshop/issues/1259#issuecomment-524522963
https://github.com/oss-gate/workshop/issues/1259#issuecomment-524523637

**Comment by hiroya-tokei** [comment]
「サンプルプログラム自体が起動しない場合」について、フィードバックのコメントを考える

**Comment by hiroya-tokei** [comment]
**どういう状態になっていてほしいか**
エラーが無い状態になっていていほしい

### フィードバック内容の概要

#### 自分の環境について

仕様PC、OSのバージョン
使用しているPythonのバージョン
インストール方法

#### 具体的な事象について

どの様な手順でプログラムを実行すると、どの様なエラーが発生しているのか
エラーの内容もコピーして追記する

**Comment by kyamaguchi81** [comment]
この方のIssueは参考になりそうです。
https://github.com/support-project/knowledge/issues/1079

**Comment by hiroya-tokei** [comment]
自分の開発環境
OS: Mac OS Mojave 10.14.6
Python(pyenv): 3.7.4

インストール方法

```
$ pip install prompt_toolkit
```

発生している事象

example内のサンプルが動作しない
具体的には、「checkbox_dialog.py」を下記コマンドのように実行すると、エラーが発生する

```
$ python checkbox_dialog.py
Traceback (most recent call last):
  File "checkbox_dialog.py", line 7, in <module>
    from prompt_toolkit.shortcuts import checkboxlist_dialog, message_dialog
ImportError: cannot import name 'checkboxlist_dialog' from 'prompt_toolkit.shortcuts' (/Users/hiroyaakita/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

**Comment by hiroya-tokei** [comment]
CONTRIBUTING.mdをリポジトリ内で探したが、見つからなかったので、こちらでフォーマットを決めて作成する。

似たようなissueがあるかどうかをざっくり確認した後、なさそうなので、
新規でissueを立てることにする。

**Comment by hiroya-tokei** [comment]
タイトル

----

Exampleが動かない

内容

----

こんにちは。
便利に使わせてもらってます。
使っている中で見つかった問題を報告します。

## 環境

OS: Mac OS Mojave 10.14.6
Python(pyenv): 3.7.4
prompt-toolkit: 2.0.9

## 再現手順とエラーログ

example内のサンプルが動作しない
具体的には、「checkbox_dialog.py」を下記コマンドのように実行すると、エラーが発生し、
プログラムが実行されない(GUIなどが表示されず、エラーで終了する)

```
$ pip install prompt_toolkit

$ git clone https://github.com/prompt-toolkit/python-prompt-toolkit.git
$ cd /python-prompt-toolkit/examples/dialogs
$ python checkbox_dialog.py
Traceback (most recent call last):
  File "checkbox_dialog.py", line 7, in <module>
    from prompt_toolkit.shortcuts import checkboxlist_dialog, message_dialog
ImportError: cannot import name 'checkboxlist_dialog' from 'prompt_toolkit.shortcuts' (/Users/xxxx/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

**Comment by hiroya-tokei** [comment]
Example checkbox_dialog.py doesn't work

Hello.
I use it conveniently.
Report problems found during use.

## Execution environment

OS: Mac OS Mojave 10.14.6
Python(pyenv): 3.7.4
prompt-toolkit: 2.0.9

## Reproduction procedure and error log

The sample in example does not work.
Specifically, when "checkbox_dialog.py" is executed like the following command, an error occurs,
The program is not executed (GUI is not displayed and the program ends with an error).

```
$ pip install prompt_toolkit

$ git clone https://github.com/prompt-toolkit/python-prompt-toolkit.git
$ cd /python-prompt-toolkit/examples/dialogs
$ python checkbox_dialog.py
Traceback (most recent call last):
  File "checkbox_dialog.py", line 7, in <module>
    from prompt_toolkit.shortcuts import checkboxlist_dialog, message_dialog
ImportError: cannot import name 'checkboxlist_dialog' from 'prompt_toolkit.shortcuts' (/Users/xxxx/.pyenv/versions/3.7.4/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)
```

Thanks.

**Comment by hiroya-tokei** [comment]
こちらでIssueを作りました
☺️

https://github.com/prompt-toolkit/python-prompt-toolkit/issues/959

**Comment by masayuki14** [comment]
おめでとうございます😀

**Comment by hiroya-tokei** [comment]
🙇

**Comment by kyamaguchi81** [comment]
おめでとうございます 〜🎉🎉🎉
