### ISSUE TITLE
OSS Gate Workshop: Fukuoka: 2019-09-10: st-tahara: plotly.py: Work log

### ISSUE THREAD

**Issue by st-tahara** [oss-gate/workshop#1268]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nagachika** [comment]
よろしくお願いします!!

**Comment by nagachika** [comment]
リポジトリはこちらでしょうか? https://github.com/plotly/plotly.py
ライセンスは MIT みたいですね。

**Comment by st-tahara** [comment]
そうです！いまから作業はじめます！

**Comment by st-tahara** [comment]
readmeをよむ
https://github.com/plotly/plotly.py/blob/master/README.md

**Comment by st-tahara** [comment]
JupyterLab 0.35.5で動かす

**Comment by st-tahara** [comment]
QUICK STARTのinstallを実行
`!pip install plotly "notebook>=5.3" "ipywidgets>=7.2"`

**Comment by st-tahara** [comment]
書く
```
import plotly.graph_objs as go
fig = go.FigureWidget()
# Display an empty figure
fig
```

**Comment by st-tahara** [comment]
実行するとエラーは無いけれど何も表示されない
```
fig.add_scatter(y=[2, 1, 4, 3])
fig.add_bar(y=[1, 4, 3, 2])
fig.layout.title = 'Hello FigureWidget'
```

**Comment by st-tahara** [comment]
Quickstartに
> Inside Jupyter notebook:
と欠かれていたので、Jupyter notebookに切り替えてみる

**Comment by st-tahara** [comment]
Jupyter notebookでも何も表示されない

**Comment by st-tahara** [comment]
再度上から順に実行するとグラフが表示された
```
import plotly.graph_objs as go
fig = go.FigureWidget()
fig
```

```
fig.add_scatter(y=[2, 1, 4, 3])
fig.add_bar(y=[1, 4, 3, 2])
fig.layout.title = 'Hello FigureWidget'
```

![newplot](https://user-images.githubusercontent.com/55121528/64609374-c49d1800-d407-11e9-84ef-fdf9d38b8af7.png)

**Comment by st-tahara** [comment]
もう一度、JupyterLabで試してみる

**Comment by st-tahara** [comment]
JupyterLab 0.35.5ではグラフは表示されず、このアウトプットのみ

```
FigureWidget({
    'data': [], 'layout': {'template': '...'}
})
```

**Comment by st-tahara** [comment]
Jupyter Notebook 5.7.8で作業進める

**Comment by st-tahara** [comment]
readmeのInstallationに

> JupyterLab Support (Python 3.5+)

を発見。JupyterLabで試してみる

**Comment by st-tahara** [comment]
実行
`!pip install jupyterlab==1.0 "ipywidgets==7.5"`

**Comment by st-tahara** [comment]
> Then run the following commands to install the required JupyterLab extensions:

この記載のとおり、拡張機能のインストールをすすめる

**Comment by st-tahara** [comment]
実行
```
# (OS X/Linux)
export NODE_OPTIONS=--max-old-space-size=4096
```

**Comment by st-tahara** [comment]
実行
`!jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0 --no-build`

**Comment by st-tahara** [comment]
実行
`!jupyter labextension install plotlywidget@1.1.1 --no-build`

**Comment by st-tahara** [comment]
実行
`!jupyter labextension install jupyterlab-plotly@1.1.2 --no-build`

**Comment by st-tahara** [comment]
実行
`!jupyter labextension install jupyterlab-chart-editor@1.2 --no-build`

**Comment by st-tahara** [comment]
実行
`!jupyter lab build`

**Comment by st-tahara** [comment]
実行
`!unset NODE_OPTIONS`

**Comment by st-tahara** [comment]
JupyterLabを再起動すると、画面が真っ白

**Comment by st-tahara** [comment]
ChromeのJavascriptコンソールでエラー
```
Uncaught Error: Plugin '@jupyterlab/plotly-extension:factory' is already registered.
    at JupyterLab.push.2R+v.Application.registerPlugin (vendors~main.74e95426574164089971.js:22599)
    at new JupyterLab (vendors~main.74e95426574164089971.js:898062)
    at main (main.36cb8c9d220c65707923.js:1935)
```

**Comment by nagachika** [comment]
細かくログ取れているので手順とエラーメッセージで報告するのもいいかと思います。もしかしたら復旧方法のヒントをもらえるかも。また既存 issue を検索して同様の現象の報告がないかというのを探すのもいいかもしれません。

**Comment by st-tahara** [comment]
無事、環境復帰しました！
