### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-09-14: imaharu: graphql-ruby: Work log

### ISSUE THREAD

**Issue by imaharu** [oss-gate/workshop#1293]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by imaharu** [comment]
まずは、graphql-rubyのGettingスタートをローカルにインストールします
https://graphql-ruby.org/getting_started#declare-types

**Comment by imaharu** [comment]
各バージョンです

```
$ rails -v
Rails 5.2.3
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
```

**Comment by imaharu** [comment]
初期のGemfileです
ここに、 `gem "graphql"` を追記します
特に規定がないので、groupは指定しません

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by imaharu** [comment]
```
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# for oss gate
gem "graphql"
```

上記のように追加した後に、**bundle install**をします

**Comment by imaharu** [comment]
その後、`rails s`を行うといつもの画面が出力されました


<img width="721" alt="スクリーンショット 2019-09-14 14 07 16" src="https://user-images.githubusercontent.com/23719154/64903722-ff010080-d6f8-11e9-9bdc-bffe4a24bf9f.png">

**Comment by imaharu** [comment]
macを利用しているので、.gitignoreに**.DS_Store**を追加した後に

git add & git commit を行いました

```
g add .
g commit -m "First commit rails new with graphql-ruby && bundle install"
```

**Comment by imaharu** [comment]
Gemfile.lockの中身を見ると

`graphql (1.9.12)`がインストールされていました

**Comment by imaharu** [comment]
Getting　Startedページの
https://graphql-ruby.org/getting_started#declare-types から

GraphQL generatorsをクリックしたのち

https://graphql-ruby.org/schema/generators#graphqlinstall

Options段落に
- --no-graphiql will exclude graphiql-rails from the setup
とあったが、 `graphql:install --help` 実行するとないため `rails g  graphql:install --no-graphiql`と実行した

```
 $ rails g  graphql:install --help
Running via Spring preloader in process 62782
Usage:
  rails generate graphql:install [options]

Options:
  [--skip-namespace], [--no-skip-namespace]                    # Skip namespace (affects only isolated applications)
  [--directory=DIRECTORY]                                      # Directory where generated files should be saved
                                                               # Default: app/graphql
  [--schema=SCHEMA]                                            # Name for the schema constant (default: {app_name}Schema)
  [--skip-keeps], [--no-skip-keeps]                            # Skip .keep files for source control
  [--skip-graphiql], [--no-skip-graphiql]                      # Skip graphiql-rails installation
  [--skip-mutation-root-type], [--no-skip-mutation-root-type]  # Skip creation of the mutation root type
  [--relay], [--no-relay]                                      # Include GraphQL::Relay installation
  [--batch], [--no-batch]                                      # Include GraphQL::Batch installation
  [--api], [--no-api]                                          # Preconfigure smaller stack for API only apps

Runtime options:
  -f, [--force]                    # Overwrite files that already exist
  -p, [--pretend], [--no-pretend]  # Run but do not make any changes
  -q, [--quiet], [--no-quiet]      # Suppress status output
  -s, [--skip], [--no-skip]        # Skip files that already exist
```

**Comment by imaharu** [comment]
すると、helpには存在しないコマンドが動いた

**Comment by imaharu** [comment]
再度、 ` rails g  graphql:install --help` を実行すると

下記のようなエラー文が出力された

```
oss-gate-graphql $ rails g  graphql:install --help
Could not find gem 'graphiql-rails' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

```

**Comment by imaharu** [comment]
次にbundle installを実行した

**Comment by imaharu** [comment]
ドキュメントがテンプレエンジンが変化してから更新されていない

**Comment by imaharu** [comment]
GitHubの該当ページはここ

https://github.com/rmosolgo/graphql-ruby/blob/master/guides/getting_started.md

**Comment by swamp09** [comment]
`rails g`で生成されるテンプレートファイルと、ドキュメントと違う部分があって、そこは直したほうが良いですね！という話をしました。
他に同じような問題でPRを出している人がいるか一緒に確認したところ、いないみたいなのでこのままいけそう！

**Comment by imaharu** [comment]
NameSpace(テンプレートエンジン)に関するPRは以下のリンクです

https://github.com/rmosolgo/graphql-ruby/commit/7279b5fc113627e4d01a6b0f39c0c520c69bd744#diff-a6f0315311fb9167ede5428eb5a574d3

https://github.com/rmosolgo/graphql-ruby/issues/1591

**Comment by imaharu** [comment]
PRヘ役立ちそうなリンク

類義語辞書
https://www.thesaurus.com/browse/

英英辞書

https://www.ldoceonline.com/dictionary/

**Comment by shioimm** [comment]
@imaharu 
知り合いの記事なのですが、OSSにPRを送るまでの流れがまとまっているので
紹介しておきます🐣
https://qiita.com/fuqda/items/a3e5270ff9cb4fbf31e2#%E7%9B%AE%E6%AC%A1

**Comment by imaharu** [comment]
## Problem
Getting Started page が最新のテンプレートジェネレーターに追従していない

## 
@bary822さんが、https://github.com/rmosolgo/graphql-ruby/issues/1591を解決するために
[コード](https://github.com/rmosolgo/graphql-ruby/commit/7279b5fc113627e4d01a6b0f39c0c520c69bd744#diff-a6f0315311fb9167ede5428eb5a574d3)を修正しました。

その結果、Getting Startedのドキュメントを参考にして `rails g graphql:object Post title:String rating:Int comments:[Comment]`  を実行すると以下のコードが生成されます

```
module Types
  class PostType < Types::BaseObject
    field :title, String, null: true
    field :rating, Integer, null: true
    field :comments, [Types::CommentType], null: true
  end
end
```

しかし、ドキュメントが修正に対応していないので初心者の人は戸惑うかもしれません。

## 解決策

ドキュメントを修正したPRを投げました

**Comment by bary822** [comment]
PR感謝です 🙏

**Comment by imaharu** [comment]
ここ、PRに投げました

https://github.com/rmosolgo/graphql-ruby/pull/2477
