### ISSUE TITLE
OSS Gate WorkshopTokyo2019-09-14inTheRyeplotly.pyWork log

### ISSUE THREAD

**Issue by inTheRye** [oss-gate/workshop#1294]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by inTheRye** [comment]
https://github.com/plotly/plotly.py
↑このOSSを使ってみる。

https://github.com/plotly/plotly.py#quickstart
クイックスタートに従って、インストールをする。

**Comment by inTheRye** [comment]
$ pip install plotly "notebook>=5.3" "ipywidgets>=7.2"
のインストールコマンドを実行したところ、すでにインストール済みだった。

**Comment by Godan** [comment]
よろしくおねがいしますー

**Comment by inTheRye** [comment]
Jupiter notebook の中で、下記を実行してみた。
```python
import plotly.graph_objs as go
fig = go.FigureWidget()
# Display an empty figure
fig
```

```python
# Add a scatter chart
fig.add_scatter(y=[2, 1, 4, 3])
# Add a bar chart
fig.add_bar(y=[1, 4, 3, 2])
# Add a title
fig.layout.title = 'Hello FigureWidget'
```

**Comment by inTheRye** [comment]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1492964/64903775-db8a8580-d6f9-11e9-9c1c-d1931b499e12.png">
上記のグラフが表示された。

**Comment by inTheRye** [comment]
quick startには、どのようなグラフが描かれるのかがなく、イメージできないので、readmeにイメージが載っていると良いと思った。

**Comment by inTheRye** [comment]
ドキュメントのリポジトリはここ
https://github.com/plotly/documentation

**Comment by inTheRye** [comment]
３Dコンターのサンプルを実行してみる。
https://plot.ly/python/contour-plots/

```python
import plotly.graph_objects as go

fig = go.Figure(data =
    go.Contour(
        z=[[10, 10.625, 12.5, 15.625, 20],
           [5.625, 6.25, 8.125, 11.25, 15.625],
           [2.5, 3.125, 5., 8.125, 12.5],
           [0.625, 1.25, 3.125, 6.25, 10.625],
           [0, 0.625, 2.5, 5.625, 10]]
    ))
fig.show()
```

エラーになった。
```sh
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-8028d662830e> in <module>
----> 1 import plotly.graph_objects as go
      2 
      3 fig = go.Figure(data =
      4     go.Contour(
      5         z=[[10, 10.625, 12.5, 15.625, 20],

ModuleNotFoundError: No module named 'plotly.graph_objects'
```

**Comment by inTheRye** [comment]
https://plot.ly/python/
にあるexampleのコードを試すが、軒並みエラーとなる。

**Comment by shioimm** [comment]
@inTheRye 
先ほどログを拝見したものです。
今回問題がとても大きそうなので、まずは仰っていた通り過去のissueやPRに同様の事例が報告されていないか確認することが必要だと思います。
エラー文言や「example」などの単語で検索してみるのはいかがでしょう🙋‍♀️
また、休憩時間中に仰っていた通り、大きな変更が発生した後ドキュメントが更新されていない可能性もあるので、changelogなどでこの2ヶ月くらいの変更を確認してみると良いと思います💪

**Comment by inTheRye** [comment]
https://plot.ly/python/getting-started/
のドキュメントを見ると、下記のようになっている。

```python
$ pip install plotly==4.1.0
```

こちらでインストールしているバージョンを確認すると、以下のようになっているので、こちらのインストールバージョンが古い。

```sh
$ pip list | grep plotly
plotly                            3.4.2 
```

**Comment by inTheRye** [comment]
```sh
% pip install plotly==4.1.0
Collecting plotly==4.1.0
  Downloading https://files.pythonhosted.org/packages/63/2b/4ca10995bfbdefd65c4238f9a2d3fde33705d18dd50914dd13302ec1daf1/plotly-4.1.0-py2.py3-none-any.whl (7.1MB)
     |████████████████████████████████| 7.1MB 1.4MB/s 
Requirement already satisfied: retrying>=1.3.3 in ./py3.6.6/lib/python3.6/site-packages (from plotly==4.1.0) (1.3.3)
Requirement already satisfied: six in ./py3.6.6/lib/python3.6/site-packages (from plotly==4.1.0) (1.12.0)
Installing collected packages: plotly
  Found existing installation: plotly 3.4.2
    Uninstalling plotly-3.4.2:
      Successfully uninstalled plotly-3.4.2
Successfully installed plotly-4.1.0
```

でバージョンアップすると、ドキュメントのサンプルコードは実行可能となった。
ただし、逆にかきREADMEのサンプルがエラーとなった。
https://github.com/plotly/plotly.py/blob/master/README.md

**Comment by Godan** [comment]
いいですね!  具体的な今日のゴールがみえてきてよかったです!

**Comment by inTheRye** [comment]
# 問題点

https://github.com/plotly/plotly.py/blob/master/README.md
のREADMEのインストールでバージョン指定が無いため、すでに古いバージョンがインストールしている場合に、気づかずに使ってしまう可能性がある。

# 環境
他の依存関係によって、すでに古いバージョンのライブラリがインストールされていた。

# 解決策

ドキュメントではバージョン指定でインストールするようになっているため、READMEのインストール方法にもバージョンを指定するような書き方とする。

**Comment by inTheRye** [comment]
# Two ways of instllation in README.md is misleading. 

## Problems

There are two ways of installation in README.md.
1. `$ pip install plotly "notebook>=5.3" "ipywidgets>=7.2"` in [Quickstart](https://github.com/plotly/plotly.py/blob/master/README.md#quickstart)
1. `$ pip install plotly==4.1.1` in [Installation](https://github.com/plotly/plotly.py/blob/master/README.md#installation)

I tried from the Quickstart installation at first. The in my environment, there was already installed older version of plotly (3.4.2). I did't notice it was older version because the 1st way of installation doesn't specify the version.

So, I executed the command ``$ pip install plotly "notebook>=5.3" "ipywidgets>=7.2"`` but it said the `plotly` is already installed.

Then I tried some example code in 'https://plot.ly/python/' but it didn't work. 
After I tried the version specified command $ pip install plotly==4.1.1`, it worked.

## Solutions 

Please modify the ”Quickstart” installation in README.md into version specific way. I think It will be beginner-friendly.

Thank you in advance.

**Comment by inTheRye** [comment]
issueあげました！
https://github.com/plotly/plotly.py/issues/1770
