### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-09-14: ikeyu0806:shoulda-matchers: Work log

### ISSUE THREAD

**Issue by ikeyu0806** [oss-gate/workshop#1295]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by satoryu** [comment]
こんにちわ。よろしくお願いします 🙋‍♂

**Comment by ikeyu0806** [comment]
READMEを読んで対象のライブラリをインストールします。
https://github.com/thoughtbot/shoulda-matchers

**Comment by ikeyu0806** [comment]
サンプルアプリケーションを作るためにRubyのバージョンを2.5.0にRails5.2.3でrails newします。

**Comment by ikeyu0806** [comment]
README通りに`spec/rails_helper.rb`に設定を書こうとしたが、rspecしかサンプルコードがない。railsのデフォルトはrspecではないので少し詰まる。

**Comment by ikeyu0806** [comment]
minitestもあるのにtest unitのサンプルがない。。

**Comment by ikeyu0806** [comment]
READMEを読むとRspecとminitestしかサポートしていないことが明記されていた。

**Comment by ikeyu0806** [comment]
gemfileにrspec追記して`bundle install`と`rails generate rspec:install`実行。

`rails generate rspec:install`実行時に以下の警告が出力された。
```
❯ rails generate rspec:install
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:90: warning: already initialized constant FileUtils::VERSION
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:92: warning: previous definition of VERSION was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1188: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1446: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1541: warning: previous definition of DIRECTORY_TERM was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1448: warning: already initialized constant FileUtils::Entry_::SYSCASE
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1543: warning: previous definition of SYSCASE was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1501: warning: already initialized constant FileUtils::OPT_TABLE
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1596: warning: previous definition of OPT_TABLE was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1555: warning: already initialized constant FileUtils::LOW_METHODS
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1650: warning: previous definition of LOW_METHODS was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1562: warning: already initialized constant FileUtils::METHODS
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1657: warning: previous definition of METHODS was here
WARNING: Nokogiri was built against LibXML version 2.9.9, but has dynamically loaded 2.9.4
Running via Spring preloader in process 30520
      create  .rspec
      create  spec
      create  spec/spec_helper.rb
      create  spec/rails_helper.rb
```

**Comment by ikeyu0806** [comment]
一旦rspecの上記の警告を追ってみる。

**Comment by ikeyu0806** [comment]
memo
rspecのレポジトリ
https://github.com/rspec/rspec-rails

**Comment by ikeyu0806** [comment]
rspecのレポジトリ内で`FileUtil`を検索したものの、initializeしている箇所は見つからず。

**Comment by ikeyu0806** [comment]
`Gemfile`を検索するが、`fileutil`は見つからず。

**Comment by Godan** [comment]
丁寧に作業ログを取っていて素敵です!
shoulda-matchersをやり続けるかrspecに切り替えるかは悩むと思いますが、みんなと悩みながら午後一緒に走り抜けましょう…!

**Comment by satoryu** [comment]
https://github.com/ruby/fileutils/issues/22

**Comment by ikeyu0806** [comment]
問題の切り分けをするために以下の手順を実行した

- `shoulda-matchers`をコメントアウトして`bundle install`からの`rails generate rspec:install`

- `rspec`をコメントアウトして`rails generate model`

結果同様の警告が出力され、rspec、shoulder-matcherの問題ではないことがわかった。

**Comment by ikeyu0806** [comment]
fileutilsに既にissueが報告されていたが、今回の状況は報告されていなかったため再現状況を方ここうすることとする。

再現条件をまとめると
- ruby 2.5.0
- fileutils 1.10
- rails generateコマンド実行時

**Comment by ikeyu0806** [comment]
fileutil1.0.2だと再現しない

**Comment by ikeyu0806** [comment]
bundle exec rails -v
→警告出力しない

rails -v
→警告出力

**Comment by ikeyu0806** [comment]
再現条件をまとめると
- `fileutil1.1.0`
- ruby2.5.0
- rails5.2.3
- `bundle exec rails -v`→警告発生せず
- `rails -v`（bundle execなし）→警告発生する
- `bundle exec`なしで`rails generate rspec:install`を実行したところ警告発生した
- `fileutils1.1.0`と`default: 1.0.2`が入っている

再現させようとして失敗したやり方として
`hoge.rb`を作成し以下のrequireのみ記述して実行した。
```
require 'fileutils'
```
```

**Comment by ikeyu0806** [comment]
### 文章に落としてみる

Railsアプリケーションを作ろうとして必要なgemfileをインストールして`rails generate rspec:install`を実行しました。
その時に以下の警告が出ました。

```
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:90: warning: already initialized constant FileUtils::VERSION
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:92: warning: previous definition of VERSION was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1188: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1446: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1541: warning: previous definition of DIRECTORY_TERM was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1448: warning: already initialized constant FileUtils::Entry_::SYSCASE
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1543: warning: previous definition of SYSCASE was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1501: warning: already initialized constant FileUtils::OPT_TABLE
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1596: warning: previous definition of OPT_TABLE was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1555: warning: already initialized constant FileUtils::LOW_METHODS
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1650: warning: previous definition of LOW_METHODS was here
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/2.5.0/fileutils.rb:1562: warning: already initialized constant FileUtils::METHODS
/Users/ikegayayuuki/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1657: warning: previous definition of METHODS was here
WARNING: Nokogiri was built against LibXML version 2.9.9, but has dynamically loaded 2.9.4
Running via Spring preloader in process 30520
      create  .rspec
      create  spec
      create  spec/spec_helper.rb
      create  spec/rails_helper.rb
```

警告が発生した条件は以下の通りです。
- `fileutil1.1.0`
- `ruby2.5.0`
- `rails5.2.3`

警告の原因を突き止めるために以下の調査を行いました。
- `bundle exec rails -v`→警告発生せず
- `rails -v`（bundle execなし）→警告発生する
- `fileutils1.1.0`と`default: 1.0.2`が入っている

**Comment by ikeyu0806** [comment]
なんで無くしたいかというと（なんでこれが嫌なのか）

- ファイルやディレクトリに絡む処理だとだいたい毎回出てくる
- 警告が長く他の警告を見逃す
- いちいちびっくりする

**Comment by satoryu** [comment]
同じものがあがっていた件

https://stackoverflow.com/questions/51334732/rails-5-2-0-with-ruby-2-5-1-console-warning-already-initialized-constant

**Comment by ikeyu0806** [comment]
`bundle exec`をつけるか否かで警告が出力されなくなることは報告されていないかも？

**Comment by ikeyu0806** [comment]
日本語で下書き
`bundle exec rails -v`で実行すると警告が出ませんでした。が、`bundle exec`なしで`rails -v`を実行すると警告が発生しました。Bundlerのversionは`2.0.1`でした。

**Comment by ikeyu0806** [comment]
Not warning when I execute `bundle exec rails -v`.But warning when `rails -v` without `bundler`.

- bundler 2.0.1
- ruby 2.5.0
- rails 5.2.3
- fileutils 1.1.0

**Comment by ikeyu0806** [comment]
コメントDONE

**Comment by ikeyu0806** [comment]
残り時間shoulder matcherを見てみる

**Comment by ikeyu0806** [comment]
再度`shoulder-matchers`を`bundle install`

**Comment by ikeyu0806** [comment]
`spec/rails_helper.rb`に設定を書き込む

**Comment by ikeyu0806** [comment]
コメント
https://github.com/ruby/fileutils/issues/22#issuecomment-531460365
