### ISSUE TITLE
OSS Gate Workshoptokyo2019-09-14norinuxoctokit.rbWork log

### ISSUE THREAD

**Issue by norinux** [oss-gate/workshop#1296]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

（サポーターで参加しましたが、サポーターの方が多かったのでビギナーに勝手に変更）

**Comment by norinux** [comment]
https://github.com/octokit/octokit.rb#quick-start　の通りに進めてみる。
`gem install octokit` をする
```
nori$ gem install octokit
Successfully installed octokit-4.14.0
Parsing documentation for octokit-4.14.0
Done installing documentation for octokit after 1 seconds
1 gem installed
```
大丈夫そう
` client.repos({}, query: {type: 'owner', sort: 'asc'})`
で、自分のリポジトリのリストっぽいのはとれた
`user = client.user 'swamp09'`
swamp09さんのユーザ情報は覗き見できた
`client.auto_paginate = true`
 これ入れたら便利そうだからいれた
```
repo = client.repo 'gaiax/Reactio-Issues'
rel = repo.rels[:issues]
p rel.get.data
```
ISSUEのリストはゲットできた、、が、、CLOSEしたISSUEがでてこない
quick-startには、これ以上の情報がないため、別のドキュメントを探る
http://octokit.github.io/octokit.rb/ のリンクがあったので、ここをみる

**Comment by norinux** [comment]
```
#create_issue(repo, title, body = nil, options = {}) ⇒ Sawyer::Resource
Also known as: open_issue
```
あとでつかえそうなの見つけたのでメモ

http://octokit.github.io/octokit.rb/Octokit/Client/Issues.html#close_issue-instance_method
ここで、ISSUEの操作のドキュメントをみつけた
`p client.list_issues 'gaiax/Reactio-Issues' , {state: "all"}`
これで、ISSUEの全件獲得できた

**Comment by norinux** [comment]
ISSUEの全件取得できたが、コメントが一緒に取得できない。困った。

**Comment by ryoon** [comment]
* GitHub APIで、list_issues methodの裏にあるAPIがcommentsを取得できるか見ておくと良いように思いました。
* GitHub APIの構成とは別に、issuesの一覧を取得しつつ、comments を取得できる新しいmethodがあると便利なように思いました。

**Comment by norinux** [comment]
### 気持ち
GithubのISSUEを取得するときに、一緒にコメントも取得したい。

### 問題点
list_issues でISSUEを取得してもコメントが含まれていないため、issue_comments を使って別に取得する実装を書かなければならず、非常に面倒

### 修正方法
list_issues_with_comments という、ISSUEのコメントも一緒に取得できる便利な新しいメソッドを追加する

**Comment by norinux** [comment]
# フィードバックの英語化

### title
Get ISSUE and ISSUE comments in one request.

### body
I want to get issue comments in issue lists. 

Becouse , list_issues method is not include issue comments.
So , It requires a lot of work to get of  issue_comments.

### Request behavior
  - add include **comments** option in list_issues method.
  - or. add new method list_issues_with_comments.

**Comment by norinux** [comment]
feedback done .
https://github.com/octokit/octokit.rb/issues/1148
