### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-09-14: YukiFujita0327: CKEditor5: Work log

### ISSUE THREAD

**Issue by YukiFujita0327** [oss-gate/workshop#1297]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by YukiFujita0327** [comment]
・対象OSSは下記の通り(CKEditor5)です。
https://github.com/ckeditor/ckeditor5
・ライセンスを確認したところ、問題ありませんでした。
GNU General Public License Version 2 or later
・readmeのクイックスタートにしたがってインストールを実施します。

**Comment by makicamel** [comment]
よろしくおねがいします！:tada:

**Comment by YukiFujita0327** [comment]
・index.htmlを作成
・下記のscriptタグを追加
```
<script src="https://cdn.ckeditor.com/ckeditor5/12.4.0/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
```
・テキストエリアを追加
```
<textarea name="content" id="editor"></textarea>
```

**Comment by YukiFujita0327** [comment]
CKEditorを以前利用した際、等幅フォントを適用しようとしたところ、下記のような問題があった。
・改行位置がずれてしまう。

しかし、今回検証してみた結果、問題なく表示された。

**Comment by YukiFujita0327** [comment]
・文字の太さ・斜体・hタグか通常文書の設定を変更した際に、太さが戻らなくなる事象が発生した。
→H1,H2,H3タグの場合、デフォルトが太字のためと判明。

**Comment by YukiFujita0327** [comment]
・ソースを落として試してみる

**Comment by YukiFujita0327** [comment]
・試してみたのはClassic editorというビルドのバージョンだが他のバージョンもあるので試してみる
Inline editor
Balloon editor
Balloon block editor
Document editor

**Comment by ryomo56** [comment]
問題点がはっきりとわかっていたのでよかったと思います。
具体的なエラーの再現もできているので
あとはそれをまとめてissueを立てると良いと思います。
その際は具体的なエラーを出来るだけ細かく伝えるのが重要ですね。

**Comment by makicamel** [comment]
お仕事で使った時にハマった理由はIEを使っていたからかもしれない、とのこと。

CDNを使って動かす、よりもカスタマイズをするとか、
お仕事で導入する時の要件をイメージして動かしてみるとフィードバックポイントが見つかりやすいかもしれないと思いました！

**Comment by YukiFujita0327** [comment]
・ビルドを試す為、モジュールのダウンロード

**Comment by YukiFujita0327** [comment]
実行環境が下記の通り
Node.js 6.9.0+
npm 4+ (note: some npm 5+ versions were known to cause problems, especially with deduplicating packages; upgrade npm when in doubt)

・対象環境に対応していない為、nodeをアップデートする

**Comment by YukiFujita0327** [comment]
nodeのアップデート
```
nvm install v10.16.3
```

**Comment by YukiFujita0327** [comment]
npmのアップデート
```
npm install -g npm
・・・
npm -v
6.9.0

```

**Comment by YukiFujita0327** [comment]
依存ライブラリのインストール
```
npm install --save \
>     postcss-loader@3 \
>     raw-loader@3 \
>     style-loader@1 \
>     webpack@4 \
>     webpack-cli@3
```

**Comment by YukiFujita0327** [comment]
・webpack.config.jsを入力
・エディタ設定のモジュールのインストール
```
npm install --save \
    @ckeditor/ckeditor5-dev-utils \
    @ckeditor/ckeditor5-editor-classic \
    @ckeditor/ckeditor5-essentials \
    @ckeditor/ckeditor5-paragraph \
    @ckeditor/ckeditor5-basic-styles \
    @ckeditor/ckeditor5-theme-lark
```

**Comment by YukiFujita0327** [comment]
・app.jsを作成する
・webpack様にビルドを実行する
```
./node_modules/.bin/webpack --mode development
```

**Comment by YukiFujita0327** [comment]
・package.jsonに下記を追記
```
"scripts": {
    "build": "webpack --mode development"
}
```

**Comment by YukiFujita0327** [comment]
・npmビルドを実行 
```
npm run build
```

**Comment by YukiFujita0327** [comment]
・index.htmlを作成し、./dist/bundle.jsを読み込み、CKEditorを作成する。
→画面に下記の内容が表示
Editor content goes here.
コンソールに下記の内容が表示
Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.
・コンソールに表示されていたURLの記事を確認
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
・下記の内容をbundle.jsを追加
```
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
```

**Comment by makicamel** [comment]
今日中にフィードバックできるまでサポートできなくてすみませんでした:pray:
たくさん課題があって難しかったと思います。おつかれさまでした！
オンラインでもお手伝いするので、今日のエラーを解決して `npm install` の記述があるとよいと思うというissueをぜひ立ててみてください！

**Comment by YukiFujita0327** [comment]
・再度READMEをじっくり精読してみる。
→環境構築手順が存在していたことがわかる。
・環境構築手順を実施
・Mr.gitとyarnをインストール
```npm install -g yarn mrgit```
・リポジトリをフォークする
・フォークしたリポジトリをcloneする。
```
git clone https://github.com/ckeditor/ckeditor5.git
cd ckeditor5
```
・yarn installの実行
```
yarn install
```
・全パッケージを取得する。
```
mrgit sync
```
・もう一度yarn install
```
yarn install
```
・テストを実行
```
yarn run test --files=core
```
・変更内容のフェッチ
```
# To update the ckeditor5 repository itself:
git pull

# To update pull changes to all the packages:
mrgit sync

# To install missing dependencies:
yarn install
```
・一応reinstallしておく
```
git pull
yarn run reinstall
```
・最後にテストでカバレッジ100%を確認
```
yarn run test --watch --coverage --source-map --files=engine
```

**Comment by YukiFujita0327** [comment]
・テスト用カスタムビルドの作成
・cloneする手順はすでに環境構築手順で実施済みのため、classicバージョンのビルドのディレクトリに移動
```
cd ./packages/ckeditor5-build-classic/
```
・依存関係のあるモジュールのインストール
```
npm install
```
・ビルド設定ファイルの更新
`src/ckeditor.js `を修正して、ビルドに取り込むモジュールを変更可能
(ここではテストのため、存在しているモジュールを削除してみる)
・ビルドの再実行
```
yarn run build
```
ビルドされたモジュールが設定通りに動作することを確認

**Comment by YukiFujita0327** [comment]
・既存のnpmプロジェクトにCKEditorを組み込む手順を実施してみる
[https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html](url)
・適当なサンプルプロジェクトを作成する。
```
mkdir ~/oss-gate/integrate_sample
cd ~/oss-gate/integrate_sample
npm init
npm install
npm install webpack --save-dev
npm install webpack-cli --save-dev
mkdir ~/oss-gate/src
vi ~oss-gate/src/app.js
```
・下記を貼り付け
```
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
```
・index.htmlの作成
```
vi ~/oss-gate/index.html
```
下記を貼り付け
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Untitled Document</title>
    </head>
    <body>
    	<textarea name="content" id="editor"></textarea>
    	<script src="./build/bundle.js"></script>
    </body>
</html>

```
・webpack.config.jsを作成し、インプットとするjs(`src/app.js`)と出力先(`build/bundle.js`)を指定する。
・ビルドの実行
```
npx webpack --mode development
```
既存のアプリにCKEditorが追加できることを確認した。
手順をよくみるとHTMLにtextareaタグを作成する旨が記載されていないので、初心者にもわかる様にISSUEを立てることにした。

**Comment by YukiFujita0327** [comment]
### 問題点
[https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html](url)
jsファイルの修正手順が記載してあるが、textareaタグも追加する必要があるはず。

### 自分の気持ち
CKEditorを使いたいんだから、当たり前でしょと言われそうだが、初心者で手順にしたがって進んでいるとその当たり前も抜けてしまいそう。

### 解決策
HTMLにtextareaタグを追記する旨の手順の追加。

**Comment by YukiFujita0327** [comment]
issueたててみた
https://github.com/ckeditor/ckeditor5/issues/2069
