### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-09-14: UsaMomokawa:marp-cli: Work log

### ISSUE THREAD

**Issue by UsaMomokawa** [oss-gate/workshop#1299]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by UsaMomokawa** [comment]
今まで使ったことあるgemを試しています

**Comment by UsaMomokawa** [comment]
Rails6に対応していないGemを探しています

**Comment by ryomo56** [comment]
お疲れ様です！
marp-cliを却下した理由なども書いてみたらどうでしょう。

**Comment by UsaMomokawa** [comment]
marp-cliはTypeScriptで実装されているとわかりました。
自分の使っている言語のOSSがよさそうということで、先にruby gemを探していました。

**Comment by UsaMomokawa** [comment]
marp-cliをインストールしてみようというところで、ドキュメント通りに進めています。
依存関係でうまくインストールできず詰まってます。

**Comment by satoryu** [comment]
さきほどのふりかえりでお伝えした内容を書きます。

- faker をGemfileのどこに追加するのが適切なのか、ハッキリとした明記がなかったので、それをネタにフィードバックできそう
  - 安定版のfakerをbundlerで取り入れる方法については書かれてなかったようだったので
- 残り時間少ないですが、別のgemなり何かに取り組むのもありそう

このあとも頑張っていきましょう 💪

**Comment by UsaMomokawa** [comment]
軽微ですが`slide-deck.html`と`output.html`の食い違いを発見しました。

# Basic usage
## Convert to HTML
The passed markdown will be converted to HTML file by default. In the below example, a converted `slide-deck.html` will output to the same directory.

You can change the output path by --output (-o) option.
```
marp slide-deck.md -o output.html
```
https://github.com/marp-team/marp-cli

**Comment by ryomo56** [comment]
これは自分も同感でした！
この調子で細かく書いていきましょう^^b

**Comment by ryomo56** [comment]
一つテクニックとして箇条書きがありました。

まずメモを箇条書きします。
そのあとカテゴリごとに整理します。

あと行った手順も箇条書きが一番伝わりやすいかも。

**Comment by UsaMomokawa** [comment]
軽微ですが`slide-deck.html`と`output.html`の食い違いを発見しました。

# 追記
これは食い違いではなく、別名でoutputできるよというものでした。

# Basic usage
## Convert to HTML
The passed markdown will be converted to HTML file by default. In the below example, a converted `slide-deck.html` will output to the same directory.

```
marp slide-deck.md #=> slide-deck.html
```

You can change the output path by --output (-o) option.
```
marp slide-deck.md -o output.html #=> output.html
```
https://github.com/marp-team/marp-cli

**Comment by ryomo56** [comment]
ネタになりそうなものを書いてみます。

slide-deck.mdの例が欲しい
npmの必須バージョンの記載が欲しい
　∟6.10.3でエラーが出たことを書いてみる
npxコマンドが必要ということがわかりずらい
　冒頭の説明はnpxがついていて
　下の説明はnpxがついていない

**Comment by UsaMomokawa** [comment]
# 追記
これは依存関係でインストールできなかったのではなく、
`npx`経由でコマンドを実行しないと`marp`が動かなかったということでした。

## これはダメ
```
$ marp -v
zsh: command not found: marp
```

## こうすると動く
```
npx marp -v
@marp-team/marp-cli v0.14.0 (w/ user-installed @marp-team/marp-core v0.13.1)
```

---

marp-cliをインストールしてみようというところで、ドキュメント通りに進めています。
依存関係でうまくインストールできず詰まってます。

```
npm install --save-dev @marp-team/marp-cli   
```

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.

+ @marp-team/marp-cli@0.14.0
added 46 packages from 22 contributors, removed 51 packages, updated 1110 packages and audited 13686 packages in 59.434s
found 0 vulnerabilities
```

環境
macOS Mojave 10.14.6
```
$ npm -v 
6.9.0
```

**Comment by UsaMomokawa** [comment]
# 期待すること
Please add '(standalone)' 


# いま
Basic Usage内は`npx`が省略されている。
`npm`経由でインストールした人が`marp`コマンドを打っても動かない。

`npx` command is omitted in Basic Usage.
If someone installed via `npm`, he hits  ` marp` command, it doesn't work.

**Comment by UsaMomokawa** [comment]
PRを出しました（どきどき）
https://github.com/marp-team/marp-cli/pull/152

**Comment by ryomo56** [comment]
おめでとうございます！

**Comment by UsaMomokawa** [comment]
- 作業メモ大事
  - Feedbackポイントになるよ
  - 動かなかったことを報告するだけでも助かる
- 直ると次の人はうまくいく

**Comment by ryomo56** [comment]
https://github.com/oss-gate/workshop/tree/master/tutorial/retrospectives
