### ISSUE TITLE
OSS Gateワークショップ 2016-01-30: tSU-RooT Linux Kernel 作業ログ

### ISSUE THREAD

**Issue by tSU-RooT** [oss-gate/workshop#13]
問題:ASUS X205TAにおいて、Linux Kernel 4.2以上において、頻繁にフリーズが起こる。
報告先がわからない。

**Comment by tSU-RooT** [comment]
ログをとるために、sysstatをapt-get

**Comment by tSU-RooT** [comment]
既存のIssueがないか、Lubuntuのページを見た

**Comment by tSU-RooT** [comment]
Kernelのバグ報告場所を探しはじめた

**Comment by tSU-RooT** [comment]
ラップトップの機種名ではなく、
中に入っているデバイスの方に問題があり、その名前で探すと良いのでは？と
今日はレポートがかければ御の字とのこと。

**Comment by tomo667a** [comment]
障害を再現されるために、Grub の設定を変更して、カーネルを選択できるようにする。

**Comment by tomo667a** [comment]
Grubの設定にてこずる

**Comment by tomo667a** [comment]
Grub を操作できて、カーネル 4.2 で起動した。フリーズするはず。

**Comment by tomo667a** [comment]
報告用に環境情報を収集する。

**Comment by tSU-RooT** [comment]
メモ:報告用に
lsmod, uname, lspci, lsusbなどの環境情報を収集した

**Comment by tSU-RooT** [comment]
いままでの手順を整理する

**Comment by tSU-RooT** [comment]
なぜカーネルのバグだと思ったか？
そもそも、Lubuntu 15.10のデフォルトのカーネルは4.2であり、頻繁にフリーズしていた。
http://solidstatelife.blogspot.jp/2015/11/asus-x205taubuntu1404lts.html
ここにのっている情報通り、カーネルを
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.1-wily/
から4.1にダウングレードすると、フリーズの頻度が愕然に下がった。
そのご静観していたが、4.4がリリースされ、それを試しに導入してみてもフリーズするので
もしかしたらそもそも問題が報告されていないのではないかと思った。

**Comment by tSU-RooT** [comment]
いま問題は２つあります

+ どこに問題を報告するか
+ 何をどう報告するか、どんな情報を報告するか

**Comment by tSU-RooT** [comment]
報告場所の問題について
・Ubuntu(LubuntuはUbuntuのフレーバー)のカーネルを使っているので、Ubuntuのカーネル関係のところに報告した方がよいということになった。もしこれがバニラカーネルでも再現するなら、報告先はLKMLでもアリとのこと。
報告場所の探しかたについて

**Comment by tomo667a** [comment]
http://exiz.org/linux/2015011912536/
Ubuntuがフリーズした時の対処法
Ubuntuでアプリが固まるとそこそこの確率でGUI全体が固まってしまことがあるのでその対処法。
フリーズしたときに下記のキーを順番にタイプしていく。
再起動する場合
「Alt+PrintScreen+R+S+E+I+U+B」
「Alt」キーと「PrintScreen」を押しながら順番に「R」「S」「E」「I」「U」「B」

**Comment by tomo667a** [comment]
なんとなく、「Ubuntu フリーズ」でインターネット検索

**Comment by tSU-RooT** [comment]
問題の説明:
現在の問題は使っているとシステムが停止することです。
現象として問題が起こると、シングルユーザーモード(Ctrl+Alt+F1)にも入れず
電源を切り再起動する以外に対処法がなくなります。

**Comment by tSU-RooT** [comment]
OS:Lubuntu 15.10
ハードウェア:ASUS X205TA
uname -a:Linux tsr-X205TA 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
これをこのラップトップにインストールすると、同じ環境を用意できる
http://cdimage.ubuntu.com/lubuntu/releases/15.10/release/lubuntu-15.10-desktop-amd64.iso
grubのインストールのみインストーラーを使わず、自分で導入。インターネットからアップデートのダウンロードオプションは入れている。(12月ごろ)
あとはインストーラーはデフォルト。
インストール済みパッケージのリスト
環境変数

同じ操作
FirefoxやEmacsを使っているときにフリーズ。
30分-3時間で再現することが多い

**Comment by tomo667a** [comment]
クラッシュした

**Comment by tomo667a** [comment]
カーネル 4.4 で起動した。

**Comment by tomo667a** [comment]
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4-wily/

**Comment by kou** [comment]
おつかれさまでした！
