### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-10-26: zukaishi: vue-editor Work log

### ISSUE THREAD

**Issue by zukaishi** [oss-gate/workshop#1320]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by zukaishi** [comment]
vue.jsのなんかやってみようかな

**Comment by zukaishi** [comment]
nuxt.js 見ている

**Comment by neko314** [comment]
よろしくおねがいします  😄

**Comment by inTheRye** [comment]
よろしくお願いします！

**Comment by zukaishi** [comment]
となると直接 vue.js nuxt.jsじゃなくて、package.jsonの中のを見た方がいいと思った

**Comment by zukaishi** [comment]
フレームワークではなくて、vue.js自体が使われているライブラリとか見ていく事にしようと考え
google で、vue.js github と検索

**Comment by zukaishi** [comment]
https://github.com/vuejs/vue　にたどり着いて

**Comment by zukaishi** [comment]
package.jsonをリンク

https://github.com/vuejs/vue/blob/dev/package.json

**Comment by zukaishi** [comment]
devDependencies　の中身を見てみた

**Comment by zukaishi** [comment]
nuxt.jsやろうと思ってたけど、先にvue.jsの開発者にお会いした事を思い出したので、
vue.jsを先に調べる事に。

package.jsonの中から、見たことのあるライブラリを眺めてみる

**Comment by zukaishi** [comment]
babelでいつもつまづいている事を思い出した

**Comment by zukaishi** [comment]
selenium-server　っていうのが気になったので、googleで調べてみる

**Comment by zukaishi** [comment]
selenium-server githubだとそれっぽいのが出ない

selenium-server  vue.js　github　で検索したらここにきたので
https://github.com/vuejs/vue-cli

にアクセスしてみる

**Comment by inTheRye** [comment]
下記に、selenium serverのgithubリポジトリのリンクありました。
https://www.npmjs.com/package/selenium-server

**Comment by zukaishi** [comment]
サポーターの方にリンクと、ググり方教えていただいたので、
selenium server npmで検索して同じリンクに到達

**Comment by zukaishi** [comment]
license を確認、BSD-3-Clause　で、あったのでOSS　である事を確認した。

**Comment by zukaishi** [comment]
https://github.com/eugeneware/selenium-server
githubアクセスしたところ、思ってたのと違うので方向変更

vue-editorを調べてみる
https://github.com/anguer/vue-editor

**Comment by zukaishi** [comment]
リンク切れ、typoをすでに見つけたので他にも何かあるのかもしれない

**Comment by zukaishi** [comment]
ライセンス情報が、なかったのでpackage.jsonを見てみたら
確認したところ、 "license": "MIT", と記載がったのでOSSの対象である事を確認

https://github.com/anguer/vue-editor/blob/master/package.json

**Comment by zukaishi** [comment]
https://github.com/anguer/vue-editor

README.mdに記載されている、DEMOがリンク切れ担っていたので、
プルリクを出してみようと思った。

**Comment by zukaishi** [comment]
その前に動かしてみる事にします。

**Comment by zukaishi** [comment]
README.mdに記載されている通り、以下実行

npm install vue-md-editor --save

npm WARN saveError ENOENT: no such file or directory, open '/Users/hishizuka/work/git/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/hishizuka/work/git/package.json'
npm WARN vue-md-editor@1.3.3 requires a peer of vue@^2.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN git No description
npm WARN git No repository field.
npm WARN git No README data
npm WARN git No license field.

+ vue-md-editor@1.3.3
added 3 packages from 270 contributors and audited 3 packages in 1.943s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by zukaishi** [comment]
実行をしたがそのあと何をしたら良いかわからない。

**Comment by zukaishi** [comment]
Usage通りに、ファイルを作成し、開いてみたが
何も反応がない。
他にサンプルファイルがあるか確認。

**Comment by zukaishi** [comment]
https://github.com/anguer/vue-editor/tree/master/examples

に、サンプルファイルっぽいのがあったので中身をみてみる

**Comment by zukaishi** [comment]
サンプルそのまま持ってきて、実行してみたところ

GET file://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/styles/atom-one-light.min.css net::ERR_FILE_NOT_FOUND

このようなエラーが

**Comment by zukaishi** [comment]
ライセンス情報packagejsonの中だったので、プルリク投げれそう

**Comment by zukaishi** [comment]
package.json　中にある、buildコマンドを実行する必要があるのかなと思いました。
"build:example": "node build/build-example.js",

**Comment by zukaishi** [comment]
フィードバックを行う場所が見当たらなかったためフォーマットに沿って記述する

1. 整理する
・README.md　記載の、DEMOリンクを開いてもデモが確認できない。
・ライセンス情報が、README.mdに記載されておらず、package.json内にしかなった
・Usage通りにファイルを作成を行ない、index.htmlを実行したが期待した通りの動作をしなかった

**Comment by zukaishi** [comment]
# 整理する　①DEMOリンク
環境
・日本の渋谷からアクセス
・macOS Mojave バージョン10.14.6
・Google Chrome バージョン: 77.0.3865.120（Official Build）

# 再現手順
https://github.com/anguer/vue-editor　ヘアクセス
DEMOリンク（http://vue-editor.beblog.cn/）をクリック

# 期待される結果
デモを実行することができる

# 実際の結果
デモを実行することができず、アクセスできない事が画面上で確認できた。

**Comment by zukaishi** [comment]
## 2. ライセンス情報の記載
### 再現手順
https://github.com/anguer/vue-editor
へアクセス

### 期待される結果
ライセンス情報を確認する事ができる

### 実際の結果
ライセンス情報を確認する事ができなかった。
しかし、packge.json内には存在した。

**Comment by zukaishi** [comment]
## 3. Usage　手順通りに作業を行なったが実行する事ができない

###  再現手順
Usage　記載通りnpm installを実行

npm install vue-md-editor --save

npm WARN saveError ENOENT: no such file or directory, open '/Users/hishizuka/work/git/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/hishizuka/work/git/package.json'
npm WARN vue-md-editor@1.3.3 requires a peer of vue@^2.1.10 but none is installed. You must install peer dependencies yourself.
npm WARN git No description
npm WARN git No repository field.
npm WARN git No README data
npm WARN git No license field.

vue-md-editor@1.3.3
added 3 packages from 270 contributors and audited 3 packages in 1.943s
found 1 moderate severity vulnerability
run npm audit fix to fix them, or npm audit for details

main.jsと、index.htmlを作成し、index.htmlをブラウザより実行。

### 期待される結果

### 実際の結果

**Comment by zukaishi** [comment]
1.DEMOリンクを英語にする

**Comment by zukaishi** [comment]
## 1.DEMO link
###environment
・ Access from Shibuya, Japan
・ MacOS Mojave version 10.14.6
・ Google Chrome version: 77.0.3865.120 (official build)

### Reproduction procedure
https://github.com/anguer/vue-editor
Click on the DEMO link on README.md
http://vue-editor.beblog.cn/

###Expected results
Can run a demo

### Actual result
It was confirmed on the screen that the demo could not be executed and was not accessible.

**Comment by zukaishi** [comment]
##  License information writing  location

```
* Access from Tokyo, Japan
* MacOS Mojave version 10.14.6
* Google Chrome version: 77.0.3865.120 (official build)
```

### Steps to reproduce
Try to this READMR.md

### Expected behavior
License  information on the  README.md
  or 
find to the license file 

### Actual behavior
Does not exist in README.md 
But, it was in package.json

### Reason
Because the first person thinks that it is better to be able to immediately judge whether to use

**Comment by zukaishi** [comment]
forkをして、ブランチ切って、アップして、そこからプルリク出すのが丁寧なやり方。

**Comment by zukaishi** [comment]
英語でどう書けばいいかわらかない場合
https://www.clear-code.com/blog/2019/7/12.html
