### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-10-26: genk1181: Gatsby: Work log

### ISSUE THREAD

**Issue by genk1** [oss-gate/workshop#1323]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by genk1** [comment]
Gatsbyでやってみる

**Comment by nico-hn** [comment]
nico-hnです。よろしくお願い致します。

**Comment by genk1** [comment]
gatsby npm で検索して
ここに行く https://www.npmjs.com/package/gatsby
license情報としてはMITだと確認できた

実際に githubに進める
https://github.com/gatsbyjs/gatsby

Readme上にQuickStartが存在したのでクリックしたら
公式ページに進められた https://www.gatsbyjs.org/docs/

**Comment by genk1** [comment]
Tutorialがあったのでクリック
https://www.gatsbyjs.org/tutorial/

**Comment by genk1** [comment]
Tutorialドキュメントを読む

**Comment by genk1** [comment]
ドキュメントが整備されすぎていたので gatsbyの使っているパッケージをたどる
https://github.com/gatsbyjs/gatsby/blob/master/package.json

**Comment by genk1** [comment]
husky npm を調べてみる

**Comment by genk1** [comment]
1. https://www.npmjs.com/package/husky
2. https://github.com/typicode/husky

**Comment by genk1** [comment]
READMEを読んでみたがわからん
withoutプロジェクトでどのようにすすめるのかがわからん。

**Comment by genk1** [comment]
一旦　空フォルダを作る 
cd ~
mkdir ossgateway
cd ossgateway
git init

**Comment by genk1** [comment]
> Initialized empty Git repository in /Users/amagata/GenkiPro/ossgateway/.git/

**Comment by genk1** [comment]
npm install husky --save-dev

**Comment by genk1** [comment]
touch package.json
package.jsonに対して  "...": "..." を抜いたものを書き込む
```
{
  "husky": {
    "hooks": {
      "pre-commit": "npm test",
      "pre-push": "npm test"
    }
  }
}
```

**Comment by genk1** [comment]
helloworld.jsを作って
```
const helloPerson = (name) => {
    console.log(`HELLO, ${name}`);
}

helloPerson("GENKI");
```

**Comment by genk1** [comment]
commitをするために一旦 .gitignoreを作って node_modulesを外す

**Comment by genk1** [comment]
git add *

**Comment by genk1** [comment]
git commit -m 'Keep calm and commit'
成功した
```
[master (root-commit) e4c940f] Keep calm and commit
 3 files changed, 620 insertions(+)
 create mode 100644 helloworld.js
 create mode 100644 package-lock.json
 create mode 100644 package.json
```

**Comment by genk1** [comment]
jsファイルを壊してコミットしてみる

**Comment by genk1** [comment]
```
const helloPerson = (name) => {
        console.log(`HELL
}

helloPerson("GENKI");
```

**Comment by genk1** [comment]
エラー起きずにすすめる

**Comment by genk1** [comment]
```
const helloPerson = (name) => {
    console.log(`HELLO, ${name}`);
}

helloPerson("GENKI");
```
これで node helloworld.js をしても動く

**Comment by genk1** [comment]
```
helloPerson("GENKI");
                     

SyntaxError: Unexpected end of input
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/l
```
エラーは起きている

**Comment by genk1** [comment]
単独では動かないので止める

**Comment by genk1** [comment]
さまよい始めたので gatsby上でどのように huskyが使われているかをチェックしている
https://github.com/gatsbyjs/gatsby/blob/master/package.json

**Comment by genk1** [comment]
```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged || node scripts/on-lint-error.js"
    }
  },
```
gatsbyでどうやって動いているのかの設定をみた

**Comment by genk1** [comment]
https://github.com/typicode/husky/blob/master/scripts/ci-husky-skip-hooks-check.js
```  
/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require('fs')
const path = require('path')

const filename = path.join(__dirname, '../ci-post-checkout')

if (fs.existsSync(filename)) {
  fs.unlinkSync(filename)
  console.log(
    '.git/hooks/post-checkout script has run, hooks were not skipped.'
  )
  process.exit(1)
} else {
  console.log(
    '.git/hooks/post-checkout script has not run, hooks were successfully skipped.'
  )
}
```

**Comment by genk1** [comment]
行間を埋めるだけの知識があるならうまく埋めてあげる
以下で書いてあるのは pre-commitでテストを走らすような感じだから一気にここに行くのではなく
テストを書く(行間を埋める)ぐらいのことがあるといいかも
```
// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "npm test",
      "pre-push": "npm test",
      "...": "..."
    }
  }
}
```

**Comment by genk1** [comment]
一旦 package.jsonの中で huskyがインストールされていないことに気づいたので npm install huskyをした

**Comment by genk1** [comment]
変更まえ
```
{
    "husky": {
        "hooks": {
            "pre-commit": "npm test",
            "pre-push": "npm test"
        }
    },
}

```

**Comment by genk1** [comment]
その後
{
    "husky": {
        "hooks": {
            "pre-commit": "npm test",
            "pre-push": "npm test"
        }
    },
    "devDependencies": {
        "husky": "^3.0.9"
    }
}

**Comment by genk1** [comment]
その上で helloworldを少し編集して再度 add & commitしてみる

**Comment by genk1** [comment]
```
ossgateway $git commit -m 'test'
husky > pre-commit (node v12.7.0)

> @ test /Users/amagata/GenkiPro/ossgateway
> echo 'Error: no test specified'

Error: no test specified
On branch master
Changes not staged for commit:
        modified:   package.json

no changes added to commit
```
コミット時に起きたエラーメッセージ

**Comment by nico-hn** [comment]
https://github.com/gatsbyjs/gatsby/blob/master/package.json
内の設定をメモしました。
``
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged || node scripts/on-lint-error.js"
    }
  },
``

**Comment by genk1** [comment]
npm testを動かすために package.json内の scripts部分にtestを追加して
テストするためのファイルを追加した
```
{
    "scripts": {
        "test": "node test/testrunner.js"
    },
    "husky": {
        "hooks": {
            "pre-commit": "npm test",
            "pre-push": "npm test"
        }
    },
    "devDependencies": {
        "husky": "^3.0.9"
    }
}
```

**Comment by genk1** [comment]
# 環境

OS: `macOS catalina version 10.15`
uname: `Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64`

# 再現手順

ドキュメント通り進めた
packageが追加されていなかった

# 期待される結果

ドキュメントに対してpackageが追加される様を見せて 初めての人がわかる

# 実際の結果

huskyの設定のみが入っていて scriptsの部分や install devendency の部分が書いていない

**Comment by genk1** [comment]
P 課題: huskyが動くべきための情報がすべて記載されていない
P 設定を入れて置かなければわからない
P precommitで呼び出される scriptsがあるかどうかわかっていない

S package.jsonに記載されるべき npm testの scripts設定部分とインストールされるところの devDependency部分を追加する

**Comment by genk1** [comment]
"pre-commit": "npm test",
対象の testスクリプトが存在していない？

**Comment by genk1** [comment]
add sample scripts & installed dependency

**Comment by nico-hn** [comment]
備忘です。

pull requestを出す場合は、プルリク用のブランチを切っておいた方が良いと思います。
（master → masterでは、マージされた時のコミットログがぱっと見分かりにくかったりするため）

**Comment by genk1** [comment]
https://github.com/typicode/husky/pull/600
