### ISSUE TITLE
OSS Gateワークショップ 2016-09-24: gfd3e34s: composer: 作業ログ

### ISSUE THREAD

**Issue by gfd3e34s** [oss-gate/workshop#133]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by gfd3e34s** [comment]
・作業：READMEを読む
・思っていること：
READMEを読んだけど、概要だけで具体的な内容がよくわからなかった
普段使ってる印象としては、ライブラリがコマンド一つでインストールできる＋ライブラリを読み込むときも短いコードで済むんだなぁくらいの印象

**Comment by gfd3e34s** [comment]
・作業：インストール
・思っていること：
https://getcomposer.org/download/
コマンドが4行あるけど、実際、内部で何やってるかわからない

**Comment by gfd3e34s** [comment]
・作業：インストール
・思ってる事：
一応、先ほどのインストールコマンドの解説が書いてあった
```
Download the installer to the current directory　←ダウンロードする
Verify the installer SHA-384 which you can also cross-check here ←使える暗号化方式をチェックしてる？？
Run the installer　←インストールスクリプトを実行する
Remove the installer ←削除する
```

```
#Verify the installer SHA-384 which you can also cross-check here
check hereのリンク先↓
https://composer.github.io/pubkeys.html
```
やっぱり、よくわからない

**Comment by gfd3e34s** [comment]
・作業：インストールオプションを使ってみる
・思ってる事：

```
[yamataka1@centos66 composer]$ mkdir ../composer2
[yamataka1@centos66 composer]$
[yamataka1@centos66 composer]$ php composer-setup.php --install-dir=/opt/project                       /composer2
Could not open input file: composer-setup.php
[yamataka1@centos66 composer]$
[yamataka1@centos66 composer]$ php composer-setup.php --install-dir=/opt/project                       /composer2
[yamataka1@centos66 composer]$ php composer-setup.php --install-dir=/opt/project/composer2
Could not open input file: composer-setup.php
[yamataka1@centos66 composer]$ 
# インストールスクリプトがカレントディレクトリになかった！
[yamataka1@centos66 composer]$
[yamataka1@centos66 composer]$ cd ../composer2/
#インストールスクリプトを落とした
[yamataka1@centos66 composer2]$ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
[yamataka1@centos66 composer2]$ php composer-setup.php --install-dir=/opt/project/composer2
Downloading 1.2.1...

Composer successfully installed to: /opt/project/composer2/composer.phar
Use it: php /opt/project/composer2/composer.phar
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

The xdebug extension is loaded, this can slow down Composer a little.
Disabling it when using Composer is recommended.
[yamataka1@centos66 composer2]$
```

**Comment by gfd3e34s** [comment]
・作業：インストール
・思っていること：
もう一回インストールが必要だった！？
```
ドキュメント：https://packagist.org/
php composer.phar install
```

**Comment by gfd3e34s** [comment]
・作業：動かす
・思っていること：
ライブラリのインストールをしたいけど、どうやって探せばいいんだろう。
実際に書くコマンド？はどこから調べればいいのかな
https://packagist.org/
```
Define Your Dependencies

Put a file named composer.json at the root of your project, containing your project dependencies:

{
    "require": {
        "vendor/package": "1.3.2",
        "vendor/package2": "1.*",
        "vendor/package3": "^2.0.3"
    }
}
For more information about packages versions usage, see the composer documentation.
```

**Comment by gfd3e34s** [comment]
・作業：動かす
・思っていること：
インストールするパッケージはページ上部の検索窓で探すことができた
https://packagist.org/
検索窓を右上に常に出してくれるUIとかだといいのかなぁ

**Comment by gfd3e34s** [comment]
・作業：動かす
・思っていること：
```
↓のコマンドはcomposer.jsonを書いてから実行するものだった
 php composer.phar install
```
installという先入観から、先に実行するものだと思った

**Comment by gfd3e34s** [comment]
・作業：動かす
・思っていること：
インストール成功した

```
パッケージはPHPUnit
https://packagist.org/packages/phpunit/phpunit
```

```
[yamataka1@centos66 composer2]$ php composer.phar install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phpunit/php-timer (1.0.8)
    Downloading: 100%

  - Installing phpunit/php-invoker (1.1.4)
    Downloading: 100%

Writing lock file
Generating autoload files
[yamataka1@centos66 composer2]$ cat composer.json
{
  "require": {
    "phpunit/php-invoker":"~1.1"
  }
}
[yamataka1@centos66 composer2]$
```

**Comment by gfd3e34s** [comment]
自分の考え
・composerでやりたいことがわかっていたら、READMEの導入手順は簡潔でわかりやすい
・composerを初めて知った人は、パッと見だと最終的に自分にどう利益がでるのかわからないんじゃないか

**Comment by gfd3e34s** [comment]
自分の要望：
READMEだけだと利便性がわからなく、使う気にならないのでコーディングでの具体事例がREADMEにほしい

着地（伝えること）：
usageって書いてあるんだから、usageのリンクもほしい（exampleなコーディングが載ったURL）
概要を知るのであればインストールだけじゃなく、usageのリンクも載ってるとわかりやすいよね

文：
basic-usageのリンクのせてほしい https://getcomposer.org/doc/01-basic-usage.md
READMEにbasic-usageのリンクがあるとより素早くcomposerの利便性が伝わるのではないでしょうか
インストール/ユーザーのセクションにbasic-usageを追加してはいかが

題名：Add a link of basic-usage in the README
本文：
As brief introduction, add link of [basic-usage](https://getcomposer.org/doc/01-basic-usage.md) to 'Installation / Usage' section in the README .

**Comment by kou** [comment]
お疲れ様でした！
