### ISSUE TITLE
ワークショップ開催テンプレートへの作業項目の追加

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1337]
issue templateを編集する権限が無いため、どなたか代わりにご対応頂けますでしょうか？

----

#1263 でいうと「やること」の配下に「 `tutorial/retrospectives/prepare.rb` を実行してアンケートのテンプレートを追加する」を加えていただけないでしょうか？
具体的に行う作業の手順は以下の通りとなります。

```
$ git clone git@github.com:oss-gate/workshop.git
$ cd tutorial/retrospectives/
$ ./prepare.rb yyyy-mm-dd-location workshop
$ git add yyyy-mm-dd-location
$ git commit -m "Add retrospective templates for yyyy-mm-dd-location workshop"
$ git push
```

pushできる権限が必要なので、可能であれば何らかの操作をトリガーに自動化した方が良いような気がしています。

**Comment by kou** [comment]
issue templateは https://github.com/oss-gate/workshop/tree/master/.github/ISSUE_TEMPLATE を更新するだけなので直接pushしたりpull requestを作ったりすれば編集できるんですよ。

**Comment by piroor** [comment]
なんと！ 設定画面からやるという説明を見つけて諦めてしまっていました。
