### ISSUE TITLE
OSS Gate Meetup: Online: 2019-11-07

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1338]
## このテンプレートを使う時にやること

以下のテンプレートを埋めてタイトルに設定する

    OSS Gate Meetup: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}

タイトル例

    OSS Gate Meetup: Tokyo: 2019-07-08

## このissueは何のために使うの？

どんな人が来て、何をするかを共有するために使います！

## なんで共有をするの？

以下のような理由があります！

- 雑談するきっかけを作る
- イベント終了後にどんなイベントになったかをふりかえられるようにする

## いつ共有をするの？

当日の始めに、共有する時間をそれぞれ設けます！

## どうやって共有するの？

以下のことを両方やってください！

- 会場で口頭で喋る
- このissueにコメントで書く

## 始めに喋る/書くとよさそうなこと

以下に示す内容のいずれかで大丈夫です！

- 呼んでほしい名前
- 普段やっていること
- 普段利用/開発しているもの
- 当日やること
- フォローアップの人は[続きをするissue](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+Workshop)
- 「よろしくお願いします！」

## 始めの共有ができたあと

共有ができたあともissueにコメントしたかったらしましょう！

- リンクの共有
- 感想
- 色々メモ

**Comment by tdtds** [comment]
tDiaryのAmazonプラグインでPA-API v5対応をやります！

**Comment by knokmki612** [comment]
[issue cleaner](https://github.com/oss-gate/issue-cleaner)のドキュメンテーションがラチが明かなそうなので、とりあえず手元でデプロイできることを確認してみることと、
YYYY-M-Dなどになっているissueをリネームして閉じられるようにできればしたいと思います！ https://github.com/oss-gate/issue-cleaner/issues/9

**Comment by knokmki612** [comment]
あれ…？

`npm i -g now` して `now` したらデプロイ自体はすぐできた…でも必要な環境変数をなにも用意していないので、これでは動かないよな

**Comment by knokmki612** [comment]
now secretsがすでに設定されていました…290日前とか出てるので、issue-cleanerを作った時のが残っていたみたいです

**Comment by knokmki612** [comment]
とりあえずデプロイはできるみたいなので2番目のほうをやろうと思います

> YYYY-M-Dなどになっているissueをリネームして閉じられるようにできればしたいと思います！

**Comment by swamp09** [comment]
もともとvue-router のドキュメントの修正をやろうとしていたのですが、今見たらすでに修正されていたので、https://github.com/thoughtbot/administrate/pulls に自分が出したPRが依存関係でCIが落ちているので治せるか見てみます。（他のPRも同じ理由で落ちていそう）

**Comment by knokmki612** [comment]
プルリクにしてデプロイできた(はず)！ https://github.com/oss-gate/issue-cleaner/pull/16

**Comment by knokmki612** [comment]
@tdtds swamp09さんの声ってきこえてましたか…？

**Comment by knokmki612** [comment]
次回は12/12にオンラインで開催することになった！

**Comment by knokmki612** [comment]
今日は @swamp09 さんの音が私の方で聞こえていなくて(@swamp09 さんのほうでは私の音は聞こえていた)、私が絶妙なタイミングで相槌的なものを聞こえていない状態でこなしていたというミラクルが起きていたみたいです。

次回から音の疎通確認をイベント開始時に欠かさずおこなうようにしたいと思います
