### ISSUE TITLE
OSS Gate Workshop: Osaka: 2019-11-24: Noyanagi: KeePass: Work log

### ISSUE THREAD

**Issue by noyanagi** [oss-gate/workshop#1339]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tshkh8** [comment]
サポーターの大澤です。よろしくお願いします。

**Comment by noyanagi** [comment]
大柳です、よろしくお願いします。

**Comment by noyanagi** [comment]
今日はKeepassにする。
KeePassホームページはhttps://keepass.info/help/v1/license.html

**Comment by noyanagi** [comment]
ライセンスは GNU General Public License version 2でした。

**Comment by noyanagi** [comment]
Open Source Initiavive
https://opensource.org/licenses/alphabetical

**Comment by noyanagi** [comment]
GNU General Public License version 2 (GPL-2.0)を確認する。

**Comment by noyanagi** [comment]
https://keepass.info/index.html
ホームページ

**Comment by noyanagi** [comment]
Installation
https://keepass.info/help/v2/setup.html

**Comment by noyanagi** [comment]
トップページにインストールの説明がない
いきなりダウンロード？

**Comment by noyanagi** [comment]
Helpに行くとInstallationがある

**Comment by noyanagi** [comment]
Installation:
To install KeePass, run the KeePass-1.xx-Setup.exe file and follow the wizard.

**Comment by noyanagi** [comment]
V1とV2がありわかりにくい

**Comment by noyanagi** [comment]
HelpはV1が上に表示されるために間違えやすい
DownloadはV2が表示される

**Comment by noyanagi** [comment]
KeePass 2.43 releasedページ
https://keepass.info/news/n190910_2.43.html

**Comment by noyanagi** [comment]
You can get it here: Download KeePass 2.43.

**Comment by noyanagi** [comment]
https://keepass.info/download.html
ダウンロードページに進む

**Comment by noyanagi** [comment]
どれをダウンロードしたらよいかわからない

**Comment by noyanagi** [comment]
https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.43/KeePass-2.43-Setup.exe/download
広告ページが表示されて、うっかりクリックしてしまいそう。

**Comment by noyanagi** [comment]
待っているとダウンロードが始まる
ダウンロードフォルダーの指定をする

**Comment by noyanagi** [comment]
KeePass-2.43-Setup (1).exeを実行する。

**Comment by noyanagi** [comment]
日本語を選択
契約書の同意

**Comment by noyanagi** [comment]
コンポーネントの選択は分からないのでデフォルトのまま次へ

**Comment by noyanagi** [comment]
追加タスクの選択
デフォルトのまま次へ

**Comment by noyanagi** [comment]
インストール準備完了
インストールをクリック

**Comment by noyanagi** [comment]
完了をクリック

**Comment by noyanagi** [comment]
First Steps Tutorial
このページがトップページ、ダウンロードページにない
Helpページに出てくる

**Comment by daddygongon** [comment]
updateかfirst installかの区別がつかなかった．
それで，どうしていいかわからなくなった．
どうしていけばいいかがそれ以降進めようがない．
2.43を動かせてるんで，問題ないが，
exe, zipの違いが初心者にはわかりにくい．
過去のバージョンはいるかどうか．
データファイルは共通なので，色々なデバイスで共有することが可能．
そこに不都合はない．

**Comment by daddygongon** [comment]
クラウドとローカルどちらが信頼できるか．
マルチプラットフォームでどれを選ぶかの選択肢が多すぎるが，
それをどう整理するのがいいのか．
macでは下の方にある KeePassX を使わないといけない．

**Comment by daddygongon** [comment]
選択肢の説明がいるかも．

**Comment by noyanagi** [comment]
わからない人はこちらをダウンロード
新規インストールはこちら
通常はこちら
案内を表示したほうが初心者にわかりやすい

**Comment by noyanagi** [comment]
KeePassを初めてダウンロードしようとすると、ダウンロードページ（https://keepass.info/download.html）
に4つのボタンが表示されており、私はどれを選択するのがベストかわかりませんでした。
他のページなど色々調べて、結局左上のボタンを選択しました。
ほとんどの人にとっては左上のボタンを選択するのがよいと思います。
「わからない人はこちらをダウンロード」あるいは「新規インストールはこちら」のような説明を左上ボタンに目立つように記入してはどうでしょうか。
初心者が迷わなくて助かると思います。

**Comment by noyanagi** [comment]
KeePassを初めてダウンロードしようとすると、ダウンロードページ（https://keepass.info/download.html）
に4つのボタンが表示されており、私はどれを選択するのがベストかわかりませんでした。
他のページなど色々調べて、結局左上のボタンを選択しました。
ほとんどの人にとっては左上のボタンを選択するのがよいと思います。
「わからない人はこちらをダウンロード」あるいは「新規インストールはこちら」のような説明を左上ボタンに目立つように記入してはどうでしょうか。
初心者が困らないと思います。

**Comment by noyanagi** [comment]
When I try to download KeePass for the first time, 

There are four buttons displayed in download page
 and I was not sure which one to choose.

I looked at other pages and selected the upper left button.

For most people, the upper left button is a good choice.

Why don't you write a prominent explanation on the upper left button like "Download here if you don't know well" or "Click here for new installation".

I think beginners will not be in trouble.

**Comment by noyanagi** [comment]
When you try to download KeePass for the first time, download page (https://keepass.info/download.html)
There are four buttons displayed and I was not sure which one to choose.
I looked at other pages and selected the upper left button.
For most people, the upper left button is a good choice.
Why don't you write an explanation on the upper left button like "Download here if you don't know" or "Click here for new installation".
I think beginners will not be in trouble.

**Comment by noyanagi** [comment]
https://sourceforge.net/p/keepass/feature-requests/2510/

**Comment by noyanagi** [comment]
![image](https://user-images.githubusercontent.com/10088107/69504737-c1c2b580-0f68-11ea-8a3a-1293a5484ac8.png)

**Comment by noyanagi** [comment]
![image](https://user-images.githubusercontent.com/10088107/69504781-149c6d00-0f69-11ea-8a6e-7aae4be6dc4e.png)

**Comment by noyanagi** [comment]
早速リプライがありました。
