### ISSUE TITLE
OSS Gateワークショップ 2016-09-24: sakag1975: mbed-os: 作業ログ

### ISSUE THREAD

**Issue by sakag1975** [oss-gate/workshop#134]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by sakag1975** [comment]
* 作業 README読む
* 思っていること Getting Started for Developersじゃなくて、Getting Started for Contributors

を参照する?
備考（必要な付加情報。）

**Comment by sakag1975** [comment]
* 作業 /docs の中をみる

**Comment by sakag1975** [comment]
* 作業 mbed-os/docs/BUILDING.md を読む
* 思っていること 環境のコンパイル？とおもったがテストの情報がかいているっぽい

**Comment by sakag1975** [comment]
* 作業 ユーザとして使うのでREADME.mdに戻り https://docs.mbed.com/docs/mbed-os-handbook/en/5.1/ を読む

**Comment by sakag1975** [comment]
* 作業 https://docs.mbed.com/docs/mbed-os-handbook/en/5.1 を読む
* 思っていること 開発ツール mbedCLIの記述を見つけてアクセスする
https://docs.mbed.com/docs/mbed-os-handbook/en/5.1/dev_tools/cli/
* 思っていること githubからdownloadしてコンパイルすると思ったが開発ツールはすでに用意されているっぽいからちょっと違う気がする

**Comment by sakag1975** [comment]
* 作業 README.mdを読む
* Getting Started for Developersはその環境を使用した開発を行うのが対象な気がする
* Getting Started for Contributors SDKの話があったのでこちらが今回参加したい対象?

**Comment by sakag1975** [comment]
* 作業 /docs を読む
* 思った事 /docsを読めとあるがどのドキュメントから読むのか?

**Comment by sakag1975** [comment]
* 作業 /docs の各ファイルを読む 上から開いてみる
* 思った事 環境を作りたいが何をすれば良いかわからなく、ファイル名からも判断ができなかったので
* TESTING.md テストmbed SDKのテストのこと

**Comment by sakag1975** [comment]
* 作業 mbed-os/docs/BUILDING.md を開く
* 思った事 Prerequisites に書かれているgitリポジトリが現在参照しているリポジトリと違う

**Comment by sakag1975** [comment]
* 作業 https://github.com/mbedmicro/mbed.git を開いてみる
* 思ったこと https://github.com/ARMmbed/mbed-os へ転送されているのでおなじもの?
* URLが古いままなのか?

**Comment by sakag1975** [comment]
* 作業 git clone https://github.com/mbedmicro/mbed.git
* 思ったこと でかいのでdownloadに時間がかかる

**Comment by sakag1975** [comment]
* 作業 pythonのバージョンを確認
* python -v 起動しちゃった?
* python --help でバージョンの確認方法を確認
* python -Vでバージョンがわかった V2.7.10

**Comment by sakag1975** [comment]
* 作業 Installing setuptools https://pythonhosted.org/an_example_pypi_project/setuptools.html#installing-setuptools-and-easy-install
* 思った事 まずセットアップから

**Comment by sakag1975** [comment]
* 作業 setuptoolsの準備
* 思ったこと pypiなに?

**Comment by sakag1975** [comment]
* 作業 PyPI
* PyPI - the Python Package Index
* 思った事 読み方わからない「ぱいぴーあい」ということ

**Comment by sakag1975** [comment]
## 振り返り
* mbedOSヘのAPI追加など行いたいなら、どこを参照するか?とかが記載されていればいいかも
* pythonのバージョン確認方法があると助かる(不要かもしれません)

**Comment by sakag1975** [comment]
自分の思っていること
https://github.com/ARMmbed/mbed-os/blob/master/docs/BUILDING.md
* git clone するURLが違う
* あれ?今アクセスする環境と違うのと不安になる
* 改めてアクセスすると現在アクセスしているURLへジャンプするから問題は発生しない
* 古いURLでもcloneできたので問題なかった

**Comment by sakag1975** [comment]
開発者にとって分かりやすくする
* 初めて環境を構築する
* mbedOSをユーザとして使用しているので今後少しでもコミットしていきたい
* 不安を感じないため、現在アクセスしているURLのリポジトリだということがわかる記述が良いと思う
* 問題は発生していない
* ドキュメトのリポジトリ名と現在のリポジトリ名が違うのでドキュメントが更新されていないのでしょうか?
*

**Comment by sakag1975** [comment]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug | Enhancement | Question
- Related issue: `#abc`
- Priority: Blocker | Major | Minor

---------------------------------------------------------------
## Bug

**Target**
K64F|??

**Toolchain:**
GCC_ARM|ARM|IAR

**Toolchain version:**

**mbed-cli version:** 
(`mbed --version`)

**meed-os sha:**
(`git log -n1 --oneline`)

**DAPLink version:**

**Expected behavior**

**Actual behavior**

**Steps to reproduce**

----------------------------------------------------------------
## Enhancement

**Reason to enhance or problem with existing solution**

**Suggested enhancement**

**Pros**

**Cons**

-----------------------------------------------------------------

## Question

**How to?**

**Comment by kou** [comment]
お疲れ様でした！
