### ISSUE TITLE
    OSS Gate Workshop: Osaka: 2019-11-24: y3134: Redmine: Work log

### ISSUE THREAD

**Issue by YO3134** [oss-gate/workshop#1340]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
西谷です．サポーターさせていただきます．

**Comment by YO3134** [comment]
大瀧です。ビギナーです、よろしくお願い申し上げます。

**Comment by YO3134** [comment]
GNU General Public License v2
GNUは伝染性が強いもの、MITとはかなり性格が違う

**Comment by YO3134** [comment]
redmine.jpにてDL
BitNamiInstallerで構築

**Comment by daddygongon** [comment]
日本語はインストールでしたね．さらに，PCに一括して入れるセットがあるんですね．

**Comment by YO3134** [comment]
一括インストールはやっぱり便利ですね！
ブラウザを利用して、起動したRedmine:IPに接続しました。

**Comment by YO3134** [comment]
Redmine.JPのインストール直後のadminユーザーログインが
手順通りにログインできない状態です。
なんでだろう？

**Comment by YO3134** [comment]
loginフォームにて
user/pass
admin/admin
を入力

**Comment by YO3134** [comment]
redmine公式DL
https://www.redmine.org/projects/redmine/wiki/Download
4.0.5 (2019-10-19):
redmine-4.0.5.tar.gz (md5: d25649272a9c347e4368cdd50e039e86)

`ootakikaakira-no-MacBook-Pro:redmine-4.0.5 yoshiki$ ls -l
total 48
-rw-r--r--@  1 yoshiki  staff   241 10 19 18:33 CONTRIBUTING.md
-rw-r--r--@  1 yoshiki  staff  2970 10 19 18:33 Gemfile
-rw-r--r--@  1 yoshiki  staff   205 10 19 18:33 README.rdoc
-rw-r--r--@  1 yoshiki  staff   275 10 19 18:33 Rakefile
drwxr-xr-x@  6 yoshiki  staff   192 10 19 18:33 app
-rw-r--r--@  1 yoshiki  staff   860 10 19 18:33 appveyor.yml
drwxr-xr-x@  7 yoshiki  staff   224 10 19 18:33 bin
drwxr-xr-x@ 13 yoshiki  staff   416 10 19 18:33 config
-rw-r--r--@  1 yoshiki  staff   154 10 19 18:33 config.ru
drwxr-xr-x@  3 yoshiki  staff    96 10 19 18:33 db
drwxr-xr-x@  8 yoshiki  staff   256 10 19 18:33 doc
drwxr-xr-x@  5 yoshiki  staff   160 10 19 18:33 extra
drwxr-xr-x@  3 yoshiki  staff    96 10 19 18:33 files
drwxr-xr-x@  8 yoshiki  staff   256 10 19 18:33 lib
drwxr-xr-x@  3 yoshiki  staff    96 10 19 18:33 log
drwxr-xr-x@  3 yoshiki  staff    96 10 19 18:33 plugins
drwxr-xr-x@ 13 yoshiki  staff   416 10 19 18:33 public
drwxr-xr-x@ 17 yoshiki  staff   544 10 19 18:33 test
drwxr-xr-x@  9 yoshiki  staff   288 10 19 18:33 tmp
drwxr-xr-x@  2 yoshiki  staff    64 10 19 18:33 vendor
ootakikaakira-no-MacBook-Pro:redmine-4.0.5 yoshiki$ rackup
Please configure your config/database.yml first
Could not find gem 'rails (= 5.2.3)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
ootakikaakira-no-MacBook-Pro:redmine-4.0.5 yoshiki$ bundle install
Please configure your config/database.yml first
Please configure your config/database.yml first
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Fetching rake 13.0.1
Installing rake 13.0.1
Using concurrent-ruby 1.1.5
Fetching i18n 0.7.0
Installing i18n 0.7.0
Fetching minitest 5.13.0
Installing minitest 5.13.0
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Fetching activesupport 5.2.3
Installing activesupport 5.2.3
Using builder 3.2.3
Fetching erubi 1.9.0
Installing erubi 1.9.0
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.5
Installing nokogiri 1.10.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.5/ext/nokogiri
/Users/yoshiki/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20191124-2450-1g4z2kl.rb
extconf.rb
checking if the C compiler accepts  -I
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... *** extconf.rb
failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/yoshiki/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler
failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in
try_compile'
	from /Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
	from /Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found
here:

/Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0-static/nokogiri-1.10.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.5 for
inspection.
Results logged to
/Users/yoshiki/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0-static/nokogiri-1.10.5/gem_make.out

An error occurred while installing nokogiri (1.10.5), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.10.5' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  rails was resolved to 5.2.3, which depends on
    actioncable was resolved to 5.2.3, which depends on
      actionpack was resolved to 5.2.3, which depends on
        actionview was resolved to 5.2.3, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri
`

**Comment by YO3134** [comment]
xcode認証errorが発生  
`ootakikaakira-no-MacBook-Pro:redmine-4.0.5 yoshiki$ gcc --version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ootakikaakira-no-MacBook-Pro:redmine-4.0.5 yoshiki$ `

**Comment by YO3134** [comment]
xcode認証が難しいため。
localにDLした環境(bitnami)にて、DBを対話環境にて上書きを行う。

`root@debian:/opt/bitnami/apps/redmine/htdocs# rackup
oot@debian:/opt/bitnami/apps/redmine/htdocs# bundle exec rails c production
Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable

Loading production environment (Rails 4.2.8)
irb(main):001:0> User.find_all()
NoMethodError: undefined method `find_all' for #<Class:0x0000557bf54a6138>
Did you mean?  find_by_mail
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
	from (irb):1
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/app_rails_loader.rb:45:in `require'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/app_rails_loader.rb:34:in `loop'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/cli.rb:5:in `<top (required)>'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/bin/rails:9:in `require'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/bin/rails:9:in `<top (required)>'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/bin/rails:23:in `load'
	from /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/bin/rails:23:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
	from /opt/bitnami/ruby/bin/bundle:23:in `load'
	from /opt/bitnami/ruby/bin/bundle:23:in `<main>'
`

**Comment by YO3134** [comment]
bitnamiVMのログイン失敗の結果を、redmineにてlogを検証して実行

**Comment by daddygongon** [comment]
https://docs.bitnami.com/installer/apps/redmine/get-started/first-steps/
に英語ではuser name, passwordが

**Comment by daddygongon** [comment]
まずは，何をすればできたかをメモってください．

**Comment by daddygongon** [comment]
今見ると右下のManageが燦然と輝いていますが，
やってた時は気がつかなかったですよね．
少なくとも，4人が見えて，気がついていませんでしたね．

**Comment by YO3134** [comment]
bitnami仮想環境 redmineを起動した際に、
右下のbitnami アイコン をクリックすると
http://192.168.64.2/bitnami/index.html　にて
Username: user
Password: bitnami1
が表示されます。

**Comment by YO3134** [comment]
何をして失敗したか、メモを詳しくかく
どこのサイトを参考にしたURL等も詳しく

**Comment by YO3134** [comment]
参考にしたURLを調査する

日本語サイトRedmine.JPのログイン方法
http://redmine.jp/tech_note/first-step/admin/login/

**Comment by YO3134** [comment]
webPageコメントに記述することも手段の１つ

**Comment by YO3134** [comment]
Github上のredmine/redmineはミラーなので
issueが用意されていないので、
日本語サイト
http://redmine.jp/tech_note/first-step/admin/login/
にてコメントします。

**Comment by YO3134** [comment]
コメント内容
何が、何をして、何をしなかったか

環境: macOS 10.14.6

 1. redmine.jp リンク先のbitnamiパッケージをDL
 https://bitnami.com/stack/redmine

 2. OSを選択してDL
https://bitnami.com/stack/redmine/installer

 アプリケーションが立ち上がるので、ブラウザにて接続
接続した際に、インストール後の初期設定にて
admin/adminを入力したが上手くログインできなかった

その後、bitnamiにて確認したところbitnamiではadmin/userを表示済み
https://docs.bitnami.com/installer/apps/redmine/get-started/first-steps/

OS X VM
The password can be obtained by clicking the Bitnami badge at the bottom right corner of the application welcome page.

そのため、日本語サイトのみ表記に欠けている状態となります。

**Comment by daddygongon** [comment]
インストールを試み，このdocumentにしたがってloginフォームにて
user/pass
admin/admin
を入力したところ，
result : ユーザー名もしくはパスワードが無効です
との結果となりました．

正しくはapplication画面の右下に現れるManageボタンを押下して現れる情報を入力するのが
正しいようです．英語のサイト，
https://docs.bitnami.com/installer/apps/redmine/get-started/first-steps/
にはその記述が見あたります．

初心者にとっては少し気づきにくいので，
Redmine.jpの記述も修正していただくよう，よろしくご対応をお願いします．

* インストール手順
環境: macOS 10.14.6

http://redmine.jp/install/内の PCにお試しでインストールのリンク先の
BitNami Redmine Installer bitnamiパッケージをDL
https://bitnami.com/stack/redmine
に行って，DEPLOYMENT OFFERINGのon my computer のOSを選択してDL
https://bitnami.com/stack/redmine/installer
しました．

* 失敗
アプリケーションを立ち上げて、ブラウザにて接続
接続した際に、インストール後の初期設定にて
admin/adminを入力したが上手くログインできませんでした．

* 英語のマニュアル
その後、bitnamiにて確認したところbitnamiではadmin/passwordは以下の通り説明されていることを確認．
https://docs.bitnami.com/installer/apps/redmine/get-started/first-steps/

OS X VM
The password can be obtained by clicking the Bitnami badge at the bottom right corner of the application welcome page.

**Comment by YO3134** [comment]
上記のぐらい詳細に書かないと、フォーム内容的には不足

**Comment by YO3134** [comment]
インストールを試み，このdocumentにしたがってloginフォームにて
user/pass
admin/admin
を入力したところ、
result : ユーザー名もしくはパスワードが無効です
との結果が表示されました。

正しくはapplication画面の右下に現れるManageボタンを押下して現れる情報を入力するのが
正しいようです。

英語のサイトには、その記述が見あたります．
https://docs.bitnami.com/installer/apps/redmine/get-started/first-steps/

初心者にとっては少し気づきにくいので，
Redmine.jpの記述も修正していただくよう，よろしくお願いします。

・インストール手順
環境: macOS 10.14.6
http://redmine.jp/install/内の PCにお試しでインストールのリンク先の
BitNami Redmine Installer bitnamiパッケージをDL
https://bitnami.com/stack/redmine
に行って，DEPLOYMENT OFFERINGのon my computer のOSを選択してDL
https://bitnami.com/stack/redmine/installer
しました。

・失敗
アプリケーションを立ち上げて、ブラウザにて接続
接続した際に、インストール後の初期設定にて
admin/adminを入力したが上手くログインできませんでした．

・英語のマニュアル
その後、bitnamiにて確認したところbitnamiではadmin/passwordは以下の通り説明されていることを確認。
https://docs.bitnami.com/installer/apps/redmine/get-started/first-steps/

OS X VM
The password can be obtained by clicking the Bitnami badge at the bottom right corner of the application welcome page.

**Comment by YO3134** [comment]
公式の報告フォームが見当たらないので、
Redmine.JP:ドキュメント >はじめてのRedmine >Redmineを使い始めるための初期設定 >ログイン
http://redmine.jp/tech_note/first-step/admin/login/
にてコメント

**Comment by daddygongon** [comment]
すでにコメントが反映されていますね．すぐに修正していただけるでしょう．
