### ISSUE TITLE
OSS Gateワークショップ 2016-9-24: ktomosada: angular-canvas-painter: 作業ログ

### ISSUE THREAD

**Issue by ktomosada** [oss-gate/workshop#135]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by ktomosada** [comment]
* 作業：READMEを読む
* 思っていること：READMEだけでどれだけ内容わかるかなぁ？

**Comment by ktomosada** [comment]
作業：READMEを読んでとりあえずインストール
思っていること：Usageの1はコマンド、2以降がインストールしたものの書き方だから分けて書いてあった方がいいのかな？？

(備考)URL: https://github.com/pwambach/angular-canvas-painter

**Comment by ktomosada** [comment]
作業：READMEを読む(で思ったこと)
思っていること：英語の一行単位なら何となくわかるけど、全体としたらもやっとした理解になる(英語力の問題説あり)

**Comment by ktomosada** [comment]
作業：DEMOする(インストール後回し)
思っていること：demoのソースと動作を比較できるといいなぁ。
　　　　　　　　READMEで書いてある内容が網羅されてて動作込みで確認したいなぁ。

**Comment by ktomosada** [comment]
作業：DEMOを動かして
思っていること：
・初期選択の色がわからない(多分黒と思うけど２番目以降に選んだやつは選んだことがわかるようになる)
・線の太さについてDEMO画面上ではわかりにくい

**Comment by ktomosada** [comment]
作業：DEMOからview codeへ移動
思っていること：DEMOのサンプルソースを期待したが、READMEに戻ってしまった。

**Comment by ktomosada** [comment]
作業：DEMOを動かして②
思っていること：
・READMEで書いてある内容で動作がどうなるか知りたかったが、色選択、文字の太さ、undoの３つしか確認できなかった。

**Comment by ktomosada** [comment]
作業：READMEを読んでとりあえずインストール(改めて)
思っていること：Usageの1はコマンド、2以降がインストールしたものの書き方だから分けて書いてあった方がいいのかな？？

**Comment by ktomosada** [comment]
作業：angularjsの環境を作る
思っていること：どうやったっけ？

**Comment by ktomosada** [comment]
作業：angularjsのインストール方法をググる
思っていること：インストール方法忘れた。

**Comment by ktomosada** [comment]
作業：view codeでREADMEに戻る理由
思っていること：demoやsampleというディレクトリで分かれているわけではなく、index.htmlにデモソースが書いてあったからだと思う。

**Comment by ktomosada** [comment]
作業：報告したい内容一覧
・初期選択の色がわからない(多分黒と思うけど２番目以降に選んだやつは選んだことがわかるようになる)
・線の太さについてDEMO画面上ではわかりにくい
・optionsの動作をdemoで網羅してあったら(それを確認できたら)よかったなぁ。
・demoからview codeで遷移した時にdemoのソースが見たかった。でも、元のページに戻った。

**Comment by ktomosada** [comment]
作業：報告したい内容一覧の整理①
①DEMO画面の初期選択の色は黒だが、選択済みの状態になっていない。(一応予想は出来るけど・・・)

**Comment by ktomosada** [comment]
作業：報告内容(日本語版)
・DEMO画面についてですが、初期選択時の色は黒となっていますが画面上の色を指定するアイコンはどれも選択された状態になっていません。
URL: http://pwambach.github.io/angular-canvas-painter/

**Comment by ktomosada** [comment]
作業：報告内容(日本語版)②
・DEMO画面についてですが、ページを開いた直後に色を選択せずにキャンバスに描画した時、黒いラインで描かれますが色選択のアイコンはどれも選ばれていませんでした。
　初期状態で黒が選択済みになっていた方がいいのではないでしょうか？
URL: http://pwambach.github.io/angular-canvas-painter/
<img width="635" alt="2016-09-24 16 19 26" src="https://cloud.githubusercontent.com/assets/14807597/18806838/677752c8-8273-11e6-997e-fa6281c60c0f.png">

**Comment by ktomosada** [comment]
作業：報告内容(英語版)②
タイトル：color selector on DEMO page
内容：
 1. open DEMO page
 2. draw a line
 3. drew line color is black. but color selector is not selected

why is not selected black?
 
<img width="537" alt="2016-09-24 16 41 36" src="https://cloud.githubusercontent.com/assets/14807597/18806930/111712ee-8276-11e6-8644-1aa9f6bce0ef.png">

**Comment by ktomosada** [comment]
作業：issueの投稿
内容：下記URLにissueを投稿。
　英語で長文は辛いので箇条書きにする。
　レイアウト関連なら画像貼れば一発で伝わりやすい。
URL: ttps://github.com/pwambach/angular-canvas-painter/issues/30 (先頭にhをつけること)

**Comment by kou** [comment]
お疲れ様でした！
