### ISSUE TITLE
PyCon JP 2020内でOSS Gateワークショップをやってみよう！

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#1350]
https://oss-gate.github.io/

> 「OSS Gate」は、OSS開発に参加する「入り口」を提供する取り組みです。 OSS開発に未参加の人を参加する人へ、少し参加したことがある人を継続的に参加する人へ。そうやってOSS開発に参加する人を継続的に増やしていく。それが「OSS Gate」の目的です。 

PythonもPythonで使えるライブラリーの多くもOSSである。OSSの開発に参加する人が増えればPythonコミュニティーもうれしいはず。

OSS GateコミュニティーにはまだOSSの開発に参加したことがない人がはじめの一歩を踏み出すためのサポートをするノウハウがある。PyCon JP 2020でそのノウハウを活用してPython関連のOSSの開発に参加し始める人を増やせたらOSS GateもPyCon JPもうれしいのではないか。
（OSS Gateは（Python関連の）OSSの開発に参加する人が増えてうれしい、PyCon JPはPythonおよびPython関連のOSSが活発になるとコミュニティーの活性化につながってうれしい。）

**Comment by kou** [comment]
@atomiyama @satoryu やり取りする場所を作りました！

**Comment by hanahiroAze** [comment]
@kou @satoryu 
@atomiyama よりお話を伺いました。PyConJP2018-2019で事務局スタッフをしてました、hanahiroAzeです。よろしくおねがいします。

**Comment by kou** [comment]
@satoryu 次のアクションとして、どんな感じでコラボできるとよさそうか提案するのはどうですか！？

**Comment by hanahiroAze** [comment]
12/5に2020に向けたミーティングがあります。もしよろしければ「にぎやかし」枠で参加いただき、提案いただくのが早いかと思います。
https://pyconjp-staff.connpass.com/event/155690/
@kou @satoryu

**Comment by satoryu** [comment]
明日は用事があって参加できそうにないです。 
12/18も今のところ行けなさそう…
https://pyconjp-staff.connpass.com/event/155695/

**Comment by kou** [comment]
@satoryu 行けませんだけだと話が進まないと思うので、なにか話を進めるアプローチはないですかねぇ。

**Comment by kou** [comment]
@satoryu 今週末のワークショップで @tdtds と @yuseitahara に相談してみるのはどうですか！？
（@yuseitahara はPyCon JPのスポンサーもしているNexediの日本法人の代表取締役社長です。）

**Comment by satoryu** [comment]
@kou そうしまーす

**Comment by yuseitahara** [comment]
一番てっとり早いのはPyConJPに必ず付いてくるスプリントの日にスプリントの枠の中でOSSGateをやることでしょうね。会期中にオープンスペースがあれば(PyCONJPに有ったか覚えていませんが)、そこでやるのもいいかも。あとは事前に宣伝すれば興味のある人は来るでしょう。

**Comment by satoryu** [comment]
昨日、 @yuseitahara さん達と話をして、[提案いただいた内容](https://github.com/oss-gate/workshop/issues/1350#issuecomment-564410229) で実行委員の方に話を持ち込んでみようという話になりました。
先日教えていただいたスプリントですが、無料で参加でき、スプリント自体の開催趣旨とOSS Gateの目的がかなり近いのでお互いにメリットを感じられそうですね。

という話を12/18のスタッフミーティングで提案してみようと思います。
https://pyconjp-staff.connpass.com/event/155695/
もしご都合がつくようでしたら @yuseitahara さんもご一緒していただけると助かります（心細い）。

**Comment by yuseitahara** [comment]
私も18日のミーティングに申し込みました。スタッフの方々とはまったく面識ないですが、人数少ないので話をしやすいと思います。

**Comment by yuseitahara** [comment]
忘れないうちに昨日のPyConスタッフミーティングのことをざっと書いておきます。

座長の西村さんとスタッフの皆さんとお話しができまして、pyconjpのslackに専用チャンネル(非公開)を設けていただきましたpyconjp自体が来年の準備を始めたばかりで、まだ何も決まっていないところなのですが、このまま話を進めていけばOSS Gateをpyconjpで開催できると私は思います。
https://pyconjp.slack.com/

**Comment by yuseitahara** [comment]
私はOSS GateとPyConJPのスプリントの両方の経験があるので、ここでPyConJPのスプリントについて簡単に説明します。来年のPyConJPでスプリントが開催されるかはまだ決まっていませんが、これまでずっと開催されていたので、おそらく来年もあるでしょう。

スプリントは基本的にスクリーンとマイクが一つある広い部屋で開催されます。参加者は自由でお題も自由です。スプリントは小さな開発イベントで、スプリント会場では複数のスプリントが同時に行なわれます。

一つのスプリントには一人のスプリントリーダーと数名(多くても5〜6名)のスプリント参加者がいます。スプリントリーダーはスプリント開催日より前に、スプリントリーダーとして名乗り出て、自分が行うスプリントのお題を発表します。スプリント参加者は当日まで何もしなくて良く、当日に会場に来てスプリントリーダーに参加したいと言えばいいだけです。

スプリントはだいたい午前10時から午後5時くらいまで行われます。朝にスプリントリーダー全員が会場のスクリーンとマイクを使って順番にこれから自分がやるスプリントの内容について、会場の人たちに説明をします。この説明を聞いてからどのスプリントに参加するか決める人もいると思います。

広い会場の中で、一つのスプリント参加者は全員でリーダーの近くに着席してリーダーに色々とアドバイスをもらいながらスプリントのお題をやります。途中で昼食の休憩がありますが、それ以外はこのグループの単位でみんなもくもくと作業します。この間は誰もスクリーンやマイクを使いません。

スプリントの最後の1時間くらいに各スプリントの成果発表を行います。このときにスプリントのグループごとに順番に、スプリントリーダー(加えて、もしかしたらそのスプリントの参加者代表)がスクリーンとマイクを使って手短に話をします。

スプリントはこういう枠組みで行われます。OSS Gate的な観点で考えると、ビギナーの人がやりたいと思っていたOSSをお題にしたスプリントが開催されるのであれば、OSS Gateよりもスプリントに参加したほうがいいでしょう。国内外から来るPyConJP参加者の中にはOSSコア開発者もいるので、そういう人たちがスプリントリーダーをやるときがあります。

OSS Gateの枠組みとスプリントの枠組みを比べると、スクリーンとマイクの使い方、進行の仕方が違うので、同じ部屋でスプリントとOSS Gateを混ぜてやるのはちょっと難しいかなと個人的には思います。OSS Gateは専用の部屋があったほうがいいと思います。

**Comment by satoryu** [comment]
自分もさっきメモにまとめてたので、貼っときます。

----

昨晩、 @yuseitahara  さんと一緒にスタッフミーティングに行って、OSS Gateワークショップの提案をしてきました。
昨晩は、来年の座長の西村さんに、OSS Gateについて、今回のワークショップの共催について説明させていただきました。
共感していただき、建設的に話を進めていこうという話になりました。
今のところPyconjp側もスプリントと一緒に開催するのが良さそうという話です。

昨晩話したときに出てきた、具体化に向けての懸念点は下記3つかなと思います。

1. スプリントはその場に集まった人たちとテーマを持ってきたオーナーが自由に集まってもくもく会のように実施するのに対して、固まった流れに沿って実施していくOSS Gateワークショップであるので参加者の期待値のズレが出るのではないか
  - おそらく開催内容について齟齬が出ないように事前告知等で対応できそう
2. それぞれで必要とする会場設備が異なる。
  - スプリント会場に隣接したところでOSS Gateワークショップを開催するという案が出ました。数年前にTokyuRuby会議の脇で開催させていただいたように気になった人が寄ってきて見学できるような形にできると良さそう。
  - まだスプリントの会場が決まっていないので、会場を探す際に考慮していただくand/or会場探しのお手伝いをする。
3. ワークショップを安定して開催できるようにサポーターの確保（OSS Gate側のタスク）
  - いつものワークショップのようにサポーターに応じてビギナー枠を増やす方式だと参加できるのか読めない。

お互いにwin-winに実施できるように運営だけでなく、趣旨や目的の設計が必要なので、それについて次回の運営ミーティングあたりでコンテンツ委員の方々と上の点をつめていきたいと思います。

----

**Comment by knokmki612** [comment]
スプリントのオンライン開催は開催する方向で、～8/15にスプリントリーダー(期間中取り組むことが決まっていて人を募ったり1人でやったりする人)の募集をする

@satoryu さんがスプリントにOSS Gateとして参加するモチベーションをお持ちの様子

**Comment by knokmki612** [comment]
@satoryu 
扱うテーマで「こういうのがしたい！」みたいなものって固まってたりしますか？

OSS Gateとして参加することを考えた時、個人的には2通りあるかなと思いました。もちろん他のテーマもアリだと思います

1. OSSを特定せず、チームに人が入ってきたら「メモをとろう」「フィードバックポイントをみつけよう」「フィードバックしよう」の順番を体験してもらう(ワークショップのような進行はなく個別にやりとりする)
2. OSS GateがOSS Gateのために使っているもので取り組む
    - アンケートの構文チェック
        - Circle CIからGitHub Actionsへの以降ができそうかのDraft PRがある @tdtds https://github.com/oss-gate/workshop/pull/1382
    - issueを自動で閉じる
        - vercel now v1が先月か今月で終了なのでGitHub Actionsに移行する @knokmki612 https://github.com/oss-gate/issue-cleaner/issues/11

**Comment by kou** [comment]
@yuseitahara https://pyconjp.connpass.com/event/183507/ PyCon JP 2020 Sprintに応募したのでどうやってやるのがよさそうか相談しましょう！

**Comment by satoryu** [comment]
@knokmki612 1を考えていました。PyConでやるので、Python関連のOSSで何かやりたいと思う人が自然と現れるのではないかと。もし何もネタが無い人のために2を用意しておくのは良いと思います。
@kou 自分も既に応募してました。とりあえずそのままにしておいて、中の人から何かいわれたらどちらかキャンセルすればいいのかな。

**Comment by kou** [comment]
あ、私は応募していません！
「 @satoryu が応募した」とつけ忘れました！すみません！

**Comment by kou** [comment]
PyCon JP 2020 Sprintって1週間なんですね！

Apache Arrowというやつを日本のPython界隈でも紹介したいと思っていたので、平日の日中にpyarrow関連のなにかみたいなので時間を使わせてもらいたいかも！

**Comment by yuseitahara** [comment]
私も1のやり方が主でいいと思います。1週間開催ということなので、参加希望の方には事前にいつ参加するか言ってもらうのがいいんでしょうね。私たちが1週間待機しているのはなかなか難しいと思いますから。

**Comment by kou** [comment]
> みなさんのテーマの目的を達成できるなら、期間中すべて活動頂いても、1日だけ活動頂いてもOKです。 （キックオフ時にプロジェクトごとに決めていただきます。）

> 2020/08/22（土） | 13:00開始 | Zoom/Discord | キックオフイベント

私は8月22日 13:00から参加することはできないのでpyarrow関連で絡むのは厳しいのかな。。。

**Comment by knokmki612** [comment]
kouさんが活動する日が案内できるのであれば、「何日にApache Arrow関連のなにかをします！」とキックオフ日に代理でどなたかに発表してもらうとかできるかもしれませんね？
OSS Gateのスプリントの中でやるのか、Apache Arrowのスプリントでやるのかとか詰めるところあるかもしれませんが
あと、参加者は期間中のチーム間の移動も気軽にして良い(Discordのチャンネルを移るだけ)ので、目的次第ですが、期間を通して人が見込めるかはあまり気にしないでも大丈夫かなと思います。スプリントリーダー1人だけで取り組むチームもあるみたいですし。

**Comment by satoryu** [comment]
いろいろゴタゴタして残り10日をきってしまった…

1週間は自由に使えるようなので、複数のことができるのかな、と思いました。
自分が下のように考えています。
- 8/23 に通常のOSS Gate ワークショップを実施
- 8/24 - 8/29 のいずれかの夜（火、木曜20時あたりとか）に、ワークショップのフォローアップ
  - ワークショップ内でフィードバックを出せなかった人が続きをやったり
  - Issueまでは出せたから、その先のPRまで作ってみたり
  - ワークショップでやったことを違うOSSでまたやってみたり

@kou 上とは別でどこか平日にpyarrowネタで実施するのは良いと思います。 @knokmki612 さんが言っているように8/22は何をやるか代理で発表すればいいと思います。
自分が8/22に参加するので、内容を教えていただければ！
あと、日程調整次第ですがお手伝いできるかもです。

と、ここまで書いて気づいたのですが、通常回をやるのであればビギナーのキャパシティを決めるために事前にサポーターを募らないといけないのでした。
どなたか参加できそうな方はいらっしゃいませんか？

**Comment by kou** [comment]
では、こんな感じでお願いします！

pyarrow関連でなにかやりたいけどOSSの開発に参加するのははじめてで不安という人は、まずはOSS Gateワークショップにpyarrowを題材に参加してください。

次のような人は期間中はいつでもいいので https://gitter.im/red-data-tools/ja に来て、pyarrowの○○をやりたいです！と書いてください。

  * そんなに不安じゃない人
  * これをやりたいとかがある人
  * ワークショップに参加して不安が払拭できて、さらにまだなにかやりたいという人

https://gitter.im/red-data-tools/ja に常にだれかが張り付いているわけではないので必ずしもすぐにレスポンスがあるわけではありませんが、1日以内にはなにかしらレスポンスがあって進め方だったりなんなりと相談しながら進められます。

8月26日（水）の10:00-21:30（特に10:00-17:00）はだれかしらすぐに反応ができるはずなので（ Red Data Toolsのオンライン開発イベント https://speee.connpass.com/event/185989/ をその時間にやるので）、その時間帯はほぼ確実にインタラクティブに相談できます。

**Comment by kou** [comment]
ワークショップのサポーターですが、オンラインなので、東京以外（関西とか広島とか）のサポーター経験者も誘ってみませんか！？

**Comment by kou** [comment]
たぶん、サポーターを募るのは https://gitter.im/oss-gate/tokyo とか https://gitter.im/oss-gate/kansai とか https://gitter.im/oss-gate/hiroshima とか https://gitter.im/oss-gate/shimane とかの方がここよりも適切だと思います！

**Comment by piroor** [comment]
サポーター参加したいと考えていますが、サポーター参加のみの場合でもSprint自体への参加エントリーが必要でしょうか？

**Comment by satoryu** [comment]
@piroor ありがとうございます！
参加エントリーは私だけで十分なようで、後ほどDiscordサーバーの招待URLをお送りします。

**Comment by piroor** [comment]
了解です！

**Comment by satoryu** [comment]
@knokmki612 @tdtds お二人ももしご都合が合えば是非。

**Comment by kou** [comment]
@yuseitahara 2020-08-23（日）にオンラインでのワークショップのサポーターはどうですか！？
https://github.com/oss-gate/workshop/issues/1350#issuecomment-672972596

**Comment by satoryu** [comment]
@piroor Discordの招待URLをGitterのプライベートメッセージで送りましたー

**Comment by satoryu** [comment]
@knokmki612 @tdtds @yuseitahara みなさま、ご都合いかがでしょうか？

**Comment by yuseitahara** [comment]
23日午前中に用事が入ってしまったので遅れますが14時すぎから参加します。その後の夜のフォローアップはいつでも大丈夫です。

**Comment by tdtds** [comment]
@satoryu 声をかけていただいてありがとうございます。最近多忙で、OSS Gateに丸一日あけるのはかなり厳しいのです……。時間ができるようになったら復帰するのでもうしばらくお待ちを。

**Comment by Nyoho** [comment]
広島からやってきました。OSS Gate のオンライン参加でサポータに挑戦してみようと思います! よろしくお願いいたします。

**Comment by satoryu** [comment]
@yuseitahara @Nyoho お返事ありがとうございます！
Discordの招待URLはGitterのプライベートメッセージで送りました。ご確認ください。

@tdtds うぅ、了解です :sob:

**Comment by knokmki612** [comment]
@satoryu 
色々取り仕切りありがとうございます。あとお返事遅れてすみません。
8/23のワークショップ参加いたします。平日の期間も可能な範囲で参加したいと思います。

**Comment by chanyou0311** [comment]
私も広島から、サポーターとして参加できればと思います！
よろしくお願いします！

**Comment by kou** [comment]
やってみた！
まとめは https://github.com/oss-gate/oss-gate.github.io/pull/104 。
