### ISSUE TITLE
OSS Gate Workshop: monotaro: 2019-12-02: imrankln: magento2: Work log

### ISSUE THREAD

**Issue by imrankln** [oss-gate/workshop#1355]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by imrankln** [comment]
ライセンスの確認します。

**Comment by imrankln** [comment]
Magento 2 のライセンスはここにあります。
https://github.com/magento/magento2/blob/2.3-develop/LICENSE.txt

**Comment by imrankln** [comment]
Magento ２のライセンスはOpen Software License ("OSL") v. 3.0と確認しました。

**Comment by imrankln** [comment]
インストールの方法調べています。

**Comment by imrankln** [comment]
インストールするために２つ点があります
１．システム要件
２．アプリのインストール

**Comment by imrankln** [comment]
ステップ　１．
githubにシステム要件のリンクがありました。
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements.html

**Comment by imrankln** [comment]
ステップ　１．
MagentoのためにlinuxーOSが必要です。例えばRHEL, CentOS, Ubuntu, Debian etc. 
以下のOSにはMagento直接インストールできません、virtual env.が必要です:
Windows OS
Mac OS

**Comment by imrankln** [comment]
RAM 2GBいります。

**Comment by imrankln** [comment]
他の必要なもの：
Composer
Mysql: 5.6, 5.7
PHP: 7.x

**Comment by imrankln** [comment]
環境が立ち上がったら、Magentoインストールに進みます。

**Comment by imrankln** [comment]
Magento インストールのためMagentoソースコードかアプリがダウンロードする。
githubからcloneしてもいいし、以下のurlからダウンロードする
www.magento.com/download

**Comment by imrankln** [comment]
Magento インストール、GUI からできます、またCLI からもできます。
CLIからインストールするために以下のコマンドを使いました
magento setup:install --<option>=<value> ... --<option>=<value>
option-valueはこのペイジーから選びます。
https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html

**Comment by imrankln** [comment]
Problem faced:
インストールする時phpの以下のextensionが必要です。phpのextensionインストールしなかったらエラーがでます
ext-bcmath、ext-ctype、ext-curl、ext-dom、ext-gd、ext-hash、ext-iconv、ext-intl、ext-mbstring、ext-openssl、ext-pdo_mysql、ext-simplexml、ext-soap、ext-spl、ext-xsl、ext-zip、lib-libxml

**Comment by imrankln** [comment]
インストールの後、以下のfolderとfileにwrite permissionが必要です。
vendor
app/code
app/etc
pub/static
Any other static resources
generated/code
generated/metadata
var/view_preprocessed

Magento root directory　から以下の１lineコマンド使ったら、file/folderにpermissionができます。

cd /var/www/html/magento2 && find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} + && find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} + && chown -R :apache . && chmod u+x bin/magento

**Comment by Silver-birder** [comment]
https://github.com/magento/magento2/issues/new?template=bug_report.md

bugReport is below.

```
<!---
Please review our guidelines before adding a new issue: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fields marked with (*) are required. Please don't remove the template.
-->

### Preconditions (*)
<!---
Provide the exact Magento version (example: 2.3.2) and any important information on the environment where bug is reproducible.
-->
1.
2.

### Steps to reproduce (*)
<!---
Important: Provide a set of clear steps to reproduce this bug. We can not provide support without clear instructions on how to reproduce.
-->
1.
2.

### Expected result (*)
<!--- Tell us what do you expect to happen. -->
1. [Screenshots, logs or description]
2.

### Actual result (*)
<!--- Tell us what happened instead. Include error messages and issues. -->
1. [Screenshots, logs or description]
2.

```

**Comment by Silver-birder** [comment]
https://github.com/magento/magento2/issues/new?template=feature_request.md

```
<!---
Important: This repository is intended only for Magento 2 Technical Issues. Enter Feature Requests at https://github.com/magento/community-features. Project stakeholders monitor and manage requests. Feature requests entered using this form may be moved to the forum. Fields marked with (*) are required. Please don't remove the template.
-->

### Description (*)
<!--- Describe the feature you would like to add. -->

### Expected behavior (*)
<!--- What is the expected behavior of this feature? How is it going to work? -->

### Benefits
<!--- How do you think this feature would improve Magento? -->

### Additional information
<!--- What other information can you provide about the desired feature? -->

```

**Comment by imrankln** [comment]
https://github.com/magento/magento2/issues/new?template=feature_request.md



### Description (*)

System requirement should be more simplified and compact. Like one Vagrantfile or docker image should provide from Magento. 

### Expected behavior (*)

Creating system environment for Magento installation.

### Benefits

It will save time and make steps more easier for Magento installation. Currently there are lots of pre-installation steps. Additional PHP extensions are needed, Apache/nginx server configuration needs special setup.

### Additional information

**Comment by imrankln** [comment]
https://github.com/magento/magento2/issues/25871
