### ISSUE TITLE
OSS Gate Workshop: MonotaRO: 2019-12-02: nonnhima: Jenkins: Work log

### ISSUE THREAD

**Issue by nonnhima** [oss-gate/workshop#1356]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nonnhima** [comment]
Jenkinsのライセンスを調べる
https://github.com/jenkinsci/jenkins/blob/master/LICENSE.txt

**Comment by nonnhima** [comment]
ライセンスの内容が同一のため、OSSであることを確認した
https://opensource.org/licenses/MIT

**Comment by nonnhima** [comment]
HPからDL
https://jenkins.io/download/
↓
DLボタンを押しても何も起きない（更新されるのみ）

**Comment by nonnhima** [comment]
Download Jenkins 2.190.3 for:
のDLを試みる

**Comment by yoichi** [comment]
サポーターです。よろしくおねがいします

**Comment by nonnhima** [comment]
「Jenkinsは Homebrew パッケージマネージャーを使用してインストールできます 。」
↓
Homebrewがない

**Comment by nonnhima** [comment]
https://brew.sh/index_ja
Homebrewを入れてみる

**Comment by nonnhima** [comment]
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

のコマンドをターミナルに叩いてインストール

**Comment by nonnhima** [comment]
Downloading Command Line Tools for Xcode
から進まなかったのでXcodeをAppStoreからインストール

**Comment by nonnhima** [comment]
Xcodeインストール後、偶然なのかHomebrewのインストールが
Installing Command Line Tools for Xcode
まで進んだ

**Comment by nonnhima** [comment]
HEAD is now at fcfa80a63 Merge pull request #6794 from MikeMcQuaid/fix-cask-style
で再びとどまる

**Comment by nonnhima** [comment]
Homebrewのインストール終了
※注意　日本語に翻訳してインストール手順を確認中

**Comment by nonnhima** [comment]
JenkinsのHPに戻る。
https://jenkins.io/download/lts/macos/

上から順番に、実行
 brew install jenkins-lts

**Comment by nonnhima** [comment]
```
erumonoMacBook-puro:~ elmo$ brew install jenkins-lts
jenkins-lts: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.
erumonoMacBook-puro:~ elmo$ 
```

**Comment by nonnhima** [comment]
1つ目からエラーになった

**Comment by nonnhima** [comment]
Java 1.8 がなかったので
コマンド
brew cask install homebrew/cask-versions/adoptopenjdk8
でJava 1.8をインストール

**Comment by nonnhima** [comment]
パスワードを求められたので、MACのパスワード入力
Java 1.8インストール完了

**Comment by nonnhima** [comment]
再度以下のコマンドでJenins1つ目インストール
brew install jenkins-lts

**Comment by nonnhima** [comment]
１．最新のLTSバージョンをインストールできた

**Comment by nonnhima** [comment]
３．Jenkinsサービスを開始　のコマンド
brew services start jenkins-lts

**Comment by nonnhima** [comment]
```
==> Successfully started `jenkins-lts` (label: homebrew.mxcl.jenkins-lts)
erumonoMacBook-puro:~ elmo$ 
```

**Comment by nonnhima** [comment]
３．Jenkinsサービスを開始できた

**Comment by nonnhima** [comment]
HPでマニュアルを探しているときにダウンロードのリンクを発見。
ダウンロードのページに飛ぶと思いきやなにかが勝手にダウンロードされた
https://jenkins.io/doc/pipeline/tour/getting-started/

**Comment by nonnhima** [comment]
Jenkins使い方の入門ページ
https://jenkins.io/doc/pipeline/tour/getting-started/

いきなり4のURLに飛んでページが開いたことを確認

**Comment by nonnhima** [comment]
```
==> Successfully started `jenkins-lts` (label: homebrew.mxcl.jenkins-lts)
erumonoMacBook-puro:~ elmo$ cd /Users/elmo/.jenkins/secrets/initialAdminPassword
-bash: cd: /Users/elmo/.jenkins/secrets/initialAdminPassword: Not a directory
erumonoMacBook-puro:~ elmo$ cat /Users/elmo/.jenkins/secrets/initialAdminPassword
XXXXXXXXXXXXXXXXXXXXXXXXXXX
erumonoMacBook-puro:~ elmo$ 
```

**Comment by nonnhima** [comment]
光っているのでsugestedを選択
<img width="1028" alt="スクリーンショット 2019-12-02 午後2 46 01" src="https://user-images.githubusercontent.com/35522042/69933581-9284e900-1512-11ea-90fa-ac91bf74170c.png">

**Comment by nonnhima** [comment]
<img width="1013" alt="スクリーンショット 2019-12-02 午後2 47 37" src="https://user-images.githubusercontent.com/35522042/69933640-be07d380-1512-11ea-942a-7fcecf823411.png">

**Comment by nonnhima** [comment]
Create First Admin User
ユーザー名: |  
パスワード: |  
パスワードの確認: |  
フルネーム: |  
メールアドレス：

**Comment by nonnhima** [comment]
３０分の休憩後、項目に入力してSave and Continueクリック
<img width="1036" alt="スクリーンショット 2019-12-02 午後3 43 00" src="https://user-images.githubusercontent.com/35522042/69936238-89981580-151a-11ea-85f2-8a9c10ec780d.png">

**Comment by nonnhima** [comment]
リロードしてもう一度内容を入力、無事Instance Configurationが表示
Jenkins URL：http://localhost:8080/

**Comment by nonnhima** [comment]
<img width="1439" alt="スクリーンショット 2019-12-02 午後3 46 26" src="https://user-images.githubusercontent.com/35522042/69936377-f27f8d80-151a-11ea-9b40-edbb49d045ba.png">

**Comment by nonnhima** [comment]
今回の提案
https://github.com/oss-gate/workshop/issues/1356#issuecomment-560238835

提案
１．ダウンロードのページに使い方のリンクがあればわかりやすい
２．ターミナル上にリンクを出してしまう：　http://localhost:8080/

**Comment by nonnhima** [comment]
それぞれのフィードバック先の確認
１．Jenkinsのコンテンツの編集　Jenkins-io
２．homebrewのJenkinsパッケージ

**Comment by yoichi** [comment]
1. https://jenkins.io/download/lts/macos/
のソースはたぶんhttps://github.com/jenkins-infra/jenkins.io のあたり。

2. homebrew の jenkins-lts は https://formulae.brew.sh/formula-linux/jenkins-lts のあたりかな

**Comment by nonnhima** [comment]
初めてダウンロードする想定で、1の提案を採用

**Comment by nonnhima** [comment]
１．ダウンロードのページにDL後のアクションについて記述があるとわかりやすい

●フィードバックのきっかけ
Homebrew packageを使ってMacOSのJenkinsをDLした場合、
DL後のアクションがマニュアル（https://jenkins.io/doc/pipeline/tour/getting-started/#download-and-run-jenkins）に掲載されている内容と異なる。

●フィードバック内容
・MacOSのダウンロードページに、DL後の手順として、下記2点の情報を追加してほしい
https://jenkins.io/download/lts/macos/

・追加したい手順
- Browse to http://localhost:8080.
- Follow the instructions to complete the installation.

**Comment by nonnhima** [comment]
contributing.adocを読む
https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#newcomers

**Comment by yoichi** [comment]
手順書いてるページのソースは
https://github.com/jenkins-infra/jenkins.io/blob/master/content/_partials/osx-brew-installer.html.haml
ぽい。

**Comment by nonnhima** [comment]
追加する文
___
After starting the Jenkins service, browse to http://localhost:8080 and follow the instructions to complete the installation.

**Comment by nonnhima** [comment]
コミットメッセージ
___
Add the instruction after Installation for MacOS

Pick up No. 4 and 5 from https://jenkins.io/doc/pipeline/tour/getting-started/#download-and-run-jenkins for MacOS users

**Comment by nonnhima** [comment]
プルリク作成しました
https://github.com/nonnhima/jenkins.io/pull/1#issue-347484725

**Comment by yoichi** [comment]
![スクリーンショット 2019-12-03 6 34 40](https://user-images.githubusercontent.com/107537/69997253-11bc0080-1597-11ea-9472-6f17dbd34897.png)

取り込まれてContributors が +1 されましたね  🎉

**Comment by nonnhima** [comment]
Jenkinsのcontributorsの一員になれました👏
ありがとうございます！完全にOSS Gateをくぐることができました
