### ISSUE TITLE
OSS Gate Workshop: monotaro: 2019-12-02: risa0320: julia: Work log

### ISSUE THREAD

**Issue by risa0320** [oss-gate/workshop#1357]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by risa0320** [comment]
ライセンスを確認。
ライセンスファイルはこれ→https://github.com/JuliaDocs/Documenter.jl/blob/master/LICENSE.md
> The Documenter.jl package is licensed under the MIT "Expat" License:
Expatをググる。
https://www.wikidata.org/wiki/Q18526198
MIT licenceの中の、一部に属しているOSSのよう。

**Comment by risa0320** [comment]
julia自体はすでにPCに入っている

> /usr/local/bin/julia

**Comment by risa0320** [comment]
検索しても公式で出てこないーー
https://docs.julialang.org/en/v1/search/?q=uninstall

**Comment by risa0320** [comment]
https://github.com/JuliaLang/julia
でやっとuninstall 方法を発見！
./julia を削除すればパッケージ自体も削除されるよう

**Comment by risa0320** [comment]
削除してみる

**Comment by risa0320** [comment]
`rm -rf ~/.julia` 実行
→juliaが起動できる。なぜ！！
確かに、ファイルなくなっている。

**Comment by risa0320** [comment]
コマンドの場所を確認
`$ which julia
/usr/local/bin/julia`

**Comment by risa0320** [comment]
こやつを削除
`rm -rf /usr/local/bin/julia`

julia起動できないので削除されったぽい。

**Comment by risa0320** [comment]
次に、install 方法を確認する

**Comment by risa0320** [comment]
https://github.com/JuliaLang/julia
にinstall方法を発見。

**Comment by risa0320** [comment]
バイナリを使うかgit cloneか

**Comment by risa0320** [comment]
以前はバイナリからだったので、今回はgit cloneにしてみる。

**Comment by risa0320** [comment]
`git clone git://github.com/JuliaLang/julia.git`
でinstall。
ファイル数が多く、なかなか終わらない。

**Comment by risa0320** [comment]
手順どおり、
`git checkout v1.3.0` でバージョンを最新化。

**Comment by risa0320** [comment]
ホームディレクトリに ./juliaがあることを確認。
この中に移動して、makeを実行する

**Comment by risa0320** [comment]
githubより
> Building Julia requires 2GiB of disk space and approximately 4GiB of virtual memory.

でかすぎる！！

**Comment by risa0320** [comment]
./julia を実行するとjuliaが起動する

**Comment by risa0320** [comment]
どういったissueを作成するか

- uninstall の方法がgithub にしかないので公式ドキュメントにも載せるようにする
- git clone からjulia install を行う場合、グローバルにjuliaを起動できない

**Comment by risa0320** [comment]
すでにissueが上がっていないかを確認する

**Comment by risa0320** [comment]
> git clone からjulia install を行う場合、グローバルにjuliaを起動できない

でいく。
uninstall 普段しないし、グローバルにjuliaを起動できないほうがストレスなのでこっちにする。

**Comment by risa0320** [comment]
`install` と `uninstall` でissue検索したが、出てこなかった。

もう片方は、 `global path` ,  `install global` で検索したが、同じく出てこなかった

**Comment by Silver-birder** [comment]
> uninstall 普段しないし、グローバルにjuliaを起動できないほうがストレスなのでこっちにする。

確かに！

**Comment by Silver-birder** [comment]
https://github.com/JuliaLang/julia/issues/new

こちらがissueの形式ですね。

```
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

```

**Comment by risa0320** [comment]
立てるissueの文言を日本語で考える。

```
title: git clone を使ったJuliaインストール時に、グローバルに起動できるようにしたい
explain:
github のTOPページ（https://github.com/JuliaLang/julia）の `Building Julia` よりインストールを行った際に
clone したjuliaのリポジトリ内では、 `./julia` で起動できますが、
バイナリでインストールした際ではできていた カレントの場所を選ばなず `julia` を起動できないです。
任意の場所から起動できたほうが、開発者にとってとても嬉しいです。
もしどこかにこれを実現する方法がすでにあれば、教えていただけると幸いです。
```

**Comment by Silver-birder** [comment]
title: git clone を使ったJuliaインストール時に、グローバルに起動できるようにしたい
explain:
github のTOPページ（https://github.com/JuliaLang/julia）の `Building Julia` よりインストールを行った際に
clone したjuliaのリポジトリ内では、 `./julia` で起動できますが、
バイナリでインストールした際ではできていた カレントの場所を選ばず `julia` を起動できないです。
任意の場所から起動できたほうが、開発者にとってとても嬉しいです。
もしどこかにこれを実現する方法がすでにあれば、教えていただけると幸いです。

<やったこと>
▽ install step & do
 ```
$ git clone git://github.com/JuliaLang/julia.git
$ git checkout v1.3.0
$ make
$ cd ~/.julia && ./julia
$ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> 
```

▽ expect
```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> 
```

▽ actual
```
$ julia
-bash: julia: command not found
```

**Comment by risa0320** [comment]
title : want to be able to run globally julia REPL 
explain:
When installing from “Building Julia” on the TOP page of github (https://github.com/JuliaLang/julia),
  It can be started with ./julia in the repository of git cloned julia.
Julia can't be started without choosing the current location that was made when installing with binary.
It would be great for developers to be able to start from any location.
If you already have a way to make this happen, please let me know.
<try install & make>
```
$ git clone git://github.com/JuliaLang/julia.git
$ git checkout v1.3.0
$ make
$ cd ~/.julia && ./julia
$ ./julia
              _
  _       _ _(_)_     |  Documentation: https://docs.julialang.org
 (_)     | (_) (_)    |
  _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
 | | | | | | |/ _` |  |
 | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
_/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> 
```
<except>
```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> 
```
<actually>
```
$ julia
-bash: julia: command not found
```

**Comment by risa0320** [comment]
https://github.com/JuliaLang/julia/issues/34001
にissueたてた
