### ISSUE TITLE
OSS Gateワークショップ 2016-9-24: puresnow: GIt-it (Desktop App): 作業ログ

### ISSUE THREAD

**Issue by purestsnow** [oss-gate/workshop#136]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by purestsnow** [comment]
* 作業：GIT ITを使ってみる
* 思っていること：何なのかよくわかっていない

**Comment by purestsnow** [comment]
作業：GIT とは何か
思っていること：プログラムソースなどの変更履歴を管理する分散型のバージョン管理システムのこと

**Comment by purestsnow** [comment]
作業：リポジトリ とは何か
結果：ファイルやディレクトリの状態を記録する場所

**Comment by purestsnow** [comment]
リポジトリとはフォルダみたいなもの　フォルダの状態を管理している一式
.GIT以下の　ファイル一式

**Comment by purestsnow** [comment]
GIT HUBとは　リポジトリをインターネットに上げて共有するできるようなもの

**Comment by purestsnow** [comment]
GITは自分のローカルで管理するリポジトリ（ソースコードと更新管理？）ができる
GIT HUBはそれをインターネット上にあげて、ほかの人がリポジトリを参照することができるようになる。
（会社とかでプライベートな空間を作るとお金かかるけど、基本的に無料）

**Comment by purestsnow** [comment]
GitHub Desktop 　Gitに必要なコマンド群がある
Crone repositories->  Create Branch -> Commit changes -> Share code この流れ
・リポジトリをDL　（クローン）
・もとのプログラムを残して変更（枝分かれ）
・変更をコミット
・変更をシェア

**Comment by purestsnow** [comment]
作業：GitHub Desktopとは何か
思っていること：Git HubとGIｔHub Desktopの違い
結果：

**Comment by purestsnow** [comment]
作業：Get Gitをやってみる
思っていること：Gitへの第一歩！
結果：名前とメールアドレスを登録しました。

**Comment by purestsnow** [comment]
作業：Repositoryをやってみる
思っていること：リポジトリってどうやって作るんだろう
結果：意外とあっけなくできてしまった。

**Comment by purestsnow** [comment]
作業：Commit To itをやってみる
思っていること：新しいファイルを作るの難しそう。。
結果：

**Comment by purestsnow** [comment]
作業：Commit To itをやってみる
思っていること：新しいファイルを作るの難しそう。。
結果：あら、これは便利！

**Comment by purestsnow** [comment]
作業：Remotecontorlをやってみる
思っていること：何をするものなのかな？
結果：ユーザ名を登録

**Comment by purestsnow** [comment]
作業：Forks And Clonesをやってみる
思っていること：食べるフォークとクローン羊？
結果：Forkとはほかの人のコードを持ってくること。
　　これら一連の処理はGitHub上（リモート）で行われています。
       Fork のボタンを押すと、自分のリポジトリ上に相手のリポジトリを持ってこれます
　　自分がAで相手がBなら
　　https://github.com/A/Bといった感じです。

　　それをクローンします（＝ローカルへ持ってくる）
git clone https://github.com/purestsnow/patchwork

レポジトリごとの設定が .git/config にある
C:\Users\YUKI-chan\.gitconfig

リポジトリ全体にわたる設定にはglobal付ける

**Comment by kou** [comment]
お疲れ様でした！
