### ISSUE TITLE
OSS Gateワークショップ 2016-09-24: alvis5: geckodriver: 作業ログ

### ISSUE THREAD

**Issue by alvis5** [oss-gate/workshop#137]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by alvis5** [comment]
* 作業 : READMEをよむ
* 思っていること : Marionette and geckodriver are not yet feature complete.！！！！

**Comment by alvis5** [comment]
* 作業 : ステータスページを呼んでいる
* 思っていること : バグたくさんあるなぁ。このページはどのくらいの頻度で更新されているのかなぁ。リアルタイムなのかな？　そうじゃないだろうなぁ。

**Comment by alvis5** [comment]
* 作業 : READMEを読む
* 思っていること : まずとりあえず動かしてみよう。動かし方の記述はどこにあるかな？

**Comment by alvis5** [comment]
* 作業 : READMEを読む
* 思っていること : これ？　Usage steps are documented on MDN

備考 : Usage stepsのページ
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by alvis5** [comment]
* 作業 : Usage steps を読む
* 思っていること : javascriptがいいなー

**Comment by alvis5** [comment]
* 作業 : npm install selenium-webdriver
* 思っていること : （叩いてみよう）

**Comment by alvis5** [comment]
* 作業 : Usage stepsを読む
* 思っていること : Downloadingという言葉を見つけたので、まずはDownloadingしようと思う

**Comment by alvis5** [comment]
* 作業 : geckodriverをダウンロードする
* 思っていること : デイビッド・バーンズ

**Comment by alvis5** [comment]
* 作業 : Usage stepsを読む
* 思っていること : サンプルコードないかなぁ

備考 : あった
```
const webdriver = require('selenium-webdriver');
const Capabilities = require('selenium-webdriver/lib/capabilities').Capabilities;

var capabilities = Capabilities.firefox();

// Tell the Node.js bindings to use Marionette.
// This will not be necessary in the future,
// when Selenium will auto-detect what remote end
// it is talking to.
capabilities.set('marionette', true);

var driver = new webdriver.Builder().withCapabilities(capabilities).build();
```

**Comment by alvis5** [comment]
* 作業 : 動かしてみる
* 思っていること : コピペRunだ

**Comment by alvis5** [comment]
* 作業 : 動かしてみた
* 思っていること : なんかブラウザが立ち上がったけど、うごいたのかな？

**Comment by alvis5** [comment]
* 作業 : Usage stepsを読む
* 思っていること : Using RemoteWebDriver にjavascript無いなぁ

**Comment by alvis5** [comment]
* 作業 : Usage stepsを読む
* 思っていること : これ以降の使い方は書いてないけれど、それは selenium-driverの仕事だし、いいといえばいいのかなぁ。各言語毎にあるし、全部のリンクを置くのも何かな、Selenium公式へのリンクくらいならあってもいいんだけどな、あるのかな？

**Comment by alvis5** [comment]
* 作業 : Usage stepsを読む
* 思っていること : 最後に、バグはBugzillaにあげてって書いてあるのかな。。Githubのissueとは違うのかな

**Comment by alvis5** [comment]
* 作業 : READMEを読む
* 思っていること : selenium公式のリンクは無くはないけど、コレを使ってgecko driverを動かすんだよ！みたいなのは、わからないような。概要も立ち位置が書いてあって、使い方ではない感じ

**Comment by alvis5** [comment]
* 作業 : どんなフィードバックにするか決める
* 思っていること : まずは簡単なので、Usage steps に Marionette という言葉しか無くて、（Gecko Driverはどこに言ったの？？？）という気持ちになってしまうので、Marionetteの横に、(Gecko Driver)とかの言葉を並べておいてくれると、新旧の名前が並ぶので、新しいユーザー分かるので嬉しいのになぁ。

**Comment by alvis5** [comment]
* 作業 : 既にそのissueが無いかどうか探す
* 思っていること : 割りと誰でも確実に思う事なので、もうissueがあるんじゃないかな・・・ まだ出来てないGecko Driverの開発に力を入れているので、ドキュメントは後回しになってるとか。まず、どこにissueを出してるのかしらべてみよう（Bugzillaっていうキーワードも見かけたし）

**Comment by alvis5** [comment]
* 作業 : 既にそのissueがないか探す
* 思っていること : Bugzillaをミてみよう

備考 : https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver の一番下のBugzillaリンク
https://bugzilla.mozilla.org/enter_bug.cgi?format=guided#h=dupes%7CTesting%7CMarionette

**Comment by alvis5** [comment]
* 作業 : 既にそのissueがないか探す
* 思っていること : Find Similar issueって書いてあるから、Marionetteって入れてみよう

**Comment by alvis5** [comment]
* 作業 : Usage stepsのissueを探す
* 思っていること : Usage stepsのissueってBugzillaではないのでは、どっか別のところなんじゃないか、と探す

**Comment by alvis5** [comment]
* 作業 : Usage stepsのissueを探す
* 思っていること : んー、右上にメニューっぽいのがあるなぁ。「Edit」って書いてある、とりあえず押してみよう。
→Please Sign in なるほど。

**Comment by alvis5** [comment]
* 作業 : Bugzillaでもう少し探してみる
* 思っていること : アドバイス頂いてもう少し探してみる。webdriverで探してみると Documentation Incorrect On WebDriver Tutorial Page というissueが見つかる「チュートリアルどおりやったけど、僕の環境ではエラーが起こったよ」というissueだった。同じページを対象にしていたけど、Usage stepsのissueもここに書いていいものなのかな。

備考 : https://bugzilla.mozilla.org/enter_bug.cgi?format=guided#h=dupes%7CTesting%7CMarionette （再掲）

**Comment by alvis5** [comment]
（右上のメニューにLanguageがあって、日本語も選べたよ・・・）

**Comment by alvis5** [comment]
（ん？その上に Feedback って書いてあるなぁ（汗））

**Comment by alvis5** [comment]
（Report a content problem ってあるなぁ）

**Comment by alvis5** [comment]
（Developer Documentation Request ってページに飛んだなぁ）

備考 : https://bugzilla.mozilla.org/form.doc?bug_file_loc=https%3A//developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by alvis5** [comment]
（コレかなぁ）

**Comment by alvis5** [comment]
* 作業 : 改めて Usage stepsを見る
* 思っていること : 英語に慣れていなくてパッと分からなかったけど、書いてあるっぽい

> Even though the project has been renamed to geckodriver, many of the Selenium clients look for the old name wires. You may need to rename the executable to wires to have it picked up automatically.

**Comment by alvis5** [comment]
* 作業 : 改めて 日本語の Usage stepsを見てみる
* 思っていること : さっきのところはなんて書いてあったんだろう

> プロジェクト名が GeckoDriver へ変わっても、多くの Selenium クライアントは古い名称のファイルを検索します。バイナリファイルの名前を 'wires' (古い名称) へ変更し、動作することを確認してください。

（んん？）

**Comment by alvis5** [comment]
* 作業 : wiresに変更して動かすと動かないだろうなぁと思って動かしてみて動かないことを確認した
* 思っていること : 日本語訳が間違っているような気がする。
プロジェクト名が GeckoDriver へ変わっても、多くの Selenium クライアントは古い名称のファイルを検索します。あなたは動作させるために、バイナリファイルの名前を 'wires' (古い名称) へ変更する必要があるかもしれません。
くらいじゃないのかな。
（特に、最近Seleniumが3.0に上がってクライアントも対応が増えてきたのでwiresに書き換えなくてもよいものが多くなってきたし）

**Comment by alvis5** [comment]
（さらっと書いてあるけど、なんだかもやっとする）
（やはり、サブタイトルにGeckoDriverと書いてないことの方が気になる）

**Comment by alvis5** [comment]
自分のきもち

Usage steps に 「Marionette実行ファイルを配置する」というタイトルがあるけれど、今はGeckoDriverにプロジェクトの名前が変わっているので、タイトルを「GeckoDriver実行ファイルを配置する」などに変えて、その下にGeckoDriverは旧Marionetteですと書くような感じにしてくれるとうれしい。

**Comment by alvis5** [comment]
開発者向けの説明

（ユースケースパターンでやってみる）
GeckoDriverのセットアップで、セットアップ手順を見たけれど、Setting up the Marionette executable というタイトルに混乱してしまった。他のページを参照するとGeckoDriverの以前の名前がMarionetteなのでそういう表記なのだと理解できたが、Setting up the GeckoDriver executable というタイトルにして、その下に旧名称がMarionetteだという説明を付ける形のほうが、混乱が少なくなると思う。

---

GeckoDriverのセットアップをするために、手順を見ました。GeckoDriverの手順を見ていたのに、Setting up the Marionette executableという言葉が出てきて混乱しました。他のページ(あとでリンクつける)を参照するとGeckoDriverの以前の名前がMarionetteなのでそういう表記なのだと理解できた。

以下のようにすると混乱が少なくなると思う。
* Setting up the Marionette executable を Setting up the GeckoDriver executable に変更する
* その本文に、GeckoDriverは旧Marionetteであると説明を入れる

**Comment by alvis5** [comment]
アドバイスメモ

* もっと簡易な言い回しにすると、翻訳しやすくなる
* そのまま機械翻訳しようとするよりも、自分でも訳せそうな言い回しに変えていく作戦の方がいい

混乱→みつかった
says    old name 
i understand that ~~~~ by this page
improve idea

**Comment by alvis5** [comment]
GeckoDriverのセットアップのためにこのページを参照した。Setting up the GeckoDriver executableではなくSetting up the Marionette executableという言葉が見つかった。他のページを見ることで、MarionetteはGeckoDriverの古い名前だと理解できた。

以下のように改善されるとより良くなると思う
* Setting up the Marionette executable を Setting up the GeckoDriver executable に変更する
* その本文に、GeckoDriverは旧Marionetteであると説明を入れる

**Comment by alvis5** [comment]
I referred the page (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver) to set up GeckoDriver. I found "Setting up the Marionette executable" instead of "Setting up the GeckoDriver executable". I  understood that Marionett（途中）

**Comment by kou** [comment]
お疲れ様でした！

**Comment by alvis5** [comment]
issueを立てました

https://bugzilla.mozilla.org/show_bug.cgi?id=1305248
