### ISSUE TITLE
 OSS Gate Workshop: Tokyo: 2019-12-14: woodsand: antdesign: Work log

### ISSUE THREAD

**Issue by woodsand** [oss-gate/workshop#1370]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by woodsand** [comment]
ant designのURLを発見

https://ant.design/

**Comment by woodsand** [comment]
サイトの　Get startボタンをクリックします。
https://ant.design/docs/react/introduce

**Comment by woodsand** [comment]
以下のコマンドで環境を作成します
yarn create react-app antd-react-sample

**Comment by woodsand** [comment]
https://ant.design/docs/react/getting-started　のGet startに沿って、codesandboxで環境を構築する方向に修正

**Comment by knokmki612** [comment]
> 理由は、ドキュメントにはないが、いつも使っているからです。

そうなんですね！

**Comment by satoryu** [comment]
> > 理由は、ドキュメントにはないが、いつも使っているからです。
> 
> そうなんですね！

これは早速コントリビューションチャンスでは！？

**Comment by woodsand** [comment]
今までの作業からフィードバックできそうな箇所があったので、それを記載します。

- Get startedのページの冒頭に、create-appのリンクを記載してほしい
    - ローカル環境で試したいユーザーもいるため

**Comment by woodsand** [comment]
- 変更したい内容
  - https://ant.design/docs/react/getting-started のページの3行目に、create-appで環境構築する手順のリンクをはる
  - create-appで構築した場合、index.jsではなく「src/index.jsを編集する」旨の説明を入れる


- 理由
  - ローカル環境で構築したいユーザーがわかるように
  - ant-designを検討するユーザーは、すでにローカル内でnode.jsを構築されている場合が多く、create-appを使っている方が多いと想定されるため

- その他
  - sandboxと併用してcreate-appの説明を追記してほしい
　・その場て試したいユーザーもいるため

**Comment by woodsand** [comment]
コントリビュートする方法を調査します。

**Comment by woodsand** [comment]
https://github.com/ant-design/ant-design
上記のページでcontributeガイドを読む

**Comment by woodsand** [comment]
https://ant.design/docs/react/contributing
contributeガイドのリンクを参照します。

**Comment by woodsand** [comment]
contributeガイドのリンク内のリンクを一読します。
https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by woodsand** [comment]
https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
上記は見た感じGithubの使い方のようだったので、流し読みして次に進みます。

以下のリンクを参照します。
https://ant.design/docs/react/contributing

**Comment by satoryu** [comment]
さきほどお伝えした、ドキュメントへのフィードバックする方法を探す方法ですが、リポジトリと一緒になっている場合もあれば別のリポジトリに分けられている場合色々あります。
自分がよくやるのは、以下の方法です。
- OSSのリポジトリの`docs` のようなディレクトリを探す
- OSSのリポジトリがGitHub上にある場合、オーガニゼーションがオーナーであると別のリポジトリとしてドキュメントが管理されている場合がある。
  - 探す時に、リポジトリ名が`docs`や`site`、公式ドキュメントのドメイン名（今回の場合、 `ant.design`）のものが無いか探してみる

今回は上の方法で見つからなかったので、ドキュメントのどこかにドキュメントへのフィードバック方法が書かれていないか探してみると良さそうです。

**Comment by woodsand** [comment]
> ドキュメントのどこかにドキュメントへのフィードバック方法が書かれていないか探してみると良さそうです。

ありがとうございます。
フィードバック方法が書かれてないか確認してみます。

**Comment by woodsand** [comment]
ドキュメントにのみ書かれてそうな単語でGithubリポジトリ内で検索しました。
今回は「Determinacy」で検索しました。

結果サイトの文章と一致する箇所があったので、そのファイルを編集すればpull requestを出せそうということがわかりました。

検索結果
https://github.com/ant-design/ant-design/search?q=Determinacy&unscoped_q=Determinacy

サイト
https://ant.design/

**Comment by woodsand** [comment]
https://github.com/ant-design/ant-design/blob/master/docs/react/getting-started.en-US.md

このドキュメントファイルを変更すれば、プルリクを送れそうです。

**Comment by woodsand** [comment]
修正内容は以下の文章の追加を検討しています。

編集対象ファイルURL
https://github.com/ant-design/ant-design/blob/master/docs/react/getting-started.en-US.md


---

- 追加箇所
    - 「Ant Design React is dedicated to providing a good development experience for programmers. Make sure that you have installed Node.js(> 8.0.0) correctly.」
の次の文章

- 追加文章(日本語)
     - もし、あなたがローカルPCで試したいなら、create-appコマンドを使うこともできます。
---
- 追加箇所
    - 「Replace the content of index.js with the following code. As you can see, there is no difference between antd's components and typical React components.」の直後

- 追加文章
    - もしcodesandbox以外の環境を使う場合は、編集ファイルのパスを適宜読み替えてください。
    - 例：create-appコマンドで作成した環境ならば、./src/index.js

---

**Comment by woodsand** [comment]
文章を修正しました。
- もしローカルPCで試したい場合は、"Use in create-react-app"の[Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization)を参照してください。

- "Use in create-react-app"の[Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization)で作成された環境の場合は./src/index.jsを編集してください。

**Comment by woodsand** [comment]
文章を翻訳しました。

---

- もしローカルPCで試したい場合は、"Use in create-react-app"の[Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization)を参照してください。

- If you try in local environment, Please refer to [Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization) section of "Use in create-react-app"

---

- "Use in create-react-app"の[Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization)で作成された環境の場合は./src/index.jsを編集してください。

- If you already set up by [Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization) section of "Use in create-react-app", Please replace the content of /src/index.js

**Comment by woodsand** [comment]
以下の文章を翻訳

- 概要
   - [Getting started](https://ant.design/docs/react/getting-started)に"Use in create-react-app"の[Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization)のリンクを追記しました。
      - 約：Add link [Install and Initialization](https://ant.design/docs/react/use-with-create-react-app#Install-and-Initialization) to [Getting started](https://ant.design/docs/react/getting-started)



- 理由
  - ローカル環境で構築したいユーザーがわかるように
     - 約：Notice to some users that want to try in a local environment.
  - create-react-appはすぐにセットアップできるため
     - 約：User can use create-react-app instantly because almost user already installed node.js when they inspect the ant-design

- その他(以下の文章内容は修正箇所を読めばわかる意図なので、記載しない)
  - sandboxと併用してcreate-appの説明を追記してほしい
　・その場て試したいユーザーもいるため

**Comment by woodsand** [comment]
https://github.com/ant-design/ant-design/pull/20251 でpull requestを提出しました。

**Comment by knokmki612** [comment]
できましたね！

**Comment by woodsand** [comment]
ありがとうございます！

**Comment by yuseitahara** [comment]
フィードバックできて素晴しい!

**Comment by knokmki612** [comment]
![image](https://user-images.githubusercontent.com/9744580/70846603-27d29680-1e9e-11ea-9b88-1e3b8ca54075.png)

PRのtitleにprefixを追加したほうが良さそうですね！何が追加できるか個々に書いてあります！
https://github.com/zeke/semantic-pull-requests
