### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-12-14: maesho: naoqi-os: Work log

### ISSUE THREAD

**Issue by maesho** [oss-gate/workshop#1372]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by maesho** [comment]
choregrapheというSDKの公式サイトを探します。

**Comment by maesho** [comment]
choregrapheはマルチライセンス表記があり、Softbankrobotics Europeの持ち物だった。

**Comment by maesho** [comment]
Android StudioでPepperを動かす方にOSSがあるか調べる

**Comment by maesho** [comment]
aldebaran(現SoftbankRoboticsEurope)のリポジトリからチュートリアルを発見
https://github.com/aldebaran/qisdk-tutorials

**Comment by maesho** [comment]
ライセンスが明記されていないが、libqi-javaと同じ内容が書かれているので、BSD 3-Clauseライセンスの下記忘れだと判断
https://github.com/aldebaran/libqi-java/blob/master/COPYING

**Comment by maesho** [comment]
Readmeの一番下にあるCOPYINGのリンクがない　これではせっかく興味を持ってPepperのチュートリアルを触り始めていくひとがOSSなのか判断がつかない
https://github.com/aldebaran/qisdk-tutorials/blob/master/README.md
License
See the COPYING file for the license.

**Comment by maesho** [comment]
「チュートリアルをandroid studuioでどう動かすか」の説明がなくて不親切
https://github.com/aldebaran/qisdk-tutorials
ここまで来た人はできるだろうという感じがする

**Comment by maesho** [comment]
・https://qisdk.softbankrobotics.com/sdk/doc/pepper-sdk/index.html
・https://developer.softbankrobotics.com/pepper-qisdk/getting-started
・https://github.com/aldebaran/qisdk-tutorials

チュートリアル、getting-startedの繋がりがわかりにくい。

**Comment by yuseitahara** [comment]
良いフィードバックポイントが見つかっていますね!

**Comment by maesho** [comment]
Readmeの一番下にあるCOPYINGのリンクがない
https://github.com/aldebaran/qisdk-tutorials/blob/master/README.md

**Comment by maesho** [comment]
リンク切れ
https://github.com/aldebaran/qisdk-tutorials/blob/master/COPYING

**Comment by maesho** [comment]
Broken link
https://github.com/aldebaran/qisdk-tutorials/blob/master/README.md

**Comment by maesho** [comment]
チュートリアルやドキュメントは最新のバージョンだと動かなくなったり、最新の状況と一致していないことがありがち。開発者がからすると優先順位が落ちがち。
初心者からするとフィードバックの宝庫。

**Comment by maesho** [comment]
There is no explanation of how to build the qisdk-tutorials with android studio.
https://github.com/aldebaran/qisdk-tutorials

**Comment by maesho** [comment]
リンク切れを治すくらいなら、git commandからもできるがpull requestをブラウザから行うのが手っ取り早い　
自分のリポジトリにコピーを作って、修正箇所の差分を作って、その部分を提案するのがプルリク

**Comment by maesho** [comment]
## Pepper アトリエ秋葉原 with SoftBank

[![Pepper atelier](logos/)](https://pepper-atelier-akihabara.jp/)

OSS Gate東京ワークショップの会場を提供しています。

以下は会場を提供したイベントです。

[OSS Gate東京ワークショップ2019-12-14](https://oss-gate.doorkeeper.jp/events/92469)

「Pepper アトリエ秋葉原 with SoftBank」はソフトバンクロボティクス株式会社が運営するPepper の開発を体験できるスペースです。

「アトリエ秋葉原」ではデベロッパーやクリエーターの方がロボアプリ開発のためにご利用できる Pepper を数台ご用意し、無料で体験やロボアプリの動作確認などができます。

**Comment by yuseitahara** [comment]
プルリクへのリンク
https://github.com/aldebaran/qisdk-tutorials/pull/8
