### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-12-14: Koki-kobe: Pandas: Work log

### ISSUE THREAD

**Issue by Koki-kobe** [oss-gate/workshop#1373]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Koki-kobe** [comment]
https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.htmlにてライセンスを確認。BSD 3-Clause Licenseと記載されている。
https://opensource.org/licenses/BSD-3-Clauseにてオープンソースである事を確認。

**Comment by yuseitahara** [comment]
ライセンス確認完了ですね!

**Comment by Koki-kobe** [comment]
インストールのために以下リンクを読みます。
<https://pandas.pydata.org/pandas-docs/stable/install.html>

**Comment by Koki-kobe** [comment]
アナコンダを経由してインストールする必要がありそう。以下リンクを読みます。
<https://docs.continuum.io/anaconda/install/>

**Comment by Koki-kobe** [comment]
以下リンクを読み、インストールします。
<https://docs.continuum.io/anaconda/install/linux/>

**Comment by Koki-kobe** [comment]
アナコンダの依存ソフトはインストール済みである事を確認しました。

**Comment by Koki-kobe** [comment]
以下リンクより3.7 versionをダウンロード。
<https://www.anaconda.com/distribution/#linux>

**Comment by Koki-kobe** [comment]
sha256sumコマンドにてハッシュ値を出力。
以下リンクに記載のハッシュ値と一致している事を確認できたため、インストールファイルが誤ファイルでないことを確認できた。
<https://docs.continuum.io/anaconda/install/hashes/Anaconda3-2019.10-Linux-x86_64.sh-hash/>

**Comment by Koki-kobe** [comment]
bashでインストールを開始。インストール完了。

**Comment by knokmki612** [comment]
issueのタイトルにユーザ名が2つ並んでいるので、1つ目をOSS名にすると良いです！

ふりかえりの内容としては、 `path/filename` のような例で任意のパスとファイル名にするような箇所について、読み替えるものだと知らない人が読むとそのまま実行してしまうので、「読み替えてね！」という注記をたすと誤解せずに済んで良いかも、という話になりました！

**Comment by Koki-kobe** [comment]
conda listをターミナル上で入力。インストールパッケージとバージョンが表示される事を確認した。

**Comment by Koki-kobe** [comment]
pythonをターミナル上で入力。Anacondaと正しく表示される事を確認した。

**Comment by Koki-kobe** [comment]
anaconda-navigatorをターミナル上で入力。GUIが立ち上がる事を確認した。

**Comment by Koki-kobe** [comment]
jupyterを起動。「10 minutes to pandas」のチュートリアルに沿って動作させてみる。

**Comment by Koki-kobe** [comment]
チュートリアルのIn[140]にてplt.figure()を実行した際に以下のエラーが出力された。
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-61-65b822729fc4> in <module>
----> 1 plt.figure()

NameError: name 'plt' is not defined

**Comment by yuseitahara** [comment]
フィードバックするものが見つかりましたね!!

**Comment by Koki-kobe** [comment]
■使用環境
https://www.anaconda.com/distribution/#linuxよりPython3.7 versionをインストール。
anaconda-navigatorを実行し、GUIでjupyterを起動。10 minutes to pandasのチュートリアルを読んで、pandasの機能を確認していた。

■エラー内容
In [140]: plt.figure()を実行した際に、以下のエラーが発生

NameError Traceback (most recent call last)
in
----> 1 plt.figure()
NameError: name 'plt' is not defined

pltはmatplotlib.pyplotを表している事を以下リンクより確認。
https://note.nkmk.me/python-pandas-plot/

import matplotlib.pyplot as pltを追加し再度実行したところ、エラーの出力が無くなりその先のコマンドを実行できた。

**Comment by Koki-kobe** [comment]
本件は修正内容が明らかなためissueでは無く、pull requestで対処する方向とする。
修正対象はgitの以下リンク。
<https://github.com/pandas-dev/pandas/blob/master/doc/source/getting_started/10min.rst>

**Comment by Koki-kobe** [comment]
pull requestを実行。
<https://github.com/pandas-dev/pandas/pull/30274>

**Comment by yuseitahara** [comment]
フィードバックできましたね!素晴しい!
