### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2020-01-25: kos31de: gore Work log

### ISSUE THREAD

**Issue by kos31de** [oss-gate/workshop#1385]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

GoのREPLである、goreを選んだ。
https://github.com/motemen/gore

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kos31de** [comment]
MIT Licenseであることを確認。

**Comment by kos31de** [comment]
- バージョン
go version go1.11.1 darwin/amd64

- インストールコマンド
`go get -u github.com/motemen/gore/cmd/gore`

- 結果
```
# github.com/motemen/gore
go/src/github.com/motemen/gore/gore.go:142:14: undefined: homedir
```

**Comment by atomiyama** [comment]
https://github.com/golang/go/issues/31070

**Comment by atomiyama** [comment]
https://golang.org/doc/go1.12#os

**Comment by kos31de** [comment]
以下を読んだところ、`os.UserHomerDir`が怪しい。
https://github.com/motemen/gore/blob/d2d6a78129f3580de982be30d36e341161b04e58/gore.go#L142

Go言語のリリースノートを調べた。
https://golang.org/doc/go1.12#os

`os.UserHomerDir`は1.12から追加された模様。
> The new function UserHomeDir returns the current user's home directory.

**Comment by kos31de** [comment]
goenvを入れて、goのバージョンを1.12に切り替えて、再度goreのインストールを試してみる。

**Comment by kos31de** [comment]
```
brew upgrade goenv
Warning: goenv 1.23.3 already installed
```

```
goenv install --list
Available versions:
  1.2.2
  1.3.0
  1.3.1
  1.3.2
  1.3.3
  1.4.0
  1.4.1
  1.4.2
  1.4.3
  1.5.0
  1.5.1
  1.5.2
  1.5.3
  1.5.4
  1.6.0
  1.6.1
  1.6.2
  1.6.3
  1.6.4
  1.7.0
  1.7.1
  1.7.3
  1.7.4
  1.7.5
  1.8.0
  1.8.1
  1.8.3
  1.8.4
  1.8.5
  1.8.7
  1.9.0
  1.9.1
  1.9.2
  1.9.3
  1.9.4
  1.9.5
  1.9.6
  1.9.7
  1.10.0
  1.10beta2
  1.10rc1
  1.10rc2
  1.10.1
  1.10.2
  1.10.3
  1.10.4
  1.10.5
  1.10.6
  1.10.7
  1.11.0
  1.11beta2
  1.11beta3
  1.11rc1
  1.11rc2
  1.11.1
  1.11.2
  1.11.3
  1.11.4
  1.12beta1
```

```
brew upgrade --fetch-HEAD goenv
Updating Homebrew...
Warning: goenv 1.23.3 already installed

```

**Comment by kos31de** [comment]
brewで入れたgoenvをアンインストールした。
```
 rm -rf `goenv root`
brew uninstall goenv
```

**Comment by kos31de** [comment]
gitでgoenvを入れ直した。
```
> git clone https://github.com/syndbg/goenv.git ~/.goenv
```

入っているgoのバージョンを確認。
```
> goenv versions

* system (set by /Users/kousy/.goenv/version)
  1.12.0
```

go1.12が入った。
```
> goenv global 1.12.0
> go version
go version go1.12 darwin/amd64
```

**Comment by kos31de** [comment]
インストールは成功した。
```
> go get -u github.com/motemen/gore/cmd/gore
```

しかし動かない。
```
> gore
```

**Comment by kos31de** [comment]
フィードバックできそうなこと
- goreのインストールにはgo1.12以降が必要そう。READMEに記載があるよ良さそう。

- go1.12でも動かない。

**Comment by kos31de** [comment]
### 環境
go version go1.11.1 darwin/amd64

### やったこと
インストールしようとして、以下のコマンドを叩いた。
以下のエラーが出力された。

```
$  go get -u github.com/motemen/gore/cmd/gore

# github.com/motemen/gore
go/1.11.1/src/github.com/motemen/gore/gore.go:142:14: undefined: os.UserHomeDir
```

1.12ではインストール出来て、正常に動作した。

gore.goの142行目のos.UserHomeDirがundefinedと言われていたので、go言語のリリースノートを見た。
https://github.com/motemen/gore/blob/d2d6a78129f3580de982be30d36e341161b04e58/gore.go#L142

UserHomeDirは1.12から追加されていることが分かった。
https://golang.org/doc/go1.12#os

このプルリクエストで、UserHomeDirに置き換わったことで、1.12より前のgoのバージョンでは、動作しなくなった。
https://github.com/motemen/gore/pull/158

なので、READMEに1.12以降が必要である旨を記載したい。

**Comment by kos31de** [comment]
プルリクエストを送りました。
https://github.com/motemen/gore/pull/180

**Comment by kos31de** [comment]
プルリクエストを送りました。
https://github.com/motemen/gore/pull/180
