### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2020-01-25: teslur: charty: Work log

### ISSUE THREAD

**Issue by teslur** [oss-gate/workshop#1386]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by teslur** [comment]
以下のドキュメントにしたがってインストールを行う。
https://github.com/red-data-tools/charty

**Comment by teslur** [comment]
MIT License

**Comment by teslur** [comment]
以下のドキュメントのUsageの通りコードを書いて試してみる。
https://github.com/red-data-tools/charty

**Comment by teslur** [comment]
使い方の想定が正しくなさそう。
（よく考えたら当たり前だけど）自分が作るプロダクトのGemfileが先に必要で、その中に `gem 'charty'` の記述がある前提。
Gemfile作って試行する。

**Comment by teslur** [comment]
`require': cannot load such file -- charty (LoadError)`

**Comment by teslur** [comment]
自分の環境では以下のコマンドを実行すると `vender/bundle` 配下にchartyがインストールされた。
`$ bundle` 

以下のサンプルプログラムをrubyプログラムとして保存して実行するだけではインストールされたchartyが読み込めない。
```
require 'charty'
charty = Charty::Plotter.new(:pyplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("sample_images/bar_pyplot.png")
```

**Comment by teslur** [comment]
サンプルプログラムの最初に以下の行を追加。
`require 'bundler/setup'`

chartyは読み込めたようだけど、以下のエラーが発生。
`require: cannot load such file -- numo/narray (LoadError)`

**Comment by teslur** [comment]
charty gem のgemspecには以下の記述がある。
```
  spec.add_dependency "red-colors"
  spec.add_dependency "red-palette", ">= 0.2.0"
  spec.add_development_dependency "bundler", ">= 1.16"
  spec.add_development_dependency "rake"
  spec.add_development_dependency "test-unit"
  spec.add_development_dependency "numo-narray"
  spec.add_development_dependency "nmatrix"
  spec.add_development_dependency "red-datasets", ">= 0.0.9"
  spec.add_development_dependency "daru"
  spec.add_development_dependency "activerecord"
  spec.add_development_dependency "sqlite3"
  spec.add_development_dependency "matplotlib"
```

見つからないライブラリは `spec.add_development_dependency` で書かれているようで、実際のGemfile.lockは以下の通り。
```
GEM
  remote: https://rubygems.org/
  specs:
    charty (0.2.1)
      red-colors
    red-colors (0.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  charty

BUNDLED WITH
   1.17.2
```

なので、サンプルプログラムは `spec.add_development_dependency` のライブラリが必要だけど、今の自分の環境にはインストールできていない？

**Comment by teslur** [comment]
memo:ロードパスに関してはガイドを書いて欲しい、というPRを出してもいいかも。

**Comment by teslur** [comment]
明示的にGemfileに記載したらやや進んだ。
```
gem 'numo-narray'
gem 'matplotlib'
```

明示的にライブラリを書かないと使えないっぽい。
どんな時にどのライブラリが必要なのか分からない。

**Comment by teslur** [comment]
`find_libpython: PyCall::PythonNotFound (PyCall::PythonNotFound)`

**Comment by teslur** [comment]
この辺が参考になりそう？
https://qiita.com/chamao/items/cd62715c6be2fad2f8e7

**Comment by teslur** [comment]
インストール手順ではシステムにインストールしたPythonを期待していたが、手元の環境で参照していたのはpyenvで作られた環境だった。
PATHからpyenvを消すことでエラー解消。

**Comment by teslur** [comment]
以下のコマンドがpyenvで実行されていたため。
`$ pip3 install matplotlib`

システムのpythonにはインストールされていなかったので、改めて実行したらインストールできて動いた。

**Comment by teslur** [comment]
以下のサンプルプログラムを実行したら空白のウィンドウが開いた。
```
❯ cat sample_1.rb
require 'bundler/setup'
require 'charty'
charty = Charty::Plotter.new(:pyplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("sample_images/bar_pyplot.png")

❯ ruby sample_1.rb
```

<img width="752" alt="スクリーンショット 2020-01-25 14 06 14" src="https://user-images.githubusercontent.com/7583139/73116573-de389980-3f7b-11ea-97c3-cb27b5a311bb.png">

**Comment by teslur** [comment]
画像ファイルは生成されていて `sample_images/bar_pyplot.png` に保存されていた。
![bar_pyplot](https://user-images.githubusercontent.com/7583139/73116584-0fb16500-3f7c-11ea-83f3-2ed109856d4c.png)

**Comment by teslur** [comment]
気になったこと：
- サンプルコードの期待結果が分からない
  - 空白のウィンドウが開くことが期待結果ならば、そのことを説明して欲しい
  - 空白のウィンドウが開くことが期待結果でないならば、説明通りの構築では期待通り動かない。

**Comment by teslur** [comment]
気になったこと２：
- chartyをロードしたいだけなのにnumo/narrayがロードされてrequireでエラーになる。
  `require: cannot load such file -- numo/narray (LoadError)`
  - gemの依存関係解消が適切ではないのでは？
  - すでにissueが上がっていた
    https://github.com/red-data-tools/charty/issues/51

**Comment by teslur** [comment]
空白のウィンドウが立ち上がるのは個人の環境依存かを確認したい。
→クリーンなdocker環境を作って確認。

**Comment by teslur** [comment]
報告内容案（日本語）

README.mdにあるサンプルコードの期待する実行結果はどのようなものでしょうか？

私の環境だと以下のような挙動をしましたが、これは想定通りの挙動でしょうか？

環境：
```
❯ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

実行したスクリプトおよびGemfile：
```
❯ cat Gemfile
source "https://rubygems.org"

gem 'charty'
gem 'numo-narray'
gem 'matplotlib'

❯ cat sample_1.rb
require 'bundler/setup'
require 'charty'

charty = Charty::Plotter.new(:pyplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("sample_images/bar_pyplot.png")
```

実行結果：
- 画像のように空白のウィンドウが立ち上がりました
<img width="752" alt="スクリーンショット 2020-01-25 14 06 14" src="https://user-images.githubusercontent.com/7583139/73116993-aa14a700-3f82-11ea-89b2-9ebf2adabe71.png">

- `sample_images/bar_pyplot.png` に以下の画像が保存されました
![bar_pyplot](https://user-images.githubusercontent.com/7583139/73117003-c31d5800-3f82-11ea-86a6-78613dc7c5b7.png)

空白のウィンドウが立ちあがることは期待する結果でしょうか？

**Comment by teslur** [comment]
# Blank window has opened when execute sample code

When I execute sample code in Usage section in README.md, blank window has opened.
Is this expected behavior?

## Environment
```
$ uname -a
Darwin xxxxMacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

$ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

## Gemfile, Gemfile.lock and executed sample code
```
$ cat Gemfile
source "https://rubygems.org"

gem 'charty'
gem 'numo-narray'
gem 'matplotlib'

$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    charty (0.2.1)
      red-colors
    matplotlib (1.1.0)
      pycall (>= 1.0.0)
    numo-narray (0.9.1.6)
    pycall (1.3.0)
    red-colors (0.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  charty
  matplotlib
  numo-narray

BUNDLED WITH
   1.17.2

$ cat sample_1.rb
require 'bundler/setup'
require 'charty'

charty = Charty::Plotter.new(:pyplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("sample_images/bar_pyplot.png")
```

## Result
- Blank window has opened.
<img width="752" alt="スクリーンショット 2020-01-25 14 06 14" src="https://user-images.githubusercontent.com/7583139/73116993-aa14a700-3f82-11ea-89b2-9ebf2adabe71.png">

- Following image has been saved as `sample_images/bar_pyplot.png`.
![bar_pyplot](https://user-images.githubusercontent.com/7583139/73117003-c31d5800-3f82-11ea-86a6-78613dc7c5b7.png)

Opening blank window is expected behavior?

**Comment by teslur** [comment]
# 報告案その２（日本語）
サンプルコードを実行するために、charty以外に以下のgemが必要だった。
```
gem 'numo-narray'
gem 'matplotlib'
```

numo-narrayは恐らく下記のissueで議論されている理由で必要になっていると思われる。
{{URL}}
matplotlibが必要であることは実行時に以下のエラーが発生したことで分かった。
```
vendor/bundle/gems/charty-0.2.1/lib/charty/backends/pyplot.rb:10:in `require': cannot load such file -- matplotlib/pyplot (LoadError)
```

chartyはグラフ描画ライブラリなので、描画用のgemであるmatplotlibはcartyの依存gemとして読み込んだ方が良いと思う。
依存gemではないという判断であれば、sampleを実行するために必要なgemをsample code周辺に提示してもらえないだろうか？

## 環境
```
$ uname -a
Darwin xxxxMacBook-Pro.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

$ ruby --version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

## 実行スクリプト
```
$ cat sample_1.rb
require 'bundler/setup'
require 'charty'

charty = Charty::Plotter.new(:pyplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("sample_images/bar_pyplot.png")
```

**Comment by atomiyama** [comment]
確かにサンプルコードで依存してるライブラリが明記されていないのはハードル上げているように感じたので良い提案だと思いました！！！英訳頑張ってください！！！
