### ISSUE TITLE
OSS Gate Workshop: tokyo: 2020-01-25: akihikoogata: Spring: Work log

### ISSUE THREAD

**Issue by akihikoogata** [oss-gate/workshop#1387]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by woodsand** [comment]
https://spring.io/guides/gs/spring-boot/

**Comment by akihikoogata** [comment]
公式ドキュメントをみてSpringフレームワークをWindowsに導入します。
- 公式ドキュメント
https://spring.io/guides/gs/spring-boot/
- 環境
Windows10
java version 1.8.0_211
Apache Maven 3.6.1
IntelliJ IDEA

**Comment by akihikoogata** [comment]
- Gitのクローン先フォルダ作成しコマンド実行
`git clone https://github.com/spring-guides/gs-spring-boot.git`

**Comment by akihikoogata** [comment]
How to complete this guideでgit clone後の
`cd into gs-spring-boot/initial`
が何をするべきなのかわからなかった。

**Comment by woodsand** [comment]
> How to complete this guideでgit clone後の
> `cd into gs-spring-boot/initial`
> が何をするべきなのかわからなかった。

「`cd into gs-spring-boot/initial`がわかりにくい」とissueを立てても良いかもしれないです！

**Comment by akihikoogata** [comment]
`To start from scratch, move on to Starting with Spring Initializr.`
で、jarか、warかどちらを選択するべきなのか記載がなく分かり難かった

**Comment by akihikoogata** [comment]
https://spring.io/guides/gs/spring-boot/#scratch
でArtifactがデフォルトで「demo」となっていたのでそのままDLしてしまったが
その下の説明で「spring-boot」と入力する旨が記載されていたため、
誤ってdemoで一度プロジェクト作成してしまい、やり直した。

**Comment by akihikoogata** [comment]
https://spring.io/guides/gs/spring-boot/#scratch
- Create a Simple Web Application
自分でclassを作成するという記載がないため、すでにクラスが存在するものかと勘違いしてしまった。

**Comment by akihikoogata** [comment]
- Run the Application
`mvnw spring-boot:run‘を実行した。
下記エラーがでた。
`[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[3,55] パッケージorg.springframework.web.bind.annotationは存在しません
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[4,55] パッケージorg.springframework.web.bind.annotationは存在しません
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[6,2] シンボルを見つけられません
  シンボル: クラス RestController
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[9,6] シンボルを見つけられません
  シンボル:   クラス RequestMapping
  場所: クラス com.example.springboot.HelloController
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.357 s
[INFO] Finished at: 2020-01-25T13:47:16+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project spring-boot: Compilation failure: Compilation failure:
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[3,55] パッケージorg.springframework.web.bind.annotationは存在しません
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[4,55] パッケージorg.springframework.web.bind.annotationは存在しません
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[6,2] シンボルを見つけられません
[ERROR]   シンボル: クラス RestController
[ERROR] /C:/Users/aogat/work/OssGate20200125/spring-boot/src/main/java/com/example/springboot/HelloController.java:[9,6] シンボルを見つけられません
[ERROR]   シンボル:   クラス RequestMapping
[ERROR]   場所: クラス com.example.springboot.HelloController
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by akihikoogata** [comment]
pom.xmlに下記を記述しbuildしたら動作した。Initialzrでwebの依存をチェックしDLするのを忘れていたのが原因。
```		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
```

**Comment by akihikoogata** [comment]
- Add Unit Tests
ドキュメント通りにpom.xmlに下記依存関係追加でサンプルテストコードが問題なく動作した。
```<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
	<exclusions>
		<exclusion>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
		</exclusion>
	</exclusions>
</dependency>```

**Comment by akihikoogata** [comment]
- Add Production-grade Services
pom.xmlに依存関係追加し、アクチュエーターが公式ドキュメント通り動作することを確認

**Comment by t-msn** [comment]
お疲れ様でした。お話しましたが次はまずcontribution.mdなどを見て、issueの立て方等を確認すると良いと思います
