### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2020-01-25: tas0131: Redmine: Work log

### ISSUE THREAD

**Issue by tas0131** [oss-gate/workshop#1388]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tas0131** [comment]
公式サイト
https://www.redmine.org/

**Comment by tas0131** [comment]
ライセンス
GNU General Public License v2 (GPL)

**Comment by tas0131** [comment]
User's Guide - Installation Guide を参照して、Windows環境にインストールします。
https://www.redmine.org/projects/redmine/wiki/RedmineInstall

**Comment by tas0131** [comment]
インストール済みの Ruby on Rails のバージョン6
Redmineサポートのバージョンは5.2
サポートバージョンをインストールします

**Comment by tas0131** [comment]
Ruby on rails 5.2.4.1 をインストール済み

**Comment by tas0131** [comment]
PostgreSQL のサポートバージョンは 9.2
インストールします。

**Comment by tas0131** [comment]
PostgreSQL 9.2インストール完了

**Comment by tas0131** [comment]
Resmine用DB作成

**Comment by tas0131** [comment]
Step 1 - Redmine application
Step 2 - Create an empty database and accompanying user
完了

**Comment by tas0131** [comment]
Step 3 - Database connection configuration を行います

**Comment by tas0131** [comment]
Step 3 - Database connection configuration　完了

**Comment by tas0131** [comment]
Step 4 - Dependencies installation
gem install bundler
bundle install --without development test

bundle install --without development test rmagick

**Comment by tas0131** [comment]
Database adapters 実施しない

**Comment by tas0131** [comment]
Additional dependencies (Gemfile.local) 実施しない

**Comment by tas0131** [comment]
Step 5 - Session store secret generation
bundle exec rake generate_secret_token　
完了

**Comment by tas0131** [comment]
Step 6 - Database schema objects creation
set RAILS_ENV=production
bundle exec rake db:migrate

DB接続失敗。状況確認中

**Comment by tas0131** [comment]
C:\DEV\OSSGate\redmine-4.1.0>bundle exec rake db:migrate
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/pg-1.1.4-x64-mingw32/lib/pg.rb:56:in `initialize'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/pg-1.1.4-x64-mingw32/lib/pg.rb:56:in `new'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/pg-1.1.4-x64-mingw32/lib/pg.rb:56:in `connect'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:90:in `connection'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
C:/DEV/OSSGate/redmine-4.1.0/path/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by tas0131** [comment]
Step 6 - Database schema objects creation
set RAILS_ENV=production
bundle exec rake db:migrate

完了

PostgreSQL 入れなおしました。

**Comment by tas0131** [comment]
Step 7 - Database default data set
完了

**Comment by tas0131** [comment]
Step 8 - File system permissions　
実施しない

**Comment by tas0131** [comment]
Step 9 - Test the installation
完了

**Comment by tas0131** [comment]
Step 10 - Logging into the application
完了

**Comment by atomiyama** [comment]
redmineの公式を日本語化しちゃいましょう
