### ISSUE TITLE
LAPRASさんのインタビューで各地域・企業の紹介をする

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#1398]
https://hackmd.io/a2Vk3USKR5-sgk78h_oBdw でOSS Gateコミュニティの紹介は書いてみたのですが、OSS Gateで活動している各地域・企業について、色々な人の視点で情報があつまるともっと良いと思っています！
全部インタビュアーさんにお伝えできるか分からないですが、

1. どの地域・企業か
2. OSS Gateの活動を始めたきっかけ
3. 現在の活動状況

の構成で、このissueのコメントに書いていただきたいです！3/19(木)がインタビューの日なのでその前日までに書いていただけると嬉しいです！

**Comment by Nyoho** [comment]
- どの地域・企業か
  - 広島
- OSS Gateの活動を始めたきっかけ
  - 広島のメンバの一人がこの活動を知って高まり、広島でもやりたいと思っていたが忙しくて2年ぐらい経っていたところ @Nyoho がジャンピングキャッチして2019年に初開催した。
- 現在の活動状況
  - まだ2019年に初開催したのみ
  - これからも1年に1度ぐらいはできたらいいなあと思っている

**Comment by masayuki14** [comment]
1. どの地域・企業か
    - 京都
1. OSS Gateの活動を始めたきっかけ
    - 大阪の立ち上げ([2017/02](https://oss-gate.doorkeeper.jp/events/56141))で参加したときに、京都でもやりたいと思ったのがきっかけ。
    - [KansaiRubyKaigi2017](https://rubykansai.github.io/kansai2017/)での縁や後押しを受け、京都での場所の確保ができたので初開催ができた。
    - 始めは大阪メンバーと一緒に活動していたが、京都でも場所などの開拓ができたので京都だけでできるようになった。
1. 現在の活動状況
    - 2017年に[初開催](https://oss-gate.doorkeeper.jp/events/62572)し、その後は年に1回のペースで毎年行っている。
    - 短期間の活発な活動も良いが、小さくても長く活動出来るような方針でやっている。

**Comment by ogom** [comment]
1. どの地域・企業か
    - 大阪
1. OSS Gateの活動を始めたきっかけ
    - 東京や札幌の他にOSS Gateを開催している地域を増やしたいと主催者からのお誘いで開始
1. 現在の活動状況
    - ワークショップを年に１、２度のペースで開催

**Comment by knokmki612** [comment]
インタビュー終わりました！自分としてはある程度各地域を紹介できたと思います、ご協力ありがとうございました！
