### ISSUE TITLE
オンライン開催の方法検討及び実験開催

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1399]
Gitterに書き出したオンライン開催のアイデアのメモです。
うまく話がまとまれば、（サポーターのみでの）実験開催もできればと考えています。

6月のイベントも中止がアナウンスされ始めており、今後は当分オフライン開催が不可能と考えられるため、代替としてオンライン開催を軌道に乗せることが望ましいと考えています。

## 開催内容

- [イベントページ](https://oss-gate.doorkeeper.jp/events/TODO)
- 会場: 
- 時間: YYYY-MM-DDT10:30/17:00
- 会場係: @
- 進行役: @
- このイベントに関する窓口: @

## 会場設備確認

参考：[ワークショップ会場の提供](https://oss-gate.github.io/sponsors/wanted.html#workshop-space)

- [ ] 10人以上座れる机と椅子（参加人数が20人を超えることはほとんどありません）
- [ ] プロジェクタと投影できるところ (スクリーンじゃなくとも見えればOKです！)
- [ ] WiFi
- [ ] 電源タップ (参加人数の半分以上の口があるとうれしいです)
- [ ] 夜間、土日祝日の入場方法について（必要な場合のみ）
- [ ] プロジェクタの入出力端子 (HDMIなど)

## やること

- [ ] Doorkeeperのイベントページ作成（開催の1ヶ月前までにやる）
- [ ] 窓口決定（開催の1ヶ月前までにやる）
- [ ] 会場決定（開催の1ヶ月前までにやる）
- [ ] 進行役決定（開催の1ヶ月前までにやる）
- [ ] サポーター募集のメッセージ作成（開催の2週間前までにやる）
- [ ] [ビギナーの繰り上がり](https://oss-gate.github.io/workshop/beginner-preferential-treatment.html)処理（開催の1週間前にやる）
- [ ] 会場案内のメッセージ作成（開催の3日前までにやる）
- [ ] `tutorial/retrospectives/prepare.rb` を実行してアンケートのテンプレートを追加する（ #1337 ）（開催当日までにやる・要コミット権）

**Comment by piroor** [comment]
## 最小構成の基本

オフライン開催時に複数テーブルに分かれて進行するケースでの、1つのテーブルを1つの会議通話に見立てる。

* サポーター1名とビギナー2～3名で会議通話を開く。
* ビギナーからの相談、サポーターからの情報提示の際は、画面共有を使う。
  * このとき他の参加者は、どういう相談が行われているかを見て学ぶ。
* 進行役ができる程度に自信があるサポーターであれば、この形態で最小のワークショップは開催できそう？

## 複数サポーターで行う場合

* 進行役が全体向けにアナウンスするときは、単一の画面を全員で視聴するタイプの画面共有（会議通話でなくてよい）に皆で入ってもらう。
* 通常時は上記の最小構成の会議通話が複数存在している状態とする。
* あるサポーター（A）が他のサポーター（B）にヘルプを求めたら、BはBが元々いた会議通話を抜けるか、別ウィンドウを開いて、そちらでAがいる会議通話にjoinする。
  * 話題に興味があるビギナーや他のサポーターがもしいれば、その人もjoinして構わない。
* この形態であれば、進行役未経験で他のサポーターやサポートメンターの補助が欲しいかも、という感じの不安があるサポーターでも参加できるのではないか？

**Comment by piroor** [comment]
ビデオ会議通話システムの例・候補

* Zoom 最近話題のようだが、色々問題が指摘されている。
* [Jitsi](https://meet.jit.si/) https://jp.techcrunch.com/2020/04/01/2020-03-31-zoom-at-your-own-risk/ でもZoomの代替として言及されているオープンな実装。クリアコードで4人までの利用実績あり。

**Comment by piroor** [comment]
ビデオ会議では若干のタイムラグがあり、誰かが話している間は他の人は黙る必要があるので、オフラインに比べて時間がかかる恐れがある。
会話に要する時間をより長く見積もった方がよいのではないか。

**Comment by kou** [comment]
オフラインと同じようなストーリーを前提としない方がいいんじゃないかと思います。
オンラインならではの特性を活かす感じのストーリーを考えられた方がいいんじゃないかな。

**Comment by piroor** [comment]
進行役の画面を皆に見てもらう場面では、ビデオ会議通話は無駄が多いように見える。
[インフラ勉強会の登壇案内](https://wp.infra-workshop.tech/how-to-hold-a-session/)では、[CrankWheel](https://chrome.google.com/webstore/detail/crankwheel-screen-sharing/dooinopjfnhlmmdkdepajfipfhlcmjgp)というGoogle Chrome用拡張機能（と連携したサービス）を使う方法が案内されている。

* 試してみたところ、WSLのRabbitの画面も共有できた。
* 閲覧者側は、提示されたURLを開くだけで閲覧できる。（ブラウザを問わない）
* 音声配信機能は無い模様。インフラ勉強会ではDiscordの音声を並行して聞く形で運用している。

**Comment by piroor** [comment]
@kou そうですね、オフラインの通りに実行することを目的とするのは本末転倒だとは思っています。
現状では考える手がかりがまだ何もない状態だったため、とりあえずオフラインのワークショップを参考に、可能性を模索している状態です。

**Comment by piroor** [comment]
* オフラインの物をそのままオンラインに持ってくる事

は目的ではないですが、

* OSS Gateワークショップに参加したからこそ勇気を出してフィードバックできた、と思ってもらえたポイント

は持ち込みたいと思っています。

* 他の人（ビギナー）もいた
* サポーターに画面を見せながら相談できた
* 他のサポーターにも違った角度から別のアドバイスをもらえた

あたりはアンケートで好評だったように記憶しているので、それをどうやれば持ち込めるだろうか？という事を考えていました。

**Comment by knokmki612** [comment]
私がオフラインのワークショップにかなり近い形から発想していった場合、
進行役兼サポーター1人とビギナー3人での開催は、ワークショップで何度か実績があったと記憶していますので、4人単位で完結したオンラインワークショップはイメージしやすいなと思いました。

話がずれまして、自分がビギナーさんのPCの画面が見る前にどんな行動をしていて、どんなことを気にしているのか考えてみました

| 行動 | キャッチアップしたいこと |
| :-- | :-- |
| 作業メモを巡回する | 作業メモからは今何を考えているのか、<br>何をしているのか分からないとき |
| 会場を巡回する | 手が止まっているとき<br>何をしようか迷っていそうなとき |

それで、

- 「作業メモを巡回する」はオンラインワークショップでもそのままできそう、かつサポートに有効そう
- 「会場を巡回する」はビギナーさんの表情、視線、手の動きなど、非言語コミュニケーション的な要素があり、画面共有、音声、動画で同等のキャッチアップができるかは未知数

かなと思いました。作業中の様子について、

1. 基本全員音声のみ
2. サポーターは作業メモを巡回
3. 気になったビギナーがいたら声をかけて画面共有してもらう
4. 他のサポーターも画面共有の様子を見て気になったらアドバイスする

という流れをイメージしてみました。

**Comment by piroor** [comment]
https://www.businessinsider.jp/post-210635
Zoomの説明に "ホストは参加メンバーを、｢ブレイクアウトルーム｣と呼ばれる少人数グループに分けられる" とあって、ああ、欲しかったのはこれか……ってなってる

**Comment by tomiik** [comment]
piroorさんからお返事を頂いたので、未参加者ですがコメントさせていただきます。
小グループに分かれる際に

- Video + Voice & Screenな部屋
- Voice & Screen onlyな部屋

で分かれているとお互いに安心して参加できるのかなと思いました。

Video&Voiceが混ざっていると、顔を写している人が一方的に見られている感じがして少し不快な感じがあるかもしれません。
個人的には顔をお互いに出した方が親交も深まるので良いと思うのですが、初対面の人とビデオチャットするのに抵抗がある人は結構いるのかなと思います。

**Comment by piroor** [comment]
https://twitter.com/ikedaosamu/status/1252187063308267523

zoomを使っての授業で

1. 課題を解くときは、ビデオをオフにしてください。
2. 課題が終わった人は、ビデオをオンにしてください。

というルールにすることで、全体の進捗状況を容易に把握できる、という事例が紹介されていました。
OSS Gateワークショップでは全体の進捗状況を把握する必要性はあまりないので、そのまま反映するのは意味が無さそうですが、映像のON/OFF自体が何らかのステータス表示となる、という運用は何かに使えるかもしれません。

----

@tomiik コメントありがとうございます！
オフラインでのワークショップでは、テーブル分けは来場された方がたまたま着席したテーブルをそのまま使う感じ（言語やプロダクトで分けるという事は特にしていない）ですが、リモートだと映像の有る無しでグループを分ける需要もあるのですね。そこは想像が及んでいませんでした。

**Comment by makicamel** [comment]
同じく @piroor さんからご連絡を頂きましてコメントします(超遅レスですみません)

オンラインのイベントを行う時、コミュニケーションが難しいなというのが課題感としてあります。
具体的には下記の 2 点です。
- 1 対多で進行役の方がお話されている時は、ビギナーの方のリアクションがわからない
- ビギナー同士のコミュニケーション、空気感(「他の人(ビギナー)もいた」の部分)といったものが得難い

前者はチャットアプリの :+1: とかの機能でリアクションしたり、ボディランゲージ(ビデオオンの前提)や拍手(音)でリアクションしたりを積極的にお願いすることで緩和されそうで、
後者は参加者同士で話せる休憩時間を取ることで緩和されそうに思います(物理の時と同様)。

---

また、画面共有は必須そうな気がするのですが、
普段していない人だと手間取る(特にビギナーの方)と思うので、参加要項に設定手順の記載があると優しそうです。
(許可していないとチャットアプリを再起動する必要があったりする)

---

@piroor さんがおっしゃっているように小グループにわけられる環境は大事そうな気がします。
(同時に喋れないので、できればサポーターとビギナーの小部屋にわけたい)

- Discord
アップデートでビデオチャットもできるようになったそうです。会社で使っている人も一定数みるようになった気がします。
https://twitter.com/tsubotax/status/1252965505117220866?s=20

- Remo
同様のようですが、 14 日間のトライアルはあるものの、基本的には有料プランになるので課金ユーザーがいる必要がありそうです。
[【オンライン飲み会にいいかも？】ZoomとRemoの違いと使い分けをまとめてみた｜コスギ＠コスギス｜note](https://note.com/mekemoke/n/n3aca17bc170b)

- Google Hangout
ある会社で 4〜50 人の会議をやった時に使用したけど、特に問題なかったという話を聞いたことがあります。
(グループ分けに関しては調べていないです、すみません)

--- 

また、 OSS Gate 初めて参加させて頂く時はものすごくハードルが高かったのですが、
オンラインイベントだと慣れない人だと余計に心理ハードルがあがるので、
『初心者でも大丈夫』ということの打ち出し、具体的なツールや参加手順、グループ分けの方法などを明確に打ち出すことでイベントのイメージがつかめ、参加までのハードルが下がりそうに思います。

**Comment by satoryu** [comment]
最近、アジャイル界隈でDiscordとMural（もしくはMiro）を使ってOST（オープンスペーステクノロジー: その場で集まった人たちが各々に出してテーマ別に分かれてディスカッションするワーク）をやっています。参加してみて、色々ワークができそうかな、と思いました。
Discordは、Slackみたいにテキストチャネルと音声とビデオ通話ができるボイスチャネルがあり、無料でも複数チャネルを作成できます。OSTの場合、各テーマごとにテキストチャネルとボイスチャネルのセットを作り、基本は音声でディスカッションしつつ、テキストでやった方がいい情報の交換はテキストで行い、画面共有が必要になればボイスチャネルで行うようにしています。

OSS Gate ワークショップでやるときはこんな感じかな、という叩き台を作ってみました。

## チャネル設計

- ホール（テキスト）
  - 全体進行のためのチャネル。GitterのURLを全体に通知など。
- ホール（ボイス）
  - メイン進行のためのボイスチャネル。アイスブレイクの自己紹介やワークショップの説明をここで画面共有で行う。
- ペア1〜N（テキスト）
  - サポーター、ビギナーのペアで利用するテキストチャット。テキストで伝えた方が早いものなどをここで共有。
- ペア1〜N（ボイス）
  - サポーター、ビギナーのペアで利用するボイスチャット。
  - ビギナーが画面共有し、サポーターはそれを観ながら音声でサポート。

## シナリオ

内容 |  やること
-- | --
チャネルの作成 | 進行役、サポーターで、参加するビギナーの人数に合わせてペアチャネル（テキスト、ボイス）を作成。
アイスブレイク | 進行役がホール（テキスト）で全体メンション（@everyone）し、ホール（ボイス）に入るように促す。自己紹介を実施。ここで参加者にマイクを使うことに慣れてもらう。
OSS開発手順を説明 | 進行役がホール（ボイス）で説明。進行役がビギナーにペアチャネルを割り当て、ビギナーは割り当てられたペア（ボイス）に入る。サポーターは好きなペア（ボイス）に入る。
対象OSSを動かす | ビギナーは画面共有を開始し、作業を開始する。
ミニふりかえり | ホール（ボイス）で進行役が全体メンションでミニふりかえりの開始を促す。ビギナーはその時点で参加しているチャネルから動かない。サポーターは隣のペア（ボイス）に移り、ふりかえりを行う。
休憩 | 進行役がホール（テキスト）で全体メンションし、休憩開始と終了時刻を案内。ホール（ボイス）で雑談することも伝える。
プロジェクトにフィードバックする | 各ビギナー、サポーターはペア（ボイス）に戻り、ワークを行う。
ふりかえり | ミニふりかえりと同様
まとめ| 進行役がホール（テキスト）へ招集し、まとめを行う。
アンケート記入 | ホール（テキスト）で進行役がアンケートのためにリポジトリをcloneするところから画面共有で説明。ビギナー、サポーターはそれを観ながらアンケートを記入する。記入方法がわからない人が出た場合、その人の画面共有に切り替えて、進行役がサポートする。
ワークショップのふりかえり | 進行役がホール（ボイス）で画面共有し、アンケート集計を写し、全体の振り返りを行う。

全体を集めたい時とペアに分かれるときの案内に注意が必要そう。

**Comment by knokmki612** [comment]
@piroor さんとDiscordをさわりながら、ワークショップのオンライン開催について検討しました

## 分かったこと

- ボイスチャンネルは移動すると居たボイスチャンネルからは退席になる
- テキストチャンネルの通知はDiscordアプリを開いている間、書き込んだチャンネルに関係なく通知が飛ぶ
- Discordのアプリ版でないと画面共有の配信と閲覧ができないので、全員アプリ版をインストールする必要がある
- 画面共有は配信を閲覧するボタンを押して初めて動画が視聴できる (押すまで静止画のまま)
- Discordのアプリ版はmacOSにもWindowsにもLinux系ディストリにもあるので、アプリのインストールを要求するのは問題ない？
- アプリのUIはどの環境でも同じなはずなので、Discordの操作のフォローが必要な場合に自分が画面共有してフォローができそう
- ボイスの自動ミュートが優秀

## 決めたこと

- 今回の[ワークショップ](https://github.com/oss-gate/workshop/issues/1353)の参加人数は7人なので、作業中は全員同じ島のモブプログラミング形式でやってみる
    - 全員同じ島で作業するのか厳しい人数なのか検証して、次回以降の参加人数で島をいくつに分けるかの基準の参考にする
- 作業中に並行してサポートを始める場合は、ボイスチャンネルを新しく作って分かれる
- ワークショップの開催日ごとに日付のテキストチャンネルを作る
    - OSS Gateの活動を振り返るときにイベントごとの記録がみやすいほうが良いため
- アイスブレイクは全員が声をかけやすくするために参加者全員でおこなうのは必須だが、ふりかえりについてはデモ以外は島を分けないと時間がかかりすぎるので分ける
- ビデオは原則使用しないが、進行役など適宜使用する

**Comment by knokmki612** [comment]
フェーズごとに適切な人数の仮説

1. アイスブレイク: 参加者全員
2. 進行役が説明する: 参加者全員
3. 作業: サポーター・ビギナーで10人
4. ふりかえり: サポーター・ビギナーで4～6人

**Comment by satoryu** [comment]
モブプロでやるとなると、

1. ドライバーの交代のタイミング
2. 作業の共有方法

を決めておくといいのかと思います。1はその場で決めてもよさそうですが、2は参加者の準備も必要になると思うので事前に決めておいた方が良さそう。2は、参加者のうちの誰かのPCとGitHubアカウントを使うことになるのかな、と想像してます。

**Comment by knokmki612** [comment]
@satoryu 申し訳ないです、モブプログラミングという言葉を使ったのは完全に語弊があったかと思います。

ビギナーはあくまで自分の選んだOSSに対してそれぞれ作業しまして、
サポーターがサポートするときはビギナーに画面共有してもらって、同じボイスチャンネルに居る参加者全員がみられる状態で作業してもらうというのが意図していた状態となります。

**Comment by knokmki612** [comment]
Discordで継続開催がまわりはじめています。
方法としては確立して、改善していく段階に入っているのでcloseします！
