### ISSUE TITLE
OSS Gate Workshop: online: 2020-06-13: sasshi-i: Rainbow CSV: Work log

### ISSUE THREAD

**Issue by sasshi-i** [oss-gate/workshop#1402]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
よろしくおねがいします！

**Comment by sasshi-i** [comment]
Rainbow CSVをググたらgithubのページを発見。
https://github.com/yzhang-gh/vscode-rainbow-csv

**Comment by sasshi-i** [comment]
Licenseを見たらMITライセンスだったので、OSSである
https://github.com/yzhang-gh/vscode-rainbow-csv/blob/master/LICENSE

**Comment by sasshi-i** [comment]
Githubのページを確認したが、特にインストール方法は記載されていなかった。
https://github.com/yzhang-gh/vscode-rainbow-csv

**Comment by sasshi-i** [comment]
そのため、VS codeのExtensionの画面からインストールを行った。
(添付画像はインストール後の画面)
<img width="1759" alt="スクリーンショット 2020-06-13 13 54 02" src="https://user-images.githubusercontent.com/28973144/84560283-64b01500-ad7d-11ea-88cd-68336d7c1356.png">

**Comment by sasshi-i** [comment]
先ほど貼り付けたGithubのページはforkしたリポジトルであった。
frok元のリポジトリはこちら。
https://github.com/mechatroner/vscode_rainbow_csv

**Comment by sasshi-i** [comment]
Usageに従い下記を実施
https://github.com/mechatroner/vscode_rainbow_csv#usage

1. VS codeを起動
2. 拡張子なしでファイル作成
3.下記をファイルに記載
```
test1;test2;test3
aaa;vvv;ccc 

```
4.VS codeの右下のLangage modeをCSV(semicolon)に変更

色が変わって表示されることを確認

<img width="397" alt="スクリーンショット 2020-06-13 14 08 19" src="https://user-images.githubusercontent.com/28973144/84560463-5ebb3380-ad7f-11ea-9898-d1b2c95280ec.png">

**Comment by sasshi-i** [comment]
パイプでも同様の手順で色がつくことを確認

<img width="339" alt="スクリーンショット 2020-06-13 14 10 00" src="https://user-images.githubusercontent.com/28973144/84560480-9b872a80-ad7f-11ea-877e-dcf2675ac427.png">

**Comment by sasshi-i** [comment]
下記の手順で色を変えてみた。
`Another way to do this: select one separator character with mouse cursor -> right click -> "Set as Rainbow separator"`

・拡張子なしでファイルを作成し、カンマ区切りのファイルを作成する。
・カンマを選んで右クリック
・Set as Rainbow Separatorを選択

色が変わることを確認
<img width="339" alt="スクリーンショット 2020-06-13 14 10 00" src="https://user-images.githubusercontent.com/28973144/84560572-56172d00-ad80-11ea-85ba-b648fbdb4d1f.png">

**Comment by sasshi-i** [comment]
.csvの拡張子をつければ自動で判定して色をつけてくれる
<img width="464" alt="スクリーンショット 2020-06-13 14 20 01" src="https://user-images.githubusercontent.com/28973144/84560675-2583c300-ad81-11ea-8559-51e23b7926e3.png">

**Comment by sasshi-i** [comment]
.tsvの場合はタブ区切りしても自動で色がついてくれない
<img width="1792" alt="スクリーンショット 2020-06-13 14 23 05" src="https://user-images.githubusercontent.com/28973144/84560709-71cf0300-ad81-11ea-888d-c64bcc81ea6a.png">

**Comment by sasshi-i** [comment]
インデントの設定を変えたら.tsvでも色がついた。
VS code の設定でIndent Using Tabsにしたら問題なく色がついた。
普段 Indent Using spaceで使っていたため

<img width="1792" alt="スクリーンショット 2020-06-13 14 27 39" src="https://user-images.githubusercontent.com/28973144/84560798-1b15f900-ad82-11ea-9dae-3214ccc0208b.png">

<img width="1792" alt="スクリーンショット 2020-06-13 14 28 43" src="https://user-images.githubusercontent.com/28973144/84560811-4698e380-ad82-11ea-8f60-efd66e31a08b.png">

**Comment by sasshi-i** [comment]
https://github.com/mechatroner/vscode_rainbow_csv#content-based-separator-autodetection

auto detectionが効かない。
やり方間違ってる。。？一応、planin text なんだが。

<img width="1792" alt="スクリーンショット 2020-06-13 14 38 28" src="https://user-images.githubusercontent.com/28973144/84560959-9035fe00-ad83-11ea-9437-4cc6df2da415.png">

**Comment by sasshi-i** [comment]
rainbow csvの設定はどこでいじるんだ。

**Comment by sasshi-i** [comment]
settingについて書いてあった。
https://github.com/mechatroner/vscode_rainbow_csv#settings

**Comment by sasshi-i** [comment]
報告する内容：autodetectionが効かない

macOS Catalina(10.15.2), VS code version: 1.45.1を使用している。
Rainbow CSVをVS codeにインストールして特に設定は変更していない。

下記リンク先の記載によるとPlain Textの状態でカンマ区切りであれば、autodetectionされるとのことなので、autodetectionが効くか試してみた
https://github.com/mechatroner/vscode_rainbow_csv#content-based-separator-autodetection

下記のファイルを作成してautodetectionが効くことを期待していたが、効かなかった
ファイル名：autodetection(拡張子なし)
VS codeのLangage mode: Plain Text
```
test,test2,test3
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
```

**Comment by sasshi-i** [comment]
# 再現手順
* 下記の環境でVS codeを起動
macOS Catalina(10.15.2)
VS code version: 1.45.1
Rainbow CSV version: 1.7.0

* VS codeでNew fileをクリック
* 拡張子のないファイルを作成
* VS codeの右下のLangage ModeがPlain Textであることを確認
* 下記のデータをファイルに記載し、cmd + sで保存
```
test,test2,test3
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
```

# 期待される結果
autodetectionが効き、カンマ区切りのデータが色分けされる

# 実際に得られた結果
カンマ区切りのデータが色分けされなかった

**Comment by sasshi-i** [comment]
Title: Autodetection doesn't work on comma separated file in Plain text language mode

# Reproduction procedure
* Turn on VS code following environment
macOS Catalina: 10.15.2
VS code version: 1.45.1
Rainbow CSV version: 1.7.0

* Click New file on VS Code to create new file
* Created file with no extension
* Confirmed Language mode is Plain text in VS code
* Put following data into file which created before(no extension file)
```
test,test2,test3
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
```

# Expected Outcome
Data is colored due to autodetection

# Actual Outcome
Data is not colored

# About rainbow_csv.autodetect_separators setting
According to the attached image. Rainbow CSV setting has not changed since I installed Rainbow CSV
<img width="1219" alt="スクリーンショット 2020-06-13 15 59 06" src="https://user-images.githubusercontent.com/28973144/84562744-d4c89600-ad91-11ea-85a2-9cf1bb37712e.png">

**Comment by piroor** [comment]
報告おつかれさまです！
https://github.com/mechatroner/vscode_rainbow_csv/issues/61

**Comment by sasshi-i** [comment]
下記のメソッドからケースが落ちているような気がする。
```
function autoenable_rainbow_csv(active_doc) {
    if (!active_doc)
        return;
    const config = vscode.workspace.getConfiguration('rainbow_csv');
    if (!config || !config.get('enable_separator_autodetection'))
        return;
    let candidate_separators = config.get('autodetect_separators');
    var original_language_id = active_doc.languageId;
    var file_path = active_doc.fileName;
    if (!file_path || autodetection_stoplist.has(file_path)) {
        return;
    }
    let is_default_csv = file_path.endsWith('.csv') && original_language_id == 'csv';
    if (original_language_id != 'plaintext' && !is_default_csv)
        return;
    let rainbow_csv_language_id = autodetect_dialect(active_doc, candidate_separators);
    if (!rainbow_csv_language_id && is_default_csv) {
        // Smart autodetection method has failed, but we need to choose a separator because this is a csv file. Let's just find the most popular one.
        rainbow_csv_language_id = autodetect_dialect_frequency_based(active_doc, candidate_separators);
    }
    if (!rainbow_csv_language_id || rainbow_csv_language_id == original_language_id)
        return;
    try_change_document_language(active_doc, rainbow_csv_language_id, false, (doc) => {
        original_language_ids.set(file_path, original_language_id);
        csv_lint(doc, false);
        refresh_status_bar_buttons(doc);
    });
}
```

**Comment by sasshi-i** [comment]
開発者から返信が来て、最初の編集時はautodetectionが効かないとのこと。
https://github.com/mechatroner/vscode_rainbow_csv/issues/61

ファイルをコピペして再作成するか、VS codeを再起動するとautodetectionが有効になるみたい。

なおせるようならPR出して直してあげたいところ。
