### ISSUE TITLE
OSS Gate Workshop: PyConJP 2020 Sprint: 2020-08-23: norihitoishida: Optuna: Work log

### ISSUE THREAD

**Issue by norihitoishida** [oss-gate/workshop#1408]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by norihitoishida** [comment]
- 開発にVSCode + Remote Containerを使うようにしました。
 - optuna開発で使われているエコシステムを勉強しました。
      - 開発用 Docker image
     - pytest
     - docstrings + Sphinx + readthedocs
 - PRを出しました。
      - 型ヒント, merge済 : https://github.com/optuna/optuna/pull/1699
      - docstring追記&修正, review待ち : https://github.com/optuna/optuna/pull/1726

**Comment by norihitoishida** [comment]
- PRを出しました。
     - docstringにEampleを追記 https://github.com/optuna/optuna/pull/1741
- branchの切り方を間違えて、前のPRに追加する形になってしまいました。
- `master`から切る、を徹底します…

**Comment by norihitoishida** [comment]
- PRを出しました。
      - docstringにEampleを追記 optuna/optuna#1742
      - ローカルで通るblack (Linter)がリモートで失敗するという現象があり、調査中です。

**Comment by norihitoishida** [comment]
- PRを出しました。
     - 型ヒント: https://github.com/optuna/optuna/pull/1743

**Comment by norihitoishida** [comment]
- PRを出しました。
     -  docstringにEampleを追記 : optuna/optuna#1744
     -  docstringにEampleを追記 : optuna/optuna#1745
- `.. testcode::`を使ってdoctest化するとよいというアドバイスを頂きました。
- 使用していない関数を定義してしまっていることを指摘して頂きました。
     - docstringはコメントアウト扱いとなり、blackやflake8等のlinterで使用の有無や変数未定義を自動で検出してくれないので、気をつけるようにしたいと思います。

**Comment by norihitoishida** [comment]
- PRを出しました。
     - docstringにEampleを追記 : optuna/optuna#1746

**Comment by norihitoishida** [comment]
- PRを出しました。
      - docstringにEampleを追記 : https://github.com/optuna/optuna/pull/1747, https://github.com/optuna/optuna/pull/1749, https://github.com/optuna/optuna/pull/1750

**Comment by norihitoishida** [comment]
Sprintが終了したためisuueを閉じます。
1週間本当にありがとうございました！

**Comment by kou** [comment]
たくさんpull requestをだしましたね！
これからもOptunaや他のOSSの開発に参加していってみてください！

今回の機会が有意義だったと思ったらまわりの人にこのOSS Gateという取り組みを紹介してください。
また、他の人たちにも同じような経験をして欲しいと思ったらOSS Gateワークショップのサポーターとして参加してみてください。次回以降のことなどは https://gitter.im/oss-gate/tokyo で相談しています。
私たちはOSSの開発に参加する人を増やし続けていきたいと思っています！
