### ISSUE TITLE
OSS Gate Workshop:PyConJp 2020 Sprint: 2020-8-23:masamori0083 : Django: Work log

### ISSUE THREAD

**Issue by masamori0083** [oss-gate/workshop#1409]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masamori0083** [comment]
Djangoの公式ガイドに沿ってインストールを試みる。
https://www.djangoproject.com/
のGet Started with Djangoのリンクから
https://www.djangoproject.com/start/
のページに移る。
まずはインストールから始めようと思い、このページの「DJANGO INSTALLATION GUIDE」のリンクから
https://docs.djangoproject.com/en/3.1/intro/install/
のページに移る。
このページ上から順に、Install Python, Set up a database, Install Django,のステップをたどる。
ターミナル（macOS10.15.6）でPythonのバージョン確認。
別個にDBを設定するつもりは無いので、Set up a databaseは飛ばす。
Install Django の項目で、以下３つのインストールの方法が記載されている。

Install an official release. This is the best approach for most users.

Install a version of Django provided by your operating system distribution.

Install the latest development version. This option is for enthusiasts who want the latest-and-greatest features and aren’t afraid of running brand new code. You might encounter new bugs in the development version, but reporting them helps the development of Django. Also, releases of third-party packages are less likely to be compatible with the development version than with the latest stable release.

今回は、一般的でかつ大多数なユーザーであるという想定のもとでインストールをしようと思ったので、official releaseの方法でインストールをする。
Install an official release. 
のリンクから
https://docs.djangoproject.com/en/3.1/topics/install/#installing-official-release
のページに移る。

1,This is the recommended way to install Django.

2,Install pip. The easiest is to use the standalone pip installer. If your distribution already has pip installed, you might need to update it if it’s outdated. If it’s outdated, you’ll know because installation won’t work.

3,Take a look at venv. This tool provides isolated Python environments, which are more practical than installing packages systemwide. It also allows installing packages without administrator privileges. The contributing tutorial walks through how to create a virtual environment.

After you’ve created and activated a virtual environment, enter the command:
$ python -m pip install Django

の通りに上から順に実行。

これでインストールは完了したはずなので、実際にDjangoを動かせるはず。
このページ最下部に「Models and databases >」と書いてあるため、これをクリック。個人的にはチュートリアル に進みたかったが、まだインストールの手順が残っているものだと思い素直に従うことにする。
https://docs.djangoproject.com/en/3.1/topics/db/
のページに移る。
すると、ここには「Models and databases」と書いてあり、database関連のドキュメント に飛んでしまう。さらに「Models>」のリンクがあるため、クリックすると
https://docs.djangoproject.com/en/3.1/topics/db/models/
のページに移ってしまい、これはチュートリアル では無いことが明らかになる。

そこで、
https://docs.djangoproject.com/en/3.1/intro/install/
まで手作業で戻り、このページの最下部に「Writing your first Django app, part 1 >」のリンクがあるため、これをクリック、
https://docs.djangoproject.com/en/3.1/intro/tutorial01/
のページに移る。URLにもtutorialと書いてあるので、このページがチュートリアル だとして作業を進める。

インストール完了までは割と親切に道筋が示されているが、インストールの後に素直にリンクを辿っていくと、いつまでもチュートリアル が始まらないことになってしまった。
https://docs.djangoproject.com/en/3.1/topics/install/#installing-official-release
の最下部に「Models and databases >」とリンクが貼ってあるが、これとは別にチュートリアル に進むようなリンクを貼ってくれると親切だと思う。

今のところ、
https://docs.djangoproject.com/en/3.1/topics/install/#installing-official-release
のページからチュートリアル に進むためには、一つ前のページ
https://docs.djangoproject.com/en/3.1/intro/install/
に自分で戻るか、あるいはチュートリアル の検索をかけるしかないので、全く初めてDjangoを使う人にはこの部分が少し不親切だと思った。

**Comment by knokmki612** [comment]
@masamori0083 
チュートリアルを忠実に読み進めていくうちに、チュートリアルの動線を見失う経緯がまとまっていて良いですね！
また、

- 現状だとどうやって解決できるのか
- どのように改善するといいか

といったことも書かれていますね！

今後のフィードバックするまでの手順としては、2\.と3\.を進めていくことになるかと思います！

1. 自分で読んでわかるように文章を整理する
    - これはできていそう :ok_hand:
2. 開発者が読んでわかるように文章を整理する
   - 後述
3. 適切な場所に報告する
    - どこに報告するのか
    - どうやって報告するのか(やり方が指定されているなら従う)
        - CONTRIBUTING.md のようなファイル
        - How to contribute のようなページ
    - 報告時のテンプレートがあるならどのようなテンプレートか

2\.をおこなう際の大事なポイントとして、

- 相手にわかるように書く
- 省略しない

がありますが、「省略しない」はできていそうですね！

「相手にわかるように書く」は、取り組む前に3.の「どこに報告するのか」「どうやって報告するのか」を先に調べておくと、相手に受け入れてもらいやすい書き方が分かることがあるので先に調べたほうがいいですね！

そのうえで、「相手にわかるように書く」ためにできることとしては、個人的には以下のものがあると思っています！

- アウトラインを整理する
    - 見出しをつける
        - 再現手順
        - 期待したこと
        - 実際に起こったこと
        - 改善方法
- 一文あたりの文字数を短くする
    - シンプルな文章構造にする
    - 「しかし」「そのため」のような接続詞を用いて文章を効果的につなげる
- Markdownが使える環境ならMarkdownを使って整理する
    - \`\`\`で囲うとコードブロックになる
    - `>`を使うと引用になる
    - 順序付きリストと箇条書きリストが書ける
    - `#` で見出しがつけられる
- スクリーンショットを貼れる環境かつ貼って理解に役立つならスクリーンショットを貼る
    - ページのどの部分がどのような状態になっているかなど

@piroor さんなら他にもフィードバックに向けた整理のやり方を示してくれるかもしれません！また、 @piroor さんが書かれた「[これでできる！ はじめてのOSSフィードバックガイド](https://github.com/oss-gate/first-feedback-guidebook) 」も参考になると思います！取り急ぎこのあたりが参考になりそうかなと思います！

- [どこにフィードバックしたらいいか分からない](https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/where.md)
- [どう報告すればいいのか分からない](https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/how.md)
- [英語での報告の仕方が分からない](https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/english.md)

**Comment by knokmki612** [comment]
PyConJPとスプリントおつかれさまでした！このissueはクローズしますが、引き続きコメントを書かれても大丈夫です！
OSS GateのDiscordサーバーも実はあったりします！
引き続き取り組まれたり、それ以外のことでも相談したいことあればgitterにてお声がけください！
