### ISSUE TITLE
OSS Gate Workshop: online: 2020-12-12: tomonori: AssertJ: Work log

### ISSUE THREAD

**Issue by se-tomo** [oss-gate/workshop#1431]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by se-tomo** [comment]
JUnit5関連のパッケージで、AssertJというものがあった。
https://assertj.github.io/doc/

**Comment by se-tomo** [comment]
https://github.com/assertj/assertj-core/blob/main/LICENSE.txt
Apache License 2.0
と記載されている。

**Comment by se-tomo** [comment]
https://github.com/assertj/doc
AssertJのドキュメントのイシューは上記

**Comment by se-tomo** [comment]
https://assertj.github.io/doc/
2.5.1. A simple example
を動かしてみる。

eclipseでGradleプロジェクトを作成し、以下をドキュメント通り追加して実行。
https://assertj.github.io/doc/#assertj-core-quick-start

**Comment by se-tomo** [comment]
テストコードを作成し、以下のコマンドを実行するも
gradle test

* What went wrong:
Error resolving plugin [id: 'java-library'].
> java.lang.NullPointerException (no error message)

**Comment by knokmki612** [comment]
ふりかえりました！

> What went wrong:
> Error resolving plugin [id: 'java-library

Gradeのバージョンが古すぎたのが原因とのこと、動作するGradleのバージョンがどこかで分かると良いのかなと思いました！

また、 https://github.com/assertj/assertj-core/labels/good%20first%20issue を見てみようかという話をお聞きしたりしました！

**Comment by se-tomo** [comment]
[https://assertj.github.io/doc/#gradle
](https://assertj.github.io/doc/#gradle
)を見てAssertJをビルドパスに追加し、build.gradleに以下の記載を追加した。
testImplementation 'org.assertj:assertj-core:3.18.1'

その自分の環境で以下の、テストケースを作成した。
```
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        assertThat("The Lord of the Rings").isNotNull()
        .startsWith("The")
        .contains("Lord")
        .endsWith("Rings");
        fail("");
    }
}
```

その上で、以下のコマンドによりテストを実行した。
```
gradle test
```

```
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.0/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
   	mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api 'org.apache.commons:commons-math3:3.6.1'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation 'com.google.guava:guava:28.0-jre'

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'

    // AssertJ
    testImplementation 'org.assertj:assertj-core:3.18.1'
}
```

■期待する結果
ビルドが成功し、テストが実施できる。

■実際の結果
ビルドが失敗した。

■期待する結果が得られなかった理由
```
plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
}
```
上記のbuild.gradleが原因

ローカルPCのgradleのバージョンが2.0のため`java-library`
のためビルド失敗

■修正して欲しい点
[https://assertj.github.io/doc/#gradle
](https://assertj.github.io/doc/#gradle
)
上記の記載に追加で、ビルドコマンドについても記載があれば良いかと感じた。
```./gradlew test```
