### ISSUE TITLE
OSS Gate Workshop: online: 2020-12-12: managoon: cocopy: Work log

### ISSUE THREAD

**Issue by managoon** [oss-gate/workshop#1432]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by managoon** [comment]
spaderというプロジェクトを見つけた
https://rubygems.org/gems/spader
ライセンスはMITと書いてある。（コピペ）

**Comment by managoon** [comment]
2020年10月5日にリリースされたChrome拡張機能
https://chrome.google.com/webstore/detail/cocopy/ihnfodlbkhgjnbheemjhkjfkfglgbdgc/related

**Comment by managoon** [comment]
Githubリポジトリ
https://github.com/pokutuna/chrome-cocopy

**Comment by managoon** [comment]
ライセンスはブログによるとMIT
https://www.moongift.jp/2020/12/cocopy-%e3%82%b3%e3%83%94%e3%83%bc%e3%81%99%e3%82%8b%e6%96%87%e5%ad%97%e5%88%97%e3%82%92%e3%83%97%e3%83%ad%e3%82%b0%e3%83%a9%e3%83%9f%e3%83%b3%e3%82%b0%e3%81%a7%e3%81%8d%e3%82%8bgoogle-chrome/

GithubによるとReadMeには書いていなかった…webpack.config.jsには使っているパッケージ？についてのライセンスは書いてあった

**Comment by managoon** [comment]
Chrome拡張機能
https://chrome.google.com/webstore/detail/dictionaries-one-to-rule/diojcfpekhhnndfmggknljpnfpcccbhc

GitHub（Chrome拡張機能ページに記載）
https://github.com/pnlpal/dictionaries

LICENCE
GNU General Public License v2.0らしい
https://github.com/pnlpal/dictionaries/blob/master/LICENSE

**Comment by managoon** [comment]
ＯＳＳに当たるかどうかのチェック
https://opensource.org/licenses/alphabetical

コミュニティサイト
https://pnlpal.dev/topic/2/welcome-to-pnlpal/1

**Comment by managoon** [comment]
既にOSS活動していそうな形跡を見つけた
Contributerに日本人のプルリクを発見
https://github.com/asakaze-at

タイポの修正ぽい
![image](https://user-images.githubusercontent.com/58316875/101976110-6b183e80-3c85-11eb-8aaf-403712c5075a.png)

**Comment by managoon** [comment]
使用感確かめ中

Helpやドキュメントは見つからない…

**Comment by managoon** [comment]
課題：人への説明　拡張機能cocopyのライセンス記載が見つからない件について
拡張機能URL：https://chrome.google.com/webstore/detail/cocopy/ihnfodlbkhgjnbheemjhkjfkfglgbdgc/related
GithubURL：https://github.com/pokutuna/chrome-cocopy

【前提】
ライセンス状況が確認できない

【想定（期待される結果）】
GithubのREADMEやLICENSEにて、ライセンス情報の記載が確認できる想定でした。

【実際の結果】
GithubのREADMEには記載が有りませんでした。
LICENSEは存在しませんでした。

licenseで検索した結果、ヒットしたwebpack.config.jsには、下記のように使用されているパッケージについてのLicenseらしき記載のみ確認できました。
`    new LicenseWebpackPlugin({
      perChunkOutput: false,
      licenseTextOverrides: {
        // LICENSE file is not included in the package
        'styled-components':
          'https://github.com/styled-components/styled-components/blob/master/LICENSE',
        isarray: 'https://github.com/juliangruber/isarray/blob/master/LICENSE',
      },
    }),`

**Comment by managoon** [comment]
ライセンスなどよくあるケースの場合は背景は余り明らかにしなくてフランクでよい。
実際の作業の再現などは背景含め詳しく書いたほうが良いかもしれない。

**Comment by managoon** [comment]
以下イシューに提出済み
https://github.com/pokutuna/chrome-cocopy/issues/49

**Comment by managoon** [comment]
![image](https://user-images.githubusercontent.com/58316875/101978743-8e011d80-3c9a-11eb-9100-41f6dc96a2da.png)
リンクを記入するとリンク先にも自動的に共有される仕様らしい

**Comment by managoon** [comment]
「Dictionaries」機能＆Github確認中

下記でリンク切れ発見
アプリの作者が中国語メインと推測されるので、英語か中国語でイシュー提出見込み

How to add more dictionaries?
https://github.com/pnlpal/dictionaries/blob/master/more-dicts.md
![image](https://user-images.githubusercontent.com/58316875/101979162-edacf800-3c9d-11eb-8871-d48bc1d64275.png)

**Comment by managoon** [comment]
extra-dicts.jsonで検索
https://github.com/search/advanced

recently commitedでソートすると5日前にremoveされた形跡がある。
https://github.com/search?l=&q=extra-dicts.json&type=commits
![image](https://user-images.githubusercontent.com/58316875/101979245-dde1e380-3c9e-11eb-80ea-fb463d9fbd83.png)

**Comment by managoon** [comment]
背景は分からないけどリンク切れは聞いていい気がする
流石に英語かな…

**Comment by managoon** [comment]
【前提】
下記リンクの文書内のリンクが切れている

【想定（期待される結果）】
How to add more dictionaries?
https://github.com/pnlpal/dictionaries/blob/master/more-dicts.md
extra-dics.json部分のリンクからhttps://github.com/pnlpal/dictionaries/blob/master/src/resources/extra-dicts.jsonに遷移する。
![image](https://user-images.githubusercontent.com/58316875/101979413-4da49e00-3ca0-11eb-9ab8-54a1ca35f11a.png)

【実際の結果】
404が表示される。
![image](https://user-images.githubusercontent.com/58316875/101979440-79c01f00-3ca0-11eb-91d3-c1a3d04aff1e.png)

**Comment by managoon** [comment]
英語版

【タイトル】
The link in the document below is broken.

【想定（期待される結果）】

【実際の結果】

【求める対応】

**Comment by ogom** [comment]
よろしくお願いします。
