### ISSUE TITLE
OSS Gate Workshop: online: 2020-12-12: viton: GitLab Development Kit (GDK): Work log

### ISSUE THREAD

**Issue by shinyaishida** [oss-gate/workshop#1433]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shinyaishida** [comment]
普段よく使う OSS っぽいもの
- GitLab
- Python
- Typescript
  - Nestjs
  - Express
  - Typeorm
- Rails

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by shinyaishida** [comment]
gitlab license で google 検索。

https://about.gitlab.com/pricing/licensing-faq/

**Comment by shinyaishida** [comment]
https://gitlab.com/gitlab-org/gitlab

GitLab に gitlab プロジェクトがあった。

**Comment by shinyaishida** [comment]
の中の[ライセンスファイル](https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE)

**Comment by ogom** [comment]
editions に記載がありました。
https://gitlab.com/gitlab-org/gitlab#editions

**Comment by shinyaishida** [comment]
`MIT Expat license` って見たことないので、どういうものか調べる。

**Comment by ogom** [comment]
https://opensource.org/licenses/MIT

**Comment by shinyaishida** [comment]
https://www.debian.org/legal/licenses/mit

**Comment by shinyaishida** [comment]
https://www.wikidata.org/wiki/Q18526198

**Comment by shinyaishida** [comment]
OSS であることは間違いない。GitLab の CE 部分を題材にワークショップをすすめてみる。

**Comment by ogom** [comment]
https://gitlab.com/gitlab-org/gitlab#installation

**Comment by ogom** [comment]
https://gitlab.com/gitlab-org/gitlab#install-a-development-environment

**Comment by shinyaishida** [comment]
Ombibus コンテナで動かすよりも、開発者としての環境を用意してみる
https://gitlab.com/gitlab-org/gitlab-development-kit

**Comment by shinyaishida** [comment]
今使っている MacOS でもいけそう
https://gitlab.com/gitlab-org/gitlab-development-kit#system-requirements

**Comment by shinyaishida** [comment]
Recommended の native install でやってみる

**Comment by shinyaishida** [comment]
と思ったけど依存がすごい
https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/index.md#install-dependencies

**Comment by shinyaishida** [comment]
ひよって vagrant に
https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/howto/vagrant.md

**Comment by shinyaishida** [comment]
三段構成にしなくてもと思うので、Vagrant/VirtualBox で
https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/howto/vagrant.md#vagrant-with-virtualbox

**Comment by shinyaishida** [comment]
MacOS なので 1. と 3. は関係ない。2. は既に入っている。
4. から

**Comment by shinyaishida** [comment]
4. をそのままするとこう
```
workspace/ossgate-online% vagrant up --provider=virtualbox --provision
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

**Comment by shinyaishida** [comment]
```
workspace/ossgate-online% vagrant init
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
/Users/shinyaishida/workspace/ossgate-online% vagrant up --provider=virtualbox --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/shinyaishida/workspace/ossgate-online/base
```

**Comment by shinyaishida** [comment]
OS を指定できていない。
https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/index.md#develop-against-the-gitlab-project-default
で推奨されているのが macOS、Ubuntu、Debian なので Ubuntu を使う

**Comment by shinyaishida** [comment]
とりあえず戻せるように残す
```
workspace/ossgate-online% git commit -m 'initial commit'                                                                                                                                                        ![master]
[master (root-commit) 46561cc] initial commit
 3 files changed, 80 insertions(+)
 create mode 100644 .vagrant/machines/default/virtualbox/vagrant_cwd
 create mode 100644 .vagrant/rgloader/loader.rb
 create mode 100644 Vagrantfile
```

**Comment by shinyaishida** [comment]
Vagrantfile 内のコメントに従って、https://vagrantcloud.com/search でイメージを探す。

**Comment by shinyaishida** [comment]
どっかに 20.04 って書いてあった気がするので、https://app.vagrantup.com/ubuntu/boxes/focal64 を使う

**Comment by ogom** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/advanced.md#ubuntu-and-debian

**Comment by shinyaishida** [comment]
```
/workspace/ossgate-online% git diff                                                                                                                                                                              +[master]
diff --git a/Vagrantfile b/Vagrantfile
index cb9d9ff..f3c4fa5 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -12,7 +12,7 @@ Vagrant.configure("2") do |config|

   # Every Vagrant development environment requires a box. You can search for
   # boxes at https://vagrantcloud.com/search.
-  config.vm.box = "base"
+  config.vm.box = "ubuntu/focal64"

   # Disable automatic box update checking. If you disable this, then
   # boxes will only be checked for updates when the user runs
```

**Comment by shinyaishida** [comment]
```
workspace/ossgate-online% vagrant up --provider=virtualbox --provision                                                                                                                                          +[master]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/focal64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/focal64' version '20200928.0.0' is up to date...
==> default: A newer version of the box 'ubuntu/focal64' for provider 'virtualbox' is
==> default: available! You currently have version '20200928.0.0'. The latest is version
==> default: '20201210.0.0'. Run `vagrant box update` to update.
==> default: Setting the name of the VM: ossgate-online_default_1607750565715_30486
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```
プロンプトが返ってこない。。。

**Comment by shinyaishida** [comment]
タイムアウトで停止
```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by shinyaishida** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/3822606/101976225-74ee7180-3c86-11eb-82c3-da78f948c938.png">

**Comment by shinyaishida** [comment]
一旦 halt

**Comment by shinyaishida** [comment]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/3822606/101976249-bc74fd80-3c86-11eb-883d-827a6c6e1608.png">

**Comment by shinyaishida** [comment]
```
workspace/ossgate-online% vagrant status                                                                                                                                                                        +[master]
Current machine states:

default                   stopping (virtualbox)

The VM is stopping.
```

**Comment by shinyaishida** [comment]
仮想マシンのメモリ、ホストには16GB 搭載してるけど、9GB強消費しているので、4GB にする。

**Comment by shinyaishida** [comment]
```
workspace/ossgate-online% git diff                                                                                                                                                                              +[master]
diff --git a/Vagrantfile b/Vagrantfile
index cb9d9ff..ba9ed6e 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -12,7 +12,7 @@ Vagrant.configure("2") do |config|

   # Every Vagrant development environment requires a box. You can search for
   # boxes at https://vagrantcloud.com/search.
-  config.vm.box = "base"
+  config.vm.box = "ubuntu/focal64"

   # Disable automatic box update checking. If you disable this, then
   # boxes will only be checked for updates when the user runs
@@ -49,13 +49,13 @@ Vagrant.configure("2") do |config|
   # backing providers for Vagrant. These expose provider-specific options.
   # Example for VirtualBox:
   #
-  # config.vm.provider "virtualbox" do |vb|
+  config.vm.provider "virtualbox" do |vb|
   #   # Display the VirtualBox GUI when booting the machine
   #   vb.gui = true
   #
   #   # Customize the amount of memory on the VM:
-  #   vb.memory = "1024"
-  # end
+    vb.memory = "4096"
+  end
   #
   # View the documentation for the provider you are using for more
   # information on available options.
```

**Comment by shinyaishida** [comment]
up できない
```
workspace/ossgate-online% vagrant up                                                                                                                                                                            +[master]
Bringing machine 'default' up with 'virtualbox' provider...
An action 'up' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
```

**Comment by shinyaishida** [comment]
VirtualBox で default が動いてた
<img width="494" alt="image" src="https://user-images.githubusercontent.com/3822606/101976357-db27c400-3c87-11eb-81e7-1e4ac959b07d.png">

**Comment by shinyaishida** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/3822606/101976386-1629f780-3c88-11eb-886a-a543e4a55787.png">

**Comment by shinyaishida** [comment]
default という名前を変えたらなんとか起動できないかな
https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name

**Comment by shinyaishida** [comment]
ふりかえり
- 今後の進め方
  - Native で動かす?
  - 題材を GitLab 以外に変える?
- コメント
  - VirtualBox 最新にしてみるとよいかも

**Comment by shinyaishida** [comment]
VirtualBox 入れ直しても症状変わらず。

**Comment by ogom** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/howto/gitpod.md

**Comment by shinyaishida** [comment]
community contributor でやる

**Comment by shinyaishida** [comment]
Issue で上げること

記載されている手順を文字通りに作業を実施すると、Vagrant 上に GDK の環境を構築できるようにしてほしい。

**Comment by shinyaishida** [comment]
1. (optional for Windows users) Disable Hyper-V then enable virtualization technology via the BIOS.
1. Install VirtualBox and Vagrant.
1. Configure NFS for Vagrant if you are on Linux.
1. Run `vagrant up --provider=virtualbox --provision` in this directory (from an elevated command prompt if on Windows).  Vagrant downloads an OS image, brings it up, and installs all the prerequisites.
1. Run `vagrant ssh` to SSH into the box.
1. Run `cd /vagrant`.
1. Continue setup at Installation.

2. の後文字通り 4. を実行しても仮想マシンは起動しない。`vagrant init` を実行しないといけないこと、Vagrantfile を "適切に" 設定しないといけないこと、の二点をユーザーが知っていて 4. の前に実施していることが前提になっている。
https://github.com/oss-gate/workshop/issues/1433#issuecomment-743704981

**Comment by shinyaishida** [comment]
Vagrantfile リポジトリにあった。。。

**Comment by shinyaishida** [comment]
Gitpod 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/3822606/101978026-40ce7d00-3c95-11eb-8bf4-dd95bdc0784d.png">
リロードボタンを押すと GitLab のログイン画面がちゃんと表示される。
<img width="639" alt="image" src="https://user-images.githubusercontent.com/3822606/101978055-7a9f8380-3c95-11eb-83c9-e6950c08ba5f.png">

**Comment by shinyaishida** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3822606/101978071-99057f00-3c95-11eb-871e-8de2ee3ea638.png">

**Comment by shinyaishida** [comment]
Open Site in New Window をクリックするとこう
![Uploading image.png…]()

**Comment by shinyaishida** [comment]
Chrome だとどうなるか見てみる

**Comment by shinyaishida** [comment]
Firefox で表示されている URL を Chrome で開いて、GitLab でサインインすると GitLab アカウントで GitPod が開いた。成功

**Comment by shinyaishida** [comment]
504 が出ることがあるけど、リロードボタンを押せばいい、と gitpod.md に書いてもらうことを提案する。
https://github.com/oss-gate/workshop/issues/1433#issuecomment-743716643

**Comment by shinyaishida** [comment]
再現手順
- OS: MacOS 10.15.7
- ブラウザ: Firefox 83.0 (64-bit)
- https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/master/doc/howto/gitpod.md の "If you are a community contributor:" で実施
  - I didn't have a Gitpod account. So, I create a new Gitpod account. Then, connected the Gitpod account to my GitLab account.
右のプレビュー画面に GitLab のサインイン画面ではなく、504 エラーの画面が表示される。プレビュー画面のリロードボタンを押すと、GitLab のサインイン画面が表示される。
<img width="111" alt="image" src="https://user-images.githubusercontent.com/3822606/101978749-9b1e0c80-3c9a-11eb-8f2f-23b12e153dde.png">

**Comment by shinyaishida** [comment]
期待

"Sign in to GitLab running in GDK, and you are ready to make or review changes. If you
have questions about the UI or if you are curious have a look at:" の文のあとに、もし 504 エラーが表示されたらプレビューのリロードボタンを押せばサインイン画面が表示される、と書いてある。

**Comment by shinyaishida** [comment]
実際

504 エラーの可能性と対処法については言及されていない。

**Comment by shinyaishida** [comment]
Issues と Merge Requests に類似の提案・リクエストがないかあらかじめ検索しておく。今回のキーワードは gitpod と timeout。504 は偶然一致する可能性があるので、言葉の方がいいらしい。

**Comment by shinyaishida** [comment]
なさげ

**Comment by shinyaishida** [comment]
どこに追加説明文を入れてほしいかも伝わるので mergerequest で出してみる。

**Comment by shinyaishida** [comment]
Merge Request で書くとき、文章の体裁が揃うように気を配る。改行のお作法とか。

**Comment by shinyaishida** [comment]
```
After that is done, you just wait 7-8 minutes for the entire setup to finish, and
you see the GDK UI pop up in the right sidebar.
```
 を
```
After that is done, you just wait 7-8 minutes for the entire setup to finish, and
you see the GDK UI pop up in the right sidebar. If you see 504 Gateway Time-out error, 
click the reload button in the right side bar.
```

**Comment by shinyaishida** [comment]
Commit message の好みも事前に調べる。長いのがいいか、短いのがいいか。

**Comment by shinyaishida** [comment]
Gitpod 上で GitLab のサインイン画面が Gateway Time-out のときの対処法を追記

**Comment by shinyaishida** [comment]
「GitLab のサインイン画面が Gateway Time-out のときはリロードすればよい、ことを追記」

**Comment by shinyaishida** [comment]
Add a note to resolve Gateway Time-out of GitLab sign-in page on Gitpod.

**Comment by ogom** [comment]
Add a note to resolve Gateway Time-out of GitLab sign-in page on howto Gitpod.

**Comment by shinyaishida** [comment]
これで出す

**Comment by ogom** [comment]
GDK はこちらに日本語で記事がありました。
https://qiita.com/tnir/items/ebcbca217b5da397d646

**Comment by ogom** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/-/merge_requests/1723
