### ISSUE TITLE
OSS Gate Workshop: online: 2020-12-12: ZeitungM: 第N曜日 API: Work log

### ISSUE THREAD

**Issue by ZeitungM** [oss-gate/workshop#1434]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by ZeitungM** [comment]
第N曜日 APIというプロジェクトを見つけた
https://github.com/kuboon/cal.kbn.one
ライセンスは package.json に MITと書いてある。

Ruby のプロジェクトの中で日本語でドキュメントが書かれていてとっつきやすそうだと思った

**Comment by knokmki612** [comment]
OSS Gate的にはドキュメントのチュートリアルとかInstallationを読みながらユーザー目線で書いてあることをすすめるのがセオリーなんだけど、今回のものはそういったドキュメント類は豊富ではなさそう

**Comment by knokmki612** [comment]
「第2、第4木曜日 みたいなやつをさっと取れる API」というのがさっと取れるが何をとっているのかピンと来ていない

といった、気になることをコメントでまず眺めながら残してもらうのがよさそう？

**Comment by knokmki612** [comment]
1. ローカルにこのパッケージを落として、nodeコマンド上で動くことを確かめる
2. リポジトリ内を眺めて、初めて使うという目線で気になることを書いてみる

の2つの進め方があるかなと思いました

**Comment by ZeitungM** [comment]
1. の実際に動くことの確認をしようと思います

**Comment by knokmki612** [comment]
![image](https://user-images.githubusercontent.com/9744580/101975902-7c604b80-3c83-11eb-99c1-5a031ecd4590.png)

**Comment by ZeitungM** [comment]
`$ git clone git@github.com:kuboon/cal.kbn.one.git`
でローカルにダウンロードした

**Comment by ZeitungM** [comment]
事前に処理系(ruby)を自分のサーバにインストールしてあったので、そっちで動かそうと思った
(ローカル = 手元の PC のことかと思った)

**Comment by ZeitungM** [comment]
認証が済んでいなかったので、 SSH でクローンできなかった
アドバイスにしたがって `git clone https://github.com/kuboon/cal.kbn.one.git` でクローン

**Comment by knokmki612** [comment]
> ローカルにこのパッケージを落として、nodeコマンド上で動くことを確かめる

勝手にnodeの対話モードで動かす必要があると思ったが、

[README](https://github.com/kuboon/cal.kbn.one#%E4%BD%BF%E3%81%84%E6%96%B9)に

> 上記関数を組み込み済みの https://cal.kbn.one/api/week/2020/2,4/th.js も用意したので、ブラウザの import() を使って以下のようにするのが一番簡単です。

と書いてあるので、ブラウザでも動かせそう

そして、この使い方に書いてあるものは既に立っているAPIサーバー https://cal.kbn.one のAPIの叩き方とか活用例のようだということが分かった

**Comment by ZeitungM** [comment]
clone ができたので ruby で api を叩いてみる
すると https://cal.kbn.one/api/week/2020/2,4/th で示されていたような結果が得られると思った

**Comment by knokmki612** [comment]
> clone ができたので ruby で api を叩いてみる

Rubyの実行環境上で https://cal.kbn.one/api/week/2020/2,4/th にgetリクエスト送って返ってくるものを確認することを考えておられた @ZeitungM 

`/api` がSinatraで書かれていて、それを立ち上げて叩くというような確認の方法も考えられた

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by ogom** [comment]
インストレーションのドキュメントがないので困っていると思います。

**Comment by ZeitungM** [comment]
「API として使う」と「API サーバとして使う」の2つで意味が混在している

**Comment by ZeitungM** [comment]
この API を用いて日付を取得するためのコードやコマンドがわからない
(サンプルコードが欲しい)

**Comment by knokmki612** [comment]
https://github.com/kuboon/cal.kbn.one/blob/master/README.md

**Comment by knokmki612** [comment]
ウェブAPIドキュメントの例 https://developer.github.com/v3/issues/

**Comment by ZeitungM** [comment]
`% curl https://cal.kbn.one/api/week/2020/2,4/th.json`

```
[{"date":"2019-01-10","wday":4,"num":2,"y":2019,"m":1,"d":10},{"date":"2019-01-24","wday":4,"num":4,"y":2019,"m":1,"d":24},{"date":"2019-02-14","wday":4,"num":2,"y":2019,"m":2,"d":14},{"date":"2019-02-28","wday":4,"num":4,"y":2019,"m":2,"d":28},{"date":"2019-03-14","wday":4,"num":2,"y":2019,"m":3,"d":14},{"date":"2019-03-28","wday":4,"num":4,"y":2019,"m":3,"d":28},{"date":"2019-04-11","wday":4,"num":2,"y":2019,"m":4,"d":11},{"date":"2019-04-25","wday":4,"num":4,"y":2019,"m":4,"d":25},{"date":"2019-05-09","wday":4,"num":2,"y":2019,"m":5,"d":9},{"date":"2019-05-23","wday":4,"num":4,"y":2019,"m":5,"d":23},{"date":"2019-06-13","wday":4,"num":2,"y":2019,"m":6,"d":13},{"date":"2019-06-27","wday":4,"num":4,"y":2019,"m":6,"d":27},{"date":"2019-07-11","wday":4,"num":2,"y":2019,"m":7,"d":11},{"date":"2019-07-25","wday":4,"num":4,"y":2019,"m":7,"d":25},{"date":"2019-08-08","wday":4,"num":2,"y":2019,"m":8,"d":8},{"date":"2019-08-22","wday":4,"num":4,"y":2019,"m":8,"d":22},{"date":"2019-09-12","wday":4,"num":2,"y":2019,"m":9,"d":12},{"date":"2019-09-26","wday":4,"num":4,"y":2019,"m":9,"d":26},{"date":"2019-10-10","wday":4,"num":2,"y":2019,"m":10,"d":10},{"date":"2019-10-24","wday":4,"num":4,"y":2019,"m":10,"d":24},{"date":"2019-11-14","wday":4,"num":2,"y":2019,"m":11,"d":14},{"date":"2019-11-28","wday":4,"num":4,"y":2019,"m":11,"d":28},{"date":"2019-12-12","wday":4,"num":2,"y":2019,"m":12,"d":12},{"date":"2019-12-26","wday":4,"num":4,"y":2019,"m":12,"d":26},{"date":"2020-01-09","wday":4,"num":2,"y":2020,"m":1,"d":9},{"date":"2020-01-23","wday":4,"num":4,"y":2020,"m":1,"d":23},{"date":"2020-02-13","wday":4,"num":2,"y":2020,"m":2,"d":13},{"date":"2020-02-27","wday":4,"num":4,"y":2020,"m":2,"d":27},{"date":"2020-03-12","wday":4,"num":2,"y":2020,"m":3,"d":12},{"date":"2020-03-26","wday":4,"num":4,"y":2020,"m":3,"d":26},{"date":"2020-04-09","wday":4,"num":2,"y":2020,"m":4,"d":9},{"date":"2020-04-23","wday":4,"num":4,"y":2020,"m":4,"d":23},{"date":"2020-05-14","wday":4,"num":2,"y":2020,"m":5,"d":14},{"date":"2020-05-28","wday":4,"num":4,"y":2020,"m":5,"d":28},{"date":"2020-06-11","wday":4,"num":2,"y":2020,"m":6,"d":11},{"date":"2020-06-25","wday":4,"num":4,"y":2020,"m":6,"d":25},{"date":"2020-07-09","wday":4,"num":2,"y":2020,"m":7,"d":9},{"date":"2020-07-23","wday":4,"num":4,"y":2020,"m":7,"d":23},{"date":"2020-08-13","wday":4,"num":2,"y":2020,"m":8,"d":13},{"date":"2020-08-27","wday":4,"num":4,"y":2020,"m":8,"d":27},{"date":"2020-09-10","wday":4,"num":2,"y":2020,"m":9,"d":10},{"date":"2020-09-24","wday":4,"num":4,"y":2020,"m":9,"d":24},{"date":"2020-10-08","wday":4,"num":2,"y":2020,"m":10,"d":8},{"date":"2020-10-22","wday":4,"num":4,"y":2020,"m":10,"d":22},{"date":"2020-11-12","wday":4,"num":2,"y":2020,"m":11,"d":12},{"date":"2020-11-26","wday":4,"num":4,"y":2020,"m":11,"d":26},{"date":"2020-12-10","wday":4,"num":2,"y":2020,"m":12,"d":10},{"date":"2020-12-24","wday":4,"num":4,"y":2020,"m":12,"d":24},{"date":"2021-01-14","wday":4,"num":2,"y":2021,"m":1,"d":14},{"date":"2021-01-28","wday":4,"num":4,"y":2021,"m":1,"d":28},{"date":"2021-02-11","wday":4,"num":2,"y":2021,"m":2,"d":11},{"date":"2021-02-25","wday":4,"num":4,"y":2021,"m":2,"d":25},{"date":"2021-03-11","wday":4,"num":2,"y":2021,"m":3,"d":11},{"date":"2021-03-25","wday":4,"num":4,"y":2021,"m":3,"d":25},{"date":"2021-04-08","wday":4,"num":2,"y":2021,"m":4,"d":8},{"date":"2021-04-22","wday":4,"num":4,"y":2021,"m":4,"d":22},{"date":"2021-05-13","wday":4,"num":2,"y":2021,"m":5,"d":13},{"date":"2021-05-27","wday":4,"num":4,"y":2021,"m":5,"d":27},{"date":"2021-06-10","wday":4,"num":2,"y":2021,"m":6,"d":10},{"date":"2021-06-24","wday":4,"num":4,"y":2021,"m":6,"d":24},{"date":"2021-07-08","wday":4,"num":2,"y":2021,"m":7,"d":8},{"date":"2021-07-22","wday":4,"num":4,"y":2021,"m":7,"d":22},{"date":"2021-08-12","wday":4,"num":2,"y":2021,"m":8,"d":12},{"date":"2021-08-26","wday":4,"num":4,"y":2021,"m":8,"d":26},{"date":"2021-09-09","wday":4,"num":2,"y":2021,"m":9,"d":9},{"date":"2021-09-23","wday":4,"num":4,"y":2021,"m":9,"d":23},{"date":"2021-10-14","wday":4,"num":2,"y":2021,"m":10,"d":14},{"date":"2021-10-28","wday":4,"num":4,"y":2021,"m":10,"d":28},{"date":"2021-11-11","wday":4,"num":2,"y":2021,"m":11,"d":11},{"date":"2021-11-25","wday":4,"num":4,"y":2021,"m":11,"d":25},{"date":"2021-12-09","wday":4,"num":2,"y":2021,"m":12,"d":9},{"date":"2021-12-23","wday":4,"num":4,"y":2021,"m":12,"d":23}]% 
```

**Comment by ZeitungM** [comment]
実行結果をブラウザで確認できるリンクが貼ってあったけど、
コマンドラインから取得するときのために、このようなコマンドの例があると迷わなかったと思う

**Comment by knokmki612** [comment]
https://github.com/kuboon/cal.kbn.one/blob/master/now.json

**Comment by knokmki612** [comment]
## やりたいこと

## 理由

**Comment by ZeitungM** [comment]
開発者にとってわかりやすくなるようにフィードバックを修正する:

# 提案内容
コマンドラインやアプリケーションコードでの使い方を記述する

# 理由
コマンドラインから API を実行して日付を取得したかったが、

ReadMe の使い方に、ブラウザでの実行例しかなかったので、

3年分の日付が取得されることは ReadMe に明記されているが、
年を指定するとその年1年分のみを取得するようにも捉えられる。

コマンドラインからの実行例も掲載してあると、
指定した年の前後1年分含めた3年分の日付が取得されることがサンプルでもわかるのでありがたかった

# 例
`% curl https://cal.kbn.one/api/week/2020/2,4/th.json`

```[{"date":"2019-01-10","wday":4,"num":2,"y":2019,"m":1,"d":10},{"date":"2019-01-24","wday":4,"num":4,"y":2019,"m":1,"d":24},{"date":"2019-02-14","wday":4,"num":2,"y":2019,"m":2,"d":14},{"date":"2019-02-28","wday":4,"num":4,"y":2019,"m":2,"d":28},{"date":"2019-03-14","wday":4,"num":2,"y":2019,"m":3,"d":14},{"date":"2019-03-28","wday":4,"num":4,"y":2019,"m":3,"d":28},{"date":"2019-04-11","wday":4,"num":2,"y":2019,"m":4,"d":11},{"date":"2019-04-25","wday":4,"num":4,"y":2019,"m":4,"d":25},{"date":"2019-05-09","wday":4,"num":2,"y":2019,"m":5,"d":9},{"date":"2019-05-23","wday":4,"num":4,"y":2019,"m":5,"d":23},{"date":"2019-06-13","wday":4,"num":2,"y":2019,"m":6,"d":13},{"date":"2019-06-27","wday":4,"num":4,"y":2019,"m":6,"d":27},{"date":"2019-07-11","wday":4,"num":2,"y":2019,"m":7,"d":11},{"date":"2019-07-25","wday":4,"num":4,"y":2019,"m":7,"d":25},{"date":"2019-08-08","wday":4,"num":2,"y":2019,"m":8,"d":8},{"date":"2019-08-22","wday":4,"num":4,"y":2019,"m":8,"d":22},{"date":"2019-09-12","wday":4,"num":2,"y":2019,"m":9,"d":12},{"date":"2019-09-26","wday":4,"num":4,"y":2019,"m":9,"d":26},{"date":"2019-10-10","wday":4,"num":2,"y":2019,"m":10,"d":10},{"date":"2019-10-24","wday":4,"num":4,"y":2019,"m":10,"d":24},{"date":"2019-11-14","wday":4,"num":2,"y":2019,"m":11,"d":14},{"date":"2019-11-28","wday":4,"num":4,"y":2019,"m":11,"d":28},{"date":"2019-12-12","wday":4,"num":2,"y":2019,"m":12,"d":12},{"date":"2019-12-26","wday":4,"num":4,"y":2019,"m":12,"d":26},{"date":"2020-01-09","wday":4,"num":2,"y":2020,"m":1,"d":9},{"date":"2020-01-23","wday":4,"num":4,"y":2020,"m":1,"d":23},{"date":"2020-02-13","wday":4,"num":2,"y":2020,"m":2,"d":13},{"date":"2020-02-27","wday":4,"num":4,"y":2020,"m":2,"d":27},{"date":"2020-03-12","wday":4,"num":2,"y":2020,"m":3,"d":12},{"date":"2020-03-26","wday":4,"num":4,"y":2020,"m":3,"d":26},{"date":"2020-04-09","wday":4,"num":2,"y":2020,"m":4,"d":9},{"date":"2020-04-23","wday":4,"num":4,"y":2020,"m":4,"d":23},{"date":"2020-05-14","wday":4,"num":2,"y":2020,"m":5,"d":14},{"date":"2020-05-28","wday":4,"num":4,"y":2020,"m":5,"d":28},{"date":"2020-06-11","wday":4,"num":2,"y":2020,"m":6,"d":11},{"date":"2020-06-25","wday":4,"num":4,"y":2020,"m":6,"d":25},{"date":"2020-07-09","wday":4,"num":2,"y":2020,"m":7,"d":9},{"date":"2020-07-23","wday":4,"num":4,"y":2020,"m":7,"d":23},{"date":"2020-08-13","wday":4,"num":2,"y":2020,"m":8,"d":13},{"date":"2020-08-27","wday":4,"num":4,"y":2020,"m":8,"d":27},{"date":"2020-09-10","wday":4,"num":2,"y":2020,"m":9,"d":10},{"date":"2020-09-24","wday":4,"num":4,"y":2020,"m":9,"d":24},{"date":"2020-10-08","wday":4,"num":2,"y":2020,"m":10,"d":8},{"date":"2020-10-22","wday":4,"num":4,"y":2020,"m":10,"d":22},{"date":"2020-11-12","wday":4,"num":2,"y":2020,"m":11,"d":12},{"date":"2020-11-26","wday":4,"num":4,"y":2020,"m":11,"d":26},{"date":"2020-12-10","wday":4,"num":2,"y":2020,"m":12,"d":10},{"date":"2020-12-24","wday":4,"num":4,"y":2020,"m":12,"d":24},{"date":"2021-01-14","wday":4,"num":2,"y":2021,"m":1,"d":14},{"date":"2021-01-28","wday":4,"num":4,"y":2021,"m":1,"d":28},{"date":"2021-02-11","wday":4,"num":2,"y":2021,"m":2,"d":11},{"date":"2021-02-25","wday":4,"num":4,"y":2021,"m":2,"d":25},{"date":"2021-03-11","wday":4,"num":2,"y":2021,"m":3,"d":11},{"date":"2021-03-25","wday":4,"num":4,"y":2021,"m":3,"d":25},{"date":"2021-04-08","wday":4,"num":2,"y":2021,"m":4,"d":8},{"date":"2021-04-22","wday":4,"num":4,"y":2021,"m":4,"d":22},{"date":"2021-05-13","wday":4,"num":2,"y":2021,"m":5,"d":13},{"date":"2021-05-27","wday":4,"num":4,"y":2021,"m":5,"d":27},{"date":"2021-06-10","wday":4,"num":2,"y":2021,"m":6,"d":10},{"date":"2021-06-24","wday":4,"num":4,"y":2021,"m":6,"d":24},{"date":"2021-07-08","wday":4,"num":2,"y":2021,"m":7,"d":8},{"date":"2021-07-22","wday":4,"num":4,"y":2021,"m":7,"d":22},{"date":"2021-08-12","wday":4,"num":2,"y":2021,"m":8,"d":12},{"date":"2021-08-26","wday":4,"num":4,"y":2021,"m":8,"d":26},{"date":"2021-09-09","wday":4,"num":2,"y":2021,"m":9,"d":9},{"date":"2021-09-23","wday":4,"num":4,"y":2021,"m":9,"d":23},{"date":"2021-10-14","wday":4,"num":2,"y":2021,"m":10,"d":14},{"date":"2021-10-28","wday":4,"num":4,"y":2021,"m":10,"d":28},{"date":"2021-11-11","wday":4,"num":2,"y":2021,"m":11,"d":11},{"date":"2021-11-25","wday":4,"num":4,"y":2021,"m":11,"d":25},{"date":"2021-12-09","wday":4,"num":2,"y":2021,"m":12,"d":9},{"date":"2021-12-23","wday":4,"num":4,"y":2021,"m":12,"d":23}] ```

**Comment by knokmki612** [comment]
# 理由
APIの使い方(入力と出力)を理解したかったが、ブラウザでの実行例だけだと不十分だった。

例えば、3年分の日付が取得されることは ReadMe に明記されているが、
このAPIを理解していないと年を指定するとその年1年分のみを取得するように捉えやすい。

コマンドラインだと入力(実行するコマンド)と出力(返ってくる文字列)をサンプルコードとして記載できるので理解しやすい。
