### ISSUE TITLE
OSS Gate Workshop: Online: 2021-01-30: pandori3: uuidjs: Work log

### ISSUE THREAD

**Issue by pandori3** [oss-gate/workshop#1443]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by pandori3** [comment]
URL：https://github.com/uuidjs/uuid

**Comment by pandori3** [comment]
README.mdを読む

**Comment by pandori3** [comment]
MIT Licenseであることを確認

**Comment by pandori3** [comment]
最終コミットは25日前

**Comment by pandori3** [comment]
Issueの最終登録は５日前。最新クローズは２日前。

**Comment by pandori3** [comment]
１件PRがレビュー必要で挙がっている。20年11月。

**Comment by pandori3** [comment]
README.mdを読む

**Comment by pandori3** [comment]
※会話やり取りを聞いて反映
ライセンスファイル
https://github.com/uuidjs/uuid/blob/master/LICENSE.md

**Comment by pandori3** [comment]
CONTRIBUTING.mdを読んで貢献方法について確認する
https://github.com/uuidjs/uuid/blob/master/CONTRIBUTING.md

**Comment by pandori3** [comment]
貢献方法はIssue起票か、PRによる提案。

**Comment by pandori3** [comment]
リリースはマスターが行う。バージョンのバンプはstandard-versionで自動化する。

**Comment by pandori3** [comment]
README.mdのQuickStartを読む

**Comment by pandori3** [comment]
npm installが必要なので
`npm init`でpackage.jsonを作成する

**Comment by pandori3** [comment]
QuickStartのまま実行すると、結果の値は実行結果に見えないのでちょっといじる
index.js
`const { v4: uuidv4 } = require('uuid');
const sampleUUID = uuidv4();
console.log("sampleUUID,",sampleUUID);`

`node index.js`
>sampleUUID, 0d79759a-86d0-4595-aeaf-847ae5c3e684

**Comment by pandori3** [comment]
実行環境の記載漏れを検知：
OS:Windows 10 
node -v：v14.15.4

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by pandori3** [comment]
気になった要素：README.mdの想定読者レベルが不明だったため、フィードバックのレベル感が合うかどうか

フィードバック：その辺りは特に気にしなくてOK（読み取れないので）

**Comment by pandori3** [comment]
気づき：Privateでリポジトリ作って、Issueに作業ログ残したら整理前の雑多な奴も残しやすくてよさそう。
　・Twitterで連ツイするより楽
　・Notionで残してもいいけど、編集しやすさが当時の実態ベースにならない可能性がある
　・検索も使えるんでは

**Comment by shava2C** [comment]
> 気づき：Privateでリポジトリ作って、Issueに作業ログ残したら整理前の雑多な奴も残しやすくてよさそう。
> 　・Twitterで連ツイするより楽
> 　・Notionで残してもいいけど、編集しやすさが当時の実態ベースにならない可能性がある
> 　・検索も使えるんでは

これ僕も真似したいと思います！！！

**Comment by pandori3** [comment]
CLIがあることに今更気づいた。どう使うんだ？

**Comment by pandori3** [comment]
これで動いた
```
$ cd node_modules\uuid\dist
$ node uuid-bin 
6f614685-ce78-497f-b8bf-ba428bd7782c
```

**Comment by pandori3** [comment]
記載ミス？前提が違う？

https://github.com/uuidjs/uuid#command-line
Command Lineの記載通りでは動かない
```
ossgateSandbox\node_modules\uuid\dist>node uuid --help
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'ossgateSandbox\node_modules\uuid\dist\uuid'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)  
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

直してやればよさげ
```
ossgateSandbox\node_modules\uuid\dist>node uuid-bin --help
Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs defined by RFC4122
```

**Comment by pandori3** [comment]
https://github.com/uuidjs/uuid/blob/master/package.json
binではdist/bin/uuidを指定してる
```
  "bin": {
    "uuid": "./dist/bin/uuid"
  },
```

**Comment by pandori3** [comment]
実行パスが1階層浅かった
```
ossgateSandbox\node_modules\uuid\dist\bin>node uuid --help
Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs defined by RFC4122
```

**Comment by pandori3** [comment]
イシューは2タイプ。バグレポートと機能リクエスト
https://github.com/uuidjs/uuid/issues/new/choose

**Comment by pandori3** [comment]
https://github.com/uuidjs/uuid/blob/master/README_js.md
スタンドアロンでさっとUUID発行したい際に非常に便利。
コマンドラインの機能についてパスを修正したい。
記載されている通りに実行するとエラーで動かない。

変更前）
$ uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4

変更後）
node node_modules\uuid\dist\bin\uuid
43902054-99b7-4bb9-952a-81139c6525b9

**Comment by pandori3** [comment]
README.mdはRunMDを使って作成されているようなので、RunMDの内容についても確認する。

**Comment by pandori3** [comment]
https://github.com/uuidjs/uuid/blob/master/package.json

scriptブロックにRunMDの生成コマンドを発見
"md": "runmd --watch --output=README.md README_js.md",

**Comment by pandori3** [comment]
$ uuid>npm run md
Error: Cannot find module './dist/'

distがないのでコケた。

$ uuid>npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uuid@8.3.2 build: `./scripts/build.sh`
npm ERR! Exit status 1

ビルド用のスクリプトがまさかのシェルスクリプト。別端末でやってみる

**Comment by pandori3** [comment]
RunMDはMarkdown内のJSでできたコードブロックが実行可能になる模様。

**Comment by pandori3** [comment]
$ npm run md で走らせても処理が終わらんな・・・と思ったら、
--watch オプションがついているとファイルをウォッチしていて、随時変更してくれる？
試してみる。

**Comment by pandori3** [comment]
$ npm run md 
console出力: Rendered README.md
-- README_js.mdを編集--
console出力: Rendered README.md
-- README.mdの自動修正を確認

該当のコードブロックはshellのため、実行周りへの影響はなさそう

**Comment by pandori3** [comment]
このリポジトリをクローンして単体で使う場合と、メインのプロジェクトに入れつつ使う場合とで
実行例を分けて記載した方がわかりやすいか？

**Comment by pandori3** [comment]
記載例(ドラフト)

## Command Line

UUIDs can be generated from the command line using `uuid`.

### Case1: Clone and use this module
```shell
$ npm run build
$ node dist/bin/uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```
The default is to generate version 4 UUIDS, however the other versions are supported. Type `uuid --help` for details:

```shell
$ npm run build
$ node dist/bin/uuid --help

Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs
defined by RFC4122
```

### Case2: Use after installing in another project
```shell
$ node node_modules/uuid/dist/bin/uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```

This case can also be used. `uuid --help`
```shell
$ npm run build
$ node node_modules/uuid/dist/bin/uuid --help

Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs
defined by RFC4122
```

**Comment by pandori3** [comment]
見づらいような気もする

**Comment by pandori3** [comment]
Case2はinstall行は削除（Quick Startにも記載があるので冗長的に感じる)

**Comment by pandori3** [comment]
PRコメントを考えてみる

**Comment by pandori3** [comment]
一発目の誉め言葉をどうしようか悩み中

**Comment by pandori3** [comment]
ReactのPR辺りを見に行けばよさそうな書きっぷりがありそう

**Comment by pandori3** [comment]
気づき：PRもIssueも善意のモノだけではない

**Comment by pandori3** [comment]
PRコメント案

This package is fantastic!
I found out that it is available from the command line and tried it.
If you copy and paste as it is, an error will occur, so
I think it will be easier to understand by adding the path.

**Comment by pandori3** [comment]
どんなエラーが発生するか？
具体的に記載する。

サンプルを記載する

**Comment by pandori3** [comment]
README.mdのまま実行すると以下の結果になる
```shell
uuid pandori3$ uuid
bash: uuid: command not found
```

build実行後、dist/binの下のパスにあるuuidを実行すれば正しく動作する
```shell
uuid pandori3$ npm run build
uuid pandori3$ node dist/bin/uuid --help
Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs defined by RFC4122
```

**Comment by pandori3** [comment]
まとめる。

**Comment by pandori3** [comment]
タイトル：
Command line usage fix suggestions

本文：
This package is fantastic!
I found out that it is available from the command line and tried it.
I suggest modifying the command line usage.

If you execute it with README.md as it is, the following result will be obtained.
```shell
uuid pandori3$ uuid
bash: uuid: command not found
```

After running `npm run build`, run `uuid` in the path under dist / bin and it works fine
```shell
uuid pandori3$ npm run build
uuid pandori3$ node dist/bin/uuid --help
Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs defined by RFC4122
```

**Comment by pandori3** [comment]
https://github.com/oss-gate/workshop/issues/1443#issuecomment-770167142

やったことだけを書く。

PRは全てSuggestionになる。

**Comment by pandori3** [comment]
読み手に瞬間的に内容が伝わる構成にする。

**Comment by pandori3** [comment]
READMEの修正案
※package.jsonのbin項はグローバルインストールすると使える。

## Command Line

UUIDs can be generated from the command line using `uuid`.

### precondition
- If you want to use this feature, run `npm install -g uuid`

```shell
$ uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```

The default is to generate version 4 UUIDS, however the other versions are supported. Type `uuid --help` for details:

```shell
$ uuid --help

Usage:
  uuid
  uuid v1
  uuid v3 <name> <namespace uuid>
  uuid v4
  uuid v5 <name> <namespace uuid>
  uuid --help

Note: <namespace uuid> may be "URL" or "DNS" to use the corresponding UUIDs
defined by RFC4122
```

**Comment by pandori3** [comment]
メモ：npx について調べる

**Comment by pandori3** [comment]
タイトル：
Fix document: CLI usage add 'npx'

本文：
This package is fantastic!

Adding'npx' to the CLI usage makes it easier to read.

### Before
```
$ uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```

### After
```
$ npx uuid
ddeb27fb-d9a0-4624-be4d-4615062daed4
```

**Comment by pandori3** [comment]
本件、PRが承認・マージされました。
ありがとうございます。これを機に他のパッケージでもできそうな事が無いか見ていこうと思います。
