### ISSUE TITLE
OSS Gate Workshop: オンライン: 2021-01-30: MUnehiroMachida: composer: Work log

### ISSUE THREAD

**Issue by MunehiroMachida** [oss-gate/workshop#1444]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by MunehiroMachida** [comment]
Composer
本家：https://getcomposer.org/
補足：https://weblabo.oscasierra.net/php-composer-1/

**Comment by MunehiroMachida** [comment]
ライセンス：https://github.com/composer/composer/blob/master/LICENSE
MIT Licenseであることを確認

**Comment by MunehiroMachida** [comment]
最終コミットは2021年 1月 29日

**Comment by MunehiroMachida** [comment]
リリースは2021年 1月 28日

**Comment by MunehiroMachida** [comment]
ライブラリのgithub：https://github.com/composer

**Comment by MunehiroMachida** [comment]
インストール手順
リンク：https://github.com/composer/composer/blob/master/README.md#composer---dependency-management-for-php
に飛び、目次の`Installation / Usage`の部分を確認

公式のダウンロード手順：Download and install Composer by following the official instructions.
使用方法：For usage, see the documentation.

**Comment by MunehiroMachida** [comment]
パッケージ
https://packagist.org/

**Comment by MunehiroMachida** [comment]
なぜ、これを控えたのか。

リリース日など、なぜ控えたのか、忘れるから、書き出しておく

**Comment by MunehiroMachida** [comment]
自分が実行して見てどうだった？

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by MunehiroMachida** [comment]
どのRead.Meを見たかもメモしとく。
ドキュメントがたくさんあるので、
・Introduction
・Basic usage
で読むといいかも

**Comment by ogom** [comment]
issue のタイトルの `オンラインワークショップ` を `composer` に変えてもよさそうです。

**Comment by MunehiroMachida** [comment]
## 午前中やってみて
OSSに参加をする。というニュアンスの違いが個人的にあった。

誰かのリポジトリを見て、コードを見て直す。
そういうことかなと思っていたけど、実際はREADMEを見て
どれくらい、活発かとか開発者がいるのかなどある程度、推測することができるので
そこからやる必要があるんだなと。

READMEに書かれていることでわかりにくいことや
公式ページのインストール手順を見てわかりにくいことがあれば

『わかりやすいようにまとめる。』

というような貢献の仕方もあるんだなと気づけた。

まだやっていないけど、実行してみてわかりにくいからまとめてみたり
コードを見てコミットしてみたり、

OSSに参加。と言ってもいろんな貢献方法があると気づけたのは大きい。

色々、手探りだし、言語化も出来ていないけど
少しづつ成長していきたい。

**Comment by MunehiroMachida** [comment]
> issue のタイトルの `オンラインワークショップ` を `composer` に変えてもよさそうです。

**Comment by MunehiroMachida** [comment]
> issue のタイトルの `オンラインワークショップ` を `composer` に変えてもよさそうです。

ご指摘ありがとうございます。
修正しました。

**Comment by MunehiroMachida** [comment]
コントリビューションガイド

READMEの中とかにあるかも。

**Comment by MunehiroMachida** [comment]
Composerのインストール手順はhttps://getcomposer.org/doc/のBasic usageを見てやってみる

**Comment by MunehiroMachida** [comment]
# Introduction
https://getcomposer.org/doc/00-intro.md

**Comment by MunehiroMachida** [comment]
Composerがそもそもわからない(2021/01/30)

**Comment by nekomatu** [comment]
1on1で得た知見をぜひここに書き出してみてください。
スペルチェッカーを当てた結果何が分かったかを書くのは忘れずに！

**Comment by MunehiroMachida** [comment]
Composerのことが自分自身わかっておらず、つまずいていた。
技術力が低い、自分でも今OSSに貢献できることとして、タイポを探す。ということを教えてもらった。

プロジェクト自体、タイポがない方がいいのでそれを探す。
なかったらなかったで、高品質なことがわかるのでそれはそれでいいんだなと。

実際にやってみて、英語がわからなかったり、用語だったり、スペース空けるべきかどうか迷ったりしたが
サポーターのnekomatuさんに教えてもらったり、調べたりした。

`drupal`の`multisite`は`multi site`のようにスペース開けるかなと思ったが検索結果がスペースを入れていない文字が出てきた。
ツールによって、その単語のルールが決まっているということを教えていただいた。

結局、Composerにタイポはなく高品質なプロジェクトなんだなとわかった。

技術力がなくても、細かい部分だったりでエンジニアとして貢献できる。
どちらも鍛えていきたい
