### ISSUE TITLE
OSS Gate Workshop: online: 2021-01-30: shava:youtube-dl : Work log 

### ISSUE THREAD

**Issue by shava2C** [oss-gate/workshop#1445]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shava2C** [comment]
## コントリビュート候補

* [radicast](https://github.com/soh335/radicast)
  →普段使っている。GoLang（未経験）。日本製。

* [youtube-dl](https://github.com/ytdl-org/youtube-dl)

  →普段使っている。Python（未経験）。海外製。

* [Friendly](https://github.com/Codeer-Software/Friendly)

  →業務で使っていた。C#。日本製。

**Comment by shava2C** [comment]
## コントリビュート決定

* radicast  
  参照：[LICENSE](https://github.com/soh335/radicast/blob/master/LICENSE)  
  [commits](https://github.com/soh335/radicast/commits/master)と[Releases](https://github.com/soh335/radicast/releases)が一年以上止まっている。
* **youtube-dl(決定)**
  参照：[LICENSE](https://github.com/ytdl-org/youtube-dl/blob/master/LICENSE)  
  [commits](https://github.com/ytdl-org/youtube-dl/commits/master)と[Releases](https://github.com/ytdl-org/youtube-dl/releases)ともに盛ん
* Friendly
  参照：[LICENSE](https://github.com/Codeer-Software/Friendly/blob/master/LICENSE)  
  [commits](https://github.com/Codeer-Software/Friendly/commits/master)は盛ん
  ※企業のRepositoryであったため、敷居が高い（かも）  
  issueなどは上げることは可能

**Comment by shava2C** [comment]
## ReadMe見ながら動かしてみる①

#### その他

参照：[README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md)  
環境：windows10

#### INSTALLATION

* win用のexeをインストール：[download an .exe file](https://yt-dl.org/latest/youtube-dl.exe)   
→英語「place it in any location on their PATH except for %SYSTEMROOT%\System32 (e.g. do not put in C:\Windows\System32).」の英語を誤解していた

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる②
#### 格納場所
C:\Users\ユーザー名\Documents\02_Resources\OSS\youtube-dl

**Comment by shava2C** [comment]
#### ReadMe見ながら動かしてみる②
> DESCRIPTION
youtube-dl is a command-line program to download videos from YouTube.com and a few more sites. It requires the Python interpreter, version 2.6, 2.7, or 3.2+, and it is not platform specific. It should work on your Unix box, on Windows or on macOS. It is released to the public domain, which means you can modify it, redistribute it or use it however you like.
youtube-dl [OPTIONS] URL [URL...]

の英語を読解中
→

**Comment by shava2C** [comment]
#### 振り返り実施  
アクション：所感も入れる、作業メモの更新頻度を上げる（細かいほどベター）

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる

#### 端末のPythonバージョン確認

**Comment by shava2C** [comment]
> ### ReadMe見ながら動かしてみる
> #### 端末のPythonバージョン確認

Python のバージョンを確認する方法 - Windows - Python の準備

```
C:\Users\ユーザ>python --version
Python 3.8.3
```

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by shava2C** [comment]
> ## ReadMe見ながら動かしてみる①
> #### その他
> 参照：[README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md)
> 環境：windows10
> 
> #### INSTALLATION
> * win用のexeをインストール：[download an .exe file](https://yt-dl.org/latest/youtube-dl.exe)
>   →英語「place it in any location on their PATH except for %SYSTEMROOT%\System32 (e.g. do not put in C:\Windows\System32).」の英語を誤解していた

所感：OSごとにインストール方法が分かれてないからわかりずらい

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる
上から読み進めているが、かなり長文であるため、割愛したほうがいいところがありそう。

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる
とりあえず、本質的な機能を動かせるか確認
[Output template examples](https://github.com/ytdl-org/youtube-dl#output-template-examples)
```
# Download YouTube playlist videos in separate directory indexed by video order in a playlist
$ youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re

```

**Comment by shava2C** [comment]
> ### ReadMe見ながら動かしてみる
> とりあえず、本質的な機能を動かせるか確認
> [Output template examples](https://github.com/ytdl-org/youtube-dl#output-template-examples)
> 
> ```
> # Download YouTube playlist videos in separate directory indexed by video order in a playlist
> $ youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re
> ```

ここが本質的な機能ではないのでは？
→質問：ReadMeを読む際の勘所（[Option](https://github.com/ytdl-org/youtube-dl#options)は適宜詰まったら読む、、、など）はどうやってつかめばいいのだろう。

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる
#### CONFIGURATION
ここら辺にプロキシなど、端末でyoutube-dlを利用する情報を入力する

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる
#### OUTPUT TEMPLATE
Filesystem Options:  
の`-o, --output TEMPLATE`の詳細を述べている

`The basic usage is not to set any template arguments when downloading a single file, like in youtube-dl -o funny_video.flv "https://some/video".`  
→`基本的な使用法は、youtube-dl -o Funny_video.flv "https：// some / video"のように、単一のファイルをダウンロードするときにテンプレート引数を設定しないことです。`

**Comment by shava2C** [comment]
### ReadMe見ながら動かしてみる

#### FAQ
基本的な使い方はこの一文のみだった。
`Video URL contains an ampersand and I'm getting some strange output [1] 2839 or 'v' is not recognized as an internal or external command`

**Comment by shava2C** [comment]
[CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)

**Comment by shava2C** [comment]
### 整理
#### 15時までの目標  
フィードバックポイントを見つけたので、フィードバック文章を作成する

**Comment by shava2C** [comment]
### フィードバックポイント
#### 気持ちの整理
Window10で、README.mdを見ながらyoutube-dlの操作を実行したが、以下で使いずらさを感じた。  

* usageが存在しないため、「とりあえず使ってみる」ができない
```
INSTALLATION
DESCRIPTION
OPTIONS
CONFIGURATION
OUTPUT TEMPLATE
FORMAT SELECTION
VIDEO SELECTION
FAQ
DEVELOPER INSTRUCTIONS
EMBEDDING YOUTUBE-DL
BUGS
COPYRIGHT
```

**Comment by shava2C** [comment]
> ### フィードバックポイント
> #### 気持ちの整理
> Window10で、README.mdを見ながらyoutube-dlの操作を実行したが、以下で使いずらさを感じた。
> 
> * usageが存在しないため、「とりあえず使ってみる」ができない。
>   以下がREADME.mdの目次
> 
> ```
> INSTALLATION
> DESCRIPTION
> OPTIONS
> CONFIGURATION
> OUTPUT TEMPLATE
> FORMAT SELECTION
> VIDEO SELECTION
> FAQ
> DEVELOPER INSTRUCTIONS
> EMBEDDING YOUTUBE-DL
> BUGS
> COPYRIGHT
> ```

usageに書く内容としては、[ここ](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)の一文が適切なのではないかと考えている。

```
For example if your URL is https://www.youtube.com/watch?t=4&v=BaW_jenozKc you should end up with following command:

youtube-dl 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'

or

youtube-dl https://www.youtube.com/watch?t=4\&v=BaW_jenozKc

For Windows you have to use the double quotes:

youtube-dl "https://www.youtube.com/watch?t=4&v=BaW_jenozKc"
```

**Comment by shava2C** [comment]
CONTRIBUTING.mdを読むために、おごもりさんが使用していた、「translation anywhere」をインストールする

**Comment by shava2C** [comment]
### [CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)の文章読解

`Please include the full output of youtube-dl when run with -v, i.e. add -v flag to your command line, copy the whole output and post it in the issue body wrapped in ``` for better formatting. It should look similar to this:`  
→CONTRIBUTION時には、オプション「-v」をつけろと言っている？

**Comment by shava2C** [comment]
### [CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)の文章読解
* 出力されるログは、スクリーンショットはNG

**Comment by shava2C** [comment]
> ### [CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)の文章読解
> `` Please include the full output of youtube-dl when run with -v, i.e. add -v flag to your command line, copy the whole output and post it in the issue body wrapped in ``` for better formatting. It should look similar to this: ``
> →CONTRIBUTION時には、オプション「-v」をつけろと言っている？

おごもりさんの回答
→ユーザーのバージョン管理を把握るために、issueに[オプション　ーｖ]を使用した、情報を載せてほしいという記載  
今回の場合、以下になるという想定  

```
 .\youtube-dl -v                                                
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]
```

* [ ] [おごもり](https://github.com/ogom)さんに上記を確認していただく

**Comment by ogom** [comment]
> ユーザーのバージョン管理を把握るために、issueに[オプション　ーｖ]を使用した、情報を載せてほしいという記載

この通りです。

**Comment by shava2C** [comment]
### [CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)の文章読解  
以下の観点が記載されていた。issueを上げる前の観点として活用
* 問題自体の説明で十分ですか？
* 最新バージョンを使用していますか？
* 問題はすでに文書化されていますか？
* 既存のオプションでは不十分なのはなぜですか？
* グレポートに十分なコンテキストがありますか？
* 問題には1つの問題が含まれ、1つの問題のみが含まれますか？
* 誰かがこの機能を必要としますか？
* youtube-dlについての質問ですか？

**Comment by shava2C** [comment]
### [CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)の文章読解  
#### DEVELOPER INSTRUCTIONSまわり
今回は、README.mdの修正なので、編集の必要なし。

**Comment by shava2C** [comment]
> ### [CONTRIBUTING.md](https://github.com/ytdl-org/youtube-dl/blob/master/CONTRIBUTING.md)の文章読解
> 以下の観点が記載されていた。issueを上げる前の観点として活用
> 
> * 問題自体の説明で十分ですか？
> * 最新バージョンを使用していますか？
> * 問題はすでに文書化されていますか？
> * 既存のオプションでは不十分なのはなぜですか？
> * グレポートに十分なコンテキストがありますか？
> * 問題には1つの問題が含まれ、1つの問題のみが含まれますか？
> * 誰かがこの機能を必要としますか？
> * youtube-dlについての質問ですか？

> * 問題はすでに文書化されていますか？
ここを調べておく。

**Comment by nekomatu** [comment]
> Window10で、README.mdを見ながらyoutube-dlの操作を実行したが、以下で使いずらさを感じた。

もう少し補足すると、DESCRIPTIONにある説明書きだけではパッと使えなかったという感じでしょうか。
多機能なため、USAGEの章を作ってしまうと、結局オプションてんこ盛りの何かになってしまうかも。（似た内容が重複してるだけになってしまう）

DESCRIPTIONのところに example として1行足すとかもあるかと。

**Comment by shava2C** [comment]
> > Window10で、README.mdを見ながらyoutube-dlの操作を実行したが、以下で使いずらさを感じた。
> DESCRIPTIONのところに example として1行足すとかもあるかと。

確かにそうですね。
使い方としては、とてもシンプルなので、1行追加追加するだけに変更します。

**Comment by shava2C** [comment]
### やる作業の整理
* CONTRIBUTING.mdの文章読解  
→現状問題ない。issue作成時に確認する
* 改修方針の検討
→nekomatuさんの指摘を踏まえて、修正案を検討

**Comment by shava2C** [comment]
### issue作成

[**Feature request**](https://github.com/ytdl-org/youtube-dl/issues/new?assignees=&labels=request&template=5_feature_request.md&title=)のテンプレートを使用する  
→issueの書き方難しい、、、、  
名に書けばいいのやら、、、

**Comment by ogom** [comment]
どんな内容を提案したいか日本語で書きましょう。

**Comment by shava2C** [comment]
### issue作成
必須入力以外は日本語で書いて確認してもらう。

日本語部分
作成中

英語部分
* version 
```
youtube-dl -v                                                
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]
```
- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
- [x] I've searched the bugtracker for similar feature requests including closed ones

**Comment by shava2C** [comment]
> ### issue作成
> 必須入力以外は日本語で書いて確認してもらう。
> 
> 日本語部分
> 作成中

私は、youtube-dlを日々使用しています。素晴らしいツールです！
今回READMEを見ながら、youtube-dlを動作させようと思いましたが、「とりあえず使ってみる」ための記載が存在しませんでした。
私の認識では、[FAQの内容](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)の内容が適切なのではないかと考えています。
なので、機能リクエストとして以下を検討しました。
1. USAGEの章を追加して、使い方を明示的に説明する
2. DESCRIPTIONの章に例`youtube-dl 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc'`を追加する

上記の2つの中で記載の重複が少なくなるためNo.2を機能リクエストしました。

**Comment by nekomatu** [comment]
>  私の認識では、[FAQの内容](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)の内容が適切なのではないかと考えています。

FAQはあくまでも変数展開が働いて初心者ユーザーが意図しない動きになる　というものです。
受け手はURLを引数に与えるだけなのになんでサンプルが必要なんだー？シンプルさが損なわれる！（＝変数展開を防ぐためにクオートでくくるのは常識なのでサンプルの必要性に全く気付いていない）と思ってしまう可能性ありです。

したがって…
「とりあえず使ってみる」ことは意外に簡単ではありません。FAQにある通りクオートでくくるなどが必要です。そのため、1行の簡単なサンプルを追記することを提案します。これはコマンドライン初心者がトラップに落ちることを防ぎます

といったように説明を省かないことをお勧めします。

**Comment by nekomatu** [comment]
タイトルも考えてみましょう～。

**Comment by shava2C** [comment]
> > 私の認識では、[FAQの内容](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)の内容が適切なのではないかと考えています。
> 
> FAQはあくまでも変数展開が働いて初心者ユーザーが意図しない動きになる　というものです。
> 受け手はURLを引数に与えるだけなのになんでサンプルが必要なんだー？シンプルさが損なわれる！（＝変数展開を防ぐためにクオートでくくるのは常識なのでサンプルの必要性に全く気付いていない）と思ってしまう可能性ありです。
> 
> したがって…
> 「とりあえず使ってみる」ことは意外に簡単ではありません。FAQにある通りクオートでくくるなどが必要です。そのため、1行の簡単なサンプルを追記することを提案します。これはコマンドライン初心者がトラップに落ちることを防ぎます
> 
> といったように説明を省かないことをお勧めします。

なるほど、これが[スライドP45](https://slide.rabbit-shocker.org/authors/oss-gate/workshop-tutorial/)あたりの省略しないってことになるんですね。

**Comment by shava2C** [comment]
### issue作成

#### Title

Modifying the README for beginner usability.  


#### Suggestion

I use youtube-dl every day. Great tool!  
I want beginners to use youtube-dl smoothly.  
Therefore, I suggest adding a simple one-line sample.   
This prevents command line beginners from falling into traps.   
Specifically, I think that the content of the FAQ is appropriate.

#### version

```
youtube-dl -v                                                
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.01.24.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]
```

* [x] I'm reporting a feature request
* [x] I've verified that I'm running youtube-dl version **2021.01.24.1**
* [x] I've searched the bugtracker for similar feature requests including closed ones

**Comment by shava2C** [comment]
> ### issue作成
> #### Title
> Modifying the README for beginner usability.
> 
> #### Suggestion
> I use youtube-dl every day. Great tool!
> I want beginners to use youtube-dl smoothly.
> Therefore, I suggest adding a simple one-line sample.
> This prevents command line beginners from falling into traps.
> Specifically, I think that the content of the FAQ is appropriate.
> 
> #### version
> ```
> youtube-dl -v                                                
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v']
> [debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
> [debug] youtube-dl version 2021.01.24.1
> [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
> [debug] exe versions: none
> [debug] Proxy map: {}
> Usage: youtube-dl.exe [OPTIONS] URL [URL...]
> ```
> 
> * [x]  I'm reporting a feature request
> * [x]  I've verified that I'm running youtube-dl version **2021.01.24.1**
> * [x]  I've searched the bugtracker for similar feature requests including closed ones

指摘
* 「beginner」の記載はいらない。
* 最初にリンクの参照を提案する。
* タイトルで何をしてほしいか、文頭にリンクを記載することで理解させる。
* タイトルに「FAQの内容をReadMEに記載しませんか？」に変更する

**Comment by shava2C** [comment]
### issueのレビュー取り込み実行
いろいろ思考がゴチャついているので、思考を整理する。

**Comment by shava2C** [comment]
### issueの修正後
日本語で書いてみた

#### タイトル

READMEのDESCRIPTIONに1行の簡単なサンプルを追記する

#### 内容

Great tool!
初心者がこのツールを簡単に使えるように[FAQ](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)のようなサンプルコードを追加することを提案します。

私は、READMEを見ながらyoutube-dlを動作させようと思いましたが、「とりあえず使ってみる」ための記載が存在しませんでした。
初心者の私にとって、「とりあえず使ってみる」ことは意外に簡単ではありません。FAQにある通りクオートでくくるなどが必要です。そのため、1行の簡単なサンプルを追記することを提案します。これはコマンドライン初心者がトラップに落ちることを防ぎます。

**Comment by shava2C** [comment]
youtube-DLでほかの方のissueを見てみる

**Comment by shava2C** [comment]
> youtube-DLでほかの方のissueを見てみる

2章立てっぽい
* Checklist
* Description
[参考](https://github.com/ytdl-org/youtube-dl/issues)

流は以下の通りっぽい
1. issueを出す
2. folkしてブランチを切る（割とブランチ名は適当っぽい）
3. プルリクを出す

**Comment by shava2C** [comment]
issueを登録

https://github.com/ytdl-org/youtube-dl/issues/28034

**Comment by shava2C** [comment]
issueを登録

本issueと紐づけられてしまった。
