### ISSUE TITLE
OSS Gate Workshop: online: 2021-03-13: thekiai Airflow Work log

### ISSUE THREAD

**Issue by thekiai** [oss-gate/workshop#1452]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by thekiai** [comment]
googleでairflow breezeと検索すると以下のページが見つかった
https://github.com/apache/airflow/blob/master/BREEZE.rst

ライセンスをこのページで確認
https://github.com/apache/airflow/blob/master/LICENSE
Apache License 2.0と書いてあった

https://opensource.org/licenses/alphabetical
にApache License 2.0があるのでOSSであることがわかった

**Comment by thekiai** [comment]
Prerequisites
のところを頭から見ると以下のコマンドが書かれていた
brew install gnu-getopt coreutils

インスールできた

以下のコマンドを実行
echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zprofile
. ~/.zprofile

再ログインしてと書いてあったので、teminalのタブを開いた

これでいいのか確認する方法がなくて不安

**Comment by thekiai** [comment]
メモリが４GB必要でdocker for macのデフォルトのメモリが2GBなので、dockerの設定からメモリを４GBに増やした

**Comment by thekiai** [comment]
Cleaning the environment
のところで
Stop Breeze with ./breeze stop
と書いてあり、なんのことか分からない

**Comment by thekiai** [comment]
docker system prune
を実行してdockerの環境を新しくしようとした

確認として
docker images --all
を実行したら、まだimageが残っていた

全てのイメージに対して
docker image rm イメージ名
を実行して全てのイメージを削除した

13:52:21:~ % docker images --all
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
docker101tutorial           latest    b68b0f293fb0   2 hours ago   27.9MB
thekiai/docker101tutorial   latest    b68b0f293fb0   2 hours ago   27.9MB
alpine/git                  latest    a939554ad0d0   3 weeks ago   25.1MB
13:52:46:~ % docker images rm docker101tutorial
"docker images" requires at most 1 argument.
See 'docker images --help'.

Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
13:56:06:~ % docker images --all               
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
thekiai/docker101tutorial   latest    b68b0f293fb0   2 hours ago   27.9MB
docker101tutorial           latest    b68b0f293fb0   2 hours ago   27.9MB
alpine/git                  latest    a939554ad0d0   3 weeks ago   25.1MB
13:56:09:~ % docker image rm docker101tutorial 
Untagged: docker101tutorial:latest
13:56:24:~ % docker images --all              
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
thekiai/docker101tutorial   latest    b68b0f293fb0   2 hours ago   27.9MB
alpine/git                  latest    a939554ad0d0   3 weeks ago   25.1MB
13:56:31:~ % docker images --all              
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
thekiai/docker101tutorial   latest    b68b0f293fb0   2 hours ago   27.9MB
alpine/git                  latest    a939554ad0d0   3 weeks ago   25.1MB
13:57:23:~ % docker image rm thekiai/docker101tutorial
Untagged: thekiai/docker101tutorial:latest
Untagged: thekiai/docker101tutorial@sha256:8e34bd3442b51c65eddbec09cd5a31ebdb0c423b09a2f1a3097da17f9e7421c7
Deleted: sha256:b68b0f293fb0094b553f23823c8a48093c34584f48cc65d2b953baf3c91bcd81
13:57:43:~ % docker image rm alpine/git                
Untagged: alpine/git:latest
Untagged: alpine/git@sha256:1eb7b41cd5226ebe64d1636c4183fe3ddc60249960c48fbe9cde61ea044db18e
Deleted: sha256:a939554ad0d0aa24f892d4285670ccc886f341300219a60fc22bbc04973c4225
Deleted: sha256:502e2eecea2c80963f3c6a83938892904503567472d25a1ebbc38ee1bbc10128
Deleted: sha256:3d290ffbd8d0d070bd821cea0094d07c1e3c58e2fac087782ada3d579d6c9576
13:58:26:~ % docker images --all                      
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
13:58:29:~ %

**Comment by thekiai** [comment]
docker ps --all
を実行して空であることを確認した

**Comment by thekiai** [comment]
Installation is as easy as checking out Airflow repository and running Breeze command.
と書いてあり、git cloneだと解釈しairflowのリポジトリを以下のコマンドでクローンした

git clone git@github.com:apache/airflow.git

クローン後以下のコマンドを実行し
14:04:10:~ % cd airflow 
14:04:53:~/airflow % ./breeze

以下の出力を得た
./breeze: line 28: @: unbound variable

./breezeの２８行目にある${@}が古いbashだと使えないらしく、$@に変更すると上のエラーが治った

**Comment by thekiai** [comment]
To use the full potential of breeze you should set up autocomplete and you can add the checked-out Airflow repository to your PATH to run Breeze without the ./ and from any directory.
と書いてあるが、PATHの追加方法は記載がない。

export PATH=$HOME/airflow:$PATH
を~/.zshrcに追加し
. ~/.zshrc
を実行し
breezeと打てばどこからでも実行できるようにした
確認として
breeze --version
と実行し、PATHが通ってることを確認した

which breeze
で確認した方が安全と教えてもらった（PATHが通ったことの確認）

安全に確認できる何かしらのbreezeコマンドがドキュメントに書いてあると良さそう。

**Comment by thekiai** [comment]
echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zprofile
. ~/.zprofile
を実行した後に、ちゃんとPATHが通ってるかどうか確認用のコマンドがあると嬉しい

**Comment by thekiai** [comment]
**Description**
https://github.com/apache/airflow/blob/master/BREEZE.rst#id11

現状
echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zprofile
. ~/.zprofile
を実行した後に、特に何も説明がない

期待される結果
ちゃんとPATHが通ってるかどうか確認用のコマンドがある

**Use case / motivation**
シェルに詳しくないと、今のドキュメントだと、チェックポイントがないため、動かないまま進んでしまう可能性がある
gnu-getoptコマンドも詳しくなくて、分からないため、確認用コマンドがあると嬉しい



**Are you willing to submit a PR?**
Yes

**Comment by thekiai** [comment]
**Description**
このドキュメントに沿ってBreezeを動かしてみて、Getopt and gstatのセクションのドキュメントで分かりづらかった。
https://github.com/apache/airflow/blob/master/BREEZE.rst#getopt-and-gstat

Actual
After executing the following commands quoted from https://github.com/apache/airflow/blob/master/BREEZE.rst#getopt-and-gstat, I cannot know that the commads enabled the PATH properly.
```
echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.zprofile
. ~/.zprofile
```

Exepected
It's better to write commands for checking that `getopt` and `gstat` are succesfully installed.
```
$ getopt --version
getopt from util-linux 2.36.2
$ gstat --version
stat (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Michael Meskes.
```

Use case / motivation
Because I'm not familiar with unix shell, with the exisiting document, I couldn't know those commands are properly installed or not.

Are you willing to submit a PR?
Yes, I'm ready.

**Comment by komagata** [comment]
Issueの内容は開発者では気付きづらい、実際にユーザーとして動かした人ならではの内容でいいと思います！
またPRまで送れたのがとっても良かったですし、表現を何度も修正してより伝わりやすいものにしていたのも素晴らしいと思いました。
