### ISSUE TITLE
OSS Gate Workshop: ONLINE: 2021-04-24: cat_3582: rubocop: Work log

### ISSUE THREAD

**Issue by 3582** [oss-gate/workshop#1465]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 3582** [comment]
rubocopがOSSか調べる
https://github.com/rubocop

**Comment by 3582** [comment]
MITライセンスであることを確認
https://github.com/rubocop/rubocop/blob/master/LICENSE.txt

**Comment by 3582** [comment]
rubocopをインストール
READMEのinstallationを見ながら実施
https://github.com/rubocop/rubocop#installation

**Comment by 3582** [comment]
rubocopを実行
quickstartを見ながら実施
https://github.com/rubocop/rubocop#quickstart
下文章から、my/cool/ruby/projectが作成されると勘違い
$ cd my/cool/ruby/project

自分のrailsアプリにて実行してみた
$ rubocop

**Comment by 3582** [comment]
自分のプロジェクトがrailsのためrubocop-railsのインストールを実施
https://github.com/rubocop/rubocop-rails#installation

rubocopの設定ファイル.rubocop.ymlへの記載忘れにより一度実行を失敗する
https://github.com/rubocop/rubocop-rails#rubocop-configuration-file

rubocop実行結果
62 files inspected, 160 offenses detected, 134 offenses auto-correctable
rubocop-railsの実行結果
56 files inspected, 109 offenses detected, 78 offenses auto-correctable

**Comment by ogom** [comment]
サポートメンターです。

**Comment by hata6502** [comment]
サポートです。

**Comment by 3582** [comment]
午前を終えて
・rubocopのquickstart
my/cool/ruby/projectがインストールで作成されると勘違い
・rubocopでrailsも対応できると考えてしまう
rubocopのREADMEにrubocop-railsへのリポジトリへのリンクを貼った方が親切かも？

**Comment by 3582** [comment]
・rubocopのquickstart
my/cool/ruby/projectがインストールで作成されると勘違い

READMEをblameで確認したところ、5年前から変更が加えれらていない。
そのため特に問題視されていないこと、表現にこだわりがありそうだと判断

・rubocopでrailsも対応できると考えてしまう
rubocopのREADMEにrubocop-railsへのリポジトリへのリンクを貼った方が親切かも？

READMEのUsageに各拡張機能へのリンクも追加するよう提案（Issue）
https://github.com/rubocop/rubocop-rspec#usage

**Comment by 3582** [comment]
rubocopのドキュメントに拡張機能へのリンクを追加するよう提案することに決定
・Next Stepsにはリンクがあるが文中には存在しないため（該当箇所：A vast number of ready-made extensions）
https://docs.rubocop.org/rubocop/1.13/index.html

**Comment by 3582** [comment]
以下の変更を加える（git diff結果）

--- a/docs/modules/ROOT/pages/index.adoc
+++ b/docs/modules/ROOT/pages/index.adoc
@@ -22,7 +22,8 @@ linter:
 * Ability to disable certain cops only for specific files or parts of files
 * Extremely flexible configuration that allows you to adapt RuboCop to pretty much every style and preference
 * It's easy to extend RuboCop with custom cops and formatters
-* A vast number of ready-made extensions (e.g. `rubocop-rails`, `rubocop-rspec`, `rubocop-performance` and `rubocop-minitest`)
+* A vast number of ready-made xref:extensions.adoc[extensions] (e.g. `rubocop-rails`, `rubocop-rspec`, `rubocop-performance` and `rubocop-minitest`)
+
 * Wide editor/IDE support
 * Many online services use RuboCop internally (e.g. HoundCI, Sider and CodeClimate)
 * Best logo/stickers ever

**Comment by 3582** [comment]
ドキュメントのPRのルールを確認
https://github.com/rubocop/rubocop/pull/4827

**Comment by 3582** [comment]
**Replace this text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following are checked:

* [ ] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

**Comment by 3582** [comment]
下記文章にてPRを実行
・The "Extension" link is attached in the "Next Step" text.
・I suggested adding a link in "extensions" in the "Overview" text.
・「拡張」リンクは「次のステップ」のテキストに添付されています。
・「概要」テキストの「拡張子」にリンクを追加することを提案しました。

**Comment by 3582** [comment]
CIが無事に通りマージされたみたいです
https://github.com/rubocop/rubocop/pull/9735
