### ISSUE TITLE
OSS Gate Workshop: online: 2021-04-24: hata6502: prh/prh: Work log

### ISSUE THREAD

**Issue by hata6502** [oss-gate/workshop#1466]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hata6502** [comment]
- [ ] 目的
- [ ] ライセンスの確認
- [ ] ユーザーとして使ってみる

**Comment by ogom** [comment]
サポーターです。

**Comment by hata6502** [comment]
**ライセンスの確認**

prh のライセンスファイル (LICENSE) はない。
`package.json` に `license: MIT` の表記あり。
`package.json` に基づき、npm のサイトではライセンスの表記がある。

![Screenshot from 2021-04-24 14-02-20](https://user-images.githubusercontent.com/7702653/115947908-bc72ed00-a505-11eb-84c3-1dcb00bc6985.png)

**Comment by hata6502** [comment]
**ユーザーとして使ってみる**

[インストール方法](https://github.com/prh/prh#%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB)には、以下の２とおりが書かれている。

- 自分のライブラリに組み込んで使う場合。
- コマンドラインツールとして使う場合。

コマンドラインツールとして使うため、

```bash
hata6502@yoga:~$ mkdir test-project
hata6502@yoga:~$ cd test-project/
hata6502@yoga:~/test-project$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test-project) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /home/hata6502/test-project/package.json:

{
  "name": "test-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) yes
hata6502@yoga:~/test-project$ npm install --save prh

added 7 packages, and audited 8 packages in 2s

found 0 vulnerabilities

```

**Comment by hata6502** [comment]
コマンドラインツールとして使う場合の API ドキュメントが存在しない模様。
ソースコードを読む！

[index.js](https://github.com/prh/prh/blob/master/index.js)
↓
[lib/index.ts](https://github.com/prh/prh/blob/master/lib/index.ts)

に、エクスポートされた API が載っている。

**Comment by hata6502** [comment]
`prh` は、実はブラウザでも動かすことができる。
ブラウザで動かす場合は、直接 `prhEngine` を使える。

すでに azu さんが issue を書いていた。
https://github.com/prh/prh/issues/29

**Comment by hata6502** [comment]
個人のプロジェクトや textlint-editor で動かすことができない textlint plugin は、
`prh` を修正するのではなく、`prh` の使い方を修正する必要がある。
つまり、textlint plugin を fork する必要あり。

**Comment by hata6502** [comment]
**フィードバック**

- .vscode ってリポジトリに含めるのかな。
  - 間違えてコミットしてる？　https://github.com/prh/prh/tree/master/.vscode
- LICENSE ファイルがない。
  - 一応 `package.json` にはライセンスが書いてある。
  - GitHub としては、`package.json` からライセンスを自動判定できないようだ。
- API ドキュメントが存在しない。

**Comment by hata6502** [comment]
**ピックアップ**
LICENSE ファイルがない。

**Comment by hata6502** [comment]
https://github.com/hata6502/prh/blob/master/package.json#L22
https://github.com/vvakame/typescript-formatter/blob/master/LICENSE.txt#L2

**Comment by hata6502** [comment]
Issue 下書き

title: 
LICENSE ファイルを設置する

description:

**Comment by hata6502** [comment]
https://github.com/prh/prh/issues/43
