### ISSUE TITLE
OSS Gate Workshop: online: 2021-6-12: ayaka-ramens: zenkaku: Work log

### ISSUE THREAD

**Issue by ayaka-ramens** [oss-gate/workshop#1475]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ayaka-ramens** [comment]
https://marketplace.visualstudio.com/items?itemName=mosapride.zenkaku
これを使ってみる

**Comment by ayaka-ramens** [comment]
ライセンス `MIT` と記載があった。

**Comment by ayaka-ramens** [comment]
既に使っているのでアンインストールする

**Comment by ayaka-ramens** [comment]
アンインストールボタンを押す
VSCode再読み込みが必要とのことで、再読み込みボタンが表示され再読み込みした

3行目の全角スペース入力の場合も表示が変わらない(アンインストールできている)
![スクリーンショット 2021-06-12 13 55 46](https://user-images.githubusercontent.com/52645663/121765460-ed76b200-cb85-11eb-8bed-5354eea25e4a.png)

**Comment by ayaka-ramens** [comment]
インストールする
[githubのREADME](https://github.com/mosapride/vscode-zenkaku) にはインストールのことは書かれていない

**Comment by ayaka-ramens** [comment]
https://marketplace.visualstudio.com/items?itemName=mosapride.zenkaku のInstallボタンをクリック
ポップアップが表示され、VisualStudioCodeを開きますか?というポップアップが表示され、VisualStudioCodeを開くボタンをクリックするとVSCodeの以下ページが表示される
![スクリーンショット 2021-06-12 14 05 23](https://user-images.githubusercontent.com/52645663/121765636-53b00480-cb87-11eb-8578-2d2b60cebfba.png)

**Comment by ayaka-ramens** [comment]
VSCodeを再起動したら、インストールされていた

![スクリーンショット 2021-06-12 14 13 41](https://user-images.githubusercontent.com/52645663/121765770-6a0a9000-cb88-11eb-87e9-255908ea91fd.png)

**Comment by ayaka-ramens** [comment]
次はvscode-gemfileを試してみる
https://marketplace.visualstudio.com/items?itemName=bung87.vscode-gemfile

**Comment by ayaka-ramens** [comment]
ライセンス
[リポジトリ](https://github.com/bung87/vscode-gemfile) にMITと記載があった
![スクリーンショット 2021-06-12 14 28 25](https://user-images.githubusercontent.com/52645663/121766089-8c051200-cb8a-11eb-867c-20c81be7a199.png)

**Comment by ayaka-ramens** [comment]
こちらもインストール済みなのでアンインストールする

**Comment by ayaka-ramens** [comment]
アンインストールボタンを押してみると以下のエラーが表示された
![スクリーンショット 2021-06-12 14 30 53](https://user-images.githubusercontent.com/52645663/121766133-d71f2500-cb8a-11eb-9107-87edbce51a8f.png)

**Comment by ayaka-ramens** [comment]
[rails](https://marketplace.visualstudio.com/items?itemName=bung87.rails) をアンインストールしてみる

**Comment by ayaka-ramens** [comment]
アンインストールできた
![スクリーンショット 2021-06-12 14 40 30](https://user-images.githubusercontent.com/52645663/121766361-29ad1100-cb8c-11eb-8357-c218d4772021.png)

**Comment by ayaka-ramens** [comment]
インストール
Gemfileのgem名をクリックするとリンクが表示される
![スクリーンショット 2021-06-12 14 47 42](https://user-images.githubusercontent.com/52645663/121766504-32eaad80-cb8d-11eb-9a6b-979334d95786.png)

**Comment by piroor** [comment]
逆にサポーターの環境では、インストールしても期待通りに動かない結果に……

**Comment by piroor** [comment]
zenkakuは再起動不要にはならないのだろうか？
vscode-gemfileは再起動を促すメッセージや案内はあっただろうか？

**Comment by ayaka-ramens** [comment]
## 再現手順 steps to reproduce
- バージョン情報
  - VScodeバージョン: 1.56.2
  - zenkaku  v0.0.3
  - OS macOS Catalina 10.15.7
  - (TODO: 他の拡張機能も書く)
- 手順
  - 1. VScodeを起動
  - 2. zenkakuをインストール
  - 3. テスト用にファイル(test.txt)を作成し、入力した
    - TODO: ファイルパスも書く

```
a あ　あ
```

  - 4. 全角スペースの場合でも強調表示されなかった
  - 5. VScodeを終了して起動した
  - 6. ファイルを開きなおした
  - 7. 全角スペースの箇所が強調表示された

## 期待される結果 expected result
- 手順4で強調表示される

## 実際の結果 actual result
- VScodeを終了し起動し直さなければ、強調表示されなかった

**Comment by ayaka-ramens** [comment]
issue: https://github.com/mosapride/vscode-zenkaku/issues/1
