### ISSUE TITLE
OSS Gate Workshop: Online: 2021-07-31: kjyn: Vue.js: Work log

### ISSUE THREAD

**Issue by kjyn** [oss-gate/workshop#1480]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ogom** [comment]
サポーターです。よろしくお願いします。

**Comment by KajikawaHaruki** [comment]
Vue.jsのライセンスを調べる

**Comment by KajikawaHaruki** [comment]
Vue.jsのライセンスを調べた
MIT License

**Comment by KajikawaHaruki** [comment]
MIT Licenseはオープンライセンスであった

**Comment by KajikawaHaruki** [comment]
参照元
https://jp.vuejs.org/support-vuejs/index.html

**Comment by KajikawaHaruki** [comment]
CDNを使用（最新のバージョン　2.6.14）
https://jp.vuejs.org/v2/guide/installation.html#CDN

**Comment by KajikawaHaruki** [comment]
バージョンの確認方法
GithubのReleaseページを確認
https://github.com/vuejs/vue/releases

**Comment by KajikawaHaruki** [comment]
「はじめに」をやってみた
https://jp.vuejs.org/v2/guide/index.html

・宣言的レンダリング
Scrimbaレッスン
https://scrimba.com/scrim/cQ3QVcr?pl=pXKqta

**Comment by KajikawaHaruki** [comment]
「はじめに」の「#appのメッセージを変えてみよう」をやってみた
しかし値が変わらなかった

**Comment by KajikawaHaruki** [comment]
「#appのメッセージを変えてみよう」
messageタグの属性を動的に変更する方法にて、Scrimbaを用いると変更後のHTMLの内容を確認できないため、初心者だと勘違いしてしまう可能性がある。
（ローカル環境に.htmlと.jsを作成して実施したところ、正常に動作することを確認できた。）

**Comment by KajikawaHaruki** [comment]
Vue.jsバージョンの違い
2.x系は開発が落ち着いており、3.x系の開発が主流になっているため、ドキュメントも3.x系を参照すること
https://v3.ja.vuejs.org/guide/introduction.html

3.x系の日本語ドキュメントGitHub
https://github.com/vuejs-jp/jp.vuejs.org

**Comment by KajikawaHaruki** [comment]
ドキュメントへの提言
束縛（バインディング）-> バインド

**Comment by KajikawaHaruki** [comment]
ドキュメントへの提言
リアクティブ（反応的） -> リアクティブ（再活性）

束縛（バインディング）との表記法の揺れを統一してほしい

**Comment by ogom** [comment]
https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/introduction.md

**Comment by KajikawaHaruki** [comment]
`束縛（バインディング）`は、`リアクティブ（反応的）`の記述と同じように`バインド（束縛）`とする方が読みやすいです。

そのため、`In addition to text interpolation, we can also bind element attributes like this:`の原文を`文字列の展開に加えて、以下のように要素の属性をバインド（束縛）することもできます:`とすると良いかもしれません。

https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/src/guide/introduction.md

**Comment by KajikawaHaruki** [comment]
PR提出済み
https://github.com/vuejs-jp/ja.vuejs.org/pull/462
