### ISSUE TITLE
OSS Gateオンラインワークショップ2022-01-29

### ISSUE THREAD

**Issue by ogom** [oss-gate/workshop#1488]
## 開催内容

- [イベントページ](https://oss-gate.doorkeeper.jp/events/125414)
- 会場: 
- 時間: 2022-01-29T10:30/17:00 
- 会場係: @
- 進行役: @daipom
- このイベントに関する窓口: @

## やること

- [x] Doorkeeperのイベントページ作成（開催の1ヶ月前までにやる・要管理権限）
- タイムライン、メッセージ送信予定（要管理権限）
  - 開催1ヵ月前（2021-12-29）
    - [x] 進行役決定
    - [ ] 窓口決定（オフライン開催の場合）
    - [ ] 会場決定（オフライン開催の場合）
    - [x] イベント未登録者向け：[サポーター募集文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_supporter_invitation.md)
  - 開催2週間前（2022-01-15）
    - [x] 参加者、キャンセル待ち向け：[不参加の場合のキャンセルを呼びかける文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_reminder_before_2_weeks.md)
    - [x] イベント未登録者向け：[イベント告知、サポーター募集文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_supporter_invitation_before_2_weeks.md)
    - [ ] イベント未登録者向け：[前半枠のみサポーター募集の場合の文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_supporter_invitation_only_first_half.md)
    - [ ] イベント未登録者向け：[後半枠のみサポーター募集の場合の文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_supporter_invitation_only_second_half.md)
  - 開催1週間前（2022-01-22）
    - [x] [ビギナーの繰り上がり](https://oss-gate.github.io/workshop/beginner-preferential-treatment.html)処理
    - [x] 参加者、キャンセル待ち向け：[不参加の場合のキャンセルを呼びかける文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_reminder_before_1_week.md)
    - [x] 参加者向け：[Discord招待URLの通知用文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_discord_url.md)（オンライン開催の場合）
  - 開催3日前（2022-01-26）
    - [ ] 参加者、キャンセル待ち向け：[サポーター不足による中止を伝える文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_canceled.md)）
    - [ ] 参加者向け：[場案内の通知用文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_location.md)（オフライン開催の場合）
  - 開催1日前（2022-01-28）
    - [ ] 参加者、キャンセル待ち向け：[サポーター不足による中止を伝える文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_canceled.md)）
    - [ ] 参加者向け：[会場案内の通知用文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_location_reminder.md)（オフライン開催の場合）
    - [x] 参加者向け：[Discord招待URLの通知用文面](https://github.com/oss-gate/workshop/raw/master/template/workshop_discord_url_reminder.md)（オンライン開催の場合）
    - [x] `tutorial/retrospectives/prepare.rb` を実行してアンケートのテンプレートを追加する（ #1337 ）（要コミット権）
- [ ] 4回分先までのDoorkeeperイベントページの作成（要管理権限）
  1. [イベントリスト](https://manage.doorkeeper.jp/groups/oss-gate/events)を開く。
  2. 「1月と4月と7月と10月は最終土曜日に10:30から17:00で開催」「3月と6月と9月と12月は第2土曜日に13:00から19:00で開催」のルールに従い、同じ開催時刻の未開催イベントまたは過去イベントから「コピーして新規イベント作成」を実行する。
  3. 2のルールに従って開催日を変更する。
  4. 開催日をイベントタイトルに反映する。
  5. ビギナー人数を0に変更する。
  6. イベントを作成する。
  7. イベントに対応するワークショップ準備用issueを作成する。

**Comment by piroor** [comment]
進行役未定ですが、一旦サポーター募集の告知のみメッセージを送信しました。

**Comment by daipom** [comment]
進行役やります。

**Comment by piroor** [comment]
今回 @daipom さんが初めて進行役をされるので、負担軽減のために、ビギナー枠の計算式の「サポーター×2」のサポーター人数は敢えて-1で計算したいと思います！

**Comment by piroor** [comment]
https://narikakun.net/matome/discord-musicbot/ 休憩時間などにBGMを流すとよいのではという話が出ていた
