### ISSUE TITLE
OSS Gate Workshop: online:2021-10-30: tsutsuji86: YamlDotNet: Work log

### ISSUE THREAD

**Issue by tsutsuji86** [oss-gate/workshop#1493]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tsutsuji86** [comment]
YamlDotNeetをやってみようと思います。
https://github.com/aaubry/YamlDotNet
YamlDotNet is a .NET library for YAML 

上記ページのフッターにMIT Licensedと書かれている。
https://github.com/aaubry/YamlDotNet/blob/master/LICENSE.txt
の中に「MIT License」があるので、これはOSSと思われる。

**Comment by tsutsuji86** [comment]
https://github.com/aaubry/YamlDotNet/wiki/Samples
にあるSampleを実行してみます。

**Comment by hata6502** [comment]
YamlDotNet にはライセンスファイルが２つあるようです。

- LICENSE-libyaml
- LICENSE.txt

念の為 LICENSE-libyaml についても調査すると、安心できそうです。

**Comment by tsutsuji86** [comment]
まずはこちらのサンプルを試してみる。
https://github.com/aaubry/YamlDotNet/wiki/Samples.LoadingAYamlStream

Visual Studio 2019 Communityで新規ソリューションYamlDotNetSampleを作成した。

そこに、C#コンソールの新規プロジェクトとして、Loading a YAML Streamを作成した。

**Comment by tsutsuji86** [comment]
https://github.com/aaubry/YamlDotNet/wiki

上記ページのInstallingには、パッケージマネージャーコンソールでのインストール方法
PM> Install-Package YamlDotNet
が書いてあるが、「NuGetパッケージの管理」を使って、参照から「YamlDotNet」を検索してインストールした。

**Comment by tsutsuji86** [comment]
ちなみに、https://github.com/aaubry/YamlDotNet/wiki/Samples
に掲載されているSampleのコードは、Xunitを介したコンソール出力の例になっており、
私はこれの使い方がよくわかっていないので、一般的なConsole.WriteLineを使う方法で試してみる。

**Comment by hata6502** [comment]
環境
Ubuntu: 20.04
node: 16.13.0
npm: 8.1.0

```bash
$ npm i -g @vue/cli
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm WARN deprecated graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead

added 944 packages, and audited 945 packages in 41s

65 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (4 moderate, 19 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

$ vue create my-project


Vue CLI v4.5.15
? Please pick a preset: Default ([Vue 2] babel, eslint)
? Pick the package manager to use when installing dependencies: NPM


Vue CLI v4.5.15
✨  Creating project in /home/hata6502/test/my-project.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...


added 1283 packages, and audited 1284 packages in 59s

83 packages are looking for funding
  run `npm fund` for details

43 vulnerabilities (18 moderate, 25 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
🚀  Invoking generators...
📦  Installing additional dependencies...


added 49 packages, and audited 1333 packages in 4s

88 packages are looking for funding
  run `npm fund` for details

45 vulnerabilities (20 moderate, 25 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project my-project.
👉  Get started with the following commands:

$ cd my-project
$ npm run serve

> my-project@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 1232ms                                                                                                                                     11:54:38


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.1.46:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

```

**Comment by piroor** [comment]
READMEのQuickstartの部分からリンクされている
https://dotnetfiddle.net/CQ7ZKi
を開いてみた。
どういう物かよく分かっていなかったが、ページを開いた時点でもう実行済みの状態になっているということらしい。
コードをリアルタイムで書き換えて「Run」を押すと、下のコンソールの出力内容が変化して、動いていることを確認できた。

**Comment by ttyniwa** [comment]
* 見つけた課題は二つ
  * リポジトリをクローンしてビルドしたらエラーが発生した
    * ライブラリ開発者がする行為なので、敷居は高い
    * でも、エラーが発生せずにコンパイルできたほうが貢献しやすいので、問題が解消できたら報告してあげると喜ばれます
  * wikiのサンプルコードがHelperクラスとXUnit(?)を利用しており、YamlDotNetをインストールしただけではコピペしても動作しない
    * XUnitは一般的なライブラリかもしれないのであったほうがよい可能性はありそう
    * Helperに定義された関数は非常にシンプルなラッパーなので、ないほうが良さそう
* 結論
  * Helperをなくしてもよいか

**Comment by tsutsuji86** [comment]
>     * リポジトリをクローンしてビルドしたらエラーが発生した
>       
>       * ライブラリ開発者がする行為なので、敷居は高い
>       * でも、エラーが発生せずにコンパイルできたほうが貢献しやすいので、問題が解消できたら報告してあげると喜ばれます

午後ちょっと試したところ、ビルドが通ってSampleのテストも実行することができた。
何がどうなってビルドできるようになったかを確認するため、
もう一度クローニングして再度チャレンジ中。

**Comment by tsutsuji86** [comment]
> wikiのサンプルコードがHelperクラスとXUnit(?)を利用しており、YamlDotNetをインストールしただけではコピペしても動作しない
> 
>     * XUnitは一般的なライブラリかもしれないのであったほうがよい可能性はありそう
> 
>     * Helperに定義された関数は非常にシンプルなラッパーなので、ないほうが良さそう

開発者の過去のブログをみると当時は、Console.WriteLineを使ったサンプルだった。
https://aaubry.net/pages/yamldotnet.html

**Comment by tsutsuji86** [comment]
> 
> 
> > ```
> > * リポジトリをクローンしてビルドしたらエラーが発生した
> >   
> >   * ライブラリ開発者がする行為なので、敷居は高い
> >   * でも、エラーが発生せずにコンパイルできたほうが貢献しやすいので、問題が解消できたら報告してあげると喜ばれます
> > ```
> 
> 午後ちょっと試したところ、ビルドが通ってSampleのテストも実行することができた。 何がどうなってビルドできるようになったかを確認するため、 もう一度クローニングして再度チャレンジ中。

どうやらGitHubからクローニングしてできるmasterブランチにあるソリューションファイルではビルドできず、
それよりちょっと進んでいるunity-compatibleブランチをクローニングするとビルドできるようになった。
この2つのブランチは、Unityに関する項目だけの違いのようであるが、
ビルド時に生成されるnetcoreapp3.1のyamlDotNet.dllあたりに問題あるのかも。

**Comment by tsutsuji86** [comment]
README.mdのQuick startにある.NET Fiddleへのリンク先に示されたコードは、
コピペするだけで実行できた。
これは「Serialization from an object to a string」と
「Deserialization from a string to an object」を含む完全な形のコードとなっている。

この例題では、出力に「System.Console.WriteLine();」が使われているので、わかりやすい。

**Comment by tsutsuji86** [comment]
対象OSS: YamlDotNet

Title: masterブランチではビルドできないが、unity-compatibleブランチだとビルドできる

# 再現手順
* OS：Windows 10 home
* ビルド環境：
  Microsoft Visual Studio Community 2019
  Version 16.10.3
* ビルド手順
  YamlDotNet.gitをクローニングしてできるmasterブランチ（コミット：baa5b66）のソリューションでビルドを行った。

# 実際に起ったこと
  YamlDotNet.gitをクローニングしてできるmasterブランチ（コミット：baa5b66）のソリューションでビルドすると、
  YamlDotNetプロジェクトでビルドエラーが発生する。
  
エラーメッセージ
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	CS0103	現在のコンテキストに 'RegexOptions' という名前は存在しません	YamlDotNet (netcoreapp3.1)	D:\Programming\OSS\YamlDotNet\YamlDotNet\Portability\unitysubset3.5\include\StandardRegexOptions.cs	28	アクティブ

  unity-compatibleブランチをチェックアウトした場合（コミット：b7d71ec）、
  問題なくビルドすることができた。
  
  もしかしたら、unityとの互換性を想定していないmasterブランチでunityに関連する機能を呼び出そうとしているのかもしれない。

# 期待される結果
masterブランチでも、unity-compatibleブランチと同様にビルドできるとよい。

**Comment by tsutsuji86** [comment]
> 
> 
> YamlDotNet にはライセンスファイルが２つあるようです。
> 
>     * LICENSE-libyaml
> 
>     * LICENSE.txt
> 
> 
> 念の為 LICENSE-libyaml についても調査すると、安心できそうです。

2つのファイルの違いは、著作権者の違いのようで、
内容的には同じみたいです。

* LICENSE-libyaml：Copyright (c) 2006 Kirill Simonov
* LICENSE.txt：Copyright (c) 2008, 2009, 2010, 2011, 2012, 2013, 2014 Antoine Aubry and contributors

**Comment by tsutsuji86** [comment]
対象OSS: YamlDotNet

Title: masterブランチではビルドできないが、unity-compatibleブランチだとビルドできる

# 再現手順
* OS：Windows 10 home
* ビルド環境：
  Microsoft Visual Studio Community 2019
  Version 16.10.3
* ビルド手順
  YamlDotNet.gitをクローニングしてできるmasterブランチ（コミット：baa5b66）のソリューションでビルドを行った。

# 実際に起ったこと
  YamlDotNet.gitをクローニングしてできるmasterブランチ（コミット：baa5b66）のソリューションでビルドすると、
  YamlDotNetプロジェクトでビルドエラーが発生する。
  
  unity-compatibleブランチをチェックアウトした場合（コミット：b7d71ec）、
  問題なくビルドすることができた。
  
2つのコミットを比較したところ、unity-compatibleブランチでは、BuildUtils.UnityPrerequisitesというフォルダにファイルが存在しているのに対して、masterブランチでは、ファイルが存在していないことが分かった。
そこで、unity-compatibleブランチのBuildUtils.UnityPrerequisitesの中身を、masterブランチにコピーしたところ、ビルドすることができた。

また、同様の現象として、masterブランチでは、ユニットテストの実行時にエラーが発生するが、
これは、YamlDotNet.Test\yaml-test-suiteフォルダの中身が不足していることが原因であった。

# 期待される結果
masterブランチでも、unity-compatibleブランチと同様にビルドでき、ユニットテストもすべてパスできるようになるとよい。

**Comment by tsutsuji86** [comment]
Target OSS: YAMLDOTNET

Title: Can not build in MASTER branch, but can be built with Unity-Compatible branch.

# Reproduction procedure
* OS: Windows 10 Home
* Build environment:
  Microsoft Visual Studio Community 2019
  Version 16.10.3
* Build procedure
  https://github.com was built with a Master branch (commit: BAA5B66) solution that can be clone/yamldotnet.git.

# What I happened actually
  When you build in the Solution of the Master branch (commit: BAA5B66) that can be cloned YAMLDOTNET.GIT,
  A build error occurs in the YAMLDOTNET project.
  
  If you checked out the Unity-Compatible branch (commit: B7D71EC),
  I was able to build without a problem.
  
Comparing two commits, it was found that the Unity-Compatible branch has a file in the folder called buildutils.unityPrerequisites, whereas the MASTER branch has not found that the file exists.
Therefore, it was possible to build the contents of the BuildUtils.UnityPrerequisites of the Unity-Compatible branch to the MASTER branch.

Also, as a similar phenomenon, the MASTER branch causes an error when the unit test is executed after the build passes through the above correction.
This was due to the lack of the contents of the YAMLDOTNET.TEST \ YAML-TEST-Suite folder.

# Expected results
MASTER branches may be built as well as Unity-Compatible branches, and all unit tests may be passed.

**Comment by yuseitahara** [comment]
細かいことなんですが、コメントします。

> Title: Can not build in MASTER branch, but can be built in Unity-Compatible branch.

能動態と受動態を混ぜる必要はないと思います、あとは build master branch でよくで in は要らないです。

あとは実際のブランチ名は小文字の master ですよね？それなら大文字にしなくていいです。

なので、

Title: I can not build master branch, but I can build unity-compatible branch.

でどうでしょうか。

> When I build with the solution file of the master branch that can be cloned from git,
A build error occurs in the YamlDotNet project.

もっと単純に書いていいと思います。あとcommitのhash値が大文字で書いてあるのはWindowsだとそういう風に表示されるんでしょうか。

When I tried to bulid with the solution file of the master branch(baa5b66), a build error occured, but I was able to build unity-compatible branch (b7d71ec) without any problems.

> (中略)  it was found that the unity-compatible branch (略)

普通に能動態で I found でいいと思います。受動態にする必要ないです。

> YamlDotNet project was possible to build.

I was able to build it. でいいんじゃないでしょうか。普通に主語は私 I で書けばいいと思いますよ。

> Also, as a similar phenomenon, 

Also だけでいいと思います。

> the master branch causes an error when the unit test is executed after the build passes through the above correction.

unit tests on master branch fail even after I fixed the above bulid problem. (tests と複数形にしてみました。実際にテストが複数あるのかどうか知らないのですが)

> Expected results 

私の感覚だと result で単数かなと思いました。まあそれは書いている人が何を考えているかを依りますが。

> master branch may be built as well as unity-compatible branch, and all unit tests may be passed.

これは may じゃなくて should のほうがよくないですかね。

master branch should be buildable as well as unity-compatible branch and all unit tests should pass.

こんなんでどうでしょうか。

**Comment by yuseitahara** [comment]
> master branch should be buildable as well as unity-compatible branch and all unit tests should pass.

これについては、そりゃビルドもテストも通ったほうがいいのは当たり前なんですが、shouldで言ってもなんか他のことで忙しい開発者にはキツく聞こえるかもしれません。これらの問題を解決するPRを送れば相手は悪い気はしないんじゃないかと思います。

**Comment by yuseitahara** [comment]
should だとキツいなあという気が自分で書いておいてなんですが、そう思いますので、そうすると

It would be nice if master branch was buildable as well as unity-compatible branch and all unit tests passed.

と書けばいいかなあと思いました。

**Comment by tsutsuji86** [comment]
Target OSS: YamlDotNet

Title: I can not build master branch, but I can built unity-compatible branch.

# Reproduction procedure
* OS: Windows 10 Home
* Build environment:
  Microsoft Visual Studio Community 2019
  Version 16.10.3
* Build procedure:
  The master branch (commit: baa5b66) was cloned from https://github.com/yamldotnet.git . 
  And then,  a solution file (YamlDotNet.sln) in master branch was opened with Visual Studio and builded.

# What happened actually
  When I tried to build with the solution file of the master branch (baa5b66), a build error occurred in YamlDotNet project.,  but I was able to build unity-compatible branch (b7d71ec)  without any problems.
  
Comparing two commits, I found that the unity-compatible branch has various files in the folder [buildutils.unityPrerequisites], whereas the master branch does not have those files in a same folder.
Therefore, by copying that folder in unity-compatible branch to a master branch, I was able to build it.

Also, some unit tests on master branch failed even after I fixed the above build problem.
This was due to the lack of the contents of the YamlDotNet.Test\yaml-test-suite folder.

# Expected result
It would be nice if master branch was buildable as well as unity-compatible branch and all unit tests passed.

**Comment by tsutsuji86** [comment]
Tahara様

丁寧な添削と貴重なコメントありがとうございます。
上記のご指摘を反映して書き直しました。

Google翻訳を使った後に、自分なりに添削したつもりだったのですが、
ブランチ名やコミット番号が大文字になっていたところをスルーしていました。

また、技術的な話を書くのに、主語として私（I）を使ってはいけない、とか
受動態で書かなければいけない、とか、
先入観を持っていたようで、どっちつかずな文章になっていました。

お忙しいところ、ご対応いただきありがとうございました。

**Comment by piroor** [comment]
添削後の報告文面を拝見しました。こちらで問題ないと自分は思いました！
