### ISSUE TITLE
OSS Gate Workshop: Online: 2021-10-30: maki: Faker-ruby ja : Work log

### ISSUE THREAD

**Issue by sandonemaki** [oss-gate/workshop#1494]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明
**OSSを決める（この中のものを調べて決めようと思います）**
- Faker-ruby ja 
https://github.com/faker-ruby/faker/tree/master/lib/locales/ja

- factory_strategist（昨日使ってみました。factory-botのgemも初めて使ってみました。）
https://github.com/neko314/factory_strategist

- Rubocop-rails（初心者用がある）
https://github.com/rubocop/rubocop/contribute

**普段使っている拡張機能**
- HTML to Figma
https://chrome.google.com/webstore/detail/html-to-figma/efjcmgblfpkhbjpkpopkgeomfkokpaim

- 画像を文字化してくれるOCR拡張機能
https://chrome.google.com/webstore/detail/copyfish-%F0%9F%90%9F-free-ocr-soft/eenjdnjldapjajjofmldgmkjaienebbj

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sandonemaki** [comment]
ライセンスは、codeの右端のaboutか、License.txtに記載されていた

**Comment by sandonemaki** [comment]
日本語版が６ヶ月前にできた。address.ymlなど、まだ登録されていないものがあるので、それを登録したいと思った。

**Comment by sandonemaki** [comment]
fakerのjaを試してみた。
#coding utf-8

require 'faker'
require 'Set'

puts Faker::Code.ean #=> EANコード
puts Faker::Name.name #=> 氏名
puts Faker::Lorem.sentence #=> loremな文章
puts Faker::Adress.postcode ##=>郵便番号

**Comment by sandonemaki** [comment]
エラーが出た
warning: already initialized constant Set::InspectKey
warning: previous definition of InspectKey was here
8523152439556
Burton Ortiz IV
Aperiam sed enim omnis.
faker.rb:9:in `<main>': uninitialized constant Faker::Adress (NameError)
Did you mean?  Faker::Address
kamuramaki@kamuramakinoMacBook-Pro hruby %

**Comment by sandonemaki** [comment]
git-hubにcodeを記入するときは、以下を入力するとRuby用のコードになる

```
```Ruby
```
```

**Comment by sandonemaki** [comment]
コードの修正をした
```Ruby
#coding utf-8

require 'faker'
require 'set' #=>修正（S→sにした）

puts Faker::Code.ean #=> EANコード
puts Faker::Name.name #=> 氏名
puts Faker::Lorem.sentence #=> loremな文章
puts Faker::Address.postcode ##=>郵便番号　#=>修正（Addressをタイポしていた）
```

**Comment by sandonemaki** [comment]
上のコードを実行するとエラーがなくなった
```Ruby
2007650787761
Genaro Armstrong
Recusandae est eligendi laborum.
24592
```

**Comment by yuseitahara** [comment]
日本語のデータを生成する方法を公式ドキュメントに追加できるといいかもしれませんね。

**Comment by sandonemaki** [comment]
### つまづきポイント
1 . `require 'set'`は無くても動いた。コードをシンプルにするために省く。
2 . Faker::Config.locale = 'ja'の置き場所をrequireの前に置いていた。

```Ruby
Faker::Config.locale = 'ja'
require 'faker'
#require 'set' #=>（なくても良い）

puts Faker::Code.ean #=> EANコード
puts Faker::Name.name #=> 氏名
puts Faker::Lorem.sentence #=> loremな文章
puts Faker::Address.postcode ##=>郵便番号
```

**Comment by sandonemaki** [comment]
上のコードを修正すると、エラーが出なくなった。
```Ruby
require 'faker'

Faker::Config.locale = 'ja'
puts Faker::Code.ean #=> EANコード
puts Faker::Name.name #=> 氏名
puts Faker::Lorem.sentence #=> loremな文章
puts Faker::Address.postcode ##=>郵便番号
```

**Comment by sandonemaki** [comment]
### 困ったこと_まとめ

- 日本語化Fakerの現状のReadmeは、`Faker::Config.locale = 'ja'`の情報がないため、英語で出力され日本語化できなかった。Fakerを各言語に対応させる方法は、TOPページの下の方にあるリンクからたどり着く必要があるが、見つけ辛かった。
- Fakerで検索するとFakerのgithubのトップページが出てくるが、日本語版へのリンクがない。Fakerのtopページに来ても、日本語版があることを知らないまま帰る人も多いように思う。

### 提案
- TOPページから各言語ページへのリンクがあると、Fakerが持っているロケールが伝わりやすい。
- Faker::Config.locale = 'ja'をトップページに掲載し、'ja'の部分を各言語に対応させることで、目当ての言語の出力が出来ることを伝えると、利用者が迷わず使いやすくなる。

**Comment by sandonemaki** [comment]
上記を書き終えた時点でサポーターさんに見てもらう。

- 困ったことを２つまとめるより、粒を細かくして開発者に伝える方がわかりやすいとのこと。
- 困ったことを分ける→それぞれに対し、実際に困ったシナリオを書く→シナリオに対する提案を書く。

**Comment by sandonemaki** [comment]
### 提案_1

**・問題点**
Fakerの日本語版git-hubページを見つけるのが困難

**・困ったこと**
Fakerのgit-hubの日本語版ページにたどり着くには、URLを覚えておかなければならなかった。日本語版があることを知らない利用者は、Readme（Topページ）に来ても日本語版に気づかず帰ってしまうことも多いと思った。

**・提案**
FakerのReadme（Topページ）に、日本語含む各言語版へのページへのリンクがあると、Fakerがどのようなロケールを持っているかがわかりやすい。

**Comment by sandonemaki** [comment]
### 提案_2

**・問題点**
Fakerを各言語に対応させる方法がわかり辛い

**・困ったこと**
Fakerの日本語版を使いたかったが、Readme（Topページ）のここへを見つけることができず、Faker::Config.locale = 'ja'を知らないため、英語での出力になってしまい、日本語の出力を出来なかった。

**・提案**
FakerのReadmeのUsageに、各言語に変換するコードが書かれている方がわかりやすい。
さらに、各言語ページのReadmeにも各言語に合わせたサンプルコードがあるとわかりやすい。

**Comment by sandonemaki** [comment]
サポーターさんからのフィードバック
提案２を解決する手段によっては提案１も解決するのではとのこと

**Comment by zonuexe** [comment]
Fakerのテストコードは[test/](https://github.com/faker-ruby/faker/tree/master/test)にあるので、それぞれのテストで何を保証しようとしているのか、テストをランダムに書き換えてみる、テスト対象のメソッドを適当に書き換えてみる、などやってみるとRuby自体の理解が深まるかもしれません。

ローカルでの開発方法などは[`CONTRIBUTING.md`](https://github.com/faker-ruby/faker/blob/master/CONTRIBUTING.md)に記載されているように `bundle exec rake` でテスト実行できそうです。

**Comment by sandonemaki** [comment]
> Fakerのテストコードは[test/](https://github.com/faker-ruby/faker/tree/master/test)にあるので、それぞれのテストで何を保証しようとしているのか、テストをランダムに書き換えてみる、テスト対象のメソッドを適当に書き換えてみる、などやってみるとRuby自体の理解が深まるかもしれません。
> 
> ローカルでの開発方法などは[`CONTRIBUTING.md`](https://github.com/faker-ruby/faker/blob/master/CONTRIBUTING.md)に記載されているように `bundle exec rake` でテスト実行できそうです。

**Comment by sandonemaki** [comment]
休憩前にサポーターさんが入れ替わり、提案内容をいちから説明する。
雑談中にFakerのコードがとても少ない量だったこと。わかりやすいコードの組み合わせで驚いた話をする。書くためのコードの見方を相談する。
全体像を捉えるためにテストをするのが良い（上記）とアドバイスを頂いた。

**Comment by sandonemaki** [comment]
困ったこと
FakerのReadmeに日本語ページへのリンクがないため、日本語版ページを探すのに苦労した。
使用法に各言語に対応した書き方がないため、どう書けば良いのか分かり辛かった。

問題点
Fakerが各言語に対応していることがReadmeからは分からない。
各言語に対応したcodeの書き方がReadmeに記載されていない。

提案
Fakerが各言語に対応していることを、利用者に理解してもらう。

具体案
・Usageの前に対応言語を記載。（French、Japanese。）
・Usageでrequire 'faker'の後に、Faker::Config.locale = 'ja'を記載。
説明として、''内には利用したい言語名を入れる。

**Comment by sandonemaki** [comment]
フィードバック
Fakerで日本語の出力をしたかったが、方法がわからなかった。

**Comment by sandonemaki** [comment]
Issuesでの提案内容

### 困ったこと
Fakerで日本語の出力を出したかったが、方法がわからなかった

### 問題点
・Fakerで英語以外に出力できる言語がわからない
・FakerのReadmeから日本語出力の設定方法がわからない


### 提案
**Usageの前に対応言語を記載**
出力言語
English/French/Japanese

**Usageに、Faker::Config.locale = 'ja'を記載
```Ruby
require 'faker'
Faker::Config.locale = 'ja'
# ''内に利用したい言語名を入れる

Faker::Name.name      #=> "Christophe Bartell"

Faker::Internet.email #=> "kirsten.greenholt@corkeryfisher.info"
```

**Comment by sandonemaki** [comment]
タイトル：Readmeにlocalesの説明を追記する

##Feature request
Readmeにlocalesの説明を追記する
* Fakerで英語以外に出力できる言語がわからない
* FakerのReadmeから日本語出力の設定方法がわからない

## 追記内容
* 対応している言語の一覧を追加する
    * 例えば `English/French/Japanese`
* `Faker::Config.locale` の設定のサンプルコードを追加する

```Ruby
require 'faker'
Faker::Config.locale = 'ja'
# ''内に利用したい言語名を入れる

Faker::Name.name      #=> "Christophe Bartell"

Faker::Internet.email #=> "kirsten.greenholt@corkeryfisher.info"

```

**Comment by sandonemaki** [comment]
*Is your feature request related to a problem? Please describe.**

* Readmeにlocalesの説明を追記する
    * Fakerで英語以外に出力できる言語がわからない
    * Fakerの README から日本語出力の設定方法がわからない

**If you're adding new objects, please describe how you would use them**

**Describe alternatives you've considered**

* 対応している言語の一覧を追加する
    * 例えば English/French/Japanese
    * Faker::Config.locale の設定のサンプルコードを追加する
```Ruby
    require 'faker'
Faker::Config.locale = 'ja'
# ''内に利用したい言語名を入れる

Faker::Name.name      #=> "Christophe Bartell"

Faker::Internet.email #=> "kirsten.greenholt@corkeryfisher.info"
```

**Comment by sandonemaki** [comment]
**Is your feature request related to a problem? Please describe.**
* Add a description of locales to the README.
    * I don't know what languages Faker can output other than English.
    * I don't know how to configure Japanese output from Faker's README.

**If you're adding new objects, please describe how you would use them**

**Describe alternatives you've considered**
* Add a list of languages that are supported by Usege.
    * For example, English/French/Japanese.
    * Add sample code for setting Faker::Config.locale.
```Ruby
require 'faker'

# Put the Language name you want to use in ''.
Faker::Config.locale = 'ja'

puts Faker::Name.name         #=> 菅原 智子

puts Faker::Lorem.sentence    #=> きゅうりょうあらあらしいちきゅうひがい。
```

**Additional context**

**Comment by sandonemaki** [comment]
issuesを立てることが出来ました！
https://github.com/faker-ruby/faker/issues/2410
色々気遣う点を細かく教えていただき、とても助かりました！
次はPull requestsもやってみようと思います！

**Comment by yuseitahara** [comment]
素晴しいです!この Issue の続きで、実際に Pull Request をやっているのがいいですね。
開発者の立場で考えれば、Issue で問題点を指摘するだけじゃなくて実際にその問題点を解決する Pull Request をしてくれたら、そのほうが断然助かりますから。
