### ISSUE TITLE
 OSS Gate Workshop: online: 2021-10-39: R-Tsukada: Devise: Work log

### ISSUE THREAD

**Issue by R-Tsukada** [oss-gate/workshop#1495]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yuseitahara** [comment]
サポーターの田原です。よろしくお願いします。

**Comment by R-Tsukada** [comment]
Railsのgemである`Devise` を選ぶことにした。
公式URLは以下のもの。
https://github.com/heartcombo/devise

**Comment by R-Tsukada** [comment]
`Devise`のgithubページで、`Devise`はMIT-LICENSEであることを確認した。

Open Source Initiativeで確認したところMIT-LICENSEの項目があったため、`Devise`はOSSであることがわかった。

**Comment by R-Tsukada** [comment]
`Devise`は事前にgemに追加済みで`bundle install`も完了してあった。
そのため`rails generate devise MODEL`を実行。

↑READMEを読み間違えてしまい、誤ったコマンドを実行してしまっていた。
`MODEL` の箇所をクラス名にする必要があった。

`rails generate devise User` を実行した。

**Comment by R-Tsukada** [comment]
`rails generate devise User`実行後、以下のコマンドが表示された。

```
Running via Spring preloader in process 52618
      invoke  active_record
      create    db/migrate/20211030024238_add_devise_to_users.rb
      insert    app/models/user.rb
       route  devise_for :users
tsukadaryou@tsukadaryounoiMac everyd
```

`ls`でディレクトリを実行し、上記ファイルが作成されていることを確認。

**Comment by R-Tsukada** [comment]
エディタ（Rubymine）では`db/migrate/20211030024238_add_devise_to_users.rb`を確認できない。

**Comment by R-Tsukada** [comment]
エディタを再起動したら`db/migrate/20211030024238_add_devise_to_users.rb`を確認できた。

**Comment by R-Tsukada** [comment]
既に`rails generate devise User`を実行してあったため、`conflict`が起こっている。
そのため、` rails db:migrate`した際に、`ArgumentError: Invalid route name, already in use: 'new_user_session' `のエラーが表示された。
`devise`の問題ではなく、自分の問題なので対応する。

**Comment by R-Tsukada** [comment]
新しくファイルを作り直し、再度`devise`をインストールしていくことにする。
`devise`をREADME通りに実行していくにあたって、元々`devise`が入っているファイルよりも、新規のファイルの方が気づきが得られやすいと思ったため、そのように判断した。

**Comment by R-Tsukada** [comment]
`rails new`を実行し、Railsファイルを新規に作成した。

- データベース作成
- `bin/rails db:create`
- ユーザー管理機能を作成
   - `devise`の作業を進めていく上で必要と判断
   - `bin/rails generate scaffold user name:string address:string afe:integer
   - `bin/rails db:migrate`を実行

**Comment by R-Tsukada** [comment]
`README.md`の指示通りに、`config/environments/development.rb:`に
 `config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
`を追加

**Comment by R-Tsukada** [comment]
- コントローラーに`before_action :authenticate_user!`を入力
- 例のコードのディレクトリを書いといてくれると初学者でもわかりやすいと思った。でもかなり初歩的なので別にいらないのかな？
Controller filters and helpers
Devise will create some helpers to use inside your controllers and views. To set up a controller with user authentication, just add this before_action (assuming your devise model is 'User'):
`before_action :authenticate_user!`

**Comment by yuseitahara** [comment]
そういう気づきはフィードバックポイントになりますね!

**Comment by R-Tsukada** [comment]
- `before_action :authenticate_user!`入力後、`3000/users/`にアクセスすると自動的に`3000/users/sign_in`に飛び、ログイン画面が表示された。
- `before_action :authenticate_user!`を入力することで、何が実行されるかの記載があった方がわかりやすい気がした。

**Comment by R-Tsukada** [comment]
- `Devise`はユーザーが`signing`、`account updating`したときにリダイレクト先の`root path`を探すとのこと。
- `routes.rb`に`devise_for :users`とあるけど、そのことなのか？

**Comment by R-Tsukada** [comment]
- 疑問点
`README.md`の、Controller filters and helpersの項目にあるサンプルコード`before_action :authenticate_user!`を記入後に何が起こるのかがわからない。
- 提案
サンプルコード`before_action :authenticate_user!`の下に説明があると理解しやすくなる。
- 具体例
`/users`にアクセスすると自動的にログイン画面（`/users/sign_in`)に移行することがわかるような画像または説明が追記されると理解がしやすくなる。

**Comment by R-Tsukada** [comment]
この時点で、`/users`にアクセスしたときに自動的に`/users/sign_in`に移行し、ログイン認証画面へと変遷する

**Comment by osyo-manga** [comment]
README のここの部分
https://github.com/heartcombo/devise#controller-filters-and-helpers

**Comment by R-Tsukada** [comment]
- 具体的な修正点
If you fill in `before_action :authenticate_user!`, when you access `/users`, you will be automatically redirected to `/users/sign_in` and the login authentication screen will be displayed.

**Comment by yuseitahara** [comment]
さっそく英文も用意して素晴しいです。恐縮ながらちょっとだけコメントさせてもらいますと

> just add this before_action (assuming your devise model is 'User'):
> `before_action :authenticate_user!`

前の文が↑ですから、それに合わせて書くとしたら、

> If you fill in before_action :authenticate_user!, when you access /users, you will be

これを次のようにしてはどうでしょうか

Once you add that before_action and you access /users, then you will be(以下はそのまま)

あとは devise を fork して自分のレポジトリ上で修正コミットしてPRを出すだけですね。

**Comment by R-Tsukada** [comment]
> 前の文が↑ですから、それに合わせて書くとしたら、
 If you fill in before_action :authenticate_user!, when you access /users, you will be
> 
> これを次のようにしてはどうでしょうか
> 
> Once you add that before_action and you access /users, then you will be(以下はそのまま)

早速ありがとうございます！
確かに僕の書き方では重複した書き方になってしまいそうですね。
ご提案していただいた英文を使わせてもらいます。

> あとは devise を fork して自分のレポジトリ上で修正コミットしてPRを出すだけですね。

わかりました！やってみます。

**Comment by yuseitahara** [comment]
PR見ました。いいですね!リンクを貼っておきます。

https://github.com/heartcombo/devise/pull/5415

**Comment by R-Tsukada** [comment]
> PR見ました。いいですね!リンクを貼っておきます。
> 
> [heartcombo/devise#5415](https://github.com/heartcombo/devise/pull/5415)

ありがとうございます！
またPRに追加のコメントしてくださってありがとうございます！修正をする理由を明記しておいた方が、PRを受け取る側が理解しやすいのだろうな、と思いました！
とても勉強になりました。ありがとうございます。
