### ISSUE TITLE
OSS Gate Workshop: online: 2020-10-30: たら: openSCAD: Work log

### ISSUE THREAD

**Issue by marufura** [oss-gate/workshop#1496]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by marufura** [comment]
# [openSCAD](https://openscad.org/)
## Licence
[GNU GENERAL PUBLIC LICENSE](https://github.com/openscad/openscad/blob/master/COPYING)

**Comment by marufura** [comment]
documentaiton に日本語が欲しい

**Comment by marufura** [comment]
座標が一致している際にdifferenceを取るとPreviewの表示がおかしくなる。

**Comment by marufura** [comment]
## test code
```openSCAD
difference(){
    cube([10, 10, 10]);
    translate([5, 5, 5])
        cube([5, 5, 5]);                             
}
```

**Comment by marufura** [comment]
https://openscad.org/documentation.html
からPreviewの挙動に関して説明されているか確認中

初めてやる人は困惑するかもしれない。

**Comment by piroor** [comment]
* スクリーンショットがあるのはとてもよい。障害として報告するときに、画像で状態が示されていると、開発者は依り状態を把握しやすい。
* ドキュメントの翻訳は、それぞれの言語の翻訳結果をどう管理するか？ということをプロジェクト側で考えないといけないため、相談してから始めるのがよさそう。

**Comment by marufura** [comment]
## ちらつきを発生させる関数の記述
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/CSG_Modelling#difference

## ちらつきに関しての説明
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#What_are_those_strange_flickering_artifacts_in_the_preview?

**Comment by marufura** [comment]
wikibooksの編集はログインしたら誰でもできそうなのでissueをたててやるほどのことでもない。
日本語版は最終更新2015年で止まってしまっている。

[Wikibooks 編集履歴](https://ja.wikibooks.org/w/index.php?title=OpenSCAD_User_Manual&action=history)

**Comment by zonuexe** [comment]
Wikibooksは継続的に編集する場合はアカウントを作成(Wikipediaと同じアカウントでログインも可)して作業するとよさそうです。

<a href="https://ja.wikibooks.org/wiki/OpenSCAD_User_Manual"><img width="565" alt="スクリーンショット 2021-10-30 16 04 54" src="https://user-images.githubusercontent.com/822086/139523875-b9518439-6895-4d26-a8e8-1fdc0b8a91a4.png"></a>

Wikibooksは「議論」がissueのようなものなので、「2015年以後の変更に追従します」のような宣言をするとよいでしょう。WikibooksはWikipediaと運営母体が同じなのでルールやガイドラインなどは基本的に共通なので参考にしてみてください。

 * [Wikibooks:新しいページの作り方 - Wikibooks](https://ja.wikibooks.org/wiki/Wikibooks:%E6%96%B0%E3%81%97%E3%81%84%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9)
 * [Wikipedia:翻訳のガイドライン - Wikipedia](https://ja.wikipedia.org/wiki/Wikipedia:%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3)
   * 英語版から翻訳する際はコメントに「`[[en:Shopping mall]] (17:15, 01 October 2013 UTC) を翻訳`」のように適切なコメントをつけないと履歴不継承として適切な著作権処理ができないので気をつけてください。
