### ISSUE TITLE
 OSS Gateワークショップ2016-01-30: まとめを作る

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#15]
次回はまとめる人を決めておこう。。。

今回はまとめる人を決めていなかったので忘れていることもたくさんあるはず。。。

**Comment by kawahara** [comment]
カンファレンスとかでワークショップなどできないか確認する

**Comment by kohei-takata** [comment]
単純に時間を短くするのは無理そう

**Comment by kou** [comment]
高専生を誘ってみよう。（高専カンファレンス関係者に相談してみよう。）

**Comment by kou** [comment]
参加者には開発元へのフィードバックがその後どうなったかを教えてもらうことにした。

@knokmki612 @akito19 @hanzgit @tSU-RooT https://gitter.im/oss-gate/workshop で教えてください！

**Comment by kou** [comment]
#14 のアンケート結果をここにまとめたいんだけどどうするのがいいんだろう。

**Comment by kou** [comment]
ワークショップを隔月開催する。

2016年3月から最終土曜日に開催する。

このワークショップの目的をなんにするか（今回は実際に経験してフィードバックを得ることを目的にした）、進行役をだれがやるかとかはオンラインで相談して決める。

**Comment by sezemiadmin** [comment]
> #14 のアンケート結果をここにまとめたいんだけどどうするのがいいんだろう。

@kou 1/30、お疲れさまでした!! アンケート内容も見ましたが、今回も好評だったようで、良かったです! 結果のスプレッドシートを作成したので、それを公開するのではどうでしょうか?

- OSS Gate 参加者向けアンケート結果 [OSS_Gate_Workshop_Form（回答）](https://docs.google.com/spreadsheets/d/1BkpcdXqgVkMRjdaRnlbExD9dKgcoTmFK3-3dY38Ee_g/edit?usp=sharing)
- OSS Gate メンバー向けアンケート結果 [OSS_Gate_Workshop_Form_4menber（回答）](https://docs.google.com/spreadsheets/d/1zV2mpu-_6OIdypjR5rJsOgyADJwmcgUVC5QfTg6n38M/edit?usp=sharing)

**Comment by tomo667a** [comment]
せっかく作成いただいたので、まずはそのスプレッドシートを公開することが現実的かなと思います。

**Comment by kou** [comment]
覚えている範囲で↓にまとめました！
https://github.com/oss-gate/workshop/blob/master/tutorial/retrospectives/2016-01-30.md
