### ISSUE TITLE
OSS Gate Workshop: freee: 2021-11-25: tatsuyah: vscode: Work log

### ISSUE THREAD

**Issue by tatsuyah** [oss-gate/workshop#1512]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tdtds** [comment]
わいわい

**Comment by teyamagu** [comment]
rubocopいい

**Comment by tatsuyah** [comment]
いきなりですがvscodeに変更します...

**Comment by tatsuyah** [comment]
こいつをやっていく
https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run

**Comment by tatsuyah** [comment]
開発機にNodeもyarnも入っていなかったのでinstall

- Node: https://nodejs.org/en/
- yarn: https://classic.yarnpkg.com/en/docs/install#mac-stable

**Comment by tatsuyah** [comment]
`yarn` 実行Done

**Comment by tatsuyah** [comment]
`./scripts/code.sh`

で以下のエラー. Electronが入ってないから？
```
[Error: ENOENT: no such file or directory, open '/Users/hatanaka-tatsuya/wor[0/41]ode/out/vs/code/electron-main/main.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/hatanaka-tatsuya/works/vscode/out/vs/code/electron-main/main.js',
  phase: 'loading',
  moduleId: 'vs/code/electron-main/main',
  neededBy: [ '===anonymous1===' ]
}
```

**Comment by tatsuyah** [comment]
```
yarn watch-web
yarn web
```
でVS Code for the Webが動作することは確認

*サンプルファイル*
![スクリーンショット 2021-11-25 12 25 21](https://user-images.githubusercontent.com/5807827/143374525-f0675023-258c-41fc-865e-1698b51ad787.png)

**Comment by tatsuyah** [comment]
> `./scripts/code.sh`
> 
> で以下のエラー. Electronが入ってないから？
> 
> ```
> [Error: ENOENT: no such file or directory, open '/Users/hatanaka-tatsuya/wor[0/41]ode/out/vs/code/electron-main/main.js'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/Users/hatanaka-tatsuya/works/vscode/out/vs/code/electron-main/main.js',
>   phase: 'loading',
>   moduleId: 'vs/code/electron-main/main',
>   neededBy: [ '===anonymous1===' ]
> }
> ```

Buildが正しくできてないからっぽい

**Comment by tatsuyah** [comment]
Node由来な気がしたので見てみると、Nodeのバージョンが指定のものと違った。16.x -> 14.xに下げて `yarn` を再実行

**Comment by tatsuyah** [comment]
```
cd vscode
yarn watch
./scripts/code-cli.sh
```

で立ち上がった

**Comment by tatsuyah** [comment]
↑のスクショ
![Uploading スクリーンショット 2021-11-25 13.54.13.png…]()

**Comment by tatsuyah** [comment]
> > `./scripts/code.sh`
> > で以下のエラー. Electronが入ってないから？
> > ```
> > [Error: ENOENT: no such file or directory, open '/Users/hatanaka-tatsuya/wor[0/41]ode/out/vs/code/electron-main/main.js'] {
> >   errno: -2,
> >   code: 'ENOENT',
> >   syscall: 'open',
> >   path: '/Users/hatanaka-tatsuya/works/vscode/out/vs/code/electron-main/main.js',
> >   phase: 'loading',
> >   moduleId: 'vs/code/electron-main/main',
> >   neededBy: [ '===anonymous1===' ]
> > }
> > ```
> 
> Buildが正しくできてないからっぽい

↑仮説は正しかったが、buildの方法が間違っていたのではなく、`yarn watch` のビルドが完了してなかった。

```
[watch-extensions] [13:51:53] Finished compilation extensions with 0 errors after 61114 ms
```

でビルドが完了したように見えたので、`./scripts/code-cid.sh` を実行したが、上記のエラーが出ていた。
実際は以下のメッセージが出るまで待つ必要がある(138074ms!!)

```
[watch-client    ] [13:53:11] Finished compilation with 0 errors after 138074 ms
```

**Comment by tatsuyah** [comment]
やること候補

- 色々ドキュメント見てみる(特にあまりメンテが及んでなさそうな所)
- 拡張機能にPR出す
- ビルドに時間かかるのをdocに反映

**Comment by tatsuyah** [comment]
wikiへのPRがDone.

https://github.com/microsoft/vscode-wiki/pull/201

**Comment by tatsuyah** [comment]
issueを漁っていく

**Comment by h7kayama** [comment]
vscodeのissue、めちゃくちゃありますねw

**Comment by tatsuyah** [comment]
漁りがいしかないやつですねw

**Comment by tatsuyah** [comment]
無駄を省く

https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Abug%2C+help-wanted

**Comment by tatsuyah** [comment]
ExtensionsへのPRもちょっと検討したい
https://github.com/microsoft/vscode/wiki/How-to-Contribute#extensions

**Comment by tatsuyah** [comment]
Extensionたち

- https://github.com/misogi/vscode-ruby-rubocop
- https://github.com/Microsoft/vscode-python

**Comment by tatsuyah** [comment]
気になるissue(拡張のやつ) https://github.com/microsoft/codetour/issues/185

**Comment by tatsuyah** [comment]
このバグが手元でも再現したので、追加情報をコメント
https://github.com/prettier/prettier-vscode/issues/2127
https://github.com/prettier/prettier-vscode/issues/2127#issuecomment-979677321

**Comment by tatsuyah** [comment]
まずは自前ビルド版を手元で動かしたいので、これの通りにやる
https://github.com/prettier/prettier-vscode/blob/main/CONTRIBUTING.md

**Comment by tatsuyah** [comment]
一瞬で拡張機能開発ホストが立ち上がった. 偉大すぎる

![スクリーンショット 2021-11-26 14 30 16](https://user-images.githubusercontent.com/5807827/143531606-34817764-fcb8-4db3-a463-103db9e2613c.png)

**Comment by tatsuyah** [comment]
設定値由来の線を疑ってhtmlWhitespaceSensitivityの値を'ignore', 'strict'に変えてみたが、影響無し

**Comment by tatsuyah** [comment]
この辺りで問題が起きてるはず

https://github.com/prettier/prettier-vscode/blob/4a9ad9d27c23d200e8103a09bbb0f78cc5b0570b/src/PrettierEditService.ts#L433

**Comment by tatsuyah** [comment]
prettierのインスタンスを作ってるのはここ

https://github.com/prettier/prettier-vscode/blob/4a9ad9d27c23d200e8103a09bbb0f78cc5b0570b/src/ModuleResolver.ts#L83

**Comment by tatsuyah** [comment]
拡張機能開発ホスト上でのprintデバッグってどうすんの

**Comment by tatsuyah** [comment]
https://github.com/prettier/prettier-vscode/blob/4a9ad9d27c23d200e8103a09bbb0f78cc5b0570b/src/PrettierEditService.ts#L316 のdocument.getText()
あるいは
https://github.com/prettier/prettier-vscode/blob/4a9ad9d27c23d200e8103a09bbb0f78cc5b0570b/src/PrettierEditService.ts#L433 のtext

と

コマンドラインからprettierを実行(npx prettier --write .)した時に渡ってくる文字列のdiffをみる

**Comment by tatsuyah** [comment]
メモ

拡張機能開発時のprintデバッグ的なことのやり方: https://stackoverflow.com/questions/34085330/how-to-write-to-log-from-vscode-extension

**Comment by tatsuyah** [comment]
問題になっているhtmlをhexでdumpした
以下の通り差分無し

```
<!DOCTYPE html>
<html lang="en">
  <body>
    <a class="footer-link" href="https://google.com"
      > Words words words words words words words words words words </a
    >
  </body>
</html>

```

**vscodeから渡ってきた文字列**

3c21444f43545950452068746d6c3e0a3c68746d6c206c616e673d22656e223e0a20203c626f64793e0a202020203c6120636c6173733d22666f6f7465722d6c696e6b2220687265663d2268747470733a2f2f676f6f676c652e636f6d220a2020202020203e20576f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f726473203c2f610a202020203e0a20203c2f626f64793e0a3c2f68746d6c3e0a

**コマンドラインで直接ダンプしたやつ**

3c21444f43545950452068746d6c3e0a3c68746d6c206c616e673d22656e223e0a20203c626f64793e0a202020203c6120636c6173733d22666f6f7465722d6c696e6b2220687265663d2268747470733a2f2f676f6f676c652e636f6d220a2020202020203e20576f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f72647320776f726473203c2f610a202020203e0a20203c2f626f64793e0a3c2f68746d6c3e0a

**Comment by tatsuyah** [comment]
なので、PrettierEditServiceに渡ってきた時点では同じ値
ということは

- 後段の処理でtextの中身が変わる
- そもそもPrettierはコマンドラインから使うのと、JSからとでは挙動が違う
- vscodeのなんらかの設定が、format直前なりにテキストを変えてる

**Comment by tatsuyah** [comment]
> そもそもPrettierはコマンドラインから使うのと、JSからとでは挙動が違う

これは違った
コードの中からprettier.format()を実行しても正しくformatされた

**Comment by tatsuyah** [comment]
PrettierEditSErvice.tsのprovideEditsの出力までは正しいのを確認したので、その後のどこかで問題が起こっている

**Comment by tatsuyah** [comment]
vscodeでformatterのextensionを作るときに実装する必要のあるインターフェース
https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

**Comment by tatsuyah** [comment]
vscodeにフォーマット後の値を返す直前で値を見てみたが、正しくformatされている。これまさかのprettier-vscodeのバグじゃないやつ？

**Comment by tatsuyah** [comment]
原因判明. この設定とPrettierのhtml formatがbuttingして、挙動がおかしくなっていたのであった

![スクリーンショット 2021-11-26 20 49 44](https://user-images.githubusercontent.com/5807827/143576766-ab749d80-ae16-46f2-90e0-a286b48ab6bf.png)
