### ISSUE TITLE
OSS Gate Workshop: freee: 2021-11-25: teyamagu: site_prism: Work log

### ISSUE THREAD

**Issue by teyamagu** [oss-gate/workshop#1517]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tdtds** [comment]
わいわい

**Comment by teyamagu** [comment]
対象OSSは
https://github.com/site-prism/site_prism
ライセンスは
3条項BSDライセンス: BSD 3-Clause "New" or "Revised" License
https://github.com/site-prism/site_prism/blob/main/LICENSE.md

**Comment by teyamagu** [comment]
「ユーザーとしてsite_prism gemが使えるか」確認していく

まずは https://github.com/site-prism/site_prism/blob/main/README.md のインストールを見る

**Comment by teyamagu** [comment]
https://github.com/site-prism/site_prism/blob/main/README.md#setup の直下に https://github.com/site-prism/site_prism/blob/main/README.md#installation があった．

**Comment by teyamagu** [comment]
`gem install site_prism`

のコマンドとのこと．

rubyのサポートバージョンが気になったので，readme.md内を探すと https://github.com/site-prism/site_prism/blob/main/README.md#supported-rubies--browsers があり，

```
SitePrism is built and tested to work on Ruby 2.4 - 2.7. Ruby 2.4 (Now EOL), is supported but this version will be removed from the Support Matrix in the coming months. If you are using SitePrism with Ruby 2.4 it is highly advisable to upgrade to a more modern Ruby such as 2.7, if for any other reason, to get a noticeable speed boost!
```

とのこと．

**Comment by teyamagu** [comment]
```
% ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
% gem -v
3.0.3
```

の環境下で， `gem install site_prism` を実行する

**Comment by teyamagu** [comment]
実行結果は下記となった．

```
% gem install site_prism
Fetching site_prism-3.7.3.gem
Fetching xpath-3.2.0.gem
Fetching capybara-3.36.0.gem
Fetching site_prism-all_there-0.3.2.gem
Successfully installed xpath-3.2.0
Successfully installed capybara-3.36.0
Successfully installed site_prism-all_there-0.3.2
Successfully installed site_prism-3.7.3
Parsing documentation for xpath-3.2.0
Installing ri documentation for xpath-3.2.0
Parsing documentation for capybara-3.36.0
Installing ri documentation for capybara-3.36.0
Parsing documentation for site_prism-all_there-0.3.2
Installing ri documentation for site_prism-all_there-0.3.2
Parsing documentation for site_prism-3.7.3
Installing ri documentation for site_prism-3.7.3
Done installing documentation for xpath, capybara, site_prism-all_there, site_prism after 3 seconds
4 gems installed
```

**Comment by teyamagu** [comment]
ライブラリはインストールできたみたいだけど，正しく動くのかの検証として何をしたらいいんだ？
`install` の節の次は `Using SitePrism with Cucumber` と `Using SitePrism with RSpec` の節となっているが。

**Comment by teyamagu** [comment]
sampleの記載もしくはファイルがないか探してみる

**Comment by tdtds** [comment]
sampleやtutorialあたりがフィードバックの狙い目ですね！

**Comment by teyamagu** [comment]
Using SitePrism with Cucumber と Using SitePrism with RSpec の節に，ライブラリを組み込む方法のサンプルおよびCapybaraのドライバー設定サンプルはある．

```
require 'capybara'
require 'capybara/cucumber'
require 'selenium-webdriver'
require 'site_prism'
require 'site_prism/all_there' # Optional but needed to perform more complex matching
```

```
Capybara.register_driver :site_prism do |app|
  browser = ENV.fetch('browser', 'firefox').to_sym
  Capybara::Selenium::Driver.new(app, browser: browser, desired_capabilities: capabilities)
end

# Then tell Capybara to use the Driver you've just defined as its default driver
Capybara.configure do |config|
  config.default_driver = :site_prism
end
```

```
require 'capybara'
require 'capybara/rspec'
require 'selenium-webdriver'
require 'site_prism'
require 'site_prism/all_there' # Optional but needed to perform more complex matching
```

および，記述方法のサンプルというか `Synopsis` は https://github.com/site-prism/site_prism/blob/main/README.md#synopsis に存在する．ただし，これだけをコードに貼り付けても動作はしない形．

**Comment by teyamagu** [comment]
`sample` および `tutorial` と名の付くファイル・ディレクトリはなかった．

**Comment by teyamagu** [comment]
capybaraが存在する環境をさらに拡張するライブラリなので，上記の断片で必要最小限と判断されているのかな？

**Comment by teyamagu** [comment]
ということで，capybaraの方をセットアップしてみる．
https://github.com/teamcapybara/capybara

**Comment by teyamagu** [comment]
https://github.com/teamcapybara/capybara#setup および慣れたrspecである https://github.com/teamcapybara/capybara#using-capybara-with-rspec を参考にセットアップする

まずは

```
Capybara requires Ruby 2.6.0 or later. To install, add this line to your Gemfile and run bundle install:

gem 'capybara'
```

とのことなので，Gemfileを作って中に `gem 'capybara'` を書く

**Comment by teyamagu** [comment]
書いたら，インストールできるか確認する

```
[teppei-yamaguchi@yamaguchi-teppei: 21-11-25 12:44:38] ~/work/site_prism_setup
% bundle install --path vendor/bundle
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line
like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'capybara' in any of the gem sources listed in your Gemfile.
```

`source 'https://rubygems.org'` の記載がGemfileになかったので，追加して再実行する

**Comment by teyamagu** [comment]
capybaraインストールはできた模様

```
[teppei-yamaguchi@yamaguchi-teppei: 21-11-25 12:45:07] ~/work/site_prism_setup
% bundle install --path vendor/bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.8.0
Installing addressable 2.8.0
Using bundler 2.0.2
Fetching matrix 0.4.2
Installing matrix 0.4.2
Fetching mini_mime 1.1.2
Installing mini_mime 1.1.2
Fetching mini_portile2 2.6.1
Installing mini_portile2 2.6.1
Fetching racc 1.6.0
Installing racc 1.6.0 with native extensions
Fetching nokogiri 1.12.5 (x86_64-darwin)
Installing nokogiri 1.12.5 (x86_64-darwin)
Fetching rack 2.2.3
Installing rack 2.2.3
Fetching rack-test 1.1.0
Installing rack-test 1.1.0
Fetching regexp_parser 2.1.1
Installing regexp_parser 2.1.1
Fetching xpath 3.2.0
Installing xpath 3.2.0
Fetching capybara 3.36.0
Installing capybara 3.36.0
Bundle complete! 1 Gemfile dependency, 13 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

**Comment by teyamagu** [comment]
フィードバック：
 - https://github.com/site-prism/site_prism#synopsis を実行できるサンプルを用意するといいのでは？

**Comment by teyamagu** [comment]
難しい．synopsisは， `When` , `Then` があるのでcucumberを想定した記述だけど，site-prismおよびcapybara自体はrspec系でテストをしている。

**Comment by teyamagu** [comment]
cucumberで動かせるようにしたら，すぐエラー出た．ここは `synopsis` はイメージコードだなぁ．これは動くコードにして提案するチャンスかな

**Comment by teyamagu** [comment]
synopsis ベースのサンプルCodeできた．英語依存なところは手元でエラーデルのやむ無しかな．エラー見たら「ですよねー」となるので．

**Comment by teyamagu** [comment]
コードなくさないように，forkした自分のリポジトリのブランチにいれておく

**Comment by teyamagu** [comment]
ブランチにいれた https://github.com/teyamagu/site_prism/tree/add_sample

**Comment by teyamagu** [comment]
PRとして伝えること

・やっていたこと：site_prismがどのようなものか知りたくてインストール
・期待：site_prismが使えること
・現状：サンプルがなく，synopsisもそのまま動くわけではない
・提案：synopsisベースにsampleテスト作ったのでインストール後すぐ試せる

**Comment by teyamagu** [comment]
既存のPRを見てみる．お作法とかあるかないか

**Comment by teyamagu** [comment]
お作法はなかった

**Comment by teyamagu** [comment]
PRの受け手として欲しい情報
- sample追加で何が良くなるのか

**Comment by teyamagu** [comment]
PR出してみた．どうなるかなー
https://github.com/site-prism/site_prism/pull/104

**Comment by teyamagu** [comment]
https://github.com/site-prism/site_prism/pull/104

**Comment by teyamagu** [comment]
次は，今回やりたかったモンキーパッチのアップストリームマージに取りかかる

**Comment by teyamagu** [comment]
上記PRは、メイン著者もトライしていていて，良い感じの作成できず追加していないとのことだった．
「時間とれるなら考える」とのことなので，残念ながら一旦クローズすることにしました．

**Comment by teyamagu** [comment]
色々やりとりして，CHANGELOGの英文添削までされて，モンキーパッチをアップストリームにマージしてもらえた．やったー！
https://github.com/site-prism/site_prism/pull/105
