### ISSUE TITLE
OSS Gate Workshop: online: 2021-12-11: OSS Gate Workshop: Toshi: ${OSS_NAME}: Work log

### ISSUE THREAD

**Issue by itotoshinori** [oss-gate/workshop#1525]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by itotoshinori** [comment]
Railsの便利なgemを選定して、インストールして使ってみたいと思います。
まずは選定します。

**Comment by itotoshinori** [comment]
こちらのために新規プロジェクト作成中です。
Windows8.1(マシーン古い）　Vagrant上で作成中です

**Comment by itotoshinori** [comment]
日頃、Railsで新規プロジェクトを作ることがなく新規作成失敗しました。
別のVagrantに移ります
![railsshoki](https://user-images.githubusercontent.com/20299252/145664599-01f68144-12b7-4e07-b5b9-3700a646bef5.png)
。

**Comment by itotoshinori** [comment]
別のCentOS7対上げてます

**Comment by itotoshinori** [comment]
![putty](https://user-images.githubusercontent.com/20299252/145664800-5cbb4a85-2155-429a-996c-dee8d4604f91.png)

**Comment by itotoshinori** [comment]
Rails new してます

**Comment by itotoshinori** [comment]
![start](https://user-images.githubusercontent.com/20299252/145664923-3f8348b5-2e8b-4afc-9cf6-54ce82ce99a2.png)
Rails立ち上げました

**Comment by itotoshinori** [comment]
rails g controller starts index
で初期画面作成　/starts/index

**Comment by itotoshinori** [comment]
![無題](https://user-images.githubusercontent.com/20299252/145665120-5cf965bf-7460-4332-aa04-706ba0073047.png)

**Comment by itotoshinori** [comment]
winSCPで当該サーバーに入り編集していきます

**Comment by itotoshinori** [comment]
![result](https://user-images.githubusercontent.com/20299252/145665191-e7c40971-7f6f-4e62-b4c1-7c2bed7e0e38.png)

**Comment by piroor** [comment]
https://www.google.com/search?client=firefox-b-d&q=holidays+japan+gem と検索してみたら、2つ出てきました
https://rubygems.org/gems/holiday_jp/versions/0.7.1
https://rubygems.org/gems/holiday_japan/versions/1.0.3?locale=ja

**Comment by itotoshinori** [comment]
hirb
rails consoleでモデル出力時に整形してくれるgemです。
を使ってみたいと思います

**Comment by itotoshinori** [comment]
https://k-koh.hatenablog.com/entry/2020/02/04/204506
を参考にして進めます

**Comment by itotoshinori** [comment]
https://ccbaxy.xyz/blog/2020/10/03/ruby53/
サイトに変えてみます

**Comment by piroor** [comment]
https://github.com/cldwalker/hirb

**Comment by itotoshinori** [comment]
https://github.com/cldwalker/hirb
公式サイト？

次のコマンドでgemをインストールします。

gem  install  hirb

**Comment by piroor** [comment]
http://masa16.github.io/holiday_japan/

**Comment by itotoshinori** [comment]
holiday Japan　にかえます
http://masa16.github.io/holiday_japan/

**Comment by itotoshinori** [comment]
gem install holiday_japan
実行

**Comment by itotoshinori** [comment]
StartsController　に
require 'holiday_japan'を追記

class StartsController < ApplicationController
  require 'holiday_japan'
  def index
  end
end

**Comment by itotoshinori** [comment]
Starts#index
<%= HolidayJapan.name(Date.new(2020,3,20)) %>
に追記　
<h1>Starts#index</h1>
<p>Find me in app/views/starts/index.html.erb</p>
<%= HolidayJapan.name(Date.new(2020,3,20)) %>

**Comment by itotoshinori** [comment]
Railsで使用しようとしたら失敗しました。
![start](https://user-images.githubusercontent.com/20299252/145665864-198b6989-89fd-4f20-bafb-80bcbbbffa3b.png)

**Comment by itotoshinori** [comment]
rubyがインストールされた環境で　holiday.rbを作成
下記を記載して
require 'holiday_japan'
holiday = HolidayJapan.check(Date.new(2020,3,20))
puts holiday
holiday_japan = HolidayJapan.name(Date.new(2020,3,20))
puts holiday_japan

>ruby holiday.rb
を実行したら正常に出力されました
true
春分の日

gem　には基本には問題ないようです

**Comment by itotoshinori** [comment]
Rails 
ルートに
gem 'holiday_japan'
を追記して作動するか確認します

**Comment by itotoshinori** [comment]
先程のRailsプロジェクトに戻って
Gemfile  にgem 'holiday_japan'を追記
bundle installを実行
エラーなしで実行できました。
Railsブラウザー上で出力してみます

**Comment by itotoshinori** [comment]
StartsControllerに
@holiday = HolidayJapan.name(Date.new(2020,3,20)) 
を追記

class StartsController < ApplicationController
  def index
    @holiday = HolidayJapan.name(Date.new(2020,3,20)) 
  end
end

**Comment by itotoshinori** [comment]
\app\views\starts\index.html.erb
ファイルに
<%= @holiday %>
を記入して実行したら
春分の日が表示されました
問題なく作動します

**Comment by itotoshinori** [comment]
![start](https://user-images.githubusercontent.com/20299252/145668449-22e2caad-d645-4966-8b84-dfb771a6ed4d.png)

**Comment by itotoshinori** [comment]
全祝日を出力したいと思います

**Comment by itotoshinori** [comment]
\app\controllers\starts_controller.rb
@holidays = [] 
@holidays = HolidayJapan.list_year(2022)
を追記し
class StartsController < ApplicationController
  def index
    @holidays = [] 
    @holidays = HolidayJapan.list_year(2022)
  end
end

\app\views\starts\index.html.erb
を
<%= @holidays %>
に変更2022年の祝日が出力されました

**Comment by itotoshinori** [comment]
![start](https://user-images.githubusercontent.com/20299252/145669045-dc5f2bf2-02fc-43ba-b97f-54ad36007f86.png)

**Comment by itotoshinori** [comment]
\app\views\starts\index.html.erb　を修正して縦一でみれるようにしました
<% @holidays.each do |weekday,day,holiday|%>
    <%=weekday %>
    <%= day %>
    <%= holiday %>
    <br />
<% end %>

**Comment by itotoshinori** [comment]
![start](https://user-images.githubusercontent.com/20299252/145669202-062a28d7-b321-411c-892f-3cdfd164e963.png)

**Comment by itotoshinori** [comment]
来年の祝日に漏れがないかチェックしてみます

**Comment by itotoshinori** [comment]
内閣府のホームページ2022年をチェックしましたが漏れなありませんでした
https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

**Comment by itotoshinori** [comment]
ループで出力すると
2022-11-03のように
英語での出力はないですね。
従って私の日本語で出して欲しいの要望
事項は取りやめます

**Comment by itotoshinori** [comment]
逆に曜日がでなくなりました。日本語で曜日出た方がありがたいと候補には入れておきます

**Comment by youkidearitai** [comment]
`HolidayJapan.print_year` メソッドのように、曜日が英語になってしまうので日本語で曜日を出力できるとありがたいかなというのを話してましたね。

    irb(main):009:0> HolidayJapan.print_year 2019
    listing year 2019...
    2019-01-01 Tue 元日
    2019-01-14 Mon 成人の日
    2019-02-11 Mon 建国記念の日
    2019-03-21 Thu 春分の日
    2019-04-29 Mon 昭和の日
    2019-04-30 Tue 国民の休日
    2019-05-01 Wed 天皇の即位の日
    2019-05-02 Thu 国民の休日
    2019-05-03 Fri 憲法記念日
    2019-05-04 Sat みどりの日
    2019-05-05 Sun こどもの日
    2019-05-06 Mon 振替休日
    2019-07-15 Mon 海の日
    2019-08-11 Sun 山の日
    2019-08-12 Mon 振替休日
    2019-09-16 Mon 敬老の日
    2019-09-23 Mon 秋分の日
    2019-10-14 Mon 体育の日
    2019-10-22 Tue 即位礼正殿の儀
    2019-11-03 Sun 文化の日
    2019-11-04 Mon 振替休日
    2019-11-23 Sat 勤労感謝の日

**Comment by itotoshinori** [comment]
要望候補
修正時のアナウンスを出して頂くとありがたい
自動的に修正がかかってくれると頂くとありがたい
Railsでの導入の手順があるとありがたい
曜日が日本語ででて欲しい

**Comment by itotoshinori** [comment]
要望候補
bundler(Rails等)での導入の手順があるとありがたい

**Comment by itotoshinori** [comment]
修正時(毎年2月)　Rubyにデータ修正があったのでアップデータして下さいのメッセージがでるとありがたい

**Comment by itotoshinori** [comment]
曜日が日本語ででて欲しい

**Comment by itotoshinori** [comment]
一例として

bundler(Rails等)での導入の手順があるとありがたい

で要望書を作成してみたいと思います

**Comment by itotoshinori** [comment]
再現手順
Railsのプロジェクトを作成する(rails5.2 ruby 2.6.6p146)
readmeに従い
>gem install holiday_japan　を実行
>rails g controller starts index でコントーラー　index　viewファイルを作成

\app\controllers\starts_controller.rbを修正
class StartsController < ApplicationController
  require 'holiday_japan'
  def index
    @holidays = [] 
    @holidays = HolidayJapan.list_year(2022)
  end
end

\app\views\starts\index.html.erb
を修正
<% @holidays.each do |weekday,day,holiday|%>
    <%=weekday %>
    <%= day %>
    <%= holiday %>
    <br />
<% end %>

期待される結果


実際の結果
