### ISSUE TITLE
OSS Gate Workshop: online: 2021-12-11:katataku: norminette: Work log

### ISSUE THREAD

**Issue by katataku** [oss-gate/workshop#1526]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by katataku** [comment]
norminetteにきめた。

https://github.com/42School/norminette

**Comment by katataku** [comment]
すでに使っているツールなので今のバージョンはこれ。
$ norminette --version
norminette 3.3.2

**Comment by katataku** [comment]
upgradeの手順に従ってバージョンアップしてみる。

python3 -m pip install --upgrade norminette

**Comment by katataku** [comment]
成功したと表示された。

Successfully installed norminette-3.3.51

**Comment by katataku** [comment]
バージョンは上がってるみたい。

$ norminette --version
norminette 3.3.51

**Comment by katataku** [comment]
norminette ft_strlen.cコマンドの実行で、チェッカー機能が動作した。

**Comment by katataku** [comment]
norminetteだけで入力すると「Runs on the current folder and any subfolder」になると読み解けなかった。

**Comment by katataku** [comment]
norminetteだけえで、チェッカー機能が動作した

**Comment by katataku** [comment]
various blocking errorsがなにかわからない

**Comment by katataku** [comment]
pdfの説明書きを読んでもわかんない

**Comment by katataku** [comment]
__main__.pyのL38をみると-dは "--debug",ぽい。

**Comment by katataku** [comment]
norminette --debugを実行してもdebugメッセージは表示されない。
norminette -ddを実行するとデバッグメッセージが表示される。
norminette --helpの実行結果は以下の通り。

$ norminette --help
usage: norminette [-h] [-d] [-o] [-v] [--cfile CFILE] [--hfile HFILE] [--filename FILENAME] [-R R] [file ...]

positional arguments:
  file                 File(s) or folder(s) you wanna run the parser on. If no file provided, runs on current folder.

optional arguments:
  -h, --help           show this help message and exit
  -d, --debug          Debug output (multiple values available)
  -o, --only-filename  By default norminette displays the full path to the file, this allows to show only filename
  -v, --version        show program's version number and exit
  --cfile CFILE        Store C file content directly instead of filename
  --hfile HFILE        Store header file content directly instead of filename
  --filename FILENAME  Stores filename if --cfile or --hfile is passed
  -R R                 compatibility for norminette 2

**Comment by daipom** [comment]
> various blocking errorsがなにかわからない

もしかしたら、プログラムの動作を停止させるようなエラーのことを言っているのかもしれません。

**Comment by daipom** [comment]
確かにreadmeのオプションの説明と、`$ norminette --help`の説明が一致していない感じがしますね。
`-d`の説明が異なっているし、`-dd`については`$ norminette --help`の方には出てこない、、

**Comment by katataku** [comment]
> もしかしたら、プログラムの動作を停止させるようなエラーのことを言っているのかもしれません。

ソースコードを確認したところ、「エラーの際に処理を停止させる」かどうかをこの引数で決定していました。
なので、READMEは正しそうでした。

**Comment by katataku** [comment]
>-dの説明が異なっているし、-ddについては$ norminette --helpの方には出てこない、、

-dの説明は合っているようでした。

-ddですが、-dのhelp内に (multiple values available)という記載が合ったので、これで表現しているのだと思います。
が、わかりにくいのでプルリク出します！！！

**Comment by katataku** [comment]
readmeがわかりにくい件、プルリクを出した。
https://github.com/42School/norminette/pull/270

**Comment by katataku** [comment]
helpオプションがわかりにくい件、修正方針が思いつかなかったのでissueを作った。

https://github.com/42School/norminette/issues/272
