### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2021-12-11: neutral2010: Simple: Work log

### ISSUE THREAD

**Issue by neutral2010** [oss-gate/workshop#1527]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by neutral2010** [comment]
Firefoxの拡張機能「Simple Translate」を入れてから不具合が生じているような気がするので、今日の対象として良いのではないか？

OSSかどうかを調べる。

Firefoxのツールバーを右クリックすると、[拡張機能管理](about:addons)のページに飛べた。

![image](https://user-images.githubusercontent.com/54997166/145664357-7295be56-6dc1-4374-9fad-b39d46033edc.png)

**Comment by neutral2010** [comment]
![image](https://user-images.githubusercontent.com/54997166/145664505-8abecc1f-94f3-4fb8-beb7-a00b37e16ed6.png)
FirefoxのADD - ONに飛ぶボタンがあったのでそこを押した。

**Comment by neutral2010** [comment]
飛んだ先のURL
https://addons.mozilla.org/ja/firefox/addon/simple-translate/

**Comment by neutral2010** [comment]
https://opensource.org/licenses/alphabetical

![image](https://user-images.githubusercontent.com/54997166/145664795-55d7fafa-4fea-4e2a-99ee-f49451d701c6.png)

**Comment by neutral2010** [comment]
オープンソースでした❗️

**Comment by neutral2010** [comment]
https://addons.mozilla.org/ja/firefox/addon/simple-translate/

このページから追加して入れたと思います。

既に、使っていて不具合がある（のではと思っている。）ので、それを再現したい。

**Comment by neutral2010** [comment]
「GitHubのページを探しましょう。」
これもADD-ONのページ 
https://addons.mozilla.org/ja/firefox/addon/simple-translate/ に載っていた。
https://github.com/sienori/simple-translate

**Comment by neutral2010** [comment]
## 不具合だと思っていたことは、実は便利機能だった❗️
最初に気がついたのは、日報を書いていてコピペしようとした時。
画面にこのアドオンの小さな画像が浮いている。

![image](https://user-images.githubusercontent.com/54997166/145665401-4ef9a898-7455-459e-a103-a2956e552bc9.png)

これは良いフィードバックだと思っていたら、機能だった。
![image](https://user-images.githubusercontent.com/54997166/145665422-a3e04b89-e6db-4d51-bd8e-7676f9f92b28.png)

画像をクリックすると、訳が出てくる。とても便利。

**Comment by neutral2010** [comment]
このアドオンを入れた経緯が、Firefoxでページ全体を訳せる機能が必要だったから。

部分的な翻訳ツールが別のものを使っていて必要がなかったので、画面右上に出るこちらばかり使っていた。（ページ全訳機能）
<img width="357" alt="image" src="https://user-images.githubusercontent.com/54997166/145665495-d62e8b23-2250-49ca-a40a-768c1eff5212.png">

**Comment by daipom** [comment]
これの画像がクリックすることですぐに翻訳結果を確認できる便利なボタンである、
ということが伝わりにくいというポイントがあるかもしれませんね。

こうだったらすぐ気づけたのに、というポイントがあるならぜひフィードバックを考えてみると良いと思います。

**Comment by neutral2010** [comment]
選択部分をすぐ訳してくれる機能は、使いやすいしとても便利。
もっと早く知っていたら、よりありがたいと思っていたに違いない
。
画像にカーソルが近づいた時に、お知らせしてくれるようなものがあると、分かりやすくてよいのではと思った。

**Comment by neutral2010** [comment]
ADD-ONの説明ページにはスクショがあるので、説明してくれているのだが、
https://addons.mozilla.org/ja/firefox/addon/simple-translate/ 
直感的に使えたり、その場ですぐ分かると便利。

**Comment by daipom** [comment]
ボタンが出た後画面を上下にスクロールすると、一緒にボタンも動いて変な感じになりますね。

**Comment by neutral2010** [comment]
選択すると画層が浮いている。じゃまでは？→ 設定できる。

そもそも、選択部分を瞬時に訳してくれるのが目玉機能だった。

https://addons.mozilla.org/ja/firefox/addon/simple-translate/ の説明も丁寧。

**Comment by neutral2010** [comment]
もっと押したくなるような画像だといいのでは。UIをより親切に。

**Comment by neutral2010** [comment]
> ボタンが出た後画面を上下にスクロールすると、一緒にボタンも動いて変な感じになりますね。
あ！そうなんですよね。そうでした。🙏

**Comment by neutral2010** [comment]
##今回の報告内容
ボタンが出た後画面を上下にスクロールすると、一緒にボタンも動いてくる。

**Comment by neutral2010** [comment]
既にissueが立ってないか調べる。

**Comment by neutral2010** [comment]
https://github.com/sienori/simple-translate/issues
検索 `scroll`
`is:open`を消してやると、`close`したものも対象になる。
閉じたものに対策が書いてある場合がある。

https://github.com/sienori/simple-translate/issues/171
既に立っていたが、古いissueにあるものなら、時間を経た今もまだ再現されることを報告するのもよい。

**Comment by neutral2010** [comment]
今立っているissueの内容を理解、ちゃんと読む。

**Comment by neutral2010** [comment]
現在、表示された翻訳ボタンも、同じような現象が起きるので報告します。

## 再現手順
macOS Montery 12.0.で、Firefox 95.0を起動する。
Simple Translate を https://addons.mozilla.org/ja/firefox/addon/simple-translate/ からインストールする。
設定で、「webページ、テキスト選択時の動作」は、「翻訳ボタンを表示」を選択。

GitHubのIssue入力ページを開き文章を選択すると、Simple Translateの翻訳ボタンが表示される。
その状態でページを上下にスクロールすると、Simple Translateの翻訳ボタンも一緒に上下する。

## 期待される結果
ページをスクロールし始めたら、Simple Translateの翻訳ボタンは消える。
または選択した部分の近く、最初に出現したところに留まっている。

## やらなかったこと
他のOSでは試していない

**Comment by neutral2010** [comment]
下書きとしてはこれでよい。

あとは、翻訳。

一つのコメントの中で、英語と日本語をまとめて記載する。

送り先　https://github.com/sienori/simple-translate/issues/171

**Comment by neutral2010** [comment]
I would like to report that currently the displayed translation button also causes the same problem.
 
 ## The steps for reappearance
 ### environment
 - macOS Montery 12.0.1（Intel Core i5
 - Firefox 95.0
1. Install "Simple Translate" from https://addons.mozilla.org/ja/firefox/addon/simple-translate.
In setting,select "Show translation button" at web page/behavior when selecting text.
1. Open issue of GitHub, "https://github.com/sienori/simple-translate/issues/171", select texts.
Translation button appears.

![image](https://user-images.githubusercontent.com/54997166/145669445-090a9e6d-9e89-48d4-984b-4bb8199d8db1.png)

So if I scroll up the page, or down tha page,Translation button moves up or down together.

・Scroll up the page

・Scroll down the page

## Expected results
At 4th step in the steps for reappearance, if I start to scroll, translation button will take off, or it stays at the place that it appeared first.

## It is that I didn't try
・other OS
・I didn't at Chrome

**Comment by daipom** [comment]
@neutral2010  お疲れ様です！レビュー遅くなり申し訳ありません！

翻訳版拝見しました。
全体的に英語はそこまで気にしなくても伝わると思いますが、
以下の点を修正頂いたらもっと伝わりやすくなるかなと思いました。

* `再現`という日本語の翻訳について
  * `reappearance`という名詞よりも、`reproduce`という動詞を使うのが一般的と思います
  * `The steps for reappearance` -> `The steps to reproduce`
* 1番めの再現手順
  * 日本語: `設定で、「webページ、テキスト選択時の動作」は、「翻訳ボタンを表示」を選択。`
  * 英語: `In setting,select "Show translation button" at web page/behavior when selecting text.`
  * `web page/behavior when selecting text`も`"`などで囲ってあげて、ボタンやラベルの名前であると伝わるようにしてあげると良いと思います
  * `In setting, select "Show translation button" at "web page/behavior when selecting text".`
* 日本語の手順と番号が異なる点について
  * 無理に合わせる必要はないと思いますが、あとで`「再現手順の4」において`（`At 4th step in the steps for reappearance,`）と言う箇所があるので、そこは調整したほうが良さそうです。
  * 英語においては、次の文章を3番目の手順として、`Expected result`における`At 4th step`を`At 3th step`にするのはどうでしょう？
    * `So if I scroll up the page, or down the page,Translation button moves up or down together.`
* `やらなかったこと`の英語訳`It is that I didn't try`について
  * 個人的な感覚かもしれませんが英語に違和感があります。`What I didn't try`などのほうが良いかもしれません。

**Comment by piroor** [comment]
reappearance/reproduceのところについてやいのやいの議論していたので、そこの所を少し補足です！

* OSS界隈だと、「再現手順」は「Steps to reproduce」で成句みたいになってる感じがあります。
* produce（主語の誰か・何かが、外力を加えて、目的語の何かを作る・起こす・発生させる）とappear（主語の誰か・何かが、自発的に発生する）というそれぞれのニュアンスの違いに基づいて考えても、「誰かが現象を再現させる」という場面では「re-appear」よりは「re-produce」の方が、元々表したかった意図により近い言葉と言えそうです。

**Comment by neutral2010** [comment]
## レビュー内容を取り入れる
 
 I would like to report that currently the displayed translation button also causes the same problem.
 
 ## Steps to reproduce
 ### environment
 - macOS Montery 12.0.1（Intel Core i5
 - Firefox 95.0
1. Install "Simple Translate" from https://addons.mozilla.org/ja/firefox/addon/simple-translate.
In setting,select "Show translation button" at "web page/behavior when selecting text".
1. Open issue of GitHub, "https://github.com/sienori/simple-translate/issues/171", select texts.
Translation button appears.

![image](https://user-images.githubusercontent.com/54997166/145669445-090a9e6d-9e89-48d4-984b-4bb8199d8db1.png)

3. So if I scroll up the page, or down the page,Translation button moves up or down together.

・Scroll up the page
![image](https://user-images.githubusercontent.com/54997166/145669649-a2b728f3-ff6e-41c1-b653-c0060a52adac.png)

・Scroll down the page
![image](https://user-images.githubusercontent.com/54997166/145669896-d939e8b3-c82d-42f1-83c8-583abb6ddfe3.png)

## Expected result
At 3th step in Steps to reproduce, if I start to scroll, translation button will take off, or it stays at the place that it appeared first.

## What I didn't try
・other OS
・I didn't try at Chrome

**Comment by neutral2010** [comment]
英訳：思っていたより、やればできた。

丁寧にレビューしていただいてありがたい。

- 決まり文句は是非知りたい。
- 注意すれば自分でも気がつけたこともあったので、これからは「全然ダメに違いない」という弱気な姿勢ではなく、積極的な気持ちで向かおう。

**Comment by neutral2010** [comment]
[sienori/simple-translate#171 ](sienori/simple-translate#171)へのコメントとして、フィードバックした。
英語と日本語を併記。
