### ISSUE TITLE
アンケート回答時のActionがエラーになる

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1532]
https://github.com/oss-gate/workshop/runs/4492163946?check_suite_focus=true

**Comment by itotoshinori** [comment]
![start](https://user-images.githubusercontent.com/20299252/145671814-2fcba7f9-be07-437d-9a04-6adacb41d309.png)
こちらからどうすすめたらいいですか

**Comment by itotoshinori** [comment]
type: beginner
questions:
  # 参加した理由
  motivation:
    # 将来的にはオープンソースにも参画したしたいと思いその第一歩として
    (ここに回答を改行を入れずに書いてください)
  # 見つけた場所
  via:
    # どこでこのワークショップを知りましたか？
    doorkeeprの周知メールから
    (ここに回答を改行を入れずに書いてください)
  # 開発対象
  target:
    # ワークショップで開発対象に選んだOSSはなんですか？
    Ruby
    (ここに回答を改行を入れずに書いてください)
  # 満足度
  satisfaction-rating:
    # ↓のうち当てはまるものだけを残してください。
    - すごく満足した
  # 想定との違い
  difference:
    # ↓のうち当てはまるものだけを残してください。
    - 想定通りだった
  # 進行役について
  moderator:
    # 進行役はうまく進行できていましたか？
    はい
    # 進行役の説明はどうでしたか？
    わかりやすかった
    # スライドの内容を理解するのに役立ちましたか？
    (ここに回答を改行を入れずに書いてください)はい
  # サポートメンターについて
  support-mentor:
    # サポートメンターはサポーターがいないときの代役としてうまくフォローできていましたか？
    はい
    # サポートメンターはサポーターをうまくフォローできていましたか？
    はい
    (ここに回答を改行を入れずに書いてください)
  # 次回のOSS Gateワークショップについて
  next:
    # (複数選択)↓のうち当てはまるものをすべて残してください。
    - ビギナーとして参加する
  # 今後のOSSの開発への参加について
  future:
    # ↓のうち当てはまるものだけを残してください。
    - 機会を作って積極的に開発に参加する
  # 次に変えて試すこと
  challenge-planning:
    # ワークショップの内容を何か1つだけ変えられるとしたら、
    実際のオープンソースを制作してるところがみれたらいいですね
    
    # どんなことを試したいと思いますか？
    (ここに回答を改行を入れずに書いてください)gem開発
  # その他
  etc:
    # なにか思ったことがあれば自由に書いてください。
    (ここに回答を改行を入れずに書いてください)公式サイトをみることの大切再認識しました

**Comment by knokmki612** [comment]
レポートありがとうございます、 https://github.com/oss-gate/workshop/pull/1534 でも同様のエラーが発生し動作時エラーを起こしていますね

**Comment by knokmki612** [comment]
対処したつもりですが、動作確認もしくはテストができていないですね…一旦完了とし再度問題あればreopenするか、適当なタイミングで同様の問題が生じていないようであれば完了とするなどお願いします :pray:

**Comment by knokmki612** [comment]
#1554 でも同様の問題が生じていますでしょうか…？（以前のログはすでに破棄されており確認しようがなかった）

https://github.com/oss-gate/workshop/runs/5474907568?check_suite_focus=true

```
Run oss-gate/issue-cleaner@v3
  with:
    DOORKEEPER_GROUP: oss-gate
    CONNPASS_KEYWORD: oss gate
    author: irasally
    GITHUB_TOKEN: ***
  env:
    DOORKEEPER_TOKEN: 
FetchError: invalid json response body at https://api.doorkeeper.jp/groups/oss-gate/events reason: Unexpected end of JSON input
    at /home/runner/work/_actions/oss-gate/issue-cleaner/v3/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/runner/work/_actions/oss-gate/issue-cleaner/v3/lib/main.js:22:11) {
  type: 'invalid-json'
}
```

**Comment by piroor** [comment]
みたいですね。
これは、どんなレスポンスが返ってきているのか確認できるものなんでしょうか？

**Comment by kou** [comment]
> そもそもOSS Gateのイベントを取得してコメント案内するという施策が、もはや継続参加率の向上に寄与していないような気もして

たしかに！

>  この機能をドロップするのでもいいような気はしました

そうしましょう！

**Comment by knokmki612** [comment]
ご意見ありがとうございます、

現状勝手な構想としては、もはやactionとして再利用可能な形ではなく、ワークショップのissueタイトルのパースをおこなう部分のみnpmパッケージとして管理して、GitHub APIを叩くワークフローは
https://github.com/actions/github-script
に任せるようにするといいのかなと思っています。
詳細は別途 https://github.com/oss-gate/issue-cleaner でissueにするなり検討しようかと思います

**Comment by daipom** [comment]
#1558 で 一時的に直った/直らなかった のか、当時の状況を追えていませんが、
とりあえず最近エラーになっているみたいです。

https://github.com/oss-gate/workshop/actions/runs/3350609457/jobs/5551524341

現在自分は普通の`clean-all-issue`の方を手動トリガーしてクリーンしています。

https://github.com/oss-gate/workshop/actions/workflows/clean-all-issue.yaml

**Comment by daipom** [comment]
`Resource not accessible by integration`のエラーメッセージをちょっと調べると、次のようにリポジトリの設定がworkflowに書き込み権限を与えていない可能性があるのかなと思いました。

https://zenn.dev/tatsugon/articles/github-actions-permission-error

自分はリポジトリの設定を見る権限が無さそうなので、確かめられません。

**Comment by daipom** [comment]
設定を変えれば直る、かつその設定で問題ないのであればそうしたいです。
一方で、wrokshop終了後に`clean-all-issue`を手動トリガーするフローでも良い気はします。

**Comment by knokmki612** [comment]
最近の状況追えてなかったので助かります。

もし書き込み権限がないことが原因だとすれば、clean-all-issueが動き続けているのもなんだか不可解という気がしますね…

私もその件調査するか、 https://github.com/oss-gate/workshop/issues/1532#issuecomment-1152378055 の構想にあるようなものを別途用意しよりメンテナンス性のよさそうなツールへの移行作業を進めるかしようと思いました。

**Comment by kou** [comment]
pull requestだとpull requestを作った人の権限で動いて手動実行だと`oss-gate`権限で動くからじゃないですかねぇ。

`on.pull_request`じゃなくて`on.pull_request_target`を使ってpull request内の`.github/workflows/`じゃなくてデフォルトブランチの`.github/workflows/`を使うようにすれば`oss-gate`権限で動くようになりそう。

**Comment by kou** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by daipom** [comment]
@knokmki612 @kou ありがとうございます！！

> もし書き込み権限がないことが原因だとすれば、clean-all-issueが動き続けているのもなんだか不可解という気がしますね…

> pull requestだとpull requestを作った人の権限で動いて手動実行だと`oss-gate`権限で動くからじゃないですかねぇ。
> 
> `on.pull_request`じゃなくて`on.pull_request_target`を使ってpull request内の`.github/workflows/`じゃなくてデフォルトブランチの`.github/workflows/`を使うようにすれば`oss-gate`権限で動くようになりそう。

なるほど！！まずは次回に向けてこの辺りを修正してみます！！

**Comment by knokmki612** [comment]
共有いただいたドキュメントにもありますが、 `pull_request_target` トリガーは外部のユーザーに対して読み書き権限を与え、secretsにアクセス可能にするので、取扱いに気をつける必要がありそうですね

> Warning: For workflows that are triggered by the pull_request_target event, the GITHUB_TOKEN is granted read/write repository permission unless the permissions key is specified and the workflow can access secrets, even when it is triggered from a fork. Although the workflow runs in the context of the base of the pull request, you should make sure that you do not check out, build, or run untrusted code from the pull request with this event. Additionally, any caches share the same scope as the base branch. To help prevent cache poisoning, you should not save the cache if there is a possibility that the cache contents were altered. For more information, see "[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)" on the GitHub Security Lab website.
 
参考 https://zenn.dev/odan/scraps/cce2165dc91080

もしかしたらpushトリガーで動作させる方が考えることが少なくなっていいかもしれません（その場合Github Actionに渡しているauthorパラメータをどうやって用意するのか問題が発生しそうな気がしますが）

**Comment by kou** [comment]
今回のケースだとすべて`oss-gate` organization管理のコードしか使っていないように見えるので大丈夫だと思いますけど、気になるならpull reuqestでの発動はやめて手動実行でいい気がします。

**Comment by knokmki612** [comment]
> すべてoss-gate organization管理のコードしか使っていないように見えるので大丈夫だと思いますけど

たしかに clean-issue-with-pr ワークフローは PR 提出者の追加したコードを参照するわけではないですし問題なさそうですね。
指摘取り下げます。

**Comment by daipom** [comment]
とりあえず `pull_request_target` を使うようにしてみました！これでしばらく様子を見てみたいと思います！
みなさんアドバイスありがとうございました！

**Comment by daipom** [comment]
https://github.com/oss-gate/workshop/blob/c6139d1a07a5fae9a0270d4de6f11d0bae0e849e/.github/workflows/clean-issue-with-pr.yaml#L2-L6

本日のworkshopで試運転してみたが、issueが閉じられなかった。

https://github.com/oss-gate/workshop/actions/runs/3663685375/jobs/6193618360

自分のforkリポジトリで試したときは想定通り動作していた。
PRのマージを実行したユーザーを認識して動作している？
だとしたら`types`を`closed`ではなくて`opened`にしたら良いかもしれない。
(もう少しちゃんと`pull_request_target`の仕組みと`clean-issue-with-pr`の仕組みを理解しないと、、)

**Comment by daipom** [comment]
想定通りopenedにしたら動いた！！
