### ISSUE TITLE
OSS Gate Workshop: Online: 2022-01-29: ikuma-t: slidev: Work log

### ISSUE THREAD

**Issue by IkumaTadokoro** [oss-gate/workshop#1538]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daipom** [comment]
ライセンスがOSSだと良いですね！

**Comment by IkumaTadokoro** [comment]
Slidevというプレゼンテーション作成ツールをこの前少し触ったので、これに貢献できないかみてみます！

**Comment by IkumaTadokoro** [comment]
- HP: https://sli.dev/
- GitHub: https://github.com/slidevjs/slidev

ライセンスを確認
→ https://github.com/slidevjs/slidev/blob/main/LICENSE

![CleanShot 2022-01-29 at 11 30 18](https://user-images.githubusercontent.com/61409641/151643860-c5d046aa-94f8-4262-a111-25fd6c6f7d33.png)

MITライセンスなので、OSSと言えそう！

refs: https://opensource.org/licenses/MIT

**Comment by IkumaTadokoro** [comment]
前に一回触ったことあるけど、雰囲気で触っただけだったので、ドキュメントを読みながら順番に試していきたいです！

**Comment by IkumaTadokoro** [comment]
まずはリポジトリのREADMEを追っていく感じにします。
https://github.com/slidevjs/slidev

**Comment by IkumaTadokoro** [comment]
https://github.com/slidevjs/slidev#getting-started

Getting Startedがあるので、これをもとに試すとよさそう。
オンライン上で試す方法があるので、まずはこれを試します。

**Comment by IkumaTadokoro** [comment]
https://github.com/slidevjs/slidev#try-it-online-%EF%B8%8F
にあるとおり、StackBlitz？ってやつでWeb上でスライドを動かすことができた。

![image](https://user-images.githubusercontent.com/61409641/151644093-c436b447-eec2-42e5-ad01-5d4a9b0db09a.png)

**Comment by IkumaTadokoro** [comment]
次に https://github.com/slidevjs/slidev#init-project-locally にあるとおり、ローカル上でスライドを作成してみます。

Node.js >= 14以上が必要みたいなので、自分のバージョンを確認
```bash
$ node -v
v16.13.1
```

v14より大きいので、コマンドを実行してインストールします。

**Comment by IkumaTadokoro** [comment]
インストールコマンドを実行した

```bash
npm init slidev
Need to install the following packages:
  create-slidev
Ok to proceed? (y) y

  ●■▲
  Slidev Creator  v0.27.20

✔ Project name: … slidev-sample
  Scaffolding project in slidev-sample ...
  Done.

✔ Install and start it now? … yes
✔ Choose the agent › npm

added 317 packages, and audited 318 packages in 36s

53 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> dev
> slidev --open



  ●■▲
  Slidev  v0.27.20

  theme   @slidev/theme-seriph
  entry   /Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample/slides.md

  slide show      > http://localhost:3030/
  presenter mode  > http://localhost:3030/presenter
  remote control  > pass --remote to enable

  shortcuts       > restart | open | edit


Sourcemap for "/@slidev/slides/3.md" points to missing source files
Sourcemap for "/@slidev/slides/6.md" points to missing source files
Sourcemap for "/@slidev/slides/7.md" points to missing source files
Sourcemap for "/@slidev/slides/8.md" points to missing source files
Sourcemap for "/@slidev/slides/10.md" points to missing source files
Sourcemap for "/@slidev/slides/2.md" points to missing source files
Sourcemap for "/@slidev/slides/5.md" points to missing source files
Sourcemap for "/@slidev/slides/9.md" points to missing source files
Sourcemap for "/@slidev/slides/4.md" points to missing source files
Sourcemap for "/@slidev/slides/1.md" points to missing source files
```

インストール完了と同時にローカルでslidevが立ち上がって、スライドが`http://localhost:3000`で立ち上がった

![CleanShot 2022-01-29 at 11 47 16](https://user-images.githubusercontent.com/61409641/151644374-764740a8-dc7f-4085-89a7-3fae23fb857e.png)

**Comment by IkumaTadokoro** [comment]
https://github.com/slidevjs/slidev#getting-started にある`init`以降の説明は

> Documentations: English | 中文文档 | Français | Español | Русский | Português-BR

ドキュメントを参照とのこと。英語・中国語・フランス語・スペイン語・ロシア語？・ポルトガル語はあるけど、日本語はない。日本語のドキュメントがあってもいいかもしれない...!

**Comment by IkumaTadokoro** [comment]
Documentationを案内されているけど、一旦READMEを最後まで読みきります。

**Comment by IkumaTadokoro** [comment]
- 技術スタック： https://github.com/slidevjs/slidev#tech-stack
- Sponsors: https://github.com/slidevjs/slidev#sponsors

があるだけだったので、[英語版のドキュメント](https://sli.dev/)を見ながら実際のスライド作成操作を試してみます。

**Comment by IkumaTadokoro** [comment]
https://sli.dev/guide/#command-line-interface

CLIがnpm scriptとして定義されているので、一度自動起動したサーバーを停止して、コマンドで起動できるか試してみる。

**Comment by IkumaTadokoro** [comment]
記載のあった`dev`コマンド（実行時は`npm run dev`）で起動ができた。

![CleanShot 2022-01-29 at 12 03 47](https://user-images.githubusercontent.com/61409641/151644890-9cb5ae10-b698-4f27-9749-8f99cecb1eb1.png)

**Comment by IkumaTadokoro** [comment]
`npm run build`も問題なく終了できた。

**Comment by IkumaTadokoro** [comment]
`npm run export`が以下のようなログを出力してエラーになった。

```bash
$ npm run export

> export
> slidev export



  ●■▲
  Slidev  v0.27.20 

  theme   @slidev/theme-seriph
  entry   /Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample/slides.md


Error: The exporting for Slidev is powered by Playwright, please installed it via `npm i playwright-chromium`
    at exportSlides (/Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample/node_modules/@slidev/cli/dist/export-FUMCNU5W.js:66:11)
    at Object.handler (/Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample/node_modules/@slidev/cli/dist/cli.js:274:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by IkumaTadokoro** [comment]
ログ出力の通りに、`npm -i playwright-chromium`を実行してみる。

```bash
$ npm i playwright-chromium

added 37 packages, and audited 355 packages in 39s

56 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

再度`npm run export`を実行したら、exportができた。

```bash
$ npm run export

> export
> slidev export

Pre-bundling dependencies:
  @antfu/utils
  @slidev/parser
  @vueuse/head
  @vueuse/motion
  codemirror
  (...and 24 more)
(this will be run only when your dependencies or config have changed)


  ●■▲
  Slidev  v0.27.20 

  theme   @slidev/theme-seriph
  entry   /Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample/slides.md


  ■ rendering ███░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1/10Sourcemap for "/@slidev/slides/3.md" points to missing source files
Sourcemap for "/@slidev/slides/6.md" points to missing source files
Sourcemap for "/@slidev/slides/7.md" points to missing source files
Sourcemap for "/@slidev/slides/8.md" points to missing source files
Sourcemap for "/@slidev/slides/10.md" points to missing source files
Sourcemap for "/@slidev/slides/2.md" points to missing source files
Sourcemap for "/@slidev/slides/5.md" points to missing source files
Sourcemap for "/@slidev/slides/9.md" points to missing source files
Sourcemap for "/@slidev/slides/4.md" points to missing source files
Sourcemap for "/@slidev/slides/1.md" points to missing source files
  ✓ exported to ./slides-export.pdf
```

**Comment by IkumaTadokoro** [comment]
https://sli.dev/guide/#command-line-interface

**Comment by daipom** [comment]
https://sli.dev/guide/exporting.html
こっちに依存に関して記載があるようですね。

**Comment by piroor** [comment]
https://github.com/slidevjs/slidev/blob/209dd412b151afc8b051bb57963a0198b334f980/package.json#L65
devDependenciesの方にはあるんですね。
なんでdependenciesにないんだろう？

**Comment by IkumaTadokoro** [comment]
piroorさんに頂いたコメントと相談して気がついたフィードバックポイント

1. `playwright-chromium`がslidevのdevDependenciesにあるのに、dependenciesにないのはなぜだろうか。slidevインストール時に一括で入れてはだめ？
1. `playwright-chromium`がない場合、https://github.com/oss-gate/workshop/issues/1538#issuecomment-1024818796 では`npm i playwright-chromium`を促されるけど、https://github.com/oss-gate/workshop/issues/1538#issuecomment-1024819788 に書いていただいたドキュメントでは`npm i -D playwright-chromium`でインストールするように書いてあるので、齟齬がある。統一した方がいいのでは？

2の方が個人的に気になったので、午後はこれを整理していきたいです。

**Comment by IkumaTadokoro** [comment]
そもそも`npm i -D playwright-chromium`にしても、`npm run export`が動くのかどうかを念のためチェックします。

- [ ] 新規サンプルプロジェクトを作成
- [ ] `npm run export`を実行：エラーになることを期待
- [ ] `npm i -D playwright-chromium`を実行
- [ ] `npm run export`を実行：動くことを期待

**Comment by IkumaTadokoro** [comment]
`npm i -D playwright-chromium`でも問題ないことは確認できた（dependenciesに落とすのと、どっちがいいのかはわからないけど）

---

- `npm run export`

期待通り、playwright-chromiumがないことで失敗する

```bash
npm run export

> export
> slidev export



  ●■▲
  Slidev  v0.27.20

  theme   @slidev/theme-seriph
  entry   /Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample2/slides.md


Error: The exporting for Slidev is powered by Playwright, please installed it via `npm i playwright-chromium`
    at exportSlides (/Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample2/node_modules/@slidev/cli/dist/export-FUMCNU5W.js:66:11)
    at Object.handler (/Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample2/node_modules/@slidev/cli/dist/cli.js:274:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

- `npm i -D playwright-chromium`

package.jsonはこんな感じ。ちゃんとdevDependenciesとして入っている。

```json
{
  "private": true,
  "scripts": {
    "build": "slidev build",
    "dev": "slidev --open",
    "export": "slidev export"
  },
  "dependencies": {
    "@slidev/cli": "^0.27.20",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"
  },
  "name": "slidev-sample2",
  "devDependencies": {
    "playwright-chromium": "^1.18.1"
  }
}
```

- `npm run export`

期待通り、正常にexportが完了する。

```bash
npm run export

> export
> slidev export

Pre-bundling dependencies:
  @antfu/utils
  @slidev/parser
  @vueuse/head
  @vueuse/motion
  codemirror
  (...and 24 more)
(this will be run only when your dependencies or config have changed)


  ●■▲
  Slidev  v0.27.20

  theme   @slidev/theme-seriph
  entry   /Users/tadokoroikuma/sandbox/slidev-sample/slidev-sample2/slides.md


  ■ rendering ███░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1/10Sourcemap for "/@slidev/slidess
Sourcemap for "/@slidev/slides/7.md" points to missing source files
Sourcemap for "/@slidev/slides/10.md" points to missing source files
Sourcemap for "/@slidev/slides/6.md" points to missing source files
Sourcemap for "/@slidev/slides/8.md" points to missing source files
Sourcemap for "/@slidev/slides/2.md" points to missing source files
Sourcemap for "/@slidev/slides/5.md" points to missing source files
Sourcemap for "/@slidev/slides/9.md" points to missing source files
Sourcemap for "/@slidev/slides/4.md" points to missing source files
Sourcemap for "/@slidev/slides/1.md" points to missing source files
  ✓ exported to ./slides-export.pdf
```

**Comment by IkumaTadokoro** [comment]
## 伝えたいこと

- `slidev export`コマンドは`playwright-chromium`に依存しているため、初回実行時にはこれをインストールする必要がある。
- [Guide - Exporting](https://sli.dev/guide/exporting.html#exporting)では、`npm i -D playwright-chromium`を実行するように記載があるが、`playwright-chromium`がインストールされていない場合に`slidev export`コマンドを実行した際のログには`npm i playwright-chromium`を実行するように記載があるため、これを統一した方がいいと思う。

## 気になっていること

- `install`と`install -D`のどちらに合わせた方がいいか

**Comment by IkumaTadokoro** [comment]
類似Issueがないか確認します。

ドキュメントに関しては、別リポジトリで管理されているので、以下のリポジトリを確認します。

- https://github.com/slidevjs/docs
- https://github.com/slidevjs/slidev

**Comment by IkumaTadokoro** [comment]
`playwright-chromium`で確認しましたが、どちらのリポジトリにも重複Issueはなさそうでした。

**Comment by IkumaTadokoro** [comment]
## 補足

https://github.com/slidevjs/slidev/commit/73fcba28c7dab53809d49d81dd17df0f5c35b660

- コマンド実行時のメッセージ
- ドキュメントの記載

は同じコミットで追加されたみたいです。

**Comment by IkumaTadokoro** [comment]
> ## 気になっていること
> * `install`と`install -D`のどちらに合わせた方がいいか

動かして気がついたことなので、リポジトリ本体の方にIssueを立てる方針にします。

**Comment by IkumaTadokoro** [comment]
https://github.com/slidevjs/slidev/issues/new/choose

**Comment by daipom** [comment]
> ## 補足
> 
> [slidevjs/slidev@73fcba2](https://github.com/slidevjs/slidev/commit/73fcba28c7dab53809d49d81dd17df0f5c35b660)
> 
>     * コマンド実行時のメッセージ
> 
>     * ドキュメントの記載
> 
> 
> は同じコミットで追加されたみたいです。

コミットまで特定できたのはとても良いですね！
報告するときも、
「コミットoxoxで追加されているけど、これ片方間違っていないですか？」
という感じで具体的に書くことができそうですね

**Comment by IkumaTadokoro** [comment]
**Describe the bug**
The installation method of `playwright-chromium`, which is required for `slidev export`, is different between the `slidev export` error log and the [documentation: Exporting | slidev](https://sli.dev/guide/exporting.html#pdf).
Either of these will not affect the behavior of `slidev export`, but the description is different as follows.

- Error Log suggests: `npm i playwright-chromium`  
- Documentation suggests: `npm i -D playwright-chromium`  

Both of these explanations were added in commit: https://github.com/slidevjs/slidev/commit/73fcba28c7dab53809d49d81dd17df0f5c35b660 
Could either of these be wrong?

**To Reproduce**
Steps to reproduce the behavior:
1. Create new slidev project by `npm init slidev`
2. Run `npm run export`
3. See the error

**Desktop (please complete the following information):**
 - OS: macOS Monterey(12.1)
 - Browser: Google Chrome:  97.0.4692.99（Official Build） （x86_64）
 - Slidev version: 0.27.20

**Comment by daipom** [comment]
Run `npm run export` without running `npm i - D playwright-chromium`.

**Comment by IkumaTadokoro** [comment]
アドバイスいただいた内容と、一部冠詞を修正

--- 





**Describe the bug**
The installation method of `playwright-chromium`, which is required for `slidev export`, is different between the `slidev export` error log and the [documentation: Exporting | slidev](https://sli.dev/guide/exporting.html#pdf).
Either of these will not affect the behavior of `slidev export`, but the description is different as follows.

- Error Log suggests: `npm i playwright-chromium`  
- Documentation suggests: `npm i -D playwright-chromium`  

Both of these explanations were added in commit: https://github.com/slidevjs/slidev/commit/73fcba28c7dab53809d49d81dd17df0f5c35b660 
Could either of these be wrong?

**To Reproduce**
Steps to reproduce the behavior:
1. Create a new slidev project by `npm init slidev`
2. Run `npm run export` without running `npm i -D playwright-chromium`
3. See the error

**Desktop (please complete the following information):**
 - OS: macOS Monterey(12.1)
 - Browser: Google Chrome:  97.0.4692.99（Official Build） （x86_64）
 - Slidev version: 0.27.20

**Comment by IkumaTadokoro** [comment]
この内容でIssueを立てたいと思います！

**Comment by IkumaTadokoro** [comment]
## The installation of `playwright-chromium` is different between the documentation and the error log.





**Describe the bug**
The installation method of `playwright-chromium`, which is required for `slidev export`, is different between the `slidev export` error log and the [documentation: Exporting | slidev](https://sli.dev/guide/exporting.html#pdf).
Either of these will not affect the behavior of `slidev export`, but the description is different as follows.

- Error Log suggests: `npm i playwright-chromium`  
- Documentation suggests: `npm i -D playwright-chromium`  

Both of these explanations were added in commit: https://github.com/slidevjs/slidev/commit/73fcba28c7dab53809d49d81dd17df0f5c35b660 
Could either of these be wrong?

As mentioned above, it does not affect the operation, but I think it is better to unify one or the other.

**To Reproduce**
Steps to reproduce the behavior:
1. Create a new slidev project by `npm init slidev`
2. Run `npm run export` without running `npm i -D playwright-chromium`
3. See the error

**Desktop (please complete the following information):**
 - OS: macOS Monterey(12.1)
 - Browser: Google Chrome:  97.0.4692.99（Official Build） （x86_64）
 - Slidev version: 0.27.20

**Comment by IkumaTadokoro** [comment]
https://github.com/slidevjs/slidev/issues/469

Issue立てられました！！🎉

**Comment by piroor** [comment]
Git blameを活用して対象コミットを特定したのはナイス！
