### ISSUE TITLE
OSS Gate Workshop: online: 2022-01-29:Risa Nishikawa: sakura-editor: Work log

### ISSUE THREAD

**Issue by risa-nishikawa** [oss-gate/workshop#1539]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by risa-nishikawa** [comment]
仕事で使っているサクラエディタについてライセンスを調べます。

**Comment by risa-nishikawa** [comment]
公式サイトを見つけました。

https://sakura-editor.github.io/

**Comment by risa-nishikawa** [comment]
githubを見つけました。

https://github.com/sakura-editor/sakura/wiki

**Comment by risa-nishikawa** [comment]
https://github.com/sakura-editor/sakura/blob/master/LICENSE

**Comment by risa-nishikawa** [comment]
下記ページにアクセス。

https://github.com/sakura-editor/sakura/wiki/License

ライセンスについて、下記記載あり。
"サクラエディタ本体はzlib licenseで開発＆配布しています。"

**Comment by risa-nishikawa** [comment]
下記サイトで、「zlib/libpng license (Zlib)」を発見。

https://opensource.org/licenses/alphabetical

OSSであることを確認できました。

**Comment by risa-nishikawa** [comment]
端末上にインストール済みなので、インストールは割愛します。

**Comment by risa-nishikawa** [comment]
<img width="915" alt="スクリーンショット 2022-01-29 115248" src="https://user-images.githubusercontent.com/74892321/151644635-f9a7dfe3-dcc1-46d9-a8d6-85d517f8aa17.png">

正規表現エラーの際、内容が英語で表示されるのが気になっていたので、
再現させてスクリーンショットを取りました。

**Comment by risa-nishikawa** [comment]
再現手順

・エディタを開く
・Ctrl+Fで検索ウィンドウを開く
・「正規表現」にチェックをつける
・「条件」に正規表現の不正なパターン(今回は"[[")を入力
・「上検索」もしくは「下検索」ボタンを押下
・正規表現エラーのメッセージボックスが表示される

このとき、エラー内容が英語で(今回は"premature end of char-class")表示される
エラーの内容が日本語で表示されるようになってほしい

**Comment by piroor** [comment]
https://github.com/sakura-editor/sakura/blob/df7c2cd9433b39e8b6154dd877a15d5409bfd214/sakura_core/extmodule/CBregexp.h
https://sakura-editor.github.io/help/HLP000006.html
BREGEXPというライブラリを使ってるみたいですね。

**Comment by piroor** [comment]
https://github.com/sakura-editor/sakura/blob/df7c2cd9433b39e8b6154dd877a15d5409bfd214/sakura_core/extmodule/CBregexp.cpp#L649-L685
ここで文法チェックの結果のメッセージを表示してるっぽいです。
`cRegexp.GetLastMessage()`の結果をローカライズできるといいのかなあ。

**Comment by piroor** [comment]
https://github.com/k-takata/bregonig 正規表現ライブラリのリポジトリ

**Comment by risa-nishikawa** [comment]
エラーメッセージのローカライズについて、サクラエディタ側と正規表現ライブラリ側のどちらでするのが適切なのかの検討も必要

公式サイトから、報告先はgithubのissueで良さそう


・公式サイト
https://sakura-editor.github.io/

GitHub Issues … 要望・バグ報告等はこちらからご連絡ください (GitHubユーザー登録が必要です。）

・サクラエディタ　issue
https://github.com/sakura-editor/sakura/issues

・正規表現ライブラリ
https://github.com/k-takata/bregonig

**Comment by risa-nishikawa** [comment]
一旦サクラエディタのissueにあげて、ライブラリ側にあげるべきかどうかの質問を添える

**Comment by risa-nishikawa** [comment]
**困っていること**
正規表現エラーの内容が英語で表示されます。

<img width="915" alt="スクリーンショット 2022-01-29 115248" src="https://user-images.githubusercontent.com/74892321/151649094-c48b146c-bcfc-494d-8d17-9d33a3e6f56c.png">

**再現手順**

・エディタを開く
・Ctrl+Fで検索ウィンドウを開く
・「正規表現」にチェックをつける
・「条件」に正規表現の不正なパターン(今回は"[[")を入力
・「上検索」もしくは「下検索」ボタンを押下
・正規表現エラーのメッセージボックスが表示される(今回はエラー内容が"premature end of char-class"となっている)

**期待する動作**

エラーの内容が日本語で表示される方が分かりやすいと思います。

**補足**
対応について、サクラエディタ側で日本語に直す方法と、ライブラリ側で日本語に直す方法が想定されます。
ライブラリ側での対応が適切であれば、そちらのissueとして報告しますが、いかがでしょうか？

**Comment by risa-nishikawa** [comment]
報告しました。

https://github.com/sakura-editor/sakura/issues/1780
