### ISSUE TITLE
OSS Gate Workshop: online: 2022-01-29: kaz: vue-loading: Work log

### ISSUE THREAD

**Issue by ktsukamoto1** [oss-gate/workshop#1540]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ktsukamoto1** [comment]
最近、現場で使っているVue.jsで、ローディングのライブラリを調べてみた。
https://kouya17.com/posts/26/
その中で、以下のものを選んでみた。
https://github.com/jkchao/vue-loading

**Comment by ktsukamoto1** [comment]
MITライセンス
MIT License (MIT)

**Comment by ktsukamoto1** [comment]
インストール方法は以下らしい。
npm install vue-loading-template --save

**Comment by daipom** [comment]
OSSですね！インストールして動かしてみてください！

**Comment by ktsukamoto1** [comment]
インストール結果は以下のように出てインストールが無事できた模様。

```html
npm install vue-loading-template --save
added 4 packages, and audited 1984 packages in 38s

100 packages are looking for funding
  run `npm fund` for details

124 vulnerabilities (4 low, 99 moderate, 21 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by ktsukamoto1** [comment]
visual studio codeがインストール済みなので、editorはにこれを使う。

**Comment by ktsukamoto1** [comment]
以下のように一旦コードを入れてみた。

```html
<template>
  <div class="home">
    <vue-loading type="bars" color="#d9544e" :size="{ width: '50px', height: '50px' }"></vue-loading> 　←ここに入れた。
    <img alt="MDB logo" src="../assets/logo-mdb-vue-small.png">
    <HelloWorld msg="Welcome to Your MDB Vue.js App"/>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/components/HelloWorld.vue'

export default {
  name: 'home',
  components: {
    HelloWorld
  }
}
</script>

```

**Comment by ktsukamoto1** [comment]
![スクリーンショット (7)](https://user-images.githubusercontent.com/19473108/151645065-6190c219-5e94-4408-bae7-b35691243d2c.png)

**Comment by ktsukamoto1** [comment]
サンプルのソースをきちんと見ていなかった。
```
<template>
  <div class="home">
    <vue-loading type="bars" color="#d9544e" :size="{ width: '50px', height: '50px' }">
    <img alt="MDB logo" src="../assets/logo-mdb-vue-small.png">
    <HelloWorld msg="Welcome to Your MDB Vue.js App"/>
    </vue-loading> 
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/components/HelloWorld.vue'
 import { VueLoading } from 'vue-loading-template'　←ここを追加

export default {
  name: 'home',
  components: {
    HelloWorld,
    VueLoading　←ここを追加
  }
}
</script>
```

**Comment by ktsukamoto1** [comment]
![スクリーンショット (8)](https://user-images.githubusercontent.com/19473108/151645243-2d0ab5cd-4817-4b0e-adcc-6769c33779d1.png)

こんな感じで出てきた。

**Comment by daipom** [comment]
一度動かなくて、サンプルを参考に修正したら動いたということみたいですが、
完全にサンプルどおりでしっかり動くのかどうかも確認してみると良いかもしれませんね！

**Comment by ktsukamoto1** [comment]
![スクリーンショット (10)](https://user-images.githubusercontent.com/19473108/151647530-22846add-85b7-42ac-a83c-af3754caa4e1.png)
![スクリーンショット (11)](https://user-images.githubusercontent.com/19473108/151647540-1e6eb968-0a12-4be4-9d1d-331599d52f25.png)
ボタンで全画面の非表示ができた。
ソースコードは以下のような感じ。
```html
<template>
  <div class="home">
    <vue-loading v-if="isloading" type="spin" color="#d9544e" :size="{ width: '100px', height: '100px' }" />
    <div v-else>
      <img alt="MDB logo" src="../assets/logo-mdb-vue-small.png">
      <HelloWorld msg="Welcome to Your MDB Vue.js App"/>    
    </div>
    <mdb-btn  @click="click" color="primary">Loading表示・非表示切替</mdb-btn>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/components/HelloWorld.vue'
import { mdbBtn } from 'mdbvue';
 import { VueLoading } from 'vue-loading-template'

export default {
  name: 'home',
  components: {
    HelloWorld,
    VueLoading,
    mdbBtn
  },
  data: function () {
    return {
      isloading: false
    }
  },
  methods: {
    click: function () {
      this.isloading = !this.isloading;
    }
  }  
}
</script>
```

**Comment by ktsukamoto1** [comment]
オブジェクトの上にローディング中を出したいができるのか。
グーグルで調べてみる。

**Comment by daipom** [comment]
先ほどの会話のメモ

* よくありそうなユースケースにおける使用例などがあるとよいかもしれない！

**Comment by ktsukamoto1** [comment]
vue-loading overlayとかでgoogleで検索すると
vue-loading-overlayの別なライブラリがヒットする。
以下が別なライブラリのサイトです。
https://github.com/ankurk91/vue-loading-overlay

**Comment by ktsukamoto1** [comment]
キーワードをかえてみる。
以下の検索キーワードを変えてみた。
vue-loading object Transparent
↓
結果は、vue-loading-overlayの別なライブラリの情報が多かった。
ローディングをオブジェクトの上に重ねたい場合、こっちのライブラリを使っている人が多いのかな。

**Comment by ktsukamoto1** [comment]
issueの内容
・一覧などのオブジェクトの上にローディングボタンを表示したいのですが、可能なのでしょうか？

**Comment by daipom** [comment]
https://github.com/jkchao/vue-loading/issues/12
他のissueの書き方が参考になりそう

**Comment by ktsukamoto1** [comment]
I would like to display a loading button on top of an object such as a list, is this possible?

**Comment by ktsukamoto1** [comment]
一覧などのオブジェクトに重ねてローディングを表示したいです。
readme.mdや参考ソースを確認しましたが、やり方が分からなかったです。
やり方を教えて下さい。

**Comment by ktsukamoto1** [comment]
一覧などのオブジェクトに重ねてローディングを表示したいですが、readme.mdや参考ソースに書かれていなかったです。
よく使う場面で参考になる書き方をreadme.mdやサンプルソースで書いてほしいです。

**Comment by ktsukamoto1** [comment]
I would like to display loading over objects such as a list, but it was not written in the readme.md or sample source.
I think this case is often used, so I would like to see how to write a reference in readme.md or sample source for such a common case.

**Comment by ktsukamoto1** [comment]
よく使うケースの記載のお願い

**Comment by ktsukamoto1** [comment]
Request for description of frequently used cases

**Comment by ktsukamoto1** [comment]
![スクリーンショット (12)](https://user-images.githubusercontent.com/19473108/151650201-93676f12-0f8e-47ba-9d06-9bb9b88a7e95.png)

書式はつけずにそのまま送る感じで。

**Comment by ktsukamoto1** [comment]
![スクリーンショット (13)](https://user-images.githubusercontent.com/19473108/151650241-0ca1ab40-cc5c-4a3b-94b7-c301460626b3.png)

**Comment by piroor** [comment]
良いと感じた点

* 既存issueから表現を学ぶのはアリ（コミュニケーションが成立した前例なので）
* 他のライブラリも調べてみるのはとても大事。1つのプロジェクトの中だけで調べていて行き詰まるのはとてもよくあることなので。

次のステップとしてできるとよさそうなこと

* 巷のサンプルコード等を集めてきて「こういう使い方をしたいときにこういう書き方をするとできるみたい」という情報を提示すると、開発者の意見を聞けるかも。「これは有用なのでドキュメントに記載できる」「これは開発者的に想定外で、やってはいけない使い方だ」など。
*
