### ISSUE TITLE
    OSS Gate Workshop:TOKYO: 2022-01-29: harunec-capy: DBeaver: Work log

### ISSUE THREAD

**Issue by haruneco-capy** [oss-gate/workshop#1541]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by haruneco-capy** [comment]
READ MEをみてダウンロード方法を探しました。
https://github.com/dbeaver/dbeaver/blob/devel/README.md

**Comment by haruneco-capy** [comment]
下のバージョンをダウンロードしました。
dbeaver-ce-21.3.3-x86_64-setup.exe

**Comment by haruneco-capy** [comment]
WIKIをみてインストール手順を確認
https://github.com/dbeaver/dbeaver/wiki/Installation

**Comment by haruneco-capy** [comment]
チュートリアルのドキュメントが探しても見つからなかった。

**Comment by piroor** [comment]
https://github.com/dbeaver/dbeaver/blob/devel/LICENSE.md
Apache License Version 2.0
ということでOSSですね（最初の方に書かれていなかったので念のため）

**Comment by piroor** [comment]
題材を見つけるお手伝いを十分にできなくて申し訳ないです。。。
もし今後、普段の業務や開発の中でOSSのツールやライブラリを使っていて、意図しないエラーに遭遇したというようなことがありましたら、 https://gitter.im/oss-gate/general （全般的なチャット）か https://gitter.im/oss-gate/tokyo （東京ワークショップのチャット）あたりで「これを報告してみたい」とお声がけ頂ければ、サポーター陣でお手伝い致します！
