### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: kawaishi-ryotaro: OpenAM: 作業ログ

### ISSUE THREAD

**Issue by kawaishi-ryotaro** [oss-gate/workshop#155]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by kawaishi-ryotaro** [comment]
公式サイト読む
https://forgerock.org/openam/

様々な認証を統括してやってくれるものらしい

> “All in one” access management that includes authentication, adaptive risk assessment, authorization, federation, single sign-on, social sign-on, basic self-service, privacy and consent, and high performance session management.

**Comment by kawaishi-ryotaro** [comment]
ユーザガイドを発見

https://backstage.forgerock.com/docs/openam-jee-policy-agents/3.5/jee-users-guide

**Comment by kawaishi-ryotaro** [comment]
とりあえずこれを進めていけば動かせるようなのでやってきます

> This guide is written for anyone installing OpenAM policy agents to interface with supported Java EE application containers.
> 
> This guide covers procedures that you theoretically perform only once per version. This guide aims to provide you with at least some idea of what happens behind the scenes when you perform the steps.

**Comment by kawaishi-ryotaro** [comment]
の前にJava EE Policy Agentsについて調べたら、Java EE上で動かす必要のあるバージョンらしい。

http://sinsengumi.net/blog/2012/03/openam%E6%97%A7opensso%E3%81%A7%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%AA%E3%83%B3%E3%82%92%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B/

**Comment by kawaishi-ryotaro** [comment]
もう一度Docs一覧を見ると、違うポシリーのものもあったため探し直し。
https://backstage.forgerock.com/docs/openam

単体で動くOpenAMのドキュメントがあったためこちらを読む。
https://backstage.forgerock.com/docs/openam/13.5/getting-started

**Comment by kawaishi-ryotaro** [comment]
スタートアップガイドを読む。
https://backstage.forgerock.com/docs/openam/13.5/getting-started#chap-first-steps

MacOSはダメらしいので、VirtualBoxでCentOSを用意する。

> Important
> You need a Linux, Solaris, or Windows system that can run the OpenAM Web policy agent (see the Web Policy Agent Release Notes section, Web Policy Agents Platform Requirements ) with a minimum of 1 GB of available RAM memory, a few hundred MB of free disk space, a web browser, and an Internet connection to download software.
> If you are using Mac OS X, set up a virtual machine running Linux to try these procedures because the web policy agent is not built for Apache HTTP Server on Mac OS X.

**Comment by kawaishi-ryotaro** [comment]
VirtualBoxでCentOSを用意します。

以下のページを参考にします。
http://qiita.com/100/items/80a899fbaeb1e82b3f67

メモリミニマム1GBと書いてあるのでその通りに仮想マシンを用意する。

> Web Policy Agents Platform Requirements ) with a minimum of 1 GB of available RAM memory, a few hundred MB of free disk space, a web browser, and an Internet connection to download software.

**Comment by kawaishi-ryotaro** [comment]
VirtualBoxで以下のisoを使ってインストール
http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso

基本的にはデフォルト設定のまま。
言語選択: 日本語
キーボード配列:  US
rootパスワード: root
ユーザ: openam Pw: openam

**Comment by kawaishi-ryotaro** [comment]
早速手順を進めます！

```
> yum groupinstall 'Development Tools'
```

リポジトリが見つからない旨のメッセージのため、書きブログを参考にして`/etc/yum.repos.d/ConsOS-Base.repo` の書き換え後も未解決。
http://qiita.com/asukiaaa/items/f92bfa7ba6fba2aeb7ed

ネットワークに繋がってないのかも？

VirtualBoxの仮想マシンの設定 > ネットワーク > アダプター1
割り当て -> ブリッジアダプター
名前 -> en0

リブートしても未解決。

minimalからインストールからの手順参考をぐぐって以下をみつける。
http://futurismo.biz/archives/1340

`ネットワーク設定` の項目を実施後、pingが通るようになったので `ツールのアップデート` を実施してこの記事からは離脱。

**Comment by kawaishi-ryotaro** [comment]
> Procedure 1.1. To Prepare Your Hosts File

を実施。

> Procedure 1.2. To Install Apache HTTP Server

を実施。

Apacheは2.2系がよい、それも2.2.9以降がよいと書かれているため、2系最新の2.2.31をダウロードした。

> Download Apache HTTP Server 2.2 sources from the Apache download page.
> 
> The OpenAM web policy agent requires Apache Portable Runtime 1.3 or later, so make sure you download Apache HTTP Server 2.2.9 or later.

`prefix` には `/usr/local/apche` を指定した。

> $ ./configure --prefix=/path/to/apache

**Comment by kawaishi-ryotaro** [comment]
> Procedure 1.2. To Install Apache HTTP Server
>   7. Edit the configuration to set the server name to www.example.com and the port to one, such as 8000 that the web server process can use when starting with your user ID.
> 
>    $ vi /path/to/apache/conf/httpd.conf
>    $ grep 8000 /path/to/apache/conf/httpd.conf
>    Listen 8000
>    ServerName www.example.com:8000

viコマンドを実行した後にないをすれば良いかわからなかった。
viの中で`8000`をgrep(検索)する...？

説明を読むとサーバ名とポートを変更するようだ？

**Comment by kawaishi-ryotaro** [comment]
接続確認を行うが、VirtualBox上で動作しているためIPアドレスを確認したい。
`ifconfig`が入っていないため `yum install -y net-tools` を行った。

`192.168.0.35` と判明したため、Macのブラウザから `http://192.168.0.35:8000/` にアクセスしたところ `It works!` が表示されたためOK。

**Comment by kawaishi-ryotaro** [comment]
> Procedure 1.3. To Install Apache Tomcat

`javac -version` をしたところ `command not found` となったため、JDKをイストールする。

Javaのバージョンは Oracle JDK 8を選択する。
最新の `Java SE Development Kit 8u112` をダウンロードした。
https://backstage.forgerock.com/docs/openam/13.5/release-notes#sec-java-requirements

下記ブログを参考にする。
http://zero-config.com/centos/install-java8.html

Mac側でダウンロードしたのでCentOSに送り込みたい。
VirtualBoxの共有フォルダ設定をし、`mount -t vboxsf Donwloads /mnt/downloads` を行なったが `vboxsf`というファイルシステムがないと怒られる。

`mount: unknown filesystem type ‘vboxsf’`でググると下記記事が見つかったためセットアップする。
http://d.hatena.ne.jp/pospome/20140309/1394346690
OKがでたのでrebootします。

再度mntしたが `mounting failed with the error: Protocol error` となったため、再度ググる。
http://rubellum.hatenablog.com/entry/20110508/1304835867
自動マウントにチェックが入っているとのことで外して再起動。

再度mntしたが `mounting failed with the error: Protocol error` となったが、タイポがあったため直すとマウントされた。
`mount -t vboxsf Downloads /mnt/downloads`

以降は `Procedure 1.3. To Install Apache Tomcat` の手順通り進めた。

**Comment by kawaishi-ryotaro** [comment]
> Create a Tomcat setenv.sh (Unix/Linux) or setenv.bat (Windows) script to set the JAVA_HOME environment variable to the file system location of the Java Development Kit, and to set the heap and permanent generation size appropriately.

JDKはインストール済みの前提で話が進んでいる。
そのため、 `export JAVA_HOME=/path/to/jdk` を知る手段を書いたほうが良い気がする...いきなりすぎてわからなかった。

**Comment by kawaishi-ryotaro** [comment]
Getting Statedを読み進めてセットアップをしていましたが、`1.3. Setting Up the Software
`の`Procedure 1.2. To Install Apache HTTP Server`にある`httpd.conf`の編集で躓きました。

ここまで記述されたコマンドの通りに実行してきため、`$ vi /path/to/apache/conf/httpd.conf`の後の`grep 8000 /path/to/apache/conf/httpd.conf`がvi上ではできなく、手が止まりました。
https://backstage.forgerock.com/docs/openam/13.5/getting-started#install-apache-http

`vi`と`grep`の間に編集があることを明示するため、1行目と以降の行を別のspaceで括って掲載して欲しいです。
> $ vi /path/to/apache/conf/httpd.conf
> $ grep 8000 /path/to/apache/conf/httpd.conf
> Listen 8000
> ServerName www.example.com:8000

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-28に開催](https://oss-gate.doorkeeper.jp/events/52881)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
