### ISSUE TITLE
OSS Gate Workshop: オンライン: 2022-03-08: 00Masato: github1s: Work log

### ISSUE THREAD

**Issue by 00Masato** [oss-gate/workshop#1550]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 00Masato** [comment]
インストール済みなので、Chromeの拡張機能画面から詳細ボタンを押すと、
拡張機能のウェブサイトを開くというボタンがあったので、押してみる。
https://github.com/conwnet/github1s

**Comment by 00Masato** [comment]
LICENSEというファイルを開いてライセンスを確認してみる。

MIT Licenseと書いてある。

ライセンス一覧（https://opensource.org/licenses/alphabetical）を確認すると
記載されていたので、OSSと言える。

**Comment by 00Masato** [comment]
拡張機能詳細画面のChromeウェブストアのページに移動というボタンを押すと、
404エラーが出た！

**Comment by piroor** [comment]
https://www.google.com/search?client=firefox-b-d&q=github1s+chrome+extension
で検索してみました
https://github.com/fhefh2015/GitHub1s_chrome_extension
これをお使いのようです

**Comment by 00Masato** [comment]
https://github.com/fhefh2015/GitHub1s_chrome_extension
の
issueを開くと同様の報告が上がっていた。
https://github.com/fhefh2015/GitHub1s_chrome_extension/issues/13

**Comment by 00Masato** [comment]
↓のリンクを見ると2022/1/9にセキュリティリスクのためremoveされたと書いてあった。
https://chrome-stats.com/d/lodjfmkfbfkpdhnhkcdcoonghhghbkhe

**Comment by piroor** [comment]
あ、セキュリティリスクについてはどうも「可能性」ということみたいですね。
公開取り下げの理由は全く不明なので、単に作者の方が自発的に消しただけの可能性もあるかと。

**Comment by 00Masato** [comment]
関連する別の拡張機能を調べることとする。
Chromeストアで「github1s」と検索してみると、
3件検索結果があった。
1番上の拡張機能を見てみる。
https://chrome.google.com/webstore/detail/open-in-vs-code-github1sc/neloiopjjeflfnecdlajhopdlojlkhll?hl=ja

**Comment by 00Masato** [comment]
概要に下のリンクを開いてとあったので、リンクを開いたが情報がない。
https://github.com/conwnet/github1s

**Comment by 00Masato** [comment]
提供元作者のリポジトリ情報を確認したが、github1sをforkしたリポジトリ1件しかなかった。
https://github.com/zulhfreelancer?tab=repositories&q=github1s&type=&language=&sort=

**Comment by 00Masato** [comment]
二つ目の検索結果を見てみる。
https://chrome.google.com/webstore/detail/shortcut-to-github1s/gfcdbodapcbfckbfpmgeldfkkgjknceo?hl=ja

右下にリポジトリのリンクがあったので、見てみる。
https://github.com/katsuhisa91/github1s-shortcut/

**Comment by 00Masato** [comment]
LICENSEファイルを見てみると
MIT License
とあったので、OSSと言える。

**Comment by 00Masato** [comment]
READ.MEをみながら使ってみる。
インストールはChromeストアからインストールしてください。
と書いてあるので、
リンクをクリックし、インストールしてみる。
https://chrome.google.com/webstore/detail/shortcut-to-github1s/gfcdbodapcbfckbfpmgeldfkkgjknceo

**Comment by 00Masato** [comment]
Chromeに追加されましたと表示される。

**Comment by piroor** [comment]
![image](https://user-images.githubusercontent.com/70062/157171805-4c5c8f05-d5d3-4ffe-b83b-abc2a031f8dc.png)
インストール時に、github.comとgithub1s.comのサイトに対する読み取り・変更の権限を要求されるんですね。その必要あるのかなあ？

**Comment by 00Masato** [comment]
使い方のところに
 Ctrl(Win)/Command(Mac)+Shift+1.
で使用と書いてあるので、Command(Mac)+Shift+1を押してみる。
押してみると、対象の画面が開いた。

**Comment by 00Masato** [comment]
書いてあるとおりの動作ができた。

**Comment by 00Masato** [comment]
その他の使い方等は特に書かれていなかった。

**Comment by 00Masato** [comment]
特につまづくところがなかったので、もう一つの検索結果を見てみることにする。
https://chrome.google.com/webstore/detail/open-in-github1s/iijaagbkdohcopmmohlgfkcloefoeaoj?hl=ja

右下に公式サイトへのリンクがあるので、それをクリックしてみる。
https://github.com/Cutwell/github1s-chrome-extension

**Comment by 00Masato** [comment]
LICENSEファイルを確認してみると、
MIT License
とあったので、OSSと言える。

**Comment by 00Masato** [comment]
READMEを見ながら使い方を見ていく。
Chromeストアからインストールとあるので、インストールを行う。
追加されたので、使用方法を見ていくと、
リポジトリ上のOpen in Github1sを押してと書いてあるので、
押してみる。
押してみると、別タブで画面が開いた。

**Comment by piroor** [comment]
https://github.com/Cutwell/github1s-chrome-extension を開いたままのタブがある状態で拡張機能をインストールしたら、インストール直後は、既存のタブには「Open in GitHub1s」ボタンが表示されませんでした。
（タブをリロードしたらボタンが現れた）

**Comment by irasally** [comment]
![スクリーンショット 2022-03-08 14 34 39（3）](https://user-images.githubusercontent.com/293996/157173537-fe903f7c-8eaf-43b2-a2d2-9b4cb50306e4.png)
インストール時に上記の権限(github.com 上のデータの読み取りと変更)を求められました。
プライベートリポジトリも読み取りされるのかもしれない？と思うとインストールを押せませんでした.

**Comment by piroor** [comment]
設定画面の「Save」ボタンを押すと一瞬設定ダイアログ（？）が伸び縮みしますね。
![image](https://user-images.githubusercontent.com/70062/157173784-dcac1642-06a0-4715-ac97-a4a7571ee466.png)
![image](https://user-images.githubusercontent.com/70062/157173799-45b9023f-84bb-4edd-8300-9d79cff7fc61.png)

**Comment by 00Masato** [comment]
User Optionsに「別タブ」、「現在のタブ」で開く設定ができると書いてあるので、試してみる。
current tabに設定して使ってみる。
リポジトリ上のOpen in Github1sを押すと現在のタブで開くことができた。

**Comment by HashidaTKS** [comment]
Githubのリポジトリに記載されているchrome://extensionsのカード
![image](https://user-images.githubusercontent.com/15982708/157174167-09997a23-b198-4604-9103-533788c99acd.png)

実際のchrome://extensionsのカード
![image](https://user-images.githubusercontent.com/15982708/157174362-837e80fa-ba08-4f6d-a4af-dab40cf00246.png)

デザインが違う気がする。

**Comment by IkumaTadokoro** [comment]
2つめの拡張機能と3つ目の拡張機能でほぼ同じ機能を提供しているのに、必要な権限が違うのはちょっと気になりますね。

![image](https://user-images.githubusercontent.com/61409641/157176936-9e3f40c2-b912-410e-b991-9c838d4e59db.png)

![image](https://user-images.githubusercontent.com/61409641/157176946-afc327cc-ff4d-44cc-aca9-d697d0810416.png)

**Comment by piroor** [comment]
サポーター陣はわりと権限の所を気にする、というのが興味深いところですね。
「そもそもこの権限無くても動くんじゃないの？」と違和感を抱くには、何が必要なんだろう……

**Comment by 00Masato** [comment]
気持ち：設定画面で「Save」ボタンを押したときに、設定ダイアログが伸び縮みする動作が気になる。伸び縮みしないようにしたい。

# 再現手順
1. ChromeストアよりOpen in GitHub1sをインストールする。（https://chrome.google.com/webstore/detail/open-in-github1s/iijaagbkdohcopmmohlgfkcloefoeaoj?hl=ja）
2. インストール後、拡張機能一覧画面から詳細ボタンを押して、詳細画面へ進む
3. 「拡張機能のオプション」ボタンを押す
4. 「New Tab」を「Current Tab」に変更し、「Save」を押す。

# 期待される動作
「Save」ボタンを押しても、設定ダイアログが伸び縮みしない。

# 実際の動作
https://user-images.githubusercontent.com/40224377/157184454-0aa08533-9fca-4637-a33e-bc5d263cc03b.mov

# 環境
Open in GitHub1s 1.3
Goggle Chrome 99.0.4844.51
Mac OS Monterey 12.2.1

**Comment by 00Masato** [comment]
title: Options page should have fixed size.

# Steps to reproduce
1. Install from https://chrome.google.com/webstore/detail/open-in-github1s/iijaagbkdohcopmmohlgfkcloefoeaoj?hl=ja
2. インストール後、拡張機能一覧画面から詳細ボタンを押して、詳細画面へ進む
3. 「拡張機能のオプション」ボタンを押す
4. 「New Tab」を「Current Tab」に変更し、「Save」を押す。

# Expected
「Save」ボタンを押しても、設定ダイアログが伸び縮みしない。

# Actual
https://user-images.githubusercontent.com/40224377/157184454-0aa08533-9fca-4637-a33e-bc5d263cc03b.mov

# Environment
Open in GitHub1s 1.3
Goggle Chrome 99.0.4844.51
Mac OS Monterey 12.2.1

**Comment by 00Masato** [comment]
気持ち：拡張機能にgithub.com上にある自分のデータの読み取りと変更権限が要求されるが、プライベートリポジトリの読み取りと変更も可能になるのではないかというのがあり、インストールを躊躇してしまう。
もう少し弱い権限の要求に変更してほしい。

**Comment by 00Masato** [comment]
要求される権限が強すぎるので、もう少し弱い権限にならないか？
↓
title: This extension require too match permission

This extension require too match permission.
Could you reduce required permission?
We just need permission to read github URL of the active tab to redirect from github to github1s.

**Comment by 00Masato** [comment]
プライベートリポジトリの読み取りと変更が可能にならないか不安
↓
I don't want to give permissions to access sensitive data in private repository.

**Comment by piroor** [comment]
PRまで達成おめでとうございます！
引き続きissueも立てていきましょう！

**Comment by piroor** [comment]
ワークショップが終了したのでクローズします（フィードバック自体は引き続き進めて頂ければ幸いです）
