### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: tkey.dll: GitLab: 作業ログ

### ISSUE THREAD

**Issue by tkeydll** [oss-gate/workshop#156]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by tkeydll** [comment]
まずぐぐる。
https://www.google.co.jp/search?client=opera&q=gitlab&sourceid=opera&ie=UTF-8&oe=UTF-8

公式っぽいサイトにいく
https://about.gitlab.com

**Comment by tkeydll** [comment]
公式からはソースの場所が見つけられなかったのでGitHubでさがす。
https://github.com/gitlabhq/gitlabhq

**Comment by tkeydll** [comment]
GitHubにソースはあるが、本体はGitLab.orgにおいてあるらしい

> GitLab CE | Please open new issues in our issue tracker on GitLab.com https://gitlab.com/gitlab-org/gitlab-ce/issues

**Comment by tkeydll** [comment]
リポジトリをみつけた。
https://gitlab.com/gitlab-org/gitlab-ce

**Comment by tkeydll** [comment]
GitLabのアカウントがない。

GitHubアカウントでログインできそうだが、422で死んだ。

**Comment by tkeydll** [comment]
googleアカウントでログイン成功。

**Comment by tkeydll** [comment]
もともとgoogleでアカウント取得していたっぽい。
SSHキーも登録してあった。

ので、ソースを取得。

```
git clone git@gitlab.com:gitlab-org/gitlab-ce.git
```

**Comment by tkeydll** [comment]
ドキュメントを読む。

> GitLab is a Ruby on Rails application that runs on the following software:
> Ubuntu/Debian/CentOS/RHEL
> Ruby (MRI) 2.3
> Git 2.7.4+
> Redis 2.8+
> MySQL or PostgreSQL

開発PC Windowsじゃん！！！

**Comment by tkeydll** [comment]
Azure上にLinux を用意する。

**Comment by tkeydll** [comment]
Ubuntu Server 14.04 LTS

**Comment by tkeydll** [comment]
待ってる間にREADMEからインストール方法を調べる。

> There are various other options to install GitLab, please refer to the installation page on the GitLab website for more information.

**Comment by tkeydll** [comment]
パッケージのインストール方法は記載されているが、ソースから動かす感じじゃない。

**Comment by tkeydll** [comment]
こっちかな？

> To work on GitLab itself, we recommend setting up your development environment with the GitLab Development Kit. If you do not use the GitLab Development Kit you need to install and setup all the dependencies yourself, this is a lot of work and error prone. One small thing you also have to do when installing it yourself is to copy the example development unicorn configuration file:

**Comment by tkeydll** [comment]
当たり。

https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md

**Comment by tkeydll** [comment]
開発環境構築。
上の Ubuntu の手順で実施。

**Comment by tkeydll** [comment]
```
$ sudo apt-get install software-properties-common python-software-properties

Reading package lists... Done
Building dependency tree
Reading state information... Done
software-properties-common is already the newest version.
The following NEW packages will be installed:
  python-software-properties
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.6 kB of archives.
After this operation, 138 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://azure.archive.ubuntu.com/ubuntu/ trusty-updates/universe python-software-properties all 0.92.37.7 [19.6 kB]
Fetched 19.6 kB in 0s (41.5 kB/s)
Selecting previously unselected package python-software-properties.
(Reading database ... 28517 files and directories currently installed.)
Preparing to unpack .../python-software-properties_0.92.37.7_all.deb ...
Unpacking python-software-properties (0.92.37.7) ...
Setting up python-software-properties (0.92.37.7) ...
```

**Comment by tkeydll** [comment]
```
tkey.dll@jns-gitlab-dev:~$ sudo apt-add-repository -y ppa:ubuntu-lxc/lxd-stable
gpg: keyring `/tmp/tmp_hgs7097/secring.gpg' created
gpg: keyring `/tmp/tmp_hgs7097/pubring.gpg' created
gpg: requesting key 7635B973 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp_hgs7097/trustdb.gpg: trustdb created
gpg: key 7635B973: public key "Launchpad PPA for Ubuntu LXC team" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
```

**Comment by tkeydll** [comment]
```
$ sudo apt-get update
$ sudo apt-get install git postgresql postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ nodejs libkrb5-dev golang ed pkg-config
```

**Comment by tkeydll** [comment]
```
tkey.dll@jns-gitlab-dev:~$ npm install phantomjs-prebuilt@2.1.12 -g
The program 'npm' is currently not installed. You can install it by typing:
sudo apt-get install npm
```

**Comment by tkeydll** [comment]
nodejs と npm って一緒に apt-get install できないの？

**Comment by tkeydll** [comment]
再度 npm install phantomjs-prebuilt@2.1.12 -g
パッケージのインストールに失敗。

```
tkey.dll@jns-gitlab-dev:~$ npm install phantomjs-prebuilt@2.1.12 -g
npm http GET https://registry.npmjs.org/phantomjs-prebuilt/2.1.12
npm http 200 https://registry.npmjs.org/phantomjs-prebuilt/2.1.12
npm http GET https://registry.npmjs.org/phantomjs-prebuilt/-/phantomjs-prebuilt-2.1.12.tgz
npm http 200 https://registry.npmjs.org/phantomjs-prebuilt/-/phantomjs-prebuilt-2.1.12.tgz
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/phantomjs-prebuilt',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/writer.js:171:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.4.0-47-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "phantomjs-prebuilt@2.1.12" "-g"
npm ERR! cwd /home/tkey.dll
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! fstream_path /usr/local/lib/node_modules/phantomjs-prebuilt
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tkey.dll/npm-debug.log
npm ERR! not ok code 0
```

**Comment by tkeydll** [comment]
root で。

```
$ sudo npm install phantomjs-prebuilt@2.1.12 -g
```

うまくいってるように見えたけど、最後の最後で

```
> phantomjs-prebuilt@2.1.12 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0
```

**Comment by tkeydll** [comment]
https://github.com/oss-gate/workshop/issues/156#issuecomment-263040882

をフィードバックする。

**Comment by tkeydll** [comment]
https://github.com/oss-gate/workshop/issues/156#issuecomment-263040882

はすでに Issue が上がっていた。
https://gitlab.com/gitlab-org/gitlab-development-kit/issues/174

**Comment by tkeydll** [comment]
この Issue に追加情報を加えるか

sudo apt-get install npm で npm をインストールしても https://github.com/oss-gate/workshop/issues/156#issuecomment-263041114 の現象が発生する。

**Comment by tkeydll** [comment]
https://github.com/oss-gate/workshop/issues/156#issuecomment-263041114 の続き。

node コマンドがないと言っている。  
/usr/share/doc/nodejs/README.Debian を読むと、nodejsコマンドを使えと言っている。

```
$ sudo ln -s /usr/bin/nodejs /usr/bin/node
$ chmod 777 /usr/bin/node
```

として、再度 sudo npm install phantomjs-prebuilt@2.1.12 -g すると、進んだ。

```
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.12 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /home/tkey.dll/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [==================================------] 86%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /home/tkey.dll/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1480139319994/phantomjs-2.1.1-linux-x86_64 -> /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
phantomjs-prebuilt@2.1.12 /usr/local/lib/node_modules/phantomjs-prebuilt
??? progress@1.1.8
??? which@1.2.12 (isexe@1.1.2)
??? es6-promise@3.2.1
??? kew@0.7.0
??? request-progress@2.0.1 (throttleit@1.0.0)
??? hasha@2.2.0 (is-stream@1.1.0, pinkie-promise@2.0.1)
??? extract-zip@1.5.0 (debug@0.7.4, mkdirp@0.5.0, yauzl@2.4.1, concat-stream@1.5.0)
??? fs-extra@0.30.0 (path-is-absolute@1.0.1, klaw@1.3.1, jsonfile@2.4.0, graceful-fs@4.1.11, rimraf@2.5.4)
??? request@2.74.0 (oauth-sign@0.8.2, tunnel-agent@0.4.3, is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, aws4@1.5.0, combined-stream@1.0.5, node-uuid@1.4.7, qs@6.2.1, mime-types@2.1.13, tough-cookie@2.3.2, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6, hawk@3.1.3, form-data@1.0.1)
```

**Comment by tkeydll** [comment]
node のインストールまわりを追加で報告する。

**Comment by tkeydll** [comment]
素のubuntuにnodeが入っていないこと、手順にある apt-get install nodejs で、nodeが入らないことを確認する。

```
$ node -v
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```
ない。

**Comment by tkeydll** [comment]
素のubuntuにnpmがないことは https://gitlab.com/gitlab-org/gitlab-development-kit/issues/174 で報告されているので、加えて nodejs-legacy が必要であると言う事を報告する！

**Comment by tkeydll** [comment]
まず日本語で。

npmをインストールしても、nodeコマンドが無い為以下のエラーが発生する。

```
> phantomjs-prebuilt@2.1.12 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0
```

クリーンインストールした ubuntu に nodejs パッケージを入れても node が見つからない。
```
$ node -v
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```

nodejs-legacy を入れれば解決する。

**Comment by tkeydll** [comment]
After install npm, the error occurs.

```
> phantomjs-prebuilt@2.1.12 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0
```

Node is not found.
```
$ node -v
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```

Needs install nodejs-legacy, or create symbolic link.

**Comment by tkeydll** [comment]
報告した。

https://gitlab.com/gitlab-org/gitlab-development-kit/issues/174#note_19007598

**Comment by kou** [comment]
コメントが2つついていますね！
インストール方法をこんな感じで直すといいよ！というmerge requestを送るのがよさそうな気がします！

（このissuあcloseしますけど引き続きここにメモを残しながら作業しても大丈夫です！）
