### ISSUE TITLE
OSS Gate Workshop: online: 2022-07-30: tazieee: JOOQ: Work log

### ISSUE THREAD

**Issue by tazieee** [oss-gate/workshop#1563]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tazieee** [comment]
Jooq
https://github.com/jOOQ/jOOQ/blob/main/LICENSE
ライセンス確認中

**Comment by tazieee** [comment]
JOOQ
ライセンスはApache-2.0なのでOSSです。
[Apache License 2.0 (Apache-2.0)](https://opensource.org/licenses/Apache-2.0)

**Comment by tazieee** [comment]
詳細
https://www.jooq.org/

**Comment by tazieee** [comment]
ダウンロードリンク
https://www.jooq.org/download/

**Comment by tazieee** [comment]
ダウンロードをクリックしたら、ダウンロードフォームが表示された。
Registration (optional)と記述があるので必須ではなさそう。

**Comment by tazieee** [comment]
ライセンスにagreeしたという認識でI agreeボタンでダウンロード開始。

**Comment by tazieee** [comment]
ダウンロードファイルはzip形式。

**Comment by tazieee** [comment]
ファイルを解凍した。中にあるREADME.mdの内容は下記のみ。
=============
Thanks for downloading jOOQ.
Please visit http://www.jooq.org for more information.
=============

**Comment by tazieee** [comment]
https://www.jooq.org/
このサイトの一番下の右側にドキュメントの欄がある。
恐らくここから始めるっぽい？

**Comment by tazieee** [comment]
チュートリアル
https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/

フィードバックのリンクも用意されている。
[We'd love to hear it!](https://github.com/jOOQ/jOOQ/issues/new?title=Feedback+about+manual+section+%22jooq-in-7-steps%22&body=%20%0a%0a%0a----%0aSee:+https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/)

**Comment by tazieee** [comment]
チュートリアル１
https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/

Mavenの設定方法がある。
Gradleの設定方法はない？

**Comment by tazieee** [comment]
チュートリアル２
mysqlが必要。
まだ MySQL インスタンスを起動して実行していない場合は、[https](https://hub.docker.com/_/mysql) ://www.mysql.comまたは[https://hub.docker.com/_/mysql](https://www.mysql.com/)から今すぐ入手してください!

**Comment by tazieee** [comment]
チュートリアル１
ページを翻訳するとmavenの設定方法も翻訳されてしまうので、コピペできない。

**Comment by tazieee** [comment]
チュートリアル２
https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step2/
このページも翻訳でSQLの内容が分からなくなってしまう。

**Comment by tazieee** [comment]
チュートリアル２
Mysqlの環境を構築する必要あり。

**Comment by tazieee** [comment]
チュートリアル２
docker-composeからDB作る場合は、ちょっと意識が必要。

**Comment by daipom** [comment]
> チュートリアル１ https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/
> 
> Mavenの設定方法がある。 Gradleの設定方法はない？

Maven や Gradle について知らないのでよくわからないですが、
Gradle の運用例があるなら、その設定例をドキュメントに追加するようにフィードバックするのもありかもしれないですね。

Gradle について既存のissueを調べると結構ヒットしますね。
この辺りを軽く確認してみると、 Gradle がどう使われているのか、皆がどう問題に思っているのかが分かるかも

* https://github.com/jOOQ/jOOQ/issues?q=is%3Aissue+is%3Aopen+gradle

**Comment by daipom** [comment]
> https://www.jooq.org/ このサイトの一番下の右側にドキュメントの欄がある。 恐らくここから始めるっぽい？

GitHubの README にこのリンクを足してほしいですね。

**Comment by hata6502** [comment]
https://github.com/jOOQ/jOOQ/issues/13171

**Comment by tazieee** [comment]
過去のイシューで似たような内容をピックアップ
gradleに対して積極的でない印象

質問者：gradleのドキュメントを増やしてください。
回答者：とりあえず、提案されているサードパーティのgradleプラグインの例に従ってみてはどうでしょうか？
https://github.com/etiennestuder/gradle-jooq-plugin

https://github.com/jOOQ/jOOQ/issues/13332

**Comment by hata6502** [comment]
https://github.com/jOOQ/jOOQ/issues/13332#issuecomment-1076367075
Gradleのサードパーティ製プラグインはあるけど、
JOOQ公式のサポートは薄そう。

**Comment by hata6502** [comment]
「このような要望は送らないでね」をドキュメントに明記する方法
Issue Templateにコメントで
```html
<--
Are you reporting about IE 11 browser's problem?
Sorry, We don't support Ie 11. 
-->
```

**Comment by tazieee** [comment]
チュートリアル１
https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/

gradleを使って導入するのでサードパーティを使ってね。的な案内がチュートリアルの記述にあった方が親切。
公式としてgradleでの導入をサポートする予定がないのであれば。

**Comment by hata6502** [comment]
https://docs.prefect.io/getting-started/installation/
![image](https://user-images.githubusercontent.com/7702653/181877024-37a38113-281f-4e13-9c46-3e9f5ec9d5c8.png)

> `Maven`使うことを推奨します。
> ⚠`Gradle`は公式にサポートはしていません。

のような注意書きを書いてもらうなど

**Comment by tazieee** [comment]
Gradleの導入方法の紹介を明記してみてはいかがでしょうか。
以前のイシューに対するあなたの回答でサードパーティの提案をされていました。
https://github.com/jOOQ/jOOQ/issues/13332#issuecomment-1076367075

もし、公式の立場としてGradleでの導入が確立されていないのであればサードパーティについての紹介をチュートリアルで紹介されてはいかがでしょうか。

**Comment by tazieee** [comment]
Why don't you specify an introduction on how to install Gradle?
You suggested a third party in your response to a previous Issue.
https://github.com/jOOQ/jOOQ/issues/13332#issuecomment-1076367075

If the official position is that Gradle implementation is not established, why don't you introduce the third party in your tutorial?
Also, how about adding a note in the README.md recommending the use of Maven?

**Comment by hata6502** [comment]
`introduce the third party in your tutorial?`
--> `introduce the third party plugin in your tutorial?`
`[text](url)`

**Comment by tazieee** [comment]
イシュー
https://github.com/jOOQ/jOOQ/issues/13834

**Comment by hata6502** [comment]
Subscribeボタンで僕も返信を待ちます！🎉
![image](https://user-images.githubusercontent.com/7702653/181878006-e04a2bb9-ed1d-4488-ada7-bdb3efe013a5.png)
