### ISSUE TITLE
OSS Gate Workshop: online: 2022-07-30: mae616: Fig: Work log

### ISSUE THREAD

**Issue by mae616** [oss-gate/workshop#1564]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mae616** [comment]
MPen

**Comment by mae616** [comment]
chromeの拡張機能
https://chrome.google.com/webstore/detail/mpen/cghmnieebgefhenggkhbdbhgcjlegkkc?hl=ja

**Comment by mae616** [comment]
youtube dual subtitles

**Comment by daipom** [comment]
リンクからこのサイトに飛べるけど、リリースノートしかなさそう

https://www.dual-subtitles.com/ja/whatsnew/3.6.7

**Comment by mae616** [comment]
fig
https://fig.io/
https://github.com/withfig/autocomplete

**Comment by mae616** [comment]
MITライセンスなのでOSS

**Comment by daipom** [comment]
https://github.com/withfig/autocomplete

ここのREADMEのInstallationでは、

```
brew intall --cask fig
```

でインストールデキル感じ

**Comment by mae616** [comment]
https://zenn.dev/schroneko/articles/616e1c61c74b4e

**Comment by mae616** [comment]
fig

macのbrewのインストールで、
>  Installation
> NOTE: Once it's downloaded, launch the app to set up Fig!

https://zenn.dev/schroneko/articles/616e1c61c74b4e
に書いてあるように
したが、
> ```
> open /Applications/Fig.app/
> ```
> アプリケーションを開くと、パーミッションを設定するよう促されるので、Accessibility > Fig にチェックを入れる。簡単なチュートリアルが始まる

まで書いてあると初心者としては分かりやすく嬉しいです。

**Comment by mae616** [comment]
FigのWebpage
https://fig.io/
に、`brew install fig`のコマンドが書いてありますが、
（https://github.com/withfig/autocomplete にも'NOTE: Once it's downloaded, launch the app to set up Fig!'とありますが）
その後、`open /Applications/Fig.app/`を実行し、Accessibility > Figのパーミッションを追加するところまで書いてありますと、自分のような初心者には分かりやすく嬉しいです。
こんなアイデアどうでしょうか

**Comment by mae616** [comment]
figをインストールしようとしました。
FigのWebpage（https://fig.io/）に、`brew install fig`のコマンドが書いてあり実行しました。
次になにをしていいのかわからなくなりました。

https://github.com/withfig/autocomplete に'NOTE: Once it's downloaded, launch the app to set up Fig!'と書いてあったので、
open /Applications/Fig.app/を実行し、Accessibility > Figのパーミッションを追加しました。
そしたら動きました。

Figの（https://fig.io/）にもこの説明が詳しく欲しいです。

**Comment by mae616** [comment]
I tried to install fig.
https://fig.io/ has a command `brew install fig` I ran it.
I expected Fig to work, but it did not.
After that, I did not know what to do next because there was no explanation on the Webpage.

I saw on https://github.com/withfig/autocomplete that 'NOTE: Once it's downloaded, launch the app to set up Fig!'
I ran `open /Applications/Fig.app/` and added permission to Fig via "Accessibility > Fig".
Then Fig worked.
it will be more helpful If this instruction appears on the https://fig.io/ also

**Comment by mae616** [comment]
[doc] better instruction to install

**Comment by mae616** [comment]
https://github.com/withfig/fig/issues/1650
