### ISSUE TITLE
OSS Gate Workshop: Online: 2022-09-06: gryu7: ansible: Work log

### ISSUE THREAD

**Issue by gryu7** [oss-gate/workshop#1575]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by gryu7** [comment]
対象案
そういえばこないだ使ってちょっと難しかった
https://github.com/google-github-actions/setup-gcloud

**Comment by gryu7** [comment]
ライセンスは`Apache License`
https://github.com/google-github-actions/setup-gcloud/blob/main/LICENSE

**Comment by daipom** [comment]
OSSですね！

**Comment by gryu7** [comment]
以下の部分で時間がかかりそうなので、選定対象を変更

> This GitHub Action establishes authentication to Google Cloud. It supports traditional authentication via a Google Cloud Service Account Key JSON and authentication via [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation).

> 
> Workload Identity Federation is the recommended approach as it obviates the need to export a long-lived Google Cloud service account key and establishes a trust delegation relationship between a particular GitHub Actions workflow invocation and permissions on Google Cloud.

**Comment by gryu7** [comment]
https://github.com/containers/skopeo

**Comment by gryu7** [comment]
https://github.com/containers/skopeo#license
上記でライセンスは`Apache License`であることを確認

**Comment by gryu7** [comment]
## 目的
Ansibleのインストールをdocument通りに対応してみて、不備があれば修正してみることにする。

## Ansibleのdocumentのライセンス
以下にドキュメントがある。
https://docs.ansible.com/ansible/latest/index.html

ドキュメント内に、ドキュメント修正方法も書いてある。
https://docs.ansible.com/ansible/latest/community/documentation_contributions.html#verifying-your-documentation-pr

**Comment by gryu7** [comment]
修正する資産があれば、以下の中のものになる想定。
https://github.com/ansible/ansible/tree/devel/docs/docsite

ライセンスは`GNU General Public License v3.0 or later`であり、OSSであることを確認。

**Comment by gryu7** [comment]
この手順を実施
https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#running-the-devel-branch-from-a-clone

**Comment by gryu7** [comment]
https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#running-the-devel-branch-from-a-clone

インストール後、手順書に従い、tab補完ができるように`activate-global-python-argcomplete`を実行したところ、恐らく、root権限ではないため、以下のエラーが発生。
> activate-global-python-argcomplete: error: [Errno 13] Permission denied: '/etc/bash_completion.d/python-argcomplete'

**Comment by gryu7** [comment]
https://github.com/oss-gate/workshop/issues/1575#issuecomment-1237807328
こちらは、`$ sudo activate-global-python-argcomplete`とすれば正常に終了することを確認。

**Comment by gryu7** [comment]
https://docs.ansible.com/ansible/latest/community/documentation_contributions.html#editing-docs-directly-on-github
こちらの方法に即して、pushせずにPRを起票する。
