### ISSUE TITLE
OSS Gate Workshop: Online: 2022-09-06: blackflog: texinfo: Work log

### ISSUE THREAD

**Issue by blackflog** [oss-gate/workshop#1577]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by blackflog** [comment]
公式サイトを確認すると、GNU General Public License Version 3との記載があった
https://git.savannah.gnu.org/cgit/texinfo.git/tree/COPYING

OSSのLicense一覧 (https://opensource.org/licenses/gpl-license)を見ると、OSSに該当することが分かった

**Comment by blackflog** [comment]
ほとんどのLinuxディストリビューションでは、標準でインストールされている

最新のソースコードは、https://git.savannah.gnu.org/git/texinfo.git よりダウンロード

**Comment by blackflog** [comment]
# バグの報告方法

メールで報告する
https://lists.gnu.org/mailman/listinfo/bug-texinfo

# 問題

## 以前に見つけた問題

トップページでCtrl-A (行頭に移動)すると、フリーズする

## 今回見つけた問題

コンパイルとインストールの手順が一目で分かりにくい

git: README -> README-hacking
tarball: README -> INSTALL -> INSTALL.generic

READMEが読み辛い? (markdownを使用していないプレーンテキスト)
しっかりと読む必要がある

# memo

開発版(git)には、configureスクリプトが無い

git: ./autogen.sh -> ./configure -> make
tarball: ./configure -> make

**Comment by blackflog** [comment]
# メール本文

こんにちは。

infoコマンドでgccのマニュアルを見ていたときに、動かなくなることがあります。


再現手順:

1. マニュアルを開く
2. トップページの1行目でC-a

期待される結果:

エラーメッセージが出るだけ

実際の結果:

エラーメッセージの後ろのカーソルが点灯したまま、操作を受け付けない
C-cでシェルに戻れる

gdbで確認したところ、無限ループしていることを確認できました。

**Comment by daipom** [comment]
@blackflog 
ワークショップ終了につき自動でこのissueを閉じましたが、
英語番のレビューなど必要でしたらこのissueをReopenして自由に使ってください！
