### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: junk0612: rails: 作業ログ

### ISSUE THREAD

**Issue by junk0612** [oss-gate/workshop#158]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by junk0612** [comment]
ググる。
公式サイトがあった。

http://rubyonrails.org/

**Comment by junk0612** [comment]
「Rails でモダンなイカした Web アプリ作れるぜ！」みたいなことが書いてある。

> Learning to build a modern web application is daunting. Ruby on Rails makes it much easier and more fun. It includes everything you need to build fantastic applications, and you can learn it with the support of our large, friendly community.

**Comment by junk0612** [comment]
公式サイトの「Contribute on GitHub」からリポジトリへ飛べた。

https://github.com/rails/rails

**Comment by junk0612** [comment]
README の Getting Started に従ってインストールする。

https://github.com/rails/rails#getting-started

**Comment by junk0612** [comment]
`gem install rails` で 5.0.0.1 が入った。

```
Done installing documentation for rails after 0 seconds
1 gem installed
```

**Comment by junk0612** [comment]
5.0.0.1 が最新かどうか確認したいのでコミットログを見る。巨大なので重くてロードに時間がかかる。

https://github.com/rails/rails/graphs/commit-activity

**Comment by junk0612** [comment]
Tags は 5.0.0.1 が一番新しいみたい。

<img width="332" alt="2016-11-26 11 32 51" src="https://cloud.githubusercontent.com/assets/4271086/20637454/2634818e-b3cc-11e6-86a6-25da7435960a.png">

**Comment by junk0612** [comment]
`rails new temp_app` を実行する。
なんかたくさん作られたあと、 `bundle install` が走った。

```
Bundle complete! 15 Gemfile dependencies, 62 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
```

**Comment by junk0612** [comment]
`cd temp_app` して `rails server` を叩く。

```
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.2 (ruby 2.4.0-p-1), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

**Comment by junk0612** [comment]
`Yay! You're on Rails!`

<img width="663" alt="2016-11-26 11 38 55" src="https://cloud.githubusercontent.com/assets/4271086/20637488/067fa0a2-b3cd-11e6-83c3-b6d73537c9dc.png">

**Comment by junk0612** [comment]
Contributing の章を読む。

https://github.com/rails/rails#contributing

**Comment by junk0612** [comment]
やろうとしていることが過去に議論されていないかどうかを確認していなかったので、Issues を見てみる。

https://github.com/rails/rails/issues?utf8=%E2%9C%93&q=keyword-arguments%20is%3Aopen%20

**Comment by junk0612** [comment]
これをみてみたけど、英語が難しくてよくわからない...

https://github.com/rails/rails/pull/24519

**Comment by junk0612** [comment]
ちょっと近そうな PR を見つけた。

https://github.com/rails/rails/issues/22982

**Comment by junk0612** [comment]
これはテストケースの話だったみたいなのでちょっと違った。

**Comment by junk0612** [comment]
`kwargs` とか `keyword argument` とかで探してみたけど、それらしい Issue は見つからなかった。

調べ始めるとついつい終わるまでメモをとるのを忘れがちになるので気をつける。

**Comment by junk0612** [comment]
forkした。

https://github.com/junk0612/rails

**Comment by junk0612** [comment]
clone する。

```sh
git clone git@github.com:junk0612/rails.git

**Comment by junk0612** [comment]
`bundle install` はOK。

```
Bundle complete! 55 Gemfile dependencies, 133 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by junk0612** [comment]
`rake test` が落ちた。

**Comment by junk0612** [comment]
随分落ちているので、なにか足りないコンポーネントがありそうだと思った。
ひとまずエラーメッセージを読んでみる。

```
  1) Error:
FileUpdateCheckerTest#test_should_not_execute_the_block_if_no_paths_are_given:
Gem::LoadError: Could not find 'rb-inotify' (>= 0.9.7, ~> 0.9) among 126 total gem(s)
Checked in 'GEM_PATH=/Users/ENIXER/.gem/ruby/2.3.0:/Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0', execute `gem env` for more information
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
    /Users/ENIXER/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/lib/active_support/dependencies.rb:292:in `block in require'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/lib/active_support/dependencies.rb:258:in `load_dependency'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/lib/active_support/dependencies.rb:292:in `require'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/test/file_update_checker_shared_tests.rb:26:in `block (2 levels) in <module:FileUpdateCheckerSharedTests>'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:13:in `block in silence_warnings'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:26:in `with_warnings'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:13:in `silence_warnings'
    /Users/ENIXER/git/github.com/junk0612/rails/activesupport/test/file_update_checker_shared_tests.rb:26:in `block in <module:FileUpdateCheckerSharedTests>'
```

**Comment by junk0612** [comment]
みていると、`listen` という gem と `rb-inotify` という gem が足りない模様。

**Comment by junk0612** [comment]
何か見落としているかもしれないので、.travis.yml をよーく読んでみる。

**Comment by junk0612** [comment]
`script: ci/travis.rb` とあったのでそれも読んでみる。

**Comment by junk0612** [comment]
```
# FIXME: Remove this fork after https://github.com/nex3/rb-inotify/pull/49 is fixed.
gem "rb-inotify", github: "matthewd/rb-inotify", branch: "close-handling", require: false
```

FIXMEがある！！

**Comment by junk0612** [comment]
このコード自体は 4ヶ月くらい前 (28 Jul) に書かれていて、コメントされている [PR](https://github.com/nex3/rb-inotify/pull/49#issue-119237120) は議論はされているようだがマージされていない。

**Comment by junk0612** [comment]
ん、`bundle exec` が足りなかったか...？

**Comment by junk0612** [comment]
`bundle exec rake test` を rails のルートディレクトリで実行すると、だいぶ時間がかかる。

**Comment by junk0612** [comment]
実装しようとすると、このワークショップの時間内では終わらなさそう...

ex. https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L808 のメソッド内のすべてのキーを置き換える。

**Comment by junk0612** [comment]
キーワード引数で置き換えようと思うんだけどどうだろう、という Issue を立ててみることにする。

**Comment by junk0612** [comment]
言いたいこと
---

Rails のハッシュでごそっと受け取っている引数をキーワード引数を利用する形に置き換えたい。

例
---

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L808

```ruby
def scope(*args)
  options = args.extract_options!.dup
  scope = {}

  options[:path] = args.flatten.join("/") if args.any?
  options[:constraints] ||= {}

  unless nested_scope?
    options[:shallow_path] ||= options[:path] if options.key?(:path)
    options[:shallow_prefix] ||= options[:as] if options.key?(:as)
  end

  if options[:constraints].is_a?(Hash)
    defaults = options[:constraints].select do |k, v|
      URL_OPTIONS.include?(k) && (v.is_a?(String) || v.is_a?(Integer))
    end

    options[:defaults] = defaults.merge(options[:defaults] || {})
  else
    block, options[:constraints] = options[:constraints], {}
  end

  if options.key?(:only) || options.key?(:except)
    scope[:action_options] = { only: options.delete(:only),
                               except: options.delete(:except) }
  end
```

```ruby
def scope(path: nil, constraints: {}, shallow_path: nil, defaults: {}, only: nil, except: nil, *args)
  scope = {}

  path = args.flatten.join("/") if path || constraints.any? || shallow_path || defaults.any? || only || except

  unless nested_scope?
    shallow_path ||= options[:path] if options.key?(:path)
    options[:shallow_prefix] ||= options[:as] if options.key?(:as)
  end

  if constraints.is_a?(Hash)
    local_defaults = constraints.select do |k, v|
      URL_OPTIONS.include?(k) && (v.is_a?(String) || v.is_a?(Integer))
    end

    defaults = local_defaults.merge(defaults)
  else
    block, constraints = constraints, {}
  end

  if only || except
    scope[:action_options] = { only: only, except: except }
  end
```

メリット
---

- メソッドのシグネチャが見やすくなる
- メソッド内で対応しないキーが与えられたときにエラーになって教えてくれる
- コードがリーダブルに！ (`options` という変数を参照しなくなる)

**Comment by junk0612** [comment]
http://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Scoping.html#method-i-scope は
`scope(*args)` というシグネチャだけど、`scope(path: nil, constraints: {}, shallow_path: nil, defaults: {}, only: nil, except: nil, *args)` みたいなシグネチャになる。

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-28に開催](https://oss-gate.doorkeeper.jp/events/52881)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
