### ISSUE TITLE
OSS Gate Workshop: online: 2022-10-29: somoriiin: Markdown All in One: Work log

### ISSUE THREAD

**Issue by somoriiin** [oss-gate/workshop#1583]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by somoriiin** [comment]
対象のOSS選定
自分が思いつくOSS？↓

- Ubuntu
- Mint
- Arch Linux 
- OpenSSL 
- VScode 
- Apache
- Apache Tomcat

**Comment by somoriiin** [comment]
CrankWheel Screen Sharingについて調査

**Comment by somoriiin** [comment]
/ Copyright (C) 2020 CrankWheel ehf. All Rights Reserved.
OSSではなさそうなので別のものを検討

**Comment by somoriiin** [comment]
Markdown All in OneというVScodeのプラグインを調査
[https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one](url)
このサイトからGithubに飛ぶ。
[github](https://github.com/yzhang-gh/vscode-markdown/blob/master/LICENSE)
MIT Licenseであることを確認した。

**Comment by somoriiin** [comment]
Markdown All in Oneのインストールを試す。

1. VScodeを起動する。
2. Markdown All in Oneがすでにインストールされていた。
3. ExtenshionsのMARKETPLACEでアンインストールをした。
4. VScodeを再起動
5. ExtenshionsのMARKETPLACEでインストールボタンを押下してインストールした。

**Comment by somoriiin** [comment]
ReadMEに書かれている機能を順番に試していく。
https://github.com/yzhang-gh/vscode-markdown#features

**Comment by somoriiin** [comment]
Fileの用意
VScodeの[NewFile]を押下して、ファイルを作成する。
ファイル名の拡張子は[.md]にする。
今回は[ossgate.md]とした。

**Comment by somoriiin** [comment]
ossgate.mdに文章を入力する。
```
normal

mulitply words

bold
```
文字の無いところで[Ctrl＋B]を押す。
すると、カーソル位置にアスタリスク4つが挿入された。
```
normal

mulitply words

bold
****
```

**Comment by somoriiin** [comment]
[normal]の真ん中にカーソルがある状態で[Ctrl+B]を押す。
```
**normal**

mulitply words

bold
****
```

**Comment by somoriiin** [comment]
Readmeのアニメーションだと、[multiply words]を選択して、[Ctrl+B]を押すと、アスタリスクが単語毎に付くように見える。
[]

**Comment by piroor** [comment]
自分の手元でも試してみたら変な躓き方をしてしまいました……

1. 拡張機能をインストールした
2. エクスプローラーの「開いているエディター」の所の「＋」ボタン（無題の新規ファイル）をクリックした
3. （名前を付けずにそのまま）normalと入力して、Ctrl-Bを押した

Markdownの太字強調になるかと思ったのだが、ならない……
（サイドバーのトグルになってしまう）

ファイル名に「.md」と拡張子を付けて保存した状態でやってみたところ、今度はサイドバーのトグルではなく、太字強調のON/OFFになった。
Markdownファイル以外では機能しないんですね、この拡張機能。

**Comment by somoriiin** [comment]
ファイル名を[.md]にしないとこの機能が使えないことはドキュメントにかいてあるだろうか。

**Comment by somoriiin** [comment]
Issueを出す。
[vscode-markdownのissue](https://github.com/yzhang-gh/vscode-markdown/issues)

フォーマット見つけた。
```
<!--
⚠ Before proceeding:

Check FAQ (command not found, Markdown syntaxes, performance issues, etc.):
https://github.com/yzhang-gh/vscode-markdown#faq

Test the latest dev build if needed:
https://github.com/yzhang-gh/vscode-markdown/actions/workflows/main.yml?query=event%3Apush+is%3Asuccess
-->

### What's the problem



### What's the expected result



### How to reproduce

1. ...
2. ...

### Other information



```

**Comment by somoriiin** [comment]
### Proposal



### Other information

**Comment by somoriiin** [comment]
VScodeにはLanguage modeがある。この機能によってMarkdownに設定すると、Markdown All In Oneを使えるようになる。拡張子でプラグインが使えるか使えないかにはならない。

**Comment by daipom** [comment]
READMEの「Keyboard shortcuts」の説明を読んでいて、「multiply words」のやり方が最初分かりませんでした。

> Readmeのアニメーションだと、[multiply words]を選択して、[Ctrl+B]を押すと、アスタリスクが単語毎に付くように見える。
> 
>     1. [multiply words]にカーソルを合わせて、選択する
> 
>     2. 選択した状態のまま [Ctrl+B]を押す。
> 
>     3. `**mulitply words**`と、アスタリスクが入力される。
> 
> 
> ```
> normal
> 
> **multiply words**
> 
> bold
> ```

調べると、次のようにマルチカーソルの機能を使えばできることが分かりました。

> 一方で、Altを押しながら単語をダブルクリックすると、単語ごとに選択することができる。 Readmeのアニメーションはこのやり方のようだけど、この説明はない。
> 
>     1. Altを押しながら単語`mulitply`と`words`をダブルクリックする（マルチカーソル）
> 
>     2. そうすると、[multiply]と[words]と別々に選択される
> 
>     3. 選択した状態のまま [Ctrl+B]を押す
> 
>     4. `**multiply** **words**`と、アスタリスクが入力される。
> 
> 
> ```
> normal
> 
> **multiply** **words**
> 
> bold
> ```

確かに、画像を見るとマルチカーソルで選択されているので、マルチカーソル機能を使い慣れている人には分かるかもしれませんが、
この機能を使い慣れていない人にとってはやり方が分からないと思います。

一言、次のような説明を足すのはどうでしょうか？

oxoxoxoxox

**Comment by somoriiin** [comment]
> READMEの「Keyboard shortcuts」の説明を読んでいて、「multiply words」のやり方が最初分かりませんでした。
> 
> > Readmeのアニメーションだと、[multiply words]を選択して、[Ctrl+B]を押すと、アスタリスクが単語毎に付くように見える。
> > ```
> > 1. [multiply words]にカーソルを合わせて、選択する
> > 
> > 2. 選択した状態のまま [Ctrl+B]を押す。
> > 
> > 3. `**mulitply words**`と、アスタリスクが入力される。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > normal
> > 
> > **multiply words**
> > 
> > bold
> > ```
> 
> 調べると、次のようにマルチカーソルの機能を使えばできることが分かりました。
> 
> > 一方で、Altを押しながら単語をダブルクリックすると、単語ごとに選択することができる。 Readmeのアニメーションはこのやり方のようだけど、この説明はない。
> > ```
> > 1. Altを押しながら単語`mulitply`と`words`をダブルクリックする（マルチカーソル）
> > 
> > 2. そうすると、[multiply]と[words]と別々に選択される
> > 
> > 3. 選択した状態のまま [Ctrl+B]を押す
> > 
> > 4. `**multiply** **words**`と、アスタリスクが入力される。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > normal
> > 
> > **multiply** **words**
> > 
> > bold
> > ```
> 
> 確かに、画像を見るとマルチカーソルで選択されているので、マルチカーソル機能を使い慣れている人には分かるかもしれませんが、 この機能を使い慣れていない人にとってはやり方が分からないと思います。
> 
> 一言、次のような説明を足すのはどうでしょうか？
> 
> oxoxoxoxox


https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts
キーボードショートカットのアニメーションの下で次のように説明するのはどうてしょうか。
Tips：
1. Altを押しながら単語`mulitply`と`words`をダブルクリックする（マルチカーソル）
2. そうすると、[multiply]と[words]と別々に選択される
3. 選択した状態のまま [Ctrl+B]を押す
4. `**multiply** **words**`と、アスタリスクが入力される。

**Comment by daipom** [comment]
README: How about adding that we can use this feature by selecting Markdown Language Mode?

**Comment by somoriiin** [comment]
I suggest that you explain that this plugin can be used by selecting Markdown in VScode's Language Mode, even if it does not have a `.md` extension.
As a test, Markdown All In One could be used by selecting Markdown in Language Mode, even if it is a text file extension.
The LanguageMode is automatically selected by VScode. If Markdown is not selected, Markdown All In One cannot be used.
For example, pressing Ctrl+B in that state will only open and close the VScode sidebar, not insert an asterisk.

Translated with www.DeepL.com/Translator (free version)

**Comment by daipom** [comment]
For example

**Comment by daipom** [comment]
I suggest that we can add explanation that ...

**Comment by somoriiin** [comment]
Issue投稿した
Title:
README: How about adding that we can use this feature by selecting Markdown Language Mode?
```
<!--
⚠ Before proceeding:

Check FAQ (command not found, Markdown syntaxes, performance issues, etc.):
https://github.com/yzhang-gh/vscode-markdown#faq
-->

### Proposal

I suggest that we can add an explanation that this plugin can be used by selecting Markdown in VScode's Language Mode, even if it does not have a `.md` extension.

For exampe, Markdown All In One can be used by selecting Markdown in Language Mode, even if it is a text file extension.
The Language Mode is automatically selected by VScode. If Markdown is not selected, Markdown All In One cannot be used.

For example, pressing Ctrl+B in that state will only open and close the VScode sidebar, not insert an asterisk.


### Other information

<!--
(Optional) Give more context to help us understand.
-->


```

**Comment by somoriiin** [comment]
振り返り
- 次のアクション
- マルチカーソルの説明をまとめてIssueを投げる
- https://github.com/yzhang-gh/vscode-markdown/issues/1190についてプルリクを投げる

**Comment by daipom** [comment]
I meant ...

**Comment by somoriiin** [comment]
明日からやってみたいこと

- 今回学んだように、自分が使っているOSSを調べて、ユーザーとしてOSSを公式通りに動かしてみて、Issueを投げるをやってみたい。
- https://github.com/yzhang-gh/vscode-markdown/issues/1190
すでに返信が来ているため、返信を書く。

**Comment by daipom** [comment]
> https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts 
> キーボードショートカットのアニメーションの下で次のように説明するのはどうてしょうか。
>  Tips：
> 
>     1. Altを押しながら単語`mulitply`と`words`をダブルクリックする（マルチカーソル）
> 
>     2. そうすると、[multiply]と[words]と別々に選択される
> 
>     3. 選択した状態のまま [Ctrl+B]を押す
> 
>     4. `**multiply** **words**`と、アスタリスクが入力される。

時間がなくてこちらについてお話しできなかったので、一応コメントさせていただきます！

ガッツリとした説明を足すのであればこういうのが好ましいと思いますが、
もし簡単な説明でいいから欲しいな〜、みたいな方向性で提案するなら以下のような説明でも良いかもしれないと思いました。

---

キーボードショートカットのアニメーションの下で次のように説明するのはどうでしょうか。

* (マルチカーソルで複数選択しています(Alt + double-click))

---

英語:

How about adding an explanation under the image of [Keyboard shorkcuts](https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts) as following?

* (Selecting multiple words by VScode's Multi-Cursor feature(Alt + double-click))

**Comment by somoriiin** [comment]
https://github.com/yzhang-gh/vscode-markdown/issues/1190
>  Thanks for the suggestion.
> 
> However, to me it is kind of strange to tell the users to select the Markdown language mode for a non-Markdown file (which will disable the functionalities from its original language). Recently I have added support for RMarkdown documents (#618). And it seems to provide better compatibility.

返信内容　草稿
Thank you for replying so fast. 
I'd appreciate you making this so useful software.

I just meant "Can I add the message about using Markdown file on README?" on this issue. So, I just wanted to tell you that a few users think they can use this plugIn even though it's not Markdown file.

**Comment by daipom** [comment]
> Can I add the message about ...

は自分が修正したい！！(PR出したい！！)って感じに聞こえそうなので、
もし同意してもらえたら自分がPRを作るよ！！ということであればよいのですが、
もしそうではないならば`Should we add ...`などのほうが良いかもしれません。

shouldとweを使うことで「私達にとってその方が良くないですか？」みたいなニュアンスを出せると思います。

> So, I just wanted to tell you that a few users think they can use this plugIn even though it's not Markdown file.

ちょっとこれは意図が伝わらないかもと感じています。
ちょっと言い回しを僕の方でも考えてみますね

**Comment by daipom** [comment]
具体例を挙げたほうが伝わりやすいかも、piroさんの例みたいな

例えば、まだファイル名を決めていない(`untitled`な)ファイルを作った時にこの機能使えないんです、みたいな。

When I create a new `untitled` file, I can't use this feature without setting the language mode.

**Comment by somoriiin** [comment]
daipomさんありがとうございます。
たしかに、この例は状況が相手にもわかってとてもいいですね。

> 例えば、まだファイル名を決めていない(untitledな)ファイルを作った時にこの機能使えないんです、みたいな。
> 
> When I create a new untitled file, I can't use this feature without setting the language mode.

**Comment by daipom** [comment]
例えばこんな感じとかどうでしょう！

Thank you for replying so fast. 
I'd appreciate you making this so useful software.

> it is kind of strange to tell the users to select the Markdown language mode for a non-Markdown file

That's true, but when I create a new `untitled` file, I can't use this feature without setting the language mode.

So I just thought it would be helpful to note that this feature is enabled when `Markdown` language mode is selected.

**Comment by daipom** [comment]
* 相手のメッセージを引用しておいて、「それは確かにそうだけれど、でもこういう時に困るんだよね」という流れにする
* その上で、だからoxoxであることを記載しておくのは便利なんじゃないかな、と思っただけなんですよ〜

って感じで英語を作ってみました！

**Comment by daipom** [comment]
上例では、記載してほしい内容を、「Markdown language modeが選択されている時にこの機能が有効になる」としてみています。

**Comment by daipom** [comment]
あくまで1つの参考にして頂ければ！！
元の文章の流れでいうと、次の点を改善できたら良いと思います。

> the message about using Markdown file on README?

ここがちょっと抽象的で伝わりにくいのかも。何の情報を足してほしいのか具体的にかけると分かりやすくなると思います！

> I just wanted to tell you that a few users think they can use this plugIn even though it's not Markdown file.

マークダウンファイルでなくてもこのプラグインを使えると思うユーザーが少数であると伝えたかっただけです、ということですよね。
これだけだと何が言いたいのか伝わりにくいと思うのですが、例えば上述したような具体的な例を紹介すれば、
「マークダウンファイルでなくてもこのプラグインを使える」となぜ嬉しいかという点を分かってもらえそうな気がします。

**Comment by somoriiin** [comment]
@daipom たくさんのTipsありがとうございます。
アドバイスを元に吟味してみます。

**Comment by somoriiin** [comment]
@daipom さんのほぼ丸コピーですが、下記の文章で返信返しました。

Thank you for replying so fast.
I'd appreciate you making this so useful software.

> it is kind of strange to tell the users to select the Markdown language mode for a non-Markdown file

That's true, but when I create a new `untitled file` like using `Ctrl+N`, I can't use this feature without setting the language mode.

So I just thought it would be helpful to note that this feature is enabled when `Markdown` language mode is selected.
