### ISSUE TITLE
OSS Gate Workshop: online: 2022-10-29: xpadev: Turbopack: Work log

### ISSUE THREAD

**Issue by xpadev-net** [oss-gate/workshop#1584]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by xpadev-net** [comment]
site: https://turbo.build/pack
repo: https://github.com/vercel/turbo
たどり着いた経緯: twitterで流れてきた

**Comment by xpadev-net** [comment]
license: MPL-2.0 (https://github.com/vercel/turbo/blob/main/LICENSE )

**Comment by xpadev-net** [comment]
とりあえずドキュメントを読んでサンプルを動かしてみる
https://turbo.build/pack/docs

**Comment by xpadev-net** [comment]
> npx create-next-app --example with-turbopack
What is your project named? ... trubo-test

とりあえずプロジェクト作成
パスに全角は無し
IDEはIdea
パッケージマネージャーはyarnらしい

**Comment by xpadev-net** [comment]
OSはwindows 11 22000.1098

**Comment by xpadev-net** [comment]
とりあえずturboでdevサーバーを起動できた

**Comment by xpadev-net** [comment]
>error - [rendering] [root of the dev server]/context/clothing
  Error during SSR Rendering
  timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/context/books
  Error during SSR Rendering
  timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/context/electronics
  Error during SSR Rendering
  timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/styling/global-css
  Error during SSR Rendering
  timed out waiting for the Node.js process to connect

環境固有？

**Comment by xpadev-net** [comment]
↑タブを切り替えていたら発生した
時間経過なのか切り替えによるものなのかはわからない

**Comment by xpadev-net** [comment]
https://github.com/vercel/turbo/issues/2479
同様のissueがすでに出ていた

**Comment by xpadev-net** [comment]
↑元issueに通知が行ってしまったので以後貼るときは気をつける

**Comment by xpadev-net** [comment]
特定のタブを開いたときに発生するわけでは無いっぽい
建ってるissueでもランダムに落ちると書いてある

**Comment by daipom** [comment]
> ↑元issueに通知が行ってしまったので以後貼るときは気をつける


あ！それはあまり気にしなくて大丈夫ですよ！
workshopの題材になってるんだな〜、という微笑ましい感じになるだけだと思いますｗ

**Comment by xpadev-net** [comment]
自動では復活しない模様
再起動で復旧する

**Comment by xpadev-net** [comment]
サンプルプロジェクトはそりゃうまく動くだろうということで自分のnextjs12のプロジェクトをnextjs13にあげて動かしてみる

**Comment by daipom** [comment]
> ↑タブを切り替えていたら発生した 時間経過なのか切り替えによるものなのかはわからない

> 特定のタブを開いたときに発生するわけでは無いっぽい 建ってるissueでもランダムに落ちると書いてある

> 自動では復活しない模様 再起動で復旧する

もし再現可能な挙動を発見できたら、このissueに情報を足してあげると喜ばれると思います！

**Comment by xpadev-net** [comment]
>Error: You are using configuration and/or tools that are not yet
supported by Next.js v13 with Turbopack:
>
>- Babel detected (.babelrc)
  Babel is not yet supported. To use Turbopack at the moment,
  you'll need to remove your usage of Babel.
>
>- Unsupported Next.js configuration option(s) (next.config.js)
  The only configurations options supported are:
    - experimental.serverComponentsExternalPackages
    - experimental.transpilePackages
  To use Turbopack, remove other configuration options.


babel未対応だから無理って言われた
特に重要ではない設定だったので一旦コンフィグ削除

**Comment by daipom** [comment]
* 僕の環境でもこれ起こりました。どうやらこの操作をするときにエラーが発生するようです。

とか！そういうコメントはよくあることだと思います！

**Comment by xpadev-net** [comment]
>babel未対応だから無理って言われた
特に重要ではない設定だったので一旦コンフィグ削除

SSRでstyled-componentsを有効化出来ないので無理だった

**Comment by xpadev-net** [comment]
>もし再現可能な挙動を発見できたら、このissueに情報を足してあげると喜ばれると思います！

ので条件を探ってみる

**Comment by daipom** [comment]
```console
$ npx create-next-app --example with-turbopack
npx: 1個のパッケージを1.857秒でインストールしました。
✔ What is your project named? … my-app
Creating a new Next.js app in /home/daipom/work/ossgateworkshop/turbo/my-app.

Downloading files for example with-turbopack. This might take a moment.

Installing packages. This might take a couple of minutes.


> core-js-pure@3.26.0 postinstall /home/daipom/work/ossgateworkshop/turbo/my-app/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> undefined postinstall /home/daipom/work/ossgateworkshop/turbo/my-app
> npm run tailwind


> @ tailwind /home/daipom/work/ossgateworkshop/turbo/my-app
> tailwindcss -i styles/globals.css -o styles/dist.css

/home/daipom/work/ossgateworkshop/turbo/my-app/node_modules/tailwindcss/lib/cli.js:214
        throw err;
        ^

TypeError: Object.fromEntries is not a function
    at args (/home/daipom/work/ossgateworkshop/turbo/my-app/node_modules/tailwindcss/lib/cli.js:158:47)
    at Object.<anonymous> (/home/daipom/work/ossgateworkshop/turbo/my-app/node_modules/tailwindcss/lib/cli.js:216:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ tailwind: `tailwindcss -i styles/globals.css -o styles/dist.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ tailwind script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daipom/.npm/_logs/2022-10-29T02_37_54_635Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined postinstall: `npm run tailwind`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the undefined postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daipom/.npm/_logs/2022-10-29T02_37_54_656Z-debug.log

Aborting installation.
  npm install has failed.
```

**Comment by xpadev-net** [comment]
https://github.com/nodejs/release#release-schedule

**Comment by xpadev-net** [comment]
m1 macで動かしてみたものの落ちなかった
node 16.15.1
yarn 1.22.19

**Comment by xpadev-net** [comment]
node 16.15.0
yarn 1.22.19
別ディレクトリで初回起動時にクラッシュ @ windows11

**Comment by honeniq** [comment]
node v14.15.4 のときに実行すると、同じエラーが出ていました。
そのあと「nodeめっちゃ古いやんけ」と思い、v18.12.0 にアップグレード
create-next-app も古いよと言われたのでアップデートすると、エラーが出なくなっちゃいました。

**Comment by xpadev-net** [comment]
メモリ使用量が6GB行ったのでもしかしたらメモリ不足で落ちてるのかも？
ただ確かキャッシュをメモリに保持するって話だったのでそのせいかもしれない

**Comment by piroor** [comment]
https://github.com/vercel/turbo/blob/main/package.json ではNode.jsの要求バージョンが明示されてないんですね

**Comment by xpadev-net** [comment]
https://qiita.com/suin/items/994458418c737cc9c3e8

**Comment by xpadev-net** [comment]
https://github.com/vercel/next.js/blob/d510204fe554561afd1cbe189cf821e7220eb21e/package.json#L220
↑nextjsのpackage.json
付属で使われること想定のために書いてないのかもしれない

**Comment by xpadev-net** [comment]
なぜか再起動しても同様のエラーが再発するようになった

**Comment by xpadev-net** [comment]
メモリの空き容量が少ない場合に発生するのかもしれない

**Comment by xpadev-net** [comment]
(現在9/16GB)

**Comment by xpadev-net** [comment]
A similar error occurred

### What version of Turbopack are you using?
nextjs 13.0.0

### What package manager are you using / does the bug impact?
yarn 1.22.19 / probably no

### What operating system are you using?
win11 21h2 (22000.1098)


### Describe the Bug
When running the yarn run dev or npm run dev on the default turbopack npx create-next-app --example with-turbopack example. The app randomly crashes and produces the following the error:

>error - [rendering] [root of the dev server]/context/clothing
Error during SSR Rendering
timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/context/books
Error during SSR Rendering
timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/context/electronics
Error during SSR Rendering
timed out waiting for the Node.js process to connect
error - [rendering] [root of the dev server]/styling/global-css
Error during SSR Rendering
timed out waiting for the Node.js process to connect

### Expected Behavior

The error shouldn't exist as there were no modifications made to any of the files.

### env
node 16.15.0
yarn 1.22.19
win11 21h2 (22000.1098) / i5-9600K / 16GB

### To Reproduce
1. Use `npx create-next-app --example with-turbopack` and create the app with any name.
2. Run `npm run dev`.
3. The above error occurs rarely when opening the application in a browser

Often crashed on first startup
Also, crashes often occurred when memory usage was high.

**Comment by xpadev-net** [comment]
![image](https://user-images.githubusercontent.com/96982836/198815224-66fa4ded-40cd-4a91-9651-c7cd8bc7a7ad.png)
