### ISSUE TITLE
OSS Gate Workshop: online: 2022-12-10: Kyohei Fukuda(hand-dot): pdfme: Work log

### ISSUE THREAD

**Issue by hand-dot** [oss-gate/workshop#1594]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hand-dot** [comment]
下記の自作のpdfmeというPDF作成ライブラリにて、リクエストが上がっている機能の対応を行う
https://github.com/pdfme/pdfme

今回のワークショップで対応したいissueは下記の内容です
https://github.com/pdfme/pdfme/issues/101

**Comment by hand-dot** [comment]
Tree Shakeに対応したライブラリにすることで、バンドルサイズが巨大化してしまう問題を対応したい

**Comment by hand-dot** [comment]
webpackのコミュニティーなど、詳しい人がいるコミュニティーに聞いてみる？

**Comment by hand-dot** [comment]
pioorさんに相談してやることが変わった

- issueテンプレート
- バグトリアージの運用

を作る

また、自分でできないことに関しては、それをIssueコメント内で返信するようにする

**Comment by hand-dot** [comment]
とりあえずTree Shakeのissueについてはコメントをしておいた
https://github.com/pdfme/pdfme/issues/101#issuecomment-1345148441

**Comment by hand-dot** [comment]
github運用に関して、下記のpiroorさんのスクリプトを参考にして動かして生きた

https://github.com/piroor/treestyletab/tree/trunk/.github

**Comment by daipom** [comment]
自分の印象に残っている事例をピックアップしておきます

* https://github.com/raysan5/raylib
  * 「サポートフォーラムとしてissueを使わないで」とissueテンプレートに明記している
* https://github.com/fluent-plugins-nursery/fluent-plugin-remote_syslog
  * 回答したらansweredタグを付ける、その後一定期間更新がなければ自動で閉じる

**Comment by hand-dot** [comment]
@daipom  非常に参考になります.... ありがとうございます！！！

**Comment by hand-dot** [comment]
テンプレート設置できた〜！

https://github.com/pdfme/pdfme/issues/new/choose

**Comment by hand-dot** [comment]
次は github/workflows でIssueが勝手に閉じられるようにしていく...!

**Comment by hand-dot** [comment]
とりあえず、設置できた。
https://github.com/pdfme/pdfme/actions/workflows/close-answered-issues.yml

過去に答えたIssueに anwerd ラベルをつけていってみる
