### ISSUE TITLE
OSS Gate Workshop: online: 2022-12-10: kamiya-s-max: moto: Work log

### ISSUE THREAD

**Issue by kamiya-s-max** [oss-gate/workshop#1595]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kamiya-s-max** [comment]
候補: pytest
公式ドキュメント: https://docs.pytest.org/en/7.2.x/
github リポジトリ: https://github.com/pytest-dev/pytest/

**Comment by kamiya-s-max** [comment]
pytest のライセンス:
ライセンスファイル
https://github.com/pytest-dev/pytest/blob/main/LICENSE

↑ では The MIT License (MIT) とある

**Comment by kamiya-s-max** [comment]
候補: moto
公式ドキュメント: https://docs.getmoto.org/en/latest/index.html
github リポジトリ: https://github.com/spulec/moto

**Comment by kamiya-s-max** [comment]
moto のライセンス:
ライセンスファイル
https://github.com/spulec/moto/blob/master/LICENSE

↑ Apache License Version 2.0

**Comment by kamiya-s-max** [comment]
Python プロジェクト: oss_gate_project を作成
以下のライブラリをあらかじめ pip install
- boto3 1.26.27
- pytest 7.2.0

**Comment by kamiya-s-max** [comment]
https://docs.getmoto.org/en/latest/docs/getting_started.html
↑ 上記のインストール方法をもとに moto をインストール
 If you don’t care about the number of dependencies, or if you want to mock many AWS services:
`pip install 'moto[all]'`

**Comment by daipom** [comment]
本番環境へ意図しない影響を与えてしまうことを回避することに関してのドキュメント

http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure

**Comment by kamiya-s-max** [comment]
普段使っていて思っていること：本当にリソースがモックできているのか不安になる時がある

**Comment by kamiya-s-max** [comment]
デバッガ を使って処理を見てみる？

**Comment by daipom** [comment]
boto3のcredential関連の仕様で、設定が反映される優先順位については次に記載がありそう

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

**Comment by kamiya-s-max** [comment]
http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure
↑ に、boto3 のクレデンシャル読み込みの優先順位↓ の記載(あるいはリンク)があった方が納得しやすい
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

**Comment by daipom** [comment]
```python
session = boto3.Session()
session.get_credentials().access_key
```

**Comment by daipom** [comment]
> boto3のcredential関連の仕様で、設定が反映される優先順位については次に記載がありそう
> 
> https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

この優先順位で少し気になった点として、
確かに環境変数をセットすれば`~/.aws/credentials`よりも優先されそうだが、
それでも3番目の優先順位である、という点。

1,2番目として記載されているように、clientやsessionオブジェクトを作成する際に直接引数で値を指定しまうと、
環境変数よりもそちらが優先されそう。

例えばもし本番コードが次のようにSessionオブジェクトを作成していた場合は危険があるかもしれない。

```python
session = boto3.Session(aws_access_key_id="hoge", aws_secret_access_key="fuga")
```

**Comment by kamiya-s-max** [comment]
client で資格情報を指定する例
```
import boto3

client = boto3.client(
    's3',
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    aws_session_token=SESSION_TOKEN
)
```

**Comment by daipom** [comment]
```python
import os
import boto3
from moto import mock_s3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session()
session.get_credentials().access_key
=> 'test'

session = boto3.Session(aws_access_key_id="hoge", aws_secret_access_key="fuga")
session.get_credentials().access_key
=> 'hoge'
```

**Comment by kamiya-s-max** [comment]
moto の CONTRIBUTING.md
https://github.com/spulec/moto/blob/master/CONTRIBUTING.md

**Comment by daipom** [comment]
コントリビュートに関して

* http://docs.getmoto.org/en/latest/docs/contributing/index.html
* https://github.com/spulec/moto/blob/master/CONTRIBUTING.md

**Comment by daipom** [comment]
以下をザッと確認したところ、既存の報告や質問は無さそう

* issues: https://github.com/spulec/moto/issues?page=1&q=is%3Aissue+credential
* FAQ: http://docs.getmoto.org/en/latest/docs/faq.html#contributing-faq

**Comment by kamiya-s-max** [comment]
# 書きたいこと
- How do I avoid tests from mutating my real infrastructure において、環境変数にダミーの認証情報を入れることで、実際の AWS リソースを変更することを防ぐとある
  - http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure
- boto3 のドキュメントによると、環境変数からの認証情報の読み込みの優先順位は 3番目であり、client や session 作成時に指定した場合は、そちらが優先される
  - https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials
- テスト対象のコード内で client や session 作成時に認証情報を読み込んでいないかを確認するような注意喚起があった方が良い

**Comment by daipom** [comment]
バグ報告であれば、再現方法、期待値、実際の結果、の3章立てで明確に意図が伝わるのですが、
今回は修正提案なので、その辺りがちょっとむずかしいかなと思います。
例えば次のような話の流れにするとすっきりするかもしれません。

* 本番環境へ影響を与えてしまうことを避けるための方法がooxxに書いてあるが、これで本当に回避できているのか不安です
  * ↑冒頭でissueを立てたモチベを明確にすると良いかも。「本当に回避できているのかが不安」という点？
* 調べてみると、ooxxのドキュメントを見つけ、確かに`~/.aws/credentials`よりは優先されることが分かりました
* しかし、上ドキュメントによると、直接hogeやfugaなどの引数に指定した場合は、そちらのほうが優先されてしまいます
* `~/.aws/credentials`よりは優先されるが、直接引数で指定した場合は防げないことを、ドキュメントに足した方が良さそうだと思いました

**Comment by daipom** [comment]
motoのissueテンプレート

```markdown
## Reporting Bugs

Please be aware of the following things when filing bug reports:

1. Avoid raising duplicate issues. *Please* use the GitHub issue search feature
   to check whether your bug report or feature request has been mentioned in
   the past.
2. When filing bug reports about exceptions or tracebacks, please include the
   *complete* traceback. Partial tracebacks, or just the exception text, are
   not helpful.
3. Make sure you provide a suitable amount of information to work with. This
   means you should provide:

   - Guidance on **how to reproduce the issue**. Ideally, this should be a
     *small* code sample that can be run immediately by the maintainers.
     Failing that, let us know what you're doing, how often it happens, what
     environment you're using, etc. Be thorough: it prevents us needing to ask
     further questions.
   - Tell us **what you expected to happen**. When we run your example code,
     what are we expecting to happen? What does "success" look like for your
     code?
   - Tell us **what actually happens**. It's not helpful for you to say "it
     doesn't work" or "it fails". Tell us *how* it fails: do you get an
     exception? A hang? How was the actual result different from your expected
     result?
   - Tell us **what version of Moto you're using**, and
     **how you installed it**. Tell us whether you're using standalone server
     mode or the Python mocks. If you are using the Python mocks, include the
     version of boto/boto3/botocore.


   If you do not provide all of these things, it will take us much longer to
   fix your problem.
```

今回はバグ報告ではないので、一応次の点を付け足しておけば大丈夫そう

* Motoのバージョン
* どうやってインストールしたか

**Comment by kamiya-s-max** [comment]
ドキュメントに追加した方が良い注意事項があると考えています。

現在、ドキュメントの How do I avoid tests from mutating my real infrastructure(http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure) の項目にはこう書かれています。

> You need to ensure that the mocks are actually in place.
> 
> 1. Ensure that your tests have dummy environment variables set up:
> ```
> export AWS_ACCESS_KEY_ID='testing'
> export AWS_SECRET_ACCESS_KEY='testing'
> export AWS_SECURITY_TOKEN='testing'
> export AWS_SESSION_TOKEN='testing'
> export AWS_DEFAULT_REGION='us-east-1'
> ```

これは、テスト対象コードの認証情報を ```~/.aws/credentials``` や、環境変数から読み込む場合には効果がありますが、```boto.client()``` メソッドの定義時や、 Session オブジェクトの作成時に認証情報を書いている場合は、そちらが優先されます。(参考: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)

なので、現在の How do I avoid tests from mutating my real infrastructure の項目内に、~/.aws/credentialsよりは優先されるが、```boto.client()``` メソッドの定義時や、 Session オブジェクトの作成時に認証情報を書いている場合には防げないことを書いた方が良いと思います。

**Comment by daipom** [comment]
`[]()`

**Comment by daipom** [comment]
[How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure)

**Comment by kamiya-s-max** [comment]
- Motoのバージョン
- どうやってインストールしたか
↑ 上記も何処かへ加える

英語に直す。(不安な場合は gitter に この issue の url を貼ってレビューしてもらう)

**Comment by kamiya-s-max** [comment]
- 「防げない」ではなく、「この方法を使うなら、テスト対象側のコードも修正してね」の方で書いた方がいいかも
- 余裕があれば、検証したコードと結果も貼るといいかも

**Comment by kamiya-s-max** [comment]
I believe there is a caveat that should be added to the document.

Currently, the [How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure)  section of the documentation says
> You need to ensure that the mocks are actually in place.
> 
> 1. Ensure that your tests have dummy environment variables set up:
> ```
> export AWS_ACCESS_KEY_ID='testing'
> export AWS_SECRET_ACCESS_KEY='testing'
> export AWS_SECURITY_TOKEN='testing'
> export AWS_SESSION_TOKEN='testing'
> export AWS_DEFAULT_REGION='us-east-1'
> ```
This method works well if the credentials are read from `~/.aws/credentials` or environment variables in the code under test, but if the credentials are specified when the `boto.client()` method is defined or the `Session` object is created, they will take precedence.
(reference: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)

So, in the [How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure) section, I think it would be a good idea to add a warning that if you use this method, you should not specify authentication information when defining the `boto.client()` method or when creating the `Session` object in the code to be tested. 

**My Environment**
- moto 4.0.11
- macOS Monterey 12.6
- Python 3.8
- venv 

**Installation Options**
- `pip install 'moto[all]'`

**Comment by kamiya-s-max** [comment]
# ↑ を再翻訳して確認

ドキュメントに追加すべき注意事項があると思います。

現在、ドキュメントの How do I avoid tests from mutating my real infrastructure のセクションには、次のように書かれています。
> You need to ensure that the mocks are actually in place.
> 
> 1. Ensure that your tests have dummy environment variables set up:
> ```
> export AWS_ACCESS_KEY_ID='testing'
> export AWS_SECRET_ACCESS_KEY='testing'
> export AWS_SECURITY_TOKEN='testing'
> export AWS_SESSION_TOKEN='testing'
> export AWS_DEFAULT_REGION='us-east-1'
> ```

この方法は、テスト対象のコード内で ~/.aws/credentials や環境変数から資格情報を読み込むとうまくいきますが、boto.client() メソッド定義時や Session オブジェクト生成時に資格情報を指定すると、そちらが優先されることになります。
(参考：https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)

例えば:
```
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session()
session.get_credentials().access_key
=> 'test'

```
↑ この場合、環境変数のダミー値が正しく使用されます。
```
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session(aws_access_key_id="hoge", aws_secret_access_key="fuga")
session.get_credentials().access_key
=> 'hoge'
```
↑ ただし、この場合、Sessionオブジェクト作成時のクレデンシャルが使用されます。

そこで、How do I avoid tests from mutating my real infrastructure の項で、この方法を使う場合は、テスト対象のコードでboto.client()メソッドを定義する際やSessionオブジェクトを生成する際に、クレデンシャルを指定してはいけないという警告を追加するとよいかと思います。

**私の環境**
- moto 4.0.11
- macOS Monterey 12.6
- Python 3.8
- venv

**インストール時のオプション**
- `pip install 'moto[all]'`

良さそう

**Comment by piroor** [comment]
caveatという単語はこの文脈で見たことがなかったです。
ふつうにwarningでいいのではないでしょうか？（後の文でもwarningという語を使っていますし）

「but if the credentials are specified when the `boto.client()` method is defined or the `Session` object is created, they will take precedence」
は、自分だったら
「but it won't effective if there are directly embedded credentials in the code (e.g. as a parameters for the `boto.client()` method or the constructor of the `Session` object)」
のように書くかなと思いました。
重要な事を文の頭の方で書いて、後からそれを修飾する方が、読み手が混乱しにくいように思います。

「In this case, the dummy value of the environment variable will be used correctly.」
の最後の
「correctly」
ですが、これだと「技術的に正しい」という意味になると思います。
ここでは「as expected（書いた人の意図通りである）」の方が、より伝えたい意図に近いんじゃないでしょうか。

「add a warning that if you use this method, you should not specify credentials when defining the boto.client() method or when creating the Session object in the code to be tested.」
という部分は、自分だったら「if～」を二重引用符で囲って例文であると分かりやすく示すか、もしくは、この例文自体が手前の話と重複することになるので、端的に
「add a warning to recommend people never embedding credentials to the code directly.」
と書くかなと思いました。

**Comment by piroor** [comment]
「 but, In this case, credentials at the time of Session object creation is used.」
ここは「credentials～is used」という主語と動詞の間に長い修飾が入っていますが、主語と動詞をもっと近付けて、名詞を前の方に前の方に寄せていき、修飾表現を後ろに追い出した方が読み手が混乱しにくい気がします。
自分だと、例えば
「but, in this case, the credentials finally used are the one given as parameters for `boto.client()`.」
と書くかなと思いました。

**Comment by piroor** [comment]
あと、先に要点を書いて後から説明するという書き方でいうと、
"It looks more helpful"（そのほうがより助かる、便利である）
という文を使って
”It looks more helpful for users that ～” （that以降で「どういうふうに書いておく」というアイデアを記載）
みたいに表現する書き方もあると思います。

こういった表現は、他の人の提案（issueやバグ報告）を見ていて「なるほど、そういう書き方もあるのか」みたいに覚えていった部分が自分は多いです。
提案内容自体は何も問題無くて、あとはどう書けば伝わるかという話なので、「自分が過去に見かけてきた提案だとこういう書き方をしていて、第三者の自分が見ても分かりやすかった」という例を思い出しながらレビューしてみました。

**Comment by daipom** [comment]
@kamiya-s-max 
全体的に大丈夫そうだと思いました！piroorさんのご指摘を取り入れるとさらに流暢な文になりそうです！
Pythonコードの例ですが、ブロックにシンタックスを付けるとより見やすくなると思います。
ブロックの開始時に特定の文字列を指定すると、それに応じたシンタックスを付けることができます。

* Pythonシンタックスのブロックを作る例

`````
```py
```
`````

**Comment by kamiya-s-max** [comment]
# 修正版
I think there is a warning that should be added to the document.

Currently, the [How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure)  section of the documentation says
> You need to ensure that the mocks are actually in place.
> 
> 1. Ensure that your tests have dummy environment variables set up:
> ```py
> export AWS_ACCESS_KEY_ID='testing'
> export AWS_SECRET_ACCESS_KEY='testing'
> export AWS_SECURITY_TOKEN='testing'
> export AWS_SESSION_TOKEN='testing'
> export AWS_DEFAULT_REGION='us-east-1'
> ```
This method works well if the credentials are read from `~/.aws/credentials` or environment variables in the code under test, but it won't effective if there are directly embedded credentials in the code.(e.g. as a parameters for the boto.client() method or the constructor of the Session object)

(reference: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)

For example :
```py
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session()
session.get_credentials().access_key
=> 'test'

```
↑ In this case, the dummy value of the environment variable will be used as expected.
```py
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session(aws_access_key_id="hoge", aws_secret_access_key="fuga")
session.get_credentials().access_key
=> 'hoge'
```
↑ but, in this case, the credentials finally used are the one given as parameters for `boto.client()`.

So, in the [How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure) section, I think It looks more helpful for users that add a warning to recommend people never embedding credentials to the code directly.

**My Environment**
- moto 4.0.11
- macOS Monterey 12.6
- Python 3.8
- venv 

**Installation Options**
- `pip install 'moto[all]'`

**Comment by kamiya-s-max** [comment]
@piroor @daipom 
↑ お二人のアドバイス部分をもとに修正してみました！

**Comment by daipom** [comment]
良いと思います！！

**Comment by piroor** [comment]
> I believe there is a warning that should be added to the document.

すみません、ここもコメントしそびれてました……
there isは多分「今実際にそこにある」ことを言い表す場面で使う表現なので、まだないものを指す時だと不自然なんじゃないかと思います。
thereの直後のisを原形に戻した上でshouldをその前に移動すると
I believe there should be a warning in the document.
という感じでよりすっきりして意味を取りやすくなるのではないでしょうか。
参考：https://pinasan.com/english/today_study/8339

ほかはいいのではないかと思います！

**Comment by kamiya-s-max** [comment]
@piroor @daipom 
ありがとうございます！↑ も取り入れて issue を出してみたいと思います！

**Comment by daipom** [comment]
あ

**Comment by daipom** [comment]
何度もすみません、改めて見ると、単に「ドキュメントに警告があった方が良い」という意味になっていて、
通じるのかどうかちょっと不安になりました。(意味が漠然としすぎ？？)

ネイティブじゃないので、ちょっとよくわからないですが、、
もしかしたら十分通じるのかも、、

自分なら次のようにするかもです。

「ドキュメントに **以下のことについての** 警告があった方が良い、と私は思います」

```
I believe there should be a warning about the following in the document.
```

**Comment by daipom** [comment]
issueを作った後でもコメントは編集できるので、もし同感だったら後から編集してもらえれば大丈夫です！

**Comment by kamiya-s-max** [comment]
@daipom 
ありがとうございます！

**Comment by kamiya-s-max** [comment]
# 修正版v3
I believe there should be a warning about the following in the document.

Currently, the [How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure)  section of the documentation says
> You need to ensure that the mocks are actually in place.
> 
> 1. Ensure that your tests have dummy environment variables set up:
> ```py
> export AWS_ACCESS_KEY_ID='testing'
> export AWS_SECRET_ACCESS_KEY='testing'
> export AWS_SECURITY_TOKEN='testing'
> export AWS_SESSION_TOKEN='testing'
> export AWS_DEFAULT_REGION='us-east-1'
> ```
This method works well if the credentials are read from `~/.aws/credentials` or environment variables in the code under test, but it won't effective if there are directly embedded credentials in the code.(e.g. as a parameters for the boto.client() method or the constructor of the Session object)

(reference: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials)

For example :
```py
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session()
session.get_credentials().access_key
=> 'test'

```
↑ In this case, the dummy value of the environment variable will be used as expected.
```py
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "test"
os.environ["AWS_SECRET_ACCESS_KEY"] = "test"

session = boto3.Session(aws_access_key_id="hoge", aws_secret_access_key="fuga")
session.get_credentials().access_key
=> 'hoge'
```
↑ but, in this case, the credentials finally used are the one given as parameters for `boto.client()`.

So, in the [How do I avoid tests from mutating my real infrastructure](http://docs.getmoto.org/en/latest/docs/getting_started.html#how-do-i-avoid-tests-from-mutating-my-real-infrastructure) section, I think It looks more helpful for users that add a warning to recommend people never embedding credentials to the code directly.

**My Environment**
- moto 4.0.11
- macOS Monterey 12.6
- Python 3.8
- venv 

**Installation Options**
- `pip install 'moto[all]'`

**Comment by daipom** [comment]
良いと思います！！

**Comment by kamiya-s-max** [comment]
moto へ追記しました！レビューありがとうございました！
https://github.com/spulec/moto/issues/5789

**Comment by kamiya-s-max** [comment]
@daipom @piroor 
moto へ issue 追加しました！レビューありがとうございました！
https://github.com/spulec/moto/issues/5789
