### ISSUE TITLE
Doorkeeperのイベント案内ページにワークショップの趣旨を明記する

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1598]
例えば https://oss-gate.doorkeeper.jp/events/141301 では、`「OSSの開発に参加する」を実際に体験するワークショップです。`の一文以外にワークショップの内容の説明がない。
既存のOSSに対してissueを立てる・プルリクエストを行うといったフィードバックの体験をすることが目的、ということはグループ自体の説明には書いてあるが、個々のイベントには書かれていないので、イベントページにも書くようにするとよさそう。
（実際に、趣旨を誤解されていた方がおられた）

**Comment by daipom** [comment]
少なくともこの「目的」はイベントページにもはっきり書いた方が良さそう。

https://github.com/oss-gate/workshop/blob/c6139d1a07a5fae9a0270d4de6f11d0bae0e849e/tutorial/scenario.md?plain=1#L16-L19

次のような一言？

```
本ワークショップの目的は、「OSS開発に参加する最初の一歩を支援すること」です。
```

具体的にやることについては、もしかしたら敢えてはっきりと定めていない可能性もあるかもしれないと思いました。
「最初の一歩」の踏み出し方は人によって異なっていて、基本的にはその人のやりたいことを支援する、というスタンスですもんね。

あまり事前に具体化しすぎずに、でもある程度内容をイメージできるような、そんな説明を考えたいなあと思うところです。

**Comment by kou** [comment]
今回は、「一歩目」がターゲットではないと誤解されていたのであっていますか？

であれば、↑の目的を書いておけば大丈夫そうです。

**Comment by piroor** [comment]
> 今回は、「一歩目」がターゲットではないと誤解されていたのであっていますか？

はい。
今回は、「すでに自分のOSSプロジェクトを持っていて他のプロジェクトにも度々コントリビュートされている方が、自分のプロジェクトのイシュートラッカーに寄せられた報告の対応について相談したい、という動機で来られた」という事例でした。
自分の印象では、Rubyだと言語のコミュニティにOSSプロジェクトオーナーが多そうでそういう話題を相談できそうな気がするんですが、曰く、TypeScriptやJSのコミュニティでは舶来の最新OSSをいち早く使うという動機で来られている方が多いそうで、プロジェクトオーナー視点での相談ができなくて困っていた……とのことでした。

**Comment by kou** [comment]
OSS Gateのチャットで相談できるよーみたいなのもどこかで宣伝できるとそういう人も救えそうですね。

**Comment by daipom** [comment]
取り急ぎ、次回のworkshopに向けて次のように更新してみました。

* 「目的」を明記
* 「内容」セクションを追加し、実際に行う内容について簡単に紹介

不備や改善点などあればご指摘ください！

https://oss-gate.doorkeeper.jp/events/141302

```diff
@@ -14,7 +14,7 @@ Discordを利用してのオンライン開催となります。各参加者が

 ## 概要

-「OSSの開発に参加する」を実際に体験するワークショップです。
+「OSSの開発に参加する」を実際に体験するワークショップです。本ワークショップの目的は、「OSS開発に参加する最初の一歩を支援すること」です。

 1月と4月と7月と10月は最終土曜日に10:30から17:00で開催しています。

@@ -92,6 +92,21 @@ OSSの開発に使えるパソコンを用意してください。「OSSの開
   * ワークショップ中に実際にOSSの開発に参加する
   * ワークショップ後も継続してOSSの開発に参加できそうな気持ちになる

+## 内容
+
+本ワークショップの目的は、「OSS開発に参加する最初の一歩を支援すること」です。実際にやることは「ビギナー」と「サポーター」で相談して決めますが、通常は次の内容を行います。
+
+  * 扱うOSSを「ビギナー」と「サポーター」で相談して決める
+  * 公式ドキュメント通りにそのOSSを動かす
+  * プロジェクトにフィードバックする
+
+フィードバックの例：
+
+  * 発見したインストールや動作時の問題に関して、GitHubのIssueやpull requestを作成する
+  * 発見した公式ドキュメントの不備に関して、GitHubのIssueやpull requestを作成する
+
+内容についてもっと詳しく知りたい人は、「概要」の「参考URL」をご覧ください。また、質問したいこと・不安なことがある、という人は[チャット](https://gitter.im/oss-gate/tokyo)で相談してください。
+
 ## 当日のプログラム

 |時間|やること|
```

**Comment by piroor** [comment]
シンプルにまとまっていて良いと思います！

**Comment by daipom** [comment]
ありがとうございます！とりあえずこれでしばらく行ってみます！
