### ISSUE TITLE
OSS Gate Workshop: online: 2023-01-28: FumiyaKai: laravel-debugbar: Work log

### ISSUE THREAD

**Issue by Fumiya-Kai** [oss-gate/workshop#1600]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Fumiya-Kai** [comment]
以下2つが気になっているのでライセンスを調べる。
[https://github.com/gdscjgec/Image-Editor/issues](https://github.com/gdscjgec/Image-Editor/issues)
[https://github.com/barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar)

**Comment by Fumiya-Kai** [comment]
laravel-debugbarから作業開始

**Comment by daipom** [comment]
`fetch`のエラーについてのissueがあった。

https://github.com/barryvdh/laravel-debugbar/issues/1311

同類の問題かもしれないが、対応してもらえないまま閉じられてしまっている。

**Comment by Fumiya-Kai** [comment]
## 事象
laravel-debugbarを有効にした状態でjsのfetchを使うと「Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position ~」のエラーが発生する

## 再現手順
### 環境
MacOS 11.3.1
chrome 109.0.5414.87
laravel 9.45.1
laravel-debugbar 3.7

### 手順

1. laravel-debugbarを有効にする
`DEBUGBAR_ENABLED = TRUE`

※laravel-debugbarを無効にするとうまくいく
`DEBUGBAR_ENABLED = FALSE`

2. laravelでapiを作成
```
Route::get('/test', function () {
    return response(json_encode(['test' => 'aaa']));
});
```
3. jsでfetchする
```
fetch(location.origin + '/api/test')
.then(response => response.json())
.then(data => console.log(data));
```
4. `php artisan serve`でサーバーを立ててページを開くと以下のエラーが出てデータの取得ができない
<img width="593" alt="スクリーンショット 2023-01-28 11 59 22" src="https://user-images.githubusercontent.com/52740717/215242924-99025fa2-93ae-452f-b24b-2e7ada76e20c.png">

## 期待される結果
上記例では以下のようにコンソールにデータが表示される
<img width="590" alt="スクリーンショット 2023-01-28 14 03 23" src="https://user-images.githubusercontent.com/52740717/215243117-71877f7a-4147-4535-b0ca-8e1b895e6452.png">

**Comment by daipom** [comment]
末尾にDebugbarをinjectします、という説明はあるようだ。

https://github.com/barryvdh/laravel-debugbar#usage

> By default, the Debugbar is injected just before </body>. If you want to inject the Debugbar yourself, set the config option 'inject' to false and use the renderer yourself and follow http://phpdebugbar.com/docs/rendering.html

> Note: Not using the auto-inject, will disable the Request information, because that is added After the response. You can add the default_request datacollector in the config as alternative.

**Comment by daipom** [comment]
再現手順

* How to reproduce
* To reproducec

**Comment by daipom** [comment]
メモ

* 一応、JSONのresponseならば末尾にinjectしないような設計になっていそう
  * https://github.com/barryvdh/laravel-debugbar/blob/master/src/LaravelDebugbar.php#L762
* ただし、GETする場合はいちいちcontent-typeを指定しないこともよくあるだろう
* そういうケースではJSONと判定することができなくて、末尾にinjectされてしまう
* それでは、ユーザーとして正しい対象方法は何か？
  * debugerのためにcontent-typeを指定するようコードを変更するのは本末転倒な感じ
  * readmeによればランタイムでON/OFFできるようなので、必要に応じてON/OFFするとか
  * readmeによればinjectの仕方をユーザー側で定義することもできるらしい
* issueで何を報告するべきか？
  * 結局一部のユーザーが困惑するであろう事実は変わらない
  * うまいことinjectの必要性を判定してほしいという要望を出す？
  * 困惑するので、もっとREADMEなどに分かりやすい説明や注意書きがほしいという要望を出す？
  * -> とりあえず、このような場合には末尾に追加しないようにできないか、という要望を出すことになった

**Comment by daipom** [comment]
`as follows`とか`following ~`とかを使って、文章とコード/ログメッセージなどを分けると書きやすいかもしれません！

* Start server as follows

```console
$ php artisan serve
```

* I failed `fetch` because of the following error

```
Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position ~
```

**Comment by Fumiya-Kai** [comment]
When I use `fetch` of javascript, I kept seeing `Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position ~`.

## How to reproduce
### environment
MacOS 11.3.1
chrome 109.0.5414.87
php 8.0.18
laravel 9.45.1
laravel-debugbar 3.7

## what I did

1. Enable laravel-debugbar
`DEBUGBAR_ENABLED = TRUE`

※if disenable laravel-debugbar, I succeeded.
`DEBUGBAR_ENABLED = FALSE`

2. Make Api
```
Route::get('/test', function () {
    return response(json_encode(['test' => 'aaa']));
});
```

3. Fetch from js
```
fetch(location.origin + '/api/test')
.then(response => response.json())
.then(data => console.log(data));
```

4. start server by `php artisan serve`
 
5. I failed fetch because of `Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position ~` error
<img width="593" alt="スクリーンショット 2023-01-28 11 59 22" src="https://user-images.githubusercontent.com/52740717/215242924-99025fa2-93ae-452f-b24b-2e7ada76e20c.png">

## Excepted
I excepted response data is shown in console.
<img width="590" alt="スクリーンショット 2023-01-28 14 03 23" src="https://user-images.githubusercontent.com/52740717/215243117-71877f7a-4147-4535-b0ca-8e1b895e6452.png">

laravel-debugbar inject code after response data, I propose stopping inject code when JSON response.
```
% curl http://127.0.0.1:8001/api/test
{"test":"aaa"}<link rel='stylesheet' type='text/css' property='stylesheet' href='//127.0.0.1:8001/_debugbar/assets/stylesheets?v=1657531602&theme=auto' data-turbolinks-eval='false' data-turbo-eval='false'><script src='//127.0.0.1:8001/_debugbar/assets/javascript?v=1657531602' data-turbolinks-eval='false' data-turbo-eval='false'>...
```
