### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: bambina: ruby/ruby: 作業ログ

### ISSUE THREAD

**Issue by Bambina** [oss-gate/workshop#161]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by Bambina** [comment]
ruby2.4preview版を試してみよう。
普段はrbenvでインストールしちゃうけど、ツール使わないでやるにはどうするんだ？
githubのpreview repoをフォークして動かしてみるのかしら？

**Comment by Bambina** [comment]
まずは、READMEをざっと見て、previewで検索してみる。
(https://github.com/ruby/ruby#readme)

**Comment by Bambina** [comment]
preview検索してもなにもヒットしなかった。

**Comment by Bambina** [comment]
ぐぐろうか。。。
(how to try ruby preview version)
いや、公式みたほうがいいか。

**Comment by Bambina** [comment]
ちゃんとREADME読むことにした。
https://github.com/ruby/ruby#how-to-get-ruby

>For a complete list of ways to install Ruby, including using third-party tools like rvm, see:

>https://www.ruby-lang.org/en/downloads/

**Comment by Bambina** [comment]
↑公式サイトのインストール手順をみることに

**Comment by Bambina** [comment]
> The current stable version is 2.3.3. Please be sure to read Ruby’s License.

previewは？

**Comment by Bambina** [comment]
もう一度ちゃんとREADME読むことにした。
https://github.com/ruby/ruby#how-to-get-ruby
git cloneで本体をローカルに落としたら、preview版はブランチで試せるっぽい。

**Comment by Bambina** [comment]
メンターにreleaseタブを教えてもらった :bulb:
https://github.com/ruby/ruby/releases

guest wifiなので、ここからpreview版だけダウンロードしよう。
https://github.com/ruby/ruby/releases/tag/v2_4_0_preview3

**Comment by Bambina** [comment]
ruby how to install preview version　でぐぐった。
https://www.ruby-lang.org/ja/documentation/installation/
みた

**Comment by Bambina** [comment]
ソースからのビルド方法が分かった。
もちろん、Ruby をソースからインストールすることができます。 ダウンロードして tarball を展開し、次のようにしてください:

```
$ ./configure
$ make
$ sudo make install
```

**Comment by Bambina** [comment]
tarball展開して、コマンド実行したけどなかった。
```
HOME ruby-2_4_0_preview3 % ./configure
zsh: no such file or directory: ./configure
```

**Comment by Bambina** [comment]
* [Source code (tar.gz)](https://github.com/ruby/ruby/archive/v2_4_0_preview3.tar.gz)がちがう？
* 説明のコンテキストを理解してないのではないか。もう一度みてみよう。
https://www.ruby-lang.org/ja/documentation/installation/

**Comment by Bambina** [comment]
tar.gzは意図したものなのか、確認した。.cのファイルなので、rubyのソースコードっぽい。。。
READ.meをみてみることに。

```
HOME ruby-2_4_0_preview3 % cat README.md
```

> 2.  If `./configure` does not exist or is older than configure.in, run
    `autoconf` to (re)generate configure.

**Comment by Bambina** [comment]
メンターに「トップページを見てみたら」と言われたので見たら、リリースノートがあった 😱 
https://www.ruby-lang.org/ja/news/2016/11/09/ruby-2-4-0-preview3-released/
ここからダウンロードしたほうが、実行ファイルconfigureが入ってる。。。

**Comment by Bambina** [comment]
autoconfでconfigureを作った。
$ autoconf
$make 

コンパイラはclangだった。

**Comment by Bambina** [comment]
ruby言語の開発はgithubではなく、svnで行われている
rubyの言語自体のバグはredmineで報告する(issue作成にはアカウント作成が必要)
(日本語)
https://bugs.ruby-lang.org/projects/ruby/wiki/HowToReportJa
(英語)
https://bugs.ruby-lang.org/projects/ruby/wiki/HowToReport

ドキュメントの不具合はどこに報告する？

**Comment by Bambina** [comment]
ircにアクセスしてみた。
* IRCNetの#ruby-ja
* IRCNetの#ruby:*.jp
* freenodeの#ruby
* freenodeの#ruby-core

あまり活発ではない。

**Comment by Bambina** [comment]
lime chatとIRCについて教えてもらった。
http://www.ircnet.ne.jp/servers.html

**Comment by Bambina** [comment]
次はメーリングリストに登録してみよう。
https://www.ruby-lang.org/ja/community/mailing-lists/

**Comment by Bambina** [comment]
1. issue作る。
公式ページ(https://www.ruby-lang.org/)で、ページの修正提案をする場所が紹介されていない。

1. プルリクを送る。
ダウンロードページ(https://www.ruby-lang.org/en/downloads/)でpreview版のターボールをダウンロードするリンクが紹介されていなかったので。

**Comment by Bambina** [comment]
2が楽しそう。
https://github.com/ruby/www.ruby-lang.org/pull/1512

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-28に開催](https://oss-gate.doorkeeper.jp/events/52881)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！

**Comment by Bambina** [comment]
貴重な機会を頂き、誠にありがとうございました 🙇
