### ISSUE TITLE
OSS Gate Workshop: online: 2023-04-29: sotszk: xo: Work log

### ISSUE THREAD

**Issue by sotszk** [oss-gate/workshop#1612]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sotszk** [comment]
xo という eslint のラッパー的なライブラリが気になる
https://github.com/xojs/xo

**Comment by sotszk** [comment]
前に prettier の設定を併用したときにうまく動かなかったので治ってほしい

**Comment by sotszk** [comment]
ライセンスを確認してみる

**Comment by sotszk** [comment]
MIT ライセンスを確認
https://github.com/xojs/xo/blob/main/license

**Comment by sotszk** [comment]
オープンソースライセンスであることを確認
https://opensource.org/licenses/?ls=mit

**Comment by sotszk** [comment]
以前 prettier との integration でうまく動かなった記憶があるため、その時の現象を再現したい

**Comment by sotszk** [comment]
まずは公式ドキュメントを読みながら↑の再現を目指す

**Comment by otegami** [comment]
Issue のタイトルに今回対象にしたい xo を入れてあげると良さそうです👍

**Comment by sotszk** [comment]
ローカルに oss-workshop0429 というプロジェクトディレクトリを作成

`mkdir oss-workshop0429`

**Comment by sotszk** [comment]
以前問題を再現したプロジェクトが github のリポジトリにあったと思うが・・・

**Comment by sotszk** [comment]
今回はそのリポジトリを参考にしつつ手元で1からプロジェクトを作成し、xo をインストールし問題を再現させたい

**Comment by sotszk** [comment]
以下のリポジトリで問題が再現したことがあったような・・・ことを思い出した
https://github.com/sotszk/simple-todo/tree/use-xo

**Comment by sotszk** [comment]
上記リポジトリを参考に、手元で問題を再現するところまでやってみる

**Comment by sotszk** [comment]
npm のプロジェクトを作成

```
npm init -y
```

**Comment by sotszk** [comment]
公式ドキュメントに従い xo をインストールする

```
$ npm install xo --save-dev
```

https://github.com/xojs/xo#install

**Comment by sotszk** [comment]
検証用リポジトリを作ったのでこちらで進める
https://github.com/sotszk/xo-with-prettier

**Comment by sotszk** [comment]
問題を再現させる

**Comment by sotszk** [comment]
プロジェクトディレクトリで下記コマンドが動くことを確認
```
$ npx xo --help 
```

https://github.com/xojs/xo#usage

**Comment by sotszk** [comment]
試しに `src/index.js` を作成

**Comment by sotszk** [comment]
下記の `Examples` をみて手元で xo が動くか確認する

https://github.com/xojs/xo#usage

**Comment by sotszk** [comment]
下記のコードを xo にかけてみる

```js
const hello = "Hello, World!"

console.log('hello', hello);

```

**Comment by sotszk** [comment]
こけた
```
$ npx xo ./src/index.js

src/index.js:1:15
  ✖  1:15  Strings must use singlequote.  quotes
  ✖  1:30  Missing semicolon.             semi

  2 errors
```

**Comment by sotszk** [comment]
`xo --fix` で fix 可能なエラーは xo が直してくれるはずなので、うまく動くか確認する

**Comment by sotszk** [comment]
`xo --fix` によってコードが直されていることを確認

```
 ~/@/xo-with-prettier   main *+  git diff                                                3243ms  Sat Apr 29 12:10:06 2023
diff --git a/src/index.js b/src/index.js
index f9f7182..5162351 100644
--- a/src/index.js
+++ b/src/index.js
@@ -1,3 +1,3 @@
-const hello = "Hello, World!"
+const hello = 'Hello, World!';
 
 console.log('hello', hello);
```

**Comment by sotszk** [comment]
問題の prettier 設定をする

**Comment by sotszk** [comment]
下記の Workflow、微妙に「？」ってなっていたけど、改めて読み直したら一応納得。

https://github.com/xojs/xo#workflow

package.json の scripts に `"test": "xxxx"` が存在する場合に `npm init xo` コマンドをたたくと、`"test": "xo && xxxx"` のように `xo &&` が挿入されるってことだとおもわれ・・

**Comment by sotszk** [comment]
ドキュメントの Config セクションを読んで pretteir の設定を方法を調べる
https://github.com/xojs/xo#config

**Comment by sotszk** [comment]
prettier の設定を発見
https://github.com/xojs/xo#prettier

**Comment by sotszk** [comment]
以前問題が再現したときと同様に、package.json に xo プロパティを追加し prettier の設定をしてみる

**Comment by sotszk** [comment]
以前は、xo の config で `"prettier": true` にして、`.prettierrc` を追加し prettier の設定を書いたところ、`.prettierrc` の設定が反映されなかった（はず）

**Comment by sotszk** [comment]
↑を再現させたい。ので、

pacakge.json に以下を追加
```json
{
  "xo": {
    "prettier": true
  }
}
```

で、

`.prettierrc` ファイルを追加して設定を書いてみる。

**Comment by sotszk** [comment]
下記コマンドを叩き `.prettierrc` の設定が効いているか確認したところ、効いてるっぽいことを確認

```
 ~/@/xo-with-prettier   main +  npx xo ./src/index.js                                             Sat Apr 29 12:12:40 2023

  src/index.js:1:15
  ✖  1:15  Replace 'Hello,·World!' with "Hello,·World!"  prettier/prettier
  ✖  3:13  Replace 'hello' with "hello"                  prettier/prettier

  2 errors
```

**Comment by sotszk** [comment]
うーん、以前うまくいかなかったリポジトリを見直してみる

**Comment by sotszk** [comment]
↑のリポジトリで prettier パッケージがローカルにインストールされていることを確認。
今回のリポジトリでもインストールして試してみる。

**Comment by sotszk** [comment]
ローカルに prettier をインストールしても特に挙動に変わりなし

**Comment by sotszk** [comment]
ダメ押しで .prettierrc の bracketSpacing の設定を `true` -> `false` に変更してみたが、問題なく .prettierrc の設定が反映されていた。

**Comment by sotszk** [comment]
一応以前問題があった（と思われる）バージョンと、今回インストールした最新バージョンの差分を確認してみる。

以前使ったバージョン
```
"xo": "^0.53.1"
```

今回のバージョン
```
"xo": "^0.54.2"
```

**Comment by sotszk** [comment]
[リリース](https://github.com/xojs/xo/releases) を確認したところ、バージョン間で気になる変更点はなし・・・

**Comment by sotszk** [comment]
気を取り直して、xo のドキュメントの中で文法とかの一貫性についてあやしいところがあったので、こちらの修正をしプルリクエストを出す

**Comment by sotszk** [comment]
Issue を出したい

**Comment by sotszk** [comment]
xo の README の以下の箇所の修正をお願いしたい。

- TypeScript supported by default -> TypeScript supported by default.
  - https://github.com/xojs/xo#highlights
- If contradicting options are set for both Prettier and XO an error will be thrown. -> If contradicting options are set for both Prettier and XO, an error will be thrown.
  - https://github.com/xojs/xo#prettier

**Comment by sotszk** [comment]
issue に書く内容を検討↓

title: [minor] Improve documentation

README の中に気になる箇所を見つけました。以下の二点です。

1. 本来ピリオドが入っているべきなのにピリオドが入っていない文章がある
2. 文法のミス

**Comment by sotszk** [comment]
英語版

title: [minor] Improve documentation

There are two points we should fix in the documentation.

1. Usage of period is not consistent
2. Grammar errors

**Comment by sotszk** [comment]
issue タイトル
[minor] Improve documentation

issue 本文
翻訳ツールを使ったバージョン↓

There are two points we should fix in the documentation.  
These were trivial fixes, so I made a pull request.

1. Usage of period is not consistent
2. Grammar errors

**Comment by daipom** [comment]
https://github.com/xojs/xo/blob/main/contributing.md

> Open issues for things that could be improved.

ちょっと難しい英語に見えますが、たしかにissue作ってねと言っているように見えますね。

> [The best issue report is a failing test proving it.](https://twitter.com/sindresorhus/status/579306280495357953)

おお、今回は関係なさそうですが、これは面白い、、
失敗するテストコードを作ってPRしてね、と。。なるほど。。

**Comment by daipom** [comment]
今回のドキュメント修正のコントリビュートのルールに関しては、その他には特に気にする必要はなさそうですね

**Comment by daipom** [comment]
自明なtypoや文法ミスの修正であれば、そのように簡潔な説明でサクッとやってしまって良いと思いますよ！
