### ISSUE TITLE
OSS Gate Workshop: online: 2023-04-29: kurosuke: Guix: Work log

### ISSUE THREAD

**Issue by blacktoad30** [oss-gate/workshop#1613]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by blacktoad30** [comment]
# Target

[GNU Guix](https://git.savannah.gnu.org/cgit/guix.git)

# Issue

* Makefile.am

`make clean-go` でwarnが出る

**Comment by daipom** [comment]
コントリビュート方法はここにかいてありそう

* https://guix.gnu.org/manual/en/html_node/Contributing.html

**Comment by daipom** [comment]
patchをやり取りしている例

https://issues.guix.gnu.org/63159

**Comment by blacktoad30** [comment]
From abe7f124fcddbeca9bed51f564e48359d30cb4e5 Mon Sep 17 00:00:00 2001
From: Keisuke Kurosawa <k.kurochan9630@gmail.com>
Date: Thu, 27 Apr 2023 22:39:10 +0900
Subject: [PATCH 1/2] build: Undo "guix/scripts/import/cpan.scm" which was
 removed in commit 3aae8145a7.

* Makefile.am (MODULES): Add it.
---
 Makefile.am | 1 +
 1 file changed, 1 insertion(+)

diff --git a/Makefile.am b/Makefile.am
index a763a7e305..7fe18c9f6b 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -329,6 +329,7 @@ MODULES =					\
   guix/scripts/lint.scm				\
   guix/scripts/challenge.scm			\
   guix/scripts/import/crate.scm			\
+  guix/scripts/import/cpan.scm			\
   guix/scripts/import/cran.scm			\
   guix/scripts/import/egg.scm   		\
   guix/scripts/import/elm.scm			\
-- 
2.39.2

**Comment by daipom** [comment]
```
block
block
```

**Comment by blacktoad30** [comment]
> ```
> From abe7f124fcddbeca9bed51f564e48359d30cb4e5 Mon Sep 17 00:00:00 2001 From: Keisuke Kurosawa [k.kurochan9630@gmail.com](mailto:k.kurochan9630@gmail.com) Date: Thu, 27 Apr 2023 22:39:10 +0900 Subject: [PATCH 1/2] build: Undo "guix/scripts/import/cpan.scm" which was removed in commit 3aae8145a7.
> 
> * Makefile.am (MODULES): Add it.
> 
> Makefile.am | 1 + 1 file changed, 1 insertion(+)
> 
> diff --git a/Makefile.am b/Makefile.am index a763a7e305..7fe18c9f6b 100644 --- a/Makefile.am +++ b/Makefile.am @@ -329,6 +329,7 @@ MODULES = guix/scripts/lint.scm guix/scripts/challenge.scm guix/scripts/import/crate.scm \
> 
> * guix/scripts/import/cpan.scm			
>   guix/scripts/import/cran.scm			
>   guix/scripts/import/egg.scm   		
>   guix/scripts/import/elm.scm			
>   --
>   2.39.2

> ```

**Comment by blacktoad30** [comment]
```
From b6c1d3a45ebf0128179493e138d9bd34e6914b05 Mon Sep 17 00:00:00 2001
From: Keisuke Kurosawa <k.kurochan9630@gmail.com>
Date: Thu, 27 Apr 2023 23:21:40 +0900
Subject: [PATCH 2/2] build: clean-go: Do not warn about "guix/build/po.go".

* Makefile.am (MODULES_NOT_COMPILED,MODULES): Move "guix/build/po.go".
(MODULES_PO,make-po-go): Remove them.
---
 Makefile.am | 7 +------
 1 file changed, 1 insertion(+), 6 deletions(-)

diff --git a/Makefile.am b/Makefile.am
index 7fe18c9f6b..511757a9a4 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -69,7 +69,6 @@ nodist_noinst_SCRIPTS =				\
 # Modules that are not compiled but are installed nonetheless, such as
 # build-side modules with unusual dependencies.
 MODULES_NOT_COMPILED =				\
-  guix/build/po.scm				\
   guix/man-db.scm
 
 include gnu/local.mk
@@ -268,6 +267,7 @@ MODULES =					\
   guix/build/bournish.scm			\
   guix/build/qt-utils.scm			\
   guix/build/make-bootstrap.scm			\
+  guix/build/po.scm				\
   guix/search-paths.scm				\
   guix/packages.scm				\
   guix/import/cabal.scm				\
@@ -778,7 +778,6 @@ MODULES_PACKAGES2 := $(filter-out $(first_half),$(filter gnu/packages/%,$(MODULE
 MODULES_PACKAGES  := $(MODULES_PACKAGES1) $(MODULES_PACKAGES2)
 MODULES_SYSTEM    := gnu.scm $(filter-out gnu/packages/%,$(filter gnu/%,$(MODULES)))
 MODULES_CLI       := $(filter guix/scripts/%,$(MODULES))
-MODULES_PO        := guix/build/po.scm
 
 $(eval $(call guile-compilation-rule,make-core-go,	\
   $(MODULES_CORE) guix/config.scm $(dist_noinst_DATA),	\
@@ -808,10 +807,6 @@ $(eval $(call guile-compilation-rule,make-cli-go,			\
   $(words $(MODULES_CORE) $(MODULES_PACKAGES) $(MODULES_SYSTEM))))
 .PHONY: make-cli-go
 
-$(eval $(call guile-compilation-rule,guix/build/po.go,			\
-  $(MODULES_PO),							\
-  0))
-
 SUFFIXES = .go
 
 # Make sure source files are installed first, so that the mtime of
-- 
2.39.2

```

**Comment by blacktoad30** [comment]
# How to Contribute

ref: https://lists.gnu.org/archive/html/bug-guix/2023-04/msg00187.html

**Comment by blacktoad30** [comment]
# Patch with message?

```
From 3c03f4343ab0353d64eac063d8b60151c1b112ae Mon Sep 17 00:00:00 2001
From: Keisuke Kurosawa <k.kurochan9630@gmail.com>
Date: Fri, 14 Apr 2023 23:58:23 +0900
Subject: [PATCH] bootloader: grub: Add gfxpayload override.

* gnu/bootloader/grub.scm (<grub-theme>): Add `gfxpayload' entry.
(eye-candy): Use it.
* doc/guix.texi (Bootloader Configuration): Document it.
---
Hello,

This is test email.

Cheers,
Keisuke

 doc/guix.texi           |  4 ++++
 gnu/bootloader/grub.scm | 11 +++++++++--
 2 files changed, 13 insertions(+), 2 deletions(-)

diff --git a/doc/guix.texi b/doc/guix.texi
index adb1975935..65fb9b9637 100644
--- a/doc/guix.texi
+++ b/doc/guix.texi
```

**Comment by daipom** [comment]
```console
$ git checkout HEAD~
```

**Comment by blacktoad30** [comment]
パッチを送信済: "guix/scripts/import/cpan.scm"が消えている

**Comment by blacktoad30** [comment]
> ```
> $ git checkout HEAD~
> ```

https://github.com/oss-gate/workshop/issues/1613#issuecomment-1528658948

**Comment by daipom** [comment]
Thank you very much! I was struggling with the same problem too. How about this?

**Comment by blacktoad30** [comment]
* メッセージ無しでパッチだけ送るのは不親切
* このように修正しました

**Comment by blacktoad30** [comment]
### [SOMEDAY] grub.cfgにgfxpayloadを追加したい
