### ISSUE TITLE
オンラインワークショップで使用するコミュニケーションツールについて

### ISSUE THREAD

**Issue by blacktoad30** [oss-gate/workshop#1619]
# 要望

## 内容

* チャットとビデオ会議をGitterに統一してほしい。

## 根拠

* GitterがElementに統合されて、ビデオ会議機能も利用できるようになったため。

# 概要

## 現状

OSS Gateのオンラインワークショップでは、2つのコミュニケーションツールを使用している。

* Discord
ワークショップでほぼ利用している。
* Gitter (Element)
ワークショップ後の報告やその後のOSS開発に関する相談などで利用する。

## 疑問

* チャット環境は2つも必要なのか?
初めてワークショップに参加したとき、どちらで会話すれば良いのか混乱した。

### 私見

(個人的な意見です。ソフトウェアの思想に関わります)

* Discordはプロプライエタリ・ソフトウェアである
  * OSSに貢献する一歩を踏み出すのが目的のワークショップにはふさわしくないと思う
    * オープンソースで開発されているコミュニケーションツールを知ったり、貢献する機会が生まれにくいのではないか?
  * インストールが難しいディストリビューションを利用していたり、プロプライエタリ・ソフトウェアに思うところがある人たちに厳しい
    * ワークショップへの参加を躊躇させてしまうのではないか?

**Comment by kou** [comment]
おぉ。Gittterでも使えるようになっていたんですか！

たしかに1つのツールで完結したほうがやりやすいかもしれませんね。

私はオンライン版には参加したことがないので実際に参加している人たちの意見を重視して欲しいと思いますが、何度か試してみてもいいんじゃないかなぁと思いました。

**Comment by daipom** [comment]
@blacktoad30  提案ありがとうございます！

Gitterでできるならその方が良いかもしれませんね！
ぜひ試してみましょう！次回か次次回！

補足として、前回のワークショップで @blacktoad30 さんが使われているOSにdiscordが入らなくて不便だったんですよね。
そういう意味でも、ぜひ新しい方法を試してみたいですね。

Gitterなら @blacktoad30 の使われているOS上でもミーティングできそうって感じでしょうか？
ブラウザーで動きそうだから？

**Comment by blacktoad30** [comment]
@daipom 

> Gitterでできるならその方が良いかもしれませんね！
> ぜひ試してみましょう！次回か次次回！

よろしくお願いいたします。

> Gitterなら @blacktoad30 の使われているOS上でもミーティングできそうって感じでしょうか？ ブラウザーで動きそうだから？

ブラウザに加えて、インストールして利用できるクライアントもあるので、いけそうです。

あとは、同時接続ができる人数の上限や遅延の確認などを事前に出来ればと思っています。

**Comment by daipom** [comment]
> ブラウザに加えて、インストールして利用できるクライアントもあるので、いけそうです。

おお、いいですね！

> あとは、同時接続ができる人数の上限や遅延の確認などを事前に出来ればと思っています。

ぼくも進行役としてイメージするために動作や仕様を確認してみるつもりですが、何か分かったら教えてください！
状況に応じては部屋に人を振り分けたりすることになるので、ブレークルームみたいな使い方が便利にできるのかどうかが気になるところです。

**Comment by blacktoad30** [comment]
@daipom 
とりあえず、自分の端末とアカウントで試してみました。

Discordとおおよそ似ていますが、気になる点がありました。

* 通常のルームで、ビデオ会議にはJitsiを使用している
  * ブレイクアウトルームの作成機能はある
    * メンバーを移動させることはできない?
    * 各々で移動しなければならない
* Elementにビデオ通話ルーム (ベータ版)がある
  * 設定->ラボより有効化
  * このルームのビデオ会議にはJitsiを使用しない
    * matrixに埋め込まれている、新しいルーム機能
  * 現時点で、ブレイクアウトルーム機能はない
    * 事前にこのルームをいくつか作成しておき、分かれて作業する際はそれぞれのルームに招待する、など

**Comment by daipom** [comment]
ありがとうございます！！

jitsiは普段よく使っているのでイメージできます！あれのブレークアウトルームなら一応問題なく進行できそうな気がします。

**Comment by daipom** [comment]
ルームを作ってみた: https://app.gitter.im/#/room/#oss-gate_online-workshop:gitter.im

動作を確かめてみた感触

* 「ビデオ通話」を押すと、Jitsiがウィジェットとして立ち上がり、ルームの人が自由に参加できるようになる
* ウィジェットを削除すると終了する
* ウィジェットとして立ち上がるので、画面は小さい。テキストチャットと高頻度に併用するなら便利かもだが、画面を大きく見たいときは不便かも
  * ポップアップすることで別タブでJitsiを開くことができる。こちらはelement要素が一切消えて純粋なJitsiになる。

想定通り、部屋分けの部分をクリアできれば十分使えそう。

アイデア

* Jitsiのブレークアウトルーム機能をつかう
  * メリット: 強制的に移動したりできるので管理しやすいかも
  * 課題: テキストチャットの区分け
* ウィジェットを使わずに、最初からJitsiのミーティングリンクを複数発行してシェアしておく
  * メリット: 分かりやすいかも
  * 課題: テキストチャットの区分け、、
* elementのルームを複数作っておく
  * メリット: テキストチャットも含めて分けられる
  * 課題: discordのチャンネル的な取り回しができるだろうか、、

**Comment by daipom** [comment]
とりあえず6/10のワークショップでは、elementのルームを複数作る方法でやってみたい。
(現在ビギナーさんは1人の予定なので、もし増えたら)

とりあえず必要になったらルームを増やして、消さずに残しておけばよさそう。

**Comment by daipom** [comment]
案内するにあたり、Gitter, Element, Matrix, あたりの概念がとっちらかっています。。

ツールの名前としては Matrix と呼ぶのが良いのでしょうか、、、

「Matrix を使うよ！そのクライアントとして Gitter とか Element とか色々使えるので自由に選んでね！」
といった理解であっているでしょうか？

少なくとも「今回から Gitter を使います」という案内は間違っている気がして、どう表現したものかと悩んでいます。

クライアントとしても、今後は Gitter ではなくて Element を使うのが良さそうですかね。
段々と Gitter は Element の一機能に置き換えられていく予定、みたいな情報がありました。

* https://blog.desdelinux.net/gitter-se-traslada-a-matrix-y-se-fusiona-con-element-matrix/

また、案内するリンクによっても選択するクライアントが変わってきそうです。

ルームのリンクを取得すると、次のリンクを取得できます。

* https://matrix.to/#/#oss-gate_online-workshop:gitter.im

これを押すとクライアントを選択する画面が出てくるのですが、
一番上に Element があり、 Gitter は選択肢にないように見えます。

Gitter でアクセスしている次の直リンクを案内すれば、 Gitter で参加できるのかもしれません。

* https://app.gitter.im/#/room/#oss-gate_online-workshop:gitter.im

今のイベントページの案内では、チャットのリンクとして次の古いリンクを案内しています。
こちらも Gitter が自動で選択されるのかもしれません。

* https://gitter.im/oss-gate/tokyo

**Comment by daipom** [comment]
正式にルームのリンクとして取得できる

* https://matrix.to/#/#oss-gate_online-workshop:gitter.im

のリンクを案内して、
特に理由がなければ Element を選択してください、
という案内になるのかなあと思ったりしています。

**Comment by daipom** [comment]
> ツールの名前としては Matrix と呼ぶのが良いのでしょうか、、、
> 
> 「Matrix を使うよ！そのクライアントとして Gitter とか Element とか色々使えるので自由に選んでね！」 といった理解であっているでしょうか？

んー、 Matrix はプロトコルのことを指すんですよね。
ツールとして「Matrix を使うよ！」というのもおかしいかも。

https://matrix.org/faq/#what-is-matrix%3F

> What is Matrix?
> Matrix is an open standard for interoperable, decentralised, real-time communication over IP. 
> ...
> Matrix defines the standard, and provides open source reference implementations of Matrix-compatible Servers, ...

Matrix はオープン・スタンダードの1つである。
Matrix は規格を定義し、Matrix 互換のサーバーなどのオープンソースリファレンス実装を提供する。

**Comment by daipom** [comment]
「Element や Gitter などのMatrixベースのツールを使います」

という表現が良さそう

**Comment by daipom** [comment]
案内する参加方法は次のようにするのが良さそう。

基本的には次のリンクで Element を選択してもらう。

* https://matrix.to/#/#oss-gate_online-workshop:gitter.im

既に Gitter アカウントを持っている人は、次のリンクで既存アカウントから参加できる。

* https://app.gitter.im/#/room/#oss-gate_online-workshop:gitter.im

**Comment by daipom** [comment]
メモ: ビデオ通話を始めるには権限の調整が必要

次の2つの行動に必要な権限を`既定値`に変更したらビデオ通話を開始できるようになった

* `音声配信` (もしかしたら無くてもいいかもしれない)
* `ウィジェットの変更` (確定で必要)

ワークショップで使うルームはこの2つの権限を変更しておくと良さそう

**Comment by kou** [comment]
>  https://blog.desdelinux.net/gitter-se-traslada-a-matrix-y-se-fusiona-con-element-matrix/

https://element.io/blog/gitter-is-joining-element/ が一次情報です。

今後はElementだけ案内でいいっす。
Gitterを使っている人にもElementにしようぜーとしていきましょう。

Webサイトとかもろもろも書き換えていきましょうか。

**Comment by kou** [comment]
https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/ がその後の情報かな。

**Comment by daipom** [comment]
おお、ありがとうございます！

> 今後はElementだけ案内でいいっす。 Gitterを使っている人にもElementにしようぜーとしていきましょう。
> 
> Webサイトとかもろもろも書き換えていきましょうか。

そうですね！
既にGitterアカウントを持っている人たちをどうしようかと迷っていましたが、ここまでの情報からElementだけ案内していく形で整理していくのが良さそうです！
そうします！

**Comment by daipom** [comment]
`オンラインイベントへのリンク`を更新したいが、なぜか「不正なURL」だと言われて設定できない。

![Screenshot from 2023-06-06 14-32-31](https://github.com/oss-gate/workshop/assets/12229857/e80ee096-c9e3-4dbc-a573-625e4025a7fe)

Doorkeeperに問い合わせ中。
とりあえず従来の形式のリンクのままにする(なぜかずっと`tokyo`になっていたが`general`に変えておく)

**Comment by blacktoad30** [comment]
ご無沙汰しております。準備の方を進めていただき、ありがとうございます。(言い出しっぺなのに手伝い等出来ず、申し訳ないです…)

> `オンラインイベントへのリンク`を更新したいが、なぜか「不正なURL」だと言われて設定できない。

Doorkeeperの対応次第ではありますが、難しいという場合は、 https://gitter.im/oss-gate/general としても良いと思います。(generalルームに飛べました)

**Comment by daipom** [comment]
@blacktoad30 いえいえ！色々と事前に調べていただいていたおかげでスムーズに準備できました！
リアクションなども下さっていてありがたかったです！

> Doorkeeperの対応次第ではありますが、難しいという場合は、 https://gitter.im/oss-gate/general としても良いと思います。(generalルームに飛べました)

はい！とりあえずそうしてあります！
@blacktoad30 さんはそのリンクから入った時にElementアカウントで入れました？それともGitterアカウントになりましたか？

**Comment by blacktoad30** [comment]
@daipom 
Gitterのアカウントでした。
GithubとGitterを連携しており、かつGithubにログインしている状態のブラウザで、ルームのリンクを開いたからだと思います。

ログアウトしている状態でも試してみました。
まず、チャット欄の下枠に
"アカウントで会話に参加    サインイン"
と出ます。
"サインイン"を選択すると、ホームサーバーがgitter.imで固定されたログイン画面となります。

**Comment by daipom** [comment]
ありがとうございます。
多分 https://gitter.im/oss-gate/general から入るとGitterアカウントで入ることになり、 https://matrix.to/#/#oss-gate_general:gitter.im から入るとElementアカウントで入ることになるのだと思っています。

Elementを案内するスタイルに整理していきたいので、できれば後者スタイルの方のリンクを設定したいなと思っています。

**Comment by blacktoad30** [comment]
@daipom 良かったです! URLの仕様で

---

P.S.

> 多分 https://gitter.im/oss-gate/general から入るとGitterアカウントで入ることになり、 https://matrix.to/#/#oss-gate_general:gitter.im から入るとElementアカウントで入ることになるのだと思っています。

自分の認識が誤っていれば申し訳ないのですが、Elementはソフトウェアの名前なので、Elementアカウントは誤りであり、Gitterアカウント(=gitter.imのMatrixアカウント)は正しいように思いました。

**Comment by daipom** [comment]
むずかしい、、

> Elementアカウントは誤りであり

正解は何なのでしょうか？

**Comment by knokmki612** [comment]
Gitterアカウント→GitterのMatrixアカウント
Elementアカウント→ElementのMatrixアカウントではないでしょうか

**Comment by daipom** [comment]
@knokmki612 ありがとうございます！まだ分かっていない部分がありますが、とりあえずそんな感じがします！

サインアップするときに、HomeServerとして`marix.org`が選択されていたようです。

僕はGitterとElementで別々のアカウントでサインインする状態になってしまっているのですが、これはHomeServerが異なるMatrixアカウントが2つある、ということなのかな、、
HomeServerを指定すればGitterで使っていたアカウントをElementにも流用できたのかな、、
(あとで試してみようかな)

**Comment by daipom** [comment]
> 僕はGitterとElementで別々のアカウントでサインインする状態になってしまっているのですが、これはHomeServerが異なるMatrixアカウントが2つある、ということなのかな、、
> HomeServerを指定すればGitterで使っていたアカウントをElementにも流用できたのかな、、

この通りでした！
前からあったGitterのアカウントは、`gitter.im`ホームサーバーのMatrixアカウントという立ち位置になっているようです！
このホームサーバーを指定すれば、`https://app.element.io/...`に元々のアカウントのままアクセスできました！

つまり、Gitter用のアカウントとか、Element用のアカウントなんてものはないんですね！
同じMatrixアカウントでどちらも使える！
異なるアカウントが必要だったと思ってしまっていたのは、指定していたホームサーバーが異なっていたからでした！

**Comment by daipom** [comment]
つまり最初に @blacktoad30 さんにご指摘いただいた通りですね！！
Gitterアカウントという言葉は、一応`gitter.im`ホームサーバーのアカウントという意味に取れるが、Elementアカウントという言葉は解釈不能なわけですね。
ありがとうございます！

**Comment by knokmki612** [comment]
> サインアップするときに、HomeServerとして`marix.org`が選択されていたようです。
> 
> 僕はGitterとElementで別々のアカウントでサインインする状態になってしまっているのですが、これはHomeServerが異なるMatrixアカウントが2つある、ということなのかな、、
> HomeServerを指定すればGitterで使っていたアカウントをElementにも流用できたのかな、、
> (あとで試してみようかな)

私も同じ状態（gitter.imとmatrix.orgアカウントが存在）で、ためしにgitter.imのアカウントでElementを使ってみたらいけました

https://matrix.to/#/!gHIZhKRtDtemauVGiE:gitter.im/$XO6vhUet9KYqZbpilzJjjmYIFIpOUpugEPdTxV7_Yhg?via=gitter.im&via=matrix.org

**Comment by yoshimotoyuk** [comment]
関係ないかもしれないですが、Discordにもご案内をご一報入れておくのがよさそうにおもいました。
（サポーターの方たちは、癖でDiscordにいらっしゃる気もするので。Gitter/generalもみられていそうですが。

**Comment by daipom** [comment]
なるほど！！
「今回からDiscord使わなくなりそうです！」という一報ですよね！
おっしゃるとおりですね！入れておきます！

**Comment by daipom** [comment]
一報入れておきました！ありがとうございます！

**Comment by daipom** [comment]
Elementで大きな問題なくワークショップを開催できました。

* #1592

今後基本的にElementを使ってオンラインワークショップを開催していきたいと思います。
