### ISSUE TITLE
OSS Gate Workshop: online: 2023-06-10: daiki0381: ruby/gem_rbs_collection: Work log

### ISSUE THREAD

**Issue by daiki0381** [oss-gate/workshop#1621]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daiki0381** [comment]
興味のあるOSS

- [ruby/gem_rbs_collection](https://www.google.com/url?q=https://github.com/ruby/gem_rbs_collection&sa=D&source=calendar&usd=2&usg=AOvVaw21jLXARlI2Ko5rd4EgRtpd)
- [railsgirls-jp/railsgirls.jp](https://github.com/railsgirls-jp/railsgirls.jp)

**Comment by daiki0381** [comment]
https://github.com/ruby/gem_rbs_collection/blob/main/.gitmodules => ここに既に型定義されたGemの一覧がある

**Comment by daiki0381** [comment]
RBSの導入は https://zenn.dev/leaner_dev/articles/20210915-rubykaigi-2021-rbs-collection が参考になりそう

**Comment by daiki0381** [comment]
https://www.youtube.com/watch?v=QK2XsIHAc9U&t=219s&ab_channel=RubyKaigi これも参考になりそう

**Comment by daiki0381** [comment]
RBSを導入してgem_rbs_collectionに貢献する手順は下記になりそう

https://github.com/ruby/gem_rbs_collection/blob/main/docs/CONTRIBUTING.md
https://product.st.inc/entry/2022/12/01/112446

1 . どのgemにrbsを入れるか決める 
2. 型を導入して、テストして ~> PRを送る

**Comment by daiki0381** [comment]
RBSを導入したいGem
既にあるgemに対してsteep checkをやるのはアリだな

gem_rbs_collectionはGemの型定義が集まっているリポジトリ

rails-girlsのcontribute


RBSの書き方
https://github.com/ruby/rbs/blob/master/docs/syntax.md
https://pocke.hatenablog.com/entry/2021/01/02/175940


コントリビュート方法
①既に型定義されているGemに型追加や修正する方法

見つける => 修正したり、追加したりする
確認する => プロダクトコードとかたの不一致などがあるか steep check
修正する 
PRする

steep check => RBSファイルを静的に解析して、型定義と実装の不一致を確認する
errorが起きたら修正する

新しくGemの型定義を追加する

型定義についてgeneretorを使って自動的に生成する

手動で型定義を書く

開発環境の０SEtup

gem_rbs_collectionをforkする
bin/setup
bin/init_new_gem gem

下記を書く
test.rb => テスト -> 呼び出しを書く
gem.rbs => RBSを書く

全てのAPIに書く必要はなくて、一部に書けばOK => よく使われているものを書く

型定義についてgeneretorを使って自動的に生成する

rbs prototype rb => RBSを自動的に生成する

https://github.com/ruby/gem_rbs_collection/pull/193

**Comment by daiki0381** [comment]
RBSを導入したいGem
既にあるgemに対してsteep checkをやる
gem_rbs_collectionはGemの型定義が集まっているリポジトリ

RBSの書き方
https://github.com/ruby/rbs/blob/master/docs/syntax.md
https://pocke.hatenablog.com/entry/2021/01/02/175940

コントリビュート方法
①既に型定義されているGemに型追加や修正する方法

見つける => 修正したり、追加したりする
確認する => プロダクトコードとかたの不一致などがあるか steep check
修正する 
PRする

steep check => RBSファイルを静的に解析して、型定義と実装の不一致を確認する
errorが起きたら修正する

新しくGemの型定義を追加する

型定義についてgeneretorを使って自動的に生成する

手動で型定義を書く

開発環境の０SEtup



下記を書く
test.rb => テスト -> 呼び出しを書く
gem.rbs => RBSを書く

全てのAPIに書く必要はなくて、一部に書けばOK => よく使われているものを書く

型定義についてgeneretorを使って自動的に生成する

rbs prototype rb => RBSを自動的に生成する

**Comment by daiki0381** [comment]
【RBSの文法】
- https://github.com/ruby/rbs/blob/master/docs/syntax.md
- https://pocke.hatenablog.com/entry/2021/01/02/175940

**Comment by daiki0381** [comment]
- 既に型定義されているGemに対してsteep checkしてエラーが起きていないかチェック => エラーが起きていたら修正 => PR
- 型定義したいGemを見つけて型定義 => PR
- RBSの略についてdocumentに記載するPRを書くのはどうだろう？ => What does RBS stand for? => Ruby Signature

**Comment by daiki0381** [comment]
RBS：Ruby の型情報を扱う言語。Ruby 3 にバンドルされる。
TypeProf：型注釈のない Ruby コードを型解析するツール。Ruby 3 にバンドルされる。
Steep/Sorbet：Ruby で静的型付けのプログラミングができるツール。

**Comment by daiki0381** [comment]
あなたがgemの所有者である場合： RBSのファイルディレクトリをgemに追加するのがよいでしょう。RBSファイルを書いて、sigディレクトリに置き、そのディレクトリをgemのパッケージに含める。

あなたがgemの所有者である場合については書いてあるが、その下にgemの所有者でない場合のAdding RBS of a gemがいきなり、始まってわかりにくい

**Comment by daiki0381** [comment]
あなたがgemの所有者である場合については書いてあるが、その下にgemの所有者でない場合のAdding RBS of a gemがいきなり、始まってわかりにくい

**Comment by daiki0381** [comment]
既にあるgemに対して修正するcontribution.mdも追加すると良さそう

**Comment by daiki0381** [comment]
gemの所有者についての説明から始まるので、初めてgem_rbs_colleciotnにcontributeする人がgemの所有者用の説明が下記に書いてあるように感じて困惑してしまう恐れがあるので、一文追加しました。

**Comment by daipom** [comment]
今は、gemの所有者についての説明から始まっています。
そのため、それ以降の手順が、gem所有者向けの手順なのか、gemの所有者でない人向けの手順なのかが分かりにくいです。

私は、それ以降の手順はgemの所有者ではない人向けの手順だと思います。

このような文を追加すると、より分かりやすくなると思いました。

**Comment by daiki0381** [comment]
今はgem_rbs_collectionに型を追加する方法

今はgem_rbs_collectionに対して型を追加する方法しかないです。
そのため、既にgem_rbs_collectionに型定義されているGemの場合はどうすればいいか分からない可能性があります。

このような文を追加すると、より分かりやすくなると思いました。

**Comment by daiki0381** [comment]
https://github.com/ruby/gem_rbs_collection/pull/337
https://github.com/ruby/gem_rbs_collection/pull/339

**Comment by daipom** [comment]
https://github.com/ruby/gem_rbs_collection/pull/339

> since there was no description of how to contribute to a Gem.

がちょっとミスリーディングな気がするので、
前半の

> Added a description of how to contribute to a Gem that is already type-defined in gem_rbs_collection.

部分だけでも十分伝わる気がしました。
