### ISSUE TITLE
OSS Gate Workshop: online: 2023-06-10: djkazunoko: pgadmin4: Work log

### ISSUE THREAD

**Issue by djkazunoko** [oss-gate/workshop#1622]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by djkazunoko** [comment]
OSS選びをする

**Comment by djkazunoko** [comment]
候補

- https://github.com/pgadmin-org/pgadmin4
- https://github.com/fgrehm/letter_opener_web
- https://github.com/Shopify/ruby-lsp
- https://github.com/ruby/debug
- https://github.com/ruby/vscode-rdbg
- https://github.com/sds/slim-lint

**Comment by blacktoad30** [comment]
# License
pgadmin4: PostgreSQL License

**Comment by daipom** [comment]
ウェブサイトのリポジトリーはこれかも？

https://github.com/pgadmin-org/pgaweb

**Comment by djkazunoko** [comment]
https://github.com/fgrehm/letter_opener_web を見てみる

**Comment by daipom** [comment]
PGadmin4 のスペルの英/米式の違いについて

* https://opensource.org/license/postgresql/

このページ内で既に2種類使われている、、、

**Comment by djkazunoko** [comment]
過去に自分が`letter_opener_web`を使った時の↓
https://github.com/djkazunoko/fjord-books_app/pull/3

**Comment by djkazunoko** [comment]
一旦、https://github.com/pgadmin-org/pgadmin4 を見ることにする

**Comment by djkazunoko** [comment]
こっちは`LICENSE`(最後がS)
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE

こっちは`LICENCE`(最後がC)
https://www.pgadmin.org/licence/

**Comment by blacktoad30** [comment]
https://github.com/pgadmin-org/pgaweb/blob/main/pgaweb/templates/pgaweb/licence.html

**Comment by djkazunoko** [comment]
githubのLICENSEファイルは`s`を使う慣習なのだろう。
PostgreSQL Licenceは`c`。
これを統一してくださいって提案は無理そう。
けど、https://www.pgadmin.org/licence/ を https://www.pgadmin.org/license/ でもリダイレクトするようにした方がいいのでは？はいけそうかも。

**Comment by djkazunoko** [comment]
もう一つは、
https://www.pgadmin.org/licence/ の`Last update: 2021-03-15`を更新する

**Comment by blacktoad30** [comment]
それぞれのPull Requestを作成できそうな気がします。

# 対象

pgadmin4 の Webページ

リポジトリ: https://github.com/pgadmin-org/pgaweb/blob/main/pgaweb/templates/pgaweb/licence.html

# 目標

- Copyright の年数を更新する (2021 -> 2023)
- license.htmlをlicence.htmlにリダイレクトする
  - metaタグを使用する
  - .htaccessの作成
  - javascript

**Comment by djkazunoko** [comment]
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE
こうして欲しい
```diff
- pgAdmin 4
+ PostgreSQL licence
```

**Comment by djkazunoko** [comment]
タイトル：LICENSEファイルにpgAdmin 4がPostgreSQL licenceだと明記してほしい

以下のファイルの1行目について
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE

以下のように修正してはどうでしょうか？
```diff
- pgAdmin 4
+ pgAdmin 4 is released under the PostgreSQL licence
```
`pgAdmin 4`だけだと、`pgAdmin 4`が`PostgreSQL licence`であることがわからないため。
ちなみに、修正案の文章は https://www.pgadmin.org/licence/ から取っています。

**Comment by blacktoad30** [comment]
```diff
Copyright (C) 2013 - 2023, The pgAdmin Development Team
+ This software is released under the PostgreSQL licence.
```

**Comment by djkazunoko** [comment]
### 修正案
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE
```diff
pgAdmin 4

Copyright (C) 2013 - 2023, The pgAdmin Development Team
+ This software is released under the PostgreSQL licence.
```

- このファイルからpgAdmin4がPostgreSQL licenceであることがわからないため
- 追加の文章はその他のファイルの先頭に記載されているテンプレートを使用

**Comment by blacktoad30** [comment]
pgAdmin 4がPostgreSQL Licenceであることが、LICENSEファイルを読んでも分かりにくい。
そこで、DockerfileやMakefileを参考にして文章を追加した。

**Comment by djkazunoko** [comment]
以下のLICENSEファイルを読んでも、pgAdmin4がPostgreSQL Licenceであることが分かりづらい。
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE

以下のようにライセンス情報を修正することを提案します。
```diff
pgAdmin 4

Copyright (C) 2013 - 2023, The pgAdmin Development Team
+ This software is released under the PostgreSQL licence.

// 省略
```

追加の文章はDockerfileやMakefileを参考にしました。

**Comment by djkazunoko** [comment]
It is hard to tell that pgAdmin4 is a PostgreSQL Licence by reading the following LICENSE file.
https://github.com/pgadmin-org/pgadmin4/blob/master/LICENSE

I suggest that you modify the license information as follows.
```diff
pgAdmin 4

Copyright (C) 2013 - 2023, The pgAdmin Development Team
+ This software is released under the PostgreSQL licence.
```

Additional text was taken from the Dockerfile and Makefile.

**Comment by blacktoad30** [comment]
Title:

- Clearly state that pgadmin4 is released under the PostgreSQL Licence.

**Comment by djkazunoko** [comment]
Clarify License Information: pgAdmin 4 is released under the PostgreSQL License

**Comment by djkazunoko** [comment]
https://github.com/pgadmin-org/pgadmin4/issues/6423

**Comment by djkazunoko** [comment]
作成したissue
https://github.com/pgadmin-org/pgadmin4/issues/6423
