### ISSUE TITLE
OSS Gate Workshop: online: 2023-07-29: ymneet: steep: Work log

### ISSUE THREAD

**Issue by yoshinori-ma** [oss-gate/workshop#1630]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yoshinori-ma** [comment]
Rubocop見ようとしてたが小規模じゃないので考える
→もうちょい小規模なものを考えて見つからなければRubocopやる

**Comment by yoshinori-ma** [comment]
rbs系に興味があるが、rbsの理解から始まるのがつらい
と思うが、一旦rbs周辺領域でやっていく
rbsで静的解析するまでには別のgemも利用する必要がある(はず)なので、その一連の過程でコントリビュートチャンスを探す

**Comment by yoshinori-ma** [comment]
rbsを実戦投入しようとしたときにrbs以外に何を使えばいいかがわからない、というのは問題に感じている

https://github.com/ruby/rbs
とりあえずrbsのリポジトリを読む

**Comment by yoshinori-ma** [comment]
rbsの導入手順(インストール)は問題なく終了
rbsを使って型検査をするライブラリの steep の導入に移る
https://github.com/soutaro/steep

**Comment by yoshinori-ma** [comment]
https://github.com/soutaro/steep#installation
`gem 'steep'` 記載して bundle install 後 に `steep init` でエラー 。自分の環境のせいな気がするが一旦メモ

```
➜  ossgate-rbs steep init
<internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- parallel/processor_count (LoadError)
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/steep-0.46.0/lib/steep.rb:19:in `<top (required)>'
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/steep-0.46.0/exe/steep:7:in `<top (required)>'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/bin/steep:25:in `load'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/bin/steep:25:in `<main>'
<internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- parallel/processor_count (LoadError)
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/steep-0.46.0/lib/steep.rb:19:in `<top (required)>'
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/steep-0.46.0/exe/steep:7:in `<top (required)>'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/bin/steep:25:in `load'
        from /Users/yoshinorimaeda/.anyenv/envs/rbenv/versions/3.0.6/bin/steep:25:in `<main>'

```

**Comment by yoshinori-ma** [comment]
https://github.com/soutaro/steep/issues/769 
closeされてるが同じエラー

**Comment by yoshinori-ma** [comment]
手元ではsteepの1.23.0が入っており、その中で `require "parallel/processor_count"` されてる

**Comment by yoshinori-ma** [comment]
最新 https://github.com/soutaro/steep/blob/master/lib/steep.rb
0.46.0 https://github.com/soutaro/steep/blob/v0.46.0/lib/steep.rb

**Comment by yoshinori-ma** [comment]
```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rbs'
gem 'steep'
```

**Comment by yoshinori-ma** [comment]
自分のリポジトリに進捗を上げました
https://github.com/yoshinori-ma/ossgate-rbs

**Comment by yoshinori-ma** [comment]
1.4.0 で parallel への依存が消えてる
https://github.com/soutaro/steep/releases/tag/v1.4.0

**Comment by yoshinori-ma** [comment]
Gemfile.lock 消して再実行したら1.5.2が入りました

**Comment by yoshinori-ma** [comment]
0.46.0が入ってしまった原因がわかったらコントリビュートできそう

**Comment by yoshinori-ma** [comment]
version指定したら、というissueは作れるかも

**Comment by yoshinori-ma** [comment]
rbs: `set` has been moved to core library, so it is always loaded. Remove explicit loading `set`

**Comment by yoshinori-ma** [comment]
- Steepfileから期待しているディレクトリの構造を読み取る必要があって、Getting Start には情報が足りてないように感じる
- ファイルを分けるべきか不明
- 3. Type checkの部分で phone.rb:46と書いており、ファイルの構造が不自然
- Type Checkで発生すべきエラーが発生しない

**Comment by yoshinori-ma** [comment]
READMEどおりに進めてもメソッド未定義のエラーが出ない点について書く

**Comment by yoshinori-ma** [comment]
_似ているissue https://github.com/soutaro/steep/issues/346_

**Comment by yoshinori-ma** [comment]
READMEの手順通りに進めてもMethodDefinitionMissingが発生しない

Usageの手順どおりにすすめました
ファイル、ディレクトリの構造は以下のようになっています
root
- lib
  - phone.rb
- sig
  - phone.rbs

steep checkの結果は以下のとおりです
```
steep check
# Type checking files:

.....................................................................................
```

phone.rbのPhone クラスに追記を行い、別のProblemが発生することは以下の通り確認しました
```
class Phone
  ...
  def self.countries
    'hoge'
  end
end
```
```
steep check
# Type checking files:

...................................................................................F.

lib/phone.rb:69:11: [error] Cannot allow method body have type `::String` because declared as type `::Hash[::String, ::String]`
│   ::String <: ::Hash[::String, ::String]
│     ::Object <: ::Hash[::String, ::String]
│       ::BasicObject <: ::Hash[::String, ::String]
│
│ Diagnostic ID: Ruby::MethodBodyTypeMismatch
│
└   def self.countries
             ~~~~~~~~~
```

READMEからはMethodDefinitionMissingが発生するように読み取れましたが、なにか手順に間違いがありますか？

**Comment by otegami** [comment]
memo
- Environment
    - Ruby version
    - steep version

**Comment by otegami** [comment]
Actual: No Error raised

Expected: Error raised

**Comment by yoshinori-ma** [comment]
# MethodDefinitionMissing does not raise even if I follow usage in README

I followed Usage section in README.
The file and directory structure is as follows.

ref: https://github.com/yoshinori-ma/ossgate-rbs/tree/main

The results of steep check are as follows.

Actual: No Error raised

Expected: Error raised

**Comment by otegami** [comment]
みたいな構造で区切ってあげると少しだけわかりやすくなるかもです🙏

title: MethodDefinitionMissing does not raise even if I follow usage in README

## My Environment
- Ruby version: 
- steep version: 

## How I reproduce
README.md 通りにやったけどうまくいかなかったこと

## What I did was add additional patterns to check the above situation
phone.rbのPhone クラスに追記を行い、別のエラーが発生することは以下の通り確認した例
