### ISSUE TITLE
OSS Gate Workshop: オンライン: 2023-07-29: Piyo: Dark Reader: Work log

### ISSUE THREAD

**Issue by Piyopanman** [oss-gate/workshop#1632]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Piyopanman** [comment]
Nest.jsの日本語訳と、ja.javascript.infoのタイポ修正みたいな小さいコントリビュートはしたことあるから、今日は実際のコードを治すようなことをできたら嬉しいな
https://github.com/javascript-tutorial/ja.javascript.info/pull/323
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs#contributors-

**Comment by Piyopanman** [comment]
ドキュメントにしっかり沿って動かして動かなかったらコントリビュートチャンス、確かに🦀

**Comment by Piyopanman** [comment]
Java最近書いているのでJavaで書かれたものがいいなと思うけど、Javaだと大規模なものが多そうなイメージで敷居が高いな...
OSSコントリビュート、これがいいって聞いたから読んでみようかな
https://goofi.vercel.app/

**Comment by Piyopanman** [comment]
https://darkreader.org/help/
DarkReaderに日本語のhelpページがない

**Comment by daipom** [comment]
DarkReaderのヘルプページがどう管理されているのかについて

https://github.com/darkreader から探すと、　https://github.com/darkreader/darkreader.github.io が見つかる。
これがウェブサイトを管理しているリポジトリーっぽい。

**Comment by daipom** [comment]
https://github.com/darkreader/darkreader.org/tree/main/src/help/topics

**Comment by daipom** [comment]
言語を追加しているPR。
参考になりそう

https://github.com/darkreader/darkreader.org/pull/11

**Comment by Piyopanman** [comment]
↑教えていただいたやつ、思ったより翻訳規模がちいさいので候補に置いておく。
できたらコード書きたいので、他も探しみてます

今はこれみてます　Lighthouse
https://github.com/GoogleChrome/lighthouse/labels/good%20first%20issue

**Comment by Piyopanman** [comment]
過去に自分が使ったライブラリ調べてる
https://github.com/Piyopanman/piyopanman-frontend-next/blob/main/package.json

**Comment by daipom** [comment]
Reactの過去のトピック例

* #1576

**Comment by Piyopanman** [comment]
https://github.com/remarkjs/react-markdown
markdownで最近日報を書くことが多いので、今からREADMEに沿って動かしてみて、何か見つけられたら嬉しい

**Comment by Piyopanman** [comment]
コントリビュートの御作法がまとまってると初めてでも安心感あって良いですね！！
https://github.com/oss-gate/workshop/issues/1631#issuecomment-1656525552

**Comment by Piyopanman** [comment]
過去のプルリク見ながら翻訳作業します💪
https://github.com/darkreader/darkreader.org/pull/11

**Comment by Piyopanman** [comment]
こっちのヘルプもあるの気づいていなかった
とりあえず上のmdファイルの方やります
https://github.com/darkreader/darkreader.github.io/tree/master/help

**Comment by blacktoad30** [comment]
https://github.com/darkreader/darkreader.org/blob/main/src/help/topics/en.md?plain=1

純粋なmarkdownではなく、htmlタグを混ぜた書き方になっている。

https://github.github.com/gfm/#html-blocks

**Comment by Piyopanman** [comment]
https://github.com/darkreader/darkreader.org/blob/main/src/help/topics/en.md

日本語以外のmdファイル、全部画像ファイルが404になってることに気づいた....
https://github.com/darkreader/darkreader.org/blob/main/images/help/darkreader-filter-settings.png

**Comment by Piyopanman** [comment]
www/imagesの下に画像類移動してるっぽい？

**Comment by Piyopanman** [comment]
https://github.com/darkreader/darkreader.org/pull/56
で既存mdファイルのimagesのパスを修正するプルリクを投げました
残り時間で日本語訳します

**Comment by blacktoad30** [comment]
このプルリクがOKならば、以下の*.mdも同様に修正する必要がありそう。

https://github.com/darkreader/darkreader.org/tree/main/src/blog/posts
https://github.com/darkreader/darkreader.org/tree/main/src/tips/topics

---

本家Webサイトのhtmlは、markdownから変換している?
画像は問題なく表示されているので、サーバーに`/images`はある。`/www/images`があるのかは分からない。
`/www/images`が正しいのならば、index.htmlなども修正する必要がありそう。
