### ISSUE TITLE
OSS Gate Workshop: online: 2023-07-29: yashirot: TortoiseGit: Work log

### ISSUE THREAD

**Issue by yashirot** [oss-gate/workshop#1633]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yashirot** [comment]
今日はTortoiseGitのUIをテーマにしたい。

**Comment by yashirot** [comment]
具体的には、Pullの「Prune」「Tag」オプションのチェックボックス

過去の社内チャットより転載：

```
Pruneオプションを見ると既にチェックが入ってました。

でもpulしてみると、オプションは付いてなかったですね。

git.exe pull --progress -v --no-rebase "origin"

それでPruneのチェックボックスを一度オフ→オンすると、--pruneオプションが入るようになりました。

git.exe pull --progress -v --no-rebase --prune "origin"

fetchについても同様でした
```

**Comment by yashirot** [comment]
実は、チェックボックスに3つ状態があると教えてもらった。

> Pruneのチェック、■と☑があるのですが、■の方ではなかったですか？

はい。よくよく見ると、初期状態はそれでした。

■ の表示
![image](https://github.com/oss-gate/workshop/assets/90631147/d68f7ff7-50a7-4418-9cd0-6828bb407b6b)

☑ の表示
![image](https://github.com/oss-gate/workshop/assets/90631147/23fd5c06-3d74-4283-a6c4-8a532ed3a452)

Window11環境では見分けづらかった。

**Comment by yashirot** [comment]
そもそも、チェックボックスに「3つ」状態があるのが常識外だった。
自分的にチェックボックスといえば、「ON」「OFF」の2値なので。

**Comment by yashirot** [comment]
今日のテーマ
1. このあたり、TortoiseGitとして過去に議論されてきているか？の確認
2. 確認結果に基づいて、働きかけ（Issueか、フィードバックか、or other?）

**Comment by yashirot** [comment]
Contributeを見る
https://tortoisegit.org/contribute/
～と、メインリポジトリはGitLabのようだ。

> Our main source code repository is hosted on GitLab: https://gitlab.com/tortoisegit/tortoisegit/;

**Comment by yashirot** [comment]
ライセンスを見る
GPL V2.0

https://gitlab.com/tortoisegit/tortoisegit/-/blob/master/LICENSE?ref_type=heads

```
                    GNU GENERAL PUBLIC LICENSE
                       Version 2, June 1991
```

下記リンクにも記載あり。
https://opensource.org/licenses/

https://opensource.org/license/gpl-2-0/

**Comment by yashirot** [comment]
How can I Contribute?を見る
https://tortoisegit.org/contribute/

> improving our [documentation](https://tortoisegit.org/docs/) (see [doc/readme.txt](https://gitlab.com/tortoisegit/tortoisegit/blob/master/doc/readme.txt) file and [doc](https://gitlab.com/tortoisegit/tortoisegit/tree/master/doc) folder),

となっているので、ドキュメンテーションのリンクへ
https://tortoisegit.org/docs/tortoisegit/

**Comment by yashirot** [comment]
`readme.txt`は、ドキュメントのビルド方法などの話。関係なさそう
https://gitlab.com/tortoisegit/tortoisegit/blob/master/doc/readme.txt

docフォルダの`HowToContribute.txt`にコントリビュートについて多少の言及あり。
https://gitlab.com/tortoisegit/tortoisegit/-/blob/master/doc/HowToContribute.txt?ref_type=heads

**Comment by yashirot** [comment]
`Tag`と`Prune`オプションの状態が3つあることは、ドキュメントに記載されていた
https://tortoisegit.org/docs/tortoisegit/tgit-dug-pull.html

```quote
Tags has three states (git 1.9 and later): Checked: All tags as well as branches are downloaded (--tags is passed to git), unchecked: No tags are downloaded (--no-tags is passed to git), and third state: use default behavior (based on remote.<name>.tagopt setting). Tags has three states (prior to git 1.9): Checked: Only all tags are downloaded but no branches are downloaded (--tags is passed to git), unchecked: No tags are downloaded (--no-tags is passed to git), and third state: use default behavior (based on remote.<name>.tagopt setting).

Prune has three states: True to remove remote-tracking branches which no longer exist on the remote, false: not to remove, and third state: use default behavior (based on remote.<name>.prune or fetch.prune git setting which can be set on [the section called “Remote”](https://tortoisegit.org/docs/tortoisegit/tgit-dug-settings.html#tgit-dug-settings-remote)).
```

**Comment by yashirot** [comment]
次のアクション：
当オプションのGUIに関する議論が過去にあったかを、Issueから探す

**Comment by yashirot** [comment]
2015年付のIssueで提起されていた

Fetch/Pull with prune does not work fine through GUI
https://gitlab.com/tortoisegit/tortoisegit/-/issues/2530

**Comment by yashirot** [comment]
こちらはpruneをGUI
https://gitlab.com/tortoisegit/tortoisegit/-/issues/383

**Comment by yashirot** [comment]
参考：チェックボックスのGUIに関するMicrosoft Learnの説明
https://learn.microsoft.com/en-us/windows/apps/design/controls/checkbox

**Comment by yashirot** [comment]
> 参考：チェックボックスのGUIに関するMicrosoft Learnの説明 https://learn.microsoft.com/en-us/windows/apps/design/controls/checkbox

Recommendationを見ると、「不定（indeterminate）」は第3のstateに使うな、ユーザに第3の状態を直接選ばせるなと書いてある。

> Don't use the indeterminate state to represent a third state. The indeterminate state is used to indicate that an option is set for some, but not all, sub-choices. So, don't allow users to set an indeterminate state directly.

TortoiseGitのPull>Options>`Tags`および`Prune`のチェックボックスの用法は、この推奨事項に反する。

**Comment by yashirot** [comment]
> 2015年付のIssueで提起されていた
> 
> Fetch/Pull with prune does not work fine through GUI https://gitlab.com/tortoisegit/tortoisegit/-/issues/2530

このIssue [#2530](https://gitlab.com/tortoisegit/tortoisegit/-/issues/2530)はOpenだった。ここへコメントする

**Comment by yashirot** [comment]
#2530でMentionされていたIssueも見てみる。

remember 'prune' state between fetches 
https://gitlab.com/tortoisegit/tortoisegit/-/issues/2656

関連は薄め。ひとまずスルーでよさそう。

**Comment by yashirot** [comment]
承前。

https://gitlab.com/tortoisegit/tortoisegit/-/issues/2562

> [@all](https://github.com/tortoisegit/tortoisegit) Seems as if the tri-state checkboxes cause some trouble; see [#2530](https://github.com/tortoisegit/tortoisegit/-/issues/2530).

3ステートのチェックボックスが時にトラブル要因となる認識はあるもよう。

**Comment by yashirot** [comment]
承前。

https://gitlab.com/tortoisegit/tortoisegit/-/issues/3037

> We could implement this as a three state checkbox, but this, however, has other implication that some users don't understand it (cf. issue [#2530](https://github.com/tortoisegit/tortoisegit/-/issues/2530); or default settings might change)

3ステートはユーザに理解されづらいことは認識している様子。

**Comment by yashirot** [comment]
ということで文案：

> The "Prune" checkbox is a Tri-state one.  
> Make sure it is checked.  
> Say :ballot_box_with_check:, instead of square.

Hi, 
I'm here from a search since I've experienced the similar to what someone who reported this had had. 

I suppose it will be so confusing to use the indeterminate state as a third state.

According to Microsoft Learn's Recommendations of Check Boxes, allowing users to set an indeterminate state directly looks a bad way.

Source:
https://learn.microsoft.com/en-us/windows/apps/design/controls/checkbox
As it recommends, maybe It is better to use radio button group in these GUI.

How about considering impovement?

**Comment by yashirot** [comment]
スクリーンショット：

![image](https://github.com/oss-gate/workshop/assets/90631147/43c23d43-f7d6-44df-9ac4-e0ab367510f6)

**Comment by daipom** [comment]
とてもわかりやすくまとまっていて良いと思いいます！
そのスクショも付けるとより分かりやすくなると思います！

もしスクショを付けにくいケースでは、次のようにリンクのあとに引用の形で重要な一文を書いておくのもありかもしれません。(ご参考までに)

> Don't use the indeterminate state to represent a third state.

**Comment by yashirot** [comment]
一部文言を整えてコメントしてみた


https://gitlab.com/tortoisegit/tortoisegit/-/issues/2530#note_1492742574

**Comment by yashirot** [comment]
【メモ】
Microsoft Learnのページは、「Windows 10 3state checkboxのGUI」を画像検索して見つかった。
元々は「Windowsのどのバージョンから、チェックボックスが現在のグラフィックになったか？」を知りたかった。
