### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: stshsmt: dalli: 作業ログ

### ISSUE THREAD

**Issue by stshsmt** [oss-gate/workshop#164]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by stshsmt** [comment]
対象のOSSを決めた。
https://github.com/petergoldstein/dalli

理由は最近仕事で少し使ってみたことがあるから。

**Comment by stshsmt** [comment]
まずはREADMEをきちんと読んでみる。
https://github.com/petergoldstein/dalli#dalli---

**Comment by stshsmt** [comment]
READMEを読んでいると、Railsのバージョンに関する古い記述があった。
https://github.com/petergoldstein/dalli#usage-with-rails-3x-and-4x

Rails3系はサポートが切れたはずなので、ここは古い記述を訂正した方がよいかも!?

**Comment by stshsmt** [comment]
memcahedのバージョンに指定があるっぽい。

> Dalli requires memcached 1.4+

**Comment by stshsmt** [comment]
ローカルのmemcachedのバージョンは、

```
➜  ~ memcached -V
memcached 1.4.24
```

だった。

**Comment by stshsmt** [comment]
README通りにgemをインストールしてみる。

> gem install dalli

**Comment by stshsmt** [comment]
READMEに書いてある通りに動くかどうか、試しに動かしてみる。

**Comment by stshsmt** [comment]
```
require 'dalli'
options = { :namespace => "app_v1", :compress => true }
dc = Dalli::Client.new('localhost:11211', options)
dc.set('abc', 123)
value = dc.get('abc')
```

これが動くか試し中。

**Comment by stshsmt** [comment]
動いた！

` 123 ` が返ってきた！

**Comment by stshsmt** [comment]
そういえばローカルのRubyのバージョンが古かった（2.2.4）ので、新しいバージョンでも試して見よう。

**Comment by stshsmt** [comment]
Ruby 2.3.0  で動かしてみたら、以下のエラーが出た。

```

**Comment by stshsmt** [comment]
Rubyのバージョンを上げてから再度gemをインストールしたらOKだった。

**Comment by stshsmt** [comment]
Rubyの最新版 ` 2.3.3 ` でも動いた！

**Comment by stshsmt** [comment]
memcachedのバージョンを上げてみたけど、動いた。

```
➜  memcached -V
memcached 1.4.33
```

**Comment by stshsmt** [comment]
現時点で考えられる案として以下の2つがある。

1. Rails3系のサポートが切れているので、そのことに関する文言を追加するよう提案してみる。
https://github.com/petergoldstein/dalli#usage-with-rails-3x-and-4x

2. Rails5系で動くか検証してみて、フィードバックする。
Cangelogには以下のような記述がある。
> Rails 5.0.0.beta2 compatibility (yui-knk, petergoldstein)

**Comment by stshsmt** [comment]
memo
http://guides.rubyonrails.org/maintenance_policy.html

**Comment by stshsmt** [comment]
残り時間を考えて ` 1 ` を選択してみる。

**Comment by stshsmt** [comment]
# dalliのRailsサポートバージョンに関して
## 3系に関して
- Rails3系に関する記述があるが、Rails3系は ` 3.2.22.5 ` でサポートが切れているので、記述が古くなってしまっている。
- これからdalliを使う人はRails3系向けの記述を見ると混乱するかもしれない。
- 開発者としては3系を使っている人も多数いると思うので、3系に関する記述を削除するのは避けたい。
- ただし3系はサポート切れてるよ、ということを明記した方がいいかもしれない。
- 

# 5系に関して
- 5系に関する記述がREADMEにないので、追加したい。（ただし検証が必要。）

**Comment by stshsmt** [comment]
↑を文章にしてみる。

READMEに書いてあるRails3系に関する記述を変更するか、3系を使用することは非推奨だという旨の記述を追記した方がよいと思います。

なぜならRails3系のサポートは既に切れており、これからこのgemを使用する人にとっては不要な情報であり、またRails3系を使用することを暗に示唆してしまうかもしれないからです。

Rails3系のサポートに関しては、http://guides.rubyonrails.org/maintenance_policy.html を参照しており、` Currently included series: 5.0.Z, 4.2.Z. ` という記述から、現在は3系が含まれていないことを確認しています。

**Comment by stshsmt** [comment]
↑をとりあえずGoogle翻訳へ...

```
I think that it is better to add a description that changes of the description on Rails 3 system written in the README or use of the 3 system is deprecated.

Because support for Rails 3 has already expired, it is unnecessary information for those who use this gem from now on, and may implicitly suggest using Rails 3 system.

Regarding the support of Rails 3 series, we refer to http: //guides.rubyonrails.org/maintenance_policy.html, and from the description of Currently included series: 5.0.Z, 4.2.Z., now 3 systems are included There is no confirmation.
```

**Comment by stshsmt** [comment]
↑を整形してみます。

I think that It would be better to delete the description about Rails 3.X from README or to add a description that 3.X is deprecated(*).

I concern that  it maybe unnecessary information for new users and may implicitly suggest using Rails 3.X.

* I found that `Currently included series: 5.0.Z, 4.2.Z. `  in http://guides.rubyonrails.org/maintenance_policy.html

Thank you.

**Comment by stshsmt** [comment]
https://github.com/petergoldstein/dalli/issues/639

issue出してみた!!!

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-28に開催](https://oss-gate.doorkeeper.jp/events/52881)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
