### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-09: umizaru: umizaru: Work log

### ISSUE THREAD

**Issue by umizaru** [oss-gate/workshop#1648]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by umizaru** [comment]
最近興味のあるOSS。
・Chromeの拡張機能：Vimium、ウェブサイトブロッカー

**Comment by umizaru** [comment]
Rubyのgem、JSのnpmから探す？

**Comment by umizaru** [comment]
VimiumのChromeウェブストアを見た
https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb

Vimiumのリリースノートを見た
https://github.com/philc/vimium/blob/master/CHANGELOG.md

**Comment by umizaru** [comment]
Vimiumの公式サイトを見る
https://vimium.github.io/

**Comment by umizaru** [comment]
MIT-Licenseあり
https://github.com/philc/vimium/tree/master

**Comment by umizaru** [comment]
別のプロファイルでChromeを開いた

**Comment by umizaru** [comment]
別のプロファイルにVimiumをインストール

**Comment by umizaru** [comment]
READMEを読み始める
https://github.com/philc/vimium/blob/master/README.md

**Comment by umizaru** [comment]
キーバインディングの設定の仕方がよく分かっていない。特に、Custom search enginesの設定方法。＃を外せば、キーを押下して目的のウェブサイトに飛ぶものと思ったがそうならない。

**Comment by umizaru** [comment]
save Changesのボタンが分かりづらい

**Comment by umizaru** [comment]
公式のSearch-Engineのドキュメントを読む。オムニバーのvim版をボムニバーと言う。
https://github.com/philc/vimium/wiki/Search-Engines

**Comment by umizaru** [comment]
o a cherry pie [enter]でAmazonでチェリーパイを検索したページに到達

**Comment by umizaru** [comment]
save Changesのボタンの表示が分かりづらいので分かりやすくしたほうがよい、もしくは修正された時点で反映されるべき、ってことをフィードバックしたい

**Comment by umizaru** [comment]
save Changesのボタンの表示が分かりづらいので分かりやすくしたほうがよい、もしくは修正された時点で反映されるべき、ってことをフィードバックしたい

**Comment by umizaru** [comment]
READMEのContributing to Vimiumのドキュメントを読む。今回はコーディングしないのでコーディングスタイルの指定は対象外。報告するときに使用しなければならないフォーマットなども特にないっぽい。

https://github.com/philc/vimium/blob/master/CONTRIBUTING.md

**Comment by umizaru** [comment]
件名：[Feature Request] `Save Changes`ボタンの表示位置の変更

## 実行環境
- MacOS : MacOS Ventura 13.5.1(22G90)
- Chrome Version : 116.0.5845.140（Official Build）（arm64）

## やったこと
- Chromeの拡張機能一覧のページにアクセス
- Vimiumの詳細ボタンを表示
- 拡張機能のオプションを表示
- `Custom search engines`のMore Examples下にあるショートカットの「#」をすべて削除。
- `o y cherry pie [enter]`したものの、youtube内で検索が行われない。

## 原因
- `Custom search engines`を編集した後に、画面下部の`Save Changes`をクリックしていなかった。
- 初めてOptionsの画面を編集するユーザにとって、`Save Changes`のボタンが見つけにくいと思う。

## 提案
- `Save Changes`ボタンを画面の中央寄りに移動させるのはどうか。例えば`Custom search engines`のすぐ下のスペースなど。
- もしくは、`Excluded URLs and keys`, `Custom key mappings`, `Custom search engines`の項目で入力内容の修正が行われたら、`Save Changes`を押すことなく、それらの項目の入力内容が反映されるようにするのはどうか。

**Comment by komagata** [comment]
フィーチャーリクエストなのでバグ報告のフォーマットは使わないほうがいいように思いました。
また、入力欄からボタンがどのぐらい離れててわかりづらいかを示すためにスクショがあったほうがいいかなと思いました。（画面の縦幅は人によって違うので）

**Comment by daipom** [comment]
この人の書き方が参考になりそうです

https://github.com/philc/vimium/issues/4301

**Comment by daipom** [comment]
Expected behaviorを複数並べるときは、単に箇条書きを並べると全部ほしいのかどれかでいいのかが分かりにくくなるかもしれないと思いました。
例えば次のように、次のうちどれかだと嬉しいという内容を書くとよいかもしれません。

I'd be happy with any of the following:

* aaaaa
* bbbb
* ccccc

**Comment by umizaru** [comment]
件名：[Feature Request] `Save Changes`ボタンの表示位置の変更

## Current behavior
- `Vimium Options`にある、`Custom search engines`の欄と`Save Changes`ボタンが離れており、`Save Changes`ボタンの存在に気づきにくい。

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:
- `Save Changes`ボタンを画面の中央寄りに移動させるのはどうか。例えば`Custom search engines`のすぐ下のスペースなど。
- もしくは`Excluded URLs and keys`, `Custom key mappings`, `Custom search engines`の項目で入力内容の修正が行われたら、`Save Changes`を押すことなくそれらの項目の入力内容が反映されるようにするのはどうか。
- `Custom search engines`の欄のすぐ下に"入力したら`Save Changes`ボタンを押してください"などの注意書きを載せるのはどうか。

**Comment by umizaru** [comment]
件名：[Feature Request] `Save Changes`ボタンを見つけやすくする

## Current behavior
- `Vimium Options`にある、`Custom search engines`の欄と`Save Changes`ボタンが離れており、`Save Changes`ボタンの存在に気づきにくい。

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:
- `Save Changes`ボタンを例えば`Custom search engines`のすぐ下のスペースに移動させるのはどうか。
- `Custom search engines`の欄のすぐ下に"入力したら`Save Changes`ボタンを押してください"などの注意書きを載せるのはどうか。
- もしくは`Excluded URLs and keys`, `Custom key mappings`, `Custom search engines`の項目で入力内容の修正が行われたら、`Save Changes`を押すことなくそれらの項目の入力内容が反映されるようにするのはどうか。

**Comment by komagata** [comment]
> Save Changesボタンを画面の中央寄りに移動させるのはどうか。

中央とは、上下での中央なのか、左右での中央なのかわからないので別の表現に変えたほうが良いかもです。（一般的にHTMLのレイアウトで中央といったら左右での中央を表すことが多いということもあり。）
言葉で表現が難しければスクショに文字や図形を書き込むのもわかりやすいかも。

また、ボタンの存在に気づかないことを回避するためにドキュメントの方に「Save Changesボタンを押して変更を保存するのを忘れないように」と書いておくのもいいかも。（PRを送る場合の現実的な変更になりそうという邪念もあり…）

**Comment by umizaru** [comment]
件名：[Feature Request] `Save Changes`ボタンを見つけやすくする

## Current behavior
- `Vimium Options`にある、`Custom search engines`の欄と`Save Changes`ボタンが離れており、`Save Changes`ボタンの存在に気づきにくい。

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:
- `Save Changes`ボタンを例えば`Custom search engines`のすぐ下のスペースに移動させるのはどうか。
- `Custom search engines`の欄のすぐ下に、"入力したら`Save Changes`ボタンを押してください"などの注意書きを載せるのはどうか。
- [`Custom search engines`のドキュメント](https://github.com/philc/vimium/wiki/Search-Engines#ideas-for-search-engine-shortcuts)に、「ショートカットを追加したらSave Changedボタンを押して変更を保存するのを忘れないように」と載せるのはどうか。
- もしくは`Excluded URLs and keys`, `Custom key mappings`, `Custom search engines`の項目で入力内容の修正が行われたら、`Save Changes`を押すことなくそれらの項目の入力内容が反映されるようにするのはどうか。

**Comment by umizaru** [comment]
件名：[Feature Request] `Save Changes`ボタンを見つけやすくする

## Current behavior
- `Vimium Options`にある、`Custom search engines`の欄と`Save Changes`ボタンが離れており、`Save Changes`ボタンの存在に気づきにくい。

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:
- `Save Changes`ボタンを例えば`Custom search engines`のすぐ下のスペースに移動させる。
- `Custom search engines`の欄のすぐ下に、"入力したら`Save Changes`ボタンを押してください"などの注意書きを載せる。
- [`Custom search engines`のドキュメント](https://github.com/philc/vimium/wiki/Search-Engines#ideas-for-search-engine-shortcuts)に、「ショートカットを追加したらSave Changedボタンを押して変更を保存するのを忘れないように」と載せる。
- もしくは`Excluded URLs and keys`, `Custom key mappings`, `Custom search engines`の項目で入力内容の修正が行われたら、`Save Changes`を押すことなくそれらの項目の入力内容が反映されるようにする。

**Comment by komagata** [comment]
> Save Changesボタンを例えばCustom search enginesのすぐ下のスペースに移動させるのはどうか。

*I'd be happy with any of the following:*の部分に「〜というのはどうか？」という意味も含まれていると思うので、４選択肢の部分は「〜というのはどうか？」はなしで言い切りの形でいいかなと思います。

**Comment by umizaru** [comment]
件名：[Feature Request] `Save Changes`ボタンの存在に気づきにくく、修正内容が反映されない

## Current behavior
- `Vimium Options`にある、`Custom search engines`の欄と`Save Changes`ボタンが離れているため`Save Changes`ボタンの存在に気づきにくく、内容を修正してもそれが設定に反映されない。

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:
- `Save Changes`ボタンを例えば`Custom search engines`のすぐ下のスペースに移動させる。
- `Custom search engines`の欄のすぐ下に、"入力したら`Save Changes`ボタンを押してください"などの注意書きを載せる。
- [`Custom search engines`のドキュメント](https://github.com/philc/vimium/wiki/Search-Engines#ideas-for-search-engine-shortcuts)に、「ショートカットを追加したらSave Changedボタンを押して変更を保存するのを忘れないように」と載せる。
- もしくは`Excluded URLs and keys`, `Custom key mappings`, `Custom search engines`の項目で入力内容の修正が行われたら、`Save Changes`を押すことなくそれらの項目の入力内容が反映されるようにする。

**Comment by umizaru** [comment]
Subject: [Feature Request] `Save Changes` button is hard to notice, and modifications are not reflected.

## Current behavior
- The `Custom search engines` field in `Vimium Options` and the `Save Changes` button are far apart, so it is difficult to notice the existence of the `Save Changes` button and the modifications are not reflected in the settings.

![スクリーンショット 2023-09-09 17 10 57](https://github.com/oss-gate/workshop/assets/57088113/c6cb10ac-fc40-43c5-bf7d-04e0532ebbed)

## Expected behavior of new feature
I'd be happy with any of the following:.
- Move the `Save Changes` button to a space just below `Custom search engines`, for example.
- Put a note just below the `Custom search engines` field that says something like "Please press the `Save Changes` button after entering information".
- In the [`Custom search engines` documentation](https://github.com/philc/vimium/wiki/Search-Engines#ideas-for-search-engine-shortcuts), add a note that says, "When you add a shortcut, press the Save Changed button. Don't forget to click the Save Changed button after adding a shortcut.
- Or, if the entries in the `Excluded URLs and keys`, `Custom key mappings`, and `Custom search engines` fields are modified, the entries in those fields will be reflected without pressing `Save Changes`.
