### ISSUE TITLE
 OSS Gate Workshop: online: 2023-09-09: orangeman7201: pretty-ts-errors: Work log

### ISSUE THREAD

**Issue by orangeman7201** [oss-gate/workshop#1650]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daipom** [comment]
iTerm2: https://github.com/gnachman/iTerm2

なぜかissue欄がない。。。

**Comment by orangeman7201** [comment]
気になるOSSメモ
* iTerm2
* Chromeの拡張機能のVue devtools https://github.com/vuejs/devtools

**Comment by orangeman7201** [comment]
一旦ITerm2のドキュメントを見てみる。

**Comment by orangeman7201** [comment]
gem見てみる

**Comment by orangeman7201** [comment]
gem のライブラリでよく使っているもの
* active_model_serializers
* kaminari
* grape
* cancancan
* jwt
* simplecov

js関連
* vue-infinite-loading
* chart.js
* dayjs
* pretty Typescript Errors(VScode の拡張)

**Comment by orangeman7201** [comment]
上記の中から良さそうなものを選ぶ

**Comment by orangeman7201** [comment]
## Pretty Typescript Errors
最近できた拡張機能だが、starの数が11kを超えていて手を出しにくそう。。

[pretty-ts-errors](https://github.com/yoavbls/pretty-ts-errors)

**Comment by orangeman7201** [comment]
一旦興味があるのでPretty Typescript Errorsで進めてみる。

**Comment by orangeman7201** [comment]
Pretty Typescript Errorsのライセンス情報は？

**Comment by orangeman7201** [comment]
ドキュメントを探す！

**Comment by orangeman7201** [comment]
📝 
結構OSS活動支援してそう。

Sponsorship
Every penny will be invested in other contributors to the project, especially ones that work
on things that I can't be doing myself like adding support to the extension for other IDEs 🫂

Contribution
Help by upvoting or commenting on issues we need to be resolved https://github.com/yoavbls/pretty-ts-errors/discussions/43
Any other contribution is welcome. Feel free to open any issue / PR you think.

**Comment by orangeman7201** [comment]
read meに沿って動かしてみる。

**Comment by orangeman7201** [comment]
before 
<img width="727" alt="index_ts_—_private" src="https://github.com/oss-gate/workshop/assets/84920430/ff994177-40fd-4d8c-96cf-5b5c2d6d5afd">

**Comment by orangeman7201** [comment]
FBポイントを探す。

**Comment by daipom** [comment]
すでにあったissue

https://github.com/yoavbls/pretty-ts-errors/issues/3

**Comment by orangeman7201** [comment]
FBポイント

githubのissues上部に表示される`contributing guidelines`に遷移すると、`Contribute good stuff`とだけ記入されているファイルに遷移する。

### 遷移前の画面

https://github.com/yoavbls/pretty-ts-errors/issues

![Cursor_と_Issues_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/72f47034-6f3a-42d9-8a01-0521f1fcf7b1)


### 遷移先のファイル
https://github.com/yoavbls/pretty-ts-errors/blob/e31e3dae263adf1f8a6c64aabf447e5228387714/CONTRIBUTING.md
![Cursor_と_pretty-ts-errors_CONTRIBUTING_md_at_e31e3dae263adf1f8a6c64aabf447e5228387714_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/347692cd-2ee1-4bed-a1fe-09f8d03823f9)

**Comment by orangeman7201** [comment]
あ〜readmeに書いていたContributionのリンクはこの拡張を作った人がvscodeにPRを積んだから応援してねという案内だけか、、

**Comment by orangeman7201** [comment]
お、この内容をガイドラインのところに入れるだけでも良さそう。。

https://github.com/yoavbls/pretty-ts-errors/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by orangeman7201** [comment]
NA 「ここ変やで〜^^。ワイ直そうか？」のissue作る
* actual result 
* expexct result

**Comment by orangeman7201** [comment]
まずは日本語で書いてみる

タイトル : githubのcontributing guidelinesの内容が変なので変えませんか？

##  現状
現状CONTRIBUTING.mdの中身は以下の1行だけです。
```
Contribute good stuff
```

このファイルへのリンクが以下のページで表示されています。
* [issuesの上部](https://github.com/yoavbls/pretty-ts-errors/issues)
* [Pull Requestsの上部](https://github.com/yoavbls/pretty-ts-errors/pulls)
* [issue記入画面](https://github.com/yoavbls/pretty-ts-errors/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=)

こんな感じです。
issuesの上部|Pull Requestsの上部|issue記入画面
-|-|-
![Issues_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/55f47b92-a531-4ad8-b955-1b78b59019ac)|![Issues_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/372ff0ad-cf59-4aea-9835-c7ad94559fd9)|![Cursor_と_New_Issue_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/c8254eec-7378-4f09-b36c-1b8c9531a8e6)

**Comment by orangeman7201** [comment]
レビュー
* 内容自体はだいたい良さそう。
* なぜガイドラインとして機能していないかを追記する。
* 英語版を作成してみる！

**Comment by orangeman7201** [comment]
# The contributing guidelines on github are too little, why don't you change them?

##  Now
[CONTRIBUTING.md](https://github.com/search?q=repo%3Ayoavbls%2Fpretty-ts-errors%20contributing&type=code) contains only the following one line, which has little content and does not function well as a guideline.
```
Contribute good stuff
```

Moreover, a link to this file is shown as a guideline on the following page.
* [Top of issues](https://github.com/yoavbls/pretty-ts-errors/issues)
* [Top of Pull Requests](https://github.com/yoavbls/pretty-ts-errors/pulls)
* [Screen for filling out an issue](https://github.com/yoavbls/pretty-ts-errors/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=)

This is a capture of the current screen
Top of issues|Top of Pull Requests|Screen for filling out an issue
-|-|-
![Issues_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/55f47b92-a531-4ad8-b955-1b78b59019ac)|![Issues_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/372ff0ad-cf59-4aea-9835-c7ad94559fd9)|![Cursor_と_New_Issue_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/c8254eec-7378-4f09-b36c-1b8c9531a8e6)

## Expected

Would you change the contents of CONTRIBUTING.md to the following?
( The contents are the same as bug_report.md. )

```
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Original error**
If this bug is related to an error that is not formatting well, please
attach the original error in a code block:
<code>
Type 'number' is not assignable to type 'string'.ts(2322)
</code>

**Screenshots**
If applicable, add screenshots to help explain your problem.
```

**Comment by orangeman7201** [comment]
レビュー
Expectedのなっかで contentsを単数形に

**Comment by orangeman7201** [comment]
CONTRIBUTING.mdにはガチガチに書くことはなくて少し抽象的にする。
バグレポートは、テンプレートに沿って書いてください。という内容にする！

**Comment by daipom** [comment]
`Expected`の方は

「バグレポートは、バグレポートのテンプレートに即して報告してください」

のような一文にするくらいがよいかもしれません！

**Comment by orangeman7201** [comment]
issueを投稿してみました！

https://github.com/yoavbls/pretty-ts-errors/issues/78
