### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-09: niwa2323: blender

### ISSUE THREAD

**Issue by niwatori-rookie** [oss-gate/workshop#1651]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

OSS Gate Workshop: online: 2023-09-09: niwa2323: blender

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daipom** [comment]
Blenderのリポジトリーはこれっぽいです。
自分たちで自前のGitサーバーを立てているみたい

https://projects.blender.org/blender/blender

**Comment by daipom** [comment]
Blenderのドキュメントリポジトリー

https://projects.blender.org/blender/blender-manual

**Comment by daipom** [comment]
Blenderの公式ドキュメント

https://docs.blender.org/manual/en/dev/

**Comment by yashirot** [comment]
ドキュメントサイト（日本語版）
https://docs.blender.org/manual/ja/4.0/contribute/install/index.html
左下で言語選択できる

**Comment by yashirot** [comment]
ライセンス情報
https://www.blender.org/about/license/

**Comment by niwatori-rookie** [comment]
マニュアルの翻訳にてあまり知られていない言語への変換の処理が遅い

**Comment by niwatori-rookie** [comment]
ドキュメントを読み始めた

**Comment by niwatori-rookie** [comment]
自分でライセンスを確認した

**Comment by niwatori-rookie** [comment]
マニュアルの翻訳にてあまり知られていない言語への変換の処理が遅い

**Comment by niwatori-rookie** [comment]
マニュアルの翻訳にてあまり知られていない言語への変換の処理が遅い
（English｛英語｝→српски ｛セルビア語｝）

**Comment by niwatori-rookie** [comment]
続けてEnglish｛英語｝←српски ｛セルビア語｝を操作するとすぐに変換された

**Comment by niwatori-rookie** [comment]
マニュアルの次、前のページ移るnextとpreviosが翻訳されない

**Comment by yashirot** [comment]
「入門」の手順に沿ってマニュアルのビルドをやってみる
https://docs.blender.org/manual/ja/4.0/contribute/index.html

**Comment by niwatori-rookie** [comment]
https://projects.blender.org/blender/blender-manual.git

**Comment by yashirot** [comment]
「貢献する」の説明を日本語`ja`に読み替える
https://docs.blender.org/manual/ja/4.0/contribute/translations/contribute.html

**Comment by daipom** [comment]
翻訳リソースは別リポジトリーでした。

https://projects.blender.org/blender/blender-manual-translations

**Comment by daipom** [comment]
翻訳の追加方法に関するドキュメントリスト

次にまとまっていそうなのだが、読んでも分かりにくい。
この辺りをもっとわかりやすくしてほしい、という報告はありだと思う。
(それをするにあたっては頑張ってこの辺りを多少読み込んだ上で報告内容を考える必要がありそうだが)

* https://docs.blender.org/manual/ja/4.0/contribute/translations/contribute.html#fork-translation-repository
* https://docs.blender.org/manual/ja/4.0/contribute/translations/add_language.html

**Comment by niwatori-rookie** [comment]
今頃になって申し訳ないのですが教えていただいた翻訳の追加方法に関するドキュメントを読んでみたのですが、用語が分からないのもあって報告内容を考えるのはちょっと厳しそうです。
あと私には荷が重たすぎたせいか頭がパンクしたのでちょっと会議には参加できそうにありません。すいません。ですが今回、OSSを深堀出来るいい機会でしたしまたもし次の機会に参加するときがあればそれまでにOSSに関する勉強しようと思います！

**Comment by yashirot** [comment]
力不足でサポートが行き届かず、すみませんでした。
続きからでもまた参加してください。

**Comment by daipom** [comment]
力不足ですみません！
ぜひまたご参加いただければと思います！
