### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-09: natsuto: aws/copilot-cli: Work log

### ISSUE THREAD

**Issue by natsuto6** [oss-gate/workshop#1652]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by natsuto6** [comment]
copilot-cliなんてどうだろう
https://github.com/aws/copilot-cli

**Comment by natsuto6** [comment]
Apache License 2.0だった

**Comment by natsuto6** [comment]
README読んで作業進めてみる

**Comment by blacktoad30** [comment]
> Apache License 2.0だった

こちらも参考として置いておきますね
https://opensource.org/license/apache-2-0/

**Comment by natsuto6** [comment]
https://aws.github.io/copilot-cli/docs/overview/

とりあえずインストールを試みる

**Comment by natsuto6** [comment]
Command Line Toolsが古いために失敗する。
```
==> Installing copilot-cli from aws/tap
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.3.
```

**Comment by blacktoad30** [comment]
> 

aws-cliではなく、homwbrewなどの問題ですかね?

**Comment by blacktoad30** [comment]
https://michimani.net/post/aws-error-occuerd-in-upgrading-copilot-at-macos-bigsur/

**Comment by natsuto6** [comment]
`softwareupdate --all --install --force`実行中

**Comment by natsuto6** [comment]
一旦上記キャンセルし、ターミナルに表示されている通り以下を実行
・`sudo rm -rf /Library/Developer/CommandLineTools`
・`sudo xcode-select --install`

**Comment by blacktoad30** [comment]
> ちょっと古い記事かもしれませんが https://michimani.net/post/aws-error-occuerd-in-upgrading-copilot-at-macos-bigsur/

エラーメッセージに、`softwareupdate --all --install --force`の記述は無かったので、やらなくても良かったかもしれない...

**Comment by natsuto6** [comment]
上記コマンドの通りCommand Line Toolsを削除後、新しいCommand Line Toolsをインストール完了。
再度`brew install aws/tap/copilot-cli`を実行する。

**Comment by natsuto6** [comment]
`copilot-cli`やっと正常にインストール完了！

**Comment by daipom** [comment]
過去の同様のissue事例 (CommandLineTools関連でインストールに失敗する)

https://github.com/aws/copilot-cli/issues/2551

**Comment by natsuto6** [comment]
`copilot-cli/CONTRIBUTING.md`確認中

**Comment by natsuto6** [comment]
今回のまとめ

参考：
[AWS Copilot CLIのREADME](https://github.com/aws/copilot-cli)
[Documentation](https://aws.github.io/copilot-cli/docs/overview/)

#実施したこと・起こったこと
1. `brew install aws/tap/copilot-cli`を実行

2. ターミナルに以下のエラーとその対応内容が出力（コマンドラインツールが古すぎ）
```
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.3.
```

3. 更新がなかったため、Macのシステム設定からアップデートは行わなかった
4. ターミナル上で`sudo rm -rf /Library/Developer/CommandLineTools`を実行し、Command Line Toolsを削除
5. ターミナル上で`sudo xcode-select --install`を実行し新しいCommand Line Toolsをインストール
6. 再度`brew install aws/tap/copilot-cli`を実行し、インストール完了
```
==> Summary
🍺  /usr/local/Cellar/copilot-cli/1.30.1: 5 files, 50.5MB, built in 16 seconds
```

# 実施環境
macOS Ventura 13.5.1

**Comment by natsuto6** [comment]
Issueを作成しました。ご確認をお願いいたします。

# `brew install aws/tap/copilot-cli`実行時の挙動内容をドキュメントに追加する

## ActualResult
1. `brew install aws/tap/copilot-cli`を実行。
ターミナルに以下のエラーとその対応内容が出力。（コマンドラインツールが古すぎる）
```
...
...
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.3.
```

2. ソフトウェアアップデートがなかったため、Macのシステム設定からアップデートは行わなかった。
3. ターミナル上で`sudo rm -rf /Library/Developer/CommandLineTools`を実行。パスワードを実行し、Command Line Toolsを削除。
4. ターミナル上で`sudo xcode-select --install`を実行。ダイアログが出るため、利用規約に同意して新しいCommand Line Toolsをインストール。
5. 再度`brew install aws/tap/copilot-cli`を実行し、インストール完了。
```
==> Summary
🍺  /usr/local/Cellar/copilot-cli/1.30.1: 5 files, 50.5MB, built in 16 seconds
```

6. バージョンの確認を実施。
```
❯ copilot version
version: v1.30.1, built for darwin
```

- 実施環境
macOS Ventura 13.5.1





## Expected behavior

I'd be happy with any of the following:

- `brew install aws/tap/copilot-cli`実行後の
エラーメッセージ(`Update them from Software Update in System Settings.`)箇所への
ソフトウェアアップデートの確認、アップデートコマンドの追記。
またはGUI実行フローの追記。

**Comment by natsuto6** [comment]
英語表記にする

# I need to add to the documentation what to do when running `brew install aws/tap/copilot-cli` and error behavior.

## ActualResult
1. Run `brew install aws/tap/copilot-cli`.
The following errors and their responses are output to the terminal. (Command line tool is too old)
```
...
...
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.3.
```

2. Regarding software updates, there were no commands or other information on the terminal, so we checked the Mac's system settings to confirm that no update was required.

3. Run `sudo rm -rf /Library/Developer/CommandLineTools on a terminal`. Run password and remove Command Line Tools.

4. Run `sudo xcode-select --install on the terminal`. A dialog box will appear, so agree to the Terms of Use and install the new Command Line Tools.

5. Run `brew install aws/tap/copilot-cli` again to complete the installation.
```
==> Summary
🍺  /usr/local/Cellar/copilot-cli/1.30.1: 5 files, 50.5MB, built in 16 seconds
```

6. Verification of version.
```
❯ copilot version
version: v1.30.1, built for darwin
```

- Implementation Environment
macOS Ventura 13.5.1


## Expected behavior

I'd be happy with any of the following:

- There is no specific response to the error message (`Update them from Software Update in System Settings.`) after executing `brew install aws/tap/copilot-cli`.
Therefore, we suggest checking for software updates and adding an update command.
Or, we suggest adding a GUI execution flow.

**Comment by natsuto6** [comment]
ちょっと修正（日本語）

# `brew install aws/tap/copilot-cli`実行時のエラー挙動時の内容をドキュメントに追加する

## ActualResult
1. `brew install aws/tap/copilot-cli`を実行する。
2. エラーメッセージが出力される。（コマンドラインツールが古い）
```
...
...
Error: Your Command Line Tools are too outdated.
...
```

## Steps to Resolve the Issue
1. Macのシステム設定でソフトウェアのアップデートが不要であることを確認。
2. ターミナルで`sudo rm -rf /Library/Developer/CommandLineTools`を実行し、パスワードを入力してコマンドラインツールを削除。
3. ターミナルで`sudo xcode-select --install`を実行し、ダイアログボックスが表示されたら利用規約に同意して新しいコマンドラインツールをインストール。
4. 再度`brew install aws/tap/copilot-cli`を実行してインストールを完了。

- 実施環境
macOS Ventura 13.5.1


## Expected behavior

I'd be happy with any of the following:

- `brew install aws/tap/copilot-cli`実行後のエラーメッセージに対する具体的な対処方法をドキュメントに追加する。
- ソフトウェアアップデートの確認方法やアップデートコマンドを追加する。

**Comment by natsuto6** [comment]
再度英語版
# Need to Add Error-Handling Steps to Documentation for `brew install aws/tap/copilot-cli`

## ActualResult
1. Execute `brew install aws/tap/copilot-cli`.
2. An error message is output indicating that the Command Line Tools are outdated.
```
...
...
Error: Your Command Line Tools are too outdated.
...
```

## Steps to Resolve the Issue
1. Checked in Mac system settings to confirm that no software update is required.
2. Executed`sudo rm -rf /Library/Developer/CommandLineTools`in the terminal, entered the password, and removed the Command Line Tools.
3. Executed`sudo xcode-select --install`in the terminal, a dialog box appeared, and agreed to the terms and conditions to install new Command Line Tools.
4. Executed`brew install aws/tap/copilot-cli`again to complete the installation.

- System Information
macOS Ventura 13.5.1


## Expected behavior

- Add specific instructions for handling the error message to the documentation.
- Add steps for checking for software updates or commands to update the system.

**Comment by natsuto6** [comment]
Issue立てたー
https://github.com/aws/copilot-cli/issues/5294

**Comment by daipom** [comment]
良いと思います！
エラーメッセージを省略しない方が良いことなどはkouさんがPRの方でコメントしてくださっていますね！
(kouさんありがとうございます！)
僕もそう思います！
kouさんとのやりとりでとても明瞭な内容になったと思います！
