### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-09: goruchan: docker-ros2-desktop-vnc: Work log

### ISSUE THREAD

**Issue by goruchanchan** [oss-gate/workshop#1653]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by goruchanchan** [comment]
UbuntuでROSを使っているが、せっかくならMacでも動かしてみたいので調査

**Comment by goruchanchan** [comment]
ブラウザでROSを動かせるコンテナのOSSっぽいものがあった

https://github.com/Tiryoh/docker-ros2-desktop-vnc

**Comment by goruchanchan** [comment]
[docker\-ros2\-desktop\-vnc/LICENSE at master · Tiryoh/docker\-ros2\-desktop\-vnc](https://github.com/Tiryoh/docker-ros2-desktop-vnc/blob/master/LICENSE)

ライセンス的にはApacheらしい

**Comment by goruchanchan** [comment]
[docker\-ros2\-desktop\-vnc/LICENSE at master · Tiryoh/docker\-ros2\-desktop\-vnc](https://github.com/Tiryoh/docker-ros2-desktop-vnc/blob/master/LICENSE)

上記にあるのでOSSとして公開されていそう

**Comment by goruchanchan** [comment]
なのでこいつをMacで動かしてみようと思います！

**Comment by goruchanchan** [comment]
[Quick Start](https://github.com/Tiryoh/docker-ros2-desktop-vnc#quick-start)ではなく、[Build
](https://github.com/Tiryoh/docker-ros2-desktop-vnc#build)の手順で進めていこうと思います！

**Comment by goruchanchan** [comment]
humble を使っているのでイメージのビルドはhumble で進めます

**Comment by goruchanchan** [comment]
イメージのビルドが結構かかって手持ち無沙汰なので、少し他の候補がないかも思案しようと思います！

**Comment by blacktoad30** [comment]
> [docker-ros2-desktop-vnc/LICENSE at master · Tiryoh/docker-ros2-desktop-vnc](https://github.com/Tiryoh/docker-ros2-desktop-vnc/blob/master/LICENSE)
> 
> ライセンス的にはApacheらしい

一応参考として置いておきますね
https://opensource.org/license/apache-2-0/

**Comment by goruchanchan** [comment]
ROS のRviz もよく使うのでこいつを調査します

**Comment by goruchanchan** [comment]
[ros2/rviz: ROS 3D Robot Visualizer](https://github.com/ros2/rviz)

**Comment by goruchanchan** [comment]
[rviz/LICENSE](https://github.com/ros2/rviz/blob/rolling/LICENSE)はBSD-3で
[The 3\-Clause BSD License – Open Source Initiative](https://opensource.org/license/bsd-3-clause/)と多分同じもの？微妙に表記に揺らぎがある気がします

**Comment by goruchanchan** [comment]
[Developer Guide](https://github.com/ros2/rviz#developer-guide)
RViz の開発フローに沿って開発環境整えることを進めていこうかと思います！

**Comment by goruchanchan** [comment]
rosbags をみてみようと思います！
[rosbags/LICENSE\.txt](https://github.com/rpng/rosbags/blob/master/LICENSE.txt)でライセンスは[Apache License, Version 2\.0 – Open Source Initiative](https://opensource.org/license/apache-2-0/)と一覧にあるので問題なさそうです！

**Comment by goruchanchan** [comment]
OSSかどうかパッと確かめるのは[Open Source Initiative – The steward of the Open Source Definition, setting the foundation for the Open Source Software ecosystem\.](https://opensource.org/)がベター

**Comment by goruchanchan** [comment]
上記に登場しないようなOSSの場合は、原文をきっちり読んで自分の信念（コードのオープン性に対する考え）に一致するかを判断した方がいいとのこと

**Comment by goruchanchan** [comment]
ビギナーの練習としてはビギナーのやりたいことを進めてもらって良いということでしたので、Rviz (BSD 3-Clause Clear License)で に対してフィードバックを立てていこうと思います

**Comment by blacktoad30** [comment]
> [rviz/LICENSE](https://github.com/ros2/rviz/blob/rolling/LICENSE)はBSD 3-Clause Clear Licenseで [The 3-Clause BSD License – Open Source Initiative](https://opensource.org/license/bsd-3-clause/)と多分同じもの？微妙に表記に揺らぎがある気がします

[SPDXのライセンスリスト](https://spdx.org/licenses/)曰く、BSD 3-Clause Clear Licenseは、FSF的にはOKだけど、OSIでは承認されていない

**Comment by goruchanchan** [comment]
RViz から位置情報を入力するときに２次元情報（x,y）データしか送信できない。
位置推定をさせるためには３次元情報（x,y,z）を与えたいため、送れるようにIssueを立てたい
![image](https://github.com/oss-gate/workshop/assets/90775541/3ea39bde-4e6b-457c-a129-9870f9846698)

**Comment by goruchanchan** [comment]
まずはIssueに相応のものがないかをみてみようと思います！

**Comment by goruchanchan** [comment]
並行して各項目としては一旦下記を仮置きします

# やりたいこと

# 理由

**Comment by goruchanchan** [comment]
Issue には重複した内容がないのでIssueの内容を考えてみようと思います。テンプレートのようなものは無さそうなので、上記に加え既存Issueの内容も参考にしようと思います

**Comment by goruchanchan** [comment]
# 初期位置入力でZ座標の情報を設定するようにできないか？

## やりたいこと

2D Pose Estimate ツールを用いて2D初期位置情報（x,y,θ）を入力する際に、高さ情報(z) も同期して調整できるようにしたい

## 理由

3次元データを利用する場合、高さ情報も調整しなければ初期位置の設定がうまくいかない。

## 現状

現状は0固定となっている。

![image](https://github.com/oss-gate/workshop/assets/90775541/7d9aa56b-cbc4-437d-83c6-a242cd85bae4)

**Comment by blacktoad30** [comment]
@goruchanchan どの部分をどのように改善してほしいのか、それに至る経緯がとても分かりやすいと感じます。
あとは英語に翻訳して、Issueを立てればOKだと思います。

**Comment by goruchanchan** [comment]
ちょっとだけ直しました🙇‍♂️

# 初期位置入力でZ座標の情報を設定するようにできないか？

## やりたいこと

2D Pose Estimate ツールを用いて2D初期位置情報（x,y,θ）を入力する際に、高さ情報(z) も同期して調整できるようにしたい

## 理由

3次元データを利用する場合、高さ情報も調整しなければ初期位置の設定がうまくいかない。

現状のやり方は下記になります。

1. 2情報をRviz2 で調整した値を確認
2. そのデータを `/initialpose` に反映する
3. 2. のデータの高さ(z)を調整する
4. 3.のデータを `ros2 topic pub` トピック送信する

2, 3 の作業フローが煩雑なため高さ情報を RViz2 ができるようにすることで作業性向上できないかと思っている。

もしくは効率的なやり方があれば、教えていただきたい

## 現状

現状は0固定となっている。

![image](https://github.com/oss-gate/workshop/assets/90775541/7d9aa56b-cbc4-437d-83c6-a242cd85bae4)

**Comment by goruchanchan** [comment]
再度、修正しました🙇‍♂️

# 初期位置入力でZ座標の情報を設定するようにできないか？

## やりたいこと

2D Pose Estimate ツールを用いて2D初期位置情報（x,y,θ）を入力する際に、高さ情報(z) も同期して調整できるようにしたい

## 理由

3次元データを利用する場合、高さ情報も調整しなければ初期位置の設定がうまくいかない。

現状のやり方は、`ros2 topic pub`  によって`geometry_msgs/msg/PoseWithCovarianceStamped` 型データを自身で飛ばすことで実現しています。具体的には下記になります。

1. 2情報をRviz2 で調整した値を確認
2. そのデータを `/initialpose` に調整する
3. 2.のデータの高さ(z)を調整する
4. 3.のデータを `ros2 topic pub` 送信する

2, 3 の作業フローが煩雑なため高さ情報を RViz2 ができるようにすることで作業性向上できないかと思っている。

もしくは効率的なやり方があれば、教えていただきたい

## 現状

現状は0固定となっている。

![image](https://github.com/oss-gate/workshop/assets/90775541/7d9aa56b-cbc4-437d-83c6-a242cd85bae4)

**Comment by goruchanchan** [comment]
# How to set the Z coordinate information in the initial pose?

## What I want

When using the 2D Pose Estimate tool to input 2D initial position information (x,y,θ), I would like to be able to adjust the height information (z) synchronously as well.

## Why need?

In the case of 3D position estimation, the height information must also be adjusted to set the initial position properly.

The current method is achieved by flying geometry_msgs/msg/PoseWithCovarianceStamped type data by ros2 topic pub by itself.

Specifically, it is as follows.

1. Check the value adjusted by Rviz2 for 2D position information.
2. Adjust that data to /initialpose.
3. Adjust the height (z) of [2. data].
4. Send [3. data] by ros2 topic pub.

The workflow of steps 2 and 3 is complicated, so I am wondering if RViz2 can provide height information to improve the workflow.

Or if there is an efficient way to do this, I would like to know.

## Actual Result

Currently, it is fixed at 0.

![image](https://github.com/oss-gate/workshop/assets/90775541/d28ff95d-6d59-476a-8405-d7f8f4b2dcfa)

**Comment by blacktoad30** [comment]
> もしくは効率的なやり方があれば、教えていただきたい

提案をしつつ、正しい/推奨される解決方法があるのかを確認することは、Issueの立て方としてとても良いと思います。
