### ISSUE TITLE
OSS Gate Workshop: Online: 2023-09-09: smiya: markdownlint: Work log

### ISSUE THREAD

**Issue by miyanew** [oss-gate/workshop#1654]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by miyanew** [comment]
普段使いのOSSはメジャーどころだらけでコントリビュート厳しそうなので、スクールのプラクティスで使うgemを2つまず調べてみる。

https://github.com/heartcombo/devise
https://github.com/tigrish/devise-i18n

**Comment by miyanew** [comment]
どちらのGemもコントリビュートの余地あまなりなさそうとのこと

fjordllc/bootcamp自体のGemfileからあたりをつけられないか...
[fjordllc/bootcamp: プログラマー向けEラーニングシステム](https://github.com/fjordllc/bootcamp/blob/main/Gemfile)

**Comment by miyanew** [comment]
ザッと90個くらいある。。公式サイトから一つずつあたるのはしんどいか
https://rubygems.org/

**Comment by miyanew** [comment]
ダウンロード数、コミット数、スター数に着目するといいらしいが

**Comment by miyanew** [comment]
普段使っているVSCodeの拡張機能をみてみる
[DavidAnson/vscode\-markdownlint: Markdown linting and style checking for Visual Studio Code](https://github.com/DavidAnson/vscode-markdownlint)

**Comment by miyanew** [comment]
ライセンスは大丈夫　＞ [MIT license](https://github.com/DavidAnson/vscode-markdownlint/blob/main/LICENSE)

**Comment by miyanew** [comment]
```
Install
1.Open [Visual Studio Code](https://code.visualstudio.com/)
2.Press Ctrl+P/Ctrl+P/⌘P to open the Quick Open dialog
3.Type ext install markdownlint to find the extension
4.Click the Install button, then the Enable button
```

**Comment by otegami** [comment]
> 一旦アンインストールして以下を実施する

まっさらな状態からインストールしてみるの、いいですね！

**Comment by miyanew** [comment]
インストールは問題なくできた。使い方をみていく...

**Comment by miyanew** [comment]
Use、Rulesは問題なさそう、Commands以降はどうだろ。。

**Comment by miyanew** [comment]
なんで、コマンド例が3つある。（3つが対応するのはなに）

**Comment by miyanew** [comment]
Installのところ、3つ目はWindows限定なのでは

**Comment by miyanew** [comment]
つまづいたところをまずは挙げていく。ドキュメント不備なのでは〜という観点で

**Comment by miyanew** [comment]
サッと読んで飲み込めないところを書いてみる　＞ Fix機能のところ

**Comment by miyanew** [comment]
コマンドパレットを開く方法　→　リンク先マニュアルに記載ある
　項目どこ　→　元のマニュアルの方に editor.XXX がある
　項目のチェックボックスにONする　（True相当）
どうやったら自動Fixが発動するのか？

**Comment by miyanew** [comment]
PROBREMターミナル
MD文法ではない観点で警告がでてるようにみえる

**Comment by miyanew** [comment]
普段使ってない機能だっとしても、ワークショップでREADMEを上から順に読んでみることで気づくこともある

**Comment by piroor** [comment]
https://github.com/DavidAnson/vscode-markdownlint#install の最後の「command-line」のやり方がmacOSで動かなかった、というのはフィードバックポイントになりうる気がしますね！

**Comment by miyanew** [comment]
Githubをみてみる
[Issues · DavidAnson/vscode\-markdownlint](https://github.com/DavidAnson/vscode-markdownlint/issues?utm_source=vsmp&utm_medium=ms%20web&utm_campaign=mpdetails)

**Comment by miyanew** [comment]
[vscode\-markdownlint/CONTRIBUTING\.md at main · DavidAnson/vscode\-markdownlint](https://github.com/DavidAnson/vscode-markdownlint/blob/main/CONTRIBUTING.md)

**Comment by miyanew** [comment]
書いてあることだけやっていいという解釈だとやれることが少ないので、
書いてないことは試みてみる。（禁じられてなければ）でいいんでは...

**Comment by miyanew** [comment]
イシューのたてかたの例（開発元はドキュメントへの貢献を想定してない可能性もある）
「document: ～～に書かれているやり方がmacOSで動作しない」

**Comment by miyanew** [comment]
イシューはつまづきポイントだけでいい（修正案まではいらない）

**Comment by miyanew** [comment]
document: The third Install method mentioned in the Overview does not work on macOS.

**Comment by miyanew** [comment]
#再現手順　steps to reproduce
macOSで起動させたVSCodeのターミナルから3つ目のInstall方法を実施する
```
1. Open a command-line prompt
2. Run code --install-extension DavidAnson.vscode-markdownlint

```

**Comment by miyanew** [comment]
#実際結果　actual result
```
 % code --install-extension DevidAnson.vscode-markdownlint
Installing extensions...
Extension 'devidanson.vscode-markdownlint' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: devidanson.vscode-markdownlint
```

**Comment by miyanew** [comment]
VSCodeの設定箇所。。
markdownlintに閉じてない箇所を触ってるようにみえるのが問題ないのか
　設定系のつまづき、更新すべき箇所が思っている箇所と違っていた、というのはよくあるからフィードバックしていいのでは

**Comment by miyanew** [comment]
# タイトル
"[markdown]": の設定の仕方がわかりづらい

document: Difficult to understand how to set "[markdown]".

**Comment by miyanew** [comment]
提案の仕方
　×　＊＊ができない　　Actual Resultに寄せる
　○　＊＊であるべき　　Exepected

**Comment by miyanew** [comment]
Fixの機能を設定しようとした時に以下のリンク先ページから対象箇所を探すのに時間を要した

```
, [configure Visual Studio Code's editor.formatOnSave or editor.formatOnPaste settings](https://code.visualstudio.com/docs/getstarted/settings) like so:

"[markdown]": {
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true
},
```
