### ISSUE TITLE
OSS Gateワークショップ 2016-11-26:cm-wada-yusuke:playframework: 作業ログ

### ISSUE THREAD

**Issue by cm-wada-yusuke** [oss-gate/workshop#166]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by cm-wada-yusuke** [comment]
ドキュメントのページは見たことあったが、

* Play Framework - Build Modern & Scalable Web Apps with Java and Scala https://www.playframework.com/

GitHubページのほうはほとんどみたことがなかったためまずはこちらから見てみることにする↓

* playframework/playframework: Play Framework https://github.com/playframework/playframework

**Comment by cm-wada-yusuke** [comment]
メンターの方に「Playはドキュメントがいまいちだからそこをつくとよいかも」というアドバイスをもらったのでそこをつく方向にするか？

**Comment by cm-wada-yusuke** [comment]
GitHubページからPlay Contributor guidlineなるもののがあった…ここは見ておいたほうが良い？あとで読むか

* Contributing https://www.playframework.com/contributing

**Comment by cm-wada-yusuke** [comment]
今日要るのはBuild from sourceなのでここをみる。

* BuildingFromSource - 2.5.x https://www.playframework.com/documentation/2.5.x/BuildingFromSource

**Comment by cm-wada-yusuke** [comment]
ガイドライン読んでないので命名規則とかわからないけどとりあえず `git checkout -b feature/2.5.x origin/2.5.x` でローカルブランチ作成した。

**Comment by cm-wada-yusuke** [comment]
> This will build and publish Play for the default Scala version (currently 2.11.7). If you 

ってあるけどこれScalaのデフォルトバージョンあってる？

**Comment by cm-wada-yusuke** [comment]
`sbt publishLocal` で終わったっぽいけど一瞬で終わった　大丈夫なのかこれ

**Comment by cm-wada-yusuke** [comment]
やっぱり違った。`framework` ディレクトリに入らないといけないっぽい

**Comment by cm-wada-yusuke** [comment]
sbt実行。ライブラリのダウンロードが始まった。

いくつかMiisingっていう文字列が気になったけど無事に終わってるぽい

```
Missing bintray credentials /Users/wada.yusuke/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /Users/wada.yusuke/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /Users/wada.yusuke/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /Users/wada.yusuke/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to Play-Framework (in build file:/Users/wada.yusuke/Documents/playframework/framework/)
```

**Comment by cm-wada-yusuke** [comment]
publishLocalでかなりのwarningがでるが大丈夫か？

**Comment by cm-wada-yusuke** [comment]
playframework のGitHubページでBuild from sourceを押したときの遷移先が、僕は2.5.xのページ、メンターの方は2.4.xのページだった。リンク自体はパスの部分が`latest`になっており、どうやらクッキーの値でここを置き換えているようだ。

**Comment by cm-wada-yusuke** [comment]
日本だと日本語のドキュメントに誘導されるがそれが2.4.xまでしかなくて2.4.xに飛んでいる様子。

**Comment by cm-wada-yusuke** [comment]
この間にビルドが完了した。`warning`が大量に出たけれどもエラーは出ていない。

**Comment by cm-wada-yusuke** [comment]
手順に従って次はドキュメントを生成する。

**Comment by cm-wada-yusuke** [comment]
プルリクを出すときはすべてのバージョンのScalaでテストしてみるのが良いようだ。

> The scripts that are run by the PR validation can be found in the framework/bin directory, you can run each of these to run the same tests that the PR validation runs.

**Comment by cm-wada-yusuke** [comment]
documentのディレクトリでsbt実行したらサーバーが立ち上がった…公式サイトのドキュメントはこうやって生成しているのか

**Comment by cm-wada-yusuke** [comment]
みえた

Home http://localhost:9000/@documentation/Home

**Comment by cm-wada-yusuke** [comment]
playframeworkは、本体のリポジトリにソースコードとドキュメントが両方含まれている。

playframwork
 - framework
 - document

**Comment by cm-wada-yusuke** [comment]
>// Change the sbt plugin to use the local Play build (2.5.0-SNAPSHOT)
> addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.0-SNAPSHOT")

使うためには、別のプロジェクトから読み込まないといけないらしい。それはその通りか。
ドキュメントのあら捜しかソースコードのwarning除去かをやりたいと思っている。

**Comment by cm-wada-yusuke** [comment]
テストを動かしてみよう。

**Comment by cm-wada-yusuke** [comment]
これ一人でやってもつまんなかったと思う

**Comment by cm-wada-yusuke** [comment]
テストもwarining出てる

**Comment by cm-wada-yusuke** [comment]
teeでファイル出力すればよかった

**Comment by cm-wada-yusuke** [comment]
テストでエラーでた

**Comment by cm-wada-yusuke** [comment]
午後からの方針

1. ドキュメントのあら捜し
1. frameworkのビルド時のwarning
1. testのwarning
1. test時のerror

Q. ドキュメントのあら捜しはどう行うか？
A. バージョン情報が正しいかどうかの観点で探そうと思います

**Comment by cm-wada-yusuke** [comment]
ドキュメントで気になったのは、Scalaのバージョン。

[BuildingFromSource \- 2\.5\.x](https://www.playframework.com/documentation/2.5.x/BuildingFromSource#Building-Play-from-source)
のGrab the sourceに、`2.11.7`という記載があったが、これが正しいかどうか。

**Comment by cm-wada-yusuke** [comment]
SBTプロジェクトのセオリー通りbuild.sbtを見てみた。ここに`scalaVersion`っていう変数があって、どうやらこれでScalaのバージョンを指定しているらしい。この変数、どこで定義されているんだ。

**Comment by cm-wada-yusuke** [comment]
1. ドキュメントのあら捜し => 英語での説明が大変そうなので後回し
1. frameworkのビルド時のwarning => まずはこれを狙う
1. testのwarning => そもそもerrorが出てるのでやりにくそう
1. test時のerror => ハマると時間なくなりそう

frameworkのビルド時のwarningをひとつ解消する方向でいきます

**Comment by cm-wada-yusuke** [comment]
`pwd`
`/Users/wada.yusuke/Documents/playframework/framework`
`sbt | tee out`
`publishLocal`

**Comment by pocke** [comment]
RuboCop ではこんな感じでwarning を直すPRがこの間きていました https://github.com/bbatsov/rubocop/pull/3698

**Comment by cm-wada-yusuke** [comment]
どういうwainingが出るかウォッチすると…

* scalariformフォーマットに合ってない
* Deprecatedなクラスやメソッドを使っている

**Comment by cm-wada-yusuke** [comment]
コミットごとにどんなタイプのwarningを解消しているか分けるスタイル

**Comment by cm-wada-yusuke** [comment]
* ブートストラップ・クラスパスが-source 1.6と一緒に設定されていません <-これは謎
* /Users/wada.yusuke/Documents/playframework/framework/src/play-streams/src/main/scala/play/api/libs/streams/Probes.scala:81: class PushPullStage in package stage is deprecated: Please use GraphStage instead. <- この通りにやって解消されたらラッキーか
* non-variable type argument String in <- 型消去されてるという警告。フレームワークレベルでもこの警告が出るコード書いてるんだ…

**Comment by cm-wada-yusuke** [comment]
* inferred existential type (Class[_$1], play.api.mvc.PathBindable[T]) forSome { type _$1 }, which cannot be expressed by wildcards,  should be enabled <- match式ワイルドカード部分での警告っぽいけれども詳しいことはわからない

**Comment by cm-wada-yusuke** [comment]
型消去の警告を解消します。

**Comment by cm-wada-yusuke** [comment]
Intellijで編集できるようにしたい

**Comment by cm-wada-yusuke** [comment]
Intellijで`framework`を読み込んでみる

**Comment by cm-wada-yusuke** [comment]
コントリビューションガイドライン読むか？

**Comment by cm-wada-yusuke** [comment]
* Contributing https://www.playframework.com/contributing

**Comment by cm-wada-yusuke** [comment]
簡単にピックアップ：

* 軽微なバグ修正程度だったらいきなりPR投げて良い。確認がもてなかったらmailing listに聞いて。
* DRY原則を犯すな
* ボーイスカウトルールに従え

あとはPlayの設計思想の話なので軽微なバグ修正では気にしなくて良さそうか。

**Comment by cm-wada-yusuke** [comment]
* Make sure you have signed the Lightbend CLA; if not, sign it online.

これやらなきゃいけない？

**Comment by cm-wada-yusuke** [comment]
オンラインでconfimしたら大丈夫そうだ。

**Comment by cm-wada-yusuke** [comment]
Intellijで修正をします

**Comment by cm-wada-yusuke** [comment]
`grep "eliminated by erasure" out`
```
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/play/api/data/Form.scala:240: non-variable type argument String in type pattern Seq[String] (the underlying of Seq[String]) is unchecked since it is eliminated by erasure
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala:172: non-variable type argument String in type pattern java.util.Map[String,AnyRef] is unchecked since it is eliminated by erasure
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala:183: non-variable type argument String in type pattern java.util.Map[String,AnyRef] is unchecked since it is eliminated by erasure
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/play/core/parsers/Multipart.scala:80: non-variable type argument Nothing in type pattern play.api.mvc.MultipartFormData.Part[Nothing] is unchecked since it is eliminated by erasure
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/views/helper/Helpers.scala:56: non-variable type argument String in type pattern Seq[String] (the underlying of Seq[String]) is unchecked since it is eliminated by erasure
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/views/helper/select.scala.html:38: non-variable type argument String in type pattern Seq[String] (the underlying of Seq[String]) is unchecked since it is eliminated by erasure
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala:81: non-variable type argument play.mvc.Result in type pattern java.util.concurrent.CompletionStage[play.mvc.Result] is unchecked since it is eliminated by erasure
```

**Comment by cm-wada-yusuke** [comment]
方法は2つ

* @uncheckedをつける
* 基本型のみチェックしてSrringとしてインスタンス化

**Comment by cm-wada-yusuke** [comment]
@unckeckedで警告が消えるかどうか確認

**Comment by cm-wada-yusuke** [comment]
Map[S,T]の場合：

* Map[S@unchecked,T@unchecked] とするべきか
* Map[S,T@unchecked] でいいのか

が不明。いったん両方やってみて警告が消えるかどうかためす。

**Comment by cm-wada-yusuke** [comment]
両方につけないと消えない

**Comment by cm-wada-yusuke** [comment]
grepで抽出した箇所すべてに同じ修正を施した。
コンパイルした。

コンパイルエラーになった。Map[]が怪しいのでひとまずその修正をなかったことにする。

**Comment by cm-wada-yusuke** [comment]
# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you [squashed your commits]? (Optional, but makes merge messages nicer.)
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

**Comment by cm-wada-yusuke** [comment]
## Fixes

match式の型消去箇所に@uncheckedアノテーションを追加しました。

## Purpose

match式にて型消去が発生していることによる警告を解消するためです。

## Background Context

型消去の警告を解消する場合、@uncheckedを付与するか、型パラメータに対応したコレクションの型を新しく作るかという手法が考えられますが、既存コードへの影響を最小化するためにアノテーションを付与する修正としました。

## References

特になし。

**Comment by cm-wada-yusuke** [comment]
## Fixes

I added @unchecked annotation to match type trail.

## Purpose

To resolve warning caused by type erasure in match expression.
This warning occurred at compile.

```
[warn] /Users/wada.yusuke/Documents/playframework/framework/src/play/src/main/scala/play/api/data/Form.scala:240: non-variable type argument String in type pattern Seq[String] (the underlying of Seq[String]) is unchecked since it is eliminated by erasure
```


## Background Context

To solve type wiping warnings, it is possible to assign `@ unchecked` or create a new collection type corresponding to type parameters, but in order to minimize the influence on existing code, I 


## References

* Type Erasure (The Java™ Tutorials > Learning the Java Language > Generics (Updated)) https://docs.oracle.com/javase/tutorial/java/generics/erasure.html

**Comment by pocke** [comment]
> but only warning of type erasure

but only **the** warnings の方がよいかも?

**Comment by cm-wada-yusuke** [comment]
PR送信Done！

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-28に開催](https://oss-gate.doorkeeper.jp/events/52881)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
