### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: peno: videospeed: Work log

### ISSUE THREAD

**Issue by peno022** [oss-gate/workshop#1665]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by peno022** [comment]
Chrome拡張から候補を探してみる
- GoFullPage
- ColorZilla

**Comment by peno022** [comment]
- https://github.com/igrigorik/videospeed

**Comment by peno022** [comment]
↑これはMITライセンスだったのでOK。これのREADMEをなぞることにする。
```
(MIT License) - Copyright (c) 2014 Ilya Grigorik
```

**Comment by peno022** [comment]
Chrome拡張のインストールはすでにしてあって、Chrome Webストアでボタン押すだけで完了した記憶・・ひとまずストアでのインストールは終わってる段階からスタートする。
https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk

**Comment by peno022** [comment]
** Once the extension is installed simply navigate to any page that offers HTML5 video ([example](http://www.youtube.com/watch?v=E9FxNzv1Tr8)), and you'll see a speed indicator in top left corner. Hover over the indicator to reveal the controls to accelerate, slowdown, and quickly rewind or advance the video.

→OK。indicatorが出てきた。

![スクリーンショット 2023-09-30 12 00 38](https://github.com/oss-gate/workshop/assets/40317050/05865771-59ee-4fe0-89e9-7b4d5090e586)

**Comment by peno022** [comment]
Or, even better, simply use your keyboard:

S - decrease playback speed.
D - increase playback speed.
R - reset playback speed to 1.0x.
Z - rewind video by 10 seconds.
X - advance video by 10 seconds.
G - toggle between current and user configurable preferred speed.
V - show/hide the controller.

→全部効いた。OK。

**Comment by peno022** [comment]
You can customize and reassign the default shortcut keys in the extensions settings page as well as add additional shortcut keys to match your preferences. As an example, you can assign multiple "preferred speed" shortcuts with different values, allowing you to quickly toggle between your most frequently used speeds. To add a new shortcut, open extension settings and click "Add New".

→`in the extensions settings`ってどこだ？と少し探した。Chrome拡張の文脈だと常識なのかな？
拡張機能のアイコンを右クリックすると表示されるメニューの「オプション」から開けた。

![スクリーンショット 2023-09-30 12 14 56](https://github.com/oss-gate/workshop/assets/40317050/df8edfca-1db3-4aa5-9ee2-49d95326464b)

**Comment by peno022** [comment]
![image](https://github.com/oss-gate/workshop/assets/40317050/7849a64c-6d0e-41d9-86ab-63b6ca17b324)

→オプションの編集ができた。ただし、動画再生中の画面を更新しないと設定は反映された状態にならない。

**Comment by peno022** [comment]
contributing.mdがあった。forkしてPR出してね、という感じ。
https://github.com/igrigorik/videospeed/blob/master/CONTRIBUTING.md

**Comment by peno022** [comment]
過去にマージされている、ドキュメントのちょっとした修正のPRを参照。
https://github.com/igrigorik/videospeed/pull/890

**Comment by peno022** [comment]
ブランチ名のルールは特にないのかな？ `minor-doc-update `くらいでいいかしら。

- jordan-christensen:doc-fixes
- muescha:patch-1

**Comment by peno022** [comment]
PRを出した: https://github.com/igrigorik/videospeed/pull/1062

**Comment by komagata** [comment]
@peno022 PRから2週間も経っているので、igrigorik さんにメンションでこちらどうですか？みたいな感じで聞いていいかもです〜。

**Comment by peno022** [comment]
@komagata 
Discordだけで返信してしまっていたので、遅れましたがこちらでも🙇‍♀️
昨日PRに、確認してもらえると嬉しいですという旨のコメントを追加してきました！

**Comment by komagata** [comment]
@peno022 おお、素晴らしいです〜！
