### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: asya81: prk_firmware: Work log

### ISSUE THREAD

**Issue by asya81** [oss-gate/workshop#1667]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by asya81** [comment]
作業メモできた〜！

**Comment by asya81** [comment]
まだ触り始めたばかりだけれど、prkfirmwareを対象にしてみたい。

**Comment by asya81** [comment]
GitHubリポジトリー: https://github.com/picoruby/prk_firmware
公式webサイト: https://github.com/picoruby/prk_firmware/wiki/Tutorial

**Comment by asya81** [comment]
GitHubリポジトリーをみると、ライセンスは`MIT License`らしい

**Comment by asya81** [comment]
このライセンスは https://opensource.org/licenses/ にあるのでprkfirmwareはOSSだと思います。
今日はこちらを触ってみます！

**Comment by asya81** [comment]
こちら https://github.com/picoruby/prk_firmware/wiki/Tutorial に沿って、ドキュメントを読みながらやっていってみる。

**Comment by asya81** [comment]
> First of all, you should learn how to install a UF2 file into Raspberry Pi Pico by reading a section "3.2.1. From the desktop" (page 10) of this document:

初心者(私)は`UF2  file`のところでなんだそれ？ってなるけど、その先を読み進めてみる

**Comment by asya81** [comment]
以下が`"3.2.1. From the desktop" (page 10) `の部分
<img width="683" alt="image" src="https://github.com/oss-gate/workshop/assets/51506307/187578f7-3c62-4ac9-9a9b-d0c7fca5b99c">

**Comment by asya81** [comment]
日本語に翻訳した結果
> ラズベリーパイデスクトップを実行している場合、ラズベリーパイピコは自動的にUSB大容量ストレージとしてマウントされます
デバイス。ここから、blink.uf2を大容量記憶装置にドラッグアンドドロップできます。
RP2040が再起動し、大容量記憶装置としてアンマウントされ、フラッシュされたコードの実行が開始されます(図1を参照)。

**Comment by asya81** [comment]
UF2ファイルが分からなかったので、ChatGPTに聞いてみた。

> Raspberry Pi Picoは、Raspberry Pi Foundationによって開発されたマイクロコントローラーボードです。このボードは、主に組み込みシステムや教育用途で使用されます。UF2ファイルは、Raspberry Pi Picoでプログラムをロードするためのファイル形式です。
> 
> [UF2ファイルについて](https://gist.github.com/machida/50283503503ef4481388980f9f3e183b#uf2%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
> UF2（USB Flashing Format）は、マイクロコントローラーにファームウェアを転送するためのファイル形式です。この形式は、Microsoftによって開発され、Raspberry Pi Picoのようなデバイスで広く使用されています。UF2ファイルは、ドラッグアンドドロップでデバイスに転送できるので、使用が非常に簡単です。
> 
> [Raspberry Pi PicoでのUF2ファイルの使用方法](https://gist.github.com/machida/50283503503ef4481388980f9f3e183b#raspberry-pi-pico%E3%81%A7%E3%81%AEuf2%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> UF2ファイルのダウンロード プログラムを開発するためのUF2ファイルをダウンロードします。例えば、MicroPythonやCircuitPythonのUF2ファイルがあります。
> 
> Raspberry Pi Picoをブートローダーモードで起動 Raspberry Pi PicoをPCに接続する前に、BOOTSELボタンを押し続けます。そのままUSBケーブルでPCに接続します。
> 
> ドラッグアンドドロップで転送 Raspberry Pi Picoがブートローダーモードで起動すると、PC上で新しいドライブとして認識されます。UF2ファイルをこのドライブにドラッグアンドドロップすることで、ファームウェアがPicoに転送されます。
> 
> 再起動 UF2ファイルの転送が完了すると、Raspberry Pi Picoは自動的に再起動します。これで、新しいファームウェアがロードされ、使用する準備が整います。
> 
> [注意点](https://gist.github.com/machida/50283503503ef4481388980f9f3e183b#%E6%B3%A8%E6%84%8F%E7%82%B9)
> Raspberry Pi Picoに適したUF2ファイルを使用してください。間違ったファイルを使用すると、デバイスが正常に動作しなくなる可能性があります。
> UF2ファイルの転送中にPicoからUSBケーブルを抜かないでください。データの損失やデバイスの損傷の原因となる可能性があります。

**Comment by asya81** [comment]
初心者向けには、`UF2(USB Flashing Format)`と説明があると分かりやすいかもしれない。

**Comment by asya81** [comment]
`"3.2.1. From the desktop" (page 10) `の説明だけではBOOTSELボタンを押す説明がないので、`3.2`も読む必要があるかも。

**Comment by asya81** [comment]
チュートリアルは日本語のサイトもあったので、こちらを確認した方が良いかも。
https://github.com/picoruby/prk_firmware/wiki/Tutorial_ja

**Comment by asya81** [comment]
`Raspberry Pi Pico`や`Sparkfun Pro Micro RP2040`のマイコンボードの名前が出てきているけれど、他のマイコンボードも使えるような気がするので、何が使えるのか？は知りたい気がする。

**Comment by asya81** [comment]
最新のリリースバイナリをダウンロードしてみる。
[prk_firmware-MSC_FLASH-0.9.22-20230904-568e003.uf2.zip](https://github.com/picoruby/prk_firmware/releases/download/0.9.22/prk_firmware-MSC_FLASH-0.9.22-20230904-568e003.uf2.zip)
![image](https://github.com/oss-gate/workshop/assets/51506307/e4c6b587-b575-44b3-9e72-08e8b09304c9)

**Comment by asya81** [comment]
今回は初回の設定は実施済みのため、2回目以降の[PRK Firmware のアップグレード](https://github.com/picoruby/prk_firmware/wiki/Tutorial_ja#prk-firmware-%E3%81%AE%E3%82%A2%E3%83%83%E3%83%97%E3%82%B0%E3%83%AC%E3%83%BC%E3%83%89)を試してみる。

**Comment by asya81** [comment]
今のバージョンはどこで確認できるのだろう？と思ったら、`PRK DRIVE`の中にある`README.txt`に記載があった。
> PRK Firmware 0.9.21 (20230523 revision 405c8e6)

最新版は`0.9.22`なのでアップグレードできそう

**Comment by asya81** [comment]
念のため、keymap.rbとREADMEを別のディレクトリにバックアップしておく。

**Comment by asya81** [comment]
BOOTSELモードに入るにはいくつかのパターンがある
https://github.com/picoruby/prk_firmware/wiki/BOOTSEL-mode-of-RP2040

今回はシンプルにBOOTSELボタンを押しながらキーボードを接続する。

**Comment by asya81** [comment]
と思ったけれど、BOOTSELボタンを押すには、一旦分解しないといけなさそう。
リセットボタンでやった方が良いかも。リセットボタンはどこだ？
https://github.com/swanmatch/keeb_rubykaigi2023

**Comment by asya81** [comment]
うーん、これやっているとお時間かかりそうなので、一旦ドキュメントの方でできることを整理してみる

**Comment by asya81** [comment]
- チュートリアルの最初にRaspberry Pi PicoとSparkfun Pro Micro RP2040の例があるが他のマイコンボードの例がないで、他にも使えるマイコンボードやキーボードが知りたい。
- RubyKaigiノベルティのキーボードが載っていないので、追加したい。

**Comment by asya81** [comment]
上げるとしたら、別々のPRで上げた方が良さそう。

**Comment by asya81** [comment]
https://github.com/picoruby/prk_firmware-wiki
こちらをクローンしてPR上げると良さそう。

**Comment by asya81** [comment]
他の方のPRを参考にやってみる。
- Issueは0件なのでIssue化はしなくて良さそう。
- ブランチの命名ルールも特になさそうなので、適切なブランチ名で作成してみる。

**Comment by komagata** [comment]
@asya81 こちらその後いかがでしょうか〜？
僕でもよろしければIssue/PR文章のサポートなどもさせていただきます〜！

**Comment by asya81** [comment]
> @asya81 こちらその後いかがでしょうか〜？
> 
> 僕でもよろしければIssue/PR文章のサポートなどもさせていただきます〜！

ありがとうございます〜😊
こちら現在PR案を作成中です。出来上がったらレビューいただけると嬉しいです。

よろしくお願いします🙌

**Comment by asya81** [comment]
prk_firmwareのwikiへのコントリビュート方法について、以下のREADMEに記載があった。
https://github.com/picoruby/prk_firmware/wiki/README

> If you want to add a new description or found a TYPO in wiki pages of picoruby/prk_firmware, do not hesitate to send a pull request to [picoruby/prk_firmware-wiki](https://github.com/picoruby/prk_firmware-wiki).

wikiに追加したいページやtypoを見つけたらお気軽にPR送ってね、ということのようなので
直接PRを送って問題なさそう。

**Comment by asya81** [comment]
まずは日本語でPRに記載するコメント案を考えてみる。

### PRのコメント案
自作キーボードを始めたばかりの初心者です。
prk_firmwareのおかげでRubyなキーボードを作ることができて、 とても嬉しいです。
最高にクールなファームウェアを作ってくださって、ありがとうございます！

[チュートリアル](https://github.com/picoruby/prk_firmware/wiki/Tutorial)の最初に`Raspberry Pi Pico`や`Sparkfun Pro Micro RP2040`のマイコンボードの説明がありますが、
その他に使えるマイコンボードがあるか？やどんなキーボードに使えるのか？が気になりました。

既にWikiに[Microcontroller boards and Keyboards](https://github.com/picoruby/prk_firmware/wiki/Microcontroller-boards-and-Keyboards)が用意されていることを発見しましたが、
このチュートリアルからリンクされているとより分かりやすいと思いましたのでPRを上げました。
ご検討いただけると嬉しいです。よろしくお願いします。

**Comment by asya81** [comment]
## Wikiの修正案

チュートリアルは英語と日本語両方あるので、それぞれに追加する文言を考える。

### 英語版 [Tutorial · picoruby/prk\_firmware Wiki](https://github.com/picoruby/prk_firmware/wiki/Tutorial)
![image](https://github.com/oss-gate/workshop/assets/51506307/13e4c477-b54f-4820-8772-855959d3819b)

追加する文言
`See [[Microcontroller-boards-and-Keyboards]] for other available microcontroller boards and keyboards.`

### 日本語版 [Tutorial\_ja · picoruby/prk\_firmware Wiki](https://github.com/picoruby/prk_firmware/wiki/Tutorial_ja)
![image](https://github.com/oss-gate/workshop/assets/51506307/7745defb-4778-4053-958f-4f0e638167ee)

追加する文言
`その他、利用可能なマイコンボードやキーボードは [[Microcontroller-boards-and-Keyboards]] を参照してください。`

**Comment by asya81** [comment]
@komagata 
PRのコメント案とwikiの修正案を記載してみました。
文章として分かりにくい箇所等がないかご確認いただき、アドバイスいただけると嬉しいです。
よろしくお願いします〜 🙏

**Comment by asya81** [comment]
PRのコメント案を英語に訳してみる。

> 自作キーボードを始めたばかりの初心者です。
> prk_firmwareのおかげでRubyなキーボードを作ることができて、 とても嬉しいです。
> 最高にクールなファームウェアを作ってくださって、ありがとうございます！
> 
> [チュートリアル](https://github.com/picoruby/prk_firmware/wiki/Tutorial)の最初にRaspberry Pi PicoやSparkfun Pro Micro RP2040のマイコンボードの説明がありますが、
> その他に使えるマイコンボードがあるか？やどんなキーボードに使えるのか？が気になりました。
> 
> 既にWikiに[Microcontroller boards and Keyboards](https://github.com/picoruby/prk_firmware/wiki/Microcontroller-boards-and-Keyboards)が用意されていることを発見しましたが、
> このチュートリアルからリンクされているとより分かりやすいと思いましたのでPRを上げました。
> ご検討いただけると嬉しいです。よろしくお願いします。

I'm a newbie to `DIY keyboard`, and I'm very grateful that prk_firmware has helped me to build my own `Ruby keyboard`.
Thank you so much for creating the coolest firmware ever!!

Now, at the beginning of the [Tutorial](https://github.com/picoruby/prk_firmware/wiki/Tutorial), I see `Raspberry Pi Pico` and `Sparkfun Pro Micro RP2040`, but I wondered what other microcontroller boards can I use?  or what kind of keyboards can I use?

I found that [Microcontroller boards and Keyboards](https://github.com/picoruby/prk_firmware/wiki/Microcontroller-boards-and-Keyboards) is already available on the Wiki, but I thought it would be easier to understand if it was linked from the Tutorial, so I raised a PR. I hope you will consider it.

**Comment by komagata** [comment]
@asya81 PRの文章、いい感じだと思います〜！

**Comment by asya81** [comment]
@komagata ご確認いただき、ありがとうございます〜🙏
ではこれでPR上げてみようと思います😊

**Comment by asya81** [comment]
以下のPRを上げることができました 🎉 
https://github.com/picoruby/prk_firmware-wiki/pull/15

@machida さん、 @komagata さん、サポートしていただき、ありがとうございました！
