### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: sadanora: Konva: Work log

### ISSUE THREAD

**Issue by sadanora** [oss-gate/workshop#1668]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sadanora** [comment]
自作サービスで使ったライブラリに、何かコントリビュートできることがあればしたい
GitHubリポジトリ: https://github.com/konvajs/konva
公式Webサイト: https://konvajs.org/

現状思い当たる不具合とかがあるわけではないので、難しい...?

**Comment by sadanora** [comment]
MITライセンスのようなので、ライセンス的にはよさそう
https://github.com/konvajs/konva/blob/master/LICENSE

**Comment by sadanora** [comment]
The MIT License: https://opensource.org/license/mit/

**Comment by sadanora** [comment]
- コントリビューション対象の探し方
  - 普段使っているツールでも改めてReadmeに従ってインストールしてみてその通り動くか試す
  - 進んでないIssueとかの不具合が自分の環境で再現するか試して報告する
  - デモがうまく動いていないとかも不具合報告になる
  - etc...

**Comment by sadanora** [comment]
上記の観点で、何かKonvaに対してできることがありそうか探してみます。

**Comment by blacktoad30** [comment]
私見ですが、APIドキュメントのフォントサイズが結構小さいと感じました。

**Comment by sadanora** [comment]
- READMEと公式サイトで読み込むスクリプトのバージョンの指定が違っている
- READMEを`@9`に更新すればよさそう？

README: https://github.com/konvajs/konva#load-konva-via-classical-script-tag-from-cdn
> Load Konva via classical <script> tag from CDN:
> `<script src="https://unpkg.com/konva@8/konva.min.js"></script>`

公式サイト: https://konvajs.org/docs/index.html
> Or just use script tag:
> `<script src="https://unpkg.com/konva@9/konva.min.js"></script>`

**Comment by sadanora** [comment]
特別な理由がなければ、指定するバージョンは揃っている方が誤解がなくて良いと思うので報告したい。

**Comment by sadanora** [comment]
報告方法:
README、公式サイトをみたところ特に報告方法の指定はなさそう

Discord: https://discord.gg/8FqZwVT
ドキュメントを参照しても解決しない質問はStackOverflowにして欲しいとあるが、バグレポートなどに関しての記載は見当たらない。

> Do you have a question?
First, take a look into docs and tutorials  https://konvajs.org/ and try to google your question!
>
>No luck? Please use StackOverflow for questions! Just use the tag konvajs (and other related tags). https://stackoverflow.com/questions/tagged/konvajs

**Comment by sadanora** [comment]
普通にissueから報告で良さそう。
https://github.com/konvajs/konva/issues/new

**Comment by blacktoad30** [comment]
今回はプログラムのバグではないので、報告する内容を書くというので良さそうですね。

**Comment by sadanora** [comment]
### 報告テキスト案

こんにちは

素敵なライブラリの提供をありがとう。

CDNからスクリプトを読み込む場合のインストール手順で、READMEと公式ウェブサイトのバージョンが違っていたので報告します。

README: https://github.com/konvajs/konva#load-konva-via-classical-script-tag-from-cdn

>Load Konva via classical <script> tag from CDN:
```<script src="https://unpkg.com/konva@8/konva.min.js"></script>```

公式サイト: https://konvajs.org/docs/index.html

>Or just use script tag:
```<script src="https://unpkg.com/konva@9/konva.min.js"></script>```

特別な理由がなければ、READMEの方を`@9`に合わせた方が良いと思いました。

**Comment by sadanora** [comment]
より簡潔に言うなら、以下でもいいかも？

CDNからスクリプトを読み込む場合のインストール手順で、READMEと公式ウェブサイトのバージョンが違っていました。

**Comment by sadanora** [comment]
一文字の変更なので、サポーターさんにみていただきつつPRを立てることにしました。

1. 本家からフォーク
2. フォークしたリポジトリでReadmeを修正
3. upstreamにPRを送る
 
と言う流れで作業します。

**Comment by sadanora** [comment]
### PRのテキスト案

- タイトル
chore: Change CDN URL in README

```
こんにちは

素敵なライブラリの提供をありがとう。

CDNからスクリプトを読み込む場合のインストール手順で、READMEと公式ウェブサイトのバージョンが違っていました。

README: https://github.com/konvajs/konva#load-konva-via-classical-script-tag-from-cdn

Load Konva via classical <script> tag from CDN:
<script src="https://unpkg.com/konva@8/konva.min.js"></script>

公式サイト: https://konvajs.org/docs/index.html

Or just use script tag:
<script src="https://unpkg.com/konva@9/konva.min.js"></script>

READMEを`@9`に修正したので、問題なければマージしてください。
```

**Comment by blacktoad30** [comment]
タイトルのchoreとはどういう意味になりますか?

**Comment by sadanora** [comment]
ありがとうございます。
> Change CDN URL in README

に変更します。

**Comment by sadanora** [comment]
コミットメッセージを修正しました。

https://github.com/sadanora/konva/commit/2ea2c4b63e2a1a3daee99ff2cb738da444c27e7d

**Comment by sadanora** [comment]
英訳をかけ、プルリクエストを作成しました。

https://github.com/konvajs/konva/pull/1646
