### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: siroemk: vscode-rainbow-end: Work log

### ISSUE THREAD

**Issue by siroemk** [oss-gate/workshop#1670]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by siroemk** [comment]
作業メモ作成しました

**Comment by siroemk** [comment]
最近VS codeに入れたので候補
- Slim
https://marketplace.visualstudio.com/items?itemName=sianglim.slim

**Comment by siroemk** [comment]
使っていないけど面白そうな拡張機能なのでこれで調べてみる
- vscode-rainbow-end
https://marketplace.visualstudio.com/items?itemName=jduponchelle.rainbow-end
https://github.com/julien-duponchelle/vscode-rainbow-end

**Comment by siroemk** [comment]
ライセンスは問題なさそう
> [Apache-2.0 license](https://github.com/julien-duponchelle/vscode-rainbow-end/blob/master/LICENCE)

**Comment by siroemk** [comment]
ドキュメントを探す

**Comment by siroemk** [comment]
README
https://github.com/julien-duponchelle/vscode-rainbow-end

**Comment by siroemk** [comment]
READMEの画像がリンク切れっぽい
https://github.com/julien-duponchelle/vscode-rainbow-end

**Comment by siroemk** [comment]
他にもドキュメントがないか探す👀

**Comment by siroemk** [comment]
ドキュメントはREADMEくらいだった

**Comment by siroemk** [comment]
READMEの画像が見えないところは冒頭のここ
<img width="714" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/e83d27b0-4c83-4210-8eb3-1e780c3f734a">

**Comment by siroemk** [comment]
VS codeにvscode-rainbow-endを入れてみる

**Comment by siroemk** [comment]
VS codeでインストールした

**Comment by siroemk** [comment]
READMEに書いてあるRubyのコードを手元で書いてみます
<img width="541" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/37fd043c-fc91-4f66-bd4b-04f5cf8c70c6">

**Comment by siroemk** [comment]
色ついてる、可愛い！

## 入れる前
<img width="428" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/a446db1d-e153-4692-9170-0ab1ba3da121">

## 入れた後
<img width="412" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/3f31015b-b32a-4114-91e4-155eb280cff0">

**Comment by siroemk** [comment]
他にもいろんな言語があるが試せないので、一旦飛ばします

**Comment by siroemk** [comment]
VS codeの詳細ページにはダークモードのスクリーンショットもあった

<img width="718" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/11371cc4-1703-4ae9-851c-80a84942792b">

**Comment by siroemk** [comment]
↑ダークモードのスクリーンショットと同じコードを書いてみる

**Comment by siroemk** [comment]
書いてみた
<img width="398" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/0421eb6b-8466-4885-9405-d9d492acbcc0">

**Comment by siroemk** [comment]
ドキュメントに記載されているスクリーンショットには`==`や`>`、`puts`にも色がついているが、私の環境だと色がつかずに白で表示される

## ドキュメント
<img width="718" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/11371cc4-1703-4ae9-851c-80a84942792b">

## 自分の環境
<img width="398" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/0421eb6b-8466-4885-9405-d9d492acbcc0">

**Comment by siroemk** [comment]
色をカスタマイズできそうなのでやってみる
<img width="704" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/4c653113-3393-4fd1-99ff-7467dcd521da">

**Comment by natsuto6** [comment]
私用のため午前で失礼させていただきます！🙇‍♂️
ありがとうございました！！

**Comment by siroemk** [comment]
@natsuto6 
いろいろアドバイスをありがとうございました！

**Comment by daipom** [comment]
> READMEの画像が見えないところは冒頭のここ <img alt="image" width="714" src="https://user-images.githubusercontent.com/31835314/271746454-e83d27b0-4c83-4210-8eb3-1e780c3f734a.png">

僕の環境だと見え方が違いますね。何か環境依存な部分があるのかもしれない？
これは画像なのかリンクなのか。。

![Screenshot from 2023-09-30 14-30-29](https://github.com/oss-gate/workshop/assets/12229857/6ed91340-a5c2-4fb6-baa1-0e2a6dd35a1c)

**Comment by siroemk** [comment]
私はChromeで確認しました

**Comment by Aseiide** [comment]
macOSのsafariだとこんな感じでしたよ〜
<img width="899" alt="スクリーンショット 2023-09-30 14 41 48" src="https://github.com/oss-gate/workshop/assets/45246171/1274cf2d-94a0-40da-b88d-d27ec1e03690">

**Comment by daipom** [comment]
マークダウンを確認してみたが、何かおかしい。

https://github.com/julien-duponchelle/vscode-rainbow-end/blob/master/README.md?plain=1#L3

**Comment by siroemk** [comment]
画像に対してリンクを貼っているのでは(?)
やはり画像自体は見えない模様。

既にIssueが上がっていないか確認する。

**Comment by siroemk** [comment]
さらっと確認した感じ、READMEの画像自体は見えない件はIssueに上がっていなかった。

**Comment by siroemk** [comment]
Issueを上げる際のルールはなさそう。

**Comment by siroemk** [comment]
Issueにあげる内容を考えます。

## 状況
- READMEのRainbow Endに掲載されている画像が見えない
<img width="686" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/9c41dcb1-cd5e-40ca-95eb-da5097e9a1fb">

## 環境
- Chrome、safari
  - 画像切れのアイコンが表示される
  - クリックすると`https://marketplace.visualstudio.com/items?itemName=jduponchelle.rainbow-end`に飛ぶ
 - Firefox
   - 通常のリンクに見える
   - クリックすると`https://marketplace.visualstudio.com/items?itemName=jduponchelle.rainbow-end`に飛ぶ

## 期待する結果
- 画像のリンク切れを修正する
もしくは
- リンクのみに修正する

**Comment by siroemk** [comment]
英語に訳していきます。

**Comment by siroemk** [comment]
- Issue タイトル
Doesn’t display image in README

**Comment by siroemk** [comment]
# Doesn’t display image in README
## Actual Result
- I can't see the images posted in README.
- The two links `Marketplace` and `Version Installs` go to the same page.
`https://marketplace.visualstudio.com/items?itemName=jduponchelle.rainbow-end`

### Chrome
<img width="686" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/9c41dcb1-cd5e-40ca-95eb-da5097e9a1fb">

### safari
<img width="640" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/fac644f9-045a-44a8-9f73-b512d529825d">

### Firefox
  - In Firefox, it looks like a normal link.
<img width="637" alt="image" src="https://github.com/oss-gate/workshop/assets/31835314/b5b554ba-c15b-49c6-8da7-5272c4d050d8">


## Expected behavior
- A link or image is displayed.

**Comment by siroemk** [comment]
vscode-rainbow-endにIssueを作成しました。
https://github.com/julien-duponchelle/vscode-rainbow-end/issues/49

**Comment by Aseiide** [comment]
はやい！めっちゃいいですね〜

**Comment by piroor** [comment]
画像のURLは https://vsmarketplacebadge.apphb.com/version/jduponchelle.rainbow-end.svg なんですね。ホストがタイムアウトしてるので、Webサイトが移転したとかなのかなあ。

**Comment by komagata** [comment]
@siroemk こちら新しいURLに直すPRとか送っても良いかもですね〜

**Comment by siroemk** [comment]
@komagata 
フォローいただき、ありがとうございました！

PRも送ってみました。
https://github.com/julien-duponchelle/vscode-rainbow-end/pull/50

**Comment by komagata** [comment]
@siroemk おおお、とっても素晴らしいと思います〜！
