### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: odentakashi Todo-Tree: Work log

### ISSUE THREAD

**Issue by OdenTakashi** [oss-gate/workshop#1671]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by OdenTakashi** [comment]
vscodeの拡張機能から探してみる

**Comment by OdenTakashi** [comment]
Todo-Treeというvscodeの拡張機能を試してみる

**Comment by miyanew** [comment]
ライセンスは MIT License　とのこと

https://github.com/Gruntfuggly/todo-tree/blob/master/License.txt

**Comment by miyanew** [comment]
https://opensource.org/licenses/

**Comment by OdenTakashi** [comment]
GitHubのリポジトリ: https://github.com/Gruntfuggly/todo-tree

**Comment by OdenTakashi** [comment]
`https://github.com/Gruntfuggly/todo-tree`のREADME記載のインストール手順を参考にする

**Comment by OdenTakashi** [comment]
環境: mac OS

**Comment by miyanew** [comment]
インストール手順はこれですかね？

https://github.com/Gruntfuggly/todo-tree/blob/master/README.md#installing

**Comment by OdenTakashi** [comment]
vscode上で
- `cmd+p`
- `ext install Gruntfuggly.todo-tree`
を実行。

**Comment by OdenTakashi** [comment]
問題なくインストールできた

**Comment by OdenTakashi** [comment]
使い方を探しているが見当たらない

**Comment by miyanew** [comment]
うーんそうみえますね。
初めてみた人が使い方を見つけられるような導線が合った方が良いみたいなフィードバックできそうかも

**Comment by OdenTakashi** [comment]
このわからなさの背景には一般的なTODOの認識とここで使われているソースコードに直接TODOを書くというTODOへの認識の違いがわからなさの原因かもしれない

**Comment by OdenTakashi** [comment]
そもそもTODOの説明が足らないかもしれない

**Comment by OdenTakashi** [comment]
ここで使われているTODOの説明: https://www.jetbrains.com/help/idea/using-todo.html

**Comment by miyanew** [comment]
Piroさんからアドバイスいただいた

参照リンク先
https://www.jetbrains.com/help/idea/using-todo.html
https://medium.com/imdoneio/the-imdone-pitch-feedback-welcome-386430accf01

**Comment by miyanew** [comment]
修正方法: 外部サイトにリンクを貼るか、文章を書くか　-> 一長一短
- リンクを貼る: メンテコストは低い、リンク先の外部サイトがいつまであるか謎
- 文章を書く: メンテコストが高い、プロダクト内で完結できる

Github内のドキュメントならパーマリンクを貼ればいいが...

アメリカだと[フェアユース \- Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A7%E3%82%A2%E3%83%A6%E3%83%BC%E3%82%B9)という基準がある
引用するにあたり、元記事を明らかにすれば問題にならないハズ

**Comment by OdenTakashi** [comment]
初めて使おうとした場合に使い方がわからないと困るので報告したい。

**Comment by OdenTakashi** [comment]
報告方法に指定はなさそう

**Comment by OdenTakashi** [comment]
使い方がわからないという問題なので`How to use`というキーワードでissueを検索してみたが見当たらなかった

**Comment by OdenTakashi** [comment]
報告テンプレートも特になし。

**Comment by OdenTakashi** [comment]
伝えたいこと
- ソースコードに "TODO" などのコメントを埋め込む文化があるという前提を知らない状態でこのREADMEを読むとここで書かれているTODOの意味が分かりずらいため、前置きとしてこのような文化があるということを明示するといいかも

**Comment by OdenTakashi** [comment]
READMEの修正に関しては、具体的に改善があるならば「ここをこういうふうに直すといいと思います。」のように具体案を提示するのが良い。
改善案が決まっていないならば、「ここが分かりずらいのでこういうニュアンスを加えるといいのではないか」と提案するのが良いとアドバイスいただきました。

**Comment by OdenTakashi** [comment]
タイトル:"How about adding an explanation about 'TODO' in the README?"

本文: 
Thankyou for great extension ! 

But It took me some time to understand how to use it. Because I didn't  know the culture of embedding comments like 'TODO' or 'FIX' in source code.

So, if possible, explaining such a culture  might make it more understandable.

**Comment by goruchanchan** [comment]
```diff
- 原文
+ 更新 
```

**Comment by OdenTakashi** [comment]
> Most programmers put TODO comments in their code to track problems they see and ideas they have, like a carpenter building a house who writes a measurement on the framing. Programmers use TODO comments because they’re convenient and allow you to stay in the code, reducing distractions.
[Using TODO Comments to Keep You Programming in the Zone \| by Jesse Piascik \| imdone\.io \| Medium](https://medium.com/imdoneio/the-imdone-pitch-feedback-welcome-386430accf01)

**Comment by goruchanchan** [comment]
アノテーションコードは、わかりやすい表記にしてもいいかもです！
上に貼ってくれたリンク先の記載も他との違いがわかるようになっている気がするので👀

**Comment by OdenTakashi** [comment]
Thank you for great extension !

But It took me some time to understand how to use it. Because I didn't  know the culture of embedding comments like _TODO_ or _FIX_ in source code.

So, explaining such a culture might make it more understandable.

How about adding links to explanations about the culture regarding TODO or FIXME as follows?

```
README.md

This extension quickly searches (using [ripgrep](https://github.com/BurntSushi/ripgrep)) your workspace for comment tags like [TODO](https://www.jetbrains.com/help/idea/using-todo.html) and [FIXME](https://www.jetbrains.com/help/idea/using-todo.html) and displays them in a tree view in the activity bar. The view can be dragged out of the activity bar into the explorer pane (or anywhere else you would prefer it to be).
```


[culture of embedding comments like _TODO_ or _FIX_ in source code](https://www.jetbrains.com/help/idea/using-todo.html)

**Comment by OdenTakashi** [comment]
リンクを追加する提案にしてみました。

**Comment by OdenTakashi** [comment]
`I didn't know `というよりもより多くの人に知ってもらえるというニュアンスにすると良い。

**Comment by goruchanchan** [comment]
https://en.wikipedia.org/wiki/Comment_(computer_programming)#Tags

**Comment by OdenTakashi** [comment]
リンク切れのある可能性があるためwikiなどのリンク切れがないであろうリンクを使うようにする。

**Comment by komagata** [comment]
@OdenTakashi こちらその後いかがでしょうか〜？
僕でもよろしければIssue文章のサポートなどもさせていただきます〜！

**Comment by OdenTakashi** [comment]
@komagata 
気にかけてくださりありがとうございます🙏

今週末を目標にして作業を続ける予定です。

その際に文章のサポートを依頼させていただくかもしれませんが、その際はどうぞよろしくお願いします🙇‍♂️。

**Comment by OdenTakashi** [comment]
## メモ
PR: [Add link to explanations about the culture regarding tags by OdenTakashi · Pull Request \#796 · Gruntfuggly/todo\-tree](https://github.com/Gruntfuggly/todo-tree/pull/796)

**Comment by OdenTakashi** [comment]
@komagata 
無事PRを送ることができました。
マージなどはまだされていませんが、取り急ぎ報告させていただきます。🙏

**Comment by komagata** [comment]
@OdenTakashi PR作成おめでとうございます〜！

**Comment by komagata** [comment]
@OdenTakashi こちら、メインのコントリビューターにメンションで、「こちらいかがでしょうか〜」的なメッセージ送ってもいいかもですね。大分日にちが経っているので。

**Comment by OdenTakashi** [comment]
@komagata 
アドバイスいただきありがとうございます。🙏

コメントを送りました。
[Add link to explanations about the culture regarding tags by OdenTakashi · Pull Request \#796 · Gruntfuggly/todo\-tree](https://github.com/Gruntfuggly/todo-tree/pull/796)

**Comment by komagata** [comment]
@OdenTakashi スバラシィ〜
