### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: SuzukaHori: htmlbeautifier: Work log

### ISSUE THREAD

**Issue by SuzukaHori** [oss-gate/workshop#1672]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by SuzukaHori** [comment]
作業メモを作りました。

**Comment by SuzukaHori** [comment]
案：https://github.com/threedaymonk/htmlbeautifier

**Comment by SuzukaHori** [comment]
MITライセンスだったのでOK
https://github.com/threedaymonk/htmlbeautifier/blob/master/COPYING.txt

**Comment by SuzukaHori** [comment]
公式サイト：https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify

**Comment by SuzukaHori** [comment]
公式サイト：https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify
Github:https://github.com/HookyQR/VSCodeBeautify
ライセンス：https://github.com/HookyQR/VSCodeBeautify/blob/master/LICENSE.txt

**Comment by SuzukaHori** [comment]
機能を触ってみる。
```
or to operate on standard input and output:

$ htmlbeautifier < input > output
```
この部分のやり方がわからない

**Comment by SuzukaHori** [comment]
学び：自分が実行しているコマンドが何の機能で提供されている物なのか、ちゃんと理解する。
似た名前の他のソフトウェアだと混同して、ずっと違うリポジトリを見ていた。

**Comment by SuzukaHori** [comment]
コマンドの引数にディレクトリが入れられると便利。
現状だとエラーになる。
```
❯ htmlbeautifier app/views                        
/Users/suzuka/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/htmlbeautifier-1.4.2/bin/htmlbeautifier:97:in `read': Is a directory @ io_fread - app/views (Errno::EISDIR)
        from /Users/suzuka/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/htmlbeautifier-1.4.2/bin/htmlbeautifier:97:in `block in <top (required)>'
        from /Users/suzuka/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/htmlbeautifier-1.4.2/bin/htmlbeautifier:96:in `each'
        from /Users/suzuka/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/htmlbeautifier-1.4.2/bin/htmlbeautifier:96:in `<top (required)>'
        from /Users/suzuka/.rbenv/versions/3.2.2/bin/htmlbeautifier:25:in `load'
        from /Users/suzuka/.rbenv/versions/3.2.2/bin/htmlbeautifier:25:in `<main>'
```

**Comment by SuzukaHori** [comment]
> 機能を触ってみる。
> 
> ```
> or to operate on standard input and output:
> 
> $ htmlbeautifier < input > output
> ```
> 
> この部分のやり方がわからない

```
$ htmlbeautifier < 整形したいファイル名 > 出力したいファイル名
```
これでやってみたができなかった。（ファイルが空になる。）

**Comment by SuzukaHori** [comment]
input output問題について

chatGPTに聞いた。
<img width="549" alt="スクリーンショット 2023-09-30 14 36 33" src="https://github.com/oss-gate/workshop/assets/129706209/d40561fe-4a14-4e9e-9aa3-8d2223b3e1d4">

**Comment by SuzukaHori** [comment]
アドバイスいただいた。
`htmlbeautifier input > &output`

**Comment by SuzukaHori** [comment]
このコマンドでも`output.txt `が空になる。（フォーマットはできている。）
`htmlbeautifier input.html.erb >&output.txt `

**Comment by SuzukaHori** [comment]
これだと何も起きない（フォーマットもできない）
```
❯ htmlbeautifier &input.html.erb > output.txt
[5]  + suspended (tty input)  htmlbeautifier
```

**Comment by SuzukaHori** [comment]
`<>`を勝手に省略してしまっていたのが原因！

`$ htmlbeautifier < フォーマットするファイル名 > 出力するファイル名`

**Comment by SuzukaHori** [comment]
日本語でのまとめ

--

READMEの説明について

以下の箇所の`input`と`output`が何を指すのかが理解できなかった。
加えて、誤ってコマンドを実行して、フォーマットできずに困った。
```jsx
$ htmlbeautifier input_file_name output_file_name
```

```jsx
or to operate on standard input and output:

$ htmlbeautifier < input > output
```

inputとoutputがファイルを指すという明記し、また`<>`を省略するではないと明記するべき。

期待値：READ MEを読んだ初心者が適切にgemを活用できること。

**Comment by SuzukaHori** [comment]
コミットメッセージの作り方

https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by SuzukaHori** [comment]
## READMEの`input` `output`の内容

以下の部分の理解に苦慮しました。
```
or to operate on standard input and output:

$ htmlbeautifier < input > output
```

`standard input and output`が何を指すのか明記すべきだと思います。

```
フォーマットしたいファイルと出力したいファイルを指定して実行できます。

$ htmlbeautifier < update_file_name > output_file_name
※<>は省略しない
```

**Comment by SuzukaHori** [comment]
英訳
## README: Input and Output Content
Thank you for creating the gem.

I had difficulty understanding the following part:
```
or to operate on standard input and output:

$ htmlbeautifier < input > output
```
It would be helpful if you specify what "standard input" and "output" refer to.

```
You can specify the file you want to format and the file you want to output to when executing.

$ htmlbeautifier < update_file_name > output_file_name

Do not omit the `<>`.
```

**Comment by piroor** [comment]
```
$ htmlbeautifier < input > output
```

を

```
$ htmlbeautifier <input> output
```

と誤読していたとのこと

**Comment by piroor** [comment]
```
$ htmlbeautifier <input_file_name >output_file_name
```

こうだと分かりやすそう

**Comment by piroor** [comment]
htmlbeautifier を使う人全員がUNIXのコマンド操作の「常識」に詳しいわけではないので、 https://github.com/oss-gate/workshop/issues/1672#issuecomment-1741699588 のような誤読が発生することは多分あると思います。
他方、UNIXの常識に属することをこのプロジェクトのREADMEで丁寧に書くと、詳しい人が見たときに違和感が生まれるというのも、事実だと思います。

なので、

```
$ htmlbeautifier < index.erb > index_formatted.erb
```

のような実例も併記するように提案するというのは、「あまり詳しくない人も誤読しにくい」「詳しい人が見たときにも邪魔にならない」というバランスをとった落とし所になるんじゃないかなあと思いました！

**Comment by SuzukaHori** [comment]
@piroor 
アドバイスいただきありがとうございます🙇‍♀️
> 他方、UNIXの常識に属することをこのプロジェクトのREADMEで丁寧に書くと、詳しい人が見たときに違和感が生まれるというのも、事実だと思います。

詳しい方も違和感のないように書く必要があるのですね！大変勉強になりました。
ファイル名の例を追記するような方向で書きたいと思います。

**Comment by SuzukaHori** [comment]
日本語メモ

## READMEのinput outputの内容
READMEの以下の箇所が理解できず、詰まってしまいました。
```
or to operate on standard input and output:

$ htmlbeautifier < input > output
```
原因は、私がUNIX操作に慣れていないため、`<input>`をファイル名として置き換えるのだと誤解して、`<>`を省略したコマンドを実行してしまったことです。
```
htmlbeautifier index.erb index_formatted.erb
```

以下のように、具体例を併記することを提案します。
```
htmlbeautifier < index.erb > index_formatted.erb
```

**Comment by SuzukaHori** [comment]
英訳

## README Input and Output Content

I had difficulty understanding the following section in the README:
```
or to operate on standard input and output:

$ htmlbeautifier < input > output
```
The reason was that,  I misunderstood that `<input>` should be directly replaced with a file name, and executed the command without the `<>` as shown below:
```
htmlbeautifier index.erb index_formatted.erb
```

For clarity, it would be helpful to provide a concrete example in the README like:
```diff
or to operate on standard input and output:
- $ htmlbeautifier < input > output
+ $ htmlbeautifier < index.erb > index_formatted.erb
```

**Comment by SuzukaHori** [comment]
フィードバック先：https://github.com/threedaymonk/htmlbeautifier
ブランチ名：readme_add_example
コミットメッセージ：Add example to the input and output contents of the README

**Comment by SuzukaHori** [comment]
完了！
https://github.com/threedaymonk/htmlbeautifier/pull/76

**Comment by komagata** [comment]
@SuzukaHori PRから2週間経っているのでメインのコントリビューターの人にメンションして、「こちらいかがでしょうか？」みたいなコメントしちゃってもいいかもです〜。

**Comment by komagata** [comment]
@SuzukaHori こちらその後いかがでしょうか〜

**Comment by SuzukaHori** [comment]
@komagata 
お返事が遅れ申し訳ありません。
htmlbeautifierのgemの更新が一年半前に止まっているため、現時点ではメンションすることは考えていないです🙇‍♀️（OSS Gateの際には、サポートメンターさんにしばらく更新されていない旨を相談した上で取り組んでおりました。）

気にかけていただき、ありがとうございます🙇‍♀️

**Comment by komagata** [comment]
@SuzukaHori あら、一年半前というのはそんなに古い方ではないですし、メンションはそんなに身構えなくても送っちゃっていいと思いますよ〜。
（他の方も大体がメンションで催促してかなりマージされております〜）

**Comment by SuzukaHori** [comment]
@komagata 
一年半前は古くないんですね！誤解していました。
メンションを送りました🙇‍♀️

**Comment by komagata** [comment]
@SuzukaHori いい感じだと思います〜！
日本のノリと違って催促がないと重要じゃないんだなと判断されたりするので全然メンションを送るのは大丈夫だと思います。

**Comment by kou** [comment]
そうですね。メンションして問題ないです。
いろんなOSSをメンテナンスしている私の視点だと、「後で見るかー」と思ったまま忘れてしまっていることもあるので、メンションしてもらえると、「あ、忘れてたわ」と気づけて助かることがあります。
メンションを見逃すこともあるので、「メンションしたのにリアクションがない！ムキー！」みたいにならないでいてくれるとメンテナンスしている側としてはうれしいです！

**Comment by SuzukaHori** [comment]
@komagata @kou 
アドバイスありがとうございます🙏
皆さん忙しくされているので、ある程度主張しないと忘れられてしまうことがあるんですね。今後はあまり気にしないでメンションしたいと思います。
そしてお返事がなくても気にしないようにします！
