### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: zamami: color_echo: Work log

### ISSUE THREAD

**Issue by zamami** [oss-gate/workshop#1674]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by zamami** [comment]
OSSを探したら

GitHubリポジトリー：
公式webサイト：

**Comment by zamami** [comment]
https://ja.wikipedia.org/wiki/Sl_(UNIX)

linuxコマンドのslがOSSならこちらに取り組んでみます。

**Comment by zamami** [comment]
https://opensource.org/licenses/
にて「sl」と検索。
ヒットしないみたい。

**Comment by blacktoad30** [comment]
https://github.com/mtoyoda/sl

**Comment by zamami** [comment]
ライセンスがなさそうなので引き続き他のOSSを探してみる。

**Comment by zamami** [comment]
https://rubygems.org/
こちらにてOSSを検索中

**Comment by zamami** [comment]
https://github.com/khotta/color_echo/blob/master/LICENSE.txt
こちらのライセンスを確認したいです。

**Comment by zamami** [comment]
https://github.com/khotta/color_echo/blob/master/LICENSE.txt
こちらはライセンス登録されていたので、OSSだと分かりました。
READMEに従い使ってみて何か提案できないか考えてみます。

**Comment by zamami** [comment]
color_echo
GitHubリポジトリー：https://github.com/khotta/color_echo
公式webサイト：　http://colorecho.github.io/

**Comment by zamami** [comment]
READEME書いてあるサンプルコードを動かしてみた。
無事動いた。
メソッドも多くあるみたいなので色々試しながら、
「こういうのがあったらいいな」と思うものがないか探してみます。

**Comment by zamami** [comment]
別のOSSを探してみます。

**Comment by zamami** [comment]
https://rubygems.org/search/advanced
ruby gem サイトで高度な検索で更新日を2023-08以降に絞って検索中。

**Comment by zamami** [comment]
普段FBCの課題で使っているGemfileから調べてみる。
```
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.6'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem 'image_processing', '~> 1.2'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  gem 'erb_lint', require: false
  gem 'faker'
  gem 'i18n_generators'
  gem 'letter_opener_web'
  gem 'rubocop-fjord', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
end

gem 'carrierwave'
gem 'devise'
gem 'devise-i18n'
gem 'kaminari'
gem 'rails_autolink'
```

**Comment by zamami** [comment]
https://github.com/tily/ruby-faker-japanese
をクローンしました。

**Comment by zamami** [comment]
READEMEにある、
要件
・naist-jdic-utf8 (ソースからインストールする場合のみ)
をやってみる。

**Comment by zamami** [comment]
> 要件
・naist-jdic-utf8 (ソースからインストールする場合のみ)

そもそも`naist-jdic-utf8 `がなんなのかわからず調べてみたところ、
NAIST Japanese Dictionary は日本語の形態素解析の実装である ChaSen 用の辞書ということがわかった。
（https://packages.debian.org/ja/sid/naist-jdic-utf8）

**Comment by komagata** [comment]
@zamami こちらその後いかがでしょうか〜？
僕でもよろしければIssue文章のサポートなどもさせていただきます〜！

**Comment by zamami** [comment]
https://github.com/tily/ruby-faker-japanese
こちらをgem installで使用できるか試してみる。

**Comment by zamami** [comment]
まずはREADMEに書かれている通りに、
`    gem install faker-japanese`を実行してみる。
<img width="737" alt="スクリーンショット 0005-10-17 13 41 48" src="https://github.com/oss-gate/workshop/assets/24470799/a1f0a5f0-55a9-4b88-8139-6d4017daa639">

無事インストールできた。
`gem list`にあるか確認してみる。
<img width="709" alt="スクリーンショット 0005-10-17 13 42 16" src="https://github.com/oss-gate/workshop/assets/24470799/0b91a4c8-8ef0-40ed-a880-a5bb788c32c0">
確認できた。

READEに記載されている、「使い方」を試してみる。
`require faker-japanese`を記述し、
コードを実行してみるとエラーが起きた。

<img width="1022" alt="スクリーンショット 0005-10-17 13 45 14" src="https://github.com/oss-gate/workshop/assets/24470799/38ace820-505e-4a0d-9bdd-74f05a3359fd">

エラー文には
`cannot load such file -- faker-japanese (LoadError)`
と書かれており、`faker-japanese`が読み込めていないことがわかる。

次は、irbを使って`faker-japanese`が読み込めるか試してみる。
<img width="791" alt="スクリーンショット 0005-10-17 13 50 20" src="https://github.com/oss-gate/workshop/assets/24470799/ba4a07fc-2267-492c-9709-51a94b37745b">
同様のエラーになった。

`require faker-japanese`ではなく、
`require faker/japanese`としてみると読み込めた。

<img width="779" alt="スクリーンショット 0005-10-17 13 52 48" src="https://github.com/oss-gate/workshop/assets/24470799/30417598-7027-4f48-85f0-b8ab8bfb1b6b">

再度READEMEのコードを実行してみると`faker-japanese`を使用することができた。
<img width="645" alt="スクリーンショット 0005-10-17 13 55 35" src="https://github.com/oss-gate/workshop/assets/24470799/8840b144-d20d-4dd3-903e-7a5874940281">

**Comment by zamami** [comment]
irbにて`require faker/japanese`と入力する際に、
`require faker/japanese/name`も検索候補に出てきたので、
`require faker/japanese/name`が使用できるのか試してみる。

<img width="632" alt="スクリーンショット 0005-10-17 13 57 25" src="https://github.com/oss-gate/workshop/assets/24470799/2ced56c4-fcbb-4d30-8f33-f0b33bc04ad0">

再度irbを起動し、`require faker/japanese/name`を読み込みコードを実行してみると`faker-japanese`を使用できた。
<img width="426" alt="スクリーンショット 0005-10-17 14 05 40" src="https://github.com/oss-gate/workshop/assets/24470799/d91dcb3a-d749-4349-b9b3-34deb5bfd76a">

**Comment by zamami** [comment]
`faker/japanese`
`faker/japanese/name`
が存在しているので、両方`require`したらどうなるか試してみる。
<img width="413" alt="スクリーンショット 0005-10-17 14 09 42" src="https://github.com/oss-gate/workshop/assets/24470799/0c323cfb-e238-4243-9332-8c6c4857bfdf">

先に、`require faker/japanese`を`require`すると` faker/japanese/name`がfalseになる。

先に、`require faker/japanese/name`を`require`すると` faker/japanese`もtrueになる。さらにその状態でコードを実行することができた。

**Comment by zamami** [comment]
以上をもとに、faker-japaneseのREADEに対して以下をPRしたい。

・READEの使い方に'require faker/japanese'もしくは'require faker/japanese/name'どちらかを記述。
２つ`require`する際は、
`require faker/japanese`
`require faker/japanese/name`
の順で記述することを追記していただきたい。

**Comment by zamami** [comment]
## Issue内容案
タイトル
提案: READMEの使い方のコードに以下を追記するのはいかがでしょうか？

```
require 'faker/japanese`

もしくは、
require 'faker/japanese/name`

もしくは、
require 'faker/japanese`
require 'faker/japanese/name`
```


## 内容（箇条書き）
『素晴らしいプロダクトに感謝しています。』
+ こうすればより良いと思うこと
使い方のソースコードに`require'の記述を含めた方がユーザーが問題なく`faker-japanese`を使用できるかもしれないと思ったため・

+ なぜそう思うのか
` gem install faker-japanese`を実行後、`require faker-japanese`と記述したところloadエラーが起こったため。
<img width="791" alt="スクリーンショット 0005-10-17 13 50 20" src="https://github.com/oss-gate/workshop/assets/24470799/f573d45c-427d-49a9-a5e2-decf378a1f4e">

・以下の方法で`require`すると`faker-japanese`を使用することができたため。
```
require 'faker/japanese'
または、
require `faker/japanese/name
または、
require `faker/japanese/name
require 'faker/japanese'
```
require 'faker/japanese'の場合
<img width="645" alt="スクリーンショット 0005-10-17 13 55 35" src="https://github.com/oss-gate/workshop/assets/24470799/679883cc-ebc9-4932-af27-c24291495ff1">
require `faker/japanese/nameの場合
<img width="426" alt="スクリーンショット 0005-10-17 14 05 40" src="https://github.com/oss-gate/workshop/assets/24470799/922c0a9d-c928-4c4d-b913-ff7fe3ace703">

require `faker/japanese/name
require 'faker/japanese'の場合
<img width="413" alt="スクリーンショット 0005-10-17 14 09 42" src="https://github.com/oss-gate/workshop/assets/24470799/c90cfd33-f2db-4a18-9475-9ab7201064c7">

## 環境

OS: mac OS Monterey 12.6.5
Ruby:3.2.2

**Comment by zamami** [comment]
@komagata 
お疲れ様です。
Issue文章を作成してみました。
こちらの内容でPRをしようと思うのですが、いかがでしょうか？

**Comment by komagata** [comment]
@zamami 僕も @kou さんと同じ意見です。
バージョンが0.0.1なので作者に聞いてみると色々わかって良いかな〜と思いました。

**Comment by zamami** [comment]
@kou
コメントありがとうございます。

> require "faker/japanese/name"でfalseが返ってくるということはすでに読み込み済みということ

gemに対しての知識がなかったのでなぜfalseになるのかわからなかったのですがおかげで理解することができました。ファイルを読み込んでいるんですね。
gemを利用する際は、
`gem install XXX => require 'XXX'`
だと勝手に思い込んでいました。ありがとうございます。

初歩的な質問で恐縮です。
> 作者の方に聞くのが確実というアプローチももちろんあります。

とありますが、作者に聞くというのはissueを立てて質問するということでしょうか？

改めてPRを作成してみました。
ご確認よろしくお願いします。

**Comment by zamami** [comment]
## Issue内容案
タイトル
提案: READMEの使い方のコードに以下を追記するのはいかがでしょうか？

```
require 'faker/japanese`

もしくは、
//Faker::japanese::nameのみ使用する場合
require 'faker/japanese/name`

```

## 内容（箇条書き）
『素晴らしいプロダクトに感謝しています。』
+ こうすればより良いと思うこと
使い方のソースコードに`require`の記述を含めた方がユーザーが問題なく`faker-japanese`を使用できるかもしれないと思ったため。

+ なぜそう思うのか
` gem install faker-japanese`を実行後、初学者はどのように`require`したらいいのかわからない可能性があるため。
私自身、`require faker-japanese`と記述してしまいloadエラーを起こしてしまったため。

また、今後の実装次第だとは思われますが、
require `faker/japanese/name`
などの方法でfaker-japaneseの一部の仕様も可能だということも記述されるのはいかがでしょうか？

## 環境

OS: mac OS Monterey 12.6.5
Ruby:3.2.2

**Comment by zamami** [comment]
初歩的な質問で恐縮です。
> 作者の方に聞くのが確実というアプローチももちろんあります。

とありますが、作者に聞くというのはissueを立てて質問するということでしょうか？

**Comment by kou** [comment]
そうですね！
今回の場合は、別途質問するだけのissueを作らずに、今回作ろうとするissueの中で質問するのでいいと思います！
（関連する話題なので。）

**Comment by zamami** [comment]
@kou 
回答ありがとうございます。
こちらでPRさせていただきます！

**Comment by komagata** [comment]
@zamami もしPR作成しましたらURL教えていただければ嬉しいです〜

**Comment by zamami** [comment]
https://github.com/tily/ruby-faker-japanese/pull/3

**Comment by komagata** [comment]
@zamami PR作成素晴らしいです〜！

> PR内容案
> タイトル
> 提案: READMEの使い方のコードに以下を追記するのはいかがでしょうか？

本番のPR自体にもそのまま入ってしまっているのでこの辺り相手の立場に立ってみた文言い変えるのがいいかもです〜

**Comment by zamami** [comment]
@komagata 
> 本番のPR自体にもそのまま入ってしまっているのでこの辺り相手の立場に立ってみた文言い変えるのがいいかもです〜
コメントありがとうございます。修正しました！
