### ISSUE TITLE
OSS Gate Workshop: online: 2023-09-30: junohm410(shodan): Video Speed Controller: Work log

### ISSUE THREAD

**Issue by junohm410** [oss-gate/workshop#1675]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by junohm410** [comment]
作業ログイシューを立てました。

**Comment by junohm410** [comment]
本当にこれで進めるかはわからないけれど、よく使っている倍速視聴のChrome拡張機能。これについて調べます。
https://github.com/igrigorik/videospeed

**Comment by junohm410** [comment]
Githubを見る感じ、「(MIT License) - Copyright (c) 2014 Ilya Grigorik」とあるので、↓で検索。
https://opensource.org/licenses/

![image](https://github.com/oss-gate/workshop/assets/128765400/8b2e5bc0-6959-4ac5-8f5c-bbbf376313b6)

**Comment by goruchanchan** [comment]
> オープンソースライセンスによって、他者が自由にリポジトリ中のプロジェクトを利用、変更、配布できるようになります。 

[Github の Docs](https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) にも『ライセンスファイルを設置して、OSS開発やりやすくなるよ』という文言ありますね👀

**Comment by junohm410** [comment]
## 気づいた現象
- リポジトリにライセンスのファイルがない
- `About`欄にライセンスが明示されていない

※フィヨルドのアプリの場合、`About`欄にMIT Licenseが明示されている（以下はそのスクショ）。
![image](https://github.com/oss-gate/workshop/assets/128765400/2f921d8f-dcc4-4726-8546-a56a95ee659b)


## それによる問題
このソフトウェアがOSSかどうかがわからず、OSS的な貢献をしていいのかわからない。

## ゴール？
- リポジトリにライセンスのファイルを置いてもらう
- `About`欄にライセンスを明示してもらう

→このどちらかの提案をしてみる？

**Comment by junohm410** [comment]
Open Source Initiative (OSI)のMITライセンスのページ。

https://opensource.org/license/mit/

**Comment by junohm410** [comment]
## todo
過去のイシューでライセンスの明示問題が蹴られていないかを確認する。
もし蹴られていなければ、そのissueを立てることが今日のゴールになる。
蹴られていれば、改善部分を探す。

**Comment by junohm410** [comment]
[License issue · Issue \#875 · igrigorik/videospeed](https://github.com/igrigorik/videospeed/issues/875)

**Comment by goruchanchan** [comment]
Issue をたてる際には、『みんなでよくしていきたいので、ライセンスをつけた方がいいとい思う』というポジティブな内容にすると良いとのことです👀

**Comment by junohm410** [comment]
「License」や「MIT」というキーワードでissuesを検索したところ、この問題について議論されたものはちょっと見つからなさそうです。
なので、午後はそれを伝えるということをゴールにしてみたいと現時点では考えています。

**Comment by zonuexe** [comment]
[`package.json`のlicense](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license)で明示する方法もあるが、ほぼ空の内容

https://github.com/igrigorik/videospeed/blob/master/package.json

**Comment by junohm410** [comment]
## 午後最初のtodo
- Video Speed Controllerにコントリビュートする際の定まったお作法がないか調べる。

**Comment by junohm410** [comment]
`CONTRIBUTING.md`には実際に修正・機能追加を書いてPRするまでのお作法は示されているけれど、Issueを立てることに関しては特に記載がありませんでした。
また、すでに立っているIssueを見ても、特別決まったフォーマットなどは無さそうでした。

なので、以下を次のtodoにしたいと思います。

## todo
自分がIssueで伝えたいことを日本語でまとめる。

**Comment by goruchanchan** [comment]
いいと思います！

**Comment by goruchanchan** [comment]
> プロジェクトによっては、ライセンスに関する情報は README に記載されています。 たとえばプロジェクトの README には、「当ライセンスは MIT ライセンスの規約に基づいて付与されています」などの文言が書かれていることがあります。
> **ベスト プラクティスとして、プロジェクトにはライセンス ファイルを含めることをお勧めします。**
> [ライセンスの置かれている場所を確認する
](https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license)

午前中の話にもありましたが、慣習の記載ありますね😅

ただ、今回の提案は『OSS開発をしていく上では、license ファイルが設置してあり、それをすぐに確認できたほうが、わかりやすくて開発しやすいと思うので設置してはいかがでしょうか？』というニュアンスだと思うので、Issue としてはありなんじゃないかなと思います！

ユーザ多いのと、コントリビュータも55人いますし、個人的は Github の about からライセンス確認できると便利だと思いますし🤔

**Comment by junohm410** [comment]
## Issue内容案(WIP)
### タイトル
提案: MIT License全文を記載したファイルをリポジトリに含めてはどうでしょうか。


### 内容（箇条書き）
- 『素晴らしいプロダクトに感謝しています。』
- こうすればより良いと思うこと
  - `MIT License`全文をファイル化するなどしてリポジトリ内に置いたほうが、より安心してユーザーがOSSとしてこのソフトウェアを使用できるかもしれない。
- なぜそう思うのか
  - 多くのOSSは、GitHubのAbout欄でライセンス情報がわかるようになっており、またそこからリポジトリの中にある`License.txt`のようなテキストファイルにリンクすることで、ライセンス情報の詳細を確認できるようになっています。
  - また、`MIT License`の中にも、下記のようにライセンス文そのものをソフトウェアのどこかに明記すべきことが示されています（『The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.』）。
  - このプロジェクトの`README`の最後には`(MIT License) - Copyright (c) 2014 Ilya Grigorik`という記載があり、それによりこのソフトウェアがOSSであることは示されいることは承知しております。そして、慣習的にそれでも問題のないことも理解しています。
  - それでも、ライセンス文全体を記載したファイルがあると、より多くの人にとって安心でわかりやすいプロダクトになるのではないかと思いますので、このような提案をさせていただきたいと思っています。

参考URL:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
（About欄にライセンスを追加するためのガイド/En版
https://opensource.org/license/mit/
（MIT License全文）

**Comment by junohm410** [comment]
## todo
↑の内容を英語でまとめる。

**Comment by junohm410** [comment]
## Issue内容案(WIP)

### タイトル
Suggestion: why don't you include a file with the full text of the MIT License in the repository?

### 内容
First of all, thank you for this wonderful and useful product.
On top of that, may I make one suggestion to make this product better?

### suggestion
It might be more comfortable for users to use and contribute to this software as OSS if the full text of the MIT License is filed or otherwise placed in the repository.

### the reason why
Many OSS include license information in the `About` section of GitHub repository, and you can also find detailed license information from there by linking to a text file, such as `License.txt`, in the repository.

The MIT License also indicates that the "permission notice" itself should be included somewhere in the software, as follows.
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

[The MIT License – Open Source Initiative](https://opensource.org/license/mit/)

Meanwhile, I am aware that at the end of the README for this project, it states `(MIT License) - Copyright (c) 2014 Ilya Grigorik`, thereby indicating that this software is OSS. I also understand that this is not a problem conventionally.

On the other hand, I would like to make this suggestion because I think that a file describing the entire license text would make the product more secure and easier to understand for more users as OSS.

Reference:
[Adding a license to a repository \- GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)
[Licensing a repository \- GitHub Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license)
(it says "As a best practice, we encourage you to include the license file with your project.")

Once again, I appreciate a great product. Thanks in advance.

**Comment by goruchanchan** [comment]
提案は How about とかの方が自然かもです👀（英語得意ではないですが😅）

https://foreignlang.ecc.co.jp/learn/l00074d/

**Comment by junohm410** [comment]
最終的にこちらのissueをたてました

https://github.com/igrigorik/videospeed/issues/1063

**Comment by komagata** [comment]
@junohm410 こちらMITライセンスのファイルを追加するPRを送ってみてもいいかもですね〜

**Comment by junohm410** [comment]
@komagata 
こちら承知いたしました！時間をとって頑張ってみたいと思います。
その中で不明点や確認いただきたい点が出てきたら、こちらでご相談させていただきたいなと思います🙇‍♂️よろしくお願いいたします。

**Comment by komagata** [comment]
@junohm410 こちらその後いかがでしょうか〜？

**Comment by junohm410** [comment]
@komagata 
こちら、その後進めておらずすみませんでした🙇‍♂️

フォークしたリポジトリにMITライセンスファイルを追加しました。
https://github.com/junohm410/videospeed/blob/add-MITlicense-to-repository/LICENSE

 （https://opensource.org/license/mit/ からライセンスの文面はコピーし、コピーライト表記についてはリポジトリの`README.md`に作者のコピーライト表記があるので、それをコピーする形で追加しています。）

PRの文面は以下を考えています。
（https://github.com/igrigorik/videospeed/blob/master/CONTRIBUTING.md によれば、PR文の規定フォーマットなどは特にありません。）

> As I mentioned in the issue below, I think that many users and developers might be more comfortable using this software as OSS if MIT license is included in the repository.
(※issueのリンクを貼る)
Therefore, I've added MIT license file(`LICENSE`) to the repository. The copyright notice is based on the one in `README.md`.

こちら、ライセンスファイルの内容と、PR文に関して一般的な作法や礼儀的な意味で問題点がないか、ご確認いただけないでしょうか？🙇‍♂️

**Comment by kou** [comment]
PRに「どこからコピーしたか」というURLも入れたら出していいと思います！
私がPRを受け取る側なら、この内容が本当に正しいかを確認したくなります。そのとき、出所があると確認しやすくなります。

**Comment by junohm410** [comment]
@kou 
ご確認、ご助言ありがとうございます🙏
PRに下記のように追加しようとおもいます！

>As I mentioned in the issue below, I think that many users and developers might be more comfortable using this software as OSS if MIT license is included in the repository.
(※issueのリンクを貼る)
Therefore, I've added MIT license file(`LICENSE`) to the repository. The license text was quoted from the Open Source Initiative website. [The MIT License – Open Source Initiative](https://opensource.org/license/mit/)
Also, the copyright notice is based on the one in `README.md`.

**Comment by kou** [comment]
いいと思います！

**Comment by komagata** [comment]
@junohm410 いい感じだと思います〜！

**Comment by junohm410** [comment]
@komagata 
ご確認ありがとうございました🙏
上記内容で、PRを提出しました。
https://github.com/igrigorik/videospeed/pull/1066

また状況に更新があれば、ここ / OSS Gateのチャットでご相談・ご報告させていただけるとありがたいです🙏
引き続きよろしくお願いいたします。

**Comment by komagata** [comment]
@junohm410 PRとってもいいですね！
こちらにも追記しておきました。
https://github.com/oss-gate/workshop/wiki/Workshop%E3%81%AE%E6%88%90%E6%9E%9C%E7%89%A92023%E2%80%9009%E2%80%9030

もう３週間経っているので、コミッターの誰かにメンションしてみるのがいいかもしれません。

**Comment by junohm410** [comment]
@komagata 
承知しました！さきほどPRの中でigrigorikさんにメンションしました。
またなにかあったら共有いたいします。

https://github.com/igrigorik/videospeed/pull/1066

**Comment by komagata** [comment]
@junohm410 スバラシィ〜！

**Comment by junohm410** [comment]
@みなさま
お疲れ様です。
昨年9/30のこちらのOSSGateに参加させていただき、その中で作成したPRがさきほどマージされましたのでご報告いたします。
MITライセンスファイルがなかったのでそれを追加するという内容で、対象のリポジトリの`master`ブランチに私が作成したライセンスファイルが入っています。

スクールであるフィヨルドブートキャンプ以外の公のOSSへの初コントリビュートとなりました🙇‍♂️
こちらでサポートいただきました皆様に感謝申し上げます🙏ありがとうございました。
以上、ご報告でございます。

**Comment by komagata** [comment]
@junohm410 素晴らしぃ～～～！
