### ISSUE TITLE
OSS Gate Workshop: Online: 2023-09-30: moegi: rails_autolink: Work log

### ISSUE THREAD

**Issue by KMZ0209** [oss-gate/workshop#1677]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by KMZ0209** [comment]
作業ログ作りました！

**Comment by KMZ0209** [comment]
こちらを対象にしたいです～ https://github.com/omnidan/node-emoji

**Comment by KMZ0209** [comment]
chinaだとごはん
$ emoj 'china'
🍚  🇨🇳
国旗が出ない windows環境
$ emoj 'cz'
🇨🇿

**Comment by umizaru** [comment]
Macだと絵文字出ている
![スクリーンショット 2023-09-30 11 48 42](https://github.com/oss-gate/workshop/assets/57088113/2485a133-158d-4c61-97cc-cf88a4bf17e1)

**Comment by KMZ0209** [comment]
ライセンスありました！https://github.com/omnidan/node-emoji/blob/main/LICENSE

**Comment by umizaru** [comment]
umizaruのPC：MacOS Ventura 13.5.1

**Comment by KMZ0209** [comment]
$ emoj 'kids'

kmz@DESKTOP-8MN9H7R:~/JavaScriptPrimer$ emoj 'adult'
🧑  🧓
kmz@DESKTOP-8MN9H7R:~/JavaScriptPrimer$ emoj 'family'
👪  👨‍👩‍👧  👨‍👩‍👧‍👦  👨‍👩‍👦‍👦  👨‍👩‍👧‍👧  👩‍👩‍👦  👩‍👩‍👧

**Comment by KMZ0209** [comment]
環境依存に関するアナウンスは書かれていなそう、、？https://github.com/omnidan/node-emoji/blob/main/README.md

**Comment by KMZ0209** [comment]
moegiのPC：Windows11
環境:WSL:Ubuntu-20.04

**Comment by KMZ0209** [comment]
Windows support #5 について議論されていた～ https://github.com/sindresorhus/emoj/issues/5

**Comment by KMZ0209** [comment]
https://github.com/sindresorhus/emoj/issues/5#issuecomment-228618094
Windows 10 Insiders ビルド 14374 の Windows 上の Ubuntu で Bashでは全く表示されないとコメントいうあり。
>> 残念ながら、これは現在、Windows コンソールによる絵文字のサポートが非常に制限されているという事実を浮き彫りにしています。 将来的にはこれを修正する計画がありますが、残念ながら今のところ、絵文字を機能させるのに十分なほど絵文字がサポートされていません :(

**Comment by umizaru** [comment]
案1：このIssue上で、Windows10だけではなく、Windows11のWSL Ubuntuでも動作しないことを報告する
案2：READMEの記載方法を修正してほしい旨のIssueを立てる（＝最新のLinuxベースマシンでもWSLで動かすとNG、など）

**Comment by KMZ0209** [comment]
## Issue内容案(WIP)

**Comment by KMZ0209** [comment]
todo
↑の内容を英語でまとめる。

**Comment by KMZ0209** [comment]
## done 
Windows supportについて議論されていたPRにコメントとしてフィードバックしました。
![image](https://github.com/oss-gate/workshop/assets/111144394/0ff969c6-19a7-4ace-9e57-b5e24c045fe0)
