### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: roasted-tea-leaves: atom: 作業ログ

### ISSUE THREAD

**Issue by roasted-tea-leaves** [oss-gate/workshop#168]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by roasted-tea-leaves** [comment]
**公式サイト**
https://atom.io/

**作業**
1. Download for mac で zipファイル落として、実行ファイルをアプリケーションフォルダに移動。
2. アプリケーション開く。

**Comment by roasted-tea-leaves** [comment]
**ビルドの実行**
1. https://github.com/atom/atom/blob/master/docs/build-instructions/macos.md を参照。
2. git clone https://github.com/atom/atom.git を実行。

**Comment by roasted-tea-leaves** [comment]
3. 依存環境が入っていないのでインストール
> macOS 10.8 or later
> Node.js 4.4.x or later (we recommend installing it via nvm)
> npm 3.10.x or later (run npm install -g npm)
> Command Line Tools for Xcode (run xcode-select --install to install)

**Comment by roasted-tea-leaves** [comment]
4. https://github.com/creationix/nvm のReadMeを読み始める

**Comment by roasted-tea-leaves** [comment]
5. ↑のInstall Script を実行してみる。
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash

**Comment by roasted-tea-leaves** [comment]
6. Path通す
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

**Comment by roasted-tea-leaves** [comment]
7. 以下のコマンドで「nvm」と表示されたので成功
command -v nvm

**Comment by roasted-tea-leaves** [comment]
8. Nodeのインストール
nvm install node

**Comment by roasted-tea-leaves** [comment]
9. script/build を実行。やや時間がかかりそう。

> $ script/build
> Node:	v7.2.0
> Npm:	v3.10.9
> Installing script dependencies

**Comment by roasted-tea-leaves** [comment]
10. エラーで止まる。

> $ script/build
> Node:	v7.2.0
> Npm:	v3.10.9
> Installing script dependencies
> Installing apm
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:196:
> ../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
>   return array->CloneElementAt(GetCurrentContext(), index);
>                 ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:3056:36: note: 'CloneElementAt' has been explicitly marked deprecated here
>                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
>                                    ^
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:202:
> In file included from ../node_modules/nan/nan_new.h:189:
> ../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                             ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:4048:56: note: 'New' has been explicitly marked deprecated here
>   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
>                                                        ^
> In file included from ../src/main.cc:1:
> ../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
>   return obj->SetAccessor(
>               ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:2761:22: note: 'SetAccessor' has been explicitly marked deprecated here
>                 bool SetAccessor(Local<Name> name,
>                      ^
> 3 warnings generated.
> ../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
>   hasMultiByteChars = (value->Length() != utf8_length_);
>                        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
> 1 warning generated.
> ../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
>     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
>                                                         ~~~ ^
> 1 warning generated.
> child_process.js:145
>     throw new TypeError('Incorrect value of args option');
>     ^
> 
> TypeError: Incorrect value of args option
>     at Object.exports.execFile (child_process.js:145:11)
>     at Object.exports.exec (child_process.js:108:18)
>     at Object.<anonymous> (/Users/masakichi/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:420:7)
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/Users/masakichi/.nvm/versions/node/v7.2.0/bin/node" "/Users/masakichi/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! atom-package-manager@1.15.1 install: `node script/postinstall.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the atom-package-manager@1.15.1 install script 'node script/postinstall.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node script/postinstall.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs atom-package-manager
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls atom-package-manager
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/masakichi/atom/apm/npm-debug.log
> npm ERR! code 1
> child_process.js:511
>     throw err;
>     ^
> 
> Error: Command failed: /Users/masakichi/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:196:
> ../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
>   return array->CloneElementAt(GetCurrentContext(), index);
>                 ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:3056:36: note: 'CloneElementAt' has been explicitly marked deprecated here
>                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
>                                    ^
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:202:
> In file included from ../node_modules/nan/nan_new.h:189:
> ../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                             ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:4048:56: note: 'New' has been explicitly marked deprecated here
>   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
>                                                        ^
> In file included from ../src/main.cc:1:
> ../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
>   return obj->SetAccessor(
>               ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:2761:22: note: 'SetAccessor' has been explicitly marked deprecated here
>                 bool SetAccessor(Local<Name> name,
>                      ^
> 3 warnings generated.
> ../src/onig-string.cc:25:40: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
>   hasMultiByteChars = (value->Length() != utf8_length_);
>                        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
> 1 warning generated.
> ../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
>     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
>                                                         ~~~ ^
> 1 warning generated.
> child_process.js:145
>     throw new TypeError('Incorrect value of args option');
>     ^
> 
> TypeError: Incorrect value of args option
>     at Object.exports.execFile (child_process.js:145:11)
>     at Object.exports.exec (child_process.js:108:18)
>     at Object.<anonymous> (/Users/masakichi/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:420:7)
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/Users/masakichi/.nvm/versions/node/v7.2.0/bin/node" "/Users/masakichi/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! atom-package-manager@1.15.1 install: `node script/postinstall.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the atom-package-manager@1.15.1 install script 'node script/postinstall.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node script/postinstall.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs atom-package-manager
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls atom-package-manager
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/masakichi/atom/apm/npm-debug.log
> npm ERR! code 1
> 
>     at checkExecSyncError (child_process.js:488:13)
>     at Object.execFileSync (child_process.js:508:13)
>     at module.exports (/Users/masakichi/atom/script/lib/install-apm.js:10:16)
>     at Object.<anonymous> (/Users/masakichi/atom/script/bootstrap:27:1)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)

**Comment by roasted-tea-leaves** [comment]
11. git checkout v1.12.5 してから、script/build を最実行。

> $ script/build
> Node:	v7.2.0
> Npm:	v3.10.5
> Installing script dependencies
> Installing apm
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:196:
> ../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
>   return array->CloneElementAt(GetCurrentContext(), index);
>                 ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:3056:36: note: 'CloneElementAt' has been explicitly marked deprecated here
>                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
>                                    ^
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:202:
> In file included from ../node_modules/nan/nan_new.h:189:
> ../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                             ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:4048:56: note: 'New' has been explicitly marked deprecated here
>   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
>                                                        ^
> In file included from ../src/main.cc:1:
> ../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
>   return obj->SetAccessor(
>               ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:2761:22: note: 'SetAccessor' has been explicitly marked deprecated here
>                 bool SetAccessor(Local<Name> name,
>                      ^
> 3 warnings generated.
> ../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
>     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
>                                                         ~~~ ^
> 1 warning generated.
> child_process.js:145
>     throw new TypeError('Incorrect value of args option');
>     ^
> 
> TypeError: Incorrect value of args option
>     at Object.exports.execFile (child_process.js:145:11)
>     at Object.exports.exec (child_process.js:108:18)
>     at Object.<anonymous> (/Users/masakichi/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:420:7)
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/Users/masakichi/.nvm/versions/node/v7.2.0/bin/node" "/Users/masakichi/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! atom-package-manager@1.12.9 install: `node script/postinstall.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the atom-package-manager@1.12.9 install script 'node script/postinstall.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node script/postinstall.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs atom-package-manager
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls atom-package-manager
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/masakichi/atom/apm/npm-debug.log
> npm ERR! code 1
> child_process.js:511
>     throw err;
>     ^
> 
> Error: Command failed: /Users/masakichi/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:196:
> ../node_modules/nan/nan_maybe_43_inl.h:220:17: warning: 'CloneElementAt' is deprecated [-Wdeprecated-declarations]
>   return array->CloneElementAt(GetCurrentContext(), index);
>                 ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:3056:36: note: 'CloneElementAt' has been explicitly marked deprecated here
>                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
>                                    ^
> In file included from ../src/main.cc:1:
> In file included from ../node_modules/nan/nan.h:202:
> In file included from ../node_modules/nan/nan_new.h:189:
> ../node_modules/nan/nan_implementation_12_inl.h:40:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
>   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
>                             ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:4048:56: note: 'New' has been explicitly marked deprecated here
>   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
>                                                        ^
> In file included from ../src/main.cc:1:
> ../node_modules/nan/nan.h:2017:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
>   return obj->SetAccessor(
>               ^
> /Users/masakichi/.node-gyp/7.2.0/include/node/v8.h:2761:22: note: 'SetAccessor' has been explicitly marked deprecated here
>                 bool SetAccessor(Local<Name> name,
>                      ^
> 3 warnings generated.
> ../deps/libgit2/deps/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
>     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
>                                                         ~~~ ^
> 1 warning generated.
> child_process.js:145
>     throw new TypeError('Incorrect value of args option');
>     ^
> 
> TypeError: Incorrect value of args option
>     at Object.exports.execFile (child_process.js:145:11)
>     at Object.exports.exec (child_process.js:108:18)
>     at Object.<anonymous> (/Users/masakichi/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:420:7)
> npm ERR! Darwin 16.1.0
> npm ERR! argv "/Users/masakichi/.nvm/versions/node/v7.2.0/bin/node" "/Users/masakichi/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
> npm ERR! node v7.2.0
> npm ERR! npm  v3.10.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! atom-package-manager@1.12.9 install: `node script/postinstall.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the atom-package-manager@1.12.9 install script 'node script/postinstall.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node script/postinstall.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs atom-package-manager
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls atom-package-manager
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/masakichi/atom/apm/npm-debug.log
> npm ERR! code 1
> 
>     at checkExecSyncError (child_process.js:488:13)
>     at Object.execFileSync (child_process.js:508:13)
>     at module.exports (/Users/masakichi/atom/script/lib/install-apm.js:10:16)
>     at Object.<anonymous> (/Users/masakichi/atom/script/bootstrap:27:1)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>

**Comment by roasted-tea-leaves** [comment]
12. ミニふりかえり
- やっていなかった Command Line Tools for Xcode (run xcode-select --install to install) を実行
- Nodeのバージョンを Node.js 4.4.x 系列でやってみる？

**Comment by roasted-tea-leaves** [comment]
13. 素の環境 (virtualboxで構築) でテストしてみる

**Comment by roasted-tea-leaves** [comment]
**問題**
- https://github.com/atom/atom/blob/master/docs/build-instructions/macos.md の手順通りにインストールしていくと、`script/build` がエラーで止まる。

**条件**
- macOS Sierra 10.12.1
- Node v7.2.0
- Npm v3.10.5
- xcode-select version 2345.1.

**Comment by roasted-tea-leaves** [comment]
**分かったこと**
- https://github.com/atom/apm/issues/636 によると、Node.jsのバージョンが7.0.0以上でapmのビルドがこけるらしい。

**Comment by roasted-tea-leaves** [comment]
**今後**
- UbuntuでNodeとnpmのバージョンを合わせて正しくビルドできるか検証する。

**Comment by roasted-tea-leaves** [comment]
**フィードバック内容**
It was reproductive on my environment.
- macOS Sierra 10.12.1
- Node v7.2.0
- Npm v3.10.5
- xcode-select version 2345.1.

I might as well correct "Requirements".
(e.g. specify recommend version)
https://github.com/atom/atom/blob/master/docs/build-instructions/macos.md

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-28に開催](https://oss-gate.doorkeeper.jp/events/52881)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
