### ISSUE TITLE
OSS Gateワークショップ2016-03-26: tsutakata: mybatis: 作業ログ

### ISSUE THREAD

**Issue by tsutakata** [oss-gate/workshop#17]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by tsutakata** [comment]
mybatisのドキュメントを読み始めました。
http://www.mybatis.org/mybatis-3/ja/getting-started.html

**Comment by tsutakata** [comment]
どこでjarファイルをダウンロードすればいいかわからない。
mybatis-x.x.x.jar

**Comment by tsutakata** [comment]
日本語だけでなく、英語のドキュメントも見てみる。

**Comment by tsutakata** [comment]
どこでjarがダウンロードできるか、ぐぐる。

**Comment by tsutakata** [comment]
ここでダウンロードできる。
https://github.com/mybatis/mybatis-3/releases

**Comment by tsutakata** [comment]
スタートガイドの１行目がJavaを知らないひとにとっては、よくわからないという意見あり。
どんなターゲット向けなのかを考える。
"MyBatis を使うためには、ダウンロードした mybatis-x.x.x.jar をクラスパスに追加する必要があります。"

**Comment by tsutakata** [comment]
EclipseでMybatisを動かす用にサンプルのプロジェクトを作成する。

**Comment by tsutakata** [comment]
作成したプロジェクトにjarを追加。

**Comment by tsutakata** [comment]
こちらの項目が読んでいてピンとこなかった。
"XML 形式の設定ファイルを使って SqlSessionFactory を生成する"

**Comment by tsutakata** [comment]
スタートガイドの１項目目と２項目目がとんでいる印象。

**Comment by tsutakata** [comment]
このコードをどのクラスに書いていいのかわからない。

```
String resource = "org/mybatis/example/mybatis-config.xml";
InputStream inputStream = Resources.getResourceAsStream(resource);
SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
```

**Comment by tsutakata** [comment]
> MyBatis 付属の Resources

実際のパッケージ名は、ibatisなので。

**Comment by tsutakata** [comment]
追加するjarはsources.jarではなく、mybatis-3.3.1.jarを追加する。

**Comment by tsutakata** [comment]
`InputStream inputStream = Resources.getResourceAsStream(resource);`

このコードではIOExceptionの例外をハンドリングする必要がある。

**Comment by tsutakata** [comment]
> XML 形式の設定ファイルを使って SqlSessionFactory を生成する

> XML を使わずに SqlSessionFactory を生成する


章立てがわかりにくい。

**Comment by tsutakata** [comment]
```
SqlSession session = sqlSessionFactory.openSession();
try {
  BlogMapper mapper = session.getMapper(BlogMapper.class);
  Blog blog = mapper.selectBlog(101);
} finally {
  session.close();
}
```

BlogMapper、Blogは自分で作るクラス。

**Comment by tsutakata** [comment]
```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
  PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
  "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.mybatis.example.BlogMapper">
  <select id="selectBlog" resultType="Blog">
    select * from Blog where id = #{id}
  </select>
</mapper>
```

どこに上記のXMLを書いていいのかわからない。

**Comment by tsutakata** [comment]
ドキュメントを読んでいてわからないときは、前の説明を読んでみる。
ただし、そういうドキュメントはよくない。

**Comment by tsutakata** [comment]
これを読み始める。
https://github.com/mybatis/mybatis-3/blob/master/CONTRIBUTING.md

**Comment by tsutakata** [comment]
issueを作るために、document関連の他のissueを見てみる。
https://github.com/mybatis/mybatis-3/issues?q=is%3Aissue+document+label%3Adocumentation

**Comment by tsutakata** [comment]
スタートガイドのInstallationでは、以下のように書いてあるが、Mavenを使わない場合、どこでjarファイルをダウンロードすればよいかわからない。

> MyBatis を使うためには、ダウンロードした mybatis-x.x.x.jar をクラスパスに追加する必要があります。

以下の文章を追加したほうがよい。

Mavenを利用しない場合は、以下からダウンロードする。
https://github.com/mybatis/mybatis-3/releases

**Comment by tsutakata** [comment]
In the manual - Getting started - Installation,

> To use MyBatis you just need to include the mybatis-x.x.x.jar file in the classpath.

When I don't use Maven, I don't know where I can download the mybatis-x.x.x.jar file.

It is better to add the following sentence.
When you don't use Maven, you can download the folllowing url.
https://github.com/mybatis/mybatis-3/releases

**Comment by tsutakata** [comment]
ドキュメントのGetting startedの中で、jarファイルのダウンロード場所がわからない。

**Comment by tsutakata** [comment]
In the manual - Getting started - Installation, I don't know where I can download the mybatis-x.x.x.jar file.

**Comment by tsutakata** [comment]
issueのタイトルは、欄の幅を目安にする。

**Comment by tsutakata** [comment]
issueを立てた。
https://github.com/mybatis/mybatis-3/issues/615

**Comment by tsutakata** [comment]
直したい文章が格納されているプロジェクトを確認する。
https://github.com/mybatis/mybatis-3/blob/master/src/site/xdoc/getting-started.xml

**Comment by tsutakata** [comment]
forkしてクローンした。

**Comment by tsutakata** [comment]
クローンしたドキュメントを修正する。

**Comment by tsutakata** [comment]
まずは日本語で修正内容を考える。

**Comment by tsutakata** [comment]
MyBatis を使うためには、mybatis-x.x.x.jar をダウンロードして、クラスパスに追加する必要があります。Mavenを使わない場合は、以下からダウンロードできます。
https://github.com/mybatis/mybatis-3/releases

**Comment by tsutakata** [comment]
ドキュメントを修正した。
DIFFで差分を確認。

+        file in the classpath. If you are not using Maven, you can download the following link.<br/>
+        <a href="https://github.com/mybatis/mybatis-3/releases">https://github.com/mybatis/mybatis-3/releases</a>

**Comment by tsutakata** [comment]
今回の場合、ダウンロードリンクを追加するだけなので、文章を追加せずに、リンクを追加して、他の言語も対応する。

**Comment by tsutakata** [comment]
1.Fork the repository on GitHub.

2.Clone your fork to your local machine.
git clone https://github.com/tsutakata/mybatis-3.git

3.Create a topic branch with a descriptive name.
git checkout -b fix-doc

4.Make changes with unit tests in the topic branch.

5.Push commits to your fork on GitHub.

6.Send a pull request.


git add
git commit
git push --set-upstream origin fix-doc

**Comment by kou** [comment]
おつかれさまでした！参加した感想をブログとかにまとめてくれるとOSS Gateワークショップの普及につながってうれしいです！
（次回からはフィードバックしたメンターの人にその場でcloseしてもらうようにしよう。おつかれ！とか言いながら。）
