### ISSUE TITLE
OSS Gateワークショップ 2016-11-26:  suganami0510: simple_form: 作業ログ

### ISSUE THREAD

**Issue by suganami0510** [oss-gate/workshop#170]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by suganami0510** [comment]
作業 simple_formのREADMEを読む　https://github.com/plataformatec/simple_form
思っていること  READMEを読んでもたまにわからない時があるので、普段でもググってしまうことが結構あると思う
備考

**Comment by suganami0510** [comment]
作業 simple_formのgemをインストールする
Gemfileに以下を追加
`gem 'simple_form'`
`bundle install`をする。

思っていること 
`rails generate simple_form:install` これはなんなんだろう？

備考

**Comment by suganami0510** [comment]
作業 `rails generate simple_form:install` をやってみた
思っていること 
色々ファイルが生成されたが、これらはなんなんだろう。

備考
```
      create  config/initializers/simple_form.rb
       exist  config/locales
      create  config/locales/simple_form.en.yml
      create  lib/templates/erb/scaffold/_form.html.erb
```
これらのファイルが生成された、

**Comment by suganami0510** [comment]
作業
Country Select https://github.com/plataformatec/simple_form#country-select
について、調べてみた。

思ったこと
他のgemのダウンロードは正直めんどくさいと思う。
gemのダウンロードをしない方法も書いてあるものの、使い方がよくわからない。

備考
coutry_selectのやり方には２種類ある
- gem 'country_select' をインストールする
`simple_form.rb` の
`config.input_mappings = { /country/ => :string }` を編集する

**Comment by suganami0510** [comment]
作業
Country Select の設定
思ったこと
simple_form.rb initializer: とは、`/config/initializers/simple_form.rb` ファイルの設定である。
デフォルトだと、
`config.input_mappings = { /count/ => :integer }` 
となっているが、READMEだと
`config.input_mappings = { /count/ => :string }` 
となっている、この違いはなんだろう

**Comment by suganami0510** [comment]
作業
https://github.com/plataformatec/simple_form#usage
これにしたがって、
```
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>
```
このようにviewファイルに書いてみる

思ったこと
@user が定義されていないので、
当然エラーメッセージが発生する。このGemのREADMEとして、ある程度Railsの動作および、form_forの動きがわかっている人向けに書かれている部分もある。分かる人には最低限の説明でいいと思うが、ほんとに一からスタートする人のために、チュートリアル用のREADMEを別URLに作ってもいいのかもしれない。

**Comment by suganami0510** [comment]
作業
simple_formを既存のアプリケーションに導入
思ったこと
既存のアプリケーションにsimple_formを導入するより
最初からアプリケーションを作った方が早いと思った
`Rails new`  からスタートするチュートリアルサイトの必要性を感じる。

**Comment by suganami0510** [comment]
作業 
placeholder: label: hint:の機能を 試してみた

思ったこと
それぞれについて、どのように表示されるのか、スクショみたいなものがあると親切だなと思った。

**Comment by suganami0510** [comment]
自分の気持ち

simple_formをgemからインストールして、それぞれの機能が実際にどのように動くかということを確認したい。
となったときに、既存のアプリケーションを改修して確認しようとすると、既存のアプリケーションの動作の影響により上手く確認できないものもあった。新規でアプリケーションで、モデルやコントローラーを考えながら作るのも時間がかかってしまう。

Rails newから始まり、Model、コントローラー、viewファイルを動かしながら、Usageの機能を確認していく、チュートリアル用のドキュメントがあると親切だと思う。
（チュートリアルのサイトでは、スクリーンショット、 同様の機能を `form_for`  や `HTML` での出力結果等が書いてあると非常に理解がしやすいと思う。）

**Comment by suganami0510** [comment]
開発者目線

最近アサインし始めたプロジェクトにて、formに代わり、simple_formを使っています。
 
これをきっかけに、 `simple_form` の機能について色々と理解したいと思いまして、READMEのUsageを読みながら、サンプルアプリケーションを動かしています。

https://github.com/plataformatec/simple_form#usage
こちらにしたがいまして、

viewファイルを、以下のように編集して機能を確認しようとしました。
```
<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>
```

しかし、機能を確認するためには少なくとも、
- コントローラー等で@userの定義を行う。
- その@userのインスタンスには、 `username`  `password` の属性が必要になる
という二つの前提条件が必要です。

機能の確認をしたいユーザーにとっては、その２つの前提条件を自前で用意しなければならないので、非常に手間になってしまいます。また、開発経験が浅いユーザーによってはそもそもその前提条件を自前で用意できないこともあると思います。

なので、機能確認をしたいユーザーにとっては、 `$ rails new`のコマンドから始まり Model、Controller、view のファイルを含めたドキュメントのようなものがあると非常に助かります。

また、確認をスムーズに行うために、 `README.md` ファイルのそれぞれの機能を紹介するところに、機能実装時のスクリーンショットや、HTMLへの変換等を記載していただくと理解がスムーズになると思います。

**Comment by suganami0510** [comment]
機能確認をしたいユーザーにとっては、 $ rails newのコマンドから始まり Model、Controller、view のファイルを含めたドキュメントのようなものがあると非常に助かります。

確認をスムーズに行うために、 README.md ファイルのそれぞれの機能を紹介するところに、機能実装時のスクリーンショットや、HTMLへの変換等を記載していただくと理解がスムーズになると思います。

**Comment by suganami0510** [comment]
開発者目線

READMEのUsageを読みながら、サンプルアプリケーションを動かして、機能の確認を試みました。
わかりずらい部分があったので、README.md の改善案をこちらに提示します。

README.mdファイルのUsageに従って、機能を確認しようとしました。
https://github.com/plataformatec/simple_form#usage

simple_formのスニペットで下記を自前で用意するのに時間がかかりました。

- viewファイルのパス
- @user 等のインスタンス変数をどこで定義するか
- Userモデルの属性定義が必要

### 改善案
- `rails g scaffold Users ...`
- 各スニペットで前提条件を記載する
自前の環境での確認がスムーズに行えると思います

**Comment by suganami0510** [comment]
英語に変換
I read Usage of README and tried to confirm the function with sample application.

Since there was a difficult part to understand, we propose an improvement plan of README.md.

I attempted to confirm the function according to Usage of README.md.
Https://github.com/plataformatec/simple_form#usage

I had a hard time preparing the following with a simple_form snippet.

### Cause

- Path of view file is ambiguous
- Unclear where to define instance variables such as @ user
- Unclear attribute definition of User model

### improvement plan
- Describe the command satisfying the prerequisite
Ex. `Rails g scaffold Users ...`
- Describe prerequisites on each snippet

I think that checking in the environment for beginners can be done smoothly

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-21に開催](https://oss-gate.doorkeeper.jp/events/54640)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
