### ISSUE TITLE
作業メモとそれ以外のissueを分けて一覧できるようにしたい

### ISSUE THREAD

**Issue by daipom** [oss-gate/workshop#1704]
ワークショップの度に大量の作業メモissueが発生するので、closedされたissueの中から過去のやり取りを探すのが大変。
作業メモとそれ以外のissueを分けて一覧できるようにしたい。

ラベルを活用することでこの問題を解決できないか？
とりあえず`enhancement`ラベルを貼るようにしてみたが、作業メモの方に作業メモ専用ラベルが自動で貼られるようにした方が良いかも。

**Comment by blacktoad30** [comment]
作業メモのタグに、`worklog`を使用するのはいかがでしょうか?

P.S. 
Issuesのタグ付けルールを決める、という内容に広げられそう。
Issueのテンプレートを作るのも良さそう。

**Comment by daipom** [comment]
`work log`ラベルを自動で付与するようにテンプレートを改良しました！

**Comment by blacktoad30** [comment]
@daipom 対応ありがとうございます。
しばらくissueを触ってなかったので、既にテンプレートがあるのを忘れていました...

**Comment by daipom** [comment]
いえいえ！！
ついでにタイトルも自動で入るようにしました！
