### ISSUE TITLE
OSS Gate Workshop: PHP Lovers: 2023-10-09: satak: phpstan-src: Work log

### ISSUE THREAD

**Issue by mt-satak** [oss-gate/workshop#1709]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mt-satak** [comment]
ﾅﾆﾓﾜｶﾗﾅｲのでとりあえず https://github.com/phpstan/phpstan から`git clone` を試みる、がなんだか重い・・・あってる・・・？🤔
→サポーターの方から https://github.com/phpstan/phpstan-src をcloneすると良いですよと教えていただいた、のでこちらをclone.

```
git clone git@github.com:phpstan/phpstan-src.git
```

**Comment by mt-satak** [comment]
cloneができたので、[LISENCE](https://github.com/phpstan/phpstan-src/blob/1.11.x/LICENSE)を確認してみる👀

**Comment by mt-satak** [comment]
[公式サイトのPHPStan](https://phpstan.org/)

**Comment by mt-satak** [comment]
概要読んだメモ
- 英→日に翻訳かけて読んでみた(翻訳がなかったので)
- ふわっと持っていた事前知識と照らし合わせつつ内容を確認
  - [Rule Levels](https://phpstan.org/user-guide/rule-levels)
  - [Baseline](https://phpstan.org/user-guide/baseline)

**Comment by mt-satak** [comment]
[getting started](https://phpstan.org/user-guide/getting-started)を読んで、動かしてみる

**Comment by mt-satak** [comment]
PHP7.2以上が必要とのこと、7.2以上なのを確認して↓実行
```
composer require --dev phpstan/phpstan
```

**Comment by mt-satak** [comment]
ここでやけに時間がかかっている気がする・・🤔
ちょっと待機

```
- Applying patches for hoa/protocol
    patches/Node.patch (0)
```

**Comment by mt-satak** [comment]
パッチ適用に失敗した模様
```
  - Applying patches for hoa/protocol
    patches/Node.patch (0)
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d '/Users/satak/dev/phpstan-src/vendor/hoa/protocol' < '/Users/satak/dev/phpstan-src/patches/Node.patch'" exceeded the timeout of 300 seconds.

In Patches.php line 331:
                                              
  Cannot apply patch 0 (patches/Node.patch)!  
                                              
```

**Comment by mt-satak** [comment]
↑
https://packagist.org/packages/hoa/protocol
> This package is abandoned and no longer maintained. No replacement package was suggested.

**Comment by mt-satak** [comment]
ここまでの一連の内容をそのまま報告あげてみても良さそう？

**Comment by mt-satak** [comment]
### 動作環境
- MacOS 13.3.1
- PHP 8.3.0beta3

**Comment by mt-satak** [comment]
似たような事象が発生していないかissueを確認してみる
https://github.com/phpstan/phpstan/issues

**Comment by mt-satak** [comment]
closedも見ていく
→ `label:bug composer require is:closed `

**Comment by mt-satak** [comment]
改めてエラー文言を読み返してみる
```
Could not apply patch! Skipping. 
The error was: The process "patch '-p1' --no-backup-if-mismatch -d '/Users/satak/dev/phpstan-src/vendor/hoa/protocol' 
< '/Users/satak/dev/phpstan-src/patches/Node.patch'" exceeded the timeout of 300 seconds.

```

**Comment by mt-satak** [comment]
phpstan-srcの`composer.json`を読んでみる

**Comment by mt-satak** [comment]
ここまで、どこで何を行ったか
```
git clone git@github.com:phpstan/phpstan-src.git

cd phpstan-src

pwd
/Users/satak/dev/phpstan-src

composer require --dev phpstan/phpstan
```

**Comment by mt-satak** [comment]
> composer require --dev phpstan/phpstan

そもそもこれを行うのが違っていた可能性、

[phpstan-srcのREADME](https://github.com/phpstan/phpstan-src#installation)
`composer install` すれば良かった

**Comment by mt-satak** [comment]
`composer install` 実行した結果、

```
  - Applying patches for hoa/protocol
    patches/Node.patch (0)
```
ここでつまづくのは先ほどの `composer require --dev phpstan/phpstan` 実行時と同じ

**Comment by mt-satak** [comment]
=========午前中はここまで=========

**Comment by mt-satak** [comment]
### 午後からやること方向性

- ここまでのことをissueを立てて報告あげるところからやってみるで良さそう
- 該当箇所の修正PRまで作れるともっと良さそう

**Comment by o0h** [comment]
`composer install -vvv` とかってやってみると、「インストールのどこに時間がかかっているのかな？」のヒントが見つかるかもです

**Comment by mt-satak** [comment]
vender配下のパッケージにパッチを当てる時の`composer patch`でググると色々でてくるかも

**Comment by mt-satak** [comment]
```
patch '-p1' --no-backup-if-mismatch -d '/Users/satak/dev/phpstan-src/vendor/hoa/protocol' < '/Users/satak/dev/phpstan-src/patches/Node.patch'
```

これを直接実行してみるのも手 > @てきめんさん

**Comment by mt-satak** [comment]
> `composer install -vvv` とかってやってみると、「インストールのどこに時間がかかっているのかな？」のヒントが見つかるかもです

```
> post-package-install: cweagans\Composer\Patches->postInstall
  - Applying patches for hoa/protocol
    patches/Node.patch (0)
patch '-p1' --no-backup-if-mismatch -d '/Users/satak/dev/phpstan-src/vendor/hoa/protocol' < '/Users/satak/dev/phpstan-src/patches/Node.patch'
Executing command (CWD): patch '-p1' --no-backup-if-mismatch -d '/Users/satak/dev/phpstan-src/vendor/hoa/protocol' < '/Users/satak/dev/phpstan-src/patches/Node.patch'
File to patch: 
   Could not apply patch! Skipping. The error was: The process "patch '-p1' --no-backup-if-mismatch -d '/Users/satak/dev/phpstan-src/vendor/hoa/protocol' < '/Users/satak/dev/phpstan-src/patches/Node.patch'" exceeded the timeout of 300 seconds.
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/

In Patches.php line 331:
                                              
  [Exception]                                 
  Cannot apply patch 0 (patches/Node.patch)!  
                                              

Exception trace:
  at /Users/satak/dev/phpstan-src/vendor/cweagans/composer-patches/src/Patches.php:331
 cweagans\Composer\Patches->postInstall() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:206
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:148
 Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Installer/InstallationManager.php:396
 Composer\Installer\InstallationManager::Composer\Installer\{closure}() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Installer/InstallationManager.php:411
 Composer\Installer\InstallationManager->executeBatch() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Installer/InstallationManager.php:319
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Installer.php:797
 Composer\Installer->doInstall() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Installer.php:289
 Composer\Installer->run() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Command/InstallCommand.php:146
 Composer\Command\InstallCommand->execute() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Console/Application.php:378
 Composer\Console\Application->doRun() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/src/Composer/Console/Application.php:141
 Composer\Console\Application->run() at phar:///Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer/bin/composer:88
 require() at /Users/satak/.asdf/installs/php/8.3.0beta3/bin/composer:29
```

**Comment by mt-satak** [comment]
@ tadsanより

`brew install patch`で直るかも。patchの互換性の問題？とのこと👀

関連issueを見つけた↓
https://github.com/phpstan/phpstan/issues/9452

**Comment by mt-satak** [comment]
Macを使っていたら古いpatchを使ってしまう可能性があるので、そこはドキュメントに入れ込んでも良いのでは？
というissueは投げてみても良さそう

**Comment by mt-satak** [comment]
コントリビューションガイドのどこに入れるのが良さそうか、など提案してみる、とか

**Comment by zonuexe** [comment]
ドキュメントに追加する場合、そのままcloneすると巨大なのでこれでcloneする

```
git clone git@github.com:phpstan/phpstan.git --filter=blob:none
```

**Comment by mt-satak** [comment]
> Macを使っていたら古いpatchを使ってしまう可能性があるので、そこはドキュメントに入れ込んでも良いのでは？ というissueは投げてみても良さそう

phpstan/phpstan/README.mdへの修正PR投げてみる

**Comment by youkidearitai** [comment]
大まかなプルリクエストの流れ

- [phpstan/phpstan ](https://github.com/phpstan/phpstan)のフォーク(fork)を作ります
- その自分のリポジトリをcloneしてきます
- そこからブランチを切って、自分のリポジトリへpushします
- GitHubで `Compare & Create Pull Request` （細かい文章は違うかもしれませんが）を押し、プルリクエストを作成します

**Comment by mt-satak** [comment]
PR出してみました👀
https://github.com/phpstan/phpstan-src/pull/2670

**Comment by mt-satak** [comment]
コメントがついていたので確認

You've opened the pull request against the latest branch 1.11.x. If your code is relevant on 1.10.x and you want it to be released sooner, please rebase your pull request and change its target to 1.10.x.
↓
最新ブランチ1.11.xに対してプルリクエストをオープンしました。もしあなたのコードが1.10.xに関連していて、より早くリリースしたいのであれば、プルリクエストをリベースしてターゲットを1.10.xに変更してください。

**Comment by mt-satak** [comment]
マージされました！🎉
https://github.com/phpstan/phpstan-src/pull/2670
