### ISSUE TITLE
OSS Gateワークショップ 2016-11-26: emitsuco3: bxSlider: 作業ログ

### ISSUE THREAD

**Issue by emitsuco3** [oss-gate/workshop#171]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by emitsuco3** [comment]
作業: サイトを見に行った。
思っていること： 懐かしい。お世話になった。ダウンロードすべき？
備考：

**Comment by emitsuco3** [comment]
作業: サイトのダウンロードボタンからダウンロードして展開した。
思っていること： スムーズにダウンロードできました。なんで使わなくなったんだろう。
備考：

**Comment by emitsuco3** [comment]
作業: 作業用フォルダを作ってそこに入れた。
思っていること： こんな細かいことまでコメントするんだ。
備考：

**Comment by emitsuco3** [comment]
作業: 使い方を調べるためサイトに戻った。
思っていること： 
備考：

**Comment by emitsuco3** [comment]
作業: サイトに書かれてはいなかったけれどHTMLファイルを作った。
思っていること： まあここにたどり着く時点でみんなHTMLファイルあるの当然だよね。
備考：

**Comment by emitsuco3** [comment]
作業: サイトの手順通りコピペ。scriptタグを追加。
思っていること： そういうものだと思ってやってしまったけれど、コピペ場所の指定とscriptタグについての説明がされていないので、本当の初心者さんは分からないかもしれない。
備考：

**Comment by emitsuco3** [comment]
作業: とりあえずブラウザで開いた。
思っていること： imageもCSSもないので当然動かない。
備考：

**Comment by emitsuco3** [comment]
作業: 手順通りで動かなかったので、一番下にあったExamplesのリンクを踏んだ。
思っていること： そこにリンクを貼ってくれるのは親切だなーと思った。
備考：

**Comment by emitsuco3** [comment]
作業: とりあえず一番上のリンクを開いた。
思っていること： これをよく使った。かつ、一番上なのできっとみんなこれを最初に見ると思う。
備考：

**Comment by emitsuco3** [comment]
作業: サイトに書かれてはいなかったけれど、cssフォルダとimageを作り、Examplesページのスライダーから画像を借用した。
思っていること： 例題のHTMLに記載されているimageの名前と、借用した物の名前が一致したので、もしかしたらみんなここからimageを持っていくのが前提とされている？
備考：

**Comment by emitsuco3** [comment]
作業: Examplesページに乗せられたHTMLに書き換え。
思っていること： imageの著作権がわからないので使ってよいのか分からない。でも例に出されているのと連動しているのは明白なので、使っていいならいいと書いていただけると良心的に素敵。
備考：

**Comment by emitsuco3** [comment]
bxSliderをゼロベースから触ってみようと思い、ダウンロードからやってみました。

Examplesページの例が、同梱されていると手元ですぐに動かして見れるので初心者に親切ではないかなーとおもいました。

**Comment by emitsuco3** [comment]
>修正

bxSliderをゼロベースから触ってみようと思い、ダウンロードからやってみました。

トップページのHow to installの手順通り使おうとしました。

>指示がなかったので勝手にHTMLファイルなどを作り、コピペ
->そのままでは動きませんでした。
>Examplesページの一番上のImage gallery with captionsを試してみる
->サンプルコードがあったので適宜修正して動かそうとしましたが、imageがないため動きませんでした。

Examplesページの例がimageと共に同梱されていると手元ですぐに動かして見れるので初心者に親切ではないかなーと思いました。

**Comment by emitsuco3** [comment]
## I want you to ship at the time of download an example of the Examples page.

>Since there was no instruction, I made an HTML file etc. arbitrarily,
I did not know whether I needed a file, the directory structure was unknown, and I could not see what kind of movement it would take.

>Try Image gallery with captions at the top of the Examples page
There was a sample code, so I tried to fix it and move it properly, but I could not move it for the same reason.

I thought that if the examples page that you can see immediately by moving it at hand is included in the download, it is kind to the beginner.

**Comment by emitsuco3** [comment]
## The full source codes of examples in jquery.bxslider.zip

To try bxSlider, I downloaded it from the top page of bxSlider, and tried to use it according to "How to install". But I don't know where to place it, what to be required. So I could not understand its behavior.

Also, I tried "Image gallery with captions" on the example pages, but I could not for the same reason.

Therefore, I think that the beginners can try bxSlider quickly if the full source codes of examples are included in `jquery.bxslider.zip`.

**Comment by kou** [comment]
おつかれさまでした！
[次回は2017-01-21に開催](https://oss-gate.doorkeeper.jp/events/54640)なので、ぜひメンター（あるいは再ビギナー）で参加してみてください！
