### ISSUE TITLE
OSS Gate Workshop: PHP Lovers: 2023-10-09: mp: laravel-breadcrumbs: Work log

### ISSUE THREAD

**Issue by mp-31** [oss-gate/workshop#1713]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mp-31** [comment]
diglactic/laravel-breadcrumbsに決めました。

**Comment by mp-31** [comment]
Read meを読み始める

**Comment by daipom** [comment]
オープンソースのライセンスについて

https://www.clear-code.com/blog/2022/4/6/introduction-to-free-software-license.html

**Comment by daipom** [comment]
Tinkerwell というサービスがあって、web上で動作確認できるかもしれない

https://web.tinkerwell.app/#/

**Comment by mp-31** [comment]
```
composer require diglactic/laravel-breadcrumbs
```
でbreadcrumbsを作成したプロジェクトにインストール

**Comment by daipom** [comment]
https://github.com/diglactic/laravel-breadcrumbs#contributing

> Documentation: If you think the documentation can be improved in any way, please do [edit this file](https://github.com/diglactic/laravel-breadcrumbs/edit/master/README.md) and make a pull request.

のリンクが404になりますね。
URLが間違っているみたい。
(`master`ブランチになっているが、今は`main`ブランチに名前が変わっている。ブランチ名を変えたときにリンクを更新し忘れた様子)

**Comment by mp-31** [comment]
以下のPRを投げました。
`https://github.com/diglactic/laravel-breadcrumbs/pull/72`
