### ISSUE TITLE
OSS Gate Workshop: PHP Lovers: 2023-10-09: ogi: guzzle: Work log

### ISSUE THREAD

**Issue by togishima** [oss-gate/workshop#1716]

**Comment by togishima** [comment]
phpstan/phpstan

**Comment by togishima** [comment]
simpleXML拡張がなかったためmakeが通らなかった
拡張をインストールしたら問題なく動いた

**Comment by togishima** [comment]
テストを回したところエラーで落ちた
```
ogi@XPS-13:~/oss/phpstan-src (1.11.x) $ make tests
php vendor/bin/paratest --runner WrapperRunner --no-coverage
ParaTest v6.6.3 upon PHPUnit 9.5.23 #StandWithUkraine

SSSSSSSSSSSSSSS..................SSSSSS....................    59 / 10442 (  0%)
...........................................................   118 / 10442 (  1%)
...........................................................   177 / 10442 (  1%)
..............................................S............   236 / 10442 (  2%)
...........................................................   295 / 10442 (  2%)
...........................................................   354 / 10442 (  3%)
............SSSS...........................................   413 / 10442 (  3%)
...........................................................   472 / 10442 (  4%)
.........SSSSSSS...............................SSSSSSSSSSSS   531 / 10442 (  5%)
SSSSS..............SSSSSSSSSSSSSSSSS....................SSS   590 / 10442 (  5%)
SSSSSSSSSS........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.........   649 / 10442 (  6%)
...........................................................   708 / 10442 (  6%)
...........................................................   767 / 10442 (  7%)
...........................................................   826 / 10442 (  7%)
...........................................................   885 / 10442 (  8%)
...........................................................   944 / 10442 (  9%)
...........................................................  1003 / 10442 (  9%)
...........................................................  1062 / 10442 ( 10%)
...........................................................  1121 / 10442 ( 10%)
...........................................................  1180 / 10442 ( 11%)
...........................................................  1239 / 10442 ( 11%)
...........................................................  1298 / 10442 ( 12%)
...........................................................  1357 / 10442 ( 12%)
...........................................................  1416 / 10442 ( 13%)
...........................................................  1475 / 10442 ( 14%)
...........................................................  1534 / 10442 ( 14%)
...........................................................  1593 / 10442 ( 15%)
...........................................................  1652 / 10442 ( 15%)
...........................................................  1711 / 10442 ( 16%)
...........................................................  1770 / 10442 ( 16%)
...........................................................  1829 / 10442 ( 17%)
...........................................................  1888 / 10442 ( 18%)
...........................................................  1947 / 10442 ( 18%)
...........................................................  2006 / 10442 ( 19%)
...........................................................  2065 / 10442 ( 19%)
...........................................................  2124 / 10442 ( 20%)
...........................................................  2183 / 10442 ( 20%)
...........................................................  2242 / 10442 ( 21%)
...........................................................  2301 / 10442 ( 22%)
...........................................................  2360 / 10442 ( 22%)
...........................................................  2419 / 10442 ( 23%)
...........................................................  2478 / 10442 ( 23%)
...........................................................  2537 / 10442 ( 24%)
...........................................................  2596 / 10442 ( 24%)
...........................................................  2655 / 10442 ( 25%)
...........................................................  2714 / 10442 ( 25%)
...........................................................  2773 / 10442 ( 26%)
...........................................................  2832 / 10442 ( 27%)
...........................................................  2891 / 10442 ( 27%)
...........................................................  2950 / 10442 ( 28%)
...........................................................  3009 / 10442 ( 28%)
...........................................................  3068 / 10442 ( 29%)
...........................................................  3127 / 10442 ( 29%)
...........................................................  3186 / 10442 ( 30%)
...........................................................  3245 / 10442 ( 31%)
...........................................................  3304 / 10442 ( 31%)
...........................................................  3363 / 10442 ( 32%)
...........................................................  3422 / 10442 ( 32%)
...........................................................  3481 / 10442 ( 33%)
...........................................................  3540 / 10442 ( 33%)
...........................................................  3599 / 10442 ( 34%)
...........................................................  3658 / 10442 ( 35%)
...........................................................  3717 / 10442 ( 35%)
...........................................................  3776 / 10442 ( 36%)
...........................................................  3835 / 10442 ( 36%)
...........................................................  3894 / 10442 ( 37%)
...........................................................  3953 / 10442 ( 37%)
.F.........................................................  4012 / 10442 ( 38%)
...........................................................  4071 / 10442 ( 38%)
...........................................................  4130 / 10442 ( 39%)
...........................................................  4189 / 10442 ( 40%)
...........................................................  4248 / 10442 ( 40%)
...........................................................  4307 / 10442 ( 41%)
...........................................................  4366 / 10442 ( 41%)
...........................................................  4425 / 10442 ( 42%)
...........................................................  4484 / 10442 ( 42%)
...........................................................  4543 / 10442 ( 43%)
...........................................................  4602 / 10442 ( 44%)
...........................................................  4661 / 10442 ( 44%)
...........................................................  4720 / 10442 ( 45%)
...........................................................  4779 / 10442 ( 45%)
...........................................................  4838 / 10442 ( 46%)
...........................................................  4897 / 10442 ( 46%)
...........................................................  4956 / 10442 ( 47%)
...........................................................  5015 / 10442 ( 48%)
...........................................................  5074 / 10442 ( 48%)
...........................................................  5133 / 10442 ( 49%)
...........................................................  5192 / 10442 ( 49%)
...........................................................  5251 / 10442 ( 50%)
...........................................................  5310 / 10442 ( 50%)
...........................................................  5369 / 10442 ( 51%)
...........................................................  5428 / 10442 ( 51%)
...........................................................  5487 / 10442 ( 52%)
...........................................................  5546 / 10442 ( 53%)
...........................................................  5605 / 10442 ( 53%)
...........................................................  5664 / 10442 ( 54%)
...........................................................  5723 / 10442 ( 54%)
...........................................................  5782 / 10442 ( 55%)
...........................................................  5841 / 10442 ( 55%)
...........................................................  5900 / 10442 ( 56%)
...........................................................  5959 / 10442 ( 57%)
...........................................................  6018 / 10442 ( 57%)
...........................................................  6077 / 10442 ( 58%)
.................................................SSSSSSS...  6136 / 10442 ( 58%)
.....................................................SSS...  6195 / 10442 ( 59%)
...............ES..........................................  6254 / 10442 ( 59%)
...........................................................  6313 / 10442 ( 60%)
................................SS.........................  6372 / 10442 ( 61%)
...........................................................  6431 / 10442 ( 61%)
...........................................................  6490 / 10442 ( 62%)
...........................................................  6549 / 10442 ( 62%)
...........................................................  6608 / 10442 ( 63%)
...........................................................  6667 / 10442 ( 63%)
...........................................................  6726 / 10442 ( 64%)
...........................................................  6785 / 10442 ( 64%)
...........................................................  6844 / 10442 ( 65%)
...........................................................  6903 / 10442 ( 66%)
...........................................................  6962 / 10442 ( 66%)
...........................................................  7021 / 10442 ( 67%)
...........................................................  7080 / 10442 ( 67%)
...........................................................  7139 / 10442 ( 68%)
...........................................................  7198 / 10442 ( 68%)
...........................................................  7257 / 10442 ( 69%)
...........................................................  7316 / 10442 ( 70%)
...........................................................  7375 / 10442 ( 70%)
...........................................................  7434 / 10442 ( 71%)
...........................................................  7493 / 10442 ( 71%)
...........................................................  7552 / 10442 ( 72%)
...........................................................  7611 / 10442 ( 72%)
...........................................................  7670 / 10442 ( 73%)
...........................................................  7729 / 10442 ( 74%)
...........................................................  7788 / 10442 ( 74%)
...........................................................  7847 / 10442 ( 75%)
...........................................................  7906 / 10442 ( 75%)
...........................................................  7965 / 10442 ( 76%)
...........................................................  8024 / 10442 ( 76%)
...........................................................  8083 / 10442 ( 77%)
...........................................................  8142 / 10442 ( 77%)
...........................................................  8201 / 10442 ( 78%)
...........................................................  8260 / 10442 ( 79%)
...........................................................  8319 / 10442 ( 79%)
...........................................................  8378 / 10442 ( 80%)
...........................................................  8437 / 10442 ( 80%)
...........................................................  8496 / 10442 ( 81%)
...........................................................  8555 / 10442 ( 81%)
...........................................................  8614 / 10442 ( 82%)
...........................................................  8673 / 10442 ( 83%)
...........................................................  8732 / 10442 ( 83%)
...........................................................  8791 / 10442 ( 84%)
.............................................S.............  8850 / 10442 ( 84%)
...........................................................  8909 / 10442 ( 85%)
...........................................................  8968 / 10442 ( 85%)
...........................................................  9027 / 10442 ( 86%)
........S..................................................  9086 / 10442 ( 87%)
...........................................................  9145 / 10442 ( 87%)
...........................................................  9204 / 10442 ( 88%)
...........................................................  9263 / 10442 ( 88%)
..................................SS.......................  9322 / 10442 ( 89%)
............S..............................................  9381 / 10442 ( 89%)
.........................................S.................  9440 / 10442 ( 90%)
................S..........................................  9499 / 10442 ( 90%)
...........................................................  9558 / 10442 ( 91%)
...........................................................  9617 / 10442 ( 92%)
......................S....................................  9676 / 10442 ( 92%)
..............FS...........................................  9735 / 10442 ( 93%)
...........................................................  9794 / 10442 ( 93%)
.............................................S.............  9853 / 10442 ( 94%)
...........................................................  9912 / 10442 ( 94%)
.....................................S.....................  9971 / 10442 ( 95%)
....................SSS.................................... 10030 / 10442 ( 96%)
........................................................... 10089 / 10442 ( 96%)
........................................................... 10148 / 10442 ( 97%)
..................................................S........ 10207 / 10442 ( 97%)
........................................................... 10266 / 10442 ( 98%)
........................................................... 10325 / 10442 ( 98%)
........................................................... 10384 / 10442 ( 99%)
..........................................................  10442 / 10442 (100%)

Time: 09:11.665, Memory: 728.50 MB

There was 1 error:

1) Error
The data provider specified for PHPStan\Analyser\NodeScopeResolverTest::testFileAsserts is invalid.
Error: Class "EnumTypeAssertions\Foo" not found
/home/ogi/oss/phpstan-src/tests/PHPStan/Analyser/NodeScopeResolverTest.php:635

---

There were 2 failures:

1) PHPStan\Type\Constant\ConstantStringTypeTest::testTextInvalidEncoding
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-''Lorem ipsum dolor s…''
+''Lorem ipsum dolor sit''

/home/ogi/oss/phpstan-src/tests/PHPStan/Type/Constant/ConstantStringTypeTest.php:167

2) PHPStan\Rules\Functions\CallToFunctionParametersRuleTest::testCurlSetOpt
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'10: Parameter #3 $value of function curl_setopt expects 0|2, bool given.
-16: Parameter #3 $value of function curl_setopt expects non-empty-string, int given.
-17: Parameter #3 $value of function curl_setopt expects array<int, string>, int given.
-19: Parameter #3 $value of function curl_setopt expects bool, int given.
-20: Parameter #3 $value of function curl_setopt expects bool, string given.
-22: Parameter #3 $value of function curl_setopt expects int, string given.
-24: Parameter #3 $value of function curl_setopt expects array, string given.
-26: Parameter #3 $value of function curl_setopt expects resource, string given.
-28: Parameter #3 $value of function curl_setopt expects array|string, int given.
-67: Parameter #3 $value of function curl_setopt expects array<int, string>, array<string, string> given.
+'
 '

/home/ogi/oss/phpstan-src/src/Testing/RuleTestCase.php:156
/home/ogi/oss/phpstan-src/tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php:1203

FAILURES!                                                            
Tests: 10365, Assertions: 82155, Errors: 1, Failures: 2, Skipped: 63.
make: *** [Makefile:6: tests] エラー 2

```

**Comment by togishima** [comment]
PHPUnitを動かすのにmb-stringが不足していた模様

**Comment by togishima** [comment]
ogi@XPS-13:~/oss/phpstan-src (1.11.x) $ make tests
php vendor/bin/paratest --runner WrapperRunner --no-coverage
ParaTest v6.6.3 upon PHPUnit 9.5.23 #StandWithUkraine

SSSSSSSSSSSSSSS..................SSSSSS....................    59 / 10442 (  0%)
...........................................................   118 / 10442 (  1%)
...........................................................   177 / 10442 (  1%)
..............................................S............   236 / 10442 (  2%)
...........................................................   295 / 10442 (  2%)
...........................................................   354 / 10442 (  3%)
............SSSS...........................................   413 / 10442 (  3%)
...........................................................   472 / 10442 (  4%)
.........SSSSSSS...............................SSSSSSSSSSSS   531 / 10442 (  5%)
SSSSS..............SSSSSSSSSSSSSSSSS....................SSS   590 / 10442 (  5%)
SSSSSSSSSS........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.........   649 / 10442 (  6%)
...........................................................   708 / 10442 (  6%)
...........................................................   767 / 10442 (  7%)
...........................................................   826 / 10442 (  7%)
...........................................................   885 / 10442 (  8%)
...........................................................   944 / 10442 (  9%)
...........................................................  1003 / 10442 (  9%)
...........................................................  1062 / 10442 ( 10%)
...........................................................  1121 / 10442 ( 10%)
...........................................................  1180 / 10442 ( 11%)
...........................................................  1239 / 10442 ( 11%)
...........................................................  1298 / 10442 ( 12%)
...........................................................  1357 / 10442 ( 12%)
...........................................................  1416 / 10442 ( 13%)
...........................................................  1475 / 10442 ( 14%)
...........................................................  1534 / 10442 ( 14%)
...........................................................  1593 / 10442 ( 15%)
...........................................................  1652 / 10442 ( 15%)
...........................................................  1711 / 10442 ( 16%)
...........................................................  1770 / 10442 ( 16%)
...........................................................  1829 / 10442 ( 17%)
...........................................................  1888 / 10442 ( 18%)
...........................................................  1947 / 10442 ( 18%)
...........................................................  2006 / 10442 ( 19%)
...........................................................  2065 / 10442 ( 19%)
...........................................................  2124 / 10442 ( 20%)
...........................................................  2183 / 10442 ( 20%)
...........................................................  2242 / 10442 ( 21%)
...........................................................  2301 / 10442 ( 22%)
...........................................................  2360 / 10442 ( 22%)
...........................................................  2419 / 10442 ( 23%)
...........................................................  2478 / 10442 ( 23%)
...........................................................  2537 / 10442 ( 24%)
...........................................................  2596 / 10442 ( 24%)
...........................................................  2655 / 10442 ( 25%)
...........................................................  2714 / 10442 ( 25%)
...........................................................  2773 / 10442 ( 26%)
...........................................................  2832 / 10442 ( 27%)
...........................................................  2891 / 10442 ( 27%)
...........................................................  2950 / 10442 ( 28%)
...........................................................  3009 / 10442 ( 28%)
...........................................................  3068 / 10442 ( 29%)
...........................................................  3127 / 10442 ( 29%)
...........................................................  3186 / 10442 ( 30%)
...........................................................  3245 / 10442 ( 31%)
...........................................................  3304 / 10442 ( 31%)
...........................................................  3363 / 10442 ( 32%)
...........................................................  3422 / 10442 ( 32%)
...........................................................  3481 / 10442 ( 33%)
...........................................................  3540 / 10442 ( 33%)
...........................................................  3599 / 10442 ( 34%)
...........................................................  3658 / 10442 ( 35%)
...........................................................  3717 / 10442 ( 35%)
...........................................................  3776 / 10442 ( 36%)
...........................................................  3835 / 10442 ( 36%)
...........................................................  3894 / 10442 ( 37%)
...........................................................  3953 / 10442 ( 37%)
.F.........................................................  4012 / 10442 ( 38%)
...........................................................  4071 / 10442 ( 38%)
...........................................................  4130 / 10442 ( 39%)
...........................................................  4189 / 10442 ( 40%)
...........................................................  4248 / 10442 ( 40%)
...........................................................  4307 / 10442 ( 41%)
...........................................................  4366 / 10442 ( 41%)
...........................................................  4425 / 10442 ( 42%)
...........................................................  4484 / 10442 ( 42%)
...........................................................  4543 / 10442 ( 43%)
...........................................................  4602 / 10442 ( 44%)
...........................................................  4661 / 10442 ( 44%)
...........................................................  4720 / 10442 ( 45%)
...........................................................  4779 / 10442 ( 45%)
...........................................................  4838 / 10442 ( 46%)
...........................................................  4897 / 10442 ( 46%)
...........................................................  4956 / 10442 ( 47%)
...........................................................  5015 / 10442 ( 48%)
...........................................................  5074 / 10442 ( 48%)
...........................................................  5133 / 10442 ( 49%)
...........................................................  5192 / 10442 ( 49%)
...........................................................  5251 / 10442 ( 50%)
...........................................................  5310 / 10442 ( 50%)
...........................................................  5369 / 10442 ( 51%)
...........................................................  5428 / 10442 ( 51%)
...........................................................  5487 / 10442 ( 52%)
...........................................................  5546 / 10442 ( 53%)
...........................................................  5605 / 10442 ( 53%)
...........................................................  5664 / 10442 ( 54%)
...........................................................  5723 / 10442 ( 54%)
...........................................................  5782 / 10442 ( 55%)
...........................................................  5841 / 10442 ( 55%)
...........................................................  5900 / 10442 ( 56%)
...........................................................  5959 / 10442 ( 57%)
...........................................................  6018 / 10442 ( 57%)
...........................................................  6077 / 10442 ( 58%)
.................................................SSSSSSS...  6136 / 10442 ( 58%)
.....................................................SSS...  6195 / 10442 ( 59%)
...............ES..........................................  6254 / 10442 ( 59%)
...........................................................  6313 / 10442 ( 60%)
................................SS.........................  6372 / 10442 ( 61%)
...........................................................  6431 / 10442 ( 61%)
...........................................................  6490 / 10442 ( 62%)
...........................................................  6549 / 10442 ( 62%)
...........................................................  6608 / 10442 ( 63%)
...........................................................  6667 / 10442 ( 63%)
...........................................................  6726 / 10442 ( 64%)
...........................................................  6785 / 10442 ( 64%)
...........................................................  6844 / 10442 ( 65%)
...........................................................  6903 / 10442 ( 66%)
...........................................................  6962 / 10442 ( 66%)
...........................................................  7021 / 10442 ( 67%)
...........................................................  7080 / 10442 ( 67%)
...........................................................  7139 / 10442 ( 68%)
...........................................................  7198 / 10442 ( 68%)
...........................................................  7257 / 10442 ( 69%)
...........................................................  7316 / 10442 ( 70%)
...........................................................  7375 / 10442 ( 70%)
...........................................................  7434 / 10442 ( 71%)
...........................................................  7493 / 10442 ( 71%)
...........................................................  7552 / 10442 ( 72%)
...........................................................  7611 / 10442 ( 72%)
...........................................................  7670 / 10442 ( 73%)
...........................................................  7729 / 10442 ( 74%)
...........................................................  7788 / 10442 ( 74%)
...........................................................  7847 / 10442 ( 75%)
...........................................................  7906 / 10442 ( 75%)
...........................................................  7965 / 10442 ( 76%)
...........................................................  8024 / 10442 ( 76%)
...........................................................  8083 / 10442 ( 77%)
...........................................................  8142 / 10442 ( 77%)
...........................................................  8201 / 10442 ( 78%)
...........................................................  8260 / 10442 ( 79%)
...........................................................  8319 / 10442 ( 79%)
...........................................................  8378 / 10442 ( 80%)
...........................................................  8437 / 10442 ( 80%)
...........................................................  8496 / 10442 ( 81%)
...........................................................  8555 / 10442 ( 81%)
...........................................................  8614 / 10442 ( 82%)
...........................................................  8673 / 10442 ( 83%)
...........................................................  8732 / 10442 ( 83%)
...........................................................  8791 / 10442 ( 84%)
.............................................S.............  8850 / 10442 ( 84%)
...........................................................  8909 / 10442 ( 85%)
...........................................................  8968 / 10442 ( 85%)
...........................................................  9027 / 10442 ( 86%)
........S..................................................  9086 / 10442 ( 87%)
...........................................................  9145 / 10442 ( 87%)
...........................................................  9204 / 10442 ( 88%)
...........................................................  9263 / 10442 ( 88%)
..................................SS.......................  9322 / 10442 ( 89%)
............S..............................................  9381 / 10442 ( 89%)
.........................................S.................  9440 / 10442 ( 90%)
................S..........................................  9499 / 10442 ( 90%)
...........................................................  9558 / 10442 ( 91%)
...........................................................  9617 / 10442 ( 92%)
......................S....................................  9676 / 10442 ( 92%)
..............FS...........................................  9735 / 10442 ( 93%)
...........................................................  9794 / 10442 ( 93%)
.............................................S.............  9853 / 10442 ( 94%)
...........................................................  9912 / 10442 ( 94%)
.....................................S.....................  9971 / 10442 ( 95%)
....................SSS.................................... 10030 / 10442 ( 96%)
........................................................... 10089 / 10442 ( 96%)
........................................................... 10148 / 10442 ( 97%)
..................................................S........ 10207 / 10442 ( 97%)
........................................................... 10266 / 10442 ( 98%)
........................................................... 10325 / 10442 ( 98%)
........................................................... 10384 / 10442 ( 99%)
..........................................................  10442 / 10442 (100%)

Time: 09:11.665, Memory: 728.50 MB

There was 1 error:

1) Error
The data provider specified for PHPStan\Analyser\NodeScopeResolverTest::testFileAsserts is invalid.
Error: Class "EnumTypeAssertions\Foo" not found
/home/ogi/oss/phpstan-src/tests/PHPStan/Analyser/NodeScopeResolverTest.php:635

---

There were 2 failures:

1) PHPStan\Type\Constant\ConstantStringTypeTest::testTextInvalidEncoding
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-''Lorem ipsum dolor s…''
+''Lorem ipsum dolor sit''

/home/ogi/oss/phpstan-src/tests/PHPStan/Type/Constant/ConstantStringTypeTest.php:167

2) PHPStan\Rules\Functions\CallToFunctionParametersRuleTest::testCurlSetOpt
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'10: Parameter #3 $value of function curl_setopt expects 0|2, bool given.
-16: Parameter #3 $value of function curl_setopt expects non-empty-string, int given.
-17: Parameter #3 $value of function curl_setopt expects array<int, string>, int given.
-19: Parameter #3 $value of function curl_setopt expects bool, int given.
-20: Parameter #3 $value of function curl_setopt expects bool, string given.
-22: Parameter #3 $value of function curl_setopt expects int, string given.
-24: Parameter #3 $value of function curl_setopt expects array, string given.
-26: Parameter #3 $value of function curl_setopt expects resource, string given.
-28: Parameter #3 $value of function curl_setopt expects array|string, int given.
-67: Parameter #3 $value of function curl_setopt expects array<int, string>, array<string, string> given.
+'
 '

/home/ogi/oss/phpstan-src/src/Testing/RuleTestCase.php:156
/home/ogi/oss/phpstan-src/tests/PHPStan/Rules/Functions/CallToFunctionParametersRuleTest.php:1203

FAILURES!                                                            
Tests: 10365, Assertions: 82155, Errors: 1, Failures: 2, Skipped: 63.
make: *** [Makefile:6: tests] エラー 2

**Comment by togishima** [comment]
`composer dump-autoload` を実行

**Comment by muno92** [comment]
> Error: Class "EnumTypeAssertions\Foo" not found

PHPStanのテスト用のファイルは作成基準ないので、あまりPSR-4とか考えられていないですね。

**Comment by togishima** [comment]
1.11.x　から　1.10.xブランチへスイッチ
composer installをしたところパッケージ関連のエラー？
一旦composer.lockを削除した上で再度composer install

**Comment by togishima** [comment]
```
  Problem 1
    - Root composer.json requires phpstan/phpstan-deprecation-rules 1.2.x-dev -> satisfiable by phpstan/phpstan-deprecation-rules[1.2.x-dev].
    - phpstan/phpstan-deprecation-rules 1.2.x-dev requires phpstan/phpstan ^1.11 -> found phpstan/phpstan[1.11.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - Root composer.json requires phpstan/phpstan-strict-rules 1.5.x-dev -> satisfiable by phpstan/phpstan-strict-rules[1.5.x-dev].
    - phpstan/phpstan-strict-rules 1.5.x-dev requires phpstan/phpstan ^1.11 -> found phpstan/phpstan[1.11.x-dev] but these were not loaded, likely because it conflicts with another require.
```

**Comment by togishima** [comment]
１回再度ブランチを消してvendorディレクトリ、composer.lockを削除して再度入れ直し

**Comment by 77web** [comment]
https://github.com/barryvdh/laravel-debugbar/actions/runs/6240544858/job/16940866509

**Comment by togishima** [comment]
環境の問題を解決することができず...一旦断念。

**Comment by togishima** [comment]
比較的テストなどが軽そうなGuzzleのIssueに関して調査
結果：Issue起票者が使用しているGuzzleのバージョンが古くEOLのものだった

Issueコメントにて

 1. 起票者が使用しているバージョンがサポートされていない旨
 2. 対象コードが別リポジトリに移動済である旨

の2点を回答

**Comment by togishima** [comment]
https://github.com/guzzle/guzzle/issues/3155#issuecomment-1752443357
