### ISSUE TITLE
OSS Gate Workshop: online: 2023-12-09: daipom: survey-sh: Work log

### ISSUE THREAD

**Issue by daipom** [oss-gate/workshop#1741]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daipom** [comment]
OSS何にしよう。

**Comment by daipom** [comment]
blacktoadさんが、OSS Gateワークショップ用のアンケート回答ツールを作ってくださった！

* https://github.com/blacktoad30/survey-sh

**Comment by daipom** [comment]
これに興味があるので、本日はこれをやってみたい

**Comment by daipom** [comment]
ライセンス調べる

**Comment by daipom** [comment]
https://github.com/blacktoad30/survey-sh を確認するとラインセスは

Creative Commons Zero v1.0 Universal

**Comment by daipom** [comment]
これは https://opensource.org/licenses/ にはないけど、blacktoadさん本人に確認すると、オープンソースだと思ってもらって良いということなので、今日はこれをやります。

**Comment by daipom** [comment]
ドキュメントとして、このリポジトリーのREADMEを読みながら触ってみる

**Comment by daipom** [comment]
説明どおりに次のコマンドを実行してみる。

```
$ ./survey.sh -t beginner -u alice
```

すると、 .....

**Comment by daipom** [comment]
引数を省略できるらしい

```
$ ./survey.sh
```

すると`Input your usertype`というものを聞かれる。
`beginner`と入力すると、次に進める。
だけど、何を入力できるのかがわからないことが気になる。

**Comment by daipom** [comment]
引数を省略して実行した時に、選択可能なusertypeがわからなくて困る。スペルミスしそう。
なので、最初に選択可能なusertypeを一覧を表示するようにしたら使いやすいと思う。

**Comment by daipom** [comment]
日本で自由に書いてみる。

**Comment by daipom** [comment]
PRで直す！

**Comment by daipom** [comment]
PRを作りました: https://github.com/blacktoad30/survey-sh/pull/1

**Comment by blacktoad30** [comment]
@daipom マージさせていただきました。ありがとうございました!
