### ISSUE TITLE
OSS Gate Workshop: online: 2023-12-09: sochi419: ESLint: Work log

### ISSUE THREAD

**Issue by sochi419** [oss-gate/workshop#1742]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sochi419** [comment]
OSS何にしよう。

**Comment by sochi419** [comment]
お題を決めたい。

下記を参考に
ワークショップで扱うOSSの決め方: https://www.youtube.com/watch?v=ABt3_brLS1g

こちらのyoutubeでの説明にあった通り、まずは自分のよく使うサービスを挙げてみる。

**Comment by sochi419** [comment]
- skyscannar
- booking.com
- google map
- github
- はてなブログ
- deepL
- chatGPT
- rails ガイド or チュートリアル
- vscode
- discord
- qiita
- yahoo

**Comment by sochi419** [comment]
1つ1つ、ライセンス表記がhttps://opensource.org/licenses/に載っているかを確認してOSSであるものを絞り込む。

**Comment by sochi419** [comment]
<img width="1100" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/590f5d29-f674-4761-9531-fb31607c0da5">

https://opensource.org/licenses/  に載っているライセンス群から、自分の知っているものを選ぶ方式に変更

**Comment by sochi419** [comment]
<img width="1209" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/dfa55928-29f6-4ac5-aea0-3bcdae026716">

`The PostgreSQL Licence`は使ったことがあるな。これにしようかな。

**Comment by sochi419** [comment]
postgreSQLをgithub上で探す。

https://github.com/postgres

<img width="1003" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/7fa4f69f-a7f5-4348-8ebb-91a528622018">

**Comment by sochi419** [comment]
<img width="912" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/561aa402-e7bb-4c70-89e8-6f51c06d30a0">

Repositoriesが５個ある。一番上のpostgresのことかな

**Comment by sochi419** [comment]
READMEを読む。

https://github.com/postgres/postgres#readme

PostgreSQL Database Management System
=====================================

This directory contains the source code distribution of the PostgreSQL
database management system.

PostgreSQL is an advanced object-relational database management system
that supports an extended subset of the SQL standard, including
transactions, foreign keys, subqueries, triggers, user-defined types
and functions.  This distribution also contains C language bindings.

See the file INSTALL for instructions on how to build and install
PostgreSQL.  That file also lists supported operating systems and
hardware platforms and contains information regarding any other
software packages that are required to build or run the PostgreSQL
system.  Copyright and license information can be found in the
file COPYRIGHT.  A comprehensive documentation set is included in this
distribution; it can be read as described in the installation
instructions.

The latest version of this software, and related software, may be
obtained at https://www.postgresql.org/download/.  For more information
look at our web site located at https://www.postgresql.org/.

**Comment by sochi419** [comment]
以下、日本語訳。

---------

このディレクトリには、PostgreSQL
データベース管理システムのソースコード配布が含まれます。

PostgreSQLは先進的なオブジェクトリレーショナルデータベース管理システムです。
標準SQLの拡張サブセットをサポートしています。
トランザクション、外部キー、サブクエリ、トリガ、ユーザ定義型
関数を含むSQL標準の拡張サブセットをサポートしています。このディストリビューションにはC言語バインディングも含まれています。

PostgreSQLの構築とインストール方法については、INSTALLファイルを参照してください。
ファイルを参照してください。このファイルには、サポートされるオペレーティングシステムと
対応するオペレーティングシステムとハードウェアプラットフォームが記載されています。
PostgreSQLシステムの構築や実行に必要な他のソフトウェアパッケージに関する情報も含まれています。
システムの構築や実行に必要な他のソフトウェアパッケージに関する情報も含まれています。著作権とライセンスに関する情報は
ファイルにあります。この配布物には包括的な文書一式が含まれています。
この配布物には包括的な文書一式が含まれています。

の説明に従ってお読みください。

本ソフトウェアおよび関連ソフトウェアの最新バージョンは、。
https://www.postgresql.org/download/ で入手できます。詳細は
https://www.postgresql.org/ にある当社のウェブサイトをご覧ください。

--------
以下の部分で、こちらのサイトからインストールしてくださいと記載がある。
> The latest version of this software, and related software, may be
obtained at https://www.postgresql.org/download/. For more information
look at our web site located at https://www.postgresql.org/.

リンク先のサイトからインストールを試して、
- まずインストールができるかどうか
- 不便なところはないか
を考えることにする。

**Comment by sochi419** [comment]
postgreSQLダウンロードサイトにいく。

https://www.postgresql.org/download/

**Comment by sochi419** [comment]
macOSを選択する。

<img width="1112" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/9ae9f2a6-4edd-4abe-9a01-c0efa994ae3f">

**Comment by sochi419** [comment]
macOSを選択すると、以下のページに遷移した。

https://www.postgresql.org/download/macosx/

どうやってインストールすればいいか読んでいく。

**Comment by sochi419** [comment]
[Download the installer](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) certified by EDB for all supported PostgreSQL versions.

> サポートされているすべてのPostgreSQLバージョンについて、EDBによって認証されたインストーラをダウンロードしてください。

EDBによって認証されたインストーラとはなんだろう

**Comment by sochi419** [comment]
PostgreSQLは大きめのサイトなので、contributeは難しいかも？
もし断念するなら、railsガイドをやるのもありかもね？

**Comment by sochi419** [comment]
以下のアドバイスをいただいた。下記サイトから探してみる

> 下記のサイトで挙げられているソフトウェアは OSS なことが多いので、少し参考になるかもです。

https://goofi.vercel.app/?language=ruby

**Comment by sochi419** [comment]
vscode 拡張機能案

- ESlint
- Prettier

**Comment by sochi419** [comment]
- ESLint
https://github.com/prettier/eslint-plugin-prettier

**Comment by sochi419** [comment]
正しいESLintのサイト

https://github.com/Microsoft/vscode-eslint

**Comment by sochi419** [comment]
上記のESLintをテーマに決定しました。

- ライセンス
https://github.com/microsoft/vscode-eslint/blob/main/License.txt

MITの記述あり。

<img width="1103" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/a8b01870-f997-4c23-8636-cf635648945e">

**Comment by sochi419** [comment]
自分が使っているversion2.4.2に関するリリースノートが書かれていない。

以下は自分の使っているversionである。 2.4.2であることを確認できる。
![image](https://github.com/oss-gate/workshop/assets/92995093/27f394c1-2c57-49bc-be37-e4dc4c39fbed)

github上( https://github.com/Microsoft/vscode-eslint )では、version2.4.1までしか記載されていない。
<img width="918" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/59a367ea-8df8-4f3c-8051-b3b261a56d8a">

**Comment by daipom** [comment]
> 自分が使っているversion2.4.2に関するリリースノートが書かれていない。

おお！いい着眼点ですね！
理由はわからないですが、ブランチが別なようです。

https://github.com/microsoft/vscode-eslint/tree/release/2.4.2

こちらのブランチだとかかれている。

**Comment by sochi419** [comment]
リリースノートがversion 2.4.1で止まっていることを指摘するissueを立ててもいいかもしれない。

一応自分のESLintのversionである2.4.2であるかをこれから確認する。

**Comment by sochi419** [comment]
issue案1. mainブランチのリリースノートにversion2.4.2が含まれていないのは何故かを聞く。

- mainブランチ
<img width="1059" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/a4503b52-bad1-4521-9a91-63d2b8477b7a">

- release/2.4.2 ブランチ
<img width="1038" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/8957401f-7f29-4b3e-a31f-b896cb6624f9">

なぜrelease/2.4.2ブランチを統合しないのか。

このissueはこれ以上何も案が思い浮かばなかったらこれを聞く予定。

**Comment by sochi419** [comment]
issue案2. READMEの下記の文章について、
<img width="840" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/e8366282-4102-4ce8-98a2-bbd493f7cf5d">

ESLintのリンク先とdocumationのリンク先は同じである。わざわざ違う名前のリンク名にせずに同じ名前に統合をするissue

**Comment by daipom** [comment]
> > 自分が使っているversion2.4.2に関するリリースノートが書かれていない。
> 
> おお！いい着眼点ですね！ 理由はわからないですが、ブランチが別なようです。
> 
> https://github.com/microsoft/vscode-eslint/tree/release/2.4.2
> 
> こちらのブランチだとかかれている。

ブランチは次のようになってる。
一般的に、リリース済みの安定版と新機能開発とを分けて管理するために、mainとreleaseブランチを分けるというのは理解できる話だが、今回はこの「Prepare 2.4.2 release」コミット(https://github.com/microsoft/vscode-eslint/commit/94eff7110841350f60929fb6021c36b24dfddaf0)自体がmainに入っていないのは不思議だ。。
(2.4.2のリリースが反映されていない状態でmainの開発が進んでしまっている、意図が分からない)
「なんで https://github.com/microsoft/vscode-eslint/commit/94eff7110841350f60929fb6021c36b24dfddaf0 をmainに入れないんですか？」みたいなissueを立てるのはあり得るかもしれない。

![Screenshot from 2023-12-09 17-12-20](https://github.com/oss-gate/workshop/assets/12229857/b0ae025d-7dc2-4956-90ee-9ac195136088)

**Comment by sochi419** [comment]
issue案3 リリースノートのversionの数字が、赤字の部分だけ2.2.3、それ以外は`2.2.3`のようになっている。
<img width="875" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/db2575ea-605c-4a6d-81a8-b522420a3d4a">

**Comment by daipom** [comment]
> issue案2. READMEの下記の文章について、 
> ESLintのリンク先とdocumationのリンク先は同じである。わざわざ違う名前のリンク名にせずに同じ名前に統合をするissue

いいですね！
もしくは`documentation`の方のリンクを https://eslint.org/docs/latest/ に変更する、というPRを作ってみてもいいかもしれないです！

**Comment by sochi419** [comment]
案１で進めようと考えています。

**Comment by daipom** [comment]
> 正しいESLintのサイト
> 
> https://github.com/Microsoft/vscode-eslint

**Comment by sochi419** [comment]
````
I am using version `2.4.2` of ESLint, but version `2.4.2` is not included in the release notes of the main branch. Is there a reason for this?

# main branch
<img width="1059" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/a4503b52-bad1-4521-9a91-63d2b8477b7a">

There is no mention of version `2.4.2` in the release notes for the main branch.

# `release/2.4.2 branch`
<img width="1038" alt="image" src="https://github.com/oss-gate/workshop/assets/92995093/8957401f-7f29-4b3e-a31f-b896cb6624f9">

The release notes for the `release/2.4.2` branch have information about version `2.4.2.`
Why not merge the `release/2.4.2` branch into the main branch?
````

**Comment by sochi419** [comment]
issueを立てました。

https://github.com/microsoft/vscode-eslint/issues/1746
