### ISSUE TITLE
OSS Gate Workshop: online: 2023-12-09: 湊: サバイバルTypeScript: Work log

### ISSUE THREAD

**Issue by ueferi** [oss-gate/workshop#1743]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ueferi** [comment]
[サバイバルTypeScript](https://typescriptbook.jp/)のハンズオン教材に取り組みながら、フィードバックできることがないか探してみたい。

**Comment by ueferi** [comment]
GitHubリポジトリ: https://github.com/yytypescript/book

**Comment by ueferi** [comment]
ライセンスの記載はないがREADMEに  
> 本書はオープンソースです  

と書かれているので、大丈夫そう。

README : https://github.com/yytypescript/book/blob/master/README.md

**Comment by ueferi** [comment]
[作って学ぶTypeScript](https://typescriptbook.jp/tutorials)の中の、[Next.jsで猫画像ジェネレーターを作ろう](https://typescriptbook.jp/tutorials/nextjs)をやってみる。

**Comment by blacktoad30** [comment]
> ライセンスの記載はないがREADMEに
> 
> > 本書はオープンソースです
> 
> と書かれているので、大丈夫そう。
> 
> README : https://github.com/yytypescript/book/blob/master/README.md

すみません。ちょっとその調べ方ではNGかな、と思いました。
https://typescriptbook.jp/license
こちらのページににライセンスについて述べられています。

**Comment by ueferi** [comment]
> > ライセンスの記載はないがREADMEに
> > > 本書はオープンソースです
> > 
> > 
> > と書かれているので、大丈夫そう。
> > README : https://github.com/yytypescript/book/blob/master/README.md
> 
> すみません。ちょっとその調べ方ではNGかな、と思いました。 https://typescriptbook.jp/license こちらのページでライセンスについて述べられています。

ご指摘ありがとうございます。訂正します。  
ライセンスページに、CC BY-SA 4.0とMIT Licenseで公開していると書かれていました。
- CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/deed.ja 
- MIT License: https://opensource.org/license/mit/

**Comment by ueferi** [comment]
完成形のソースコードを参考に、`random-cat`という名前でローカルにディレクトリを作成します。  
`mkdir random-cat`  

チュートリアル「Next.jsで猫画像ジェネレーターを作ろう」の完成版コード: https://github.com/yytypescript/random-cat

**Comment by ueferi** [comment]
パッケージ管理ツールのYarnをインストールします。  
`npm install -g yarn`

**Comment by blacktoad30** [comment]
IDEA: ソースコードにライセンスファイルを含める

ドキュメント内でライセンスについて言及されているが、ソースコードにはライセンスファイルが見当たらない。

e.g.
[Rustのリポジトリ](https://github.com/rust-lang/rust/tree/master/LICENSES)

**Comment by ueferi** [comment]
実際にご指摘頂くまでドキュメントにはライセンスの記載があることに気が付きませんでした。
Issueを立てて提案したいと思います。

**Comment by ueferi** [comment]
サバイバルTypeScriptの執筆に関するページ: https://typescriptbook.jp/writing

**Comment by ueferi** [comment]
執筆会のDiscordコミュニティに入った方がよいかも？  
https://typescriptbook.jp/writing/contributing

**Comment by ueferi** [comment]
ソースコードには「本書はオープンソースです」と記載されているが、
ドキュメントのライセンスページを見に行かないと何のライセンスが適用されるか分からない。

ソースコード内にライセンスについての言及があると良いと思った。

**Comment by ueferi** [comment]
ドキュメントの[はじめて執筆する方へ](https://typescriptbook.jp/writing/getting-started)ページに、
> 改善点が見つかってもすぐに着手せず、まずはissueにて話し合いを行う必要があります。  

と書かれている。

**Comment by blacktoad30** [comment]
> ドキュメントの[はじめて執筆する方へ](https://typescriptbook.jp/writing/getting-started)ページに、
> 
> > 改善点が見つかってもすぐに着手せず、まずはissueにて話し合いを行う必要があります。
> 
> と書かれている。

なるほど。であれば、

> ソースコードには「本書はオープンソースです」と記載されているが、 ドキュメントのライセンスページを見に行かないと何のライセンスが適用されるか分からない。
> 
> ソースコード内にライセンスについての言及があると良いと思った。

この文章をいい感じに整えて、Issueに登録すれば良さそうです。

**Comment by ueferi** [comment]
チケット駆動の流れ: https://typescriptbook.jp/writing/ticket-driven

**Comment by ueferi** [comment]
Issueの書き方指定がないか調べる。

**Comment by ueferi** [comment]
1. GitHubリポジトリからIssueを登録する際、報告用のテンプレートはあるか？

<img width="1383" alt="スクリーンショット 2023-12-09 16 47 24" src="https://github.com/oss-gate/workshop/assets/58869038/1435d88a-4d96-4383-8b85-02c6c57bfd18">

結果: なし

**Comment by ueferi** [comment]
2. ドキュメントにIssueの書き方についての指定はあるか？

>本書に変更を加えたいときは、そのアイディアをissueとして共有してください。
>issueには次の内容を記してください。
>- 何をどうしたいか？
>- そうしたい理由は何か？ (誤植の修正など理由が自明な場合は不要)
>- やるとなったら自分が担当したいか？ (自分がその変更のプルリクエストを作りたい場合)

結果: あり。
[issueを作る](https://typescriptbook.jp/writing/ticket-driven#issue%E3%82%92%E4%BD%9C%E3%82%8B)項目に盛り込むべき内容が言及されている。

**Comment by blacktoad30** [comment]
> * 何をどうしたいか？
> 
> * そうしたい理由は何か？ (誤植の修正など理由が自明な場合は不要)
> 
> * やるとなったら自分が担当したいか？ (自分がその変更のプルリクエストを作りたい場合)

この3点を踏まえて、Issueの文章を(下書きも兼ねて)メモしていただきたいです。

**Comment by ueferi** [comment]
## タイトル

ソースコード内にライセンスについての記載を追加しませんか？

## 何をどうしたいか

- README.mdにCC BY-SA 4.0とMIT Licenseで公開している旨を追記する。
- LICENSESディレクトリを作成し、そこにCC BY-SA 4.0とMIT Licenseの詳細を記載したテキストファイルを格納する。  

```
(例)

└── LICENSES_dir
    ├── CC BY-SA 4.0
    └── MIT License
```

## そうしたい理由は何か

ドキュメントのライセンスページを見に行かないと何のライセンスが適用されるか分からないため。

## やるとなったら自分が担当したいか？ 

ぜひPRを立てたいと思います。

**Comment by ueferi** [comment]
「何をどうしたいか？」に参考としてRustのリポジトリを追記します。

**Comment by blacktoad30** [comment]
確認しました。良いと思います!

> ```
> (例)
> 
> └── LICENSES_dir
>     ├── CC BY-SA 4.0
>     └── MIT License
> ```

`LICENSES_dir`は、`LICENSES`でも良いかなと思いました。

**Comment by ueferi** [comment]
ありがとうございます！タイトル以外を修正しました。

- 文末をですます調に修正
- `LICENSES_dir` -> `LICENSES`
- 参考情報としてRustのリポジトリを追記

***

## 何をどうしたいか

- README.mdにCC BY-SA 4.0とMIT Licenseで公開している旨を追記します。
- LICENSESディレクトリを作成し、そこにCC BY-SA 4.0とMIT Licenseの詳細を記載したテキストファイルを格納します。
参考: 本書と同様に複数のライセンスで公開しているRustのリポジトリ 
https://github.com/rust-lang/rust/tree/master/LICENSES

```
(例)

└── LICENSES
    ├── CC BY-SA 4.0
    └── MIT License
```

## そうしたい理由は何か

ドキュメントのライセンスページを見に行かないと、どのライセンスが適用されるか分からないためです。

## やるとなったら自分が担当したいか？ 

ぜひPRを立てたいと思います。

**Comment by blacktoad30** [comment]
とても分かりやすい内容です!

**Comment by ueferi** [comment]
Issueを登録しました！
https://github.com/yytypescript/book/issues/801

**Comment by blacktoad30** [comment]
参考: プレーンテキストのライセンスファイル
CC-BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt

**Comment by ueferi** [comment]
Issueにコメントを頂いた。

> GitHubにも本プロジェクトのライセンスを認識してもらえると、サイドバーにライセンスが表示されるため、より目的を達成しやすいと思うのですがいかがでしょうか。
LICENSESディレクトリではGitHubに認識してもらえないようです。RustではプロジェクトルートにLICENSE-MITファイルを配置しているようで、これによりマルチライセンスとGitHubに認識され、サイドバーに表示されているようです。

**Comment by ueferi** [comment]
テスト用のリポジトリを作って、マルチライセンスをGitHubに認識させてみる。

**Comment by ueferi** [comment]
<img width="1259" alt="スクリーンショット_2023-12-19_0_37_55" src="https://github.com/oss-gate/workshop/assets/58869038/5211f9b2-c1e3-4c11-85e0-84c836970146">

**Comment by ueferi** [comment]
CC Licensesは`LICENSE`という名前で保存すると、GitHubが認識してくれるようだ。

参考記事
[GitHub リポジトリに CC Licenses を設定したい](https://zenn.dev/spiegel/articles/20200919-ccl)

**Comment by ueferi** [comment]
GitHub Docsにライセンスの追加方法について記載されている

[リポジトリへのライセンスの追加](https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)
