### ISSUE TITLE
OSS Gate Workshop: online: 2023-12-09: Angy-h: Railsガイド: Work log

### ISSUE THREAD

**Issue by Angy-h** [oss-gate/workshop#1745]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Angy-h** [comment]
Railsのガイドで始めたいと思います。
https://railsguides.jp/getting_started.html#%E3%83%A2%E3%83%87%E3%83%AB%E3%82%92%E7%94%A8%E3%81%84%E3%81%A6%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%A8%E3%82%84%E3%82%8A%E3%81%A8%E3%82%8A%E3%81%99%E3%82%8B

**Comment by Angy-h** [comment]
ライセンスについて確認すると、次の通りでした（GitHubのReadMeより）。
コンテンツ部分は、[クリエイティブ・コモンズ 表示-継承 4.0 国際](https://creativecommons.org/licenses/by-sa/4.0/deed.ja) (CC BY-SA 4.0でした。
ソースコードは、[MIT ライセンス](http://www.opensource.org/licenses/MIT)でした。

**Comment by Angy-h** [comment]
Railsガイドの「Rails をはじめよう」の3.1 Railsのインストールの項目のところで、（Macを使用）
Rubyのバージョンを確認し古いバージョンだったので、最新のRubyをインストールした（$ brew install ruby）。しかし、$ ruby -vで確認しても古いバージョンのままで、インストール済みの最新版が使用できるようにならず、ガイドの先に進めなかったので困りました。
使用できるようになるには、.zshrcを書き換える必要があったみたいで（ChatGPT等を参照）、初心者には、そこまで考慮は及ばなかったのでRailsを開始するまでにハードルが高いと感じました。

**Comment by Angy-h** [comment]
8.4 コントローラを生成するのところで、
表示されている成果物の中に、解説がついていない箇所がありました。
成果物には、Edid | Backのリンクがついていますが、解説にはなく、Localhostを使用しているので、HTMLでどのようなリンクをつけて良いか、わかりませんでした。

**Comment by Angy-h** [comment]
Railsガイドのフィードバックで、Rubyのインストールでつまづきました。
「OS環境ごとのインストール方法について詳しくは、[ruby-lang.org](https://www.ruby-lang.org/ja/documentation/installation/)を参照してください。」という記述はありましたが、初心者にとっては内容が難しく、パソコン環境によって必要な作業が異なってくるような説明があった方がいいと思いました。

**Comment by Angy-h** [comment]
Railsガイドのリポジトリに行きました。
https://github.com/yasslab/railsguides.jp

**Comment by Angy-h** [comment]
Railガイドの手順通りに進めても、8.4 「コントローラを生成する」の成果物と同じものができませんでした。違いは、Edid | Backのリンクが付けられませんでした。
この点を報告します。

**Comment by Angy-h** [comment]
8.4では、下記のような成果物が期待されている。
<img width="543" alt="スクリーンショット 2023-12-09 17 14 49" src="https://github.com/oss-gate/workshop/assets/140281190/761e3277-6c19-4a37-a2d8-b6306f5ff361">

実際の成果物は次のようなものになりました。
<img width="414" alt="スクリーンショット 2023-12-09 17 17 03" src="https://github.com/oss-gate/workshop/assets/140281190/1265dabe-82e0-445e-a5e1-1faa2c841510">

**Comment by Angy-h** [comment]
issueを書きます。

**Comment by Angy-h** [comment]
# タイトル
RailガイドのRails をはじめようの8.4「コントローラを生成する」について

## やったこと
このパートの内容を手順通りに進めました。

## 期待する結果
8.4の終わりに次のような成果物が示されていました。
<img width="543" alt="スクリーンショット 2023-12-09 17 14 49" src="https://github.com/oss-gate/workshop/assets/140281190/93c4deec-b8d0-43d2-800d-3a0e5e5a7d1b">

## 実際の結果
次のような結果となりました。
<img width="414" alt="スクリーンショット 2023-12-09 17 17 03" src="https://github.com/oss-gate/workshop/assets/140281190/d3c401f3-f549-4fbb-86b6-c9b1891e1b62">

## フィードバック
Edid | Backのリンクを付けるための手順の記載がないようでした。
示されている成果物と同じ結果にならないようでしたので、ご報告させていただきます。

**Comment by otegami** [comment]
https://github.com/rurema/doctree/issues/2852

**Comment by otegami** [comment]
| 期待する結果 | 実際の結果 |
| --- | --- |
|  |  |

**Comment by Angy-h** [comment]
# タイトル
RailガイドのRails をはじめようの8.4「コントローラを生成する」について

## フィードバック
Edid | Backのリンクを付けるための手順の記載がないようでした。
示されている成果物と同じ結果にならないようでしたので、ご報告させていただきます。

## 再現方法
RailガイドのRails をはじめようの[8.4 コントローラを生成する](https://railsguides.jp/getting_started.html#%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%A9%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B)」のパートの内容を手順通りに進めました。



| 期待する結果 | 実際の結果 |
| --- | --- |
| <img width=100% alt="スクリーンショット 2023-12-09 17 14 49" src="https://github.com/oss-gate/workshop/assets/140281190/04d8d1de-8020-4ef1-a8e4-262837f40eef"> | <img width=100% alt="スクリーンショット 2023-12-09 17 17 03" src="https://github.com/oss-gate/workshop/assets/140281190/d3c401f3-f549-4fbb-86b6-c9b1891e1b62"> |

**Comment by daipom** [comment]
https://github.com/yasslab/railsguides.jp/issues/1550

**Comment by otegami** [comment]
ふりかえり会であったコメント
- 原著側の修正にあたるのではないか？ その場合は、https://github.com/rails/rails 側に Issue を立ててあげると良さそう

気付いてあげられず申し訳ないです🙏

**Comment by kou** [comment]
https://matrix.to/#/!gHIZhKRtDtemauVGiE:gitter.im/$9jXXJJ3M9Waui5GFnfKA6JGesTpOWchs_Czbj-op9Wg?via=gitter.im&via=matrix.org の続き。

> こんにちは。先日OSS GATEのワークショップでお世話になりましたAngy-hです。Railsガイドに画像の相違についてフィードバックを送りました。
> その後yasulabさんから該当部分の画像を差し替えるプルリクエストを送ってもらえるようにというお返事がありました。英語版にも送るとマージされる可能性にあるとのことでした。
> Railsガイドの「3 Railsのドキュメントに貢献する」というページを見たりしましたが、私一人では、プルリクエストを送るのは難しそうです。

**Comment by kou** [comment]
> Railsガイドの「3 Railsのドキュメントに貢献する」というページ

このページのURLを教えてもらえますか？どんな内容なのかを知りたいです！

**Comment by kou** [comment]
すでにやったこと：

https://matrix.to/#/!gHIZhKRtDtemauVGiE:gitter.im/$GZKcQtSPApkrzIwLIbHkKCYR4IY4AHTYIdjY-pBr4Yo?via=gitter.im&via=matrix.org

> * 再度、RailガイドのRails をはじめようの8.4 コントローラを生成する」のパートの内容を手順通りに進めて、画像を撮り直す。
> * 同時に、出来たblogの成果物（blogフォルダとコード）を残しておく。
> * 現状のimageと撮り直した写真を照合し、ガイドの内容を再確認、相違点に赤色で印をつける。

**Comment by Angy-h** [comment]
返信が遅くなり大変申し訳ございません！
Railsガイドの「3 Railsのドキュメントに貢献する」というページのリンクは、下記でございます。
[Railsガイド - Railsのドキュメントに貢献する](https://railsguides.jp/contributing_to_ruby_on_rails.html#rails%E3%81%AE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AB%E8%B2%A2%E7%8C%AE%E3%81%99%E3%82%8B)
大変申し訳ございませんでした。これからまめにチェックするようにいたします。

**Comment by kou** [comment]
@Angy-h あざっす。

ということは、やることは↓ですね。

> 英語ドキュメントに貢献したい方は、Railsガイドの[英語ソースファイル](https://github.com/rails/rails/tree/main/guides/source)を変更してから、プルリクエストでmainブランチに変更の反映を依頼してください。 ドキュメント変更のプルリクエストでは、CIビルドの実行を避けるため、プルリクエストのタイトルに[ci skip]を含めてください。

タスクに分けるとこうですね。

1. [ ] Railsガイドの[英語ソースファイル](https://github.com/rails/rails/tree/main/guides/source)を変更する
2. [ ] プルリクエストでmainブランチに変更の反映を依頼する
3. [ ] ドキュメント変更のプルリクエストでは、CIビルドの実行を避けるため、プルリクエストのタイトルに[ci skip]を含める

いままでプルリクエストは作ったことはありますか？

あるなら、そのときと同じように1.をやってみてつまづいたところを教えてください。サポートします。

ないならどうやって1.をやるか説明します。

**Comment by kou** [comment]
@Angy-h 続きは https://github.com/yasslab/railsguides.jp/issues/1550 で！

**Comment by Angy-h** [comment]
承知いたしました。https://github.com/yasslab/railsguides.jp/issues/1550の方を拝見させていただきます。

**Comment by kou** [comment]
最終的に https://github.com/rails/rails/pull/50756 としてプルリクエストしてマージされた。
