### ISSUE TITLE
OSS Gate Workshop: online: 2023-12-09: niikz: rurema: Work log

### ISSUE THREAD

**Issue by niikz** [oss-gate/workshop#1746]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by niikz** [comment]
るりまのリンク切れを修正したい

- https://docs.ruby-lang.org/ja/latest/method/Gem=3a=3aGemPathSearcher/i/find_all.html

**Comment by niikz** [comment]
りんく切れを確認しました

- https://docs.ruby-lang.org/ja/latest/method/Array/i/find_all.html

**Comment by niikz** [comment]
OSSか確認する

- https://github.com/rurema/doctree

**Comment by niikz** [comment]
ライセンスがぱっと見わからなかったので以下を確認する

- https://github.com/rurema/doctree/wiki

**Comment by niikz** [comment]
ライセンスのページ

- https://github.com/rurema/doctree/wiki/License

**Comment by niikz** [comment]
ライセンスを確認しました

Creative Commons — Attribution 3.0 Unported

- https://github.com/rurema/doctree/blob/master/refm/doc/license.rd

**Comment by niikz** [comment]
GitHub上の[doctree](https://github.com/rurema/doctree)のリポジトリで確認できるとうれしい

- https://github.com/rurema/doctree

**Comment by niikz** [comment]
OSSか確認する

- https://opensource.org/licenses/

**Comment by niikz** [comment]
Creative Commons — Attribution 3.0 Unported で検索するとヒットしない

- https://opensource.org/licenses/?ls=Creative+Commons+%E2%80%94+Attribution+3.0+Unported

**Comment by niikz** [comment]
Creative Commons で検索してもヒットしなかった

- https://opensource.org/?s=Creative+Commons

**Comment by niikz** [comment]
[bitclust](https://github.com/rurema/bitclust/tree/master) のライセンスを確認しました

```
License
-------

  Ruby License.
```

- https://github.com/rurema/bitclust/blob/master/README

**Comment by niikz** [comment]
Creative Commons なのでオープンソースの文書に該当すると思われる
あとで確認！

- https://creativecommons.org/licenses/by/3.0/

**Comment by otegami** [comment]
A Creative Commons (CC) license is one of several [public copyright licenses](https://en.wikipedia.org/wiki/Public_copyright_license) that enable the free distribution of an otherwise [copyrighted](https://en.wikipedia.org/wiki/Copyright) "work".[[](https://en.wikipedia.org/wiki/Creative_Commons_license#cite_note-1)

https://en.wikipedia.org/wiki/Creative_Commons_license

**Comment by niikz** [comment]
Ruby License を検索してみる

**Comment by niikz** [comment]
オープンソースと判断してもよさそう

> Rubyライセンス（Ruby’s License[[3]](https://ja.wikipedia.org/wiki/Ruby%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9#cite_note-3)、License of Ruby[[2]](https://ja.wikipedia.org/wiki/Ruby%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9#cite_note-gnu-ruby-2)[[注釈 1]](https://ja.wikipedia.org/wiki/Ruby%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9#cite_note-4)）とは、[プログラミング言語](https://ja.wikipedia.org/wiki/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E8%A8%80%E8%AA%9E)[Ruby](https://ja.wikipedia.org/wiki/Ruby)がその頒布物に適用する[ソフトウェアライセンス](https://ja.wikipedia.org/wiki/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9)であり、[オープンソース](https://ja.wikipedia.org/wiki/%E3%82%AA%E3%83%BC%E3%83%97%E3%83%B3%E3%82%BD%E3%83%BC%E3%82%B9)ライセンスの一つである。その他関連するプロジェクトをはじめ、採用されているケースもある。

- https://www.ruby-lang.org/en/about/license.txt
- https://ja.wikipedia.org/wiki/Ruby%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9

**Comment by niikz** [comment]
どっちの対応をするか

1. 手元でリンクを修正する
2. 間違っていることをお知らせする

**Comment by niikz** [comment]
1. 手元でリンクを修正する にチャレンジしてみます

**Comment by niikz** [comment]
コントリビュートの方法を確認する

- https://github.com/rurema/doctree/wiki/HowToContribute

**Comment by niikz** [comment]
プロジェクトに参加する必要がありそう

**Comment by niikz** [comment]
参加資格は、日本語が話せたらたぶんOK

- https://github.com/rurema/doctree/wiki/HowToJoin

**Comment by niikz** [comment]
ruby-reference-manual メーリングリストに参加する必要がありそう

- https://github.com/rurema/doctree/wiki/MailingList

**Comment by niikz** [comment]
メーリングリストは消滅したそうです

> QuickML の仕様により、長期間が投稿がなかったため消滅しました。

メーリングリストに参加しなくてもいいかも

- https://maimux2x.hatenablog.com/entry/2023/03/07/004429
- https://imaizumimr.hatenablog.com/entry/2020/12/02/235121

**Comment by niikz** [comment]
Issueを登録してみよう

**Comment by niikz** [comment]
Issueを登録する際は、最新版で修正済かどうか確認する

**Comment by niikz** [comment]
doctreeのリポジトリ上でGemPathSearcherを検索

- https://github.com/search?q=repo%3Arurema%2Fdoctree+GemPathSearcher&type=code

**Comment by niikz** [comment]
📝 ふりかえりメモ

ドキュメントのコード自体はMITのことが多いのでたぶん大丈夫と思われます！

**Comment by niikz** [comment]
以下ファイルに記載がありそう

- https://github.com/rurema/doctree/blob/91fa497b3fdaefc76db15c5d51741de99008d359/refm/api/src/rubygems/gem_path_searcher.rd

**Comment by niikz** [comment]
最終更新日が11年前なので現在のファイルが最新であってそう

> Commits on Sep 29, 2012

- https://github.com/rurema/doctree/commits/91fa497b3fdaefc76db15c5d51741de99008d359/refm/api/src/rubygems/gem_path_searcher.rd

**Comment by otegami** [comment]
実際にリンク切れを Issue で報告している人がいそう
- https://github.com/rurema/doctree/issues/2849

**Comment by niikz** [comment]
https://github.com/oss-gate/workshop/issues/1746#issuecomment-1848292213 を参考にIsseを作成する

**Comment by niikz** [comment]
CONTRIBUTING.md を確認する

- https://github.com/rurema/doctree/blob/master/CONTRIBUTING.md

**Comment by niikz** [comment]
Issueの文章を作成する

---

## 概要
https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND_ALL において、[Array\#find_all](https://docs.ruby-lang.org/ja/latest/method/Array/i/find_all.html) のリンクが切れてしまっていました。 

## 期待される振る舞い
Array#find_allのリンク先は以下に変更するとよさそうです。
https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/filter.html

**Comment by niikz** [comment]
https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND の [Array\#find](https://docs.ruby-lang.org/ja/latest/method/Array/i/find.html) もリンクが切れてしまっている

- https://docs.ruby-lang.org/ja/latest/method/Array/i/find.html

**Comment by niikz** [comment]
できそうだったら動画ものせてあげると親切

**Comment by niikz** [comment]
https://github.com/oss-gate/workshop/issues/1746#issuecomment-1848309476 の文章を修正しました。
動画はサイズが大きかったのでスクリーンショットの画像を添付しています。

---

## 概要
Gem::GemPathSearcherクラスのページにリンク切れがありました。
https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html

- https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND
  - [SEE_ALSO] [Array\#find](https://docs.ruby-lang.org/ja/latest/method/Array/i/find.html)のリンク
- https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND_ALL
  - [SEE_ALSO] [Array\#find_all](https://docs.ruby-lang.org/ja/latest/method/Array/i/find_all.html) のリンク

## 期待される振る舞い
- https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND
  - Array#findのリンクは以下に修正するとよさそうです。
https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/detect.html

- https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND_ALL
  - Array#find_allのリンクは以下に修正するとよさそうです。
https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/filter.html

## スクリーンショット
<img width="1792" alt="screenshot-2023-12-09" src="https://github.com/oss-gate/workshop/assets/60736158/9fa209de-1402-4752-bcc6-bf388dd48b47">

**Comment by niikz** [comment]
Issueを登録しました

- https://github.com/rurema/doctree/issues/2852

**Comment by niikz** [comment]
まずはForkする

- https://github.com/rurema/doctree

**Comment by niikz** [comment]
Forkできました

- https://github.com/niikz/doctree

**Comment by niikz** [comment]
Tutorialにそってcloneする

- https://github.com/rurema/doctree/wiki/Tutorial

**Comment by niikz** [comment]
`refm/api/src/rubygems/gem_path_searcher.rd` を修正する

- https://github.com/rurema/doctree/blob/91fa497b3fdaefc76db15c5d51741de99008d359/refm/api/src/rubygems/gem_path_searcher.rd#L15
- https://github.com/rurema/doctree/blob/91fa497b3fdaefc76db15c5d51741de99008d359/refm/api/src/rubygems/gem_path_searcher.rd#L21

**Comment by otegami** [comment]
下記に全体をプレビューできる方法がありそうです。
https://github.com/rurema/doctree/wiki/Tutorial

**Comment by niikz** [comment]
修正できました！

**Comment by niikz** [comment]
バージョンはなにを指定したらいいのだろう🤔

> データベースのディレクトリ名は、ここではdb-2.5.0/としましたが、好きな名前を付けて構いません。
> 2.3.0や2.4.0など、Rubyの他のバージョンのリファレンスをプレビューしたい場合は、versionを変えて上記の手順を繰り返して下さい。

**Comment by otegami** [comment]
> データベースのディレクトリ名は、ここではdb-2.5.0/としましたが、好きな名前を付けて構いません。

ここから見るに本当になんでも大丈夫そうな気がします🙌
現状だと、`db-3.2.` にしてあげると良さそうかなと思いました。
- Ruby 3.2 のリファレンスなため

**Comment by niikz** [comment]
3.2.0 を指定してみる

```console
$ bitclust -d ./db-3.2.0 init version=3.2.0 encoding=UTF-8
$ bitclust -d ./db-3.2.0 update --stdlibtree=refm/api/src
$ bitclust server --database=db-3.2.0 --debug
```

**Comment by niikz** [comment]
もしかしたら動作していないかも…

> ```console
> $ bitclust server --database=db-2.5.0 --debug ※状況確認中。動作しません。
> ```

**Comment by niikz** [comment]
全体プレビューではなくて、htmlファイルとして出力してみる

> ```console
> $ bitclust htmlfile ./refm/api/src/_builtin/Array --target=Array#pop --ruby=2.5.0 > /tmp/Array_pop.html
> ```

**Comment by niikz** [comment]
`Gem::GemPathSearcher#find_all` を出力する
バージョンは3.2.0を指定

```console
$ bitclust htmlfile ./refm/api/src/rubygems/gem_path_searcher.rd --target=Gem::GemPathSearcher#find_all --ruby=3.2.0 > /tmp/GemPathSearcher_find_all.html
```

**Comment by niikz** [comment]
[SEE_ALSO]を`Enumerable#filter` へ変更できました
<img width="1273" alt="screenshot-2023-12-10-11" src="https://github.com/oss-gate/workshop/assets/60736158/d0ee087e-d8bb-42bb-a54b-80edc014b344">

**Comment by niikz** [comment]
`Gem::GemPathSearcher#find` を出力する
バージョンは3.2.0を指定

```console
$ bitclust htmlfile ./refm/api/src/rubygems/gem_path_searcher.rd --target=Gem::GemPathSearcher#find --ruby=3.2.0 > /tmp/GemPathSearcher_find.html
```

**Comment by niikz** [comment]
[SEE_ALSO]を`Enumerable#detect` へ変更できました
<img width="1273" alt="screenshot-2023-12-10-12" src="https://github.com/oss-gate/workshop/assets/60736158/7458871c-63a0-411d-9073-ec58aa75420f">

**Comment by niikz** [comment]
変更を確認できたのでPRをつくってみます
※リンク先は未確認

**Comment by niikz** [comment]
ブランチを作成

```console
$ git switch -c fix-gempathsearcher-link
```

**Comment by niikz** [comment]
commitする

**Comment by niikz** [comment]
PRの文章を作成する

---

https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND
https://docs.ruby-lang.org/ja/latest/class/Gem=3a=3aGemPathSearcher.html#I_FIND_ALL

[SEE_ALSO]のリンクが切れていたため修正しました。

**Comment by niikz** [comment]
pushする

**Comment by niikz** [comment]
Compare & pull request でPRを作成する

**Comment by niikz** [comment]
PR送りました！！！

**Comment by otegami** [comment]
お疲れ様です！ :clap:
https://github.com/rurema/doctree/pull/2853
