### ISSUE TITLE
OSS Gate Workshop: online: 2024-01-27: びきニキ: doc-ja : Work log

### ISSUE THREAD

**Issue by 012xx** [oss-gate/workshop#1774]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 012xx** [comment]
OSS決めを始めます📛

気になってるのは以下の通りだけど、どっちも有名すぎて悩んでいる
- Perl：YAPCに行くので！貢献出来たらそういう内容でLT応募したい
- PHP：OSSに興味持った要因なので。。。。

最近使ってるソフト（他の候補）が浮かんでこない～～～

**Comment by 012xx** [comment]
決められるのか不安になってきたぞ！

**Comment by 012xx** [comment]
[doc-ja](https://github.com/php/doc-ja) :https://github.com/php/doc-ja

**Comment by 012xx** [comment]
web-php: https://github.com/php/web-php/tree/master

**Comment by 012xx** [comment]
ライセンス：https://github.com/php/doc-base/blob/master/LICENSE
https://creativecommons.org/licenses/by/3.0/deed.ja

doc-base: https://github.com/php/doc-base/tree/master

doc-jaに「ライセンス情報が無いこと」を聞くとか？

**Comment by 012xx** [comment]
てきめんさんのPR 
参考になるかも：https://github.com/php/php-src/issues/11878

**Comment by 012xx** [comment]
ライセンス：https://github.com/php/doc-ja/blob/master/bookinfo.xml

**Comment by 012xx** [comment]
- 「https://www.php.net/manual/ja/」の誤字を探してIssue立てる

**Comment by 012xx** [comment]
リポジトリをローカルに落としてVSCodeで見てもらうとかもあり？

**Comment by 012xx** [comment]
doc-ja :https://github.com/php/doc-ja
の誤字脱字を見ることにした

**Comment by youkidearitai** [comment]
Creative Commonsはオープンソースではないが、Creative Commons Attribution 3.0（CC BY）は自由なライセンスの一部であると考えます。

**Comment by 012xx** [comment]
- http://doc.php.net/tutorial/local-setup.php のシンタックスハイライトが効いていない
- https://www.php.net/manual/en/install.unix.apache2.php のようなページはシンタックスハイライトが効いているので、統一してもいいような気がする
- ソースコードを見た感じ、コードブロックの表記はされているので、doc.php.netの装飾の仕方が斜体のみになっていそう
- 「https://www.php.net/manual/en/install.unix.apache2.php 」のページは.xml拡張子、「https://www.php.net/manual/en/install.unix.apache2.php」のページは.md拡張子になっている

**Comment by 012xx** [comment]
拡張子を変えるのは微妙なので一旦保留かなあ http://doc.php.net/tutorial/local-setup.php ページ以外のコードもmdぽい

**Comment by 012xx** [comment]
- 斜体文字は折り返しが効いておらず、SPにした際にはみ出している
- 実機で見た時も同じ
![image](https://github.com/oss-gate/workshop/assets/79149878/e17cdac0-9a36-4a14-9995-848d89ae1fce)

**Comment by 012xx** [comment]
.mdのスタイルを決めてるファイル見つけたらハイライトのところも貢献できそう？

**Comment by 012xx** [comment]
https://github.com/php/web-doc/blob/master/include/Parsedown.php ここらへんは生成してるコード

**Comment by daipom** [comment]
> * http://doc.php.net/tutorial/local-setup.php のシンタックスハイライトが効いていない
> 
>     * https://www.php.net/manual/en/install.unix.apache2.php のようなページはシンタックスハイライトが効いているので、統一してもいいような気がする
> 
>     * ソースコードを見た感じ、コードブロックの表記はされているので、doc.php.netの装飾の仕方が斜体のみになっていそう
> 
>     * 「https://www.php.net/manual/en/install.unix.apache2.php 」のページは.xml拡張子
> 
>     * 「http://doc.php.net/tutorial/local-setup.php 」のページは.md拡張子になっている

ウェブサイトとして異なるものなので、異なる仕組みになっていそうな気がしますね。
なるべく揃えた方が良いんじゃないかというのはその通りだと思います！

ただ、仕組みが異なるのであれば、もしかしたら簡単には揃えられないのかも、、

シンプルに、`doc.php.net`の方のコードブロックが見にくいので、`www.php.net`みたいな感じにならないかなあ、みたいあ方向性でフィードバックするのでよさそうな気もします！

**Comment by daipom** [comment]
> * 斜体文字は折り返しが効いておらず、SPにした際にはみ出している
> 
> * 実機で見た時も同じ

おお、合わせてフィードバックしたらよさそうですね！
ブロックの改善！

**Comment by 012xx** [comment]
https://github.com/php/web-doc

**Comment by 012xx** [comment]
Readmeが分かりにくいという提案
https://www.php.net/manual/ja/faq.mailinglist.php

**Comment by daipom** [comment]
メーリス一覧。ドキュメント用のメーリスが最後にある

https://www.php.net/mailing-lists.php

**Comment by 012xx** [comment]
[phpdoc@lists.php.net](mailto:phpdoc@lists.php.net)

**Comment by 012xx** [comment]
### 今ある問題点
- https://github.com/php/web-doc のコントリビュートの仕方が分かりにくい
  - Issueじゃなくてメーリングリストに送ってねって書いてあるけど、Issueは立っている
  - 実際にコントリビュートする際にどうするべきか迷ったので、Readmeの表記の仕方も改善の余地があるかも

**Comment by 012xx** [comment]
[phpdoc@lists.php.net](mailto:phpdoc@lists.php.net) に送られてきたメールの一覧？
https://news-web.php.net/group.php?group=php.doc

**Comment by youkidearitai** [comment]
@012xx ここ https://www.php.net/mailing-lists.php にphpdoc@lists.php.netがあるのですが、アーカイブを見るとほとんどVCS Account Requestで使われてるので単純なIssueだったらそのままGitHub Issueに投稿してしまって良いと思います。

**Comment by 012xx** [comment]
ありがとうございます！一旦Issue作ってみます👀

**Comment by 012xx** [comment]
@youkidearitai 
立ててみました！レビューお願いします（ドキドキ）
https://github.com/php/web-doc/issues/46
