### ISSUE TITLE
OSS Gate Workshop: online: 2024-01-27: s1a: SCP: Work log

### ISSUE THREAD

**Issue by Samurai-git** [oss-gate/workshop#1775]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Samurai-git** [comment]
OSSぎめを始めます

**Comment by Samurai-git** [comment]
昔GISを触っていたので、OSSかどうかを調べます。

**Comment by blacktoad30** [comment]
QGIS: Pythonプラグインの構成に関して

https://docs.qgis.org/3.28/ja/docs/pyqgis_developer_cookbook/plugins/plugins.html#qm-file

**Comment by Samurai-git** [comment]
QGIS: https://github.com/qgis
GRASS GIS: https://github.com/OSGeo/grass/tree/main

**Comment by Samurai-git** [comment]
QGISのライセンス: https://github.com/qgis/QGIS/blob/master/doc/LICENSE GNU GENERAL PUBLIC LICENSE
GRASS GISのライセンス: https://grass.osgeo.org/about/license/ GNU GENENERAL PUBLIC LICENSE

**Comment by Samurai-git** [comment]
プラグインの方を見てみます。

**Comment by Samurai-git** [comment]
Semiautomatic Classification Plugin: https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/tree/master

**Comment by Samurai-git** [comment]
ライセンス：　https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/blob/master/LICENSE

GNU GENERAL PUBLIC LICENSE

**Comment by blacktoad30** [comment]
> QGISのライセンス: https://github.com/qgis/QGIS/blob/master/doc/LICENSE GNU GENERAL PUBLIC LICENSE GRASS GISのライセンス: https://grass.osgeo.org/about/license/ GNU GENENERAL PUBLIC LICENSE

GRASS GISのライセンスの詳細:
https://github.com/OSGeo/grass/blob/main/COPYING
https://github.com/OSGeo/grass/blob/main/GPL.TXT

**Comment by blacktoad30** [comment]
[tsファイルをコンパイルして、qmファイルを作成する方法](https://docs.qgis.org/3.28/ja/docs/pyqgis_developer_cookbook/plugins/plugins.html#qm-file)曰く、
`lrelease semiautomaticclassificationplugin_ja.ts`
を実行すれば良さそう?

**Comment by blacktoad30** [comment]
[プラグインを読み込む](https://docs.qgis.org/3.28/ja/docs/pyqgis_developer_cookbook/plugins/plugins.html#load-the-plugin)の警告コラムにて、`.ts`と`.qm`両方のファイルを再生成する必要がある、と書いてある。

**Comment by blacktoad30** [comment]
参考: QGIS 3のプラグインディレクトリの場所について
https://gis-stackexchange-com.translate.goog/questions/274311/what-is-the-default-plugin-folder-location-in-qgis-3?_x_tr_sl=en&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=sc

**Comment by blacktoad30** [comment]
そもそも、日本語に翻訳されていなかった。(ファイルの中身を見ておくべきでした...すみません。)

**Comment by blacktoad30** [comment]
Qt Linguistをインストールする: https://docs.qgis.org/3.28/ja/docs/pyqgis_developer_cookbook/plugins/plugins.html#software-requirements

`apt` (DebianやUbuntuのパッケージマネージャー)なので、Macでは変わりそうです。(brewコマンド、パッケージ名も違うかも)
