### ISSUE TITLE
OSS Gate Workshop: online: 2024-01-27: ochi_work: ${OSS_NAME}: Work log

### ISSUE THREAD

**Issue by sho-work** [oss-gate/workshop#1776]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sho-work** [comment]
https://github.com/rubocop/rubocop
https://github.com/rubocop/rubocop-rspec
https://github.com/rubocop/rubocop-rails

**Comment by daipom** [comment]
* #1745

**Comment by sho-work** [comment]
## 取り組みやすそうなやつ
https://github.com/yasslab/railsguides.jp
https://github.com/rails/thor
https://github.com/redis/redis-rb

**Comment by daipom** [comment]
Rubyのドキュメントを直すのであれば、これが参考になりそう

* https://github.com/rurema/doctree/wiki

**Comment by sho-work** [comment]
一旦rubyの以下のメソッド`Time#strftime`の`%C`の挙動が怪しい。
ドキュメントに`2009年であれば 20`と書いてあるが、`2009年であれば 21`ではないか？

https://docs.ruby-lang.org/ja/latest/method/Time/i/strftime.html

**Comment by daipom** [comment]
```rb
Time.new.strftime("%C")
=> "20"
```

**Comment by daipom** [comment]
仕様の是非を確認するのはどうしたらよいのか？

Ruby のGitHub リポジトリは https://github.com/ruby/ruby
だが、issueがない

**Comment by daipom** [comment]
READMEから、次のページにたどり着いた。

https://docs.ruby-lang.org/en/master/contributing_md.html

**Comment by sho-work** [comment]
https://www.ruby-lang.org/ja/news/2023/12/25/ruby-3-3-0-released/

**Comment by daipom** [comment]
日本語のドキュメントだと分かりにくいが、`Century`という概念が西暦の上2桁を指すものになってしまっているように見える。

https://docs.ruby-lang.org/ja/latest/method/Time/i/strftime.html

```
%C: 世紀 (2009年であれば 20)
...
%Y: 西暦を表す数
%y: 西暦の下2桁(00-99)
```

英語だと

```
%C Century (20 in 2009)
...
%y Year without a century (00..99)
%Y Year which may include century, if provided
```

英語だと、`%C`のみでなく、`%y`や`%Y`の説明もおかしいのが分かる。
`Year without a century`というのは、明らかに上2桁の数字のことを`century`と呼んでいる。
これは我々の一般的な世紀の概念と合わない。

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

上2桁の数字のことを`century`と呼ぶのは、Pythonの英語ドキュメントでも同様だった。
(Pythonには`%C`で世紀を返すフォーマットはないが)

ソフトウェア業界では上2桁のことをCenturyと呼ぶ文化があるのだろうか？

**Comment by daipom** [comment]
少なくともRubyの日本語ドキュメントでは`%y`や`%Y`の説明に世紀という言葉を使っていない。

```
%y: 西暦の下2桁(00-99)
```

ならば、`%C`は`西暦の上2桁`と記載したほうが良いドキュメントではないか？という考え方はできそう。

**Comment by blacktoad30** [comment]
参考: [dateコマンドのPOSIX仕様: アプリケーションの使用方法](https://pubs-opengroup-org.translate.goog/onlinepubs/9699919799/utilities/date.html?_x_tr_sl=auto&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=wapp#tag_20_30_16)

**Comment by daipom** [comment]
> 参考: dateコマンドのPOSIX仕様
> 
>     * [変換仕様](https://pubs-opengroup-org.translate.goog/onlinepubs/9699919799/utilities/date.html?_x_tr_sl=auto&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=wapp#tag_20_30_05_01)
>       `%C`の説明が参考になりそうです。

おお。

> %C
> Century (a year divided by 100 and truncated to an integer) as a decimal number [00,99]. 

いい感じに説明してますね

>     * [アプリケーションの使用方法](https://pubs-opengroup-org.translate.goog/onlinepubs/9699919799/utilities/date.html?_x_tr_sl=auto&_x_tr_tl=ja&_x_tr_hl=ja&_x_tr_pto=wapp#tag_20_30_16)
>       `%C`が導入された経緯と注意点について書かれています。

これですね！なるほど〜

> The century number is calculated as the year divided by 100 and truncated to an integer; it should not be confused with the use of ordinal numbers for centuries (for example, "twenty-first century".)

**Comment by sho-work** [comment]
お二人とも、ありがとうございます！
内容まとめてみようと思います！

**Comment by sho-work** [comment]
# Rubyに立てようと思っているissue
## 概要
`Time#strftime`の以下のメソッドで第一の位置引数が`%C`の時に、西暦の上2桁を読み込んで返す仕様になっている。
この仕様は言語仕様としては正しいが、一般的な世紀とは異なるので、ドキュメント上では以下のような記述を加えた方が親切なのではないか？と思っている。
```diff
- %C: 世紀 (2009年であれば 20)
+ %C: 世紀 (2009年であれば 20。)。一般的な世紀とは異なり、西暦の上2桁を表す。
```

# Rspec-Coreに立てようと思っているissue

**Comment by daipom** [comment]
「Rubyに立てようと思っているissue」の方は、「るりま」の方に立てるとよさそうな気がします！

* https://github.com/rurema

ドキュメントの表現の仕方の改善提案、みたいな立ち位置になるかなあと

**Comment by daipom** [comment]
「一般的な世紀とは異なり、西暦の上2桁を表す」というような説明を足す、という改善はとても自然で良いものに思います！ぜひフィードバックしたいですね

**Comment by daipom** [comment]
https://github.com/rurema/doctree/wiki/HowToContribute

**Comment by daipom** [comment]
https://docs.ruby-lang.org/ja/latest/method/Time/i/strftime.html
の右上の`edit`ボタンからすぐにPR作れそう。

https://github.com/rurema/doctree/edit/master/refm/api/src/_builtin/Time#L552

**Comment by sho-work** [comment]
るりまのPull Requestを作成する

**Comment by sho-work** [comment]
PR作成できました！
https://github.com/rurema/doctree/pull/2869

**Comment by daipom** [comment]
おお！簡潔でいい感じだと思います！

**Comment by daipom** [comment]
元ページのURLも貼っとくといいかもですね！
