### ISSUE TITLE
OSS Gate Workshop: online: 2024-03-09: daipom: OurBoard: Work log

### ISSUE THREAD

**Issue by daipom** [oss-gate/workshop#1796]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daipom** [comment]
身近なOSS、何にしよう
普段使っているのは

...

**Comment by daipom** [comment]
最近使っている OurBoard というお絵描きツールがあるので、それにしてみようかな

**Comment by daipom** [comment]
OurBoard Webアプリ: https://www.ourboard.io/
GitHub: https://github.com/raimohanska/ourboard

**Comment by daipom** [comment]
まずはライセンス確認

**Comment by daipom** [comment]
これは https://opensource.org/license/mit にあるので、正式なOSSだった。
今日はこれを触ってみます。

**Comment by daipom** [comment]
公式ドキュメントを探す

**Comment by otegami** [comment]
Issue の OSS_NAME を忘れないうちに更新すると良いかも！

**Comment by daipom** [comment]
https://github.com/raimohanska/ourboard/tree/master?tab=readme-ov-file#features-and-user-guide

この部分が公式ドキュメントだと思う。
これにそってさわってみる。

**Comment by daipom** [comment]
`Setting your nickname` をしてみる

**Comment by daipom** [comment]
top right cornerにnickname fieldはない！！
アイコンがあって、それをクリックすると、ダイアログでてきて、
そこでニックネームを変更できる。
ちょっとドキュメントがおかしそう！！

![Screenshot from 2024-03-09 13-45-42](https://github.com/oss-gate/workshop/assets/12229857/f30bf7d8-5b38-4acd-8139-d95011d3e3ed)

右上のアイコンをクリックすると出てくるダイアログ:

![Screenshot from 2024-03-09 13-45-45](https://github.com/oss-gate/workshop/assets/12229857/4245414c-60a0-441f-bf6f-4d24fb80f106)

**Comment by daipom** [comment]
Ctrl + C もしくは Cloneボタンでコピーができなかった。
これはとても困るので、報告したい

**Comment by daipom** [comment]
特にルールはなさそう: https://github.com/raimohanska/ourboard?tab=readme-ov-file#contribution に `See Issues`と書いてあるだけ。他には指示がない。

テンプレートがあったので、これに従って書く。

# Feature request story or issue

## Screenshot

YOUR SCREENSHOT HERE:

## Url

-   Url where you took the screenshot:
-   URL:

## A sentence description of the problem

Short DESCRIPTION:

That's it! Thanks.

**Comment by daipom** [comment]
実際に出したIssue

* https://github.com/raimohanska/ourboard/issues/246
