### ISSUE TITLE
OSS Gate Workshop: online: 2024-03-09: SotaYamaguchi: chikamichi: Work log

### ISSUE THREAD

**Issue by SotaYamaguchi** [oss-gate/workshop#1797]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by SotaYamaguchi** [comment]
普段使っているやつは、、

- [Chikamichi](https://chromewebstore.google.com/detail/gkhobepjbiepngbeikhbpnfgjcjgmgha?hl=ja)
  - Github: https://github.com/kawamataryo/chikamichi
    - LICENSE: [MIT](https://github.com/kawamataryo/chikamichi/blob/main/LICENSE)
  - 知り合いのプロジェクトだから今日は別のものを扱いたいお気持ち

正式なOSSであることを確認。

他のライブラリで同じ手順で探してみる。

**Comment by SotaYamaguchi** [comment]
ちょっと大きいけど
- metabase

**Comment by SotaYamaguchi** [comment]
今日はひとつでもissueを作れたら嬉しいので、他のツールも探ってみる

**Comment by SotaYamaguchi** [comment]
dynamodb-toolboxはドキュメントに足りない感があるんだが、たくさん使われているライブラリである。

**Comment by SotaYamaguchi** [comment]
Chikamichiにドキュメントでサポートされていなかった気のする機能がある。

**Comment by SotaYamaguchi** [comment]
下記の操作がドキュメントに書かれているか調査。
- Ctrl + Shift + n
- Ctrl + Shift + p

**Comment by SotaYamaguchi** [comment]
あ〜もうissueあげてくれてる。さすがだ。
https://github.com/kawamataryo/chikamichi/issues/685

**Comment by SotaYamaguchi** [comment]
上記issueに対してPRを作るぞ！

**Comment by daipom** [comment]
コントリビューティングガイドについて

https://github.com/kawamataryo/chikamichi/tree/main?tab=readme-ov-file#-contributing

**Comment by SotaYamaguchi** [comment]
とりあえずForkしてきてテストを動かすところから着手。
※機能修正はするつもりがないが、素振りの意味も含めて。

**Comment by SotaYamaguchi** [comment]
localでdev実行するとエラーになるから、contributeの手順満たせないな。
https://github.com/kawamataryo/chikamichi/issues/1034

これの修正からやるか。

**Comment by SotaYamaguchi** [comment]
PR作成時に、開発環境を作れていない旨を記載すればいいのでは。

**Comment by daipom** [comment]
> localでdev実行するとエラーになるから、contributeの手順満たせないな。 [kawamataryo/chikamichi#1034](https://github.com/kawamataryo/chikamichi/issues/1034)
> 
> これの修正PR作る方にシフトするか。

> PR作成時に、開発環境を作れていない旨を記載すればいいのでは。 ドキュメント追記に戻る

そうですね、今回はREADMEの修正なので、そこまで気にしなくていいと思います！

**Comment by SotaYamaguchi** [comment]
正確なふるまいを確認するためにコードを見てみる。

実装はこの辺。
https://github.com/search?q=repo%3Akawamataryo%2Fchikamichi%20changeOrderOfSelectedFavoriteItems&type=code

**Comment by daipom** [comment]
> 正確なふるまいを確認するためにコードを見てみる。
> 
> 実装はこの辺。 https://github.com/search?q=repo%3Akawamataryo%2Fchikamichi%20changeOrderOfSelectedFavoriteItems&type=code

口頭でお伝えしましたが、コメントも残しておきますね。
コードの確認をした上でドキュメントを作るのはとても素晴らしいことですが、
必ずしもそこまで必要というわけではありません。
ドキュメントは結果的にユーザーにとって分かりやすいものであればよいので、コードが分からない状態でも自信をもってフィードバックして問題ありません！
むしろコードが分からない状態のユーザーの方がよいドキュメントを作れたりすることもあると思います。（開発者視点だと、コードが頭に入ってしまっているがゆえにドキュメントで何を伝えればよいのかを考えにくいう部分があったりする）

**Comment by SotaYamaguchi** [comment]
localのエラーが原因で
![image](https://github.com/oss-gate/workshop/assets/24993603/d508a726-ce45-48b0-a23a-8761116aa32e)

**Comment by SotaYamaguchi** [comment]
案1：既存のコードでエラーが発生するため、E2Eは通っていないが、動くんじゃない？だけでPRをあげておく。

**Comment by SotaYamaguchi** [comment]
対応方針：
- アプリケーションコードとドキュメントでPRを出し分ける。
- アプリケーションコードについては、ビルドができないためE2Eテストは動かしていないが、一応PRだけ上げておくね。と報告する。
- どちらも対応したら、ブロックしているバグの修正に取りかかる。

**Comment by SotaYamaguchi** [comment]
ドキュメントはドラフトでPRを作成
https://github.com/kawamataryo/chikamichi/pull/1064

**Comment by SotaYamaguchi** [comment]
^ 特に更新予定ないため、PRオープン

**Comment by SotaYamaguchi** [comment]
chrome extention としての buildはできていそう？
読み込んで動かしてみる。

**Comment by SotaYamaguchi** [comment]
UI崩れが起きてそう。
Shortcutをスクロールにしたりする方法もあると思うが、とりあえず画面サイズを大きくすることで対応してみようかな。
軽く周辺コード探ってよき対応案を検討してみる。

![image](https://github.com/oss-gate/workshop/assets/24993603/b4c4dc91-506c-4302-a0e6-cefbaebebcfc)

**Comment by SotaYamaguchi** [comment]
E2Eテストもこれで実行できるな。`pnpm dev` のスクリプトだけが死んでいる模様。

```bash
pnpm serve
pnpm cypress:open
```

**Comment by SotaYamaguchi** [comment]
before:
![image](https://github.com/oss-gate/workshop/assets/24993603/a1fc1fd7-de94-4141-93d9-cd6f60f18543)


after: 
![image](https://github.com/oss-gate/workshop/assets/24993603/c11affd2-9fe7-4dc7-9907-61a7368b3bdd)
![image](https://github.com/oss-gate/workshop/assets/24993603/247de447-dbf6-4250-99cb-a20d2485c883)



![image](https://github.com/oss-gate/workshop/assets/24993603/654524df-ec00-4a43-8ad2-163fc39ce3e0)

**Comment by SotaYamaguchi** [comment]
アプリケーションコードに対してもPRをオープン。
https://github.com/kawamataryo/chikamichi/pull/1065
