### ISSUE TITLE
OSS Gate Workshop: online: 2024-03-09: unikounio: minimist Work log

### ISSUE THREAD

**Issue by unikounio** [oss-gate/workshop#1798]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by unikounio** [comment]
なににしよう
フィヨルドの課題でつくるnpmがOSSのはずだけど、知り合いのじゃない方がいいのかしら

**Comment by unikounio** [comment]
RubyのOSSの探し方例
- 自分がつくったRailsアプリのGemを一つ選んで見に行く

**Comment by unikounio** [comment]
Toggle Trackを見に行ってみる。
https://toggl.com/

**Comment by otegami** [comment]
^Google Chrome の拡張機能を見る流れから

**Comment by otegami** [comment]
https://github.com/toggl/track-extension

**Comment by unikounio** [comment]
GitHubのStarが100未満くらいのOSSを探す

**Comment by unikounio** [comment]
npmをつくったときの依存ライブラリを確認してみる

**Comment by otegami** [comment]
https://github.com/unikounio/capital-city-quiz

**Comment by unikounio** [comment]
[minimistjs/minimist: parse argument options](https://github.com/minimistjs/minimist)のREADMEにes-module形式が記載されていないかも（otegamiさんが気づいてくださった！）

**Comment by unikounio** [comment]
スクールの学習で利用したGemを確認中

**Comment by unikounio** [comment]
minimistを触ってみる！

**Comment by unikounio** [comment]
READMEのコピペだとファイル名がひっかかってエラーになってしまう

![スクリーンショット 2024-03-09 144012](https://github.com/oss-gate/workshop/assets/125527162/1a62c663-9b38-45aa-acb6-a2bf3a57c0a4)

**Comment by otegami** [comment]
ライセンスの確認をするのを一緒に確認するのを失念していましたmm
- https://opensource.org/licenses

**Comment by unikounio** [comment]
現在報告したいこと
- READMEが手順通りに動くようにする
- es-module形式の例示を追加する

**Comment by unikounio** [comment]
どこに入力すべきコマンド／コードなのかがわかりにくい。
各コードブロックの手前に「JavaScriptのファイルに記述する」「コマンドラインに入力する」等の案内があった方がよさそう。

![スクリーンショット 2024-03-09 161252](https://github.com/oss-gate/workshop/assets/125527162/33b8d9da-b876-4ff3-b46c-55968adf6a73)

**Comment by unikounio** [comment]
ES Module形式の例示を追加するIssueを立てる方向で進めていく。

**Comment by unikounio** [comment]
似たIssueはなさそう。
ES Moduleのサポートに言及しているIssueはあったけど、READMEの修正ではないよう。
https://github.com/minimistjs/minimist/issues/58

**Comment by otegami** [comment]
ES Module 形式で利用していそうな記述を発見
- https://github.com/minimistjs/minimist/issues/59#issuecomment-1933052800

**Comment by unikounio** [comment]
報告のルールも特になさそう。
Issueのテンプレートもなし。

**Comment by otegami** [comment]
ES Module 形式で動くサンプルコードを書いてみる

**Comment by otegami** [comment]
```ruby
# ./example/parse.rb

```

**Comment by unikounio** [comment]
READMEのexampleのモジュール読み込み部分にES Modules用の記述を追加したい。

CommonJS
```javascript
// ./example/parse.js
var argv = require('minimist')(process.argv.slice(2));
console.log(argv);
```
ES Modules
```javascript
// ./example/parse.js
import minimist from "minimist";
const argv = minimist(process.argv.slice(2));
console.log(argv);
```

**Comment by unikounio** [comment]
日本語での報告文が概ねできあがったので、英文にしていく。

**Comment by unikounio** [comment]
How about adding ES Modules format sample code to the examples in the README?
I am a beginner and I had a problem because there was no explanation when I tried to use the ES Modules format.
I will show an example below. The execution result has been confirmed.
Executed with Node.js version 20.9.0

CommonJS
```javascript
// ./example/parse.js
var argv = require('minimist')(process.argv.slice(2));
console.log(argv);
```
```javascript
$ node example/parse.js -a beep -b boop
{ _: [], a: 'beep', b: 'boop' }
```
```javascript
$ node example/parse.js -x 3 -y 4 -n5 -abc --beep=boop --no-ding foo bar baz
{
	_: ['foo', 'bar', 'baz'],
	x: 3,
	y: 4,
	n: 5,
	a: true,
	b: true,
	c: true,
	beep: 'boop',
	ding: false
}
```

ES Modules
```javascript
// ./example/parse.mjs
import minimist from "minimist";
const argv = minimist(process.argv.slice(2));
console.log(argv);
```
```javascript
$ node example/parse.mjs -a beep -b boop
{ _: [], a: 'beep', b: 'boop' }
```
```javascript
$ node example/parse.mjs -x 3 -y 4 -n5 -abc --beep=boop --no-ding foo bar baz
{
	_: ['foo', 'bar', 'baz'],
	x: 3,
	y: 4,
	n: 5,
	a: true,
	b: true,
	c: true,
	beep: 'boop',
	ding: false
}
```

**Comment by unikounio** [comment]
otegamiさんの助けを借りて英文が完成！
いざ報告

**Comment by otegami** [comment]
> I am a beginner and I had a problem

Beginners might be confused when there are no sample codes in the ES Modules format.

**Comment by unikounio** [comment]
【タイトル】
READMEのexampleにES Modules形式のサンプルコードを追加したい

**Comment by unikounio** [comment]
【Title】
Docs: Add sample code ES Modules format to the examples in the README.

**Comment by unikounio** [comment]
以下のような文章を追加したい。
- Issueを受け入れてくださった場合、私がPRをつくりますよ。

**Comment by unikounio** [comment]
If you accept my idea, I will create a PR.

**Comment by unikounio** [comment]
Issueを立てられた！！
https://github.com/minimistjs/minimist/issues/61

**Comment by otegami** [comment]
@unikounio 
昨日はお疲れ様でした。
Issue にメンテナーから返信が来ていたので返信して対応してあげると良さそうに思います！

**Comment by unikounio** [comment]
@otegami さん
一昨日はありがとうございました！
メンテナーさんお二人ともご対応が早くて嬉しいです😄
対応させていただきます～

**Comment by otegami** [comment]
@unikounio 
メンテナーさんからのコメントにリアクションだけではなくコメントで反応しておくと良さそうに思います。
リアクションだけだと次 PR をつくるまで対応してくれるのかな？などメンテナーさんが不安になっちゃうかなとおもったためです。

**Comment by unikounio** [comment]
@otegami さん
お疲れ様です！
[ご協力いただいたminimistのIssue](https://github.com/minimistjs/minimist/issues/61)について、先ほど関連PRがマージされました！
otegamiさんにお力添えいただいたおかげで、貴重な経験ができました！
ありがとうございました～🙏✨

**Comment by otegami** [comment]
@unikounio 
おめでとうございます🎉
