### ISSUE TITLE
OSS Gate Workshop: online: 2024-03-09: chihara: use-web-animations: Work log

### ISSUE THREAD

**Issue by chiiira** [oss-gate/workshop#1799]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by chiiira** [comment]
普段使い慣れているのは、ReactとかNodeJS系です。

**Comment by chiiira** [comment]
最近興味があるのはWebAssembly系ですが、
大半がRustで書かれててまだ勉強中なので、自信はないです。

**Comment by daipom** [comment]
候補になりそうな例

* 自分が過去に使っていて困った点があったもの
  * ブログとかを読まないと解決しなかったことがあった点はフィードバックできそうかも
* 1つ1つのライブラリー
* 使っているツールやその拡張機能
  * ChromeやVisual Studio Codeの拡張とか

**Comment by chiiira** [comment]
以下のライブラリを昔使ってましたが、別のアカウントでforkして少しいじったことがあります。
何をいじったか覚えてないですが、何か足りない部分があったと思います。

https://github.com/omar-dulaimi/prisma-trpc-generator
↓
https://github.com/conte-ltd/prisma-trpc-generator

**Comment by chiiira** [comment]
あとこれもいじったことあります。

https://github.com/wellyshen/use-web-animations

**Comment by daipom** [comment]
メモ: [use-web-animations](https://github.com/wellyshen/use-web-animations) を動かしてみる。

もし時間が足りなくなりそうであれば、途中で私の #1796 のOurBoardを題材にしてもらっても良いと思います。

**Comment by daipom** [comment]
何か動かしたことがあれば作業メモに簡単にメモしてもらえると嬉しいです！

**Comment by chiiira** [comment]
サンプルコードで用意されている一通りの機能は動かしてみました。
今のところフィードバックしたいことは見つかっていない状況です。

**Comment by daipom** [comment]
OurBoard

> OurBoard Webアプリ: https://www.ourboard.io/
> GitHub: https://github.com/raimohanska/ourboard

**Comment by daipom** [comment]
OurBoardを触って１番気になった点についてIssueを作ってみる方針！

**Comment by daipom** [comment]
ご本人の都合でここまでで終了
