### ISSUE TITLE
OSS Gateワークショップ2016-03-26: yuki0627: payjp-ruby: 作業ログ

### ISSUE THREAD

**Issue by yuki0627** [oss-gate/workshop#18]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by yuki0627** [comment]
*作業: インストール
https://github.com/payjp/payjp-ruby

**Comment by yuki0627** [comment]
*作業:インストール
ドキュメント
https://pay.jp/docs/api/

**Comment by yuki0627** [comment]
*作業:インストール
決済ページ作成

**Comment by yuki0627** [comment]
決済ページヘのリンク
<h2><%= link_to pay_path(@item.id) do "通常決済(クレジットカード)" end %></h2>

**Comment by yuki0627** [comment]
認証OK
https://pay.jp/docs/api/?ruby#認証

**Comment by yuki0627** [comment]
サンプルコードのAPIキーは使えないので自分のAPIキーを利用して顧客の登録OK

**Comment by yuki0627** [comment]
課金エラー
Cannot charge a customer that has no active card: cus_a67723dc15826b6a9be34bf6f0a0

顧客のカード登録を先に行えば通りそう

**Comment by yuki0627** [comment]
カード登録と課金OK
```
  #カード登録
  customer = Payjp::Customer.retrieve('cus_a67723dc15826b6a9be34bf6f0a0')
  customer.cards.create(
    number: "4242424242424242",
    exp_month: "12",
    exp_year: "2017",
    cvc: "123",
    name: "HOGE HOGE"
  )
  
  #課金
  Payjp::Charge.create(
    :amount => 3500,
    :customer => 'cus_a67723dc15826b6a9be34bf6f0a0',
    :currency => 'jpy',
  )
```

**Comment by yuki0627** [comment]
支払情報を取得
```@res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716b')```

結果
```
{ "id": "ch_9ac9e317a18a3afa8f3534853716b", "amount": 3500, "amount_refunded": 0, "captured": true, "captured_at": 1458960766, "card": {"id":"car_7949ddf458fa8886aaa1d549fbf6","address_city":null,"address_line1":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":"unchecked","brand":"Visa","country":null,"created":1458960766,"customer":"cus_a67723dc15826b6a9be34bf6f0a0","cvc_check":"passed","exp_month":12,"exp_year":2017,"fingerprint":"e1d8225886e3a7211127df751c86787f","last4":"4242","livemode":false,"metadata":{},"name":"HOGE HOGE","object":"card"}, "created": 1458960766, "currency": "jpy", "customer": "cus_a67723dc15826b6a9be34bf6f0a0", "description": null, "expired_at": null, "failure_code": null, "failure_message": null, "livemode": false, "metadata": {}, "object": "charge", "paid": true, "refund_reason": null, "refunded": false, "subscription": null }
```

**Comment by yuki0627** [comment]
存在しない支払情報を取得
```@res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716a')```
There is no charge with ID: ch_9ac9e317a18a3afa8f3534853716a

**Comment by yuki0627** [comment]
エラーを発生させた際エラーレスポンスが来ず、例外(Payjp::InvalidRequestError)が発生する
期待する結果はエラーが発生した際はエラーレスポンスが来ること

処理:支払情報を取得
正常(支払情報がある)
@res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716b')
結果
{ "id": "ch_9ac9e317a18a3afa8f3534853716b", "amount": 3500, "amount_refunded": 0, "captured": true, "captured_at": 1458960766, "card": {"id":"car_7949ddf458fa8886aaa1d549fbf6","address_city":null,"address_line1":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":"unchecked","brand":"Visa","country":null,"created":1458960766,"customer":"cus_a67723dc15826b6a9be34bf6f0a0","cvc_check":"passed","exp_month":12,"exp_year":2017,"fingerprint":"e1d8225886e3a7211127df751c86787f","last4":"4242","livemode":false,"metadata":{},"name":"HOGE HOGE","object":"card"}, "created": 1458960766, "currency": "jpy", "customer": "cus_a67723dc15826b6a9be34bf6f0a0", "description": null, "expired_at": null, "failure_code": null, "failure_message": null, "livemode": false, "metadata": {}, "object": "charge", "paid": true, "refund_reason": null, "refunded": false, "subscription": null }

異常(支払情報がない)
@res = Payjp::Charge.retrieve('ch_9ac9e317a18a3afa8f3534853716a')
結果(例外)
Payjp::InvalidRequestError: There is no charge with ID: ch_9ac9e317a18a3afa8f3534853716a
from /usr/local/rvm/gems/ruby-2.2.1/gems/payjp-0.0.3/lib/payjp.rb:224:in `handle_api_error'

期待する結果(エラーレスポンスで戻ってくる)
{
  "error": {
    "message": "There is no charge with ID: ch_9ac9e317a18a3afa8f3534853716a",
    "param": "id",
    "status": 404,
    "type": "client_error"
  }
}

**Comment by yuki0627** [comment]
やってないこと

他の処理でのエラーレスポンスの発生検証

**Comment by yuki0627** [comment]
* 作業：issueを出した
* 思っていること：issue読まれる？？
https://github.com/payjp/payjp-ruby/issues/5

**Comment by yuki0627** [comment]
* payjp-rubyをフォークしてローカルでソースをチェック開始
* バグ見つかるかな？

**Comment by yuki0627** [comment]
* アプリで読み込んでいるgemをローカルに変更
`gem 'payjp', path: '../payjp-ruby'`

**Comment by yuki0627** [comment]
* ローカルのgemはspringが読み飛ばすのでspringを停止

```
chmod +x bin/spring
bin/spring status
bin/spring stop
```

**Comment by yuki0627** [comment]
* issueがクローズドになった！
* とても早くてビックリ
https://github.com/payjp/payjp-ruby/issues/5
正しい挙動でドキュメントが間違っていたとのこと。
payjp-rubyのデバッグ不要

**Comment by yuki0627** [comment]
* エラーハンドリングを試す
* 今度はうまくいくはず

**Comment by yuki0627** [comment]
* エラーハンドリングOK(支払い情報取得)

`@res = e.json_body`

**Comment by yuki0627** [comment]
* 他のAPIの正常・エラー動作検証をします

**Comment by yuki0627** [comment]
* 返金APIの検証完了
* 他のAPIも多分OKかと

**Comment by kou** [comment]
おつかれさまでした！参加した感想をブログとかにまとめてくれるとOSS Gateワークショップの普及につながってうれしいです！
（次回からはフィードバックしたメンターの人にその場でcloseしてもらうようにしよう。おつかれ！とか言いながら。）
