### ISSUE TITLE
OSS Gate Workshop: online: 2024-03-09: hdkzkg: OrgChart: Work log

### ISSUE THREAD

**Issue by hdkzkg** [oss-gate/workshop#1800]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hdkzkg** [comment]
よく使う言語python
直近の案件で使いそうなライブラリ：組織図を作れるjavascriptのライブラリ

**Comment by hdkzkg** [comment]
javascriptの組織図ライブラリ
ライセンスはMIT
https://github.com/dabeng/OrgChart

**Comment by hdkzkg** [comment]
readmeに沿ってインストールする

**Comment by hdkzkg** [comment]
Usageの記述を読みながら実際にコードを書いてみる

**Comment by hdkzkg** [comment]
githubのreadme「CDN」のリンク
https://cdnjs.com/libraries/orgchart

のページで、https://cdnjs.cloudflare.com/ajax/libs/orgchart/4.0.1/js/jquery.orgchart.min.jsのスクリプトタグをコピーすると、
![image](https://github.com/oss-gate/workshop/assets/38377014/0fd49fd5-3aea-4cbc-9db5-4fc84066402c)

上記コピーしたhtmlファイルを開くと、
下記のエラーがconsoleに表示された。

Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/orgchart/4.0.1/js/jquery.orgchart.min.js' with computed SHA-512 integrity '0dLxVDV+RMilliGduh7uXePakPcIyPFCc9TGx1NDl9ehZJK/YHt84mNQDHqPR/XxZ4jnMYXi/0ff0QOtY5FbuA=='. The resource has been blocked.

**Comment by blacktoad30** [comment]
> 上記コピーしたhtmlファイルを開くと、 下記のエラーがconsoleに表示された。
> 
> Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/orgchart/4.0.1/js/jquery.orgchart.min.js' with computed SHA-512 integrity '0dLxVDV+RMilliGduh7uXePakPcIyPFCc9TGx1NDl9ehZJK/YHt84mNQDHqPR/XxZ4jnMYXi/0ff0QOtY5FbuA=='. The resource has been blocked.

ローカルのhtmlファイルで試してみたところ、同様のエラーが発生しました。

**Comment by blacktoad30** [comment]
`integrity`の値が合わない問題は、cdnjs側にありそうな気がする。
しかし、リンク元の情報をどこから仕入れているのかが分からない。

**Comment by daipom** [comment]
> 上記コピーしたhtmlファイルを開くと、 下記のエラーがconsoleに表示された。

cdnjs のことを全然知らないので恐縮なのですが、このコピー結果はhtmlファイルとして開いて何か動作することが期待される挙動ということなんですかね？

**Comment by blacktoad30** [comment]
@daipom 

> cdnjs のことを全然知らないので恐縮なのですが、このコピー結果はhtmlファイルとして開いて何か動作することが期待される挙動ということなんですかね？

たぶん、そうなのだと思います。(私もJS関連は詳しくないですが...)

**Comment by daipom** [comment]
期待値が分かっている状態であれば、この点が期待値通りにならないことについてフィードバックをできそうということになりますよね。

一方で、もしこのCDNが何に使うためのものなのかよくわからない、という状態なのであれば、このエラーについて詳しく調べるのとは別の観点で見てみたほうがよいかもしれません。

**Comment by blacktoad30** [comment]
- README: URLのリンク切れ
  https://github.com/cdnjs/packages?tab=readme-ov-file#contributing
  Discourseのリンクが切れている。(Discourseのディスカッショングループがもう存在していない?)
  https://github.com/cdnjs/cdnjs/discussions に移行した?

- `integrity` の値が間違っている
  https://github.com/cdnjs/cdnjs/discussions で報告する内容?

**Comment by daipom** [comment]
> 一方で、もしこのCDNが何に使うためのものなのかよくわからない、という状態なのであれば、このエラーについて詳しく調べるのとは別の観点で見てみたほうがよいかもしれません。

この場合、本来なら、もっとREADMEにCDNについて説明してほしい、というフィードバックの方向もありうるのですが、今回は

> Users could find the related CDN support

と書いてあるので、そもそもCDN supportが必要な人用の説明という感じにも見えて、CDNが必要ない人は読み飛ばせばいいような箇所であるかもしれませんね。

**Comment by daipom** [comment]
> * README: URLのリンク切れ
>       https://github.com/cdnjs/packages?tab=readme-ov-file#contributing
>       Discourseのリンクが切れている。(Discourseのディスカッショングループがもう存在していない?)
>       https://github.com/cdnjs/cdnjs/discussions に移行した?
> 
>     * `integrity` の値が間違っている
>       https://github.com/cdnjs/cdnjs/discussions で報告する内容?

OrgChart自体は問題なく一通り動いちゃった感じですか？

**Comment by blacktoad30** [comment]
@daipom はい。デベロッパーツールのコンソールに出力されたエラーメッセージ通りに、ハッシュ値を変更したところ動きました。

**Comment by daipom** [comment]
> @daipom
> 
> > OrgChart自体は問題なく一通り動いちゃった感じですか？
> 
> はい。デベロッパーツールのコンソールに出力されたエラーメッセージ通りに、ハッシュ値を変更したところ動きました。

おお！なんかフィードバックできそうですね！

**Comment by hdkzkg** [comment]
> * README: URLのリンク切れ
>   https://github.com/cdnjs/packages?tab=readme-ov-file#contributing
>   Discourseへのリンクが切れている。(Discourseのディスカッショングループがもう存在しない)
>   [cdnjsリポジトリのディスカッション](https://github.com/cdnjs/cdnjs/discussions) に移行した?
> * `integrity` の値が間違っている
>   https://cdnjs.com/libraries/orgchart にて、[orgchart.min.js](https://cdnjs.cloudflare.com/ajax/libs/orgchart/4.0.1/js/jquery.orgchart.min.js) の `integrity` のハッシュ値が違う。
>   [ディスカッション](https://github.com/cdnjs/cdnjs/discussions) で報告する内容?

cdnjs側の問題のようなので、cdnjs側でイシューを出す準備

**Comment by hdkzkg** [comment]
cdnjs側ではなく、orgchartへイシューを報告。cdnjsへ直接対応を依頼するかはorgchartの返答次第。

**Comment by hdkzkg** [comment]
sri、integrity、cdnで検索して同様のイシューはなさそう。

**Comment by blacktoad30** [comment]
メモ: イシューの内容について

- OrgChart
  `integrity` (SRI Hash) の値がおかしい (間違っている) ことの報告

- cdnjs
  README.md のリンク切れの報告、および変更の提案

**Comment by hdkzkg** [comment]
イシューのフォーマットなし。

タイトル
CDNのリンクをコピーしてそのまま使用するとエラーがでる

READMEのCDNにある[リンク先のページ](https://cdnjs.com/libraries/orgchart)で、orgchart.min.jsのリンクをコピーして使用すると下記のエラーとなる。
cdnのコピー
![image](https://github.com/oss-gate/workshop/assets/38377014/242dcb71-cf80-4dcf-81dd-3f70323b71ea)
consoleエラー内容
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/orgchart/4.0.1/js/jquery.orgchart.min.js' with computed SHA-512 integrity '0dLxVDV+RMilliGduh7uXePakPcIyPFCc9TGx1NDl9ehZJK/YHt84mNQDHqPR/XxZ4jnMYXi/0ff0QOtY5FbuA=='. The resource has been blocked.

itegrityの値をエラー内容の値に書き換えると、jsファイルがダウンロードできるようになる。

**Comment by hdkzkg** [comment]
英語に翻訳しました。
タイトル
Copying and pasting a CDN link directly can result in errors.

When using the [link for orgchart.min.js found in the README of a CDN](https://cdnjs.com/libraries/orgchart), the following error occurs.

### Copy link of cdn:
![image](https://github.com/oss-gate/workshop/assets/38377014/c318a55f-047f-405f-be6a-c75bad0efad2)

### Error Details:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/orgchart/4.0.1/js/jquery.orgchart.min.js' with computed SHA-512 integrity '0dLxVDV+RMilliGduh7uXePakPcIyPFCc9TGx1NDl9ehZJK/YHt84mNQDHqPR/XxZ4jnMYXi/0ff0QOtY5FbuA=='. The resource has been blocked.
```

### Solution:
By changing the integrity value to the one provided in the error details, the JS file becomes downloadable.

OS：windows 10 pro
browser：chrome  122.0.6261.112

**Comment by daipom** [comment]
良いと思います！

**Comment by hdkzkg** [comment]
今日はありがとうございました！
イシュー投稿までできました。
https://github.com/dabeng/OrgChart/issues/745
