### ISSUE TITLE
OSS Gate Workshop: Techouse: 2024-04-18: ReiFujise00: alt-tab-macos: Work log

### ISSUE THREAD

**Issue by ReiFujise00** [oss-gate/workshop#1811]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ReiFujise00** [comment]
普段 AltTab を使っているが、サムネイルの表示時に動作が重くなることがあった。https://github.com/lwouis/alt-tab-macos
サムネイルに実際の画面が表示されているのが原因ではないかと思い設定から切ったところ改善した。

**Comment by ReiFujise00** [comment]
カスタマイズするパラメータの説明で、行と表示するべきところが列となっていることに気づいた

**Comment by ReiFujise00** [comment]
動作が重くなるのは現状だと再現しなかった

**Comment by ReiFujise00** [comment]
starship という便利そうなツールを見つけたので試してみる。
https://starship.rs/ja-JP/

**Comment by ReiFujise00** [comment]
> [Nerd Font](https://www.nerdfonts.com/)がインストールされ、端末にて有効になっている（例えば、[FiraCode Nerd Font](https://www.nerdfonts.com/font-downloads)を試してみてください）。
ターミナル上での有効化の方法がわからない。
有効化できているか検証する方法が書いてあったりするといいのかも

**Comment by ReiFujise00** [comment]
brew からインストール
```
% brew install starship                                                                                                                                                             [main]
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Homebrew collects anonymous analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
ffmpeg@6             kubecolor            libscfg              manim                morpheus             oj                   policy_sentry        rustcat              valkey
gitu                 lexido               llvm@17              mantra               msieve               overarch             rage                 sysaidmin            vfox
jtbl                 liblc3               logdy                mdformat             navidrome            parsedmarc           redict               uni-algo
==> New Casks
arctic                         capcut                         flox                           hhkb-studio                    requestly                      viable
arm-performance-libraries      clearvpn                       fujifilm-x-raw-studio          outfox                         starnet2                       yandex-music
boltai                         ente-auth                      halloy                         phoenix-code                   toneprint

You have 1 outdated formula installed.

==> Downloading https://ghcr.io/v2/homebrew/core/starship/manifests/1.18.2
#################################################################################################################################################################################### 100.0%
==> Fetching starship
==> Downloading https://ghcr.io/v2/homebrew/core/starship/blobs/sha256:38e579d1d0b477e004118a7d61125692a76eb00b01f1ae61531a5de52a7d8fc9
#################################################################################################################################################################################### 100.0%
==> Pouring starship--1.18.2.arm64_sonoma.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/starship/1.18.2: 11 files, 6.7MB
==> Running `brew cleanup starship`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by daipom** [comment]
> カスタマイズするパラメータの説明で、行と表示するべきところが列となっていることに気づいた

「翻訳がおかしいと思う。なおし方教えてくれたら直すよ。」
みたいなissueを作るのはアリだと思います！

**Comment by daipom** [comment]
> 普段 AltTab を使っているが、サムネイルの表示時に動作が重くなることがあった。https://github.com/lwouis/alt-tab-macos サムネイルに実際の画面が表示されているのが原因ではないかと思い、設定から切ったところ改善した。

「この設定をオフにするとパフォーマンスが改善するかもしれない」というissueを作るとか、READMEにそういう記載を追加するPRを作るとか、アリだと思います。

**Comment by ReiFujise00** [comment]
Zsh は `eval "$(starship init zsh)"` を ~/.zshrc に追記するとあったので追記して source した。

```
$ echo 'eval "$(starship init zsh)”' >> ~/.zshrc
$ source ~/.zshrc
```
みたいに書いてもらえると簡単なのかもしれない

**Comment by ReiFujise00** [comment]
- 行ったこと
    - AltTab の設定から、外観のカスタマイズを行なった。
    - 「サムネイルの列」の値を4 にしているが、サムネイルが表示される列数は4つで行数が1行となった。
    - 「サムネイルの列」の値を4 -> 2 に変更したところサムネイルが表示される列数は3列となり、行数が2行となった。
    - ここから「サムネイルの列」が設定しているのはサムネイルが表示される行数であることが分かった。
    - また、英語の説明では「Rows of thumbnail」となっているため、日本語に翻訳すると「サムネイルの行」となる
- 問題点
    - 「サムネイルの列」を変更すると一つの行に表示されるサムネイルの数が変更されるのかと思うが、実際にはサムネイルの表示される行数が変更されるため混乱する
  - 期待する結果
    - 設定項目名が「サムネイルの行」と表示されること
<img width="657" alt="image" src="https://github.com/oss-gate/workshop/assets/108464619/bffc2d60-8fbf-41e5-b0b7-7fba7ce8ef0e">

**Comment by daipom** [comment]
翻訳リソース見つけました

https://github.com/lwouis/alt-tab-macos/blob/master/resources/l10n/ja.lproj/Localizable.strings
