### ISSUE TITLE
OSS Gate Workshop: Techouse: 2024-04-18: nodematerial: test-prof: Work log 

### ISSUE THREAD

**Issue by nodematerial** [oss-gate/workshop#1812]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nodematerial** [comment]
test-prof Gem で進める
https://github.com/test-prof/test-prof

**Comment by nodematerial** [comment]
社内のリポジトリではすでに使用されているが、改めてインストールから行ってみる
1. `gem install rails`
2. `rails new oss_work`
3. Gemfile を編集して、test-prof を追加 https://github.com/test-prof/test-prof?tab=readme-ov-file
4. `bundle install`
5. 適当なモデルと、それに対するテストを追加する

**Comment by nodematerial** [comment]
最低限の model と RSpec を書いて準備を行う

```
# frozen_string_literal: true

require 'rails_helper'

RSpec.describe User, type: :model do
  let(:user) { User.build }

  describe 'hello_world' do
    it 'returns Hello World!' do
      expect(user.hello_world).to eq 'Hello World!'
    end
  end

  describe 'hello_world2' do
    it 'returns Hello World2!' do
      expect(user.hello_world2).to eq 'Hello World2!'
    end
  end

  describe 'name_with_age' do
    before do
      user.name = 'Alice'
      user.age = '20'

    end

    it 'returns Hello World!' do
      expect(user.name_with_age).to eq 'Alice(20)'
    end
  end
end
```

```
# frozen_string_literal: true

class User < ApplicationRecord
  validates :age, presence: true
  validates :name, presence: true

  def hello_world
    'Hello World!'
  end

  def hello_world2
    'Hello World2!'
  end

  def name_with_age
    "#{name}(#{age})"
  end


end

```

**Comment by nodematerial** [comment]
日本語対応していないことが判明した

**Comment by nodematerial** [comment]
課題
* 公式ドキュメントが日本語対応していない

<img width="219" alt="スクリーンショット 2024-04-18 14 24 37" src="https://github.com/oss-gate/workshop/assets/69585273/8784e4a7-2a50-49a9-a638-1f14bd0dad6a">

**Comment by nodematerial** [comment]
test-prof を開発している組織が、日本支部を有していそうなので、対応してもらえるかもしれない
https://evilmartians.jp/

**Comment by nodematerial** [comment]
提案用の文章を作成する

私の周りの人はこの Gem を頻繁に使用しています！ しかし英語が苦手な人は公式ドキュメントを読むのに苦労し、多くの機能を持つこの Gem を十分に使いこなせていません。

そのため、ロシア語や中国語と同様に、日本語訳を公式ドキュメントで選択できることが可能になると、とても喜ばしいです。

私は公式ドキュメントがどのようにホスティングされ、どのような方法で訳文が提供されているかを推測することができませんでしたが、もし私が協力できることがあれば、お手伝いしたいと考えております。
(例えば文章が手動翻訳されているのであれば、私は翻訳を行いたいと考えております）


![Uploading image.png…]()

**Comment by nodematerial** [comment]
Hello, I hope this message finds you well. I'm a  enthusiast of the test-prof Gem, currently residing in Japan.

I humbly propose the inclusion of Japanese translations within the documentation.

Within my community, the utilization of this Gem is widespread! However, individuals not proficient in English often encounter challenges comprehending the official documentation, thus limiting their ability to use diverse functionalities of this Gem.

Consequently, it would be immensely beneficial and delightful if an option were available to access Japanese translations alongside Russian and Chinese translations within the official documentation.

While I'm uncertain about the logistics of hosting the official documentation and providing translations, I would be more than willing to contribute to the effort, whether through manual translation or any other means.

Warm regards.

**Comment by nodematerial** [comment]
Discussion を作成した
https://github.com/test-prof/test-prof/discussions/288

**Comment by daipom** [comment]
ドキュメントは https://github.com/test-prof/docs でやってそう

**Comment by daipom** [comment]
翻訳ガイド: https://github.com/test-prof/docs/blob/master/TRANSLATIONS.md

**Comment by nodematerial** [comment]
返信が来た
https://github.com/test-prof/test-prof/discussions/288

**Comment by nodematerial** [comment]
日本語訳の第一弾がリリースされた
https://twitter.com/palkan_tula/status/1785078967877431693

**Comment by daipom** [comment]
おおおお！！やりましたね！！

**Comment by nodematerial** [comment]
まだまだ訳す箇所はたくさんあるので、少しずつ進めていきます！
