### ISSUE TITLE
OSS Gate Workshop: techouse: 2024-04-18: Kaffff: ${OSS_NAME}: Work log

### ISSUE THREAD

**Issue by Kaffff** [oss-gate/workshop#1814]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Kaffff** [comment]
vscode の拡張機能が気になっている
https://marketplace.visualstudio.com/items?itemName=MateuszDrewniak.ruby-test-runner

**Comment by Kaffff** [comment]
リポジトリはGitLab
https://gitlab.com/mateuszdrewniak/ruby-test-runner/-/issues/?sort=created_date&state=all&first_page_size=20

**Comment by Kaffff** [comment]
Gitlab のアカウントがなかったので作成し、SSH鍵を登録

**Comment by Kaffff** [comment]
まずは issue を作成するためにインストールからのコマンドが失敗するまでの手順を詳細に示す

**Comment by Kaffff** [comment]
1. 拡張機能をインストール
2. 実行ボタンを押す

拡張機能のバージョン 0.3.8

以下のコマンドが実行
```
 /Users/kaffff/.vscode/extensions/mateuszdrewniak.ruby-test-runner-0.3.8/print_and_save docker compose exec rails bundle exec rake test TEST= /Users/kaffff/src/github.com/Kaffff/RailsExample/test/test.rb
```

**Comment by Kaffff** [comment]
キャプチャとれる環境がないので、docker環境から作る

**Comment by daipom** [comment]
あ、コマンド結果だけで十分そうであれば無理にキャプチャを取る必要はないですよ！
GUIが関係してくる話の場合はキャプチャあるといいんですけど、今回は多分そうじゃなさそうですよね

**Comment by Kaffff** [comment]
1. 拡張機能をインストール
2. 実行ボタンを押す

拡張機能のバージョンは 0.38.0

cpu: Apple M1 Pro
macOS: 14.4.1
vscode: 1.88.1
rails: 6.1.7.7
minitest: 5.18.1



<img width="54" alt="image" src="https://github.com/oss-gate/workshop/assets/52491088/1b26f489-ec1e-45dc-a63a-eb694f182f5d">

再生ボタンを押すと、以下がターミナルで実行される
```
 /Users/kaffff/.vscode/extensions/mateuszdrewniak.ruby-test-runner-0.3.8/print_and_save docker compose exec rails bundle exec rails test /Users/kaffff/src/github.com/Kaffff/RailsExample/test/models/user_test.rb
```

**Comment by Kaffff** [comment]
ファイルパスが絶対パス ` /Users/kaffff/src/github.com/Kaffff/RailsExample/test/models/user_test.rb` で指定されてしまうためエラーが発生

期待の挙動としては 相対パス `test/models/user_test.rb` で指定されること
```
 /Users/kaffff/.vscode/extensions/mateuszdrewniak.ruby-test-runner-0.3.8/print_and_save docker compose exec rails bundle exec rails test test/models/user_test.rb
```

**Comment by Kaffff** [comment]
参考になりそうな issue を発見
https://github.com/vitest-dev/vscode/issues/135

そのまま使えそう
> Is your feature request related to a problem? Please describe.
> I'm running my client on Docker, and would like to be able to initiate my tests from vscode on my host machine.
> I can almost do so, by changing the extension settings to call a different command; however, the filenames to test are incorrect for my docker machine.
> 
> Describe the solution you'd like
> I think the easiest solution would be an options to setup a relative path mode.
> Instead of passing the file "/home//repos//tests/a.test.ts", passing "tests/a.test.ts"
> Or a way for me to remap "/home//repos//" to whatever file structure the docker image is using (less preferred)

**Comment by Kaffff** [comment]
参考になりそうな issue を発見

そのまま使えそう
> Is your feature request related to a problem? Please describe.
> I'm running my client on Docker, and would like to be able to initiate my tests from vscode on my host machine.
> I can almost do so, by changing the extension settings to call a different command; however, the filenames to test are incorrect for my docker machine.
> 
> Describe the solution you'd like
> I think the easiest solution would be an options to setup a relative path mode.
> Instead of passing the file "/home//repos//tests/a.test.ts", passing "tests/a.test.ts"
> Or a way for me to remap "/home//repos//" to whatever file structure the docker image is using (less preferred)

**Comment by Kaffff** [comment]
vscode-rdbg という拡張機能では localfsMap というオプションで同様の問題を解決している

**Comment by Kaffff** [comment]
# Docker support or relative path option

I am running a Rails application on Docker and was challenged to be able to use the extension to start tests from vscode on the host machine.
From the extension settings, I was able to change the command to run to the command for the docker environment.
However, the filename to test is specified as an absolute path, which does not match the file path on Docker and does not work correctly.

### Steps to reproduce
Extension settings docker compose exec app bundle exec rails t to unitTestCommand  
Press the Start Unit Test button

my environment
- Ruby Test Runner 0.38.0
- vscode 1.88.1
- rails 7.0.7 (on docker)
- minitest 5.18.1

### What is Expected?
```
/home/.vscode/extensions/mateuszdrewniak.ruby-test-runner-0.3.8/print_and_save docker compose exec app bundle exec rails test t tests/a_test.rb
```

### What is actually happening?
```
/home/.vscode/extensions/mateuszdrewniak.ruby-test-runner-0.3.8/print_and_save docker compose exec app bundle exec rails test t  /home/repos/tests/a_test.rb
```
=> `LoadError: cannot load such file -- /home/repos/tests/a_test.rb`

### Suggestion
I suggest adding a relative path option to the extension options.
Instead of passing the file "/home/repos/tests/a_test.rb", pass "tests/a_test.rb" and it will work on the docker environment.

**Comment by Kaffff** [comment]
初Issue 🎉
https://gitlab.com/mateuszdrewniak/ruby-test-runner/-/issues/8
