### ISSUE TITLE
OSS Gate Workshop: Techouse: 2024-04-18: pupudesu: annotate_models: Work log

### ISSUE THREAD

**Issue by pupudesu** [oss-gate/workshop#1816]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by pupudesu** [comment]
インターン生の時、作業で新しいモデル作ってました。
アノテーションをつけるためにannotate_modelsというgemを使おうと思ったので、使い方わからなかったので[githubページ](https://github.com/ctran/annotate_models)を見てみました。

**Comment by pupudesu** [comment]
After checking out their Usage section, I figured that I can use the `annotate --models` command.
<img width="856" alt="Screenshot 2024-04-18 at 12 00 00" src="https://github.com/oss-gate/workshop/assets/111111072/0f51c761-9d75-411a-9f54-79f28c6397c7">

I tried using it and it annotated not only the model I made, but also rewrote other models annotations.
I was confused because I didn't touch other models, then I realized that the other model annotations were not up to date.
This is an issue for sure, but I didn't want to include these changes in my pull request because it's out of scope.

**Comment by pupudesu** [comment]
I wondered if there is a way to annotate a specific file, just like how rspec is capable of running a specific test by adding file name after the command, so I tried searching some relevant keywords in the readme page, but I couldn't find anything.

I then checked if it's registered in issue and found a pretty similar problem:
https://github.com/ctran/annotate_models/issues/989

**Comment by pupudesu** [comment]
Thinking that it's probably similar to rspec, I then tried this command:
`annotate --models <model_file_path>` 
With this command, I got the annotation done only to that model, factory, and spec files.

Since this is what the issue author probably wants to do, I wrote a comment there.

**Comment by pupudesu** [comment]
I then checked the readme to see whether it's mentioned.
I saw that although there is no singe model command example, it is mentioned in Options that it's doable.

<img width="859" alt="Screenshot 2024-04-18 at 12 29 24" src="https://github.com/oss-gate/workshop/assets/111111072/f6437d53-6e51-4ae8-824d-d51f69073028">

However, I think this is hard to notice especially as a beginner, so I thought it would be nice to have it specifically explained as an example in the readme.

**Comment by daipom** [comment]
* READMEにexampleを追加するPRを作ってみるとよさそう！
* 足りない機能について機能リクエストするissueを作るのもいいかも！

**Comment by pupudesu** [comment]
> * READMEにexampleを追加するPRを作ってみるとよさそう！
> * 足りない機能について機能リクエストするissueを作るのもいいかも！

さっき相談した時もそうする予定ですので、今からやろうと思ってます！

**Comment by pupudesu** [comment]
Based on that, I submitted a pull request to include the single model use case.
<img width="1253" alt="Screenshot 2024-04-18 at 15 56 49" src="https://github.com/oss-gate/workshop/assets/111111072/97b87e4f-8b33-4868-a9e9-c81a473aed2e">
