### ISSUE TITLE
OSS Gate Workshop: Techouse: 2024-04-18: shiro-tec: iTerm2: Work log

### ISSUE THREAD

**Issue by shiro-tec** [oss-gate/workshop#1817]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shiro-tec** [comment]
iTerm2 の公式サイト（https://iterm2.com/）に "iTerm2 is licensed under GPL v2." と記載されていた。
opensource.org/licenses で検索すると GPL-2.0 の登録が確認できた。

**Comment by shiro-tec** [comment]
公式サイトに大きく Download ボタンがあるので押してアプリケーションファイルを起動すると問題なく起動できた

**Comment by shiro-tec** [comment]
PointerとKeyBoardの節は不具合なく進められたが、設定項目を探すのに時間がかかったしまった
図があるとわかりやすいかもしれない

**Comment by Nozomi-Hijikata** [comment]
https://www.warp.dev/

warpという選択肢も、、、

**Comment by daipom** [comment]
`[documentation ページ](https://iterm2.com/documentation.html)`

[documentation ページ](https://iterm2.com/documentation.html)

**Comment by Nozomi-Hijikata** [comment]
@shiro-tec 
https://github.com/gnachman/iTerm2

**Comment by Nozomi-Hijikata** [comment]
<img width="694" alt="スクリーンショット 2024-04-18 12 55 08" src="https://github.com/oss-gate/workshop/assets/116155762/c96bcea6-1111-4bbe-afd4-5f9708785803">

GitlabはIssue側に乗ってそう

**Comment by shiro-tec** [comment]
ドキュメントはバージョンごとにディレクトリを分けられているらしい
https://github.com/gnachman/iterm2-website/tree/master/source

**Comment by shiro-tec** [comment]
https://iterm2.com/news.html
3.5のベータ版が出ているようだがダウンロードしたアプリケーションのバージョンは3.4.23
[Webサイトのドキュメント](https://iterm2.com/documentation.html)はバージョン3.4のもの

**Comment by shiro-tec** [comment]
タイトル: Edit Current Session で説明されている設定項目の開き方がわかりにくい

再現手順
1. 公式サイト (https://iterm2.com/index.html) を開く
2. Documentation > General Usage とアクセスする
3. Edit Current Session の節に移動する

期待する結果
Session の編集画面を開く方法が読み取れる

実際の結果
Edit Current Session という名前のメニューはなく、メニューバーに Session > Edit Session... というメニューがあるが開かれる設定画面のタイトルは "Preferences" なので _Edit Current Session_ panel を開けているのかがわかりにくい

**Comment by shiro-tec** [comment]
https://github.com/gnachman/iterm2-website/issues/99
