### ISSUE TITLE
OSS Gate Workshop: Techouse: 2024-04-08: ozachun: sidekiq-cron: Work log

### ISSUE THREAD

**Issue by ozachun** [oss-gate/workshop#1819]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ozachun** [comment]
sidekiq-cron で第四月曜日みたいな書き方ができると記載があったが、今使っているsidekiq-cronでは使用できなかった。
最新ver.でのみ使用できるものなのか？

**Comment by ozachun** [comment]
fujit にて、specのテストが下記のリンクに記載されている。
https://github.com/floraison/fugit/blob/b1521eb6abc777230f4512be09fd95dc0dc72f14/spec/cron_spec.rb#L855C5-L855C62

**Comment by ozachun** [comment]
そもそも、sidekiq を インストールして使えるようになるまでのコマンドがreadme網羅されていないのではないか？

**Comment by ozachun** [comment]
sidekiq を 起動するコマンド
bundle exec sidekiq -q default event

**Comment by ozachun** [comment]
sidekiqのgetting started に新しく始めた時の方法は書いてあった。
https://github.com/sidekiq/sidekiq/wiki/Getting-Started

**Comment by ozachun** [comment]
getting start のところで、粗探しできないか調べる

**Comment by ozachun** [comment]
使用しているバージョンは下記
2024-04-18T03:23:01.718Z pid=55527 tid=129j INFO: Booted Rails 7.0.7 application in development environment
2024-04-18T03:23:01.718Z pid=55527 tid=129j INFO: Running in ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
2024-04-18T03:23:01.718Z pid=55527 tid=129j INFO: Sidekiq Pro 5.5.8 / Sidekiq Enterprise 2.5.3, commercially licensed.

**Comment by ozachun** [comment]
fujitの readme
https://github.com/floraison/fugit

**Comment by Nozomi-Hijikata** [comment]
fugitはsidekiqのwrapperなので、第二月曜日の指定は、fugit側でextensionとしてサポートしているのではないか？

**Comment by Nozomi-Hijikata** [comment]
``` ruby
require 'fugit'

p Fugit.parse('every day at 12am').original  # ==> "0 0 * * *"
p Fugit.parse('every day at 12pm').original  # ==> "0 12 * * *"

p Fugit.parse('every day at 12:00am').original   # ==> "0 0 * * *"
p Fugit.parse('every day at 12:00pm').original   # ==> "0 12 * * *"
p Fugit.parse('every day at 12:00 am').original  # ==> "0 0 * * *"
p Fugit.parse('every day at 12:00 pm').original  # ==> "0 12 * * *"
p Fugit.parse('every day at 12:15am').original   # ==> "15 0 * * *"
p Fugit.parse('every day at 12:15pm').original   # ==> "15 12 * * *"
p Fugit.parse('every day at 12:15 am').original  # ==> "15 0 * * *"
p Fugit.parse('every day at 12:15 pm').original  # ==> "15 12 * * *"

p Fugit.parse('every day at 12 noon').original         # ==> "0 12 * * *"
p Fugit.parse('every day at 12 midnight').original     # ==> "0 24 * * *"
p Fugit.parse('every day at 12:00 noon').original      # ==> "0 12 * * *"
p Fugit.parse('every day at 12:00 midnight').original  # ==> "0 24 * * *"
p Fugit.parse('every day at 12:15 noon').original      # ==> "15 12 * * *"
p Fugit.parse('every day at 12:15 midnight').original  # ==> "15 24 * * *"

  # as of fugit 1.7.2
```

ヒントになりそう

**Comment by ozachun** [comment]
問題点
[sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) - recent versions of Sidekiq-Cron use fugit to parse cron strings
sidekiq-cornの最新バージョンで利用可能と書いてあるが、どのバージョンから利用できるのか？記載されていない。

期待値
どのsidekiq-cornのバージョンから利用可能なのか記載されていること

実際どうだったか
Booted Rails 7.0.7, Running in ruby 3.2.2, Sidekiq Pro 5.5.8 / Sidekiq Enterprise 2.5.3の場合、[0 5 * * mon#1]のように記載しても動作しなかった。

**Comment by ozachun** [comment]
## Issue description
https://github.com/floraison/fugit?tab=readme-ov-file 

A clear and concise description of what the issue is. (There is an example of a carefully filled issue at https://github.com/floraison/fugit/issues/18)

## How to reproduce

The simplest piece of code that reproduces the issue, for example:
```ruby
require 'fugit'
c = Fugit.parse('0 9 29 feb *')
p c.previous_time
```
Or else, please describe carefully what to do to see a live example of the issue.

## Error and error backtrace (if any)

(This should look like:
```
ArgumentError: found no time information in "0-65 * * * *"
  from /home/john/w/fugit/lib/fugit/parse.rb:32:in `do_parse'
  from ...
  from /home/john/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from /home/john/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
  from /home/john/.gem/ruby/2.3.7/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
  from /home/john/.gem/ruby/2.3.7/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  from /home/john/.gem/ruby/2.3.7/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
  from /home/john/.gem/ruby/2.3.7/bin/bundle:22:in `load'
  from /home/john/.gem/ruby/2.3.7/bin/bundle:22:in `<main>'
```
)

## Expected behaviour

A clear and concise description of what you expected to happen.

## Context

Please replace the content of this section with the output of the following commands:
```
uname -a
bundle exec ruby -v
bundle exec ruby -e "p [ :env_tz, ENV['TZ'] ]"
bundle exec ruby -r et-orbi -e "EtOrbi._make_info"
bundle exec ruby -r et-orbi -e "p [ :et_orbi, EtOrbi::VERSION ]"
bundle exec ruby -e "require 'fugit'; p [ :fugit, Fugit::VERSION ]"
bundle exec ruby -e "p [ :now, Time.now, :zone, Time.now.zone ]"
```

(It's supposed to look like
```
Darwin pollux.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018;
  root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin17]
[:env_tz, nil]
(secs:1553304485.185308,utc~:"2019-03-23 01:28:05.18530797958374023",ltz~:"JST")
(etz:nil,tnz:"JST",tziv:"2.0.0",tzidv:"1.2018.9",rv:"2.3.7",rp:"x86_64-darwin17",win:false,
  rorv:nil,astz:nil,eov:"1.1.7",eotnz:#<TZInfo::TimezoneProxy: Asia/Tokyo>,eotnfz:"+0900",
  eotlzn:"Asia/Tokyo",eotnfZ:"JST",debian:nil,centos:nil,osx:"zoneinfo/Asia/Tokyo")
"1.3.9"
```
)

## Additional context

Add any other context about the problem here.
