### ISSUE TITLE
2024-04-18 Techouse

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1820]
（グループごとのまとめ用）

**Comment by daipom** [comment]
グループB

* hoge
* foo
* bar

**Comment by ReiFujise00** [comment]
### グループC
- ワークショップ前のイメージ
  - OSS の開発は誰でも開発できるのは知ってたが、本当は偉い人しかやってないと思ってた
  - OSS は基本的に誰でも、PRとか issue 出せることは知ってたが、今あるOSSには自分の技術で改善できる課題はないと思っていた
  - 周りにはOSS活動をやっている人が結構いたが、何が楽しいのかわからなかった。
- ワークショップ後のイメージ
  - OSS の開発は本当に誰でも開発できる
  - OSS にも自分で貢献できるスキルがあることを学んだ
  - issue 出してみて、OSSに貢献できるのが楽しくてOSS活動やる人の気持ちが少し分かった。
  - 自分でもOSSに貢献する方法があることを知ってよかった。
  - 自分の使うツールの改善ができるのは結構楽しい

**Comment by ozachun** [comment]
グループA
ワークショップをやる前からの変化
・OSSを開発している人との近さを感じれた
・OSSは完璧なものなので自分が問題を指摘できるものではないと思っていたが、実際は気軽にできるものであった

他の人の作業を見て学びになったこと
・前回 issueを出した時からスピードが上がった
・慎重になりすぎるのは良くないので、思い切ってやってみるのはいい
