### ISSUE TITLE
OSS Gate Workshop: online: 2024-06-08: fusen: OSS_NAME: Work log

### ISSUE THREAD

**Issue by mugifusen** [oss-gate/workshop#1833]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mugifusen** [comment]
所属する組織で投げたissue
## What
ローカルで記事を確認するためにwsl2上でhugoをsnapでインストールした(hugo 0.126.1)
```
fusen@DESKTOP-VCO6K3F:~/slp/hugo-homepage$ hugo version
hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended
 linux/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=snap:0.126.1
```

hugo server -Dで記事を確認しようとした所、以下のようなエラーが発生した
```
fusen@DESKTOP-VCO6K3F:~/slp/hugo-homepage$ hugo server -D
Watching for changes in /home/fusen/slp/hugo-homepage/{archetypes,content,layouts,static,themes}
Watching for config changes in /home/fusen/slp/hugo-homepage/config.toml
Start building sites … 
hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended linux/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=snap:0.126.1

ERROR render of "404" failed: execute of template failed: html/template:404.html:62:18: no such template "_internal/google_analytics_async.html"
ERROR render of "page" failed: "/home/fusen/slp/hugo-homepage/themes/hugo-tranquilpeak-theme/layouts/_default/single.html:1:3": execute of template failed: template: _default/single.html:1:3: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:62:18: no such template "_internal/google_analytics_async.html"
ERROR render of "term" failed: "/home/fusen/slp/hugo-homepage/layouts/taxonomy/author.html:1:3": execute of template failed: template: taxonomy/author.html:1:3: executing "taxonomy/author.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:62:18: no such template "_internal/google_analytics_async.html"
Built in 78 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/home/fusen/slp/hugo-homepage/layouts/_default/list.html:1:3": execute of template failed: template: _default/list.html:1:3: executing "_default/list.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:62:18: no such template "_internal/google_analytics_async.html"
```

以下は同じようなエラー
https://discourse.gohugo.io/t/build-error-on-v0-125-2-calling-internal-template-internal-google-analytics-async-html/49410

hugo 0.125.2以降で"_internal/google_analytics_async.html"が非推奨になり、"_internal/google_analytics.html"が推奨になったみたい

解決方法
"google_analytics_async.html"を"google_analytics.html"にすべて置換する
これによってhugo server -Dで表示されるようになった
(とても雑な気がします)
```
find . -name "*.html" -exec sed -i 's/_internal\/google_analytics_async.html/_internal\/google_analytics.html/g' {} \;
```****

**Comment by blacktoad30** [comment]
snapstore: https://snapcraft.io/hugo
pypi: https://pypi.org/project/hugo/

**Comment by mugifusen** [comment]
vscodeでマークダウンを書き、pdfに変換する拡張機能がある。
pdfを全画面表示で閲覧するとき、画像の箇所だけスクロールがうまく動作しないことがある(モニター等で見る時)
これを調査してみる

**Comment by blacktoad30** [comment]
https://github.com/tomoki1207/vscode-pdfviewer

**Comment by mugifusen** [comment]
新しそうなossを探してます
以下を見ているけどossではなさそう
https://github.com/Joshua-Yu/graph-rag

**Comment by mugifusen** [comment]
https://github.com/BaranziniLab/KG_RAG#using-gpt

**Comment by mugifusen** [comment]
gpt3.5-turboを利用しているみたいだけどapi必要か確認中

**Comment by mugifusen** [comment]
hugoのホームページのヘッダにあるDocsとQ&Aの公式サイトのDocsの遷移先が異なる問題について調査

- ホームページ
https://gohugo.io/
- hugoのサポーター
https://discourse.gohugo.io/

**Comment by blacktoad30** [comment]
discourse でのバグを報告しているらしきページです
https://discourse.gohugo.io/t/discourse-bug/49244

**Comment by mugifusen** [comment]
discourse.gohugo.ioでアカウント登録をすることで報告できる

**Comment by daipom** [comment]
参考: Hugoのコントリビュートガイドライン

https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md

* HugoにおけるIssueとフォーラム(https://discourse.gohugo.io/)の使い分け
  * 質問はフォーラムで
  * バグだと確信するものについてはIssueで
    > If you believe you have found a defect in Hugo or its documentation, use the GitHub issue tracker
    > If you're not sure if it's a bug or not, start by asking in the [discussion forum](https://discourse.gohugo.io/).

**Comment by daipom** [comment]
元々のエラーについて: https://github.com/oss-gate/workshop/issues/1833#issuecomment-2155809946 

既存のIssueだとこれが関係ありそう？

https://github.com/gohugoio/hugo/issues/8549

**Comment by blacktoad30** [comment]
https://github.com/gohugoio/hugo/issues/10899

**Comment by mugifusen** [comment]
HUGOの公式サイトとdiscorseでヘッダにあるDocsの遷移先が異なるIssue内容
```txt
discorse.gohugo.ioのヘッダにあるDocsからはgohugo.ioに遷移する。しかし、gohugo.ioのDocsはHugo Documentationに遷移する。ユーザの操作性の観点から統一したほうが良いのではないでしょうか。具体的には、discorse.gohugo.ioのDocsの遷移先をHugo Documentationにすることが挙げられます。また、discorse.gohugo.ioのヘッダにあるHUGOの遷移先をgohugo.ioにする方が直感的であると思います
```

**Comment by blacktoad30** [comment]
Google Analyticsのテンプレートに関するドキュメントを見つけました。
https://gohugo.io/templates/embedded/#google-analytics

**Comment by mugifusen** [comment]
> HUGOの公式サイトとdiscorseでヘッダにあるDocsの遷移先が異なるIssue内容
> 
> discourse.gohugo.ioのヘッダにあるDocsからはgohugo.ioに遷移します。しかし、gohugo.ioのDocsはHugo Documentationに遷移する。ユーザの操作性の観点から統一したほうが良いのではないでしょうか。具体的には、discourse.gohugo.ioのDocsの遷移先をHugo Documentationにすることが挙げられます。

英語version
Docs in the header of discorse.gohugo.io will take you to gohugo.io. But Docs in gohugo.io transitions to Hugo Documentation. It would be better to unify them from the viewpoint of user usability. Specifically, the transition destination of Docs in discorse.gohugo.io should be Hugo Documentation.

**Comment by mugifusen** [comment]
リンクありの日本語version

https://discourse.gohugo.io/ のヘッダにある"Docs"からはhttps://gohugo.io/に遷移します。しかし、https://gohugo.io/の"Docs"はHugo Documentationに遷移します。ユーザの操作性の観点から統一することを提案します。具体的には、https://discourse.gohugo.io/の"Docs"の遷移先をhttps://gohugo.io/documentation/にすることが挙げられます。

**Comment by mugifusen** [comment]
テーマ名
The destination of the header "Docs" is different between https://discourse.gohugo.io/ and https://gohugo.io/

**Comment by blacktoad30** [comment]
本文の修正案です。

I suggest that “Docs” should be redirected to https://gohugo.io/documentation/.

“Docs” in the header of https://discourse.gohugo.io/ will take you to https://gohugo.io/. However, “Docs” in the header of https://gohugo.io/ leads to Hugo Documentation.

I felt it was confusing.

**Comment by mugifusen** [comment]
本文中にリンクが2つ以上あると報告できないみたいなので、以下のようにすると回避できるか試してみる
Hugo Documentation | Hugoはページのタイトルです

Suggesting that “Docs” should be redirected to [Hugo Documentation | Hugo](https://gohugo.io/documentation/)

The destination of the header “Docs” is different between https://discourse.gohugo.io/ and https://gohugo.io/ .

I felt it was confusing.
