### ISSUE TITLE
OSS Gate Workshop: online: 2024-06-08: wxqmailbox: Tabnine: Work log

### ISSUE THREAD

**Issue by wxqmailbox** [oss-gate/workshop#1835]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by wxqmailbox** [comment]
AIによるソースコードの補完を提供するVSCode (Visual Studio Code) の拡張機能

1.GitHub Copilot
説明: GitHubとOpenAIが共同開発した拡張機能で、AIがリアルタイムでコードの提案を行います。関数の自動生成やコードの一部を補完する機能があります。
インストール: GitHub Copilot - Visual Studio Marketplace

2. Tabnine
説明: TabnineはAIを用いたコード補完ツールで、複数の言語に対応しています。個々の開発者のコードスタイルに適応し、よりパーソナライズされた補完を提供します。
インストール: Tabnine - Visual Studio Marketplace

3.Kite
説明: KiteはAIを利用したコード補完ツールで、PythonやJavaScriptなどの多くのプログラミング言語をサポートしています。リアルタイムでのコード提案やドキュメントの表示などの機能があります。
インストール: Kite - Visual Studio Marketplace

4.IntelliCode
説明: Microsoftが提供するAI支援のコード補完ツールで、コードの文脈を理解し、最も関連性の高い補完を提供します。特にVisual Studioとの相性が良いです。

**Comment by wxqmailbox** [comment]
今日は、「1.GitHub Copilot」を選択します。

**Comment by daipom** [comment]
https://qiita.com/posi_posi/items/17efe284d68c640168bf

**Comment by wxqmailbox** [comment]
「1.GitHub Copilot」は、OSSではありません。
「2. Tabnine」は、MITライセンスですので、今日は、「2. Tabnine」にします。

**Comment by daipom** [comment]
ご本人のご都合で前半作業までで終了。
