### ISSUE TITLE
OSS Gate Workshop: ゆるい勉強会旭川: 2024-07-28: hana979: laravel/pint: Work log

### ISSUE THREAD

**Issue by hana979** [oss-gate/workshop#1852]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hana979** [comment]
https://github.com/laravel/pint を選びました。

https://github.com/laravel/pint/blob/main/LICENSE.md があり、MITライセンスだったので、OSSだと確認できました。

**Comment by hana979** [comment]
CONTRIBUTING.mdにコントリビュートの説明があった。
（LaravelのContribution Guideに従って行うように記載があった）

https://github.com/laravel/pint/blob/main/.github/CONTRIBUTING.md
https://laravel.com/docs/11.x/contributions

**Comment by fujiokayu** [comment]
公式ドキュメントにインストール方法や利用方法が記載してあった
- [Laravel Pint](https://laravel.com/docs/11.x/pint)

**Comment by hana979** [comment]
README.mdなどには、ローカルテストの記述はありませんでした。
なので、標準的なphpライブラリのパッケージのインストールやテストなどを試してみる。

**Comment by hana979** [comment]
テストを実行したらオールパスしました。
```
./vendor/bin/pest
```
<img width="1159" alt="スクリーンショット 2024-07-28 11 52 17" src="https://github.com/user-attachments/assets/b21732a7-cd70-4a0c-aa0b-3b51b8813fe8">

**Comment by hana979** [comment]
phpstanを実行してエラーが出た
```
hanada@toshiki pint % ./vendor/bin/phpstan
Note: Using configuration file /Users/hanada/study/oss-gate/pint/phpstan.neon.
⚠️  You're using a deprecated config option checkGenericClassInNonGenericObjectType ⚠️️

It's strongly recommended to remove it from your configuration file
and add the missing generic typehints.

If you want to continue ignoring missing typehints from generics,
add missingType.generics error identifier to your ignoreErrors:

parameters:
        ignoreErrors:
                -
                        identifier: missingType.generics

 27/27 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 -- ---------------------------------------------------------------------------- 
     Error                                                                       
 -- ---------------------------------------------------------------------------- 
     Some parallel worker jobs have not finished. while running parallel worker  
 -- ---------------------------------------------------------------------------- 


                                                                                                                        
 [ERROR] Found 1 error                                                                                                  
                                                                                                                        

⚠️  Result is incomplete because of severe errors. ⚠️
   Fix these errors first and then re-run PHPStan
   to get all reported errors.
```

**Comment by hana979** [comment]
どうやらメモリ不足によるエラーのようなので、オプションをつけて実行するとエラーは解決できた。
https://github.com/phpstan/phpstan/discussions/11137

```
hanada@toshiki pint % ./vendor/bin/phpstan --memory-limit=256G
Note: Using configuration file /Users/hanada/study/oss-gate/pint/phpstan.neon.
⚠️  You're using a deprecated config option checkGenericClassInNonGenericObjectType ⚠️️

It's strongly recommended to remove it from your configuration file
and add the missing generic typehints.

If you want to continue ignoring missing typehints from generics,
add missingType.generics error identifier to your ignoreErrors:

parameters:
        ignoreErrors:
                -
                        identifier: missingType.generics

 27/27 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


                                                                                                                        
 [OK] No errors                                                                                                         
                                                                                                                        
```

**Comment by hana979** [comment]
> ⚠️  You're using a deprecated config option checkGenericClassInNonGenericObjectType ⚠️️
> 
> It's strongly recommended to remove it from your configuration file
> and add the missing generic typehints.

以前として、非推奨オプションに関しての警告が出ていたが、「phpstan.neon


```
hanada@toshiki pint % ./vendor/bin/phpstan --memory-limit=256G
Note: Using configuration file /Users/hanada/study/oss-gate/pint/phpstan.neon.
 27/27 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


                                                                                                                        
 [OK] No errors                                                                                                         
                                                                                                                        
```

**Comment by hana979** [comment]
非推奨オプションのcheckGenericClassInNonGenericObjectTypeに関しては、削除する方針で良さそう。
削除後に再度、テストも実行したが問題なくパスしていることを確認した。

非推奨オプションの削除に関するPRを実行しようと思う

**Comment by hana979** [comment]
PRを送りました！
https://github.com/laravel/pint/pull/287
