### ISSUE TITLE
OSS Gate Workshop: ゆるい勉強会旭川: 2024-07-28: myou1985: django-debug-toolbar: Work log

### ISSUE THREAD

**Issue by myou1985** [oss-gate/workshop#1853]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by myou1985** [comment]
今日はDjango JazzBand下のDjango Debug ToolbarのIssue　”Dark mode text needs higher contrast”の中身を見ていきます。

**Comment by myou1985** [comment]
・作業ディレクトリを作った（OSSGate）
・作業環境を作った
`python -m venv venv`
・GitHubのDjango Debug ToolbarをGit Clone
`git clone https://github.com/jazzband/django-debug-toolbar.git`

**Comment by myou1985** [comment]
・GitHub上のReadMeを読み、ドキュメントが下記にあることが分かった
https://django-debug-toolbar.readthedocs.io/en/latest/
・ドキュメントを読み、Contributeのやり方の記載を見つけたため、この通りに進めていく
https://django-debug-toolbar.readthedocs.io/en/latest/contributing.html

**Comment by myou1985** [comment]
・ドキュメントに従い、下記コマンドを実行
`python -m pip install -r requirements_dev.txt`
`DJANGO_SETTINGS_MODULE=example.settings python -m django migrate`
ここでエラー
`'DJANGO_SETTINGS_MODULE' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。`
・開発環境がWindowsなので、DJANGO_SETTINGS_MODULE環境変数を用意する必要がある。下記コマンドを実行
`set DJANGO_SETTINGS_MODULE=example.settings`
`python -m django migrate`

**Comment by myou1985** [comment]
・ドキュメントに従い、下記コマンドを実行したところエラー
`make example`
・Windowsはmakeが入っていない！のでPathが通っている場所にmakeを置く

1. Pathを通す。Windowsのシステム環境変数(Path)に任意の場所を追加（C:\bin)
2. https://gnuwin32.sourceforge.net/packages/make.htmから「Binaries」をZipでダウンロード
3. zipないのbinディレクトリの中身を置く

・ここでmakeを再度実行、でエラー「libintl3.dllがない」といわれる
・よく見たら先ほどのページ下部に依存関係のダウンロードリンクがまとめられていたので、それぞれダウンロード
・普通にクリックすると404エラーになるため、Googleでdll名を検索
・どうやらそれぞれ末尾の数字を消したアドレスが正規の者らしい。同じく「Binaries」をZipでダウンロード
・ダウンロードしたもののbinフォルダの中身をPathを通した場所に置く
・makeを実行。makeが動く。

**Comment by myou1985** [comment]
・makeの中で下記エラー
`python example/manage.py migrate --noinput
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
DJANGO_SUPERUSER_PASSWORD=p python example/manage.py createsuperuser \
                --noinput --username="" --email="@mailinator.com"
'DJANGO_SUPERUSER_PASSWORD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
make: [example] Error 1 (ignored)
python example/manage.py runserver
Watching for file changes with StatReloader
Performing system checks...`
・makefile内の環境変数エラーなので、追加で環境変数を設定
`set DJANGO_SETTINGS_MODULE=example.settings`
・再度make example
・動いたので、試しにpython -m django test
`FAILED (failures=4, errors=1, skipped=25, expected failures=1)`
・これは置いておいて、サーバは動いたので動作確認をする

**Comment by myou1985** [comment]
・make exampleを動かすと下記エラーが発生
```
make: [example] Error 1 (ignored)
python example/manage.py runserver
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
make: *** [example] Error 1
```
・DEBUGがfalseの場合はALLOWED_HOSTSの設定が必要だよ、と言われているが…
・settings.pyを見てみると、DEBUG=Trueの記載あり。どうして…？
・再度Makefileを見てみる

**Comment by myou1985** [comment]
・エラーメッセージを見逃していた。
```
DJANGO_SUPERUSER_PASSWORD=p python example/manage.py createsuperuser \
                --noinput --username="" --email="@mailinator.com"
'DJANGO_SUPERUSER_PASSWORD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
make: [example] Error 1 (ignored)
```

**Comment by myou1985** [comment]
・右サイドにあるDjango Debug Toolbarで「Settings」を選択
・表示された文字列のコントラストがIssueの通りコントラストがpoorであることを確認
https://coolors.co/contrast-checker/acc8e5-ffffff

**Comment by myou1985** [comment]
・間違えた。コントリビュータの人が言っているものと動かしたexampleの背景色が違う
・取得しているソースはメインブランチであることを確認
・OSのモードに原因がある可能性あるため調査する
・OSのモードが「ライトモード」で、Toolbarが「ダークモード」の場合に再現した
・OSのモード判定部分に原因がありそうな予感

**Comment by myou1985** [comment]
・この部分のコントラストを修正する必要があるが、OSモードが「ダーク」の時の状態が正しいのか？
・OSモードとアプリのモードの２×２の検証をハードコピー付で添付してみる
  - OSライト/アプリライト
  - OSライト/アプリダーク
  - OSダーク/アプリライト
  - OSライト/アプリダーク

**Comment by myou1985** [comment]
・以下の内容でissueにコメント
「Windows環境下では、OSモードが「ライト」でかつアプリモードが「ダーク」の際に再現しました。
　コントラストは重要ですが、アプリのスタイルはOSモードに追従するのが良いのではないでしょうか。」
・コメントURLは下記：
https://github.com/jazzband/django-debug-toolbar/issues/1943#issuecomment-2254350530

**Comment by myou1985** [comment]
・ほかにW3Cなどのコントラストに関する英語情報があれば追記する

**Comment by myou1985** [comment]
・W3Cのコントラストに関する記載を探し、下記リンクの情報を共有（難しくて理解できないので、参考までに）
https://w3c.github.io/wcag/techniques/general/G18

**Comment by myou1985** [comment]
issueに返信あり。
訳：
OS モードを反映するという提案をいただきありがとうございます。それが妥当なデフォルトでしょう。
お二人のうちどちらかにこれらの変更を行う時間はありますか? これらの変更がツールバーに反映されるのを見たいです。

**Comment by myou1985** [comment]
・Chromeの開発者ツールで適用されているCSSを追ってみる
・ライトモードまたはデフォルト時はtoolbar.cssの19行目が適用されているように見えるが、ダークモード時は該当のものがない。設定漏れ？
`--djdt-panel-content-table-background-color: var(--djdt-background-color);`
・同様のスタイルをtoolbar.cssの64行目に追加。思った通りの適用を確認…
・結局、この設定漏れによりOSのダークモード時にもDjango Debug Toolbarのデフォルト(ライトモード時)CSSが適用されていたような気がする

**Comment by myou1985** [comment]
・issueにこちらでやってみる旨返信

**Comment by myou1985** [comment]
・プルリクを出すための準備をする
・ほかの方のプルリクを見ると自身のアカウントにforkして、修正用ブランチを切ってからプルリクを作っているようなので、作り方を調べて倣う
参考：https://qiita.com/y-vectorfield/items/b955617712f3b66359f2
・forkとupstreamの設定はできた。
・branchも作った
・commitの前に、コミット・プルリクに関するルールがないかcontribution guideを再確認
・今回のコミットに該当しそうなのはpre-commitを設定するくらい？設定してみる
`pre-commit install`
・インストールされたようだ
・コミットしてみる。コミットメッセージは英語で何となく。
・Pushして、あとはプルリクのみ？

**Comment by myou1985** [comment]
サポーターの方から指摘があったので、以下作業中

1. Jazzbandプロジェクトに参加登録しといてほしい（CoC同意とかのため
[](https://github.com/jazzband/django-debug-toolbar/blob/main/CONTRIBUTING.md)
2. 修正は1行だけなので、PRには説明をしっかり入れておきましょう
a.説明に元のissueの番号 #1943 を入れておくとissue側にもバックリンクされます。これは入れるべき
b.このPRをマージすると何が変わるのか
c.なぜその行を変更したか（このスレッドに書いてくれた通り、1つ指定の抜けを見つけたので、それを指定すると良さそうに見えた旨）
d.動作確認結果（スクショとか）

**Comment by myou1985** [comment]
・pre-commitでエラー
・改行コードがCRLFになっているとだめらしい。LFに変更しコミット～プッシュ

**Comment by myou1985** [comment]
・再度PRを作成
・issue番号を間違えた…修正

**Comment by myou1985** [comment]
無事マージされました！

**Comment by kou** [comment]
やりましたね！
