### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2024-09-21: shallowfield: Athenz: Work log

### ISSUE THREAD

**Issue by shallowfield** [oss-gate/workshop#1876]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shallowfield** [comment]
今日は何を触ろう

**Comment by shallowfield** [comment]
https://github.com/AthenZ/athenz
のutilがWindowsに対応していないのが許せない

**Comment by shallowfield** [comment]
https://github.com/AthenZ/athenz/blob/master/LICENSE

**Comment by shallowfield** [comment]
何故Home Directoryを取るのに標準ライブラリを使わないのか？
https://github.com/AthenZ/athenz/blob/master/utils/zms-cli/zms-cli.go#L84

**Comment by shallowfield** [comment]
環境変数周りが怪しい
https://github.com/AthenZ/athenz/blob/master/utils/zms-cli/zms-cli.go#L48

**Comment by shallowfield** [comment]
会社のPCを使っているからgitの設定が会社のアカウントになっているかも知れないので直す

**Comment by shallowfield** [comment]
良く分からないのでtestリポジトリを作った
https://github.com/shallowfield/test

**Comment by shallowfield** [comment]
https://github.com/shallowfield/test
認証をしました

**Comment by shallowfield** [comment]
CONTRIBUTINGを見る
https://github.com/AthenZ/athenz/blob/master/CONTRIBUTING.md

**Comment by shallowfield** [comment]
やはり先にissueを立てた方が良さそう。

内容

- utilsのCLIツールがWindows環境で実行すると動かないから困る
- 原因は環境変数関係のコードが環境依存になっているからだと思う

**Comment by shallowfield** [comment]
コード部分を見ています。
userとhomedirは分かるのですが、他の環境変数の扱いが良く分かっていない

**Comment by shallowfield** [comment]
Linuxは常にSOCKS5_PROXYの中身があるのか？

**Comment by blacktoad30** [comment]
https://github.com/cloudfoundry/socks5-proxy/blob/main/socks5_proxy.go
`SOCKS5_PROXY` で検索したら、上に出てきた

**Comment by shallowfield** [comment]
気にしている部分はこれ
https://github.com/AthenZ/athenz/blob/master/utils/zms-cli/zms-cli.go#L52

**Comment by shallowfield** [comment]
とりあえずユーザー名とHomeDirだけ修正してPRを投げる
どんな雰囲気のPRがあるのか確認する

**Comment by shallowfield** [comment]
過去の修正を見ていると、ユーザー名関連で更に修正が入っているので確認しています

**Comment by shallowfield** [comment]
社内事例でやはりUSER環境変数を参照したい場合があるということで追加の修正がなされていた。詳細が分からないので対応方針が分からない。

**Comment by shallowfield** [comment]
issueを上げるに留めておきます。
タイトル
request for multi-platform support for cli tools

**Comment by shallowfield** [comment]
next action

- 一旦社内で事情を知っている人に聞いてみる
- 問題なさそうならissueとPRをOSS版に上げる
