### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2024-09-21: 3-yuma-3: FlatGeobuf: Work log

### ISSUE THREAD

**Issue by 3-yuma-3** [oss-gate/workshop#1877]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 3-yuma-3** [comment]
https://flatgeobuf.org/

geojsonに独自のpropertyを生やしていると、JavaScriptではserialize, deserializeできるけど、Javaだとできなかった(半年~1年前頃)ので、直したい

**Comment by 3-yuma-3** [comment]
今もJavaだとserialize, deserializeできないのかを調べる

**Comment by 3-yuma-3** [comment]
flatgeobufのライセンス

https://github.com/flatgeobuf/flatgeobuf/blob/1d3647cec277aee63494a9f3b1958c3cb58674f5/LICENSE

opensource.org に書いてあるのでOSSという理解であってそう

https://opensource.org/licenses?ls=BSD-2-Clause

**Comment by 3-yuma-3** [comment]
2024-09-21 時点 `1d3647cec277aee63494a9f3b1958c3cb58674f5` で同じように動かないかどうかを試す

**Comment by 3-yuma-3** [comment]
JavaのAPI仕様がないので、generateするようにfeedbackするのもあり

**Comment by 3-yuma-3** [comment]
JavaScriptでdeserializeするexampleはあるけど、serializeするexampleはないので、作ってあげるといいのか

**Comment by 3-yuma-3** [comment]
contribution.mdがリポジトリにない

https://github.com/flatgeobuf/flatgeobuf/tree/1d3647cec277aee63494a9f3b1958c3cb58674f5

issueのtabには以下のような文章がある
> 👋Want to contribute to flatgeobuf/flatgeobuf?
If you have a bug or an idea, browse the open issues before opening a new one. You can also take a look at the [Open Source Guide](https://opensource.guide/).

https://opensource.guide/ja/

他にissueを漁ってみたけど、テンプレはなさそう

**Comment by 3-yuma-3** [comment]
issueを上げる文章を一部日本語で考える

title

```
serialize.js の exampleも欲しい
want node example serialize.js
```

body

```
このlibraryを使うのに初心者やけど、JavaScriptでのexampleとしてdeesrialize.jsがあってすごく助かりました。
I'm new to use this library.

```

**Comment by 3-yuma-3** [comment]
これぐらいの差分であればいきなりPR作っても良さそうとのこと。
issueにコードを貼ると、それも所有権の問題を気にされる可能性もあるので、
issueにコードを貼るときはコードブロック内にライセンスの表記とかするらしい。

**Comment by 3-yuma-3** [comment]
PR出した

https://github.com/flatgeobuf/flatgeobuf/pull/386

**Comment by 3-yuma-3** [comment]
次はJavaのexampleを作りたい

**Comment by youkidearitai** [comment]
> Might be a helpful example but I think I need to make it more clear that the current ts/js impl. doesn't make spatial index

What should I do?みたいに食い下がっても良さそうですね
