### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2024-09-21: seiya2130: TomatoBar: Work log

### ISSUE THREAD

**Issue by seiya2130** [oss-gate/workshop#1879]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by seiya2130** [comment]
Good First Issue探そうかな
https://goofi.vercel.app/?language=typescript

**Comment by seiya2130** [comment]
ライセンスはOSSトップの右画面に出ているか確認する
LICENSEファイルがあり、そこに記載されている
GitHubが自動判定している

**Comment by seiya2130** [comment]
ここで検索してあればライセンスとしてOK
https://opensource.org/licenses

**Comment by seiya2130** [comment]
公式の資料に基づいて触る、最新かつ正確
分かりにくければ自分が開発できるチャンス

**Comment by seiya2130** [comment]
普段使っているもの、開発環境が簡単なものから選ぶ

**Comment by seiya2130** [comment]
業務で使っている、勉強中のRSpecを見てみる
https://github.com/rspec/rspec-core

**Comment by seiya2130** [comment]
RSpecはstarが多かったからhomerowにしよう
https://github.com/nchudleigh/homerow

**Comment by seiya2130** [comment]
普段からもっとこうした方がいいのに、、とか思っていないと探すのむずい

**Comment by seiya2130** [comment]
これいいかも、ポモドーロタイマーのOSSでクリックじゃなくて入力にして欲しい
https://github.com/ivoronin/TomatoBar

**Comment by seiya2130** [comment]
ライセンスもOK
https://opensource.org/licenses?ls=MIT+license

**Comment by seiya2130** [comment]
READMEに動かし方が書いてないな

**Comment by seiya2130** [comment]
むしろそれをissueにすればいいのか

**Comment by seiya2130** [comment]
ある意味動かすことはできているからいいのか

**Comment by seiya2130** [comment]
ショートカットも入力できないな
<img width="248" alt="image" src="https://github.com/user-attachments/assets/2ca7994f-f278-4667-9809-801f06e8ffb7">

**Comment by seiya2130** [comment]
もうちょっと触ってみて

既存issue見る
関係あるものがないか確認
なければ自分で立てる
既存であるなら自分でも追加コメントする

**Comment by seiya2130** [comment]
ショートカットいけた、文字キーだとダメなのか
<img width="267" alt="image" src="https://github.com/user-attachments/assets/32960630-4b79-485a-aeb9-52d63e9bcdc5">

**Comment by seiya2130** [comment]
これissueじゃなくてただ感謝してるだけだけど、開発者からしたらめちゃくちゃ嬉しいだろうな
https://github.com/ivoronin/TomatoBar/issues/69

**Comment by seiya2130** [comment]
1!って同感って意味かな
https://github.com/ivoronin/TomatoBar/issues/66

**Comment by seiya2130** [comment]
issue見ていると今使っているアプリがどれだけフィードバックされてきたか分かる、便利であればあるほど
開発者とユーザーが一緒に積み上げてきたんだなぁ

**Comment by seiya2130** [comment]
会社のペアプロのおかげで色んなツール知っててよかった

**Comment by seiya2130** [comment]
報告は相手が知らない前提で書く、何をやって何をやらなかったか、期待結果も書く

**Comment by seiya2130** [comment]
すでに同じこと書いている人いた
https://github.com/ivoronin/TomatoBar/issues/26

**Comment by seiya2130** [comment]
フォークしたリポジトリに実装しているみたいだけどPRあげてほしいな

**Comment by seiya2130** [comment]
なんにせよ同じissueあったから+1!しておいた

**Comment by seiya2130** [comment]
フォークしたリポジトリでissueを実装したみたいだから、オリジナルのリポジトリでPR作れないか聞いてみる
https://github.com/ivoronin/TomatoBar/issues/85#issuecomment-2365017000

**Comment by seiya2130** [comment]
小さなバグ、マニュアル、typoなど探したり貢献しようと思えばある
大きな中のうち、一部だけでもいいから自分が担当するでいい
規模が大きいとそれだけ深い知識が必要
Nuxt>モジュールなど小さなところからでもいい
メーリングリスト=メンテナーがやっていることの報告
できることを積み上げていく

**Comment by seiya2130** [comment]
TomatBarはLocalizationファイルの日本語版とかに貢献してもいいかもしれない
https://github.com/ivoronin/TomatoBar/blob/main/TomatoBar/en.lproj/Localizable.strings#L14

日本人でも使っている人いるみたいだし
https://mono-post.com/2023/04/05/pomodoro-tomatobar/
https://www.youtube.com/watch?v=Zh85ZtisV-A

**Comment by youkidearitai** [comment]
翻訳はこれでできそうですね
https://sunny10side.com/localization-settings-in-xcode/

**Comment by seiya2130** [comment]
もしかしてメンテされてないからフォークしているのかも。。？

**Comment by seiya2130** [comment]
@daipom @youkidearitai 
先日はワークショップ開催ありがとうございました！
フォーク先のリポジトリに日本語のローカライズファイルを修正して無事マージされました
https://github.com/AuroraWright/TomatoBar/pull/3#event-14441737202

ワークショップ中にアドバイスいただいたお陰で、プルリクで初コントリビュートできました！

**Comment by daipom** [comment]
おめでとうございます！よかったです！
この方はイタリアの方で、日本語を勉強しているみたいですね！
PRの翻訳を読んで興味深いって言ってくれていますね！

ぜひ今後とも気楽にオープンソース開発を楽しんでもらえたらと思います！

**Comment by youkidearitai** [comment]
おめでとうございます！オープンソース開発楽しんでもらえたら幸いです！
