### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2024-09-21: toririm: biome: Work log

### ISSUE THREAD

**Issue by toririm** [oss-gate/workshop#1880]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by toririm** [comment]
とりあえずこれに
https://github.com/biomejs/biome-vscode

**Comment by toririm** [comment]
デュアルライセンス

- Apache License Version 2.0
- MIT License

**Comment by toririm** [comment]
インストール手順を調べた。
marketからインストールする手順がドキュメントには書かれていたが、サポーターの方に開発者向けの手順を調べるようアドバイスをいただき、[CONTRIBUTING.md](https://github.com/biomejs/biome-vscode/blob/main/CONTRIBUTING.md)をみることに

**Comment by toririm** [comment]
VSCode拡張のデバッグの仕方は下記を参考
https://code.visualstudio.com/api/get-started/your-first-extension

立ち上がったデバッグ用環境の Output: Biome を確認するとログが確認できた

**Comment by toririm** [comment]
ここのログの確認手順が分かりづらかったので、それを CONTRIBUTING.md の記載することで貢献していく方針にする

**Comment by toririm** [comment]
- VSCode 拡張の開発が初めての人にさっきのリンクを案内する
- ログの確認方法を明示する

**Comment by toririm** [comment]
- README の contributing からだけではなく、installation からも development build のやり方の案内を出してもよい

**Comment by toririm** [comment]
Biome本体に日本語ドキュメントのみ未翻訳の箇所があったので、そこを書いてもよい

https://biomejs.dev/recipes/continuous-integration/

https://biomejs.dev/ja/recipes/continuous-integration/

**Comment by toririm** [comment]
手元でtextlintなどを動かしてみた

既存のJP翻訳のPRのコメントを参考にPRを作成してみた
https://github.com/biomejs/website/pull/1186

**Comment by youkidearitai** [comment]
翻訳で足りないところとか増やしていけるとよいと思いました！！
