### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2024-12-14: kadowakiBNG: ???: Work log

### ISSUE THREAD

**Issue by kadowakiBNG** [oss-gate/workshop#1902]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kadowakiBNG** [comment]
どのようにOSSを探していけばいいかから知りたい

**Comment by kadowakiBNG** [comment]
仕事でmacOSのデスクトップアプリをSwiftで触ったから、OSSでそういうものがあるのか気になる

**Comment by KaitoMuraoka** [comment]
macOS のデスクトップアプリで、Swift製のものであれば、以下のようなものがあります
ご参考になれば、
https://github.com/coteditor/CotEditor
https://github.com/nikitabobko/AeroSpace

**Comment by kadowakiBNG** [comment]
ありがとうございます！CotEditorは使ってみたことありました。ちょっと見てみます

**Comment by kadowakiBNG** [comment]
CotEditorを昔調べ物で使った事あったけど、何かでしっくりこない感覚があった気がする。軽く使ってみて手をつけられないか見てみる

**Comment by kadowakiBNG** [comment]
あと.NET開発で使っていた、埋め込みのNoSQLのDBライブラリ（https://www.litedb.org）を同じ感覚でMac環境で使えるものないかとは思ってた

**Comment by Watson1978** [comment]
私が気になっている最近のエディタ https://zed.dev

**Comment by kadowakiBNG** [comment]
手をつけるOSSを明確に決めれていない。とりあえず前半で見つけていたsniffnetの使い方で気になる点があったため調べてみる。
https://github.com/GyulyVGC/sniffnet?tab=readme-ov-file

**Comment by kadowakiBNG** [comment]
リポジトリによるとライセンスはApache-2.0, MITの２つ

**Comment by kadowakiBNG** [comment]
インストール方法としてはインストーラがメインで、Alternative Methodとしてbrewによる方法が記載されており、
brewをとりあえず叩いてみたが使えるようになったのかよくわからない。brewは以下のように実行して正常終了したっぽいけど
```
% brew install sniffnet
==> Downloading https://ghcr.io/v2/homebrew/core/sniffnet/manifests/1.3.1
######################################################################### 100.0%
==> Fetching dependencies for sniffnet: ca-certificates and openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2024-
######################################################################### 100.0%
==> Fetching ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:7a
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.4.0
######################################################################### 100.0%
==> Fetching openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:706b2f22
######################################################################### 100.0%
==> Fetching sniffnet
==> Downloading https://ghcr.io/v2/homebrew/core/sniffnet/blobs/sha256:a1f464910
######################################################################### 100.0%
==> Installing dependencies for sniffnet: ca-certificates and openssl@3
==> Installing sniffnet dependency: ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2024-
Already downloaded: /Users/hiroshik/Library/Caches/Homebrew/downloads/e16b55434e8bc1472ffb41e1a71c1b853417578c631fa1b69e8730f8cafca76c--ca-certificates-2024-11-26.bottle_manifest.json
==> Pouring ca-certificates--2024-11-26.all.bottle.tar.gz
==> Regenerating CA certificate bundle from keychain, this may take a while...
🍺  /opt/homebrew/Cellar/ca-certificates/2024-11-26: 4 files, 239.4KB
==> Installing sniffnet dependency: openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.4.0
Already downloaded: /Users/hiroshik/Library/Caches/Homebrew/downloads/a8a169d38329b14f967d497d0ea77eee6dc5444175093fc7b26026b357e81736--openssl@3-3.4.0.bottle_manifest.json
==> Pouring openssl@3--3.4.0.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/openssl@3/3.4.0: 7,236 files, 33.4MB
==> Installing sniffnet
==> Pouring sniffnet--1.3.1.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/sniffnet/1.3.1: 9 files, 27.7MB
==> Running `brew cleanup sniffnet`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by kadowakiBNG** [comment]
ターミナルでコマンド叩くとGUIまで普通に起動した。。
Applicationに登録されるものだと思い込んでしまってた

**Comment by kadowakiBNG** [comment]
brewでインストールした後はターミナルでsniffnetと実行するってわかるようになってればいい気はした

**Comment by KaitoMuraoka** [comment]
> ターミナルでコマンド叩くとGUIまで普通に起動した。。
> Applicationに登録されるものだと思い込んでしまってた

↓からダウンロードすると Application に登録されますね
<img width="1134" alt="スクリーンショット 2024-12-14 16 28 29" src="https://github.com/user-attachments/assets/74866197-2800-49c2-b4f8-76a217f2e364" />

**Comment by kadowakiBNG** [comment]
別ページのGetting Startedのスクリーンショットはおそらく古いmacOSバージョンなのでこういうの見ると新しくしたくはなる
ただ同じ画面は自分の環境で再現できないかも
<img width="790" alt="スクリーンショット 2024-12-14 16 30 37" src="https://github.com/user-attachments/assets/ae45901b-0837-4716-a9db-cc5ad61967a3" />

**Comment by Watson1978** [comment]
一般的に DNS は UDP を使用すると思いますが、TCP も DNS で使用できるので、TCP でフィルターすると良いです？

**Comment by kadowakiBNG** [comment]
TCP/UDPでPort53を設定しても一見して取れているようには見えない。。

**Comment by kadowakiBNG** [comment]
使用方法で一瞬戸惑ったので改善提案してみようかと思ったけど、https://github.com/GyulyVGC/sniffnet/blob/main/CONTRIBUTING.md
によると寄付するか技術的な貢献を指定されてるような・・

**Comment by kadowakiBNG** [comment]
とりあえず、インストールの後に起動方法まで書いた方がわかりやすいんちゃう？という提案をする方向で対応してみる
