### ISSUE TITLE
OSS Gate Workshop: TOKYO: 2024-12-14: ymat19: vscode-neovim: Work log

### ISSUE THREAD

**Issue by ymat19** [oss-gate/workshop#1903]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ymat19** [comment]
やったことと結果を残す

**Comment by ymat19** [comment]
候補が以下
- https://github.com/VSpaceCode/VSpaceCode
- https://github.com/vscode-neovim/vscode-neovim
- https://github.com/lunarvim/lunarvim

**Comment by ymat19** [comment]
最初二つがVSCodeの拡張機能なので、インストール手順などのフィードバックが見つかりずらそう

**Comment by ymat19** [comment]
ライセンス見る

**Comment by ymat19** [comment]
-  https://github.com/VSpaceCode/VSpaceCode
  - MIT License
-  https://github.com/vscode-neovim/vscode-neovim
  - MIT License
-  https://github.com/lunarvim/lunarvim
  - GPL-3.0 license 

良さげ
https://opensource.org/license/mit
https://opensource.org/license/gpl-3-0

**Comment by ymat19** [comment]
vscodeのプロファイル？を変えて綺麗な環境を用意する

**Comment by ymat19** [comment]
多分用意できた

**Comment by ymat19** [comment]
３つのREADMEやPRの状況を見てみる

**Comment by ymat19** [comment]
- vspace code 
  - PR https://github.com/VSpaceCode/VSpaceCode/pulls?q=is%3Apr+is%3Aclosed
    - 元気そう
  - https://vspacecode.github.io/
    - ドキュメントがある

**Comment by ymat19** [comment]
- vscode neovim
  - https://github.com/vscode-neovim/vscode-neovim/pulls?q=is%3Apr+is%3Aclosed
    - 候補の中で一番賑わってる
  - README https://github.com/vscode-neovim/vscode-neovim

**Comment by ymat19** [comment]
- lunarvum
  - あまり動いてなさそう? https://github.com/LunarVim/LunarVim/pulls?q=is%3Apr+is%3Aclosed

**Comment by ymat19** [comment]
とりあえず　vscode neovim 　のREADMEを読む

**Comment by ymat19** [comment]
snapを使ってる場合の手順があったので、試しても良さそう

**Comment by ymat19** [comment]
see belowのリンクが生きてない

File and editor management commands such as :e/:q/:vsplit/:tabnext/etc are mapped to corresponding VSCode commands and behavior may be different ([see below](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#%EF%B8%8F--keybindings-shortcuts)).

**Comment by ymat19** [comment]
↓が正しいリンクっぽい。READMEのリンクは`-`が一個多い
https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#%EF%B8%8F-keybindings-shortcuts

**Comment by ymat19** [comment]
Troubleshootingセクションがインストール前提ぽいのでひとまずinstallしてみる
installの説明はneovimの0.10以上が必要としかかいてない

**Comment by ymat19** [comment]
インストールしたらとりあえず動いた

**Comment by ymat19** [comment]
vscodeが落ちる問題は自分だけじゃなかった模様
Windows依存でもないっぽい
issueを探してみる

**Comment by ymat19** [comment]
:wすると、buftypeなんとかで固まってた記憶がある。
最近は見てないのでなおった？
https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+buftype+

**Comment by ymat19** [comment]
READMEに戻る

**Comment by ymat19** [comment]
jjのエスケープとjkの保存設定を試してみる

**Comment by ymat19** [comment]
ポピュラーな設定が二つあるが、これを二つ並べても動作しない
ドキュメント
![image](https://github.com/user-attachments/assets/dca7cb2f-99f6-4b45-b703-b3af16fb14e3)
正しい書き方
![image](https://github.com/user-attachments/assets/c1f1de95-31a6-477f-ba5e-cebc14469ada)

**Comment by ymat19** [comment]
報告をまとめはじめる

**Comment by ymat19** [comment]
コントリビューションのドキュメントがあったが開発者向けっぽい
https://github.com/vscode-neovim/vscode-neovim/blob/master/CONTRIBUTING.md

good first issueタグがあるらしい

**Comment by ymat19** [comment]
issueのテンプレートが三つあった。リンクに飛べない話はBugで良さそうだが、設定サンプルの件はどれが良いか不明

- Bug Report
- Feature Request
- Report a security vulnerability

**Comment by ymat19** [comment]
Bug Reportテンプレ
![image](https://github.com/user-attachments/assets/9454f1f3-0d1c-4690-9507-dcdbee04d07d)

**Comment by ymat19** [comment]
修正が自明で簡易なのでPRを作ってみる

**Comment by ymat19** [comment]
リンクを直して遷移できた
https://github.com/ymat19/vscode-neovim/tree/docs/fix-keybindings-link

**Comment by ymat19** [comment]
PRの説明を日本語で下書きする

**Comment by ymat19** [comment]
下書き
日本語`💡 Tips and Features`セクションの`see below`のリンクが機能していなかったのを修正
英語　Fixed the issue where the `see below` link in the `💡 Tips and Features` section was not working

**Comment by ymat19** [comment]
タイトル
docs: Fixed link to keybindings section

**Comment by ymat19** [comment]
コミット名が規則に沿っていないっぽくてCIが通らない
直してforce push する
だめなら作り直す

**Comment by KaitoMuraoka** [comment]
> PRの説明を日本語で下書きする

<details>
<summary>日本語</summary>
ここに日本語の下書きを作成します。
</details>

```md
<details>
<summary>日本語</summary>
ここに日本語の下書きを作成します。
</details>
```

↑な感じで、日本語も一緒に載せるのも個人的にはアリだと思っています。
後から見返しやすいとか、色々メリットがあると思っています。

**Comment by ymat19** [comment]
force pushでCIが再走したのでいけそう

**Comment by ymat19** [comment]
<details>
<summary>日本語</summary>
テスト
</details>

**Comment by ymat19** [comment]
https://github.com/vscode-neovim/vscode-neovim/pull/2327
マージされてた。嬉しい
