### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2024-12-14: nhp65: ${OSS_NAME}: Work log

### ISSUE THREAD

**Issue by nhp65** [oss-gate/workshop#1904]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nhp65** [comment]
今日は[CudaText](https://cudatext.github.io)というテキストエディタを対象にしたいと思っています。
ライセンスはMPL 2.0で、[https://opensource.org/license](https://opensource.org/license)を見たところ、OSSライセンスに含まれていました。
以前使用したときShift-JISで日本語表示したとき半角カタカナが文字化けしたので、それが設定ミスによるものではないか、最新バージョンでも問題が発生するかなどを確認してIssueを送りたい。

**Comment by nhp65** [comment]
OSSか否かはライセンスで決まるというのは以前[OSS開発者に向けられる「搾取の精神」　まつもとゆきひろ氏が語る、正しい生産的関係に必要なのは “リスペクト”と“参加すること”](https://logmi.jp/main/technology/326575)を読んで知りましたが、[https://opensource.org/license](https://opensource.org/license)に含まれるものがOSS、という端的な調べ方は知らなかったので、それだけでも知見が増えたなと思いました。

**Comment by nhp65** [comment]
CudaTextの文字コードはデフォルトでUTF-8となっています
<img width="628" alt="image" src="https://github.com/user-attachments/assets/d70653c8-1116-48cf-89b0-f11358fa8b3a" />
文字コードをクリックし、【Convert to...】を選択すると文字コードの一覧が表示されます。
<img width="630" alt="image" src="https://github.com/user-attachments/assets/a62ee493-a0ad-4cc6-8b57-81e4e6820067" />
<img width="626" alt="image" src="https://github.com/user-attachments/assets/9ff07dc3-0069-450f-b180-6074acd16958" />
別の文字コードを選択して変換したのち、保存。その保存したファイルを開くと、文字コードが変換したものに変わっていることが確認できます
<img width="626" alt="image" src="https://github.com/user-attachments/assets/c80da0b0-d4a6-4a93-8fe8-a86177d1a263" />

**Comment by daipom** [comment]
関係ないですが、OSSのパワーシェルのドキュメントがあったのでリンク共有しておきます

https://learn.microsoft.com/en-us/powershell/

**Comment by daipom** [comment]
↑ GitHubはこれでした https://github.com/MicrosoftDocs/PowerShell-Docs

**Comment by daipom** [comment]
いいですね！これだけでも十分Issueにできそうに思います。
もっと情報があればもちろん足せた方がベターですが、それは可能な範囲で良いと思います。

**Comment by nhp65** [comment]
サポーターの方からのアドバイス

・他のテキストエディタで開くとどうなるか？（保存がおかしいのか？開くのがおかしいのか？）
　→他のテキストエディタでは正しく表示される（そのため、おそらくは読み込みの問題）
　→cp1252の状態で上書き保存しても他のテキストエディタでは正しく表示されるため、内部的に勝手に変換などはされていないっぽい

**Comment by nhp65** [comment]
ちなみにUTF-8ではちゃんと半角カタカナ表示される
<img width="633" alt="image" src="https://github.com/user-attachments/assets/75c5a458-3b9b-4ba3-b8b9-51e1353da451" />

**Comment by nhp65** [comment]
先頭が半角カタカナで始まっている場合、エラーメッセージがでる
<img width="262" alt="image" src="https://github.com/user-attachments/assets/c5bd777a-c24b-41da-85c3-be7249f6f3cd" />

文中に半角カタカナがある場合は上記のように文字コードがおかしくなる。

**Comment by nhp65** [comment]
材料が集まってきたのでそろそろまとめようかなと思う。
Github確認したら以下のような記載。
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/69bbb78c-f39b-429f-b9fc-8e544221ec4f" />

プロジェクト固有のルールでなく普遍的なものをどどんとお出しされるとどの程度読み込めばいいのかちょっと不安・・・

**Comment by daipom** [comment]
口頭でお話しましたが、これはGitHubがよしなに表示してくれているものなので、必要に応じて参考にすればよいという程度のものです。
このリポジトリーは特にルールを定めていないので、大丈夫です！

**Comment by nhp65** [comment]
> 口頭でお話しましたが、これはGitHubがよしなに表示してくれているものなので、必要に応じて参考にすればよいという程度のものです。 このリポジトリーは特にルールを定めていないので、大丈夫です！

ありがとうございます😊
意外とこういうところでつまづきがちなので、さっとアドバイスをいただけるのは大変助かります。

**Comment by nhp65** [comment]
既存のIssueの検索。
Shift-JISで検索→ヒット０
cp1252で検索→ヒット０
garbled, garbling(文字化けの意っぽい）→クローズでヒットするが違いそう

**Comment by nhp65** [comment]
タイトル候補
Shift-JISのエンコードで、半角カタカナが正しく表示されない
Half-width katakana characters are not displaying correctly with Shift-JIS encoding

本文
日本語の文字コード,Shift-JISでの問題です。
日本語は英数字の他にひらがな、カタカナ、漢字を文字として持ち、これらは全角文字なのですが、このうちカタカナのみ英数字と同じように半角も持っています。
UTF-8のこの半角カタカナを含むテキストファイルを表示したとき、正しく表示されます。
This is about Japanese character encoding issues with Shift-JIS.
Japanese text includes hiragana, katakana, and kanji characters in addition to alphanumeric characters. These are all full-width characters, but among them, only katakana also has half-width versions, similar to alphanumeric characters.
When displaying a text file containing these half-width katakana in UTF-8 encoding, it displays correctly.

<img width="624" alt="image" src="https://github.com/user-attachments/assets/8af31a38-41c1-44b4-afd4-16a96ef192ad" />

しかし、Shift-JISで保存された半角カタカナを含むテキストファイルは、
Cp1252と誤判定され、正しく表示されません。
However, when a text file containing half-width katakana is saved in Shift-JIS encoding,
it is incorrectly identified as cp1252 encoding and doesn't display properly.

<img width="627" alt="image" src="https://github.com/user-attachments/assets/b35a38b9-72cd-4d76-8d77-c5b2f8c99172" />

また、先頭が半角カタカナではじまるShift-JISのテキストファイルは、以下のようなエラーメッセージが表示されて、そもそも正しく読み込まれません。
Furthermore, when a Shift-JIS text file begins with half-width katakana,
an error message appears and the file cannot be loaded correctly.

<img width="265" alt="image" src="https://github.com/user-attachments/assets/c557ca8f-099d-4d3f-be95-83afd4477f7c" />

UTF-8と同じように、半角カタカナが含まれる文章が問題なく表示されることを期待します
I expect text containing half-width katakana to display without issues, just like with UTF-8.

以下のテキストをコピーして、試してみてください。
Please copy and test the following text.

```
あいうえおｱｲｳｴｵ
```

```
ｱｲｳｴｵ
```

このテストは、以下の環境で実行しました。
This test was executed in the following environment.

macOS Sequoia 15.1.1
cudatext-macos-cocoa-aarch64-1.219.1.0

**Comment by Watson1978** [comment]
https://www.unicode.org/charts/PDF/UFF00.pdf

**Comment by nhp65** [comment]
直すかどうかはともかくとりあえずコンパイル環境を整えようと思って手順を調べていたら、Wikiに記載があった
[https://wiki.freepascal.org/CudaText#How_to_compile_CudaText](https://wiki.freepascal.org/CudaText#How_to_compile_CudaText)
Tech topics/Encoding detection

> UTF-8コンテンツ検出は、ファイルの最初の8Kで動作します。UTF-16コンテンツ検出は、ファイルの最初の5Kで動作します。エンコーディングがUTF8として検出された場合、ファイルローダーは、UTF8文字が正しいかどうか、再度コンテンツ（現在のファイルサイズ全体）をチェックし、「UTF8文字が正しくない」と検出された場合、エンコーディングはANSIに変更されます。
> ANSIは実際のコードページの1つにマップされ、それは現在のWindowsロケールに依存します。Windows以外のOSでは、ANSIはcp1252にマップされます。
> UTF-8 content detection works by first 8K of file. UTF-16 content detection works by first 5K of file. If encoding was detected as UTF8, the file loader checks the content again (the entire file size now) for UTF8 chars correctness, and if it finds "not correct UTF8 chars", encoding will be changed to ANSI.
> ANSI maps to one of real codepages, it depends on current Windows locale. On non-Windows OS, ANSI maps to cp1252.

とあるので仕様というのはこのことを言っているのだろう。IssueだけでなくコードやWikiでももうちょっと検索かけるべきだった。
ただ、これを見るに、問題が単純に『Shift-JISがEncoding detectionされない』ことだととられてしまったような気がする。
shift-jisに設定してからテキストを読み込むとshift-jisにはなるのだがやはり半角カタカナがおかしくなってしまうので、こっちの軸でIssue建てた方が半角カタカナ固有の問題とはっきり言えてよかったな・・・（あとのまつり
<img width="573" alt="image" src="https://github.com/user-attachments/assets/e8eb4317-065f-422b-96e1-9baaa95565e2" />

これを踏まえてレスをするか、コード投げてって言われてるしちょっと時間置いてでも何か改善投げられないか検討するかどうしよう

**Comment by nhp65** [comment]
単にクローズされたと思ってたけどDiscussionsに移してもらっていたみたいだ。
上の内容で開発のひとからレスがついてた。それについては対応できそうだけれど、以下については調べないといけないな。

>  can you try to repeat the issue in the SynEdit in the Lazarus IDE? we may have incomplete shift-jis coding in Lazarus?

**Comment by daipom** [comment]
おお、これ早速修正されました？

**Comment by nhp65** [comment]
Elementsでもご報告しましたが、早速修正されていました！嬉しい！
