### ISSUE TITLE
OSS Gate Workshop: 東京: 2024-12-14: Yusuke-Hi: ${OSS_NAME}: Work log

### ISSUE THREAD

**Issue by Yusuke-Hi** [oss-gate/workshop#1906]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Yusuke-Hi** [comment]
ちょうどいい規模で貢献しやすいOSSを探し中

**Comment by Yusuke-Hi** [comment]
C++で書かれたライブラリなど？

**Comment by Yusuke-Hi** [comment]
ChatGPTにライブラリを聞いてみる
C++/数値計算/小規模

**Comment by Yusuke-Hi** [comment]
Eigenという数値計算ライブラリを確認する。
https://github.com/eigenteam/eigen-git-mirror

**Comment by Yusuke-Hi** [comment]
ライセンスはMozilla Public License 2.0
https://opensource.org/license/mpl-2-0
OSSであることを確認

**Comment by Yusuke-Hi** [comment]
公式ページを見ながら動かしてみる。

**Comment by Yusuke-Hi** [comment]
Getting startedページを見ながら、、、
https://eigen.tuxfamily.org/dox/GettingStarted.html

**Comment by Yusuke-Hi** [comment]
安定版をzipでインストール
https://eigen.tuxfamily.org/index.php?title=Main_Page#Download

**Comment by Yusuke-Hi** [comment]
解凍したディレクトリを実行環境に移動

**Comment by Yusuke-Hi** [comment]
サンプルコードを実行完了
期待していた結果になった
main.cpp
```
#include <iostream>
#include <Eigen/Dense>

using Eigen::MatrixXd;

int main(){
    MatrixXd m(2, 2);
    m(0, 0) = 3;
    m(1, 0) = 2.5;
    m(0, 1) = -1;
    m(1, 1) = m(1, 0) + m(0, 1);
    std::cout << m << std::endl; 
}
```

$g++ -I /dir/eigen-3.4.0 ./main.cpp -o main
$./main
  3  -1
2.5 1.5

**Comment by youkidearitai** [comment]
Issueの `Contributions welcome` タグを見てみました。
https://gitlab.com/libeigen/eigen/-/issues/?sort=created_date&state=opened&label_name%5B%5D=contributions%20welcome&last_page_size=20&page_before=eyJjcmVhdGVkX2F0IjoiMjAyMy0wNy0wNyAxMzoxNzoyNS4zNzI0NjkwMDAgKzAwMDAiLCJpZCI6IjEzMDQ2MTUwNyJ9

**Comment by Yusuke-Hi** [comment]
以下のサンプルコードを実行し、問題なく動作した。
動作説明が丁寧にされていて親切だと思った。
'''
#include <iostream>
#include <Eigen/Dense>

using Eigen::Matrix3d;
using Eigen::VectorXd;

int main(){
    Matrix3d m = Matrix3d::Random();
    std::cout << "m = " << std::endl 
        << m << std::endl;
    m = (m + Matrix3d::Constant(1.2)) * 50;
    VectorXd v(3);
    std::cout << "m = " << std::endl 
        << m << std::endl;
    std::cout << "m = " << std::endl 
        << Matrix3d::Constant(1.2) << std::endl;
    v << 1, 2, 3;
    std::cout << "m * v = " << std::endl
        << m * v << std::endl; 
}
'''

**Comment by Yusuke-Hi** [comment]
GitLabのREADMEから公式ページに飛ぶリンクをクリックすると接続エラーが起こることがわかった。（@youkidearitai さんから教えてもらった）

![image](https://github.com/user-attachments/assets/099d8f51-90df-45c6-aec4-b8df1aa97d12)

https://eigen.tuxfamily.org/index.php?title=Main_Page

**Comment by youkidearitai** [comment]
参考：EigenのContribution guideを見つけました。
https://eigen.tuxfamily.org/index.php?title=Contributing_to_Eigen

**Comment by Yusuke-Hi** [comment]
Issue文章の例

Official documentation page connection has weak connections aroud the site.
It takes few seconds to get new page, in sometime cannot get it because of certification error.

**Comment by Yusuke-Hi** [comment]
Issueしました。
https://gitlab.com/libeigen/eigen/-/issues/2885
