### ISSUE TITLE
2016年1月30日（土）にOSS Hack 4 Beginners相当のイベントを開催する

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#2]
# 目的

  * OSS Hack 4 Beginnersに参加していない人も「どういうイベントなのか」を体験する
    * 体験することで、どうすればOSS Gateを継続的に成果をあげられる取り組みにできるかをより考えれるようになることを期待。
  * [OSS Gate を立ち上げよう](https://oss-gate.doorkeeper.jp/events/33335)であがった継続的に成果をあげる案を試す
    * すべての案を100%の力で試すのではなく、試せるものは試せる範囲で試す。試して成果がでなくてもよい。試してフィードバックを得て、次の行動につなげられれば十分。なので、成果がでない案かもしれないというのがわかるということも重要なフィードバック。

# 内容

[OSS Hack 4 Beginnersの内容](https://github.com/clear-code/sezemi-2015/tree/master/oss-hack-4-beginners)をベースにOSS Gate向けにアレンジする。

# 規模

OSS Gateという取り組みに協力したい！という人たち（≒ OSS Gateを立ち上げように参加した人たち）がフィードバックを得られる規模でよい。[OSS Hack 4 Beginnersのアンケート結果](https://creativesurvey.com/public/results/d3f23880988141c2fe6338677436b3011b982137/questions/353746)を見るとOSS Hack 4 Beginnersは参加者が約30人だったが、もっと少なくても十分だと思う。

# TODO

  * [x] 会場を決める
  * [x] 内容をアレンジ
  * [x] 告知
  * [x] 開催

**Comment by kou** [comment]
「OSS Gate を立ち上げよう」で、最後に一回イベントをやってみよう、という話になったとき、「継続性を考える」と曖昧な言い方しか指定なかったのでイメージがつきやすいように具体例も書いておきます。

継続的に実現する案として次のような案があがりました。それらの中から試せるものを試せる範囲で試し、有効な案かどうかを判断するフィードバックを得ることは「継続性を考える」ことにつながります。有効な案が見つかればその案を実践することで継続性が高まるでしょうし、有効ではない案とわかったらその案を避けるようにすれば継続性が落ちることを避けられるからです。

  * 大学1,2年生をターゲットにする。1,2年生を誘うのは先輩。大学3,4年のときにOSSの開発に参加しているとメリットがあることがある（たとえば技術系の職種への就職など）がわかっても時間がなくて手遅れだから。1,2年ならまだ間に合う。先輩が誘うのは1,2年のときは先輩の影響が大きそうだから。
    * →実際にこのイベントの参加者をこの方法で募ってみる。
  * 先生に告知して参加者を募る。
    * →知り合いの先生がいるならお願いしてみる。
  * 十分に告知していればアンテナの高い社会人には届くはず。
    * →十分に告知してみる。どうすれば十分な告知になるだろう？
  * いろんなOSSのコミュニティーにOSS Gateのやり方を伝えて、各コミュニティーで運営できるようにする（各コミュニティーのイベントでLightning TalksをやっているようにOSS Gateをやる、みたいなイメージ）
    * →実際にイベントを経験して、コミュニティーへの適切な伝え方を具体化する
    * →まずはどんなコミュニティーに伝えるのがよさそうか検討し、そのコミュニティーの人にも参加を促す（見学・体験しにきてもらう）
  * OSCなどのイベントでOSS Gateという取り組みを宣伝する
    * →実際にイベントを経験して、どう宣伝するとよいかを具体化する
    * →どのイベントに伝えに行くのがよさそうかを検討し、ターゲットを決める
  * ...

**Comment by kou** [comment]
会場は @kawahara さんが http://www.codeal.asia/company/#access を手配してくれそう。

**Comment by sezemiadmin** [comment]
Doorkeeper でも募集ページ https://oss-gate.doorkeeper.jp/events/36359 作ってますが、公開前だとほかの人に見せられないようで、ちょっと困ってます。(@kou なら見えるかもしれません)

**Comment by kou** [comment]
公開してしまっても大丈夫ですよ！

**Comment by kou** [comment]
イベント名は「OSS Door」がいいかしら。「OSS Gate - doorエディション」とかだと長いし。

**Comment by kou** [comment]
GateとかDoorとか紛らわしいかしら。

**Comment by sezemiadmin** [comment]
Done

**Comment by kou** [comment]
ありがとうございます！
（伝え忘れましたが、「告知しなければ」気づく人はほとんどいないので公開しても問題ないですよ、というつもりでした。）

**Comment by kou** [comment]
（Doorkeeperのページの内容はこれから変わるはずです。）

**Comment by sezemiadmin** [comment]
わかりました! ちなみに私は当日仕事なので、出れないんです。。

**Comment by kohei-takata** [comment]
あ、まだURLとかSNSに流さないほうがよかったですかね

**Comment by kohei-takata** [comment]
投稿は削除しました。

**Comment by kou** [comment]
もう流れたものは大丈夫です！

TODO: 内容ができたら、広く告知するだけでなく、すでに参加登録した人にもちゃんとアナウンスする。

**Comment by kou** [comment]
TODO:

  * イベントページでは参加者とフォローする人をわけて登録してもらうようにする
    * 参加者数とフォローする人のバランスを確認したい（フォローする人が多い分には問題ないだろうけど少ないと回らなそう）
  * 事前に確認したい内容（登録時に聞く内容）をちゃんと考える
    * 登録後に聞くのは大変

**Comment by kohei-takata** [comment]
>イベントページでは参加者とフォローする人をわけて登録してもらうようにする
connpassだと参加枠を分けて募集することができますね、Doorkeeperは分かりませんが

**Comment by sezemiadmin** [comment]
Doorkeeperの事前アンケートで、現在、以下3つの質問を用意しています
- 開発言語
- 普段使っているOSS
- フォローする人としての参加

**Comment by sezemiadmin** [comment]
いま現状想定されているOSS Gate ワークショップの内容(Doorkeeperに載せようとしているもの)をまとめてみました。　

## 概要
OSSの開発に未参加、または参加したことはあるけどまだ自信がない人にオススメの参加方法を伝えて、実際やってみるワークショップです
  
## 参加してほしい人
- OSS開発に参加したことがない方(学生、社会人、先生、誰でもOK)
- OSS開発に参加したことはあるけど、まだ自信がない方
- OSS開発に参加したことがない方をフォローする方
  
## 事前準備
- GitHubでアカウントを取得してください
  
## 目標
- フォローがなくとも1人でOSS開発に参加できそうな気持ちになる
- Pull Requestを出せそうなら出してみよう
    
## 当日のプログラム
|時間|やること|
|---|---|
|10:30|アイスブレイク　|
|10:35|OSS開発手順を説明　|
|11:30|対象OSSを動かす　|
|12:30|昼食　|
|13:30|対象OSSを動かす(続き)　|
|15:00|プロジェクトにフィードバックする　|
|17:00|まとめ　|
|17:10|QA　|
|17:30|ワークショップのふりかえり　|
詳細は [シナリオ](https://github.com/clear-code/sezemi-2015/blob/master/oss-hack-4-beginners/scenario.md#シナリオ) をご覧ください
  
## 開催するもう一つのモチベーション
- **[OSS Hack 4 Beginners](http://www.seplus.jp/sezemi/4beginners/)に参加していない人も「どういうイベントなのか」を体験する**
体験することで、どうすればOSS Gateを継続的に成果をあげられる取り組みにできるかをより考えれるようになることを期待
  
- **OSS Gate を立ち上げようであがった[継続的に成果をあげる案](https://github.com/oss-gate/meetup/blob/master/2015-12-15/log.md)を試す**
すべての案を100%の力で試すのではなく、試せるものは試せる範囲で試す。試して成果がでなくてもよい。試してフィードバックを得て、次の行動につなげられれば十分。なので、成果がでない案かもしれないというのがわかるということも重要なフィードバック。

**Comment by sezemiadmin** [comment]
続いて、事前アンケート内容です(Doorkeeperの事前アンケートに載せようとしている内容です)
  
- 普段使っている開発言語をお選びください(使っているものはすべて上げてください)   
C / C++ / Java / C# / Perl / PHP / Ruby / Python / Node.js / Go / Swift / JavaScript / Haskell / Scala / その他
- 普段使っているOSSがあれば教えてください(ない場合は無しと入力ください) 
- 今回の参加はOSS開発参加を促す、ファシリテーターとしての参加ですか?　　
YES or NO

**Comment by S-Shimotori** [comment]
connpassって質問設定できましたっけ、管理者やったことないので定かではないんですが

**Comment by tSU-RooT** [comment]
このリポジトリのライセンスなんですが
リンク先はCC BY-SA 4.0 Internationalになっているのに、ファイルにはUniversalとなっているので直してもいいですかね？

**Comment by kohei-takata** [comment]
@S-Shimotori 
事前アンケートは作成できます。
[こちら](http://help.connpass.com/organizers/event-form)参照ください。

**Comment by S-Shimotori** [comment]
ありがとうございます。事前の質問が可能ならどちらでも大丈夫そうですね。

何かしらのスライド資料を公開するならconnpassの方が辿りやすいとも思いますが、この辺りは好みですかね……

**Comment by sezemiadmin** [comment]
というわけで、未決を整理してみたんですが、どうでしょうか?
1. 公開内容はOK?
1. 未経験 / 経験者 / フォローする人 で参加枠を分けます?
  - 参加枠を分ける機能があるのは connpass だけです
  - 事前アンケートはconnpass も Doorkeeper も設定可能
1. 事前に聞きたいことはこれでOK?
  - 未経験者向けのオススメOSSのリスト(言語別)は用意したほうがよい気がしてきました
  - ↑ 前回のイベントでは、あとで聞いて大変だった記憶があります
  - ↑ もし用意するのであれば、フォローする人に携わっているOSSを伺いたい

**Comment by yu1ro** [comment]
> 未経験者向けのオススメOSSのリスト(言語別)は用意したほうがよい気がしてきました

元参加者（未経験者）としては確かに有ったほうが良いと思います。
「何か選べと言われましても...」って感じだったので。
ただ、そのリストに縛られてしまうのも良くないかとも思いますので、
「それ以外でももちろんOK」みたいな表記があると良さげ？
と思いました。

**Comment by iwamatsu** [comment]
今回は翻訳(po)、ドキュメント整備、パッケージング(rpm,deb)などは対象に入らないのでしょうか。
アンケート内容にプログラミング言語の選択を書くだけではなく、どのようなことをやってみたいのか
聞けるようにしておくとよいと思いました（そういうことすらわからない人もいると思いますが。）
プログラミングはできないが、翻訳はできるという方もOSS活動に参加できるようにすれば敷居も
ぐっと下がると思います。
前回のミーティングでは typo の修正で PR したという例もあったようですので、上記のような選択
もありだと思っています。

2015年12月25日 10:45 toshiyahirose <notifications@github.com>:

> というわけで、未決を整理してみたんですが、どうでしょうか?
> 1. 公開内容はOK?
> 1. 未経験 / 経験者 / フォローする人 で参加枠を分けます?
>
>    - 参加枠を分ける機能があるのは connpass だけです
>    - 事前アンケートはconnpass も Doorkeeper も設定可能
>       1. 事前に聞きたいことはこれでOK?
>    - 未経験者向けのオススメOSSのリスト(言語別)は用意したほうがよい気がしてきました
>    - ↑ 前回のイベントでは、あとで聞いて大変だった記憶があります
>    - ↑ もし用意するのであれば、フォローする人に携わっているOSSを伺いたい
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oss-gate/workshop/issues/2#issuecomment-167176585>.
>



-- 
Nobuhiro Iwamatsu
   iwamatsu at {nigauri.org / debian.org}
   GPG ID: 40AD1FA6

**Comment by kou** [comment]
> connpassだと参加枠を分けて募集することができますね、Doorkeeperは分かりませんが

@kohei-takata Doorkeeperでもできるので、非公開になったあとに設定しておいたんですが、非公開なので、わからないですよね。。。ということで、管理者に追加しておきました。これで、確認できると思います。

Doorkeeperだと参加枠毎の人数を設定できないんですが、そこまでかっちりする必要はないと思うので十分じゃないかなぁと思っています。

（すでに登録している人がいるので、少なくとも今回はDoorkeeperでいきたい気持ちがあります。）

**Comment by kohei-takata** [comment]
@kou 
確認しました！ありがとうございます！
Doorkeeperで問題ないと思います！

**Comment by kou** [comment]
@sezemiadmin 文面案、アンケート案、ありがとうございます！それをベースにDoorkeeperのやつに反映しました！

あと、管理者しか確認できないのはやはり面倒なので、公開しました。 （告知しても大丈夫です。）
https://oss-gate.doorkeeper.jp/events/36359

事前アンケートは次の3つにしました。

  * 全員への質問：開発に使えるプログラミング言語をすべて教えてください。（例：C, C++, Java, Ruby, Python, PHP, Perl, JavaScript, Goなど） *
  * 「参加者」への質問：普段使っているOSSをできるだけ多く教えてください。（開発対象のOSSとして使うかもしれません。）
  * 「メンター」への質問：開発に参加しているOSSをできるだけ多く教えてください。（「参加者」が開発対象のOSSとして使うかもしれません。）

SEゼミのときと同等の内容になっているので、今回はこれでやってみて、過不足は今後のワークショップで反映するのでいいかなぁと思っています。

**Comment by sezemiadmin** [comment]
@kou :ok_woman:

**Comment by kou** [comment]
@iwamatsu 

> 今回は翻訳(po)、ドキュメント整備、パッケージング(rpm,deb)などは対象に入らないのでしょうか。

入るのですが、「それらを選ぶ」というのができない人向け（どうやって開発に参加したらよいかわからない人が対象ということを思い出してください！）なので、それを聞くのは敷居が高いなぁと思いました。

「程度がどのくらい」かというのはワークショップを体験してみるとわかることだと思うので、ぜひ一度体験してみてもらいたいです！

> プログラミングはできないが、翻訳はできるという方もOSS活動に参加できるようにすれば敷居も ぐっと下がると思います。

それはあると思います！
このワークショップは「翻訳ならできると思っている人」よりも前の人向け（なにかしたい、けど、なにをできるかわからない）なので、内容でフォローするのがいいかなぁと思いました。（SEゼミの内容でフォローできている気もします。）

**Comment by tSU-RooT** [comment]
素朴な疑問なんですが、参加者ってラップトップ持ってくるの必須ですかね。
それにUNIX互換持ってくる人とWindows持ってくる人で環境構築の手順や
開発対象になるソフトウェアも変わりそうだなーというのが

**Comment by kou** [comment]
> 素朴な疑問なんですが、参加者ってラップトップ持ってくるの必須ですかね。

あぁ、そうですね。それを書くのを忘れていました。

> それにUNIX互換持ってくる人とWindows持ってくる人で環境構築の手順や
> 開発対象になるソフトウェアも変わりそうだなーというのが

そうですね。変わります。が、それでも大丈夫な内容なのです。
なので、体験していない人は「体験してみる」というのを楽しみにしてもらうといいと思っています！

**Comment by y-goto** [comment]
今回はメンターというよりも、「様子を見学させてください」という参加方法はダメでしょうか？
　- 自分自身が、Linux Kernelの開発から数年遠ざかっていてブランクがあって、アドバイスができるかどうか正直ちょっと自信がない
　　（昔こんなことやってました。http://itpro.nikkeibp.co.jp/article/COLUMN/20090501/329459/?rt=nocnt　)
　- いきなりKernelを開発したいっていう”濃ゆい”学生はいなさそうな気がします。
  　せいぜいLinuxのDistributerが提供しているツールとかのほうだとおもうのですが、そちらのコミュニティは経験がないのでアドバイスできない。
　- そもそも"開発で使えるnote PC”を持ってない。

**Comment by y-goto** [comment]
あ、質問する場所が違ってたかな？gitterのほうが良いでしょうか？

**Comment by S-Shimotori** [comment]
@y-goto 内容上ここでもいいような気がしますが、一応質問用の所がある( https://gitter.im/oss-gate/support )ので、可能ならそちらでどうでしょう

**Comment by kou** [comment]
> 今回はメンターというよりも、「様子を見学させてください」という参加方法はダメでしょうか？

大丈夫です！ただ、登録するときは「メンター」で登録しておいてください。「参加者」ではないので、「参加者」のカウントとは混同したくないのです。

あと、たぶん、「メンター」できると思います！
「メンター」をやってみればわかること、なんですが、自分が得意なことを「参加者」に教える、という内容ではないんです。「参加者」と一緒に考えて一緒にやる、という内容なんです。なので、「メンター」が開発に参加したことがないOSSの開発に参加する「参加者」をサポートすることは別に問題ないのです。すでになんらかのOSSの開発に参加している「メンター」は考えて行動できるはずだからです。

改めて書きますが、OSS Gateは「まだOSSの開発に参加していない人は単に方法を知らないから参加していないだけで方法を伝えれば参加できる」という前提ではじめました。ざっくり言うと、「自信がなくて不安かもしれないけどやってみればいけるもんだよ！一緒にやってみよう！」ということです。 @y-goto さんはやったことがないことで自信がなくて不安かもしれませんが、やってみればいけるもんです。 :-)

> - そもそも"開発で使えるnote PC”を持ってない。

あ、「メンター」の人はあれば便利ですが必須ではないです。たとえば、進行役の人（今回の場合は私）は、「参加者」をサポートする時間も自分のノートパソコンでスライドを映し続けるので、ノートパソコンを持っていますが開発には使えません。それでも大丈夫だったりします。

**Comment by kou** [comment]
@S-Shimotori 告知していなかったのにサポート用のチャットルームを見つけてくれてありがとうございます！

細かくやり取りが必要なやつ、あるいは、チャットの方が気軽だと思う人はチャットを使うといいかなぁと思って用意したものでした。すぐにまとまるやつは後から参照しやすそうなのでissueだったりリポジトリーに入れるんだったりした方がいいかなぁと思っていました。（チャットでなにか決めたら、まとめだけをissueにコメントするとか。）

これも、細かいやり取りをした方がよさそうならチャットに移動するのはどうでしょうか！？

**Comment by kou** [comment]
TODO:
  * 終了後の参加者向けアンケートを用意する
    * OSS GateバージョンでもSEゼミのときと同じくらい「参加者」が[目標](https://oss-gate.doorkeeper.jp/events/36359#goal)を達成するかを確認した方がよさそう。もし、達成しないならSEゼミのときは無意識にやっていたなにかを見つけて明文化する必要がありそう。
    * 聞く内容は[SEゼミのときのやつ](https://creativesurvey.com/public/results/d3f23880988141c2fe6338677436b3011b982137/questions/353746)からSEゼミ関連の内容を削るだけでよいかしら。

**Comment by y-goto** [comment]
@kou さん　@S-Shimotori さん、案内ありがとうございます。　ではメンターとして参加したいと思います。よろしくお願いします。

**Comment by sezemiadmin** [comment]
@kou 
> 終了後の参加者向けアンケートを用意する  
  
ザッと見ましたが、
- step6 企業のエンジニアが勉強会にメンターとして～ は削除
- step9 選択肢OSS Hack Weekend に参加したいを削除
  
この2点で良いのではと思いました。
  
あとは **OSS Gateメンバー向けのアンケート** があると、ふりかえりしやすくなると思いますが、いかがでしょうか?
- 今日のワークショップで見つかった課題はありますか?
- OSS Gateを立ち上げよう で挙がった課題とその解決のアイデアで有効そうなものはありましたか?  
etc.

**Comment by kou** [comment]
@sezemiadmin 確認ありがとうございます！その案でいきましょう！

**Comment by sezemiadmin** [comment]
[参加者向けアンケート](https://docs.google.com/forms/d/1f9-g3Rk8w_T_YPOUNW83wdFa0DEVxfC8-oZkqs3EbYI/viewform)を作りました。
また、[OSS Gateメンバー向けのアンケート](https://docs.google.com/forms/d/1bzdrnXWGqv27qawXcAI37bRl34MBkt-xM9hUKeIkwHM/viewform)も作成してみました。

ただ、いずれのアンケートも編集権の設定をどうするか迷い中です。リンクを知っている全員で良い気がしているのですが。。

**Comment by kou** [comment]
ありがとうございます！
今回は、改善案がある場合は、ここで受け付けて編集できる人が編集するでよいと思います！

「アンケートをうまくとってうまく活用すること」は今回の目的で言うと一番大事なことではないと思うので、どうするのがよいかは（今回ものすごく頑張ることではなく）今後の課題でよい気がします！

**Comment by kou** [comment]
@sezemiadmin アンケート結果を確認する方法を教えてもらえないでしょうか！？

**Comment by sezemiadmin** [comment]
@kou 回答者向けページの右上に編集ボタンがあると思うのですが、それを押すと回答が表示されるかと (編集権のあるアカウントだけボタン表示されます)。また誰か回答すると、回答ファイル(Spreadsheet)がOSS Gateのドライブ内に生成されます

**Comment by kou** [comment]
@sezemiadmin ありがとうございます！たしかに表示されました！

**Comment by kou** [comment]
Done!
#15 でのまとめの協力をおねがいします！
