### ISSUE TITLE
OSS Gate Workshop 2017-01-16: colorbox: amazon-ecs: Work log

### ISSUE THREAD

**Issue by colorbox** [oss-gate/workshop#200]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by zonuexe** [comment]
こんにちはこんにちは ヾ(〃＞＜)ﾉﾞ

**Comment by colorbox** [comment]
よろしくお願いします。

**Comment by colorbox** [comment]
#### やりたいこと
 amazon-ecs のgemを手元に持ってくる。

#### やったこと

* 自分のプロダクトのGemfileからgemの識別名を取得
* それを[rubygems.org](https://rubygems.org/gems/amazon-ecs)で検索、出てきたページからGithubの[ページ](https://github.com/jugend/amazon-ecs)を取得してclone
* rubymineからbundle installをして一旦取得は完了？

**Comment by colorbox** [comment]
テストを動かしたい

**Comment by colorbox** [comment]
ので、ソースを見てみる
READMEにはそれらしき記述がない、CONTRIBUTE.mdファイルもないので、そこから情報は取り出せない。
ディレクトリ形式から、railsのデフォルトのテスト機構を使っているようなので、それで実行してみる。

**Comment by colorbox** [comment]
コマンドを思い出せないのでググru

**Comment by colorbox** [comment]
Gemfileを覗く
そこから、開発用にrakeが導入されていることがわかった。
プロジェクト内のRakefileを覗くと、rakeコマンドでテストが実行されることがわかった。

**Comment by colorbox** [comment]
rakeでテストを実行しようとすると、下記エラーで失敗した。
```
/Users/merge/.rbenv/versions/2.3.3/bin/ruby -w -I"lib:test" -I"/Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib" "/Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/amazon/ecs_test.rb" 
/Users/merge/work/amazon-ecs/test/amazon/ecs_test.rb:13:in `<class:EcsTest>': AWS_ACCESS_KEY_ID env variable is not set (RuntimeError)
        from /Users/merge/work/amazon-ecs/test/amazon/ecs_test.rb:8:in `<top (required)>'
        from /Users/merge/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/merge/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
        from /Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib" "/Users/merge/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/amazon/ecs_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by colorbox** [comment]
テストとエラー内容から、AWSにアクセスするための認証トークンが必要なことがわかった。

**Comment by colorbox** [comment]
AWSの認証情報をAWSのサイトから取り出せないか見てみる。

**Comment by colorbox** [comment]
AWSのコンソールから、AWSの認証情報を再生成した。

**Comment by colorbox** [comment]
その認証情報を使用してテスト実行を行う。
`export ${変数名}='${トークン}'`で環境変数にトークンを格納する。

**Comment by colorbox** [comment]
その状態で、rakeを実行すると、テストが実行された。
ただし、エラーが大量に出ている。

**Comment by colorbox** [comment]
エラー文言内に下記ページへのガイドがあったためそこを見る。
https://affiliate-program.amazon.com/gp/associates/join/landing/main.html

**Comment by colorbox** [comment]
そもそもAWSは関係なかったので、無駄に生成したトークンを無効化する。

**Comment by colorbox** [comment]
amazon Product Advertising API関連なので、そこの認証情報を取ってこれないか見てみる

**Comment by colorbox** [comment]
AWSの認証情報が必要なようなので、もう一度認証情報を見てみる。
IAMの認証情報を再度生成し、それを環境変数にセットする。

**Comment by colorbox** [comment]
認証情報をセットしたが、同じエラーが出てくる。
テストを見てみると、associateタグをセットしている箇所がある。
このタグを自分のものに書き換えてテストを再度実行したが、またエラーとなった。

**Comment by colorbox** [comment]
http://webservices.amazon.com/scratchpad/index.html?rw_useCurrentProtocol=1&rw_useCurrentProtocol=1
API実行をテストできるツールがamazonから公開されているため、これを使用して認証情報が正しいかの確認を行う。

**Comment by colorbox** [comment]
必要情報を入力してツールを動かすと正常に動作した。
テストとの相違点は、国の指定。
国を指定する箇所をREADMEなどから確認する。

**Comment by knokmki612** [comment]
> READMEにはそれらしき記述がない、CONTRIBUTE.mdファイルもないので、そこから情報は取り出せない。

情報がなかった、というのは、フィードバックできそうですね！

**Comment by koic** [comment]
README だけ見ても動かせないポイントがあれば、不足している点を加筆すると後で動かそうとした人が同じようにつまづかなくなるというフィードバックにできそうです。

また、コントリビューションのためのテストの実行方法が分かりづらかったようであれば、コントリビューションしやすくするためのテストの簡単な手順があると、あとでコントリビューションしようとした人の助けになりそうですね。

**Comment by colorbox** [comment]
VCRを導入するというアドバイスも貰ったので、テストが実行できたらVCRの導入も行う。

**Comment by zonuexe** [comment]
めも： そもそもこの開発者は、現時点で他人がテストを動作させることを想定してなさそう

**Comment by colorbox** [comment]
テストで国指定についてたどり着くには、テスト対象のコードを読まないとわからないので、それについてREADMEに追記したら良いかも？

**Comment by knokmki612** [comment]
おつかれさまでした！
