### ISSUE TITLE
OSS Gate Workshop 2017-01-16: soudegesu: spring-boot Work log

### ISSUE THREAD

**Issue by soudegesu** [oss-gate/workshop#203]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by koic** [comment]
よろしくお願いします！

**Comment by soudegesu** [comment]
公式のリポジトリ(https://github.com/spring-projects/spring-boot)でspring-boot-gradle-pluginのプロジェクトを探してみましたが、見つかりませんでした。

**Comment by soudegesu** [comment]
公式サイトを見たら、spring-boot-starter-parent が本体っぽい？

**Comment by soudegesu** [comment]
サイト見てもわからなかったので、ローカルにcloneしてみた

**Comment by soudegesu** [comment]
README.mdのBuilding reference documentationの項を見たところ、spring-boot-tools のディレクトリ下にspring-boot-maven-plugin が存在する記載を見つけたので、spring-boot-gradle-pluginもあるのでは？と思った

**Comment by soudegesu** [comment]
見つけた。
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-tools/spring-boot-gradle-plugin

**Comment by soudegesu** [comment]
で、どうやって起動するんだ？

**Comment by soudegesu** [comment]
READMEを更に読んでいくと、
./mvnw clean install -pl spring-boot-tools/spring-boot-maven-plugin -Pdefault,full
でmvnのプラグインは動くようだ。
gradleはこれでいけるだろうか？

**Comment by soudegesu** [comment]
./mvnw clean install -pl spring-boot-tools/spring-boot-maven-plugin -Pdefault,full
↓
./mvnw clean install -pl spring-boot-tools/spring-boot-gradle-plugin -Pdefault,full
に変えて実行してみる

**Comment by soudegesu** [comment]
モジュールのダウンロードに結構時間かかる。とりあえず、READMEを読み進めるとよいかも。

**Comment by soudegesu** [comment]
spring-boot がやはり親であることがわかった。

**Comment by soudegesu** [comment]
spring-boot プロジェクト内にSpringApplicationクラスが存在することがわかったが、どう起動するのが、これを立ち上げることになるのであろうか？

**Comment by soudegesu** [comment]
普通にアプリケーションを立ち上げるときのように書くだけでよいのか？

**Comment by soudegesu** [comment]
public static void main(String[] args) throws Exception {
 *   SpringApplication app = new SpringApplication(MyApplication.class);
 *   // ... customize app settings here
 *   app.run(args)
 * }
 *

**Comment by soudegesu** [comment]
モジュールにしてローカルの適当なJavaプロジェクトで読み込ませたらかっこいいけど、とりあえずは動かしたいので、同じプロジェクトの中にmainクラスを作ってみよう

**Comment by soudegesu** [comment]
デフォルトパッケージでとりあえず動くかやってみる
```java
public Class Hoge {
        public static void start(android.content.Context context) {
            System.out.println("aaaa");
        }
}
```

**Comment by soudegesu** [comment]
runできない。IDEがパッケージを認識していないようだ。

**Comment by soudegesu** [comment]
"IntelliJ gradle パス" でIDEから起動するための方法を探す。

**Comment by soudegesu** [comment]
READMEに戻ってみる

**Comment by soudegesu** [comment]
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples
にJavaのサンプルがあることがわかった。

**Comment by suginoy** [comment]
- sample を見つけることができたので、もしかしたらそれをイイカンジに修正すれば貢献できるかもしれないですね

**Comment by soudegesu** [comment]
アプリケーションの起動ができたらsampleが今のJavaの書き方に即しているか見てみます！

**Comment by suginoy** [comment]
- バグレポートの仕方などが `CONTRIBUTING.adoc` にありますね、という話をしました。

**Comment by koic** [comment]
サンプルを動かそうとした際の、非推奨警告のログが気になりました。置き換えになる新しい API があればそちらを使うようにすると非推奨警告のログを消すフィードバックのチャンスになりそうです :shinto_shrine:

**Comment by satoryu** [comment]
1/16開催の東京ミートアップで午前のパートに相当する部分は終わっていたということで、そのふりかえり。

* spring-coreのビルドをしてみるが、時間がかかるので、中断。
* リポジトリに収録されているサンプルを実行時の非推奨警告が出ていたので、そこからフィードバックのネタを考える。

現在、mvnでspring-boot本体のビルド中。

**Comment by soudegesu** [comment]
ドキュメントどおり以下を実行した
```
 ./mvnw clean install
```

**Comment by soudegesu** [comment]
以下のようなスタックトレースが出た。

````
[ERROR] Failed to execute goal on project spring-boot-configuration-metadata: Could not resolve dependencies for project org.springframework.boot:spring-boot-configuration-metadata:jar:2.0.0.BUILD-SNAPSHOT: Failed to collect dependencies at com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1: Failed to read artifact descriptor for com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1: Could not transfer artifact com.vaadin.external.google:android-json:pom:0.0.20131108.vaadin1 from/to spring-ext (http://repo.spring.io/ext-release-local/): /Users/takaaki-suzuki/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.pom.part.lock (No such file or directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-boot-configuration-metadata
```

**Comment by soudegesu** [comment]
実行環境は 
Mac OS X Yosemite
2.6 GHz Intel Core i5
8 GB 1600 MHz DDR3

**Comment by soudegesu** [comment]
maven repositoryに存在しないのかしらべてみる

**Comment by soudegesu** [comment]
フルデバッグロギングをしてみる

```
./mvnw clean install -X
```

**Comment by soudegesu** [comment]
.m2ディレクトリ配下を削除して、再度実行する

**Comment by soudegesu** [comment]
日本語にしてみる。
=====================================

Spring BootにContributeしようと思い、https://github.com/spring-projects/spring-boot のリポジトリから https://github.com/spring-projects/spring-boot のドキュメントを参考に以下のコマンドを実行しました

```
./mvnw clean install
```

以下のように、Spring Boot Maven Pluginのビルドの途中でFAILUREになりました。

```
[INFO] Spring Boot Dependencies ........................... SUCCESS [  6.237 s]
[INFO] Spring Boot Parent ................................. SUCCESS [04:36 min]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.984 s]
[INFO] Spring Boot Configuration Metadata ................. SUCCESS [01:10 min]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [  7.661 s]
[INFO] Spring Boot Loader ................................. SUCCESS [02:39 min]
[INFO] Spring Boot Loader Tools ........................... SUCCESS [ 47.458 s]
[INFO] Spring Boot Maven Plugin ........................... FAILURE [03:43 min]
[INFO] Spring Boot Gradle Plugin .......................... SKIPPED
```

**Comment by soudegesu** [comment]
英語にしてみる

I tried to contribute to spring-boot, and I ran the command with reference to the document of https: // github.com/spring-projects/spring-boot

```
./mvnw clean install
```

Then, it became FAILURE on the way of building Spring Boot Maven Plugin as follows.

```
[INFO] Spring Boot Dependencies ........................... SUCCESS [  6.237 s]
[INFO] Spring Boot Parent ................................. SUCCESS [04:36 min]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.984 s]
[INFO] Spring Boot Configuration Metadata ................. SUCCESS [01:10 min]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [  7.661 s]
[INFO] Spring Boot Loader ................................. SUCCESS [02:39 min]
[INFO] Spring Boot Loader Tools ........................... SUCCESS [ 47.458 s]
[INFO] Spring Boot Maven Plugin ........................... FAILURE [03:43 min]
[INFO] Spring Boot Gradle Plugin .......................... SKIPPED
```

**Comment by soudegesu** [comment]
実際に出してみました。

http://stackoverflow.com/questions/41907096/mvnw-clean-install-can-not-be-built

**Comment by knokmki612** [comment]
おつかれさまでした！
クローズされていても、引き続きメモすることはできますので、よかったらどうぞ！
