### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-01-16: yamagata: TOMCAT: Work log

### ISSUE THREAD

**Issue by Ryamagata** [oss-gate/workshop#204]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by ycatch** [comment]
よろしくお願いします :-)

**Comment by Ryamagata** [comment]
1,tomcatのインストール方法を検索(公式サイト)

**Comment by Ryamagata** [comment]
2,サイト(https://tomcat.apache.org/tomcat-7.0-doc/appdev/installation.html)で手順確認

**Comment by Ryamagata** [comment]
3,Tomcat 8.5.9をダウンロード(http://tomcat.apache.org/download-80.cgi)

**Comment by Ryamagata** [comment]
4,ダウンロードの手順書を再度確認。見つけにくい。

**Comment by Ryamagata** [comment]
5,サイト(http://tomcat.apache.org/tomcat-8.5-doc/setup.html)で確認。
　バージョンごとにインストール手順がある。

**Comment by Ryamagata** [comment]
環境変数でCATALINA_HOMEにtomcatのパスを指定する。

**Comment by Ryamagata** [comment]
http://tomcat.apache.org/tomcat-8.5-doc/setup.htmlのUnix daemonの項目で
Tomcat can then be run as a daemon using the following commands.の内容を
試そうと同じコマンド
./bin/jsvc 
を実行したがライブラリが
-bash: ./bin/jsvc: No such file or directory
と出た。

**Comment by Ryamagata** [comment]
http://tomcat.apache.org/tomcat-8.5-doc/setup.htmlのIntroductionのRUNNING.txtのリンクがありそこに、インストール手順と起動手順が書いてあった。こちらの指示に従い再度、インストールおよび起動を試みる。

**Comment by Ryamagata** [comment]
手順に従い、インストールおよび起動し、http://localhost:8080/ と表示できた。

**Comment by Ryamagata** [comment]
インストール手順でハマったところ。
http://tomcat.apache.org/tomcat-8.5-doc/setup.html の
サイトの項目名がIntroduction、Windows、Unix daemonで
MacOSはUnix daemonだと判断し利用した。
また、Html形式ではなくテキストになっていたためインストール手順を
探すのに手間取ってしまった。

**Comment by Ryamagata** [comment]
問題点
・インストールの手順がWindowsとUnix daemonで違い分かりにくい。
・HTML形式ではくRUNNING.txtとテキストベースになっている。
改善案
・OSごとに丁寧にインストール手順を作成する。
　Windows,Mac,Linux(CentOS)
・HTML形式でインストール手順を作成する。

**Comment by zonuexe** [comment]
> 改善案
> ・OSごとに丁寧にインストール手順を作成する。
> 　Windows,Mac,Linux(CentOS)

おそらく、サポートするOSが幅広いので、そのように書けない事情もあるのかもしれない。

* コードリポジトリはここにある(svn): http://tomcat.apache.org/svn.html
* Apache FoundationなのでSubversionを使ってる
  * フィードバックの送り先はここかも
    * http://tomcat.apache.org/lists.html
    * http://tomcat.apache.org/bugreport.html

**Comment by zonuexe** [comment]
本家はsvnだが、些細な修正はGitHubでPRを送ってもパッチを取り込んでくれることもあるらしい
  *  https://github.com/apache/tomcat/pulls?q=is%3Apr+is%3Aclosed

**Comment by ycatch** [comment]
先日は、お疲れさまでした。
指摘したいドキュメントのところに、何かフィードバック方法があったりしないかな？
と思いました。
お時間があれば、参考にしてください。

**Comment by Ryamagata** [comment]
インストール手順書についての要望。
・テキスト形式のファイルを見てインストールする必要があり、
　HTML形式の画像やコマンドを含めたインストール手順が欲しい。
・OS依存の手順のインストール手順が欲しい。

**Comment by Ryamagata** [comment]
・テキストベースのインストールではダメなのか？
　→そこまでの工数をかけてやるのかどうかが問題。
　　CIの場合だと、テキストでも問題ない。
・最初のインストールのサイトTomcat Setup(http://tomcat.apache.org/tomcat-9.0-doc/setup.html)
   でわかりやすくする方法があるのではないか？
　→英語の表現の方法や注目しやすい様にする方法がないか？

**Comment by Ryamagata** [comment]
RUNNING.txtを見る必要があるため以下の案が考えられる
・The main documentation for this is a file called RUNNING.txtを太文字にする。
・Table of ContentsにIntroductionにThe main documentationを追加する。
　または、The main documentation for this is a file called RUNNING.txtをここに持ってくる。

**Comment by Ryamagata** [comment]
TOMCATの公式サイト(http://tomcat.apache.org/tomcat-9.0-doc/setup.html)を
見てインストールいたしましたが、
インストールする際に手間取ってしまったところがあり、
下記の様にしていただけるとより良くなると考えメール致しました。

※RUNNING.txtを見ないとインストール方法の詳細がわからないため
・Introductionのthe main documentation for this is a file called RUNNING.txt.を太文字にする。
・Table of ContentsにIntroductionをIntroduction(the main documentation)または、
　Table of Contentsの先頭にthe main documentation for this is a file called RUNNING.txt.を
　記述する。

以上、お手数ですがご対応のほどよろしくお願いいたします。

**Comment by Ryamagata** [comment]
インストールする際に、メインドキュメントの場所がわかりにくく
MacでNo deamonで利用したかったがWindowsとUnix daemonしかなく
Unix daemonで見てどうにかできないかと悩んでしまった。

**Comment by Ryamagata** [comment]
TOMCATの公式サイト(http://tomcat.apache.org/tomcat-9.0-doc/setup.html)を
見てインストールいたしましたが、
インストールする際に、メインドキュメントの場所がわかりにくく
最初、MacでNo deamonで利用したかったがWindowsとUnix daemonしかなく
Unix daemonで見てどうにかできないかと悩んでしまった。
下記の様にしていただけるとより良くなると考えメール致しました。

※RUNNING.txtを見ないとインストール方法の詳細がわからないため
・Introductionのthe main documentation for this is a file called RUNNING.txt.を太文字にする。
・Table of ContentsにIntroductionをIntroduction(the main documentation)または、
　Table of Contentsの先頭にthe main documentation for this is a file called RUNNING.txt.を
　記述する。

以上、お手数ですがご対応のほどよろしくお願いいたします。

**Comment by Ryamagata** [comment]
Official website(http://tomcat.apache.org/tomcat-9.0-doc/setup.html) I installed it and installed it.

**Comment by Ryamagata** [comment]
TomcatをMacにインストールしたかったため、公式サイトを見てインストールいたしました。

**Comment by mtsmfm** [comment]
ふりかえり相手の松島です!

**Comment by mtsmfm** [comment]
https://github.com/apache/tomcat/blob/trunk/webapps/docs/setup.xml

これかな?

**Comment by mtsmfm** [comment]
「こうして欲しい」という文言があるならば、PR 出すとさらによいと思いました :+1:

**Comment by tricknotes** [comment]
おつかれさまでした！よかったら次回はメンターで参加してみてください！
