### ISSUE TITLE
OSS Gateワークショップ2016-03-26: hanzgit: nodejs: 作業ログ

### ISSUE THREAD

**Issue by hanzgit** [oss-gate/workshop#21]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by hanzgit** [comment]
前回1月の続きを行うことにした。
まず、前回の記録を確認する。

**Comment by hanzgit** [comment]
ソースをダウンロードするところから始める。
以下を参照。
https://github.com/nodejs/node/blob/master/BUILDING.md

**Comment by hanzgit** [comment]
[HP](https://github.com/nodejs/node/blob/master/BUILDING.md)の解説がわかりにくいため、readme.mdを確認する。

**Comment by hanzgit** [comment]
makefileを作成できないため方法を確認する。

**Comment by hanzgit** [comment]
ダウンロード方法を間違えていたことに気づく。
githubのnode.jsの[node](https://github.com/nodejs/node)からgit cloneのパス取得。
https://github.com/nodejs/node.git

**Comment by hanzgit** [comment]
githubからのcheck out方法として、
git cloneとfolkの違いを教えていただく。
・folk：pull requestを前提にcheck outする。
・git clone：pull requestは特に意識せずcheck outする。git hubのレポジトリからは分離。
後日自分で調査してみる。

**Comment by hanzgit** [comment]
check outに時間がかかるので待機。

**Comment by hanzgit** [comment]
ソースコードの取得方法のフィードバックを後で考える。

**Comment by hanzgit** [comment]
チェックアウトが完了した。

**Comment by hanzgit** [comment]
[HP](https://github.com/nodejs/node/blob/master/BUILDING.md)を参考に再度ビルドを試行する。

**Comment by hanzgit** [comment]
ビルド中...ビルド後にすることを検討中

**Comment by hanzgit** [comment]
ビルドが無事に完了した。
`$ node -e "console.log('Hello from Node.js ' + process.version)"`

**Comment by hanzgit** [comment]
チュートリアルにてnode.jsに関する理解を深める。
公式サイトにチュートリアルが見当たらなかったため、Googleにて検索する。
解説が詳しく記載されており、ソースコードが公開されていたHPにて試行してみる。

**Comment by hanzgit** [comment]
Github上のページは以下。
https://github.com/manuelkiessling/nodebeginner.org

**Comment by hanzgit** [comment]
1つ目のチュートリアルが完了。
※チュートリアルの内容：ブラウザにてhttp://localhost:8888/ にアクセスされると、”Hello World”と表示しているWebページが表示する

`var http = require("http");

http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  response.end();
}).listen(8888);`

**Comment by hanzgit** [comment]
node.jsを使用した何かを作成してみる方針からnode.js自体の理解を深める方針に変更。
[HP](http://blog.otakumode.com/2014/08/14/nodejs-code-reading-startup-script/)を参考に進める。

**Comment by hanzgit** [comment]
OSSのソースコードを読み動作を追う
というのが個人的な当初の目標を一つ達成。

**Comment by kou** [comment]
おつかれさまでした！参加した感想をブログとかにまとめてくれるとOSS Gateワークショップの普及につながってうれしいです！
（次回からはフィードバックしたメンターの人にその場でcloseしてもらうようにしよう。おつかれ！とか言いながら。）
