### ISSUE TITLE
OSS Gate Workshop: 札幌: 2017-01-21: naka-aki-spl: php/php-src: Work log

### ISSUE THREAD

**Issue by naka-aki-spl** [oss-gate/workshop#219]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by naka-aki-spl** [comment]
* 作業
ホームページのREADMEを読む
* 思っていること
ビルドのしかたが判るといいなあ

**Comment by naka-aki-spl** [comment]
* 作業
トップのREADMEを読む

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
--enable-maintainer-ztsってなんだろう？

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
知らない言葉。zts とTSRM

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
上のは「For development use …」の中。開発者が使うもの

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
「TSRM は PHP における全能の神」なのだそうです。
ZTSのほうも、
なにかマルチスレッドに関係ある話らしいです。

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
  PHP-7.1   Is used to release the PHP 7.1.x series. This is a prerelease
            version.

  PHP-7.0   Is used to release the PHP 7.0.x series. This is a current
            stable version and is open for bugfixes only.

  PHP-5.6   Is used to release the PHP 5.6.x series. This is a current
            stable version and is open for bugfixes only.

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
Do not commit multiple files：コミット混ぜるなっていう話ですね

**Comment by naka-aki-spl** [comment]
* 作業
README.GIT-RULESを読んでる

* 思った事
https://bugs.php.net/　→Most recent open bugs (PHP 5.6)→トップページに書かれたイシュー番号55371で検索→　Bug #55371	get_magic_quotes_gpc() throws deprecation warningに到達した

**Comment by naka-aki-spl** [comment]
* 作業
動かしてみるに至る方針

* 思った事

**Comment by naka-aki-spl** [comment]
* 作業
README.WIN32-BUILD-SYSTEM見てみる

**Comment by naka-aki-spl** [comment]
* 作業
README.WIN32-BUILD-SYSTEM見てみる

* 思った事
https://wiki.php.net/internals/windows/stepbystepbuild　を見ろと書いてある
↓
 MinGW and other compilers are NOT supported
VC以外ダメだそうですorz

**Comment by naka-aki-spl** [comment]
* 作業
仮想環境にしてみる

Vagrantfile(覚えのない)が有ったので起動してみた
cent7

**Comment by naka-aki-spl** [comment]
* 作業
上記環境にgitをインストール

sudo yum install git

**Comment by naka-aki-spl** [comment]
*作業
README.UNIX-BUILD-SYSTEM　を見始めた

**Comment by naka-aki-spl** [comment]
* 作業
「動作」環境としてdockerいれてみる

sudo yum install docker

**Comment by naka-aki-spl** [comment]
https://hub.docker.com/?
「php」で検索
https://hub.docker.com/_/php//

docker run -it --rm 7.1.0-alpine ash
をやってみた→動かない

https://docs.docker.com/engine/installation/linux/centos/　
によるとdockerがunofficialらしい

**Comment by naka-aki-spl** [comment]
https://docs.docker.com/engine/installation/linux/centos/
「Most users set up Docker’s repositories」
↓
https://docs.docker.com/engine/installation/linux/centos/#/install-using-the-repository
sudo yum -y remove docker
$ sudo yum install -y yum-utils
$ sudo yum-config-manager \
    --add-repo \
    https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo


3 Optional:
を飛ばす

**Comment by naka-aki-spl** [comment]
sudo yum -y install docker-engine
エラーになった。
Error: docker-engine-selinux conflicts with 2:container-selinux-1.10.3-59.el7.centos.x86_64

$ sudo yum -y install docker-engine --skip-broken
進んだ

**Comment by naka-aki-spl** [comment]
（Packages skipped because of dependency problems:
とは出たけど成功した）

**Comment by naka-aki-spl** [comment]
yum list docker-engine.x86_64  --showduplicates |sort -r
sudo yum -y install docker-engine-1.13.0-1.el7.centos

**Comment by naka-aki-spl** [comment]
「CentOS 7.0でDockerを動かしてみた - 夜はいよいよ冴えたのだ。」 http://furandon-pig.hatenablog.com/entry/2014/07/29/082607

selinuxを無効化？
「/etc/selinux/configを以下のように修正し」

**Comment by naka-aki-spl** [comment]
SELINUX=disabled

**Comment by naka-aki-spl** [comment]
リブート
sudo getenforce
Disabled

**Comment by naka-aki-spl** [comment]
ホストに戻ろう。
docker-machineが入ってるようだ

docker-machine create --driver virtualbox dev

**Comment by naka-aki-spl** [comment]
cent7にphpenvを入れよう

**Comment by naka-aki-spl** [comment]
http://raichel.hatenablog.com/entry/2015/10/18/CentOS7%E3%81%A7PHP%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B
curl -L https://raw.github.com/CHH/phpenv/master/bin/phpenv-install.sh | bash

export PATH="/home/vagrant/.phpenv/bin:$PATH"
eval "$(phpenv init -)"

Add above line at the end of your ~/.bashrc and restart your shell to use phpenv.

「パスを通す」段落は上記で既にやってるのでスキップ。

**Comment by naka-aki-spl** [comment]
sudo yum install libxml2-devel bison bison-devel openssl-devel curl-devel libjpeg-devel libpng-devel libmcrypt-devel readline-devel libtidy-devel libxslt-devel

sudo yum install wget
sudo wget -P /usr/share/ http://sourceforge.net/projects/re2c/files/re2c/0.14.3/re2c-0.14.3.tar.gz
2017-01-21 03:06:27 ERROR 404: Not Found.

「re2cを入れる」は飛ばす

**Comment by naka-aki-spl** [comment]
phpenv install --list
phpenv install 7.1.0

**Comment by naka-aki-spl** [comment]
configure: error: no acceptable C compiler found in $PATH

↓

sudo yum install gcc bison libxml2 libxml2-devel openssl-devel   \
    libcurl-devel libjpeg-turbo-devel libpng-devel libmcrypt-devel \
    readline-devel libtidy-devel libxslt-devel

**Comment by naka-aki-spl** [comment]
phpenv install 7.1.0
(ビルド中)

**Comment by naka-aki-spl** [comment]
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
[Warn]: Aborting build.

えらー、いや警告か。じゃあコンパイルは通ってるか。

$ phpenv versions
  7.1.0

**Comment by naka-aki-spl** [comment]
$ phpenv 7.1.0
rbenv: no such command `7.1.0'
 phpenv global 7.1.0
phpenv rehash
php -v
PHP 7.1.0 (cli) (built: Jan 21 2017 03:29:45) ( NTS )


やっと動きそうになった

 php -a
php > print( 1+1 );
2

動いた！

**Comment by naka-aki-spl** [comment]
$ phpenv 7.1.0
rbenv: no such command `7.1.0'

こちら　http://qiita.com/toshiro3/items/2ca2765c1a5fee78d504　の
「phpenv 5.5.16」という書き方は
できないようだ。

**Comment by knokmki612** [comment]
おつかれさまでした！
クローズされていても、引き続きメモすることはできますので、よかったらどうぞ！
