### ISSUE TITLE
OSS Gate Workshop: 札幌: 2017-01-21: toryonogi: Font-Awesome: Work log

### ISSUE THREAD

**Issue by toryonogi** [oss-gate/workshop#223]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by toryonogi** [comment]
ドキュメントの場所を探している

**Comment by toryonogi** [comment]
公式サイト：http://fontawesome.io/get-started/ からソースをダウンロードしました。
その後に何をすれば良いか分からない。

**Comment by toryonogi** [comment]
公式サイト：http://fontawesome.io/examples/ を基にサンプルソースを入力して挙動を確認した。

**Comment by toryonogi** [comment]
エンドユーザとしての使い方は理解できたが、開発者向けのドキュメントの場所が分かりづらい。

**Comment by toryonogi** [comment]
開発者向けのドキュメントの場所が分からないので検索エンジンより検索した。

**Comment by toryonogi** [comment]
北村メンターより、CONTRIBUTING.mdに本オープンソースに参加するための情報が書かれているとアドバイスを頂きました。

**Comment by toryonogi** [comment]
https://github.com/FortAwesome/Font-Awesome/wiki を参照してscss、lessのコンパイル環境を整える準備をした。

**Comment by toryonogi** [comment]
コンパイル環境を構成する際に下記のエラーが発生し、正常に環境を構成できなかった。

```　
\Users\epson\Desktop\Font-Awesome>bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using colorator 0.1
Using highline 1.6.21
Using commonjs 0.2.7
Using ffi 1.9.10 (x86-mingw32)
Using liquid 2.5.5
Using rb-fsevent 0.9.6
Using maruku 0.7.0
Using posix-spawn 0.3.11
Using yajl-ruby 1.1.0 (x86-mingw32)
Using redcarpet 2.3.0
Using safe_yaml 1.0.4
Installing libv8 3.16.14.15 with native extensions
Using ref 2.0.0
Using sass 3.4.19
Using bundler 1.14.0
Using parslet 1.5.0
Using classifier 1.3.4
Using commander 4.1.6
Using less 2.5.1
Using rb-inotify 0.9.5
Using rb-kqueue 0.2.4
Using pygments.rb 0.5.4
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15/ext/libv8
C:/Ruby23/bin/ruby.exe -r ./siteconf20170121-4964-7m2gju.rb extconf.rb
creating Makefile
指定されたパスが見つかりません。
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:86:in
`setup_python!': libv8 requires python 2 to be installed in order to build, but
it is currently 3.5.2 (RuntimeError)
from
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:53:in
`build_libv8!'
from
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15/ext/libv8/location.rb:24:in
`install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15 for inspection.
Results logged to
C:/Ruby23/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/libv8-3.16.14.15/gem_
make.out

An error occurred while installing libv8 (3.16.14.15), and Bundler cannot
continue.
Make sure that `gem install libv8 -v '3.16.14.15'` succeeds before bundling.

C:\Users\epson\Desktop\Font-Awesome>
```

**Comment by toryonogi** [comment]
下記のエラーより、pythonのバージョン２が必要であるメッセージを確認した。

```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:86:in
`setup_python!': libv8 requires python 2 to be installed in order to build, but
it is currently 3.5.2 (RuntimeError)
```

**Comment by knokmki612** [comment]
おつかれさまでした！
クローズされていても、引き続きメモすることはできますので、よかったらどうぞ！
