### ISSUE TITLE
OSS Gateワークショップ2016-03-26: knokmki612: twm: 作業ログ

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#23]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by knokmki612** [comment]
やること:

* twmの改変をした方に、本家にコードを取り込んで貰っても良いか確認をとる。ライセンス周りについても相談する
* コードを取り込んでもらう先がどこか調べる
* 改変したtwmがクラッシュする原因の特定と修正をする

**Comment by knokmki612** [comment]
> * twmの改変をした方に、本家にコードを取り込んで貰っても良いか確認をとる。ライセンス周りについても相談する
メールを送った！

**Comment by knokmki612** [comment]
> * コードを取り込んでもらう先がどこか調べる

調べたところ、X.org Foundation下のプロジェクトなのではないか

**Comment by knokmki612** [comment]
> * 改変したtwmがクラッシュする原因の特定と修正をする

フォント周りが怪しい？

**Comment by knokmki612** [comment]
>> * コードを取り込んでもらう先がどこか調べる
> 調べたところ、X.org Foundation下のプロジェクトなのではないか

メンターの方からアップストリームがあるという話を聞き、<https://cgit.freedesktop.org/cgit/?url=xorg/app/twm/>にたどり着いた

**Comment by knokmki612** [comment]
>> * twmの改変をした方に、本家にコードを取り込んで貰っても良いか確認をとる。ライセンス周りについても相談する

> メールを送った！

「依存はありません。」という返事をいただけた！

**Comment by knokmki612** [comment]
<https://cgit.freedesktop.org/cgit/?url=xorg/app/twm/>にどうしたらコードを取り込んで貰えるのか調べる

**Comment by knokmki612** [comment]
READMEを読んでいたら

> For patch submission instructions, see: <http://www.x.org/wiki/Development/Documentation/SubmittingPatches/>

> All questions regarding this software should be directed at the
Xorg mailing list: <http://lists.freedesktop.org/mailman/listinfo/xorg>

というのを見つけた

**Comment by knokmki612** [comment]
パッチの内容を<gist.github.com>に上げた
<https://gist.github.com/knokmki612/a8b10c9ac56163e202bd>

**Comment by knokmki612** [comment]
>> For patch submission instructions, see: http://www.x.org/wiki/Development/Documentation/SubmittingPatches/

この方法に従えば良さそうなことが分かった

**Comment by knokmki612** [comment]
gdbを使う方法を<https://rat.cis.k.hosei.ac.jp/article/devel/debugongccgdb1.html>を参考にして、twmのMakefileを編集してビルドしてみた

**Comment by knokmki612** [comment]
デバッグに使うツールのページを発見した<http://wiki.x.org/wiki/XorgTesting/>が、有用な情報はなかった

**Comment by knokmki612** [comment]
パッチをgist.github.comに公開した
<https://gist.github.com/knokmki612/c708950eddf5e129f0fc>

**Comment by knokmki612** [comment]
クラッシュが確認されている.twmrcをgist.github.comに公開した
<https://gist.github.com/knokmki612/06ba86531b0fcb937e32>

**Comment by knokmki612** [comment]
> クラッシュが確認されている.twmrcをgist.github.comに公開した
> https://gist.github.com/knokmki612/06ba86531b0fcb937e32

この.twmrcの

> MenuRuns "l2r"

というオプションが有効である状態でメニューの呼び出しを行うと、クラッシュすることが分かった

**Comment by knokmki612** [comment]
起動したtwmを、別の仮想コンソールでgdb --pid (twmのpid)でデバッグできる状態になることが分かった。その後、

```
(gdb) continue
```

をしてメニューを呼び出すと、Segmentation Faultとなった。その際のメッセージとして

> MyFont_DrawString_Rotated ... at util.c : 754

の辺りで落ちていることが分かった。また、

```
(gdb) p font
(gdb) p font->font
```

をしたら、p font->fontに値が入っていないことが分かった。

**Comment by knokmki612** [comment]
```
(gdb) bt
```
をすると、MyFont_DrawString_Rotatedを呼び出しているのが、

> PaintEntry ... at menus.c : 530

であることが分かった。

**Comment by knokmki612** [comment]
> MenuRuns "l2r"

を無効にした状態でgdbで直前にブレークポイントを設定し、p fontをしたところ、値がなかった。util.cのGetFontで値がなければ終了するはずなのに、GetFontが正常に呼ばれていない可能性がある

**Comment by knokmki612** [comment]
私がビルドできているもののtar.gzをアップロードした
<https://drive.google.com/open?id=0BwLKJ6vnpcYkMWNLb0xCN2tpcjg>

**Comment by knokmki612** [comment]
twm.cでScr->HaveFontsがFALSEだとCreateFontsが呼ばれるなのにCreateFontsが一度も呼ばれていない可能性があったため、この部分をgdbで追う必要があった。
メンターの方から該当部分の前にsleepを噛ませて、その間にgdbを起動してみてはと言われたので、twm.cを修正してビルドをした。

**Comment by knokmki612** [comment]
gdbで追った結果、Scr->HaveFontsに1が立っていたので、初期化時は0だったのが、どの段階で1が立っているのか調べれば良い所まで進むことが出来た。

**Comment by knokmki612** [comment]
結局HaveFontsがtrueになる経路は、
main(twm.c)→ParseTwmrc(parse.c)→doparse(parse.c)→yyparse(gram.c)→AddtToMenu(menu.c)→CreateFonts(twm.c)→GetFont(util.c)
であることが分かった。
CreateFontsはちゃんと一度は呼ばれていることになり、動きとしては正常であることが分かった。

**Comment by knokmki612** [comment]
元をたどればMyFont_DrawString_Rotatedにおけるfont->fontに値が入っていないのが問題だったので、GetFontが上手く機能していないかを眺めた。
結論としてはGetFontではuse_fontsetというフラグで処理が分けられており、trueだとXFontSet型のMyFont font->fontsetに値が入り、falseだとXFontStruct型のMyFont font->fontに値が入るようになっていた。
この違いはXにおけるフォント表示において、前者はマルチバイト、後者は8ビット固定のものを扱うものらしい。(参考: ウィンドウマネージャーの国際化 <http://www8.plala.or.jp/tkubota1/winman.ja.html>)

**Comment by knokmki612** [comment]
そして、MyFont_DrawString_RotatedではXSetFontでフォントを指定する箇所があるが、これはXFontStruct用の関数であるために、use_fontsetがtrueになる実行環境で落ちていることが分かった。
なので、if(!XFontStruct)で分けるようにした。

**Comment by knokmki612** [comment]
なお、use_fontsetがtrueになるかどうかはtwm.c:290あたりに書いてあるが、ロケールが"CまたはPOSIX"以外かどうかとかを見ているみたい。
ちなみに利用していた人に聞いてみたところ、「export LANG=Cが普通」とか言っていたので、今まで誰も落ちなかったのは、たまたまそういう人しか使っていなかったためだと思われる

**Comment by knokmki612** [comment]
無事動くようになったため使ってみたところ、ウィンドウのタイトルバーの文字列が更新されないのが気になったため調べた。
すると、MyFont_DrawString_Rotated内で主な処理をif (*pixp == None)で囲むことによって、一度タイトルバーで文字を表示したら更新しないようになっていた。これを削ったところ、文字列が更新されるようになった。

**Comment by knokmki612** [comment]
気になっていること: 改変で追加された機能と競合しているために削られた処理があり、パッチが受け付けられるか不安

add_window.c:700あたり

```
       }
     } else {       /* put it where asked, mod title bar */
- /* if the gravity is towards the top, move it by the title height */
- if (gravy < 0) tmp_win->attr.y -= gravy * tmp_win->title_height;
     }
```

twm.c:882あたり

```
          &JunkWidth, &JunkHeight, &bw, &JunkDepth)) {

  GetGravityOffsets (tmp, &gravx, &gravy);
- if (gravy < 0) xwc.y -= tmp->title_height;

  if (bw != tmp->old_bw) {
      int xoff, yoff;
```

**Comment by knokmki612** [comment]
動作の様子(twmrcにTitleAtRight, MenuAtLeft, MenuUpward, MenuRus "l2r"を書くとこうなります)
![_2016-03-29_22-07-48](https://cloud.githubusercontent.com/assets/9744580/14109003/ff54f09c-f5fa-11e5-9b45-94856579479d.png)

**Comment by kou** [comment]
おつかれさまでした！参加した感想をブログとかにまとめてくれるとOSS Gateワークショップの普及につながってうれしいです！
（次回からはフィードバックしたメンターの人にその場でcloseしてもらうようにしよう。おつかれ！とか言いながら。）
