### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-01-28: shuheiktgw: moment.js: Work log

### ISSUE THREAD

**Issue by shuheiktgw** [oss-gate/workshop#233]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by koic** [comment]
今日はよろしくお願いします。

**Comment by shuheiktgw** [comment]
momentjsとgoogleで検索する

**Comment by shuheiktgw** [comment]
公式のドキュメントページが一番上にヒットするので開く

**Comment by shuheiktgw** [comment]
installのページが一番上にあるけどnpm installとかしないで気軽にサクッと試したい. どうしようか

**Comment by shuheiktgw** [comment]
詳しいインストール情報を調べるためにdocsのページを開く

**Comment by shuheiktgw** [comment]
簡単に試したいだけなので,ブラウザ上で使ってみたい.

**Comment by shuheiktgw** [comment]
playgroundみたいなものがほしい?

**Comment by shuheiktgw** [comment]
console上で使いたい

**Comment by shuheiktgw** [comment]
console上で叩いてみたら動いた. 何処かでインポートされてるっぽい

**Comment by shuheiktgw** [comment]
もしかしたら引っかかる部分があるかもしれないので,ブラウザ上で動かすだけではなくてインストールしてみる

**Comment by shuheiktgw** [comment]
npmを使ってインストールするためにreactのboiler plateをダウンロードしてくる

**Comment by shuheiktgw** [comment]
webstorm立ち上げたり結構面倒くさい

**Comment by shuheiktgw** [comment]
npm install moment

**Comment by shuheiktgw** [comment]
boilerplateが古いやつだったので読めない...
別のboilerplateを落としてくる

**Comment by shuheiktgw** [comment]
昔使ったreactのアプリにmomentjsをnpm install

**Comment by shuheiktgw** [comment]
node の使い方を忘れてて困った

**Comment by shuheiktgw** [comment]
画面上でmoment().format()をconsole.logで表示してみる

**Comment by shuheiktgw** [comment]
buildの仕方を忘れててつらい

**Comment by shuheiktgw** [comment]
とりあえず動いてるけど,ソースコードを変更する→build→確認のプロセスはつらい.

**Comment by shuheiktgw** [comment]
documentに載ってるコマンドをブラウザのコンソールから試してみる

**Comment by shuheiktgw** [comment]
そう言えば閏年の計算ってどうなってるんだっけ? 結構ハマったような....

**Comment by shuheiktgw** [comment]
2016年は閏年なので2017/12/31から1年引くと...?

**Comment by shuheiktgw** [comment]
2016年は閏年だけど,2016/3/1から1年を引くと...?

**Comment by shuheiktgw** [comment]
substructを使って1年引こうとしてもうまくいかない... なぜ?

**Comment by shuheiktgw** [comment]
format()を使って表示すればうまくいってた. 1年を引くと2015/3/1になった. 内部の実装的には365日を引いているわけではなくて単純に年の値から1を引いているだけっぽい

**Comment by shuheiktgw** [comment]
1dayを引くと..?

**Comment by shuheiktgw** [comment]
ちゃんと29日になった

**Comment by shuheiktgw** [comment]
2016/2/29から1年を引くと...?

**Comment by shuheiktgw** [comment]
2015/2/28になった. 閏年の処理も直感的には正しい値が帰ってきていそう

**Comment by shuheiktgw** [comment]
jaのlocalの表記はどうかな?

**Comment by shuheiktgw** [comment]
moment.months();で日本語の月のリストが帰ってくる. 和名の月名が帰ってきても面白いかもしれない(神無月てきな)

**Comment by shuheiktgw** [comment]
神無月とかの和名の月名をパースできるようにしたら面白いかもしれない

**Comment by shuheiktgw** [comment]
和暦は処理できあほうがよい?

**Comment by y-goto** [comment]
コメントしました

**Comment by colorbox** [comment]
#### 和暦について
和暦の元号を追加するという話をしてみたが、それに関する実装をしようとすると特殊な実装となる可能性が高いという話をした。

#### console
ドキュメントページでconsoleを開くとそのままライブラリを試すことができて、インストールなどの必要なく使用でき、便利であることなどを話した。

**Comment by shuheiktgw** [comment]
npm installとか面倒臭いことしなくてもplayground的に気軽に試したい.
実は,インストールしなくても実はコンソール上で気軽に試すことができるので,そのことをドキュメントで言及すると親切かもしれない.

**Comment by shuheiktgw** [comment]
Title: Add a comment about momentjs execution on browser consoles
Title: コンソールに関する記述の追加

### Suggestion
Add a comment that people can try momentjs on browser consoles in the document page.
ドキュメントページ内のコンソールでmomentjsが試すことができる旨の記述を追加する.

### Why
It improves user experiences if they can know that it is possible for them to easily try momentjs on document consoles without any installations.

サンプルコードを気軽に試すことができることによって,ユーザビリティが向上する.
npm install などをせずに気軽にドキュメントに載っているコードを試したい

### Solutions

Add a comment at  the beginning of the document that people can try momentjs on their browses consoles.

ドキュメントの先頭にコンソールで気軽に試すことができるという記述を追加するとユーザーがmomentjsを試しやすくなるのではないか.

**Comment by shuheiktgw** [comment]
https://github.com/moment/momentjs.com/pull/389

**Comment by treby** [comment]
共有頂きました、お疲れ様でした
