### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-01-28: tac-yacht: Apache Jena: Work log

### ISSUE THREAD

**Issue by tac-yacht** [oss-gate/workshop#234]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by yyamano** [comment]
やまのです。

**Comment by tac-yacht** [comment]
ドキュメントを探す

**Comment by tac-yacht** [comment]
Googleで"jena"で検索
、、、検索時点では公式が三番目　関連ページ（qiita）が一件

**まず、見つからない**

Googleで"apache jena"で検索するとほぼ関連ページしか出てこないし、公式が一番上に来る

[公式サイト](https://jena.apache.org/)

**Comment by tac-yacht** [comment]
使い始めるには、、、？

**Comment by tac-yacht** [comment]
一番最初のページに、「Get started now!」と「Download」のボタンが目立つ

どっちだ？
まず使ってみようとしてるので、スタートのほうか？

**Comment by tac-yacht** [comment]
いっぱい出てきた。　読む気がなくなる。
とりあえずチュートリアルの一番上を進む

チュートリアルのところの最下行に「中国語、ポルトガル語、フランス語」も使えると案内がある、、、
日本語はない、、、

**Comment by tac-yacht** [comment]
チュートリアルにサンプルコードが乗っているがそのまま実行できる方法が説明されていなくてどうれ場よいか迷う

**Comment by tac-yacht** [comment]
とりあえず、序論の中にソースがダウンロードできると書いているので、落とす。

が、、、？
チュートリアルに対応してるソースがどれかわからない。

**Comment by tac-yacht** [comment]
とりあえず、Apache Jenaセクションで、tar.gzとzipの二種があるので、
今回はwin環境なのでzipを落とす。

どれに含まれているという案内がほしいところ　tutorial's source in this 的な

**Comment by tac-yacht** [comment]
展開するとREADMEがあるのでとりあえず読んでみたが
tutorialについては参照先リンクについてしか言及がない

トップディレクトリの構造についても言及がない

**Comment by tac-yacht** [comment]
仕方ないので、解凍ディレクトリ全域に「tutorial」で検索する。
やりたいことはtutorialコードの実行

**Comment by tac-yacht** [comment]
検索に出てきたファイルがすべて同じ場所にあるのでどうやらこれがそれっぽい
「解凍ディレクトリルート\src-examples\jena\examples\rdf」

**Comment by tac-yacht** [comment]
本当にソースしかなくて、そのままでは依存解消ができない

**Comment by tac-yacht** [comment]
「解凍ディレクトリルート」にjena-examplesフォルダがあり、
その中にpom.xmlがあるのでmavenで依存解消できそう

**Comment by tac-yacht** [comment]
mavenを知っていることが前提になる＠ソースコードのzip

**Comment by tac-yacht** [comment]
ちなみに"apache jene"で出てくるqiitaにも最初のとりあえず実行する手順は書いてない
http://qiita.com/cloudysunny14@github/items/46ecd0fa5dba09290746

こっちはfusekiなので、関係あるけど最初のとりあえず実行には関係ない
http://qiita.com/sken/items/c0aeb76ae1e3f74233cd

**Comment by tac-yacht** [comment]
jena-examplesフォルダに次のクラスがあるけれどもtutorialとはかすりもしない
org.apache.jena.example.helloworld.HelloWorld.java

**Comment by tac-yacht** [comment]
先ほどのソースだけをインポートしてみる

**Comment by tac-yacht** [comment]
先ほどのjena-examplesで依存解決したところに
マージする形でインポートする
tutorialにはない

jena-examplesはsrc-examplesの中

**Comment by tac-yacht** [comment]
これで、tutorialのコードは実行できるようになった。

が、実行してもコンソールに何も出ないので、「だからどうした？」感がすごい

**Comment by tac-yacht** [comment]
よく読んだら、チュートリアルの序論にXMLとJavaを知っていることって書いてある
原文→Some familiarity with both XML and Java is assumed.
Javaを知ってるからといってMaven知ってるとは限らないのでは？

**Comment by tac-yacht** [comment]
前提条件記述部分＠グーグル翻訳
> RDFに精通していないプログラマのために書かれたもので、プロトタイピングでベストを習う人、または他の理由からすぐに実装に移りたいと思っています。XMLとJavaの両方に精通していることが前提です。

**Comment by treby** [comment]
振り返りました。
純粋な視点でイケてない部分を指摘できているのが素晴らしいと思います。
フィードバックのやり方があると思うのでその点も調べてみると良いと思います(メーリスとか)。

**Comment by tac-yacht** [comment]
チュートリアルのページにソースのリンクがあるが、ソースのどの部分と対応しているか明示するべき
http://jena.apache.org/tutorials/rdf_api.html
`\src-examples\jena\examples\rdf`

方法はそのまま編集するらしい
ただ、説明には[Diff]と書いてあるのに全文入ってくる。 
http://jena.apache.org/getting_involved/index.html#improving-the-website

**Comment by tac-yacht** [comment]
チュートリアルのソースコードへのリンクが、基本的にはコードのあらわれる前に記載されている。
しかし、１と２だけコードの現れた後に出現している。
そのため、一見ソースコードへ飛ぶことが難しくなっている。
※一個前のコメントの段階でもまた見落としていた。

ほかとあわせてコード表記の直前にリンクを表記すると統一されて読みやすくなると報告する。

**Comment by tac-yacht** [comment]
2については直前に出てくるので許容範囲
1については異なるコードをはさんだ後に出現するため、ソースへの追従性が低下している

編集した後にメールが来るので、それにコメントを付けて送る必要がある。

**Comment by tac-yacht** [comment]
タイトル：チュートリアル１の文の順序
The sentence of "Tutorial 1" order.

「チュートリアル１」のセンテンスはほかのコードブロックの出現前にある方がわかりやすい
The sentence of "Tutorial 1" is easier to understand if there is another sentence before the code block appears

**Comment by tac-yacht** [comment]
とりあえず、successと表示されたので送信されたはず、、、、
編集画面でメール欄空にしてquickメールも外すと単にコミットになるので、
その後Mail diffでタイトルと本文付けて送れる　はず、、、

**Comment by colorbox** [comment]
フィードバックしました

**Comment by tac-yacht** [comment]
代理クローズ
