### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-01-28: entaku0818: vue.js : Work log

### ISSUE THREAD

**Issue by entaku19890818** [oss-gate/workshop#235]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by treby** [comment]
よろしくお願いします！

**Comment by entaku19890818** [comment]
よろしくお願いします！

**Comment by entaku19890818** [comment]
開発環境をVagrantで立ち上げる！

**Comment by entaku19890818** [comment]
vue.jsの本サイトにアクセスして、使い方を見る

**Comment by entaku19890818** [comment]
インストール方法をcheckする！

**Comment by entaku19890818** [comment]
checkした！
https://jp.vuejs.org/v2/guide/installation.html
$ npm install vue

**Comment by entaku19890818** [comment]
errorが出た！
---
npm WARN npm npm does not support Node.js v0.10.46
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN checkPermissions Missing write access to /var/www/html
/var/www/html
└── vue@2.1.10

npm WARN enoent ENOENT, open '/var/www/html/package.json'
npm WARN html No description
npm WARN html No repository field.
npm WARN html No README data
npm WARN html No license field.
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "vue"
npm ERR! node v0.10.46
npm ERR! npm  v4.0.5
npm ERR! path /var/www/html
npm ERR! code EACCES

npm ERR! Error: EACCES, access '/var/www/html'
npm ERR!     at module.exports (/usr/lib/node_modules/npm/lib/install/access-error.js:4:18)
npm ERR!     at /usr/lib/node_modules/npm/lib/install/writable.js:30:25
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR!  { [Error: EACCES, access '/var/www/html'] code: 'EACCES', path: '/var/www/html' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "vue"
npm ERR! node v0.10.46
npm ERR! npm  v4.0.5
npm ERR! path npm-debug.log.3695524641
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, open 'npm-debug.log.3695524641'
npm ERR!  { [Error: EACCES, open 'npm-debug.log.3695524641'] errno: 3, code: 'EACCES', path: 'npm-debug.log.3695524641' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log

**Comment by entaku19890818** [comment]
ログを見る！
/var/www/html/npm-debug.log

**Comment by entaku19890818** [comment]
Please try running this command again as root/Administrator.
権限がない？

**Comment by entaku19890818** [comment]
sudo npm install vue
npm WARN npm npm does not support Node.js v0.10.46
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
/var/www/html
└── vue@2.1.10

npm WARN enoent ENOENT, open '/var/www/html/package.json'
npm WARN html No description
npm WARN html No repository field.
npm WARN html No README data
npm WARN html No license field.

**Comment by entaku19890818** [comment]
入ったっぽい！😄

**Comment by entaku19890818** [comment]
vueをweb上で動かしたい！

**Comment by entaku19890818** [comment]
どうやって動かす？
ググる。
公式サイトで動かす方法を探す

**Comment by entaku19890818** [comment]
https://jp.vuejs.org/v2/guide/index.html
もしくは、単純に .html を作成し、以下のように Vue を含むことができます:
<script src="https://unpkg.com/vue/dist/vue.js"></script>

**Comment by entaku19890818** [comment]
もう一回インストールページを見る
> インストールしたやつは使わないの？
解決できず...

**Comment by entaku19890818** [comment]
いや、でもとりあえず動かす

**Comment by entaku19890818** [comment]
Hello Worldしたい！

<div id="app">
  {{ message }}
</div>
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})

**Comment by entaku19890818** [comment]
htmlのjavascriptの書き方はわかってる前提。。。。

**Comment by treby** [comment]
https://github.com/oss-gate/workshop/issues/235#issuecomment-275821659

> 公式ガイドは、HTML、CSS そして JavaScript の中レベルのフロントエンドの知識を前提にしています。フロントエンドの開発が初めてであるならば、最初のステップとして、フレームワークに直接入門するのは良いアイデアではないかもしれません。基礎を学んで戻ってきましょう！他のフレームワークでの以前の経験は役に立ちますが、必須ではありません。

らしいw
https://jp.vuejs.org/v2/guide/index.html#はじめに

**Comment by entaku19890818** [comment]
ファイルを作成した！

**Comment by entaku19890818** [comment]
webサーバー上で動かしたい！

**Comment by entaku19890818** [comment]
アクセスしてみる！

**Comment by entaku19890818** [comment]
できた！

**Comment by entaku19890818** [comment]
![170128-0001](https://cloud.githubusercontent.com/assets/9211010/22393698/6ee1aa2e-e54f-11e6-9dfe-ca36a398cb5b.jpg)

**Comment by treby** [comment]
> ファイルを作成した！

中身が分かると良いかも

**Comment by entaku19890818** [comment]
シム化とは？https://jp.vuejs.org/v2/guide/installation.html

**Comment by entaku19890818** [comment]
https://jp.vuejs.org/v2/guide/installation.html#スタンドアロン
ダウンロードし script タグで読み込んでください。Vue はグローバル変数として登録されます。

なんでコード例ないの？？？？？？？？？？

こんな感じで↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
<script src="${インストールした場所}"></script>

**Comment by entaku19890818** [comment]
もう少し動かしたい。

**Comment by entaku19890818** [comment]
clickしたら文字変えたい

**Comment by entaku19890818** [comment]
やっぱやめた。

**Comment by entaku19890818** [comment]
ジェネーレータ
installしたら、
webサーバ立てなくでも使えて、テンプレートがある。
テンプレを変更すると、プログラマー気分になれて楽しいはず。

**Comment by treby** [comment]
vue-cliというのはあるらしい、起動まではいかなさそうだけれど
https://github.com/vuejs/vue-cli

**Comment by entaku19890818** [comment]
> 起動まではいかなさそうだけれど
chance!

**Comment by entaku19890818** [comment]
とりあえずもう一度動かしてみる！！
https://github.com/vuejs/vue-cli

**Comment by entaku19890818** [comment]
npm install -g vue-cli

**Comment by entaku19890818** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/vue-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "vue-cli"
npm ERR! node v0.10.46
npm ERR! npm  v4.2.0
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES

npm ERR! Error: EACCES, access '/usr/lib/node_modules'
npm ERR!     at module.exports (/usr/lib/node_modules/npm/lib/install/access-error.js:4:18)
npm ERR!     at /usr/lib/node_modules/npm/lib/install/writable.js:30:25
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR!  { [Error: EACCES, access '/usr/lib/node_modules'] code: 'EACCES', path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.npm/_logs/2017-01-28T03_06_57_029Z-debug.log

**Comment by entaku19890818** [comment]
> npm ERR! Please try running this command again as root/Administrator.

またrootで実行するって書いてある

**Comment by entaku19890818** [comment]
最初にrootで実行してって言ってよ！！！！！！！！！！！！

**Comment by entaku19890818** [comment]
実行中の間にvue-cliの使い方をもう一度見る

**Comment by entaku19890818** [comment]
これで実行してくれるかなぁ？？？？？？
vue init <template-name> <project-name>

**Comment by entaku19890818** [comment]
vue init webpack my-projectでとりあえず実行

**Comment by entaku19890818** [comment]
できない！！！！

**Comment by entaku19890818** [comment]
もう一度インストールする
npm install -g vue-cli

**Comment by knokmki612** [comment]
ふりかえりました！

**Comment by entaku19890818** [comment]
インストールの方法を分けて書いたほうがいい
->どこに書いたらいいか？の案を考えてみる。
わからない単語「シム化」の理由をリンクを貼ってみたりする。
インストールの手順内で権限がない場合はsudoを実行してみる手順がある。
->インストールが正常にできたことをどうやって確認するかを追加するー

**Comment by hiroyuki-sato** [comment]
振り返り担当しました。午後も頑張ってください。

**Comment by entaku19890818** [comment]
手順
	1.「インストール」ページに記載されている手順でvue.jsをインストールした
	```
	npm install vue 
	```
	
	2.「はじめに」のページに書いてある手順で、インストールしたvue.jsを実際に動かそうとした。

	3.しかし、「はじめに」のページはweb上のvue.jsを指定して利用する手順に成っていたので、
		せっかくインストールで落としたvue.jsを利用しなかった。

期待する動作:
	installしたvue.jsを利用する手順になっていて欲しかった。

**Comment by entaku19890818** [comment]
I am interested in the javascript framework and I wanted to use vue.js this time.
I attempted to set up referring to the official site of vue.js,
There was a confusing point in the document.
Https://vuejs.org/v2/guide/index.html

Procedure
1. I installed vue.js by following the instructions on the "Installation" page

```
npm install vue
````

2. I attempted to move the installed vue.js in the procedure written on the "Introduction" page.

3. However, since the page of "Introduction" was a procedure to designate and use vue.js on the web,
I did not use vue.js that I dropped by installation.

Expected behavior:
I wanted it to be a procedure to use the installed vue.js.

Possible remedy:
Write code example of script tag when installing on "Introduction" page

What do you think?

**Comment by y-goto** [comment]
お疲れ様でした。英語は難しい単語よりも、簡単な中学生の英語を使うことから慣れていってください。あと、他の人の質問などをみて、真似していくことから初めて見てください。
