### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-1-28: cohki0305: ruby-trello: Work log

### ISSUE THREAD

**Issue by cohki0305** [oss-gate/workshop#236]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by y-goto** [comment]
よろしく

**Comment by cohki0305** [comment]
インストール方法については github の [README](https://github.com/jeremytregunna/ruby-trello) に書いていた

**Comment by cohki0305** [comment]
README に記述されている コマンドを実行すると trello の public_key が習得できた。
コマンド：`Trello.open_public_key_url`

**Comment by cohki0305** [comment]
README に記述されている  
`Trello.open_authorization_url key: PUBLIC_KEY` 
コマンドで、key が習得することができる。

**Comment by cohki0305** [comment]
config の設定と consumer key 等の取得方法がわからなかったので
`ruby-trello example` で検索したら、 [ruby-trello gem で API を利用して Trello を操作する #trello #ruby #api](http://qiita.com/tbpgr/items/60fc13aca8afd153e37b)の記事を見つけた。

**Comment by cohki0305** [comment]
README に複数の config 設定が記述されており、どれを利用すべきなのか不明。

**Comment by cohki0305** [comment]
README に様々な言葉が使われていてわかりにくい。

**Comment by cohki0305** [comment]
結局 qiita に書いている記事通りに実行したみた。認証に成功した。

役に立った記述

> CONSUMER_KEY / CONSUMER_SECRET の取得
> Trello にログイン後、下記 URL より CONSUMER_KEY / CONSUMER_SECRET を取得します。

> https://trello.com/1/appKey/generate

> アプリケーショントークンの取得
> Trello にログイン後、下記 URL より OAUTH_TOKEN を取得します。

> https://trello.com/1/authorize?key=your_key&name=My+Application&expiration=1day&response_type=token&scope=read,write

**Comment by cohki0305** [comment]
> #step 3 

README に以上のように記述されているが、step1, 2 しかない。
3 と 2 を間違えた？

```ruby
Trello.configure do |config|
  config.developer_public_key = TRELLO_DEVELOPER_PUBLIC_KEY # The "key" from step 1
  config.member_token = TRELLO_MEMBER_TOKEN # The token from step 3.
end
```

**Comment by cohki0305** [comment]
なぜキーが4つも出てきたの？

> 2-legged OAuth authorization

```
Trello.configure do |config|
  config.consumer_key = TRELLO_CONSUMER_KEY
  config.consumer_secret = TRELLO_CONSUMER_SECRET
  config.oauth_token = TRELLO_OAUTH_TOKEN
  config.oauth_token_secret = TRELLO_OAUTH_TOKEN_SECRET
end
```

**Comment by cohki0305** [comment]
最初に動かせる方法を説明して、その後に別の方法での認証方法を紹介してもよいのではないかな。

**Comment by cohki0305** [comment]
Getting Started

**Comment by cohki0305** [comment]
```
# Print his bio
puts bob.bio # A wonderfully delightful test user
# How about a list of his boards?
bob.boards
```

bio と boards がどういうメソッドかわからなかったので、実際にコードを読もうと思った。

**Comment by cohki0305** [comment]
boards について[ソースコード](https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/member.rb) に記述があった

**Comment by cohki0305** [comment]
bio は member の attributes

**Comment by cohki0305** [comment]
今までは `Trello::Member` を使っていたがメインのクラスは
`Trello::Client` だったようだ

**Comment by cohki0305** [comment]
```
@client_bob = Trello::Client.new(
  :consumer_key => YOUR_CONSUMER_KEY,
  :consumer_secret => YOUR_CONSUMER_SECRET,
  :oauth_token => "Bob's access token",
  :oauth_token_secret => "Bob's access secret"
)
```

`Trello::Client` においてもキーが4つあるが、 Qiita だと3つのキーしかない。
READMEでは、`oauth_token_secret` があるのが違う。

**Comment by cohki0305** [comment]
Client Class についての説明が README にないので[コード](https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/client.rb)を読んだ。

**Comment by koic** [comment]
README に記されているキーの役割や、コメントにあるようにミニマムで動作するための Getting Started があると使い方が分かりやすくなりそうですね。

**Comment by cohki0305** [comment]
フィードバックしたい内容

## Step 3 ってなに？

Step 2 ではないのか？

## Getting Started があると親切だと思う。

- 簡易的な設定
- client を使ってボードやメンバーを習得する方法を伝える

```
client = Trello::Client.new(
  :consumer_key => CONSUMER_KEY,
  :consumer_secret => CONSUMER_SECRET,
  :oauth_token => OAUTH_TOKEN
)

member = client.find(:member, 'cohki0305')
puts member.attributes
```

**Comment by cohki0305** [comment]
Title "What is Step 3 in README ?"

In README, 

```ruby
config.member_token = TRELLO_MEMBER_TOKEN # The token from step 3.
```

I cannot find step 3 when geting API public key. 
Is it step 2 ?

> Trello.open_authorization_url key: 'yourpublickey'

I thought it is "step 3".

**Comment by cohki0305** [comment]
Title "What is purpose of each keys?"

Hello 

In reading [README](https://github.com/jeremytregunna/ruby-trello), I confused purpose of each keys. 
At first, I cannot find what are `TRELLO_CONSUMER_KEY` and `TRELLO_CONSUMER_SECRET` because these keys are not explained on it.

In addition, I thought that the purpose of `TRELLO_DEVELOPER_PUBLIC_KEY` is similar to `TRELLO_CONSUMER_KEY`.
I did not get difference between `TRELLO_OAUTH_TOKEN` and `TRELLO_CONSUMER_SECRET`.

Please tell me each keys purpose.

**Comment by cohki0305** [comment]
2つのissueを報告した。
1つのPRを出して、タイポを修正。

**Comment by hiroyuki-sato** [comment]
フィードバックしました。
お疲れ様でした。

**Comment by knokmki612** [comment]
おつかれさまでした！
立てたissueやPRのメモはされましたか？
クローズされていても、引き続きメモすることはできますので、よかったらどうぞ！
