### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-01-28: kadoppe: remotipart: Work log

### ISSUE THREAD

**Issue by kadoppe** [oss-gate/workshop#237]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by hiroyuki-sato** [comment]
よろしくお願いします。

**Comment by kadoppe** [comment]
Googleで`remotipart`キーワードで検索し、ドキュメントをさがしたらGitHubのリポジトリをみつけた。

https://github.com/JangoSteve/remotipart

**Comment by kadoppe** [comment]
READMEを読み始めた。
```
Remotipart is a Ruby on Rails gem enabling AJAX file uploads with jQuery in Rails 3 and Rails 4 remote forms.
```

Rails 3と4には言及されているけど、Rails 5についてはどうなんだろう。うごくのかな。

**Comment by kadoppe** [comment]
READMEから、Github以外の場所にホストされている公式サイトみつけた。

https://os.alfajango.com/remotipart/

こっちにもドキュメントあるけど、ちゃんと最新化されているか不安。GitHubと公式サイトのどっちが正？？

**Comment by kadoppe** [comment]
公式サイト https://os.alfajango.com/remotipart/ のほうには Rails 3についての言及しか無い。

これはGitHubのドキュメントの方が新しいと考えて良さそう。

古いドキュメントは最新化するか、サイト削除するかのどっちかにしてほしいなぁ。

**Comment by kadoppe** [comment]
念のため、公式サイトの最終更新日を調べてみようとしてる。

**Comment by kadoppe** [comment]
Github上のREADMEの最終コミットは、on Oct 14, 2015

**Comment by kadoppe** [comment]
公式サイトの最終更新日はわからんけど、とりあえず古そう。

**Comment by kadoppe** [comment]
Railsのどのバージョンで動くGemなのかが、すごく気になりだしている。

公式サイトから、サンプルのRailsアプリケーションが保存されたGitHubリポジトリへのリンクをみつけた。

[JangoSteve/Rails-jQuery-Demo: Demo Rails App with jQuery UJS](https://github.com/JangoSteve/Rails-jQuery-Demo)

**Comment by kadoppe** [comment]
サンプルRailsアプリケーションの最終更新日（masterブランチは）二年前。あんまりメンテされていない感。

**Comment by kadoppe** [comment]
Rails 5で動くのか動かないのか、そもそもRails 5だとこのGem必要ないのか。そういった情報はREADMEにほしいと思ったりした。

**Comment by kadoppe** [comment]
> Rails 5で動くのか動かないのか、そもそもRails 5だとこのGem必要ないのか。そういった情報はREADMEにほしいと思ったりした。

これが気になるので、remotipartに登録されているIssueを確認してみる。

**Comment by kadoppe** [comment]
Issueのページにアクセスしたら、すぐ目につくタイトルのIssueが見つかった。

[in rails 5 remotipart is not working · Issue #170 · JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/issues/170)

**Comment by kadoppe** [comment]
↑のコメントでremotipartのIssueへのリンクを張ったら、リンク先でこんなことになった。

ノイズ混ぜたような気がして申し訳ない気持ちになった。

![screen shot 2017-01-28 at 11 35 05](https://cloud.githubusercontent.com/assets/20763/22393634/f163b728-e54d-11e6-9fb1-f20a0c3aa1c6.png)

**Comment by kadoppe** [comment]
Issueとそれについているコメントを読んで見る。

**Comment by kadoppe** [comment]
Issue読んでいる途中に「これいつのIssue？」と思ったので日付を確認したら、Oct 14, 2016

**Comment by kadoppe** [comment]
remotipart 1.3.1 で動いたよ、というコメントがIssueに投稿されていた。

```
1.3.1 works fine for me
```

**Comment by kadoppe** [comment]
つづいて、他の人からも1.3.1で動くとコメント。ついでにこの人は、「READMEで Rails5 は1.3.1が必要だよと言及すべき」と意見出してる。

```
1.3.1 works great. IMO there should be mentioned on main page bout specifying 1.3.1 in gemfile for 5-th.
```

この意見に対するコメントは特になく、 👍 が３件ついているだけ。

**Comment by kadoppe** [comment]
上記提案をみつけたので改めてREADMEにRails5についての記述がないか確認した。

やっぱりなかった。

**Comment by hiroyuki-sato** [comment]
Rails5を使う場合は、1.3.1以降を使ってくださいとどこかに案内があるといいですね。

**Comment by kadoppe** [comment]
もしかしたら、README修正するPull Requestがでてるかもしれないとおもったので、確認してみる

**Comment by kadoppe** [comment]
今openになっているPull Requestのタイトルを読む限り、README修正するためのPull requestはなさそう。

**Comment by kadoppe** [comment]
もうすでにPull Requestが挙がっている場合は、自分でやっても仕方がないとおもったので、今openのPull Requestを全部確認中。

**Comment by kadoppe** [comment]
全PRのdiffを確認し、READMEに対して何らかの修正を行っているものが存在しないことがわかった。

**Comment by kadoppe** [comment]
Issueでは他の人が「1.3.1がRails5で動くよ！」と言ってるけど、鵜呑みにしないほうがいいと思い始めたので、自分のローカル環境で試してみようと思う。

**Comment by kadoppe** [comment]
公式サイトのソースコードがどこにあるのか気になったので調べ始めた。

ドメインが os.alfajango.com なので、 alfajango でググったら、GitHubアカウントをみつけた
https://github.com/alfajango

**Comment by kadoppe** [comment]
上でみつけたGitHubアカウントで管理されているリポジトリに、何か静的Webサイト管理してそうな名前のやつがないか調べる。

全リポジトリの名前確認中。

**Comment by kadoppe** [comment]
alfajango は 企業organization。 people欄にremotipartのリポジトリを持っている JangoSteve さんが登録されていた。

alfajango という会社に JangoSteveさんが勤めている or 勤めていたのかな？

**Comment by kadoppe** [comment]
GitHub Pages用のリポジトリをみつけた。

Descriptionに「Open Source by Alfa Janog site http://os.alfajango.com」って書いてあるってことは、公式サイトのソースはこのリポジトリに管理されているっぽい。

**Comment by kadoppe** [comment]
_posts ディレクトリ配下にソースあるんじゃないかと推測し、中身を見るとあった。

https://github.com/alfajango/alfajango.github.com/blob/master/_posts/2012-01-09-remotipart.md

markdownだ。

ドキュメントが二重管理になってることで、メンテが行き届かなかくなる事例を見た。

**Comment by kadoppe** [comment]
まとめると、GitHub と 公式サイト（？）の２つのドキュメントがあり、それぞれが別のリポジトリで管理されている。

公式サイトのドキュメントはRails 3まで、GitHubのドキュメントはRails 4まで言及されており、両者に差がある状態。

加えて、Rails5にかんしてはどちらも言及していない。

**Comment by kadoppe** [comment]
ドキュメントの現状は把握できた気がするので、Rails 5でremotipart動くかどうか実際に試すフェーズに行こうと思う。

そういえばdemoアプリのリポジトリはさっきみつけたので、それをCloneして見ようと思う。
https://github.com/JangoSteve/Rails-jQuery-Demo

**Comment by hiroyuki-sato** [comment]
ちなみに私は以下でぐぐって見つけました。

```
"The Remotipart gem enables AJAX file-upload capability to remote forms in Rails 3" site:github.com
```

上記のキーワードは、オフィシャルページの適当な一文です。

**Comment by kadoppe** [comment]
サンプルアプリのCloneは完了した。

でも、サンプルアプリにもREADMEがあるので、まずそれを読んでみることにする。

**Comment by kadoppe** [comment]
READMEを読んでこのサンプルアプリのリポジトリは、remotipartのためだけに作られたものではないことがわかった。

```
Also, see the remotipart branch for AJAX file-upload functionality.
```
remotipartブランチの内容を調べる必要がある模様。たらい回し感、疲れてきた。

remotipart専用にサンプルアプリのリポジトリ作ったほうが、混乱ないかもとおもった。

**Comment by hiroyuki-sato** [comment]
余談、このメモには言及されていないが、
https://github.com/JangoSteve/remotipart
には、forked from xxxという記述がある。
その先をみると、なにか情報が書かれているだろうか？

**Comment by kadoppe** [comment]
サンプルアプリのブランチをremotipartに切り替えて改めてREADMEを読んだ。

見出しが以下。Remotipart!!!
```
Demo Rails 3.1 App with jQuery UJS (AJAX) and Remotipart
```

どうやらRails 3.1用らしい。ただ、コミットログにはUpdate to Rails 4.0の文字。

ドキュメントとソースが動悸していない。

**Comment by kadoppe** [comment]
気になってforkもとのリポジトリ確認してみた。

とりあえず、メンテナンスはとまっている旨の文言は確認。

**Comment by kadoppe** [comment]
forkモトのリポジトリは、もうメンテナンス止まっている旨書いているから、こっちへのドキュメント更新は必要ない

**Comment by kadoppe** [comment]
ローカルにチェックアウトしたサンプルアプリがmasterむいているので、remotipartブランチに切り替えてみる。

**Comment by kadoppe** [comment]
ローカルでコミットログ確認して、Rails 4向けのremotipartサンプルアプリがチェックアウトされていること確認できた。

![screen shot 2017-01-28 at 12 16 36](https://cloud.githubusercontent.com/assets/20763/22393861/b4b3284e-e553-11e6-9e35-17245ada975e.png)

**Comment by kadoppe** [comment]
とりあえず、Rails5で動くかどうかを試す前に、Rails4向けのサンプルが動くかどうかを確認しようと思う。

動かし方についてはREADMEに記載がない。一般的なあぷりとして動かせということかな。

**Comment by kadoppe** [comment]
とりあえず、bundle install

**Comment by kadoppe** [comment]
## いただいたアドバイス
- CloseのIssueやPRも確認した方がよさそう。
- プロジェクトのアクティブさも見たほうが、察しやすい。

## 質問
- Q: 察した結果、モチベーションがなさそうなプロジェクトにも何らかのフィードバックすべきなのか？基準とか線引とかありますか？
- A: 自分の中にとどめておくよりもpublicにしたほうが、他の人がそれを見つけたときに幸せになるから、たとえそれが取り込まれなくてもフィードバックすると思う。

**Comment by yyamano** [comment]
ふりかえりました。

**Comment by kadoppe** [comment]
FBの内容を自分なりに整理。

公式サイト（？）のドキュメントと、GitHubリポジトリのREADMEの内容に差分がある。（例えば Rails 4への言及がないなど。）
https://os.alfajango.com/remotipart/

Rails 5への言及をREADMEに追加したいと思ったが、どちらのドキュメントにPull Requestを送るべきか迷ってしまった。

公式サイトのドキュメントの内容をGitHubリポジトリのREADME相当にアップデートする、または 公式サイトのドキュメントの内容を最小限にし詳細はGitHub上のReadmeへのリンクを貼るようにすれば、これからこのGemを使い始めるためにREADMEを読み始める人や、よりよいREADMEになるように貢献しようとしている人の助けになると思う。

**Comment by kadoppe** [comment]
GitHubのリポジトリに CONTRIBUTING.md があった。
https://github.com/JangoSteve/remotipart/blob/master/CONTRIBUTING.md

ドキュメントに関する記載はなし。

**Comment by kadoppe** [comment]
Gem本体ではなく、公式サイトに対する改善希望をFBするため、以下のリポジトリにFB送ってみようと思う。（過去、IssueもPRも投稿された形跡がなくて、少し不安）
https://github.com/alfajango/alfajango.github.com

**Comment by kadoppe** [comment]
Issueの内容を日本語で整理

### タイトル
remotipartのドキュメントが古くなっています。

### 内容
本サイト上のremotipartに関するドキュメントの内容が、[JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/blob/master/README.rdoc)の内容と比べて古くなっています。

例）本サイト上のドキュメントには Rails 4に関する記載がない

私はremotipartのドキュメントにRails 5に関する記載を追加したいと思っていますが、ドキュメントが複数あり、またそれぞれに差分が生じているため、どちらに向けてPull Requestを作成すべきか迷っています。

私の提案として、以下のいずれかに方針を決めた方がよいと思いますが、いかがでしょうか。

- A) 本サイト上のドキュメントを [JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/blob/master/README.rdoc) の内容と一致する形にアップデートする。
- B) 本サイト上のドキュメントを内容をシンプルにし、 [JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/blob/master/README.rdoc)にリンクを貼る形にする。

ご検討していただけるとうれしいです。

**Comment by hiroyuki-sato** [comment]
* ホームページのメンテナはオリジナルの開発者です。
* すでにプロジェクトのメンテナをやめています。
* プロジェクトのホームページはオリジナル作者が作ったもののままで古いもになっています。
* 自分はこのプロジェクトをRails5でも使いたいと思ってます。

オリジナルの作者に敬意をしめすとともに、現在メンテナンスされているREADMEのページの案内を一文追加してもらうことはできますか？というのが角が立たなくて良いように思います。

**Comment by kadoppe** [comment]
【WIP】追記・編集していきます。

### Title
Documentation for remotipart is out of date.

###  Content

It seems the documentation for remotipart on https://os.alfajango.com/remotipart/ is out of date in comparison with [remotipart/README.rdoc at master · JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/blob/master/README.rdoc)

e.g. 
- There is no reference about compatibility for Rails 4.

I want to use this great gem on Rails 5, and also want to add refarence about compatiblity for Rails 5 to documentation for remotipart.

**Comment by kadoppe** [comment]
もうちょっと角を取りたい。

**Comment by hiroyuki-sato** [comment]
私は英語が苦手なので
* お礼などなどは一番最初に
* 要件は手短に一番最初に
* 理由はそのあとで
の順番を意識しています。

イメージとしてはこんな感じです。

このプロジェクトを作ってくれてありがとう。
ホームページの修正についてのお願いです。
理由
* xxxx
* xxx
* xxx

よろしくお願いします。

**Comment by kadoppe** [comment]
順番を変えてみた。

**Comment by kadoppe** [comment]
あまり開発者がアクティブではない状態では、方針お伺いするよりもPRで自分がいいと思う修正を投げたほうがよい、というアドバイスもらった。

**Comment by kadoppe** [comment]
公式サイトにPRを送るために、公式サイトのリポジトリをforkする。

**Comment by kadoppe** [comment]
PRつくって投稿した。

https://github.com/alfajango/alfajango.github.com/pull/1

**Comment by kadoppe** [comment]
最終的なFBの内容。

```
Thank you for your contribution to remotipart gem.

I have a request for you to update documentation for remotipart on [this site](https://os.alfajango.com/remotipart/).

My suggestion is below:

- adding a reference or a link to [remotipart/README.rdoc at master · JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/blob/master/README.rdoc)  on this site.

Because: 
- It seems the documentation for remotipart on [this site](https://os.alfajango.com/remotipart/) is out of date in comparison with [remotipart/README.rdoc at master · JangoSteve/remotipart](https://github.com/JangoSteve/remotipart/blob/master/README.rdoc)
  - e.g. There is no reference about compatibility for Rails 4.
- I want to use your great gem on Rails 5, and also want to add reference about compatibility for Rails 5 to documentation for remotipart. But I'm little confusing because there are two documentations and there are differences between them.

Note:
I couldn't check my update is valid, because I don't know how to build this site. I with you could tell me how to build.

Thank you for your consideration.
```

**Comment by kadoppe** [comment]
ビルドのやり方がわからなかったので、動作確認ができなかった旨を伝えておいた。

**Comment by kou** [comment]
おつかれさまでした！
これからもOSSの開発に継続的に参加していってください！
