### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-01-28: yinm: Composer: Work log

### ISSUE THREAD

**Issue by yinm** [oss-gate/workshop#238]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by yyamano** [comment]
やまのです。

**Comment by yinm** [comment]
よろしくお願いします！

**Comment by yinm** [comment]
公式サイトはどこにあるんだろう？

**Comment by yinm** [comment]
Googleで、"composer"で検索
公式サイトがあった https://getcomposer.org/

**Comment by yinm** [comment]
どこから始めたらいいかページを見てたら、Getting Startedがあったのでクリック
https://getcomposer.org/doc/00-intro.md

**Comment by yinm** [comment]
日本語で読めるドキュメントがあったらいいなと思って、
Googleで、"composer 日本語"で検索
日本語訳のドキュメントがあった https://kohkimakimoto.github.io/getcomposer.org_doc_jp/doc/00-intro.html

**Comment by yinm** [comment]
日本語ドキュメントは、個人が作成しているものだった。
公式のものと同期されているのだろうか？

**Comment by yinm** [comment]
ダウンロード・インストールの手順が公式と日本語違っているみたい

公式
```
https://getcomposer.org/download/ に書いてある方法でダウンロード
php composer-setup.php --install-dir=bin --filename=composer
```

日本語訳
```
$ curl -sS https://getcomposer.org/installer | php
$ curl -sS https://getcomposer.org/installer | php -- --install-dir=bin
```

**Comment by yinm** [comment]
公式のダウンロード方法 https://getcomposer.org/download/ の1行目実行してみた。`
`composer-setup.php` をカレントディレクトリに持ってこれた。

```
~/Study/oss -
(*'-') < php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
~/Study/oss -
(*'-') < ll
total 608
-rw-r--r--  1 Cminor9  staff    15B  1 28 10:31 170128.md
-rw-r--r--  1 Cminor9  staff   298K  1 28 11:34 composer-setup.php
```

**Comment by yinm** [comment]
> Now just run `php composer.phar` in order to run Composer.

とあるので、`php composer.phar`を実行してみる。
バージョン情報や使えるコマンドなどがずらずらっと出てきた。

**Comment by yinm** [comment]
インストールが完了して、使い方を調べたいと思った。
同じページの一番下に、Basic usageがあったのでアクセスする。
https://getcomposer.org/doc/01-basic-usage.md

**Comment by yinm** [comment]
ログのライブラリである、`monolog/monolog`をインストールしてみる

`composer.json` が必要なので、例を参考に作成する

```
~/Study/oss -
(*'-') < cat composer.json
{
    "require": {
        "monolog/monolog": "1.0.*"
    }
}
```

インストールコマンドを実行する

```
~/Study/oss -
(*'-') < php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing monolog/monolog (1.0.2) Downloading: 100%
Writing lock file
Generating autoload files
```

インストールできた。
`composer.lock`はバージョン管理ツールにはちゃんとコミットしておいてほしいらしい (他のユーザーが利用する時に、同じバージョンを使えるようにするため)

> Commit your application's composer.lock (along with composer.json) into version control.

> If no composer.lock file exists, Composer will read the dependencies and versions from composer.json and create the lock file after executing the update or the install command.

**Comment by yinm** [comment]
Packagistというもので、Composerのライブラリが管理されているらしい
https://packagist.org/search/?q=%EF%BD%8A%EF%BD%8A%EF%BD%8A%EF%BD%8A%EF%BD%8A%EF%BD%8A%EF%BD%8A%EF%BD%8A

**Comment by yinm** [comment]
autoloadingの機能は、PSR-4のautoloaderに準拠してる？
http://www.php-fig.org/psr/psr-4/ のリンクがあったのでアクセス。

PHPのautoloadがわかってないなと思ってたら、
http://php.net/autoload のリンクがあったのでアクセス(日本語サイト！)

**Comment by yinm** [comment]
spl_autoload_register() 関数 というよく知らない関数があったが、リンクがあったのでアクセス
http://php.net/manual/ja/function.spl-autoload-register.php

**Comment by yinm** [comment]
## 午前のふりかえり
* ダウンロードとインストールは、コマンドは一発でいけたらいいのでは?
* 日本語サイトほしい！(他言語対応)

**Comment by treby** [comment]
振り返りしました！
比較的すんなり動かすことができたようで素晴らしいです。
動かすまでの過程で気になった点を深掘りすると、フィードバックの機会がよりありそうですね！

**Comment by yinm** [comment]
## 言いたいことをまとめる
https://getcomposer.org/download/ のインストール方法は2種類ある
* コマンドを順番に実行する方法
* シェルスクリプトを実行する方法

ページを上から順番に見ていくと、コマンドを実行する方法が目に付くのでそちらでインストールしたが、その後にシェルスクリプトで実行する方法を知った。

もし、シェルスクリプトの方法があることも知っていれば、コマンド1行で実行できるので、そちらでインストールしたと思う。
そのため、インストール方法は2つあることがわかりやすくなるようにドキュメントを作成した方がいいと思う

https://getcomposer.org/doc/00-intro.md のInstallation - Linux / Unix / OSX# - Downloading the Composer Executable# のあたりみたいな感じ。

**Comment by yinm** [comment]
Following the page of https://getcomposer.org/download/, I executed the command for download and install.
However after finishing the installation, I saw the following description and learned how to install with shell script.

> WARNING: Please do not redistribute the install code. Instead, please link to this page or check how to install Composer programmatically.

Is there any reason to recommend the PHP command at the beginning of the page at https://getcomposer.org/download/ ?
If it is the same as a shell script, I think that documents should be created easier to understand that there are two installation methods.
If I have a shell script installation method, I can do it with one command line, so I think that I installed it there.

**Comment by yinm** [comment]
Composerのインストール方法は2つある。
* PHP command https://getcomposer.org/download/
* Shell Script https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

ただ、PHPコマンドの方が目立っているため、シェルスクリプトの方法が見つけにくい。
インストール方法が2つあることをわかりやすくした方が、ユーザーがやりやすいインストール方法を選択できるようになっていいと思う。

**Comment by yinm** [comment]
The way of install Composer
* to use the PHP command  (link: https://getcomposer.org/download/)
* to use Shell Script (link: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md)

However, the way of to use Shell Script is difficult to find, because the way of to use the PHP command.
I think that it makes it easier for users to understand that there are two installation methods, so that users can choose the installation method that is easier for users to do.

**Comment by koic** [comment]
お疲れ様でした :shipit:
