### ISSUE TITLE
OSS Gate Workshop: 東京：2017-01-28: commitjoy:poi: Work log

### ISSUE THREAD

**Issue by commitjoy** [oss-gate/workshop#239]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.
h
Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by hiroyuki-sato** [comment]
よろしくお願いします。

**Comment by commitjoy** [comment]
よろしくお願いいたします。

**Comment by commitjoy** [comment]
まずは、ドキュメントを探す。
jakarta poiで検索。

**Comment by commitjoy** [comment]
URLはhttps://poi.apache.org/

**Comment by commitjoy** [comment]
ドキュメントとソースを眺めたくてアーカイブをダウンロードしたくて、downloadをリンクした
https://poi.apache.org/download.html

**Comment by commitjoy** [comment]
拡張子がzipだったので、ダウンロードの対象らしきものを見つけたが、本当にそれでいいのかがわからなかった。
beta1というのも気になった。
本当はリリース版が欲しい。
poi-bin-3.16-beta1-20161120.zip

**Comment by commitjoy** [comment]
さっきのはバイナリだったので、ソースを落としたい。
下記を見つけた。
poi-src-3.16-beta1-20161120.zip

**Comment by commitjoy** [comment]
ドキュメントがトップページのどこにあるのかわからなかった。
jakarta poi ドキュメントで検索
下記のページを見つけた。
http://www.javadrive.jp/poi/install/index4.html

**Comment by commitjoy** [comment]
とりあえずリリース版のソースのアーカイブを探す
下記がそれっぽい。
落として中身を見てみる。
poi-src-3.15-20160924.zip

**Comment by commitjoy** [comment]
下記をダウンロードした。中身を見てみる。
http://ftp.jaist.ac.jp/pub/apache/poi/release/src/poi-src-3.15-20160924.zip

**Comment by commitjoy** [comment]
対象のOSSの過去の変更履歴を知ることも重要だと教えていただいた
poiは何でバージョン管理をしているのか探してみる
下記で検索apatch poi subversion
poiはgithubでバージョン管理しているらしい
https://github.com/apache/poi

**Comment by commitjoy** [comment]
https://github.com/apache/poiはミラーのサイトらしい
mirrored from git://git.apache.org/poi.git
git://git.apache.org/poi.gitで検索してみる

**Comment by commitjoy** [comment]
下記のページにソースコードのリポジトリについての記載があった
https://poi.apache.org/subversion.html

**Comment by commitjoy** [comment]
poiはsubversionでバージョン管理しているが、gitでもダウンロードできるようになっている。
下記日本語訳

バージョン管理されたソースコード
ASF Subversion、リポジトリへの接続に関する一般的な情報については、 バージョン管理ページを参照してください。

Apache POIはSubversionをバージョン管理システムとして使用しますが、読み取り専用のgitミラーも備えています

注 ：サブバージョンを使用してサブプロジェクトをチェックアウトするときは、スパースチェックアウトを実行するか、トランクまたは単一のブランチまたはタグをチェックアウトして、ハードディスクをいっぱいにして帯域幅を無駄にしないようにします。

最新のApache POIコードへの読み取り専用アクセスについては、 https://svn.apache.org/repos/asf/poi/trunk/を使用してください。
ウェブブラウザでsvnリポジトリを参照するには、ViewVCを使用してください
コミッターではないが、パッチを提出したり、コミット権を要求したりする場合は、 寄稿ガイドラインを参照してください。

gitでダウンロードしたい人対象にgitに定期的にミラーリングしているとのこと

**Comment by commitjoy** [comment]
上記ページの寄稿ガイドラインを参照してみた。
ソースをコミットするのに、どのようなフローでするのかがわからなかった。
（コンパイルも通らないようなソースをコミットされたりしたら困るはずなので、誰か承認するような人がいるのかとか）

**Comment by commitjoy** [comment]
poi ソース コミットで検索
githubでもコミットできるらしい
http://www.ne.jp/asahi/hishidama/home/tech/apache/poi/build.html

**Comment by yyamano** [comment]
ふりかえりました。

**Comment by commitjoy** [comment]
下記サイトにgitのミラーに対してプルリクエストができるということが書いてある。
http://www.ne.jp/asahi/hishidama/home/tech/apache/poi/build.html
しかしpoiのサイトに記載がなければ本当にできるのかがわからないので、調べてみる。

**Comment by hiroyuki-sato** [comment]
* プロジェクトのホームページはどこですか？URL
* プロジェクトはどのようなどのようなツールを使ってソースコード管理をしていますか？、それは一つですか？複数ですか？
* プロジェクトのソースコード管理のURLを記載してください。
* プロジェクトのユーザ同士が交流するメーリングリストのようなものはありますか？
* 最近他の人が行ったフィードバックはありますか？
* 最近他の人が行ったフィードバックでメンテナが取り込みを行ったものはありますか？

**Comment by commitjoy** [comment]
- プロジェクトのホームページはどこですか？URL
　→https://poi.apache.org/
- プロジェクトはどのようなどのようなツールを使ってソースコード管理をしていますか？、それは一つですか？複数ですか？
　→Subversionを使ってソースコード管理をしています。gitでもプルリクエストをできるように、ミラーリングをしています。
- プロジェクトのソースコード管理のURLを記載してください。
　→https://svn.apache.org/repos/asf/poi/trunk/src/
　→https://github.com/apache/poi/tree/trunk/src
　→git://git.apache.org/poi.git
- プロジェクトのユーザ同士が交流するメーリングリストのようなものはありますか？
　→https://lists.apache.org/list.html?dev@poi.apache.org
　→https://lists.apache.org/list.html?user@poi.apache.org
　→https://lists.apache.org/list.html?general@poi.apache.org
- 最近他の人が行ったフィードバックはありますか？
　→16時間前に行ったフィードバックがあります。
　　Added fullwidth character to WorkbookUtil.validateSheetName
- 最近他の人が行ったフィードバックでメンテナが取り込みを行ったものはありますか？
　→下記が1ヶ月くらい前にとりこまれました。
　　update java doc for CellStyle#setDataFormat

**Comment by commitjoy** [comment]
下記をフィードバックしようと思います。
バイナリとソースの正式版ダウンロードのリンクは一番上にあったほうがよい。
正式版ソースをダウンロードしようとしたら、beta版が一番上にあったので、beta版しかないと思った。
一般的にbeta版より正式版をダウンロードしたい人が多いと思うので、正式版のリンクは一番上にあって、beta版はその下にあるほうが良いと思った。
※報告するメーリングリストが違う場合は、指摘をしてください。

**Comment by satoryu** [comment]
ふりかえりました。

**Comment by knokmki612** [comment]
おつかれさまでした！
クローズされていても、引き続きメモすることはできますので、よかったらどうぞ！
