### ISSUE TITLE
OSS Gateワークショップ2016-03-26: 進め方

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#24]
次回、須藤が進行役をしなくても進められるように、2016-03-26での進め方をメモしておく。

**Comment by kou** [comment]
開始前（10:00-10:35）：参加者の開発OSS決め

参加者ごとに開発対象のOSSを決める。

  * まず、参加者にこのワークショップの概要を説明する。
    * 概要は「実際に『OSSの開発に参加する』を経験するワークショップ」でよい。
  * 開発に参加するためには「OSS」を決める必要がある、と説明する。
  * 開発対象にするOSSは「難易度」ではなく、その人に「関係があるか」を重視して選ぶ。
    * 例：普段使っているOSS。
    * 例：使っていてうまく動かないところがある（改良したいところがある）OSS。
    * 例：開発に参加したいOSS。
    * まずは、参加者自身に「普段使っているOSSはなんですか？」と聞く。
    * そこで上がったOSSの中からやりたいものが見つかればそれにする。
    * 参加者によっては「OSSを使っていること」を自覚していない場合もある。その場合は、普段コンピューターで何をしているかを聞き、その中であがってきたソフトウェアの中でOSSのものを「それも実はOSSですよ！」と教えながら話を聞いていく。そうすると開発対象に適切なOSSが見つかるはず。

**Comment by kou** [comment]
アイスブレイク（10:40-10:50）

scenario.mdの「アイスブレイク」にある通り、「参加者・メンターそれぞれ同じテーブルの人たちに自分がどうしてOSS Gateに関わっているかを話す」ことをして、今日相談しやすい雰囲気を作る。

**Comment by kou** [comment]
会場説明（10:50-10:53）

川原さんに会場について他を説明してもらった。

**Comment by kou** [comment]
作業ログissueを作成（10:53-11:00）

[2016-01-30の作業ログissueテンプレート](https://github.com/oss-gate/workshop/issues/4)をコピペして日付を置換して[2016-03-26用の作業ログissueテンプレート](https://github.com/oss-gate/workshop/issues/16)を作成する。

各参加者には、作業ログissueテンプレートを使って自分の作業ログissueを作ってもらう。

進行役は、メンターの人から各参加者が作業ログissueを作ったかどうかを教えてもらう。作業ログissueができたら次へ進む。

**Comment by kou** [comment]
メモ：作業ログissueの作成は次回はissueテンプレート機能を使うのを試してみるとよさそう。参考： #26

**Comment by kou** [comment]
OSS開発手順を説明（11:00-11:10）

scenario.mdにある通り、「参加者がどうやってOSS開発に着手すればよいかわかること」を目的としてOSS開発手順を説明する。

手順は[スライド](http://slide.rabbit-shocker.org/authors/kou/oss-gate-workshop-tutorial-overview/)（[ソース](https://github.com/oss-gate/workshop/tree/master/tutorial/overview)）を使って説明する。

（スライドには説明しなくてもよい内容が残っているので削除しておこう。）

**Comment by kou** [comment]
この時間の作業で大事なところは次の点である。

  * 作業をしている中で思ったこと・考えたことは作業ログに残す。
  * 特に、詰まったところは作業ログに残す。
  * 解決策はこの時間では考えなくてもよい。後で考える時間は用意してあるから。（説明することを忘れた。）
    * どうして詰まったか、どうして自分はピンとこなかったか、わからなかったか、ということはメモしておく。いま残しておかないと後で忘れちゃうから。忘れてしまうと解決策も考えられない。
  * メンターは教えないこと！教えるんじゃなくて一緒に考える、一緒にやること。

**Comment by kou** [comment]
開発対象OSSを動かす（11:10-12:05）

scenario.mdにある通り、各参加者は、それぞれ開発対象にしたOSSをドキュメントにしたがってインストール・チュートリアルの実行を進める。

メンターは教えないこと！一緒に考える・一緒にやること！

**Comment by kou** [comment]
ミニふりかえり（12:05-12:15）

各参加者は、午前中の作業ログをもとにメンターに自分が作業した作業を説明し、メンターからフィードバックをもらう。

説明をするメンターは違うグループのメンター（作業を見てないメンター）にする。メンターには、時計回りに島を移動して、違うグループの参加者に対して説明を聞いてフィードバックをしてもらった。

**Comment by kou** [comment]
昼休み（12:20-13:20）

グループ（ビギナー+メンター）ごとにお昼ごはんを食べに行く。

**Comment by kou** [comment]
フィードバック（13:20-13:30）

scenario.mdでは、午前中の続きをする（開発対象OSSを動かす）ことになっているが、インストールは全員終わっている、動作確認は終わっている人もいる、という状態だったので、フィードバックの説明を先にして、作業メモissueに溜まったうまくいかなかったことを開発元に報告することにした。

作業メモissueに溜まったうまくいかなかったことをすべて報告し終わったら、動作確認作業を続けることにした。

**Comment by kou** [comment]
前回も午後はすぐにフィードバックにした気がするので、いつも、午後はすぐにフィードバックでもいいかもしれない。

**Comment by kou** [comment]
ふりかえり（16:00-16:15）

各参加者は、一日の作業ログをもとにメンターに自分が作業した作業を説明し、メンターからフィードバックをもらう。

説明をするメンターは違うグループのメンター（作業を見てないメンター）にする。メンターには、半時計回り（午前中の最後は時計回りだったから逆まわり）に島を移動して、違うグループの参加者に対して説明を聞いてフィードバックをしてもらった。

**Comment by kou** [comment]
まとめ（16:20-16:25）

scenario.mdにある通り、[スライド](http://slide.rabbit-shocker.org/authors/kou/oss-gate-workshop-tutorial-conclusion/)（[ソース](https://github.com/oss-gate/workshop/blob/master/tutorial/conclusion/next-step.rab)）このワークショップのまとめをした。

**Comment by kou** [comment]
@y-goto 進行役をやる人の参考になるといいなぁと思ってまとめたものです。必要なら活用してください！

**Comment by y-goto** [comment]
ありがとうございます。
ところで、一つ質問なのですが、いつも最後にアンケートを行っていますが、あれ、どういうものをお使いなのでしょう？@kou

**Comment by kou** [comment]
#28 のことですよね？
よくわかっていないんですが、Googleのサービスを使っています。最初に @sezemiadmin が作ってくれたフォームをコピーして書き換えたものが #28 です。権限管理とかは私はよくわかっていないので @sezemiadmin にフォローしてもらうのがよさそうです！

**Comment by kou** [comment]
あ、そうそう、もし、事前に当日の進行の相談をした方がよさそうなら https://gitter.im/oss-gate/general を活用するのがよいかもしれません。

**Comment by sezemiadmin** [comment]
@y-goto @kou 遅くなりました。。スイマセン。アンケートはGoogle Formを使っていて、↓がその場所です。
Googleアカウントがあれば編集できます(編集権限を変更しました)
[OSS_Gateのアンケートのフォルダ](https://drive.google.com/folderview?id=0B8Opxnj2eaANeWczVXRlaTBVMEU&usp=sharing)

**Comment by y-goto** [comment]
なるほどー！
ありがとうございます。勉強になります。
では少し触って慣れてみます。
