### ISSUE TITLE
OSS Gate Workshop: 東京:2017- 01-28:YuiOmata:pg: Work log

### ISSUE THREAD

**Issue by YuiOmata** [oss-gate/workshop#240]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by koic** [comment]
今日はよろしくお願いします。

**Comment by YuiOmata** [comment]
googleで公式サイトを検索
"postglesql" -> 本体のサイトが出てきた
"rails pg" -> https://rubygems.org/gems/pg/versions/0.18.4

-> Homeリンク　 -> https://bitbucket.org/ged/ruby-pg/wiki/Home

**Comment by YuiOmata** [comment]
インストール手順が書いてあった

**Comment by YuiOmata** [comment]
$ gem install pg

Building native extensions.  This could take a while...
Successfully installed pg-0.19.0
Parsing documentation for pg-0.19.0
Installing ri documentation for pg-0.19.0
Done installing documentation for pg after 3 seconds
1 gem installed

インストール成功

**Comment by YuiOmata** [comment]
googleで　pg_config　検索

**Comment by YuiOmata** [comment]
http://bitarts.jp/blog/archives/004171.html がヒット
/usr/pgsql-9.2/bin　にあるらしい

-> ない

**Comment by YuiOmata** [comment]
document https://deveiate.org/code/pg/

**Comment by YuiOmata** [comment]
ドキュメントの読み方
先にざっくり全体像をつかむ
何のためのライブラリなのか
どうやって使うのか

**Comment by YuiOmata** [comment]
https://bitbucket.org/ged/ruby-pg/wiki/Home と
https://github.com/ged/ruby-pg
で動作環境の説明が違う。

home :ruby 2.0->mirror : ruby 2.2

**Comment by YuiOmata** [comment]
サンプルコード動かしてみる

**Comment by YuiOmata** [comment]
作業ディレクトリ ~/projects/lessons/oss-gate

**Comment by YuiOmata** [comment]
$ ruby sample.rb
/Users/yui/.rvm/gems/ruby-2.3.1/gems/pg-0.19.0/lib/pg.rb:45:in `initialize': could not connect to server: No such file or directory (PG::ConnectionBad)
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
	from /Users/yui/.rvm/gems/ruby-2.3.1/gems/pg-0.19.0/lib/pg.rb:45:in `new'
	from /Users/yui/.rvm/gems/ruby-2.3.1/gems/pg-0.19.0/lib/pg.rb:45:in `connect'
	from sample.rb:4:in `<main>'

**Comment by YuiOmata** [comment]
ｐｇに接続できないらしい

**Comment by YuiOmata** [comment]
pgのサーバを立てる

**Comment by YuiOmata** [comment]
google検索　psql サーバ　ローカル
http://www.dbonline.jp/postgresql/connect/index2.html

**Comment by YuiOmata** [comment]
google検索　postgresql 使い方　mac
http://qiita.com/_daisuke/items/13996621cf51f835494b

**Comment by YuiOmata** [comment]
$ initdb /usr/local/var/postgres -E utf8
The files belonging to this database system will be owned by user "yui".
This user must also own the server process.

The database cluster will be initialized with locale "ja_JP.UTF-8".
initdb: could not find suitable text search configuration for locale "ja_JP.UTF-8"
The default text search configuration will be set to "simple".

Data page checksums are disabled.

initdb: directory "/usr/local/var/postgres" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/usr/local/var/postgres" or run initdb
with an argument other than "/usr/local/var/postgres".

**Comment by YuiOmata** [comment]
$ postgres -D /usr/local/var/postgres
FATAL:  could not open directory "pg_tblspc": No such file or directory

**Comment by YuiOmata** [comment]
$ ls /usr/local/var/postgres
PG_VERSION            global/               pg_hba.conf           pg_multixact/         pg_subtrans/          postgresql.auto.conf  postmaster.opts
base/                 pg_clog/              pg_ident.conf         pg_notify/            pg_xlog/              postgresql.conf

**Comment by YuiOmata** [comment]
google検索　pg_tblspc no such file
http://tyano.shelfinc.com/post/101245342268/yosemite-postgresql
$ mkdir pg_tblspc

**Comment by YuiOmata** [comment]
$ postgres -D /usr/local/var/postgres
LOG:  database system was shut down at 2016-06-16 23:12:00 JST
LOG:  creating missing WAL directory "pg_xlog/archive_status"
FATAL:  could not open directory "pg_replslot": No such file or directory
LOG:  startup process (PID 5662) exited with exit code 1
LOG:  aborting startup due to startup process failure

**Comment by YuiOmata** [comment]
動いたー

**Comment by YuiOmata** [comment]
動いてない

**Comment by YuiOmata** [comment]
様々ディレクトリがない。。
pg_replslot　pg_twophase　pg_commit_ts

**Comment by YuiOmata** [comment]
公式サイト見ることにした！https://www.postgresql.org/

**Comment by YuiOmata** [comment]
Download -> Mac oSX

**Comment by YuiOmata** [comment]
homebew でインストールしたのでhttp://braumeister.org/formula/postgresqlをかくにん

**Comment by YuiOmata** [comment]
brew uninstall postgresql
brew install postgresql

**Comment by YuiOmata** [comment]
インストール後の手順がドキュメントに書いてあると嬉しい

**Comment by YuiOmata** [comment]
==> Installing postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.6.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring postgresql-9.6.1.el_capitan.bottle.tar.gz
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.0) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/upgrading.html

To migrate existing data from a previous minor version (9.0-9.5) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/pgupgrade.html

  You will need your previous PostgreSQL installation from brew to perform `pg_upgrade`.
  Do not run `brew cleanup postgresql` until you have performed the migration.

To have launchd start postgresql now and restart at login:
  brew services start postgresql
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgres start
==> Summary
🍺  /usr/local/Cellar/postgresql/9.6.1: 3,242 files, 36.4M

**Comment by y-goto** [comment]
コメントしました

**Comment by YuiOmata** [comment]
伝えたいこと

ホームページとgithubで推奨環境において、ruby のバージョンの表記が違う
具体的には、
ホームページでの表記2.0以降
mirror (github)での表記2.2
CIでは2.2 2.3でテストしている
gemspecでは2.0以上

**Comment by YuiOmata** [comment]
# 編集

(PRへのコメントであることが前提)

## タイトル　
2.2”以上”という表記を追記した

## 本文
以下の点がわかっていない。
リポジトリから推測される2.0以上と読み取れるものと、2.2以上と読み取れるものが混在している。
具体例
 - bitbucket(README): Ruby 2.0 or newer  
 - github(README): Ruby 2.2  
 - .travis.yml: Ruby 2.2, 2.3.0でテストを実行  
 - pg.gemspec: 2.0.0以上でテストを実行

**Comment by YuiOmata** [comment]
#英語に変更

**Comment by knokmki612** [comment]
フィードバックできましたね！

**Comment by treby** [comment]
お疲れ様でした！
