### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-01-28: RossyWhite: elasticsearch-ruby: Work log

### ISSUE THREAD

**Issue by RossyWhite** [oss-gate/workshop#241]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by y-goto** [comment]
よろしく

**Comment by RossyWhite** [comment]
インストールする方法を調べるために,elasticsearch-dslのreadmeを読む。

**Comment by RossyWhite** [comment]
readmeにインストールのコマンドがあったので、それを実行してみる。

```
gem install elasticsearch-dsl
```
と打てばインストールできた

**Comment by RossyWhite** [comment]
google で 'elasticsearch ruby'で検索しても、
'elasticsearch-dsl'はいきなり出てこない事に気づく。

**Comment by RossyWhite** [comment]
'elasticsearch-ruby'
というのがトップで出てくるが、その中にディレクトリがいくつかあって、
'elasticsearch-dsl'はその中の一つ。

他にも色々あり、使い分けがイマイチ解りにくい。

**Comment by RossyWhite** [comment]
とりあえず、
先に本体の'elasticsearch-ruby'のreadmeを読もうと思う。

**Comment by RossyWhite** [comment]
railsで使いたい場合は、
'elasticsearch-rails'を使えとかいてある。

何が違うんだろう？

**Comment by RossyWhite** [comment]
とりあえずusage通りにやってみようと思う。

**Comment by RossyWhite** [comment]
初めて使ってみるひとの目線で考えて、
トップのREADMEを読んだときに、
似たような名前のモジュールが多くて、
どれを最初に使い始めて良いか分かりづらい。

できれば、最初はインストールして、簡単なクエリを投げるところまでは
さっとできると嬉しいと思った。

**Comment by RossyWhite** [comment]
クエリ投げたいと思っていて、
それで考えると、elasticsearch-apiを開けば良さげな気がしたけど、
下の方に、elasticsearch-dslというのもあって、こっちもapiを提供してるらしく、
どっちを開けば良いか悩む。

**Comment by RossyWhite** [comment]
apiの方を読んでみて、dslの方も読んでみた結果、
結局単独で使うことはマイナーケースで、rubyの方を入れておけば良い事が分かった。

**Comment by RossyWhite** [comment]
dslのreadmeを見れば、
クエリの詳細を設定できる事はわかるのだが、
「そもそも、データをどうやって入れるのか」という疑問が発生する。

**Comment by RossyWhite** [comment]
「そもそも、データをどうやって入れるのか」
という疑問は、elasticsearch-api のUsageを読みなおしたら書いてあった。

```
require 'elasticsearch'

client = Elasticsearch::Client.new log: true

client.index  index: 'myindex', type: 'mytype', id: 1, body: { title: 'Test' }
# => {"_index"=>"myindex", ... "created"=>true}

client.search index: 'myindex', body: { query: { match: { title: 'test' } } }
# => {"took"=>2, ..., "hits"=>{"total":5, ...}}
```

とりあえず、これが一番簡単なサンプルなのかな？

**Comment by RossyWhite** [comment]
上のコード実行したらなんかとりあえず、それっぽい結果が返ってきた

```
2017-01-28 12:12:00 +0900: PUT http://localhost:9200/myindex/mytype/1 [status:200, request:0.102s, query:n/a]
2017-01-28 12:12:00 +0900: > {"title":"Test"}
2017-01-28 12:12:00 +0900: < {"_index":"myindex","_type":"mytype","_id":"1","_version":3,"_shards":{"total":2,"successful":1,"failed":0},"created":false}
2017-01-28 12:12:00 +0900: GET http://localhost:9200/myindex/_search [status:200, request:0.013s, query:0.008s]
2017-01-28 12:12:00 +0900: > {"query":{"match":{"title":"test"}}}
2017-01-28 12:12:00 +0900: < {"took":8,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":0.30685282,"hits":[{"_index":"myindex","_type":"mytype","_id":"1","_score":0.30685282,"_source":{"title":"Test"}}]}}
```

**Comment by colorbox** [comment]
#### リポジトリの切り分けがわかりにくい
```
For integration with Ruby models and Rails applications, see the elasticsearch-rails project.
```

という書き方がわかりにくい点は、リポジトリに対するフィードバックになりうるかもしれませんね。

#### 検索について
リポジトリを直接探すのであれば、googleを使うよりもgithubで直接検索するほうが良いかもしれませんね。

**Comment by RossyWhite** [comment]
Hello,

today, I want to use Elasticsearch in ruby. this is first experience for me. so, I read [README](https://github.com/elastic/elasticsearch-ruby#elasticsearch).

However I couldn't find which gem I should use,
elasticsearch-ruby or elasticsearch-rails.

Is there any difference betweeen using elasticsearch-ruby and elasticsearch-rails?

please tell me each use-case respectively.

bye

**Comment by hiroyuki-sato** [comment]
フィードバックしました。
お疲れ様でした。

**Comment by knokmki612** [comment]
おつかれさまでした！
クローズされていても、引き続きメモすることはできますので、よかったらどうぞ！
