### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-02-20: kozy4324: freeCodeCamp: Work log

### ISSUE THREAD

**Issue by kozy4324** [oss-gate/workshop#259]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by youchan** [comment]
よろしくお願いします！

**Comment by kozy4324** [comment]
よろしくお願いします！ 😃

**Comment by kozy4324** [comment]
こいつを動かします
https://github.com/freeCodeCamp/freeCodeCamp

**Comment by kozy4324** [comment]
public なサービスはこいつ
https://www.freecodecamp.com/

**Comment by kozy4324** [comment]
docker-compose ファイルが存在するのですぐ動くもんだと思っています。
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/docker-compose.yml

ドキュメントはこれからちょっと漁ります。

**Comment by youchan** [comment]
ドキュメントがみつからなかったら、既存のissueやpull requestがないかも見てみましょう。

**Comment by kozy4324** [comment]
docker-compose ファイルにあるコメントの通りにコマンド実行して動かしてみる
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/docker-compose.yml#L4-L5

**Comment by kozy4324** [comment]
その前に clone !
```
$ git clone https://github.com/freeCodeCamp/freeCodeCamp.git
```

**Comment by kozy4324** [comment]
Prerequisites の説明発見
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#contribution-guidelines

**Comment by kozy4324** [comment]
ローカルのセットアップはこれっぽい。
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#setup-freecodecamp

Dockerでのセットアップは？ 🤔

**Comment by kozy4324** [comment]
コメントにある Bootstrap コマンドを打つ。

```
$ docker-compose run --rm server npm install
$ docker-compose run --rm server npm run only-once
```

**Comment by kozy4324** [comment]
2つ目のコマンドでエラー 🙈 

```
express-session deprecated req.secret; provide secret option server/middlewares/sessions.js:23:39
strong-remoting deprecated The built-in CORS middleware provided by REST adapter was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. node_modules/strong-remoting/lib/remote-objects.js:97:25
loopback-explorer deprecated The built-in CORS middleware provided by loopback-component-explorer was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. server/boot/explorer.js:22:3
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/fcc/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/fcc/node_modules/passport-facebook/lib/strategy.js:54:18)
    at PassportConfigurator.configureProvider (/fcc/node_modules/loopback-component-passport/lib/passport-configurator.js:252:18)
    at /fcc/server/component-passport.js:104:18
    at Array.map (native)
    at setupPassport (/fcc/server/component-passport.js:101:34)
    at Object.<anonymous> (/fcc/server/server.js:47:1)
    at Module._compile (module.js:541:32)
    at loader (/fcc/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/fcc/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/fcc/seed/index.js:10:11)

npm info lifecycle freecodecamp@0.1.0~only-once: Failed to exec only-once script
npm ERR! Linux 4.9.8-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "only-once"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 only-once: `npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 only-once script 'npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /fcc/npm-debug.log
```

**Comment by kozy4324** [comment]
`OAuth2Strategy` でサーチ、それっぽい以下 Issue が見つかった。
https://github.com/freeCodeCamp/freeCodeCamp/issues/4682

**Comment by kozy4324** [comment]
↑の Issue はアテが外れた。他のサーチ結果を漁る。
https://github.com/freeCodeCamp/freeCodeCamp/search?q=OAuth2Strategy&type=Issues&utf8=%E2%9C%93

**Comment by kozy4324** [comment]
`clientID` でサーチ。設定ファイル系がくさい。
https://github.com/freeCodeCamp/freeCodeCamp/search?q=clientID&type=Code&utf8=%E2%9C%93

`process.env.` から値引っ張っているぽい、

```
clientID: process.env.GITHUB_ID,
```

ので、 `.env` ファイルあたりが怪しい。
`.evn` ファイルはローカル環境で動かすドキュメント内に言及あった。
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#setup-freecodecamp

これでローカルで事前にコピーしておく。
```
cp sample.env .env
```

ローカルのカレントディレクトリがコンテナの `/fcc` にマウントされるっぽい。
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/docker-compose.yml#L22

**Comment by kozy4324** [comment]
`.env` をコピーして再実行。

```
$ docker-compose run --rm server npm run only-once

:
/****/
Seeding Completed
/****/
npm info lifecycle freecodecamp@0.1.0~postonly-once: freecodecamp@0.1.0
npm info ok 
```

正常終了 🤘

**Comment by youchan** [comment]
👏 👏 👏

**Comment by kozy4324** [comment]
実行コマンドを実行してみる。

```
$ docker-compose up
```

動いているっぽい 🎊

**Comment by kozy4324** [comment]
動いたけど、盛大に画面崩れしてる 🙈 
![image](https://cloud.githubusercontent.com/assets/170064/23123921/c5a4e78e-f7ad-11e6-9796-488b33e63f80.png)


FYI: キャプチャのChrome拡張はこれ。
https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl

**Comment by kozy4324** [comment]
DevTool コンソールにもエラー
![image](https://cloud.githubusercontent.com/assets/170064/23123954/e725b172-f7ad-11e6-8629-96e8f76dd380.png)

**Comment by kozy4324** [comment]
Webpackとか使っているので、そこらへんの準備必要？
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/package.json#L165

**Comment by kozy4324** [comment]
ローカルのセットアップを確認すると、
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#setup-freecodecamp

```
$ bower install
```

は docker-compose.yml ではやっていないっぽい。

**Comment by kozy4324** [comment]
とりあえず `$ bower install` 実行。それらしくインストールされた。
再度、 `$ docker-compose up` で確認。
状況変わらず 🙉

**Comment by kozy4324** [comment]
`docker-compose up` で何が動いているの？

- MongoDB → 素の MongoDB コンテナなので、 mongod のプロセスが動いているだけだろう
- Server → `npm start` しているっぽい

**Comment by kozy4324** [comment]
docker-compose の情報が少ない & ローカルで動かす情報のほうが多いので、方針変更で、まずはローカルから動かしてみる。

**Comment by kozy4324** [comment]
コンテナ側で `npm start` じゃなくて、 `gulp` で動かしてみる（ドキュメントに `gulp` で動かせの記述あり）

docker-compose.yml を修正して、
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 0c80d45..36e26aa 100755
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -22,7 +22,6 @@ services:
             - .:/fcc
         working_dir: /fcc
         command:
-            - npm
-            - start
+            - gulp
         ports:
             - "3000:3000" # Change port if needed
```

実行。

```
$ docker-compose up
Starting freecodecamp_db_1
Recreating freecodecamp_server_1

ERROR: for server  Cannot start service server: oci runtime error: container_linux.go:247: starting container process caused "exec: \"gulp\": executable file not found in $PATH"
ERROR: Encountered errors while bringing up the project.
```

動かん。

**Comment by kozy4324** [comment]
コンテナ側に gulp インストールしてみる。
```
$ docker-compose run --rm server npm install -g gulp
```

が同様に動かない、というかコンテナ側に gulp 入らない...

**Comment by kozy4324** [comment]
一旦、 Docker ではなく、ローカルで動かしてみる方向でがんばる。

**Comment by changeworld** [comment]
🐱 < ふりかえりしました。Dockerでの起動手順がないのを追加するのは、よいコントリビュートポイントだと思います。

**Comment by tricknotes** [comment]
おつかれさまでした！よかったら次回はメンターで参加してみてください！
