### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-02-20: ninoseki: uirusu: Work log

### ISSUE THREAD

**Issue by ninoseki** [oss-gate/workshop#260]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by ebihara99999** [comment]
よろしくお願いします！

**Comment by ninoseki** [comment]
* Reameは読了
* テストを動かすが、Skipされるテストケースあり

**Comment by ninoseki** [comment]
* TODO: Test方法を追記する

**Comment by ninoseki** [comment]
Skipされたテストケースを探し始める

**Comment by ninoseki** [comment]
Skipされるテストケースがあるテストファイルが判明

**Comment by ninoseki** [comment]
* Skipを除去してテストを走らせる
* こけたメソッド: VTUrlTest#test_return_additional_info_for_url_google_com

**Comment by ninoseki** [comment]
* こけてた原因: PublicではないAPI Key(Private API Key?)を設定していないため

**Comment by ebihara99999** [comment]
[上記URL](https://github.com/oss-gate/workshop/issues/260)は、Private API keyの取得方法の調査のためのURL

**Comment by ninoseki** [comment]
* https://www.virustotal.com/ja/documentation/private-api/#
 * Getting StartedにPrivate API Keyの取得方法の記述あり

**Comment by ninoseki** [comment]
* https://www.virustotal.com/ja/about/contact/
  * リクエストを行うことで、Private API Keyを取得できる模様

**Comment by ninoseki** [comment]
For ongoing information about our activity follow VirusTotal's blog. Also, feel free to contact us with service questions, media requests, bug reports and any other inquiry that you may have. This is also the place to ask for further information about premium services and privileged access to VirusTotal resources.

The following form is equivalent to writing an e-mail to contact@virustotal.com, some subject suggestions have been embedded in the corresponding drop down list, do not hesitate to contact us regarding any other subject that may consider relevant.

**Comment by ninoseki** [comment]
* テストケースではHTTPレスポンスのモックを用意していない様子

**Comment by ninoseki** [comment]
* HTTPレスポンスをモック化してテストが実行できるようにしたい
  * Private API Keyが必要なテストケースも同様

**Comment by ninoseki** [comment]
* 困ること
  * テストの度に実際にHTTPレスポンスを送ると、クライアント/サーバーともに負荷がかかる
  * 再現性(日によってウイルスの検知結果に差が出る可能性があり、常に同じHTTPレスポンスが帰ってくるとは限らないはず)に疑問符がつく
  * サーバー側が落ちているとテストができない
  * サーバーが落ちている場合の挙動のテストができない(現状はないはず)

**Comment by ninoseki** [comment]
* 上記の内容をIssue化する作業に着手

**Comment by ninoseki** [comment]
* Contributeの方法はリポジトリ上に非明記

**Comment by ebihara99999** [comment]
receives

**Comment by ninoseki** [comment]
# There is no mocks of HTTP response in test cases.
## Problem
* Cannot test if the server-side is down
* Cannot test cases when the server-side is down
* No guarantee that responses are same(such as virus detection numbers)
* Servicer receives unnecessary load.

**Comment by ebihara99999** [comment]
* いつもプロダクト使ってます。ありがとう。
* もしよければ直します。

**Comment by koic** [comment]
テストコードの在り方について、モックを使う方針にしたいという意思が明確なようなので、PR を出すことを前提に ISSUE でお伺いを立ててから出すというのは良いと思います。

**Comment by koic** [comment]
↑PR はこうあるのが正しいという意思も入っているので、そういった形でいきなり PR を出すことを不安に思う場合 :ok_man:

**Comment by koic** [comment]
私もそういった ISSUE を立てたことあります。
https://github.com/rsim/oracle-enhanced/issues/1027

**Comment by tricknotes** [comment]
おつかれさまでした！よかったら次回はメンターで参加してみてください！
