### ISSUE TITLE
issue template の一番上に issue のタイトルのテンプレが入っていたほうがよさそう

### ISSUE THREAD

**Issue by mtsmfm** [oss-gate/workshop#264]
スクロールした先にしかタイトルのテンプレが見えなかったので、最初から見えたほうがいいなぁと思いました。

**Comment by knokmki612** [comment]
私もそのほうが見やすいと思います！
https://github.com/oss-gate/retrospective/issues に書いておくと残りやすいです！

**Comment by mtsmfm** [comment]
つづきは https://github.com/oss-gate/retrospective/issues/37 で

**Comment by mtsmfm** [comment]
@knokmki612 指摘あざます、移しておきました!
