### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-02-20: takayuki-f: NumPy: Work log

### ISSUE THREAD

**Issue by takayuki-f** [oss-gate/workshop#265]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by koic** [comment]
よろしくお願いします！

**Comment by takayuki-f** [comment]
googleでNumpyと検索
公式っぽいのが出てきた
http://www.numpy.org/

**Comment by takayuki-f** [comment]
公式ページで使い方を確認

**Comment by takayuki-f** [comment]
チュートリアル見つけた
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

**Comment by takayuki-f** [comment]
exampleを書いてみる

**Comment by takayuki-f** [comment]
ドキュメントを確認しながらexampleを進める

**Comment by takayuki-f** [comment]
レファレンスの検索できないので探したいwordが見つからない

**Comment by takayuki-f** [comment]
インストール手順から確認しなおしてみる

**Comment by takayuki-f** [comment]
shape
配列の要素数？

**Comment by takayuki-f** [comment]
```python
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> a.ndim
2
```

返却値の内容がわからない

**Comment by takayuki-f** [comment]
ドキュメントの場合
```python
>>> a.dtype.name
'int64'
```

自分のPCの場合
```python
>>> a.dtype.name
'int32'
```

環境によって挙動が違う

**Comment by takayuki-f** [comment]
```python
>>> a.itemsize
8

>>> a.itemsize
4
```
これも違ってた

**Comment by takayuki-f** [comment]
探してみたら見つかった

ndarray.flags	Information about the memory layout of the array.
ndarray.shape	Tuple of array dimensions.
ndarray.strides	Tuple of bytes to step in each dimension when traversing an array.
ndarray.ndim	Number of array dimensions.
ndarray.data	Python buffer object pointing to the start of the array’s data.
ndarray.size	Number of elements in the array.
ndarray.itemsize	Length of one array element in bytes.
ndarray.nbytes	Total bytes consumed by the elements of the array.
ndarray.base	Base object if memory is from some other object.

**Comment by takayuki-f** [comment]
>>> a = np.array(1,2,3,4)    # WRONG
>>> a = np.array([1,2,3,4])  # RIGHT

WRONGのケースの何が悪いのか分からなかったので打ってみたらこうなった
>>> a = np.array(1,2,3,4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: only 2 non-keyword arguments accepted

**Comment by takayuki-f** [comment]
>>> np.ones((2,3,4), dtype=np.int16)
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

2パターンの出力があった

**Comment by takayuki-f** [comment]
これも出力結果が違う

ドキュメント
```
>>> np.empty( (2,3) )                                 # uninitialized, output may vary
array([[  3.73603959e-262,   6.02658058e-154,   6.55490914e-260],
       [  5.30498948e-313,   3.14673309e-307,   1.00000000e+000]])
```

自分のPC
```
>>> np.empty((2, 3))
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
```

**Comment by takayuki-f** [comment]
rangeの使い方

```python
>>> np.arange(10,30,5)
array([10, 15, 20, 25])
```

**Comment by takayuki-f** [comment]
```
>>> a = np.arange(6)
>>> a
array([0, 1, 2, 3, 4, 5])
>>> print(a)
[0 1 2 3 4 5]
```

printで出力すると通常のリストで表示される

**Comment by takayuki-f** [comment]
```
>>> b = np.arange(12).reshape(3, 4)
>>> b
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
>>>
>>> b.sum()
66
>>> b.sum(axis=0)
array([12, 15, 18, 21])
```

パラメータのaxisは列みたい

**Comment by ebihara99999** [comment]
お疲れ様でした！確認しました。

**Comment by tricknotes** [comment]
おつかれさまでした！よかったら次回はメンターで参加してみてください！
