### ISSUE TITLE
OSS Gate Workshop:Osaka:2017-02-25:daddygongon:hiki:Work log

### ISSUE THREAD

**Issue by daddygongon** [oss-gate/workshop#283]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by iderihatakeshi** [comment]
よろしくお願いします。

**Comment by daddygongon** [comment]
ありがうございます．よろしくお願いします．

**Comment by daddygongon** [comment]
hikiwiki.orgが死んでた．hiki　front pageでライセンス確認，GPL2
https://opensource.org/licenses
https://opensource.org/licenses/alphabetical
GNU General Public License version 2 (GPL-2.0)

**Comment by daddygongon** [comment]
hiki/hikiから
bob% mkdir tmp
[bob:~/Sites] bob% cd tmp
[bob:~/Sites/tmp] bob% git clone git@github.com:hiki/hiki.git

**Comment by daddygongon** [comment]
sudo emacs /etc/apache2/users/bob.conf

<Directory "/Users/bob/Sites/tmp/hiki">
    DirectoryIndex hiki.cgi
    Options MultiViews ExecCGI Indexes FollowSymLinks SymLinksIfOwnerMatch
    AddHandler cgi-script .cgi .rb

   AllowOverride None
   Order allow,deny
   Allow from all

</Directory>
 bob% sudo apachectl restart

**Comment by daddygongon** [comment]
open -a safari http://localhost/~bob/tmp/hiki

**Comment by daddygongon** [comment]
memoのいみふ

**Comment by daddygongon** [comment]
```text
bob% mv dot.htaccess .htaccess
bob% mv data ..
[bob:~/Sites/tmp/hiki] bob% ls ..
data/ hiki/
bob% chmod -R og+w ../data
bob% mv hikiconf.rb.sample hikiconf.rb
```

**Comment by daddygongon** [comment]
bob% rackup
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop
open localhost:9292だと見えた．
でも，apache経由の
open localhost://~bob/tmp/hik
だと
cannot load such file -- sequel (LoadError)

**Comment by daddygongon** [comment]
bob% /usr/bin/env ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]

bob% diff hiki.cgi ~/Sites/new_ist/hiki.cgi 
0a1
> #!/usr/local/opt/ruby/bin/ruby
2a4
> $LOAD_PATH.unshift "lib"

16c18
<   $:.unshift( org_path.untaint, "#{org_path.untaint}/lib" )
---
>   $:.unshift( org_path.untaint, "#{org_path.untaint}/hiki" )

**Comment by daddygongon** [comment]
bob% open http://localhost/~bob/tmp/hiki

**Comment by daddygongon** [comment]
$LOAD_PATH.unshift "lib"
$:.unshift( org_path.untaint, "#{org_path.untaint}/hiki" )
どちらも
Hiki Error

cannot load such file -- sequel (LoadError)
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by daddygongon** [comment]
hikiでcgi errorがでた．safariを再起動すると見えた．

**Comment by daddygongon** [comment]
bob% gem list sequel

*** LOCAL GEMS ***

sequel (4.36.0, 4.35.0)

**Comment by daddygongon** [comment]
Hiki Errorcannot load such file -- sequel (LoadError)で検索
Qiitaを見た．Hikiをお引越し - Qiita
http://qiita.com/saruo@github/items/4a1122953e7a1511a42e

**Comment by daddygongon** [comment]
/etc/apache2/users/bob.confを修正
<     Options FollowSymLinks ExecCGI
<     Options -MultiViews 
---
>     Options MultiViews ExecCGI Indexes FollowSymLinks SymLinksIfOwnerMatch
>     AddHandler cgi-script .cgi .rb
でもだめ．

**Comment by daddygongon** [comment]
bob% ls lib/hiki/storage/rdb.rb 
lib/hiki/storage/rdb.rb

**Comment by yoichi** [comment]
説明聞かせてもらいました。ありがとうございます。
ちょっと違いで動いている比較対象があるので答えにたどり着くのはそう遠くない気がするのですが、あとちょっとのところが難しいですね。。。

**Comment by daddygongon** [comment]
反応が遅れて申し訳ありません．最新版のmasterをgit cloneして動かそうとしましたが，失敗しました．rackupでは立ち上がりますが，apache経由でのaccessで失敗します．やり方が間違っているのかもしれません．

http://hikiwiki.orgが反応しないので，http://hikiwiki.org/ja/install.htmlの手順に従ってやってみました．
OS X(10.11.6)で/Users/bob/Sites/tmp/hikiに展開して，手順どおりやっています．
そのdirectoryからrackupで立ち上げると立ち上がります．
一方，/etc/apache/users/bob.confを以下の通り直しています．
```
<Directory /Users/bob/Sites/tmp/hiki>
    DirectoryIndex hiki.cgi
    Options FollowSymLinks ExecCGI
    Options -MultiViews 
   AllowOverride None
   Order allow,deny
   Allow from all

</Directory>
```
ですが，
 bob% sudo apachectl restart
 
 
```
 Hiki Error
 bob% open http://localhost/~bob/tmp/hiki
でsafariをopenすると
cannot load such file -- sequel (LoadError)
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/lib/hiki/storage/rdb.rb:4:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/lib/hiki/storage.rb:12:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/lib/hiki/config.rb:16:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/hiki.cgi:21:in `<main>'
```
とのエラーで動きません．なにか間違いがあればご指摘ください．

**Comment by daddygongon** [comment]
反応が遅れて申し訳ありません．最新版のmasterをgit cloneして動かそうとしましたが，失敗しました．rackupでは立ち上がりますが，apache経由でのaccessで失敗します．やり方が間違っているのかもしれません．なにか間違いがあればご指摘ください．


http://hikiwiki.orgが反応しないので，
http://hikiwiki.org/ja/install.html
の手順に従ってやってみました．
OS X(10.11.6)で/Users/bob/Sites/tmp/hikiに展開して，手順どおりやっています．
そのdirectoryからrackupで立ち上げると立ち上がります．
一方，/etc/apache/users/bob.confを以下の通り直しています．
```
<Directory /Users/bob/Sites/tmp/hiki>
    DirectoryIndex hiki.cgi
    Options FollowSymLinks ExecCGI
    Options -MultiViews 
   AllowOverride None
   Order allow,deny
   Allow from all

</Directory>
```
ですが，
 bob% sudo apachectl restart
 bob% open http://localhost/~bob/tmp/hiki
 
```
 Hiki Error
 bob% open http://localhost/~bob/tmp/hiki
でsafariをopenすると
cannot load such file -- sequel (LoadError)
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/lib/hiki/storage/rdb.rb:4:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/lib/hiki/storage.rb:12:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/lib/hiki/config.rb:16:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/bob/Sites/tmp/hiki/hiki.cgi:21:in `<main>'
```
とのエラーで動きません．なにか間違いがあればご指摘ください．

sequelですが，
bob% gem list sequel

*** LOCAL GEMS ***

sequel (4.43.0, 4.36.0, 4.35.0)
のとおり入っています．

**Comment by ogom** [comment]
メンターです。よろしくお願いします。

**Comment by daddygongon** [comment]
hiki.cgiのshibangですが，
 #!/usr/bin/env ruby
 #!/usr/local/opt/ruby/bin/ruby
で，上だとエラーが出て，下だとFrontPageまででます．

OSXのlocalでの動かせるように起動をかけています．OSXのapacheでは_wwwでの起動になっており，．．．

再度pull reqへ投げる予定です．

**Comment by ogom** [comment]
エラーの再現方法と解決方法まで issue に登録できていすごいです。 😄

**Comment by daddygongon** [comment]
Okkezさんから返答ありました．
 cgi やめれるならやめた方がいいかも。passenger とか使うのがいいのではないでしょうか。
でした．試したんですが．．．

**Comment by daddygongon** [comment]
Passenger試してみました．うまくいきかけたようですが，他のエラーで死んでいます．
```
/etc/apache2/users/bob.confの設定は，
PassengerEnabled on
PassengerFriendlyErrorPages on

<Location /~bob/hiki>
    PassengerAppRoot /Users/bob/Sites/tmp/hiki
    PassengerBaseURI /~bob/hiki
</Location>
<Directory /Users/bob/Sites/tmp/hiki>
    DirectoryIndex hiki.cgi
    Options FollowSymLinks ExecCGI
    Options -MultiViews

   AllowOverride None
   Order allow,deny
   Allow from all

</Directory>
```
です．

 open http://localhost/~bob/hiki
としたところ，
 You're seeing this error because you use Rack::ShowExceptions.
として，
```
Encoding::CompatibilityError at /~bob/hiki/
incompatible character encodings: US-ASCII and UTF-8

Ruby	layout.html: in concat, line 14
Web	GET localhost/~bob/hiki/
Jump to:
GETPOSTCookiesENV
Traceback (innermost first)

layout.html: in concat
layout.html: in render_layout
/Users/bob/Sites/tmp/hiki/lib/hiki/page.rb: in to_html
      __send__(layout_method_name){ __send__(content_method_name) }...
```
となっています．

元に戻して，OSXではapacheが_wwwで実行されるので，そちらで叩いてみても，

bob% sudo -s -u _www
bash:[_www@bob 2017-02-25-osaka]$ whoami
_www
bash:[_www@bob 2017-02-25-osaka]$ /usr/bin/env ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
bash:[_www@bob 2017-02-25-osaka]$ /usr/bin/env irb
irb(main):001:0> require 'sequel'
=> true
irb(main):002:0> exit

と正常にsequel入っているようです．

やはりこちらの環境のせいでしょうか．他のマシンで試してみます．

**Comment by kou** [comment]
お疲れ様でした！
次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
