### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-02-25: cm-nishida-masayuki: carrierwave-direct: Work log

### ISSUE THREAD

**Issue by cm-nishida-masayuki** [oss-gate/workshop#285]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by ogom** [comment]
メンターです。よろしくお願いします。

**Comment by cm-nishida-masayuki** [comment]
githubみつけたよ！

https://github.com/dwilkie/carrierwave_direct

**Comment by cm-nishida-masayuki** [comment]
installation みつけたよ！

https://github.com/carrierwaveuploader/carrierwave#installation

**Comment by cm-nishida-masayuki** [comment]
Pluginだから単体で動かない。OSSにコントリビュートするのにどこまで動作確認するんだろう。RSpecだけとかでやる？全部用意して動かす？

**Comment by cm-nishida-masayuki** [comment]
とりあえず Rails いれてみよう！

**Comment by cm-nishida-masayuki** [comment]
`rails new ossgate` でRails newしたよ！

**Comment by cm-nishida-masayuki** [comment]
`gem 'carrierwave', '~> 1.0'` を Gemfile追加したよ！

**Comment by cm-nishida-masayuki** [comment]
Model無しで使うためにstore_dir をコメントあうとしたよ！

**Comment by cm-nishida-masayuki** [comment]
Fileアップロード場所がわからなかったけど、publicの下に置いておけば、ローカルで動かしてるときに、そのままホストされるのでできるとうひらめき

圧倒的閃き

**Comment by cm-nishida-masayuki** [comment]
Carrierwaveが動いたので、carrierwave_direct にすすむよ！

**Comment by cm-nishida-masayuki** [comment]
s3にバケットつくったよ！

**Comment by cm-nishida-masayuki** [comment]
`N Such fog`

**Comment by cm-nishida-masayuki** [comment]
Intellijに慣れすぎて保存わすれてた

**Comment by cm-nishida-masayuki** [comment]
UserModelいるじゃん

**Comment by springkuma** [comment]
面白くていいなぁ、コメントが 😄

**Comment by springkuma** [comment]
最初、なにするかの目的が書いてあったらもっとよかったかもしれません！

**Comment by cm-nishida-masayuki** [comment]
@springkuma フィードバックあざます！

**Comment by cm-nishida-masayuki** [comment]
やりたかったこと

- 保存するとs3のkeyが長くなる問題を解決したい(path/file => path/path/file)
- AWSのcredentialを指定するのに key と secret をコンフィグに書かなくても良いようにしたい
- validationがおかしくて、ほとんど通らないので直したい

**Comment by cm-nishida-masayuki** [comment]
既にissueが上がってないか確認

- s3key 長い問題 => [あった2013年物](https://github.com/dwilkie/carrierwave_direct/issues/118)
- credential問題 => [これでもいけそう？](https://github.com/dwilkie/carrierwave_direct/issues/208)
- validationおかしい問題 => [ちかいのがあった2016年](https://github.com/dwilkie/carrierwave_direct/issues/202)

**Comment by cm-nishida-masayuki** [comment]
- credential問題 => これでもいけそう？
これについてフィードバックしませう

aws-sdkをそのまま使うと、`access_key_id`と`secret_access_key`を指定しなくてもプロファイルからとってくるので、その機能を利用してほしいです！

**Comment by cm-nishida-masayuki** [comment]
iam role で認証をできるようにしてほしい。

Using IAM role credential to authenticate AWS

Because Uploading `config/initializers/carriearwave`  is possible to be Security Incident.
it is popular accident.

**Comment by yoichi** [comment]
この機能あると嬉しい人結構居そうと思いました！すばらしい。

**Comment by kou** [comment]
お疲れ様でした！
次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
