### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-02-25: masayuki14: rabbit: Work log

### ISSUE THREAD

**Issue by masayuki14** [oss-gate/workshop#288]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by znz** [comment]
メンターです！よろしくお願いします！

**Comment by masayuki14** [comment]
rabbitにしよう。
検索する。
https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=active&q=rabbit&*

**Comment by masayuki14** [comment]
3番目にあった。うさぎに注意。

Rabbit - はじめに https://rabbit-shocker.org/ja/

**Comment by masayuki14** [comment]
インストールページへのリンクをたどる。


> インストール方法
>
> [インストールページ](https://rabbit-shocker.org/ja/install/)で説明しています。

**Comment by masayuki14** [comment]
ヘッダにもあった。

**Comment by masayuki14** [comment]
Homebrewでもインストールできるようだが、めんどくさそう。
`gem` を使ってインストールをする。

```
gemを使う方法

% gem install rabbit
% gem install rabbiter # Twitter関連機能を利用する場合
```

**Comment by znz** [comment]
Homebrew で入るのは依存しているライブラリということを説明した。
説明がわかりにくいということでフィードバックのチャンス?

**Comment by masayuki14** [comment]
作業用のディレクトリを作る。

 `$ mkdir oss-gate`

**Comment by masayuki14** [comment]
`bundler` を使ってインストールをする。

```sh
$ bundle init    # Gemfile ができる
$ vim Gemfile    # 編集する


$ cat Gemfile
# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem "rabbit"
```

インストールにはけっこう時間がかかります。

**Comment by masayuki14** [comment]
いまのうちにライセンスを確認しよう。

ヘッダの[開発](https://rabbit-shocker.org/ja/development.html) から移動。
ページにはライセンスの表示がない！
のでGitHubページへ移る。

https://github.com/rabbit-shocker/rabbit/

**Comment by masayuki14** [comment]
**COPYING** どのライセンスを使っているか、が書かれたファイル。
> GPLv2 or later. See 'GPL' file about GPLv2.

**GPL** がライセンス

**Comment by masayuki14** [comment]
**README.md** にはサイトのホームページがかかれていた。
初めて見たぺーじだった。
http://rabbit-shocker.org/
Google検索結果は **はじめに** のぺーじだった！

**Comment by masayuki14** [comment]
ヘッダの [使い方](http://rabbit-shocker.org/ja/usage.html) へ移動。
概要とリンクがいくつかあるけれど、次はどこを見ればよいのか・・・？
とりあえず [rabbitコマンドの使い方](http://rabbit-shocker.org/ja/usage/rabbit.html) を見る。

**Comment by masayuki14** [comment]
> コマンドライン
> コマンドラインから起動する場合は引数にスライドを書いたファイ ルを指定してください。
> % rabbit XXX.rd
> 例えば、sample/rabbit-implementation.rdを使うには、トップの ディレクトリで以下のようにします。
> % rabbit sample/rabbit-implementation.rd

`XXX.rd` も `sample/rabbit-implementation.rd` も持ってないよ！動かせない！

**Comment by masayuki14** [comment]
`.rd` ってなに？わからない。
ヘッダの[作り方](http://rabbit-shocker.org/ja/how-to-make/) を見てみよう。

**Comment by masayuki14** [comment]
スライドの作り方に [RD形式でのスライドの作り方](http://rabbit-shocker.org/ja/how-to-make/rd.html) がある。
たぶんこれが `.rd` の正体だろう。みてみよう。

**Comment by masayuki14** [comment]
> サンプルスライドにサンプルがあります。
を辿ってサンプルページをひらく。

http://rabbit-shocker.org/ja/sample/ -> http://rabbit-shocker.org/ja/sample/rd/rabbit.html

ながい！情報量が多い！

**Comment by masayuki14** [comment]
> 基本的に[RD](http://rabbit-shocker.org/ja/rd.html)の書式を使いますが

のリンクを開く。PODってなに？難しそう。
慣れてきたら書き方のリファレンスとして使えそうではある。

**Comment by masayuki14** [comment]
[スライドの作り方](http://rabbit-shocker.org/ja/how-to-make/rd.html) のページに戻る。

**Comment by znz** [comment]
(横で同じページを見ていたら [RDとは何かのページの脚注1](https://rabbit-shocker.org/ja/rd.html#foottext-1) の[リンク先](http://www.ueda.info.waseda.ac.jp/~igarashi/ruby/xml.html#rubyapi2)がなくなっていることに気づいた。)

**Comment by masayuki14** [comment]
最初の **ページ** のところのサンプルをコピペして `page.rd` を作る。

```sh
$ cat <<END > page.rd
= タイトル

なにか

...

= 次のページ

...
END
```

**Comment by masayuki14** [comment]
うごかすぞ。

```sh
$ bundle exec rabbit page.rd
```

うごいたー。

![2017-02-25 14 59 12](https://cloud.githubusercontent.com/assets/2756405/23328672/0d33dab8-fb6b-11e6-87ae-adafe96419b2.png)
![2017-02-25 14 59 23](https://cloud.githubusercontent.com/assets/2756405/23328673/0d371160-fb6b-11e6-9f8f-f23060652e7e.png)

**Comment by masayuki14** [comment]
次はこのスライドを何らかの形式で出力したい。
さて。

**Comment by masayuki14** [comment]
[使い方](http://rabbit-shocker.org/ja/usage.html) ページをもう一度見る。

[rabbit-slideコマンドの使い方](http://rabbit-shocker.org/ja/usage/rabbit-slide.html) にスライドっかいてあるから書いてあるかな？

**Comment by masayuki14** [comment]
> rabbit-slideはスライドの雛形を生成するコマンドです。

ちがうか？
とりあえずスクロールしてざっとみてみる。

**PDF生成** の項目を発見！！ 😄

**Comment by masayuki14** [comment]
> rake pdfでPDFを生成できます。

!!!

```sh
$ bundle exec rake pdf                                                                       [workspace/tmp/oss-gate 15:05:57]
bundler: failed to load command: rake (/Users/morisaki/.rvm/rubies/ruby-2.3.3/bin/rake)
Gem::Exception: can't find executable rake
  /Users/morisaki/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:407:in `block in replace_bin_path'
  /Users/morisaki/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:433:in `block in replace_bin_path'
  /Users/morisaki/.rvm/rubies/ruby-2.3.3/bin/rake:22:in `<top (required)>'
```

できないじゃないか！👿

**Comment by masayuki14** [comment]
`rabbit` コマンドのマニュアルをみようかな。

```
$ bundle exec man rabbit
No manual entry for rabbit
```

oops 😢

**Comment by masayuki14** [comment]
じゃヘルプはどうだ？

```
$ bundle exec rabbit --help
```

たくさん出てきた。

**Comment by kou** [comment]
なるほど！

**Comment by masayuki14** [comment]
`less` でひらいて `output` で検索してみるといくつかオプションを発見。

**Comment by yabuki** [comment]
quick startのドキュメントに改善の余地があるね。

**Comment by masayuki14** [comment]
- インストールして動かしてスライドが見れるまでのクイックスタートガイドがほしい。
- スライドのサンプルテキストがすぐ動かせる
- `bundler` を使ってインストールする方法がある
- `rabbit` コマンドの input と output  がわからない。
- `XXX.rd` が何なのか。
- **動いた！** の手応えを得られるまでがたいへん。

**Comment by masayuki14** [comment]
初めてRabbitを試す時に早い段階で **動いた** の手応えがほしいですが、
そこにたどり着くまでに1時間ほどかかってしまいました。
[rabbitコマンドの使い方](https://rabbit-shocker.org/ja/usage/rabbit.html) の
`% rabbit XXX.rd`の `XXX.rd`の簡単な中身があると、そのファイルを作ってすぐに動かしてスライドが表示できそうです。

たとえばこのような `XXX.rd` の例があると良いと思います。
```text
= 発表のタイトル

: author
   須藤功平
: institution
   COZMIXNG

= 1ページ目

ここは内容

= 2ページ目

おしまい
```

GitHubに[サンプルRD](https://raw.githubusercontent.com/rabbit-shocker/rabbit/master/sample/rabbit.rd)がありURL指定でコマンドが実行できるので

```
% rabbit https://raw.githubusercontent.com/rabbit-shocker/rabbit/master/sample/rabbit.rd
```

これも合わせて記載があると多くの情報がえられます。

**Comment by masayuki14** [comment]
Issueの報告先を探す。

[開発](http://rabbit-shocker.org/ja/development.html)ページをひらくと

>ご意見ご要望不具合報告等は作者へのメール、メーリングリスト（メーリング リストについてはユーザーページを見てください）、 [GitHubの Issues](https://github.com/rabbit-shocker/rabbit/issues)をご利用く ださい。

とある。

**Comment by masayuki14** [comment]
既存の Issues を見てみる。

https://github.com/rabbit-shocker/rabbit/issues/92
日本語でのIssueがあるので日本語でも大丈夫そうだ。

**Comment by springaki** [comment]
こんにちは。メンターの Aki です。

####  一日全体ふりかえり
- 先週rabbit 使ったばっかりでしかも 作者の須藤さん来ててビックリですね。更に メンター にRubyコミッターの znzさんでびっくり !
- 不安とか迷いがコメントに残ってるのがすごくいいと思います !! これから そのOSSを使う人も同じ悩みやモヤモヤを抱えるかもしれないので、よい改善ポイントになると思います ✨ 
- 同じく rabbit を使い始める人の悩みを抱える人を減らせるとてもいい Issue でしたね。次はこの内容を Pull Request にできるともっと良くなりそうです !
- 更にこのプロダクトに対する感謝の一言があれば、OSS作者の方々も「あぁ、自分達の活動が人の役に立ってて、さらにこの人はこのOSSを良くしようとしてくれてるんだなぁ」という気持ちが伝わっていいなぁと思いました。

**Comment by masayuki14** [comment]
ありがとうございます 😆

**Comment by masayuki14** [comment]
Issueに報告しました 😁  バンザーイ 🙌 
https://github.com/rabbit-shocker/rabbit/issues/104

**Comment by znz** [comment]
[RDの説明のページ](http://rabbit-shocker.org/ja/rd.html) に出てくる POD というのは多分 Perl の [Plain Old Documentation](https://ja.wikipedia.org/wiki/Plain_Old_Documentation) のことだと思います。

**Comment by kou** [comment]
お疲れ様でした！
引き続きOSSの開発を継続していていいですね！

次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
