### ISSUE TITLE
OSS Gate Workshop: OSAKA: 2017-02-25: YuuSakaguchi:standardnotes Work log

### ISSUE THREAD

**Issue by YuuSakaguchi** [oss-gate/workshop#290]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by tshkh8** [comment]
メンターです！よろしくお願いします。

**Comment by YuuSakaguchi** [comment]
Standard notes のサイト
https://standardnotes.org/

**Comment by YuuSakaguchi** [comment]
プログラムの種別が分かれている

Getting Started

**Comment by YuuSakaguchi** [comment]
github のwebを確認する

https://github.com/standardnotes/web

**Comment by YuuSakaguchi** [comment]
web をclone

git clone https://github.com/standardnotes/web.git

**Comment by YuuSakaguchi** [comment]
bundle install

**Comment by YuuSakaguchi** [comment]
npm install

**Comment by YuuSakaguchi** [comment]
bundle exec rake bower:install

**Comment by YuuSakaguchi** [comment]
grunt

**Comment by YuuSakaguchi** [comment]
readme(手順)

Running locally
6. rails s

**Comment by YuuSakaguchi** [comment]
動作確認
http://localhost:3000

**Comment by YuuSakaguchi** [comment]
使い方がわからないので、操作マニュアルを探す
下記の項目は、webのアプリが動いてしまう！

https://standardnotes.org/
Getting Started

**Comment by YuuSakaguchi** [comment]
検索しても見つからず

Standard Notes manual oss

**Comment by YuuSakaguchi** [comment]
ライセンス

License
Licensed under the GPLv3: http://www.gnu.org/licenses/gpl-3.0.html

**Comment by YuuSakaguchi** [comment]
解説しているサイトを発見

http://gigazine.net/news/20170119-standard-notes/

**Comment by YuuSakaguchi** [comment]
使用方法
webページの左下のaccountからURL(https://n3.standardnotes.org)と
email,passwordをregisterして登録する必要がある

**Comment by YuuSakaguchi** [comment]
登録すると新規メモの作成が可能となる。
ローカルだと登録まえにいじっていたデータが反映された。

**Comment by YuuSakaguchi** [comment]
同じアカウントで本番のサイトにログインする。
本番のサイトもローカルと同期されることを確認

**Comment by YuuSakaguchi** [comment]
アカウントを登録しないままローカルで動作させると、画面には反映されていないが、データは保存されていた

**Comment by YuuSakaguchi** [comment]
左下のhelpを押すと元サイトに飛ぶ

https://standardnotes.org/

**Comment by YuuSakaguchi** [comment]
わかりにくい点をまとめる
・本家のドキュメントが不足している。
　アカウント作成についての記載がない

**Comment by YuuSakaguchi** [comment]
web版

-左下の項目は気づきにくいので、画面キャプチャでアカウントの作成方法の手順をサイトに載せてほしい
-getting startの続きでそれぞれのアプリの使用方法の項目があれば良さそう。
-githubのRunning locallyの最後にある説明に加えて、画面キャプチャーでアカウント登録手順がわかるにしてサイトに載せて欲しい。

**Comment by murajun1978** [comment]
ヘルプのリンク先の説明が不足しているところなどがフィードバックできそうですねー 😄

わかりにくかったことや困ったことは細かく残すと 👍

**Comment by YuuSakaguchi** [comment]
開発者向け
下記のような登録手順をサイトのgetting startの次項目に設けて欲しい。

1.画面左下に、サーバー、メール、パスワードを入力してregisterで新規登録する。
  画面左下のaccountは気づきにくいので、画面キャプチャで箇所がわかるようにして欲しい。

2.次に、設定したメール、パスワードでsign inする。

3.メモを入力すると、反映されるようになる。

**Comment by YuuSakaguchi** [comment]
issue

Getting Startedからwebを開いてメモを登録したが、反映されなかった。
なぜなら、アカウントを作成が必要なことがわからなかったから。
Getting Startedにアカウント作成の手順についても記載して欲しい。

**Comment by YuuSakaguchi** [comment]
1 Getting Startedにアカウント作成の手順についても記載して欲しい。

なぜなら、下記にアカウント作成の手順の記載がないかったから。
https://standardnotes.org/
Getting Started

初めて使用するときにアカウント作成の手順があるほうが親切だと思うから。

**Comment by iderihatakeshi** [comment]
さきほど振り返りしたものです、お疲れ様です！

**Comment by kou** [comment]
お疲れ様でした！
これからも引き続きOSSの開発に参加していきましょう！

次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
