### ISSUE TITLE
OSS Gate Workshop: OSAKA: 2017-2-25: benben643: raspberry-gpio-python: Work log

### ISSUE THREAD

**Issue by benben643** [oss-gate/workshop#291]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by yoichi** [comment]
コメント

**Comment by benben643** [comment]
ライセンスはMITだった！

https://pypi.python.org/pypi/RPi.GPIO

**Comment by benben643** [comment]
pythonは入ってた！

versionは2.7.10だった。

コマンドはpython！

**Comment by benben643** [comment]
このページに2.7で使えるって書いてあるから大丈夫だろう！

https://pypi.python.org/pypi/RPi.GPIO

**Comment by benben643** [comment]
ここも参考見ながらやってみます！

https://tool-lab.com/make/raspberrypi-startup-26/

**Comment by benben643** [comment]
test.pyは動いた！

/Users/username/20170225/test.py

Hello, world!

**Comment by benben643** [comment]
import RPi.GPIO as GPIO

を記入したら下記のエラーが出た！

Traceback (most recent call last):
  File "/Users/xxxxxxx/20170225/test.py", line 2, in <module>
    import RPi.GPIO as GPIO
ImportError: No module named RPi.GPIO

**Comment by benben643** [comment]
ライブラリのインストール方法を探さないと！

**Comment by benben643** [comment]
pipでライブラリをインストールしないと！

**Comment by benben643** [comment]
pipがない！

**Comment by benben643** [comment]
pipを入れよう！

http://qiita.com/zaburo/items/fbdaf6c04151671407db

**Comment by benben643** [comment]
pythonを新しくいれるぞ！

brew install python

```
Error: Could not create /usr/local/Cellar
Check you have permission to write to /usr/local
```

**Comment by benben643** [comment]
ディレクトリがなかったので、ディレクトリを作ってみる！
sudo mkdir /usr/local/Cellar
sudo chown -R xxxxxx /usr/local/Cellar/

**Comment by benben643** [comment]
再度インストールするぞ！

brew install python

**Comment by benben643** [comment]
エラーだ！

```
==> Installing python dependency: readline
==> Downloading http://ftpmirror.gnu.org/readline/readline-6.3.tar.gz
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2a

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "readline--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2af/raw/d6aec221e7369ea152e64c8af83f6b048433dd82/readline-6.3.6.diff
```

**Comment by benben643** [comment]
brewが古い？？

brewを更新しよー！

**Comment by benben643** [comment]
brew updateでエラーだ！

```
/usr/local/.git: Permission denied
```

**Comment by benben643** [comment]
sudo付けたら回避した！

**Comment by benben643** [comment]
またエラーだ！！

```
HEAD is now at 2a45dfd Merge pull request #2161 from reitermarkus/spec-cask
To restore the stashed changes to /usr/local run:
  'cd /usr/local && git stash pop'
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by benben643** [comment]
brew doctorをした！

**Comment by benben643** [comment]
これにしたがってみる

```
Warning: /usr/local is not writable.

You should change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local
```

**Comment by benben643** [comment]
brew updateをする。

反応ないので

sudo brew updateする！

```
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

**Comment by benben643** [comment]
エラーでたので、再度brew updateする！

すると

```
Already up-to-date.
```

**Comment by benben643** [comment]
brew install pythonがうまく終わった！！！

**Comment by benben643** [comment]
which pythonでどこに入ってるかチェック。

```
/usr/local/bin/python
```

**Comment by benben643** [comment]
which pip もはいってるぞ！

```
/usr/local/bin/pip
```

**Comment by benben643** [comment]
pipのパッケージ名を調べる！

**Comment by benben643** [comment]
pip search RPi.GPIO　でライブラリがあるかチェック！

あった！

```
Adafruit-GPIO (1.0.1)       - Library to provide a cross-platform GPIO interface on the Raspberry Pi and
                              Beaglebone Black using the RPi.GPIO and Adafruit_BBIO libraries.
RPi.GPIO-def (0.1.1-alpha)  - Definition library for RPi.GPIO(used for IntelliSense)
fakeRPiGPIO (0.3a0)         - fakeRPiGPIO is a package to simulate the RPi.GPIO package
gpiocrust (1.0.0)           - A pythonic wrapper around RPi.GPIO
GPIOEmu (0.0.3)             - A module simulating the RPi.GPIO module
raspi (0.0.2)               - This module provides some helper functions to use with the Raspberry Pi and the
                              RPi.GPIO.
RPi.GPIO (0.6.3)            - A module to control Raspberry Pi GPIO channels
tingbot-RPIO (0.11)         - Advanced GPIO for the Raspberry Pi. Extends RPi.GPIO with PWM, GPIO interrups, TCP
                              socket interrupts, command line tools and more
RPIO (0.10.0)               - Advanced GPIO for the Raspberry Pi. Extends RPi.GPIO with PWM, GPIO interrups, TCP
                              socket interrupts, command line tools and more
```

**Comment by ogom** [comment]
よろしくお願いします。

**Comment by benben643** [comment]
ありがとうございました！

**Comment by ogom** [comment]
Python のパッケージ管理には easy_install というツールがありました。
pip は  easy_install でもインストールが可能かもしれません。

**Comment by benben643** [comment]
macでpythonのインストールでエラーがでた話

macには最初から`python`は入ってたけど、`pip`がなかったので`brew`で新たに`python`をインストールしようとしたんだけど。。。

```
brew install python

Error: Could not create /usr/local/Cellar
Check you have permission to write to /usr/local
```

この後に`brew doctor`でエラー内容を確認して対応する。

```
Warning: /usr/local is not writable.

You should change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local
```

ディレクトリの所有権をログインユーザに変更すれば、インストール出来た！

`sudo chown -R $(whoami) /usr/local`を実行してやる！

その後に、

`brew update`
`brew install python`

を実行するば、新しく`python`も`/usr/local/bin/`にインストールされ、`pip`も使えるようになった。

`which pip`で`/usr/local/bin/pip`と表示されるので問題なしだ。

**Comment by chimame** [comment]
1日の振り返りをさせて頂きました。ありがとうございました。

**Comment by benben643** [comment]
ありがとうございましたー！

**Comment by yoichi** [comment]
ありがとうございました。
いろいろはまりましたが一個一個解決していく過程が楽しかったです（最後のエラーは乗り越えられませんでしたが。。。）

**Comment by kou** [comment]
お疲れ様でした！
これからも引き続きOSSの開発に参加していきましょう！

次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
