### ISSUE TITLE
OSS Gate Workshop: Osaka:2017-02-25:mou34:faker:Work log

### ISSUE THREAD

**Issue by mou34** [oss-gate/workshop#292]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by yabuki** [comment]
メンターです。よろしく。

**Comment by mou34** [comment]
dbのダミーデータを作りたい
言語はrubyがいい
ググったらfakerってやつが出てきた
https://github.com/stympy/faker

**Comment by mou34** [comment]
ライセンスをみたら大丈夫そう
This code is free to use under the terms of the MIT license.

**Comment by mou34** [comment]
使い方を確認するためにREADMEをみよう

**Comment by mou34** [comment]
インストールについて下記が記載されていた
gem install faker

**Comment by mou34** [comment]
ローカルPCにインストールするのは怖いのでvagrantで仮想環境を立ててそこにインストールする

**Comment by mou34** [comment]
仮想環境がminimalのcentosだったのでまずruby環境を整える
```
sudo yum -y install openssl-devel readline-devel zlib-devel libcurl-devel
sudo yum install git
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
source ~/.bash_profile
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
cd ~/.rbenv/plugins/ruby-build
sudo ./install.sh
rbenv install 2.3.1
rbenv rehash
rbenv global 2.3.1
```

**Comment by mou34** [comment]
上記の手順はruby install centosでググってわかりやすそうだったので[ここ](http://qiita.com/Fendo181/items/d14ebfb148223c8e5ecb)を参照

**Comment by mou34** [comment]
本家を確認するほうがよかったか？

**Comment by mou34** [comment]
パッケージでインストールできたらもっといいのに

**Comment by mou34** [comment]
仮想環境へのインストールが時間がかかっていたのでローカル環境にインストールする。
アンインストールはgem uninstallでいける。[参考ページ](http://qiita.com/muran001/items/14f34b735e0a6b4af98c)

**Comment by mou34** [comment]
公式ページはググった結果１０個目くらい。英語の時点で避けてしまう。。[公式](http://guides.rubygems.org/command-reference/#gem-uninstall)

**Comment by mou34** [comment]
commandで見ることもできる。
`gem help`

**Comment by mou34** [comment]
ブロックは```で、インラインは\`でいける

**Comment by mou34** [comment]
ローカルにインストールする前にログを残したい。
`script oss.log`

**Comment by mou34** [comment]
インストール実施
`gem install faker`

**Comment by mou34** [comment]
稼働確認した
```
require 'Faker'

p Faker::Name.name
```

**Comment by mou34** [comment]
成功
' "Miss Travon Lemke" '

**Comment by mou34** [comment]
ランダムで名前が出るけど日本人名はないのかな？

**Comment by yabuki** [comment]
ruby faker Japanese で検索してみては

**Comment by mou34** [comment]
[これ](https://github.com/tily/ruby-faker-japanese)出ました。日本語もあったんですね

**Comment by mou34** [comment]
ライセンスの確認が必要そう

**Comment by mou34** [comment]
MITっぽいとのことなのでmit Licenseでググる

**Comment by mou34** [comment]
githubに書かれているライセンスの３行ぐらいをグーグル検索に入れると大体それっぽいライセンスが出てくる

**Comment by mou34** [comment]
faker-japaneseの開発が2011年に止まっているので「ライセンスをわかりやすくして」というissueはやめとこう。モヤっとするところを探すため、fakerの[README](https://github.com/stympy/faker/blob/master/README.md#installing)の手順を進めてみよう

**Comment by mou34** [comment]
'p Faker::Internet.email'

**Comment by mou34** [comment]
"camryn.mcglynn@ullrichkling.info"

**Comment by mou34** [comment]
```
irb(main):007:0> Faker::Name.unique.name
=> "Chaim Gaylord"
```

**Comment by mou34** [comment]
日本語が出来るか確認するため、issueでjapanで検索。Add japanese locale file: ja.ymlがあった

**Comment by ShinjiEnoki** [comment]
振り返り、お疲れ様でした！

**Comment by iderihatakeshi** [comment]
１回目の振り返りしたものです、お疲れさまです

**Comment by kou** [comment]
お疲れ様でした！
これからも引き続きOSSの開発に参加していきましょう！

次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
