### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-02-25:mt-u:cognitom/felt:Work log

### ISSUE THREAD

**Issue by mt-u** [oss-gate/workshop#294]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by ShinjiEnoki** [comment]
メンターです。よろしくお願いします！

**Comment by mt-u** [comment]
とりあえずCloneしようかな？

**Comment by mt-u** [comment]
cloneしようとしたら怒られた。

```
$ git clone git@github.com:cognitom/felt.git
Cloning into 'felt'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by mt-u** [comment]
ローカルにキーの登録ができてないからっぽい。
今度入れておきます。

**Comment by mt-u** [comment]
httpsでcloneしよう。

```
$ git clone https://github.com/cognitom/felt.git
Cloning into 'felt'...
remote: Counting objects: 347, done.
remote: Total 347 (delta 0), reused 0 (delta 0), pack-reused 347
Receiving objects: 100% (347/347), 200.81 KiB | 198.00 KiB/s, done.
Resolving deltas: 100% (187/187), done.
Checking connectivity... done.
```

**Comment by mt-u** [comment]
最後に必要になるので、キーをもう登録しておくことにします。

**Comment by mt-u** [comment]
Linux Mintのキーを登録した。

**Comment by mt-u** [comment]
もう一度cloneを試してみる。

**Comment by mt-u** [comment]
成功！
```
$ git clone git@github.com:cognitom/felt.git
Cloning into 'felt'...
remote: Counting objects: 347, done.
remote: Total 347 (delta 0), reused 0 (delta 0), pack-reused 347
Receiving objects: 100% (347/347), 200.81 KiB | 193.00 KiB/s, done.
Resolving deltas: 100% (187/187), done.
Checking connectivity... done.
```

**Comment by mt-u** [comment]
問題の箇所を直したいので、ソースコードを開いてみよう。

**Comment by mt-u** [comment]
その前に、最新でもエラーが起こるか試してみよう。

**Comment by mt-u** [comment]
やっぱりエラーが起きた。
```
$ npm start

> bicu(provisional)@1.0.0 start /{home}/development/test
> felt --config --src src --debug --watch

Error: felt-recipe-minimal is not installed
    at /{home}/development/test/node_modules/felt/bin/index.js:40:13
    at Generator.next (<anonymous>)
    at onFulfilled (/{home}/development/test/node_modules/co/index.js:65:19)

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/{home}/.nodebrew/node/v7.4.0/bin/node" "/{home}/.nodebrew/current/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! bicu(provisional)@1.0.0 start: `felt --config --src src --debug --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bicu(provisional)@1.0.0 start script 'felt --config --src src --debug --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bicu(provisional) package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     felt --config --src src --debug --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bicu(provisional)
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bicu(provisional)
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /{home}/npm-debug.log
```

**Comment by mt-u** [comment]
改めてソースを開こう！

**Comment by mt-u** [comment]
該当箇所はここ
```
 if (!flags.recipe && !flags.config) flags.recipe = 'minimal'

  if (flags.recipe) {
    const pkgName = 'felt-recipe-' + flags.recipe
    try {
      recipe = require(pkgName)
    } catch(err) {
      throw new Error(`${ pkgName } is not installed`)
    }
  }
```
https://github.com/cognitom/felt/blob/master/bin/index.js#L33
ここのチェックがまずい。

**Comment by mt-u** [comment]
今日は時間がないので、違うのにしたいと思います。

**Comment by mt-u** [comment]
cognitom/felt-recipe-riotのissueを英語で出してみよう！

**Comment by mt-u** [comment]
riot3.0系に対応していなかったので、今もそうなのか確かめてみよう。

**Comment by mt-u** [comment]
まず自分のプロジェクトをcloneしてみる。

**Comment by mt-u** [comment]
cloneできた。（プライベートリポジトリなので割愛）

**Comment by mt-u** [comment]
該当のパッケージがうまく動くか試す。

**Comment by mt-u** [comment]
プロジェクトに対象パッケージを組み込みます。
package.jsonをいじっちゃう。

**Comment by mt-u** [comment]
間違えた。
npmでインストールします。

**Comment by mt-u** [comment]
下記でインストールできた。
```
npm install felt-recipe-riot -D
```

**Comment by mt-u** [comment]
package.jsonを確認してみよう。

**Comment by mt-u** [comment]
できてる。
```
  "devDependencies": {
    "felt": "^0.3.2",
    "felt-postcss": "^0.1.0",
    "felt-recipe-riot": "^0.2.1",    ←これ
    "felt-rollup": "^0.1.2",
    "postcss-cssnext": "^2.9.0",
    "postcss-import": "^9.1.0",
    "rollup-plugin-buble": "^0.15.0",
    "rollup-plugin-commonjs": "^7.0.0",
    "rollup-plugin-includepaths": "^0.1.8",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-riot": "^1.1.0"
  },
 ```

**Comment by mt-u** [comment]
動かしてみよう。

**Comment by mt-u** [comment]
怒られた。
```
$ npm start

> bicu(provisional)@1.0.0 start /home/usk/development/test
> felt --config felt.config.js --src src --debug --watch

sh: 1: felt: not found
```

他のやついれてなかった。

**Comment by mt-u** [comment]
じゃー入れちゃいましょう。

**Comment by mt-u** [comment]
できた。
```
$ npm install
```

**Comment by mt-u** [comment]
改めて動かしてみよう。

**Comment by mt-u** [comment]
動いた！
```
$ npm start
```

**Comment by mt-u** [comment]
ブラウザで確認しよう！

**Comment by mt-u** [comment]
自分のアプリにログインしてみる。

**Comment by mt-u** [comment]
ログインできた！

**Comment by mt-u** [comment]
エラーが発生していた箇所を確かめる！

**Comment by mt-u** [comment]
確か、タグ内のスタイルを適用するのができてなかったはず。

**Comment by mt-u** [comment]
あれ？いけてる？

**Comment by mt-u** [comment]
自分のソースを確かめてみよう。

**Comment by mt-u** [comment]
package.jsonを確認したら、該当パッケージを使うようになってない！
```
  "scripts": {
    "start": "felt --config felt.config.js --src src --debug --watch"
  },
```

**Comment by mt-u** [comment]
使うように変更しよう。

**Comment by mt-u** [comment]
こんな感じにしよう！
```
  "scripts": {
    "start": "felt --recipe riot --src src --debug --watch"
  },
```

**Comment by mt-u** [comment]
変更した！
動かし直そう！

**Comment by mt-u** [comment]
あ、エラーが発生！
```
$ npm start

> bicu(provisional)@1.0.0 start /{home}/development/test
> felt --recipe riot --src src --debug --watch

Compiling: main.js
Compiling: scripts/models/services/password.js
Error: Could not resolve 'components/app.tag' from /{home}/development/test/src/main.js
```

**Comment by mt-u** [comment]
自分のやつだととりあえず試せないので、サンプルのプロジェクトを使って試すことにします。

**Comment by mt-u** [comment]
サンプルの紹介ページを検索しよう！

**Comment by chimame** [comment]
振り返りメンターです。
とても丁寧に説明して下さってありがとうございます。

**Comment by mt-u** [comment]
報告のたたきだい
・バージョン0.2.2はriot3.x系に対応していない
・riot3.x系に対応してほしい


なぜ？
・最新のriotが使いたいので
・riotの3.x系は3ヶ月以上前にでているので、そっちがこれからのメイン版かなと

**Comment by mt-u** [comment]
現在のIssueを確認して、同様のやつがないか確認してみた。

**Comment by mt-u** [comment]
同様のやつはなかったので、上げてみよう！

**Comment by mt-u** [comment]
バージョン`0.2.2`ではriot3.xを使うようになっていないようです。
https://github.com/cognitom/felt-recipe-riot/blob/master/package.json#L41

これからriotを使った開発を始める場合は3.x系が多いと考えられるので、feltの公式レシピも対応していただけると嬉しいです。

**Comment by ShinjiEnoki** [comment]
英語でのレポート、書きたいissueに似たようなものがあると、それを真似する手もあるかなと思います

**Comment by mt-u** [comment]
Version `0.2.2` uses Riot `2.X`.
https://github.com/cognitom/felt-recipe-riot/blob/master/package.json#L41

But, Riot's latest version is `3.3.1`. New Riot project will use it or newer.
So, would you like update to using Riot `3.X`?

**Comment by mt-u** [comment]
I want use Riot 3.X

**Comment by mt-u** [comment]
Issueを登録しちゃう！

**Comment by mt-u** [comment]
最新のRiotで動くか試してみる！

**Comment by mt-u** [comment]
サンプルプロジェクトをインストールしてみる。
http://qiita.com/cognitom/items/fedcfe08bf5527e43bcb
https://github.com/cognitom/felt-example-riot/

**Comment by mt-u** [comment]
できた。
```
git clone git@github.com:cognitom/felt-example-riot.git
Cloning into 'felt-example-riot'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
remote: Counting objects: 14, done.
remote: Total 14 (delta 0), reused 0 (delta 0), pack-reused 14
Receiving objects: 100% (14/14), done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
```

**Comment by mt-u** [comment]
必要なパッケージをインストールする。
```
$ npm install
```

**Comment by mt-u** [comment]
とりあえず、feltを動かしてみる。

**Comment by mt-u** [comment]
動いてる！
```
$ npm start
```

**Comment by mt-u** [comment]
3.X系の書き方で動くか試してみる。

**Comment by mt-u** [comment]
ソースコードで3.X系の機能を使ってみよう！

**Comment by mt-u** [comment]
styleタグからタイプ指定をとってみる。

**Comment by mt-u** [comment]
こうなってる。
```
riot$1.tag2('md', '', ':scope { display: block; }', '', function(opts) {
    this.root.innerHTML = opts.content ? marked$1(opts.content) : ''
});
```

**Comment by mt-u** [comment]
本来はこうなるはず。
```
riot$1.tag2('md', '', 'md,[riot-tag="md"],[data-is="md"]{ display: block; }', '', function(opts) {
    this.root.innerHTML = opts.content ? marked$1(opts.content) : ''
});
```

**Comment by mt-u** [comment]
次はRiotの3を使うようにしてみる。

**Comment by mt-u** [comment]
Issueはこれです。
https://github.com/cognitom/felt-recipe-riot/issues/2

**Comment by springkuma** [comment]
わかりやすく説明していただいて、ありがとうございました！
個人的にも内容が興味深かったです。

**Comment by kou** [comment]
お疲れ様でした！
これからも引き続きOSSの開発に参加していきましょう！

次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579
