### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-02-25: nobiki: satis: Work log

### ISSUE THREAD

**Issue by nobiki** [oss-gate/workshop#295]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by springkuma** [comment]
よろしくお願いします！

**Comment by nobiki** [comment]
satisを動かす所までやってみます！

**Comment by springkuma** [comment]
お願いします！
こちらですね。
https://github.com/composer/satis

**Comment by nobiki** [comment]
$ git clone git@github.com:composer/satis

クローン成功

**Comment by nobiki** [comment]
問題になっている、buildの実行箇所を探してみます

**Comment by nobiki** [comment]
https://github.com/composer/satis/blob/master/src/Builder/PackagesBuilder.php

buildクラス

**Comment by nobiki** [comment]
一度、build実行させる環境を作ります

**Comment by nobiki** [comment]
リポジトリを2つ作成

hoge.git
moge.git

**Comment by nobiki** [comment]
nginxを動かして、ブラウザで見れるようにします

**Comment by nobiki** [comment]
gitのhookスクリプトに、satisのbuildを設置します

**Comment by nobiki** [comment]
composerの実行箇所を探してみます

**Comment by nobiki** [comment]
その前に、コンストラクタで実行ユーザを確認

**Comment by nobiki** [comment]
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 250 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: --------- Applicationstring(3) "git"
remote: ---------Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
remote: Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
remote: Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
remote: To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
remote: Scanning packages
remote: Executing command (/repos/git/hoge.git): git show-ref --tags --dereference
remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
remote: Cannot create cache directory /root/.composer/cache/repo/-repos-git-hoge.git/, or directory is not writable. Proceeding without cache
remote: Executing command (/repos/git/hoge.git): git branch --no-color
remote: Executing command (/repos/git/hoge.git): git show 'master':'composer.json'
remote: Executing command (/repos/git/hoge.git): git log -1 --format=%at 'master'
remote: Reading composer.json of nobiki/hoge (master)
remote: Executing command (/repos/git/hoge.git): git show '1aef029ec24b45bc711f6e2e3f5c34e0a463ba70':'composer.json'
remote: Executing command (/repos/git/hoge.git): git log -1 --format=%at '1aef029ec24b45bc711f6e2e3f5c34e0a463ba70'
remote: Importing branch master (dev-master)
remote: Selected nobiki/hoge (dev-master)
remote: abcwrote packages to /repos/satis//include/all$45cfb214651ba00936c1a9a83c52bea7e6c1841c.json
remote: Writing packages.json
remote: Pruning include directories
remote: Deleted /repos/satis//include/all$a7cf0009a26a7397201c1e4133bb39ae1cf66433.json
remote: Writing web view
To git://9zilla-repos-composer/hoge.git
   9faade4..1aef029  master -> master


実行ユーザがgitで、「Cannot create cache directory /root/.composer/cache/files/, or directory is not writable」がエラー出力されているところまで、確認しました

**Comment by nobiki** [comment]
実行ユーザは正しくて、参照先がrootになっている？

**Comment by nobiki** [comment]
これを、調査してみます

**Comment by nobiki** [comment]
function getComposerHome ← これが超あやしい

**Comment by nobiki** [comment]
getenv('COMPOSER_HOME')で、環境変数が無いと、falseがreturnされてる

**Comment by nobiki** [comment]
getComposerHome内で、環境変数COMPOSER_HOMEが無い場合、環境変数HOMEの値が使用されて、"/root"を参照している事を確認

remote: [1][3]string(5) "/root"

**Comment by nobiki** [comment]
git の環境変数を一度確認

**Comment by nobiki** [comment]
ドキュメントを作成

**Comment by nobiki** [comment]
せっかく調べたので、調べた内容を伝えるように、まとめる

**Comment by ShinjiEnoki** [comment]
先ほどはありがとうございました。まとめ、がんばってください！

**Comment by nobiki** [comment]
1.私は、9zilla-repos-composerというDockerコンテナ上にSatisをインストールして使用しています

https://github.com/nobiki/9zilla-repos-composer/blob/master/Dockerfile

2.git daemonのhooksスクリプトとして、satis buildを実行されるようにしました

https://github.com/nobiki/9zilla/blob/master/settings/satis/post-receive

3.実行すると、/root/.composer/cache/files/, or directory is not writableが出力されました。

	Compressing objects: 100% (2/2), done.
	Writing objects: 100% (3/3), 263 bytes | 0 bytes/s, done.
	Total 3 (delta 1), reused 0 (delta 0)
	remote: Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
	remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
	remote: Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
	remote: Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
	remote: To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
	remote: Scanning packages
	remote: Executing command (/repos/git/hoge.git): git show-ref --tags --dereference
	remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
	remote: Cannot create cache directory /root/.composer/cache/repo/-repos-git-hoge.git/, or directory is not writable. Proceeding without cache
	remote: Executing command (/repos/git/hoge.git): git branch --no-color
	remote: Executing command (/repos/git/hoge.git): git show 'master':'composer.json'
	remote: Executing command (/repos/git/hoge.git): git log -1 --format=%at 'master'
	remote: Reading composer.json of nobiki/hoge (master)
	remote: Executing command (/repos/git/hoge.git): git show '4be957c8f9b9e0515a444318e1d54c4dac465cd0':'composer.json'
	remote: Executing command (/repos/git/hoge.git): git log -1 --format=%at '4be957c8f9b9e0515a444318e1d54c4dac465cd0'
	remote: Importing branch master (dev-master)
	remote: Executing command (/repos/git/moge.git): git show-ref --tags --dereference
	remote: Executing command (/repos/git/moge.git): git branch --no-color --no-abbrev -v
	remote: Cannot create cache directory /root/.composer/cache/repo/-repos-git-moge.git/, or directory is not writable. Proceeding without cache
	remote: Executing command (/repos/git/moge.git): git branch --no-color
	remote: Executing command (/repos/git/moge.git): git show 'master':'composer.json'
	remote: Executing command (/repos/git/moge.git): git log -1 --format=%at 'master'
	remote: Reading composer.json of nobiki/moge (master)
	remote: Executing command (/repos/git/moge.git): git show 'edea9b92dbe81b538ac24b7e8b23cc06277b9039':'composer.json'
	remote: Executing command (/repos/git/moge.git): git log -1 --format=%at 'edea9b92dbe81b538ac24b7e8b23cc06277b9039'
	remote: Importing branch master (dev-master)
	remote: Selected nobiki/hoge (dev-master)
	remote: Selected nobiki/moge (dev-master)
	remote: wrote packages to /repos/satis//include/all$e9d823d3205482fe59ffaf000a8934fce5cfce60.json
	remote: Writing packages.json
	remote: Pruning include directories
	remote: Writing web view
	To git://9zilla-repos-composer/hoge.git
	   461ae0b..4be957c  master -> master

3.実行している、git daemonの状態は、下記のようになっています

	~$ docker exec 9zilla-repos-composer ps aux
	USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
	root        18  0.0  0.0  17244  1168 ?        S    14:43   0:00 git daemon --user=git --reuseaddr --export-all --enable=receive-pack --base-path=/repos/git/ --listen=0.0.0.0 --port=9418 /repos/git/
	git         19  0.0  0.1  24680  2380 ?        S    14:43   0:00 git-daemon --user=git --reuseaddr --export-all --enable=receive-pack --base-path=/repos/git/ --listen=0.0.0.0 --port=9418 /repos/git/

4.getComposerHomeを以下のように変更して実行してみました

    private function getComposerHome()
    {
		var_dump(posix_getpwuid(posix_geteuid())['name']);
		var_dump(getenv('COMPOSER_HOME'));
        $home = getenv('COMPOSER_HOME');
        if (!$home) {
            if (defined('PHP_WINDOWS_VERSION_MAJOR')) {
                if (!getenv('APPDATA')) {
                    throw new \RuntimeException('The APPDATA or COMPOSER_HOME environment variable must be set for composer to run correctly');
                }
                $home = strtr(getenv('APPDATA'), '\\', '/') . '/Composer';
            } else {
				var_dump(getenv('HOME'));
                if (!getenv('HOME')) {
                    throw new \RuntimeException('The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly');
                }
                $home = rtrim(getenv('HOME'), '/') . '/.composer';
            }
        }

        return $home;
    }

5.--user=gitを指定していますが、git push時の出力は下記のようになります

	Counting objects: 3, done.
	Delta compression using up to 2 threads.
	Compressing objects: 100% (2/2), done.
	Writing objects: 100% (3/3), 249 bytes | 0 bytes/s, done.
	Total 3 (delta 1), reused 0 (delta 0)
	remote: string(3) "git"
	remote: bool(false)
	remote: string(5) "/root"
	remote: Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
	remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
	remote: Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
	remote: Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json

6.実行ユーザ(--user=git)の、HOMEを参照されるのを期待していましたが、実際には、/rootのHOMEが使用されていて、/root/.composerを参照していました

**Comment by nobiki** [comment]
1. I'm installing and am using Satis on the Docker container as 9zilla-repos-composer.

https://github.com/nobiki/9zilla-repos-composer/blob/master/Dockerfile

2. I decided to carry out satis build as a hooks script of git daemon.

https://github.com/nobiki/9zilla/blob/master/settings/satis/post-receive

3. When executed, / root / .composer / cache / files /, or the directory is not writable, it was output

```
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 263 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
remote: Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
remote: Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
remote: To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
remote: Scanning packages
remote: Executing command (/repos/git/hoge.git): git show-ref --tags --dereference
remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
remote: Cannot create cache directory /root/.composer/cache/repo/-repos-git-hoge.git/, or directory is not writable. Proceeding without cache
remote: Executing command (/repos/git/hoge.git): git branch --no-color
remote: Executing command (/repos/git/hoge.git): git show 'master':'composer.json'
remote: Executing command (/repos/git/hoge.git): git log -1 --format=%at 'master'
remote: Reading composer.json of nobiki/hoge (master)
remote: Executing command (/repos/git/hoge.git): git show '4be957c8f9b9e0515a444318e1d54c4dac465cd0':'composer.json'
remote: Executing command (/repos/git/hoge.git): git log -1 --format=%at '4be957c8f9b9e0515a444318e1d54c4dac465cd0'
remote: Importing branch master (dev-master)
remote: Executing command (/repos/git/moge.git): git show-ref --tags --dereference
remote: Executing command (/repos/git/moge.git): git branch --no-color --no-abbrev -v
remote: Cannot create cache directory /root/.composer/cache/repo/-repos-git-moge.git/, or directory is not writable. Proceeding without cache
remote: Executing command (/repos/git/moge.git): git branch --no-color
remote: Executing command (/repos/git/moge.git): git show 'master':'composer.json'
remote: Executing command (/repos/git/moge.git): git log -1 --format=%at 'master'
remote: Reading composer.json of nobiki/moge (master)
remote: Executing command (/repos/git/moge.git): git show 'edea9b92dbe81b538ac24b7e8b23cc06277b9039':'composer.json'
remote: Executing command (/repos/git/moge.git): git log -1 --format=%at 'edea9b92dbe81b538ac24b7e8b23cc06277b9039'
remote: Importing branch master (dev-master)
remote: Selected nobiki/hoge (dev-master)
remote: Selected nobiki/moge (dev-master)
remote: wrote packages to /repos/satis//include/all$e9d823d3205482fe59ffaf000a8934fce5cfce60.json
remote: Writing packages.json
remote: Pruning include directories
remote: Writing web view
To git://9zilla-repos-composer/hoge.git
   461ae0b..4be957c  master -> master
```

4. The state of git daemon which is being carried out is as follows.

```
~$ docker exec 9zilla-repos-composer ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        18  0.0  0.0  17244  1168 ?        S    14:43   0:00 git daemon --user=git --reuseaddr --export-all --enable=receive-pack --base-path=/repos/git/ --listen=0.0.0.0 --port=9418 /repos/git/
git         19  0.0  0.1  24680  2380 ?        S    14:43   0:00 git-daemon --user=git --reuseaddr --export-all --enable=receive-pack --base-path=/repos/git/ --listen=0.0.0.0 --port=9418 /repos/git/
```

5. getComposerHome was changed and carried out as follows for an investigation.

```
private function getComposerHome()
{
	var_dump(posix_getpwuid(posix_geteuid())['name']);
	var_dump(getenv('COMPOSER_HOME'));
	$home = getenv('COMPOSER_HOME');
	if (!$home) {
		if (defined('PHP_WINDOWS_VERSION_MAJOR')) {
			if (!getenv('APPDATA')) {
				throw new \RuntimeException('The APPDATA or COMPOSER_HOME environment variable must be set for composer to run correctly');
			}
			$home = strtr(getenv('APPDATA'), '\\', '/') . '/Composer';
		} else {
			var_dump(getenv('HOME'));
			if (!getenv('HOME')) {
				throw new \RuntimeException('The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly');
			}
			$home = rtrim(getenv('HOME'), '/') . '/.composer';
		}
	}

	return $home;
}
```

6. --user=git is designated, but output at the time of git push will be as follows.

```
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 249 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: string(3) "git"
remote: bool(false)
remote: string(5) "/root"
remote: Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
remote: Executing command (/repos/git/hoge.git): git branch --no-color --no-abbrev -v
remote: Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
remote: Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
```

7. It was expected that the execution user (--user=git) refers to HOME, but HOME in /root be used actually, and refer to /root/.composer.

**Comment by y-goto** [comment]
お疲れ様でした。
どちらかというと、自分の書いたDockerfileのデバッグみたいになってしまいましたね。
自分のDockerfileがsatisの本サイトが提示しているDockerfileとどう違っているのかを意識されると良いかと思いました。
また、実はまだ本サイトの提示してるDockerfile側に問題がある／ドキュメントがわかりにくいのであれば、pullreqを投げる方向にしても良いかと思います。
