### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-02-25: gh640: Sublime Text のパッケージのどれか: Work log

### ISSUE THREAD

**Issue by gh640** [oss-gate/workshop#296]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by yabuki** [comment]
よろしく、お願いします

**Comment by gh640** [comment]
Sublime Text そのものはインストール済みなので、パッケージを探します。

https://packagecontrol.io/

**Comment by gh640** [comment]
これがよさそう。

PhpDoc
https://github.com/SublimeText/PhpDoc

日本語入力時に、変換するためにエンターキーを押すと変換未確定の日本語が削除されて改行されてしまう問題がある。

**Comment by gh640** [comment]
最近はあまり動きがないので独り言にならないかが心配。

https://github.com/SublimeText/PhpDoc/graphs/contributors

**Comment by gh640** [comment]
オリジナルのリポジトリは動きがないけどフォーク先で進んでいるものはなかろうか。

https://github.com/SublimeText/PhpDoc/network/members

**Comment by gh640** [comment]
本当にこれが問題かどうかがわからないのでいったん置いておきます。

**Comment by gh640** [comment]
次の候補を探しに行きます。

**Comment by gh640** [comment]
対象範囲を拡げて、明らかな問題があるものだけじゃなくて使っててモヤモヤするものも候補として探していきます。

**Comment by gh640** [comment]
Bracket Highlighter がいいのではなかろうか。

https://packagecontrol.io/packages/BracketHighlighter

ブラケットのタイプを追加したいけどできるのかどうかよくわからないので。

**Comment by gh640** [comment]
そもそもできる可能性があるのでドキュメントを見てみます。

http://facelessuser.github.io/BracketHighlighter/

**Comment by yabuki** [comment]
phpdoc 見せてもらいました。

日本語入力ができないのは、issue をあげるのにちょうどいいですね。
ただ、日本語入力ができないというのを、英語で説明するのが難しい
ので、動画を取って、あるべき姿と、現状を表して、コメントを添えて
提出すると日本語をわからない開発者に問題を理解してもらいやすい

**Comment by yabuki** [comment]
日本語を入力できないだけがMajor bugなのか要確認ですね。

**Comment by yabuki** [comment]
forkした所をたどってactiveな人を探すのもあり

**Comment by y-goto** [comment]
説明ありがとうございました。
まずは質問を投げてみるという方向でもよいかと思います。
お話したとおり、似たようなことを試されている方が他にいらっしゃるかもしれないので、
以後の時間は、質問をどう伝えるかに取り組んでみましょう。

**Comment by gh640** [comment]
Bracket Highlighter で backtick を使ったハイライトをしたいのに設定ができない。

**Comment by gh640** [comment]
Bracket Highlighter のイシューのまとめ。

- やりたいこと: Markdown で backtick によるハイライトがしたい。
- 現状: ドキュメントと README を読んで設定ファイルに書いた。設定ファイルは読み込めた。
- 課題: ルールが効いていないみたい。
- 環境: MacX / Sublime Text 2 ver.2.0.2 build 2221 / Bracket Highlighter 2.2.1.

**Comment by gh640** [comment]
もう少し調べると次のことがわかった。

- Markdown の backtick ではないけど、 backtick によるハイライトは最新版では導入されていた。
- ただし最新版が使えるのは Sublime Text 3 だけで Sublime Text 2 のものでは使えない。
- ドキュメントにほしい。

**Comment by gh640** [comment]
I'd like to add backtick quote support for the Markdown syntax in Sublime Text 2.

I read the following README and commit log on HEAD and understood it's possible to add custom quote types.

- https://packagecontrol.io/packages/BracketHighlighter
- https://github.com/facelessuser/BracketHighlighter/commit/d884e8ab7aa69477c1af5d29cef24589efaf2b8e

I edited my config file as following but it doesn't work... I expected that the string surrounded by backticks would be highlighted but didn't.

```
{
    "debug_enable": true,
    "user_scope_brackets": [
        // Single backtick
        {
            "name": "backtick_quote",
            "open": "(`)",
            "close": "(`)",
            "style": "single_quote",
            "language_filter": "blacklist",
            "language_list": [],
            "sub_bracket_search": "true",
            "enabled": true
        }
    ]
}
```

I'd like a support for my problem.

My environment is as follows.

- MacX
- Sublime Text 2 ver. 2.0.2 build 2221
- Bracket Highlighter v2.2.1

If the information above is not enough, please let me know. Thanks in advance.

**Comment by gh640** [comment]
イシューのテンプレートがありました！

https://github.com/facelessuser/BracketHighlighter/issues/new

**Comment by gh640** [comment]
HEAD （ Sublime Text 3 のみ）バッククォートがサポートされていることがドキュメントに書かれていないので、その分を PR してもいいかも。

**Comment by znz** [comment]
バッククォート対応のドキュメント改善は明白な変更なので、 pull request しやすいのではないかという話などをしました。

**Comment by gh640** [comment]
順番が前後しましたが、 Bracket Highlighter のコントリビュート方法についてのドキュメントが下の方にありました。

- http://facelessuser.github.io/BracketHighlighter/contributing/

**Comment by kou** [comment]
お疲れ様でした！
これからも引き続きOSSの開発に参加していきましょう！

次回は4月22日に開催です！メンターあるいはもう一度ビギナーとしてどうぞ！
https://oss-gate.doorkeeper.jp/events/58579

**Comment by gh640** [comment]
報告です。

その後、別のプロジェクトにはなりますが、 OSS Gate での経験のおかげでイシューの登録や PR の作成等の作業をスムーズに行うことができました！

https://github.com/drush-ops/drush/pull/2711
https://github.com/drush-ops/drush/issues/2710

内容的にリジェクトはされましたが、具体的な作業の流れと感じがわかったのでこれからスムーズにコントリビュートしていけそうです。ありがとうございました！
