### ISSUE TITLE
LICENSE内のライセンス表記が間違っている

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#3]
「CC BY-SA 4.0 International」が正しい。

https://github.com/oss-gate/workshop/issues/2#issuecomment-167148655

> このリポジトリのライセンスなんですが
リンク先はCC BY-SA 4.0 Internationalになっているのに、ファイルにはUniversalとなっているので直してもいいですかね？

**Comment by kou** [comment]
@tSU-RooT 別の話題なのでissueをわけました。（同じissueに異なる話題が複数あると紛らわしいから。）

修正おねがいします！

**Comment by tSU-RooT** [comment]
了解しました、修正しますね
