### ISSUE TITLE
告知の仕方とその効果

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#32]
告知の仕方をいくつか試してみた。その結果を活かすことで今後より有効に告知できるのではないか。

**Comment by kou** [comment]
メンターを募集するときは人数に関する情報（いまどのくらい登録されているかとか、あとどのくらいいるとよさそうかとか）入れたほうがよさそう。

https://twitter.com/ktou/status/707925428078399488

> 3月26日開催のOSS Gateワークショップには「OSS開発に参加したい！」という人が14人も登録しているよ！でもそんな人たちをサポートするメンターの人が10人で少し足りないです。OSS開発経験者の人は手伝いに来てくれませんか！？

↑はRT 12。数人増えたはず。

https://twitter.com/ktou/status/735086484928106496

> OSS開発者を増やしたい人で5月28日（土）に時間がある人はメンターとして参加して欲しいです！OSS開発経験者ならメンターできます！ - OSS Gateワークショップ2016-05-28 #oss_gate

↑はRT 21。増えていない。

**Comment by kou** [comment]
プログラミング言語のメーリングリストに、その言語特有の文脈で書いた紹介を告知すると効果がありそう。

Ruby向けにやったときはビギナー・メンター・すぐにワークショップには参加できないけどなにかしら協力したい、という人が5-10人くらい増えた。

Rubyの場合は「OSSの開発に参加」じゃなくて「Ruby本体の開発に参加・gemの開発に参加」という言い方にした。

紹介内容はブログ記事にした。ブログ記事にしたのはリンクを貼って拡散しやすそうだったからである。

[2016年5月28日開催のOSS Gateワークショップは東京Ruby会議11と同建物で開催](http://oss-gate.github.io/announce/update/2016/05/18/workshop-with-tokyo-rubykaigi-11.html)

ruby-list（Rubyユーザー向けのメーリングリスト）への告知は詳細は書かずに↑のリンクをつけて、興味がある人を↑に誘導するようにしてみた。

[[ruby-list:50333] [ANN] OSS Gateワークショップ2016-05-28](http://blade.nagaokaut.ac.jp/cgi-bin/vframe.rb/ruby/ruby-list/50333?50310-50335)

Ruby以外のプログラミング言語でもこのやり方を使えるかもしれない。

**Comment by sezemiadmin** [comment]
ありがとうございます! なるほど! より具体的にということと、コンテキストを合わせるということですね。
この2つを考えると、分かった段階で、ビギナーやメンターのことも告知文に載せるのも良い気がしました。

- ex. (メンター向け) ScalaでOSS開発デビューしたい人が3人もいるよ
- ex. (ビギナー向け) Scalaでメンター出来る人が3人もいるよ

**Comment by kou** [comment]
古いので閉じます！

サイトとかどっかに知見をまとめておいたほうがいいのかしら。

**Comment by sezemiadmin** [comment]
関連からすると、ここが良いかもしれません
https://github.com/oss-gate/retrospective/issues/28
