### ISSUE TITLE
OSS Gate Workshop: sapporo: 2017-03-18: kotonikushidori docker: Work log

### ISSUE THREAD

**Issue by kotonikushidori** [oss-gate/workshop#324]
This is a work log of "OSS Gate".

"OSS Gate" is about an activity to increase OSS developers.

Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」の形式でつけてください
  - 例：「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by tricknotes** [comment]
こんにちは！メンターの佐藤です。
今日はよろしくお願いします！

**Comment by kotonikushidori** [comment]
docker インストールをするので本家サイトとかqiitaをぐぐってコピペでコマンドを実行する
わからないときはコピペをするのが基本だと思っている

**Comment by kotonikushidori** [comment]
url発見
http://qiita.com/hshimo/items/e24b1fbfbf775ec7c941

**Comment by kotonikushidori** [comment]
本家サイトで頑張ることにする
https://docs.docker.com/docker-for-mac/

英語が読めないのでノリでコピペる

**Comment by kotonikushidori** [comment]
とりあえず上から書いてあるコマンドをコピペして実行してみる

docker --version

**Comment by kotonikushidori** [comment]
わかってはいたけど ない。

sugisawayousukenoMacBook-Pro:~ sugisawayousuke$ docker --version
-bash: docker: command not found
sugisawayousukenoMacBook-Pro:~ sugisawayousuke$

**Comment by kotonikushidori** [comment]
中学生の英語力でもなんとか読めたので
ちゃんと読んでみる努力は大事だと思いました


＞Got Docker for Mac? If you have not yet installed Docker for Mac, please see Install Docker for Mac for an explanation of stable and beta channels, system requirements, and download/install information.

ここのリンクを踏む

**Comment by kotonikushidori** [comment]
リンクをメモる
https://docs.docker.com/docker-for-mac/install/

**Comment by kotonikushidori** [comment]
安定バージョンっぽい単語なのでステーブルの方をゲットする

Stable channel

**Comment by kotonikushidori** [comment]
ダウンロード中

**Comment by kotonikushidori** [comment]
インストールはドラッグアンドドロップでした。
マックのドラッグはちょっと反応が変でした

**Comment by kotonikushidori** [comment]
インストールしたのでゲットしたページの続きを読む

**Comment by kotonikushidori** [comment]
最後の単語がわからない

Docker for Mac requires OS X El Capitan 10.11 or newer macOS release running on a 2010 or newer Mac, with Intel’s hardware support for MMU virtualization. The app will run on 10.10.3 Yosemite, but with limited support. Please see What to know before you install for a full explanation and list of prerequisites.

**Comment by kotonikushidori** [comment]
じぶんのマックは大丈夫だった

MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)

**Comment by kotonikushidori** [comment]
10.12.3（16D32）
バージョン情報貼り忘れ

**Comment by kotonikushidori** [comment]
英語を読むのが疲れたので翻訳してみる


インストールする前に知っておくべきこと
Docker ToolboxおよびDocker MachineユーザーのためのREADME FIRST：すでにDocker for MacとDocker Toolboxを読んでいる場合は、このインストールが既存のセットアップに与える影響を理解し、Docker for Macの環境を設定する方法、そしてどのように2つの製品が共存できるかについて説明します。
Dockerマシンとの関係：Mac用Dockerをインストールしても、Docker Machineで作成したマシンには影響しません。ローカルのデフォルトマシン（存在する場合）から新しいDocker for Mac HyperKit "VMにコンテナとイメージをコピーするオプションがあります。 Docker for Macを実行しているときは、Docker Machineノードはすべてローカル（またはそれ以外の場所）で実行する必要はありません。 Docker for Macには、VirtualBoxシステムに代わる新しいネイティブ仮想化システム（HyperKit）があります。詳細は、Docker for MacとDocker Toolboxを参照してください。
システム要件：Docker for Macは、これらの要件がすべて満たされている場合にのみ起動します。
Macは2010年以降のモデルでなければならず、Intelのハードウェアでメモリ管理ユニット（MMU）の仮想化をサポートしている必要があります。すなわち、拡張ページテーブル（EPT）および無制限モード。
OS X El Capitan 10.11以降のMacOSリリースがサポートされています。最低限、Docker for MacにはMacOSのYosemite 10.10.3以降が必要です.10.10.xが今後のリリースで使用される際の注意点は、お客様自身のリスク提案です。
Docker for Mac安定版1.13（予定）、および同時リリースのEdgeリリースから、OS X Yosemite 10.10に固有の問題は解決されません。今後のリリースでは、Mac用Dockerは、このOS Xバージョンの非推奨状態のため、OS X Yosemite 10.10の動作を停止する可能性があります。 MacOSの最新バージョンにアップグレードすることをお勧めします。
少なくとも4GBのRAM
バージョン4.3.30より前のVirtualBoxはインストールしないでください（互換性がありません）

**Comment by tricknotes** [comment]
Google 翻訳で、ちょろっと単語とか文章とか確認したいときってありますよね…！
ぼくはこちらを使ってますー https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

ごさんこうまで！

**Comment by kotonikushidori** [comment]
どっかークジラをダブルクリックしたらすごい権限を求められました。
おk

**Comment by kotonikushidori** [comment]
インスコできたように見える

sugisawayousukenoMacBook-Pro:~ sugisawayousuke$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: FPSI:5NZH:AYZU:HU4K:QULQ:SJYA:M6MH:VD6S:EJV7:KBVZ:7B36:CZEN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-03-18T05:11:40.565107181Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
sugisawayousukenoMacBook-Pro:~ sugisawayousuke$

**Comment by kotonikushidori** [comment]
英語がわからないので gotit 押下する

**Comment by kotonikushidori** [comment]
Where to go next

という案内先に進むと良いというアドバイスをもらったので進めてみる

**Comment by kotonikushidori** [comment]
https://docs.docker.com/learn/
学習ページにきました

**Comment by kotonikushidori** [comment]
getdocker

https://docs.docker.com/engine/getstarted/step_one/#step-1-get-docker

から戻る

**Comment by kotonikushidori** [comment]
https://docs.docker.com/engine/getstarted/step_one/#step-3-verify-your-installation
このページでコマンドコピペ

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
sugisawayousukenoMacBook-Pro:~ sugisawayousuke$

**Comment by kotonikushidori** [comment]
英語疲れたので読み飛ばす

**Comment by kotonikushidori** [comment]
pullした後に再度はハローワールど実施
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

問題なさそうに見えました。
これで自分のやりたいことができるのかな？
php5.6とアパッチ2.2とmysql5.6 の環境がサクッと入れられたり
php5.1.6とアパッチ2.2とmysql5.1 の環境にサクッと入れなおせたり
できるイメージ。

**Comment by kotonikushidori** [comment]
英語読み飽きたので次のページ
https://docs.docker.com/engine/getstarted/step_three/

**Comment by kotonikushidori** [comment]
どっかー羽生に入りなさいと言われたので従う。

https://hub.docker.com/

世の中はぶだらけだ

**Comment by kotonikushidori** [comment]
https://hub.docker.com/
ねんがんの どっかーはぶ  あかうんと を て に いれたぞ

**Comment by kotonikushidori** [comment]
whalesay で検索したらマニュアルと違う画面でざいん＋知らない人たちのwhalesay であふれていた
困った。
英語読めない、仕組みを理解していない、見よう見まねでしか進めない人にはこの世界は厳しすぎる

**Comment by kotonikushidori** [comment]
docker/whalesay
で検索して
stars で絞り込んだら先頭にそれらしきものが表示された

**Comment by kotonikushidori** [comment]
詳細画面もまたでざいんが違う、、、だと、、、、

**Comment by kotonikushidori** [comment]
https://hub.docker.com/r/docker/whalesay/
詳細は見るだけでよかった。ここで何かダウンロードとかコマンドを探してしまった。
騙された

**Comment by kotonikushidori** [comment]
$ docker run docker/whalesay cowsay boo
Unable to find image 'docker/whalesay:latest' locally
latest: Pulling from docker/whalesay
e190868d63f8: Pull complete 
909cd34c6fd7: Pull complete 
0b9bfabab7c1: Pull complete 
a3ed95caeb02: Pull complete 
00bf65475aba: Pull complete 
c57b6bcc83e3: Pull complete 
8978f6879e2f: Pull complete 
8eed3712d2cf: Pull complete 
Digest: sha256:178598e51a26abbc958b8a2e48825c90bc22e641de3d31e18aaf55f3258ba93b
Status: Downloaded newer image for docker/whalesay:latest
 _____ 
< boo >
 ----- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
sugisawayousukenoMacBook-Pro:~ sugisawayousuke$ 

ホイールがsayしました。

**Comment by iakio** [comment]
宜しくお願いします！

**Comment by kotonikushidori** [comment]
修正ページの特定
修正するべき箇所の特定

残課題
修正内容の推敲をする

**Comment by kotonikushidori** [comment]
▲困っていること
マニュアルに記載されているコンテナが
記載されている 検索方法で絞り込めなかった

対象ページ
https://docs.docker.com/engine/getstarted/step_three/#step-2-run-the-whalesay-image

元
Enter the word whalesay in the search bar.

修正後
Enter the word docker/whalesay in the search bar.

で、絞り込んだ結果に対して

セレクタで
Starsを選択することで
目的のコンテナが先頭に表示される可能性が非常に高くなる

**Comment by tricknotes** [comment]
Fork されたリポジトリを clone して、表示を確認してみましょうか！
https://github.com/kotonikushidori/docker.github.io/tree/patch-1

**Comment by kotonikushidori** [comment]
教わるままにgitコマンドを叩く

$ git clone https://github.com/kotonikushidori/docker.github.io


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

**Comment by tricknotes** [comment]
XCode の設定が足りていないようですね…！(こういうのってどこを調べるとわかるんだろう…)
```
$ sudo xcodebuild -license
```

**Comment by kotonikushidori** [comment]
実行ログ
sugisawayousukenoMacBook-Pro:~ sugisawayousuke$ sudo xcodebuild -license
Password:


You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.

Hit the Enter key to view the license agreements at '/Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf'

Apple Inc.

Xcode and Apple SDKs Agreement

PLEASE SCROLL DOWN AND READ ALL OF THE FOLLOWING TERMS AND CONDITIONS CAREFULLY BEFORE USING THE APPLE SOFTWARE OR APPLE SERVICES.  THIS IS A LEGAL AGREEMENT BETWEEN YOU AND APPLE.  IF YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS, CLICK THE “AGREE” BUTTON.  BY CLICKING “AGREE” OR BY DOWNLOADING, USING OR COPYING ANY PART OF THIS APPLE SOFTWARE OR USING ANY PART OF THE APPLE SERVICES, YOU ARE AGREEING ON YOUR OWN BEHALF AND/OR ON BEHALF OF YOUR COMPANY OR ORGANIZATION TO THE TERMS AND CONDITIONS STATED BELOW.  IF YOU DO NOT OR CANNOT AGREE TO THE TERMS OF THIS AGREEMENT, YOU CANNOT USE THIS APPLE SOFTWARE OR THE APPLE SERVICES.  DO NOT DOWNLOAD OR USE THIS APPLE SOFTWARE OR APPLE SERVICES IN THAT CASE.

1.      Definitions
Whenever capitalized in this Agreement:

“Agreement” means this Xcode and Apple SDKs Agreement.

“Apple” means Apple Inc., a California corporation with its principal place of business at One Infinite Loop, Cupertino, California 95014, U.S.A.

“Apple Developer Program License Agreement” means a separate agreement that may be entered into between You and Apple regarding the development and submission of Applications to the App Store for approval and digital signing by Apple, development of libraries for iOS, watchOS, and/or tvOS, and the use of Apple services such as the Apple Push Notification Service, In-App Purchase, and iCloud, among other things.

“Apple Maps Service” means the mapping platform and Map Data provided by Apple via the MapKit API (which is the documented API that enables You to add mapping features or functionality to Applications).  

“Apple Services” or “Services” means the developer services that Apple provides to You under this Agreement solely for use with Your Applications and not for use by You as an end-user (e.g., Game Center, Apple Maps Service, any Apple-certificate issuance services, etc.), including any Updates thereto (if any) that may be provided to You by Apple.  

“Apple Software” means the Xcode Developer Tools and the Apple SDKs, including any Updates thereto (if any) that may be provided to You by Apple.

“Apple SDKs” means the macOS SDK, and the Apple-proprietary Software Development Kits (SDKs) provided hereunder, including but not limited to header files, APIs, libraries, simulators, and software (source code and object code) labeled as part of the iOS SDK, watchOS SDK and/or tvOS SDK and included in the Xcode Developer Tools package for purposes of targeting Apple-branded products running iOS, watchOS, or tvOS.


By typing 'agree' you are agreeing to the terms of the software license agreements. Type 'print' to print them or anything else to cancel, [agree, print, cancel] q

You can view the license agreements in Xcode's About Box, or at /Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf

sugisawayousukenoMacBook-Pro:~ sugisawayousuke$ sudo xcodebuild -license


You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.

Hit the Enter key to view the license agreements at '/Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf'

Apple Inc.

Xcode and Apple SDKs Agreement

PLEASE SCROLL DOWN AND READ ALL OF THE FOLLOWING TERMS AND CONDITIONS CAREFULLY BEFORE USING THE APPLE SOFTWARE OR APPLE SERVICES.  THIS IS A LEGAL AGREEMENT BETWEEN YOU AND APPLE.  IF YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS, CLICK THE “AGREE” BUTTON.  BY CLICKING “AGREE” OR BY DOWNLOADING, USING OR COPYING ANY PART OF THIS APPLE SOFTWARE OR USING ANY PART OF THE APPLE SERVICES, YOU ARE AGREEING ON YOUR OWN BEHALF AND/OR ON BEHALF OF YOUR COMPANY OR ORGANIZATION TO THE TERMS AND CONDITIONS STATED BELOW.  IF YOU DO NOT OR CANNOT AGREE TO THE TERMS OF THIS AGREEMENT, YOU CANNOT USE THIS APPLE SOFTWARE OR THE APPLE SERVICES.  DO NOT DOWNLOAD OR USE THIS APPLE SOFTWARE OR APPLE SERVICES IN THAT CASE.

1.      Definitions
Whenever capitalized in this Agreement:

“Agreement” means this Xcode and Apple SDKs Agreement.

“Apple” means Apple Inc., a California corporation with its principal place of business at One Infinite Loop, Cupertino, California 95014, U.S.A.

“Apple Developer Program License Agreement” means a separate agreement that may be entered into between You and Apple regarding the development and submission of Applications to the App Store for approval and digital signing by Apple, development of libraries for iOS, watchOS, and/or tvOS, and the use of Apple services such as the Apple Push Notification Service, In-App Purchase, and iCloud, among other things.

“Apple Maps Service” means the mapping platform and Map Data provided by Apple via the MapKit API (which is the documented API that enables You to add mapping features or functionality to Applications).  

“Apple Services” or “Services” means the developer services that Apple provides to You under this Agreement solely for use with Your Applications and not for use by You as an end-user (e.g., Game Center, Apple Maps Service, any Apple-certificate issuance services, etc.), including any Updates thereto (if any) that may be provided to You by Apple.  

“Apple Software” means the Xcode Developer Tools and the Apple SDKs, including any Updates thereto (if any) that may be provided to You by Apple.

“Apple SDKs” means the macOS SDK, and the Apple-proprietary Software Development Kits (SDKs) provided hereunder, including but not limited to header files, APIs, libraries, simulators, and software (source code and object code) labeled as part of the iOS SDK, watchOS SDK and/or tvOS SDK and included in the Xcode Developer Tools package for purp

By typing 'agree' you are agreeing to the terms of the software license agreements. Type 'print' to print them or anything else to cancel, [agree, print, cancel] agree

You can view the license agreements in Xcode's About Box, or at /Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf

sugisawayousukenoMacBook-Pro:~ sugisawayousuke$

**Comment by kotonikushidori** [comment]
困ったときのチャットルームを教えてもらいました。

https://gitter.im/oss-gate/sapporo

**Comment by kotonikushidori** [comment]
日本語で文章を書いて、英語に翻訳して、翻訳された英語の清書を行う。
ポイントは
・主語 の 記載
・can not の内容（表示が無い のか表示が探せなかった のか。の違いなど）
・単純な英単語への書き換え

**Comment by kotonikushidori** [comment]
今後やってみたいこと
・開発サーバ簡単ビルド（webとDBとサーバスクリプトのインスコ）の設定を持っておく
・新人アサイン時の開発サーバビルドコスト削減
・PG以外のデザイナーの人でも気軽にサーバ体験、テンプレート修正体験

http://koni.hateblo.jp/entry/2017/01/28/150522

**Comment by tricknotes** [comment]
おつかれさまでした！よかったらまた遊びにきてみてくださいね！
