### ISSUE TITLE
Tutorial Feedback on Workshop Tokyo 2017-03-25

### ISSUE THREAD

**Issue by tdtds** [oss-gate/workshop#331]
進行役のサポートが、スライドなどに問題を感じた場合に使うメモ。

**Comment by tdtds** [comment]
* 冒頭のgitterの説明用のスライドを追加

**Comment by tdtds** [comment]
* 未体験の理由の一覧がどこで終わるかわからず次のページにいってしまう
  * 「ここでおわり」のようなマーク(「...」のような)を入れる

**Comment by tdtds** [comment]
* OSSの定義に関するスライドを追加する
  * OSDのページへのリンクを貼る

**Comment by tdtds** [comment]
* 「まずは動かす」の手順が開発用にインストールになっているが、まず一般向けのREADMEを基本にするようにした方がよい?

**Comment by tdtds** [comment]
最後のアンケートでプルリクを作る手順はスライドで解説すべきか?

**Comment by kou** [comment]
アンケートとそのアンケートを使ったふりかえりをやめて、代わりにその場で今日のレポートを書いてもらうのはどうだろう。

理由は、この時間だと疲れていてふりかえりする気力が残っていない人が多そうだからというのとその場でレポートを書くと後でレポートを書く時間を確保する必要がなくなるから。

レポートは https://github.com/oss-gate/oss-gate.github.io/ にpull requestしてもらうようにすればpull requestの練習にもなりそう。自分のサイトとかブログとかを持っている人はそっちに書いて oss-gate.github.io の方の内容はリンクにする、とかでいいと思う。

**Comment by kou** [comment]
雑談場所みたいなスペースを用意しておいて（なにか飲食物があるといいのかしら。大阪ではスペースを用意していた。）、早くレポートを書き終わった人はそこに移動してざっくばらんに今日どうだった？とかもやっとしていることある？とかどうするといいかなぁ？とか話せるとふりかえりの時間でやっていたことと同じ効果を得られるかも。アンケートよりも柔軟に会話できるので、もしかしたら、もっと得られるかも。

**Comment by kou** [comment]
「メンター」という名前を「サポーター」にするのはどうか。 実際にやることは教えることとか導くことじゃなくて、大丈夫だよ、ということだから、というのと、 https://github.com/oss-gate/oss-gate.github.io/issues/33 にあるように「メンター」だとすごい人しかできなそうというイメージがでてしまうから。（実際は元ビギナーの人にもメンターして欲しい。元ビギナーの人の得られることもたくさんあるはず。）

**Comment by knokmki612** [comment]
アンケートは

* 参加した人が気になっているので書きたいこと(記述式)
* 参加した人は気にしていないけどやることを少し変えたのでフィードバックがほしいこと(選択式)

に分けられるかなと思いました。

前者は

> アンケートとそのアンケートを使ったふりかえりをやめて、代わりにその場で今日のレポートを書いてもらうのはどうだろう。

で、後者は

> 早くレポートを書き終わった人はそこに移動してざっくばらんに今日どうだった？とかもやっとしていることある？とかどうするといいかなぁ？とか話せる

で話した後、今やっているように、専用のissueにコメントで残しておけば  
アンケートでやっていることをカバーできるかも！と思いました。

**Comment by knokmki612** [comment]
やってみたいこと:  
スライドでの説明を「動かしてみる」で午前、と「フィードバック」で午後、という分け方をやめて、ワークショップの最初に全て説明する

理由:
* ワークショップの時間が短くできそう
* ビギナーの状況に柔軟にあわせてサポートできそう
* フィードバックまでいけそうな人は早く行けそう

考えたいこと:
* ビギナーを混じえたデモをどうする？(現状のほうが進行にあわせてやりやすい)

**Comment by knokmki612** [comment]
今回のワークショップで試みられた「1つのテーブルでメンター1対ビギナー4」の、フィードバックの文章を他のビギナーも交えてレビューしようとしたやつが、良いアイデアだなあと思ったので、なんらかの形で実現できないでしょうか

**Comment by knokmki612** [comment]
@kou 
> アンケートとそのアンケートを使ったふりかえりをやめて、代わりにその場で今日のレポートを書いてもらうのはどうだろう。

これですが、

1. "2017-03-25-tokyo"みたいなディレクトリだけ用意する
2. そこにgithubでファイルを作成してもらって、レポート(書式の指定とかはとくになし)を書いてもらう

というのを想像しましたが、どうですかね

**Comment by knokmki612** [comment]
> スライドでの説明を「動かしてみる」で午前、と「フィードバック」で午後、という分け方をやめて、ワークショップの最初に全て説明する

ミートアップでは、続きの作業をする人は聞かずに作業を始めて、説明が必要なだけ集まってもらうという感じが良いかなと思いました！

**Comment by kou** [comment]
> これですが、
> 
>  1.  "2017-03-25-tokyo"みたいなディレクトリだけ用意する
>  2. そこにgithubでファイルを作成してもらって、レポート(書式の指定とかはとくになし)を書いてもらう
> 
> というのを想像しましたが、どうですかね

https://github.com/oss-gate/oss-gate.github.io/tree/master/_posts に`2017-03-25-tokyo-report-beginner-#{アカウント名}.md`みたいなファイルを作ってもらうのがいいと思っていました。そうしたら、そのまま公開されるし http://oss-gate.github.io/workshop/report.html を手動でメンテナンスする手間も減るのでいいなぁと思っていました。

**Comment by knokmki612** [comment]
> レポートは https://github.com/oss-gate/oss-gate.github.io/ にpull requestしてもらうようにすれば

ここを見落としていました…！

これも今週の東京ミートアップでできるかなと思ったのですが、やるにはスライドか何かで説明をする用意が必要そうですかね

**Comment by knokmki612** [comment]
@koic さんが「1つのテーブルでメンター1対ビギナー4」の観察係をしていて、

* 4人サポートする @kou さんの役割は誰でもはできなさそう
* 午後のフィードバックは自分もサポートにまわっていた

ため、続けるとしたら何らかの改善が必要だという話があった気がします

**Comment by knokmki612** [comment]
@onk さんの「コード書くほうにもっていきたい」という話は、ミートアップの開発者枠でやっていこうという感じだったと思います

**Comment by knokmki612** [comment]
そもそも、OSS Gateワークショップで門をくぐった次のステップは、 @kou さんの話では、ミートアップの開発者枠で  
「ベテランの開発者に話を聞けたりお互いにコミュニケーションをとりながら開発する」  
でやりたい、ということでした。

私もそれが良いなあと思うのですが、そのためには開発者枠での参加人数を増やしていくことが必要で、どういう工夫が必要かなあと思いました

**Comment by tdtds** [comment]
ふりかえりをする気力の残ってない人には、レポートを書く気力も残ってないんじゃないかなぁw もっとも、終わった人が雑談できるスペース & 時間をとるのはいいと思う。ついでにピザとドリンクを買ってきてビアバッシュにしてしまってもいいかもしれない。

**Comment by satoryu** [comment]
> ふりかえりをする気力の残ってない人には、レポートを書く気力も残ってないんじゃないかなぁw 

参加したみんなで一本レポートを書くくらいの分量で、一言メッセージをもらうとかどうでしょう。
今日の感想を付箋に書いて、壁に貼ってもらって、進行役なりレポーターなりが箇条書きにまとめるような。

**Comment by tdtds** [comment]
「メンター」という呼称を改めたほうがいいというのには賛成だけど、「サポートメンター」もいっしょに改名しないとね。というか、

* メンター → サポーター
* サポートメンター → メンター

がいい気がする。

**Comment by knokmki612** [comment]
> * メンター → サポーター
> * サポートメンター → メンター
>
> がいい気がする。

私はサポートメンターはそのままの呼称でも良い気がしますが、過去の参加者に誤解されなさそうだったら、サポートメンター→メンターで良いと思います

**Comment by kou** [comment]
> ふりかえりをする気力の残ってない人には、レポートを書く気力も残ってないんじゃないかなぁw

私が進行役で前から見ている感じだと、アンケートを書く気力が残っていない人はいなそう（むしろ毎回みんなちゃんと考えて書いてくれている！）で、その後のふりかえりだとぐったりの人がちらほら、です。たぶん、みんながみんな他の人の考えや、ワークショップをもっとよくするには？、に興味があるわけじゃない、ということだろうなぁと思います。興味がないと、まぁ、気力が続かなそうです。

なので、アンケートを書くみたいにレポートも考えて書いてくれるんじゃないかなぁと期待しています。（実験してみたい。）
あと、今日のワークショップはよかった！という気持ちは、後よりもその場の方が強いと思うので、そのときに書いてもらえると率直な感想を知れてよさそうだなぁという風にも期待しています。

**Comment by kou** [comment]
> 参加したみんなで一本レポートを書くくらいの分量で、一言メッセージをもらうとかどうでしょう。
> 今日の感想を付箋に書いて、壁に貼ってもらって、進行役なりレポーターなりが箇条書きにまとめるような。

うーん。。。それならアンケートを書いてもらうだけ、でいいかなぁと思いました。今でもその他欄にメッセージをもらっていますし。

そういう風に集めた感想を箇条書きにまとめた内容って、参加していない人には断片的すぎて伝わらないし（レポートとして微妙そう）、参加していた人にとっても、後で見たら文脈が抜けていて思い出しづらくて（ログとしても微妙そう）、私はあんまりよいイメージがないんですよね。。。

**Comment by kou** [comment]
> * サポートメンター → メンター

今の「サポートメンター」も「すごい人」じゃなくて、「困ったときに相談できる人」、「（今の）メンター経験がある先輩」くらいなので、「メンター」という単語を入れないほうがいいんじゃないかなぁと思いました。

字面だけで言うと「相談役」とか「シニアサポーター」とかなんですが、「相談役」っていうとおじいさんみたいなイメージがでそうだし、「シニア」ってつくと「メンター」とはまた別の「すごい人」感がでそうでアレなんですよねぇ。

「アドバイザー」だとなにもしなそうだしなぁ。。。

サポーターをフォローする人はなんなのかしら。

**Comment by knokmki612** [comment]
スライドへのフィードバックについてですが、

* OSSの定義に関するスライドを追加する
* 「まずは動かす」の手順が開発用にインストールになっているが、まず一般向けのREADMEを基本にするようにした方がよい?

は今回のkouさんの資料の更新で反映されましたね！

**Comment by knokmki612** [comment]
だいぶ古いし、ここに上がっている話題はだいたい旬をすぎている感じがしたので、閉じますね
