### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: vividmuimui: roo: Work log

### ISSUE THREAD

**Issue by vividmuimui** [oss-gate/workshop#332]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by koic** [comment]
hi

**Comment by ryfjwr** [comment]
👍

**Comment by keisei1092** [comment]
Cheers!

**Comment by u16suzu** [comment]
🎉

**Comment by vividmuimui** [comment]
とりあえずgithubのぺーじひらこ

**Comment by vividmuimui** [comment]
動かすんだから、`how tow contribute`みたいのがreadmeにあるのを期待してreadme眺めてみよ

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo#contributing
あった！

**Comment by vividmuimui** [comment]
features, testingあるからとりあえずこれ順番にやっていこうかな

**Comment by vividmuimui** [comment]
> 1.Fork it ( https://github.com/[my-github-username]/roo/fork )

forkするぞい

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo#installation
やっぱり！installから！

**Comment by vividmuimui** [comment]
初心取り戻して一から見てくぞ！！！

**Comment by vividmuimui** [comment]
> Roo provides an interface to spreadsheets of several sorts.

さぱらん
このspreadsheetsはgoogle spreadsheetの話なのかな
`several sorts`もちょっとうまく理解できないな～

**Comment by vividmuimui** [comment]
とりあえずreadme眺めようかな

**Comment by vividmuimui** [comment]
> ![image](https://cloud.githubusercontent.com/assets/1803598/24318767/4ecfa8b4-114e-11e7-96c2-3988b7feb55f.png)

そこそこちゃんとメンテされてる感あるな

**Comment by vividmuimui** [comment]
readme!

**Comment by vividmuimui** [comment]
> Roo implements read access for all common spreadsheet types. It can handle:

[さっき](https://github.com/oss-gate/workshop/issues/332#issuecomment-289182315)のspreadsheetもこれと同じ話かな。

**Comment by vividmuimui** [comment]
そもそも `spreadsheet`とは！alcで見よ

**Comment by vividmuimui** [comment]
http://eow.alc.co.jp/search?q=spreadsheet&ref=sa

> ![image](https://cloud.githubusercontent.com/assets/1803598/24318783/a914ddf8-114e-11e7-9d70-579dccd29724.png)

spreadsheetで`表計算`なのか
googleのspreadsheetのことじゃないのなー

**Comment by vividmuimui** [comment]
> Excel 2007 - 2013 formats (xlsx, xlsm)
LibreOffice / OpenOffice.org formats (ods)
CSV
Excel 97, Excel 2002 XML, and Excel 2003 XML formats when using the roo-xls gem (xls, xml)
Google spreadsheets with read/write access when using roo-google

excel, 2013までってあるけどそれ以降はどうなんだろ。そもそもそれ以降のバージョンあるのか知らないけど。
古いexcelはroo-xls, google spreadsheetsはroo-googleに別gemとして切り出されてるのか。良さ。
エクセルのファイルフォーマット書かれてるのわかりやすさあって良いなー。
それがあってればバージョンずれてても動きそうな気がする

**Comment by vividmuimui** [comment]
わんちゃんreadmeが更新されてないだけなのかな。
とりあえず次すすも

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo#installation
install方法は普通。
> "~> 2.7.0"

2.7.0以前はバグか何かかな。気になるけど気にしないでおこ

**Comment by vividmuimui** [comment]
最新バージョン気になる
tags見よ

**Comment by vividmuimui** [comment]
> ![image](https://cloud.githubusercontent.com/assets/1803598/24318841/c47996e6-114f-11e7-8953-c818f2f4da6f.png)

単純に、最新使ってね、ぐらいかな。
rubygemsもみておこうかな

**Comment by vividmuimui** [comment]
https://rubygems.org/gems/roo
リリースされてるバージョン一緒だった。

> ![image](https://cloud.githubusercontent.com/assets/1803598/24318849/ea2bd098-114f-11e7-984f-ad5ea6bc7dec.png)

そこそこちゃんとメンテされてそう

**Comment by vividmuimui** [comment]
usage眺めると、結構ボリュームあるし、
とりあえずinstallしてから、usage見ながら動かそうかな

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo#installation
installすっぞ！

**Comment by vividmuimui** [comment]
rubyのバージョンはいくつでもいいのかな

**Comment by vividmuimui** [comment]
rubygems見ても特に無いし、とりあえず手元に入ってるのでいいか

**Comment by vividmuimui** [comment]
> gem install roo

**Comment by vividmuimui** [comment]
nokogiriかー

**Comment by vividmuimui** [comment]
nokogiriやっぱりコケた

**Comment by vividmuimui** [comment]
nokogiri
![tiqav](https://img.tiqav.com/1zC.jpg)

**Comment by vividmuimui** [comment]
でもどっかでnokogiri入れてるはずだから、
rubyのバージョン変えてみよっかな。

**Comment by vividmuimui** [comment]
2.3.3だったから
2.4.0でも一回チャレンジ!

**Comment by vividmuimui** [comment]
![tiqav](https://img.tiqav.com/3BM.jpg)

**Comment by vividmuimui** [comment]
既にroo使ってるリポジトリあるから、とりあえずそれで動かしてみようかな。
今nokogiriで疲弊したくないや

**Comment by vividmuimui** [comment]
とりあえずそのリポ最新にしよ

**Comment by vividmuimui** [comment]
nokogiri外せるといいのに！
xml使ってるから大変そうだけど

**Comment by vividmuimui** [comment]
gemを必要に応じて分割するのが良い感ある

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo/blob/master/roo.gemspec
依存gem見てみたけど
>   spec.add_dependency 'nokogiri', '~> 1'
  spec.add_dependency 'rubyzip', '>= 1.2.1', '< 2.0.0'

これしか使ってない
gemの分割してもnokogiriの依存外すのはしんどそう

**Comment by vividmuimui** [comment]
nokogiri以外のxml処理できるのがあればそれが最高
でも、それがあれば人類こんなにnokogiriに苦しんでなさそう。
nokogiriのこと知らないけど、nokogiriが辛いのc拡張だから、っていうのが大きそうだから、
rubyだけでxml処理できれば良かったりするのでは・・？

**Comment by vividmuimui** [comment]
xmlのこと知らないからそれができるのかさっぱりだけど。
rooに求められるの速度ではない感じするから、遅くてもいいと思うんだよな

**Comment by vividmuimui** [comment]
リポジトリは最新にできたらから、usage見ながらとりあえず動かすぞ!

**Comment by vividmuimui** [comment]
irbかな

**Comment by vividmuimui** [comment]
エクセルファイルーーーー

**Comment by vividmuimui** [comment]
サンプルおいてないかな

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo/tree/master/examples
examplesディレクトリにあるかなって思ったけど、なかった!

**Comment by vividmuimui** [comment]
testはどうかな！

**Comment by vividmuimui** [comment]
testとspecあるけどなんなのこのこ

**Comment by vividmuimui** [comment]
両方更新が3monthsになってるけど、両方書いてるのこれ。。
宗教問題かな。。

**Comment by vividmuimui** [comment]
specみよ

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo/tree/master/spec/lib/roo/excelx
期待させておいてエクセルファイルおいてない!

**Comment by vividmuimui** [comment]
test見よ

**Comment by vividmuimui** [comment]
ていうか、拡張子でファイル検索するのがはやいか

**Comment by vividmuimui** [comment]
> ![image](https://cloud.githubusercontent.com/assets/1803598/24318975/f853cbb4-1152-11e7-8f3a-66c3a3d285fb.png)

たくさんあるじゃん。
適当に選ぼ

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo/blob/master/test/files/numbers1.xlsx
numbersが一番シンプルそうな予感あるからこれ使うか。

**Comment by vividmuimui** [comment]
downloadした

**Comment by vividmuimui** [comment]
手元にエクセル入ってた!

**Comment by vividmuimui** [comment]
> ![image](https://cloud.githubusercontent.com/assets/1803598/24318988/535e7b30-1153-11e7-9ffd-52052f6e0354.png)

`numbers1.xlsx`というには数字以外のも入ってるな。
変換できるか、みたいなテスト用なのかな

**Comment by vividmuimui** [comment]
` require "roo"`

**Comment by vividmuimui** [comment]
```
irb(main):002:0> xlsx = Roo::Spreadsheet.open('./numbers1.xlsx')
=> <#Roo::Excelx:1774107206707400 @tmpdir @shared @filename @sheet_files @sheet_names @sheets @sheets_by_name @options @cell @cell_type @cells_read @first_row @last_row @first_column @last_column @header_line>
```
エラー出てないから読めたのかな

**Comment by vividmuimui** [comment]
あ、これspreadsheetだ
エクセルのはその下にあった

**Comment by vividmuimui** [comment]
んもー

**Comment by vividmuimui** [comment]
この`Roo::Spreadsheet`は表計算の意味のspreadsheetなのか google spreadsheetなのかどっちなんだろ

**Comment by vividmuimui** [comment]
`xlsx`ファイルを引数に渡してるから前者か。
google spreadsheetのは外部gemに出てたし、まーそうか

**Comment by vividmuimui** [comment]
```ruby
xlsx = Roo::Spreadsheet.open('./new_prices.xlsx')
xlsx = Roo::Excelx.new("./new_prices.xlsx")

# Use the extension option if the extension is ambiguous.
xlsx = Roo::Spreadsheet.open('./rails_temp_upload', extension: :xlsx)
```

一つのエクセルを開くのに、いくつもあるよってことか

**Comment by vividmuimui** [comment]
```
irb(main):003:0> xlsx.info
=> "File: numbers1.xlsx\nNumber of sheets: 5\nSheets: Tabelle1, Name of Sheet 2, Sheet3, Sheet4, Sheet5\nSheet 1:\n  First row: 1\n  Last row: 18\n  First column: A\n  Last column: G\nSheet 2:\n  First row: 5\n  Last row: 14\n  First column: B\n  Last column: E\nSheet 3:\n  First row: 1\n  Last row: 1\n  First column: A\n  Last column: BA\nSheet 4:\n  First row: 1\n  Last row: 1\n  First column: A\n  Last column: E\nSheet 5:\n  First row: 1\n  Last row: 6\n  First column: A\n  Last column: E"
```
読めてそう

**Comment by vividmuimui** [comment]
> Roo::Spreadsheet.open can accept both paths and File instances.

へー。
たいへんそう。

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo#working-with-sheets
さっきまでは読み込み部分で、ここから実際操作していくのか

**Comment by vividmuimui** [comment]
> ods.sheets

どこから`ods`でてきたの！！
んもー

**Comment by vividmuimui** [comment]
ods is 何

**Comment by vividmuimui** [comment]
http://eow.alc.co.jp/search?q=ods&ref=sa
全く関係ないの出たけど。。
何かの略語かな

**Comment by vividmuimui** [comment]
https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ods+%E3%81%A8%E3%81%AF&*
拡張子なのか。

**Comment by vividmuimui** [comment]
> LibreOffice / OpenOffice.org formats (ods)

これか。
さっきまでエクセルだったのに、なんでいきなりodsにしたの！！
`spreadsheet`で統一でいいのに

**Comment by vividmuimui** [comment]
https://github.com/roo-rb/roo#working-with-sheets
```ruby
ods.sheets
# => ['Info', 'Sheet 2', 'Sheet 3']   # an Array of sheet names in the workbook

ods.sheet('Info').row(1)
ods.sheet(0).row(1)

# Set the last sheet as the default sheet.
ods.default_sheet = ods.sheets.last
ods.default_sheet = ods.sheets[2]
ods.default_sheet = 'Sheet 3'

# Iterate through each sheet
ods.each_with_pagename do |name, sheet|
  p sheet.row(1)
end
```

odsは単なるファイル、ぐらいの意味合いしか無いことわかったから、
続けてさっきのエクセルでこれ試していけばいいかな

**Comment by vividmuimui** [comment]
```
irb(main):004:0> xlsx.sheets
=> ["Tabelle1", "Name of Sheet 2", "Sheet3", "Sheet4", "Sheet5"]
```

**Comment by kou** [comment]
いろいろフィードバックチャンスありそう！

**Comment by vividmuimui** [comment]
午後の部。
- 自分にわかりやすくまとめる
- 開発者に向けてわかりやすくまとめる
  - 英語化も
- 報告

**Comment by vividmuimui** [comment]
フィードバックポイントになりそうなやつをまとめた

### 概要の部分のexcelのバージョン周り更新されてないかも?

https://github.com/oss-gate/workshop/issues/332#issuecomment-289182754


### install方法のgemのバージョン

https://github.com/oss-gate/workshop/issues/332#issuecomment-289182912
このバージョン指定のお作法みたいのがあるかもしれないけど、
"~> 2.7.1"が良いかも？？
勝手に基本的には`~> 2.7.0`で基本的には最新が入りそうだし別にいいのかも？

### rubyのバージョン

https://github.com/oss-gate/workshop/issues/332#issuecomment-289183165
本当にどのバージョンでも動くのかは怪しいのでは・・？
travis(無料だっけ?)で各バージョンでテストがされてると良さそう

> ![image](https://cloud.githubusercontent.com/assets/1803598/24319661/9f693b16-1165-11e7-80cc-659f23123b30.png)
バッジおいてあった! https://travis-ci.org/roo-rb/roo

2.0.0以降では動いていそう

### nokogiri以外の代案

大変そう！

### サンプル動かすようのエクセルファイル

https://github.com/oss-gate/workshop/issues/332#issuecomment-289184104
置いておいてあげるのが優しいのでは？
エクエルがメインじゃない人もいるだろうけど、usageでさくっと動かせるように、ファイルを用意して、それを使うようなusageになっていたほうが優しそう

### testとspecディレクトリ

https://github.com/oss-gate/workshop/issues/332#issuecomment-289184132

### `ods`とは！？

https://github.com/oss-gate/workshop/issues/332#issuecomment-289184787
> さっきまでエクセルだったのに、なんでいきなりodsにしたの！！
spreadsheetで統一でいいのに

**Comment by vividmuimui** [comment]
どれにしようかな

**Comment by vividmuimui** [comment]
今の時間内でできるのを考えると、
`ods`のやつを直すのがサクッとできそう

**Comment by vividmuimui** [comment]
自分にわかるようにまとめる

# 現象

> https://gyazo.com/43d558369ef0241a8b3b36696626af5d

[usage](https://github.com/roo-rb/roo#usage)を順番にやっていくとき、
[Working with sheets](https://github.com/roo-rb/roo#working-with-sheets)の部分で、
いきなり`ods`と出てきて何かわからない。

> ![image](https://cloud.githubusercontent.com/assets/1803598/24319728/6063b318-1167-11e7-8b6f-7af62b9587a6.png)

[Usage](https://github.com/roo-rb/roo#usage)の一番最初では`xlsx`。その後に、odsがいきなり出てくるので、このodsが何かわからない。

実際は
> LibreOffice / OpenOffice.org formats (ods)

このファイルのことだった。

ほかにも
https://github.com/roo-rb/roo#accessing-rows-and-columns
いきなり`sheet.row(1)`と出てきたり、
https://github.com/roo-rb/roo#accessing-cells
`s.cell(1,1)`と`sheet`が省略されていたり、
統一感がない。

https://github.com/roo-rb/roo/blob/master/README.md#csv-support
ここも`s = Roo::CSV.new("mycsv.csv")`なんで`s`なのかわからない。

# 期待すること

上から順番にusageを実行していって、驚きが少なく実行できること。

# 変更するところ

:one:
いきなりodsが出てくるところに関しては、`ods`ファイルである必要がない&その上で`xlsx`を使っているので、`xlsx`に変えるのが良さそう

:two: 
省略しない
https://github.com/roo-rb/roo/blob/master/README.md#accessing-cells
https://github.com/roo-rb/roo/blob/master/README.md#csv-support

**Comment by vividmuimui** [comment]
> :two:
省略しない
https://github.com/roo-rb/roo/blob/master/README.md#accessing-cells
https://github.com/roo-rb/roo/blob/master/README.md#csv-support

をまずやる！

**Comment by vividmuimui** [comment]
英語にする前に日本語でそれっぽく。

--------

# 変数を省略せずにreadmeをわかりやすくした

https://github.com/roo-rb/roo/blob/master/README.md#accessing-cells

`s.cell(1,1)`などいきなり`s`が出てきてわかりづらい。他の箇所では丁寧にsheetと書いてある。

https://github.com/roo-rb/roo/blob/master/README.md#csv-support
ここの`s = Roo::CSV.new("mycsv.csv")`もいきなり`s`になっていてわかりづらい。他の箇所では、
xlsxとかodsなど拡張子をもとに変数をつけている。

**Comment by vividmuimui** [comment]
変数名を省略しない、の省略はomitでいいのかな

**Comment by vividmuimui** [comment]
Readabilityをあげた、を使いたい感じある

**Comment by vividmuimui** [comment]
# Update README to increase readability

Omitted local variable names in [README](https://github.com/roo-rb/roo/blob/master/README.md) are not readble.
For example, `s.cell(1,1)` and `s = Roo::CSV.new("mycsv.csv")`.
So fix it.

**Comment by kou** [comment]
abbreviated

**Comment by vividmuimui** [comment]
指摘された箇所直しました！
- リンク貼る
- typo
  - readble -> readable
- omitted -> v

**Comment by cesare** [comment]
`are not readable` だと「読めない」ぐらいのニュアンスになりそうなので、「ちょっと読みづらくなる」ぐらいのニュアンスが出せるとより良いかなと思いました。

たとえば `are not very easy to read` みたいな感じでどうでしょう？

**Comment by vividmuimui** [comment]
ありがとうございます！！
直します！

**Comment by vividmuimui** [comment]
https://github.com/oss-gate/workshop/issues/332#issuecomment-289192047
直しました。

**Comment by vividmuimui** [comment]
一応、既存のissueとprにかぶってるのがないか見ようかな

**Comment by vividmuimui** [comment]
なさそうだった

**Comment by cesare** [comment]
これは pull request (PR) を出す流れでしょうか？ あるいは issue ですかね？

PR だと差分が分かるのですが、issue だとどうなってほしいのかが伝わらないかもしれないので「こうなっていると嬉しい」という例を挙げておくと理解されやすくなりそうです。

たとえば、

* `s.cell(1,1)` ではなくて `sheet.cell(1, 1)` になっていると分かりやすくなると思う
* なぜなら、直前の例でも `sheet` を使っているから

みたいな感じでどうでしょう？

**Comment by vividmuimui** [comment]
PRを出す流れです！
完全にdiffある前提で英語書いてました。(英語苦手なので..)

**Comment by cesare** [comment]
なるほど。PR であれば、どう変更したのかは相手にも伝わるので、大丈夫かと思います！

**Comment by vividmuimui** [comment]
コミットメッセージ悩むー
readmeだから`Update README to increase readability`でもだいたい抵抗なくマージしてもらえそうではあるけど、
`{abbreviateの反対語} variable names to increase readability`が丁寧な気がする

**Comment by cesare** [comment]
README を変更したことは PR の内容から分かると思うので、「サンプルコードを読みやすくしたよ」ぐらいでも良いかもですね。

たとえば 

* Update sample codes to increase readability
* Fix sample codes to be easier to read

みたいな感じでしょうか。(ご参考に)

**Comment by kou** [comment]
後ちょっとでpull requestできそう！
