### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: ryfjwr Mroonga: Work log

### ISSUE THREAD

**Issue by ryfjwr** [oss-gate/workshop#333]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by vividmuimui** [comment]
🎉

**Comment by u16suzu** [comment]
🎉 やっていきましょう！！

**Comment by keisei1092** [comment]
Mroonga初めて聞きました がんばっていきましょう

**Comment by koic** [comment]
Hello!

**Comment by ryfjwr** [comment]
ライセンスを確認する

**Comment by ryfjwr** [comment]
どこをみればいい？

**Comment by ryfjwr** [comment]
ここにあんのかな...
http://mroonga.org/ja/

**Comment by ryfjwr** [comment]
あった

![screen shot 2017-03-25 at 11 21 41](https://cloud.githubusercontent.com/assets/713034/24318731/4029b648-114d-11e7-95c5-fa3043931203.png)

https://opensource.org/licenses/LGPL-2.1

![screen shot 2017-03-25 at 11 22 53](https://cloud.githubusercontent.com/assets/713034/24318740/67464a16-114d-11e7-9cac-fd099e0b4618.png)

**Comment by ryfjwr** [comment]
Mroonga インストール済なんで、まずアンインストール！

**Comment by ryfjwr** [comment]
これが使えそう？

http://y-ken.hatenablog.com/entry/mroonga-create-function

**Comment by ryfjwr** [comment]
Mroonga アンインストールでググった！ ↑ が出た

**Comment by ryfjwr** [comment]
Mroonga の公式サイトに無さそう（アンインストール方法が）

**Comment by ryfjwr** [comment]
これ正しいんだろうか...？

http://y-ken.hatenablog.com/entry/mroonga-create-function

![screen shot 2017-03-25 at 11 31 37](https://cloud.githubusercontent.com/assets/713034/24318782/a8f0e4d4-114e-11e7-8548-46d9e638745b.png)

**Comment by ryfjwr** [comment]
リポジトリから

`vim uninstall **/*` で検索した。

**Comment by ryfjwr** [comment]
リポジトリから検索して、見つからない... uninstall のやり方が...

**Comment by ryfjwr** [comment]
これを実行してみた。で、本当にインストール出来ているか見てみる

```
DROP FUNCTION mroonga_snippet;
DROP FUNCTION last_insert_grn_id;
DROP FUNCTION mroonga_command;
UNINSTALL PLUGIN mroonga;
FLUSH TABLES;

```

**Comment by ryfjwr** [comment]
公式ドキュメントにインストールチェックがあるので、これを実行してみよう

http://mroonga.org/ja/docs/tutorial/installation_check.html

**Comment by ryfjwr** [comment]
- 見事に見つからない。
- ので、アンインストール成功

```
> SHOW ENGINES;
+--------------------+---------+----------------------------------------------------------------------------+--------------+------+------------+
| Engine             | Support | Comment                                                                    | Transactions | XA   | Savepoints |
+--------------------+---------+----------------------------------------------------------------------------+--------------+------+------------+
| CSV                | YES     | CSV storage engine                                                         | NO           | NO   | NO         |
| MRG_MyISAM         | YES     | Collection of identical MyISAM tables                                      | NO           | NO   | NO         |
| MEMORY             | YES     | Hash based, stored in memory, useful for temporary tables                  | NO           | NO   | NO         |
| BLACKHOLE          | YES     | /dev/null storage engine (anything you write to it disappears)             | NO           | NO   | NO         |
| MyISAM             | YES     | MyISAM storage engine                                                      | NO           | NO   | NO         |
| InnoDB             | DEFAULT | Percona-XtraDB, Supports transactions, row-level locking, and foreign keys | YES          | YES  | YES        |
| ARCHIVE            | YES     | Archive storage engine                                                     | NO           | NO   | NO         |
| FEDERATED          | YES     | FederatedX pluggable storage engine                                        | YES          | NO   | YES        |
| PERFORMANCE_SCHEMA | YES     | Performance Schema                                                         | NO           | NO   | NO         |
| Aria               | YES     | Crash-safe tables with MyISAM heritage                                     | NO           | NO   | NO         |
+--------------------+---------+----------------------------------------------------------------------------+--------------+------+------------+
```

**Comment by ryfjwr** [comment]
ソースからビルドする！（しかないので、こちらからやってみる）

http://mroonga.org/ja/docs/install/others.html#build-from-source

**Comment by ryfjwr** [comment]
- mariadb のバージョンを確認する。
- `10.0.13` が入っている

```
$ mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.0.13-MariaDB MariaDB Server
```

**Comment by ryfjwr** [comment]
mariadb と groonga のソースを探す。どこだ...

https://downloads.mariadb.org/mariadb/10.0.13/

**Comment by ryfjwr** [comment]
華麗に失敗

```
$ wget https://downloads.mariadb.org/interstitial/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/
--2017-03-25 11:42:19--  https://downloads.mariadb.org/interstitial/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/
downloads.mariadb.org をDNSに問いあわせています... 173.203.201.148
downloads.mariadb.org|173.203.201.148|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 FOUND
場所: https://downloads.mariadb.org/f/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/?serve [続く]
--2017-03-25 11:42:43--  https://downloads.mariadb.org/f/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/?serve
downloads.mariadb.org:443 への接続を再利用します。
HTTP による接続要求を送信しました、応答を待っています... 302 FOUND
場所: http://ftp.hosteurope.de/mirror/archive.mariadb.org//mariadb-10.0.13/source/mariadb-10.0.13.tar.gz [続く]
--2017-03-25 11:42:43--  http://ftp.hosteurope.de/mirror/archive.mariadb.org//mariadb-10.0.13/source/mariadb-10.0.13.tar.gz
ftp.hosteurope.de をDNSに問いあわせています... 2a01:488:10:1::50ed:888a
ftp.hosteurope.de|2a01:488:10:1::50ed:888a|:80 に接続しています... 失敗しました: ネットワークに届きません.

```

**Comment by ryfjwr** [comment]
ここのページを二回行ったり来たりしたら、ダウンロード出来た。何故だ...

https://downloads.mariadb.org/mariadb/10.0.13/

**Comment by ryfjwr** [comment]
here って書いてるんでこっから

https://downloads.mariadb.org/interstitial/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz/from/http%3A//ftp.hosteurope.de/mirror/archive.mariadb.org/

![screen shot 2017-03-25 at 11 45 07](https://cloud.githubusercontent.com/assets/713034/24318873/8cc89304-1150-11e7-9b2c-6a48b9cc2a39.png)

**Comment by ryfjwr** [comment]
```
$ wget  https://downloads.mariadb.org/f/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz
--2017-03-25 11:46:25--  https://downloads.mariadb.org/f/mariadb-10.0.13/source/mariadb-10.0.13.tar.gz
downloads.mariadb.org をDNSに問いあわせています... 173.203.201.148
downloads.mariadb.org|173.203.201.148|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 302 FOUND
場所: http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb//mariadb-10.0.13/source/mariadb-10.0.13.tar.gz [続く]
--2017-03-25 11:46:26--  http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb//mariadb-10.0.13/source/mariadb-10.0.13.tar.gz
ftp.yz.yamagata-u.ac.jp をDNSに問いあわせています... 133.24.248.19, 133.24.248.18, 2001:df0:25e:e100::3, ...
ftp.yz.yamagata-u.ac.jp|133.24.248.19|:80 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 404 Not Found
2017-03-25 11:46:36 エラー 404: Not Found。
```

**Comment by ryfjwr** [comment]
よくよく読んだらこう書いてる

If the mirror is down or returns 'file not found', click here to try a different mirror or return to the downloads page and select a new mirror.

**Comment by ryfjwr** [comment]
インターネットにつながってない？

```
$ wget google.com
--2017-03-25 11:49:11--  http://google.com/
google.com をDNSに問いあわせています... 2404:6800:4004:809::200e
google.com|2404:6800:4004:809::200e|:80 に接続しています... 失敗しました: ネットワークに届きません.
```

**Comment by ryfjwr** [comment]
ipv6 無効にする？

**Comment by ryfjwr** [comment]
centos ipv6 無効

でググる

**Comment by ryfjwr** [comment]
ここでググると良いか

http://blog.redbox.ne.jp/disable-ipv6-centos6.html

**Comment by ryfjwr** [comment]
↑ のサイトは、こう書いている

```
/etc/sysconfig/networkにNETWORKING_IPV6=という項目を追記している方は、項目を削除していただくか明示的にNETWORKING_IPV6=noと記載しておきます。

ここまでは今までのCentos5と同じ作業ですがCentos６はさらに以下のようにカーネルの設定で無効にする必要があります。
```

**Comment by ryfjwr** [comment]
ここからやったほうがよいか？

http://www.1x1.jp/blog/2013/03/disable_ipv6_on_centos6.html

**Comment by ryfjwr** [comment]
これをやれとな？

```
# ipv6 disable
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```

**Comment by ryfjwr** [comment]
以下の方法で出来るかな

```
$ sudo vim /etc/sysctl.conf 

# ipv6 disable
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```

```
$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:8E:A1:0E
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10486 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6674 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:785358 (766.9 KiB)  TX bytes:648611 (633.4 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:98:A5:27
          inet addr:192.168.44.99  Bcast:192.168.44.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:347 errors:0 dropped:0 overruns:0 frame:0
          TX packets:49 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:29428 (28.7 KiB)  TX bytes:7846 (7.6 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:17647 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17647 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:967883 (945.1 KiB)  TX bytes:967883 (945.1 KiB)
```

**Comment by ryfjwr** [comment]
IPv6 切っても、ソースのダウンロードに失敗している。。。。

http://ftp.hosteurope.de/mirror/archive.mariadb.org//mariadb-10.0.13/source/mariadb-10.0.13.tar.gz

**Comment by ryfjwr** [comment]
ブラウザからは落とせるんで、vagrant の sync するやつで行く

**Comment by ryfjwr** [comment]
これを使ってみる

http://qiita.com/okoi/items/8fbf87772217c1b1ffb7

**Comment by ryfjwr** [comment]
地道に sync して mariadb のソースを移す

**Comment by ryfjwr** [comment]
vagrant で scp 

http://qiita.com/suzuki_koya/items/a9e3b261a783070ea0b6

**Comment by ryfjwr** [comment]
ローカルのホスト

http://qiita.com/sxo/items/2a2ce57a84b90100a20d

**Comment by koic** [comment]
http://koic.hatenablog.com/entry/2016/12/26/000000 の `invernizzi/vagrant-scp` のくだりをどうぞ。

**Comment by ryfjwr** [comment]
↑ vagrant-scp でかいけつ❗

**Comment by ryfjwr** [comment]
今度こそ！

http://mroonga.org/ja/docs/install/others.html#build-from-source

**Comment by ryfjwr** [comment]
これのコマンドのアレが死亡！

```
% wget http://packages.groonga.org/source/mroonga/mroonga-6.12.tar.gz
% tar xvzf mroonga-6.12.tar.gz
% cd mroonga-6.12
% ./configure \
    --with-mysql-source=/usr/local/src/mysql-5.6.21 \
    --with-mysql-build=/usr/local/build/mysql-5.6.21 \
    --with-mysql-config=/usr/local/mysql/bin/mysql_config
% make
% sudo make install
% /usr/local/mysql/bin/mysql -u root < /usr/local/share/mroonga/install.sql
```

```
$ wget http://packages.groonga.org/source/mroonga/mroonga-6.12.tar.gz
--2017-03-25 12:10:17--  http://packages.groonga.org/source/mroonga/mroonga-6.12.tar.gz
packages.groonga.org をDNSに問いあわせています... 157.7.238.131
packages.groonga.org|157.7.238.131|:80 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 404 Not Found
2017-03-25 12:10:37 エラー 404: Not Found。
````

**Comment by ryfjwr** [comment]
ここから一覧を見ると、`6.12` が無くて死亡！

http://packages.groonga.org/source/mroonga/

**Comment by ryfjwr** [comment]
これなら通った。

```
$ wget http://packages.groonga.org/source/mroonga/mroonga-6.13.tar.gz
```

**Comment by ryfjwr** [comment]
無理だったっぽい

```
$ ./configure --with-mysql-source=/home/vagrant/mariadb-10.0.13 --with-mysql-build=/home/vagrant/mariadb-10.0.13  --with-mysql-config=/usr/bin/mysql_config

checking if gcc supports -Wall... yes
checking if g++ supports -Wall... yes
checking if gcc supports -Wextra... yes
checking if g++ supports -Wextra... yes
checking if gcc supports -Wno-unused-parameter... yes
checking if g++ supports -Wno-unused-parameter... yes
checking if gcc supports -Wno-strict-aliasing... yes
checking if g++ supports -Wno-strict-aliasing... yes
checking if gcc supports -Wno-deprecated... yes
checking if g++ supports -Wno-deprecated... yes
checking for the suffix of plugin shared libraries... .so
checking mysql source... configure: error: invalid MySQL source directory
```

**Comment by kou** [comment]
いろいろフィードバックチャンスあってやったー！

**Comment by ryfjwr** [comment]
# フィードバックの対象

- Mroonga 公式ドキュメントに Mroonga アンインストールの手順が無い

**Comment by ryfjwr** [comment]
# 開発者向けのまとめ

## Background 

- [Mroonga の ドキュメント](http://mroonga.org/ja/docs/index.html) には、インストール手順が書かれているようでした。
- しかしながら、アンインストールの手順に関しては、手順が無い様でした。
- Mroonga をインストール済の方を対象に、アンインストールガイドを追加してはいかがでしょうか

**Comment by ryfjwr** [comment]
# 開発者向けにする

- 概要は良い。
- この方法でインストールしたというやり方が書いてある。
- MariaDB のバージョンを書いておいた方が良い。

# Etc

- issue 等で周りの人が使っている言語で書きましょう。

**Comment by ryfjwr** [comment]
# Title

- Add Uninstall Guide for Mroonga

# Background

- There is only [install guide](http://mroonga.org/ja/docs/install.html) for Mroonga at Official site.
-  But, no document exists when developer uninstalls Mroonga, without removing MySQL or  MariaDB.

# Environment

- OS: Linux(as for me, CentOS 6.5)
- Installed MariaDB or MySQL(for me, MariaDB `10.0.13`)
- Installed Mroonga by source code.
  - for me, [this way](http://mroonga.org/ja/docs/install/others.html#build-from-source).
- Used Mroonga by MySQL's Plugin. 

# Expectation

- I propose publishing uninstall Mroonga guide for developer who already installed Mroonga.

**Comment by kou** [comment]
やったね！
