### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: masasjp: kaminari: Work log

### ISSUE THREAD

**Issue by masasjp** [oss-gate/workshop#334]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by masasjp** [comment]
こちらこそよろしくお願いします！

**Comment by masasjp** [comment]
感じている問題点が、本当に問題なのかがわからない。
もしかして、実装済みの機能で対応できるのかもしれない。

**Comment by masasjp** [comment]
まず感じている問題点の整理をする？

**Comment by masasjp** [comment]
まず発生していたバージョンの確認をする

**Comment by masasjp** [comment]
発生していたのは kaminari(0.17.0)
最新の開発バージョンはどこを見たらいいんだっけ？？

**Comment by masasjp** [comment]
githubのリリースページでlatest releaseが0.17.0と確認
https://github.com/kaminari/kaminari/releases

**Comment by masasjp** [comment]
問題を再現させる？
リファレンスをさらに熟読？

**Comment by masasjp** [comment]
問題の状況を整理する

**Comment by masasjp** [comment]
web apiへ通信して大量の json の配列を受け取る
そのデータをページネートしたい

**Comment by masasjp** [comment]
機能があるかどうか
- ソースを見る
- リファレンスを見る

**Comment by masasjp** [comment]
リファレンスは既にそこそこ見ているのでソースを少し見て見る

**Comment by masasjp** [comment]
どこを見ていったらいいだろう
arrayをpaginateするあたり？

**Comment by masasjp** [comment]
gem内をarrayでサーチ中
array_extension.rbを見てる

**Comment by masasjp** [comment]
もしかして、active recordの実装見ると、"apiへのリクエスト"への付け替えの可能性がわかるかしら？

**Comment by koyhoge** [comment]
実践的でもし実装されれば役に立つ機能だと思いました。
ソースがどのように設計されているのかを探るのは案外大変ですが、がんばってみると良い経験になるのではと思います。

**Comment by masasjp** [comment]
作業履歴の説明がめちゃくちゃしやすい

**Comment by masasjp** [comment]
issueが既にないかチェック

**Comment by masasjp** [comment]
これは何をいっている？
https://github.com/kaminari/kaminari/issues/716

**Comment by masasjp** [comment]
少し違うようなのでissue素案を作成する

**Comment by masasjp** [comment]
問題点:
arrayをページネートするとき、全配列が必要
web apiがデータソースの場合、全データ取得はweb apiに負荷がかかりすぎる。

per pageの件数毎にリクエストするようにしたい。

**Comment by masasjp** [comment]
全件数とか、設定する値の例もある方がいいよね

**Comment by onk** [comment]
json-api-resources を使っていて、
kaminari で上手にページネートしたい

`Kaminari::PaginateArray` を使うと配列を受け取れるので自アプリ内でのページネートができるが、
単なる配列だと全件持つ必要があって、API の先に負荷をかけてしまう。

そこで、API の endpoint や paginate 用のクエリパラメータ等を `Kaminari::ApiArray` のようなものを作って、めちゃくちゃ簡単に API + kaminari を使えるようになっていれば良いと考えた。

----

ここまでだと巨大機能なので少し切り分けたくて、

* API にページネートしたリクエストを投げて
* `Kaminari::PaginateArray` にそのレスポンスを設定し
* ページ数や全件数を上手に設定する

と、上記の `Kaminari::ApiArray` を実装できそう。

で、ページ数や全件数を設定する方法があるのかを知りたい。

**Comment by onk** [comment]
やり方を調べたが分からなかったので、よくある使い方に上記を乗せてくれないか
という提案に落とし込むのはアリなんじゃないかと思いました。

**Comment by masasjp** [comment]
今後web apiがデータソースになるケースは増える
kaminariで簡単にそのデータ(配列)をページネートできるといいと思う。

**Comment by masasjp** [comment]
kaminariでweb apiのデータを簡単に扱えるようにすべきだ
kaminariの実装でそれを実現されてもいいし、または、やり方をリファレンスにわかりやすく書かれていてもいいと思う

**Comment by kou** [comment]
お疲れ様でした！

**Comment by knokmki612** [comment]
私のつたない英語です

I think increasing case of use web api in data source
I would like to paginate these array data in kaminari
It is happy if add new feature in kaminari or written "HOW TO" in reference document for user

**Comment by masasjp** [comment]
お疲れ様でした！

@knokmki612 
わざわざありがとうございます！
