### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: @u16suzu: capistrano-bundler: Work log

### ISSUE THREAD

**Issue by u16suzu** [oss-gate/workshop#336]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by keisei1092** [comment]
cheers!

**Comment by vividmuimui** [comment]
🎉

**Comment by ryfjwr** [comment]
みました！

**Comment by koic** [comment]
👀

**Comment by u16suzu** [comment]
capistranoはデプロイツールなので、デプロイするものを決めないといけない。

**Comment by u16suzu** [comment]
rails new blog とかしてみる

**Comment by u16suzu** [comment]
ここを読んで始める。
https://github.com/capistrano/bundler

**Comment by u16suzu** [comment]
readme.md の Installation を読んでみて、rails じゃなくても動きそう？？と思った。

**Comment by u16suzu** [comment]
うーん。Gemfile と system どっちに入れればいいかな？？

**Comment by u16suzu** [comment]
リーデミーのUsageを読む https://github.com/capistrano/bundler#usage

**Comment by u16suzu** [comment]
Require in Capfile to use the default task:
デフォルトのタスクを使うために Capfile で require する
require 'capistrano/bundler'

The task will run before deploy:updated as part of Capistrano's default deploy, or can be run in isolation with cap production bundler:install

このデフォルトタスクは `deploy:updated` の前に Capistrano のデフォルトデプロイとして実行される、
または、cap productin bundle:install の中で単独で実行される

By default, the plugin adds bundle exec prefix to common executables listed in bundle_bins option. This currently applies for gem, rake and rails.

You can add any custom executable to this list:
カスタムな動作を指定できる
```
set :bundle_bins, fetch(:bundle_bins, []).push('my_new_binary')
```

**Comment by u16suzu** [comment]
installの所に書いてあるけど、どっちがオススメか判断基準がわからない。

**Comment by u16suzu** [comment]
できれば、システムに入れると、自分の開発環境に入ってしまって、他のプロダクトが
影響を受けるかもしれないので、Gemfile の方がオススメだよと書いてあると
判断材料になって良いと思った。

**Comment by u16suzu** [comment]
こんなGemfileを書いて、bundle したらエラーが出た。
```text
gem 'capistrano', '~> 3.6'
gem 'capistrano-bundler', '~> 1.2'
```

エラー

```text
u16suzu@MBP ~/RubymineProjects/oss-gate
$ bundle
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'capistrano (~> 3.6)' in any of the gem sources listed in your Gemfile.
```

**Comment by u16suzu** [comment]
Readme には　`Add these lines to your application's Gemfile:` と書いてあったので
すでにrailsなどの application が入っている想定のため、source 'https://rubygems.org' はすでに
書いてある想定だったのかな？

**Comment by u16suzu** [comment]
source 'https://rubygems.org' をGemfileに書いて bundle コマンドを実行したらインストールできた。

Gemfile
```
source 'https://rubygems.org'

gem 'capistrano', '~> 3.6'
gem 'capistrano-bundler', '~> 1.2'
```

```
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing rake 12.0.0
Installing net-ssh 4.1.0
Installing i18n 0.8.1
Using bundler 1.14.4
Installing net-scp 1.2.1
Installing sshkit 1.13.0
Installing airbrussh 1.1.2
Installing capistrano 3.8.0
Installing capistrano-bundler 1.2.0
Bundle complete! 2 Gemfile dependencies, 9 gems now installed.
Bundled gems are installed into ./bun_path.
```

**Comment by u16suzu** [comment]
bundle コマンドの実行ログから `capistrano-bundler` の依存gemが色々入ったようなので見る。

**Comment by u16suzu** [comment]
bundle コマンドの実行結果の
```
Using bundler 1.14.4
```
は、システムに既存のbundlerを使うので、インストールしなかったということなのかな？

**Comment by u16suzu** [comment]
https://github.com/capistrano/bundler#usage にCapfileに

```
require 'capistrano/bundler'
```

をかけとあるけど、Capfileがない。

**Comment by u16suzu** [comment]
safari ブラウザが落ちた。珍しい。

**Comment by u16suzu** [comment]
capistrano にCapfile を作るコマンドがあるのそれで作る。
capistranoの本家サイトでコマンドを確認する. https://github.com/capistrano/capistrano#capify-your-project

あった。

```
"Capify" your project

Make sure your project doesn't already have a "Capfile" or "capfile" present. Then run:

$ bundle exec cap install
```

**Comment by u16suzu** [comment]
ちょっと奥の方にあって探しづらい

**Comment by u16suzu** [comment]
Capfileできた。

```bash
$ bundle exec cap install
mkdir -p config/deploy
create config/deploy.rb
create config/deploy/staging.rb
create config/deploy/production.rb
mkdir -p lib/capistrano/tasks
create Capfile
Capified
```

**Comment by u16suzu** [comment]
Capfile に require 'capistrano/bundler' とコメントアウトですでにあったので、
それをアンコメントアウトにする。

**Comment by u16suzu** [comment]
ローカルにデプロイしようとしたけど、macにsshサーバが立っていないので失敗した。

ssh サーバをマックに立てる

https://rcmdnk.com/blog/2013/10/29/computer-mac/

**Comment by kou** [comment]
ドキュメント周りでフィードバックできるかも！

**Comment by u16suzu** [comment]
### 問題と感じていること
- capistrano-bundler の READMEのInstallation部分を読んで、gemを入れる際に、gemのインストール先をローカルディレクトリとシステムのどちらにしたらよいか判断に迷いました
- できれば、作者のお勧めがあれば、そちらをInstallationに書いておくとよいと思いました。

```md
## Installation

Add these lines to your application's Gemfile:

```ruby
gem 'capistrano', '~> 3.6'
gem 'capistrano-bundler', '~> 1.2'
```

And then execute:

```sh
$ bundle
```

Or install it yourself as:

```sh
$ gem install capistrano-bundler
```
```

### どうなれば良いか?
- 自分は `Gemfile` に書いて、ローカルディレクトリにインストールをしたほうが良いと思います。
- 以下のように、お勧め情報の方に [Recommended] と一言書いておくとよいと思います。

```md
## Installation

Add these lines to your application's Gemfile **[Recommended]**:

```ruby
gem 'capistrano', '~> 3.6'
gem 'capistrano-bundler', '~> 1.2'
```

And then execute:

```sh
$ bundle
```

Or install it yourself as:

```sh
$ gem install capistrano-bundler
```
```

**Comment by u16suzu** [comment]
Hello I am Yuichiro Suzuki(u16suzu) from Japan.
I have an opinion to README.

### What's problem?
- At [READMEのInstallation](https://github.com/capistrano/bundler/blob/master/README.md#installation),
I could not decide which one is best installation way for me (install to system or local directory).
- If you have a recommendation way, the way should be written on installation.

```text
Add these lines to your application's Gemfile:

gem 'capistrano', '~> 3.6'
gem 'capistrano-bundler', '~> 1.2'

And then execute:

$ bundle

Or install it yourself as:

$ gem install capistrano-bundler
```

### Expected
- For avoiding unintended effects to other projects on local machine.
- I think, the gem should be install to local directory by installation using Gemfile.

- An word [Recommended] is written on the recommended way.
- As below.

```text
Add these lines to your application's Gemfile **[Recommended]**:

gem 'capistrano', '~> 3.6'
gem 'capistrano-bundler', '~> 1.2'

And then execute:

$ bundle

Or install it yourself as:

$ gem install capistrano-bundler
```

**Comment by kou** [comment]
How about adding `[Recommended]` to the recommended way like the following:

```text
...
```

**Comment by kou** [comment]
最後のふりかえり、あとでやろうと思っていたのにそのまま終わりにしてしまってすみませんでした。。。

送ったpull requesttはマージされていましたね！
この調子でこれからも「こうなっていたほうがよさそうだなぁ」というところをフィードバックしていってください！

**Comment by u16suzu** [comment]
@kou はい！無事マージされました。とても嬉しいです。ありがとうございます。 😄

**Comment by u16suzu** [comment]
翌日、無事マージされましたー。https://github.com/capistrano/bundler/pull/91
