### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: kanpou0108: activerecord : Work log

### ISSUE THREAD

**Issue by kanpou0108** [oss-gate/workshop#337]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by y-goto** [comment]
よろしくお願いします。

**Comment by kanpou0108** [comment]
active recordのgithubページを検索

**Comment by kanpou0108** [comment]
「rails activerecord github」でググると一番上に出てきた
https://github.com/rails/rails/tree/master/activerecord

**Comment by kanpou0108** [comment]
動かしてみたいので、install方法をページ内で確認

**Comment by kanpou0108** [comment]
ページ内で「install」で検索した所、「Download and installation」が見つかったので、読んで見る

**Comment by kanpou0108** [comment]
$ gem install activerecord
を実行しろとあるので、自分のPC上で実行してみる

**Comment by kanpou0108** [comment]
ターミナルを開く

**Comment by kanpou0108** [comment]
実行した結果、エラーは出ないので成功した。

```text
╰─○ gem install activerecord
Fetching: i18n-0.8.1.gem (100%)
Successfully installed i18n-0.8.1
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: activesupport-5.0.2.gem (100%)
Successfully installed activesupport-5.0.2
Fetching: activemodel-5.0.2.gem (100%)
Successfully installed activemodel-5.0.2
Fetching: arel-7.1.4.gem (100%)
Successfully installed arel-7.1.4
Fetching: activerecord-5.0.2.gem (100%)
Successfully installed activerecord-5.0.2
8 gems installed
```

**Comment by kanpou0108** [comment]
ARを動かすためにはDBが必要なので、どのDBを使うかを選択する。
sqliteかPostgreSQLがよさそう。
PostgreSQLを選択してみる。

**Comment by kanpou0108** [comment]
PostgreSQLは自分のPCにインストール済みなので起動する。

**Comment by kanpou0108** [comment]
コマンド起動(Alfred)で「postgres」と入力して実行。
DBが起動したと思われる。
念の為、モニターで確認。

**Comment by kanpou0108** [comment]
モニターでもpsコマンドでも動いていることを確認できた.

**Comment by kanpou0108** [comment]
ARのgithubページ内に「examples」フォルダがあったので、開いてみる。

**Comment by kanpou0108** [comment]
READMEなどはないが、サンプルっぽい.rbファイルがあった。
しかし、この.rbファイルはsqliteを対象としていた。

**Comment by kanpou0108** [comment]
まずはサンプルの.rbファイルを動かすために、まずはsqliteで動かしてみることにする。
※READMEなどにサンプルがsqliteであることが記載されていれば親切なのに、と思った。

**Comment by kanpou0108** [comment]
sqliteが自分のPCに入っているか確認する。
homebrewで入れたような気がするので確認してみる。

**Comment by kanpou0108** [comment]
入っていた。
```text
╰─○ brew list |grep -i sqlite
sqlite
```

**Comment by kanpou0108** [comment]
メモ
※サンプルの.rbファイルにsqliteのバージョンは特に記載されていない。

**Comment by kanpou0108** [comment]
sqliteを動かすには、.sqliteファイル？が必要だったと思うが自信がない。
sqliteの公式サイトを探してみる

**Comment by kanpou0108** [comment]
「sqlite」ググったところ、公式サイトっぽいのが2番目に出てきた
https://www.sqlite.org/

**Comment by kanpou0108** [comment]
Latest Release:   Version 3.17.0 (2017-02-13)
と書かれていた。自分のsqliteのバージョンが気になったので確認してみる。

**Comment by kanpou0108** [comment]
3.8.10.2だった。

```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ sqlite --version
zsh: command not found: sqlite
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ sqlite3 --version
3.8.10.2 2015-05-20 18:17:19 2ef4f3a5b1d1d0c4338f8243d40a2452cc1f7fe4
```

**Comment by kanpou0108** [comment]
sqliteの公式サイトのトップに「Getting Started」を見つけたので開いてみた。
https://www.sqlite.org/quickstart.html

**Comment by kanpou0108** [comment]
以下によると
```text
$ sqlite3  XXX.db
```
でXXX.dbファイルが作成されるみたいだった。とりあえず実行してみる。

```text
Create A New Database

At a shell or DOS prompt, enter: "sqlite3 test.db". This will create a new database named "test.db". (You can use a different name if you like.)

Enter SQL commands at the prompt to create and populate the new database.

Additional documentation is available here.
```

**Comment by kanpou0108** [comment]
実行した結果、いきなりプロンプトが起動した。

```text
╰─○ sqlite3 test.db
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite>
```

**Comment by kanpou0108** [comment]
ディレクトリ内に、test.dbが作成された確認するためにターミナルをもう一つ開いてみる

**Comment by kanpou0108** [comment]
まだ作成されていないようだった。

**Comment by kanpou0108** [comment]
```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ ls -al
total 0
drwxr-xr-x    2 ihara staff   68  3 25 10:26 .
drwxr-xr-x+ 204 ihara staff 6936  3 25 11:39 ..
```

**Comment by kanpou0108** [comment]
ARのgithubページにexamplesの動かし方が書いてないか再確認してみる

**Comment by kanpou0108** [comment]
そんなに長くないので上から読んで見る

**Comment by kanpou0108** [comment]
トップページのLearn moreリンクが切れてた

```
Automated mapping between classes and tables, attributes and columns.

class Product < ActiveRecord::Base
end
Learn more
```
https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/Base.html

**Comment by kanpou0108** [comment]
トップページのLearn moreリンクは殆どが404になっている

**Comment by kanpou0108** [comment]
トップページの情報は既に使い方はわかっている人向けだと感じた

**Comment by kanpou0108** [comment]
リンク切れになっているURLで検索した所 issueを発見した。
「https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/ConnectionAdapters/SQLite3Adapter.html」で検索した所以下が1番上でだった。
https://github.com/rails/rails/issues/28256

**Comment by kanpou0108** [comment]
動かし方はトップページには書かれていない。
なのでとりあえずサンプルのrbファイルを動かす方向でDBを作る。
https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb

**Comment by kanpou0108** [comment]
sqliteでDBを作成する方法を確認する。
「sqlite create db file」で検索した所、以下がトップに出てきた。
公式サイトではないが、こちらで確認してみる。
https://www.tutorialspoint.com/sqlite/sqlite_create_database.htm

**Comment by kanpou0108** [comment]
.databasesコマンドを実行した時点で、test.dbファイルが作成されたみたい。

```text
sqlite> .databases
seq  name             file
---  ---------------  ----------------------------------------------------------
0    main             /Users/ihara/oss_handson_20170325/test.db
sqlite>
```

**Comment by kanpou0108** [comment]
.quitコマンドでプロンプトから脱出。

```text
sqlite>
sqlite> .quit
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ ll
total 0
drwxr-xr-x    3 ihara staff  102  3 25 12:03 .
drwxr-xr-x+ 204 ihara staff 6936  3 25 12:05 ..
-rw-r--r--    1 ihara staff    0  3 25 12:03 test.db
```

**Comment by kanpou0108** [comment]
以下のサンプルファイルではファイル内で
create_table
しているみたいなので、準備した後にまずは実行してみる。

またdatabase名が"foobar.db"なので、これに合わせるため、foobar.dbファイルを作成する。

```rb
require "active_record"

class Person < ActiveRecord::Base
  establish_connection adapter: "sqlite3", database: "foobar.db"
  connection.create_table table_name, force: true do |t|
    t.string :name
  end
end

bob = Person.create!(name: "bob")
puts Person.all.inspect
bob.destroy
puts Person.all.inspect
```

**Comment by kanpou0108** [comment]
foobar.dbを作成した。

```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ sqlite3 foobar.db
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite>
sqlite> .databases
seq  name             file
---  ---------------  ----------------------------------------------------------
0    main             /Users/ihara/oss_handson_20170325/foobar.db
sqlite>
sqlite>
sqlite> .quit
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ l
total 0
drwxr-xr-x    3 ihara staff  102  3 25 12:08 .
drwxr-xr-x+ 204 ihara staff 6.8K  3 25 12:09 ..
-rw-r--r--    1 ihara staff    0  3 25 12:08 foobar.db
```

**Comment by kanpou0108** [comment]
同ディレクトリにsample.rbを作成した。

```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ l
total 4.0K
drwxr-xr-x    4 ihara staff  136  3 25 12:10 .
drwxr-xr-x+ 204 ihara staff 6.8K  3 25 12:10 ..
-rw-r--r--    1 ihara staff    0  3 25 12:08 foobar.db
-rw-r--r--    1 ihara staff  304  3 25 12:10 sample.rb
```

**Comment by kanpou0108** [comment]
実行したところ、以下のエラーが発生。

```
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ ruby sample.rb
/Users/ihara/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/connection_specification.rb:176:in `rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
	from /Users/ihara/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/connection_specification.rb:173:in `spec'
	from /Users/ihara/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:53:in `establish_connection'
	from sample.rb:4:in `<class:Person>'
	from sample.rb:3:in `<main>'
```

**Comment by kanpou0108** [comment]
```text
Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
```
とあるので、sqlite3 gem が入っているか確認。

**Comment by kanpou0108** [comment]
入ってない。

```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ gem list |grep -i sqlite
```

**Comment by kanpou0108** [comment]
sqlite3 gemを入れた

```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ gem i sqlite3
Fetching: sqlite3-1.3.13.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.13
1 gem installed
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ gem list |grep -i sqlite
sqlite3 (1.3.13)
```

**Comment by kanpou0108** [comment]
sample.rbファイルの実行に成功した。

```text
╭─ihara@iharaMBP ‹2.4.0› ~/oss_handson_20170325
╰─○ ruby sample.rb
#<ActiveRecord::Relation [#<Person id: 1, name: "bob">]>
#<ActiveRecord::Relation []>
```

**Comment by kanpou0108** [comment]
ARのgithubページのリンク切れ問題で、
「
link https://github.com/rails/rails/blob/master/activerecord/classes/ActiveRecord/Base.html
」
で検索した所、3番目に関連しそうなページが出てきた。
'Learn more' links are broken on the active record README page · Issue #17976 · rails/rails
https://github.com/rails/rails/issues/17976

**Comment by knokmki612** [comment]
ふりかえりました！

activerecord

* examplesフォルダへのリンクとサンプルコードがある説明がほしい
* サポートされているDBはもっと目立つ位置に説明があってもよいのでは！？  
> Learn more and read about the built-in support for MySQL, PostgreSQL, and SQLite3.
* 自動生成されたページとリンク切れの話はなんらかの対応が必要そう

sqlite3

* `sqlite3 test.db` するだけではtest.dbというファイルが作成されないので、説明を書き換えたほうが良さそう

**Comment by kanpou0108** [comment]
午後やろうとすること
activerecord
・トップページにARの試し方(getting started)的な記載を追加したい。
・examplesフォルダ内のsimple.rbを動かせたので、その手順をまとめる。
https://github.com/rails/rails/tree/master/activerecord
https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb

**Comment by kanpou0108** [comment]
もしかしたら、api.rubyonrails.orgの方にARのGetting Startedがあるかもしれないので、ちょっと探してみる。
http://api.rubyonrails.org/files/activerecord/README_rdoc.html

**Comment by kanpou0108** [comment]
ARのGuideページはあったが、Getting Startedはなさそう
http://guides.rubyonrails.org/active_record_basics.html

**Comment by kanpou0108** [comment]
色々検索したが、Getting Startedはなさそう。

Guideページの方のFeedbackの手順ページを発見した。
GithubのARの方のFeedback手順がないか確認してみる。

Contributing to Ruby on Rails — Ruby on Rails Guides
http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation

**Comment by kanpou0108** [comment]
「activerecord getting started」で検索してら、2番目にrailsのgetting startedは出てきた。
AR単体で動かすための公式のgetting startedはなさそう。

Getting Started with Rails — Ruby on Rails Guides
http://guides.rubyonrails.org/getting_started.html

「activerecord tutorial」でも同様に、AR単体で動かすための公式のgetting startedはなさそう。

**Comment by kanpou0108** [comment]
とりあえずドキュメントを作ってみる方針とする。
https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb
を動かすための手順を日本語で書く。
対象はsqliteなので、まずはその前提で書く。

**Comment by kanpou0108** [comment]
環境：Mac OS X El Capitan 10.11.6

1)
```text
$ brew install sqlite
```

**Comment by kanpou0108** [comment]
ActiveRecordのGithubトップページにActiveRecord単体で動かすためのGetting Startedの手順を記載しました。
https://github.com/rails/rails/tree/master/activerecord#download-and-installation

ご確認よろしくお願いします。

**Comment by kanpou0108** [comment]
▽Getting Started (for ActiveRecord Only)

1. install sqlite

2. install ActiveRecord
```text
$ gem install activerecord
```
3. install sqlite3
```text
$ gem install sqlite3
```

4. prepare `simple.rb` locally
https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb

5. execute `simple.rb`

$ ruby sample.rb
```text
#<ActiveRecord::Relation [#<Person id: 1, name: "bob">]>
#<ActiveRecord::Relation []>
```

※foobar.dbはsimple.rb実行前には存在しないが、simple.rb実行後に自動的に生成される

**Comment by kanpou0108** [comment]
▽Draft for PullRequest
Background：
Although there is a sample file for ActiveRecord, there is no procedure for executing sample file.
I think it is beneficial for beginner, if there is a procedure.


やったこと：
ActiveRecordのGithubトップページにActiveRecord単体で動かすためのGetting Startedの手順を記載しました。
https://github.com/rails/rails/tree/master/activerecord#download-and-installation

ご確認よろしくお願いします。

**Comment by kanpou0108** [comment]
Make Getting Started for ActiveRecord README.rdoc

**Comment by kanpou0108** [comment]
最終的にこれを作成しました。
https://github.com/rails/rails/pull/28566

**Comment by knokmki612** [comment]
フィードバックまで行き良かったです！

アサインされた人とやりとりしてPRが取り込まれるとよいですね！

**Comment by kou** [comment]
お疲れ様でした！
