### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: 23tk: natto: Work log

### ISSUE THREAD

**Issue by 23tk** [oss-gate/workshop#338]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by onk** [comment]
メンターの @onk です。
よろしくお願いします！

**Comment by 23tk** [comment]
ライセンスを確認したい

**Comment by 23tk** [comment]
https://opensource.org/licenses/alphabetical

**Comment by 23tk** [comment]
あった
2-clause BSD License (BSD-2-Clause)

**Comment by 23tk** [comment]
OSSということがわかった
のでとりあえず動かす

**Comment by 23tk** [comment]
一次資料のreadmeとかないだろうか

**Comment by 23tk** [comment]
日本語の形態素解析器なのに英語で書かれているのか・・・

**Comment by 23tk** [comment]
google翻訳は良くないらしい

**Comment by 23tk** [comment]
インストールする
gem install natto

**Comment by 23tk** [comment]
```
gem install natto
```

**Comment by 23tk** [comment]
```
FUMITAKAnoMacBook-Air:~ fumitaka$ gem install natto
Fetching: ffi-1.9.18.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
FUMITAKAnoMacBook-Air:~ fumitaka$ 
```

**Comment by 23tk** [comment]
googleで検索
    You don't have write permissions

**Comment by 23tk** [comment]
一番上にあったのでとりあえず見る
http://ameblo.jp/siroikinoko/entry-11059282205.html

**Comment by 23tk** [comment]
sudoでインストールできそう

**Comment by 23tk** [comment]
```
FUMITAKAnoMacBook-Air:~ fumitaka$ sudo gem install natto
Password:
Fetching: ffi-1.9.18.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.18
Fetching: natto-1.1.1.gem (100%)
Successfully installed natto-1.1.1
Parsing documentation for ffi-1.9.18
Installing ri documentation for ffi-1.9.18
Parsing documentation for natto-1.1.1
Installing ri documentation for natto-1.1.1
2 gems installed
FUMITAKAnoMacBook-Air:~ fumitaka$ 
```

**Comment by 23tk** [comment]
インストールできたので使って見る？

**Comment by 23tk** [comment]
Usageに使い方が書いてある

**Comment by 23tk** [comment]
```
require 'natto'
```
って何するコマンド？

**Comment by 23tk** [comment]
コマンドじゃないっぽい
宣言文？

**Comment by 23tk** [comment]
ググったところrubyの宣言文

**Comment by 23tk** [comment]
Usageはrubyのサンプルコード

**Comment by 23tk** [comment]
natto-test.rbを作成

**Comment by 23tk** [comment]
とりあえず実行

**Comment by 23tk** [comment]
```FUMITAKAnoMacBook-Air:test fumitaka$ ruby natto-test.rb 
/Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto/binding.rb:58:in `rescue in find_library': Please set MECAB_PATH to the full path to libmecab.dylib (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto/binding.rb:48:in `find_library'
	from /Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto/binding.rb:64:in `<module:Binding>'
	from /Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto/binding.rb:6:in `<module:Natto>'
	from /Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto/binding.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto/natto.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/natto-1.1.1/lib/natto.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from natto-test.rb:1:in `<main>'
FUMITAKAnoMacBook-Air:test fumitaka$ 
```

**Comment by 23tk** [comment]
Mecabのパスをセットする必要がある
Mecabがない

**Comment by 23tk** [comment]
Mac Mecabでググる

**Comment by 23tk** [comment]
一時情報を見た方が良いらしい

**Comment by 23tk** [comment]
http://taku910.github.io/mecab/#download

**Comment by 23tk** [comment]
http://taku910.github.io/mecab/
バグ修正とかしてるのでおそらく一次情報

**Comment by 23tk** [comment]
ソースをダウンロード

**Comment by 23tk** [comment]
インストールする

**Comment by 23tk** [comment]
macのインストール方法は載っていない
UNIXはMacではない

**Comment by 23tk** [comment]
ここで二次情報を探す

**Comment by 23tk** [comment]
Mac Mecabで検索
一番上のページを見る

**Comment by 23tk** [comment]
http://qiita.com/ichiroex/items/c330413d5bc286df4801

**Comment by 23tk** [comment]
./configure --enable-utf8-only --prefix=/opt/local/
インストール

**Comment by 23tk** [comment]
cakebrewからもインストールして見た

**Comment by 23tk** [comment]
とりあえず実行してみる
```
FUMITAKAnoMacBook-Air:mecab-0.996 fumitaka$ mecab
param.cpp(69) [ifs] no such file or directory: /usr/local/lib/mecab/dic/ipadic/dicrc
```

**Comment by 23tk** [comment]
IPA辞書を入れる

**Comment by 23tk** [comment]
cakebrewにmecab-ipadicがあるのでインストールする

**Comment by 23tk** [comment]
とりあえずできた
```FUMITAKAnoMacBook-Air:mecab-0.996 fumitaka$ mecab
すもももももももものうち
すもも	名詞,一般,*,*,*,*,すもも,スモモ,スモモ
も	助詞,係助詞,*,*,*,*,も,モ,モ
もも	名詞,一般,*,*,*,*,もも,モモ,モモ
も	助詞,係助詞,*,*,*,*,も,モ,モ
もも	名詞,一般,*,*,*,*,もも,モモ,モモ
の	助詞,連体化,*,*,*,*,の,ノ,ノ
うち	名詞,非自立,副詞可能,*,*,*,うち,ウチ,ウチ
EOS
```

**Comment by 23tk** [comment]
これでnattoを動かしてみる

**Comment by 23tk** [comment]
```
irb
```
を使う

**Comment by y-goto** [comment]
振り返りをしました。「初心者向けの案内を書いてみて投稿する」という方法で、貢献できるかもしれませんね。

**Comment by 23tk** [comment]
https://github.com/taku910/mecab/blob/master/index.html
Macでのインストール方法が分からなかったのでMacのインストールの項目を作って以下を追記したいです。
「homebrewでmecabを検索してインストールしてください」

**Comment by 23tk** [comment]
辞書のインストール方法は以下
「homebrewでmecab-ipadicを検索してインストールしてください」

**Comment by 23tk** [comment]
Macでのインストール方法が分からなかったのでMacのインストールの項目を作って以下を追記したいです。
---
インストール方法
$ brew install mecab
$ brew install mecab-ipadic
---

**Comment by 23tk** [comment]
Macでインストールする方法を追加しました。
Added method to install on Mac.

**Comment by 23tk** [comment]
やったこと
・フォーク
・クローン
・index.htmlの修正
・Hunkをステージへ移動
・コミット

**Comment by 23tk** [comment]
プルリクエストしたい

**Comment by 23tk** [comment]
コメントを考える

---

Macにはシンプルなインストール方法があります。
Mac has a simple installation.

---

**Comment by y-goto** [comment]
お疲れ様でした。フィードバックできてよかったですね。

**Comment by kou** [comment]
お疲れ様でした！
