### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: ktshun: fuelphp: Work log

### ISSUE THREAD

**Issue by ktshun** [oss-gate/workshop#339]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by cesare** [comment]
よろしくおねがいしますー。

**Comment by ktshun** [comment]
fuelphpで検索

**Comment by ktshun** [comment]
3番目に発見。1番上は日本語ドキュメント
https://fuelphp.com/

**Comment by ktshun** [comment]
downloadリンクを発見したのでダウンロード

**Comment by ktshun** [comment]
ダウンロードしたものを解凍

**Comment by ktshun** [comment]
リポジトリがzipで固まってるだけだった模様

**Comment by ktshun** [comment]
contributeタブを発見

**Comment by ktshun** [comment]
docsの中にquickstart発見

**Comment by ktshun** [comment]
書かれていたcurlを叩く

**Comment by ktshun** [comment]
次がcdだったのでディレクトリできてるのかと思ったら自分で作るんだった

**Comment by cesare** [comment]
`Site` というディレクトリがすでにある前提っぽいですね。

**Comment by cesare** [comment]
↑ https://fuelphp.com/docs/ を見ています。

**Comment by ktshun** [comment]
next stepへ進む

**Comment by ktshun** [comment]
1はドキュメントを読むだけ

**Comment by ktshun** [comment]
サーバーサイドにおけばもう動くということかな？

**Comment by cesare** [comment]
http://qiita.com/shuntaro_tamura/items/bdabcb77926dc92617b1
Mac のローカルの Apache で PHP を使うのはここらあたりが参考になりそうです。

**Comment by ktshun** [comment]
apacheの起動はできた。
http://nantekottai.com/2014/10/26/os-x-10-10-sites/
こっちも見てみてる

**Comment by cesare** [comment]
http://qiita.com/daei/items/aaa79e9486241bac8a8b
Mac で userdir を使う方法、これで行けますかね？

**Comment by ktshun** [comment]
↑で頂いたものでconfの設定をやり直し。

**Comment by ktshun** [comment]
http://localhost/~ktshun/blog/public/
にアクセスしてみる

**Comment by ktshun** [comment]
blog/fuel/app/logs
に書き込めないと怒られるのでパーミッションを変更

**Comment by ktshun** [comment]
date_default_timezone_get()
を使うな的なエラーに変わる

**Comment by ktshun** [comment]
![ss 2017-03-25 12 07 09](https://cloud.githubusercontent.com/assets/12622055/24319003/9f3eb736-1153-11e7-9a81-ce5bd30a7d2b.png)

**Comment by ktshun** [comment]
http://qiita.com/s0hno/items/55c54eaa120ef21f1ccb
これっぽい

**Comment by ktshun** [comment]
↑の実行でとりあえず動くようになった模様

**Comment by ktshun** [comment]
![ss 2017-03-25 12 15 41](https://cloud.githubusercontent.com/assets/12622055/24319059/d103069a-1154-11e7-9508-36b2734946da.png)

**Comment by onk** [comment]
```
cd Sites/
```

と Timezone のところで引っかかってましたが、Timezone の設定は 1 行先の

> Configure your new FuelPHP installation

https://fuelphp.com/docs/general/configuration.html

で、とても強く **ABSOLUTELY** と枠付きで紹介されている設定でした。

ドキュメント通りの順番で進めていたら詰まらなかったはずですし、これだけ派手に書いてあるのでフィードバックポイントではないなぁという感じですね。。

```
cd Sites/
```

の件については、一般的に PHP のアプリケーションは web サーバの管理下にあるディレクトリで開発するので、そのディレクトリに移動しろという指示ですが、
それが伝わらない、というフィードバックを送るのはアリなんじゃないかと思います。

他のフィードバックポイントを探すには次の Step 4 のチュートリアルを進めてみるか、
普段 Fuel に入れたいライブラリを入れながらライブラリのチュートリアルを進めてみるかを行うと良いんじゃないでしょうか。

**Comment by ktshun** [comment]
本家サイトの導入ではあまり引っかかるところがなかった（ちゃんとドキュメント呼んでいれば）ので、今回は日本語サイトの方での翻訳で少し見てみる。

**Comment by ktshun** [comment]
↑はすぐできそうなので、その前に本家のstep4をすすめてみる

**Comment by ktshun** [comment]
controllerを見てみるがあるはずのhelloがみれない。

**Comment by ktshun** [comment]
mod_rewriteが有効になっていないからではというアドバイスをいただき、有効化。見れた。

**Comment by ktshun** [comment]
step4リンクで飛ばされたページのcontrollerのexampleを動かしてみる

**Comment by ktshun** [comment]
```
class Controller_Example extends Controller
{

    public function action_index()
    {
        $data['css'] = Asset::css(array('reset.css','960.css','main.css'));
        return Response::forge(View::forge('welcome/index'));
    }
}
```
css読み込みでコケる。

**Comment by ktshun** [comment]
そんなファイルは存在してなかった。

**Comment by ktshun** [comment]
本家にはやはり突っ込みどころがあまりなかったため、日本語化の方でプルリクを送ることに。

**Comment by ktshun** [comment]
プルリク
https://github.com/NEKOGET/FuelPHP_docs_jp/pull/761

**Comment by kou** [comment]
お疲れ様でした！
