### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: keisei1092: rails: Work log

### ISSUE THREAD

**Issue by keisei1092** [oss-gate/workshop#340]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by ryfjwr** [comment]
👍

**Comment by vividmuimui** [comment]
rails! 👍

**Comment by keisei1092** [comment]
やっていきをするぞ

**Comment by koic** [comment]
👀

**Comment by u16suzu** [comment]
やっていくぞ！🎉

**Comment by keisei1092** [comment]
まずはRailsをローカル環境にインストールします

**Comment by keisei1092** [comment]
タブを開きすぎたのでタブを閉じます

**Comment by keisei1092** [comment]
RailsはMIT Licenseということを知った。OSS触りながらライセンス周りの知識も身につける。
https://github.com/rails/rails/blob/master/MIT-LICENSE

**Comment by keisei1092** [comment]
Railsのインストール方法を調べます。

**Comment by keisei1092** [comment]
Google 'rails install'.

**Comment by keisei1092** [comment]
あれ？検索結果の1番目にRailsInstallerがでてきたぞ。
RailsInstallerは既存の環境を汚しそう。なぜならRubyやSQL Serverのサポートなどを一緒にインストールするから。
なのでこれを使うのはやめたい・・・が、公式サイトではないので公式サイトに行くのが正しそう。

**Comment by keisei1092** [comment]
Google 'rails'

**Comment by keisei1092** [comment]
一番目にRuby on Railsのサイトがでてきた！

**Comment by keisei1092** [comment]
インストールしたいのでページ内をinstallで調べます

**Comment by keisei1092** [comment]
でない :(

**Comment by keisei1092** [comment]
公式サイト（rubyonrails.org）にデッカく `Latest version — Rails 5.1.0.rc1 released March 20, 2017` というボタンがあるのでタップします

**Comment by keisei1092** [comment]
なんかブログエントリっぽいのでてきた。

**Comment by keisei1092** [comment]
ここでもinstallでページ内検索します

**Comment by keisei1092** [comment]
`gem install rails -v 5.1.0.rc1` という文字列と
`Make sure you are using RubyGems 2.6.11 or later before trying to install a pre release, with:` という文字列がヒットした。

**Comment by keisei1092** [comment]
前者はコマンドであると判断したが、後者に「RubyGemsが2.6.11よりも高いことを確認してください」と書いてあるので先にRubyGemsのバージョンを確認します

**Comment by keisei1092** [comment]
`gem update --system 2.6.11` を実行します

**Comment by keisei1092** [comment]
先に今のバージョンを調べとけば良かったな〜

**Comment by keisei1092** [comment]
result

```bash
% gem update --system 2.6.11
Updating rubygems-update
Fetching: rubygems-update-2.6.11.gem (100%)
Successfully installed rubygems-update-2.6.11
Parsing documentation for rubygems-update-2.6.11
Installing ri documentation for rubygems-update-2.6.11
Installing darkfish documentation for rubygems-update-2.6.11
Done installing documentation for rubygems-update after 27 seconds
Parsing documentation for rubygems-update-2.6.11
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.6.11
RubyGems 2.6.11 installed
Parsing documentation for rubygems-2.6.11
Installing ri documentation for rubygems-2.6.11

=== 2.6.11 / 2017-03-16

Bug fixes:

* Fixed broken tests on ruby-head. Pull request #1841 by
  SHIBATA Hiroshi.
* Update vendored Molinillo to 0.5.7. Pull request #1859 by Samuel
  Giddins.
* Avoid activating Ruby 2.5 default gems when possible. Pull request #1843
  by Samuel Giddins.
* Use improved resolver sorting algorithm. Pull request #1856 by
  Samuel Giddins.

=== 2.6.10 / 2017-01-23

Bug fixes:

* Fix `require` calling the wrong `gem` method when it is overridden.
  Pull request #1822 by Samuel Giddins.

=== 2.6.9 / 2017-01-20

Bug fixes:

* Allow initializing versions with empty strings. Pull request #1767 by
  Luis Sagastume.
* Fix TypeError on 2.4. Pull request #1788 by Nobuyoshi Nakada.
* Don't output mkmf.log message if compilation didn't fail. Pull request
  #1808 by Jeremy Evans.
* Fixed broken links and overzealous URL encoding in gem server. Pull
  request #1809 by Nicole Orchard.
* Update vendored Molinillo to 0.5.5. Pull request #1812 by Samuel
  Giddins.
* RakeBuilder: avoid frozen string issue. Pull request #1819 by Olle
  Jonsson.

=== 2.6.8 / 2016-10-29

Bug fixes:

* Improve SSL verification failure message. Pull request #1751
  by Eric Hodel.
* Ensure `to_spec` falls back on prerelease specs. Pull request
  #1755 by André Arko.
* Update vendored Molinillo to 0.5.3. Pull request #1763 by
  Samuel Giddins.


------------------------------------------------------------------------------

RubyGems installed the following executables:
	/Users/keisei/.rbenv/versions/2.3.1/bin/gem

Ruby Interactive (ri) documentation was installed. ri is kind of like man
pages for ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

RubyGems system software updated
%
```

**Comment by keisei1092** [comment]
なるほど。アップデートがあるとプルリクの概要が表示されて便利。

**Comment by keisei1092** [comment]
`RubyGems system software updated` ということでRubyGemsがアップデートされたっぽい。
バージョンを確認します。

**Comment by keisei1092** [comment]
あれ？RubyGemsのバージョンってどうやって確認するんだ？

**Comment by keisei1092** [comment]
検索します
Google 'rubygems check version'

**Comment by keisei1092** [comment]
`gem -v` #ﾄﾉｺﾄ

**Comment by keisei1092** [comment]
execute it..

```bash
% gem -v
2.6.11
```

うむ。正常にアップデートされている。

**Comment by keisei1092** [comment]
RubyGemsのバージョン制約を越えたので、Railsをインストールするため次のコマンドを打ちます。
`gem install rails -v 5.1.0.rc1`
メモ：これやらずにコマンド打ってコケる人いるのでは。

**Comment by keisei1092** [comment]
`5.1.0.rc1` の `rc1` ってなんだ？

**Comment by keisei1092** [comment]
`rcとは` で検索してみる。

**Comment by keisei1092** [comment]
1番目に建築用語としてのRCが出てきたが、2番目にASCII.jpデジタル用語辞典が出てきた。

**Comment by keisei1092** [comment]
>  製品候補版のこと。ソフトウェアまたはハードウェアの開発において、ベータテストが完了し、製品候補のテスト段階に入ったものを指す。

#ﾄﾉｺﾄ

**Comment by keisei1092** [comment]
たぶん `Release Candidate` の略？

**Comment by keisei1092** [comment]
とりあえず次に進みます

**Comment by keisei1092** [comment]
```bash
% gem install rails -v 5.1.0.rc1
Fetching: activesupport-5.1.0.rc1.gem (100%)
Successfully installed activesupport-5.1.0.rc1
Fetching: erubi-1.6.0.gem (100%)
Successfully installed erubi-1.6.0
Fetching: actionview-5.1.0.rc1.gem (100%)
Successfully installed actionview-5.1.0.rc1
Fetching: actionpack-5.1.0.rc1.gem (100%)
Successfully installed actionpack-5.1.0.rc1
Fetching: activemodel-5.1.0.rc1.gem (100%)
Successfully installed activemodel-5.1.0.rc1
Fetching: arel-8.0.0.gem (100%)
Successfully installed arel-8.0.0
Fetching: activerecord-5.1.0.rc1.gem (100%)
Successfully installed activerecord-5.1.0.rc1
Fetching: activejob-5.1.0.rc1.gem (100%)
Successfully installed activejob-5.1.0.rc1
Fetching: actionmailer-5.1.0.rc1.gem (100%)
Successfully installed actionmailer-5.1.0.rc1
Fetching: actioncable-5.1.0.rc1.gem (100%)
Successfully installed actioncable-5.1.0.rc1
Fetching: railties-5.1.0.rc1.gem (100%)
Successfully installed railties-5.1.0.rc1
Fetching: rails-5.1.0.rc1.gem (100%)
Successfully installed rails-5.1.0.rc1
Parsing documentation for activesupport-5.1.0.rc1
Installing ri documentation for activesupport-5.1.0.rc1
Parsing documentation for erubi-1.6.0
Installing ri documentation for erubi-1.6.0
Parsing documentation for actionview-5.1.0.rc1
Installing ri documentation for actionview-5.1.0.rc1
Parsing documentation for actionpack-5.1.0.rc1
Installing ri documentation for actionpack-5.1.0.rc1
Parsing documentation for activemodel-5.1.0.rc1
Installing ri documentation for activemodel-5.1.0.rc1
Parsing documentation for arel-8.0.0
Installing ri documentation for arel-8.0.0
Parsing documentation for activerecord-5.1.0.rc1
Installing ri documentation for activerecord-5.1.0.rc1
Parsing documentation for activejob-5.1.0.rc1
Installing ri documentation for activejob-5.1.0.rc1
Parsing documentation for actionmailer-5.1.0.rc1
Installing ri documentation for actionmailer-5.1.0.rc1
Parsing documentation for actioncable-5.1.0.rc1
Installing ri documentation for actioncable-5.1.0.rc1
Parsing documentation for railties-5.1.0.rc1
Installing ri documentation for railties-5.1.0.rc1
Parsing documentation for rails-5.1.0.rc1
Installing ri documentation for rails-5.1.0.rc1
Done installing documentation for activesupport, erubi, actionview, actionpack, activemodel, arel, activerecord, activejob, actionmailer, actioncable, railties, rails after 18 seconds
12 gems installed
```

**Comment by keisei1092** [comment]
:tada:

**Comment by keisei1092** [comment]
railsをインストールできたっぽいので、動かす方法を模索します。

**Comment by keisei1092** [comment]
http://weblog.rubyonrails.org/2017/3/20/Rails-5-1-rc1/
さっきと同じこのページで 'run' で検索した。

> Notably, Stephen Touset helped us up the encryption used for encrypted secrets, so you’ll want to run this script to upgrade your app if you’re already dabbling with the feature. Thanks Stephen!

これと

> Basecamp 3 is already running this release candidate in production. Our friends at Heroku prepared the platform that is now fully compatible with all those shiny new features.


がでてきたが、期待した結果ではない。

**Comment by keisei1092** [comment]
ページをひとつ戻って公式サイトのトップへ

**Comment by keisei1092** [comment]
https://rubyonrails.org のナビゲーションに Guides というリンクがあるので踏む

**Comment by keisei1092** [comment]
http://guides.rubyonrails.org
見覚えのあるところにきた。

**Comment by keisei1092** [comment]
ここで `run` でgrepするが、何もヒットしない。

**Comment by keisei1092** [comment]
たぶんここはRailsの仕様が載っているところ（なので見つからない）。

**Comment by keisei1092** [comment]
Ruby on Railsの動かし方をGoogleで検索します

**Comment by keisei1092** [comment]
Google 'how to run ruby on rails'

**Comment by keisei1092** [comment]
一番目に「Getting Started with Rails — Ruby on Rails Guides」がでてきた

**Comment by keisei1092** [comment]
tap it

**Comment by keisei1092** [comment]
http://guides.rubyonrails.org/getting_started.html
ここでもう一度「run」で検索します

**Comment by keisei1092** [comment]
3 Creating a New Rails Project にそれっぽい内容がありそうだが その前に制約が載っていそうで心配なので上から順番に見ていく。

**Comment by keisei1092** [comment]
ちなみにヒット件数は33でヒットしたのは `The best way to read this guide is to follow it step by step. All steps are essential to run this example application and no additional code or steps are needed.` とか

**Comment by keisei1092** [comment]
> 1 Guide Assumptions

ここから見ていく。

**Comment by keisei1092** [comment]
> you need to have some prerequisites installed:

> The Ruby language version 2.2.2 or newer.
> Right version of Development Kit, if you are using Windows.
> The RubyGems packaging system, which is installed with Ruby by default. To learn more about RubyGems, please read the RubyGems Guides.
> A working installation of the SQLite3 Database.

**Comment by keisei1092** [comment]
上から順番に調べていく。

**Comment by keisei1092** [comment]
> The Ruby language version 2.2.2 or newer.

Rubyはrbenvでインストールしている。Rubyのバージョンを調べる。

```bash
% ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by keisei1092** [comment]
> Right version of Development Kit, if you are using Windows.

`Development Kit` って何？

**Comment by keisei1092** [comment]
> The RubyGems packaging system, which is installed with Ruby by default. To learn more about RubyGems, please read the RubyGems Guides.

RubyGemsはさっきインストールした。

:ok:

**Comment by keisei1092** [comment]
> A working installation of the SQLite3 Database.

SQLite3が動いていることが必要っぽい。
SQLite3が動いていることを調べるにはどうすればいいんだろう。

**Comment by keisei1092** [comment]
ps -aux とか？

**Comment by keisei1092** [comment]
Check if sqlite3 is installed で検索してみる。

**Comment by keisei1092** [comment]
一番目に https://www.tutorialspoint.com/sqlite/sqlite_installation.htm が出てきたので見る

**Comment by keisei1092** [comment]
Install SQLite On Mac OS Xの章があった

**Comment by keisei1092** [comment]
てか目grepするよりちゃんとgrepする習慣つけたほうがいいかも

**Comment by keisei1092** [comment]
ということで、「installでgrepして `Install SQLite On Mac OS X` の章を見つけた。」

**Comment by keisei1092** [comment]
幾度となくRailsプロジェクトをこの環境で作っていて インストールは済んでいるはずなので 

> Above procedure will end with SQLite installation on your Mac OS X machine which you can verify by issuing following command:

> $sqlite3

このコマンドを叩く。

**Comment by keisei1092** [comment]
（ $ と sqlite3 の間にスペースが開いてなくて$を含めちゃってコケる人いそう）

**Comment by keisei1092** [comment]
```bash
% sqlite3
SQLite version 3.14.0 2016-07-26 15:17:14
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
```

tutorialspoint.com の例とほぼ同じ文言が表示された。

**Comment by keisei1092** [comment]
これでRailsのprerequisitesをすべてクリアしたので、次に進む

**Comment by keisei1092** [comment]
このページに動いてるか簡単にチェックできる方法が載ってるといいなぁとは思った

**Comment by keisei1092** [comment]
> 2 What is Rails?

この章は飛ばす。

**Comment by keisei1092** [comment]
DRY制約は大事。

**Comment by keisei1092** [comment]
> 3 Creating a New Rails Project

ここがキモ

**Comment by keisei1092** [comment]
>  Verify that you have a current version of Ruby installed:

> $ ruby -v

打ちます

**Comment by keisei1092** [comment]
と思ったらSQLite3のコンソールがつけっぱで一回切らなきゃいけなかったｗ

**Comment by keisei1092** [comment]
C-c連打で殺す。

**Comment by keisei1092** [comment]
```bash
% ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

🆗

**Comment by keisei1092** [comment]
> Many popular UNIX-like OSes ship with an acceptable version of SQLite3. On Windows, if you installed Rails through Rails Installer, you already have SQLite installed. Others can find installation instructions at the SQLite3 website. Verify that it is correctly installed and in your PATH:

> $ sqlite3 --version

結局SQLite3もここで確認してくれるんかい 😅 
さっきも確認したけど、もう一度打ちます

**Comment by keisei1092** [comment]
```bash
% sqlite3 --version
3.14.0 2016-07-26 15:17:14 91e811f51e611a37372875e96a4c51bbed2dfdea
```

properly installed. :shamrock:

（結構古そうだな。いつかアップデートしよう。）

**Comment by keisei1092** [comment]
> To install Rails, use the gem install command provided by RubyGems:

> $ gem install rails

これはすでにやっている。
（前に入れたのは　rails -v 5.1.0.rc1 で、上はrailsだけど・・・）

**Comment by keisei1092** [comment]
> To verify that you have everything installed correctly, you should be able to run the following:
> $ rails --version

```bash
% rails --version
Rails 5.1.0.rc1
```

:ok:

**Comment by keisei1092** [comment]
> 3.2 Creating the Blog Application

ここが本当のキモ^^;

**Comment by keisei1092** [comment]
> To use this generator, open a terminal, navigate to a directory where you have rights to create files, and type:
> $ rails new blog

```bash
% cd Desktop
% rails new blog
      create
      create  README.md
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/keisei/Desktop/blog/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_5_1.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  tmp
      create  tmp/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  package.json
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_5_1.rb
         run  bundle install
Fetching https://github.com/rails/sass-rails.git
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.1
Using minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubi 1.6.0
Using mini_portile2 2.1.0
Using rack 2.0.1
Using nio4r 2.0.0
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 8.0.0
Using public_suffix 2.0.5
Using bundler 1.14.6
Using byebug 9.0.6
Using ffi 1.9.18
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using method_source 0.8.2
Using thor 0.19.4
Using debug_inspector 0.0.2
Using multi_json 1.12.1
Using rb-fsevent 0.9.8
Installing ruby_dep 1.5.0
Installing puma 3.8.2 with native extensions
Installing rubyzip 1.2.1
Using sass 3.4.23
Installing websocket 1.2.4
Using sqlite3 1.3.13p
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Installing nokogiri 1.7.1 with native extensions
Using rack-test 0.6.3
Installing sprockets 4.0.0.beta4
Using websocket-driver 0.6.5
Using mime-types 3.1
Using addressable 2.5.0
Installing childprocess 0.6.2
Using rb-inotify 0.9.8
Using coffee-script 2.4.1
Installing uglifier 3.1.9
Using turbolinks 5.0.1
Using activesupport 5.1.0.rc1
Using loofah 2.0.3
Using xpath 2.0.0
Using mail 2.6.4
Installing selenium-webdriver 3.3.0
Installing listen 3.1.5
Using rails-dom-testing 2.0.2
Using globalid 0.3.7
Using activemodel 5.1.0.rc1
Using jbuilder 2.6.3
Using spring 2.0.1
Using rails-html-sanitizer 1.0.3
Installing capybara 2.13.0
Using activejob 5.1.0.rc1
Using activerecord 5.1.0.rc1
Using spring-watcher-listen 2.0.1
Using actionview 5.1.0.rc1
Using actionpack 5.1.0.rc1
Using actioncable 5.1.0.rc1
Using actionmailer 5.1.0.rc1
Using railties 5.1.0.rc1
Using sprockets-rails 3.2.0
Using coffee-rails 4.2.1
Using web-console 3.4.0
Using rails 5.1.0.rc1
Using sass-rails 6.0.0.beta1 from https://github.com/rails/sass-rails.git (at master@dfbcc6a)
Bundle complete! 16 Gemfile dependencies, 69 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
```

:ok:

**Comment by keisei1092** [comment]
インストールできた

**Comment by keisei1092** [comment]
bundle installとかGemfileについて書いてある。だいたい分かるのでskip

**Comment by keisei1092** [comment]
`cd blog`

**Comment by keisei1092** [comment]
ファイル構成について書いてある。

**Comment by keisei1092** [comment]
> 4.1 Starting up the Web Server
You actually have a functional Rails application already. To see it, you need to start a web server on your development machine. You can do this by running the following in the blog directory:
> $ bin/rails server

Railsアプリケーションを立てる準備が整った。
ページを見るためにサーバを立ててみよう。
コマンドを打つとサーバを立てられるらしい

```bash
% bin/rails server
=> Booting Puma
=> Rails 5.1.0.rc1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

**Comment by keisei1092** [comment]
<img width="639" alt="2017-03-25 12 09 08" src="https://cloud.githubusercontent.com/assets/3320719/24319022/deea8702-1153-11e7-817e-71f31334fa17.png">

<font size="24"><b>YAY! YOU'RE ON RAILS!</b></font>

**Comment by keisei1092** [comment]
コンソールに表示されたPumaについての表示で
`* Listening on tcp://0.0.0.0:3000` ってのがあって間違えてtcp://とかアドレスバーに打ちそうになったw

**Comment by keisei1092** [comment]
とりあえずPumaが立ってRailsが正しくHTMLをサーブしたので、動いたと判断する。

**Comment by keisei1092** [comment]
http://guides.rubyonrails.org/getting_started.html このページの後部はControllerを生やしたりModelを生やしたりする説明なので、省略する。

**Comment by keisei1092** [comment]
同じページのナビゲーション部に「Contribute」の欄があるので見てみる。

**Comment by keisei1092** [comment]
> After reading this guide, you will know:
> How to use GitHub to report issues.
> How to clone master and run the test suite.
> How to help resolve existing issues.
> How to contribute to the Ruby on Rails documentation.
> How to contribute to the Ruby on Rails code.

GitHubにIssueを出したり、masterをクローンしてテストを回したりIssueを改善するのを手伝ったりdocにコントリビュートしたりコードにコントリビュートする方法がわかるとのこと

**Comment by kou** [comment]
ドキュメント周りでフィードバックチャンスありそう。
tcpがhttpの方が戸惑う人が少なくなりそう。

**Comment by keisei1092** [comment]
後半戦

**Comment by keisei1092** [comment]
Rails公式サイトのエントリにあった「RubyGemsを先にアップデートしてなきゃいけないことに気づかない危険性問題」と、Rails Guideにあった「インストール準備冗長問題」のどちらか、または両方について提案を出してみたいと思う。

**Comment by keisei1092** [comment]
同時進行はバッドプラクティスなので、問題を一つに絞る。
Rails Guideのインストール準備確認二重問題にする。

**Comment by keisei1092** [comment]
自分にわかるようにまとめる

# 現象

Rails Guide (http://guides.rubyonrails.org/getting_started.html)のGetting Started with Railsのページ内「1 Guide Assumptions」に、Railsをインストールする環境に必要な制約が列挙されている。
利用者がこの制約を満たしているか確認する方法は、この章には載っていないため、自分で各制約について外部リソースを参照することが必要になる。
しかしこの制約を確認することが可能なコマンドが幾つか同じページ内に載っている。それは3章にある。

# 期待すること

制約について知り、確認したいがコマンドを知らない利用者が外部リソースを参照する必要がない（それは3章にすべて書いてある）ことを1章の時点で明示されていること。

**Comment by keisei1092** [comment]
開発者に伝えるまでのプロセス

* まずsummaryを書く。「必須要件を確認したができなかった」
* summary→phenomenon

**Comment by keisei1092** [comment]
開発者に伝わるようにまとめる

# Summary

It can't determine whether a user environment is suitable for rails development

**Comment by keisei1092** [comment]
レビューをうけて文言修正。1文増やした。翻訳残しがちょっとあるが、とりあえずとばしてRails GuideへのContributeの仕方を調べにいく。

**Comment by keisei1092** [comment]
ふたたび http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html へ

**Comment by keisei1092** [comment]
guideでgrep。 `3 Contributing to the Rails Documentation` が出てきた。

**Comment by keisei1092** [comment]
> When working with documentation, please take into account the API Documentation Guidelines and the Ruby on Rails Guides Guidelines.

the Ruby on Rails Guides Guidelinesを見たらよさそう

**Comment by keisei1092** [comment]
http://guides.rubyonrails.org/ruby_on_rails_guides_guidelines.html

**Comment by keisei1092** [comment]
Feedbackの項あったぞ

**Comment by keisei1092** [comment]
> Feedback
> You're encouraged to help improve the quality of this guide.

> Please contribute if you see any typos or factual errors. To get started, you can read our documentation contributions section.

**Comment by keisei1092** [comment]
あ、無限ループじゃないかこれ・・・

**Comment by keisei1092** [comment]
もしかして Rails Guide はrais/railsから生成してる？

**Comment by keisei1092** [comment]
chapter名でリポジトリをgrepするとあるかどうかがわかりそう。

**Comment by keisei1092** [comment]
rails/rails を clone します

**Comment by keisei1092** [comment]
Issueを出すだけならcloneでいいけど、PRを出すならForkした方が良い

**Comment by keisei1092** [comment]
ので、Forkしてみます。

**Comment by keisei1092** [comment]
反省：railsのクローンでクラウドワークスの帯域を食ってしまった

**Comment by keisei1092** [comment]
guides ディレクトリにそれっぽいのがあった

**Comment by keisei1092** [comment]
いきなりPRを出すよりもIssueで様子を見て、よさそうなら僕がそのままPRを出すよという風にしておく。

メモ：タイトルにci-skipってつけるとCIをSkipできる。
　　　過去のPRを見てみて。
　　　docのPRではCIを回さないようにしたほうがいい。

**Comment by keisei1092** [comment]
rails/railsのIssueにテンプレートがありそう。
rails/railsのREADMEでtemplateでgrepしたけどでない

**Comment by keisei1092** [comment]
READMEのContributingの項に [Contributing to Ruby on Rails guide](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) というのがあったので押す

**Comment by keisei1092** [comment]
また [3 Contributing to the Rails Documentation](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) ここにきた

**Comment by keisei1092** [comment]
> To help our CI servers you should add [ci skip] to your documentation commit message to skip build on that commit. Please remember to use it for commits containing only documentation changes.

CI Skipの話ここに書いてあった。

**Comment by keisei1092** [comment]
Issueを出すぞ

**Comment by keisei1092** [comment]
rails/railsのIssueでdocsラベルをつければよさそう　https://github.com/rails/rails/issues?q=is%3Aissue+is%3Aopen+label%3Adocs

**Comment by keisei1092** [comment]
New Issueを押したら、Contribute Guideを見ろと言われたのでさっと目を通す
https://github.com/rails/rails/blob/master/CONTRIBUTING.md

**Comment by keisei1092** [comment]
Issueにラベルはつけられない #ﾄﾉｺﾄ

**Comment by keisei1092** [comment]
プレースホルダに次の文章が入っていた。

> ### Steps to reproduce

> (Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

> ### Expected behavior
> Tell us what should happen

> ### Actual behavior
> Tell us what happens instead

> ### System configuration
> **Rails version**:

> **Ruby version**:

**Comment by keisei1092** [comment]
でました https://github.com/rails/rails/issues/28565

**Comment by keisei1092** [comment]
make a pull requestじゃなくてopen。

**Comment by keisei1092** [comment]
Railsはtime onなので半日後にレビューが来るかもしれない

**Comment by keisei1092** [comment]
Contributingをわかりやすくするのもやりたいなぁ

**Comment by kou** [comment]
やったね！
フィードバック方法が簡単にわかるようにできるといいかも！

**Comment by kou** [comment]
B

**Comment by koic** [comment]
@keisei1092 Issue での回答をもらえてますね。次のステップに進めるかなと思いました 🌟
