### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-03-25: GorillaKing518: OpenStack: Work log

### ISSUE THREAD

**Issue by GorillaKing518** [oss-gate/workshop#341]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by GorillaKing518** [comment]
OpenStackの入手方法を調査
公式サイトは以下
> https://www.openstack.org/

**Comment by GorillaKing518** [comment]
インストール方法を調査
トップページで”install”検索
→見つからない…

**Comment by GorillaKing518** [comment]
[Software]タブに”Get Started”の文字があるのでクリック‼

**Comment by GorillaKing518** [comment]
Optionが2つ‼
> Option 1：Public Clouds on the Marketplace
> Option 2：Option 2: Local Dev Environment: devstack.org
クラウド上で動かせる！？知らなんだ・・・

**Comment by GorillaKing518** [comment]
Option 1のほうはクレジットカード情報がいる…のかな？
> with the swipe of a credit card. 

エキサイト翻訳いわく
> クレジットカードの強打で

ぶん殴れば使えるようだ

**Comment by GorillaKing518** [comment]
♯♯ Option 1の調査
世界各地にデータセンターがある？
誰が構築して、管理しているんだろう…
> Using a cloud
>There are OpenStack powered public clouds all over the world. Explore the possibilities.

東京にもある！
> https://www.openstack.org/marketplace/public-clouds/city-network/city-cloud

**Comment by GorillaKing518** [comment]
誤り(はやとちり)に気づく
”Building a Cloud”ではなく”Using a Cloud”を選んでいたので、OpenStack環境を構築しているクラウドサービスサイトに飛んでしまっていた
> https://www.openstack.org/marketplace/

”Building a Cloud”を読み進める

**Comment by GorillaKing518** [comment]
説明文からは社内環境への導入、くらいの大仰な感じがします。
```
Building a cloud
You'll want to understand which Software Distributions and Converged Appliance options there are.
Many users start by hiring experts, which you can find in our Consultants and System Integrators section.
Want to train your staff? Check out our Training section.
Wondering if your compute, storage, and networking gear has compatible drivers? Check out the Drivers section to learn the status of ongoing testing.
```

**Comment by GorillaKing518** [comment]
既存知識でDevStack(Opetion 2)を選択
Ubuntu上に構築するか??
ISOを落としつつ、ほかの方法がないかを調査しよう
ISOダウンロードサイト(16.04.02)
> https://www.ubuntu.com/download/server

**Comment by GorillaKing518** [comment]
## DevStackのサイトを読んでみる
DevStackの説明ページ
> https://docs.openstack.org/developer/devstack/

Ubuntu16.04推奨のような文言あり
```
If you do not have a preference, Ubuntu 16.04 is the most tested, and will probably go the smoothest.
```

メンターただただしさんのコメント
```
推奨じゃないOSのほうが、手が行き届いていない分、発見があるかも
```

でCentOSを選択。ISOを落とそう
> http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso
> http://www.ftp.ne.jp/Linux/packages/CentOS/7/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso 

Virtual BoxでのCentOS構築手順(外部ネットにつなごう)
> http://qiita.com/100/items/80a899fbaeb1e82b3f67

ネットワーク設定をしておくのを忘れていた…あとでやろう

**Comment by kou** [comment]
なるほど！
https://www.openstack.org/software/start/ で迷ったということなので、迷わないようななにかになっているといいかも！？

**Comment by GorillaKing518** [comment]
## Feedback案
### 自分の気持ち
お試しインストールをしたい
Get Startedでそれっぽい情報を見つけた
Option 1とOption 2と書かれていると”同じ目的の違う方法”案内されているように見える
Option 2はDeveloper向けの情報なので
　Try OpenStack as User or as Developer
のように書いてくれるとわかりやすいのでは??

### わかりやすく書き直す
目的：(コミュニティ活動を視野に入れて)OpenStackを試しに使ってみたい
作業：公式サイトのトップページの[SOFTWARE]>[GET STARTED]からインストールを試みた
> https://www.openstack.org/
> https://www.openstack.org/software/start/

”Try OpenStack”にOptionが2つあるが、片方(Option1)は利用者として、他方(Option2)は開発者向けの情報のように見える
Optionという書き方ではなく、as a Userやas a Developerなど、目的が違うことが分かるように書いてほしい

### In English




## そもそも探し方が正しかったのか??

**Comment by GorillaKing518** [comment]
### ただただしさんよりコメント

自分の立場を明確にして、相手の心に響くように

### 修正案
OpenStack開発を始めたく、公式サイトから開発者向けの導入手順を探していた。
公式サイトから以下の手順で、導入の入り口までたどり着いた
  [TOP]>[SOFTWARE]>[GET STARTED]
”Option 1”と”Option 2”と二つに分かれているが、前者は利用者向け、後者は開発者向けの情報にみえる。
”Option”ではなく”For a User”や”For a Developer”などのように、目的に応じた区分にしてもらえると迷わなかった。

**Comment by GorillaKing518** [comment]
ページの最下部に
‘‘‘
Give us your Feedback On this Page
‘‘‘
> https://www.openstack.org/software/start/

**Comment by GorillaKing518** [comment]
ドキュメントのコントリビュータ用のガイドを読んだが、サイトの文言の指摘はlauchpadの対象外にみえる
> https://docs.openstack.org/contributor-guide/team-structure.html

やはり、ページ最下部からのコメントか?

**Comment by GorillaKing518** [comment]
試しに”test”→”submit”をしてみると…簡単に送られてしまった

**Comment by GorillaKing518** [comment]
最終的に以下の分をコピペして”Submit”を押下‼

I would like to be a OpenStack developer and am searching how to install it.
I think the indexes "Option 1" and "Option 2" in this page are not explicit expressions.
The former seems for users and the latter seems for developers.
I hope these expressions to be more explicit: e.g. "For Users" and "For Developers"

無事インターネット空間に消えていったっぽい。

**Comment by kou** [comment]
お疲れ様でした！
