### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-3-30: solaWat: OpenCV: Work log

### ISSUE THREAD

**Issue by solaWat** [oss-gate/workshop#366]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by solaWat** [comment]
OpenCVのインストールを行う為，ドキュメントを探す．

「opencv android インストール」で検索．

**Comment by solaWat** [comment]
Quiteのページ「OpenCV for AndroidをAndroid Studioに導入するメモ」のOpenCVの公式サイトへのリンク(http://opencv.org/downloads.html)は飛べなかった（404 Not found）．

**Comment by solaWat** [comment]
そのままgoogleで「OpenCV」で検索すると，公式ページに行ける．http://opencv.org

**Comment by solaWat** [comment]
macにOpenCVをインストールしたいのだけど，リンクがどこにあるのかがわからない……

**Comment by solaWat** [comment]
Platformsや Online documentation，releasesなどを見ても，わからない．

**Comment by solaWat** [comment]
OpenCV.jpという日本語コミュニティサイトがあった．

**Comment by solaWat** [comment]
OpenCV.jpに「(翻訳)OpenCVへ貢献するには」という便利そうなページを発見．

**Comment by solaWat** [comment]
2010の「http://opencv.jp/tips」には，mac用のインストール先は見つからなかった．
windowsとlinuxはあった．

**Comment by solaWat** [comment]
quite「PythonでOpenCVを使う@Mac」2015年03月31日に更新
を参考に，とりあえず

'''
brew tap homebrew/science
'''
をやって見る．

**Comment by solaWat** [comment]
成功したので，numpyがあることをpipで確認した．

''''
brew install opencv
''''

を行う．

**Comment by solaWat** [comment]
Pythonのsite-packagesディレクトリに移動して，シンボリックリンクを貼る．

```
cd /Library/Python/2.7/site-packages/
ln -s /usr/local/Cellar/opencv/2.4.9/lib/python2.7/site-packages/cv.py cv.py
ln -s /usr/local/Cellar/opencv/2.4.9/lib/python2.7/site-packages/cv2.so cv2.so
```

**Comment by solaWat** [comment]
pythonのREPLに入って，import を行うも，エラー．

```
s.Watanabe$ python
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv'
>>> import cv;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv'
>>> 
```

**Comment by solaWat** [comment]
pythonをアナコンダ3系からノーマルの2系にしてみても，エラー．

```
s.Watanabe$ python
Python 2.7.9 (default, Oct 31 2016, 17:33:46) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cv
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cv2
>>> pyenv version
  File "<stdin>", line 1
    pyenv version
                ^
SyntaxError: invalid syntax
```

**Comment by solaWat** [comment]
```
brew info opencv
```
をしてみると，先ほどインストールしたOpenCVのバージョンは，2.4.13.2だった．

**Comment by solaWat** [comment]
バージョンの記法を変更して試す．
```
ln -s /usr/local/Cellar/opencv/2.4.9/lib/python2.7/site-packages/cv.py cv.py
ln -s /usr/local/Cellar/opencv/2.4.9/lib/python2.7/site-packages/cv2.so cv2.so
```
↓
```
ln -s /usr/local/Cellar/opencv/2.4.13.2/lib/python2.7/site-packages/cv.py cv.py
ln -s /usr/local/Cellar/opencv/2.4.13.2/lib/python2.7/site-packages/cv2.so cv2.so
```

でもエラー．
```
s.Watanabe$ python
Python 2.7.9 (default, Oct 31 2016, 17:33:46) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cv.py", line 1, in <module>
    from cv2.cv import *
ImportError: numpy.core.multiarray failed to import
```

**Comment by changeworld** [comment]
よろしくお願いします！

**Comment by changeworld** [comment]
やった手順としてはよいと思います。
ただどうやったら公式に貢献できるのか？という観点もあった方がもっとよかったかもしれません。

**Comment by solaWat** [comment]
うまく動くところまで確認できたら，それをOpenCVの公式サイトに貢献させる．
おそらく　https://github.com/opencv/opencv
のdocフォルダ　https://github.com/opencv/opencv/tree/master/doc
をいじるのかもしれない．

**Comment by knokmki612** [comment]
先日はおつかれさまでした！brewのOpenCVは動きましたでしょうか！？
issueはcloseしますが、このまま作業のメモを書いていただいて問題ありません！
[oss-gate/devel](https://gitter.im/oss-gate/devel)などでも相談いただければと思います！

また、次回のミートアップは5/22(月)になりました！Doorkeeperにイベントページが作成されるのを待っていただくか、[oss-gate/general](https://gitter.im/oss-gate/general)というチャットルームでイベントについて話されているので、こちらを見ていただければと思います！
