### ISSUE TITLE
OSS Gate東京ミートアップ2017-04-13の募集の原案

### ISSUE THREAD

**Issue by koic** [oss-gate/workshop#377]
以下のようなイベント内容で、Doorkeeper のページを作成しようと思います。

前回 3月のミートアップの募集との差分はタイムテーブルのみです。

主に以下の点がタイムテーブルの差分となっています。

- 1回目のビギナーと2回目のビギナーを分けずに通しで説明するようにしている
- 3月のミートアップで最後の「まとめ」の時間をとっていなかったため10分用意した
- 「まとめ」の時間を作った分、「OSS開発手順を説明」「フィードバックを説明」を5分づつ切り詰めた

4月5日(水) くらいに募集を出せるといいなと思っております。レビューよろしくお願いします。

---

*「メンター」と「開発者」は参加人数に制限はありません！「キャンセル待ち」になっていても気にせずに登録してください。管理者が本登録に変更します。「メンター」・「開発者」の参加をお待ちしています！*

## 概要

OSSを開発する人たちが集まる場です。同じ場所で次の2つのことをやっています。

  1. [「OSSの開発に参加する」を実際に体験するワークショップ](http://oss-gate.github.io/report/workshop/2016/09/24/workshop-report-tokyo.html)
     * 奇数月の最終土曜日に開催しているワークショップと同じ内容です。土曜日に開催している方は1日で全部の内容を実施しますが、このミートアップでは数回にわけて少しずつ進めます。
  2. OSSの開発
     * 各自OSSを開発します。開発対象のOSSはなんでも構いません。このミートアップでOSSを開発するメリットは他の開発者と相談できることです。

「ワークショップ」に参加する人は「ビギナー」か「メンター」で申し込んでください。OSSを開発する人は「開発者」で申し込んでください。

* 「ビギナー」とは次のような人です。

  * OSSの開発に参加したいけどまだ参加したことがない人
  * OSSの開発に参加したことはあるけどまだ自信がない人
  * OSSの開発に参加したい！という人は「ビギナー」として申し込んでください

* 「メンター」とは次のような人です。

  * OSSの開発に参加している人（OSSの開発に参加していれば「OSS Gateワークショップ」・「OSS Gateミートアップ」未経験でも大丈夫です。）
  * 「ビギナー」をサポートしたい！という人は「メンター」として申し込んでください

* 「開発者」とは次のような人です。

  * 過去に「ビギナー」としてOSSの開発に参加する1歩を踏み出した人
  * OSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません。）

以下は参考URLです。

  * OSS Gateについての説明：
    * [OSS Gateへようこそ！](http://oss-gate.github.io/announce/update/2015/12/17/welcome-to-oss-gate.html)
  * ワークショップについての説明：
    * [OSS Gateワークショップ2016-01-30開催のおしらせ - ククログ(2016-01-07)](http://www.clear-code.com/blog/2016/1/7.html)
  * ワークショップ参加者の感想：
    * [ワークショップレポート](https://oss-gate.github.io/workshop/report.html)
  * Twitterのハッシュタグ
    * [#oss_gate](https://twitter.com/hashtag/oss_gate)

## 事前準備

「ビギナー」・「メンター」は事前にGitHubのアカウントを取得しておいてください。

## 当日持ってくるもの

OSSの開発に使えるノートパソコンを持ってきてください。「OSSの開発に使えるノートパソコン」というのは次のようなノートパソコンです。

  * バージョン管理システム（GitクライアントやSubversionクライアントなど）をインストール済み
  * GitHubにログインできる状態になっている
  * 開発に使うプログラミング言語の処理系（コンパイラーやインタプリターなど）をインストール済み
  * 開発に使うIDE・エディターをインストール済み
  * などなど

特にダウンロードに時間がかかりそうなもの（特に仮想マシンやIDE）は事前に使える状態にしておいてください。

準備で困った・不安なことがあるという人は[チャット](https://gitter.im/oss-gate/general)で相談してください。

## <span id="goal">目標</span>

  * ワークショップ参加者
    * ワークショップ中に実際にOSSの開発に参加する
    * ワークショップ後も継続してOSSの開発に参加できそうな気持ちになる
  * OSSを開発する人
    * OSSの開発が捗ること

## ワークショップの内容

従来1日かけて実施していた内容を2回にわけて実施します。内容の詳細は [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md#シナリオ)をご覧ください。

### 初参加の「ビギナー」

|時間|やること|
|---|---|
|19:15-19:30|開場|
|19:30-19:40|アイスブレイク|
|19:40-20:05|OSS開発手順を説明|
|20:05-20:20|フィードバックを説明|
|20:20-21:00|対象OSSを動かす|
|21:00-21:15|対象OSSを動かしたふりかえり|
|21:15-21:25|まとめ|
|21:25-21:35|アンケート記入|
|21:35-21:50|ミートアップのふりかえり|

## OSSを開発する人の内容

|時間|やること|
|---|---|
|19:15-19:30|開場|
|19:30-19:40|アイスブレイク|
|19:40-21:25|OSSの開発|
|21:25-21:35|アンケート記入|
|21:35-21:50|ミートアップのふりかえり|

----

## 遅れてくる方へ

20時以降の入場については正面玄関が閉まるため、夜間通用口からの出入りとなります。ビルの右手通りにある通用口にあります、インターフォンで702を鳴らして中の者にコンタクトしてください。「OSS Gateの参加者です」みたいに言っていただければ通じると思います。開錠されましたら通用口から入り、エレベーターに乗り7階にお越しください。

**Comment by koic** [comment]
現状で軽く気になっている点としては、4月のこの募集の時点でメンターをサポーターという名称に変えた方が良いかどうかです。このあたりの決着がついたかどうかがよく分かっていないため、現状のメンターという呼称のままにしています。

**Comment by koic** [comment]
ミートアップへのドラスティックな変更案としては、ワークショップとミートアップを別のものと捉えるものです。

ざっくりいうと、OSS Gate をくぐる1歩目に用意したワークショップと、OSS Gate をくぐった2歩目以降に用意したミートアップです。

生煮えながらも可能であれば4月のミートアップから試行してみる線を含みつつ、いま頭の中で描いているものをダンプしておきます。

現在、ミートアップにはふたつの目的があると思っています。

- 目的1. 土日に一日参加できないビギナーを平日に分けて参加する機会を作る
- 目的2. OSS Gate ワークショップで1歩目を踏み出したビギナーが、2歩目以降継続する場を作る

ミートアップをこれまで3回開催して、個人的には目的2の 2歩目以降継続する場を作ることにフォーカスした内容にできると良いのかなという考えがあります。

## 1. 時間が足りない

もともと1日で組み立てていたワークショップを、前半の「動かしてみる」と後半の「フィードバックする」に分割して開催してみるという試みでしたが、ふりかえりやアンケートなどの時間確保などで本筋 (?) の手を動かしてみる時間が減ってしまっているように思えます。結果として時間が足りないという声がいくつか上がっている点が気になっています。

## 2. ワークショップではなくミートアップ

名前に合わせるのであれば、ワークショップの形式をミートアップに持ってくる方法に限らず (既存の開催方法に乗るのは初手として分かりやすいです) 、目的2にある __2歩目以降の OSS 開発者に継続する場を作る__ に焦点を合わせた (OSS 開発者の) ミートアップという形式にするのはどうかと思いました。

粗い進行案としては、最初に参加者の自己紹介をした後は、各々の OSS 開発をして、最後にチェックアウトとしてひとことずつやったことを喋れるといったものになります。

懸念点としては、OSS Gate をくぐって2歩目以降に進んだという参加者がどの程度いるのか分からないの点です (が、そこは気にせず募集してみるのはどうかという気もしております) 。

タイムテーブルに表すと以下のような形になります。全体としては OSS を開発する人の内容をベースにしたもので、アンケート記入をなくして全体の時間を繰り上げています。

### OSSを開発する人の内容

|時間|やること|
|---|---|
|19:15-19:30|開場|
|19:30-19:40|アイスブレイク|
|19:40-21:15|OSSの開発|
|21:15-21:30|ミートアップのふりかえり|

解決できる問題は以下です。

- アンケートの準備が不要になる
- 進行役が誰かという話をしなくてもよい
- 開発者で参加したいメンターが多くなってきている気がして (2歩目以降の OSS 開発者をサポートしつつ) 開発者にまわれる
- アンケート入力などでの全体の時間を同期する必要がなくなるため、時間がきたら個々人の作業はお仕舞いにできる

募集概要や参加者の申込枠の名前などは、新たに (初回) 準備する必要があると思います。

**Comment by knokmki612** [comment]
作成ありがとうございます！募集の原案ですが、

タイムテーブルの時間配分は前回のミートアップを踏まえたものになっていると思いますし、良いと思います！

> | | |
> |---|---|
> |20:20-21:00|対象OSSを動かす|
> |21:00-21:15|対象OSSを動かしたふりかえり|

ここの時間は「対象OSSを動かす」の先も進めるビギナーがいた時に進んで欲しいので、  
「プロジェクトにフィードバックする」もやってよさそうな説明にしたいと思いました。

> | | |
> |---|---|
> |20:20-21:00|対象OSSを動かす＆フィードバックする|
> |21:00-21:15|作業のふりかえり|

「開発者」にはワークショップの続きをやる人も該当する(後半パートのビギナーに相当)ので、それが伝わる説明を追加したいですね。

> * 「開発者」とは次のような人です。
> 
>   * 過去に「ビギナー」としてOSSの開発に参加する1歩を踏み出した人
>   * OSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません。）

ここに一つ箇条書きを追加するとしたらなんでしょうか…

* ワークショップの続きをやる人

しか浮かびませんでしたが、もっと良い説明があるかもしれません。

**Comment by hiroyuki-sato** [comment]
ちょっと細かいんですが、

> * 過去に「ビギナー」としてOSSの開発に参加する1歩を踏み出した人

「OSSの開発に参加する1歩」ってところが少しわかりづらいなと感じました。

* 過去に「ビギナー」としてOSS Gateに参加し、OSS開発の一歩を踏み出した人。

とかどうでしょうか？

**Comment by sezemiadmin** [comment]
とっても良い変更だと思ってます!!
で、まったくもってアイデアなんですが、二歩目の方には "様々なコミット方法をやってみる" というのはどうかなぁと思ってます。
例えば、バグを回避するようにしてたけど、これを機会にやってみよう、みたいな目標です
// inspired by ↓

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">バグを見つけたら報告しろよ！って思うけどそういう文化なんだろうなぁ。報告するのが当たり前な組織を増やしたいなぁ。 <a href="https://t.co/bBLPI3cW1M">https://t.co/bBLPI3cW1M</a><br>代わりにパッチを送っておいた。<a href="https://t.co/UF1upMgRaa">https://t.co/UF1upMgRaa</a></p>&mdash; す (@ktou) <a href="https://twitter.com/ktou/status/844905787218571264">2017年3月23日</a></blockquote>

**Comment by koic** [comment]
フィードバックありがとうございます。盛り込めそうなところを反映してみます。

**Comment by koic** [comment]
前回のミートアップから前半と後半を分けていないため、概要の冒頭について少し以下のような手入れをします。

```diff
-  1. [「OSSの開発に参加する」を実際に体験するワークショップ](http://oss-gate.github.io/report/workshop/2016/09/24/workshop-report-tokyo.html)
-     * 奇数月の最終土曜日に開催しているワークショップと同じ内容です。土曜日に開催している方は1日で全部の内容を実施しますが、このミートアップでは数回にわけて少しずつ進めます。
+  1. [「OSSの開発に参加する」を実際に体験するワークショップ](http://oss-gate.github.io/report/workshop/2016/09/24/workshop-report-tokyo.html)
+     * 奇数月の最終土曜日に開催しているワークショップとほぼ同じ内容です。土曜日に開催している方は1日で全部の内容を実施しますが、このミートアップでは作業の進捗に合わせて継続的に参加しながら少しずつ進めます。
```

**Comment by koic** [comment]
[Gitter での共有となりましたが](https://gitter.im/oss-gate/general?at=58e37938408f90be66886ad0)、Doorkeeper 募集の下書きを作成しました。Doorkeeper の募集を公開したら、この Issue を Close しようと思います。

@knokmki612 @hiroyuki-sato @sezemiadmin 繰り返しになりますが、フィードバックありがとうございました 🙏

**Comment by knokmki612** [comment]
ミートアップについて、誰がどれに参加したらいいのか分かりやすく説明するのに、こんなのを考えてみました！

1. OSS Gateイベントは初参加でOSS開発に自信がない人  
→ **「ビギナー」** で登録してOSS開発の一歩の踏み出しかたを知りましょう！
2. OSS Gateイベントは参加経験アリでOSS開発に自信がない人  
→ **「開発者」** で登録して「ビギナー」でやった作業の続きをするか、  
　 **「メンター」** で登録して「ビギナー」の背中を押しましょう！
3. OSS開発に自信がある人  
→ **「開発者」** で登録して自信がなさそうな「開発者」の背中を押しましょう！

現状の説明で該当する部分は以下の部分だと思うのですが、比較してどう思われますか？

> 「ワークショップ」に参加する人は「ビギナー」か「メンター」で申し込んでください。OSSを開発する人は「開発者」で申し込んでください。
> 
> * 「ビギナー」とは次のような人です。
> 
>   * OSSの開発に参加したいけどまだ参加したことがない人
>   * OSSの開発に参加したことはあるけどまだ自信がない人
>   * OSSの開発に参加したい！という人は「ビギナー」として申し込んでください
> 
> * 「メンター」とは次のような人です。
> 
 >  * OSSの開発に参加している人（OSSの開発に参加していれば「OSS Gateワークショップ」・「OSS Gateミートアップ」未経験でも大丈夫です。）
>   * 「ビギナー」をサポートしたい！という人は「メンター」として申し込んでください
> 
> * 「開発者」とは次のような人です。
> 
 >  * 過去に「ビギナー」としてOSSの開発に参加する1歩を踏み出した人
 >  * OSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません。）

**Comment by koic** [comment]
なるほど。参加者のいまの立ち位置ベースで、参加枠を選んでもらうというのは面白いと思いました。

1点、「OSS開発に自信がある人」だと少し敷居が高くなる気がしました。
既存のテキストに少し手を加えた感じですが「すでにOSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません）」というのはどうでしょうか？

**Comment by hiroyuki-sato** [comment]
> * メンター」とは次のような人です。
>   *「ビギナー」をサポートしたい！という人は「メンター」として申し込んでください

「サポート」ってなにするの？ってちょっと思うかもと感じました。

須藤さんの言葉を借りて

* これからOSSの開発に参加したと思っているビギナーに、ビギナー視点で自身の体験や経験をアドバイスし、一緒に考えてくれる人


文章イマイチですが、「開発経験が豊富ではない方がむしろいいんですよ。」的な表現が入るといいような気がしました。

**Comment by koic** [comment]
レビューありがとうございます。こんな感じの diff まで作ってみましたが、夕方の公開までに文章の前後関係を練る時間を作れそうにないため、 4月13日のミートアップぶんは Doorkeeper に下書きしてある状態のもので告知しようと思います 🙏 

```diff
「ワークショップ」に参加する人は「ビギナー」か「メンター」で申し込んでください。OSSを開発する人は「開発者」で申し込んでください。

- * 「ビギナー」とは次のような人です。
-
-   * OSSの開発に参加したいけどまだ参加したことがない人
-   * OSSの開発に参加したことはあるけどまだ自信がない人
-   * OSSの開発に参加したい！という人は「ビギナー」として申し込んでください
-
- * 「メンター」とは次のような人です。
-
-   * OSSの開発に参加している人（OSSの開発に参加していれば「OSS Gateワークショップ」・「OSS Gateミートアップ」未経験でも大丈夫です。）
-   * 「ビギナー」をサポートしたい！という人は「メンター」として申し込んでください
-
- * 「開発者」とは次のような人です。
-
-   * 過去に「ビギナー」としてOSSの開発に参加する1歩を踏み出した人
-   * OSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません。）
+ * OSS Gateイベントは初参加でOSS開発に自信がない人  
+   * __「ビギナー」__ で登録してOSS開発の一歩の踏み出しかたを知りましょう！
+ * OSS Gateイベントは参加経験アリでOSS開発に自信がない人  
+   * __「開発者」__ で登録して「ビギナー」でやった作業の続きをするか、  
+   * __「メンター」__ で登録して「ビギナー」の背中を押しましょう！
+     * メンターとは、これからOSSの開発に参加したいと思っているビギナーに、ビギナー視点で自身の体験や経験をアドバイスし、一緒に考えてくれる人です
+ * すでにOSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません）
+   * __「開発者」__ で登録して自信がなさそうな「開発者」の背中を押しましょう！

以下は参考URLです。
```

**Comment by koic** [comment]
4月13日の OSS Gate の募集ページを公開しましたので、こちらの Issue を Close します。

https://oss-gate.doorkeeper.jp/events/59418

今回反映できなかった分のフィードバックは、今後に加味したいなと思います。ありがとうございました。

**Comment by knokmki612** [comment]
> 1点、「OSS開発に自信がある人」だと少し敷居が高くなる気がしました。
> 既存のテキストに少し手を加えた感じですが「すでにOSSの開発に参加している人（自分が作者のOSSでもそうでないOSSでもOSSならなんでも構いません）」というのはどうでしょうか？

良いと思います！(closeのままで大丈夫です)
