### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-04-13: ikamasa: OpenJDK: Work log

### ISSUE THREAD

**Issue by ikamasa** [oss-gate/workshop#381]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by master-q** [comment]
https://www.debian.org/ をvirtualbox上で動かすと楽かもしれません。

‘‘‘
$ apt-get source openjdk-9-jdk
‘‘‘

でソースコードが取ってこれます。

**Comment by ikamasa** [comment]
ありがとうございます！やってみます！

**Comment by knokmki612** [comment]
ここに作業用のチャットがありますので、聞きたいことがあったらここに書くのも良いです！ https://gitter.im/oss-gate/devel

**Comment by ikamasa** [comment]
[教えていただいたリンクから](https://www.debian.org/)からDebianを落としてよう。

**Comment by ikamasa** [comment]
debianを使うのは初めて。WEBサイトがわかりづらい。どこから落とすのだろう。

**Comment by ikamasa** [comment]
VirtualBoxはインストールされているので、isoファイルをダウンロードする。

**Comment by ikamasa** [comment]
[インストールマニュアル](https://www.debian.org/releases/stable/i386/)をみてみる。

**Comment by master-q** [comment]
Installing Debian via the Internet https://www.debian.org/distrib/netinst
からisoイメージをダウンロードできますよ！

**Comment by ikamasa** [comment]
[ミラーサイト一覧](https://www.debian.org/distrib/ftplist)から、[FTPサイト](http://ftp.jaist.ac.jp/debian-cd/)にたどり着いたので、8.7.1を落としてみる。

**Comment by ikamasa** [comment]
[教えていただいたページ](https://www.debian.org/distrib/netinst)から、i386のイメージを落とす。

**Comment by ikamasa** [comment]
debian-8.7.1-i386-netinst.isoをダウンロードできた。

**Comment by ikamasa** [comment]
VirtualBoxを起動する。

**Comment by ikamasa** [comment]
メモリーサイズをどうすればよいか。OpenJDKをビルドすることを考えると、大きめにとっておくことにする。8192MBにする。

**Comment by ikamasa** [comment]
ハードディスクは、仮想ハードディスクを作成するを選択する。

**Comment by ikamasa** [comment]
ハードディスクのファイルタイプをVDIにする。

**Comment by ikamasa** [comment]
物理ハードディスクにあるストレージは、可変サイズを選択する。

**Comment by ikamasa** [comment]
ファイルの場所とサイズは、30GBにする。

**Comment by ikamasa** [comment]
OpenJDK のサイトから、installのリンクをたどって、http://openjdk.java.net/install/index.html にたどり着いた。

**Comment by ikamasa** [comment]
Mac OS Xでは、どうインストールするのか？

**Comment by ikamasa** [comment]
"openjdk mac install"でGoogleで検索してみると、[Mac OS X Port Project](http://openjdk.java.net/projects/macosx-port/)にたどり着く。

**Comment by ikamasa** [comment]
Mac OS X Port Projectから、[OpenJDK](https://wiki.openjdk.java.net/display/MacOSXPort/Main)にたどり着いた。

**Comment by ikamasa** [comment]
hgは入れてないな。Mercurialか。

**Comment by ikamasa** [comment]
hgを入れてみる。

**Comment by ikamasa** [comment]
hgが入ったので、

> hg clone http://hg.openjdk.java.net/jdk8/jdk8

destination directory: jdk8
requesting all changes
adding changesets
adding manifests
adding file changes
added 942 changesets with 1309 changes to 136 files
updating to branch default
82 files updated, 0 files merged, 0 files removed, 0 files unresolved

**Comment by ikamasa** [comment]
サイトの手順に従って、

> cd jdk8
> chmod 755 get_source.sh
> ./get_source.sh

**Comment by ikamasa** [comment]
落としてくるだけで、この時間がおわってしまいそう。。。

**Comment by ikamasa** [comment]
> CPATH="/usr/X11/include" LANG=C make ALLOW_DOWNLOADS=true ALT_BOOTDIR=`/usr/libexec/java_home -v 1.7+` HOTSPOT_BUILD_JOBS=`sysctl -n hw.ncpu`

**Comment by ikamasa** [comment]
環境変数のセットって、どうやるんだっけ？
exportだったよな。

**Comment by ikamasa** [comment]
おそらく環境変数だと思うのだが。
サイトにその記載がない。

**Comment by ikamasa** [comment]
コードを書くだけがOSS開発参加方法じゃない！

**Comment by master-q** [comment]
そもそも論として公式ページにWindows/Mac OS Xでのビルド手順が掲載されてればよかったですね...

**Comment by ikamasa** [comment]
たしかに、そうですね。

勉強になりました。とても楽しかったです。
ありがとうございました！！

**Comment by knokmki612** [comment]
先日はおつかれさまでした！
issueはcloseしますが、このまま作業のメモを書いていただいて問題ありません！
[oss-gate/devel](https://gitter.im/oss-gate/devel)などでも相談いただければと思います！

また、次回のミートアップは5/22(月)になりました！Doorkeeperにイベントページが作成されるのを待っていただくか、[oss-gate/general](https://gitter.im/oss-gate/general)というチャットルームでイベントについて話されているので、こちらを見ていただければと思います！
