### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-04-13: mochibuta: fzaninotto/Faker: Work log

### ISSUE THREAD

**Issue by mochibuta** [oss-gate/workshop#382]
This is a work log of "OSS Gate".  
"OSS Gate" is about an activity to increase OSS developers.  
Here's been discussed in Japanese. Thanks.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by mochibuta** [comment]
laravelのfakerライブラリが気になる

**Comment by mochibuta** [comment]
「laravel faker」で検索
Githubのページを発見

[fzaninotto/Faker](https://github.com/fzaninotto/Faker)

**Comment by mochibuta** [comment]
READMEをよむ

**Comment by mochibuta** [comment]
インストールする

```
composer require fzaninotto/faker
```

**Comment by mochibuta** [comment]
ローカルの環境でインストールしてみる

**Comment by mochibuta** [comment]
composerが入ってなかったのでいれる

**Comment by mochibuta** [comment]
composerで検索

https://getcomposer.org/

**Comment by mochibuta** [comment]
composerインストール方法らしきものがあったので
これに従ってインストールする

https://getcomposer.org/doc/00-intro.md

**Comment by mochibuta** [comment]
https://getcomposer.org/download/

ダウンロードページを見つけたので
ひとまずlatest版にする

**Comment by mochibuta** [comment]
```
$ wget https://getcomposer.org/composer.phar
$ mv composer.phar /usr/local/bin/composer
$ composer
```
実行するが
```
bash: /usr/local/bin/composer: Permission denied
```

**Comment by mochibuta** [comment]
```
-rw-r--r-- 1 root root 1838679 Apr 10 16:47 composer
```

権限がなかったので与えてみたらうごいた

```
# chmod +x /usr/local/bin/composer
```

**Comment by mochibuta** [comment]
composerインストールおわったのでfakerをいれてみる

**Comment by mochibuta** [comment]
```
# composer require fzaninotto/faker
```
を実行したら

なにか入った
```
bash-4.2# ls -al
total 32
dr-xr-x--- 1 root root 4096 Apr 13 11:27 .
drwxr-xr-x 1 root root 4096 Apr 13 06:49 ..
-rw------- 1 root root  217 Apr 13 11:19 .bash_history
drwxr-xr-x 3 root root 4096 Apr 13 11:24 .composer
drwxr----- 3 root root 4096 Feb  9 00:59 .pki
-rw-r--r-- 1 root root   62 Apr 13 11:27 composer.json
-rw-r--r-- 1 root root 2128 Apr 13 11:27 composer.lock
drwxr-xr-x 4 root root 4096 Apr 13 11:27 vendor
```

**Comment by mochibuta** [comment]
```
# wget https://getcomposer.org/composer.phar
# mv composer.phar /usr/local/bin/composer
```

composerを入れた際に権限をいじったが
composerのドキュメントに記載がなかった？
https://getcomposer.org/doc/00-intro.md

**Comment by mochibuta** [comment]
fakerのREAD.MEに
そもそもcomposerが必要な旨を書いておいておいてくれると助かる

**Comment by mochibuta** [comment]
composerのドキュメント
権限の変更が必要な場合の作業例があってもいいかな？

**Comment by mochibuta** [comment]
Fakerのインストールができたので
readmeのBasic Usageを試してみる

**Comment by mochibuta** [comment]
test.phpというファイルにBasic Usageをコピペする

```
<?php
// require the Faker autoloader
require_once '/path/to/Faker/src/autoload.php';
// alternatively, use another PSR-0 compliant autoloader (like the Symfony2 ClassLoader for instance)

// use the factory to create a Faker\Generator instance
$faker = Faker\Factory::create();

// generate data by accessing properties
echo $faker->name;
  // 'Lucy Cechtelar';
echo $faker->address;
  // "426 Jordy Lodge
  // Cartwrightshire, SC 88120-6700"
echo $faker->text;
  // Dolores sit sint laboriosam dolorem culpa et autem. Beatae nam sunt fugit
  // et sit et mollitia sed.
  // Fuga deserunt tempora facere magni omnis. Omnis quia temporibus laudantium
  // sit minima sint.
```

**Comment by mochibuta** [comment]
requireのパス修正
```
require_once '/path/to/Faker/src/autoload.php';
```

**Comment by mochibuta** [comment]
test.php実行
```
bash-4.2# php test.php
Miss Carmen Shanahan DVM87888 Ledner Manor
North Russeltown, CT 44621-1679Accusantium qui a labore et officiis dignissimos eligendi. Consequatur occaecati hic rem voluptas assumenda. Recusandae nesciunt voluptas at ipsum.
```

**Comment by mochibuta** [comment]
もう一つのBasic Usageのサンプルをうごかしてみる

**Comment by mochibuta** [comment]
```
for ($i=0; $i < 10; $i++) {
  echo $faker->name, "\n";
}
```

**Comment by mochibuta** [comment]
ランダムに名前っぽいのがでた
```
bash-4.2# php test.php
Grayson Schinner V43412 Bechtelar Green Suite 179
Kuvalischester, NC 38084Minima et dolorem nihil odio omnis nisi. Suscipit rerum in ea reiciendis. Quia possimus dicta eos. Nihil iure aliquid in officia aspernatur.Julien Leuschke
Andres Daniel
Mrs. Nayeli Ebert
Curtis Gaylord
Prof. Jodie Ullrich DDS
Mathias Lockman
Savion Hand
Hayden Quitzon PhD
Carlo Champlin
Prof. Vinnie Fadel
```

**Comment by mochibuta** [comment]
READMEにfaker-cliの紹介があったので見てみた。
これも便利そう

```
Tip: For a quick generation of fake data, you can also use Faker as a command line tool thanks to faker-cli.
```

https://github.com/bit3/faker-cli

**Comment by mochibuta** [comment]
一旦fakerを動かしてしまったが
composerの権限に関するドキュメントへ報告してみたいので窓口を探してみる

**Comment by mochibuta** [comment]
composerのgithubを見つけた
https://github.com/composer/composer

**Comment by mochibuta** [comment]
ドキュメントページはmarkdownで書かれてるらしい
ここにフィードバックしたらいいのかな
https://github.com/composer/composer/blob/master/doc/00-intro.md

**Comment by mochibuta** [comment]
Issueを検索してみる

https://github.com/composer/composer/issues

**Comment by mochibuta** [comment]
事例の検索が難しい

**Comment by mochibuta** [comment]
検索するのも大変なので
重複しててもissueあげちゃうか？

**Comment by mochibuta** [comment]
issueで00-intro.mdを検索すると
ドキュメントの編集はプルリクエストを送る形みたいだ

**Comment by knokmki612** [comment]
先日はおつかれさまでした！
issueはcloseしましたが、このまま作業のメモを書いていただいて問題ありません！
フィードバックのレビューはいつでもお待ちしています！issueのメモは私のところでも追えますし、[oss-gate/devel](https://gitter.im/oss-gate/devel)などでも相談いただければと思います！

また、次回のミートアップは5/22(月)になりました！Doorkeeperにイベントページが作成されるのを待っていただくか、[oss-gate/general](https://gitter.im/oss-gate/general)というチャットルームでイベントについて話されているので、こちらを見ていただければと思います！
