### ISSUE TITLE
OSS Gate Workshop: osaka: 2017-04-22: daddygongon: chef: Work log

### ISSUE THREAD

**Issue by daddygongon** [oss-gate/workshop#386]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
ruby2d : processing, vm windows--7
yard : tex記述をつけたいんですが．
chef : 学生のmacへ環境構築の時に便利に

のなかからchefを選択．
https://www.chef.io/chef/
https://github.com/chef/chef/blob/master/LICENSE
のLicenseを開けると
Apache License Version 2.0
でした．OSS

**Comment by daddygongon** [comment]
ではinstall
1. git clone git@github.com:daddygongon/chef.git
1. bundle install
errorが出た．
An error occurred while installing chef-zero (13.0.0), and Bundler cannot continue.
Make sure that `gem install chef-zero -v '13.0.0'` succeeds before bundling.

**Comment by daddygongon** [comment]
bob% gem install chef-zero -v '13.0.0'
ERROR:  Error installing chef-zero:
	chef-zero requires Ruby version >= 2.3.1.
[bob:~/Github/chef] bob% ruyb -v
ruyb: Command not found.
[bob:~/Github/chef] bob% ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
[bob:~/Github/chef] bob% rbenv versions
* system (set by /Users/bob/.ruby-version)
  1.8.7-p358
  1.9.3-p125
  2.1.2
  2.2.3
  2.3.0-dev
  jruby-1.6.7.2

**Comment by daddygongon** [comment]
https://www.google.co.jp/search?client=safari&rls=en&q=chef+development+kit&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=TOP6WK3kPPTO8ge0soagAw
から
MacOS X 10.11用をDL
chefdk-1.3.43-1.pkg

**Comment by daddygongon** [comment]
GithubのDLは依存が多そうなので，chef-dkからDL. 無事
bob% chef -v 
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0
[bob:~/Github/chef] bob% which chef
/usr/local/bin/chef

**Comment by znz** [comment]
Chef DK は https://www.chef.io/chef/ から DOWNLOAD CHEF → Chef Development Kit とたどりました。

**Comment by daddygongon** [comment]
Docks / Quick Start

bob% /opt/chefdk/embedded/bin/ruby

^C-: Interrupt

[bob:~/Github/chef] bob% /opt/chefdk/embedded/bin/ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
[bob:~/Github/chef] bob% chef generate app first_cookbook

**Comment by daddygongon** [comment]
step 5でdefault.rbを編集せよとなっているが，
bob% tree
.
├── README.md
├── cookbooks
│   └── first_cookbook
│       ├── Berksfile
│       ├── chefignore
│       ├── metadata.rb
│       ├── recipes
│       │   └── default.rb
│       └── spec
│           ├── spec_helper.rb
│           └── unit
│               └── recipes
│                   └── default_spec.rb
└── test
    └── smoke
        └── default
            └── default_test.rb

9 directories, 8 files
とdirectoryが深い．説明なかった．

**Comment by daddygongon** [comment]
Learn the Chef basicsに行くが，osxを選ぶチョイスはない．

**Comment by daddygongon** [comment]
https://docs.chef.io/resource_homebrew_package.html
でhomebrewのが入れられる．

ちょっとむづかしいので．．．やめます．

**Comment by daddygongon** [comment]
ansible, puppet, などosxに対応している．
作業serverをつくって，sshでアクセスして作ったら．
versionがあがったら書き換えないといけないので，

sshでアクセスできる環境を作ってはどうだろう．
shell，bashですが，fishでは

**Comment by daddygongon** [comment]
step 5でdefault.rbを編集せよ
で悩んだところを，commentすることにしました．

**Comment by daddygongon** [comment]
daddygongon/chef-web-docs
をforkして，そこから編集して，pull-requestまで進めた．
内容は，
https://github.com/chef/chef-web-docs/pull/604/commits/2434ed55625fdb2dfa4251ba101d2addd10cd802
に反映されて，
When doing step 5 of editing default.rb,
because the location of the file is deep and uncertain,
I looked around to find the file for a while.
Thus the exact directory path will be described explicitly.
とのコメントを残した．

**Comment by daddygongon** [comment]
作業serverを最新版に維持して，そこへsshでaccessすることで，開発環境を統一することにします．localの
chef, chefdkを消去．
chef/          chefdk/        homebrew-cask/
[bob:~/Github] bob% sudo rm -rf /opt/chefdk
Password:
[bob:~/Github] bob% sudo rm -rf /opt/chef
[bob:~/Github] bob% sudo pkgutil --forget com.getchef.pkg.chefdk
[bob:~/Github] bob% sudo find /usr/local/bin -lname '/opt/chefdk/*' -delete

**Comment by akipii** [comment]
Chefも良いですが、最近はAnsibleを使う人をよく見かけます。

**Comment by yabuki** [comment]
コメント遅れました。

**Comment by daddygongon** [comment]
ありがとうございます．ansibleの推薦を他の方からもいただいたので，チェックしてみます．でも，矢吹さんのおすすめのさぎょうserverにアクセスするように指導するのが，一番手間いらずなんで，そこに行きそうです．
emacsだと通信が重そうというのに気がつきましたが．．．

**Comment by daddygongon** [comment]
ありがとうございます．ansibleはその他にも推薦いただいたので，チェックします．
