### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-04-22: orzoy2: emacs: Work log

### ISSUE THREAD

**Issue by orzoy2** [oss-gate/workshop#388]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by orzoy2** [comment]
emacs の read me を読むために、ホームページを探す

**Comment by ShinjiEnoki** [comment]
今日はよろしくお願いします！

**Comment by orzoy2** [comment]
使っているemacsの種類を 
% sudo apt-cache show emacs
Package: emacs
Source: emacs-defaults
Version: 46.1
Installed-Size: 25
Maintainer: Rob Browning <rlb@defaultvalue.org>
Architecture: all
Depends: emacs24 | emacs24-lucid | emacs24-nox
Description-ja: GNU Emacs エディタ (メタパッケージ)
 GNU Emacs は、拡張可能で自己説明的なテキストエディタです。
 これは常に推奨の最新 Emacs リリースに依存するメタパッケージです。
Description-md5: 21fb7da111336097a2378959f6d6e6a8
Tag: devel::editor, role::dummy, role::metapackage, suite::emacs, suite::gnu,
 use::editing
Section: editors
Priority: optional
Filename: pool/main/e/emacs-defaults/emacs_46.1_all.deb
Size: 1634
MD5sum: 1f115942065ac452467e02377368ee22
SHA1: dbb1343a3d24f60e5038994e3528dd7486e40943
SHA256: c1fad54e790d69b83f32f2612963baba3ea8091ff3ca72c960c7312096223e3a

で確認した。

**Comment by orzoy2** [comment]
https://packages.debian.org/ja/jessie/emacs このページを読む

**Comment by orzoy2** [comment]
% where emacs
/usr/bin/emacs

この/usr/binに移動して
 % ls -al | grep emacs
-rwxr-xr-x  1 root   root       98484  3月  8  2015 ctags.emacs24
-rwxr-xr-x  1 root   root       38748  3月  8  2015 ebrowse.emacs24
lrwxrwxrwx  1 root   root          23  9月 28  2016 emacs -> /etc/alternatives/emacs
lrwxrwxrwx  1 root   root           9  3月  8  2015 emacs24 -> emacs24-x
-rwxr-xr-x  1 root   root     9459168  3月  8  2015 emacs24-x
lrwxrwxrwx  1 root   root          29  9月 28  2016 emacsclient -> /etc/alternatives/emacsclient
-rwxr-xr-x  1 root   root       22364  3月  8  2015 emacsclient.emacs24
-rwxr-xr-x  1 root   root       94292  3月  8  2015 etags.emacs24
-rwxr-xr-x  1 root   root        7168  3月  8  2015 grep-changelog.emacs24

**Comment by orzoy2** [comment]
GNU Emacs のホームページを読む
https://www.gnu.org/software/emacs/

**Comment by orzoy2** [comment]
GNU emacs のライセンス
https://www.gnu.org/licenses/licenses.html#GPL

**Comment by orzoy2** [comment]
https://opensource.org/licenses/alphabetical
のサイトで GNU General Public License version 3 (GPL-3.0) のライセンスがあることを確認

**Comment by orzoy2** [comment]
emacs のread me を探しているが、みつからない

**Comment by orzoy2** [comment]
https://www.gnu.org/software/emacs/tour/index.html
emacs の tour を読んだ

**Comment by orzoy2** [comment]
EmacsTutorial は見かけたけど、やったことある

**Comment by orzoy2** [comment]
emacs 上に read me があるとおもって、emacs 上で C-h i を入力したけど、infoページが表示されなかった。

**Comment by orzoy2** [comment]
一旦emacs を消して、もう一度起動してから C-h i を入力したら、ちゃんと infoページが表示された。
期待していたものとはちがっていた。

**Comment by orzoy2** [comment]
emacs はread me というスタイルでおいてないかもしれない？
C-h t のチュートリアルが read me の代わりか？

**Comment by orzoy2** [comment]
C-h t で、チュートリアルを起動したが、久々に見てなつかしい気持ちになった

**Comment by orzoy2** [comment]
emacs の C-h t で表示されたページの下部に、もっともっとヘルプがあったので、それをやってみる

**Comment by orzoy2** [comment]
C-h i のinfoページ内にemacs の FAQ ページをみつけた。
emacs 上で M-x report-emacs-bug をすることで、リポートできるようだ

*****
This is the GNU Emacs FAQ.
   This FAQ is maintained as a part of GNU Emacs.  If you find any
errors, or have any suggestions, please use ‘M-x report-emacs-bug’ to
report them.
*****

**Comment by orzoy2** [comment]
emacs のソースコードを読んで見る

**Comment by orzoy2** [comment]
http://ftp.jaist.ac.jp/pub/GNU/emacs/
ここにソースコードがある

**Comment by orzoy2** [comment]
自分の emacs のヴァージョンを確認する
% emacs --version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

**Comment by iderihatakeshi** [comment]
emacsのソースコードを見てみるのも良いですし、emacsのパッケージ周りをみても面白いと思います。

**Comment by orzoy2** [comment]
emacs のバグレポートがどこに貯められているかを見る

**Comment by orzoy2** [comment]
emacswiki のページからgunのページに飛んで、バグレポートのデーターベースをみつけた
https://debbugs.gnu.org/cgi/pkgreport.cgi?package=emacs

**Comment by orzoy2** [comment]
実際に、あがっているバグレポートを見てみた

**Comment by orzoy2** [comment]
ソースコードをダウンロードして、展開したファイルの中にread me があった。読んで見る

**Comment by orzoy2** [comment]
etc の中に Richard Stallman のインタビューのログファイルがあった

**Comment by orzoy2** [comment]
ディレクトリに入っているファイルの中で、特定のキーワードを grep を使って、そのキーワードと一致するファイルをすべて表示させた
% grep [keyword] * -R

ファイル名を指定するなら
% grep [keyword] [filename]

**Comment by orzoy2** [comment]
debian の apt でemacs のソースコードをとろうとして、失敗した

% sudo apt-get source emacs
[sudo] password for sumi: 
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
'emacs' の代わりに 'emacs-defaults' をソースパッケージとして選出しています
2,582 B のソースアーカイブを取得する必要があります。
取得:1 http://http.debian.net/debian/ jessie/main emacs-defaults 46.1 (dsc) [1,446 B]
取得:2 http://http.debian.net/debian/ jessie/main emacs-defaults 46.1 (tar) [1,136 B]
2,582 B を 1秒 で取得しました (1,889 B/s)   
sh: 1: dpkg-source: not found
展開コマンド 'dpkg-source -x emacs-defaults_46.1.dsc' が失敗しました。
'dpkg-dev' パッケージがインストールされていることを確認してください。
E: 子プロセスが失敗しました

**Comment by orzoy2** [comment]
'dpkg-dev' パッケージがインストールされていることを確認してください。
とあったので、
% sudo apt-get install dpkg-dev

で取ってきて、もう一度
% sudo apt-get source emacs
を実行すると
% sudo apt-get source emacs    
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
'emacs' の代わりに 'emacs-defaults' をソースパッケージとして選出しています
2,582 B のソースアーカイブを取得する必要があります。
取得:1 http://http.debian.net/debian/ jessie/main emacs-defaults 46.1 (dsc) [1,446 B]
取得:2 http://http.debian.net/debian/ jessie/main emacs-defaults 46.1 (tar) [1,136 B]
2,582 B を 0秒 で取得しました (3,663 B/s)   
gpgv: keyblock resource `/root/.gnupg/trustedkeys.gpg': ファイルのオープン・エラー
gpgv: 2014年08月08日 02時03分23秒 JSTにRSA鍵ID 5A5A42F1で施された署名
gpgv: 署名を検査できません: 公開鍵が見つかりません
dpkg-source: warning: failed to verify signature on ./emacs-defaults_46.1.dsc
dpkg-source: info: extracting emacs-defaults in emacs-defaults-46.1
dpkg-source: info: unpacking emacs-defaults_46.1.tar.xz

**Comment by yabuki** [comment]
いろいろと言いましたが、info を読むのもいいですが、書籍もいいですよ。

apt-cache searchを活用して、*-elはemacs lispプログラムです。

**Comment by orzoy2** [comment]
プレリクエストするときのメモ
% git clone https://github.com/orzoy2/workshop.git  
% git add beginner-orzoy2.yaml    
% git status
% git commit -m "Add beginner-orzoy2.yaml"  
% git log
% git push origin master
