### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-04-22: ryo-endo: fish shell: Work log

### ISSUE THREAD

**Issue by ryo-endo** [oss-gate/workshop#389]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ryo-endo** [comment]
今日はfish shellを使ってみる。
https://fishshell.com/

**Comment by yabuki** [comment]
本日はよろしくお願いします

**Comment by ryo-endo** [comment]
インストール
```
EndryMac:Coupon ryo-endo$ brew install fish
==> Downloading https://homebrew.bintray.com/bottles/fish-2.2.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring fish-2.2.0.el_capitan.bottle.tar.gz
==> Caveats
You will need to add:
  /usr/local/bin/fish
to /etc/shells.

Then run:
  chsh -s /usr/local/bin/fish
to make fish your default shell.

If you are upgrading from an older version of fish, you should now run:
  killall fishd
to terminate the outdated fish daemon.
==> Summary
🍺  /usr/local/Cellar/fish/2.2.0: 725 files, 4.6M
```

**Comment by ryo-endo** [comment]
インストール終わったっぽいが、そもそもMacに慣れていないのでメッセージを見て悩む。

**Comment by ryo-endo** [comment]
`/usr/local/bin/`にfishがあることを確認。

```
/usr/local/bin/fish
to /etc/shells.
```
を勘違いして
`mv /usr/local/bin/fish /etc/shells`
として/etc/shellsを壊す。あぁ。

**Comment by ryo-endo** [comment]
http://www.task-notes.com/entry/20150117/1421482066
の内容で`/etc/shells`復旧。

**Comment by yabuki** [comment]
どんまい。復旧したら後は、楽しい動作たーいむ。

**Comment by ryo-endo** [comment]
`fish`で起動できた。
せっかくなので寄り道して`/etc/shells`について調べる。

**Comment by ryo-endo** [comment]
チュートリアルを眺めてみる。
https://fishshell.com/docs/current/tutorial.html

**Comment by ryo-endo** [comment]
bug issue 眺めてみる。
https://github.com/fish-shell/fish-shell/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by ryo-endo** [comment]
再現を試せそうなbug issueがないので、
過去にCLSOEされたissueを眺めてみる。
https://github.com/fish-shell/fish-shell/milestone/12?closed=1

**Comment by ryo-endo** [comment]
### FB
```
/usr/local/bin/fish
to /etc/shells.
```
だと同じ事故するかもしれないので、もっと具体的なほうが良いのでは。

**Comment by ShinjiEnoki** [comment]
先ほどはありがとうございました

**Comment by ryo-endo** [comment]
### よくしたいこと
brewでインストール後に表示されるメッセージがわかりにくい。
`/etc/shells`が何者か知らないと、末尾に追記するということがわからない。

```
You will need to add:
  /usr/local/bin/fish
to /etc/shells.
```

1. `/etc/shells`の中身を確認する
2. `/etc/shells`に`/usr/local/bin/fish`を追記する

みたいなメッセージのほうがわかりやすいのでは？

**Comment by ryo-endo** [comment]
↑
過去に同様のIssueが無いか調べてみたが無さそう。なので投稿してみる。
https://github.com/fish-shell/fish-shell/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20shells%20%20brew%20install%20%20understand

**Comment by ryo-endo** [comment]
こんな感じのIssue でしょうか
↓

i installed fish with `$ brew install fish`.

install is complete.
but, i cant understand the Caveats message.

```
==> Caveats
You will need to add:
  /usr/local/bin/fish
to /etc/shells.
```

i don't know `/etc/shells`.
so, i run command `mv /usr/local/bin/fish /etc/shells`.
(of course, my env is broken)

i propose, modified the Caveats message. like this.
its friendly for beginners.
```
==> Caveats
You will need to add:
  /usr/local/bin/fish
to /etc/shells.

Run this command:
$ echo /usr/local/bin/fish >> /etc/shells
```

### my env
fish, version 2.2.0
Homebrew 0.9.5 (git revision 937e; last commit 2016-02-13)

**Comment by ryo-endo** [comment]
issue 立てました。
フォローありがとうございました:)
```
https://github.com/fish-shell/fish-shell/issues/3976
```

**Comment by znz** [comment]
フィードバックをしたという説明を受けました。
簡潔な説明で、時間があまったので、ここの過去の issue が参考になるという話をしました。
