### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-04-22: dolly8mimiga: WP to kintone: Work log

### ISSUE THREAD

**Issue by dolly8mimiga** [oss-gate/workshop#390]
# ToDo
* WordPressの環境と連携するkintoneの環境を構築する
    - WordPressの環境はすでに以前作成済のものがあったのでOK
    - 対応するkintoneのアプリを作成中

* 構築後に実際に挙動を確認する
* 動かない箇所を確認してソースを修正する（トライアンドエラーみたいな感じで

**Comment by akipii** [comment]
* dolly8mimigaさんにWordPress環境は既にあり。

* 下記プラグインは、GPLｖ２なので問題なし。
WP to kintone — WordPress Plugins https://ja.wordpress.org/plugins/cybozu-wp-to-kintone/#description

**Comment by dolly8mimiga** [comment]
*WordPressのバージョンを最新版にアップデート：バージョン4.7.4

**Comment by dolly8mimiga** [comment]
* kintoneですでに完成しているアプリを開発用のkintoneアカウントに移行する

**Comment by akipii** [comment]
お話を聞くと、REST APIでJSONデータをWordpressからKintoneへ送信しているだけ、とのこと。
ソースを見ると、そんなに難しいソースではない。
但し、お互いのアプリのI/Fが合っていない可能性があるので、試行錯誤が必要と思われる。

**Comment by dolly8mimiga** [comment]
* kintoneですでに完成しているアプリを開発用のkintoneアカウントに移行する
  - アプリの移行完了。あとサンプルデータも（念のため）移行する。

**Comment by akipii** [comment]
kintoneはPaasで作っている、とのことなので、環境作成中。後もう少し。

**Comment by akipii** [comment]
環境構築完了

**Comment by akipii** [comment]
プラグインの配置完了。APIキーも設定完了。

**Comment by akipii** [comment]
WordPress画面から、API実行後、エラー発生。
Numericエラーが出ている。
原因調査中。

**Comment by dolly8mimiga** [comment]
KINTONE API ERROR

Error Message: Application ID must be numeric.
Error Code: kintone

**Comment by dolly8mimiga** [comment]
フォーマットちゃんと直したらエラーはなくなったけど、フォームのレイアウトが反映されていない。要調査。

**Comment by dolly8mimiga** [comment]
ドキュメント読んでひっかかった箇所をフィードバック。

**Comment by dolly8mimiga** [comment]
ドキュメントちゃんと読んだことないから読んだほうがいいかも。

**Comment by znz** [comment]
説明を受けたのと、前回はドキュメントのフィードバックが多かった印象だったという話をしました。

**Comment by dolly8mimiga** [comment]
[kintone app="74" token=”xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx” sub_domain=”0ec8b” orderby=”code” order=”asc”]

**Comment by akipii** [comment]
テキスト1つの問い合わせフォームでも、正常表示されない

**Comment by dolly8mimiga** [comment]
ショートコード通りに記載しても画面にまったく表示されない

**Comment by akipii** [comment]
環境構築したWordPressで、他プラグインが干渉している可能性があるかも、ということで、削除して試してみる。

**Comment by dolly8mimiga** [comment]
<form class="kintone" role="form" method="post" enctype="multipart/form-data">
<input type="hidden" name="_kintone_nonce" value="90d355ae03"><input type="hidden" name="_kintone_key" value="kintone-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<p><button type="submit" class="btn btn-primary btn-large">送信</button></p>
</form>

**Comment by akipii** [comment]
プラグインのソースcybozu-wp-to-kintone.phpのうち、下記をコメントアウトして試してみた。

1)L136～L152　をコメントアウト
→問い合わせボタンが出ない

2)L136～L144　をコメントアウト
→問い合わせボタンが出た

**Comment by akipii** [comment]
cybozu-wp-to-kintone.php　のL144に、else文を追加したところ、WordPressの管理画面が500エラーとなった。
仕方ないので、プラグインを削除して、環境を元に戻す。

**Comment by akipii** [comment]
環境は復活した。フィードバック文を書く。

**Comment by dolly8mimiga** [comment]
`if
 ( get_option( 'kintone-error-message', false ) ) {
				$html .= '<div class="kintone-alert">' . get_option( 'kintone-error-message', false ) . '</div>';
				$error = get_option( 'kintone-error-data', array() );
				$html .= '<script type="application/javascript">var kintone_error = '.json_encode( $error ).';</script>';
				delete_option( 'kintone-error-message' );
				delete_option( 'kintone-error-data' );
			} elseif ( get_option( 'kintone-success', false ) ) {
				$html .= '<div class="kintone-alert kintone-alert-success">' . __( 'Your message was sent successfully.', 'kintone' ) . '</div>';
				delete_option( 'kintone-success' );
			}`

この部分が正常に動作していない

**Comment by dolly8mimiga** [comment]
# 再現手順
* インストールしてショートコード記述

```
    [kintone app="74" token=”xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx” sub_domain=”0ec8b” orderby=”code” order=”asc”]
```

* 上記で記述しても、WordPress側で「送信」ボタンは表示されるが、kintoneのフォームの画面が出ない。
* コンソールで特にエラーもなし。
* formタグは出ているものの、中身が空になっている（おそらく生成されていないと思われる）

```
    if ( get_option( 'kintone-error-message', false ) ) { $html .= '<div class="kintone-alert">' . get_option( 'kintone-error-message', false ) . '</div>'; $error = get_option( 'kintone-error-data', array() ); $html .= '<script type="application/javascript">var kintone_error = '.json_encode( $error ).';</script>'; delete_option( 'kintone-error-message' ); delete_option( 'kintone-error-data' ); } elseif ( get_option( 'kintone-success', false ) ) { $html .= '<div class="kintone-alert kintone-alert-success">' . __( 'Your message was sent successfully.', 'kintone' ) . '</div>'; delete_option( 'kintone-success' ); }
```

**Comment by akipii** [comment]
KintoneはPaasでどんどんバージョンアップされているため、公開APIが変わっている可能性もある。
フィードバックはサイボウズ様へ送付する予定。

**Comment by iderihatakeshi** [comment]
本日はお疲れ様です。とりあえずissueを出す、パッチを書いてPRを出すなど様々な方法があると思いました
