### ISSUE TITLE
ふりかえりの手順が明確でない

### ISSUE THREAD

**Issue by yoichi** [oss-gate/workshop#392]
2017-04-22 Osaka workshopのふりかえりで
https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md
の「ふりかえりの仕方はissueに書いてある」のissueが何を指すのかわかりませんでした。

* 作業ログを書いたissueを指す？ (ふりかえりの題材はあるけど、仕方は書いてないので違う？)

**Comment by knokmki612** [comment]
フィードバックありがとうございます！

以前はissueテンプレートに手順が書いてあった(のでissueに自動的にかかれる)のですが、 7822aee0017751de2e595b8c0d52f690294cde1a で削られたようです。

ふりかえりの説明は、スライドのものを読むと良いかと思います。
https://github.com/oss-gate/workshop/blob/master/tutorial/overview/how-to-start-oss-development.rab#L221

scenario.mdは一度更新する必要があるようですね;

**Comment by kou** [comment]
作業ログのissueに書いてあっても活用されていなかったので消しました！
（どんな心構えでやればいいとか結構細かく書いていたんですけど、細かすぎて読まれない、みたいなパターンだと思います。）
