### ISSUE TITLE
アンケートの pull request 作成手順

### ISSUE THREAD

**Issue by znz** [oss-gate/workshop#406]
2回目の参加で前回の fork がある人が戸惑うことが多いようなので、初回、2回目、3回目以降の pull request の手順がまとまっていると良いのではないかと思いました。

案としては以下のような感じでどうでしょうか。

## 初回

1. https://github.com/oss-gate/workshop を開く
2. 右上の Fork ボタンで fork する
3. Clone する
4. `workshop/tutorial/retrospectives/${YEAR}-${MONTH}-${DAY}-${LOCATION}` に移動する
5. `${ROLE}.yaml` を `${ROLE}-${アカウント名}.yaml` にコピー (移動ではない) して編集する
6. 可能なら `ruby -r yaml -e 'YAML.load(ARGF)' ${ROLE}-${アカウント名}.yaml` などで syntax check する (syntax error があっても進行役が直すので必須ではありません)
7. `git add ${ROLE}-${アカウント名}.yaml`; `git commit`; `git push` で変更を push する
8. https://github.com/oss-gate/workshop から Pull request を作成する

## 2回目

1. `workshop` ディレクトリに移動する
2. `git remote add upstream https://github.com/oss-gate/workshop` で `upstream` という `remote` を追加する
3. `git fetch upstream` で `upstream` の変更をとってくる
4. `git merge upstream/master` で `upstream` の変更を手元の `master` にマージする
5. 以降は初回の4以降と同じ

## 3回目以降

2回目の3以降と同じ

**Comment by kou** [comment]
たしかに、こういうのはあるとよさそうですね！
1回目の人のやつは進行役がデモしながらのフォローもあるといいと思いますけど、2回目以降の人はここを参考に、という感じで読んでもらうやつがよさそうだなぁと思いました。

どこに書くのがいいですかねぇ。
scenario.mdみたいに、how-to-send-questionnaire.mdとか作るといいんですかねぇ。

**Comment by knokmki612** [comment]
https://github.com/oss-gate/retrospective/issues/38
は1回目の手順についてのissueですが、2回目以降についてもworkshop/retrospective/README.mdに書くと、Githubで読みながら作業ができて良いかと思います。

**Comment by kou** [comment]
それはよさそうですね！
