### ISSUE TITLE
OSS Gateワークショップ2016-05-28:  syamagata:  redmine: 作業ログ

### ISSUE THREAD

**Issue by syamagata** [oss-gate/workshop#41]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ2016-03-26: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by syamagata** [comment]
* 作業：インストーラーでドキュメントにない画面が表示される
* 思っていること：ドキュメントの内容が最新ではないのかも

備考：Quick Start と言う画面が追加されている
Docker Quickstart Treminalと、Kitematic（Betaa）から選択するよう表示される
後で、Docker directoryから見ることができるということなので、そのまま続ける

**Comment by syamagata** [comment]
* 作業：いきなり使い方がわからない
* 思っていること：自分が理解できないだけ？

備考：Create a new (or start an existing) virtual machine って言われている
これって、Virtual BoxのVMのこと？ それともDocker自体のVMがあるの？

**Comment by syamagata** [comment]
* 作業：Docker Quickstart Terminal でマニュアルにないエラーが表示される
*思っていること：何が起きているかわからない

備考：ターミナルに以下ように表示される
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate signed by unknown authority.
See 'docker run --help'.

**Comment by syamagata** [comment]
* 作業：Docker Quickstart Terminal が先に進んだ
* 思っていること：とりあえず安心

備考：セキュリティソフトを切ってから、docker run hello-world を実行したらうまく行った

**Comment by kou** [comment]
お疲れ様でした！
（いまさらですが）（まだ覚えていたら）参加した感想をブログなどにまとめてWebに公開してください！新しいビギナー・メンターが増えるきっかけになったり、今後もっとうまくワークショップをやるためのフィードバックになることを期待しています！
