### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-05-27: knokmki612: gPodder: Work log

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#412]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by knokmki612** [comment]
gPodderサイトってどこだろう？

**Comment by knokmki612** [comment]
Sailfish OS版のGpodderの開発ベージってどこ？？？

**Comment by knokmki612** [comment]
Google先生に"gpodder"で検索したら、トップに https://gpodder.org が出てきた！

**Comment by knokmki612** [comment]
Get It!のなかに、Sailfish OSの案内がないな…

**Comment by knokmki612** [comment]
Githubリポジトリはあった https://github.com/gpodder/gpodder

けどSailfish OSは見当たらない

**Comment by knokmki612** [comment]
https://github.com/gpodder gPodderの他のリポジトリを探そう

**Comment by knokmki612** [comment]
https://github.com/gpodder/gpodder-sailfish あった！！！

**Comment by knokmki612** [comment]
RPMのspecファイルにライセンスは ISC / GPLv3 と書いてあった
