### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-05-27: hirakawa-c-connect: vue.js: Work log

### ISSUE THREAD

**Issue by hirakawa-c-connect** [oss-gate/workshop#413]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by onk** [comment]
サポーターの @onk です。よろしくお願いします！

**Comment by ShigeUed** [comment]
植田です。よろしくお願いします。

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by hirakawa-c-connect** [comment]
Googleにて[nginx]で検索し、３つ目に公式サイトと思しき結果を発見。

https://nginx.org/en/

**Comment by hirakawa-c-connect** [comment]
ライセンスの記述がありそうなページを見るも、ぱっと見でライセンスの種類がよくわからない。
https://nginx.org/LICENSE

**Comment by hirakawa-c-connect** [comment]
Googleにて[nginx ライセンス形態]で調べるも、、情報がない。

**Comment by hirakawa-c-connect** [comment]
https://nginx.org/LICENSE
に記述はあるが、、下記のページのリストにあるライセンスとは別の模様。

https://opensource.org/licenses/alphabetical

**Comment by hirakawa-c-connect** [comment]
OSSではあるはずだが、下記のライセンスの一覧になく不安なので、、
nginxからvue.jsへ変更する。

https://opensource.org/licenses/alphabetical

**Comment by hirakawa-c-connect** [comment]
googleで「vue.js」で検索し、公式サイトを探す。

**Comment by hirakawa-c-connect** [comment]
検索結果１件目にあった。

https://jp.vuejs.org/

**Comment by hirakawa-c-connect** [comment]
ページ下にからライセンスページへアクセスし、[MIT License]であることを確認した。

https://opensource.org/licenses/MIT

**Comment by hirakawa-c-connect** [comment]
「はじめる」とあったので、、インストール方法、概要が書いてあると思いアクセス。

https://jp.vuejs.org/v2/guide/

**Comment by hirakawa-c-connect** [comment]
[Vue.js]を簡単に試すための方法として[JSFiddle Hello World example]で
リアルタイムにブラウザで確認しながら試せるので楽。

https://jsfiddle.net/chrisvfritz/50wL7mdz/

**Comment by hirakawa-c-connect** [comment]
local環境でvue.jsを動かすためにHTMLファイルを作成し、公式ページの内容をコピー。

``
<script src="https://unpkg.com/vue"></script>

<div id="app">
  {{ message }}
</div>

var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
``

**Comment by hirakawa-c-connect** [comment]
公式通りの内容が無事表示された！

**Comment by hirakawa-c-connect** [comment]
Chrome(Mac版)でデベロッパーツールの表示方法を忘れたので、Googleで検索。[chrome デベロッパーツール mac]

[option]+[command]+i

で表示可能。

**Comment by hirakawa-c-connect** [comment]
JSコンソールでapp.messageの値を変更し、ブラウザの表示も変わることを確認。

app.message = "hogehoge"

**Comment by hirakawa-c-connect** [comment]
デベロッパーツールのコンソールにて

[入力内容]app2.message = 'some new message'
[出力内容]"some new message"

無事、spanタグのtitle属性の値が変わった。。

**Comment by hirakawa-c-connect** [comment]
変わるのはspanタグのtitle属性だったが、、
間違えてtitleタグかと思い、HTMLのタイトルの内容を確認しようとしてしまう。。。

**Comment by hirakawa-c-connect** [comment]
vue.jsのはじめに記載のある次の構文(if)を試す。

**Comment by hirakawa-c-connect** [comment]
<div id="app-3">
  <p v-if="seen">Now you see me</p>
</div>

var app3 = new Vue({
  el: '#app-3',
  data: {
    seen: true
  }
})
Now you see me

必要な部分のみコピーしたつもりが、余計な次の行までコピーしてしまいJavascriptのエラーとなる。

**Comment by hirakawa-c-connect** [comment]
if文の確認をしたかったので、下記の文を実行し、表示されていた「Now you see me」が消えることを確認

[入力内容]app3.seen=false
[出力内容]false

**Comment by hirakawa-c-connect** [comment]
HTMLやJavascriptのコードを書いたコメントについて、コードをそのまま表示したいのでバッククォートで囲むようコメントを修正する。

**Comment by hirakawa-c-connect** [comment]
次にfor文を試す。

`<div id="app-4">`
`  <ol>`
`    <li v-for="todo in todos">`
`      {{ todo.text }}`
`    </li>`
`  </ol>`
`</div>`

`var app4 = new Vue({`
`  el: '#app-4',`
`  data: {`
 `   todos: [`
 `     { text: 'Learn JavaScript' },`
 `     { text: 'Learn Vue' },`
 `     { text: 'Build something awesome' }`
 `   ]`
`  }`
`})`

**Comment by hirakawa-c-connect** [comment]
`
    app4.todos.push({ text: 'New item' })
`

**Comment by knokmki612** [comment]
ふりかえりました！
vue.jsのドキュメントはよく整備されていそうですね！
普段使っているvue.jsのプラグインを掘り下げてみるのも良いかもしれません！

**Comment by hirakawa-c-connect** [comment]
午前中の間では、フィードバックの内容が見当たらなかったので、vue.jsのプラグインを別途探してフィードバックの内容がないか探す。

**Comment by hirakawa-c-connect** [comment]
Googleで[vue.js validation]で検索し、以下のライブラリを発見。

https://monterail.github.io/vuelidate/

**Comment by hirakawa-c-connect** [comment]
githubのページからLICENSEの内容を確認し、MITライセンスであることを確認。

https://github.com/monterail/vuelidate/blob/master/LICENSE

**Comment by hirakawa-c-connect** [comment]
installコマンド

npm install vuelidate --save

らしいが、npmコマンドが入っているかチェック

`which npm`

インストールされていないようなので、、インストール

`brew install npm`

**Comment by hirakawa-c-connect** [comment]
Vuelidateをインストール

$ npm install vuelidate --save
npm WARN saveError ENOENT: no such file or directory, open '/Users/xxxxxxx/Desktop/vue/package.json'
/Users/xxxxxxx/Desktop/vue
└─┬ vuelidate@0.4.3 
  └── babel-plugin-transform-inline-environment-variables@0.0.2 

npm WARN enoent ENOENT: no such file or directory, open '/Users/fuminori/Desktop/vue/package.json'
npm WARN vue No description
npm WARN vue No repository field.
npm WARN vue No README data
npm WARN vue No license field.

**Comment by hirakawa-c-connect** [comment]
Vue.js同様に[JSFiddle example ]で簡単に動かせるように準備されている。

**Comment by hirakawa-c-connect** [comment]
[Basic form]に書いてある内容をひとまず実施。

**Comment by hirakawa-c-connect** [comment]
記載通りで動いていくので、別のプラグインも試す。

**Comment by hirakawa-c-connect** [comment]
Googleで[vue.js sort plugin]で検索し、ソート用のプラグインを発見。

http://sagalbot.github.io/vue-sortable/

**Comment by hirakawa-c-connect** [comment]
インストール

`npm install vue-sortable`

⸨░░░░░░░░░░░░░░░░░░⸩ ⠏ normalizeTree: sill install loadCurrentTree
/Users/fuminori/Desktop/vue
└─┬ vue-sortable@0.1.3 
  └── sortablejs@1.5.1 

npm WARN enoent ENOENT: no such file or directory, open '/Users/fuminori/Desktop/vue/package.json'
npm WARN vue No description
npm WARN vue No repository field.
npm WARN vue No README data
npm WARN vue No license field.

**Comment by hirakawa-c-connect** [comment]
vue.jsのsortableの内容をみて、GithubのREADMEの内容も見てみたが、記述通りで正しく動いている。

https://github.com/sagalbot/vue-sortable

**Comment by hirakawa-c-connect** [comment]
[vue plugin]で検索し、フォームジェネレータのプラグインを発見。

https://github.com/icebob/vue-form-generator

**Comment by hirakawa-c-connect** [comment]
ひとまずインストール

`npm install vue-form-generator`
`/Users/xxxxxxx/Desktop/vue`
`└── vue-form-generator@2.0.0-beta6 `

`npm WARN enoent ENOENT: no such file or directory, open` `'/Users/xxxxxx/Desktop/vue/package.json'`
`npm WARN vue No description`
`npm WARN vue No repository field.`
`npm WARN vue No README data`
`npm WARN vue No license field.`

**Comment by hirakawa-c-connect** [comment]
git clone

https://github.com/icebob/vue-form-generator.git

**Comment by hirakawa-c-connect** [comment]
ドキュメントに載っている内容を一つづつチェック。

https://icebob.gitbooks.io/vueformgenerator/content/

**Comment by hirakawa-c-connect** [comment]
{
    type: "checklist",
    label: "Roles",
    model: "roles",
    values: [
        { value: "admin", name: "Administrator"},
        { value: "moderator", name: "Moderator"},
        { value: "user", name: "Registered User"},
        { value: "visitor", name: "Visitor"}
}

**Comment by hirakawa-c-connect** [comment]
ドキュメント内の不備(配列がただしく終了していない)があった。

**Comment by hirakawa-c-connect** [comment]
gitbooksを使用したドキュメントであった。まずはgitbooksについて調べる。

**Comment by hirakawa-c-connect** [comment]
Googleで[gitbooksとは]で調べる。

`GitBookとは GitBook とはざっくり言うと、 markdownで書いたドキュメントをhtmlやpdfなどで読みやすい形式に変換をかけて公開まで行えるツール です。 構成する要素として、ざっくり以下の2種類の機能が提供されています。`

**Comment by hirakawa-c-connect** [comment]
しかし、、修正方法に関する記述はない。

**Comment by hirakawa-c-connect** [comment]
以下のgitリポジトリ内を[ grep -ir 'group in the schema groups related fields' .]で検索するも、
該当のドキュメントはなかった。

https://github.com/icebob/vue-form-generator.git

**Comment by hirakawa-c-connect** [comment]
開発者の他のリポジトリも検索したが、ドキュメントと思われるリポジトリはなかった。

**Comment by hirakawa-c-connect** [comment]
ドキュメントの修正方法がわからないので、ソースコードのgit リポジトリのほうにissueで
連絡するのもありかも、とアドバイスを受けたので、あとで実施してみたい。
