### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-05-27 :Makanai : Alamofire: Work log

### ISSUE THREAD

**Issue by maka-nai** [oss-gate/workshop#414]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tdtds** [comment]
がんばりましょう！

**Comment by yukihigasi** [comment]
よろしくお願いします！

**Comment by yuinore** [comment]
宜しくお願いします！！！！！！

**Comment by miurabo** [comment]
よろしくおねがいします！

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by maka-nai** [comment]
cocoapodでインストールは済んでいるので、readmeをちゃんと読もう

**Comment by maka-nai** [comment]
alamofire の https://github.com/Alamofire/Alamofire はここにある

**Comment by maka-nai** [comment]
英語ェ・・・

**Comment by maka-nai** [comment]
readme の Installation は飛ばして、Usage から進める

**Comment by maka-nai** [comment]
Making a Request に下記が書いてあるので、コピペして動かしてみる。

import Alamofire
Alamofire.request("https://httpbin.org/get")

**Comment by maka-nai** [comment]
通信できてんのかわからん！！！！！！！！！！！

**Comment by maka-nai** [comment]
とりあえずブラウザで叩いてみよう

**Comment by maka-nai** [comment]
下記が表示された

{
  "args": {}, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "Accept-Encoding": "gzip, deflate, sdch, br", 
    "Accept-Language": "ja-JP,ja;q=0.8,en-US;q=0.6,en;q=0.4", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "Referer": "https://github.com/oss-gate/workshop/issues/414", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
  }, 
  "origin": "124.219.242.114", 
  "url": "https://httpbin.org/get"
}

**Comment by maka-nai** [comment]
Usage を読み進めよう

**Comment by maka-nai** [comment]
通信できてるのかわからんとか言っていたら、次は Response Handling だった

**Comment by maka-nai** [comment]
再度、下記をコピペ

Alamofire.request("https://httpbin.org/get").responseJSON { response in
    print(response.request)  // original URL request
    print(response.response) // HTTP URL response
    print(response.data)     // server data
    print(response.result)   // result of response serialization

    if let JSON = response.result.value {
        print("JSON: \(JSON)")
    }
}

**Comment by maka-nai** [comment]
print しているので、ログが吐かれた
Optional(https://httpbin.org/get)
Optional(<NSHTTPURLResponse: 0x60800003da40> { URL: https://httpbin.org/get } { status code: 200, headers {
    "Access-Control-Allow-Credentials" = true;
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 400;
    "Content-Type" = "application/json";
    Date = "Sat, 27 May 2017 02:25:00 GMT";
    Server = "meinheld/0.6.1";
    Via = "1.1 vegur";
    "X-Powered-By" = Flask;
    "X-Processed-Time" = "0.000760078430176";
} })
Optional(400 bytes)
SUCCESS
JSON: {
    args =     {
    };
    headers =     {
        Accept = "*/*";
        "Accept-Encoding" = "gzip;q=1.0, compress;q=0.5";
        "Accept-Language" = "en;q=1.0";
        Connection = close;
        Host = "httpbin.org";
        "User-Agent" = "GourmetApp-for-iOS/1.0 (com.gmail-5610.k.takumi.GourmetApp-for-iOS; build:1; iOS 10.3.0) Alamofire/4.4.0";
    };
    origin = "124.219.242.114";
    url = "https://httpbin.org/get";
}

**Comment by maka-nai** [comment]
Usage にはレスポンス例は特に書かれていない

**Comment by maka-nai** [comment]
サンプルコードの下に In the above example から始まる文言があるが、英語で何を書いてあるのかいまいちわからない

**Comment by maka-nai** [comment]
google翻訳に翻訳させてみた

> サーバーからの応答を待つように実行をブロックするのではなく、受信した応答を処理するためのクロージャ形式のコールバックが指定されています。

**Comment by maka-nai** [comment]
非同期通信で行うということがわかったので、さらに Usage 読み進める

**Comment by maka-nai** [comment]
response handler は5種類あるらしい

**Comment by maka-nai** [comment]
レスポンスハンドラは、サーバーエラーを受けてもエラーにならない

**Comment by maka-nai** [comment]
その次の Response Handler を読んでみて、すぐにあるサンプルコードを動かしてみたが、何をしているんだかさっぱりわからない・・・

**Comment by maka-nai** [comment]
Response Handler の見出しとすぐ下のサンプルコードの間の文言の意図を考える・・・

**Comment by maka-nai** [comment]
> 応答ハンドラは、応答データを評価しません。 URLセッションデリゲートから直接すべての情報を転送するだけです。リクエストを実行するのにcURLを使用するのは、Alamofireの同等の機能です。

これは、、、サーバーエラーを判断しない代わりに、サンプルコード内の Error にエラーが入ってくるから、後はよしなにやってくれ、と言っているの・・・か？

**Comment by maka-nai** [comment]
サンプルコードが何をしようとしていて、どうレスポンスを処理しようとしているのかを書いて欲しい

**Comment by maka-nai** [comment]
エラーハンドリングを期待しているのだとしたら、リクエスト先が今までと同じ https://httpbin.org/get だから、エラーにならない

**Comment by maka-nai** [comment]
実行結果は下記で、Error に nil が入ってきている
Request: Optional(https://httpbin.org/get)
Response: Optional(<NSHTTPURLResponse: 0x600000222ea0> { URL: https://httpbin.org/get } { status code: 200, headers {
    "Access-Control-Allow-Credentials" = true;
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 400;
    "Content-Type" = "application/json";
    Date = "Sat, 27 May 2017 02:45:11 GMT";
    Server = "meinheld/0.6.1";
    Via = "1.1 vegur";
    "X-Powered-By" = Flask;
    "X-Processed-Time" = "0.00079607963562";
} })
Error: nil
Data: {
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip;q=1.0, compress;q=0.5", 
    "Accept-Language": "en;q=1.0", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "GourmetApp-for-iOS/1.0 (com.gmail-5610.k.takumi.GourmetApp-for-iOS; build:1; iOS 10.3.0) Alamofire/4.4.0"
  }, 
  "origin": "124.219.242.114", 
  "url": "https://httpbin.org/get"
}

**Comment by maka-nai** [comment]
エラーが発生するように、サンプルのリクエストURLを修正
https://httpbin.org/get  ->   "https://httpb"

**Comment by maka-nai** [comment]
応答結果は、下記

Request: Optional(https://httpb)
Response: nil
Error: Optional(Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x600000054940 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://httpb/, NSErrorFailingURLKey=https://httpb/, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.})
Data:

**Comment by maka-nai** [comment]
その後の項にエラーの処理について、特に言及されてなさそう
（encodingの話になってしまった）

**Comment by maka-nai** [comment]
ここまでの整理として、
・サンプルコードが唐突
　ー　このサンプルを実行すると、こうなる　ってことを先に書いて欲しい
・Error のプロパティが初めて出てきたが、エラーが返ってこないリクエストを送っているので、エラーが返ってくるサンプルも欲しい
　ー　前述にサーバーエラーのことを書いているので、前述したサーバーエラーが起こった時に何が入ってくるのか書いて欲しい

**Comment by maka-nai** [comment]
次に進んで、Response Data Handler を読んでみると、
> responseDataハンドラは、サーバによって返されたデータを抽出するために、responseDataSerializer（サーバデータを他の型にシリアライズするオブジェクト）を使用します。エラーが発生せず、Dataが返された場合、応答Resultは.successになり、値はデータ型になります。

と書いてあった

**Comment by maka-nai** [comment]
実行結果

"All Response Info: SUCCESS: 400 bytes"
Data: {
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip;q=1.0, compress;q=0.5", 
    "Accept-Language": "en;q=1.0", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "GourmetApp-for-iOS/1.0 (com.gmail-5610.k.takumi.GourmetApp-for-iOS; build:1; iOS 10.3.0) Alamofire/4.4.0"
  }, 
  "origin": "124.219.242.114", 
  "url": "https://httpbin.org/get"
}

**Comment by maka-nai** [comment]
わかってたけど、Usage には期待された結果は書かれていない、わかってたけど

**Comment by maka-nai** [comment]
また、Usage には、
> If no errors occur and Data is returned, the response Result will be a .success and the value will be of type Data.

と書いてあるが、successじゃない場合も欲しい

**Comment by maka-nai** [comment]
再度、リクエストURLをエラーが起こるものに変えて実行

"All Response Info: FAILURE: Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.\" UserInfo={NSUnderlyingError=0x600000050350 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 \"(null)\" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://httpb/, NSErrorFailingURLKey=https://httpb/, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}"

**Comment by onk** [comment]
お疲れさまでした！

https://github.com/oss-gate/workshop/issues/414#issuecomment-304423082 にご自身で書いておられるように、README にあるサンプルに出力結果が添えられているとより初心者に対してやさしいというフィードバックができそうですね！

**Comment by maka-nai** [comment]
実行した環境を整理しよう

**Comment by maka-nai** [comment]
XCode は 8.3.2

**Comment by maka-nai** [comment]
Alamofireのバージョンを確認するために、pod list | grep Alamofire を実行

**Comment by maka-nai** [comment]
Alamofire 4.4.0 がインストールされていることを確認

**Comment by maka-nai** [comment]
フィードバックしたい内容は、
* サンプルコードの実行結果を載せて欲しい
* 実行結果を入れるなら、エラーの場合も入れて欲しい
の2点

**Comment by maka-nai** [comment]
実行結果を載せて欲しいので、自分の環境で試した結果をプルリクとして送る

**Comment by maka-nai** [comment]
Alamofire へ送られているプルリクを見てみる

**Comment by maka-nai** [comment]
README の Usage の Response Handling の実行結果の例を追加して欲しい
実行結果の例には、エラー時の結果も追加して欲しい

**Comment by maka-nai** [comment]
google先生お願いします。

**Comment by maka-nai** [comment]
I would like you to add an example of the execution result of Response Handling of Usage of README
As an example of the execution result, I also want to add the result at the time of error

**Comment by maka-nai** [comment]
「README の Usage の Response Handling の実行結果の例を追加して欲しい」の翻訳を少し直す

Add the execution result of Response Handling in README .

**Comment by maka-nai** [comment]
Add the execution result of Response Handling in README .
(Success case and Failure case)

**Comment by maka-nai** [comment]
フィードバックに送る内容を記述したので、descriptionを考える

**Comment by maka-nai** [comment]
プルリクをしました

**Comment by onk** [comment]
ふりかえりました！
Pull Request お疲れさまでしたー
