### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-5-27: yukikato: thymeleaf: Work log

### ISSUE THREAD

**Issue by yukihigasi** [oss-gate/workshop#415]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by parvest** [comment]
よろしくお願いします。

**Comment by miurabo** [comment]
よろしくお願いします！

**Comment by yuinore** [comment]
宜しくお願いします！！！！！！

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by yukihigasi** [comment]
Spring-bootで最近使ったライブラリを全部みる

**Comment by yukihigasi** [comment]
tymeleafのgithub　https://github.com/thymeleaf

**Comment by yukihigasi** [comment]
ライセンスはApache License 2.0 https://github.com/thymeleaf/thymeleaf/blob/3.0-master/LICENSE.txt

**Comment by yukihigasi** [comment]
pom で使ったのを順番に見る

**Comment by yukihigasi** [comment]
spring-projects/spring-boot https://github.com/spring-projects/spring-boot

**Comment by yukihigasi** [comment]
ライセンスは Apache License 2.0　https://github.com/spring-projects/spring-boot/blob/master/LICENSE.txt

**Comment by yukihigasi** [comment]
japのgithub spring-boot/spring-boot-starters/spring-boot-starter-data-jpa/

**Comment by yukihigasi** [comment]
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters/spring-boot-starter-data-jpa

思ったようなファイルがない。

**Comment by yukihigasi** [comment]
starter　というプロジェクトはまた別なのかもしれない　https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters

**Comment by yukihigasi** [comment]
Data JPAは　こっちだった　https://github.com/spring-projects/spring-data-jpa

**Comment by yukihigasi** [comment]
licenceがない

**Comment by yukihigasi** [comment]
data jpaは難しそうなため、一旦tymeleafにする

**Comment by yukihigasi** [comment]
thymeleafはreadmeが空で次のリンクに内容があった　http://www.thymeleaf.org/

**Comment by yukihigasi** [comment]
導入手順を確認 [Looking to get started? Check out our Download section for getting Thymeleaf, then go to our Docs pages for several tutorials to slowly ease you into using Thymeleaf.]とあるので、Downloadを確認し、次にDocsを見る。　導入の先になるプロジェクトをSpring-bootに作っておく

**Comment by yukihigasi** [comment]
Mavenでの導入手順に従う
The easiest way to include Thymeleaf in your project is to use a build system like Maven or Gradle and make use of the Thymeleaf artifacts living in the Central Repository. All you need to do is add the Thymeleaf dependencies you need to your project:

**Comment by yukihigasi** [comment]
先に、載せるプロジェクトを動かす　次に導入手順を行う

**Comment by yukihigasi** [comment]
空のブロジェクトが用意できたため、pomにthymeleafを引き込む

**Comment by knokmki612** [comment]
ふりかえりました！
とりあえず動かしたい人向けに example用のプロジェクトとかあると良いのかなと思いました！

**Comment by yukihigasi** [comment]
ふりかえりいただきありがとうございました！

- 単体で動かせるサンプルがなく、試しづらい
-> とりあえず動かせる空のプロジェクトなどがあればわかりやすい
-> UnitTestがあるのでは？あるのであればそれは単体で動かせる？　確認する
-> そういうものがあることを紹介する記載があれがばかりやすいのではないか

**Comment by yukihigasi** [comment]
mavenでthymleafを読み込むが、この時テンプレートは生成されない。他に最小構成で何が必要なのかが、多分わかりづらい

**Comment by yukihigasi** [comment]
とりあえずまず動かして見たい、という時に、ダウンロードしてから最初に画面を表示するまでの動線がドキュメントではない？

**Comment by yukihigasi** [comment]
tutorialがある。もしかしたらここを読めば解決する？この流れを確認。最小構成がここの手順を追うだけでできるならこの提案は不要。 http://www.thymeleaf.org/documentation.html

**Comment by yukihigasi** [comment]
日本語のドキュメントが提供されていた　http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf_ja.html

**Comment by yukihigasi** [comment]
現在のドキュメントは3.0であるが、日本語のドキュメントは2.1までしかない。今回はこれには触れないことにして、
・初学者がチュートリアルへたどり着き、サンプルを作りきるまでの動線のわかりやすさ
・サンプルの確認
を観点にする

**Comment by yukihigasi** [comment]
1. githubからスタートする  https://github.com/thymeleaf/thymeleaf
2. readmeを確認しリンクを移動する http://www.thymeleaf.org/
3. Let's go!　を確認すると
Looking to get started? Check out our Download section for getting Thymeleaf, then go to our Docs pages for several tutorials to slowly ease you into using Thymeleaf.
　とある。
  「tutorials to slowly ease you into using Thymeleaf.」
　slowlyの意図は？　サクッと動かせる簡単なサンプルはやっぱりないか？
4. ...

**Comment by yukihigasi** [comment]
4. Docsに入りTutrialを確認する
　Using Thymeleaf項目に
　Example application: Good Thymes Virtual Grocery

5. thymeleaf/thymeleafexamples-gtvg サンプルのリポジトリ？
     https://github.com/thymeleaf/thymeleafexamples-gtvg

**Comment by yukihigasi** [comment]
6. サンプルをダウンロードしビルドを進める　問題なし

$ mvn clean
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Thymeleaf Examples - Good Thymes Virtual Grocery ci
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gtvg ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.642 s
[INFO] Finished at: 2017-05-27T14:54:35+09:00
[INFO] Final Memory: 4M/65M
[INFO] ------------------------------------------------------------------------
kato-no-MacBook-Air:thymeleafexamples-gtvg-3.0-master katoyuki$

**Comment by yukihigasi** [comment]
7. compileを行う。問題なし
mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Thymeleaf Examples - Good Thymes Virtual Grocery ci
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.pom (8 KB at 4.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.jar (31 KB at 68.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.2/maven-compiler-plugin-3.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.2/maven-compiler-plugin-3.2.pom (12 KB at 43.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.2/maven-compiler-plugin-3.2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.2/maven-compiler-plugin-3.2.jar (45 KB at 141.6 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.pom
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.pom (3 KB at 10.7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-parent/1.6.6/slf4j-parent-1.6.6.pom
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.6.6/slf4j-parent-1.6.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.6.6/slf4j-parent-1.6.6.pom (13 KB at 51.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
Downloading: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
Downloaded: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom (14 KB at 53.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom (3 KB at 11.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom (10 KB at 35.7 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.pom (2 KB at 6.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/log4j/log4j/1.2.16/log4j-1.2.16.pom
Downloading: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.pom
Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.16/log4j-1.2.16.pom (20 KB at 77.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/log4j/log4j/1.2.15/log4j-1.2.15.pom
Downloading: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.pom
Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.pom (18 KB at 70.9 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/javax/mail/mail/1.4/mail-1.4.pom
Downloading: https://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.pom
Downloaded: https://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.pom (993 B at 4.1 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/log4j/log4j/1.2.15/log4j-1.2.15.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/javax/mail/mail/1.4/mail-1.4.jar
Downloading: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar
Downloading: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.jar
Downloading: https://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.jar
Downloaded: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar (94 KB at 240.5 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar (10 KB at 20.4 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar (25 KB at 36.9 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.jar (383 KB at 365.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.jar (380 KB at 357.9 KB/sec)
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ gtvg ---
[INFO] Using 'ISO-8859-1' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ gtvg ---
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.4/plexus-compiler-api-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.4/plexus-compiler-api-2.4.pom (865 B at 3.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler/2.4/plexus-compiler-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler/2.4/plexus-compiler-2.4.pom (6 KB at 21.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.4/plexus-compiler-manager-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.4/plexus-compiler-manager-2.4.pom (690 B at 2.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.4/plexus-compiler-javac-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.4/plexus-compiler-javac-2.4.pom (769 B at 3.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compilers/2.4/plexus-compilers-2.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compilers/2.4/plexus-compilers-2.4.pom (2 KB at 5.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.4/plexus-compiler-api-2.4.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.4/plexus-compiler-manager-2.4.jar
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.4/plexus-compiler-javac-2.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.4/plexus-compiler-api-2.4.jar (25 KB at 100.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.4/plexus-compiler-manager-2.4.jar (5 KB at 18.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.4/plexus-compiler-javac-2.4.jar (19 KB at 61.5 KB/sec)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 23 source files to /Users/katoyuki/Desktop/thymeleafexamples-gtvg-3.0-master/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.309 s
[INFO] Finished at: 2017-05-27T14:56:08+09:00
[INFO] Final Memory: 15M/83M
[INFO] ------------------------------------------------------------------------

**Comment by yukihigasi** [comment]
サンプルのビルドまでの流れは特に問題なくスムーズに進むことができた。

サンプルを取得するまでに、readmeから公式サイトへ移動し、公式サイトからgithubへ移動する、という流れが長い
サンプルの配置されているリポジトリのリンクを、readmeへ置いてもらえるとすぐサンプルを動かせる

**Comment by yukihigasi** [comment]
サンプル自体に対して
問題や障害などではないが、
formの例がtextfieldしかないが、カレンダー入力、ラジオボタン等の動作するサンプルがあるとありがたい

**Comment by yukihigasi** [comment]
thymeleaf/thymeleafexamples-gtvg 
サンプルのプロジェクト　念のためライセンスをチェック。オープンソース
https://github.com/thymeleaf/thymeleafexamples-gtvg/blob/3.0-master/LICENSE.txt
Apache License 2.0

**Comment by yukihigasi** [comment]
CONTRIBUTING.markdown　
hymeleafexamples-gtvg/blob/3.0-master/CONTRIBUTING.markdown

この部分マークダウン崩れているのでは
![2017-05-27 15 19 32](https://cloud.githubusercontent.com/assets/6186025/26518669/ee862856-42ef-11e7-8f68-e8308b8ebf82.png)

**Comment by yukihigasi** [comment]
・CONTRIBUTING.markdown中に記載されているmarkdownが正しく表示されていない
・場所は「Thymeleaf Individual Contributor License Agreement」以降の見出し

**Comment by yukihigasi** [comment]
マークダウンの修正のみのため、タイトルの部分で「markdownを直した」という旨の記載をし、discriptonは空欄でプルリクエストを行う

**Comment by yukihigasi** [comment]
thymeleaf/thymeleafexamples-gtvg
のドキュメントを修正し、
プルリクエストを行いました。

タイトル： fix broken markdown

**Comment by yukihigasi** [comment]
(リンク添付漏れのため再送)タイトル： fix broken markdown
https://github.com/thymeleaf/thymeleafexamples-gtvg/pull/5

**Comment by onk** [comment]
ふりかえりました！
Pull Request お疲れさまでしたー

example はあまりしっかりバージョン管理してないですけど、ライブラリのリポジトリには
ちゃんと CHANGELOG ありますね。

https://github.com/thymeleaf/thymeleaf/blob/3.0-master/ChangeLog.txt

**Comment by tdtds** [comment]
ぶじにマージされましたね。おめでとう！
PR内では他に同様の壊れ方をしているファイルがないかという会話がされていました。ついでに他のファイルについてもチェックできればよかったですね。
