### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-05-27: miurabo: php-ml: Work log

### ISSUE THREAD

**Issue by miurabo** [oss-gate/workshop#416]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tdtds** [comment]
がんばりましょう！

**Comment by parvest** [comment]
よろしくお願いします。

**Comment by yukihigasi** [comment]
よろしくお願いします！

**Comment by yuinore** [comment]
宜しくお願いします！！！！！！

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by miurabo** [comment]
https://github.com/oss-gate/workshop/issues/415
https://github.com/oss-gate/workshop/issues/414
https://gitter.im/oss-gate/devel

**Comment by miurabo** [comment]
https://github.com/oss-gate/workshop/issues/419

**Comment by miurabo** [comment]
セルフィッシュOS用のgpotter?

**Comment by miurabo** [comment]
より良いメモ

**Comment by miurabo** [comment]
推測とかも書くといいかも

**Comment by miurabo** [comment]
URLとか書く

**Comment by miurabo** [comment]
スライドhttps://slide.rabbit-shocker.org/authors/oss-gate/workshop-tutorial-conclusion/

**Comment by miurabo** [comment]
OSSライセンスの一覧 https://opensource.org/licenses/alphabetical

**Comment by miurabo** [comment]
メモのとり方のスライドどこだろ

**Comment by miurabo** [comment]
まずはライセンスを確認した。https://github.com/php-ai/php-ml/blob/master/LICENSE
MITライセンスだった。

**Comment by miurabo** [comment]
composer require php-ai/php-ml でインストール

**Comment by miurabo** [comment]
サンプル作成
```
require_once 'vendor/autoload.php';

use Phpml\Classification\KNearestNeighbors;

$samples = [[1, 3], [1, 4], [2, 4], [3, 1], [4, 1], [4, 2]];
$labels = ['a', 'a', 'a', 'b', 'b', 'b'];

$classifier = new KNearestNeighbors();
$classifier->train($samples, $labels);

$classifier->predict([3, 2]);
// return 'b'

```

**Comment by miurabo** [comment]
ドキュメントのサンプルに以下を追加
```
+ require_once 'vendor/autoload.php';
```
```
- $classifier->predict([3, 2]);
+ echo $classifier->predict([3, 2]);
```

**Comment by miurabo** [comment]
ライセンスは万一文句いわれないように決めておく。コントリビュートしてもらった、したときとか。普通はどうぞ好きにして下さいという人がほとんどだが変なのがいるかもしれないから決めておく。

**Comment by miurabo** [comment]
ライセンスをはっきりさせてくれというIssueを上げることもある。

**Comment by miurabo** [comment]
サンプルは動いた。

**Comment by miurabo** [comment]
ドキュメントのサンプルコピペで動かない。

**Comment by miurabo** [comment]
これはコントリビュートしてみる。

**Comment by miurabo** [comment]
echo のほうは動かないってか結果が出力されないのでちょっとわかりにくい。

**Comment by miurabo** [comment]
たとえばこれだとreadme.mdを修正してプルリクを出す。プルリクは「コピペだけだと動かないから初心者向けじゃないと思った。こうしたらどうでしょうか？」みたいな感じで出す。ポリシーに合わなかったら受け入れられないだけなので気軽にコントリビュート出せる気がしてきた。

**Comment by miurabo** [comment]
コントリビュート出せる？コントリビュートできる？

**Comment by miurabo** [comment]
プルリク午後から

**Comment by miurabo** [comment]
他なんかないか探す

**Comment by miurabo** [comment]
特徴量をつくる機能があるか調べる

**Comment by miurabo** [comment]
前提条件が書いてないサンプルとかよくあるらしい

**Comment by miurabo** [comment]
コントリビュートするチャンス

**Comment by miurabo** [comment]
Apriori って概念って意味かも。特徴量出すやつこれかな

**Comment by miurabo** [comment]
アプリオリアルゴリズム 読む
https://en.wikipedia.org/wiki/Apriori_algorithm

**Comment by miurabo** [comment]
データマイニング（Data Mining）とは、膨大なデータの集積から何らかの知識（傾向、法則、一般的ルール）を導出する方法を探る研究分野である。http://www.cs.t-kougei.ac.jp/SSys/Apriori.htm

**Comment by miurabo** [comment]
特徴量とデータマイニングの関連性について調査する

**Comment by miurabo** [comment]
sampleいっぱいあるからとりあえずsample動かしてちゃんと動くかみてみるものよかった。午後はそうする。

**Comment by miurabo** [comment]
発電力予想→人工知能は人間を超えるか→特徴量選択、ディープラーニング→アプリオリ→データマイニング

**Comment by miurabo** [comment]
ログ残しといて振り返りするの良い

**Comment by miurabo** [comment]
エラーメモがあると良かった

**Comment by miurabo** [comment]
フィードバック

**Comment by onk** [comment]
お疲れさまでした！

* `require_once` が無いと動かない
* `return` だと出力されないので動かして確認できない

というのをサンプルコードに対してフィードバックするのは絶対に他の人も詰まるところなので、とてもヨサソウなフィードバックポイントだと思いました。

**Comment by miurabo** [comment]
フィードバックの内容整理

サンプルコードをそのままコピペしたみたんですが想定した動作をしませんでした。
具体的には以下のような内容です。

- `require_once` がないと動かない
- `return` だと出力されないので動かして確認できない

（readmeを修正してリンクなどを示す）このように修正してみましたが、PHPの初心者にはこっちのほうがわかりやすくないでしょうか。

```:readme.md
+ require_once 'vendor/autoload.php';
```
```
- $classifier->predict([3, 2]);
+ echo $classifier->predict([3, 2]);
```

**Comment by miurabo** [comment]
英語にする

**Comment by miurabo** [comment]
Feedback summary

I tried copying the sample code as it is but did not do what I assumed.
Specifically, it is as follows.

It does not work without require_once
If it is a return it will not be output so it can not be confirmed by moving it
(I modified the readme to show links etc.) I tried to fix this way, but is not it easy for beginners of PHP to comprehend this?

**Comment by miurabo** [comment]
初プルリクエスト！やったー！
https://github.com/php-ai/php-ml/pull/95

**Comment by miurabo** [comment]
githubもいいな

**Comment by miurabo** [comment]
gitできるまえのOSS開発ってどうやってたんだろう。個人開発ばっかり？

**Comment by miurabo** [comment]
エラー出た。phpunitが必要みたい。
Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /Users/miura/Programs/90_oss_gate/vendor/php-ai/php-ml/tests/Phpml/Association/AprioriTest.php on line 11

**Comment by miurabo** [comment]
そういえばテストの動かし方みたいなのがドキュメントにはないかも

**Comment by miurabo** [comment]
あ、なんかphpunitついて書いてる。https://github.com/php-ai/php-ml/blob/master/CONTRIBUTING.md

**Comment by miurabo** [comment]
CONTRIBUTING.md というのがあった。
https://github.com/php-ai/php-ml/blob/master/CONTRIBUTING.md
コードの修正する場合はコーディング規約とかも気をつける必要あり。
```
コーディング基準

PHP-MLにコードを提供する際には、そのコーディング基準に従わなければなりません。php-cs-fixerルートディレクトリで（v2）を実行するのと同じくらい簡単です。

PHP-CS-Fixerの詳細：http : //cs.sensiolabs.org/
```

**Comment by miurabo** [comment]
`composer require phpunit/phpunit`しないと `ventor/bin` がない

**Comment by miurabo** [comment]
テストのやりかたわかった。
```
% bin/phpunit php-ai/php-ml/tests/Phpml/Association/AprioriTest.php 
PHPUnit 6.1.4 by Sebastian Bergmann and contributors.

...............                                                   15 / 15 (100%)

Time: 125 ms, Memory: 4.00MB

OK (15 tests, 37 assertions)

```

**Comment by miurabo** [comment]
phpunitだと再帰的にテストできるっぽい
```
% bin/phpunit php-ai/php-ml/tests/Phpml/                           
PHPUnit 6.1.4 by Sebastian Bergmann and contributors.

...............................................................  63 / 217 ( 29%)
............................................................... 126 / 217 ( 58%)
............................................................... 189 / 217 ( 87%)
............................                                    217 / 217 (100%)

Time: 21.32 seconds, Memory: 30.00MB

OK (217 tests, 496 assertions)

```

**Comment by miurabo** [comment]
php-ml-examples インストールできない。
```
% composer require php-ai/php-ml-examples
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

                                                                                                                                                          
  [InvalidArgumentException]                                                                                                                              
  Could not find package php-ai/php-ml-examples at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
 ```

**Comment by miurabo** [comment]
php-ml-examplesコピペだけだと動かない。
```
% php classification/languageDetection.php                                                                            (git)-[master]
PHP Warning:  include(vendor/autoload.php): failed to open stream: No such file or directory in /Users/miura/Programs/92_php-ml-examples/classification/languageDetection.php on line 5
PHP Stack trace:
PHP   1. {main}() /Users/miura/Programs/92_php-ml-examples/classification/languageDetection.php:0
```

**Comment by miurabo** [comment]
`composer require php-ai/php-ml` してみる。

**Comment by miurabo** [comment]
動いた。
```
% php classification/languageDetection.php                                                                            (git)-[master]
Accuracy: 0.83333333333333%
```

**Comment by miurabo** [comment]
なんか2個位フィードバックできそうなねたがあるな。１exampleだうんろーどわかりにくい。php-mlのテストそのままではうごかなかったかも。

**Comment by miurabo** [comment]
ドキュメントに書いてない系おおい

**Comment by miurabo** [comment]
再現手順
環境

**Comment by miurabo** [comment]
チェンジログ見る

**Comment by miurabo** [comment]
チェンジログ見ると特徴抽出は機能として有りそう。
```
0.1.0（2016-07-08）

最初にリリースを開発する
機械学習のための基礎ツール：アルゴリズム、相互検証、前処理、特徴抽出
バグ[全般]＃7 - MacでPHP-MLが動作しない
```

**Comment by onk** [comment]
ふりかえりました！
他の人も詰まりそうなところをたくさん見つけられましたね。
Pull Request お疲れさまでしたー

**Comment by miurabo** [comment]
おつかれさまでした。ありがとうございました！

**Comment by miurabo** [comment]
ミートアップもあるらしい平日２時間位

**Comment by miurabo** [comment]
https://github.com/oss-gate/workshop/tree/master/tutorial/retrospectives/2017-05-27-tokyo

**Comment by miurabo** [comment]
ワークショップは一回ビギナーで参加したらサポーターで参加してもよい。手が足りないのでサポーターで参加してほしい。

**Comment by miurabo** [comment]
最近はやりのマストドン

**Comment by miurabo** [comment]
アンケートyaml→集計してた

**Comment by tdtds** [comment]
おっ、マージされましたね。おめでとう！

**Comment by miurabo** [comment]
@tdtds ありがとうございます！うれしいですね！
