### ISSUE TITLE
 OSS Gate Workshop: Tokyo: 2017-05-27: shigeUed: OpenModelica: Work log

### ISSUE THREAD

**Issue by ShigeUed** [oss-gate/workshop#417]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by onk** [comment]
サポーターの @onk です。よろしくお願いします！

**Comment by hirakawa-c-connect** [comment]
よろしくお願いします！

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by ShigeUed** [comment]
https://opensource.org/licenses/alphabetical　からOpenModelicaのライセンス Modelica lisenceを調べるが、リストの中にlisenceがない

**Comment by ShigeUed** [comment]
googleで"modelica license 2"について調べると
https://www.modelica.org/licenses/ModelicaLicense2
が見つかった

**Comment by ShigeUed** [comment]
上記サイトの"Preamble"を読むと、
"The goal of this license is that Modelica related model libraries, software, images, documents, data files etc. can be used freely in the original or a modified form, in open source"
かつ
"Modelica License 2 (to remain free of charge and open source)"
とあるのでオープンソースであることが確認できた（と思う）

**Comment by ShigeUed** [comment]
githubからOpenModelicaのコンパイラOMCompilerのリポジトリを見つける
https://github.com/OpenModelica/OMCompiler

**Comment by ShigeUed** [comment]
Readmeを見つける
https://github.com/OpenModelica/OMCompiler/blob/master/README.Linux.md

**Comment by ShigeUed** [comment]
VurtualBoxにUbuntu16.04を入れた環境からReadMeを上から順に試してみる

**Comment by ShigeUed** [comment]
Windows10環境上にVurtualBoxに入れているが、
Windows上でコピーしたものがUbuntuに貼り付けできない
VurtualBoxのクリップボードの設定は双方向にしているが、昔から成功したためしがない
VMWareなら貼り付けできるが、Windows10だと画面が小さくなってしまう
ツールを入れれば大きくなるらしいがインストール出来なかった思い出がある

**Comment by ShigeUed** [comment]
上記の理由でコピペがやりづらい。。。
ubuntuからコピーするが、ubuntuが日本語化していないので検索しづらい

**Comment by ShigeUed** [comment]
一行目エラーがないので通ったと思う
細かいメッセージや作業ログはubuntu上にとる

**Comment by ShigeUed** [comment]
ubuntu上でログをとっているが、日本語化していなかったので
たどたどしい英語でログをとる。作業効率が悪い。

**Comment by ShigeUed** [comment]
フィードバックしたいエラーを頂いたのでここにコピペしたいが
VurtualBox上でsharefolderの設定をしないとここに貼り付けできない。面倒。
概要だけ記述する。

**Comment by ShigeUed** [comment]
Macbook持ってくればよかった

**Comment by ShigeUed** [comment]
開発元が提供している依存パッケージが間違っているようで
apt-getで
"some package could not be installed"と出てくる。
g++-4.4（とその他）がインストールできない、と言われる

**Comment by ShigeUed** [comment]
ここまでのターミナルのログを張り付ける

**Comment by ShigeUed** [comment]
ちなみに以下のコマンドを行う前に、公開鍵の設定の問題も起こっている。

**Comment by ShigeUed** [comment]
LibreOfficeでメッセージログを記録していたが、
LibreOfficeからgithubのissueにコピペするとpngファイルになり、
さらにメッセージが切れてしまう。
一回テキストに書いてここにコピペする。

**Comment by ShigeUed** [comment]
1step
$ echo deb http://build.openmodelica.org/apt precise nightly | sudo tee -a /etc/apt/sources.list
[sudo] password for ueda: 
deb http://build.openmodelica.org/apt precise nightly

**Comment by ShigeUed** [comment]
2 step
$ echo deb-src http://build.openmodelica.org/apt precise nightly | sudo tee -a /etc/apt/sources.list
deb-src http://build.openmodelica.org/apt precise nightly

**Comment by ShigeUed** [comment]
3 step
ueda@ueda-VirtualBox:~$ sudo apt-get update	
	Hit:1 http://jp.archive.ubuntu.com/ubuntu xenial InRelease                     
	Get:2 http://jp.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]    
	Get:3 http://jp.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]  
	Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
	Ign:5 http://build.openmodelica.org/apt precise InRelease                      
	Get:6 http://build.openmodelica.org/apt precise Release [16.6 kB]
	Get:7 http://build.openmodelica.org/apt precise Release.gpg [473 B]
	Ign:7 http://build.openmodelica.org/apt precise Release.gpg
	Get:8 http://build.openmodelica.org/apt precise/nightly Sources [41.1 kB]
	Get:9 http://build.openmodelica.org/apt precise/nightly amd64 Packages [20.0 kB]
	Get:10 http://build.openmodelica.org/apt precise/nightly i386 Packages [20.0 kB]
	Fetched 405 kB in 6s (59.0 kB/s)                                               
	W: GPG error: http://build.openmodelica.org/apt precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3A59B53664970947
	W: The repository 'http://build.openmodelica.org/apt precise Release' is not signed.
	N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
	N: See apt-secure(8) manpage for repository creation and user configuration details.
	E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
	E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by ShigeUed** [comment]
上記は公開鍵のエラーが起こった場合のログ。
解決策は以下

**Comment by ShigeUed** [comment]
$ sudo apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 3A59B53664970947
[sudo] password for ueda: 
Executing: /tmp/tmp.WnFjWSTdIJ/gpg.1.sh --keyserver
ha.pool.sks-keyservers.net
--recv-keys
3A59B53664970947
gpg: requesting key 64970947 from hkp server ha.pool.sks-keyservers.net
gpg: key 64970947: public key "OpenModelica Build System <build@openmodelica.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

**Comment by ShigeUed** [comment]
再度、3行目を行う

**Comment by ShigeUed** [comment]
ueda@ueda-VirtualBox:~$ sudo apt-get update
Hit:1 http://jp.archive.ubuntu.com/ubuntu xenial InRelease                                                       
Get:2 http://jp.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                                      
Get:3 http://jp.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                                    
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                       
Ign:5 http://build.openmodelica.org/apt precise InRelease                                                        
Hit:6 http://build.openmodelica.org/apt precise Release  
Get:7 http://build.openmodelica.org/apt precise Release.gpg [473 B]
Fetched 307 kB in 3s (86.9 kB/s)
Reading package lists... Done
W: http://build.openmodelica.org/apt/dists/precise/Release.gpg: Signature by key D229AF1CE5AED74E5F59DF303A59B53664970947 uses weak digest algorithm (SHA1)

**Comment by ShigeUed** [comment]
4 step
$ sudo apt-get build-dep openmodelica
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 builddeps:openmodelica : Depends: g++-4.4 but it is not installable
                          Depends: openjdk-6-jdk but it is not installable or
                                   sun-java6-jdk but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by ShigeUed** [comment]
g++-4.4をインストールしようと試みる

**Comment by ShigeUed** [comment]
$ sudo apt install g++-4.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package g++-4.4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'g++-4.4' has no installation candidate

**Comment by ShigeUed** [comment]
g++-4.4はインストールできないらしい。
上記の 4 stepが
開発元が提供している依存パッケージが間違っているとonkさんからアドヴァイス頂く。
とりあえず最新のg++をインストールする

**Comment by ShigeUed** [comment]
$ sudo apt install g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.

**Comment by ShigeUed** [comment]
すでに最新バージョンだったと。。。　軽いフラストレーションがたまることを実感する。

**Comment by ShigeUed** [comment]
以下の他の依存を確認する。
openjdk-6-jdk
sun-java6-jd

**Comment by ShigeUed** [comment]
$ sudo apt-get install openjdk-6-jdk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package openjdk-6-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt apt:i386

E: Package 'openjdk-6-jdk' has no installation candidate

**Comment by ShigeUed** [comment]
openjdk-6-jdkはないので、
openjdk-7-jdkかopenjdk-8-jdkをインストールする

**Comment by ShigeUed** [comment]
$ sudo apt-get install openjdk-8-jdk

…
Processing triggers for ca-certificates (20160104ubuntu1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.

**Comment by ShigeUed** [comment]
openjdkの新しいバージョンがインストールできた

**Comment by ShigeUed** [comment]
ようやくgit cloneまできた

**Comment by ShigeUed** [comment]
git cloneでエラー発生

**Comment by ShigeUed** [comment]
$ git clone --recursive https://openmodelica.org/git-readonly/OpenModelica.git OpenModelica
Cloning into 'OpenModelica'...
remote: Counting objects: 129234, done.
remote: Compressing objects: 100% (27634/27634), done.
remote: Total 129234 (delta 104191), reused 121303 (delta 100255)
Receiving objects: 100% (129234/129234), 48.21 MiB | 651.00 KiB/s, done.
Resolving deltas: 100% (104191/104191), done.
Checking connectivity... done.
Submodule 'OMC' (https://openmodelica.org/git-readonly/OMCompiler.git) registered for path 'OMCompiler'
Submodule 'OMEdit' (https://openmodelica.org/git-readonly/OMEdit.git) registered for path 'OMEdit'
Submodule 'OMNotebook' (https://openmodelica.org/git-readonly/OMNotebook.git) registered for path 'OMNotebook'
Submodule 'OMOptim' (https://openmodelica.org/git-readonly/OMOptim.git) registered for path 'OMOptim'
Submodule 'OMPlot' (https://openmodelica.org/git-readonly/OMPlot.git) registered for path 'OMPlot'
Submodule 'OMShell' (https://openmodelica.org/git-readonly/OMShell.git) registered for path 'OMShell'
Submodule 'common' (https://openmodelica.org/git-readonly/OpenModelica-common.git) registered for path 'common'
Submodule 'doc' (https://openmodelica.org/git-readonly/OpenModelica-doc.git) registered for path 'doc'
Submodule 'libraries' (https://openmodelica.org/git-readonly/OMLibraries.git) registered for path 'libraries'
Submodule 'testsuite' (https://openmodelica.org/git-readonly/OpenModelica-testsuite.git) registered for path 'testsuite'
Cloning into 'OMCompiler'...
remote: Counting objects: 154944, done.
remote: Compressing objects: 100% (27036/27036), done.
remote: Total 154944 (delta 129052), reused 151963 (delta 126401)
Receiving objects: 100% (154944/154944), 55.68 MiB | 454.00 KiB/s, done.
Resolving deltas: 100% (129052/129052), done.
Checking connectivity... done.
Submodule path 'OMCompiler': checked out 'ddfec0ed75ac8907910c3f3d641ab7db61861385'
Submodule '3rdParty' (https://openmodelica.org/git-readonly/OMCompiler-3rdParty) registered for path '3rdParty'
Submodule 'common' (https://openmodelica.org/git-readonly/OpenModelica-common) registered for path 'common'
Cloning into '3rdParty'...
remote: Counting objects: 10237, done.
remote: Compressing objects: 100% (6023/6023), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://openmodelica.org/git-readonly/OMCompiler-3rdParty' into submodule path '3rdParty' failed
Failed to recurse into submodule path 'OMCompiler'

**Comment by ShigeUed** [comment]
submoduleの"OMCompiler-3rdParty"をcloneするのに失敗した。
パスがおかしいらしい

**Comment by ShigeUed** [comment]
I searched (fatal: clone of  into submodule path failed) in google
and get following site
http://d.hatena.ne.jp/pasela/20120722/git_submodule_error

**Comment by ShigeUed** [comment]
$ cat .gitmodules
[submodule "OMEdit"]
	path = OMEdit
	url = ../OMEdit.git
[submodule "doc"]
	path = doc
	url = ../OpenModelica-doc.git
[submodule "OMOptim"]
	path = OMOptim
	url = ../OMOptim.git
[submodule "OMPlot"]
	path = OMPlot
	url = ../OMPlot.git
[submodule "OMNotebook"]
	path = OMNotebook
	url = ../OMNotebook.git
[submodule "common"]
	path = common
	url = ../OpenModelica-common.git
[submodule "libraries"]
	path = libraries
	url = ../OMLibraries.git
[submodule "OMC"]
	path = OMCompiler
	url = ../OMCompiler.git
[submodule "testsuite"]
	path = testsuite
	url = ../OpenModelica-testsuite.git
[submodule "OMShell"]
	path = OMShell
	url = ../OMShell.git

**Comment by ShigeUed** [comment]
submoduleについて知らないので以下のサイトで調べる
http://qiita.com/ma2saka/items/4bd00ef6f8c240847807
http://qiita.com/sotarok/items/0d525e568a6088f6f6bb

**Comment by ShigeUed** [comment]
以下を使って3rdPartyのパスを設定してあげれば解決しそう

以下、コピペ
------------------------------------------------------------------------------------------------
git submodule add で別の git リポジトリを追加できる
$ git submodule add "git:../library1.git" library1
これやった直後は .gitmodules ってファイルができるだけだと思ってOK。

$ cat .gitmodules 
[submodule "library1"]
    path = library1
    url = git:../library1.git
追加した後は、git submodule update --init してあげること。

**Comment by ShigeUed** [comment]
$ git submodule add "git:../OMCompiler-3rdParty.git" 3rdParty
Cloning into '3rdParty'...
ssh: Could not resolve hostname git: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git:../OMCompiler-3rdParty.git' into submodule path '3rdParty' failed
ueda@ueda-VirtualBox:~/OpenModelica$ git submodule add "git:https://github.com/OpenModelica/OMCompiler-3rdParty.git" 3rdParty
Cloning into '3rdParty'...
fatal: I don't handle protocol 'git:https'
fatal: clone of 'git:https://github.com/OpenModelica/OMCompiler-3rdParty.git' into submodule path '3rdParty' failed

**Comment by ShigeUed** [comment]
$ git submodule add "https://github.com/OpenModelica/OMCompiler-3rdParty.git" 3rdParty
Cloning into '3rdParty'...
remote: Counting objects: 10237, done.
remote: Total 10237 (delta 0), reused 0 (delta 0), pack-reused 10236
Receiving objects: 100% (10237/10237), 28.22 MiB | 816.00 KiB/s, done.
Resolving deltas: 100% (4425/4425), done.
Checking connectivity... done.

**Comment by ShigeUed** [comment]
7 step
$ autoconf
installされていなかった。

**Comment by ShigeUed** [comment]
$ autoconf
The program 'autoconf' is currently not installed. You can install it by typing:
sudo apt install autoconf

$ sudo apt-get install autoconf

$ autoconf
ueda@ueda-VirtualBox:~/OpenModelica$

**Comment by ShigeUed** [comment]
8 step

**Comment by ShigeUed** [comment]
たぶんomniidlがない

**Comment by ShigeUed** [comment]
$ sudo apt-get install omniidl
and OK

**Comment by ShigeUed** [comment]
$ ./configure --with-omniORB
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
ln: failed to create symbolic link '.git/hooks/pre-commit': File exists
configure: OpenModelica commit-msg hook has been installed
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
build_short: x86_64-linux-gnu
host_short: x86_64-linux-gnu
checking if cppruntime is requested... no
checking for omlibrary target... core
checking for libraries directory... yes
checking for omniidl... /usr/bin/omniidl
checking for CORBA... omniorb
/usr/bin/m4:configure.ac:98: cannot open `common/m4/pre-commit.m4': No such file or directory
/usr/bin/m4:configure.ac:100: cannot open `common/m4/ombuilddir.m4': No such file or directory
/usr/bin/m4:configure.ac:254: cannot open `common/m4/ax_cxx_compile_stdcxx_11.m4': No such file or directory
/usr/bin/m4:configure.ac:599: cannot open `common/m4/corba.m4': No such file or directory
/usr/bin/m4:configure.ac:768: cannot open `common/m4/semver.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
configure: error: "Failed to autoconf OMCompiler"

**Comment by ShigeUed** [comment]
Searched following message in google
/usr/bin/m4:configure.ac:98: cannot open common/m4/pre-commit.m4': No such file or directory /usr/bin/m4:configure.ac:100: cannot opencommon/m4/ombuilddir.m4': No such file or directory

and I found this site
https://chess.eecs.berkeley.edu/ptexternal/wiki/Main/OpenModelica

**Comment by knokmki612** [comment]
ふりかえりしました！お疲れ様でした！

https://www.openmodelica.org/download/download-linux こちらのページが参考になりそうです！

DebianのjessieとUbuntuのtrusty, xenial, yakketyにパッケージを提供しているようですね！
VMに入っているUbuntuはxenialかなと思います。それに対して、今回の作業で指定されていたのはpreciseなので、それでパッケージの依存関係がおかしかったのだと思います！

/etc/apt/souces.listで`deb-src http://build.openmodelica.org/apt xenial nightly`に書き換えからbuild-depでパッケージを引っ張ってこれるかもしれません！

**Comment by knokmki612** [comment]
なので、 https://github.com/OpenModelica/OMCompiler/blob/master/README.Linux.md のDebian/Ubuntu Compile Cheat Sheetのpreciseの部分がとにかく古いので、xenialに書き換えてプルリクするとかがフィードバックポイントかもしれません！

また、"Debianの場合はxenialの部分をjessieに書き換えて実行してください"みたいな文言が欲しいかもしれませんね！

**Comment by ShigeUed** [comment]
返信遅くなり申し訳ありません。
振り返りありがとうございます！！
Ubuntuのバージョンの違いがあるとは思いませんでした。
今から教えていただいた方法でビルドしてみます！

**Comment by ShigeUed** [comment]
/etc/apt/souces.listの
"deb-src http://build.openmodelica.org/apt precise nightly"
を
"deb-src http://build.openmodelica.org/apt xenial nightly"
に書き換えてupdateを実行

**Comment by ShigeUed** [comment]
W: http://build.openmodelica.org/apt/dists/precise/Release.gpg: Signature by key D229AF1CE5AED74E5F59DF303A59B53664970947 uses weak digest algorithm (SHA1)

**Comment by ShigeUed** [comment]
グーグルで調べると、セキュリティ的に弱い、という警告らしいので続けて作業を行う

**Comment by ShigeUed** [comment]
2 step
$ sudo apt-get build-dep openmodelica
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list

**Comment by ShigeUed** [comment]
上記のエラーは、多分source.listにちゃんとしたURLを入れてくれってことだと思うが、
そのURLは何だろうか？

**Comment by ShigeUed** [comment]
まだ適切な設定とエラーを読み解くスキルがないので
大人しくpreciseでビルドを試してみるのが良いかもしれない。

**Comment by ShigeUed** [comment]
とりあえずpreciseは気にしないで、現状のエラー
"/usr/bin/m4:configure.ac:98: cannot open common/m4/pre-commit.m4': No such file or directory "
について対処してみる

**Comment by ShigeUed** [comment]
https://chess.eecs.berkeley.edu/ptexternal/wiki/Main/OpenModelica
のサイトの
"autoconf fails because common/m4/pre-commit.m4 is not found."
の中で解決策を書いてある。

**Comment by ShigeUed** [comment]
# Replace the openmodelica.org pull URL with https://github.com/OpenModelica/OpenModelica.git if you want to pull directly from github
# The default choice is to push to your fork on github.com (SSH). Replace MY_FORK with OpenModelica to push directly to the OpenModelica repositories (if you have access)
MY_FORK=MyGitHubUserName ; git clone https://openmodelica.org/git-readonly/OpenModelica.git --recursive && (cd OpenModelica && git remote set-url --push origin git@github.com:$MY_FORK/OpenModelica.git && git submodule foreach --recursive 'git remote set-url --push origin `git config --get remote.origin.url | sed s,^.*/,git@github.com:'$MY_FORK'/,`')

**Comment by ShigeUed** [comment]
上記のコマンドの意味を一つ一つ調べて自分用に書き換えれば解決するのかもしれない

**Comment by ShigeUed** [comment]
いったん諦めてpreciseでビルドできるか確認してみたいと思う
