### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-05-27: yuinore: beatoraja: Work log

### ISSUE THREAD

**Issue by yuinore** [oss-gate/workshop#419]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tdtds** [comment]
がんばりましょう！

**Comment by yukihigasi** [comment]
よろしくお願いします！

**Comment by parvest** [comment]
よろしくお願いします。

**Comment by yuinore** [comment]
宜しくお願いします！！！！！！

**Comment by sioaji** [comment]
鈴木です。よろしくお願いします。

**Comment by miurabo** [comment]
三浦です。よろしくお願いします！

**Comment by yuinore** [comment]
まず、githubのリポジトリを探します。

**Comment by yuinore** [comment]
https://github.com/exch-bms2/beatoraja ありました。

**Comment by yuinore** [comment]
ライセンスを確認します。GPL-3.0でしたのでOSSです。

**Comment by yuinore** [comment]
git clone します。

**Comment by yuinore** [comment]
git clone に時間がかかりそうなので先に環境を用意します。

**Comment by yuinore** [comment]
JRE 1.8.0 64bit Windows 版をダウンロードしてインストールします。

**Comment by yuinore** [comment]
なぜなら、readme.mdにそう書いてあるからです。

**Comment by yuinore** [comment]
How to contribute を探しましたが、ありませんでした。Eclipseのプロジェクトファイルもなさそうでした。

**Comment by yuinore** [comment]
build.xml というファイルがあるので、「build.xml java」でgoogle検索します。

**Comment by yuinore** [comment]
http://www.atmarkit.co.jp/ait/articles/0301/16/news002.html

なんということでしょう！ build.xml は、Ant というビルドツールで使われる設定ファイルだったのです！ これで開発環境が分かりました。Ant をインストールしましょう。

**Comment by yuinore** [comment]
beatorajaのリポジトリにはantのインストール方法は書かれていないため、「ant windows インストール」で検索し、出てきた記事を見ます。

http://uturo2.nevernothing.jp/apache_ant/
https://www.javadrive.jp/ant/install/

これらによると、zip形式のバイナリをダウンロードし、展開し、環境変数 ANT_HOME, JAVA_HOME, PATH を設定すればよいことが分かります。

**Comment by yuinore** [comment]
Ant を C:\usr\ant に置き、環境変数 ANT_HOMEをC:\usr\ant に、JAVA_HOME を C:\Program Files\Java\jdk1.8.0_131 にして、PATHの末尾に %ANT_HOME%\bin を追加します。

**Comment by yuinore** [comment]
コマンドプロンプトを開き、 java コマンドと ant コマンドが通ることを確認します。

**Comment by yuinore** [comment]
beatoraja リポジトリの git clone が終わりました。1時間半掛かりました。

**Comment by yuinore** [comment]
beatoraja リポジトリをクローンしたディレクトリに移動し、ant コマンドを叩きます。少し経過すると BUILD SUCCESSFUL と表示されました。

**Comment by yuinore** [comment]
無事にビルドされたことを確認するために、beatoraja を起動しようと思います。

README.md に How to Use というセクションがあり、ここに、起動時のコマンドが書いてあるため、これを入力します。

>java -jar beatoraja.jar

これを入力すると、無事画面が表示されたので、ビルドに成功したことが分かります。

**Comment by yuinore** [comment]
楽曲が入っているディレクトリを指定してbeatorajaを起動する方法がわからないことに気が付きました。調べます。

**Comment by yuinore** [comment]
存在しない譜面ファイルを指定すると、プロセスが残ったまま描画ウィンドウが消失してしまい、タスクマネージャーからプロセスを終了させる必要があることがわかりました。

**Comment by yuinore** [comment]
README.md の How to Use を見ると -c で設定画面を開けることがわかりました。

**Comment by yuinore** [comment]
README.md の How To Use のオプション一覧の部分がリスト状になっていないことが分かりました。

**Comment by yuinore** [comment]
releaseパッケージに入っているbeatoraja-config.batがリポジトリに存在せず、またビルドしても生成されないようです。

**Comment by yuinore** [comment]
フィードバックを作成します

**Comment by yuinore** [comment]
環境はWindows 10 64bit, JRE 1.8.0_131です

beatoraja.jar をBMSファイル指定で起動した場合で、指定されたファイルが存在しなかった場合、
描画ウインドウが消失したまま、Ctrl+C以外の入力を受け付けない状態になるという現象が発生しました。

例えば、

java -jar beatoraja.jar C:\non-existing-file

このように入力すると、次のようにエラーが出力されました。

C:\mint\Dropbox\github\beatoraja>java -jar beatoraja.jar C:\non-existing-file
Controllers: added manager for application, 1 managers active

5 27, 2017 2:25:00 午後 bms.model.BMSDecoder decode
重大: BMSファイル解析中の例外 : java.nio.file.NoSuchFileException - C:\non-existing-file
5 27, 2017 2:25:00 午後 bms.player.beatoraja.PlayerResource setBMSFile
警告: 楽曲が存在しないか、解析時にエラーが発生しました:C:\non-existing-file
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.play.BMSPlayer.<init>(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.MainController.create(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

最新のRelease版0.4.1でも同様の現象が発生しました。

**Comment by yuinore** [comment]
箇条書きにするなどして、簡潔なものに修正します。

**Comment by yuinore** [comment]
現象
描画ウィンドウが消失した状態のまま、コンソール画面が入力を受け付けなくなる。
ソースコードからビルドしたものでも、最新のRelease版0.4.1でも同様の現象が発生しました。

再現方法
・存在しないファイルを指定して beatoraja.jar を起動する
　（例えば、java -jar beatoraja.jar C:\non-existing-file）

コンソール出力

Controllers: added manager for application, 1 managers active

5 27, 2017 2:25:00 午後 bms.model.BMSDecoder decode
重大: BMSファイル解析中の例外 : java.nio.file.NoSuchFileException - C:\non-existing-file
5 27, 2017 2:25:00 午後 bms.player.beatoraja.PlayerResource setBMSFile
警告: 楽曲が存在しないか、解析時にエラーが発生しました:C:\non-existing-file
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.play.BMSPlayer.<init>(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.MainController.create(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

環境
・Windows 10 64bit
・JRE 1.8.0_131
・Apache Ant 1.10.1

**Comment by yuinore** [comment]
期待する出力の項を追加します

**Comment by yuinore** [comment]
タイトルと期待する結果を追加しました

**Comment by yuinore** [comment]
【存在しないファイルが指定されたとき、描画ウィンドウが消失した状態のまま、コンソール画面が入力を受け付けなくなる。】

現象
描画ウィンドウが出現した後、すぐに描画ウィンドウが消失し、
その状態のまま、コンソール画面が入力を受け付けなくなります。
ソースコードからビルドしたものでも、最新のRelease版0.4.1でも同様の現象が発生しました。

期待する結果
プログラムが直ちに終了し、コマンドプロンプトに処理を返す。

再現方法
・存在しないファイルを指定して beatoraja.jar を起動する
　（例えば、java -jar beatoraja.jar C:\non-existing-file）

コンソール出力

Controllers: added manager for application, 1 managers active

5 27, 2017 2:25:00 午後 bms.model.BMSDecoder decode
重大: BMSファイル解析中の例外 : java.nio.file.NoSuchFileException - C:\non-existing-file
5 27, 2017 2:25:00 午後 bms.player.beatoraja.PlayerResource setBMSFile
警告: 楽曲が存在しないか、解析時にエラーが発生しました:C:\non-existing-file
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.play.BMSPlayer.<init>(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.MainController.create(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

環境
・Windows 10 64bit
・JRE 1.8.0_131
・Apache Ant 1.10.1

**Comment by yuinore** [comment]
when I execute jar with a non-existing BMS path, the application receives no keyboard inputs

What happens:
Immediately after the game window appear, the game window disappears.
After that, the console window receives no keyboard input.
I built the source code and ran the application,
but the same thing has happened with Released version 0.4.1.

Expected behavior:
The application exits immediately, and returns to cmd.exe

Reproduce step:
execute beatoraja.jar with a non-existing BMS path.
(for example: `java -jar beatoraja.jar C:\non-existing-file` )

Console output:

```
Controllers: added manager for application, 1 managers active

5 27, 2017 2:25:00 午後 bms.model.BMSDecoder decode
重大: BMSファイル解析中の例外 : java.nio.file.NoSuchFileException - C:\non-existing-file
5 27, 2017 2:25:00 午後 bms.player.beatoraja.PlayerResource setBMSFile
警告: 楽曲が存在しないか、解析時にエラーが発生しました:C:\non-existing-file
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.play.BMSPlayer.<init>(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.MainController.create(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

Environment
- Windows 10 64bit
- JRE 1.8.0_131
- Apache Ant 1.10.1

**Comment by yuinore** [comment]
もとのリポジトリの方にissueを立てました。

**Comment by yuinore** [comment]
https://github.com/exch-bms2/beatoraja/issues/42

**Comment by onk** [comment]
ふりかえりました！
issue お疲れさまでしたー
