### ISSUE TITLE
    OSS Gate Workshop: Tokyo:  2017-05-27: peterchinzhen: summernote: Work log

### ISSUE THREAD

**Issue by peterchinzhen** [oss-gate/workshop#420]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by peterchinzhen** [comment]
# summernote editor 調査
### 調査手順
- Googleで「summernote」を検索し、公式サイトを見つかりました。
- 公式サイト内でGithubリポージトリのリンクからGithubページを開きます。
    - ライセンス：MIT License 
    - インストール手順などreadmeに記載されます。


### まとめ
- Official website: http://summernote.org/ 
- Github repository: https://github.com/summernote/summernote

**Comment by peterchinzhen** [comment]
Githubのリポージトリをローカルにクローンします。
`git clone https://github.com/summernote/summernote.git`


インストール手順

```
npm install

# build full version of summernote: dist/summernote.js
npm run build

# generate minified copy: dist/summernote.min.js, dist/summernote.css
npm run dist
```

**Comment by peterchinzhen** [comment]
ビルドしたソースコードをdistフォルダに入れます。

![image](https://cloud.githubusercontent.com/assets/18191219/26518159/52da2a88-42e5-11e7-8597-e63d0ec30ef6.png)

**Comment by peterchinzhen** [comment]
オフィシャルサイト提供のデモとローカルビルドしたソースのバーションをチェックし、同じバーションとわかります。

**Comment by peterchinzhen** [comment]
利用の際に、発見した不具合

**再現手順**
1. 任意の文字をエィターに入力する。
![image](https://cloud.githubusercontent.com/assets/18191219/26518300/c66d62a0-42e8-11e7-9ec6-51ca07443a86.png)

2. Ctrl(Command) + Aで入力した内容全選択し、delete/backspaceキーを押すと、全文字を削除される。
![image](https://cloud.githubusercontent.com/assets/18191219/26518307/e2f26ccc-42e8-11e7-9442-8e5534b3deba.png)

3. ただし、htmlコードを見ると、brまたpタグを残される。
![image](https://cloud.githubusercontent.com/assets/18191219/26518314/17d466c0-42e9-11e7-829f-9e2744e71f70.png)

**Comment by peterchinzhen** [comment]
そういうイシューを既に報告されるがどうかをGithub上で確認します。

**Comment by peterchinzhen** [comment]
select all, clear all, delete allなどキーワードで検索すると、この問題報告のイシューが存在しないです。

**Comment by peterchinzhen** [comment]
![image](https://cloud.githubusercontent.com/assets/18191219/26518408/0ba19132-42eb-11e7-920f-8d351c0be580.png)

**Comment by peterchinzhen** [comment]
![summernote](https://cloud.githubusercontent.com/assets/18191219/26518426/36ccbea4-42eb-11e7-8226-6cb5106c3a63.gif)

**Comment by peterchinzhen** [comment]
#### 確認環境

tag: v.0.8.3
       v.0.7.0


バージョン Chrome 58.0.3029.110 (64-bit)
OSバージョン macOS 10.12.6 Beta（16G8c）

**Comment by peterchinzhen** [comment]
整理します。

**Comment by peterchinzhen** [comment]
# 内容を全選択、削除すると、htmlタグを残すことがある。

#### 動作環境
- code tag: v.0.8.3
                 v.0.7.0

- バージョン Chrome 58.0.3029.110 (64-bit)
- OSバージョン macOS 10.12.6 Beta（16G8c）

#### 再現手順
1. 任意の文字をエィターに入力する。
![image](https://cloud.githubusercontent.com/assets/18191219/26518300/c66d62a0-42e8-11e7-9ec6-51ca07443a86.png)

2. Ctrl(Command) + Aで入力した内容全選択し、delete/backspaceキーを押すと、全文字を削除される。
![image](https://cloud.githubusercontent.com/assets/18191219/26518307/e2f26ccc-42e8-11e7-9442-8e5534b3deba.png)

3. ただし、htmlコードを見ると、brまたpタグを残される。
![image](https://cloud.githubusercontent.com/assets/18191219/26518314/17d466c0-42e9-11e7-829f-9e2744e71f70.png)

* Gif:
![summernote](https://cloud.githubusercontent.com/assets/18191219/26518719/f46e7fd8-42f0-11e7-94bb-4eb29554f16d.gif)

従来の問題点と思いますが、ご確認ください。

**Comment by peterchinzhen** [comment]
# Html tags will be left when deleting all content

#### Environment
- code tag: v.0.8.3
                 v.0.7.0

- Browser: Chrome 58.0.3029.110 (64-bit)
- OS: macOS 10.12.6 Beta（16G8c）

#### Operation Procedure
1. Input few words
![image](https://cloud.githubusercontent.com/assets/18191219/26518300/c66d62a0-42e8-11e7-9ec6-51ca07443a86.png)

2. Use Ctrl(Command) + A or mouse to select all contents, and press delete/backspace key to delete
![image](https://cloud.githubusercontent.com/assets/18191219/26518307/e2f26ccc-42e8-11e7-9442-8e5534b3deba.png)

3. When we switch to html code view mode, you can see those tags still exist.
![image](https://cloud.githubusercontent.com/assets/18191219/26518314/17d466c0-42e9-11e7-829f-9e2744e71f70.png)

4. However we you press delete key again, any tags do not exist any more.

* Gif:
![summernote](https://cloud.githubusercontent.com/assets/18191219/26518719/f46e7fd8-42f0-11e7-94bb-4eb29554f16d.gif)

**Comment by peterchinzhen** [comment]
#### steps to reproduce
1. Input few words
![image](https://cloud.githubusercontent.com/assets/18191219/26518300/c66d62a0-42e8-11e7-9ec6-51ca07443a86.png)

2. Use Ctrl(Command) + A or mouse to select all contents, and press delete/backspace key to delete
![image](https://cloud.githubusercontent.com/assets/18191219/26518307/e2f26ccc-42e8-11e7-9442-8e5534b3deba.png)

3. When we switch to html code view mode, you can see those tags still exist.
![image](https://cloud.githubusercontent.com/assets/18191219/26518314/17d466c0-42e9-11e7-829f-9e2744e71f70.png)

4. However we you press delete key again, any tags do not exist any more.

#### browser version and os version
- code tag: v.0.8.3
                 v.0.7.0

- Browser: Chrome 58.0.3029.110 (64-bit)
- OS: macOS 10.12.6 Beta（16G8c）

#### screenshot of issue
![summernote](https://cloud.githubusercontent.com/assets/18191219/26518719/f46e7fd8-42f0-11e7-94bb-4eb29554f16d.gif)

**Comment by knokmki612** [comment]
ふりかえりました！
プルリクエストおめでとうございます :tada: https://github.com/summernote/summernote/issues/2340
