### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-05-27: marztest: postgresql: Work log

### ISSUE THREAD

**Issue by marztest** [oss-gate/workshop#422]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by genya0407** [comment]
こんにちわ！サポーターです！

**Comment by topporo** [comment]
こんにちわ!ビギナーです!

**Comment by daddygongon** [comment]
西谷＠関学・理工・情報科学です．よろしく．

**Comment by kou** [comment]
創始者です！

**Comment by daddygongon** [comment]
元祖，創設者，始祖，

**Comment by masayuki14** [comment]
こんにちわ。森崎です。主夫代表のサポーターです。よろしくお願いします。

**Comment by marztest** [comment]
グーグルでpostgresqlの公式サイトを検索して見る

**Comment by marztest** [comment]
公式サイトを発見
https://www.postgresql.jp/

**Comment by marztest** [comment]
公式サイトを開いてダウンロードのリンクを開く
https://www.postgresql.jp/download

**Comment by marztest** [comment]
インストールガイドがあるのでリンクを開く
http://lets.postgresql.jp/map/install

**Comment by marztest** [comment]
公式サイトではなくユーザ会を見ていました :cry:

**Comment by marztest** [comment]
検索結果の下の方に公式サイトがあった。
公式サイトを開く
https://www.postgresql.org/

**Comment by marztest** [comment]
インストールするためにdownloadのリンクを開く
https://www.postgresql.org/download/

**Comment by marztest** [comment]
osがubuntuなのでubuntuのパッケージをダウンロードする
https://www.postgresql.org/download/linux/ubuntu/

**Comment by marztest** [comment]
ダウンロードするためにubuntuのバージョンを選択しなければならない
バージョンを調べるために端末でコマンドを実行しなければならない
コマンドをグーグルで検索する

**Comment by marztest** [comment]
ubuntu バージョン　コマンド
でグーグル検索を行う

**Comment by marztest** [comment]
検索結果の一番上のページを開く
ウェブエンジニアのメモ帳
http://mawatari.jp/archives/check-ubuntu-version

**Comment by marztest** [comment]
以下のコマンドを実行することで調べることができる模様
cat /etc/lsb-release

**Comment by marztest** [comment]
実行結果
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```
実行結果からバージョンは16.04であると思われる

**Comment by marztest** [comment]
ダウンロードページに戻りダウンロードを行う

**Comment by marztest** [comment]
端末上でコマンドを実行することでダウンロードを行うことができる
コマンド
```
deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
```

**Comment by marztest** [comment]
コマンドをじっこうした結果debのコマンドが有効ではないというエラーが出ました
```
コマンド 'deb' は見つかりませんでした。もしかして:
 コマンド 'dex' - パッケージ 'dex' (universe)
 コマンド 'dab' - パッケージ 'bsdgames' (universe)
 コマンド 'debc' - パッケージ 'devscripts' (main)
 コマンド 'xdeb' - パッケージ 'xdeb' (universe)
 コマンド 'deb3' - パッケージ 'quilt' (main)
 コマンド 'dub' - パッケージ 'dub' (universe)
 コマンド 'dwb' - パッケージ 'dwb' (universe)
 コマンド 'debi' - パッケージ 'devscripts' (main)
 コマンド 'derb' - パッケージ 'icu-devtools' (main)
deb: コマンドが見つかりません
```

**Comment by marztest** [comment]
Create the file /etc/apt/sources.list.d/pgdg.list, and add a line for the repository 
ダウンロードを行う前にダウンロード先のディレクトリを作らなければならないのか？

**Comment by marztest** [comment]
Create the file /etc/apt/sources.list.d/pgdg.list, and add a line for the repository
以下のディレクトリを作成しなければならない
/etc/apt/sources.list.d/

**Comment by marztest** [comment]
ディレクトリを作成するためにコマンドを実行したが
mkdir /etc/apt/sources.list.d/
すでにディレクトリは存在していた。
 /etc/apt/sources.list.d/
にcdコマンドで移動する

**Comment by marztest** [comment]
cd /etc/apt/sources.list.d/
コマンドを実行して移動した

**Comment by marztest** [comment]
移動したディレクトリ内でpgdg.listを作成する

**Comment by marztest** [comment]
作成するためのコマンドを調べる
ubuntu テキスト　コマンド　で調べる

**Comment by marztest** [comment]
検索結果の一番上のページを開く
Ubuntu 10.04 LTS デスクトップ版のススメ
http://www.ubuntu-d.com/_operation/command_reference.html

**Comment by marztest** [comment]
gedit [開きたいテキストファイル] Enter
を実行することで編集することができる

**Comment by marztest** [comment]
`gedit pgdg.list `を実行する
エディタを開くことができた
deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
を記入し保存する

**Comment by marztest** [comment]
以下のエラーが発生し保存を行うことができない
そのファイルを保存するために必要な権限がありません。入力した場所が正しいか確認して、もう一度実行してみてください。

**Comment by marztest** [comment]
以下のコマンドを実行することで保存することができた
sudo gedit pgdg.list

**Comment by marztest** [comment]
保存することができたのでダウンロードを行うコマンドを実行する
` wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
  sudo apt-key add -
sudo apt-get update`

**Comment by marztest** [comment]
** (appstreamcli:5835): CRITICAL **: Error while moving old database out of the way.
↑のようなメッセージが出たが
パッケージリストを読み込んでいます... 完了
インストールが完了したかのようなメッセージが出ている

**Comment by marztest** [comment]
ダウンロードページの次のコマンドを実行してみる
apt-get install postgresql-9.4

**Comment by marztest** [comment]
apt-get install postgresql-9.4
権限がないためsudoで行う
sudo apt-get install postgresql-9.4

**Comment by marztest** [comment]
容量の問題を聞かれたが多分問題ない
この操作後に追加で 27.4 MB のディスク容量が消費されます。
続行しますか? [Y/n]

**Comment by marztest** [comment]
yで実行

**Comment by marztest** [comment]
以下のメッセージが出たのでおそらくインストールはできた。
成功しました。以下を使用してデータベースサーバを起動することができます。

**Comment by marztest** [comment]
インストールできているか怪しいので動作確認をしたい

**Comment by marztest** [comment]
端末に以下のコマンドを実行することで起動することができると書いてある？
/usr/lib/postgresql/9.4/bin/postmaster -D /var/lib/postgresql/9.4/main
ダウンロードページには起動コマンドはない

**Comment by marztest** [comment]
sudoでコマンドをじっこうした結果以下のエラーが発生
システムセキュリティの危険防止のため非特権ユーザIDでサーバを起動しな
ければなりません。適切なサーバの起動方法に関する詳細はドキュメントを
参照してください

**Comment by marztest** [comment]
/usr/lib/postgresql/9.4/bin/postmaster -D /var/lib/postgresql/9.4/main
または
    /usr/lib/postgresql/9.4/bin/pg_ctl -D /var/lib/postgresql/9.4/main -l logfile start

Ver Cluster Port Status Owner    Data directory               Log file
9.4 main    5432 down   postgres /var/lib/postgresql/9.4/main /var/log/postgresql/postgresql-9.4-main.log
update-alternatives: /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) を提供するために自動モードで /usr/share/postgresql/9.4/man/man1/postmaster.1.gz を使います
postgresql-contrib-9.4 (9.4.12-1.pgdg16.04+1) を設定しています ...
sysstat (11.2.0-1ubuntu0.1) を設定しています ...

Creating config file /etc/default/sysstat with new version
update-alternatives: /usr/bin/sar (sar) を提供するために自動モードで /usr/bin/sar.sysstat を使います
libc-bin (2.23-0ubuntu3) のトリガを処理しています ...
ureadahead (0.100.0-19) のトリガを処理しています ...
systemd (229-4ubuntu4) のトリガを処理しています ...

**Comment by marztest** [comment]
ダウンロードを行う前にバージョンを調べる必要があるが
調べ方は書いていない

**Comment by marztest** [comment]
作成したファイルに以下の行を追加して保存する作業をコマンドを実行すると勘違いしてしまう
deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main

**Comment by marztest** [comment]
ファイルに行を追加する方法が公式サイトにない

**Comment by marztest** [comment]
apt-get install postgresql-9.4
sudoをコマンドの前につけなければ実行できない

**Comment by marztest** [comment]
postgresのバージョンが古い

**Comment by marztest** [comment]
postgresの最新バージョンを調べる
http://openstandia.jp/oss_info/postgresql/
最新バージョンは9.6.2

**Comment by marztest** [comment]
Included in distribution
postgresのインストールを行うコマンドが記載されているが、インストールするバージョンが最新の9.6.2ではなく9.4になっている。
更新したほうがいいのではないか？

Ubuntu includes PostgreSQL by default. To install PostgreSQL on Ubuntu, use the apt-get (or other apt-driving) command:
`apt-get install postgresql-9.4`

**Comment by marztest** [comment]
apt-get install postgresql-9.4
↓
apt-get install postgresql-9.6.2

**Comment by marztest** [comment]
インストールする際のコマンドにsudoを追加しなければエラーが発生するので追加したほうがいいのではないか？
sudo apt-get install postgresql-9.6.2

**Comment by marztest** [comment]
apt-get install postgresql-9.6.2
↓
sudo apt-get install postgresql-9.6.2

**Comment by marztest** [comment]
postgresqlの9.6.2がない
postgresqlの9.6はある

**Comment by marztest** [comment]
apt-get install postgresql-9.4
↓
sudo apt-get install postgresql-9.6

**Comment by marztest** [comment]
公式サイトのダウンロードページにpostgresqlのインストールを行うコマンドがありますが、sudoをつけたほうがいいのではないでしょうか。
sudoをつけなければエラーが発生します。
apt-get install postgresql-9.4
↓
sudo apt-get install postgresql-9.4
ダウンロードページ
https://www.postgresql.org/download/linux/ubuntu/

**Comment by marztest** [comment]
ダウンロードページではバージョン9.4のインストール方法が記載されていますが、
最新バージョンの9.6に変更したほうがいいのではないでしょうか。

**Comment by marztest** [comment]
There is a command to install postgresql on the download page of the official site,
If I do not add sudo, an error will occur.
It may be better to add sudo before the command

**Comment by marztest** [comment]
There is a command to install postgresql on the download page of the official site,
If I do not add sudo, an error will occur.
It may be better to add sudo before the command.

download page
https://www.postgresql.org/download/linux/ubuntu/

command
apt-get install postgresql-9.4
↓
sudo apt-get install postgresql-9.4

**Comment by marztest** [comment]
There is a command to install postgresql on the download page of the official site,
If I do not add sudo, an error will occur.
It may be better to add sudo before the command.

download page
https://www.postgresql.org/download/linux/ubuntu/

command
before:  `apt-get install postgresql-9.4`
↓
after:  `sudo apt-get install postgresql-9.4`

**Comment by marztest** [comment]
メーリングリスト
https://www.postgresql.org/message-id/CAJuFng0RAj0rp2AeTP3e3ALx-v%2B%2Bznbd5AywSbQv-LsUgaRoAA%40mail.gmail.com

**Comment by masayuki14** [comment]
おめでとうございます！

**Comment by genya0407** [comment]
メーリングリストに返信ついてるですよ！
