### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-05-27: topporo: sinatra: Work log

### ISSUE THREAD

**Issue by topporo** [oss-gate/workshop#423]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
西谷＠関学・理工・情報科学です．よろしく．

**Comment by genya0407** [comment]
こんにちわ！サポーターです！

**Comment by marztest** [comment]
アイクラフト株式会社の松田です。よろしおねがいします。

**Comment by kou** [comment]
創始者です！

**Comment by masayuki14** [comment]
こんにちわ。森崎です。主夫代表のサポーターです。よろしくお願いします。

**Comment by topporo** [comment]
sinatraでググる

**Comment by topporo** [comment]
sinatraの公式サイトに行った

**Comment by topporo** [comment]
公式サイトにgemをインストールしろとあった。
Install the gem:
gem install sinatra

**Comment by topporo** [comment]
5% gem install sinatra
Fetching: rack-protection-2.0.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/lib/ruby/gems/2.3.0 directory.

↑のようなエラーがでたのでsudoをつけて実行するとうまく行った。
% sudo gem install sinatra

**Comment by topporo** [comment]
gem のインストール終了した

MacBook-Air-5% sudo gem install sinatra
Password:
Fetching: rack-protection-2.0.0.gem (100%)
Successfully installed rack-protection-2.0.0
Fetching: mustermann-1.0.0.gem (100%)
Successfully installed mustermann-1.0.0
Fetching: sinatra-2.0.0.gem (100%)
Successfully installed sinatra-2.0.0
Parsing documentation for rack-protection-2.0.0
Installing ri documentation for rack-protection-2.0.0
Parsing documentation for mustermann-1.0.0
Installing ri documentation for mustermann-1.0.0
Parsing documentation for sinatra-2.0.0
Installing ri documentation for sinatra-2.0.0
Done installing documentation for rack-protection, mustermann, sinatra after 323 seconds
3 gems installed

**Comment by topporo** [comment]
~/sinatra用のディレクトリを作成

**Comment by topporo** [comment]
公式サイトの通り、maapp.rbtというファイルを~/sinatraに作った。

**Comment by genya0407** [comment]
「なんだこれは！？」はどこで出たんですかね...?

**Comment by topporo** [comment]
単純に最初の項目を飛ばしていました...

**Comment by topporo** [comment]
ruby myapp.rbを実行し、localhost:4567にアクセスして、"Hello World"を見ることに成功した。

**Comment by topporo** [comment]
新しいパスを作成し、

get '/foo' do
  # Does not match "GET /foo/"
  "fooが表示される"
end

閲覧に成功した。

**Comment by genya0407** [comment]
公式サイトのリンクがあるとbetterです 👍

**Comment by topporo** [comment]
>単純に最初の項目を飛ばしていました...
# myapp.rb
require 'sinatra'

get '/' do
  'Hello world!'
end

↑のように最初の項目にファイル作成の指示が出ていたけど、わかりにくくて飛ばしてしまった。

**Comment by topporo** [comment]
日本語のページを見つけたのでそちらで作業を進めることにする。

**Comment by topporo** [comment]
sinatraでViewを作ることにする。
項目"ビュー / テンプレート(Views / Templates)"

**Comment by topporo** [comment]
```
get '/' do
  erb :index
end
```

↑のようにファイルに書き込むよう指示されているされており、これは/view/index/erbを配置しないと行けないのだけど、erbの書き方乗っていないので作成できないし、もし実行してもエラーになる。

**Comment by daddygongon** [comment]
myapp.rbとかindex.erbとかの具体例の時に，順番とか，

**Comment by daddygongon** [comment]
japanese小さいよね．

**Comment by topporo** [comment]
公式サイトのREADMEの一番最初にファイルを作るというプロセスがあるけど、もっと明示的に書いてあると嬉しいなぁ

**Comment by topporo** [comment]
Sinatraは最小の労力でRubyによるWebアプリケーションを手早く作るためのDSLです。
```
# myapp.rb
require 'sinatra'

get '/' do
  'Hello world!'
end
```
↑を
↓のように

Sinatraは最小の労力でRubyによるWebアプリケーションを手早く作るためのDSLです。
好きなディレクトリにmyapp.rbというファイルを作成し、下記の通り書き込む。
```
# myapp.rb
require 'sinatra'

get '/' do
  'Hello world!'
end
```

**Comment by daddygongon** [comment]
記述が作業を順番に書いているのではないのは，スタイルかもしれないんで，言い方は，受け入れらるように考えたほうがいいかも．．．

**Comment by daddygongon** [comment]
受け入れられる

**Comment by topporo** [comment]
このままだと公式のREADMEのコンセプト？に反する可能性が高いので少し方向転換したい

**Comment by topporo** [comment]
別ページでRailsチュートリアルみたいにサクッと動くもの作るようなチュートリアルが欲しい

**Comment by topporo** [comment]
初めてsinatraを触るに際して公式のREADMEに沿って行おうとしたところ、最初の"始めよう"という項目でつまづきました。最初にmyappというファイルを作成する手順だったのですが、割と唐突に始まっていて何をしているのかわかりずらかったです。

**Comment by topporo** [comment]
初めてsinatraに触っています。
公式のREADMEに沿って行いました。
最初の"始めよう"という項目でつまづきました。
READMEは最初にmyappというファイルを作成せよと指示しているようです。
しかし、唐突に始まっていて何をしているかわかりづらいです。

**Comment by daddygongon** [comment]
I've tried running 'sinatra' for the first time.
Try to follow 'README' at the public site, but stopped at 'Getting started'
The instruction of getting started uses the first example, 'myapp.rb'.
But I did not notice it.
Thus I suggest to revise the instruction,
Using the myapp.rb as shown above,

**Comment by daddygongon** [comment]
Thus I suggest to revise the instruction,
Not only
> And run with:
but 
> And run using the myapp.rb as shown above,

**Comment by topporo** [comment]
I've tried running 'sinatra' for the first time.
Try to follow 'README' at the public site, but stopped at 'Getting started'
The instruction of getting started uses the first example, 'myapp.rb'.
But I did not notice it.
Thus I suggest to revise the instruction,
Using the myapp.rb as shown above,

Thus I suggest to revise the instruction,
Not only

>And run with:
```
ruby myapp.rb
```
but
>Make myapp.rb as shown above with:
>And run with:
```
ruby myapp.rb
```

**Comment by daddygongon** [comment]
おめでとう．はえある，OSSerや．

**Comment by topporo** [comment]
https://github.com/sinatra/sinatra/issues/1299

**Comment by daddygongon** [comment]
お疲れ様でした。wen appliの開発を理解するのにはperfect ruby という書籍が最適です。これの最後の二章を写経するだけで理解できます。おためしあれ.西谷@関西学院大・理工

iPhoneから送信

2017/05/27 16:34、topporo <notifications@github.com> のメッセージ:

**Comment by topporo** [comment]
お疲れ様でした。
OSSにどうやったら採用されやすいかという話(READMEのスタイルの話とか)とても面白かったです。
「perfect ruby」これ読んでみます！
