### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-05-27: tshkh8: *****: Work log

### ISSUE THREAD

**Issue by tshkh8** [oss-gate/workshop#424]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tshkh8** [comment]
公式サイトをみにいく

**Comment by tshkh8** [comment]
cli-kintoneでぐぐる

**Comment by tshkh8** [comment]
githubのページが見つかった。
https://github.com/kintone/cli-kintone

**Comment by tshkh8** [comment]
https://github.com/kintone/cli-kintone

にHow to buildの項目があった。
この手順に従ってビルドしてみる

**Comment by tshkh8** [comment]
RequirementにGo 1.2以上とある。
自分のPCにはgo 1.7が入っているのでこれはスキップ

go version go1.7.5 darwin/amd64

**Comment by tshkh8** [comment]
各コマンドの後に、実行例があればいいのになぁ

**Comment by tshkh8** [comment]
コマンド
実行例

コマンド
実行例

のような形になっていれば、すぐじっこうできるのに…

**Comment by topporo** [comment]
このままだと公式のREADMEのコンセプト？に反する可能性が高いので少し方向転換したい

**Comment by topporo** [comment]
別ページでRailsチュートリアルみたいにサクッと動くもの作るようなチュートリアルが欲しい

**Comment by topporo** [comment]
ごめん！
