### ISSUE TITLE
OSS Gate Workshop: Sapporo: 2017-06-17: iakio: terraform: Work log

### ISSUE THREAD

**Issue by iakio** [oss-gate/workshop#440]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by iakio** [comment]
最近terraform使っているのでこれをやるぞー
https://www.terraform.io/

**Comment by iakio** [comment]
https://www.terraform.io/intro/index.html
から読み始める

**Comment by iakio** [comment]
インストールしたいんだけどどこを読めばいいだろう

**Comment by iakio** [comment]
https://www.terraform.io/intro/getting-started/install.html
ここっぽい

**Comment by tricknotes** [comment]
今日はおつかれさまでした！
