### ISSUE TITLE
OSS Gate Workshop: Sapporo: 2017-06-17: gfd3e34s: jenkins: Work log

### ISSUE THREAD

**Issue by gfd3e34s** [oss-gate/workshop#442]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tricknotes** [comment]
こんにちは！どうぞよろしくお願いします！

**Comment by gfd3e34s** [comment]
公式サイトからインストーラをDLしてインストールした
https://jenkins.io/download/

**Comment by gfd3e34s** [comment]
localhost:8080 でjenkinsが自動で立ち上がった
すでに8080が使われてたらエラーが起きてしまうのでは？と思った

**Comment by gfd3e34s** [comment]
画面の指示でプラグインをインストール

**Comment by gfd3e34s** [comment]
ユーザを作成

<img width="1059" alt="2017-06-17 14 10 30" src="https://user-images.githubusercontent.com/20813980/27250313-e8ee2d08-5366-11e7-83bb-77c8323bb22b.png">

**Comment by gfd3e34s** [comment]
アカウント登録完了

<img width="1256" alt="2017-06-17 14 25 59" src="https://user-images.githubusercontent.com/20813980/27250383-ee336ab0-5368-11e7-84ce-38fc3a4375a6.png">

**Comment by gfd3e34s** [comment]
get started を見つけたので、ここを参考に進めていくことにする
https://jenkins.io/doc/book/getting-started/

**Comment by gfd3e34s** [comment]
[疑問]

インストール方法
https://jenkins.io/doc/book/getting-started
↓　jenkinsを使う
https://jenkins.io/doc/book/using/
↓　入門者向けのリンク
https://jenkins.io/doc/book/getting-started

無限ループになってる？？

**Comment by gfd3e34s** [comment]
パイプライン入門のドキュメントを見つけたので試してみる
https://jenkins.io/doc/book/pipeline/getting-started/

**Comment by gfd3e34s** [comment]
hello worldをechoするタスクを実行できた

<img width="1168" alt="2017-06-17 15 16 38" src="https://user-images.githubusercontent.com/20813980/27250670-fd94137c-536f-11e7-8d29-c2282154df36.png">

**Comment by gfd3e34s** [comment]
Hello worldのジョブ実行までは問題なくできていたので、
ドキュメントの不親切をしてすることに

<img width="1168" alt="2017-06-17 15 16 38" src="https://user-images.githubusercontent.com/20813980/27251103-9191022e-537a-11e7-80b0-10fa743cb5d2.png">

**Comment by tricknotes** [comment]
本日はおつかれさまでした！
今日取り組んでいた Pull Request で、もし困ったことや悩んだことがあったら気軽に相談してみてくださいね！
