### ISSUE TITLE
    OSS Gate Workshop: sapporo: 2017-06-17:emitsuco3:bxSlider: Work log

### ISSUE THREAD

**Issue by emitsuco3** [oss-gate/workshop#443]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tricknotes** [comment]
こんにちは！どうぞよろしくお願いします！

**Comment by emitsuco3** [comment]
https://github.com/oss-gate/workshop/issues/171
これにお返事が来てしまったのを半年スルーし続けているのでそろそろ良心が痛むのでお返事ありがとうといいたい。

**Comment by emitsuco3** [comment]
http://bxslider.com/
ここです

**Comment by emitsuco3** [comment]
https://github.com/stevenwanderski/bxslider-4/issues/1068
これなんですが

**Comment by emitsuco3** [comment]
http://placehold.it/350x150
なんとこんなありがたいものを教えていただいていた
かたじけない

**Comment by emitsuco3** [comment]
こんな素敵なものを教えていただいてありがとうございます。
ご親切感謝します。

をグーグル先生に翻訳してもらいます

**Comment by emitsuco3** [comment]
Thank you for telling me such a wonderful thing.
I appreciate your kindness.

**Comment by emitsuco3** [comment]
おわりました。
ありがとうございました。

**Comment by tricknotes** [comment]
ミッションコンプリートですね！おつかれさまでした！

**Comment by emitsuco3** [comment]
wordpress触ってるのでそっち見てみます

https://ja.wordpress.com/
と
https://wordpress.org/
の違いがそもそもわかってませんでした

**Comment by emitsuco3** [comment]
https://github.com/WordPress/WordPress/blob/master/license.txt
ここをみたら
https://ja.wikipedia.org/wiki/GNU_General_Public_License
GNU Licenseというのでした

**Comment by tricknotes** [comment]
さんこう https://opensource.org/licenses/GPL-2.0

**Comment by emitsuco3** [comment]
GNU GENERAL PUBLIC LICENSE Version 2
が正式名称らしいです
いろいろあるようです

**Comment by emitsuco3** [comment]
勉強になりました

**Comment by emitsuco3** [comment]
https://ja.wordpress.org/
日本語インストールしてみます

**Comment by emitsuco3** [comment]
https://ja.wordpress.org/install-ja/
インストール手順です

**Comment by emitsuco3** [comment]
http://www.mousouchiku.net/blog/2009/04/20-170548.php
こっちでよくない

**Comment by emitsuco3** [comment]
https://8bitodyssey.com/archives/1478
winならこっちだろ、と思ってリンクたどり、
Web Platform Installer
をぐぐったところ
http://www.weblio.jp/content/%E3%83%97%E3%83%AD%E3%83%97%E3%83%A9%E3%82%A4%E3%82%A8%E3%82%BF%E3%83%AA
にたどり着きました
ちょう勉強になりました

**Comment by emitsuco3** [comment]
http://stevenwanderski.com/
bxSliderのお父さん

**Comment by tricknotes** [comment]
> ご使用のコンピューターに api-ms-win-crt-runtime-l1-1-0.dll がないため、プログラムは起動できません

おやおや

**Comment by tricknotes** [comment]
:eyes: https://answers.microsoft.com/ja-jp/windows/forum/windows_7-update/api-ms-win-crt-runtime-l1-1-0dll/ea23163c-85c4-4757-85b2-523140308657

**Comment by emitsuco3** [comment]
インストールがおわりませんでしたー
ざんねん！

**Comment by tricknotes** [comment]
本日はおつかれさまでした！
よかったらまた参加してみてくださいね！
