### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-6-29: bash0C7: Mastodon: Work log

### ISSUE THREAD

**Issue by bash0C7** [oss-gate/workshop#450]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by bash0C7** [comment]
「github mastodon」で検索した

**Comment by bash0C7** [comment]
それっぽいリポジトリがでてきたので、ひらいた
https://github.com/tootsuite/mastodon

**Comment by bash0C7** [comment]
macのdeveopmentのドキュメントがあった
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md#mac

**Comment by bash0C7** [comment]
> xcode-select install

入らない....

>$ xcode-select install
```
xcode-select: error: invalid argument 'install'
Usage: xcode-select [options]

Print or change the path to the active developer directory. This directory
controls which tools are used for the Xcode command line tools (for example,
xcodebuild) as well as the BSD development commands (such as cc and make).

Options:
  -h, --help                  print this help message and exit
  -p, --print-path            print the path of the active developer directory
  -s <path>, --switch <path>  set the path for the active developer directory
  --install                   open a dialog for installation of the command line developer tools
  -v, --version               print the xcode-select version
  -r, --reset                 reset to the default command line tools path
```

**Comment by bash0C7** [comment]
とりあえず続行。 `Prerequisites` を進める

**Comment by bash0C7** [comment]
```
initdb /usr/local/var/postgres -E utf8                                                                              master
The files belonging to this database system will be owned by user "bash".
This user must also own the server process.

The database cluster will be initialized with locale "ja_JP.UTF-8".
initdb: could not find suitable text search configuration for locale "ja_JP.UTF-8"
The default text search configuration will be set to "simple".

Data page checksums are disabled.

initdb: directory "/usr/local/var/postgres" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/usr/local/var/postgres" or run initdb
with an argument other than "/usr/local/var/postgres".
/mastodon ❯❯❯ echo $?                                                                                                           ⏎ master
1
```
通らない

**Comment by kou** [comment]
お疲れ様でした！
