### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-6-29: smaruy30: Mastodon: Work log

### ISSUE THREAD

**Issue by smaruy30** [oss-gate/workshop#451]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by smaruy30** [comment]
公式サイトをみつける

**Comment by smaruy30** [comment]
mastodonで検索しよう　公式サイトを探す
https://www.google.co.jp/search?q=mastodon&oq=mastodon&aqs=chrome..69i57j69i61l2j69i59j69i60j69i59.3364j0j7&sourceid=chrome&ie=UTF-8#safe=off&q=%E3%83%9E%E3%82%B9%E3%83%88%E3%83%89%E3%83%B3+%E5%85%AC%E5%BC%8F%E3%82%B5%E3%82%A4%E3%83%88

**Comment by smaruy30** [comment]
公式っぽい
https://mstdn.jp/about

**Comment by smaruy30** [comment]
OSSの公式サイトは
https://github.com/mstdn-jp/mastodon/
ここ

**Comment by smaruy30** [comment]
インストールしようとしてどうやればいいのかなぁ
https://github.com/mstdn-jp/mastodon/

**Comment by smaruy30** [comment]
インスタンスの立ち上げ方ががわからない
どこにかいてあるのかな

git かどこか

**Comment by smaruy30** [comment]
https://github.com/mstdn-jp/mastodon/
インストールで検索

**Comment by smaruy30** [comment]
Readmeに"install"でてこない

なぜ。。。

**Comment by smaruy30** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md
development guide に書いてあるかも
開発者向けドキュメントだから

**Comment by smaruy30** [comment]
development guideにインストール手順のってると思ったが
production guideみろってかいてある

**Comment by smaruy30** [comment]
インストール環境は？Linux Mac?

**Comment by smaruy30** [comment]
イベントの案内ページにはvagrantって書いてあったから、
Linuxにするか
https://oss-gate.doorkeeper.jp/events/61807?utm_campaign=20170619&utm_medium=email&utm_source=recommend_events

**Comment by smaruy30** [comment]
Linux版でインストール失敗
[root@localhost ~]# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root
users on this machine.
Could not locate Gemfile

**Comment by smaruy30** [comment]
時間ないからmacインストール手順でためす

**Comment by smaruy30** [comment]
やっぱりLinuxでインストール
GemFileがないだけっぽい
git cloneする

**Comment by smaruy30** [comment]
つまったのはgit cloneの手順がなかったから
改善点かもしれない

**Comment by smaruy30** [comment]
Linuxのインストールコマンドは
bundle install
であってる？？
macのほうは
bundle install --with development
ってなってる

けど一旦いいや

**Comment by smaruy30** [comment]
bundleコマンドがない。。
[vagrant@localhost mastodon]$ bundle install
-bash: bundle: コマンドが見つかりません

**Comment by smaruy30** [comment]
インストールする方法は？

**Comment by smaruy30** [comment]
bundle rails rubyのインストール手順をもう一度やりなおさないといけないかも
理由：rootで実行すると怒られる

**Comment by smaruy30** [comment]
./.bash_historyの手順は正しいのか？

**Comment by smaruy30** [comment]
bundle rails rubyがインストールされていることが前提条件に書いてい無いので、
書いてあってもいいかも

**Comment by smaruy30** [comment]
rails rubyは自分でインストールする必要ないから、文章がすくない
からbundlerのインストール手順かいてあってもいいかも

**Comment by smaruy30** [comment]
buildエラー発生
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg-0.20.0/ext
/home/vagrant/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170629-13786-1bryqyl.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.


To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/pg-0.20.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg-0.20.0 for inspection.
Results logged to /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/pg-0.20.0/gem_make.out

An error occurred while installing pg (0.20.0), and Bundler cannot continue.
Make sure that `gem install pg -v '0.20.0'` succeeds before bundling.

In Gemfile:
  pg

**Comment by smaruy30** [comment]
ログをみて原因をさぐる
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/pg-0.20.0/mkmf.log

**Comment by smaruy30** [comment]
conftest.c:3:22: 致命的エラー: libpq-fe.h: そのようなファイルやディレクトリはありません
ヘッダーファイルがないから
ぐぐる インストールしたい

**Comment by smaruy30** [comment]
http://qiita.com/s_osa/items/9b72643c9f7185736395
ここにかいてあった

$ sudo yum install postgresql-devel

インストール手順にも書いておいたほうがいいかも

**Comment by smaruy30** [comment]
さらにコンパイルエラー
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cld3-3.1.2/ext/cld3
/home/vagrant/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170629-27079-10gc7uo.rb extconf.rb
Failed to locate protobuf
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/cld3-3.1.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cld3-3.1.2 for inspection.
Results logged to /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/cld3-3.1.2/gem_make.out

An error occurred while installing cld3 (3.1.2), and Bundler cannot continue.
Make sure that `gem install cld3 -v '3.1.2'` succeeds before bundling.

In Gemfile:
  cld3

**Comment by kou** [comment]
お疲れ様でした！
クローズしますが、この後もここを使い続けても大丈夫です！

**Comment by keisei1092** [comment]
おつかれさまでした！！！！

**Comment by abcang** [comment]
お疲れ様でした！

**Comment by smaruy30** [comment]
ありがとうございました！

**Comment by smaruy30** [comment]
@kou 
先日はありがとうございました。
教えていただきたいことがあるのですが、
ノートPCを中古でもなんでもいいので買って、Ubuntuインストールしたいなって
思ってるんですが、おすすめノートPCありますか？
イベントの時Linux使ってるようでしたので。。

**Comment by kou** [comment]
私はThnkPad X240というのにDebian GNU/Linuxのsidをインストールして使っています！快適です！

**Comment by smaruy30** [comment]
@kou 
ありがとうございます！
