### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-6-29: medi-hikawa: Mastodon: Work log

### ISSUE THREAD

**Issue by medi-hikawa** [oss-gate/workshop#452]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by medi-hikawa** [comment]
まずはソースコードを探して見たい！

**Comment by medi-hikawa** [comment]
まずは、「mastodon github」で検索して見よう

**Comment by medi-hikawa** [comment]
検索で、これが出た！
GitHub - tootsuite/mastodon: A GNU Social-compatible microblogging ...
https://github.com/tootsuite/mastodon

**Comment by medi-hikawa** [comment]
README.mdを見てみる

**Comment by medi-hikawa** [comment]
デプロイのガイドっぽいものがある！

Development
Please follow the development guide from the documentation repository.

**Comment by medi-hikawa** [comment]
リンク開いてみる

https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md

**Comment by medi-hikawa** [comment]
Linuxという単語があり、どうやら動かす場所の話っぽいので、これのようだ

**Comment by medi-hikawa** [comment]
Mac　ガイド発見！！

**Comment by medi-hikawa** [comment]
これはいらなさそう！
xcode-select install

**Comment by medi-hikawa** [comment]
これは必要そう
brew install imagemagick ffmpeg yarn postgresql redis rbenv nodejs protobuf

**Comment by medi-hikawa** [comment]
完了まで遅い

**Comment by medi-hikawa** [comment]
エラーが出た！でも大丈夫そう
Error: yarn 0.23.2 is already installed

**Comment by medi-hikawa** [comment]
問題なく実行できた
rbenv init
 rbenv install 2.4.1

**Comment by medi-hikawa** [comment]
問題なく実行できた
gem update --system
 gem install bundler

**Comment by medi-hikawa** [comment]
怪しさを感じる 
initdb /usr/local/var/postgres -E utf8
```
The files belonging to this database system will be owned by user "yoi".
This user must also own the server process.

The database cluster will be initialized with locale "ja_JP.UTF-8".
initdb: could not find suitable text search configuration for locale "ja_JP.UTF-8"
The default text search configuration will be set to "simple".

Data page checksums are disabled.

initdb: directory "/usr/local/var/postgres" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/usr/local/var/postgres" or run initdb
with an argument other than "/usr/local/var/postgres".
```

**Comment by medi-hikawa** [comment]
ここら辺をググってみる
Data page checksums are disabled.

**Comment by medi-hikawa** [comment]
一旦放置

**Comment by medi-hikawa** [comment]
問題無し
createdb
 export PGDATA=/usr/local/var/postgres

**Comment by medi-hikawa** [comment]
怪しさを感じる
```
/usr/local/bin/postgres
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 406) running in data directory "/usr/local/var/postgres"?
```

**Comment by medi-hikawa** [comment]
問題なさそう
/usr/local/bin/psql
 CREATE USER mastodon CREATEDB;
 \q

**Comment by medi-hikawa** [comment]
ワーキングディレクトリ以外で実行していたが、問題はなさそう

**Comment by medi-hikawa** [comment]
cd mastodon

**Comment by medi-hikawa** [comment]
bundle install --with development

**Comment by medi-hikawa** [comment]
何か出た
```
The name of the Microformats Ruby Parser is changing from
"microformats2" to "microformats". This is a one time change.
(Thanks to @chrisjpowers for transferring the namespace to us.)

Follow these instructions to migrate.

1. Install the new gem. Uninstall the old gem.

    gem install microformats
    gem uninstall microformats2


2. Change any Gemfiles from:

    gem "microformats2"

to

    gem "microformats"
    bundle


3. Change any requires from:

    require "microformats2"

to

    require "microformats"

4. Change any references to the module such as:

    Microformats2.parse(source)

to
    Microformats.parse(source)
```

**Comment by medi-hikawa** [comment]
書き換え

**Comment by medi-hikawa** [comment]
実行
yarn install --pure-lockfile

**Comment by medi-hikawa** [comment]
実行
bundle exec rails db:setup
bin/rails assets:precompile

**Comment by medi-hikawa** [comment]
既に立ち上っている
Start PostgreSQL: /usr/local/bin/postgres
立ち上げok
Start Redis: redis-server
立ち上げok
Start Mastodon (from the Mastodon folder): foreman start

**Comment by medi-hikawa** [comment]
立ち上げok!!!
http://localhost:3000/about

**Comment by medi-hikawa** [comment]
アカウントパス
Admin account is admin@localhost:3000. Password is mastodonadmin.

**Comment by medi-hikawa** [comment]
入れたので、投稿をしてみる

**Comment by medi-hikawa** [comment]
投稿完了！

**Comment by medi-hikawa** [comment]
フィードバックポイントを洗い出す

**Comment by medi-hikawa** [comment]
```xcode-select install``` は間違いのため、 ```xcode-select --install ```に直して貰う？

**Comment by medi-hikawa** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md
公式のデベロッパメントガイドを見て、Macで環境構築をしようとしたところ、エラーが発生した。

```
$ xcode-select install
xcode-select: error: invalid argument 'install'
Usage: xcode-select [options]

Print or change the path to the active developer directory. This directory
controls which tools are used for the Xcode command line tools (for example, 
xcodebuild) as well as the BSD development commands (such as cc and make).

Options:
  -h, --help                  print this help message and exit
  -p, --print-path            print the path of the active developer directory
  -s <path>, --switch <path>  set the path for the active developer directory
  --install                   open a dialog for installation of the command line developer tools
  -v, --version               print the xcode-select version
  -r, --reset                 reset to the default command line tools path
```

引数が可笑しいというエラーが発生した

**Comment by medi-hikawa** [comment]
統一しても良いのかも？
```
bundle exec rails db:setup
bin/rails assets:precompile
```

**Comment by medi-hikawa** [comment]
I read the official Developer Guide. An error occurred when trying to build the environment on Mac.
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md
I hit ```$ xcode-select install```

```
$ xcode-select install
xcode-select: error: invalid argument 'install'
Usage: xcode-select [options]

Print or change the path to the active developer directory. This directory
controls which tools are used for the Xcode command line tools (for example, 
xcodebuild) as well as the BSD development commands (such as cc and make).

Options:
  -h, --help                  print this help message and exit
  -p, --print-path            print the path of the active developer directory
  -s <path>, --switch <path>  set the path for the active developer directory
  --install                   open a dialog for installation of the command line developer tools
  -v, --version               print the xcode-select version
  -r, --reset                 reset to the default command line tools path
```

```error: invalid argument``` has occurred



```$ xcode-select --install``` is correct

**Comment by kou** [comment]
お疲れ様でした！
クローズしますがこの後もここを使い続けても大丈夫です！

**Comment by medi-hikawa** [comment]
ありがとうございました！
今回、このissuesを提出出来ました！
https://github.com/tootsuite/documentation/issues/325

**Comment by saturday06** [comment]
めっちゃ詳しくて背中押すだけだったので楽でした！次回はもっとすごいのができると思います！
