### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-6-29: keisei1092: Mastodon: Work log

### ISSUE THREAD

**Issue by keisei1092** [oss-gate/workshop#454]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by keisei1092** [comment]
インストールしたいので、まず公式サイトを探す

**Comment by keisei1092** [comment]
mastodonでgoogle検索する。

**Comment by keisei1092** [comment]
1番目はMastodonインスタンスのサイトなので公式サイトではなさそう
https://mastodon.social/about

**Comment by keisei1092** [comment]
3番目が公式リポジトリっぽいのでここが公式そう
https://github.com/tootsuite/mastodon

**Comment by keisei1092** [comment]
ここでインストール方法が載っているところを探す

**Comment by keisei1092** [comment]
READMEに`Resources` という項があってそれっぽい

**Comment by keisei1092** [comment]
List of Mastodon instances
Use this tool to find Twitter friends on Mastodon
API overview
Frequently Asked Questions
List of apps
みたいなリンクが並んでいるけれど、どれもインストール方法に関係がなさそう

**Comment by keisei1092** [comment]
見進めていくと `Development` という項があってそれっぽい

**Comment by keisei1092** [comment]
Development Guideというリンクがそれっぽいので辿ってみる

**Comment by keisei1092** [comment]
↑https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md

**Comment by keisei1092** [comment]
いきなり結構むずかしいことがかいてある

**Comment by keisei1092** [comment]
> Don't use Docker to do development. It's a quick way to get Mastodon running in production, it's really really inconvenient for development. Normally in Rails development environment you get hot reloading of backend code and on-the-fly compilation of assets like JS and CSS, but you lose those benefits by compiling a Docker image. If you want to contribute to Mastodon, it is worth it to simply set up a proper development environment.

**Comment by keisei1092** [comment]
しかたがないのでよむ

**Comment by keisei1092** [comment]
`Don't use Docker to do development.` dockerをつかうなということは分かった

**Comment by keisei1092** [comment]
下に読み進めていく

**Comment by keisei1092** [comment]
OSごとのインストール方法が載っているのでMacを見る

**Comment by keisei1092** [comment]
英語がむずかしい・・・・

**Comment by keisei1092** [comment]
とりあえずコマンドっぽいものが羅列されているので打っていく

**Comment by keisei1092** [comment]
xcode-selectは入ってるのでbrewうつ

**Comment by keisei1092** [comment]
` brew install imagemagick ffmpeg yarn postgresql redis rbenv nodejs protobuf`

終わったので先に進む

**Comment by keisei1092** [comment]
```shell
 rbenv init
 rbenv install 2.4.1
```
を打つ

**Comment by keisei1092** [comment]
rbenvはすでに入れているので `already exists continue with installation? (y/N) `って言われた

**Comment by keisei1092** [comment]
コピペで勝手に動くので便利

**Comment by keisei1092** [comment]
```sh
initdb /usr/local/var/postgres -E utf8
 createdb
 export PGDATA=/usr/local/var/postgres
 /usr/local/bin/postgres
 /usr/local/bin/psql
```
PostgreSQL いきなりいけるのかわからないけどとりあえず打ってみる

**Comment by keisei1092** [comment]
```
Keiseis-MacBook:Documents keisei_1092$ initdb /usr/local/var/postgres -E utf8
The files belonging to this database system will be owned by user "keisei_1092".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    UTF-8
  MESSAGES: en_US.UTF-8
  MONETARY: en_US.UTF-8
  NUMERIC:  en_US.UTF-8
  TIME:     en_US.UTF-8
initdb: could not find suitable text search configuration for locale "UTF-8"
The default text search configuration will be set to "simple".

Data page checksums are disabled.

initdb: directory "/usr/local/var/postgres" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/usr/local/var/postgres" or run initdb
with an argument other than "/usr/local/var/postgres".
```

警告っぽいかもなのですすめる

**Comment by keisei1092** [comment]
```
Keiseis-MacBook:Documents keisei_1092$  createdb
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
たぶん動いてない気がする

**Comment by keisei1092** [comment]
```
Keiseis-MacBook:Documents keisei_1092$  export PGDATA=/usr/local/var/postgres
Keiseis-MacBook:Documents keisei_1092$  /usr/local/bin/postgres
LOG:  database system was shut down at 2017-06-29 20:25:19 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
^CLOG:  received fast shutdown request
```
launcher startedの後反応がなくなって C-c で強制終了させた。
動いてるのか動いてないのかわからない。

**Comment by keisei1092** [comment]
createdbがちゃんと動いてない気がするのでPostgreSQLらへんの知見を漁りにいく

**Comment by keisei1092** [comment]
ぽすぐれが動いてるか確認するので `ps aux | grep postgres` してみる

**Comment by keisei1092** [comment]
```
Keiseis-MacBook:Documents keisei_1092$ ps aux | grep postgres
keisei_1092      13723   0.0  0.0  2433828   1652 s008  R+    8:32PM   0:00.00 grep postgres
```

うごいてなさそう

**Comment by keisei1092** [comment]
`brew info postgres`

**Comment by keisei1092** [comment]
```
To have launchd start postgresql now and restart at login:
  brew services start postgresql
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgres start
```
このセッションで動かして大丈夫かなって感じなので最終行の `pg_ctl` を打つ

**Comment by keisei1092** [comment]
今度は `createdb` が通った

**Comment by keisei1092** [comment]
```
Keiseis-MacBook:Documents keisei_1092$ /usr/local/bin/postgres
FATAL:  lock file "postmaster.pid" already exists
HINT:  Is another postmaster (PID 13898) running in data directory "/usr/local/var/postgres"?
```
複数プロセス起動してる？

**Comment by keisei1092** [comment]
とりあえず進めてみようぜな機運を得たのでコマンドを打ってみる

**Comment by keisei1092** [comment]
```
Keiseis-MacBook:Documents keisei_1092$ /usr/local/bin/psql
psql (9.6.3)
Type "help" for help.

keisei_1092=# 
```
きた

**Comment by keisei1092** [comment]
できた

**Comment by keisei1092** [comment]
ここでようやく `Installation` という単語が出てきた

**Comment by keisei1092** [comment]
```
bundle install --with development
yarn install --pure-lockfile
gem install foreman --no-ri --no-rdoc
bundle exec rails db:setup
bin/rails assets:precompile
```

実行していく

**Comment by keisei1092** [comment]
git clone してへんやんけ！

**Comment by keisei1092** [comment]
`git clone` をするステップがなくて謎感が高い。フィードバックチャンスかも

**Comment by keisei1092** [comment]
ということで `git clone` をする・・・・・と思ったらこの記述があるページは https://github.com/tootsuite/documentation とかいう別リポジトリになってる・・・・めんどい

**Comment by keisei1092** [comment]
`git@github.com:tootsuite/mastodon.git`

ランボー怒りの `git clone`

**Comment by keisei1092** [comment]
git clone できたのでコマンドを打っていく

**Comment by keisei1092** [comment]
$ がなくてコピペビリティが高くて便利

**Comment by keisei1092** [comment]
bundle install をしている間にフィードバックチャンスについて考える

## インストール方法の記述中に `git clone` がない

* 場所
  * https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md
* 何が起きるか
  * `git clone` をせずに上からコマンド打っているとInstallationsで `bundle install` を打つとコケる
  * インストールガイドが書いてある場所が `tootsuite/Mastodon` と別リポジトリでソースリポジトリに行くのが困難
* どうなればよいか
  * Installations の前までに次の記述があるとよさそう

```sh
git@github.com:tootsuite/mastodon.git
```
```

**Comment by keisei1092** [comment]
```
ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```
なのに
```
Keiseis-MacBook:mastodon keisei_1092$ bundle exec rails db:setup
Your Ruby version is 2.0.0, but your Gemfile specified >= 2.3.0, < 2.5.0
```
ってなって謎

**Comment by keisei1092** [comment]
git cloneしてcdしたあとに.ruby-versionがディレクトリにあってバージョンが指定されたので
今までにしていた `gem install` の対象から外れてしまった。泣

**Comment by keisei1092** [comment]
↑フィードバックポイントかも

**Comment by keisei1092** [comment]
もう一度 `gem install` らへんのを繰り返す

**Comment by keisei1092** [comment]
N o k o g i r i

**Comment by keisei1092** [comment]
nokogiriのインストールはだいたい大変という感じなのでとりあえずnokogiri 1.8.0のインストールの知見を探す、前に公式のドキュメントかIssueを探してみる

**Comment by keisei1092** [comment]
そういえば最初にFAQとかあったな

**Comment by keisei1092** [comment]
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/FAQ.md

**Comment by keisei1092** [comment]
ここで `nokogiri` とかでgrepしてみる

**Comment by keisei1092** [comment]
ない

**Comment by keisei1092** [comment]
書いてある内容もMastodonのサービスに関するものが多そうなのでちょっとパス

**Comment by keisei1092** [comment]
ということで https://github.com/oss-gate/workshop/issues/454#issuecomment-311943293 が良さげなフィードバックポイントなのでこれをプルリクにしてみる。とりあえず先にコメントをどうするか考える

**Comment by keisei1092** [comment]
まずcontributeのルールがあるかどうか探したいのでgithubを見る

**Comment by keisei1092** [comment]
Contributing-Mastodon.mdというディレクトリがあるので見てみる
https://github.com/tootsuite/documentation/tree/master/Contributing-to-Mastodon

**Comment by keisei1092** [comment]
Translatingは翻訳っぽい
Sponsorsは提供者のリストっぽい

**Comment by keisei1092** [comment]
README.mdを見てみる

**Comment by keisei1092** [comment]
Report bugs and submit ideas のリストを押したら直でMastodonのIssueに飛ぶのがなかなかにアツい

**Comment by keisei1092** [comment]
前回 rails/railsのIssueが無視されたのが悔しいので今度はプルリクをいきなり出してみる
Pull RequestのDescriptionのテンプレートがあるかどうか確認したいのでNew Pull Requestしてプレースホルダを確認する

**Comment by keisei1092** [comment]
ISSUE_TEMPLATE.mdを見ると

```
[Issue text goes here].

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a tagged release and not on master (If you're a user, don't worry about this).
```

検索をしてかぶってないか確認が必要なのと、このバグが・・・・・・・・と思って tootsuite/mastodonじゃなくてtootsuite/documentationsにコミットしたかったのを思い出したのでそっちを見る。。。。。

**Comment by keisei1092** [comment]
https://github.com/tootsuite/documentation こっちにはテンプレートがないのでだらっと聞いて良さそう
内容がかぶっている他のIssueがすでに存在しないか調べる

**Comment by keisei1092** [comment]
いけさんがもう出してるやんけ！ https://github.com/tootsuite/documentation/pull/324

**Comment by keisei1092** [comment]
おや、このPRではDocker-Guideについて触れられているだけで、マニュアルインストールについてのことは触れてなさそうだぞ

**Comment by keisei1092** [comment]
いけそう

**Comment by keisei1092** [comment]
rails/railsを久しぶりに見に行ったらIssueがcloseされて他のエンジニアによりPRが立ってmergeされているという好プレーが発生していたので、今回もとりあえずIssueから始めることにした

**Comment by keisei1092** [comment]
ということでちゃんとしたIssueのコメントを考える

**Comment by keisei1092** [comment]
https://github.com/oss-gate/workshop/issues/454#issuecomment-311943293

## インストール方法の記述中に `git clone` がない

* 理想
  * [インストール方法](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md)の `rbenv install 2.4.1` の後に次の記述がある
     * `git clone git@github.com:tootsuite/mastodon.git`
     * `cd mastodon`
  * インストール済みであることを確認するため次の記述があると尚良いだろう
     * `rbenv versions`
* 現在
  * `git clone` をせずにインストール方法に従っていると次の問題が発生する
     * `gem update --system`, `gem install bundler` がMacのデフォルトのRubyに対して実行される
     * `bundle install --with development` 以降の操作が失敗する

**Comment by keisei1092** [comment]
↑日本語でまとめられたので、英語にする

**Comment by keisei1092** [comment]
**[WIP]**

## No any operations about cloning sources in installation guide

* Expected
  * [Development Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md) describes some instructions about cloning sources after preparing rbenv, like below:
     * `git clone git@github.com:tootsuite/mastodon.git`
     * `cd mastodon`
  * Confirmation of installation is better, like below:
     * `rbenv version`
* Actual
  * I got the following problem reading [this instructions](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md)
  * I didn't clone the source and I faced
     * `gem update --system`, `gem install bundler` がMacのデフォルトのRubyに対して実行される
     * `bundle install --with development` 以降の操作が失敗する

**Comment by kou** [comment]
お疲れ様でした！
クローズしますがこの後もここを使い続けても大丈夫です！

**Comment by bash0C7** [comment]
ステップを飛ばさずきっちりやっていく様子が素晴らしかったです！
今後社内にも広めていきましょう！！
