### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-06-29: nullkal: mastodon: Work log

### ISSUE THREAD

**Issue by nullkal** [oss-gate/workshop#455]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nullkal** [comment]
公式サイトを見つけよう！

**Comment by nullkal** [comment]
ここです: https://github.com/tootsuite/mastodon/

**Comment by nullkal** [comment]
セットアップ自体は大体済んだPCを持ち込んでしまっているので、とりあえず動かすのはおしまいです。

**Comment by nullkal** [comment]
どこかのタイミングでbundle exec rails mastodon:dailyからsidekiq-schedulerによる定期実行に置き換えられた。例: mastodon:feeds:clear (https://github.com/tootsuite/mastodon/blob/master/lib/tasks/mastodon.rake#L121)

しかし、mastodon:users:clearはまだsidekiq-schedulerに移植されていないようだ。

* https://github.com/tootsuite/mastodon/blob/master/config/sidekiq.yml
* https://github.com/tootsuite/mastodon/blob/master/lib/tasks/mastodon.rake#L145

**Comment by nullkal** [comment]
rails db:migrateするとdb/schema.rbが書き換わる

```
% git diff -- db/schema.rb
diff --git a/db/schema.rb b/db/schema.rb    
index 159704c6..de14a450 100644             
--- a/db/schema.rb    
+++ b/db/schema.rb    
@@ -300,7 +300,7 @@ ActiveRecord::Schema.define(version: 20170625140443) do              
                      
   create_table "statuses_tags", id: false, force: :cascade do |t|                       
     t.bigint "status_id", null: false      
-    t.integer "tag_id", null: false        
+    t.bigint "tag_id", null: false         
     t.index ["status_id"], name: "index_statuses_tags_on_status_id"                     
     t.index ["tag_id", "status_id"], name: "index_statuses_tags_on_tag_id_and_status_id", unique: true
   end 
```

**Comment by nullkal** [comment]
mastodon公式のDevelopment guideでは`bundle exec rails db:setup`でデータベースの初期化をすることになっているが、既にデータベースがセットアップされていたので`bundle exec rails db:migrate`をした。

**Comment by nullkal** [comment]
`bundle exec rails db:setup`すると、ユーザー名: admin@localhost:3000, パスワード: mastodonadminでログインできるようになる。

`bundle exec rails db:migrate:reset`するとログインできなくなる。

**Comment by nullkal** [comment]
```
% rails -T | grep db:reset
rails db:setup                                       # Creates the database, loads the schema, and initializes with the seed data (use db:reset to also drop the database first)
```

↑をみた感じではできるみたい

**Comment by nullkal** [comment]
あ、できた

**Comment by nullkal** [comment]
`rails db:migrate`すると…の問題に関係ありそう？
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/compatibility.rb#L21

**Comment by kou** [comment]
お疲れ様でした！
クローズしますがこの後もここを使い続けても大丈夫です！

**Comment by akihikodaki** [comment]
今回は以下の問題を扱いましたね. どちらもまだ完了していませんがぜひ解決まで頑張って欲しいです.

# `db/migrate`と`db/seeds.rb`の整合性の問題
Railsの`compatibility`の改修が必要.

# `mastodon:users:clear`がSidekiq-schedularにあるべきではという提案
私は :+1: 是非実装してPRして欲しい.
