### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-06-29: yensaki: Mastodon: Work log

### ISSUE THREAD

**Issue by yensaki** [oss-gate/workshop#456]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yensaki** [comment]
公式サイトをみつけよう

**Comment by yensaki** [comment]
カタカナのマストドンだと公式リポジトリっぽいのがないので
mastodon で再検索する
https://www.google.co.jp/search?q=mastodon&oq=mastodon&aqs=chrome..69i57j69i60j69i61l2j0l2.4703j0j9&sourceid=chrome&ie=UTF-8

**Comment by yensaki** [comment]
3番目のが公式リポジトリっぽいのでそれをみる
https://github.com/tootsuite/mastodon

**Comment by yensaki** [comment]
README があるのですこし読んで見る

**Comment by yensaki** [comment]
Development の項目があるのでそちらを参照する
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md

**Comment by yensaki** [comment]
docker を使うなと言われている

**Comment by yensaki** [comment]
開発しにくいとか。

**Comment by yensaki** [comment]
Mac と Linux 両方の立ち上げ方がある
Mac の方をやってみる

**Comment by yensaki** [comment]
Development guide にそって
Mac の手順をこなした

**Comment by yensaki** [comment]
Get Xcode Command Line Tools:
　できた

**Comment by yensaki** [comment]
Get Homebrew and use it to install the other dependencies:
できた

**Comment by yensaki** [comment]
Configure Rbenv
rbenv は既にインストールずみで指定バージョンを rbenv local install で使った

**Comment by yensaki** [comment]
gem update --system
 gem install bundler
 rbenv rehash

これはそのままやった
rehash も念のためそのまま実行

**Comment by yensaki** [comment]
PostgreSQL:　は使ったことがないので念入りに見ながらとりいれた

**Comment by yensaki** [comment]
そのままコマンド実行でできるか不安だったがとりあえず実行
コマンドの意味はあまりわからず

**Comment by yensaki** [comment]
initdb /usr/local/var/postgres -E utf8
は実行
さすがにちょっと何してるか不安すぎて貼ってあるリンクを観た
https://www.postgresql.org/

**Comment by yensaki** [comment]
Postgre の公式サイトでさっと理解はできなさそうなので
当時はちょっとググって少しだけ理解してみた
+コマンド名である程度初期設定らしいことを推測して進めた
+ Mysql の設定とある程度対照が取れているだろうと推測

**Comment by yensaki** [comment]
createdb
 export PGDATA=/usr/local/var/postgres
まではそのまま実行して特になにもおきず

**Comment by yensaki** [comment]
/usr/local/bin/postgres
 /usr/local/bin/psql

このあたりがそのままでやるとちょっとよさげじゃない感じに出た（と思う

**Comment by yensaki** [comment]
ググって psql , postgres がやってることを少し勉強

**Comment by yensaki** [comment]
一応動くようになった
恐らく db 起動できて入れたはず

**Comment by yensaki** [comment]
initdb /usr/local/var/postgres -E utf8
↑不安で２回ぐらいやったら既にあるよ、みたいなメッセージが出て

```
initdb: directory "/usr/local/var/postgres" exists but is not empty
```

**Comment by yensaki** [comment]
CREATE USER mastodon CREATEDB;

db user 作成のよう。
とくに問題はなく；

**Comment by yensaki** [comment]
bundle install --with development
yarn install --pure-lockfile
gem install foreman --no-ri --no-rdoc
bundle exec rails db:setup
bin/rails assets:precompile


これはそのまま実行したが
ちょっと前の db 設定から日が空いていて
bundle exec rails db:setup
がこける
postgre が起動していなかったよう。

なので postgre の起動を調べて起動してから再実行
問題なし

**Comment by yensaki** [comment]
/usr/local/bin/postgres
実行
問題なく動く

**Comment by yensaki** [comment]
redis-server
は既に常時実行状態だったのでスルー

**Comment by yensaki** [comment]
foreman start
foreman は理解がなかったが必要なのだろうと実行
server starter っぽい挙動だったのでそういうものだろうと認識しておく

**Comment by yensaki** [comment]
http://localhost:3000/
にアクセス
今はアクセスできたが当時はエラー画面が出ていた。

**Comment by yensaki** [comment]
admin@localhost:3000
が管理画面だというのでアクセス

管理画面が見れる…パスワード入力かと思ったのだがなぜか表のほうにリダイレクトされているよう
なぜ？

**Comment by yensaki** [comment]
admin@localhost:3000　が管理画面URLだと思っていたのだがそうでもない？

**Comment by yensaki** [comment]
アカウントだった。

**Comment by yensaki** [comment]
Development tips
も読む

**Comment by yensaki** [comment]
a localhost->world tunneling service like ngrok
ngrok ... ?

**Comment by yensaki** [comment]
ローカルホストから internet と繋げれるものっぽい

**Comment by yensaki** [comment]
TIPS なので今はそこまで時間かけて読まなくてもよいかなと

**Comment by yensaki** [comment]
実際開発環境できてるような気がする

**Comment by yensaki** [comment]
開発したいものがあればしたいが特にそういうものもない

**Comment by yensaki** [comment]
PostgreSQL の設定コマンドっぽいもの
それぞれが何をやるものなのかかんたんにでもわかれば PostgreSQL が初めてでも
ある程度そのままやることに抵抗少なくできるかもしれない

**Comment by yensaki** [comment]
PostgreSQL が初めてのひとにもフレンドリーな  guide になってると自分のような人が次に見ても楽になるかなあ

**Comment by yensaki** [comment]
それぞれのコマンド、作業が何をするものなのか
descriotion 的なものをつけれないか

**Comment by yensaki** [comment]
initdb /usr/local/var/postgres -E utf8

PostgreSQL の新規データベースクラスタを作成する
Encoding は UTF-8 指定

createdb

新規データベース作成.　デフォルトの system user 名で作成される


export PGDATA=/usr/local/var/postgres
指定のディレクトリに全てのデータを格納する

/usr/local/bin/postgres

PostgreSQL のデータベースサーバープロセスを起動する


/usr/local/bin/psql

PostgreSQL の対話的ターミナル
ここでプロンプトに入る

CREATE USER mastodon CREATEDB;

mastodon という名前で データベースユーザーアカウントを作成
http://www.postgresql.jp/document/pg721doc/reference/sql-createuser.html

 \q
プロンプトから離脱

**Comment by yensaki** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md
PostgreSQL が初めての人でも設定しやすいように
Development Guide の Configure PostgreSQL 
作業内容に説明を加えるのはいかがでしょうか。

下記のようなものはどうでしょうか。



```
# create PostgreSQL database cluster
 initdb /usr/local/var/postgres -E utf8
# create new database, database name is system user name
 createdb
# configure directory which all PostgreSQL data are stored in
 export PGDATA=/usr/local/var/postgres
# start database server process
 /usr/local/bin/postgres
# start PostgreSQL interactive terminal 
 /usr/local/bin/psql
```

```
 CREATE USER mastodon CREATEDB;
 \q
```
`¥q`: quit PostgreSQL terminal

**Comment by yensaki** [comment]
documentation を clone してそっちに　 PR つくる

**Comment by kou** [comment]
お疲れ様でした！
クローズしますがこの後もここを使い続けても大丈夫です！

**Comment by zonuexe** [comment]
ヾ(〃＞＜)ﾉﾞ
