### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-06-29: ik11235: Mastodon: Work log

### ISSUE THREAD

**Issue by ik11235** [oss-gate/workshop#457]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ik11235** [comment]
Mastodonの公式を探す

**Comment by ik11235** [comment]
「Mastodon」でgoogle検索

https://www.google.co.jp/search?q=Mastodon&oq=Mastodon&aqs=chrome..69i57j69i60j69i61j69i60j69i59j0.319j0j4&sourceid=chrome&ie=UTF-8

**Comment by ik11235** [comment]
1つ目を開く
https://mstdn.jp/about

ここは　「Mastodon日本鯖」　となっているので、公式ではなさそう

**Comment by ik11235** [comment]
4つめのgithubリポジトリが公式っぽい
https://github.com/tootsuite/mastodon

**Comment by ik11235** [comment]
ローカルに開発環境を作ってみる

**Comment by ik11235** [comment]
インストールガイドを探す

**Comment by ik11235** [comment]
READMEに Deployment へのリンクがある

https://github.com/tootsuite/documentation#running-mastodon

**Comment by ik11235** [comment]
Running Mastodon というリンクは ドキュメントのリポジトリへのリンクだった

**Comment by ik11235** [comment]
Deployment 内にdocker guideがあったので試してみる

https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md

**Comment by ik11235** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md

のSetting up がどこで実行すればいいかわからない

**Comment by ik11235** [comment]
Mastodonリポジトリから、ローカルで動かす方法を探していた
https://github.com/tootsuite/mastodon
→ Deployment
https://github.com/tootsuite/documentation#running-mastodon
→ Docker guide
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md

たどり着いたDocker-Guide にSetting up があるが、どこで実行すればいいか書いていないため分からない

**Comment by ik11235** [comment]
Mastodonリポジトリ をローカルで動かす環境を READMEから探していた

README内の「Deployment」より、「Docker guide」を開いたが、
Docker guideの Docker-Guide.md にかかれている 「Setting up」 を動かす環境、記載されている「docker-compose.yml」や「.env.production.sample」の取得方法が記載されておらず、分からなかった

Setting up の最初のステップで、以下の記載があると詰まること無く進めると思った。

```sh
git clone git@github.com:tootsuite/mastodon.git
cd mastodon
```

**Comment by ik11235** [comment]
I was reading [documentation/Docker\-Guide\.md](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md) to run Mastodon with Docker.

I did not know which directory to execute the "Setting up" chapter.

With the following command I successfully proceeded to the next step.

```sh
git clone git@github.com:tootsuite/mastodon.git
cd mastodon
```

Please add this description to the document.

**Comment by ik11235** [comment]
I was reading [documentation/Docker\-Guide\.md](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md) to run Mastodon with Docker.

I did not know which directory to execute the "Setting up" chapter.

With the following command I successfully proceeded to the next step.

```sh
git clone git@github.com:tootsuite/mastodon.git
cd mastodon
```

I started reading from the [mastodon/README\.md](https://github.com/tootsuite/mastodon/blob/master/README.md) and read the [Deployment](https://github.com/tootsuite/documentation#running-mastodon), [Docker guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md), but I could not find this command anywhere.

Please add this description to the document.

**Comment by ik11235** [comment]
MRを作って送った

https://github.com/tootsuite/documentation/pull/324

**Comment by ik11235** [comment]
↓でコケた
```sh
% docker-compose run --rm web rake db:migrate                         [master][/Users/ik/git/mastodon]

Starting mastodon_db_1 ...
Starting mastodon_redis_1 ... done
Creating mastodon user (UID : 991 and GID : 991)...
Updating permissions...
Executing process...
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'efa3c15530ab762007f36d3befe594a669ef2ac0002453bd51ef9cf5423313fbc403ad23f256962cac52e506dfc0c77a137248fff8b17d402d9a21f26e0872d5'

Please ensure you restarted your application after installing Devise or setting the key.
/mastodon/vendor/bundle/ruby/2.4.0/gems/devise-4.3.0/lib/devise/rails/routes.rb:498:in `raise_no_secret_key'
/mastodon/vendor/bundle/ruby/2.4.0/gems/devise-4.3.0/lib/devise/rails/routes.rb:226:in `devise_for'
/mastodon/config/routes.rb:22:in `block in <top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:424:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:424:in `eval_block'
/mastodon/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:406:in `draw'
/mastodon/config/routes.rb:6:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:55:in `each'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:55:in `load_paths'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:18:in `reload!'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:41:in `block in updater'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/file_update_checker.rb:81:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:42:in `updater'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
/mastodon/config/environment.rb:5:in `<top (required)>'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
/mastodon/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:329:in `require_environment!'
/mastodon/vendor/bundle/ruby/2.4.0/gems/railties-5.1.2/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/mastodon/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by ik11235** [comment]
↑ 
> Now the image can be used to generate secrets. Run the command below for each of PAPERCLIP_SECRET, SECRET_KEY_BASE, and OTP_SECRET then copy the results into the .env.production file:

を読み飛ばしていたせい。
実行したらうまく動いた

**Comment by ik11235** [comment]
無事たちあがったので、 READMEに戻ってadminガイドを探した
https://github.com/tootsuite/mastodon/blob/master/README.md

**Comment by ik11235** [comment]
adminガイドあった
https://github.com/ik11235/documentation/blob/master/Running-Mastodon/Administration-guide.md

**Comment by ik11235** [comment]
adminユーザーを作る
    docker-compose run --rm web rails mastodon:make_admin USERNAME=alice

**Comment by ik11235** [comment]
エラーが出た
 ユーザーがある前提だった
```
% docker-compose run --rm web rails mastodon:make_admin USERNAME=ik 
Starting mastodon_db_1 ...
Starting mastodon_redis_1 ... done
Creating mastodon user (UID : 991 and GID : 991)...
Updating permissions...
Executing process...
User could not be found; please make sure an Account with the `ik` username exists.
```

**Comment by ik11235** [comment]
https://github.com/ik11235/documentation/blob/master/Running-Mastodon/Development-guide.md#running
を見たら、adminあるっぽかったけど、ログインできなかった

> Admin account is admin@localhost:3000. Password is mastodonadmin.

**Comment by kou** [comment]
お疲れ様でした！
クローズしますがこの後もここを使い続けても大丈夫です！

**Comment by satoryu** [comment]
お疲れ様でした！ いつもより短い時間のワークショップでしたが、プルリクエストを出せて良かったですね！
Gitterでもこちらでもどこでもいいので、何か困ったことがあればいつでも聞いてくださいー
