### ISSUE TITLE
OSS Gate Workshop: pixiv: 2017-06-29: nezuku: Mastodon: Work log

### ISSUE THREAD

**Issue by nezuku** [oss-gate/workshop#458]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nezuku** [comment]
公式サイトを見つけよう。

**Comment by nezuku** [comment]
「Mastodon」で検索をする。

**Comment by nezuku** [comment]
1つ目は日本語版サイトみたい。
https://mstdn.jp/about
3つ目が公式のGitリポジトリのようだ。
https://github.com/tootsuite/mastodon

**Comment by nezuku** [comment]
Clone or DownloadボタンからMastodonのリポジトリへのアドレスを取得する。
https://github.com/tootsuite/mastodon.git
リポジトリのアドレスを確認。

**Comment by nezuku** [comment]
ソースコードをCloneするまえに
README読んでみる

**Comment by nezuku** [comment]
READMEの中からDevelopmentの節を確認、Development Guideを見る
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Development-guide.md

**Comment by nezuku** [comment]
Development Guideで説明のあるプラットフォームはLinuxとMacなので、別のページを探してみる。

**Comment by nezuku** [comment]
続いてDeploymentの項目を読む
https://github.com/tootsuite/documentation#running-mastodon

**Comment by nezuku** [comment]
リンク先の節のうちRunning Mastodon へ進む
https://github.com/tootsuite/documentation/tree/master/Running-Mastodon
Markdownファイルの一覧だった

**Comment by nezuku** [comment]
一旦戻って、節の下に並ぶ各項目のリンク先がドキュメントのようなので辿る。

- Resources needed
- Production guide
- Docker guide
- Alternative: Running on Heroku
- Development guide
- Alternative: Development with Vagrant
- Alternative: Development and Production with Nanobox
- Administration guide
- Maintenance Tasks
- Tuning Mastodon
- System Configuration Alternatives

上から順番に読んでみる

**Comment by nezuku** [comment]
Resource needed
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Resources-needed.md
稼働するサーバに必要なリソースについて

**Comment by nezuku** [comment]
Production guide
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md
必要な依存パッケージやその導入手順についての説明

**Comment by nezuku** [comment]
Docker guide
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md
Dockerで動かす方法の手順のページ

**Comment by nezuku** [comment]
Alternative として他の動かし方があるので、この中から
Vagrant Guideを参照する。
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Vagrant-guide.md

**Comment by nezuku** [comment]
Vagrantでの動作手順があるので、これに従って進める。

**Comment by nezuku** [comment]
オプション扱いではあるがVagrantへプラグインの導入を行う
`vagrant plugin install vagrant-hostsupdater`

**Comment by nezuku** [comment]
プラグインのインストールが始まる
`Installing the 'vagrant-hostupdater' plugin. This can take a few minutes...`
が、失敗する。
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostupdater (> 0)'
```

**Comment by nezuku** [comment]
原因
`vagrant plugin install vagrant-hostupdater`
タイプミス
やり直し
```
> vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
```

**Comment by nezuku** [comment]
エラーがすぐ返らず少し時間をかかったのち、インストールに成功した旨が返る。
```
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Fetching: vagrant-hostsupdater-1.0.2.gem (100%)
Installed the plugin 'vagrant-hostsupdater (1.0.2)'!
```

**Comment by nezuku** [comment]
導入した vagrant-hostsupdater の説明について

> The following command will update your 'hosts' file when you start the virtual machine, allowing you to access the site at http://mastodon.dev (instead of http://localhost:3000):

**Comment by nezuku** [comment]
hosts を実行開始時に更新し、 http://mastodon.dev でアクセスできるように補助するプラグイン。
ここでは mastodon.dev であるが、動かす対象によってホスト名は異なるとみられる。

**Comment by nezuku** [comment]
Mastodon の開発環境の VM を作成する。先ほどからのドキュメントを続きを読む。

**Comment by nezuku** [comment]
これから行う操作の手順
```
git clone https://github.com/tootsuite/mastodon.git
cd mastodon
vagrant up --provider virtualbox
```

1. Mastodon の公式リポジトリからコードを clone する
2. clone した Mastodon のディレクトリに移動
3. Vagrant で開発環境の VM を立ち上げる
-- VirtualBox を使うようオプションを指定する

**Comment by nezuku** [comment]
(Markdown の書き方を間違えて、3. の子ノードにオプション指定について箇条書きしようとして失敗)

**Comment by nezuku** [comment]
ソースコードの clone
アドレスは同じだけどリポジトリのアドレスを公式サイト/リポジトリのトップページにある "Clone or Download" から取得。
clone 元は https://github.com/tootsuite/mastodon.git

**Comment by nezuku** [comment]
clone する
`git clone https://github.com/tootsuite/mastodon.git`

**Comment by nezuku** [comment]
clone の結果
```
> git clone https://github.com/tootsuite/mastodon.git
Cloning into 'mastodon'...
remote: Counting objects: 38755, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 38755 (delta 1), reused 4 (delta 1), pack-reused 38743
Receiving objects: 100% (38755/38755), 39.46 MiB | 6.42 MiB/s, done.
Resolving deltas: 100% (24398/24398), done.
Checking out files: 100% (5157/5157), done.
```
clone 完了し、Mastodon のソースコードを取得。

**Comment by nezuku** [comment]
続いて clone 先に移動し vagrant で開発環境の起動を行う。
`cd mastodon`
`ls`
移動して、Mastodon のリポジトリトップの一覧を眺めてみてみる

**Comment by nezuku** [comment]
開発環境の VM を立ち上げる
`vagrant up --provider virtualbox`
その手前、リポジトリのトップに Vagrantfile があるのを見つける
これを解釈して開発環境の VM を作成するとみられる

**Comment by nezuku** [comment]
途中ホストオンリーインタフェースを作成する必要があり、権限昇格を受け付けて継続
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: mastodon
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aInterfaceName.isEmpty()] at 'F:\tinderbox\win-5.1\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in long __cdecl HostNetworkInterface::init(class com::Bstr,class com::Bstr,class com::Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0038).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
```
ホストオンリーインタフェースの作成で失敗する

**Comment by nezuku** [comment]
エラーメッセージから、VirtualBox 内部でクラッシュしているとみられる
対処策を考える

**Comment by nezuku** [comment]
対処策

- もう一度実行してみる
- 既存の VirtualBox ホストオンリーインタフェースを削除する

**Comment by nezuku** [comment]
一瞬デバイスドライバのインストールダイアログが出るも、そのあとクラッシュして失敗する

**Comment by nezuku** [comment]
既存のホストオンリーインタフェースを消し、明示的に再作成を試す

**Comment by nezuku** [comment]
VirtualBox のホストオンリーインタフェースが複数生成されているので、これらをまず全て消去し、クリーンアップする

**Comment by nezuku** [comment]
ホストオンリーインタフェース3つを無効にはできるも消せない

**Comment by nezuku** [comment]
デバイスマネージャーから3つともホストオンリーインタフェースを消した

**Comment by nezuku** [comment]
もう一度 Vagrant を実行する

**Comment by nezuku** [comment]
ホストオンリーインタフェースは作成されるも失敗する

**Comment by nezuku** [comment]
再起動を試す その前に中途半端に作成されたホストオンリーインタフェースを消してから再起動

**Comment by nezuku** [comment]
再起動が完了したので、もう一度実行する
が、失敗する

**Comment by nezuku** [comment]
再起動が完了したので、もう一度実行する
が、失敗する

**Comment by nezuku** [comment]
provider を変更して試す。
現在の環境には VMware Workstation Playerもあるので、vagrant の provider を VMware に変更して試す。

**Comment by nezuku** [comment]
vagrant up -h で up 時に VMware 指定する方法を確認。
provider オプションの指定方法がわからなかったので、公式サイトへ行く。
指定方法が見つからないので、 virtualbox での指定方法を基に vmware に置換する

**Comment by nezuku** [comment]
失敗した。
```
An active machine was found with a different provider. Vagrant
currently allows each machine to be brought up with only a single
provider at a time. A future version will remove this limitation.
Until then, please destroy the existing machine to up with a new
provider.

Machine name: default
Active provider: virtualbox
Requested provider: vmware
```
途中でプロバイダとなる VM を切り替えられない。
destroy する必要がある。

**Comment by nezuku** [comment]
プロバイダ変更に失敗する。
```
> vagrant up --provider vmware
The provider 'vmware' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

```

**Comment by nezuku** [comment]
これまでの手順

1. Mastodon のソースコードの取得を完了する
2. VirtualBox をプロバイダとして開発環境の VM の作成と実行を行う
3. ホストオンリーのネットワークインタフェースを作成するところで失敗する

原因の考察

- VirtualBox がホストオンリーインタフェースを作成する際、それを担当するプログラムのクラッシュ
- Mastodon および公式のドキュメントについて誤りがあるものでないと考察
- 今回実施した環境特有の問題とみられる

ほかに考えられる対処

- 適切に Vagrant で用いるプロバイダの仮想機械のオプションを確認する
- VirtualBox の再インストール
- 他にある Linux 機を用いる

**Comment by kou** [comment]
お疲れ様でした！
クローズしますがこの後もここを使い続けても大丈夫です！

**Comment by igaiga** [comment]
おつかれさまでした！
がつがつ進めていってすごいなと思いました。
解決していくプロセスも論理的で私も勉強になりました。

最初の失敗の手順と起きた環境の報告だけでも開発者さんには有用だと思うので、今後issue報告したら後続の人のためになるかと思います。 👍

**Comment by kou** [comment]
よろしくお願いします！

**Comment by nezuku** [comment]
遅くなりましてすみません、その後の報告です。
Vagrant上でmastodonインスタンスを立ち上げ、表示することに成功しました。
以下経過となります。

1. VirtualBoxにてVagrantから稼働させる、ゲストVM向けホストオンリーネットワークインタフェースの作成失敗
    - 実行する環境特有の問題であった。VirtualBoxの再起動で解消。
2. yarn実行途中にシンボリックリンクの作成で失敗する
    - VirtualBoxの共有フォルダ機能はゲストからのシンボリックリンクの作成操作には対応している。マウント先がNTFSの場合もシンボリックリンクを作成するが、NTFSにおいてシンボリックリンクを作成するには管理者権限が必要であった。
    - Vagrantおよびそこから呼ばれるheadlessなVirtualBoxゲストを管理者権限で実行して対処。
3. 一部の実行可能属性のついたスクリプトについて、1行目シバンでのインタプリタ指定に異常があった
    - ~/.gitconfigのcore.autocrlfがautoであったため、改行コードがcloneないしはpull時にLFからCRLFに変換。
    - シバンの内容を "/usr/env ruby[CR]"と誤認し、実行可能属性のついたRubyスクリプトが始動できないなどの事象が発生。
    - 間違ったパスにCRが含まれるため、エラーメッセージの端末での表示も崩れる。
    - ~/.gitconfigのcore.autocrlfをinputもしくはfalseに変更し、再びgit cloneを実行。

これらの問題を解消し、mastodonインスタンスを起動することができました。起きた問題点については一通り利用した環境特有の問題でありました。お騒がせしてすみませんでした。
