### ISSUE TITLE
OSS Gate Meetup: Tokyo: 2017-07-13

### ISSUE THREAD

**Issue by koic** [oss-gate/workshop#478]
# 東京ミートアップ2017-07-13

## このissueは何のために使うの？

ミートアップの始めと終わりに誰が来て、何をして、どうだったかを共有するために使います！

## いつ共有をするの？

当日の始めと終わりに、共有する時間をそれぞれ設けます！

## どうやって共有するの？

以下のことを両方やってください！

* 会場で口頭で喋る
* このissueにコメントで書く

## ミートアップの始めに喋る/書くとよさそうなこと

以下に示す内容のいずれかで大丈夫です！

* 呼んでほしい名前
* 普段やっていること
* 普段利用/開発しているもの
* 当日やること
* 「よろしくお願いします！」

## ミートアップの終わりに喋る/書くとよさそうなこと

以下に示す内容のいずれかで大丈夫です！

* やったことの進捗
* ミートアップの感想
* 「お疲れ様でした！」

**Comment by koic** [comment]
@koic Ruby 関係の OSS へのパッチを書く予定です。

**Comment by yasulab** [comment]
## 今日やること

- [CoderDojo Japan](http://coderdojo.jp/) の動画編集とアップロード

**Comment by highwide** [comment]
### 今日やること
* 初参加なので、まずは感覚をつかみます...！

**Comment by selmertsx** [comment]
## 今日やること

- custom_validatorにて、ドキュメントにある方法ではstrictを使えないので、それに関して何かする。

**Comment by swamp09** [comment]
### 今日やりたいこと

https://github.com/sunspot/sunspot
へのワーニングを抑えるPRを出し終える。

**Comment by satoryu** [comment]
# 今日やること

- [ ] [tdiary/tdiary-blogkit](https://github.com/tdiary/tdiary-blogkit) にgfmスタイルを追加するPRを作る。

**Comment by jjjjpppp** [comment]
# 今日やること

- [ ] https://github.com/refinery/refinerycms に貢献すべくローカルに落としてテスト回す

**Comment by yasulab** [comment]
PR出しました ✅😸 

Add link to YouTube playlist
https://github.com/oss-gate/oss-gate.github.io/pull/46

**Comment by satoryu** [comment]
おもむろに @kou さんからネタをもらって、バグチケットを作った。  https://bugs.ruby-lang.org/issues/13744

**Comment by yasulab** [comment]
- [x] いい雰囲気だったので突発的に動画を撮ってしまった 📹 👀  ✨

**Comment by yasulab** [comment]
@kou PR投げました! Review お願いします 🙏 

Put link to YouTube Channel on footer
https://github.com/oss-gate/oss-gate.github.io/pull/47

**Comment by yasulab** [comment]
- [x] One more PR sent

**Comment by yasulab** [comment]
Tweeted. 🐦 https://twitter.com/yasulab/status/885474962995257345

> たまたま三脚とカメラと収録機材一式をもっていたので、今日の OSS Gate ミートアップの雰囲気を動画で撮影してみました! 📹✨ #oss_gate 
> https://www.youtube.com/watch?v=vjT2BbHzlUM

**Comment by kou** [comment]
たまたますごい！

**Comment by satoryu** [comment]
@yasulab 動画公開、問題ないです！ 👍

**Comment by yasulab** [comment]
ありがとうございます! 😸

**Comment by koic** [comment]
メンテナンスしている Ruby のライブラリへの frozen string literal 対応をしていたり、Ruby ライブラリのプロジェクトへのパッチの送り方など伝えたりしていました。

**Comment by koic** [comment]
お疲れ様でした。次回の OSS Gate 東京ミートアップは 8/28 (月) にてお願いします。Doorkeeper の用意まで少々お待ち下さいませ。
