### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-07-29: freddiefujiwara: chromy: Work log

### ISSUE THREAD

**Issue by freddiefujiwara** [oss-gate/workshop#480]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by freddiefujiwara** [comment]
"chromy"でgoogleで検索する

**Comment by freddiefujiwara** [comment]
https://github.com/OnetapInc/chromy が一番上に出てきた

**Comment by freddiefujiwara** [comment]
https://github.com/OnetapInc/chromy をクリック

**Comment by freddiefujiwara** [comment]
READMEを読む

**Comment by hori031617** [comment]
堀：よろしくお願いします。

**Comment by KimiakiKinugasa** [comment]
よろしくお願いします。

**Comment by komainu8** [comment]
よろしくお願いします。

**Comment by cuon-kakimoto** [comment]
今日は、よろしくお願いします！

**Comment by freddiefujiwara** [comment]
READMEから 必須環境として
Node 6 以上
と
Chrome59 以上が
必要だと認識

**Comment by freddiefujiwara** [comment]
`npm i chromy`
をターミナル上で実行

**Comment by freddiefujiwara** [comment]
インストール中に
```
npm WARN enoent ENOENT: no such file or directory, open '/home/fujiwarafumi01/oss-gate/package.json'
npm WARN oss-gate No description
npm WARN oss-gate No repository field.
npm WARN oss-gate No README data
npm WARN oss-gate No license field.
```
のワーニングを確認

**Comment by freddiefujiwara** [comment]
READMEのサンプルプログラム
をコーディングして　実行

**Comment by freddiefujiwara** [comment]
具体的な　サンプルプログラムの起動方法は記載されていない

**Comment by freddiefujiwara** [comment]
実行方法を予測して実行したところエラー
```
 node sample.js 
/home/fujiwarafumi01/oss-gate/sample.js:1
(function (exports, require, module, __filename, __dirname) { t Chromy = require('chromy')
                                                                ^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

**Comment by freddiefujiwara** [comment]
nodeのバージョンが古いかを確認
```
node --version
v7.9.0
```
READMEに記載されているNode 6.0以上であることを確認

**Comment by freddiefujiwara** [comment]
サンプルプログラムを確認

**Comment by freddiefujiwara** [comment]
constと記載すべきがコピペミスで
t
だけになっていることを確認

**Comment by freddiefujiwara** [comment]
コピペミスを修正

**Comment by freddiefujiwara** [comment]
` node sample.js 
を実行

**Comment by freddiefujiwara** [comment]
13がリターンされたので
コードを見て確認する

**Comment by freddiefujiwara** [comment]
内容を確認するためサンプルプログラム中の
`document.querySelectorAll('*').length`
を
`document.querySelectorAll('*')`
に変更して確認

**Comment by freddiefujiwara** [comment]
再実行して確認したところ　
理解が出来なかった
```
node sample.js 
{ '0': {},
  '1': {},
  '2': {},
  '3': {},
  '4': {},
  '5': {},
  '6': {},
  '7': {},
  '8': {},
  '9': {},
  '10': {},
  '11': {},
  '12': {} }
```

**Comment by freddiefujiwara** [comment]
ソースコードの説明がないことを確認

**Comment by freddiefujiwara** [comment]
次のサンプルコードが
内容が同じことを確認

**Comment by freddiefujiwara** [comment]
Mobile Emulationのサンプルプログラムを
コピペして実行

**Comment by freddiefujiwara** [comment]
下記を実行
```
node sample_mobile.js 
Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
```

**Comment by freddiefujiwara** [comment]
サンプルプログラムのソースコードを読んで内容を理解

**Comment by freddiefujiwara** [comment]
https://github.com/OnetapInc/chromy/wiki/FAQ 
を確認

**Comment by freddiefujiwara** [comment]
下記を確認

1. chromy複数インスタンスの立ち上げ方法
2. chromy中でJavaScriptを評価した時にchromyからJavaScritpの変数へのアクセス方法
3. chromyが画像等のリソースにアクセスしない方法(disable)

**Comment by freddiefujiwara** [comment]
APIの項目を確認

**Comment by freddiefujiwara** [comment]
chromelessとの比較からサジェスチョン


あるとベター( https://github.com/graphcool/chromeless と比較 )
- 何を目指しているか 何ができるのか
- 現在の進捗
- 全体構成がわかる図
- デモ example: https://goo.gl/837ATd
- このツールの目的 Nightmare.jsみたいな　としか書いてない
- Local setup 知っている人しかわからない
- - Windows/Linux/Mac環境ごとのローカルセットアップ方法
- npmのパッケージのバージョン

**Comment by freddiefujiwara** [comment]
APIの説明、サンプルがないものがある

-  .end()
- type(selector, text)
- .insert(selector, text)
- .check(selector)
- .uncheck(selector) 
- .select(selector, value)

**Comment by freddiefujiwara** [comment]
サンプルコード
https://github.com/OnetapInc/chromy/blob/master/examples/screenshot.js
を発見したので　内容を理解するために　見てみる

**Comment by freddiefujiwara** [comment]
https://github.com/OnetapInc/chromy/tree/master/examples
に大量のsample codeを発見

**Comment by freddiefujiwara** [comment]
サンプルコードを実行してみる

- usageがない

`node examples/screenshot.js `

**Comment by freddiefujiwara** [comment]
出力結果が下記になった

![out_doc](https://user-images.githubusercontent.com/16923/28741715-94af0b60-7457-11e7-8fe7-7b803e77f5ec.png)
![out_form](https://user-images.githubusercontent.com/16923/28741713-94ac0b5e-7457-11e7-83cb-6691ddc2d48f.png)
[out.pdf](https://github.com/oss-gate/workshop/files/1184594/out.pdf)
![out](https://user-images.githubusercontent.com/16923/28741714-94adb300-7457-11e7-91a3-55a65a34f353.png)

**Comment by freddiefujiwara** [comment]
chromy/examples/pages/index.html
をスクリーンショットにとって
出していることを確認

**Comment by freddiefujiwara** [comment]
基本的には chrome devtools-protocolのAPIラッパーだと思うが
see detail "here"
と　"chrome document" 
と表記ゆれがある

**Comment by freddiefujiwara** [comment]
Issueを作ってみる
Title:  to fix installation warning 

# Background
In developer point of  view 
the warnings make him uneasy.
so I'd like to fix the warnings 

# Steps to reproduce
`npm i chromy`

# Expected behavior
installation finished w/o any warnings.

 ```
 │ └─┬ tar@3.1.7 
  │   ├── minipass@2.2.1 
  │   ├── minizlib@1.0.3 
  │   └── yallist@3.0.2 
  └── uuid@3.1.0 
```

# Actual behavior
```
  │ └─┬ tar@3.1.7 
  │   ├── minipass@2.2.1 
  │   ├── minizlib@1.0.3 
  │   └── yallist@3.0.2 
  └── uuid@3.1.0 

npm WARN enoent ENOENT: no such file or directory, open '/path/to/dir/package.json'
npm WARN oss-gate No description
npm WARN oss-gate No repository field.
npm WARN oss-gate No README data
npm WARN oss-gate No license field.
```

# Environment
node --version
v7.9.0

**Comment by freddiefujiwara** [comment]
↑はnpmの仕様かもしれないので次のissue

**Comment by freddiefujiwara** [comment]
# Issue
環境のセットアップ方法がなく
事前知識がない人は次に何をしていいかわからない

# Solution
環境セットアップ方法はいくつかあるが、
そのうちの代表的なものを、記載することで
次のアクション、サンプルコードを動かす
にスムーズに移行できる

**Comment by freddiefujiwara** [comment]
Title: unclear local setup 

# Issue
some developer who doesn't have any basic knowledge about headless chrome and how to set up might be confused 
Depending on his enviroment he can not proceed next step.




 

# Example Solution
add some example for setting up local environment to README.md

Linux
ex1)
Docker env

docker run --init -it --rm --name chrome --shm-size=1024m -p=127.0.0.1:9222:9222 --cap-add=SYS_ADMIN \
  yukinying/chrome-headless-browser

https://github.com/yukinying/chrome-headless-browser-docker

ex2)
chrome \
  --headless \                   # Runs Chrome in headless mode.
  --disable-gpu \                # Temporarily needed for now.
  --remote-debugging-port=9222 


https://developers.google.com/web/updates/2017/04/headless-chrome

Windows
I'm not sure

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
