### ISSUE TITLE
OSS Gate Workshop: Tokyo:2017-07-29: kamimura: phpexcel: Work log

### ISSUE THREAD

**Issue by carotene4035** [oss-gate/workshop#481]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by carotene4035** [comment]
phpexcelで検索

**Comment by carotene4035** [comment]
一番上にでてきた
https://github.com/PHPOffice/PHPExcel

**Comment by carotene4035** [comment]
licence.mdがあったのでちょっと開いてみる

**Comment by carotene4035** [comment]
長くてよめない

**Comment by carotene4035** [comment]
readmeをよんでみる

**Comment by kono** [comment]
斜め前の赤いdellです!

**Comment by selmertsx** [comment]
正面の白Tです！

**Comment by takaishi** [comment]
ボーダーシャツ野郎です！よろしくお願いします！

**Comment by banban9999** [comment]
右端の黒服です！よろしくお願いいたします！

**Comment by carotene4035** [comment]
pdf出力もできる

**Comment by carotene4035** [comment]
ただし他のmpdfというソフトをinstallする必要がある

**Comment by carotene4035** [comment]
php5.2.0以上が必要

**Comment by carotene4035** [comment]
PHP extension php_zip 
PHP extension php_xml
PHP extension php_gd2

以上のextensionが必要。
これを知っていればあのときに苦労せずに住んだのに。。

**Comment by carotene4035** [comment]
PhpSpreadsheet to contribute patches and features.

**Comment by carotene4035** [comment]
えええ〜
phpexcelの後継がでているのかよ！

**Comment by carotene4035** [comment]
phpspreadsheetで検索して上から２番めのサイトを見てみる
http://ariarijp.hatenablog.com/entry/2017/03/27/090000

**Comment by carotene4035** [comment]
PHPExcelと互換性のない変更が含まれる
とのこと

**Comment by carotene4035** [comment]
まだ開発中なので、業務でつかうかはちょっと考え中。

**Comment by carotene4035** [comment]
phpspread sheetのリポジトリをみてみる

**Comment by carotene4035** [comment]
比較している表があるのでみてみる

**Comment by carotene4035** [comment]
phpexcelから以下の点を改善しているそう
namespaceをつかったり
新しいバージョンのphpに適した形でソースコードを書き直している

**Comment by carotene4035** [comment]
phpの規約
psrに則って書いている

**Comment by carotene4035** [comment]
公式リリースはまだ。

**Comment by carotene4035** [comment]
だから使ったらうまく動かない可能性もあるそう。

**Comment by carotene4035** [comment]
でも使ってみたいので今回使ってみる

**Comment by carotene4035** [comment]
https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/CHANGELOG.PHPExcel.md
change logをみてみる

**Comment by carotene4035** [comment]
vlookup sortも使えるのか。。

**Comment by carotene4035** [comment]
そろそろ動かし始めてみる

**Comment by carotene4035** [comment]
ローカル開発環境上で動かしてみる

**Comment by carotene4035** [comment]
vagrantで起動

**Comment by carotene4035** [comment]
たちあがったので、実験用のディレクトリを作成。

**Comment by carotene4035** [comment]
php -vで5.6だったので、
phpenvをいれてphp 7.0にしておこう

**Comment by carotene4035** [comment]
http://qiita.com/toshiro3/items/2ca2765c1a5fee78d504
これをみながら作業

**Comment by carotene4035** [comment]
すでにはいってたっぽい

**Comment by carotene4035** [comment]
https://github.com/PHPOffice/PHPExcel
後継の開発が始まっていることを
もっと上の方にかいてほしいな〜

**Comment by carotene4035** [comment]
なんとなくphp7.0.10をinstall

**Comment by carotene4035** [comment]
失敗した

**Comment by carotene4035** [comment]
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
configure: error: xml2-config not found. Please check your libxml2 install

エラーないよう

**Comment by carotene4035** [comment]
re2cを最新の状態にしてみる

**Comment by carotene4035** [comment]
re2cをinstallするときにepelリポジトリが必要。
yum install epel-release
その後install
yum install re2c

**Comment by carotene4035** [comment]
sudo していなかったので　おこられた

**Comment by carotene4035** [comment]
phpenv install 7.0.10

**Comment by carotene4035** [comment]
をもっかいやってみた

**Comment by carotene4035** [comment]
おこられた

**Comment by carotene4035** [comment]
configure: error: xml2-config not found. Please check your libxml2 installation.

**Comment by carotene4035** [comment]
エラー分でググる

**Comment by carotene4035** [comment]
sudo yum install -y libxml2 libxml2-devel
をいれたらよさそう

**Comment by carotene4035** [comment]
いれたので
phpenv install 7.0.10

**Comment by carotene4035** [comment]
Please reinstall the BZip2 distribution

**Comment by carotene4035** [comment]
bzip2を入れる

**Comment by carotene4035** [comment]
sudo yum install bzip2-devel

**Comment by carotene4035** [comment]
もっかいphpenv install

**Comment by carotene4035** [comment]
jpeglib.h not found

**Comment by carotene4035** [comment]
こういうのはできれば一度にでてきたほしいなぁ

**Comment by carotene4035** [comment]
yum searchでパッケージが探せることを知った

**Comment by carotene4035** [comment]
sudo yum -y install libjpeg-devel
を実行

**Comment by carotene4035** [comment]
configure: error: png.h not found

**Comment by carotene4035** [comment]
yum install libpng-devel

**Comment by carotene4035** [comment]
https://blog.77jp.net/php-528-%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB-linux

**Comment by carotene4035** [comment]
configure: error: Cannot find libtidy

**Comment by carotene4035** [comment]
phpのversion up、はまりそうなのでいったんやめます

**Comment by carotene4035** [comment]
イマイチinstall方法がわからない

**Comment by carotene4035** [comment]
ぐぐる

**Comment by carotene4035** [comment]
vim composer.jsonの中に
{
    "require": {
        "phpoffice/phpspreadsheet": "dev-develop"
    }
}

**Comment by carotene4035** [comment]
を追加

**Comment by carotene4035** [comment]
composer install

**Comment by carotene4035** [comment]
installできたい

**Comment by carotene4035** [comment]
http://phpspreadsheet.readthedocs.io/en/develop/
サポーターの方にみつけていただいた

**Comment by carotene4035** [comment]
一番上に書かれてもわからないｗｗｗ

**Comment by carotene4035** [comment]
やはりreadmeにhow to installがあるとよい

**Comment by carotene4035** [comment]
そこで
http://phpspreadsheet.readthedocs.io/en/develop/
のリンクをはってくれればよいのに

**Comment by carotene4035** [comment]
sample.xlsxをつくって動かしてみたら
エラー。

**Comment by carotene4035** [comment]
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'File "sample1.xlsx" does not exist.' in /var/www/html/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/File.php:160\nStack trace:\n#0 /var/www/html/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(350): PhpOffice\\PhpSpreadsheet\\Shared\\File::assertFile('sample1.xlsx')\n#1 /var/www/html/spreadsheet/test.php(15): PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx->load('sample1.xlsx')\n#2 {main}\n  thrown in /var/www/html/spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/File.php on line 160

**Comment by carotene4035** [comment]
↑
cd /var/log/httpd/error_log

**Comment by carotene4035** [comment]
をみた
エクセルファイル名がまちがっていたっぽい

**Comment by carotene4035** [comment]
例外をちゃんとキャッチして表示して欲しい

**Comment by carotene4035** [comment]
そのまま投げるだけだと
phpの設定によってはエラーが画面に表示されない

**Comment by carotene4035** [comment]
https://github.com/PHPOffice/PhpSpreadsheet#want-to-contribute
のreadmeには、install方法が記載されていない。

インストールがすぐにしやすいよう、
インストール時にコマンドライン上で実行するコマンドが書かれているとうれしい。

```
aaaaaaaa
```

**Comment by carotene4035** [comment]
README.mdにはinstall方法がかかれていないので、導入に少し時間がかかりました。
導入しやすいように、README.mdに以下のような記載をしてみてはどうでしょうか。

## How to install
```
composer require phpoffice/phpspreadsheet
```

## How To Install
http://phpspreadsheet.readthedocs.io/en/develop/
see Installation section

**Comment by carotene4035** [comment]
リポジトリの.github下にissueのテンプレートがあった。

**Comment by carotene4035** [comment]
This is:

- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?


### What is the current behavior?


### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```


### Which versions of PhpSpreadsheet and PHP are affected?

**Comment by carotene4035** [comment]
これにそって書き直そうと思う。

**Comment by carotene4035** [comment]
This is:

- [ ] a bug report
- [ ] a feature request
- [x ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?


### What is the current behavior?


### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```


### Which versions of PhpSpreadsheet and PHP are affected?

**Comment by carotene4035** [comment]
This is:

- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
I suppose that put "How to install" section below "PHP version support" to install more easily PhpSpreadsheet for beginners.

#### example1

```
composer require phpoffice/phpspreadsheet
```

#### example2

http://phpspreadsheet.readthedocs.io/en/develop/
see Installation section


### What is the current behavior?
I find document link in repository description, but didn't find this in README.md.
So it is a little difficult to install PhpSpreadsheet for beginners.

**Comment by carotene4035** [comment]
issue 
https://github.com/PHPOffice/PhpSpreadsheet/issues/191

**Comment by komainu8** [comment]
振り返り完了しました！

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
