### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-07-29: ota: aasm: Work log

### ISSUE THREAD

**Issue by OtaYohihiro** [oss-gate/workshop#482]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by OtaYohihiro** [comment]
aasmで検索してみる！

**Comment by OtaYohihiro** [comment]
之が一番上に出てきたので、之のREADMEを読んで見る。
https://github.com/aasm/aasm

**Comment by Kohei909Otsuka** [comment]
一番上にでてくるやつ!

**Comment by nasum** [comment]
見てます！

**Comment by hiroyuki-sato** [comment]
よろしくおねがいします！

**Comment by takaya-fuj19** [comment]
よろしくお願いします。

**Comment by OtaYohihiro** [comment]
ReadMeを読んで見る。

**Comment by OtaYohihiro** [comment]
とりあえずUsageをirbで動かしてみよう。

**Comment by OtaYohihiro** [comment]
そりゃ動くな。。

**Comment by OtaYohihiro** [comment]
eventでstateが遷移していく。で。`may_#{event名}?`というメソッドが自動生成されて、今のstateで、そのeventが実行できるか判断されるようだ。

**Comment by OtaYohihiro** [comment]
whinyってなんだ。英語だと読むのちょっと面倒だなぁ。

**Comment by OtaYohihiro** [comment]
へー例外起こさないようにする事もできるんだ。面白いな。。

**Comment by OtaYohihiro** [comment]
英語のReadMeが長すぎるので、Qiitaを先に読もう。。
http://qiita.com/satton_maroyaka/items/fe838dc21dc95df95c62

**Comment by OtaYohihiro** [comment]
`When firing an event, you can pass a block to the method, it will be called only if the transition succeeds :`ここまで来たけど、挫折。。英語だったから読むのがちょっと面倒になってしまって、上のQiitaがそのまま和訳したReadMeみたいな感じのようなので。

**Comment by OtaYohihiro** [comment]
コールバックがいっぱい有ってわかりにくい。。

**Comment by OtaYohihiro** [comment]
一旦無視するか。

**Comment by OtaYohihiro** [comment]
ActiveRecordにも使えて、デフォルトだとcolumn名はaasm_stateっていうのを使うんだ。すごい。

**Comment by OtaYohihiro** [comment]
一通り読んだけど、、、これから何が問題かを探さないといけないんだなーーー困った。凄く色々改善されていてもう治す所ない気がする。

**Comment by OtaYohihiro** [comment]
んー実際にこのgemを使うサンプルソースを作ってみて、使い勝手で困ることないかを考えて見ると良いんだろうな。
出来上がっているものから粗を探すスタイルだとこのGemは不具合が見つけにくい気がする。もうVer4だしなー。

**Comment by nasum** [comment]
あるいは自分で最初からコードを書いてみて疑問に思うことを探すとか？

**Comment by OtaYohihiro** [comment]
そうですね。ちょっと自分で遷移図になるModelを考えてみようかと思いました。

**Comment by OtaYohihiro** [comment]
[牡蠣](http://soyat-info.com/%E9%9B%8C%E9%9B%84%E5%90%8C%E4%BD%93%E3%81%AE%E7%94%9F%E7%89%A9%E3%81%9F%E3%81%A1%EF%BC%81%E9%AD%9A%E3%81%A0%E3%81%A3%E3%81%A6%E6%80%A7%E8%BB%A2%E6%8F%9B%E3%81%99%E3%82%8B%EF%BC%81%EF%BC%9F-2809)

```
卵⇒子供⇒雌の大人 　　⇒ 中性の大人　⇒雌の大人　⇒　死
　　　　⇒雄の大人　　　　　　　　　  ⇒雄の大人
```

んーまぁ作ってみようか。

**Comment by OtaYohihiro** [comment]
```
Class Oyster
  include AASM
  aasm do
    state :egg, :initial => true
    state :child
    state :male_adult
    state :female_adult
    state :neutral_adult
    state :death

    event :birth do
      transitions :from => :egg,  :to => :child
    end

    event :grown_up do
      if 栄養豊富
        transitions :from => :child,  :to => :male_adult
      else
        transitions :from => :child,  :to => :female_adult
      end
    end

    event :lay_egg do
        transitions :from => [:female_adult, :male_adult],  :to => :neutral_adult
    end

    event :die do
        transitions :from => [:neutral_adult,:female_adult, :male_adult],  :to => :death
    end
  end

end
```
とりあえず途中ですが。

**Comment by OtaYohihiro** [comment]
- 今日の午前中で気づいた点だと(ソースは全然見れていないので)、ReadMeのレイアウトが少しわかりづらいなと思いました。
- なぜならReadMeは凄い充実していて良いのですが、文章が長く、IndexがReadMeの頭にあって、それぞれがリンクになっているとよりわかりやすいと思いました。イメージとしては下記です。

```
-  AASM - Ruby state machines
    - Upgrade from version 3 to 4
    - Usage
        - Callbacks
          - Lifecycle
          - The current event triggered
(以下略)
```

**Comment by OtaYohihiro** [comment]
- 上に書いたsisimaiのReadMeを見ていて気づきましたが、以下の要素も足りていなさそうです。
    - 対応ruby version。Localで確認すると1.9.3以上が必要
```
-> % gem install aasm
/Users/ota-yoshihiro/.rvm/gems/ruby-1.8.6-p420/gems/rubygems-bundler-1.1.1/lib/rubygems-bundler/regenerate_binstubs_command.rb:48: warning: parenthesize argument(s) for future version
ERROR:  Error installing aasm:
	concurrent-ruby requires Ruby version >= 1.9.3.
```

    - how to install

```
  gem install aasm
```

**Comment by OtaYohihiro** [comment]
- ReadMeにIndexを追加するとよいかと思います。
    - なぜなら、ReadMeが充実している分長くなっているので、目次が冒頭に有って、必要な部分へリンクでjump出来るようになっていると利便性が高いからです。
- System要件を追加したほうが良いかと思います。
    - Localでインストールを試みた所、`ERROR:  Error installing aasm:  concurrent-ruby requires Ruby version >= 1.9.3.`と表示されました。RubyのVersion以外にも要件有る場合は記載していただきたいです。

**Comment by OtaYohihiro** [comment]
- MarkDownのサンプルソースが有ったほうが良い。
- Issueは一つずつに分けたほうが良い！

**Comment by nasum** [comment]
こんなチートシートがあったりします
[GitHub English Challenge Cheat Sheet](http://qiita.com/kawasima/items/feac49a299213e2c8ba6)

**Comment by OtaYohihiro** [comment]
■■Issue 1：No Index in README■■
ASAM `README` is very substantial, but it is very long due to its substantiality.
I think it is better to add Index to `README.md` like this as below;


```
e.g)

## Index
- [Upgrade from version 3 to 4](https://github.com/aasm/aasm#upgrade-from-version-3-to-4)
- [Usage](https://github.com/aasm/aasm#usage)
    - [Callbacks](...)
      - [Lifecycle](...)
      - [The current event triggered](...)
....
```



■■Issue2：No system requirements in README■■
It may be better to add system requirements like ruby version and so on.
I try to install in my local and error: `ERROR:  Error installing aasm:  concurrent-ruby requires Ruby version >= 1.9.3.` happend.
Especially, since official support about Ruby ver1.9.3 has been already over,  it is helpful to describe supoort verision about Ruby.

**Comment by OtaYohihiro** [comment]
とりあえず出しました！後せっかくだからソース的な提案もやってみたいなー

**Comment by OtaYohihiro** [comment]
IssueのID
https://github.com/aasm/aasm/issues/486
https://github.com/aasm/aasm/issues/487

**Comment by selmertsx** [comment]
このOSSが参考になりそう
https://github.com/openresty/lua-nginx-module

**Comment by takaishi** [comment]
ふりかえりました！

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
