### ISSUE TITLE
  OSS Gate Workshop: Tokyo: 2017-07-29: kono: bricolage: Work log

### ISSUE THREAD

**Issue by kono** [oss-gate/workshop#483]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kono** [comment]
公式サイト(github)を開く。

**Comment by selmertsx** [comment]
サポーターやらせていただきます！
お願いします :bow:

**Comment by takaishi** [comment]
ボーダーシャツ野郎です！よろしくお願いします！

**Comment by carotene4035** [comment]
灰色シャツです。よろしくおねがいします〜

**Comment by banban9999** [comment]
斜め前の黒服です。よろしくお願いいたします！

**Comment by kono** [comment]
Readmeあっさりしすぎ。とりあえずダウンロードする。

**Comment by kono** [comment]
バッチ用のSQLを作ってくれるはずなので作ってみたい。

**Comment by kono** [comment]
docディレクトリがあったらよいのにない。

**Comment by kono** [comment]
https://github.com/bricolages/bricolageでdocディレクトリがない。

**Comment by kono** [comment]
ここには情報がなさそうに思った。

**Comment by kono** [comment]
% rake test
に何かヒントがあるか？

**Comment by kono** [comment]
実行してみたい。
(Windowsで大丈夫?)

**Comment by kono** [comment]
rakeはWindowsで動かせるか確認する。

**Comment by kono** [comment]
rakeの公式ドキュメントを調べる。

**Comment by kono** [comment]
googleでわかるのかな
公式ドキュメント https://docs.ruby-lang.org/ja/latest/library/rake.html

**Comment by selmertsx** [comment]
```
memo
```

**Comment by kono** [comment]
'''

'''
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\hiros>rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

C:\Users\hiros>
'''

rake本体は使えそうな感じ。

**Comment by kono** [comment]
実際にrake testをやってみる。

```
C:\Tools\bricolage-master>rake test
rake aborted!
LoadError: cannot load such file -- bricolage/jobclass
C:/Tools/bricolage-master/test/test_c_streaming_load.rb:2:in `<top (required)>'
C:/Tools/bricolage-master/test/all.rb:2:in `load'
C:/Tools/bricolage-master/test/all.rb:2:in `block in <top (required)>'
C:/Tools/bricolage-master/test/all.rb:1:in `each'
C:/Tools/bricolage-master/test/all.rb:1:in `<top (required)>'
C:/Tools/bricolage-master/Rakefile:2:in `load'
C:/Tools/bricolage-master/Rakefile:2:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)

C:\Tools\bricolage-master>
```
エラーになった。

**Comment by kono** [comment]
```
LoadError: cannot load such file -- bricolage/jobclass
```
がエラーの内容。
bricolageというディレクトリもない。

**Comment by kono** [comment]
どうすれば良い?  詰まったかも。

**Comment by kono** [comment]
Rakefileの中を見てみる。

```
task :test do
  load "#{__dir__}/test/all.rb"
end
```

**Comment by kono** [comment]
```
LoadError: cannot load such file -- bricolage/jobclass
C:/Tools/bricolage-master/test/test_c_streaming_load.rb:2:in `<top (required)>'
```
で問題の行は
```
require 'bricolage/jobclass'
```
```
C:\Tools\bricolage-master>tree
フォルダー パスの一覧:  ボリューム OS
ボリューム シリアル番号は 000000E0 14B0:0882 です
C:.
├─bin
├─jobclass
├─lib
│  └─bricolage
├─libexec
└─test
    └─home
        ├─data
        └─subsys
```
でjobclassディレクトリはあるので、この中をrequireできればエラーは解消できるのではないか?

**Comment by kono** [comment]
サポーターからヒントをもらって、
bundle installを実行した。
```
C:\Tools\bricolage-master>bundle install
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Fetching rake 12.0.0
Installing rake 12.0.0
Fetching aws-sigv4 1.0.1
Installing aws-sigv4 1.0.1
Fetching jmespath 1.3.1
Installing jmespath 1.3.1
Fetching mysql2 0.4.8 (x64-mingw32)
Installing mysql2 0.4.8 (x64-mingw32)
Fetching pg 0.18.4 (x64-mingw32)
Installing pg 0.18.4 (x64-mingw32)
Fetching redis 3.3.3
Installing redis 3.3.3
Using power_assert 1.0.2
Fetching coderay 1.1.1
Installing coderay 1.1.1
Fetching method_source 0.8.2
Installing method_source 0.8.2
Fetching slop 3.6.0
Installing slop 3.6.0
Fetching metaclass 0.0.4
Installing metaclass 0.0.4
Using bundler 1.15.1
Fetching aws-sdk-core 2.10.19
Installing aws-sdk-core 2.10.19
Using test-unit 3.2.5
Fetching pry 0.10.4
Installing pry 0.10.4
Fetching mocha 1.2.1
Installing mocha 1.2.1
Fetching aws-sdk-resources 2.10.19
Installing aws-sdk-resources 2.10.19
Fetching aws-sdk 2.10.19
Installing aws-sdk 2.10.19
Using bricolage 5.24.2 from source at `.`
Bundle complete! 5 Gemfile dependencies, 19 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from mysql2:

======================================================================================================

  You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.10.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:
  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.10-win32.zip

  This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/README.

======================================================================================================


C:\Tools\bricolage-master>
```

bincolage.gemspecの内容が

```
require_relative 'lib/bricolage/version'

Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.name = 'bricolage'
  s.version = Bricolage::VERSION
  s.summary = 'SQL Batch Framework'
  s.description = 'Redshift-oriented Data Warehouse Batch Framework'
  s.license = 'MIT'

  s.author = ['Minero Aoki']
  s.email = 'aamine@loveruby.net'
  s.homepage = 'https://github.com/aamine/bricolage'

  s.executables = Dir.entries('bin').select {|ent| File.file?("bin/#{ent}") }
  s.files = Dir.glob(['README.md', 'bin/*', 'lib/**/*.rb', 'libexec/**/*', 'jobclass/*.rb', 'test/**/*'])
  s.require_path = 'lib'

  s.required_ruby_version = '>= 2.0.0'
  s.add_dependency 'pg', '~> 0.18.0'
  s.add_dependency 'aws-sdk', '~> 2'
  s.add_dependency 'mysql2'
  s.add_dependency 'redis', ">= 3.0.0"
  s.add_development_dependency 'test-unit'
  s.add_development_dependency 'pry'
  s.add_development_dependency 'rake'
  s.add_development_dependency 'mocha'
end
```
で、今の自分にはうまく読めない。

**Comment by kono** [comment]
‘‘‘
C:\Tools\bricolage-master>bundle exec rake test
rake aborted!
LoadError: cannot load such file -- 2.3/pg_ext
C:/Tools/bricolage-master/lib/bricolage/postgresconnection.rb:2:in `require'
C:/Tools/bricolage-master/lib/bricolage/postgresconnection.rb:2:in `<top (required)>'
C:/Tools/bricolage-master/lib/bricolage/psqldatasource.rb:5:in `require'
C:/Tools/bricolage-master/lib/bricolage/psqldatasource.rb:5:in `<top (required)>'
C:/Tools/bricolage-master/jobclass/streaming_load.rb:2:in `require'
C:/Tools/bricolage-master/jobclass/streaming_load.rb:2:in `get'
C:/Tools/bricolage-master/lib/bricolage/jobclass.rb:42:in `module_eval'
C:/Tools/bricolage-master/lib/bricolage/jobclass.rb:42:in `get'
C:/Tools/bricolage-master/test/test_c_streaming_load.rb:3:in `<top (required)>'
C:/Tools/bricolage-master/test/all.rb:2:in `load'
C:/Tools/bricolage-master/test/all.rb:2:in `block in <top (required)>'
C:/Tools/bricolage-master/test/all.rb:1:in `each'
C:/Tools/bricolage-master/test/all.rb:1:in `<top (required)>'
C:/Tools/bricolage-master/Rakefile:2:in `load'
C:/Tools/bricolage-master/Rakefile:2:in `block in <top (required)>'
LoadError: cannot load such file -- pg_ext
C:/Tools/bricolage-master/lib/bricolage/postgresconnection.rb:2:in `require'
C:/Tools/bricolage-master/lib/bricolage/postgresconnection.rb:2:in `<top (required)>'
C:/Tools/bricolage-master/lib/bricolage/psqldatasource.rb:5:in `require'
C:/Tools/bricolage-master/lib/bricolage/psqldatasource.rb:5:in `<top (required)>'
C:/Tools/bricolage-master/jobclass/streaming_load.rb:2:in `require'
C:/Tools/bricolage-master/jobclass/streaming_load.rb:2:in `get'
C:/Tools/bricolage-master/lib/bricolage/jobclass.rb:42:in `module_eval'
C:/Tools/bricolage-master/lib/bricolage/jobclass.rb:42:in `get'
C:/Tools/bricolage-master/test/test_c_streaming_load.rb:3:in `<top (required)>'
C:/Tools/bricolage-master/test/all.rb:2:in `load'
C:/Tools/bricolage-master/test/all.rb:2:in `block in <top (required)>'
C:/Tools/bricolage-master/test/all.rb:1:in `each'
C:/Tools/bricolage-master/test/all.rb:1:in `<top (required)>'
C:/Tools/bricolage-master/Rakefile:2:in `load'
C:/Tools/bricolage-master/Rakefile:2:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)

C:\Tools\bricolage-master>
‘‘‘

**Comment by kono** [comment]
自分には難しい。。

**Comment by kono** [comment]
```
Fetching pg 0.18.4 (x64-mingw32)
Installing pg 0.18.4 (x64-mingw32)
```
インストールうまく行ってないのかも

**Comment by kono** [comment]
```
C:\Tools\bricolage-master>bundle info pg
  * pg (0.18.4)
        Summary: Pg is the Ruby interface to the {PostgreSQL RDBMS}[http://www.postgresql.org/]
        Homepage: https://bitbucket.org/ged/ruby-pg
        Path: C:/Tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/pg-0.18.4-x64-mingw32
```
pgは入っている感じ。

```
C:\Tools\bricolage-master>irb
irb(main):001:0> require 'pg'
LoadError: cannot load such file -- 2.3/pg_ext
        from C:/Tools/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/pg-0.18.4-x64-mingw32/lib/pg.rb:14:in `rescue in <top (required)>'
        from C:/Tools/Ruby23-x64/lib/ruby/gems/2.3.0/gems/pg-0.18.4-x64-mingw32/lib/pg.rb:3:in `<top (required)>'
        from C:/Tools/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Tools/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Tools/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from C:/Tools/Ruby23-x64/bin/irb.cmd:19:in `<main>'
irb(main):002:0>
```

**Comment by kono** [comment]
pg入ってない。

**Comment by kono** [comment]
pg(gem)のドキュメントを調べる。

**Comment by kono** [comment]
pgはpostgresqlに接続するためのgemらしい。
https://github.com/ged/ruby-pg/blob/master/README.rdoc
Windowsは特別なインストール方法が必要な模様。
https://github.com/ged/ruby-pg/blob/master/README-Windows.rdoc

**Comment by kono** [comment]
In order to build this extension on MS Windows you will need a couple things.

First, a compiler. For the one click installer this means you should use the DevKit or the compiler that comes with cygwin if you're building on that platform.

If you've built Ruby yourself, you should use the same compiler to build this library that you used to build Ruby.

Second, PostgreSQL. Be sure you installed it with the development header files if you installed it using the standard PostgreSQL installer for Windows. If you didn't, you can run the installer again, select “modify”, and then select the 'development headers' option to install them.

DevKitはインストール済のはずなのでPostgreSQLをインストールする必要がありそう。

**Comment by kono** [comment]
https://teratail.com/questions/37195
に記述あり。

>Windows向けのpg Gemには、あらかじめWindowsのRuby向けにコンパイルされたバイナリのランタイムが付属していますが、これがRuby 2.2用までしかないので、Ruby 2.3ではエラーとなってしまします。

>自力でコンパイルするには、PostgreSQLの開発用ヘッダーをインストール、またはそれを入れたDocker上でコンパイルするなど面倒な手順が必要となります（Gem添付のREADME-Windows.rdocを御覧ください）。

>そこまでするだけの技量がないなら、Ruby 2.2に戻すのが手っ取り早いです。

```
C:\Tools\bricolage-master>ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
```
rubyが新しすぎた。。

**Comment by kou** [comment]
ふりかえりデモをしました！

**Comment by kono** [comment]
https://github.com/bricolages/bricolage/wiki
に詳しい説明があったのに全然きづかなかった。

**Comment by kono** [comment]
wikiにもインストール方法は書いていない...

**Comment by kono** [comment]
自分の気持ちとしては、まずreadmeがあまりに素っ気なくて
```
rake test
```
しか書いていないので、wikiへのリンクがあると嬉しい。
(wikiには日本語しか書いていないので英語のResdmeからは敢えて
リンクを張っていないのかもしれないが)

**Comment by kono** [comment]
知りたかったこと: インストール方法
試したこと: githubからzipでダウンロードして展開し、rake testを実行してみた。
環境: windows10 ruby2.3
その後、bundle install  bundle rake testを実行し、pg gemがうまくインストールできていないところまでわかった。
なぜrake testしたか?  バッチ用のsqlファイルを何か作ってみたかったがやり方がわからず、readmeにrake testとあったので実行してみると何かヒントがわかるかと思った。
何があったら解決したか: インストールの手順と、サンプルプロジェクトのようなもの

**Comment by kono** [comment]
使ってみたかった。

**Comment by kono** [comment]
SQLバッチを楽に作るために、bricolageを使ってみようと思って
githubからダウンロードしてみました。
インストールしようと思ってreadmeを見たところ、rake testとしかなかったので
実行したら何かヒントがあるのかと思って実行してみました(エラーになりました)。
その後、github上のwikiに気がついて、そちらに使い方が書いてあることが判りました。
wikiに気づくまで数時間かかりました。
readmeにwikiへのリンクがあるとより親切なように思います。

**Comment by kono** [comment]
仕事でDWHのメンテを担当していて、大量のSQLバッチを効率よく作りたいと
思っていたところ、briclageのことを知り、試してみようと思いました。
readmeを見ても使い方の情報がなくて、いろいろ試しているうちに、
githubのwikiに使い方のドキュメントがあることに気がつきました
(恥ずかしながらここまで2時間かかりました)。
readmeにもこのwikiへのリンクがあるともっと素晴らしかったと思います。

**Comment by kono** [comment]
issue
https://github.com/bricolages/bricolage/issues/97

**Comment by kono** [comment]
pull request
https://github.com/bricolages/bricolage/pull/98

**Comment by komainu8** [comment]
振り返り完了しました！

**Comment by selmertsx** [comment]
forkして、PR作るまではこれがよくまとまってます！

https://github.com/nginxinc/nginx-wiki/blob/master/source/contributing/github.rst#forking

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
