### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-07-19: takaya.fuj19: chef: Work log

### ISSUE THREAD

**Issue by takaya-fuj19** [oss-gate/workshop#484]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nasum** [comment]
見てます！

**Comment by OtaYohihiro** [comment]
太田です、よろしくお願いします！

**Comment by Kohei909Otsuka** [comment]
大塚です:)　お願いします。

**Comment by hiroyuki-sato** [comment]
佐藤です。よろしくお願いします！

**Comment by takaya-fuj19** [comment]
Chefのsiteを検索。
Gitのsiteを見つけた。https://github.com/chef/chef

**Comment by takaya-fuj19** [comment]
README.mdを読む。

**Comment by takaya-fuj19** [comment]
Gitからのinstall方法を読む。

**Comment by takaya-fuj19** [comment]
git clone https://github.com/chef/chef.git
cd chef
bundle install
bundle exec rake gem
bundle exec rake install

**Comment by takaya-fuj19** [comment]
bundle installでpasswordを訊かれた。

**Comment by takaya-fuj19** [comment]
sudoで入れるpasswordを入れることで継続できた。

**Comment by takaya-fuj19** [comment]
bundle installでfail。rubyのversionが古いため。2.3.3でないとだめ。

**Comment by takaya-fuj19** [comment]
Installing winrm 2.2.3
Using chefstyle 0.6.0 from https://github.com/chef/chefstyle.git (at master@5b59b52)
Installing cheffish 13.0.0

Gem::InstallError: cheffish requires Ruby version >= 2.3.3.
Installing serverspec 2.39.1
Installing travis 1.8.8
Installing octokit 4.7.0
Installing winrm-fs 1.0.1
An error occurred while installing cheffish (13.0.0), and Bundler cannot continue.
Make sure that `gem install cheffish -v '13.0.0'` succeeds before bundling.
takaya@ubuntu-vm:~/chef$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by takaya-fuj19** [comment]
必要な条件が前に書いてあった。
Prerequisites

Install:

    git
    C compiler, header files, etc.
    ruby 2.3.3 or later
    rubygems
    bundler gem

**Comment by takaya-fuj19** [comment]
rbenvを使って、rubyを2.3.4へupgrade.

**Comment by takaya-fuj19** [comment]
bundle installを実施。
結果、以下のメッセージが表示された。
As of YARD v0.9.2:

RubyGems "--document=yri,yard" hooks are now supported. You can auto-configure
YARD to automatically build the yri index for installed gems by typing:

    $ yard config --gem-install-yri

See `yard config --help` for more information on RubyGems install hooks.

You can also add the following to your .gemspec to have YARD document your gem
on install:

    spec.metadata["yard.run"] = "yri" # use "yard" to build full HTML docs.

--------------------------------------------------------------------------------

**Comment by takaya-fuj19** [comment]
簡単に動くサンプルが見たらない。

**Comment by takaya-fuj19** [comment]
Quick Startのlinkを見つける。
https://docs.chef.io/quick_start.html

**Comment by takaya-fuj19** [comment]
- README.mdの"Installing From Git"に従ってinstallしたが、Installが正しく出来たか確認する方法が、README.mdには書かれていない。

- 実施したinstall手順:
git clone https://github.com/chef/chef.git
cd chef
bundle install
bundle exec rake gem
bundle exec rake install

- Quick Startsのpageを見つけたが、Chef DKのbinary packageのinstallが必要となるもので、
sourceからinstallした場合の確認方法がないように見える。
https://docs.chef.io/quick_start.html

**Comment by takaya-fuj19** [comment]
- README.mdが、User用とDeveloper用を明確に分けて書いてあった方がわかりやすい。
例えば、最初にUser用にGetting Startedの項目があって、Installing From Git項目にはfor Developerを付ける。
- UserのためのGetting Startedとして、以下のlinkを載せておく方がわかりやすい。
https://docs.chef.io/quick_start.html

**Comment by takaya-fuj19** [comment]
It is better to divide User and Developer instructions clearly in README.md.
For example,

- Add "Getting Started" section for User
- Change "Installing From Git" section to "Installing From Git for Developers"

It is easy to understand to add the following link to "Getting Started" as the reference for User.
https://docs.chef.io/quick_start.html

**Comment by takaishi** [comment]
ふりかえりました！

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
