### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-7-29: RyoYokoyama: Atom-package-jumpy: Work log

### ISSUE THREAD

**Issue by RyoYokoyama** [oss-gate/workshop#485]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tomo667a** [comment]
サポーターのかとうです

**Comment by hisamura333** [comment]
ひさむらです！

**Comment by RyoYokoyama** [comment]
公式ページ見る

**Comment by RyoYokoyama** [comment]
最終更新がひと月前。結構最近

**Comment by RyoYokoyama** [comment]
ReadMe見る

**Comment by RyoYokoyama** [comment]
動作の説明が動画付きでわかりやすい

**Comment by RyoYokoyama** [comment]
Issueは13件。PRはopenされてるのが5件。closeされてるのが9件

**Comment by RyoYokoyama** [comment]
こんなきちんとREADME読んだことないわ

**Comment by RyoYokoyama** [comment]
設定で色変えたりできるの知らんかった

**Comment by RyoYokoyama** [comment]
必要十分な構成でわかりやすいREADME

**Comment by RyoYokoyama** [comment]
と言ったそばから、
Use Homing Beacon Effect On Jumps: If left on, will display a homing beacon (usually red) after all jumps.
これ何する機能かわからん。

**Comment by RyoYokoyama** [comment]
SEO用にキーワード羅列してるのすごい。

**Comment by RyoYokoyama** [comment]
他にもatomパッケージ作っててそれも紹介してる。

**Comment by RyoYokoyama** [comment]
インストールしよ。

**Comment by RyoYokoyama** [comment]
```apm install jumpy```

**Comment by RyoYokoyama** [comment]
![image](https://user-images.githubusercontent.com/16218220/28741551-605d0cee-7453-11e7-90b7-363a8ace4a4b.png)

**Comment by RyoYokoyama** [comment]
できたっぽい。

**Comment by RyoYokoyama** [comment]
atom起動する

**Comment by RyoYokoyama** [comment]
パッケージ一覧見る

**Comment by RyoYokoyama** [comment]
![image](https://user-images.githubusercontent.com/16218220/28741565-d533744a-7453-11e7-97ab-1e085034f959.png)

**Comment by RyoYokoyama** [comment]
インストールされてた

**Comment by RyoYokoyama** [comment]
apm installだけじゃなくて、atom上からも検索できるよね。

**Comment by RyoYokoyama** [comment]
っていうか似たようなジャンプ機能のパッケージいっぱいあるんだな。

![image](https://user-images.githubusercontent.com/16218220/28741579-3001f432-7454-11e7-9017-85384c0432b7.png)

**Comment by RyoYokoyama** [comment]
使ってみる

**Comment by RyoYokoyama** [comment]
ちゃんとshift + enterでジャンプ先が出て来た

**Comment by RyoYokoyama** [comment]
ジャンプ先入力した時になんか赤いの出てくるの何。

**Comment by RyoYokoyama** [comment]
ハイライト設定でグリーンに。

**Comment by RyoYokoyama** [comment]
![image](https://user-images.githubusercontent.com/16218220/28741620-3d6e4c32-7455-11e7-91ff-e03b1c090613.png)

**Comment by RyoYokoyama** [comment]
ハイライトの色、atomのスタイルシートいじらないと変えられないのか。設定ページから変えられると楽。

**Comment by RyoYokoyama** [comment]
あああああ、ジャンプ後に赤い光みたいなのでるのがREADMEでわからんかった説明の機能か。。

**Comment by RyoYokoyama** [comment]
設定ページに書いてある説明の方がREADMEよりわかりやすい。

![image](https://user-images.githubusercontent.com/16218220/28741644-dc4cd6a2-7455-11e7-9283-722bc43d4779.png)

**Comment by RyoYokoyama** [comment]
HomingBeaconEffectはなんのためにあんの。おしゃれ？

**Comment by RyoYokoyama** [comment]
READMEの説明動画で一瞬出てた。。気がつかないというか、READMEの説明と紐付かなかった。

**Comment by RyoYokoyama** [comment]
shift + enter した時にカーソルキーが使えないの不便。ジャンプ先が出たままで画面スクロールしたいときがある。

**Comment by RyoYokoyama** [comment]
けど、とりあえず便利。

**Comment by RyoYokoyama** [comment]
コーディング捗る。

**Comment by RyoYokoyama** [comment]
![image](https://user-images.githubusercontent.com/16218220/28741721-c9b2520e-7457-11e7-91e2-42e84a20aa16.png)

**Comment by RyoYokoyama** [comment]
一般的な用語じゃないからわからんかったわ。。

**Comment by RyoYokoyama** [comment]
HomingBeaconEffectの機能が何をする機能なのかがREADME上でわかりにくかった。
Settingsの箇所にキャプチャ画像があるとわかりやすいです。

**Comment by RyoYokoyama** [comment]
To dev:
READMEにHomingBeaconの機能説明があるが、HomingBeaconが何を示すのかがわかりませんでした。HomingBeaconの機能説明の箇所にキャプチャ画像があるとわかりやすいと思います。

**Comment by RyoYokoyama** [comment]
I couldn`t understand the function of "HomingBeaconEffect" when I read description of "Use Homing Beacon Effect On Jumps" in README.
So,  I expect you to add the capture image of "HomingBeaconEffect" at Example to understand clearly.

**Comment by RyoYokoyama** [comment]
contribute.mdが無い。。どうやってFBすれば良いのかな

**Comment by RyoYokoyama** [comment]
issuesにquestionラベルがある！他の人もissueで質問しているのでissue投げるわ

**Comment by RyoYokoyama** [comment]
issue投げました。

**Comment by RyoYokoyama** [comment]
README.md編集してPR投げちゃおうか

**Comment by tomo667a** [comment]
pull request から issue をクローズする方法 https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
