### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-07-29: hori031617: React: Work log

### ISSUE THREAD

**Issue by hori031617** [oss-gate/workshop#487]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hori031617** [comment]
Reactで検索。

**Comment by hori031617** [comment]
公式サイトを見つけた。
https://facebook.github.io/react/

**Comment by hori031617** [comment]
公式サイトを読む。

**Comment by komainu8** [comment]
よろしくお願いします。

**Comment by KimiakiKinugasa** [comment]
よろしくお願いします

**Comment by cuon-kakimoto** [comment]
頑張りましょう！

**Comment by freddiefujiwara** [comment]
https://github.com/oss-gate/workshop/issues/480 の freddiefujiwaraで　よろしくお願いします

**Comment by hori031617** [comment]
Docsを見る。
https://facebook.github.io/react/docs/hello-world.html

**Comment by hori031617** [comment]
Tutorialをやってみる。
https://facebook.github.io/react/tutorial/tutorial.html

**Comment by hori031617** [comment]
Tutorialに貼ってあった、動作確認を行うためのリンクを開く。
https://codepen.io/gaearon/pen/oWWQNa?editors=0010

**Comment by hori031617** [comment]
Node.js をインストールする。
https://nodejs.org/en/

**Comment by hori031617** [comment]
node v6.11.1 LTS をインストールする。

**Comment by hori031617** [comment]
インストール完了。

Node.js was installed at

   /usr/local/bin/node

npm was installed at

   /usr/local/bin/npm

Make sure that /usr/local/bin is in your $PATH.

**Comment by hori031617** [comment]
インストール自体は画面からボタンを押すだけで簡単にできた。

**Comment by hori031617** [comment]
create-react-appを下記コマンドでインストール。
npm install -g create-react-app

**Comment by hori031617** [comment]
エラーになった。

horimasahiro@MacBook-Air-2:~/oss$ npm install -g create-react-app
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-app"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! path ../lib/node_modules/create-react-app/index.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/create-react-app/index.js' -> '/usr/local/bin/create-react-app'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '../lib/node_modules/create-react-app/index.js' -> '/usr/local/bin/create-react-app'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/create-react-app/index.js',
npm ERR!   dest: '/usr/local/bin/create-react-app' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/horimasahiro/oss/npm-debug.log

**Comment by hori031617** [comment]
>npm ERR! Please try running this command again as root/Administrator.
とあったので、rootでコマンドを実行してみる。

**Comment by hori031617** [comment]
horimasahiro@MacBook-Air-2:~/oss$ sudo npm install -g create-react-app
Password:
/usr/local/bin/create-react-app -> /usr/local/lib/node_modules/create-react-app/index.js
/usr/local/lib
└─┬ create-react-app@1.3.3 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├── commander@2.11.0 
  ├─┬ cross-spawn@4.0.2 
  │ ├─┬ lru-cache@4.1.1 
  │ │ ├── pseudomap@1.0.2 
  │ │ └── yallist@2.1.2 
  │ └─┬ which@1.2.14 
  │   └── isexe@2.0.0 
  ├─┬ fs-extra@1.0.0 
  │ ├── graceful-fs@4.1.11 
  │ ├── jsonfile@2.4.0 
  │ └── klaw@1.3.1 
  ├─┬ hyperquest@2.1.2 
  │ ├─┬ buffer-from@0.1.1 
  │ │ └─┬ is-array-buffer-x@1.3.0 
  │ │   ├─┬ has-to-string-tag-x@1.4.0 
  │ │   │ └── has-symbol-support-x@1.4.0 
  │ │   ├─┬ is-object-like-x@1.3.0 
  │ │   │ ├── is-function-x@1.4.0 
  │ │   │ └── is-primitive@2.0.0 
  │ │   └─┬ to-string-tag-x@1.4.0 
  │ │     ├── lodash.isnull@3.0.0 
  │ │     └── validate.io-undefined@1.0.3 
  │ ├─┬ duplexer2@0.0.2 
  │ │ └─┬ readable-stream@1.1.14 
  │ │   ├── isarray@0.0.1 
  │ │   └── string_decoder@0.10.31 
  │ └─┬ through2@0.6.5 
  │   ├── readable-stream@1.0.34 
  │   └── xtend@4.0.1 
  ├── semver@5.4.1 
  ├─┬ tar-pack@3.4.0 
  │ ├─┬ debug@2.6.8 
  │ │ └── ms@2.0.0 
  │ ├─┬ fstream@1.0.11 
  │ │ ├── inherits@2.0.3 
  │ │ └─┬ mkdirp@0.5.1 
  │ │   └── minimist@0.0.8 
  │ ├─┬ fstream-ignore@1.0.5 
  │ │ └─┬ minimatch@3.0.4 
  │ │   └─┬ brace-expansion@1.1.8 
  │ │     ├── balanced-match@1.0.0 
  │ │     └── concat-map@0.0.1 
  │ ├─┬ once@1.4.0 
  │ │ └── wrappy@1.0.2 
  │ ├─┬ readable-stream@2.3.3 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── isarray@1.0.0 
  │ │ ├── process-nextick-args@1.0.7 
  │ │ ├── safe-buffer@5.1.1 
  │ │ ├── string_decoder@1.0.3 
  │ │ └── util-deprecate@1.0.2 
  │ ├─┬ rimraf@2.6.1 
  │ │ └─┬ glob@7.1.2 
  │ │   ├── fs.realpath@1.0.0 
  │ │   ├── inflight@1.0.6 
  │ │   └── path-is-absolute@1.0.1 
  │ ├─┬ tar@2.2.1 
  │ │ └── block-stream@0.0.9 
  │ └── uid-number@0.0.6 
  ├─┬ tmp@0.0.31 
  │ └── os-tmpdir@1.0.2 
  └─┬ validate-npm-package-name@3.0.0 
    └── builtins@1.0.3

**Comment by hori031617** [comment]
horimasahiro@MacBook-Air-2:~/oss$ which create-react-app
/usr/local/bin/create-react-app

インストール成功。

**Comment by hori031617** [comment]
ドキュメントにrootで実行の旨を記載していた方がいいと感じた。

**Comment by hori031617** [comment]
プロジェクトを下記コマンドで作成。
create-react-app my-app

**Comment by hori031617** [comment]
プロジェクト作成成功。

horimasahiro@MacBook-Air-2:~/oss$ create-react-app my-app
Creating a new React app in /Users/horimasahiro/oss/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...


> fsevents@1.1.2 install /Users/horimasahiro/oss/my-app/node_modules/fsevents
> node install

[fsevents] Success: "/Users/horimasahiro/oss/my-app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
my-app@0.1.0 /Users/horimasahiro/oss/my-app

**Comment by hori031617** [comment]
>cd my-app
>npm start

上記コマンドを実行。

**Comment by hori031617** [comment]
ローカルサーバーが起動し、ブラウザに表示された。

Compiled successfully!

You can now view my-app in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.0.87:3000/

Note that the development build is not optimized.
To create a production build, use npm run build.

**Comment by hori031617** [comment]
ローカルサーバーのURL。

http://localhost:3000/

**Comment by hori031617** [comment]
READMEのリンクがあったのでREADMEを読む。

https://github.com/facebookincubator/create-react-app#create-react-app-

**Comment by hori031617** [comment]
User Guideを読む。

https://github.com/facebookincubator/create-react-app#create-react-app-

**Comment by hori031617** [comment]
User Guideはボリュームも多くさらに英語なので中項目ぐらいまでの内容を確認。。

**Comment by hori031617** [comment]
>Delete all files in the src/ folder of the new project.

チュートリアルに従い、上記を実行。

**Comment by hori031617** [comment]
-rw-r--r--    1 horimasahiro  staff  104074  7 29 11:50 README.md
drwxr-xr-x  880 horimasahiro  staff   29920  7 29 11:53 node_modules
-rw-r--r--    1 horimasahiro  staff     343  7 29 11:50 package.json
drwxr-xr-x    5 horimasahiro  staff     170  7 29 11:50 public
drwxr-xr-x    9 horimasahiro  staff     306  7 29 11:50 src
horimasahiro@MacBook-Air-2:~/oss/my-app$ rm -fR src
horimasahiro@MacBook-Air-2:~/oss/my-app$ ls -l
total 216
-rw-r--r--    1 horimasahiro  staff  104074  7 29 11:50 README.md
drwxr-xr-x  880 horimasahiro  staff   29920  7 29 11:53 node_modules
-rw-r--r--    1 horimasahiro  staff     343  7 29 11:50 package.json
drwxr-xr-x    5 horimasahiro  staff     170  7 29 11:50 public

削除実行。

**Comment by hori031617** [comment]
>Add a file named index.css in the src/ folder with this CSS code.

チュートリアルに従い、index.cssをsrcディレクトリ配下に作成。
(srcディレクトリは削除する必要はなく、src配下のファイルを削除でよかった。)

**Comment by hori031617** [comment]
horimasahiro@MacBook-Air-2:~/oss/my-app$ mkdir src
horimasahiro@MacBook-Air-2:~/oss/my-app$ ls -l
total 216
-rw-r--r--    1 horimasahiro  staff  104074  7 29 11:50 README.md
drwxr-xr-x  880 horimasahiro  staff   29920  7 29 11:53 node_modules
-rw-r--r--    1 horimasahiro  staff     343  7 29 11:50 package.json
drwxr-xr-x    5 horimasahiro  staff     170  7 29 11:50 public
drwxr-xr-x    2 horimasahiro  staff      68  7 29 12:13 src
horimasahiro@MacBook-Air-2:~/oss/my-app$ cd src
horimasahiro@MacBook-Air-2:~/oss/my-app/src$ touch index.css
horimasahiro@MacBook-Air-2:~/oss/my-app/src$ ls -l
total 0
-rw-r--r--  1 horimasahiro  staff  0  7 29 12:13 index.css

index.cssファイルを作成。

**Comment by hori031617** [comment]
vi index.css
サンプルコードを貼り付け。

**Comment by hori031617** [comment]
https://facebook.github.io/react/tutorial/tutorial.html
チュートリアルにある、
>3. Delete all files in the src/ folder of the new project.
上記手順を行う実行コード例があればいいと思った。

**Comment by hori031617** [comment]
> 3. Delete all files in the src/ folder of the new project.

I think that good example code here.
Because, I had a misunderstanding remove src directory.

**Comment by hori031617** [comment]
[Documentation] Tutorial example code write

**Comment by hori031617** [comment]
https://github.com/facebook/react/issues/10323

**Comment by hori031617** [comment]
`npm install -g create-react-app`
上記コマンドには管理者権限が必要。
従って、管理者権限で実行する必要がある説明と実行例があればいいと思う。

**Comment by hori031617** [comment]
`npm install -g create-react-app`
This command need administrator authority.
So, I think that good explan for do command by administrator authority.

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
