### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-07-29: hisamura333: Rails: Work log

### ISSUE THREAD

**Issue by hisamura333** [oss-gate/workshop#488]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hisamura333** [comment]
まず調べてみよ

**Comment by tomo667a** [comment]
サポーターのかとうです

**Comment by RyoYokoyama** [comment]
よろしくお願いします

**Comment by hisamura333** [comment]
http://rubyonrails.org/
これを調べる

**Comment by hisamura333** [comment]
公式のやつ↑

**Comment by hisamura333** [comment]
なんとなく top ページを眺める

**Comment by hisamura333** [comment]
guideを読んでみよ

**Comment by hisamura333** [comment]
http://guides.rubyonrails.org/

**Comment by hisamura333** [comment]
いろいろ書いてあるので、とりあえず start hereを読んでみる
http://guides.rubyonrails.org/getting_started.html

**Comment by hisamura333** [comment]
読むのが大変

**Comment by hisamura333** [comment]
1 Guide Assumptions　をとりあえずざっとみる

**Comment by hisamura333** [comment]
ruby のリンクはスルーしとく

**Comment by hisamura333** [comment]
なんやら version のことがちらほら

**Comment by hisamura333** [comment]
2 What is Rails?をよむ

**Comment by hisamura333** [comment]
rails 便利ということが書いてある

**Comment by hisamura333** [comment]
http://guides.rubyonrails.org/getting_started.html

**Comment by hisamura333** [comment]
The Rails philosophy includes two major guiding principles:
 大事そう　もっと強調してあっても

**Comment by hisamura333** [comment]
3 Creating a New Rails Projectよむ

**Comment by hisamura333** [comment]
最良の方法は以下の内容らしい

**Comment by hisamura333** [comment]
やってみるか

**Comment by hisamura333** [comment]
3.1 Installing Railsから始まる

**Comment by hisamura333** [comment]
command走らせって

**Comment by hisamura333** [comment]
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by hisamura333** [comment]
sqlite3 --version

**Comment by hisamura333** [comment]
gem install rails

**Comment by hisamura333** [comment]
rails --version
Rails 5.1.2

できたっぽい

**Comment by hisamura333** [comment]
3.2 Creating the Blog Applicationに移る

**Comment by hisamura333** [comment]
自動で生成してやる的な内容

**Comment by hisamura333** [comment]
$ rails new blog

**Comment by hisamura333** [comment]
新しいapp を作成するのか

**Comment by hisamura333** [comment]
cd blog

 ざっくりと書いてある感じが、初めだとわからんだろうな

**Comment by hisamura333** [comment]
cd の説明するのもあれだけど、以外とわからん人もいるかも

**Comment by hisamura333** [comment]
わかるもんだな普通なら

**Comment by hisamura333** [comment]
次に folder の説明があるのはいいな

**Comment by hisamura333** [comment]
初めて読んだけど、これ通りやってちゃんとなんでやらなかったかな

**Comment by hisamura333** [comment]
4 Hello, Rails!
コードを書く感じか

**Comment by hisamura333** [comment]
bin/rails server
サーバー動かすぜ

**Comment by hisamura333** [comment]
![image](https://user-images.githubusercontent.com/22094892/28741668-845593de-7456-11e7-8bff-a4fd08003562.png)

**Comment by hisamura333** [comment]
止め方も書いてある

**Comment by hisamura333** [comment]
4.2 Say "Hello", Railsよむ

**Comment by hisamura333** [comment]
you need to create at minimum a controller and a view.らしい

**Comment by RyoYokoyama** [comment]
公式サイトのTOPページでインストール方法が簡単に見つけられなかった。。

**Comment by RyoYokoyama** [comment]
最新Releaseのリンク見たいな目立つようなリンクでインストール方法を書いて欲しかったなー

**Comment by RyoYokoyama** [comment]
![image](https://user-images.githubusercontent.com/16218220/28741880-a856b11e-745b-11e7-944b-4a16d3d8fcb6.png)

**Comment by RyoYokoyama** [comment]
![image](https://user-images.githubusercontent.com/16218220/28741884-ba269fbc-745b-11e7-8e9b-a87e4cc4ba05.png)

**Comment by RyoYokoyama** [comment]
rubyのバージョン古い

**Comment by RyoYokoyama** [comment]
振り返ったよ！

**Comment by hisamura333** [comment]
公式サイトのTOPページにインストール方法を簡単に見つけやすくするための ボタンを配置したい。（Latest version のような）

 guideや you can learn it のようなリンクからインストールに辿ることはできるが、インストールをしたいという明確な理由を持ったユーザーのために、「インストール」のボタンを配置。

**Comment by hisamura333** [comment]
公式サイトのTOPページにインストール方法を簡単に見つけやすくするためのボタンを配置したい。（Latest version のような）

guidesや you can learn it のようなリンクからインストールに辿ることはできるが、気がつきににくい。
インストールをしたいという明確な理由を持ったユーザーのために、「インストール」のボタンを配置。

**Comment by hisamura333** [comment]
i want to add "install button"

i can get install information from "guides" and "you can learn it ", but it is not easy.
i want to add "install button" for user who want to install only.

**Comment by hisamura333** [comment]
https://github.com/rails/rails/blob/master/CONTRIBUTING.md
ここからフィードバック先を調べる

**Comment by hisamura333** [comment]
contribute しようとサイトを見てもなかなか見つけらなかったな。
それも問題かな。

**Comment by hisamura333** [comment]
https://github.com/rails/homepage/issues/88
イシュー投げました！

**Comment by tomo667a** [comment]
pull request から issue をクローズする方法 https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
