### ISSUE TITLE
OSS Gate Workshop: tokyo: 2017-07-29: KimiakiKinugasa:  cygwin: Work log

### ISSUE THREAD

**Issue by KimiakiKinugasa** [oss-gate/workshop#489]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by KimiakiKinugasa** [comment]
cygwin で検索

**Comment by KimiakiKinugasa** [comment]
https://cygwin.com/licensing.html が一番上にでた

**Comment by komainu8** [comment]
よろしくお願いします。

**Comment by cuon-kakimoto** [comment]
柿本: よろしくお願いします。

**Comment by hori031617** [comment]
よろしくお願いします。

**Comment by freddiefujiwara** [comment]
https://github.com/oss-gate/workshop/issues/480 の freddiefujiwaraで　よろしくお願いします

**Comment by KimiakiKinugasa** [comment]
ユーザーガイドを見つけたので読む
https://cygwin.com/cygwin-ug-net/cygwin-ug-net.html

**Comment by KimiakiKinugasa** [comment]
設定方法の記事を発見
https://cygwin.com/cygwin-ug-net/setup-net.html

**Comment by KimiakiKinugasa** [comment]
https://cygwin.com/ からsetup-x86_64.exe
をダウンロード

**Comment by KimiakiKinugasa** [comment]
ユーザーズガイドが膨大で、英語だけなので辛い
多言語化希望

**Comment by KimiakiKinugasa** [comment]
/OSS-gate/cache/
にsetup-x86_64.exeを配置

**Comment by KimiakiKinugasa** [comment]
cygwinを
.../OSS-gate/cygwin/
にインストール
ローカルパッケージを
.../OSS-gate/cache/
にダウンロード

**Comment by KimiakiKinugasa** [comment]
インストール後にデスクトップにショートカットを作成しない場合、
cygwinの起動方法がよくわからない。
bin/mintty.exe
を起動させると、cygwinが起動するが、名前がcygwinではないので、非常にわかりづらい。
このあたりのことをユーザーズガイドに書いていてほしい

**Comment by KimiakiKinugasa** [comment]
必要最低限のインストール手順だけを説明したものがほしい。
スクショなどでグラフィカルにインストール手順を説明したものがあった方がいい
https://cygwin.com/cygwin-ug-net/setup-net.html#internet-setup
環境変数の設定は必須なのか、そうじゃないのかを明確にしてほしい
https://cygwin.com/cygwin-ug-net/setup-env.html

**Comment by KimiakiKinugasa** [comment]
デフォルトでインストールしたら ls コマンドがなかった！

**Comment by KimiakiKinugasa** [comment]
ls.exe はあったけどバスが通ってなかった

**Comment by KimiakiKinugasa** [comment]
インストールが成功したかどうかをテストする手順がほしい
あるかもしれないので、ユーザーズガイドで探してみる

**Comment by KimiakiKinugasa** [comment]
windows10 64bit でsetup-x86_64.exeを全てデフォルトでインストール
ダウンロードサイトは http://ftp.jaist.ac.jp
インストール終了後 mintty.exe を起動したところ、
```
$ ls
bash: ls: command not found
```
となったが、以下のコマンドは実行できた
```
$ /usr/bin/ls.exe
Cygwin-Terminal.ico  Cygwin.ico  cygdrive  etc   lib   sbin  usr
Cygwin.bat           bin         dev       home  proc  tmp   var
```
このため、ls.exe は存在するが、パスが通っていないことがわかる。

このことから、必要なパスが通っているか通っているか確認できるテスト手順が
ユーザーズガイドにほしいと感じた

**Comment by kou** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
