### ISSUE TITLE
 OSS Gate Workshop: Kyoto: 2017-07-29: masayuki14: docker: Work log

### ISSUE THREAD

**Issue by masayuki14** [oss-gate/workshop#491]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masayuki14** [comment]
dockerで検索する。
https://www.google.co.jp/search?q=docker&oq=docker&aqs=chrome.0.69i59j69i60j35i39j69i61l2j69i60.5306j0j7&sourceid=chrome&ie=UTF-8

**Comment by masayuki14** [comment]
1番目にでてきたページがそれっぽい。
https://www.docker.com/

**Comment by masayuki14** [comment]
英語だからわかりにくいけど、「Try　Dpcler」ってボタンがあったから
そこにいってみる。

**Comment by masayuki14** [comment]
https://store.docker.com/editions/enterprise/docker-ee-trial

**Comment by kyamaguchi81** [comment]
山口です。よろしくお願いいたします！

**Comment by hudiwo** [comment]
ヒキダです。よろしくお願いします。

**Comment by masayuki14** [comment]
インストールがうまくいかなｋった。

**Comment by masayuki14** [comment]
Uninstall方法がわかりにくかった。

なんぜなら・・・

**Comment by masayuki14** [comment]
アイコンがばくだんだったから。

**Comment by masayuki14** [comment]
ばくだんはこわい。Uninstallするのをちゅうちょしてしまう。

**Comment by masayuki14** [comment]
まだDockerのことをわかってないからだ。

**Comment by masayuki14** [comment]
Uninstall したいけれど、
アイコンが爆弾であったため、わかりにくかった。
まだ自分は初心者の状態なので、安易にUninstallするのが
こわくなってしまう。
