### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-07-29: quad9: review: Work log

### ISSUE THREAD

**Issue by quad9** [oss-gate/workshop#492]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masayuki14** [comment]
進行の森崎です。楽しんでやっていきましょう！

**Comment by kyamaguchi81** [comment]
山口です。よろしくお願いいたします！

**Comment by kun432** [comment]
:thumbsup:

**Comment by quad9** [comment]
以前から知っていたが、改めて使い出すことにする。
下記のサイトからフォークする。
https://github.com/kmuto/review

**Comment by quad9** [comment]
フォークして運営する方法は以下のサイトを参考にする。
http://kik.xii.jp/archives/179

**Comment by kun432** [comment]
ライセンスを確認した経緯も書いておきましょうー

**Comment by quad9** [comment]
reviewのgithub、README.mdにあったリンクを参照。
https://github.com/kmuto/review/blob/master/COPYING

**kmuto/review is licensed under the**
**GNU Lesser General Public License v2.1**

以下のページで同じ表記を確認した。
https://opensource.org/licenses/alphabetical

**Comment by quad9** [comment]
該当gemを以前にインストールしていたはずだったが詳細は忘れた。
自分のローカル環境にどんなgemをインストールしているかを使う前に確認しておきたかったので、下記のサイトの記載を参考にした。
http://qiita.com/h5y1m141@github/items/74029cab9706971c8dbe

**Comment by quad9** [comment]
review gemをインストールしていたことは確認。
README.mdに
rake installをしなさいとある。これって何か？　調べてみる。

**Comment by quad9** [comment]
rake gemも入っていることを確認した。
README.mdに以下のようにあったので、

> add the ./bin directory to your $PATH:
> $ echo "export PATH=PATH_OF_REVIEW/bin:$PATH" >> ~/.profile

自分の場合は、~/.bashrcに追記する。

**Comment by quad9** [comment]
クイックスタートをしてみる。

### Quick Start

> review-init hello
> cd hello
> (... add and edit *.re file, config.yml and catalog.yml ...)
> rake epub  ## generating EPUB
> rake pdf   ## generating PDF(Requirement TeX)

なるほど、ここで『rake』を使うのだとわかった。
EPUB、PDFの生成とも問題なく出来た。

**Comment by quad9** [comment]
時間があるので、リンク先のクイックスタートをしてみる。
https://github.com/kmuto/review/blob/readme-md/doc/quickstart.md

そうすると、
$ review-compile --target html -a  ## convert all files into HTML
このコマンドで問題が発生。

quad9:hello quad9$ review-compile --target html -a
review-compile: error: invalid option: -a
Usage: review-compile [--target=FMT]

**Comment by quad9** [comment]
> You can convert all *.re files in catalog.yml with -a option.
> $ review-compile --target html -a  ## convert all files into HTML

とすると、下記のエラー

> review-compile: error: invalid option: -a

reviewのバージョンが古かったので最新版に上げてみたのですが上手くいきませんでした。

**Comment by kun432** [comment]
やったことは「都度」可能な限り細かく書いたほうがいいですね、覚えているとしてもあとでissueにするときに二度手間になっちゃいますしね。

**Comment by quad9** [comment]
下記、クイックスタート
https://github.com/kmuto/review/blob/readme-md/doc/quickstart.md

において手順通り行い、

> To convert hello.re, you can use review-compile command.
> $ review-compile --target html hello.re > hello.html  ## generating HTML
> $ review-compile --target latex hello.re > hello.tex  ## generating LaTeX
> $ review-compile --target idgxml hello.re > hello.xml ## generating XML for InDesing

ここまでは難なく出来ました。次に

> You can convert all *.re files in catalog.yml with -a option.

の箇所で、複数の「.re」ファイルを作成し、catalog.ymlに増やしたファイル名も追記。

> CHAPS:
>   - hello.re
>   - hello2.re
>   - hello3.re

その上で、記載されているオプションをつけてコマンドを実行しました。
$ review-compile --target html -a

ところが、これが受け付けられないオプションであるとのエラーが帰ってきました。
review-compile: error: invalid option: -a

なお、複数の「.re」ファイルを作成せず、catalog.ymlにもファイル名を追記しない初期状態でやっても同じエラーが帰ってきます。

----- 環　境 -----
MacOS 10.12.6
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
review2.3.0
rbenv 1.1.0
Homebrew 1.2.2
Homebrew/homebrew-core (git revision d467e; last commit 2017-06-08)

**Comment by kun432** [comment]
👍

**Comment by quad9** [comment]
本日の成果です。ありがとうございました！
https://github.com/kmuto/review/issues/807

**Comment by masayuki14** [comment]
おめでとうございます！

**Comment by masayuki14** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
