### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-07-29: Rei-HAYASHI: Docker: Work log

### ISSUE THREAD

**Issue by Rei-HAYASHI** [oss-gate/workshop#493]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masayuki14** [comment]
進行の森崎です。楽しんでやっていきましょう！

**Comment by kyamaguchi81** [comment]
山口です。よろしくお願いします！

**Comment by Rei-HAYASHI** [comment]
Dockerが持参のMacにすでにインストールされているので、削除してみる。
LaunchpadからDockerを選んで削除してみる。

**Comment by kun432** [comment]
清水です。よろしくお願いいたします。

**Comment by Rei-HAYASHI** [comment]
消し方がわからない。アイコン長押しで×ボタンが出てこない！
「Mac Docker uninstall」で検索してみる。

**Comment by hudiwo** [comment]
ヒキダです。
よろしくお願いします。

**Comment by Rei-HAYASHI** [comment]
https://github.com/docker/for-mac/issues/488　が見つかる。
も、上手くいっていないというコメントばかりで解決方法が分からない。

**Comment by Rei-HAYASHI** [comment]
Dockerが起動中だったので、とりあえず「Quit Docker」で終了させる。
しかし、Launchpadでアイコン長押ししても×ボタンが出ない。何故。

**Comment by Rei-HAYASHI** [comment]
「Mac docker」でググり、アンインストール方法を模索中。
https://docs.docker.com/docker-for-mac/

**Comment by Rei-HAYASHI** [comment]
ページ内検索で「uninstall」で探すと、「Uninstall or reset」という項目が見つかった！

**Comment by Rei-HAYASHI** [comment]
とりあえずまたDockerを起動させる。
早くインストールしたい…。

**Comment by Rei-HAYASHI** [comment]
Preferenceから「Reset」を選択する。爆弾のアイコンが危なっかしい。
<img width="492" alt="2017-07-29 14 10 07" src="https://user-images.githubusercontent.com/30530775/28742321-b0e9092e-7467-11e7-85b2-b1602c19929e.png">

**Comment by Rei-HAYASHI** [comment]
「全部消していいね？」と聞かれる。全部消してしまおう。
<img width="710" alt="2017-07-29 14 11 11" src="https://user-images.githubusercontent.com/30530775/28742333-e25705ba-7467-11e7-9a8c-b31ff5b31640.png">

**Comment by Rei-HAYASHI** [comment]
削除完了したようだが、まだDockerが存在する…！
とりあえず「Quit Docker」で終了させる。

**Comment by Rei-HAYASHI** [comment]
LaunchpadにDockerのクジラがまだいるけど、公式サイトからインストールしてみる。
https://www.docker.com

**Comment by Rei-HAYASHI** [comment]
ナビゲーションの「Get Docker」から「For Desktop Mac」を選ぶ。
https://www.docker.com/docker-mac

**Comment by Rei-HAYASHI** [comment]
「Download from Docker Store」からダウンロードすることに。
https://store.docker.com/editions/community/docker-ce-desktop-mac

**Comment by Rei-HAYASHI** [comment]
「Docker Community Edition for Mac」というものをインストールするらしい。
右のほうに「Get Docker」があるから、これを押してダウンロードする。

**Comment by Rei-HAYASHI** [comment]
ダウンロードちょっと時間かかってる。1分くらい？

**Comment by Rei-HAYASHI** [comment]
ダウンロードファイルを展開する。インストールできそう？
![2017-07-29 14 19 27](https://user-images.githubusercontent.com/30530775/28742370-049441aa-7469-11e7-9984-67ff1d43b965.png)

**Comment by Rei-HAYASHI** [comment]
「古いのがあるよ」と言われる。やはりか…。
![2017-07-29 14 20 27](https://user-images.githubusercontent.com/30530775/28742371-1f1d9b66-7469-11e7-935a-0b5794e23f41.png)
置き換えることにする。

**Comment by Rei-HAYASHI** [comment]
Launchpadから起動すると、警告ダイアログ出た。

<img width="586" alt="2017-07-29 14 22 00" src="https://user-images.githubusercontent.com/30530775/28742378-51010780-7469-11e7-90b1-377820aeb7b9.png">

「開く」を選択する。

**Comment by Rei-HAYASHI** [comment]
上のバーのところにDockerのアイコンが出てきたので、インストール完了したとみなす。

**Comment by Rei-HAYASHI** [comment]
https://store.docker.com/editions/community/docker-ce-desktop-mac　の下のほうに「Installation」があり、
「Run it」があるので試してみる。
コマンドラインで `docker version` を実行せよ、とのこと。

**Comment by Rei-HAYASHI** [comment]
```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Rei-HAYASHI** [comment]
https://store.docker.com/editions/community/docker-ce-desktop-mac の「Run It」のところに
「Run docker run hello-world to verify that Docker is pulling images and running as expected.」とある。
次は `hello-world` を試してみることにする。

**Comment by Rei-HAYASHI** [comment]
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b04784fba78d: Pull complete 
Digest: sha256:f3b3b28a45160805bb16542c9531888519430e9e6d6ffc09d72261b0d26ff74f
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Comment by Rei-HAYASHI** [comment]
ここまで出来たのは良しとして、次はどうすれば？
と思い、
https://store.docker.com/editions/community/docker-ce-desktop-mac
の最下部のリンク「Docker for Mac Documentation」のリンクへ飛ぶ。
https://docs.docker.com/docker-for-mac/#check-versions-of-docker-engine-compose-and-machine

**Comment by Rei-HAYASHI** [comment]
「Check versions of Docker Engine, Compose, and Machine」ということなので、
手順通りにコマンドを実行する。

**Comment by Rei-HAYASHI** [comment]
```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

**Comment by Rei-HAYASHI** [comment]
```
$ docker-compose --version
docker-compose version 1.11.2, build dfed245
docker-compose version 1.14.0, build c7bdf9e
```

コピペしたら2行出てきたけども？

**Comment by Rei-HAYASHI** [comment]
```
$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
```

もう1回実行したら、さっきの2行目だけ出てきた。なんで。

**Comment by Rei-HAYASHI** [comment]
さっきの件は置いておいて、次のコマンドを実行することにした。

```
$ docker-machine --version
docker-machine version 0.12.0, build 45c69ad
```

こっちは大丈夫そう。

**Comment by Rei-HAYASHI** [comment]
次は「Explore the application and run examples」ということで、Dockerがちゃんと動いているか見てみましょうね、とのこと。
`docker version` と  `docker run hello-world` はさっき実行したので、
`docker ps` を実行してみる。

**Comment by Rei-HAYASHI** [comment]
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

うーん？これでいいの？

**Comment by Rei-HAYASHI** [comment]
以下のコマンドが「Dockerized web server」を立ち上げられるコマンドとのこと。
`docker run -d -p 80:80 --name webserver nginx`
これが上手くいけば、ブラウザからアクセスできるとのこと。ワクワク。

**Comment by Rei-HAYASHI** [comment]
```
$ docker run -d -p 80:80 --name webserver nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
94ed0c431eb5: Pull complete 
9406c100a1c3: Pull complete 
aa74daafd50c: Pull complete 
Digest: sha256:788fa27763db6d69ad3444e8ba72f947df9e7e163bad7c1f5614f8fd27a311c3
Status: Downloaded newer image for nginx:latest
f181117e50027f0790440139634096690b88405f25479f34e5cbdb02b68bfa76
```

メキメキっとダウンロードが進んで、あっという間に完了した模様。

**Comment by Rei-HAYASHI** [comment]
ブラウザのURLバーに「http://localhost/」を入れてアクセスしてみる。

**Comment by Rei-HAYASHI** [comment]
公式ドキュメントにある通りの画面が表示された。

<img width="570" alt="2017-07-29 14 42 01" src="https://user-images.githubusercontent.com/30530775/28742474-1f570c04-746c-11e7-89b4-c1ec70711df8.png">

やったー！

**Comment by kun432** [comment]
👍

**Comment by Rei-HAYASHI** [comment]
↑の状態で `docker ps` を実行せよとのこと。
さっきも同じコマンドを実行したけど、さっきはコンテナーIDとかが空っぽだった。
今度はコンテナーIDとかが見られるのかな？

**Comment by Rei-HAYASHI** [comment]
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
f181117e5002        nginx               "nginx -g 'daemon ..."   4 minutes ago       Up 4 minutes        0.0.0.0:80->80/tcp   webserver
```

表示されてるー！！
上手くいっているっぽい。

**Comment by Rei-HAYASHI** [comment]
今、起動してるWebサーバーを停止させるには、`docker stop webserver` を、
再起動させるには `docker start webserver` を実行せよ、とのこと。

**Comment by Rei-HAYASHI** [comment]
停止中のコンテナは `docker ps` では出てこない。
`docker ps -a` で表示されるよ、と書いてある。

英語のドキュメントを読みながら進めてるけど、これ、日本語訳になってるドキュメントがすでにあるような気がする…。(まだ探してないけども)

**Comment by Rei-HAYASHI** [comment]
メニューバーの「Preference」は環境設定だろうか。
クジラアイコンから「Preference」を選択する。(これ、最初にアンインストールする時にやったな…)
<img width="304" alt="2017-07-29 14 51 52" src="https://user-images.githubusercontent.com/30530775/28742543-7d6b6672-746d-11e7-82ab-a70761411491.png">

**Comment by Rei-HAYASHI** [comment]
起動時の設定やファイル共有のディレクトリの設定などが書いてあった。
とりあえずデフォルト設定のままにしておく。

**Comment by Rei-HAYASHI** [comment]
環境設定はこれで良し、として先に進めないか探す。

https://docs.docker.com/docker-for-mac/#preferences
の上に
「Want more example applications? Get Started and Samples are great places to start.」というリンクがある。
とりあえず、「Get Started」のほうのリンクを押す。
https://docs.docker.com/get-started/

**Comment by Rei-HAYASHI** [comment]
コンテナの仕組みとVMの仕組みの比較なんかが書いてある。
コマンドを実行したいけど、次の章以降っぽい。。
このページこそ日本語訳のドキュメントがあればいいのになぁ。(ありそう)(探してないけど)

**Comment by Rei-HAYASHI** [comment]
多分あんまり良くないんだろうけど、次の章に行っちゃう。
https://docs.docker.com/get-started/part2/

**Comment by Rei-HAYASHI** [comment]
まずは「Dockerfile」を作りましょう、とのこと。
新規ディレクトリを作って、その中にDockerfileを作る。
内容は公式ドキュメントのものをそのまま使う。

```
# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
```

**Comment by masayuki14** [comment]
> Uninstall 方法がわかりにくい
フィードバックできそうですね！

**Comment by masayuki14** [comment]
Uninstallダイアログの文言、アイコンが初心者にやさしくなさそうですね。

**Comment by masayuki14** [comment]
`$ docker-compose --version` 2行出る問題

**Comment by masayuki14** [comment]
GetStarted, Smples  がもっと目だっていたら、スムーズに続けられたかもしれない！？

**Comment by masayuki14** [comment]
公式の日本語ドキュメントがほしい！

**Comment by Rei-HAYASHI** [comment]
アンインストール時に私がやりたかったのは「Remove all data」ではなく、多分「Uninstall」だ。
ちゃんと英語を読めばよかった…。

**Comment by Rei-HAYASHI** [comment]
**フィードバックしたいポイント**
Unintallの方法が分かりづらかった。

**Comment by Rei-HAYASHI** [comment]
本当はMac上からDockerを消し去ってまっさらな状態にしたかったのに、結果的にはデータを消しただけだった。
本当にやりたかったことは「Uninstall」で実行できたのに、一番下にあるのが気づかない原因の一つだったように思う。

**Comment by Rei-HAYASHI** [comment]
「Uninstall」が一番上にあるか、「Reset」とは別のタブに置いてあれば分かりやすいのではないか。
・データを消すだけ
・アプリケーションごと消す
のは性質が違うように思う。

**Comment by Rei-HAYASHI** [comment]
:memo:下書き
Docker for Macのアンインストールの方法が分かりづらかった。
公式ドキュメントに沿って「Reset」タブを選択したものの、表示されている3つのボタンのうち、私が達成したかったことは1番下の「Uninstall」ボタンで実行できたようだ。
ドキュメントのURL: https://docs.docker.com/docker-for-mac/#uninstall-or-reset

「Uninstall」ボタンが一番上にあるか、「Reset」とは別のタブに「Uninstall」ボタンがあれば分かりやすくなるのではないか。

**Comment by Rei-HAYASHI** [comment]
📝下書き2
Docker for Macのアンインストールの方法が分かりづらかった。

私はDockerをあまり理解できていない状態だった。
Dockerをインストールし、最新のDockerをインストールし直そうと思っていた。
そのため、インストール済みのDockerをアンインストールをしようと試みた。

Dockerの公式ドキュメントに沿って「Reset」タブを選択した。
ドキュメントのURL: https://docs.docker.com/docker-for-mac/#uninstall-or-reset

表示されている3つのボタンのうち、私は一番上の「Remove all data」ボタンを押した。
しかし、アプリケーションが残ったままになった。
私が達成したかったことは1番下の「Uninstall」ボタンで実行できたようだ。

<img width="492" alt="2017-07-29 14 10 07" src="https://user-images.githubusercontent.com/30530775/28743092-3b316914-747c-11e7-87f9-27c81f62eae2.png">

そこで、以下の提案をしたいと思う。
・「Uninstall」ボタンを一番上に置く
・「Reset」とは別のタブに「Uninstall」ボタンを置く

尚、アンインストール前のDockerのバージョンは不明です。

Mac OS version: macOS Sierra 10.12.6

**Comment by Rei-HAYASHI** [comment]
:memo: 提出用(英訳): 
It was difficult for me to recognize how to uninstall Docker for Mac. 

I didn't have a lot of knowledge about Docker so I'm 'beginner'.

I tried to uninstall older Docker for install the latest version.

I chose the "Reset" tab along with the official Docker documentation.
documentation URL: https://docs.docker.com/docker-for-mac/#uninstall-or-reset

I pressed the "Remove all data" button at the top of the three buttons displayed in the dialog.

<img width="492" alt="2017-07-29 14 10 07" src="https://user-images.githubusercontent.com/30530775/28743092-3b316914-747c-11e7-87f9-27c81f62eae2.png">

However, old Docker application remained.
What I accomplished was that I could run it with the "Uninstall" button at the bottom.

I wonder if it is easy to understand by putting the "Uninstall" button on a different tab than "Reset".

Incidentally, the version of Docker that I tried to uninstall is unknown.

Mac OS version: macOS Sierra 10.12.6

**Comment by Rei-HAYASHI** [comment]
Issueを提出しました。

https://github.com/docker/docker.github.io/issues/4020

**Comment by kun432** [comment]
👍

**Comment by masayuki14** [comment]
おめでとうございます！Gateをくぐりましたね！

**Comment by quad9** [comment]
お疲れ様でした！

**Comment by Rei-HAYASHI** [comment]
:memo: Issueを送るまでの流れ
・日本語で**箇条書き**でまとめる。
背景を書くのが大事！

・英語にする。
Google翻訳さんを頼るのもアリ。

・書き方に決まりはあるのか？まずは公式ドキュメントからリンクをたどる。
https://docs.docker.com

・「Request Doc Changes」のリンクを発見する。
https://github.com/docker/docker.github.io/issues/new?assignee=johndmulhausen&body=File:%20[index.md](https://docs.docker.com/),%20CC%20@johndmulhausen
ここから投稿するのかな。

・で、書き方は？
↑の投稿ページの上になんか書いてある。
 「the guidelines for contributing」のリンクを見てみる。
https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md

うーん、なんか違うっぽい。。
一番下に「Style guide」というのがあるので見てみる。
https://docs.docker.com/opensource/doc-style/#metaphor-and-figurative-language

うーん、長い。わかりにくい。

他の人のIssueを見てみると皆わりと自由な感じなので、自由な感じで投稿してみる。

**Comment by Rei-HAYASHI** [comment]
:memo:  ライセンスを確認する手順

・OSSを決めるデモで決めました。
　・興味があるOSSがあったので、「Docker」をググってみる。

・OSSかどうか？を調べるには
　・公式ドキュメントにあるかどうか
`https://www.docker.com`

・公式ドキュメントでは分からなかったので、DockerのGutHubの `LICENCE` を見てみる。
　→Dockerのライセンスは「Apache Licence 2.0」であることが分かる。
`https://github.com/moby/moby/blob/master/LICENSE`

　・Open Source Initiativeで調べる。
`https://opensource.org/`
　ここにあったのでOK！
`https://opensource.org/licenses/Apache-2.0`

**Comment by masayuki14** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
