### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-07-29: kyamaguchi81: react: Work log

### ISSUE THREAD

**Issue by kyamaguchi81** [oss-gate/workshop#494]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masayuki14** [comment]
進行の森崎です。楽しんでやっていきましょう！

**Comment by Rei-HAYASHI** [comment]
ビギナーの林です。宜しくお願いします！

**Comment by tshkh8** [comment]
サポーターの大澤です。お願いします！

**Comment by kyamaguchi81** [comment]
react.jsを検索する

**Comment by hudiwo** [comment]
ビギナーのヒキダです。
よろしくお願いします。

**Comment by kyamaguchi81** [comment]
https://www.google.co.jp/search?q=react.js&oq=react.js&aqs=chrome..69i57j69i61j0l2j69i61j0.244j0j4&sourceid=chrome&ie=UTF-8

**Comment by kyamaguchi81** [comment]
１個目は広告なので２個目がそれっぽい

**Comment by kyamaguchi81** [comment]
https://facebook.github.io/react/

**Comment by kyamaguchi81** [comment]
ブラウザでlicenseを検索してみる

**Comment by kyamaguchi81** [comment]
引っかからない。。

**Comment by kun432** [comment]
清水です。よろしくお願いいたします。

**Comment by kyamaguchi81** [comment]
Docsページをみてみる

**Comment by kyamaguchi81** [comment]
https://facebook.github.io/react/docs/hello-world.html

**Comment by kyamaguchi81** [comment]
ブラウザでlicenseを検索してみる

**Comment by kyamaguchi81** [comment]
同じくひっかからない

**Comment by kyamaguchi81** [comment]
Githubを見てみる

**Comment by kyamaguchi81** [comment]
https://github.com/facebook/react/blob/master/LICENSE

**Comment by kyamaguchi81** [comment]
licenseを確認

**Comment by kyamaguchi81** [comment]
BSD 3-clause "New" or "Revised" License

**Comment by kyamaguchi81** [comment]
ライセンス確認
https://opensource.org/licenses

**Comment by kyamaguchi81** [comment]
Popular Licensesに記載があった！

**Comment by kyamaguchi81** [comment]
README.mdを確認

**Comment by kyamaguchi81** [comment]
https://github.com/facebook/react

**Comment by kyamaguchi81** [comment]
>React is a JavaScript library for building user interfaces.
 なるほど

**Comment by kyamaguchi81** [comment]
ぱっとみ英語ばっかりなのでどこみたら良いか、、。

**Comment by kyamaguchi81** [comment]
上から見ていく

**Comment by kyamaguchi81** [comment]
>React is available as the react package on npm.

Reactはnpm上で使えるよってことか

**Comment by kyamaguchi81** [comment]
CDNでもokらしい

**Comment by kyamaguchi81** [comment]
とりあえず一番上のリンク押して見る

**Comment by kyamaguchi81** [comment]
Trying Out React

**Comment by kyamaguchi81** [comment]
https://facebook.github.io/react/docs/installation.html#trying-out-react

**Comment by kyamaguchi81** [comment]
当たり前だけどまた英語ばかりだ

**Comment by kyamaguchi81** [comment]
installを目指してるけどどこに向かっているのかわからなくなる。
とりあえず使ってみようってことみたい

**Comment by kyamaguchi81** [comment]
codepenのリンクがあるので見てみる

**Comment by kyamaguchi81** [comment]
https://codepen.io/gaearon/pen/rrpgNB?editors=0010

**Comment by kyamaguchi81** [comment]
使ってみた。
なるほど。

**Comment by kyamaguchi81** [comment]
download this HTML fileのリンクを押して見る

**Comment by kyamaguchi81** [comment]
ダウンロードしたhtml見てみる

**Comment by kyamaguchi81** [comment]
うむ。codepenと同じ。

**Comment by kyamaguchi81** [comment]
Next押して見る

**Comment by kyamaguchi81** [comment]
Try Reactは一旦置いておいてCreate a NEW App してみる

**Comment by kyamaguchi81** [comment]
https://facebook.github.io/react/docs/installation.html

**Comment by kyamaguchi81** [comment]
やってみる
```
npm install -g create-react-app
create-react-app my-app

cd my-app
npm start
```

**Comment by kyamaguchi81** [comment]
npmのinstallについては手順なさそう

**Comment by kyamaguchi81** [comment]
入ってたので今回はうまくいきそう

**Comment by kyamaguchi81** [comment]
$ create-react-app my-app

**Comment by kyamaguchi81** [comment]
たくさんpackages入っていってる
>Installing packages. This might take a couple of minutes.
>Installing react, react-dom, and react-scripts...

**Comment by kyamaguchi81** [comment]
もうちょっと時間かかるかと思ったけど２，３分ぐらいでinstall

**Comment by kyamaguchi81** [comment]
コマンドライン上で下記が表示された
```
Success! Created my-app at /Users/yamaguchikensuke/workspace/ossgate/react/my-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  yarn start

Happy hacking!
```

**Comment by kyamaguchi81** [comment]
メモとってるから落ち着いて見返せるけど、英語アレルギーで一旦素通りしてしまう

**Comment by kyamaguchi81** [comment]
suggestされてるから乗っかってみる

**Comment by kyamaguchi81** [comment]
localで立ち上がった！
create new app(install)できたってことかな

**Comment by kyamaguchi81** [comment]
コマンドラインでなんか言われてる

```
Note that the development build is not optimized.
To create a production build, use yarn build.
```

**Comment by kyamaguchi81** [comment]
サポータの方に教えてもらう
上記は開発用のjsファイルの圧縮とかしてないからプロダクションではyarn buildした方がよいっていう注意書きみたい

**Comment by tshkh8** [comment]
Qiitaにこんなページありました。
http://qiita.com/kikunantoka/items/3cf94a43394f3c632ad2

**Comment by kyamaguchi81** [comment]
>Yarnは Fast で Reliable で Secure なパッケージマネジメントシステムです。
なかなかな英語の記述から始まりましたｗ

**Comment by kyamaguchi81** [comment]
コマンドライン上で一通り上手く言ったぽいのでドキュメントに戻る
https://facebook.github.io/react/docs/installation.html#trying-out-react

**Comment by kyamaguchi81** [comment]
https://github.com/facebookincubator/create-react-app#create-react-app-

**Comment by kyamaguchi81** [comment]
https://github.com/facebookincubator/create-react-app#getting-started

**Comment by kyamaguchi81** [comment]
>npm install -g create-react-app
yarnでなくて問題ないのか。
とりあえずやってみる

**Comment by kyamaguchi81** [comment]
```
  npm install -g create-react-app
/usr/local/bin/create-react-app -> /usr/local/lib/node_modules/create-react-app/index.js
/usr/local/lib
└── create-react-app@1.3.3
```

**Comment by kyamaguchi81** [comment]
>You’ll need to have Node >= 6 on your machine. 

と書いてあるので確認する

**Comment by kyamaguchi81** [comment]
```
 node -v
v7.10.0
```

**Comment by kyamaguchi81** [comment]
6以上だからok

**Comment by kyamaguchi81** [comment]
>You can use nvm to easily switch Node versions between different projects.

nvmってなんだ

**Comment by kyamaguchi81** [comment]
リンク踏んだら別のrepositoryのinstallationがでた。

https://github.com/creationix/nvm#installation

今更読み返してわかった。projectによってnodeのバージョン変えれるものってことか。
入れておく。

**Comment by kyamaguchi81** [comment]
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

**Comment by kyamaguchi81** [comment]
nvm の設定zshに入れとく

**Comment by kyamaguchi81** [comment]
入ってた

**Comment by kyamaguchi81** [comment]
フィードバックする文章をまとめる

**Comment by kyamaguchi81** [comment]
# フィードバックポイント
1. Readmeにかかれているinstallationがinstall以外にtry outなどinstall以外のものがある
2. Create a NEW App の時に installとinstall後にすることが書かれている
3. Readmeのget startedで初めてnodeのバージョンが聞かれる

**Comment by kyamaguchi81** [comment]
## 各理由
### 1. 
- どうなったらinstallした状態になるかわかりづらい
-

**Comment by kyamaguchi81** [comment]
どうなったらinstallした状態になるかわかりづらい

**Comment by kyamaguchi81** [comment]
どうなったらinstallした状態になるかわかりづらい

**Comment by kyamaguchi81** [comment]
わかりづらかったらinstallするまでしんどい

**Comment by kyamaguchi81** [comment]
他の章に分けた方が見やすい、やることがわかりやすい、ゴールが見えやすい

**Comment by kyamaguchi81** [comment]
2. Create a NEW App の時に installとinstall後にすることが書かれている

**Comment by kyamaguchi81** [comment]
詳細
```
npm install -g create-react-app
create-react-app my-app

cd my-app
npm start
```

**Comment by kyamaguchi81** [comment]
install はたぶんこれだけ

`npm install -g create-react-app`

**Comment by kyamaguchi81** [comment]
理由は
1と同様

- なぜなら、やることが複数あってどうなったらinstallした状態になるかわかりづらい
- わかりづらかったらinstallするまでしんどい
- 他の章に分けた方が見やすい、やることがわかりやすい、ゴールが見えやすい

**Comment by kyamaguchi81** [comment]
3. Readmeのget startedで初めてnodeのバージョンが聞かれる

**Comment by kyamaguchi81** [comment]
どのバージョンを使ってよいかわからなかった
npmも同様

**Comment by kyamaguchi81** [comment]
3は引っかかる人おおそうなので3を選択

**Comment by kyamaguchi81** [comment]
installation の前に使うものとバージョンをわかりたい

**Comment by kyamaguchi81** [comment]
こっちにはバージョン書いてあった。。
https://github.com/facebookincubator/create-react-app#getting-started

**Comment by kyamaguchi81** [comment]
ただドキュメントにはバージョン先に書いておいてほしい。

https://facebook.github.io/react/docs/installation.html

**Comment by kyamaguchi81** [comment]
ここでかかれているみたい
https://github.com/facebook/react/blob/master/docs/docs/installation.md

**Comment by kyamaguchi81** [comment]
Creating a New Applicationの前にnode, npmのバージョンを記載してほしい

**Comment by kyamaguchi81** [comment]
なぜなら、いざinstallする時にエラーでinstallできないと嫌だから

**Comment by kyamaguchi81** [comment]
Creating a New Application の`npm install -g create-react-app`する前にnode, npmのバージョンを記載してほしい
なぜならいざinstallする際に他のバージョンの違いでinstallできなくなるとinstallしたい気持ちが薄れるから

**Comment by kyamaguchi81** [comment]
In [Creating a New Application] of the document https://facebook.github.io/react/docs/installation.html, please list [You’ll need to have Node >= 6 on your machine.] before the description in [npm install -g create-react-app]
Because you want to know the required version before running the command

**Comment by kyamaguchi81** [comment]
issueたてたら返信きた

**Comment by kyamaguchi81** [comment]
issue: https://github.com/facebook/react/issues/10324
返信: https://github.com/facebook/react/issues/10324#issuecomment-318820798

**Comment by kyamaguchi81** [comment]
リンク消えない。。

**Comment by kun432** [comment]
create-react-appしたら、Node4の場合にはいろいろ古いかもだから6以上にするといいよ、ってメッセージが出るようにしてて、4使ってる人にも公平感与えてるけどどう？みたいな感じですね。

で、最終的には向こうでドキュメントに6以上がオススメみたいな文言追加のPRもう投げてくれたみたいです。

なにかしらコメント残してあげるといいですね。
おめでとうございます！

**Comment by kyamaguchi81** [comment]
@kun432 
コメントありがとうございます！
なかなか英語が読み慣れてないのでとても助かります！

>なにかしらコメント残してあげるといいですね。

なにかしたコメントしてみます。

>おめでとうございます！

ありがとうございます！
こんなに早く返信してくれると思ってなかったので嬉しいです！

**Comment by masayuki14** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！

**Comment by masayuki14** [comment]
https://github.com/facebook/react/issues/10324
