### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2017-07-29: hudiwo: ttsh2: Work log

### ISSUE THREAD

**Issue by hudiwo** [oss-gate/workshop#495]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tshkh8** [comment]
サポーターの大澤です。よろしくお願いします！

**Comment by kun432** [comment]
清水です。よろしくお願いいたします。

**Comment by hudiwo** [comment]
とりあえず、本家ページへ。
https://ja.osdn.net/projects/ttssh2/

**Comment by hudiwo** [comment]
おっ、GitHubに対応してない！
![001](https://user-images.githubusercontent.com/7713274/28742334-ea9be394-7467-11e7-8436-40180f7d1936.JPG)

**Comment by hudiwo** [comment]
しょうがない、CVSでいくか…

https://ja.osdn.net/cvs/view/ttssh2/

**Comment by hudiwo** [comment]
んじゃ、CVS本家ページへ。

http://www.nongnu.org/cvs/

**Comment by hudiwo** [comment]
CVSはGNUライセンスやった。

**Comment by hudiwo** [comment]
Windows用バイナリをここから取得。

http://ftp.gnu.org/non-gnu/cvs/binary/stable/x86-woe/

**Comment by masayuki14** [comment]
進行の森崎です。楽しんでやっていきましょう！

**Comment by hudiwo** [comment]
Windows用のCVSクライアントを動かそうとしたが、
ちょっとハマりそう…
なので、直接バイナリをダウンロードすることへ方針変更。

**Comment by hudiwo** [comment]
とりあえず、ここからteratermバイナリを取得。https://ja.osdn.net/projects/ttssh2/downloads/67769/teraterm-4.95.exe/

**Comment by hudiwo** [comment]
素のままで起動。
![002](https://user-images.githubusercontent.com/7713274/28742536-52da7d9e-746d-11e7-84bb-edce32834981.JPG)

**Comment by hudiwo** [comment]
こっちが本家やったみたい…https://ttssh2.osdn.jp/
（さっきのはOSDNのプロジェクトページ）

**Comment by hudiwo** [comment]
このページを読んでみる。

**Comment by hudiwo** [comment]
ライセンスはBSDとシッカリ記載あり！

＞TeraTerm Project は、ターミナルエミュレータ Tera Term 、および SSH 対応拡張モジュール TTSSH の開発をしています。BSDライセンスに基づくオープンソース・ソフトウェアです。オリジナルの Tera Term Pro 2.3 の原作者公認の後継版です。開発は、OSDN上のプロジェクトページで行われています。

**Comment by hudiwo** [comment]
ターミナルソフトは相手ありきなので、とりあえずはヘルプの内容確認とメニュー等の表示間違いにスポットして問題点を漁ってみることにする！

**Comment by hudiwo** [comment]
ヘルプファイル：アンインストールの項

Tera Term を削除するには、コントロールパネルの「プログラムの追加と削除」を実行するか、Tera Term ディレクトリにある unins000.exe を実行してください。

**Comment by hudiwo** [comment]
Windows10は「プログラムと機能」

![image](https://user-images.githubusercontent.com/7713274/28743046-00a180d2-747b-11e7-8fc3-6b2563d253e7.png)

**Comment by hudiwo** [comment]
オンラインヘルプも一緒。

https://ttssh2.osdn.jp/manual/ja/uninstall.html

**Comment by hudiwo** [comment]
まとめると、

```
ヘルプファイル「アンインストール」の項番において、

Tera Term を削除するには、コントロールパネルの「プログラムの追加と削除」を実行するか…

の記述中で、Windows10 のコントロールパネルでは「プログラムの追加と削除」が「プログラムと機能」に変更されている。
Windows10 に追従するために、

Tera Term を削除するには、コントロールパネルの「プログラムの追加と削除」（Windows10 では「プログラムと機能」）を実行するか…

に修正するほうが良いと思われる。
```

かな…

**Comment by hudiwo** [comment]
提出だん。

_https://osdn.net/ticket/browse.php?group_id=1412&tid=37409_

**Comment by masayuki14** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！

**Comment by kun432** [comment]
レスポンスありましたねー
おめでとうごさいます
