### ISSUE TITLE
OSS Gateワークショップ 2016-06-11: hatappi: chatwork-ruby: 作業ログ

### ISSUE THREAD

**Issue by hatappi** [oss-gate/workshop#50]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

```
* 作業 : 
* 思っていること: 
```

## 対象gem
https://github.com/asonas/chatwork-ruby

**Comment by hatappi** [comment]
* 作業 : とりあえずREADMEを読もう
* 思っていること: `TODO: Write a gem description`ってかいてある・・・・
　でもlast commitが2015の10月・・・
　これ一生かかないやつだ

**Comment by hatappi** [comment]
READMEを読む感じ
```
require "chatwork"

# Create message
ChatWork.api_key = "XXX"
ChatWork::Message.create(room_id: 1234, body: "Hello, ChatWork!")
```
は出来る感じだけど今のchatworkのapiを見る感じだと
メッセージをうけとったりできるはずだし、それはないのかな

**Comment by hatappi** [comment]
* 作業 : とりあえずインストールしてみよう
* 思っていること: 

 dependenciesを見る感じだと、http clientはfaraday使っているのか・・・
個人的にはrest-clientが好き

```
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using multipart-post 2.0.0
Using bundler 1.11.2
Using faraday 0.9.2
Using chatwork 0.2.0
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by hatappi** [comment]
* 作業 : とりあえず実行してみよう
* 思っていること: 
とりあえずトークンいれてみて実行したけど
投稿されない・・・・・
辛い・・・
エラーなし・・・・
辛い・・・

```
require "chatwork"

# Create message
ChatWork.api_key = "XXX"
ChatWork::Message.create(room_id: 1234, body: "Hello, ChatWork!")
```

**Comment by hatappi** [comment]
よしソースコードを読もう

**Comment by hatappi** [comment]
作業: ソース読む
メモ：
　ここらへんに各モジュールが入ってる  
　https://github.com/asonas/chatwork-ruby/tree/master/lib/chatwork  

    **ドキュメントには書いてないけど他のapiにも対応してそう**
    readmeとかに対応しているapiの情報とかあるとよさそう

**Comment by hatappi** [comment]
動かない理由わかった！！！
トークンのユーザーがroomにいないからだ！！！
**初歩的な感じだけど、これREADMEに追加しないと、はまる人いそう**

**Comment by hatappi** [comment]
作業: READMEに書いてあるものは動いたから、コード読んだときに発見した他のメソッドも叩いてみる

**Comment by hatappi** [comment]
作業：一通り実行してみて、再度ドキュメントとかソースを読んでみて
ログ：

* chatworkには独自のメッセージ記法とかあるからそれの書き方のリンクとかのせてほしかった
　http://developer.chatwork.com/ja/messagenotation.html
* rsepcのtestでshoudかぁーexcept使いたいないーーー

**Comment by hatappi** [comment]
作業: `ChatWork::Message.create(room_id: 1234, body: "Hello, ChatWork!")`これをいじってみる
ログ:

### room_idが存在しないものの場合
request
```
p ChatWork::Message.create(room_id: 11111111111111111111111111111111111, body: "Hello, ChatWork!")
```

response
```
~/p/oss ❯❯❯ ruby test.rb
#<ChatWork::APIError: 400>
```

### room_idがString
```
p ChatWork::Message.create(room_id: 'afdsfaf', body: "Hello, ChatWork!")
```

```
~/p/oss ❯❯❯ ruby test.rb
/Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/chatwork-0.2.0/lib/chatwork/operations.rb:35:in `%': invalid value for Integer(): "afdsfaf" (ArgumentError)
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/chatwork-0.2.0/lib/chatwork/operations.rb:35:in `parse_if_hash_key_exists'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/chatwork-0.2.0/lib/chatwork/operations.rb:25:in `create'
        from test.rb:6:in `<main>'
```

### room_idがそもそも指定されなかった場合
```
p ChatWork::Message.create(body: "Hello, ChatWork!")
```

```
~/p/oss ❯❯❯ ruby test.rb                                                                                                                                                                                                                    ⏎
/Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1100:in `rescue in merge': bad URI(is not URI?): /v1/rooms/%d/messages (URI::InvalidURIError)
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1097:in `merge'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:406:in `build_exclusive_url'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:192:in `build_env'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/chatwork-0.2.0/lib/chatwork/client.rb:37:in `block (2 levels) in <class:Client>'
        from /Users/hatanakayusaku/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/chatwork-0.2.0/lib/chatwork/operations.rb:27:in `create'
        from test.rb:6:in `<main>'
```

**Comment by hatappi** [comment]
**入力値にはバリデーションとかほしいかも**

**Comment by hatappi** [comment]
## 自分の考えをまとめる

#### api_keyをデフォルトは環境変数を指定するようにしてほしい
このgemを使用する際に`ChatWork.api_key = "XXX"`と記載をしてトークンをセットするが、
これを明示しない場合は環境変数(exp: CHATOWRK_API_TOKEN)から取得するようにしてほしい。
例えばgoogleが出している[google-auth-library-ruby](https://github.com/google/google-auth-library-ruby)と呼ばれるgoogleのauthに使うようなgemでも下記のように認証に必要な情報がなかった場合などに環境変数から取得するようにしていたりする
https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/user_refresh.rb#L61

### エラーに関しては、apiから返される文言も付与してほしい
現状だと下記のようにエラーになった場合にエラーコードのようなものしか帰ってこない。
コードとして反映させる場合は、エラーコードでエラーハンドリングが出来るが、デバッグする際などはなぜ駄目かなどの情報がないとデバッグがしにくい
```
~/p/oss ❯❯❯ ruby test.rb
#<ChatWork::APIError: 403>
```

### rspecの書き方を新しいほうにしたい
現状はのコードでは
https://github.com/asonas/chatwork-ruby/blob/master/spec/lib/chatwork_spec.rb
下記に記載されているがコードが`should`で書かれている。ただこの書き方はrspecの2.11から
`except`で書けるようになった。
理由は下に公式で記載されていますが、shouldを使うとBaseObjectを継承したクラスのテストを書く際にエラーが出てしまうようです
http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/

### ドキュメントに追記がほしい
* このgemで対応している機能一覧がほしい
  * 現状のドキュメントですとmessageのpostしかありませんが、コードを見るとtodoを作成するapiなど他の機能も使えるようになっていると思うので、コードを見に行くのを省くためにも使用できるAPIとサンプルはほしいです

**Comment by hatappi** [comment]
## 開発者にむけてに関してのやつ
### api_keyをデフォルト値に環境変数をもたせてほしい
下記のREADME.mdのUSAGEにも記載されていますが、
本gemを使用する際にはまず初めに`ChatWork.api_key = "XXX"`を記載しないといけません。

この実装だとメソッドを使用する際に毎回定義してあげなければならないです。
使用するケースを考えると、トークンは環境変数にまたせて読み込ませるような下記のコードになるかと思います。
```ruby
ChatWork.api_key = ENV['CHATWORK_API_TOKEN']
```

本gemでは下記のコードのようにdefaultがnilになっているので、デフォルトを環境変数にしてあげるとよいかもしれません。
https://github.com/asonas/chatwork-ruby/blob/master/lib/chatwork.rb#L20

他のgemの実装などを見てみると例えばgoogleが出しているauthに使用するgemの[google-auth-library-ruby](https://github.com/google/google-auth-library-ruby)ではuserがoptionsとして認証情報を指定しなかった場合に下記のコードのように環境変数を指定するようにしています
https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/user_refresh.rb#L61

**Comment by hatappi** [comment]
## 開発者にむけてに関してのやつ part2
### テストコードのshouldをexpectに変更したい
https://github.com/asonas/chatwork-ruby/blob/master/spec/lib/chatwork_spec.rb
上記に本gemのテストコードが記載されていますが、この中でshouldが使用されています。

rspecではv2.11からexpectの記載ができるようになりました。
https://github.com/rspec/rspec

**Comment by hatappi** [comment]
作業：https://github.com/oss-gate/workshop/issues/50#issuecomment-225339266
に関して修正PRを実装していく
https://github.com/hatappi/chatwork-ruby/tree/token-default-env

**Comment by hatappi** [comment]
とりあえず
## api_keyはデフォルトで環境変数を使ってほしい
のissueを作成した
https://github.com/asonas/chatwork-ruby/issues/11

**Comment by hatappi** [comment]
こういうgemはchatworkのapiをさらでhttp clientでかかなくてもよくなるので
凄い便利

**Comment by kou** [comment]
お疲れさまでした！
