### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-8-12: mr-xx: nadesiko3: Work log

### ISSUE THREAD

**Issue by mr-xx** [oss-gate/workshop#525]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
西谷＠関学・理工・情報科学です．よろしくお願いします．

**Comment by mr-xx** [comment]
よろしくお願いします

**Comment by mr-xx** [comment]
はじめます

**Comment by mr-xx** [comment]
開発環境のセットアップをしようかなと
https://github.com/kujirahand/nadesiko3/blob/master/SETUP.md

**Comment by mr-xx** [comment]
Windowsアップデートに阻まれる。再起動。

**Comment by mr-xx** [comment]
node.js インストール

**Comment by mr-xx** [comment]
必要なライブラリをインストール
npm install -g npm-check-updates electron asar

**Comment by mr-xx** [comment]
asar ってなんだろう・・

**Comment by mr-xx** [comment]
asarを使ってみる - Qiita
http://qiita.com/niusounds/items/2739fdbc26df03421bfe

> asarとは
> 複数のファイル・ディレクトリを一つのファイルにパックする、tarのような仕組みです。Electronでアプリをパッケージ化するためにGitHubが作りました。

すばらしくわかりやすい説明。ありがたいです。

**Comment by mr-xx** [comment]
C:\～\OSSgate>npm install --no-optional
npm WARN enoent ENOENT: no such file or directory, open 'C:\～\OSSgate\package.json'
npm WARN OSSgate No description
npm WARN OSSgate No repository field.
npm WARN OSSgate No README data
npm WARN OSSgate No license field.

エラー（正確には警告（Warning）？）でた

**Comment by mr-xx** [comment]
npm の勉強しないと・・

**Comment by mr-xx** [comment]
> コマンドラインから以下のコマンドを実行することで、ソースコードをビルドできる。
必要を感じたのは、開発環境構築手順ページに上記のように書かれているので、 GIT clone して pull してくる必要があるのかなと思ったので

**Comment by mr-xx** [comment]
IEのセキュリティに阻まれてたけど、信頼してクリア！

**Comment by mr-xx** [comment]
Folk だん

**Comment by tshkh8** [comment]
振り返りを担当した大澤です。

セットアップのドキュメントに、

・nadesiko3をローカルにダウンロードする
・ローカルのディレクトリで、記載のコマンドを実行する

という記載があれば
セットアップで困ることがなかったんじゃないかと思いましたので、
これはフィードバックポイントかなと感じました。

**Comment by daddygongon** [comment]
フィードバックポイントなんかみつかりました？

**Comment by mr-xx** [comment]
@tshkh8 アドバイスありがとうございます
@daddygongon @tshkh8 さんからアドバイスいただいた内容で、いけそうな気がしています

**Comment by mr-xx** [comment]
SourceTree インストールだん

**Comment by mr-xx** [comment]
ローカルへのリポジトリダウンロード（クローン？）だん

**Comment by mr-xx** [comment]
というわけで、以下のコマンドも無事実行できました。
npm install --no-optional

**Comment by mr-xx** [comment]
npm run build
も、うまいこといったような気がします。（エラーがでずに終わるという意味で）

**Comment by mr-xx** [comment]
npm install -g nadesiko3
で、なでしこをインストール

**Comment by mr-xx** [comment]
>cnako3 -e "「こんにちは」と表示"
こんにちは

無事実行できることを確認。

**Comment by mr-xx** [comment]
開発環境のセットアップのドキュメントへをより易しくなるような補足を追加したい · Issue #181 · kujirahand/nadesiko3
https://github.com/kujirahand/nadesiko3/issues/181

issue登録してみました

**Comment by mr-xx** [comment]
プルリクにトライ。
・・・と思ったら、 クローンしたほうじゃなくて、オリジナルの方のリポジトリのクローンをとってコミットしようとしてしまいエラーとなってしまったので、やりなおし (*_*)

**Comment by mr-xx** [comment]
気を取り直して、プルリクだん！

開発環境のセットアップ手順ドキュメントへnadesiko3リポジトリをローカルにダウンロードが必要の旨の補足を追加( Issue #181 ) by mr-xx · Pull Request #182 · kujirahand/nadesiko3
https://github.com/kujirahand/nadesiko3/pull/182

**Comment by murajun1978** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
