### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-08-12: waka1012: learn-anything: Work log

### ISSUE THREAD

**Issue by waka1012** [oss-gate/workshop#526]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
西谷＠関学・理工・情報科学です．よろしくお願いします．この後，Githubからメールがたくさん来ます．

**Comment by waka1012** [comment]
使い方の調査。どのように使うことを想定しているのか。

**Comment by waka1012** [comment]
「mindmaps」に対象のOSSを変更します。
https://github.com/drichard/mindmaps

**Comment by daddygongon** [comment]
ライセンス確認されました．GNU Affero General Public License v3.0ですかね．OSSですね．

**Comment by waka1012** [comment]
インストールをします。

**Comment by waka1012** [comment]
npmを使えるようにします。

**Comment by waka1012** [comment]
npm run start でNo module named SimpleHTTPServerと怒られる

**Comment by waka1012** [comment]
'''
[wakayama@mba11:~/Prg/oss_gate/mindmaps] $ npm run start

> mindmaps@0.8.0 start /Users/wakayama/Prg/oss_gate/mindmaps
> cd src && python -m SimpleHTTPServer 3000

/Users/wakayama/anaconda/bin/python: No module named SimpleHTTPServer
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mindmaps@0.8.0 start: `cd src && python -m SimpleHTTPServer 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mindmaps@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wakayama/.npm/_logs/2017-08-12T05_46_16_297Z-debug.log
'''

**Comment by waka1012** [comment]
/Users/wakayama/anaconda/bin/python: No module named SimpleHTTPServer
→AnacondaのpythonではSimpleHTTPServerは入っていない？

**Comment by waka1012** [comment]
疑問・はまった点
（１）ディレクトリ→「npm run start」を実行するディレクトリの場所によって成否が変わる？
（２）anacondaだと、SimpleHTTPServerが入っていない。代わりに「python -m http.server 3000」で起動し、http://localhost:3000にアクセスすると繋がる。

**Comment by yoichi** [comment]
ふりかえりでご一緒させていただいた、なかやまです。

* はまったことのメモが残っている
* 対象を動かすところまで到達している

ともとてもよいと思いました。他の人もはまりそうなところではまりましたね。

**Comment by waka1012** [comment]
＞中山さん
ありがとうございます。
他にも
・pythonを使っていることがREADMEからわからない
・ソフトの構成がわからない、どのような手順で処理が行われているかわからない
といった点などがはまる可能性があると思います。

**Comment by daddygongon** [comment]
まずは日本語でまとめてもらってからですかね．

**Comment by waka1012** [comment]
問題点
・pythonを使っていることが書かれていないが、pythonでエラーがでた。
・AnacondaでSimpleHTTPServerが入っていないためエラーとなる
について報告します。

**Comment by waka1012** [comment]
インストール手順について、もう少し詳しく記載していただけないでしょうか。
pythonを使ってHTTPサーバーを立ち上げているということがわかるようにしていただきたいです。
以下の点で苦戦しました。

（１）pythonを使っていることは書かれていないが、「No module named SimpleHTTPServer」というpythonのエラーが出た
（２）pythonのディストリビューションAnacondaにはSimpleHTTPServerが入っていないため、「npm run start」でhttpサーバーの起動に失敗する

今回はSimpleHTTPServerの代わりに「python -m http.server 3000」でHTTPサーバーを立ち上げて対処しました。

エラーメッセージは以下になります。

'''
$ npm run start

> mindmaps@0.8.0 start /Users/user/Prg/mindmaps
> cd src && python -m SimpleHTTPServer 3000

/Users/user/anaconda/bin/python: No module named SimpleHTTPServer
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mindmaps@0.8.0 start: `cd src && python -m SimpleHTTPServer 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mindmaps@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-08-12T05_43_51_971Z-debug.log
'''

**Comment by waka1012** [comment]
Thank you for developing interesting tools.
Would you please describe the installation process in more detail?
I'd like you to know that you are using python to launch an HTTP server.
Sometimes I am new to python and struggled with the following points.

(1) Although it is not written that you are using python, you get a python error "No module named SimpleHTTPServer"
(2) Since python distribution Anaconda does not contain SimpleHTTPServer, startup of http server fails at "npm run start"

In this case, instead of SimpleHTTPServer, "python -m http.server 3000" was started up HTTP server.

The error message is as follows.

```
$ npm run start

> mindmaps@0.8.0 start /Users/user/Prg/mindmaps
> cd src && python -m SimpleHTTPServer 3000

/Users/user/anaconda/bin/python: No module named SimpleHTTPServer
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mindmaps@0.8.0 start: `cd src && python -m SimpleHTTPServer 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mindmaps@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-08-12T05_43_51_971Z-debug.log
```

**Comment by daddygongon** [comment]
Thank you for developing such an interesting tool.
Would you please describe the installation process in more detail?

On the installation process, you use python to launch an HTTP server,
but a novice of python, like me, struggled with the following points:
(1) I got a python error "No module named SimpleHTTPServer", but I can't predict where it comes from.
(2) Since python distribution Anaconda does not contain SimpleHTTPServer, startup of http server fails at "npm run start".

In this case, instead of SimpleHTTPServer, "python -m http.server 3000" on src/ directory makes possible to start up HTTP server.

The error message is as follows.
```
$ npm run start

> mindmaps@0.8.0 start /Users/user/Prg/mindmaps
> cd src && python -m SimpleHTTPServer 3000

/Users/user/anaconda/bin/python: No module named SimpleHTTPServer
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mindmaps@0.8.0 start: `cd src && python -m SimpleHTTPServer 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mindmaps@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2017-08-12T05_43_51_971Z-debug.log
—
```

**Comment by waka1012** [comment]
https://github.com/drichard/mindmaps/issues/64

**Comment by murajun1978** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
