### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-08-12: takuya: sinatra: Work log

### ISSUE THREAD

**Issue by GraniteRock** [oss-gate/workshop#527]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by GraniteRock** [comment]
公式ページを確認する

**Comment by GraniteRock** [comment]
http://www.sinatrarb.com/

**Comment by GraniteRock** [comment]
Getting Startedを確認

**Comment by GraniteRock** [comment]
公式トップ上部メニューのreadmeがそれにあたる。
http://www.sinatrarb.com/intro.html

**Comment by GraniteRock** [comment]
Getting Startedを試す。
http://localhost:4567/
でサイトを表示確認した。

**Comment by GraniteRock** [comment]
Routesを記述する。
そのままやっても挙動確認できない…

**Comment by GraniteRock** [comment]
毎回追記をするたびにサーバー起動し直すのがちょっと手間。

**Comment by GraniteRock** [comment]
↑https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/reloader.rb
に再起動不要にするコードがあった。

READMEにそのあたりの誘導はあってもいいかもー。

**Comment by GraniteRock** [comment]
★作業の粒度を最小単位ぐらいまで下げてみるほうが良い
　「一番小さい作業に対して、結果がこうだった」まで

**Comment by GraniteRock** [comment]
Routesを一つずつ読み進める（実行する）。

**Comment by GraniteRock** [comment]
get '/' do
  .. show something ..
end

を実行する。

**Comment by GraniteRock** [comment]
実行できた。

**Comment by GraniteRock** [comment]
post '/' do
  'post'
end

を実行する。

**Comment by GraniteRock** [comment]
別ページからのpost遷移がないと実行できない。

**Comment by GraniteRock** [comment]
put '/' do
  'put'
end

を実行する。

**Comment by GraniteRock** [comment]
404エラーが表示された。
put元からの遷移でないため、404エラーが表示された。
別ページからのput遷移がないと実行できない…。

**Comment by GraniteRock** [comment]
以下の残りのroutesにおいても、同様の結果になると考えられる。
確認を省略します。

**Comment by GraniteRock** [comment]
get '/foo' do
  # Does not match "GET /foo/"
end

を実行する。

**Comment by GraniteRock** [comment]
実行できた。（白ページの表示）

**Comment by GraniteRock** [comment]
```
get '/hello/:name' do
  # matches "GET /hello/foo" and "GET /hello/bar"
  # params['name'] is 'foo' or 'bar'
  "Hello #{params['name']}!"
end
```

を実行する。

**Comment by tshkh8** [comment]
遅くなりましたがメンターの大澤です。
よろしくお願いします

**Comment by GraniteRock** [comment]
田村です。よろしくお願いします。

**Comment by gh640** [comment]
ご説明いただきありがとうございました！

以下お話に上がったポイントです。

- ルーティング設定を書き換えても即時反映されない点は確かにわかりづらくドキュメントに追加するとよいかもしれない、とのこと
- 実際にドキュメントにコントリビュートするときのワークフローについては http://www.sinatrarb.com/contributing.html に書かれており、 https://github.com/sinatra/sinatra.github.com/#contributing を見るのがよさそう・・・

**Comment by GraniteRock** [comment]
ありがとうございます！

**Comment by GraniteRock** [comment]
「ルーティング設定を書き換えても即時反映されない点をドキュメントに追加する」
を今回のフィードバックにします。

**Comment by GraniteRock** [comment]
http://www.sinatrarb.com/contributing.html
ワークフローを読む。

**Comment by GraniteRock** [comment]
ワークフローより抜粋
> Want to write docs?
> The process for contributing to Sinatra’s website, documentation or the book is the same as contributing code. We use git for versions control and GitHub to track patch requests.
> 
> The sinatra.github.com repo is where the website sources are managed. There are almost always people in #sinatra that are happy to discuss, apply, and publish website patches.
> 
> The Book has its own git repository and build process but is managed the same as the website and project codebase.
> 
> Sinatra Recipes is a community project where anyone is free to contribute ideas, recipes and tutorials. Which also has its own git repository.
> 
> The Introduction is generated from Sinatra’s README file.
> 
> If you want to help translating the documentation, the README is already available in Japanese, German, Chinese, Russian, European and Brazillian Portugese, French, Spanish, Korean, and Hungarian. The translations tend to fall behind the English version. Translations into other languages would also be appreciated.

**Comment by GraniteRock** [comment]
この中で大事なのは

> The Introduction is generated from Sinatra’s README file.

という記述。つまり、 README fileを直すことで、今回のフィードバックにする。

**Comment by GraniteRock** [comment]
READMEに書きたい内容を考える。

**Comment by GraniteRock** [comment]
「コードを変更するたびにサーバーを再起動してください。」
あたりが簡潔でいいのかもしれない。

**Comment by GraniteRock** [comment]
google翻訳
「Please restart the server every time you change the code.」

**Comment by GraniteRock** [comment]
でも、サーバーを再起動したいことを強調したいので、
「Please restart the server, every time you change the code.」
でもいいのかもしれない。英語力の自信は皆無。

**Comment by GraniteRock** [comment]
> View at: http://localhost:4567
> 
> It is recommended to also run gem install thin, which Sinatra will pick up if available.

この間に追加する予定

**Comment by GraniteRock** [comment]
はなしをまとめた結果、

英訳
> The code you changed will not take effect until you restart the server.
> Please restart the server every time you change.

和訳
> 変更したコードは、サーバーを再起動するまで有効になりません。
> 変更のたびにサーバーを再起動してください。

**Comment by GraniteRock** [comment]
https://github.com/sinatra/sinatra/pull/1331

**Comment by daddygongon** [comment]
ラストに参加した西谷です．適切だと思います．Perfect Rubyの15章も観てみてください．

**Comment by murajun1978** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
