### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-08-12: ksilverwall: git: Work log

### ISSUE THREAD

**Issue by ksilverwall** [oss-gate/workshop#529]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kun432** [comment]
よろしくお願いします

**Comment by ksilverwall** [comment]
`git clone https://github.com/git/git` でクローン

**Comment by ksilverwall** [comment]
README.mdを読む
INSTALLを参照する

**Comment by ksilverwall** [comment]
ガイドの通り`make install`を実行する。
コンパイルエラー発生
```
./gettext.h:17:11: fatal error: 'libintl.h' file not found
#       include <libintl.h>
                ^
1 error generated.
make: *** [credential-store.o] Error 1
```

**Comment by kun432** [comment]
ビルドする場合は環境に依存しちゃいますね、、、

**Comment by ksilverwall** [comment]
vagrant上のcentosで実行して環境差分を確認する。
gcc, openssl-devel, zlib-devel, curl-devel, expat-devel がコンパイルに必要

**Comment by ksilverwall** [comment]
更にperlモジュールのExtUtils:MakeMakerが必要
centos系ではperl-ExtUtils-MakeMakerでyum installできる

**Comment by ksilverwall** [comment]
更に別のエラーが発生
```
tclsh failed; using unoptimized loading
```
以下のサイトを参考に`yum install -y gettext`する
http://qiita.com/yusukaaay/items/6a39cc2f983cb0319bd1

**Comment by kun432** [comment]
すさまじいYAK SHAVINGになりますねー^^;
ソースから入れるとなりがちではあります。

**Comment by ksilverwall** [comment]
ビルド完了。CentOSでビルドできました
```
[vagrant@localhost git]$ ~/bin/git --version
git version 2.14.1.145.gb3622a4
```

**Comment by ksilverwall** [comment]
Mac側の対策
エラーコードでググるといかのStackOverflowにぶち当たる
https://stackoverflow.com/questions/11370684/what-is-libintl-h-and-where-can-i-get-it

**Comment by kun432** [comment]
INSTALLの中に依存するものとかが書いてあるかもしれませんね

**Comment by ksilverwall** [comment]
以下のようにNO_GETTEXTをしているとビルドが始まりました。
`NO_GETTEXT=1 make install`

**Comment by ksilverwall** [comment]
NO_GETTEXTが何のオプションなのかは不明

**Comment by kun432** [comment]
INSTALLの90行目以降にいろいろありますね

**Comment by yalab** [comment]
改善の方向として OS 毎に依存してる外部ライブラリのインストールの仕方のドキュメントを書いたり例えば make depend-install みたいに依存ライブラリのインストールごとやってくれる task があると便利ですね

**Comment by izudon** [comment]
（ビギナー参加ですがひとこと）
依存関係でコケること、ありますよね。
私の場合、あきらめる、の一択だったんですけど、
INSTALL を読むと、書いてあったりするんですね。
勉強になりました。

**Comment by kun432** [comment]
まずはシンプルに箇条書きでいいと思います。

・何を見て何をしたか？
・その結果、何が起きたか？
・それを踏まえてどうしたらよいか？

伝え方はあとでいいと思いますよー

**Comment by ksilverwall** [comment]
書いているけどわかりにくい

**Comment by ksilverwall** [comment]
作業内容：CentOSとMacOSXでビルドした
事象：コンパイルエラが発生した
改善点：INSTALLファイルの記述をもっと見通しよくする。

**Comment by kun432** [comment]
「INSTALLファイルの記述をもっと見通しを良くする」というところを、具体的に書けるといいですね！

**Comment by ksilverwall** [comment]
問題点：NO_GETTEXTを有効にして実行すると英語のみのサポートになる
改善案：MacでNO_GETTEXTを使わないやり方を探す

**Comment by ksilverwall** [comment]
問題点：INSTALLの規模の割に段落が少ない
改善案：カテゴリごとに分けて見出しをつける

**Comment by ksilverwall** [comment]
理由：手順が先にあると実行してしまう。

**Comment by ksilverwall** [comment]
INSTALLの規模の割に段落が少なく見通しが悪い。
またコマンド実行手順が先頭にあるため、必要な依存ライブラリをインストールする前に実行してしまい二度手間になってします。
そのため依存関係の解決は先頭に持ってくると良いと思います。

**Comment by kun432** [comment]
いい感じだと思います。

**Comment by kun432** [comment]
では、
・提案を伝える手段はどう規定されているか？issue or pullreq or 他の方法 
・英語でどう書くか？
にすすみますかー

**Comment by ksilverwall** [comment]
Macでビルドした場合エラーが発生する。
NO_GETTEXTを有効にすると回避できるが、英語のみのサポートになってしまう。
Macでの正しい回避手段を記載して欲しい

**Comment by kun432** [comment]
基本的にissueは一つに絞ったほうがいいと思います。

**Comment by ksilverwall** [comment]
Google翻訳に突っ込みました
INSTALLの規模の割に段落が少なく見通しが悪い。
またコマンド実行手順が先頭にあるため、必要な依存ライブラリをインストールする前に実行してしまい二度手間になってします。
そのため依存関係の解決は先頭に持ってくると良いと思います。

The paragraph looks a bit bad for the scale of INSTALL.
Also, since the command execution procedure is at the beginning, it is executed twice before installing the necessary dependent libraries.
Therefore, I think that it is good to bring solution of dependency to the head.

**Comment by ksilverwall** [comment]
README情報をもとに
majordomo@vger.kernel.org宛に本文"subscribe git"でメールを送信しました。
認証メールが飛んできたのでガイドに従って送り返し、登録完了しました。

**Comment by kun432** [comment]
シンプルに考えていいとおもいますよ。詳細に説明しようとするといろいろ複雑になって相手側も何？みたいな感じになっちゃうんで。

Simple is bestで😄

**Comment by ksilverwall** [comment]
シンプルにしてみました。
I install git with INSTALL.
I execute 'make install' but get some errors while building.
I find necessary libs written in INSTALL after all build errors solved.
How about write about libs before install command ?

**Comment by kun432** [comment]
最初の3行は過去形にしましょうか。

**Comment by ksilverwall** [comment]
シンプルにしてみました。

Hello!

  I have an idea about document.
  I installed git with INSTALL.  I executed 'make install' but got some errors while building. I found necessary libs written in INSTALL after all build errors have solved.
How about write about libs before install command ?  I think it is better :)

**Comment by ksilverwall** [comment]
表題案
Proposal: Refactor Document INSTALL

**Comment by ksilverwall** [comment]
案２
Proposal: Change paragraph in Document INSTALL

**Comment by kun432** [comment]
必要なライブラリ、というところがあるといいですね

description about necessary libs on INSTALL

**Comment by kun432** [comment]
一例ですんで、参考までに。

**Comment by ksilverwall** [comment]
案３
Add description about necessary libs on INSTALL

**Comment by kun432** [comment]
いきましょう！

**Comment by kun432** [comment]
あと、このメール、多分MLでWebで見れると思うので、URLを貼ってください

**Comment by ksilverwall** [comment]
git@vger.kernel.org に送信しました。

**Comment by yoichi** [comment]
ふりかえりご一緒させていただきました。なかやまです。

git/INSTALL 改めて見てみると、後半は "Issues of note:" となっていて、確かにINSTALL に書くべき内容じゃなくなってる気がしますね。いいところに着目できていると思います。

**Comment by kun432** [comment]
お疲れ様でした！何かしらリアクションが返ってくるといいですね！

**Comment by murajun1978** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
