### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-08-12: izudon: Redmine: Work log

### ISSUE THREAD

**Issue by izudon** [oss-gate/workshop#530]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kun432** [comment]
よろしくお願いします

**Comment by izudon** [comment]
こちらこそお願いいたします。

**Comment by izudon** [comment]
公式サイトを見つけました。ここから情報をいろいろ拾いたいと思います。
http://www.redmine.org/

**Comment by izudon** [comment]
公式サイトの一番上に、GPL v2 であるとかかれてありました。
OSSの定義に従っていたことがわかりましたのでこれでやりたいと思います。
Licenses by Name | Open Source Initiative <https://opensource.org/licenses/alphabetical>

**Comment by izudon** [comment]
下のほうに「Contributing and helping out」という節があり、その中に、
Contribute - Redmine <http://www.redmine.org/projects/redmine/wiki/Contribute>
へのリンクがありました。Cntribute の仕方がｋといらにあると思われちょっと探して見ます。

**Comment by izudon** [comment]
> The official code repository is located in Subversion
オリジナルは Subversion
> A copy of the source is mirrored to Bitbucket (this is maintained by the community) and GitHub (this is maintained by the community)
BitBucket と GitHub にミラーありとのこと。

**Comment by izudon** [comment]
Redmine のプロジェクト管理自体 Redmine でおこなわれていました。
issue もこちらで管理されているようなので、まずはそこにアカウントを作ることかと。
というわけでアカウントを作ります。
Redmine <http://www.redmine.org/account/register>

**Comment by izudon** [comment]
作りました。
Masakazu IZUI - Redmine <http://www.redmine.org/users/306303>

**Comment by izudon** [comment]
アカウントを作ったので「新しいチケット」が作れる模様。
新しいチケット - Redmine <http://www.redmine.org/projects/redmine/issues/new>

**Comment by izudon** [comment]
上部に注釈が出ている。
これを読むと参考になるか。


> This is the Redmine issue tracker for reporting bugs or feature requests about the Redmine core software.
> All data submitted here will be publicly available.
> 
> Support requests are not accepted here in the issue tracker. You can try to get help in the message board.
> 
> Before submitting a bug report, please read SubmittingBugs to make sure that you provide all the required information.
> If you just want to test Redmine, you can go to the online demo.
> All submissions must be written in english.

**Comment by izudon** [comment]
趣旨

* ここは Redmine のコアソフトウェア（プラグインは対象外ということか）のイシューラッカーだよ。
* ここの情報はすべて公に利用可能だよ。
* サポートリクエストはフォーラムでやってね。
* バグレポートの前に SubmittedBugs を見てね。
* Redmine をテストしたいだけならデモサイトがあるよ。

**Comment by izudon** [comment]
SubmittingBugs 読む。
なるほどバグの提出方法的なことが書いてあるゾ。

**Comment by gh640** [comment]
👍

バグの提出方法はアカウントを作らなくても見れるようです。ドキュメントを改善できる気がします。

**Comment by izudon** [comment]
ですね。
・・・そういうのをどこに issue したらいいのかですかね。
・・・。

**Comment by izudon** [comment]
ここか！？
Documentation issues - Redmine <http://www.redmine.org/projects/redmine/issues?query_id=84>

**Comment by izudon** [comment]
カテゴリ「Documentation」というのがあってそこにあがっているっぽい。

**Comment by izudon** [comment]
たまたま一番上にあった issue を開いてみる。
なるほどこんな風に issue をあげてるんだなとなんとなくわかる。

Feature #23583: Need documentation on custom field "Key/value list" - Redmine <http://www.redmine.org/issues/23583>

**Comment by izudon** [comment]
２番目は、「そうそう思ってたのよこれ」的な issue 。
さすがに思ってる人いたんだなと。

Feature #23413: synchronize Textile and Markdown documents - Redmine <http://www.redmine.org/issues/23413>

**Comment by izudon** [comment]
３番目「ドキュメント更新されてへんやん」みたいな内容。
Defect #21682: Documentation for nginx configuration is outdated and broken - Redmine <http://www.redmine.org/issues/21682>

「Wiki編集できるよ」と返信がついてる。「そやったらきみ、直しといてぇな」みたいな。

**Comment by izudon** [comment]
なんかやりとりの雰囲気がわかりますわ。

**Comment by yalab** [comment]
ドキュメントの改善は開発者が忘れがちなのでサポートしてもらえるととても助かります

**Comment by izudon** [comment]
では・・・・
ここ改善してほしいみたいなのをちょっと。

**Comment by izudon** [comment]
こんな改善提案はどうか・・・

* Redmine のドキュメントは Redmine 上の Wiki に基本的に載っかっている。
* ドキュメントの改善は、（ロックされている一部の基本的情報のページを除いて）アカウントを作り、編集権限があるページならば、自由に編集してもらってよいっぽい。
* でも、そのことがわかる記述は「 Contribute 」というページにはわかりやすい形では載っていない。
  * Contribute というページにはわりとすんなりといけるかとは思う。
* そこを、改善してもらえないか・・・
  * つまり、 Contribute の Non Code Related というチャプタの中に、何か１節作ってもらってそのことを書いてもらえたらという方向性。

**Comment by izudon** [comment]
* Code Related のところに実を言えば 「 List of documentation issue 」なるリンクがあり、Documentation 関係の issue はここというような雰囲気はわかる。
* しかしながら・・・
* RDoc で生成されるような Code 関係のドキュメントの話がここにあるのはいいのだが、それ以外の話
  * インストレーションとか
  * Wiki の記法みたいな話
* みたいなことだと、Code Raleted とはなかなか思いにくいと思うので、
* やはり Non Code Related に１節あったほうがいいんじゃないかなぁ。

**Comment by gh640** [comment]
同感です！

**Comment by izudon** [comment]
ありがとうございます！

**Comment by izudon** [comment]
Non Code Raleted の章には冒頭に「ソフト開発の経験は要りませんよ！」と書いてある。
ドキュメントはコードのスキルなくても貢献できる分野だし、自分も Ruby はまだそれほど経験もないので、
こういうところにそういう記述があったら自分のような人間でも「 貢献できる！ 」って、
より思いやすくなるのではないかと思う。

**Comment by izudon** [comment]
というような方向性をなんか文章に（体よく）まとめたいなァ・・。

**Comment by izudon** [comment]
題名「Contribute ページの Non Code Related セクションに Documentation support という節を設ける」
：

**Comment by izudon** [comment]
ドキュメントの編集はCodeの経験がなくてもできる分野。
なので、せっかくならそのことを冒頭に歌っている「 Non Code Related 」というセクションに
そういうことが書いてある節を設けてほしい。
：

**Comment by izudon** [comment]
Redmine はドキュメントの多くが Wiki 上に載っており、
基本部分を除いてアカウントさえ作ればそこを自由に編集して貢献することができる。
そのこともこの節にわかりやすく書いておいてもらえたら人々がより貢献しやすくなるのではないか。
：
的な。

**Comment by izudon** [comment]
該当の記述は Code Related の章にも、ないことはないが、
上記のような理由から、Non Code Related の部分に節を設けて記述していただくことを提案したい。
：
的な。

**Comment by gh640** [comment]
いま口頭でお話にあがった点について記述させていただきます。

- Wiki ページには、作りたてのアカウントで編集できるページとそうでないページがあり、編集できるページはそのまま編集したらいいし、できないページについてはイシューキューにイシューを登録する、となる

**Comment by izudon** [comment]
ですね！ありがとうございます。

**Comment by izudon** [comment]
英語に挑戦やな～。。。（がんばろう）

**Comment by izudon** [comment]
題名
Create "Documentation support" subsection in the "Non Code Related" section of the "Contribution" page.

**Comment by gh640** [comment]
Wiki を直接編集するときの注意点のようです↓

> Submitting a Wiki improvement
> 
> When you edit a wiki page to improve its content, make sure that you fill the comment field with a descriptive summary of the changes you've made to the page. This way we'll be better able to "monitor" and "maintain" the quality of the actual wiki content.

http://www.redmine.org/projects/redmine/wiki/Submissions

**Comment by gh640** [comment]
こちらのイシューは似ていそうです: http://www.redmine.org/issues/11041

**Comment by izudon** [comment]
It would be great to show how to support documentation in the "Non Code Related" section of the "Contribution" page.
...

**Comment by izudon** [comment]
Related information is in the "Code documentation" subsection in the "Code Related" section.
But, documentation needs not code experience.
So, Non Code Related section is also appropriate, I think.

**Comment by izudon** [comment]
Redmine documentation is almost scripted on the "Wiki" of redmine.org.
So, that is more better to be linked to "Submitting a Wiki improvement" subsection in the "Submissions" page.

**Comment by izudon** [comment]
Related information is in the "Code documentation" subsection in the "Code Related" section.
Surely, code documentation needs code experience, but the documentation on this site doesn't necessarily need code experience.
But, documentation needs not code experience.
So, Non Code Related section is a good place to put this kind of information in, I think.
It would be easier for new contributors to find.

**Comment by izudon** [comment]
題名
Create "Documentation support" subsection in the "Non Code Related" section of the "Contribution" page.

----

It would be great to show how to support documentation in the "Non Code Related" section of the "Contribute" page.

The related information is already in the "Code documentation" subsection in the "Code Related" section. Surely, code documentation needs code experience, but the documentation on this site doesn't necessarily need code experience. So non code related section is a good place to put this kind of information in, I think.
It would be easier for new contributors to find.

The most of Redmine documentation is written on the "Wiki" of redmine.org. So, that is better to have a link to "Submitting a Wiki improvement" subsection in the "Submissions" page in this section.

**Comment by gh640** [comment]
For example,

> ## Documentation on this site
> 
> You can contribute to the documentation on this site with directly editing the Wiki. Firstly you need to register your account on this site and you can edit the Wiki. Some Wiki pages doesn't allow you to edit and in the case you need to file an issue on the issue queue with the category "documentation".

**Comment by izudon** [comment]
issue をたてました。

Defect #26668: Create "Documentation support" subsection in the "Non Code Related" section of the "Contribution" page. - Redmine <http://www.redmine.org/issues/26668>

**Comment by tshkh8** [comment]
振り返り担当の大澤です。

お疲れ様でした。
issue登録までできてよかったです。
おめでとうございます！

コメントを細かく書いていただいていて、
振り返りがとてもスムーズにできました！

**Comment by kun432** [comment]
お疲れ様でした！何かしらリアクションが返ってくるといいですね！

**Comment by murajun1978** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
