### ISSUE TITLE
OSS Gateワークショップ 2016-06-11:yasuomi.takano:litexbrl: 作業ログ

### ISSUE THREAD

**Issue by YasuomiTakano** [oss-gate/workshop#54]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by YasuomiTakano** [comment]
XBRLのgem「litexbrl」を触ってみる！
https://github.com/tyn-iMarket/litexbrl

**Comment by YasuomiTakano** [comment]
* 作業：
まず、README.mdを読む

* 思っていること：
どんなgemなんだろう・・・

備考：

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む

* 思っていること：
README短い。
LiteXBRLはXBRLパーサで決算短信に対応している。

**Comment by YasuomiTakano** [comment]
作業：[WIP] README.mdを読む

思っていること：
README短い。
LiteXBRLはXBRLパーサで決算短信に対応している。
Usageが「作成中」だったので、specを読んで把握してみる。

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む

 * 思っていること：
specをどこから読めばいいかわからないけど「litexbrl_spec.rb」から読む。

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む

* 思っていること：
Litexbrlのversionがnilじゃないかを確認しているテストだけあった。
とりあえず、Litexbrlをインストールして確かめてみる。

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む
1. 作業でディレクトリを作る
2. READMEのInstallation通りに進める

* 思っていること：
ない

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む

* 思っていること：rails new いるんじゃないかなって思ったけど、とりあえず `gem 'litexbrl'`のコマンドを打ってみる

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む

* 思っていること：
```
yasuomitakano-no-MacBook-Pro:litexbrl yasuomi.takano$ gem 'litexbrl'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command litexbrl
```
Installationの1行目に下記のように書いてあるから、やっぱり、railsのプロジェクトを作るところから始める
Add this line to your application's Gemfile:

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む

 * 思っていること：
自分としてはrailsから使いたいから、`rails scaffold`を使って簡単なアプリを用意するところから用意する

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む
* 思っていること：

**Comment by YasuomiTakano** [comment]
* 作業：[WIP] README.mdを読む
`tdnet_spec.rb`を読む

* 思っていること：
`tdnet`って単語が入っているから、決算短信関連の情報が書いてあると予想した

**Comment by YasuomiTakano** [comment]
## 整理する
### 自分で自分の気持ちを整理する

READMEのUsageがまだ「作成中」となっているので、早めに書いて欲しい
 * 理想の状態：
ドキュメントがある状態

 * 解決策：

1. 自分が書いてプルリクを送る
2. 開発者がまとめる

**Comment by YasuomiTakano** [comment]
## 目的
このgemが何がてできるかを知りたかった

## 分かったこと
短信サマリが使えることが分かった

## 分からなかったこと
どうやって使えばいいかが分からなかった

## どうなっていればいいか
ドキュメントととしてまとまっていればよかった
具体例のコードと解説

**Comment by YasuomiTakano** [comment]
どうやって使えばいいかっていう情報を具合的に書いて欲しい
1. ファイルを取ってくる
2. そのファイルの中の値を取り出す
例）NetSales 売上高

**Comment by YasuomiTakano** [comment]
## 1. ファイルを取ってくる
`tdnet`って名前が入っているspecファイルがあったから、ファイルを取ってくる処理のヒントがあるとおもった
で、見た結果・・・`tdnet_spec.rb` にそれっぽい情報が載っている

```
      context 'Summary' do
        it do
          document = TDnet.send :find_document, doc("#{dir}/summary.xbrl")
          expect(document).to eq(LiteXBRL::TDnet::Summary)
        end
      end
```

特に`document = TDnet.send :find_document, doc("#{dir}/summary.xbrl")`がそれっぽい処理

**Comment by YasuomiTakano** [comment]
## 2. そのファイルの中の値を取り出す
`litexbrl/spec/tdnet/`以下のファイルを探っている
commitメッセージに `短信・業績予想も連結・非連結を取得する` とあったのでこのファイルに注目した
`results_forecast2_spec.rb` の中を調べていると `Net_Sales `と言う単語があったので怪しそうな処理をその中から見つける
`expect(forecast_q2[:previous_forecast_net_sales]).to eq 7320` この処理が怪ししそう

**Comment by YasuomiTakano** [comment]
# 自分の気持ち整理のまとめ

## 要望
### このGemの使い方をドキュメントにまとめいて欲しい。
READMEのUsageに「具体例のコード例とその解説」が記載してあって欲しい。
具体的に以下の操作を行いたい。
1. XBRLのファイルの取得方法
2. 取得したファイルの中の値の取得方法

**Comment by YasuomiTakano** [comment]
# Issuesに投稿できる形式でまとめる

litexbrlの使い方がわからなかったためREADMEのUsageに「サンプルコードとその解説」を記載して欲しい
今私がやりたいことは以下の操作です。
1. XBRLのファイルの取得
2. 取得したファイルの中の値 (売上高や営業利益 等) の取得

**Comment by YasuomiTakano** [comment]
* 作業：
TDnetに直接検索をかけてファイルを取得する処理も書かれているのかローカルにXBRLのファイルがあることが前提で処理が書かれているのかを知るために、ソースコードを読む

 * 思っていること：

**Comment by YasuomiTakano** [comment]
* 作業：
TDnetに直接検索をかけてファイルを取得する処理も書かれているのかローカルにXBRLのファイルがあることが前提で処理が書かれているのかを知るために、ソースコードを読む

 * 思ったこと：
https://github.com/tyn-iMarket/litexbrl/blob/master/lib/litexbrl/tdnet.rb#L17
この行でファイルを取得しているっぽいので、ローカルのファイルを参照しているっぽい

**Comment by kou** [comment]
お疲れさまでした！
