### ISSUE TITLE
OSS Gate Workshop: Kosen: 2017-09-02: corona365: openCV Work log

### ISSUE THREAD

**Issue by corona365** [oss-gate/workshop#552]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by corona365** [comment]
openCVの公式サイトを探す

**Comment by corona365** [comment]
サイトを見つけた http://opencv.org/

**Comment by corona365** [comment]
windows7 SP1以上に対応したインストール方法を見つけた http://docs.opencv.org/master/d3/d52/tutorial_windows_install.html

**Comment by selmertsx** [comment]
さぽーたーの白シャツメガネです！

**Comment by unasuke** [comment]
サポーターのうなすけです！

**Comment by corona365** [comment]
公式サイトのLicenseというリンクから、BSDライセンスであることを確認。
それがOpenSourceのライセンスであることも確認

**Comment by corona365** [comment]
インストール手順に従い、downloadフォルダ直下にBuild済みのファイルを解凍する

**Comment by corona365** [comment]
その中のbuildフォルダの中のbinフォルダをPATHに通す

**Comment by corona365** [comment]
インストール手順は、「Installation by Using the Pre-built Libraries」の手順を参考にした
Set The PATHという文言を発見したのでPATHを通してみた

**Comment by corona365** [comment]
「Installation by Using the Pre-built Libraries」の5番のリンクへとんだ。
自分の場合は、以下のPATHをシステム環境変数へ通した。
```
C:\opencv\build\bin
```

**Comment by selmertsx** [comment]
> To use the OpenCV library you have two options: Installation by Using the Pre-built Libraries or Installation by Making Your Own Libraries from the Source Files . While the first one is easier to complete, it only works if you are coding with the latest Microsoft Visual Studio IDE and do not take advantage of the most advanced technologies we integrate into our library. .. _Windows_Install_Prebuild:

**Comment by corona365** [comment]
「Installation by Using the Pre-built Libraries」だと最新のVisual Studioをインストールする必要があった。
そのため、visual studioの公式サイトを探す。

**Comment by corona365** [comment]
visual studioの最新版は以下のリンクを参考に、2017であることを確認
```
https://docs.microsoft.com/ja-jp/visualstudio/install/install-visual-studio
```

**Comment by corona365** [comment]
そのリンクのStep1では、「お使いのコンピューターでのシステム要件を確認してください」という手順があった。
それを実践し、自分のコンピューターで使用できることを確認する(以下のリンク参照)
```
https://www.visualstudio.com/ja-jp/productinfo/vs2017-system-requirements-vs
```

**Comment by unasuke** [comment]
https://www.visualstudio.com/ja-jp/productinfo/vs2017-system-requirements-vs

**Comment by corona365** [comment]
https://www.visualstudio.com/ja-jp/productinfo/vs2017-compatibility-vs
リンク先では、システム要件についてを表形式でまとめられていた。
自分のPCのOSのwindows10で使用できるということを、表から確認できた。

**Comment by corona365** [comment]
step1に戻り、自分のPCにUpdateがないことを確認する手順があったので、確認する
　　→最新版であることを確認

**Comment by corona365** [comment]
インストール対象の要求容量を確認すると、1GBから40GBであることを確認。
空き容量が30GBなので次ステップへ進む

**Comment by corona365** [comment]
visual studioのダウンロードをするため、以下のリンクへ飛んだ
https://www.visualstudio.com/ja/downloads/?utm_source=mscom&utm_campaign=msdocs

そこで、無料で使用できるオープンソースや個人開発に限られたEditionを選択し、ダウンロードを開始

**Comment by corona365** [comment]
フィードバック
　 / visual studioのインストール手前で、visual studio 2015までのインストール手順しかなかった
　 / 選択すべき必要なインストールオプションが情報としてなかった(Unityでの開発のデバック等々)
　 / visual studio周りのインストールは情報少ない。画面が古い(解凍後のフォルダの画面等)

**Comment by corona365** [comment]
openCVを解凍後の画面のキャプチャが古い
　　→何が困る・・・最新版のディレクトリ構造の違いから、解凍したファイルが違うのではと感じた
visual studioで使用する場合のコマンド欄
　　→何が困る・・・vcが2015だとvc14で、2013だとvc12で、2012だとvc11で、ってバラバラなのである。これは、初めてvcを使う側として、何が基準なのかがわからず、どこをみて確認することなのかもわからない。
　　ので、これはコマンド欄に一文追記してほしい。そうすると、喜びます。

**Comment by corona365** [comment]
link: http://docs.opencv.org/master/d3/d52/tutorial_windows_install.html#tutorial_windows_install_path 
上記はwindowsユーザ向けに、openCVをIDEで使用できるところまでの手順を明記しているものだと思います。
まずは以下の点が改善点だと思います。
・画面のキャプチャが古い
・visual studio 2015までの説明しか載っておらず、最新版の2017での手順が不明慮
・visual studioの必要最低限なインストールオプションが不明記

以上の改善要望は、こちらのリンク先での手順通りに進めた際に、不明慮だなと感じた点です。
そのほかの資料や情報は、今回見ておりません。

これらの改善をして下さると、ユーザがほかの情報を調べる必要がないかと思いました。
私もこれらの情報があると、喜びます。

画面のキャプチャの差し替えは、ぜひ御願い致します。これははじめ、混乱した。

**Comment by corona365** [comment]
openCVでの報告ルートを調べる

**Comment by corona365** [comment]
見つけた。
公式サイトの「report a bug」からgithubのopenCVのリポジトリの「issue」ページへとんだ。
どうやらこちらに報告をあげるようだ。

**Comment by corona365** [comment]
またサポーターの方に、issueで報告するなら、一個ずつ分割する方がよいとアドバイスを頂いた

**Comment by corona365** [comment]
contributeを見つけた。方法も明記されているようなので、そちらを参考に
報告をあげてみる

**Comment by unasuke** [comment]
https://github.com/opencv/opencv/blob/master/.github/ISSUE_TEMPLATE.md#system-information-version

これに沿って書いていくとよさそう!

```
<!--
If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.
If you need further assistance please read [How To Contribute](https://github.com/opencv/opencv/wiki/How_to_contribute).

This is a template helping you to create an issue which can be processed as quickly as possible. This is the bug reporting section for the OpenCV library.
-->

##### System information (version)
<!-- Example
- OpenCV => 3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
-->

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

<!-- your description -->

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example
    ```
 or attach as .txt or .zip file
-->
```

**Comment by unasuke** [comment]
```
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit

##### Detailed description
ここに書いていく
```

**Comment by corona365** [comment]
windowsユーザ向けのインストール方法が書かれたリンク先}}}}
画面のキャプチャが古い。
私が使用するopenCV3.3の解凍直後のディレクトリ構造とキャプチャ画像のディレクトリ構造が違ったものになっていた。仕様の変更等で変更されたのであれば、変えてほしい。
混乱し、再インストールなども試したが、やはり変わらずにいたので、画面のキャプチャが古い仕様のままなのかと思い、issueを立てます。

差し替えることで、混乱せずにインストールできるかと思います。

**Comment by unasuke** [comment]
> 差し替えることで、混乱せずにインストールできるかと思います。

「指し替えるか、3.3での画像を追加することで、混乱せずにインストールできるかと思います。」

のほうが、2.3を使っているひとにもやさしくなるかもしれません 😊

**Comment by corona365** [comment]
windowsユーザ向けのインストール方法が書かれたリンク先}}}
[ visual studio 2017]での使用方法や、ライブラリとしてのインポート方法までのコマンドなどがない
openCVを環境変数へ通し、IDEで使用するまでの手順に2017番も盛り込んでおいて頂けますでしょうか。
追記して頂けたらユーザが、何か別の情報を探しに行くことがなくなるのではいでしょうか。
また、コマンドのvc11やvc14など、末尾の数字なども、どこを参照すべきなのかの情報がないので、
混乱した。

**Comment by unasuke** [comment]
`'OpenCV_Install_Directory.png' is old in 'Installation in Windows' page` とかどうだろう?

**Comment by unasuke** [comment]
とかとか?
```
Since I want to use OpenCV 3.3 on Windows 10, I saw http: // docs.opencv.org/master/d3/d52/tutorial_windows_install.html#tutorial_ windows_install_path.
However, since 'OpenCV_Install_Directory.png' is of OpenCV 2.3, I was worried because I did not understand that what I downloaded is different and contents downloaded are correct.

If the content of the downloaded file has changed, please update the image. Or add an image of the latest case. That way, I am glad.

[I use google transrate]
```

**Comment by corona365** [comment]
issue title[  'OpenC V_Install_Directory.png' in 'Installation in Windows' page is old ]

body[
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => Windows 64 Bit

##### Detailed description
Since I want to use OpenCV 3.3 on Windows 10, I saw http: // docs.opencv.org/master/d3/d52/tutorial_windows_install.html#tutorial_ windows_install_path.
However, since 'OpenCV_Install_Directory.png' is of OpenCV 2.3,
I was worried because I did not understand that what I downloaded is different and contents downloaded are correct.

If the content of the downloaded file has changed, please update the image. Or add an image of the latest case. That way, I am glad.

[I use google transrate]
]

**Comment by unasuke** [comment]
lack of information of the Visual Studio 2017

**Comment by corona365** [comment]
Information on visual studio on the page for windows users is stopped at 2015.
Specifically, you can see the lack of information in 2017 in the command column under 'Set the OpenCV environment variable and add it to the systems path'.
It is helpful to add the information of 2017 if you can write it.

**Comment by unasuke** [comment]
Information on visual studio on the page for windows users is stopped at VS2015.Specifically, you can see the lack of information in VS2017 in the command column under http://docs.opencv.org/master/d3/d52/tutorial_windows_install.html#tutorial_windows_install_path . It is helpful to add the information of VS2017 if you can write it.

**Comment by corona365** [comment]
title [ lack of information of the Visual Studio 2017 ]
body[

OpenCV => 3.3
Operating System / Platform => Windows 10(64 Bit)
Detailed description

Information on visual studio on the page for windows users is stopped at VS2015.Specifically, you can see the lack of information in VS2017 in the command column under http://docs.opencv.org/master/d3/d52/tutorial_windows_install.html#tutorial_windows_install_path . It is helpful to add the information of VS2017 if you can write it.

[I use google transrate]
]

**Comment by corona365** [comment]
google 翻訳を利用し、英語へ直感的に翻訳した英文を体裁整え、issueへ上げる

**Comment by corona365** [comment]
visual studio についての報告
https://github.com/opencv/opencv/issues/9542

**Comment by corona365** [comment]
画像差し替えの件を報告した
https://github.com/opencv/opencv/issues/9543

**Comment by unasuke** [comment]
```
報告しました〜〜
* https://github.com/opencv/opencv/issues/9542
* https://github.com/opencv/opencv/issues/9543
```

**Comment by komainu8** [comment]
UpstreamにIssuesの数が多いので、1週間ぐらいUpstream側の応答が無かった場合は、ドキュメントを修正してPRしてしまうのも良い方法かなと思いました。

**Comment by kou** [comment]
お疲れ様でした！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料として高専生・学生向けに実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
