### ISSUE TITLE
  OSS Gate Workshop: Kosen: 2017-09-02: ryonacat: bash Work log 

### ISSUE THREAD

**Issue by ryonacat** [oss-gate/workshop#553]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ryonacat** [comment]
bashがOSSか調べた　https://www.gnu.org/licenses/licenses.html
GNU　GPLというライセンスだとわかった

**Comment by komainu8** [comment]
コメント確認しました。

**Comment by ryonacat** [comment]
bashのインストール方法を見つけたhttps://www.gnu.org/software/bash/manual/bash.html#Basic-Installation
手順は書いてあるが説明中の「ソースコード」がどこにあるのかわからない

**Comment by ryonacat** [comment]
ソースコードをトップページから見つけたhttps://www.gnu.org/software/bash/

**Comment by ryonacat** [comment]
ソースコードをダウンロードしたhttp://ftp.gnu.org/gnu/bash/

**Comment by ryonacat** [comment]
コマンドプロンプトからダウンロードしたソースコードが入っているディレクトリまで移動し上記のインストール方法に従い「./configure」と実行した

**Comment by ryonacat** [comment]
インストール方法に従いインストールした後に実際に実行してみた結果、無事に起動した

**Comment by ryonacat** [comment]
起動の確認としてバージョンの確認を行い以前のものから変更されていたのでインストールされて起動されたのだと判断した

**Comment by ryonacat** [comment]
インストール手順についてインストール方法はわかるがその確認方法が不明瞭なので記述をした方がいい
https://www.gnu.org/software/bash/manual/bash.html#Basic-Installation

**Comment by unasuke** [comment]
ダウンロードしたもの → http://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz

**Comment by unasuke** [comment]
https://github.com/oss-gate/workshop/issues/553#issuecomment-326718277 で実行したコマンド

1. `./configure`
1. `make`
1. `make install`

**Comment by unasuke** [comment]
https://github.com/oss-gate/workshop/issues/553#issuecomment-326718350

`4.3.46(1)`から`4.4.0(1)`に変化していた

**Comment by ryonacat** [comment]
インストール手順には以下のような記述があると便利だと考えられる

「bashのインストールが正常に希望のバージョンがインストールされたかの確認は「bash -version」にて確認が可能である」

**Comment by ryonacat** [comment]
インストール手順に記載されている「make test」を実行した。
時間が少々掛かったが無事終了したが特に目立った変化が見られなかった。
上記のため「make test」の必要性を調べるため「make test　とは」で検索https://oshiete.goo.ne.jp/qa/5379043.html
詳細を発見

**Comment by ryonacat** [comment]
フィードバックする項目を「インストール確認の方法の記述」に決定した

**Comment by ryonacat** [comment]
https://www.gnu.org/software/bash/manual/bash.html#Installing-Bashの10.1 Basic Installationという項目にインストール確認のための方法が書いてあると嬉しいと思う。

具体的にいうと以下の文が手順の下に書いてあると嬉しい

…
インストールの確認のために「bash -version」と実行して以下のように出てくるか確認してください。
” GNU bash,, version "希望バージョン" -release (x86_64-unknown-linux-gnu)"
…

**Comment by ryonacat** [comment]
I'd be happy if there was a way to confirm the installation in the item 10.1 Basic Installation in https://www.gnu.org/software/bash/manual/bash.html#Installing-Bash.The reason is that I did not know how to confirm the installation when actually installing.

Specifically, I am glad that the following sentences are written after the procedure.

…
Please execute "bash -version" for installation confirmation and check whether it is displayed as follows.
” GNU bash,, version "Desired version" -release (x86_64-unknown-linux-gnu)"
…

**Comment by ryonacat** [comment]
フィードバックのために連絡先を https://www.gnu.org/software/bash/にて発見

上記のメール文を bug-bash@gnu.org宛に improve document about "bash install" という件名で提出した。

**Comment by komainu8** [comment]
おめでとうございます:tada:

**Comment by ashie** [comment]
前半は手順の記載が抜けていたりしたけど、後半はフィードバックを受けてか細かくやったことが書かれていて良かったと思いました！

**Comment by ashie** [comment]
フィードバック文は最初に日本語で書いて英語に訳し、おかしい場合は日本語を直して再度英語に直していくプロセスで作成したとのこと。修正過程も残っていると良かったかな?と思いました！

**Comment by ashie** [comment]
他にもフィードバック候補があったとのこと

> 手順は書いてあるが説明中の「ソースコード」がどこにあるのかわからない

ので、同じところに入手先も書いておいた方が良いということと、

> 「make test」とはMakefile内の「test」というコマンドを実行させてインストールされた「bash」が正しく動作するか確認するためのものであることがわかった。

`make test`とは何のために実行するものか分からないので、それを書いておいた方が良いとのこと

これられも今後フィードバックできると良いですね！

**Comment by kou** [comment]
お疲れ様でした！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料として高専生・学生向けに実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
