### ISSUE TITLE
OSS Gate Workshop: Kosen: 2017-09-02: kazukiigeta: Wireshark: Work log

### ISSUE THREAD

**Issue by kazukiigeta** [oss-gate/workshop#554]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kazukiigeta** [comment]
Wiresharkで検索したところ英語のページが見つかったhttps://www.wireshark.org/develop.html

**Comment by kazukiigeta** [comment]
見るべき場所がわからなかったがサポータの方にDevelopに開発に参加する際の情報が書いてあることが多いと聞いた

**Comment by kazukiigeta** [comment]
Webサイト上に書いていなかったので、ライセンスを探すためにソースファイルを探しに行った

**Comment by kazukiigeta** [comment]
COPYINGやREADME、LICENSEに乗っていることが多いとサポータの方から聞いて、COPYINGから
GPLｖ２（一部GPLv3+）が使われていることを確認した
※３＋はVersion３以上

**Comment by kazukiigeta** [comment]
GPLv2のライセンスを見つけたため、WiresharkがOSSであることを確かに確認https://opensource.org/licenses/GPL-2.0
今回のWorkshopでしようする。

**Comment by kazukiigeta** [comment]
ソースコードからビルドする
なぜなら、Wiresharkはパッケージが提供されており簡単にインストールできる
他のOSSをビルドする際に、ソースコードからびるどしなければいけない場面もある
開発に参加する際にソースコードからビルドすることになるため、ここで経験しておく。

**Comment by kazukiigeta** [comment]
英語の単語がよくわからなかったので聞いた
Repository 書庫のようなもの 修正した人のコメントなども書いてあるため 修正した人を特定もできる
Clone Repositoryを複製してローカル環境に置くこと 分散型のGitではみんながローカル環境で編集を行いその変更点をRepositoryに反映していく

**Comment by piroor** [comment]
GItそのもののことやソースコードのバージョン管理ってどういう意味があるの？という話については
「わかばちゃんと学ぶGit使い方入門」という本がわかりやすくてよいです。
https://codeiq.jp/magazine/2016/05/41205/
本の元になったWeb連載で、リポジトリの概念などの解説を読めます。

**Comment by kazukiigeta** [comment]
To clone the repository run レポジトリを複製してローカル環境におくために下記CLIからコマンド実行
git clone https://code.wireshark.org/review/wireshark

**Comment by kazukiigeta** [comment]
If you cannot use Git you can download the source code for each official release and for recent development commits . 
上記のOfficial release とRecent development commitsのどちらのソースを選ぶべきか迷った
→ここは実際に動かすところとは別なので読み飛ばし

**Comment by kazukiigeta** [comment]
Buildするための方法を探すためにDeveloper's Guideを確認する

**Comment by tjnet** [comment]
個人的には開発フローがあんまりStandard wayじゃないのとちょっとボリューミーな感じがするので、
curlとかどうですかね、、
この辺で探して、再検証ログ送ってあげたりすると喜ばれると思います
一意見ですが
https://github.com/curl/curl/issues?q=is%3Aissue+is%3Aopen+label%3Aneeds-info-or-update

**Comment by kazukiigeta** [comment]
Githubでのコントリビュートを経験するため、時間内でフィードバックポイントを見つけるために以下curlにてはじめから実施

**Comment by kazukiigeta** [comment]
検索で英語のページを見つけたhttps://curl.haxx.se/

**Comment by kazukiigeta** [comment]
ページの中からライセンスの項目を見つけたhttps://curl.haxx.se/legal/licmix.html
CURLは複数のコンポーネントから成っており、それぞれがOpen sourceのライセンスを持っている

**Comment by kazukiigeta** [comment]
ページ内より、レポジトリのクローンコマンドをみつけたので実施
git clone https://github.com/curl/curl.git

**Comment by kazukiigeta** [comment]
Compile and Build the Sources の項目にコンパイル・ビルドするときはGIT-INFOを読むと書いてある

**Comment by kazukiigeta** [comment]
検証にあたり、下記コマンドにてインストールした時のバージョンでも検証を行うこととする
apt-get install curl

**Comment by kazukiigeta** [comment]
クローンしたレポジトリから現在の最新バージョンを探した
github上のディレクトリからversionで検索し、curlver.h というものを見つけた。

クローンしたレポジトリから、下記コマンドでcurlver.h を探した
find . --name curlver.h

**Comment by kazukiigeta** [comment]
curlver.h確認結果、最新ヴァージョンは7.56.0だった
#define LIBCURL_VERSION "7.56.0-DEV"

**Comment by kazukiigeta** [comment]
追試ができそうかhttps://github.com/curl/curl/issues/1587 を見てみたが、現在の状況がつかめず諦めた。
自分が報告するとき、報告者として、現在の状況を簡単に把握してもらえるようにする必要性がある。
再現コマンドをすべて記載する、環境を記載するなど

**Comment by unasuke** [comment]
> Buildするための方法を探すためにDeveloper's Guideを確認する

https://www.wireshark.org/docs/wsdg_html_chunked/ のこと

**Comment by unasuke** [comment]
> Compile and Build the Sources の項目にコンパイル・ビルドするときはGIT-INFOを読むと書いてある

https://curl.haxx.se/dev/source.html のこと

**Comment by unasuke** [comment]
> github上のディレクトリからversionで検索し、curlver.h というものを見つけた。

https://github.com/curl/curl/blob/master/include/curl/curlver.h のこと

**Comment by unasuke** [comment]
> Compile and Build the Sources の項目にコンパイル・ビルドするときはGIT-INFOを読むと書いてある

これがREDME.mdにないのはなぜなんだろう?? README.mdに追加するという提案をしてみるのもひとつの手だったのかも……

**Comment by kou** [comment]
お疲れ様でした！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料として高専生・学生向けに実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
