### ISSUE TITLE
OSS Gate Workshop: Kosen: 2017-09-02: n0h0: faker Work log

### ISSUE THREAD

**Issue by n0h0** [oss-gate/workshop#555]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ashie** [comment]
あしえと申します。よろしく！

**Comment by n0h0** [comment]
fakerで検索するとgithubのページが見つかった
https://github.com/stympy/faker

**Comment by n0h0** [comment]
READMEの一番下にLicenseの項目があり、MIT Licenseだった。
https://opensource.org/licenses/alphabeticalで検索し、リストに載っていたのでOSSと判断

**Comment by n0h0** [comment]
インストールしてみる。Installingに書かれていた`gem install faker`のコマンドをルートディレクトリで実行。

**Comment by n0h0** [comment]
動かしてみようとする。
`irb`コマンド後に、FakerのREADMEのUsageに載っていた`Faker::Name.name`を実行しようとしたが失敗した。
```
irb(main):001:0> Faker::Name.name
NameError: uninitialized constant Faker
	from (irb):1
	from /Users/n0_h0/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```

**Comment by ashie** [comment]
「書いてあるとおりにやっても動かなった」は絶好のフィードバックポイントだと思います！

**Comment by n0h0** [comment]
動かない理由がわからない…ので、既にfakerを使っている人がいないか検索してみる。
fakerで検索すると、[Rubyのテストデータ作成gem](http://rochefort.hatenablog.com/entry/2016/01/23/224538)が見つかる。

"railsでfakerを使用するには、以下のように環境ごとにスクリプトを書いて
db/fixtures/development
あとは、rake db:seed_fu すればok。"

と記述があったらが、普通にrailsなしで動かすにはどうすれば…。

**Comment by n0h0** [comment]
rubygems.orgのページを見つける。https://rubygems.org/gems/faker/versions/1.6.6

右サイドバーの`links`の欄に`documentation`のリンクがあったので観てみる。
http://www.rubydoc.info/gems/faker/1.6.6

**Comment by n0h0** [comment]
ドキュメント（http://www.rubydoc.info/gems/faker/1.6.6）は利用例はいっぱいあったけど、他はgithubのreadmeと変わらなさそう

**Comment by n0h0** [comment]
他の記事も観てみる
- http://qiita.com/saino-katsutoshi/items/29c0918e489b27df637a
- https://teratail.com/questions/44523
railsプロジェクト内じゃないと使えなさそう…？
テスト用のrailsプロジェクトを作ってみる

**Comment by n0h0** [comment]
サンプルコードを探してみる用にアドバイスをいただく。
"faker sample code"で検索。今回関係ないfakerも出てきたので"faker gem sample code"で再検索。
[使ってそうな記事](http://geekswithblogs.net/alexmoore/archive/2010/01/18/faker-gem---a-quick-and-dirty-introduction.aspx)を見つける。

観てみると、Now you can use it in your favorite ruby program or script. For now let's fire up irb and see what we can fake. の記述のあとに
`require 'faker'`と書かれたサンプルコードが…！

irbで`require 'faker'`すると`true`と帰ってきた。
再度`Faker::Name.name`を実行すると、無事`"Miss Lonnie Hermiston"`と結果が返ってきた。

**Comment by n0h0** [comment]
railsプロジェクトで使用していたときは、`require`してなかったので、"rails gem require"で検索すると[railsのgemの自動で読み込む仕組みを解説した記事](http://onody-onody.hatenablog.com/entry/2016/03/06/165823)があった。
fakerもこの前提があったので、`require`について書いてなかったのかも…。
でもハマるのはハマったので書いていて欲しい。

**Comment by n0h0** [comment]
## 報告したいこと
READMの[Installing](https://github.com/stympy/faker#installing)は成功した。
じゃあ取り敢えず動かしてみるかってなったときに、[Usage](https://github.com/stympy/faker#usage)の欄を観てみてる。`Faker::Name.name`とあったので、irbで打ち込んで実行してみると
```
irb(main):001:0> Faker::Name.name
NameError: uninitialized constant Faker
	from (irb):1
	from /Users/n0_h0/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```
とエラーになってしまった。
これは`require 'faker'`がなかったために起きてしまったエラーであったが、その記述があると良いと思った。

**Comment by n0h0** [comment]
あと、Rubyのどのバージョンで使えるかの記述もなかった…。
[rubygems](https://rubygems.org/gems/faker/versions/1.8.4)のページに記述されていたが、githubのREADMEにも欲しいと思った。

**Comment by ashie** [comment]
じゃあ、一個ずつ進めましょう。それぞれ別々のissueとして登録するのが良いと思います。一問題一isueで！

**Comment by ashie** [comment]
>これはrequire 'faker'がなかったために起きてしまったエラーであったが、その記述があると良いと思った。

具体的に、Usageのところにどう書かれていたら嬉しかった、という修正例を書いてあげると、開発者にとってわかりやすいと思いました

**Comment by n0h0** [comment]
現在こうなっているのを
# Usage
```ruby
Faker::Name.name      #=> "Christophe Bartell"

Faker::Internet.email #=> "kirsten.greenholt@corkeryfisher.info"
```

こうしたい
# Usage
```ruby
require 'faker'

Faker::Name.name      #=> "Christophe Bartell"

Faker::Internet.email #=> "kirsten.greenholt@corkeryfisher.info"
```

**Comment by ashie** [comment]
どうやって報告したら良いかを調べてみよう！

**Comment by n0h0** [comment]
READMEのContributingの欄に[CONTRIBUTING.md](https://github.com/stympy/faker/blob/master/CONTRIBUTING.md)のリンクがあったので見てみる。

**Comment by n0h0** [comment]
"Add a test for your change. Only refactoring and documentation changes require no new tests. If you are adding functionality or fixing a bug, we need a test!"の記述があった。

**Comment by ashie** [comment]
今回の場合はGItHub上でpull requestを受け付けているようですし、issueも普通に使われているようなので、GitHub上での報告で問題無さそうですね！

**Comment by ashie** [comment]
pull requestでいく、とのこと

**Comment by ashie** [comment]
ブランチ名で悩んでいるとのこと「報告したいこと」にタイトルをつけましょう！これがそのままブランチ名に使えると思います。

**Comment by n0h0** [comment]
fakerリポジトリをforkボタンを押してforkする。
その後、できた[リポジトリ](https://github.com/n0h0/faker)を
`git clone git@github.com:n0h0/faker.git`
で手元に持ってきた。

**Comment by n0h0** [comment]
`master`から`fix_usage_document`という名前でブランチを作成した。

**Comment by n0h0** [comment]
コミットの練習。
`git commit`して開かれるエディタ上で編集すれば、PRのタイトルと本文をコミットの段階で生成できるのは知らなかったので感動

**Comment by n0h0** [comment]
実際に送る本文を考える

**Comment by n0h0** [comment]
英語が駄目なので、まず可能な限りシンプルな日本語にしてみる。

**Comment by ashie** [comment]
今回の場合

> これはrequire 'faker'がなかったために起きてしまったエラーであったが、その記述があると良いと思った。

ここはコミットの内容で伝わるので、前半部分だけ伝えてあげると良いと思いました！

> じゃあ取り敢えず動かしてみるかってなったときに、Usageの欄を観てみてる。Faker::Name.nameとあったので、irbで打ち込んで実行してみると
> 
> irb(main):001:0> Faker::Name.name
> NameError: uninitialized constant Faker
> 	from (irb):1
> 	from /Users/n0_h0/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
> 
> とエラーになってしまった。

**Comment by n0h0** [comment]
## 本文の内容
実行しようとした。
Usageを読む。
Faker::Name.nameとあったので、irbで実行する。
```
irb(main):001:0> Faker::Name.name
NameError: uninitialized constant Faker
	from (irb):1
	from /Users/n0_h0/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```
エラーが出た。

**Comment by ashie** [comment]
↑英語に訳しやすいように、情報が欠落しないレベルでシンプルな文章にした！

**Comment by n0h0** [comment]
## 本文の内容（英語）
I read Usage and tried to do it on irb as follows.
```ruby
irb(main):001:0> Faker::Name.name
```
An error was output.
```ruby
NameError: uninitialized constant Faker
	from (irb):1
	from /Users/n0_h0/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```

**Comment by n0h0** [comment]
作成した文でコミットする

**Comment by n0h0** [comment]
プッシュした。

**Comment by n0h0** [comment]
プルリクエストをつくる。https://github.com/stympy/faker/pull/1013
ドキドキ…。

**Comment by n0h0** [comment]
今度はRubyのバージョンの記述やってみる。

**Comment by n0h0** [comment]
## 本文の内容
Rubyのバージョン情報がないのは不親切です。

**Comment by ashie** [comment]
↑最初はネガティブな表現だったけど、ポジティブな表現に直した。そのほうが開発者が気分良くPRを受け取れることが多いと思ったので。

**Comment by n0h0** [comment]
## 本文の内容（英語)
### Add version information of Ruby
It is kind to have Ruby version information description.

**Comment by ashie** [comment]
↑他のライブラリを参考にして、要求するRubyのバージョンに関して記述があった方が良いと思ったとのこと。

そのライブラリの情報をここに残そう！

**Comment by n0h0** [comment]
[paperclip](https://github.com/thoughtbot/paperclip)の記述を参考。

**Comment by n0h0** [comment]
`master`から`add_version_requirement_of_ruby`との名前でブランチを切り出す。

**Comment by ashie** [comment]
> ↑最初はネガティブな表現（〜が無いのは不親切）だったけど、ポジティブな表現に直した。そのほうが開発者が気分良くPRを受け取れることが多いと思ったので。

英訳するときに、結局この部分まるごと要らないね！ということになった。

**Comment by n0h0** [comment]
コミットしてプッシュする。https://github.com/n0h0/faker/tree/add_version_requirement_of_ruby

**Comment by ashie** [comment]
↑スタイルが周りと違ってたので直してもらった（headingの前後に空行）

**Comment by n0h0** [comment]
プルリクエストをつくる。https://github.com/stympy/faker/pull/1014

**Comment by tjnet** [comment]
今回、課題を見つけるworkshopでしたが、すでにある課題に取り組むと入りやすいかもしれません。これとか、、？

[New Feature: Non-Random distribution · Issue #802 · stympy/faker](https://github.com/stympy/faker/issues/802)

**Comment by tjnet** [comment]
気持ち萎えそうなときは、これ見てテンション上げてました

http://developer.hatenastaff.com/entry/opensource-activity

**Comment by kou** [comment]
お疲れ様でした！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料として高専生・学生向けに実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
