### ISSUE TITLE
OSS Gate Workshop: Kosen: 2017-09-02: Taillook: SDWebImage Work log

### ISSUE THREAD

**Issue by Taillook** [oss-gate/workshop#556]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tjnet** [comment]
田中純 @tjnet といいます。よろしくお願いします! SDWebImage 楽しみですね!

**Comment by Taillook** [comment]
丸尾一真 @Taillook といいます．よろしくお願いします！

**Comment by Taillook** [comment]
SDWebImageと検索した
GitHubのページが見つかった
https://github.com/rs/SDWebImage

**Comment by Taillook** [comment]
READMEのLicensesの項目を見るとMITLicenseであることがわかった

**Comment by Taillook** [comment]
リポジトリをクローンした

**Comment by tjnet** [comment]
なんか、こうあれですねえ。"開発"への参加の敷居がちょっと高いライブラリかなと思います

- How to contributionみたいなDocsがあるとか。(あるのかな?)

- ReactiveSwiftみたいにPlaygroundで簡単に色々できるとか
https://github.com/ReactiveCocoa/ReactiveSwift#playground

**Comment by Taillook** [comment]
CONTRIBUTING.mdが探しづらかった

**Comment by tjnet** [comment]
なるほど、ここにあるんですね。READMEに書いてあげても良い気もしますね。

[SDWebImage/CONTRIBUTING.md at master · rs/SDWebImage](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)

**Comment by tjnet** [comment]
手元でビルドしきるとこまで持っていって、わかりにくかった記述、足りない記述があればそれをフィードバックしてあげるとか

**Comment by tdtds** [comment]
いまなにをやっているかを、もっと細かくメモにとりましょう。なにかエラーが出たらそのログを貼りましょう。

**Comment by Taillook** [comment]
Examplesを実行する

**Comment by Taillook** [comment]
ExamplesをビルドするとApple LLVM 8.1 Error Groupというエラーが出た

**Comment by ashie** [comment]
> CONTRIBUTING.mdが探しづらかった

これを探そうと思った理由があると良いと思いました
（あとから振り返ると、「まず動かす」というアクションに至る情報が足りていなくて、アクションに飛躍があるように見えました）

**Comment by Taillook** [comment]
Apple LLVM 8.1 Error Groupについて他の人がissueで書いていないか調べる

**Comment by selmertsx** [comment]
https://github.com/rs/SDWebImage/blob/master/Docs/ManualInstallation.md

**Comment by Taillook** [comment]
https://github.com/rs/SDWebImage#installation-by-cloning-the-repository
これを実行した

**Comment by Taillook** [comment]
https://github.com/rs/SDWebImage#installation-by-cloning-the-repository
のOther Linker Flagsがリンク切れになっていた

**Comment by tjnet** [comment]
なるほど! もうこれPull Request出しちゃっていいと思いますよ 😄  mergeされるはず...

**Comment by tjnet** [comment]
これ、僕がAlamofireObjectMapperのドキュメントを修正したときの例なのですが、issueは、こんな感じで書いてあげると良いかと。

[Extra Argument in call error · Issue #166 · tristanhimmelman/AlamofireObjectMapper](https://github.com/tristanhimmelman/AlamofireObjectMapper/issues/166)

あと要素としてあった方がいいのは

- やったこと
- やっていないこと
- 期待している結果を書く

**Comment by tjnet** [comment]
https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md#reporting-issues

ここ見ると、重複しているissue上げないでねって書いてますが、ドキュメント明らかに間違ってるので、
今回は気にしなくて良いと思います。

リポジトリによっては、セキュリティの問題とかはissueにいきなり書かずにメールで開発元にフィードバックしてください。みたいな話があるので、どこにフィードバックするかは気にした方が良いと思います。大体はドキュメントのどこかに書いてあることが多いです。メジャーなプロダクトなら。

**Comment by tjnet** [comment]
適当に検索しましたが、今回のissueだとこれくらいのvolumeで十分だと思いますねえ
https://github.com/wootapa/watable/issues/34

**Comment by tjnet** [comment]
正直、英語は通じれば良いと思います。僕も英語苦手ですが、ちゃんとフィードバック返ってくるので、、

**Comment by Taillook** [comment]
["Other Linker Flags"](https://camo.githubusercontent.com/605afda81ea172bf876f8c52a7002ffebb27dd3a/687474703a2f2f646c2e64726f70626f782e636f6d2f752f3132333334362f5344576562496d6167652f31305f6f746865725f6c696e6b65725f666c6167732e6a7067) in [https://github.com/rs/SDWebImage#installation-by-cloning-the-repository](https://github.com/rs/SDWebImage#installation-by-cloning-the-repository) is link expired.
Want more information.

**Comment by tjnet** [comment]
"Other Linker Flags" in https://github.com/rs/SDWebImage#installation-by-cloning-the-repository is 404(not found).
where should I access to see latest document?

**Comment by tjnet** [comment]
issueタイトルは "Other Linker Flags" setting is not found とか、、

**Comment by tjnet** [comment]
ひとつ貢献しちゃいましたね、、、すごい!
["Other Linker Flags" setting is not found · Issue #2012 · rs/SDWebImage](https://github.com/rs/SDWebImage/issues/2012)

**Comment by Taillook** [comment]
# "Other Linker Flags" setting is not found

### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description
["Other Linker Flags"](https://camo.githubusercontent.com/605afda81ea172bf876f8c52a7002ffebb27dd3a/687474703a2f2f646c2e64726f70626f782e636f6d2f752f3132333334362f5344576562496d6167652f31305f6f746865725f6c696e6b65725f666c6167732e6a7067) in https://github.com/rs/SDWebImage#installation-by-cloning-the-repository is 404(not found).
where should I access to see latest document?

というissueを出した

**Comment by tjnet** [comment]
PRのタイトルはこれにする？
”When user is using "yes".boolValue ,  return false”

**Comment by Taillook** [comment]
”When using "yes".boolValue , return false”
こんな感じですかね

**Comment by tjnet** [comment]
そうですね。descriptionは、、こんな感じ？
https://github.com/ReactiveCocoa/ReactiveSwift/pull/496

**Comment by tjnet** [comment]
タイトルはWhen using "yes".boolValue , return trueにしましょう。

**Comment by Taillook** [comment]
"When using "yes".boolValue , return true - issue #863"

これにします

**Comment by Taillook** [comment]
https://github.com/SwiftyJSON/SwiftyJSON/pull/884
プルリクを出しました

**Comment by piroor** [comment]
躓いた所を見逃さずにフィードバックに繋げたことが何より素晴らしいです！

口頭で述べたこと：

 * 躓いた「理由」「動機」の記述があると、見る側もアドバイスをしやすくなります。報告の内容にも、動機が書いてあると「その使い方は想定していなかった」や「その動機ならこの機能を使うのが適切」といった誘導を受けられることが期待されます。
 * 今回のissueとPRは「実際に起こっていること」と「PR後に起こること」をそのまま表現していますが、issue, PRのタイトルでは自分は「XXX should return YYY」のような表現を使うことが多いです。これだと、期待される状態と実際の状態があるということ、その実際の状態は期待される状態に反しているという文脈が読み取りやすくなるかなと思っています。

**Comment by kou** [comment]
お疲れ様でした！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料として高専生・学生向けに実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
