### ISSUE TITLE
OSS Gateワークショップ 2016-6-11: MKenta: td-client: 作業ログ

### ISSUE THREAD

**Issue by MKenta** [oss-gate/workshop#56]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by MKenta** [comment]
README読みながらinstallする `gem install td-client`

**Comment by MKenta** [comment]
bundleで入れようとしたらgem installだった(勝手にハマった)
`run in your console` とか書くと親切かも

**Comment by MKenta** [comment]
Configuration読みながらやってるけど実際にコピペですぐに使えない書き方されてるの若干不親切な感じがする

**Comment by MKenta** [comment]
TreasuredataからAPI key取ってくる、公式のなんだし公式のAPI取ってこれるURLをREADMEに書くと便利

**Comment by MKenta** [comment]
Getting Started見ながらやっても想像で補わなきゃいけない部分があってつらい。
method名しか書かれてなくてクラス名を書かなきゃいけない。
備考: 想像のして間違えた結果
``` text
irb(main):002:0> Treasuredata.initalize('389/e492f0f4d2159c7db606e5177c7d9d7134835a4b')
NameError: uninitialized constant Treasuredata
	from (irb):2
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

**Comment by MKenta** [comment]
実行環境:
```
[kenta.miyachi]% ruby -v                                                                                                 [~/OSSWS]
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
[kenta.miyachi]% gem -v                                                                                                  [~/OSSWS]
2.4.5.1
```

**Comment by MKenta** [comment]
githubのdescriptionに公式ドキュメントへのlink貼るならREADMEにも貼れば便利なのに

**Comment by MKenta** [comment]
明らかに `td` に依存してるのにユーザーにそれをわかってる前提でREADME書かれてる。

**Comment by MKenta** [comment]
`td-client` の説明見てるのに公式のドキュメント見たら `td` の話し始めた。

**Comment by MKenta** [comment]
それぞれの役割とかをREADMEなり公式ドキュメントやらに書いておくとわかりやすい

**Comment by MKenta** [comment]
公式ドキュメントにはクラス名とか詳しく書かれてるから別にtd-clientのREADMEにも書いておけば便利っぽい

**Comment by MKenta** [comment]
ドキュメント通りやってたらエラー

```text
irb(main):012:0> cln.databases.each { |db|
irb(main):013:1*   db.tables.each { |tbl|
irb(main):014:2*     p tbl.db_name
irb(main):015:2>     p tbl.table_name
irb(main):016:2>     p tbl.count
irb(main):017:2>   }
irb(main):018:1> }
TreasureData::AuthError: List databases failed: Failed to Login
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/td-client-0.8.81/lib/td/client/api.rb:640:in `raise_error'
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/td-client-0.8.81/lib/td/client/api/database.rb:12:in `list_databases'
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/td-client-0.8.81/lib/td/client.rb:73:in `databases'
	from (irb):12
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

**Comment by MKenta** [comment]
`Failed to Login` なのでインスタンス生成時に何かコケてるっぽいけどAPIKeyは合ってる。
今回はYBIを通してTreasuredataを使ってるのでそれが原因っぽい。

``` text
 @host="api.treasure-data.com",
```

**Comment by MKenta** [comment]
`td-client` の方にはAPI endpoint の設定方法が書いてあった。今までtdの公式ドキュメントを呼んでたので流れがめんどくさい `td-clientのREADME -> tdのドキュメント -> td-clientのREADME` って戻ってきた

**Comment by MKenta** [comment]
https://github.com/oss-gate/workshop/issues/56#issuecomment-225331421 で書いたAPI Keyを取得するURLはYBIのAPI Keyを取得するURLなので環境によって違うっぽい。defaultのendpointごとのAPI Key取得URLをREADMEには書くべき。

**Comment by MKenta** [comment]
`opts.merge({:endpoint => "https://api-alternate.treasuredata.com"} `でendpoint設定できるよ！ってREADMEに書かれてるけどどこのmethodなのかわかりづらい
察しようとしたけど無理だった

```
irb(main):020:0* opts.merge({:endpoint => "https://api-alternate.treasuredata.com"})
NameError: undefined local variable or method `opts' for main:Object
	from (irb):20
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
irb(main):021:0> cln.
irb(main):022:0* cln.opts.merge({:endpoint => "https://api-alternate.treasuredata.com"})
NoMethodError: undefined method `cln' for #<TreasureData::Client:0x007f9e8c4b8750>
	from (irb):22
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
irb(main):023:0> cln.merge({:endpoint => "https://api-alternate.treasuredata.com"})
NoMethodError: undefined method `merge' for #<TreasureData::Client:0x007f9e8c4b8750>
	from (irb):23
	from /Users/kenta.miyachi/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

**Comment by MKenta** [comment]
環境変数でも設定できるっぽいのでそっちでやる...

**Comment by MKenta** [comment]
Running Testってよりかは実際にtd-clintでコードを書いた時に、specファイルを書くときに有用なgemの話なので若干README不親切

**Comment by MKenta** [comment]
作業と感想をセットでメモする

**Comment by MKenta** [comment]
READMEの各順番がおかしい。先にどんなoptがあるのかを明確に書けばわかりやすいっぽい。
```
ops = Hash.new
ops.merge 
initalize (key, ops)
```
で書ける?

**Comment by MKenta** [comment]
ybiのendpointはこっち http://ybi.jp-east.idcfcloud.com
opsにhashでendpoint埋め込んでインスタンス生成する

**Comment by MKenta** [comment]
いけた。
``` text
opts = Hash.new
opts = opts.merge({:endpoint => "http://ybi.jp-east.idcfcloud.com"})
cln = TreasureData::Client.new('API_KEY',opts)
```

**Comment by MKenta** [comment]
不満点
- READMEの順番が不親切
- インスタンス生成時( `initialize(apikey, opts={}) (constructor)` )にoptsの書き方がないのでそれを追記したい
- 具体的には https://github.com/oss-gate/workshop/issues/56#issuecomment-225337694 っぽく

**Comment by MKenta** [comment]
rdocをmdに書き換える...?

**Comment by MKenta** [comment]
READMEがrdocでつらい問題

**Comment by MKenta** [comment]
https://github.com/kirkbowers/rdoc2md

**Comment by MKenta** [comment]
rdoc2mdでREADME.md化

**Comment by MKenta** [comment]
forkしてbranch切ってREADME.rdocを変換した。PR書く。

**Comment by MKenta** [comment]
Convert README.rdoc to Markdown using [rdoc2md](https://github.com/kirkbowers/rdoc2md)

**Comment by MKenta** [comment]
rdocからmdに変換する理由

**Comment by MKenta** [comment]
markdownだったら別のドキュメントを書き換えてやるっていう気持ちを伝える

**Comment by MKenta** [comment]
それをPRのコメントに書くとよりmergeされやすい。

**Comment by MKenta** [comment]
その後にどこを書き換えようとしているのかを伝えると尚良。

**Comment by MKenta** [comment]
ドキュメントが壊れていないかをURLなどを貼って確認する/させる。
[本家](https://github.com/treasure-data/td-client-ruby)
[fork先](https://github.com/MKenta/td-client-ruby/tree/replace-README)

**Comment by MKenta** [comment]
リンクより画像を貼っておくと吉

**Comment by MKenta** [comment]
* commitするようなOSSの管理者は忙しいのでそれを考慮したPRを書く。

**Comment by MKenta** [comment]
convertしたmarkdownと本家rdocで差がないかなーって見てたらそもそも本家のrdoc記法に漏れがあるのを見つけた
https://github.com/treasure-data/td-client-ruby#additional-user-agents

**Comment by MKenta** [comment]
mdにならないならならないでhttps://github.com/oss-gate/workshop/issues/56#issuecomment-225341099 のPRを送れば良い

**Comment by MKenta** [comment]
ちゃんと変換できてるのを確認したから今度こそPR書く

**Comment by MKenta** [comment]
他の人がplease, review it.って語尾につけてるの結構いいかも、そこまで必須のPRではないし、作者が好き好んでrdocを書いている可能性もあるし

**Comment by MKenta** [comment]
PR出しました 🎉

**Comment by kou** [comment]
お疲れさまでした！
