### ISSUE TITLE
OSS Gateワークショップ 2016-06-11: suemoc: capybara: 作業ログ

### ISSUE THREAD

**Issue by suemoc** [oss-gate/workshop#57]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by suemoc** [comment]
* README読む

**Comment by suemoc** [comment]
- README長い
- 英語か...

**Comment by suemoc** [comment]
> Ask on the mailing list (please do not open an issue on GitHub)

質問はissueじゃなくてMLでやるらしい

**Comment by suemoc** [comment]
- テスト用途以外はあまり想定していない？

**Comment by suemoc** [comment]
↑ 用途(Using~)がrspecなどのテストライブラリばっかだったので

**Comment by suemoc** [comment]
- テスト以外(クロールとか)にも使いたいのでそれが実現するような流れでいく
- Setup -> Drivers

**Comment by suemoc** [comment]
- 活発に開発されているのか確かめたいので最終コミットや開発者を見てみる
- 最終コミットは今月！

<img width="500" alt="2016-06-11 11 21 52" src="https://cloud.githubusercontent.com/assets/2887750/15982615/e2eede8a-2fc6-11e6-915e-473c3dbc192c.png">

- 今日の進行の方が！！

**Comment by suemoc** [comment]
- インストールする
- rubyは2.3.0
- bundle
- macが遅い気がする
- 早く新機種出て欲しい
- 全てnokogiriのせい
- スモールnokogiri作りたい
- 問題なくbundle完了

**Comment by suemoc** [comment]
- ドライバはpoltergeistを使いたい
- 時代はheadlessなので
- capybara-webkitとそこまで比較したことないのでしてみてもいいかも(後で)

**Comment by suemoc** [comment]
- capybaraだけインストールしても何もできない
- 悲しい
- poltergeist入れて動作確認する

**Comment by suemoc** [comment]
- poltergeist入れた
- 成功

**Comment by suemoc** [comment]
- poltergeist使って適当なサイトをクロールしてみる
- poltergeistの使い方はcapybaraではなくpoltergeistのドキュメントを読む必要がある
https://github.com/teampoltergeist/poltergeist

**Comment by suemoc** [comment]
- poltergeistのREADME読む
> It allows you to run your Capybara tests on a headless WebKit browser

- capybara testのためと明言されている

**Comment by suemoc** [comment]
- phantomjsのインストール方法書いてあるの親切

**Comment by suemoc** [comment]
- 使い方は書いてあるけどサンプルコードみたいなものは無い
- `example.com`にアクセスするやりかたとか書いてあってもいいかも

**Comment by suemoc** [comment]
- yahooにアクセスしてみる

**Comment by suemoc** [comment]
- オンラインゲームの操作を自動化したい

- そのために
 - リンクをたどる
 - フォーム入力
 - セッション保持
 - GET/POST
 - JavaScriptの実行
 - スクリーンショット
 - スクレイピング

**Comment by suemoc** [comment]
- やりたいことができるか？READMEからそれが判断できるか？

- リンクをたどる : https://github.com/jnicklas/capybara#clicking-links-and-buttons
- フォーム入力 : https://github.com/jnicklas/capybara#interacting-with-forms
- セッション保持 : 
  - https://github.com/jnicklas/capybara#named-sessions
  - https://github.com/jnicklas/capybara#using-the-sessions-manually
  - できそうだが基本の使い方は書いてない(driverに依存する？)
- GET/POST : 
  - https://github.com/jnicklas/capybara#navigating
  - The visit method only takes a single parameter, the request method is always GET.
  - POSTできない
- JavaScriptの実行 : https://github.com/jnicklas/capybara#scripting
- スクリーンショット : https://github.com/jnicklas/capybara#debugging
- スクレイピング :  
  - https://github.com/jnicklas/capybara#xpath-css-and-selectors
  - DOMセレクタの使い方は分かる

**Comment by suemoc** [comment]
master ビルド落ちてる

**Comment by suemoc** [comment]
### セッションについて深掘り
- 探し方ログ
  - 目次に「Named sessions」「Using the sessions manually」の項目がある
  - capybaraにおけるセッションは基本名前無し、マニュアルで制御はしないもの？という推測ができる
  - 推測しなくても分かるようにREADMEに書いてあるといい

**Comment by suemoc** [comment]
## 何をして欲しいか
capybara READMEの主な機能説明にセッション管理に対応していることを書いて欲しい

## 理由
- ログインが必要なテスト/クローラー実装に使えるか判断したい
- 今のREADMEからはセッション管理の応用方法(Named session, Manually Session)は分かるがデフォルトでセッションにどのように対応しているのかが分からない

**Comment by suemoc** [comment]
v2
## 何をして欲しいか
READMEにセッションにどのように対応しているか追記してほしい
- セッション対応に実装は必要か(必要ならサンプルコードが欲しい)
- セッション対応が利用するdriverに依存しているならその記述

## 理由
- ログインが必要なテスト/クローラー実装に使えるか判断したい
- 今のREADMEからはセッション管理の応用方法(Named session, Manually Session)は分かるがデフォルトでセッションにどのように対応しているのかが分からない

**Comment by suemoc** [comment]
- 方針転換
READMEのNamed sessionsに「どのようにセッション対応してるか」「driverがセッション生成する」ことが書いてあった
追記するのではなく、見出しを正しく内容を表すものにすれば分かりやすくなるのでは

**Comment by suemoc** [comment]
- diff作った

**Comment by suemoc** [comment]
- PR文章

`Named sessions`より`Using sessions`という見出しのほうが正しく内容を表している
`Named sessions`セクションにはnamed sessions以外にもCapybaraがどのようにセッション対応しているか書いてある

**Comment by suemoc** [comment]
`Using sessions` is better heading than `Named sessions`.
The section discribe how Capybara managed sessions.

**Comment by suemoc** [comment]
- PR内容変更

Named sessionsのセクションは消さずに１段下げる
Named sessionsとManually sessionsを囲むセクションとしてUsing sectionsを入れる

**Comment by suemoc** [comment]
Capybaraのセッション管理内容が目次から参照しやすいように
`Named sessions`、`Using the sessions manually`セクションを
`Using sessions`セクションでまとめました。

**Comment by suemoc** [comment]
Surround the `Named sessions` and `Using the sessions manually` section in `Using sessions`,
To make it easier to look for how Capybara managed sessions.

**Comment by kou** [comment]
お疲れさまでした！
