### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-9-30: chiroruxx: fzaninotto/Faker : Work log

### ISSUE THREAD

**Issue by chiroruxx** [oss-gate/workshop#574]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: Tokyo: 2017-9-30: chiroruxx: fzaninotto/Faker
: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by y-goto** [comment]
よろしくです

**Comment by chiroruxx** [comment]
[fakerで検索](https://www.google.co.jp/search?q=faker&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=0&ei=0wLPWaeDK6SL8QeR3KeoAg) すると韓国人が出てくる・・・・

**Comment by chiroruxx** [comment]
[faker phpで検索](https://www.google.co.jp/search?client=firefox-b-ab&dcr=0&q=faker+php&oq=faker+php&gs_l=psy-ab.3...45977.46656.0.47368.4.4.0.0.0.0.202.361.0j1j1.2.0.dummy_maps_web_fallback...0...1.1.64.psy-ab..2.1.158...0.0.A9KqRA7syps) で検索すると[GitHub](https://github.com/fzaninotto/Faker)ページがヒットした。

**Comment by chiroruxx** [comment]
[installation](https://github.com/fzaninotto/Faker#installation)を発見

**Comment by chiroruxx** [comment]
とりあえず作業ディレクトリ作ります・・・

**Comment by chiroruxx** [comment]
C:\Users\username\project\fakerTest 作った

**Comment by chiroruxx** [comment]
`composer require fzaninotto/faker` 実行します。

```
'composer' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

**Comment by chiroruxx** [comment]
composer入れます・・・

**Comment by chiroruxx** [comment]
[composerで検索](https://www.google.co.jp/search?q=composer&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=0&ei=6ATPWeO4H_Td8AeFnpPoCQ)したらページヒット。
https://getcomposer.org/

**Comment by chiroruxx** [comment]
トップページにダウンロードリンク発見

**Comment by chiroruxx** [comment]
Windowsインストーラーがあるので落として入れます。

**Comment by chiroruxx** [comment]
`Developer mode` のチェックボックスがある・・・
アンインストーラーがつかないみたいなので、外して進める。
(composerの開発者用ってこと?)

**Comment by chiroruxx** [comment]
phpの実行パスをきかれたので、調べて入力。

**Comment by chiroruxx** [comment]
php.iniの更新をしないと進められないみたい。
でも自動でやってくれるようす。

**Comment by chiroruxx** [comment]
エラー出た。

```
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: 到達できないホストに対してソケット操作を実行しようとしました。
The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: そのようなホストは不明です。
failed to open stream: php_network_getaddresses: getaddrinfo failed: そのようなホストは不明です。
```

ネットワーク途中で切れたみたい。

**Comment by chiroruxx** [comment]
リトライ。無事にインストールできた様子。

**Comment by chiroruxx** [comment]
fakerのインストールに戻ります。

```
composer require fzaninotto/faker
```

**Comment by chiroruxx** [comment]
```
'composer' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

composerの最後に再ログインしてねって書いてあったので、再ログインします。

**Comment by chiroruxx** [comment]
```
Using version ^1.7 for fzaninotto/faker
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing fzaninotto/faker (v1.7.1): Downloading (100%)
Writing lock file
Generating autoload files

```

**Comment by chiroruxx** [comment]
無事に動いた様子。

**Comment by chiroruxx** [comment]
[Basic Usage](https://github.com/fzaninotto/Faker#basic-usage)があるのでやってみます。

**Comment by chiroruxx** [comment]
以下の部分だけ変更して実行してみます。

```php
<?php
require_once '/path/to/Faker/src/autoload.php';
```

↓

```php
require_once __DIR__ . '/vendor/fzaninotto/faker/src/autoload.php';
```

**Comment by chiroruxx** [comment]
```
Ruth Feeney339 Anderson Manors
New Jamie, PA 04244Quos beatae atque quos voluptas saepe doloribus. Quae iste autem facilis quasi. Vitae facilis culpa nostrum et dolor. Anim
i dolor dolore ipsam officia ut sed.
```

**Comment by chiroruxx** [comment]
BasicUsageの2個目も実行します。

```php
<?php
// require the Faker autoloader
require_once __DIR__ . '/vendor/fzaninotto/faker/src/autoload.php';
// use the factory to create a Faker\Generator instance
$faker = Faker\Factory::create();

for ($i=0; $i < 10; $i++) {
    echo $faker->name, "\n";
}
// Adaline Reichel
// Dr. Santa Prosacco DVM
// Noemy Vandervort V
// Lexi O'Conner
// Gracie Weber
// Roscoe Johns
// Emmett Lebsack
// Keegan Thiel
// Wellington Koelpin II
// Ms. Karley Kiehn V
```

結果は
```
Miss Joanny Farrell I
Isaias Gottlieb
Jodie King MD
Jackeline Medhurst
Prof. Lura Yundt
Wilfred Bartell
Myra Hauck
Otto Cassin
Kaia Gulgowski
Mrs. Raquel Little
```

ランダムになってますね。

**Comment by chiroruxx** [comment]
別の人の作ったCLIコマンドもあるみたい。
https://github.com/bit3/faker-cli

**Comment by chiroruxx** [comment]
https://github.com/fzaninotto/Faker#modifiers

楽しそうなのでやってみる。

**Comment by chiroruxx** [comment]
サンプルコード動かすときに毎回

```
<?php
// require the Faker autoloader
require_once '/path/to/Faker/src/autoload.php';
// alternatively, use another PSR-0 compliant autoloader (like the Symfony2 ClassLoader for instance)

// use the factory to create a Faker\Generator instance
$faker = Faker\Factory::create();
```

を自分で補完しないといけないのが面倒・・・

**Comment by chiroruxx** [comment]
サンプルコードがPSR-2に則っていない気がする。ちょっと読みづらい。

**Comment by chiroruxx** [comment]
フィードバックポイントを自分でわかるようにまとめる。

**Comment by chiroruxx** [comment]
BasicUsageの2つ目のサンプルコードと、Modifiers以降のサンプルコードが、Fakerインスタンスを作成する部分が省略されているので、コピペしても動かない。
でも、今説明したい部分を強調するために、わざと外しているのかも。

**Comment by chiroruxx** [comment]
サンプルコードがPSR-1/PSR-2に則ってないので読みづらい。最近のコードは則って書いてあるものが多いので、則って書いてほしい。

例：
```php
for ($i=0; $i < 10; $i++) {
```

to

```php
for ($i = 0; $i < 10; $i++) {
```

**Comment by chiroruxx** [comment]
サンプルコードのやつ

- 直編集してプルリク投げたほうがいいかも

コピペのやつ

- これからのサンプルコードはインスタンスの生成を省略してるよ。みたいな一文が欲しい
- 誰にとってやりづらいかを書く

**Comment by chiroruxx** [comment]
サンプルコードのやつは気のせいかも・・・(よく調べたらイコール前後のスペースについては言及されていなかった)

**Comment by chiroruxx** [comment]
[BasicUsage](https://github.com/fzaninotto/Faker#basic-usage)の2番目のサンプルコードから、オートロードとFaker/Factoryインスタンスの生成が省略されている。
初心者にとっては気づかない場合があるので、2番目のサンプルコードの前に、「以降のサンプルコードではオートロードとFaker/Factoryインスタンスの生成については省略する」旨を書いてほしい。

**Comment by chiroruxx** [comment]
最初に「I'm newby.」と書く

**Comment by chiroruxx** [comment]
とりあえず英語に。

I think this sample code in [readme.md](https://github.com/fzaninotto/Faker/blob/master/readme.md) is hard to understand for beginners because the code of auto loading and creating a `Faker/Factory` instance is omitted from 2nd sample code in [Basic Usage](https://github.com/fzaninotto/Faker#basic-usage).

So, this adds the sentence "After this sample code, they are omitted the code of auto loading and creating a `Faker/Factory` instance" before 2nd sample code.

**Comment by chiroruxx** [comment]
I think sample codes in [readme.md](https://github.com/fzaninotto/Faker/blob/master/readme.md) is hard to understand for beginners. Because the code of auto loading and creating a `Faker/Factory` instance is omitted from 2nd sample code in [Basic Usage](https://github.com/fzaninotto/Faker#basic-usage).

So, this adds kinder sentence before 2nd sample code. "After this sample code, they are omitted the code of auto loading and creating a `Faker/Factory` instance" .

**Comment by chiroruxx** [comment]
issue だしました・・・！！

https://github.com/fzaninotto/Faker/issues/1311

**Comment by piroor** [comment]
コーディングスタイルが不統一なのはそれだけで問題と言えるので（「リーダブルコード」などでも言及されていますね）、特に何かルールが無い部分であっても、気にせず指摘していいと思います。

サンプルコードを変えずに説明文で対応するというのは、変更対象をやたらに広げてしまわず小さい範囲に留める方法として有効で良いと思います。
あとは、#573 へのコメントとも重なるのですが、「〜ということなので、こう実装（解決）してみました」というPRを間をおかずに出したり、あるいはPRするつもりであることを表明しておくと、プロジェクト運営者が安心しやすくて良いと思います。

**Comment by knokmki612** [comment]
おつかれさまでした！いったんこちらのissueはクローズしますが、出したissueに変化があった時など、引き続きこちらに書いていくのもアリです！
