### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-09-30: koichiro.T: n(nodeバージョン管理) : Work log

### ISSUE THREAD

**Issue by KoichiroT** [oss-gate/workshop#576]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by syumikko** [comment]
よろしくお願いします。

**Comment by wotsushi** [comment]
よろしくお願いします！

**Comment by KoichiroT** [comment]
'node.js バージョン管理 n'で検索
(https://www.google.co.jp/search?q=node.js+%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E7%AE%A1%E7%90%86+n&oq=node.js+%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E7%AE%A1%E7%90%86+n&aqs=chrome..69i57.1064j0j4&sourceid=chrome&ie=UTF-8)

**Comment by KoichiroT** [comment]
qiitaの記事からgithubへの公式リンクが貼られていた
(https://qiita.com/bigplants@github/items/2d75bf552e0da4a7e822)

**Comment by KoichiroT** [comment]
githubのページにいって、ドキュメントを読む
(https://github.com/tj/n)

**Comment by KoichiroT** [comment]
ライセンスを探すがみつからない

**Comment by KoichiroT** [comment]
ライセンス条項発見
(License

(The MIT License)

Copyright (c) 2014 TJ Holowaychuk <tj@vision-media.ca>)

**Comment by KoichiroT** [comment]
同じページにあった
(https://github.com/tj/n)

**Comment by KoichiroT** [comment]
環境構築の方法を探す、英語難しい

**Comment by KoichiroT** [comment]
nodeの環境を作る
'node.js windows インストール'で検索
’https://qiita.com/akabei/items/43f9d6614d2d6d5b3730’を参考にインストール

**Comment by KoichiroT** [comment]
公式サイトからイントーラダウンロード
(https://nodejs.org/en/)

**Comment by KoichiroT** [comment]
https://nodejs.org/en/download/

windows64bit版

**Comment by KoichiroT** [comment]
ダウンロードした実行ファイルからインストール
ダイアログに従いyesをポチポチ

**Comment by KoichiroT** [comment]
インストール完了

**Comment by KoichiroT** [comment]
npmがつかえるか調べる
コマンドプロンプトから
'npm -v'が使えることを確認

**Comment by KoichiroT** [comment]
n パッケージをnpmを使わず
githubからソースコードを落としてlocal環境で
実行できる方法を調べる

**Comment by KoichiroT** [comment]
（https://github.com/tj/n）からソースをダウンロード

**Comment by KoichiroT** [comment]
nのリポジトリURLをgithubクライアントを使い
cloneする

**Comment by KoichiroT** [comment]
nodeのインストールドキュメントにはlinux前提の記載
しかないため、bash on ubuntu をいれてmakeしてnの実行環境を入れる方向にする

**Comment by KoichiroT** [comment]
’bash on ubuntu インストール’で検索
https://qiita.com/Aruneko/items/c79810b0b015bebf30bb
を参考にインストール

**Comment by KoichiroT** [comment]
下記ページを参考にbash on ubuntuをインストール
'https://qiita.com/Aruneko/items/c79810b0b015bebf30bb'

**Comment by KoichiroT** [comment]
インストールしたbash on ubuntu 上にnode.jsをインストールする
方法を調べる
'node uninstall windows'で検索

**Comment by KoichiroT** [comment]
インストールしたbash on ubuntu 上にnode.jsをインストールする
方法を調べる
'node install windows'で検索

**Comment by KoichiroT** [comment]
インストールしたbash on ubuntu 上にnode.jsをインストールする
方法を調べる
'node install bash on ubuntu'で検索

**Comment by KoichiroT** [comment]
下記ページを参考にbash on ubuntu 上にnode.jsをインストールする
'http://shigeo-t.hatenablog.com/entry/2016/06/25/024632'

**Comment by KoichiroT** [comment]
インストールされたか確認
'node -v'　だとnodeでエイリアス定義がないためエラー
正しくは'nodejs　-v'
でインストールされたバージョンが確認できた。

**Comment by KoichiroT** [comment]
bash on　ubuntu上に
'https://github.com/tj/n.git'からnパッケージをダウンロードする

**Comment by KoichiroT** [comment]
bash on ubuntu にダウンロードするgitの方法を調べる
'https://qiita.com/masamitsu-konya/items/abb572337156e4d003cf'を参考

**Comment by KoichiroT** [comment]
環境整えるのは時間が厳しいので先にフィードバックするためのissueを立てることにする

**Comment by KoichiroT** [comment]
issueを考える

**Comment by KoichiroT** [comment]
タイトル：README.mdのInstallationについて
本文：
githubからcloneしてリポジトリファイルから
インストールする場合の記載部分について、
makeコマンドを利用する方法が書かれているが
windowsだとmakeコマンドが使えない。

**Comment by KoichiroT** [comment]
問題点：
githubからcloneしてリポジトリファイルから
インストールする場合の記載部分について、
makeコマンドを利用する方法が書かれているが
windowsだとmakeコマンドが使えない。

ゴール：
windowsの場合でもリポジトリファイルからnパッケージを利用できるようにして欲しい。

解決策：

**Comment by KoichiroT** [comment]
タイトル
windows環境での、コピーしたリポジトリからのインストール

**Comment by KoichiroT** [comment]
問題点
githubからcloneして、コピーしたリポジトリから
インストールする方法について、README.mdのInstallationに
makeコマンドを利用する方法が書かれているが
windowsの場合、makeコマンドが使えない。

**Comment by KoichiroT** [comment]
ゴール
windowsの場合でもコピーしたリポジトリからnパッケージをインストールできるようにして欲しい。

**Comment by KoichiroT** [comment]
解決策
コピーしたリポジトリからのインストール手順にwindows環境の場合を追記する。

**Comment by KoichiroT** [comment]
nパッケージのissueテンプレート

# Issue Template:

### Describe issue including what OS you are using

_i.e. I'm using MacOS Sierra_

### Describe what version of N you have
_i.e. n --version output: 2.1.4_


### Describe how you installed N

* _i.e. npm install -g n_
* _i.e. make install_

### Steps to reproduce issue _1.2.3_
_i.e._
1. n latest
2. couldn't pull latest from source

### Describe the results you received

_i.e. blank screen_
### Describe the results you expected

_i.e. I was supposed to see the lastet being pulled from source_


### What version of npm you are using

_i.e. npm --version output: 4.0.5_

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`
* Output of `node -v:`

#### (paste your output here)

**Comment by KoichiroT** [comment]
タイトル
Installation from repo in windows

**Comment by KoichiroT** [comment]
タイトル
Installation from repo on windows

**Comment by KoichiroT** [comment]
### Describe issue including what OS you are using

I'm using windows10 64bit

### Describe what version of N you have

n --version output: 2.1.8_

### Describe how you installed N

-

### Steps to reproduce issue _1.2.3_

1. n latest
2. couldn't install latest from source on windows

### Describe the results you received

-

### Describe the results you expected

I want to be able to install n package from repo on windows.

### What version of npm you are using

not use

### Additional information you deem important (e.g. issue happens only occasionally):

Clone from github and from repo
For instructions on how to install, in the Installation of README.md
Although there is written a method to use the 'make' command, 
make command can not be used on windows.

Add the case of the windows environment to the installation procedure from repo.

#### (paste your output here)

none

**Comment by KoichiroT** [comment]
タイトル
Missing information how to install n from repo on Windows.

**Comment by KoichiroT** [comment]
Describe issue including what OS you are using
 I'm using windows10 64bit
Describe what version of N you have
 n --version output: 2.1.8_
Describe how you installed N
 from repo(not succeeded).
Steps to reproduce issue 1.2.3

Describe the results you received
 I want to be able to install n package from repo on windows.

What version of npm you are using
 not use
Additional information you deem important (e.g. issue happens only occasionally):

 Clone from github and from repo
 For instructions on how to install, in the Installation of README.md
 Although there is written a method to use the 'make' command,
 make command can not be used on windows.

 Add the case of the windows environment to the installation procedure from repo.
(paste your output here)
none

**Comment by y-goto** [comment]
お疲れ様です。Windows環境での動作はまだ多くのOSSが気にしていないことが多いので、いいフィードバックのねたになると思います。gitterとかで相談しながらぜひ続けてみてください。

**Comment by knokmki612** [comment]
おつかれさまでした！いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き文章の整理にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談してみるのもアリです！
