### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-09-30: noppo0831: jvectormap: Work log

### ISSUE THREAD

**Issue by noppo0831** [oss-gate/workshop#577]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by noppo0831** [comment]
```
git clone https://github.com/almasaeed2010/AdminLTE.git
```
AdminLTEを使用するとき、webpackでjvectormapのcss読み込みでエラーをはいたため

> https://github.com/almasaeed2010/AdminLTE/issues/1448

**Comment by noppo0831** [comment]
公式サイトにAtminLte Installationがある

> https://adminlte.io/docs/2.4/installation

**Comment by noppo0831** [comment]
```
npm install admin-lte --save
```

**Comment by noppo0831** [comment]
上のやつは修正されていたぽいので、

mimepullのメモリーリーク問題に変えます

> https://github.com/jersey/jersey/issues/3259

**Comment by noppo0831** [comment]
Gitのリポジトリを見つけた

> https://github.com/javaee/metro-mimepull

**Comment by noppo0831** [comment]
FIle.deleteOnExit()が原因みたいなので、最新のJavaで直っているかどうか確認する

**Comment by noppo0831** [comment]
org.jvnet.mimepull.MemoryData#createNext
内で、java.io.FIle#deleteOnExitを呼び出している。

java.io.FIle.deleteOnExitはFileのパスを引数にとって、
java.io.DeleteOnExitHookのprivate static LinkedHashSet<String> files = new LinkedHashSet<>();
にaddしている.

java.io.DeleteOnExitHookのfilesは、VMをリスタートしないと初期化されないため、
プロセスが起動し続ける限りfilesにpathを保持し続ける。

つまり、java.io.FIle#deleteOnExitを呼び出すとpathのサイズ分メモリを追加で圧迫し続ける。

java.io.DeleteOnExitHookのfilesはVMを再起動する以外通常初期化する方法がない（リフレクションを使用すればできるけど）

**Comment by noppo0831** [comment]
Javaの最新バージョンでのjava.io.FIle#deleteOnExitの挙動は確かめる（Java 7,8はhttps://github.com/oss-gate/workshop/issues/577#issuecomment-333279547の現象が起きた）

**Comment by noppo0831** [comment]
自分のmacにはjava9が入っていないため入れる

**Comment by noppo0831** [comment]
```
brew install jenv
```

.bashrcに下記を入れて、source ~/.bashrcを打つと失敗
```
if which jenv > /dev/null; then
  # JENV_ROOTがemptyの場合、'${HOME}/.jenv'がrootと設定される
  export JENV_ROOT=/usr/local/var/jenv
  eval "$(jenv init -)"
fi
```

```
mkdir: /usr/local/var/jenv/shims: Permission denied
mkdir: /usr/local/var/jenv/plugins: Permission denied
mkdir: /usr/local/var/jenv/versions: Permission denied
```

あきらめて、普通にjava9をインストールする

**Comment by noppo0831** [comment]
> https://github.com/gcuisinier/jenv
どおりにやる

**Comment by noppo0831** [comment]
```
git clone https://github.com/gcuisinier/jenv.git ~/.jenv
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bashrc
 ```

**Comment by noppo0831** [comment]
jenvではjavaのインストールができないっぽいので、java9をbrewで入れる

**Comment by noppo0831** [comment]
brewもjava9いれることができないっぽいので、公式からダウンロードする

> https://docs.oracle.com/javase/9/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-2FE451B0-9572-4E38-A1A5-568B77B146DE

にダウンロードリンクがない

**Comment by noppo0831** [comment]
> http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html
にdmgのリンクがあった

**Comment by noppo0831** [comment]
現象

* org.jvnet.mimepull.MemoryData#createNext(DataHead dataHead, ByteBuffer buf)をコールすると、メモリリークする

再現した環境
Java7 ,Java8, Java9(build 9+181)

原因

* org.jvnet.mimepull.MemoryData#createNextの下記のコードのtempFile.deleteOnExit();が原因

```
String suffix = config.getTempFileSuffix();
File tempFile = TempFiles.createTempFile(prefix, suffix, config.getTempDir());
// delete the temp file when VM exits as a last resort for file clean up
tempFile.deleteOnExit();
if (LOGGER.isLoggable(Level.FINE)) {
    LOGGER.log(Level.FINE, "Created temp file = {0}", tempFile);
}
```

tempFile.deleteOnExit()の実体は、java.io.File#deleteOnExitであり
java.io.File#deleteOnExitは内容は下記のコード
```
public void deleteOnExit() {
    SecurityManager security = System.getSecurityManager();
    if (security != null) {
        security.checkDelete(path);
    }
    if (isInvalid()) {
        return;
    }
    DeleteOnExitHook.add(path);
}
```

java.io.File#deleteOnExitの処理として、java.io.DeleteOnExitHook.add(path);が呼びだされる

DeleteOnExitHookの内容は下記の通り

```
static synchronized void add(String file) {
        if(files == null) {
            // DeleteOnExitHook is running. Too late to add a file
            throw new IllegalStateException("Shutdown in progress");
        }

        files.add(file);
}
```

java.io.DeleteOnExitHook#add内でfilesにStringをaddしており、filesは
javaVMが再起動するまで初期化されない。

よって、org.jvnet.mimepull.MemoryData#createNextが呼び出されるたびに、pathのサイズ分メモリが圧迫される。

**Comment by okkez** [comment]
deleteOnExit のやつは16年前からあるっぽい。 http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4513817

**Comment by noppo0831** [comment]
> http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6664633

にあるように、FileとDeleteOnExitHookを独自に実装して、File.deleteが呼びださたとき、DeleteOnExitHookのfilesから対象のパスを消すというアイディアもある。


だが、そもそもorg.jvnet.mimepull.MemoryData#createNextの処理のdataHead.dataFile = new DataFile(tempFile);がcloseされるときtmpfileはdeleteされるので、
DeleteOnExitHookはメモリリークを引き起こすので呼び出さないのが一番安全ではないか？

**Comment by noppo0831** [comment]
対策案：

1.
そもそもdataHead.dataFile = new DataFile(tempFile);がcloseされるときtmpfileはdeleteされる、
DeleteOnExitHookはメモリリークを引き起こすので呼び出さない

メリット：変更箇所が少ない
デメリット：dataHead.dataFile.closeが呼び出される前にVMがシャットダウンされると一時ファイルが残る

2. 
> http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6664633
にあるように、FileとDeleteOnExitHookを独自に実装して、File.deleteが呼びだされたとき、DeleteOnExitHookのfilesから対象のパスを消すというアイディアもある。

メリット：dataHead.dataFile.closeが呼び出される前にVMがシャットダウンされても一時ファイルが消える
デメリット：コードの変更箇所が多い

3.
2.と同じようにDeleteOnExitHookを継承したクラスにremoveを実装して、それをmimepull内でtmpFileをdelteしている部分で呼び出す。(おそらくorg.jvnet.mimepull.WeakDataFile#closeのみ)
File.deleteOnExitは呼び出さずDeleteOnExitHookの拡張クラスのaddを呼び出してpathをfilesにaddする。

メリット：  
2.よりはコード変更箇所が少なく、dataHead.dataFile.closeが呼び出される前にVMがシャットダウンされても一時ファイルが消える。  
デメリット：
1.よりコード変更箇所が多い

3の方法が既存の動作を変えず、コード変更量が少ないのでおすすめ。

**Comment by noppo0831** [comment]
Problem

* Calling org.jvnet.mimepull.MemoryData#createNext (DataHead dataHead, ByteBuffer buf) causes memory leak.

environment
Java 7, Java 8, Java 9 (build 9 + 181)

Cause

caused by "tempFile.deleteOnExit ();" of "org.jvnet.mimepull.MemoryData#createNext"

`` `
String suffix = config.getTempFileSuffix ();
File tempFile = TempFiles.createTempFile (prefix, suffix, config.getTempDir ());
// delete the temp file when VM exits as a last resort for file clean up
tempFile.deleteOnExit ();
if (LOGGER.isLoggable (Level.FINE)) {
    LOGGER.log (Level.FINE, "Created temp file = {0}", tempFile);
}
`` `

"tempFile.deleteOnExit ()" has the following code
`` `
public void deleteOnExit () {
    SecurityManager security = System.getSecurityManager ();
    if (security! = null) {
        security.checkDelete (path);
    }
    if (isInvalid ()) {
        return;
    }
    DeleteOnExitHook.add (path);
}
`` `

"java.io.DeleteOnExitHook.add (path);" is called as the processing of "java.io.File#deleteOnExit"

The contents of "DeleteOnExitHook # add" are as follows

`` `
static synchronized void add (String file) {
        if (files == null) {
            // DeleteOnExitHook is running. Too late to add a file
            throw new IllegalStateException ("Shutdown in progress");
        }

        files.add (file);
}
`` `

"String files" is "add" to "files" in "java.io.DeleteOnExitHook#add", "files" is
It is not initialized until javaVM restarts.

Therefore, each time "org.jvnet.mimepull.MemoryData#createNext" is called, memory of the size of "String path" is compressed.

Proposed countermeasure:


1.
Initially "tempfile" is deleted when "dataHead.dataFile = new DataFile (tempFile);" is "closed".
Therefore, "DeleteOnExitHook" will cause memory leak, so it will not be called

Advantages: There are few changes
Disadvantage: A temporary file remains when the VM is shut down before "dataHead.dataFile.close" is called


2.
> http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6664633

There is an idea in the above URL.
There is also an idea to extend "File" and "DeleteOnExitHook" and remove the target path from DeleteOnExitHook files when "File.delete" is called.

Benefit: temporary files do not disappear even if VM is shut down before dataHead.dataFile.close is called
Disadvantage: There are many changes in the code


3.
Like 2., we implement remove in the class that inherited DeleteOnExitHook and call it in the part that delivered tmpFile in mimepull. (Perhaps "org.jvnet.mimepull.WeakDataFile#close" only)
It does not call File.deleteOnExit, it calls add of DeleteOnExitHook extension class and adds path to files.

merit: 
2. There are fewer code changes than 2., temporary files disappear even if the VM is shut down before dataHead.dataFile.close is called.
Demerit:
1. There are more code change parts than 1.

3 method does not change the existing behavior, so it is recommended because the code change amount is small.

**Comment by knokmki612** [comment]
おつかれさまでした！いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き文章の整理やフィードバックした時の報告にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談/報告するのもアリです！
