### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-09-30: bitmansuzki: civetweb: Work log

### ISSUE THREAD

**Issue by suzukibitman** [oss-gate/workshop#578]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by y-goto** [comment]
よろしく

**Comment by suzukibitman** [comment]
よろしくおねがいします！

**Comment by suzukibitman** [comment]
civetwebのページ
https://github.com/civetweb/civetweb/blob/master/LICENSE.md

**Comment by suzukibitman** [comment]
▲civetwebで調べてらあった

**Comment by suzukibitman** [comment]
READMEがあった
[README](https://github.com/civetweb/civetweb/blob/master/README.md)

**Comment by suzukibitman** [comment]
インストールの方法は下記です。

OS X

This pre-built version comes with Lua, IPV6 and SSL support.

Download the latest Civetweb.dmg from SourceForge
Click on the it and look for the attachment in the finder.
Drag Civetweb to the Applications folder.
When started, Civetweb puts itself into top menu.
Linux

Download the latest civetweb.tar.gz from SourceForge
Open archive and change to the new directory.
make help
make
make install
Run the program /usr/local/bin/civetweb, it will use the configuration file /usr/local/etc/civetweb.conf.

**Comment by suzukibitman** [comment]
今回はビルドをしてやってみたいです。
```
$git clone https://github.com/civetweb/civetweb.git
$cd civetweb
$make

```

**Comment by suzukibitman** [comment]
make helpを叩くとこんな感じ

> $ make help
> make help                show this message
> make build               compile
> make install             install on the system
> make clean               clean up the mess
> make lib                 build a static library
> make slib                build a shared library
> make unit_test           build unit tests executable
> 
>  Make Options
>    WITH_LUA=1            build with Lua support; include Lua as static library
>    WITH_LUA_SHARED=1     build with Lua support; use dynamic linking to liblua5.2.so
>    WITH_LUA_VERSION=502  build with Lua 5.2.x (501 for Lua 5.1.x to 503 for 5.3.x)
>    WITH_DUKTAPE=1        build with Duktape support; include as static library
>    WITH_DUKTAPE_SHARED=1 build with Duktape support; use libduktape1.3.so
>    WITH_DEBUG=1          build with GDB debug support
>    WITH_IPV6=1           with IPV6 support
>    WITH_WEBSOCKET=1      build with web socket support
>    WITH_SERVER_STATS=1   build includes support for server statistics
>    WITH_CPP=1            build library with c++ classes
>    CONFIG_FILE=file      use 'file' as the config file
>    CONFIG_FILE2=file     use 'file' as the backup config file
>    DOCUMENT_ROOT=/path   document root override when installing
>    PORTS=8080            listening ports override when installing
>    SSL_LIB=libssl.so.0   use versioned SSL library
>    CRYPTO_LIB=libcrypto.so.0 system versioned CRYPTO library
>    PREFIX=/usr/local     sets the install directory
>    COPT='-DNO_SSL'       method to insert compile flags
> 
>  Compile Flags
>    NDEBUG                strip off all debug code
>    DEBUG                 build debug version (very noisy)
>    NO_CGI                disable CGI support
>    NO_SSL                disable SSL functionality
>    NO_SSL_DL             link against system libssl library
>    NO_FILES              do not serve files from a directory
>    NO_CACHING            disable caching (usefull for systems without timegm())
> 
>  Variables
>    TARGET_OS='OSX'
>    CFLAGS='-Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -DOSX -Iinclude  -DUSE_STACK_SIZE=102400 -O2 -DNDEBUG'
>    CXXFLAGS=''
>    LDFLAGS=''
>    CC='cc'
>    CXX='c++'

**Comment by suzukibitman** [comment]
実際動かすとこんな感じ：

> 
> $ ./civetweb &
> [1] 38256
> $ CivetWeb V1.10 started on port(s) 8080 with web root [/Users/bitman/01_OSS/civetweb]
>

**Comment by suzukibitman** [comment]
ただし
$make install
をしていないので、indexページが動かないもよう？
prefixを指定して頑張ってみる

**Comment by suzukibitman** [comment]
システムコールが違うとか？
よくわからないが、macOSの対応をドキュメントを調べてみる！

# make -n install PREFIX=$OSS/civetMaking
echo "Target not flagged for installation.  Use CAN_INSTALL=1 to force"
echo "As a precaution only LINUX targets are set as installable."
echo "If the target is linux-like, use CAN_INSTALL=1 option."
# echo $OSS
/Users/bitman/01_OSS
# make install
Target not flagged for installation.  Use CAN_INSTALL=1 to force
As a precaution only LINUX targets are set as installable.
If the target is linux-like, use CAN_INSTALL=1 option.

**Comment by suzukibitman** [comment]
インストール時に、make installするとエラー出る問題解決
思い込み：
$make build CAN_INSTALL=1
実際：
$make install CAN_INSTALL=1
でございます

**Comment by suzukibitman** [comment]
mac osがlinux-likeだからか、dmg出なくてお動きました
めでたしめでたし

**Comment by suzukibitman** [comment]
再度ビルドしようとして、エラーが出て
$make clean
してもきれいになれません。

**Comment by suzukibitman** [comment]
▲sudo でビルドしたためと考えています。
のため、特に問題ではありません！

**Comment by suzukibitman** [comment]
フィードバック：
macOSでビルドできましたことについての報告
気になったことですが、ビルド方法ではcivetwebはmac osにおいてdmgを展開と書いてあります。
実際macOSで行った手順は下記します：
$make build
$make install CAN_INSTALL=1
ただし、localhostのルートディレクトリは/usr/local/share/civetwwebではないようです。
osはmac os sierraです。

**Comment by suzukibitman** [comment]
英語に直します??
いやそのままwikiからコピーします。
Apple changed the original name "Mac OS X" to "OS X" in 2012 and then to "macOS" in 2016.

**Comment by suzukibitman** [comment]
そのまま編集して、上記コメントを残します。

**Comment by swamp09** [comment]
PRのタイトルと、本文が十分でないかなと感じました。

また、OSの名前が変わったとのことですが、ソースが示されていなかったので、ソースを載せると良いと思いました。

**Comment by suzukibitman** [comment]
フィードバックありがとうございます。
PR title
(-)OSX->macOS
(+)Fixed README.md "OSX->macOS" 
本文にリンクを追加（ただソース力が弱い）、変更場所を記載しました。

**Comment by knokmki612** [comment]
おつかれさまでした！いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き文章の整理やフィードバックした時の報告にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談/報告するのもアリです！
