### ISSUE TITLE
OSS Gateワークショップ 2016-06-11: @Kohtaro-NISHI: cancancan: 作業ログ

### ISSUE THREAD

**Issue by Kohtaro-NISHI** [oss-gate/workshop#58]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by Kohtaro-NISHI** [comment]
* README読む
* 長い

**Comment by Kohtaro-NISHI** [comment]
* Getting Started
* Railsプロジェクト作らないと試せない！

**Comment by Kohtaro-NISHI** [comment]
* 作業:プロジェクト作る
```text
$ rails new
No value provided for required arguments 'app_path'
```
あーpath指定必要だった

**Comment by Kohtaro-NISHI** [comment]
```text
$ mkdir ossworkshop
$ cd ossworkshop
$ rails new .
       exist
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/views/layouts/application.html.erb
      create  app/assets/images/.keep
      create  app/mailers/.keep
      create  app/models/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies........
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Installing mini_portile2 2.1.0
Installing pkg-config 1.1.7
Using rack 1.6.4
Using mime-types-data 3.2016.0521
Using arel 6.0.3
Using debug_inspector 0.0.2
Using bundler 1.11.2
Installing byebug 9.0.5 with native extensions
Using coffee-script-source 1.10.0
Installing execjs 2.7.0
Using thor 0.19.1
Using concurrent-ruby 1.0.2
Installing multi_json 1.12.1
Installing sass 3.4.22
Installing tilt 2.0.5
Installing spring 1.7.1
Installing sqlite3 1.3.11 with native extensions
Installing rdoc 4.2.2
Using tzinfo 1.2.2
Installing nokogiri 1.6.8 with native extensions
Using rack-test 0.6.3
Using mime-types 3.1
Using binding_of_caller 0.7.2
Using coffee-script 2.4.1
Installing uglifier 3.0.0
Using sprockets 3.6.0
Installing sdoc 0.4.1
Using activesupport 4.2.6
Using loofah 2.0.3
Using mail 2.6.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.6
Installing jbuilder 2.5.0
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.6
Using activerecord 4.2.6
Using actionview 4.2.6
Using actionpack 4.2.6
Using actionmailer 4.2.6
Using railties 4.2.6
Using sprockets-rails 3.0.4
Using coffee-rails 4.1.1
Installing jquery-rails 4.1.1
Using rails 4.2.6
Using sass-rails 5.0.4
Using web-console 2.3.0
Installing turbolinks 2.5.3
Bundle complete! 12 Gemfile dependencies, 56 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
```
rails newするの久々すぎて覚えてない

**Comment by Kohtaro-NISHI** [comment]
* Gemfileにcancancan追加する

```Gemfile
gem 'cancancan'
```

```text
$ bundle
Resolving dependencies...
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 1.6.4
Using mime-types-data 3.2016.0521
Using arel 6.0.3
Using debug_inspector 0.0.2
Using bundler 1.11.2
Using byebug 9.0.5
Using cancancan 1.13.1
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using thor 0.19.1
Using concurrent-ruby 1.0.2
Using multi_json 1.12.1
Using sass 3.4.22
Using tilt 2.0.5
Using spring 1.7.1
Using sqlite3 1.3.11
Using rdoc 4.2.2
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using mime-types 3.1
Using binding_of_caller 0.7.2
Using coffee-script 2.4.1
Using uglifier 3.0.0
Using sprockets 3.6.0
Using sdoc 0.4.1
Using activesupport 4.2.6
Using loofah 2.0.3
Using mail 2.6.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.6
Using jbuilder 2.5.0
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.6
Using activerecord 4.2.6
Using actionview 4.2.6
Using actionpack 4.2.6
Using actionmailer 4.2.6
Using railties 4.2.6
Using sprockets-rails 3.0.4
Using coffee-rails 4.1.1
Using jquery-rails 4.1.1
Using rails 4.2.6
Using sass-rails 5.0.4
Using web-console 2.3.0
Using turbolinks 2.5.3
Bundle complete! 13 Gemfile dependencies, 57 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

ああもう入ってた

**Comment by Kohtaro-NISHI** [comment]
* README読む
* 取り敢えず `rails g cancan:ability` すればいいのか

**Comment by Kohtaro-NISHI** [comment]
```
$ rails g cancan:ability
Running via Spring preloader in process 32943
      create  app/models/ability.rb
```

**Comment by Kohtaro-NISHI** [comment]
* https://github.com/CanCanCommunity/cancancan/wiki/defining-abilities 読む
> user ||= User.new # guest user (not logged in)

* ユーザが入ってなかったらnewしてゲストユーザ扱いにするのか

**Comment by Kohtaro-NISHI** [comment]
* まず動かす
* ドキュメント読んでるだけで終わりそう

**Comment by Kohtaro-NISHI** [comment]
* 後ろの康弘トークで気が散る

**Comment by Kohtaro-NISHI** [comment]
* 多分以下の手順で進めば動く
- roleを持つUser Modelを作る
- 適当なControllerとViewを作る
- ApplicationControllerでcurrent_userを設定して

**Comment by Kohtaro-NISHI** [comment]
https://github.com/CanCanCommunity/cancancan
README読み直してたら

> In Rails 2.3

古いことにきづいた

最新のバージョンで動作することを明示すべき（古いままだと不安になる）

**Comment by Kohtaro-NISHI** [comment]
* roleを持つUser Modelを作る
* db設定しないと。。

**Comment by Kohtaro-NISHI** [comment]
* 整理する
- https://github.com/oss-gate/workshop/issues/58#issuecomment-225331519
- https://github.com/oss-gate/workshop/issues/58#issuecomment-225333560

**Comment by Kohtaro-NISHI** [comment]
https://github.com/oss-gate/workshop/issues/58#issuecomment-225333560
よくよく見ると

>  CanCan 1.5 includes a Rails 3 and 4 generator for creating this class.
> rails g cancan:ability

> In Rails 2.3, just add a new class in app/models/ability.rb with the following contents:

なので、2.3は `app/models/ability.rb` を自分で作成し、3, 4は `rails g cancan:ability` を叩くということだった。

**Comment by Kohtaro-NISHI** [comment]
https://github.com/oss-gate/workshop/issues/58#issuecomment-225331519
```
$ rails new
No value provided for required arguments 'app_path'
```

app_pathって何の事や？ってなったので
引数でパスを指定しなきゃいけないことを教えてくれると嬉しかった
```
No value provided for required arguments 'app_path'
ex: rails new myapp
```

**Comment by Kohtaro-NISHI** [comment]
### rails newコマンドミスのサポートメッセージの改修案

railsプロジェクトを新しく作りたい時、下記のようなコマンドミスをしてしまうと、以下のメッセージが示される。
```
$ rails new
No value provided for required arguments 'app_path'
```

これではapp_pathという引数が何を示すのかが明示されないため、サポートメッセージとして不適切だと考える。
適切な例を示すか、helpメッセージを出すことを提案したい

```
No value provided for required arguments 'app_path'
rails new APP_PATH
```

これはRails 4系,5系 最新で発生している

**Comment by Kohtaro-NISHI** [comment]
https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/CONTRIBUTING.md
* CONTRIBUTING.md見る
* Do you want to contribute to the Rails documentation? かと思ったけど、Rails-Guides周りのやり取りっぽいので違いそう
* Do you intend to add a new feature or change an existing one? かな

**Comment by Kohtaro-NISHI** [comment]
* Suggest your change in the rubyonrails-core mailing list and start writing code.
* Do not open an issue on GitHub until you have collected positive feedback about the change. GitHub issues are primarily intended for bug reports and fixes.

一旦rubyonrails-core mailing listにメールを送ってFBをもらい、その上でIssue化するということなので
Issueは作らずメールするのが良さそう

**Comment by Kohtaro-NISHI** [comment]
wip
### rails newコマンドミスのサポートメッセージの改修案
### support message of "rails new" command mistake

railsプロジェクトを新しく作りたい時、下記のようなコマンドミスをしてしまうと、以下のメッセージが示される。
```
$ rails new
No value provided for required arguments 'app_path'
```

これではapp_pathという引数が何を示すのかが明示されないため、サポートメッセージとして不適切だと考える。
適切な例を示すか、helpメッセージを出すことを提案したい

```
No value provided for required arguments 'app_path'
rails new APP_PATH
```

これはRails 4系,5系 最新で発生している
In Rails 4,5

**Comment by Kohtaro-NISHI** [comment]
### rails newコマンドミスのサポートメッセージの改修案

私がrailsプロジェクトを新しく作ろうとコマンドを打ったところ、以下のメッセージが示された。
```
$ rails new
No value provided for required arguments 'app_path'
```

私はこのメッセージを見て、自分のコマンドに何らかの不足があることは理解できたが、
app_pathという引数が何を示すのかが不明だったため、ヘルプを少し眺めて気づくことができた。
私はその時、
`No value provided for required arguments 'app_path'`
は、コマンドに引数の指定を促すサポートメッセージとしては分かりにくく、
適切な例を示すか、helpメッセージを出してくれたほうが良いのではないかと感じた。

```
No value provided for required arguments 'app_path'
rails new APP_PATH
```

私はこれをRails 4系,5系 最新で確認した。

**Comment by Kohtaro-NISHI** [comment]
https://github.com/oss-gate/workshop/issues/58#issuecomment-225337448
改めて確認すると、
railsはもう3未満のバージョンをサポートしていないにも関わらず、2.3用の例が書かれていることに気づいた
http://guides.rubyonrails.org/maintenance_policy.html

**Comment by Kohtaro-NISHI** [comment]
### cancancanのREADME長くてムカついた
README流し読みしてたら
`rails g cancan:ability`
と
`add a new class in app/models/ability.rb`
```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
  end
end
```

の両パターンが書いてある。
よくよく見たらRails versionの違いによる対応の話で、
2.3は `app/models/ability.rb` を自分で作成し、3, 4は `rails g cancan:ability` すればいけるよーということだった。
railsはもう3未満のバージョンをサポートしていないので、2.3用の例をわざわざ残す必要はないと思う。
ただでさえREADME長くてムカつくので消してスリムにしましょう！！

**Comment by Kohtaro-NISHI** [comment]
### Delete the notation  for the Rails version 2.3
https://github.com/CanCanCommunity/cancancan#1-define-abilities
このセクションで、Rails 2.3に向けたパターンが記載されている。

> In Rails 2.3, just add a new class in app/models/ability.rb with the following contents:
>```ruby
> class Ability
>   include CanCan::Ability
>
>   def initialize(user)
>   end
> end
> ```

しかし、railsは既にバージョン3未満をサポートしていないです。
なので私はversion 2.3用の例をわざわざ残す必要はないと思う。
However , rails is not already support the less than version 3 .
So I think not need to leave an example for version 2.3.

 http://guides.rubyonrails.org/maintenance_policy.html
> 4 Severe Security Issues
For severe security issues we will provide new versions as above, and also the last major release series will receive patches and new versions. The classification of the security issue is judged by the core team.

> Currently included series: 4.2.Z, 4.1.Z, 3.2.Z.

ので、READMEからこの記述を消しませんか？
So , I suggest remove this description from the README

**Comment by Kohtaro-NISHI** [comment]
あとIssueに紐付けてPR送る

**Comment by Kohtaro-NISHI** [comment]
https://github.com/CanCanCommunity/cancancan/issues/329

**Comment by kou** [comment]
お疲れさまでした！
