### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-09-30:syumikko:未定:Work log

### ISSUE THREAD

**Issue by syumikko** [oss-gate/workshop#580]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by syumikko** [comment]
ライセンスの表記を調べていきます。

**Comment by KoichiroT** [comment]
よろしくお願いします

**Comment by wotsushi** [comment]
よろしくお願いします！

**Comment by syumikko** [comment]
普段使っているvimのプラグインを調べていきます。

**Comment by syumikko** [comment]
vimのプラグインがどこにあるのかわからないので(vim プラグイン 管理)[http://post.simplie.jp/posts/55]検索しました。

**Comment by syumikko** [comment]
カスタマイズしているファイルが存在しなかった。

**Comment by syumikko** [comment]
vim上で普段使うchromeを操作できる拡張機能があるらしい。
興味がvimでブラウザを使う、調べやすさでchromeでvimのキーバインドを使えるようにする。

**Comment by syumikko** [comment]
まず(vimでブラウザ)[http://rhysd.hatenablog.com/entry/2015/11/22/223050]を調べてみる。

**Comment by syumikko** [comment]
つぎにchromeでvimのキーバインドを調べるが、firefox上での拡張機能vimperetorから乗り換えで記事が多いので(vimperator chrome)[http://easyramble.com/chrome-vimperator-like-extension.html]を調べる。

**Comment by syumikko** [comment]
記事でchromeウェブストアにある候補4つが記載されていた。
* (Vimium)[https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb/reviews?hl=ja]ユーザー数: 293,367 人
* (Vichrome)[https://chrome.google.com/webstore/detail/vichrome/gghkfhpblkcmlkmpcpgaajbbiikbhpdi?hl=ja]ユーザー数: 8,667 人
* (Vrome)[https://chrome.google.com/webstore/detail/vrome/godjoomfiimiddapohpmfklhgmbfffjj?hl=ja]ユーザー数: 5,727 人
* (cVim)[https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh?hl=ja]ユーザー数: 28,253 人

**Comment by syumikko** [comment]
まずは使ってみること、ユーザー数が少ない方がバグを踏みやすい=バグ報告をできるかもなので現状ユーザー数の最も少ない(Vrome)[https://chrome.google.com/webstore/detail/vrome/godjoomfiimiddapohpmfklhgmbfffjj?hl=ja]をいれる。

**Comment by syumikko** [comment]
chromeに追加からすぐに追加された。

**Comment by syumikko** [comment]
追加されchromeのタブが開くも最初のページがchange logで初心者にはすぐには使えなさそう。あと日本語にはできるのかな？

**Comment by syumikko** [comment]
ページ内タブにFeaturesがあり
Help
        <F1>      Open this help page
と記載あるがページを閉じて F1 を押下するも開かない。。

**Comment by syumikko** [comment]
そもそもVromeが機能していないかもしれないのでchromeメニューのウインドウから拡張機能を確認する。

**Comment by syumikko** [comment]
機能しているように見える。

**Comment by syumikko** [comment]
チューターのゆうきさんから
* 追加したあとで開いたタブ、ウインドウから有効になる。
* 「新しいタブ」では F1 を押下しても help を開けない。

**Comment by syumikko** [comment]
【まとめる】
# 追加後開くページがChangeLog。

**初心者はまず最初に使いたいので使い方が書かれていてほしい。**

  * 最初に開くページをFeaturesにする。

# F1 Open this help pageが使えない。
* 使い方が書かれたページ、GoogleドメインのページではHelpが開けない。
* Vromeを追加する前に開かれたページではHelpが開けない。

**最初に正しく追加できたかの確認をしたいので確認する方法を記載してほしい。**

  * 使えないページがあるので既知のページで使われる可能性があるところは記載しておく。
  * 最初に試す場所を指定しておく。例えば開発ページとか。
  * チュートリアルを用意しておく。

**Comment by syumikko** [comment]
初心者への要望がすでに書かれていないか(開発リポジトリ)[https://github.com/jinzhu/vrome/issues]を確認する。

**Comment by syumikko** [comment]
書かれていないようなのでissues書くためのフォーマットに当てはめて記述する。

**Comment by syumikko** [comment]
# 概要
最初に開くページがChangeLogだと初心者には使いにくい。

# 再現手順
Chromeを開きVromeを追加する。

# 期待される状態
追加された直後に使い方がわかる。

# 実際の状態
初心者にはまだ必要ないChangeLogが表示される。

# 要望
最初に開くページをFeaturesに変更する。

**Comment by syumikko** [comment]
# 概要
VromeのHelpが開かないページがあり初心者には拡張機能が追加できたのか検証をできない。

# 再現手順
ChromeにVromeを追加し、F1 を押下する。

# 期待される状態
Vromeが使えるようになったことがわかること。
実際にHelpを開けるページがわかる。

# 実際の状態
* 説明の書かれた[ページ](chrome-extension://godjoomfiimiddapohpmfklhgmbfffjj/background/html/options.html#features)では F1 を押下しても Help が開かない。 
* 導入前に開いたページで Help も使えない。
* Googleドメインのページでも Help が開かない。

# 要望
* 使えない既知のURLは記載しておく。
* 最初に試す場所を用意して指定する。
* チュートリアルを用意する。

**Comment by y-goto** [comment]
わかりやすくかけていると思います。
ぜひ英語にして投稿してみてください。英語などで困った時も含めてgitterで相談するのもおすすめです。

**Comment by knokmki612** [comment]
おつかれさまでした！

私もVromeを入れてみたのですが、syumikkoさんのフィードバックに共感しました！

いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き作業したり、フィードバックした時の報告にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談/報告するのもアリです！
