### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-9-30: T-a-n-a-k-a-M-a-s-a-k-i: async-dns: Work log

### ISSUE THREAD

**Issue by T-a-n-a-k-a-M-a-s-a-k-i** [oss-gate/workshop#581]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by onk** [comment]
よろしくお願いします 💪

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
async-dnsのREADMEを読み始める

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
mkdir oss_gate
bundle init
vim Gemfile
cat Gemfile
# frozen_string_literal: true
source "https://rubygems.org"

gem "async-dns"
bundle

インストールに成功

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
```
Tanaka-no-MacBook-Air:oss_gate bob$ ls
Gemfile			Gemfile.lock		resolver_test.rb
Tanaka-no-MacBook-Air:oss_gate bob$ cat resolver_test.rb 
Bundler.require

Async::Reactor.run do
  resolver = Async::DNS::Resolver.new(
    [[:udp, "8.8.8.8", 53],
    [:tcp, "8.8.8.8", 53]]
  )
  addresses = resolver.addresses_for("www.google.com.")
  puts addresses.inspect
end
Tanaka-no-MacBook-Air:oss_gate bob$ bundle exec ruby resolver_test.rb 
[#<Resolv::IPv4 216.58.197.132>]
```

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
```
Tanaka-no-MacBook-Air:oss_gate bob$ cat server_test.rb 
Bundler.require

class TestServer < Async::DNS::Server
  def process(name, resouce_class, transaction)
    @resolver ||= Async::DNS::Resolver.new(
      [[:udp, "8.8.8.8", 53],
      [:tcp, "8.8.8.8", 53]]
    )
    transaction.passthrough!(@resolver)
  end
end

server = TestServer.new([[:udp, "127.0.0.1", 2346]])
server.run
Tanaka-no-MacBook-Air:oss_gate bob$ bundle exec ruby server_test.rb 
```

```
Tanaka-no-MacBook-Air:~ bob$ dig @localhost -p 2346 google.com

; <<>> DiG 9.10.2 <<>> @localhost -p 2346 google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56233
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		299	IN	A	216.58.197.142

;; Query time: 97 msec
;; SERVER: 127.0.0.1#2346(127.0.0.1)
;; WHEN: Sat Sep 30 11:57:17 JST 2017
;; MSG SIZE  rcvd: 44
```

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
FAQを読み始める

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
ユニットテストを動かしてみる

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
git cloneした後にrakeでユニットテスト
warningが出る
→warningを改善することはできないか？

**Comment by onk** [comment]
> ```
> warning: assigned but unused variable
> warning: shadowing outer local variable
> ```

この辺り、美味しいフィードバックポイントですねー。

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
Tanaka-no-MacBook-Air:async-dns bob$ bundle exec rake
/Users/bob/.rbenv/versions/2.3.0-dev/bin/ruby -I/Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/gems/2.5.0/gems/rspec-core-3.6.0/lib:/Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/gems/2.5.0/gems/rspec-support-3.6.0/lib /Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/gems/2.5.0/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/gems/2.5.0/gems/async-io-1.0.0/lib/async/io/socket.rb:59: warning: shadowing outer local variable - task
/Users/bob/github/async-dns/lib/async/dns/extensions/resolv.rb:29: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
/Users/bob/github/async-dns/lib/async/dns/extensions/resolv.rb:53: warning: method redefined; discarding old to_s
/Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/2.5.0/resolv.rb:1305: warning: previous definition of to_s was here
/Users/bob/github/async-dns/lib/async/dns/extensions/resolv.rb:57: warning: method redefined; discarding old inspect
/Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/2.5.0/resolv.rb:1237: warning: previous definition of inspect was here
/Users/bob/github/async-dns/lib/async/dns/resolver.rb:216: warning: assigned but unused variable - peer
/Users/bob/github/async-dns/lib/async/dns/resolver.rb:223: warning: assigned but unused variable - context
/Users/bob/github/async-dns/lib/async/dns/handler.rb:119: warning: assigned but unused variable - context
/Users/bob/github/async-dns/lib/async/dns/system.rb:140: warning: assigned but unused variable - search
/Users/bob/github/async-dns/lib/async/dns/replace.rb:46: warning: method redefined; discarding old getaddress
/Users/bob/.rbenv/versions/2.3.0-dev/lib/ruby/2.5.0/resolv-replace.rb:10: warning: previous definition of getaddress was here
/Users/bob/github/async-dns/spec/async/dns/resolver_performance_spec.rb:93: warning: assigned but unused variable - resolved
/Users/bob/github/async-dns/spec/async/dns/resolver_performance_spec.rb:99: warning: assigned but unused variable - resolved
/Users/bob/github/async-dns/spec/async/dns/resolver_performance_spec.rb:90: warning: assigned but unused variable - a
/Users/bob/github/async-dns/spec/async/dns/resolver_performance_spec.rb:96: warning: assigned but unused variable - b
/Users/bob/github/async-dns/spec/async/dns/resolver_spec.rb:38: warning: assigned but unused variable - data
/Users/bob/github/async-dns/spec/async/dns/server_performance_spec.rb:60: warning: assigned but unused variable - resolved
/Users/bob/github/async-dns/spec/async/dns/server_performance_spec.rb:148: warning: assigned but unused variable - pending

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
async-ioのwarningは修正箇所が少なくてやり易そう
async-ioのプロジェクトをclone

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
async-ioでユニットテストが失敗する。
'''
Failures:

  1) echo client/server should send/receive 10,000 messages
     Failure/Error: socket = ::Socket.new(*args)
     
     Errno::ENFILE:
       Too many open files in system - socket(2)
     # ./lib/async/io/socket.rb:88:in `initialize'
     # ./lib/async/io/socket.rb:88:in `new'
     # ./lib/async/io/socket.rb:88:in `build'
     # ./lib/async/io/socket.rb:108:in `connect'
     # ./spec/async/io/c10k_spec.rb:66:in `block in echo_client'
'''
async-dns側のFAQに基づいて修正してみる。

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
ulimit -n 10000で修正できるはずだがうまくいかない。
ulimitコマンドについて調べてみる。

**Comment by T-a-n-a-k-a-M-a-s-a-k-i** [comment]
vagrant上のubuntuでも上手くいかない
念のためエラーメッセージToo many open filesについてググって対策を見てみる

**Comment by okkez** [comment]
> Too many open files in system 

が解決したら、最初に見つけたwarningの対応をしていくそう。
フィードバックするところまで辿り付けていたので、今後もこの調子でがんばってほしいです。

**Comment by knokmki612** [comment]
おつかれさまでした！いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き作業にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談してみるのもアリです！
