### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-9-30: tetsuyaohira: json2csv: Work log

### ISSUE THREAD

**Issue by tetsuyaohira** [oss-gate/workshop#582]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by onk** [comment]
よろしくお願いします 💪

**Comment by tetsuyaohira** [comment]
git hub のurl は https://github.com/zemirco/json2csv

**Comment by tetsuyaohira** [comment]
licenseは　MIT license
https://github.com/zemirco/json2csv/blob/master/LICENSE.md

**Comment by tetsuyaohira** [comment]
npmはinstall 済みなので、vs code で install してみる

**Comment by tetsuyaohira** [comment]
npm install json2csv --save

**Comment by tetsuyaohira** [comment]
install できた
npm のupdate があったので、そちらも行う
’’’
Update available 5.3.0 → 5.4.2    │
Run npm i -g npm to update 
’’’

**Comment by tetsuyaohira** [comment]
package-lock.json　ができた
-lockってなんだ

**Comment by tetsuyaohira** [comment]
初めてreadme.mdを呼んでみる

**Comment by tetsuyaohira** [comment]
npm の update が終わらない。。。

**Comment by tetsuyaohira** [comment]
repl で sample code を打ち込む

**Comment by tetsuyaohira** [comment]
sample code を実行したら error
ReferenceError: myData is not defined
    at repl:2:29
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

**Comment by tetsuyaohira** [comment]
myDataがない

**Comment by tetsuyaohira** [comment]
myDataを宣言して動作したことを確認

var myData = {'field1':1,'field2':2,'field3':3};

**Comment by tetsuyaohira** [comment]
command line で実行する

**Comment by tetsuyaohira** [comment]
node_modules\.bin\json2csv
で実行可能

**Comment by tetsuyaohira** [comment]
-i オプションが入力ファイル

**Comment by tetsuyaohira** [comment]
node_modules\.bin/json2csv -i input.json -f carModel,price,color
を実行したところerrro

**Comment by tetsuyaohira** [comment]
input.json にcsvを書いてた。。。

**Comment by onk** [comment]
README どおりに How to use を実行したらエラーになった部分はフィードバックポイントですね。

下の方に Example があるんだけど、そこに辿り着く前に How to use だけ実行してエラーになって萎えそう。
How to use を直すか、Example へのリンクを How to use のところに置いておくとかしてあげるとユーザに親切だと思いました。

**Comment by onk** [comment]
CLI examples が output しか無い (input.json がどんな形か分からない) のもフィードバックポイントっぽいです

**Comment by tetsuyaohira** [comment]
# issue
- sample cpde 通りに入力してもエラーになる
- インプットのjson がsampleに書いていないため
- ある程度開発経験があればすぐ気づくが、初心者ははまる可能性がある
- また、json はどんな形式なのか、想像しないとわからない

**Comment by onk** [comment]
これぐらいならどう直すか決めて Pull Request 出しちゃっても良いかもー。

**Comment by tetsuyaohira** [comment]
json2csv を git clone 
git clone https://github.com/zemirco/json2csv.git

**Comment by tetsuyaohira** [comment]
branch作成 と 変更
git branch feature/readmechange
git checkout feature/readmechange

**Comment by tetsuyaohira** [comment]
README.md を更新する

**Comment by tetsuyaohira** [comment]
完璧(実行可能)なcode sampleへのlink を追加する

**Comment by tetsuyaohira** [comment]
# pull request comment
When I ran the "How to use" code, I got an error.
Beginners may not be able to solve the error.
I would like to add a link to the complete example.

**Comment by onk** [comment]
初心者じゃなくてもこの README の修正は嬉しいので title は

> Add a link to the complete example

で良いかなぁ。

description には起きたエラーを足したい。

**Comment by tetsuyaohira** [comment]
あっtitleの指摘ありがとうございます。
期がづきませんでした。。。

**Comment by okkez** [comment]
`myData`が未定義であることについて、コードにコメントを追加するとより良いのではー、というフィードバックをした。
動くサンプルコードへのリンクを追加したのはとてもよい変更だと思いました。

**Comment by tetsuyaohira** [comment]
ありがとうございます。
さらに pull request したいと思います。
- CLI examples に Jsonの例が無いのでsample の json を追加
- myData がなくてエラーになることをcommet に追加

**Comment by knokmki612** [comment]
おつかれさまでした！いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き作業したり、PR/フィードバックした時の報告にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談/報告するのもアリです！

**Comment by tetsuyaohira** [comment]
prがaccept されました！
