### ISSUE TITLE
    OSS Gate Workshop: Tokyo: 2017-Nov-30: s223: xmonad: Work log

### ISSUE THREAD

**Issue by s223** [oss-gate/workshop#583]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by onk** [comment]
よろしくお願いします 💪

**Comment by s223** [comment]
xmonadを検索してみる。

**Comment by s223** [comment]
トップに公式ページが出てきた。

**Comment by s223** [comment]
downloadページにディストリビュージョンごとのインストール方法が書いてある。
tarballを使った方法とgitを使った方法も。

**Comment by s223** [comment]
Arch Linuxのパッケージがあるけど、すぐ入っちゃいそうだからコンパイルしてみる方針。

**Comment by s223** [comment]
http://xmonad.org/intro.html
インストールイントロダクション
とりあえずHaskellの処理系を入れてないのでghcをインストール

**Comment by s223** [comment]
```
#pacman -S ghc
```
容量が大きい

**Comment by s223** [comment]
ghcインストール完了

**Comment by s223** [comment]
libx11をインストールするように記述があるが、既にインストール済み。

**Comment by s223** [comment]
HaskellのパッケージシステムCabalをインストールしろって書いてある。

**Comment by s223** [comment]
cabal-installもpacmanで入った

**Comment by s223** [comment]
cabal入ったからもう楽勝かなって思ったけど、cabal install がエラーなので　cabalの使い方を調べる

**Comment by s223** [comment]
```
#cabal update
```
を実行してからもう一度
```
#cabal install xmonad
```

**Comment by s223** [comment]
There are files missing in the `base-4.10.0.0' package,
    try running 'ghc-pkg check'.

**Comment by s223** [comment]
すごくいっぱいファイルが無いって言われた

**Comment by s223** [comment]
ghcは各々のディストリビュージョンのバイナリで入れるように書いてあったので
何も考えず、
```
# pacman -S ghc
```
したんですが、何か足りなかったのかも。
xmonadのインストールイントロダクションにはapt-getの例だけがあった。
ArchWiki のhaskellのページを見てみる。

**Comment by s223** [comment]
ghc-staticが怪しい気がする

**Comment by s223** [comment]
archlinux のパッケージでは ghcのコンパイラ(ghc)と静的ライブラリ(ghc-statics)が分かれている。

**Comment by s223** [comment]
ghc-staticsを入れて再度
```
#cabal install xmonad
```

**Comment by s223** [comment]
Failed to install xmonad-0.13
Build log ( /root/.cabal/logs/ghc-8.2.1/xmonad-0.13-ILFqxDWFT2tCDyVDJtWcOg.log ):
cabal: Entering directory '/tmp/cabal-tmp-6016/xmonad-0.13'
Configuring xmonad-0.13...
Preprocessing library for xmonad-0.13..
Building library for xmonad-0.13..
[1 of 9] Compiling Paths_xmonad     ( dist/build/autogen/Paths_xmonad.hs, dist/build/Paths_xmonad.o )
[2 of 9] Compiling XMonad.StackSet  ( src/XMonad/StackSet.hs, dist/build/XMonad/StackSet.o )
[3 of 9] Compiling XMonad.Core      ( src/XMonad/Core.hs, dist/build/XMonad/Core.o )

src/XMonad/Core.hs:40:1: error:
    Could not find module `Control.Monad.State'
    There are files missing in the `mtl-2.2.1' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
40 | import Control.Monad.State
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

src/XMonad/Core.hs:41:1: error:
    Could not find module `Control.Monad.Reader'
    There are files missing in the `mtl-2.2.1' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
41 | import Control.Monad.Reader
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-6016/xmonad-0.13'
cabal: Error: some packages failed to install:
xmonad-0.13-ILFqxDWFT2tCDyVDJtWcOg failed during the building phase. The
exception was:
ExitFailure 1

**Comment by s223** [comment]
```
#cabal install mtl
```

**Comment by s223** [comment]
Resolving dependencies...
All the requested packages are already installed:
mtl-2.2.1
Use --reinstall if you want to reinstall anyway.

**Comment by s223** [comment]
インストール済みだって言われる

**Comment by knokmki612** [comment]
https://wiki.archlinux.org/index.php/haskell#cabal-install

**Comment by s223** [comment]
archlinux固有の問題で、cabalでインストールされた実行形式のものは~/.cabal/binに入るのでそこにもパスを通さなければいけない

**Comment by s223** [comment]
Could not find module `Control.Monad.State'

**Comment by s223** [comment]
パスを通して再度　cabal install xmonadを実行するが失敗。
Could not find のエラーメッセージを検索してみる。

**Comment by s223** [comment]
cabalでインストールされたパッケージにghcからpathが通って無い？
とりあえずpacmanを使わずにcabalをインストールし直してみる。

**Comment by s223** [comment]
インストールし直そうと思ったらディスクのスペースが無くなっちゃった

**Comment by s223** [comment]
```
$ ghc-pkg describ mtl
```
これで問題のmtlが置いてあるのは~/.cabal/libだってわかった。

**Comment by okkez** [comment]
Arch Linux特有の問題なのでArch Wikiへのフィードバックするそう。
Arch Linuxを使う人は Arch Wiki を読むだろう、という仮定は妥当だと思う。

**Comment by okkez** [comment]
問題のある箇所をきちんと絞り込めていたので、他のOSSでもフィードバックやっていけそう。

**Comment by knokmki612** [comment]
おお、mtlが入っているpathがわかったんですね！！進んでますね！

おつかれさまでした！いったんこちらのissueはクローズしますが、クローズされた状態でもコメントできます！
引き続き作業したり、PR/フィードバックした時の報告にこちらのissueを活用するのもアリですし、[gitter](https://gitter.im/oss-gate/devel)で相談/報告するのもアリです！
