### ISSUE TITLE
ワークショップの時間を短くする

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#6]
終日ではなく、午後だけで終わるようにした方がよいのかもしれない。

https://twitter.com/trorornmn/status/690833865250762752

> ＿人人人人人人人人＿
> ＞　10:30 - 18:00　＜
> ￣^Y^Y^Y^Y^Y^Y^Y^￣

https://twitter.com/trorornmn/status/690833896515043328

> せめて午後からだったらな〜

時間が短くても同じ成果を出せるなら参加者だけでなく開催する側の負担も減らせるのでよさそう。

**Comment by sezemiadmin** [comment]
とりあえず現行の1日のプログラムで必要なものを出してみました

1. OSS開発手順を説明 // 1時間
1. 対象OSSを動かす // 2.5時間
1. プロジェクトにフィードバックする // 2時間

合計5.5時間 (13:00~18:30) なので、どこか圧縮できるところがあればというところですが、いかがでしょう?

**Comment by kou** [comment]
ありがとうございます！

動かすところとフィードバックするところを0.5時間ずついけるかも？という感じですかねぃ。あんまり減らして「参加したけど不安は解消しなかった」となるとアレなんですが、次回以降、試してみるとよさそうな気がしています！

**Comment by sezemiadmin** [comment]
↑ を見て思ったのが、動かすところとフィードバックの部分を削る -> 消化不良に繋がるのは、対象OSSによって発生するのではと思いました。
なので、ある程度、コレ(メンターが関わっているOSS か OSS GateのOSS など) というのが決まっていたほうが良いかもなぁと。　(1/30 やってみてからの議論ですが)

**Comment by kou** [comment]
2016-01-30のワークショップを経験した人たちの話だとこの内容で減らすのはやめた方がよさそう。（今回くらいの長さが適切）

なので閉じる。

やることを限定するとか（すでに見つけてある問題をバグレポートするだけにするとか）すれば減らせるかも。
