### ISSUE TITLE
OSS Gateワークショップ 2016-06-11: tama1029: simple-rss: 作業ログ

### ISSUE THREAD

**Issue by tama1029** [oss-gate/workshop#60]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by tama1029** [comment]
* ドキュメントを読む

何がしんぷるなんだろう？

**Comment by tama1029** [comment]
* インストールはじめた

コマンド
`gem install simple-rss`

結果
```
Fetching: simple-rss-1.3.1.gem (100%)
Successfully installed simple-rss-1.3.1
Parsing documentation for simple-rss-1.3.1
Installing ri documentation for simple-rss-1.3.1
Done installing documentation for simple-rss after 0 seconds
1 gem installed
```

**Comment by tama1029** [comment]
* 使い方読み始めた

そのAPIはって書いてるからAPIかな？

require 'rubygems'　ってなんでいるんだろ？

**Comment by tama1029** [comment]
流れとして、

```ruby
rss = SimpleRSS.parse open('http://slashdot.org/index.rdf')

rss.channel.title # => "Slashdot"
rss.channel.link # => "http://slashdot.org/"
rss.items.first.link # => "http://books.slashdot.org/article.pl?sid=05/08/29/1319236&amp;from=rss"
```

1. `open-uri`使ってhtml情報とってくる　`open-uri`の情報はこちら的なのはないのね
2. nokogiriなしでもparseができるみたい

**Comment by tama1029** [comment]
最初のサンプル試しはじめた。

`vi parse_test.rb`

でつくって

```ruby
require 'rubygems'
require 'simple-rss'
require 'open-uri'

rss = SimpleRSS.parse open('http://slashdot.org/index.rdf')

rss.channel.title # => "Slashdot"
rss.channel.link # => "http://slashdot.org/"
rss.items.first.link # => "http://books.slashdot.org/article.pl?sid=05/08/29/1319236&amp;from=rss"
```

を実行して

情報が見れることを期待したが

```ruby
/Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop': redirection forbidden: http://slashdot.org/index.rdf -> https://slashdot.org/index.rdf (RuntimeError)
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from parse_test.rb:5:in `<main>'
```

とりあえず死んだ

**Comment by tama1029** [comment]
原因は `http://slashdot.org/index.rdf` から `https://slashdot.org/index.rdf` にリダイレクトされており

そちらから情報を取れていない気がする。

ので、`https://slashdot.org/index.rdf`に変えて試してみる。

**Comment by tama1029** [comment]
上記で実行するとさらに

```
/Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop': redirection forbidden: https://slashdot.org/index.rdf -> http://rss.slashdot.org/Slashdot/slashdot/to (RuntimeError)
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /Users/tamaki1/.rbenv/versions/2.2.3/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from parse_test.rb:5:in `<main>'
```

エラーがでて`http://rss.slashdot.org/Slashdot/slashdot/to`　こっちにまたリダイレクトされている。

次は`http://rss.slashdot.org/Slashdot/slashdot/to`にurlを変えてみる。

**Comment by tama1029** [comment]
ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!

平和にエラーがでなくなった

**Comment by tama1029** [comment]
サンプルコードがputsかかれていないので　すぐに実行しても情報が何もでない。

**Comment by tama1029** [comment]
推奨ruby versionとかが書かれていない。

**Comment by tama1029** [comment]
htmlのどことどう対応して抜き出しているのか見てみよう

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:feedburner="http://rssnamespace.org/feedburner/ext/1.0">
<channel>
<title>Slashdot</title>
```

の`channel.title`で抜き出してるみたい

**Comment by tama1029** [comment]
次は　フィードが抜き出せるぽいので、下記埋め込んで見る

```ruby
rss.feed.title # => "Slashdot"
rss.feed.link # => "http://slashdot.org/"
rss.entries.first.link # => "http://books.slashdot.org/article.pl?sid=05/08/29/1319236&amp;from=rss"
```

feedとれるかなー

**Comment by tama1029** [comment]
# 問題点

* 一つ目の下記サンプルを使ってみたのですが、リダイレクトループしており情報が取得できませんでした。

# どういう気持ち？

* サンプルコードを試して、すぐに結果が得られると思っていたが、取得できなかったので、残念な気持ちになった。
  * なんで残念な気持ちになったか?
    * サンプルコードは動いてあたりまえ、かつみんなが通るところなので通って欲しいと思っていた。

# だからどうしたい？（案ベース）

1. RSSを試せる場所がないので、そういう場所があると幸せ。
2. 動くURLに修正する。

**Comment by tama1029** [comment]
# 開発者にむけてに関してのやつ

urlがリダイレクト後のものになっていてほしい。

# 変更前のサンプル

```ruby
require 'rubygems'
require 'simple-rss'
require 'open-uri'

rss = SimpleRSS.parse open('http://slashdot.org/index.rdf')

rss.channel.title # => "Slashdot"
rss.channel.link # => "http://slashdot.org/"
rss.items.first.link # => "http://books.slashdot.org/article.pl?sid=05/08/29/1319236&amp;from=rss"
```


# 変更後のサンプル

```ruby
require 'rubygems'
require 'simple-rss'
require 'open-uri'

rss = SimpleRSS.parse open('http://rss.slashdot.org/Slashdot/slashdot/to')

rss.channel.title # => "Slashdot"
rss.channel.link # => "http://slashdot.org/"
rss.items.first.link # => "http://books.slashdot.org/article.pl?sid=05/08/29/1319236&amp;from=rss"
```

**Comment by tama1029** [comment]
# First sample failed.

This url contains a redirect loop.
`rss = SimpleRSS.parse open('http://slashdot.org/index.rdf')`

**Comment by tama1029** [comment]
https://github.com/cardmagic/simple-rss/issues/24

あげました＼(^o^)／

**Comment by kou** [comment]
お疲れさまでした！
