### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: tochi-y: Mattermost: Work log

### ISSUE THREAD

**Issue by tochi-y** [oss-gate/workshop#602]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mikami3** [comment]
宜しくお願いします！

**Comment by tochi-y** [comment]
Mattermostの公式ページ
https://github.com/mattermost/mattermost-server

**Comment by tochi-y** [comment]
以前、Githubアカウントでログインしたときに、Public MailAddressが設定されてないときのエラーメッセージが全然違ったので、既出の報告がなければ報告したい。

**Comment by tochi-y** [comment]
1. Issuesに報告されてないか確認
2. 最新版で再現するか確認

**Comment by tochi-y** [comment]
逆の方がいいとアドバイス受けたので、逆でいく。

**Comment by tochi-y** [comment]
最新版で動かす方法はなんだろう。Githubのページで確認しよう。

**Comment by tochi-y** [comment]
`Install on your own machine:` のあたり。４つ方法がある。Dockerあり・なしなどでいくつかありそう。

**Comment by tochi-y** [comment]
`One-line Docker Install`を試してみる。

```
docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
```

**Comment by tochi-y** [comment]
待っている間に`mattermost/mattermost-preview`について調べてみる。

**Comment by tochi-y** [comment]
https://hub.docker.com/r/mattermost/mattermost-preview/

latest releaseが動きそう。

**Comment by tochi-y** [comment]
成功。

```
$ sudo docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
Unable to find image 'mattermost/mattermost-preview:latest' locally
latest: Pulling from mattermost/mattermost-preview
aa18ad1a0d33: Pull complete
1324423d52e9: Pull complete
ee152a81987c: Pull complete
b054cf37bcae: Pull complete
eb0cbad90353: Pull complete
710fc2dae571: Pull complete
5ff098d10285: Pull complete
79f9dfa6f98f: Pull complete
5d033d38431e: Pull complete
bdde10ea566e: Pull complete
1a36bb8deb0e: Pull complete
c79cd509b64e: Pull complete
3f8571b9277b: Pull complete
10f52f2783e9: Pull complete
322ecebe758e: Pull complete
cefdce9e106b: Pull complete
40cc24b20964: Pull complete
d86afc9b3332: Pull complete
dbf77c6798a1: Pull complete
Digest: sha256:059850db0d5ffe21f16b783a905344d00d18bc6a7ee131b3d984f8d000320986
Status: Downloaded newer image for mattermost/mattermost-preview:latest
2b6cf3a7aa6bab2da9a04659712a452a52ed2f5bb52034559ceb5abeca859f0a
```

**Comment by tochi-y** [comment]
動作している。

```
$ sudo docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED              STATUS              PORTS                              NAMES
2b6cf3a7aa6b        mattermost/mattermost-preview   "/bin/sh -c ./dock..."   About a minute ago   Up About a minute   3306/tcp, 0.0.0.0:8065->8065/tcp   mattermost-preview
```

**Comment by tochi-y** [comment]
ブラウザで確認してみる。

**Comment by tochi-y** [comment]
8065ポートにアクセスして表示できた。

![01](https://user-images.githubusercontent.com/32325140/31062041-6c38d8a8-a762-11e7-88a2-37a583ed385e.png)

**Comment by tochi-y** [comment]
GitLabログインのボタンはなし。ひとまず、普通のID/パスワードでログインできるか試してみる。

**Comment by tochi-y** [comment]
アカウントとチームを作成して、ログインできた。`Version: 4.1.0  (4.1.1)` これはどっちのバージョンだ
!？

![02](https://user-images.githubusercontent.com/32325140/31062127-48c59838-a763-11e7-8260-825079e5b940.png)

**Comment by tochi-y** [comment]
最新のバージョンを調べてみる。

**Comment by tochi-y** [comment]
https://github.com/mattermost/mattermost-server/releases

`v4.2.0`タグも存在。。

**Comment by tochi-y** [comment]
ひとまず`Version: 4.1.0 (4.1.1)`で再現するか確認してみる。

**Comment by tochi-y** [comment]
GitLabアカウントでログインできる設定を調べる。

**Comment by tochi-y** [comment]
https://docs.mattermost.com/administration/config-settings.html?highlight=gitlab#gitlab

これでできそう。コンテナーに入って設定を変えてみる。

**Comment by tochi-y** [comment]
コンテナーにこのコマンドでは入れた。

```
$ sudo docker exec -it 2b6cf3a7aa6b /bin/bash
```

GitLabログインの設定を発見。

```
# find . -name 'config.json'
./mattermost/config/config.json
```

```json
    "GitLabSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    },
```

**Comment by tochi-y** [comment]
報告したい内容の整理。

`Version: 4.1.0 (4.1.1)`というバージョン表記で表示されるが、どちらのバージョンかわからない。

このバージョン表記にしている意図は何かを聞きたい。

**Comment by tochi-y** [comment]
- One-line Docker Installを試してみた。
https://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install

```
docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
```

- GUIからMattermostのバージョンを表示させた。
- `Version: 4.1.0 (4.1.1)`という表記で表示された。
- 画像

**Comment by tochi-y** [comment]
What is the meaning of the version which is described in the parentheses?

I installed the latest mattermost by [One-line Docker Install](https://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install), and displayed the Mattermost version.


 
画像

Then, the version is displayed `4.1.0 (4.1.1)`.  
I think the version 4.1.0 is installed, is my understanding correct?  
And what is the meaning of the version which is described in the parentheses?

**Comment by tochi-y** [comment]
イシューテンプレートに沿うように修正。

What is the meaning of the version which is described in the parentheses?

Summary
The version is displayed `4.1.0 (4.1.1)` after Mattermost installation.  
I think the version 4.1.0 is installed, is my understanding correct?  
And what is the meaning of the version which is described in the parentheses, 4.1.1?

Steps to reproduce

1. Install the latest mattermost by [One-line Docker Install](https://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install).
2. Open the browser.
3. Click 'About Mattermost'.

Expected behavior

Display only `4.1.0`, not `4.1.0 (4.1.1)`.

Observed behavior (that appears unintentional)

![02](https://user-images.githubusercontent.com/32325140/31065986-8995fb34-a784-11e7-8659-59f0bc2e91d8.png)

**Comment by tochi-y** [comment]
コミュニティに報告。
https://github.com/mattermost/mattermost-server/issues/7547

**Comment by y-goto** [comment]
お疲れ様でした。 フィードバック後、返事がきたりすることもあると思いますが、ぜひ活動を続けてみてください。
