### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: kou: PHP document: Work log

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#603]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kou** [comment]
PHPのドキュメントはどこにあるだろう！

**Comment by kou** [comment]
「PHP document」で検索してみよう！
https://www.google.co.jp/search?q=php+document&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=0&ei=lJjRWar3H-6Q8Qeg94nACg

**Comment by kou** [comment]
PHPのドキュメントの日本語の情報ばかりが出てきて、本家の情報が見つからない！

**Comment by kou** [comment]
「PHP document」検索したら検索結果ページの1ページ目に出てほしいんだよなぁ。
なぜなら、。。。。
日本語のページがたくさんでるのもそれはそれでいい気はするけども、訳し間違いとかやくがよくわからないときとか、原文を確認したくなるから、公式の英語の文書も参照しやすくなるといいんだよなぁ。

**Comment by y-goto** [comment]
本日は本当にありがとうございました！
本Issueは役目を終えたのでクローズ致します。
