### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: chigiriki: ansible: Work log

### ISSUE THREAD

**Issue by chigiriki** [oss-gate/workshop#604]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by HidekazuMorimoto** [comment]
よろしくおねがいします。

**Comment by f-higashi** [comment]
よろしくお願いします

**Comment by chigiriki** [comment]
まずansibleの公式サイトを探そう

**Comment by chigiriki** [comment]
"ansible"でぐぐった
https://www.google.co.jp/search?hl=ja&q=ansible&lr=lang_ja&gws_rd=ssl

**Comment by chigiriki** [comment]
ググった結果の"すべての言語"にすると２つ目に公式サイトっぽいところがあった
https://www.ansible.com/

**Comment by chigiriki** [comment]
ＧＥＴ　ＳＴＡＲＴＥＤを押す

**Comment by chigiriki** [comment]
GET STARTEDページ、これどうすりゃええの

**Comment by chigiriki** [comment]
再生ボタン的なものを押したらEmailを要求された。
なんかいやなので×押して戻る。

**Comment by chigiriki** [comment]
STEP1を読もう。
”Download and install Ansible”というリンクがあった。押してみる。

**Comment by chigiriki** [comment]
ようやくインストール方法のページへ飛べた。
http://docs.ansible.com/ansible/latest/intro_installation.html

**Comment by chigiriki** [comment]
とりあえず最初のほう読もう。

**Comment by chigiriki** [comment]
_If you are wishing to run the latest released version of Ansible and you are running Red Hat Enterprise Linux (TM), CentOS, Fedora, Debian, or Ubuntu, we recommend using the OS package manager._
って書いてある。
aptでインストールするのがいいのか。

**Comment by chigiriki** [comment]
管理対象のノードにはSSHが必要です。
わかりました。

**Comment by chigiriki** [comment]
なんかこまごまとNote（注意事項）があって、ちょっと読みづらい
リモートノードでSELinuxが有効なら、libselinux-pythonをインストールしないといけない。

**Comment by chigiriki** [comment]
どこに、ってそのリモートノードに。ってことか。

**Comment by chigiriki** [comment]
Python3サポートとかsimplejson module とかの記事もあるが、今回のマシンには関係なさそうなのでとりあえず読み飛ばす。

**Comment by chigiriki** [comment]
Aptでのインストール
http://docs.ansible.com/ansible/latest/intro_installation.html#id15
をやってみる。

**Comment by chigiriki** [comment]
PPAってなんだ？
apt-getのリポジトリのことかな。

**Comment by chigiriki** [comment]
コマンド例の３つ目で失敗した。
$ sudo apt-get update
・・・
パッケージリストを読み込んでいます... 完了
oss-gate@FVc6167:~$ sudo apt-get install software-properties-common
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています
状態情報を読み取っています... 完了
software-properties-common はすでに最新バージョン (0.96.20.7) です。
アップグレード: 0 個、新規インストール: 0 個、削除: 0 個、保留: 0 個。
$  sudo apt-add-repository ppa:ansible/ansible
Cannot add PPA: 'ppa:~ansible/ubuntu/ansible'.
ERROR: '~ansible' user or team does not exist.

**Comment by chigiriki** [comment]
ansible という名前のユーザを作らないといけないのかな

**Comment by f-higashi** [comment]
> PPAってなんだ？
apt-getのリポジトリのことかな。

パーソナルパッケージアーカイブ のようです

https://allabout.co.jp/gm/gc/438675/

**Comment by chigiriki** [comment]
sudoに-E つけたらいけた

$ sudo -E apt-add-repository ppa:ansible/ansible
 Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy. Avoid writing scripts or custom code to deploy and update your applications― automate in a language that approaches plain English, using SSH, with no agents to install on remote systems.

http://ansible.com/
 More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpj93csgqm/secring.gpg' created
gpg: keyring `/tmp/tmpj93csgqm/pubring.gpg' created
gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpj93csgqm/trustdb.gpg: trustdb created
gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

**Comment by chigiriki** [comment]
つづけよう

**Comment by chigiriki** [comment]
$ sudo apt-get update
ヒット:1 http://jp.archive.ubuntu.com/ubuntu xenial InRelease
ｰ・牴蜑・ http://jp.archive.ubuntu.com/ubuntu xenial-updates InRelease
ｰ・牴蜑・ http://jp.archive.ubuntu.com/ubuntu xenial-backports InRelease
取得:4 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease [18.0 kB]
ヒット:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
取得:6 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages [560 B]
取得:7 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main i386 Packages [560 B]
取得:8 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main Translation-en [340 B]
19.5 kB を 2秒 で取得しました (7,579 B/s)
パッケージリストを読み込んでいます... 完了

いい感じ

**Comment by chigiriki** [comment]
$ sudo apt-get install ansible
・・・

うまくいった。

**Comment by chigiriki** [comment]
apt-add-repository でproxyが越えられなかったせいで失敗したが
apt-add-repositoryで失敗したのはproxyのせいだとわからなかった。
apt-getのために、/etc/apt/apt.conf.d/80proxy に設定を書いていて、apt-getは問題なくproxyを越えられたので、apt-add-repositoryではproxy設定が別に必要だと思わなかった。
proxy内でインストールする際の記事があればよかった。

**Comment by chigiriki** [comment]
"Latest Releases Via Apt (Ubuntu)"において
http://docs.ansible.com/ansible/latest/intro_installation.html#id15
Proxy環境内で実行した際に、apt-add-repository で失敗した。
私の環境では /etc/apt/apt.conf.d/80proxy にproxy設定を書いてあるが、apt-add-repositoryには効かなかった。

```
$ sudo apt-add-repository ppa:ansible/ansible
 Cannot add PPA: 'ppa:~ansible/ubuntu/ansible'.
 ERROR: '~ansible' user or team does not exist.
```

Proxy環境内で実行する場合のコマンド例も載せてほしい。
例えば、
`$ sudo http_proxy=http://<proxy_user>:<proxy_password>@<proxy_server>:<proxy_port> apt-add-repository  ppa:ansible/ansible`

**Comment by chigiriki** [comment]
言いたいことは大体まとまったのでgithubのCONTRIBUTING.mdを読もう。
https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md

**Comment by chigiriki** [comment]
”[I’d Like To Help With Documentation](http://docs.ansible.com/ansible/latest/community.html#i-d-like-to-help-with-documentation)”
ここを読めばいいかな

**Comment by chigiriki** [comment]
アドバイスもらったので投稿する記事を推敲する

**Comment by chigiriki** [comment]
"[Latest Releases Via Apt (Ubuntu)](http://docs.ansible.com/ansible/latest/intro_installation.html#id15)"において
Proxy環境内での実行方法も載せてほしい。
例えば、
```
$ export http_proxy=http://<proxy_user>:<proxy_password>@<proxy_server>:<proxy_port>
$ export https_proxy=http://<proxy_user>:<proxy_password>@<proxy_server>:<proxy_port>
$ sudo -E apt-get update
$ sudo -E apt-get install software-properties-common
$ sudo -E apt-add-repository ppa:ansible/ansible
$ sudo -E apt-get update
$ sudo -E apt-get install ansible
```


apt-getのために /etc/apt/apt.conf.d/80proxy にproxy設定を書くひともいるだろうが、apt-add-repositoryには効かなかった。

```
$ sudo apt-add-repository ppa:ansible/ansible
 Cannot add PPA: 'ppa:~ansible/ubuntu/ansible'.
 ERROR: '~ansible' user or team does not exist.
```

**Comment by chigiriki** [comment]
英語化してみる

**Comment by chigiriki** [comment]
Please add installation steps for backward of proxy environment to "[Latest Releases Via Apt (Ubuntu)](http://docs.ansible.com/ansible/latest/intro_installation.html#id15)".
For example,
```
$ export http_proxy=http://<proxy_user>:<proxy_password>@<proxy_server>:<proxy_port>
$ export https_proxy=http://<proxy_user>:<proxy_password>@<proxy_server>:<proxy_port>
$ sudo -E apt-get update
$ sudo -E apt-get install software-properties-common
$ sudo -E apt-add-repository ppa:ansible/ansible
$ sudo -E apt-get update
$ sudo -E apt-get install ansible
```


I wrote proxy settings to /etc/apt/apt.conf.d/80proxy, but apt-add-repository command does not refer that setting. 
I got following error mesages.
```
$ sudo apt-add-repository ppa:ansible/ansible
 Cannot add PPA: 'ppa:~ansible/ubuntu/ansible'.
 ERROR: '~ansible' user or team does not exist.
```

**Comment by chigiriki** [comment]
出しちゃった。
https://github.com/ansible/ansible/issues/31165

**Comment by chigiriki** [comment]
フィードバック完了済。
トリアージされ、Assigneeが決まったようだ。

**Comment by y-goto** [comment]
お疲れ様でした。
これが終わりではなくて始まりです。
Assigneeの方から色々質問とか来たりすることもあると思います。
ぜひ今後とも活動を続けて欲しいと思います。
