### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: tfnagao: GlassFish: Work log

### ISSUE THREAD

**Issue by tfnagao** [oss-gate/workshop#605]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mikami3** [comment]
よろしくお願いします

**Comment by tfnagao** [comment]
GitHub上のREADMEを見てビルド＆インストールする。
https://github.com/javaee/glassfish

**Comment by tfnagao** [comment]
JDK8+が必要とのこと。オラクルの公式サイトからダウンロードする。
http://www.oracle.com/technetwork/articles/javase/index-jsp-138363.html

最新バージョンはJDK9だけど、今回はJDK8をダウンロードする。

**Comment by tfnagao** [comment]
jdk-8u144-linux-x64.tar.gz をダウンロードして、JDK8を入れる。
```
$ tar xvf  jdk-8u144-linux-x64.tar.gz
$ sudo mv jdk1.8.0_144/ /opt
$ export PATH=/opt/jdk1.8.0_144/bin:$PATH
$ export JAVA_HOME=/opt/jdk1.8.0_144/
```

**Comment by tfnagao** [comment]
Maven 3.0.3+も必要とのこと。公式サイトからMavenをダウンロード。
https://maven.apache.org/download.cgi

apache-maven-3.5.0-bin.tar.gz をダウンロードした。

**Comment by tfnagao** [comment]
```
$ tar xvf apache-maven-3.5.0-bin.tar.gz
```

**Comment by tfnagao** [comment]
インストールドキュメントを見ながらインストールする。
https://maven.apache.org/install.html

**Comment by tfnagao** [comment]
```
$ sudo mv apache-maven-3.5.0 /opt
$ export PATH=/opt/apache-maven-3.5.0/bin:$PATH
```
``mvn -v`` して、とりあえず動くことを確認した。

**Comment by tfnagao** [comment]
JDKとMavenがインストールできたので、GlassFishをビルドする。
```
$ mvn install
```

**Comment by tfnagao** [comment]
ビルドに成功した。
"Locate the Zip distributions:" のところに書かれている2つのZIPファイルができていることを確認。
```
$ ls appserver/distributions/glassfish/target/
archive-tmp  dependency  dependency-maven-plugin-markers  glassfish.zip  stage
$ ls appserver/distributions/web/target/
archive-tmp  dependency  dependency-maven-plugin-markers  stage  web.zip
```

**Comment by tfnagao** [comment]
"Locate staged distributions:" に書かれている2つのディレクトリもできている。

**Comment by tfnagao** [comment]
GlassFish を起動してみる。READMEには単に ``glassfish5/bin/asadmin start-domain`` と書いてあるだけで、どこに asadmin ができているかわからない。``find`` で探してみる。
```
$ find . | grep glassfish5/bin/asadmin
./appserver/packager/glassfish-common-web/target/stage/glassfish5/bin/asadmin.bat
./appserver/packager/glassfish-common-web/target/stage/glassfish5/bin/asadmin
./appserver/distributions/minnow/target/stage/glassfish5/bin/asadmin.bat
./appserver/distributions/minnow/target/stage/glassfish5/bin/asadmin
./appserver/distributions/minnow/target/dependency/glassfish5/bin/asadmin.bat
./appserver/distributions/minnow/target/dependency/glassfish5/bin/asadmin
./appserver/distributions/web/target/stage/glassfish5/bin/asadmin.bat
./appserver/distributions/web/target/stage/glassfish5/bin/asadmin
./appserver/distributions/web/target/dependency/glassfish5/bin/asadmin.bat
./appserver/distributions/web/target/dependency/glassfish5/bin/asadmin
./appserver/distributions/glassfish/target/stage/glassfish5/bin/asadmin.bat
./appserver/distributions/glassfish/target/stage/glassfish5/bin/asadmin
./appserver/distributions/glassfish/target/dependency/glassfish5/bin/asadmin.bat
./appserver/distributions/glassfish/target/dependency/glassfish5/bin/asadmin
```

**Comment by f-higashi** [comment]
コマンドと結果がセットになっており、また何を確認したかもコメントも記載されているのが良かったです
自分の環境情報を最初に書いておくとよりよいと思います

**Comment by tfnagao** [comment]
``glassfish5/bin/asadmin`` がどこにあるか分からなかった。
READMEに書かれている "Zip distributions" と "staged distributions" の中に ``glassfish5`` ディレクトリがある、ということがREADMEを読んだだけでわかれば、つまづかずにすみそう。

**Comment by tfnagao** [comment]
"Building" 節の最後に次のような説明を入れるのがよい？
「これらのディストリビューションのルートディレクトリは ``glassfish5`` です。」

それか、"Starting GlassFish" 節で、コマンドの後に次のような注記を入れる。
「ここで、``glassfish5`` はディストリビューションのルートディレクトリです。」

**Comment by tfnagao** [comment]
Improve README.md

In the "Starting GlassFish" section of ``README.md``, I could not find out the location of ``glassfish5`` at first sight.

To make ``README.md`` self-contained, I want to propose inserting some explanation such that:
```
Note that ``glassfish5`` is the root directory of the distributions.
```

**Comment by tfnagao** [comment]
場所を指定するのを忘れていた。最後に次の文言も入れる。

at the end of the "Starting GlassFish" section.

**Comment by mikami3** [comment]
Issueのタイトルは、他のIssueを参考にするとベター。
README.mdの修正提案をしているタイトルなどを探してみると判りやすい。
glassfish Issue README　とかでググってみるとか。

**Comment by tfnagao** [comment]
タイトルをもう少し具体的に。

Add explanation for the name of distro root directories to README.md

**Comment by tfnagao** [comment]
イシュー出してみました！
https://github.com/javaee/glassfish/issues/22284

**Comment by tfnagao** [comment]
イシュー出してみました！
https://github.com/javaee/glassfish/issues/22284

**Comment by tfnagao** [comment]
イシュー発行しました。
https://github.com/javaee/glassfish/issues/22284

**Comment by y-goto** [comment]
お疲れ様でした。
issueに対するコミュニティの反応が楽しみですね。
ぜひ、応対もトライしてみてください。
困ったときは私や当日のサポーターに相談してみましょう。
