### ISSUE TITLE
 OSS Gate Workshop: Fujitsu: 2017-10-2: a.shiraishi: OpenStack Monasca: Work log

### ISSUE THREAD

**Issue by akihiro-shiraishi** [oss-gate/workshop#606]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kaakaa** [comment]
よろしくお願いしまーす

**Comment by nekia** [comment]
よろしくおねがいします。Gateをくぐりましょう

**Comment by akihiro-shiraishi** [comment]
monascaについて検索

**Comment by akihiro-shiraishi** [comment]
｢Openstack Monasca｣で検索
https://wiki.openstack.org/wiki/Monasca#License

**Comment by akihiro-shiraishi** [comment]
概要を読みます

**Comment by akihiro-shiraishi** [comment]
使い方についての記述をさがす

**Comment by akihiro-shiraishi** [comment]
SSHでマシン接続

**Comment by akihiro-shiraishi** [comment]
利用手順についての記述が公式ウィキにない(っぽい)
｢monasca 利用手順｣で検索

**Comment by akihiro-shiraishi** [comment]
monascaマシンにブラウザでアクセスしたが、日本語化が不十分に感じる

**Comment by akihiro-shiraishi** [comment]
monascaに監視するサーバ、アプリケーションの追加はどう行うんだろう

**Comment by akihiro-shiraishi** [comment]
監視対象のサーバはどうすればいいんだろうか

**Comment by akihiro-shiraishi** [comment]
サーバ追加操作についての公式記述を探す
https://wiki.openstack.org/wiki/Monasca#Overview

**Comment by akihiro-shiraishi** [comment]
モニタリングについての記述参照
https://wiki.openstack.org/wiki/Monasca/Monitoring_Of_Monasca

**Comment by akihiro-shiraishi** [comment]
monasca usageで検索
https://github.com/openstack/monasca-vagrant/blob/master/README.md

**Comment by akihiro-shiraishi** [comment]
monascaの手順が見当たらないので再度検索｢monasca 手順｣
https://www.slideshare.net/VirtualTech-JP/ss-44333970

**Comment by akihiro-shiraishi** [comment]
http://software.fujitsu.com/jp/manual/manualfiles/m160010/j2ul2187/01z000/j2ul-2187-01z0.pdf

**Comment by akihiro-shiraishi** [comment]
ssh接続先で[monasca metric-list]
Ignoring domain related config project_domain_id because identity API version is 2.0
Ignoring domain related config user_domain_id because identity API version is 2.0
Ignoring domain related config project_domain_id because identity API version is 2.0
Ignoring domain related config user_domain_id because identity API version is 2.0
Expecting to find domain in project. The server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error. (HTTP 400) (Request-ID: req-e1aa0edc-72d6-4d84-be1b-5087f9661fbc)

**Comment by akihiro-shiraishi** [comment]
monascaコマンド一覧
Commands:
  alarm-count    Count alarms.
  alarm-definition-create  Create an alarm definition.
  alarm-definition-delete  Delete the alarm definition.
  alarm-definition-list  List alarm definitions for this tenant.
  alarm-definition-patch  Patch the alarm definition.
  alarm-definition-show  Describe the alarm definition.
  alarm-definition-update  Update the alarm definition.
  alarm-delete   Delete the alarm.
  alarm-history  Alarm state transition history.
  alarm-history-list  List alarms state history.
  alarm-list     List alarms for this tenant.
  alarm-patch    Patch the alarm state.
  alarm-show     Describe the alarm.
  alarm-update   Update the alarm state.
  command list   List recognized commands by group (python-openstackclient)
  complete       print bash completion command (cliff)
  dimension-name-list  List names of metric dimensions.
  dimension-value-list  List names of metric dimensions.
  help           print detailed help for another command (cliff)
  measurement-list  List measurements for the specified metric.
  metric-create  Create metric.
  metric-create-raw  Create metric from raw json body.
  metric-list    List metrics for this tenant.
  metric-name-list  List names of metrics.
  metric-statistics  List measurement statistics for the specified metric.
  module list    List module versions (python-openstackclient)
  notification-create  Create notification.
  notification-delete  Delete notification.
  notification-list  List notifications for this tenant.
  notification-patch  Patch notification.
  notification-show  Describe the notification.
  notification-type-list  List notification types supported by monasca.
  notification-update  Update notification.

**Comment by osanai-hisashi** [comment]
確かに利用者ガイドがないと、どのように使ってよいかわからないですね。
良いフィードバック・ネタが見つかりましたね！

**Comment by akihiro-shiraishi** [comment]
利用法に関するドキュメントがないので、どうやって使えばいのかわからない。。。
そもそも監視サーバ追加は？アラートの設定は？UIで行う？コマンドで実行する？

**Comment by akihiro-shiraishi** [comment]
Monascaを利用して、サーバを監視しようとしたが、モニタリングサーバ一覧にどのようにサーバを追加するのかで躓いた。
公式ドキュメントに従って追加を試みたが、ドキュメントに具体的な追加方法・監視方法が記載されていない。
https://wiki.openstack.org/wiki/Monasca
例えば、インストールしてブラウザで表示確認、その後追加等の一連の仮想的な仕様についての操作が記載されているとわかりやすい。

**Comment by akihiro-shiraishi** [comment]
利用者ガイドがどれなのかを聞いてもよい

**Comment by akihiro-shiraishi** [comment]
サーバ監視をmonascaで行おうとしているが、
monascaで検索して1番最初にヒットした公式wiki(https://wiki.openstack.org/wiki/Monasca)に具体的な追加方法・監視方法を見つけることができなかった。
サーバ追加法、その他一般的な操作に関するガイドはどこにあるか

**Comment by akihiro-shiraishi** [comment]
サーバ監視をmonascaで行おうとしたが、監視サーバの追加方法がわからなかった。
「monasca」で検索して1番最初にヒットした公式wiki(https://wiki.openstack.org/wiki/Monasca)に具体的な追加方法・監視方法を見つけることができなかった。
サーバ追加法、その他一般的な操作に関するガイドはどこにあるか

**Comment by akihiro-shiraishi** [comment]
issue報告先がわからない

**Comment by akihiro-shiraishi** [comment]
I tried to monitor the server at monasca, but I did not know how to add the monitoring server.

I could not find a concrete addition method / monitoring method in the official wiki (https://wiki.openstack.org/wiki/Monasca) that I searched for in "monasca" and hit first.

Please tell me where the user guide on server addition method and other general operations is

**Comment by akihiro-shiraishi** [comment]
title:I can not see the document for users

**Comment by akihiro-shiraishi** [comment]
サーバ監視をmonascaで行おうとしたが、監視サーバの追加方法がわからなかった。
「monasca」で検索して1番最初にヒットした公式wiki(https://wiki.openstack.org/wiki/Monasca)に具体的な追加方法・監視方法を見つけることができなかった。
その他にも
・https://wiki.openstack.org/wiki/Monasca/Monitoring_Of_Monasca
・https://github.com/openstack/monasca-agent/blob/master/README.md
を見てみたが、操作方法についての記述を見つけることができなかった。
サーバ追加法、その他一般的な操作に関するユーザーガイドはどこにあるか教えてほしい

**Comment by akihiro-shiraishi** [comment]
I tried to monitor the server at monasca, but I did not know how to add the monitoring server.

I could not find a concrete addition method / monitoring method in the official wiki (https://wiki.openstack.org/wiki/Monasca) that I searched for in "monasca" and hit first.

Other
· Https://wiki.openstack.org/wiki/Monasca/Monitoring_Of_Monasca
· Https://github.com/openstack/monasca-agent/blob/master/README.md
I could not find a description about the operation method though.

Please tell me where the user guide on server addition method and other general operations is?

**Comment by akihiro-shiraishi** [comment]
title:I can not find the document for adding monitoring server

**Comment by akihiro-shiraishi** [comment]
I tried to monitor the server at monasca, but I did not know how to add the monitoring server.

I could not find a concrete addition method / monitoring method in the official wiki (https://wiki.openstack.org/wiki/Monasca) that I searched for in "monasca" and hit first.

Other
· Https://wiki.openstack.org/wiki/Monasca/Monitoring_Of_Monasca
· Https://github.com/openstack/monasca-agent/blob/master/README.md
I could not find a description about the operation method though.

Would you like to tell me where the user guide on server addition method and other general operations is?

**Comment by akihiro-shiraishi** [comment]
launchpad-monascaプロジェクトにQuestionをpost
https://answers.launchpad.net/monasca/+question/658831

**Comment by akihiro-shiraishi** [comment]
あらためてmonascaの利用法を探す

**Comment by akihiro-shiraishi** [comment]
https://www.ntt-tx.co.jp/column/tec/openstack_summit_austin03/

**Comment by akihiro-shiraishi** [comment]
なぜか仮想マシンのmonascaに監視サーバ追加されている

**Comment by akihiro-shiraishi** [comment]
StackOverFlowで探してみる
https://stackoverflow.com/search?q=monasca

**Comment by akihiro-shiraishi** [comment]
インストールからセットアップまでを記述した(様な)記事を見つけたので読む
**https://blog.zhaw.ch/icclab/how-to-install-and-setup-monasca-1-3/**

**Comment by akihiro-shiraishi** [comment]
新規監視サーバ追加についての記述が見当たらない
