### ISSUE TITLE
OSS Gate Workshop: Fujitsu 2017-10-2}: HidekazuMorimoto: Fess: Work log

### ISSUE THREAD

**Issue by HidekazuMorimoto** [oss-gate/workshop#607]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: Fujitsu 2017-10-2}: HidekazuMorimoto: Fess: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nishi-fj-qis** [comment]
よろしくお願いします。

**Comment by chigiriki** [comment]
今日はよろしくお願いします。

**Comment by f-higashi** [comment]
よろしくお願いします

**Comment by HidekazuMorimoto** [comment]
Fessでgoogle.
http://fess.codelibs.org/ja/index.html
がヒット。

**Comment by HidekazuMorimoto** [comment]
構築サーバにproxyを設定
export no_proxy="127.0.0.1,localhost,*.ｘｘｘ.com"
export http_proxy="http://ｘｘｘ:1234567890@rep.proxy.ｘｘｘ.com:8080"
export https_proxy="http://ｘｘｘ:1234567890@rep.proxy.ｘｘｘ.com:8080"

**Comment by HidekazuMorimoto** [comment]
公式ドキュメント　http://fess.codelibs.org/ja/documentation.html　を参照
インストールにしたがいオペレーション。

**Comment by HidekazuMorimoto** [comment]
Fess を利用したい環境に Java がインストールされていない場合は、Oracle のサイト より JDK をインストールしてください
とあるので　http://www.oracle.com/technetwork/java/javase/downloads/index.html からrpmをダウンロードして転送しインストール。

**Comment by HidekazuMorimoto** [comment]
Fess をインストールする前に elasticsearch の RPM パッケージをインストールする必要があります。 https://www.elastic.co/downloads/elasticsearch からダウンロードし、インストールします。
とのことなのでダウンロードしてインストール。

**Comment by HidekazuMorimoto** [comment]
JDKがrpmではいらなかったので
https://qiita.com/tachapu/items/93e6e420227c0e241799
にしたがいインストール。

**Comment by HidekazuMorimoto** [comment]
ESは　https://www.elastic.co/downloads/past-releases/elasticsearch-5-6-1
のdebをダウンロードして転送してインストール

**Comment by HidekazuMorimoto** [comment]
oss-gate@FVc6168:~$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
oss-gate@FVc6168:~$

**Comment by HidekazuMorimoto** [comment]
DebパッケージはあったがDebパッケージを使用したインストール手順が記載されていない。

**Comment by HidekazuMorimoto** [comment]
ESのdebをダウンロードしたがインストール手順がない。

**Comment by f-higashi** [comment]
https://wiki.ubuntulinux.jp/UbuntuTips/Application/PackageManagementSystem/Apt

**Comment by HidekazuMorimoto** [comment]
dpkgでインストール

oss-gate@FVc6168:~$ sudo dpkg -i elasticsearch-5.6.1.deb
以前に未選択のパッケージ elasticsearch を選択しています。
(データベースを読み込んでいます ... 現在 59093 個のファイルとディレクトリがインストールされています。)
elasticsearch-5.6.1.deb を展開する準備をしています ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
elasticsearch (5.6.1) を展開しています...
elasticsearch (5.6.1) を設定しています ...
systemd (229-4ubuntu19) のトリガを処理しています ...
ureadahead (0.100.0-19) のトリガを処理しています ...

**Comment by HidekazuMorimoto** [comment]
oss-gate@FVc6168:~$ sudo dpkg -i fess-11.4.0.deb 
[sudo] password for oss-gate: 
以前に未選択のパッケージ fess を選択しています。
(データベースを読み込んでいます ... 現在 59225 個のファイルとディレクトリがインストールされています。)
fess-11.4.0.deb を展開する準備をしています ...
Creating fess group... OK
Creating fess user... OK
fess (11.4.0) を展開しています...
fess (11.4.0) を設定しています ...
systemd (229-4ubuntu19) のトリガを処理しています ...
ureadahead (0.100.0-19) のトリガを処理しています ...

**Comment by HidekazuMorimoto** [comment]
インストール完了。
初期セットアップへ。

**Comment by HidekazuMorimoto** [comment]
fessの事前準備としてelasticsearchのインストールはzipの場合もrpmの場合も必須ではないか。現状rpmの場合にのみ書いてある。

**Comment by HidekazuMorimoto** [comment]
インストールの項目にerasticsearchとfessの連携方法が一緒くたに書いてあるが別の項目に起すべきではないか。

**Comment by HidekazuMorimoto** [comment]
インストールの配下にElasticsearchクラスタの利用方法があるのは違う気がする

**Comment by HidekazuMorimoto** [comment]
とりあえずdebianのやり方が書いてないのに絞る

**Comment by HidekazuMorimoto** [comment]
UbuntuにてInstallationのドキュメントを参照しながらインストールを実施していたのですが、"Using ZIP package"と"Using RPM package"の記述はあるのですが、 "Using DEB package"がなく戸惑いました。"Using DEB package"があれば理解しやすいと思います。また、”Using Your Elasticsearch Cluster On ZIP package”は一見上記の項目と同レベルの項目に見えますが、実際には、"Using ZIP package"の追加情報かインストールの次の段階のオペレーションのため、この位置に記述するのは混乱を招くと思います。

**Comment by HidekazuMorimoto** [comment]
I installed Fess on ubuntu while referring to your Installation document (http://fess.codelibs.org/11.4/install/index.html).
There are sections "Using ZIP package" and "Using RPM package",but a section of "DEB package using" is lacking.
It is confusing. 
I think that it is easier to understand if "Using DEB package" is available.

**Comment by HidekazuMorimoto** [comment]
UbuntuにてFessインストールガイドを参照しながらインストールを実施していたのですが、
「ZIP パッケージの場合」と「RPM パッケージの場合」の記述はあるのですが、 "
DEBパッケージを使用するため戸惑いました。「DEBパッケージの場合」をくわえるか、
まとめて「パッケージを利用する場合」などと記述すれば理解しやすいのではないでしょうか。

**Comment by HidekazuMorimoto** [comment]
対象のossの既存のissueが全部日本語だったので日本語で投稿済み。
クローズ

**Comment by y-goto** [comment]
お疲れさまでした。
投稿後、反応はどうだったでしょうか？
ぜひ、意見が反映されるまで続けて見てください。
