### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: Shinsa888: OpenStack Monasca: Work log

### ISSUE THREAD

**Issue by Shinsa888** [oss-gate/workshop#608]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tideri** [comment]
今日はよろしくお願いします

**Comment by fjtkodama** [comment]
よろしくお願いします。

**Comment by Shinsa888** [comment]
Monascaの公式サイトを開こうとしたが、どこが公式サイトかわからなかった。
とりあえず以下のサイトを開いた。
https://wiki.openstack.org/wiki/Monasca
http://monasca.io/

**Comment by Shinsa888** [comment]
wikiって公式サイトなのか？と思った。

**Comment by Shinsa888** [comment]
↓が公式サイトっぽい。
https://www.openstack.org/

**Comment by Shinsa888** [comment]
[Doc]-[View the Docs]-[End User Guides]を選択。マニュアル一覧が表示されるが、Monascaの操作マニュアルがどれなのかわからない。
https://docs.openstack.org/pike/user/

**Comment by Shinsa888** [comment]
Monascaの環境は構築済みとのこと。GUIの操作マニュアルは無いとのことなので、まずはアラーム定義を作成して監視対象に負荷を与えてどうモニタされるかを確認してみる。

**Comment by Shinsa888** [comment]
まず、以下のアラーム定義を作成した。Severityの詳細説明がほしい。それぞれの設定に対してどのような挙動をするのかが分からない。
　名前：[test-alarm]
    説明：[test-alarm]
    Severity：[Low]

**Comment by Shinsa888** [comment]
アラームを作成しようとしたが、[Expression]画面で[No metric available]と表示されたため作成できなかった。アラーム作成前にメトリックの作成が必要らしい。アラームの作成を中断。
----------------------------------------------
Each alarm definition is defined by its expression composed out of: mathematical function, metric, threshold and comparator for metric's value and the threshold.
----------------------------------------------

**Comment by Shinsa888** [comment]
アラームの作成前にメトリックの作成が必要だということが分かるとうれしい。

**Comment by Shinsa888** [comment]
メトリックの作成方法が不明。メニューにそれらしいものが無い。

**Comment by Shinsa888** [comment]
UI操作について公式マニュアルがないため、どこに何の情報があるのかわからない。
(例：各ユーザーに割り当てられた権限、各パラメータの意味、各操作に必要な前提条件など)

マニュアルがないならばUIに説明を表示するか、情報が記載されているサイトへのナビゲーションがほしい。

**Comment by Shinsa888** [comment]
↑だとフィードバックの範囲が大き過ぎるので、今回はアラーム作成時に事前にメトリックの作成が必要だということに焦点をあててフィードバックする。

**Comment by Shinsa888** [comment]
Monascaの操作画面でアラームを作成するため、[Monitoring]-[Alarm Difinications]から新規アラームを作成しようとした。
しかし、[Expression]に[No metric available]というメッセージが表示されアラームが作成できなかった。

画面上部の注意書きからあらかじめメトリックを作成する必要があると判断したが、メトリックの作成方法について情報が記載されていない。
([Expression]横の[?]マークにカーソルを合わせても[An alarm expression]としか表示されない)
メトリックの作成方法について情報が記載されているページへのナビゲーションが欲しい。

**Comment by Shinsa888** [comment]
小見出しを作成して文章を見やすくした。

・背景
Monascaの操作画面でアラームを作成するため、[Monitoring]-[Alarm Difinications]から新規アラームを作成しようとした。
しかし、[Expression]に[No metric available]というメッセージが表示されアラームが作成できなかった。
画面上部の注意書きからあらかじめメトリックを作成する必要があると判断したが、メトリックの作成方法について情報が記載されていない。
([Expression]横の[?]マークにカーソルを合わせても[An alarm expression]としか表示されない)

・要望
メトリックの作成方法について情報が記載されているページへのナビゲーションが欲しい。

・環境
OpenStack Monasca(Pike)

**Comment by Shinsa888** [comment]
英訳した↓

・Background
I tried to create a new alarm on [Alarm Difinications] window.
But it was failed and displayed the message "No metric available" at [Expression].
I realized that I need to create metrics before create Alarms,
however there is no information about creating metrics.

・Request
I want to the guide to webpages about creating metrics at the window displayed when the cursor is over the question mark.

・Environment
OpenStack Monasca(Pike)

**Comment by Shinsa888** [comment]
↑の内容でフィードバック完了しました。

**Comment by y-goto** [comment]
お疲れ様でした。
返事が返ってきたら、対応できるようにがんばってください。
困ったときは私にメールを送るなどして、相談してください。
