### ISSUE TITLE
 OSS Gate Workshop: fujitsu: 2017-10-02: nishi-fj-qis: monasca: Work log

### ISSUE THREAD

**Issue by nishi-fj-qis** [oss-gate/workshop#609]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by nishi-fj-qis** [comment]
よろしくお願いいたします。

**Comment by mikami3** [comment]
宜しくお願い致します。

**Comment by nishi-fj-qis** [comment]
公式サイトを開く　monasca　だ。
https://www.openstack.org/software/releases/ocata/components/monasca

**Comment by nishi-fj-qis** [comment]
インストール方法を調べる！
ン！どうするんだ？

**Comment by nishi-fj-qis** [comment]
get started ? source code ?

**Comment by nishi-fj-qis** [comment]
get start は、openstack 全般のことみたい。どこだ？

**Comment by nishi-fj-qis** [comment]
Option 2: Local Dev Environment: devstack.org
の
running devstack quick start
or 
wiki

**Comment by nishi-fj-qis** [comment]
monasca install で　ググる
https://github.com/hpcloud-mon/monasca-installer
これかな？

**Comment by nishi-fj-qis** [comment]
上のは誰かの記録。公式を探すぞ。

**Comment by nishi-fj-qis** [comment]
monasca wiki を探す。
https://wiki.openstack.org/wiki/Monasca
から
Development Environment
• Monasca DevStack Plugin: ◦ DevStack is the primary developmement environment for OpenStack. ◾See http://docs.openstack.org/developer/devstack/

◦ The Monasca DevStack plugin installs the Monasca Service, Agent, Horizon Monitoring Panel, and Grafana
◦ README at, https://github.com/openstack/monasca-api/tree/master/devstack

plugin ? わかりくいな？

**Comment by nishi-fj-qis** [comment]
つきの
Best way to get started is to use Vagrant with the Vagrantfile at, https://github.com/openstack/monasca-api/blob/master/devstack/Vagrantfile
こっちか

**Comment by nishi-fj-qis** [comment]
Vagrant　を知らない。

**Comment by nishi-fj-qis** [comment]
Vagrant monasca でググると
https://github.com/openstack/monasca-vagrant
にたどり着いた。

**Comment by f-higashi** [comment]
ログから思考過程が把握できるので、忘れた頃に見ても、わかりやすいと思います 

なお、失敗した部分はコメントの最初にこれはうまくいかなかったとかを追記しとくといいです

**Comment by nishi-fj-qis** [comment]
フィードバックする内容
公式サイトを開く　monasca　の
https://www.openstack.org/software/releases/ocata/components/monasca
は、DevStack で openstack 全体の話しになっていている。
monasca の個別のインストールについては、ここ　という誘導がない。
誘導があるほうが、monasca　をターゲットにしたひとにはわかりやすい。
さらに、MAC と　ubuntu は、例があるが、RedHat/CentOS については、
コメントが無いので、wikiやFQAを探してね　があるとよい。

**Comment by nishi-fj-qis** [comment]
Vagrant がベストだと言っているが、Vagrant を知らない人には優しくない説明。

**Comment by nishi-fj-qis** [comment]
インストールとして何が書いてある？
openstackごとまるまるインストール
開発環境のインストール
何が書いて無い？
monasca　を既存のopenstack にインストール

**Comment by nishi-fj-qis** [comment]
monasca は、どのopenstack バージョンからサポート？

**Comment by nishi-fj-qis** [comment]
チャット、メーリングリストで聞いてみるのもひとつとアドバイスをいただいた。

**Comment by nishi-fj-qis** [comment]
monasca は、Newton　からサポートしている。

**Comment by nishi-fj-qis** [comment]
packstack　に向けた提案ができるか、継続して検討するということかな

**Comment by nishi-fj-qis** [comment]
一旦クローズとします。

**Comment by y-goto** [comment]
お疲れ様でした。
