### ISSUE TITLE
OSS Gateワークショップ 2016-06-11: pataiji: doctree: 作業ログ

### ISSUE THREAD

**Issue by pataiji** [oss-gate/workshop#61]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by pataiji** [comment]
* READMEを読む
* 一度読んだけど再読

**Comment by pataiji** [comment]
* [ここ](https://github.com/rurema/doctree/wiki/ProjectTimeLine)から辿れるWorkinSchemeがない
* かなしい

**Comment by pataiji** [comment]
* [ここ](https://github.com/rurema/doctree/wiki/ClassReferenceManualFormat)から[ここ](http://www.fdiary.net/ml/ruby-reference-manual/msg/587)にリンクが
* sublibraryについて書いてあるらしいけどなにそれ

**Comment by pataiji** [comment]
* 読んだ
* gemのnamespace配下のクラスをsublibraryということですな。このMLの結果どうなったんだ

**Comment by pataiji** [comment]
* 読んでる https://github.com/rurema/doctree/wiki/ClassReferenceManualFormat
* 「インデントするとリストになります。」ってmd慣れているとビビる

**Comment by pataiji** [comment]
* 読んだ https://github.com/rurema/doctree/wiki/ClassReferenceManualFormat
* 長い、長かった。

**Comment by pataiji** [comment]
* 読む https://github.com/rurema/doctree/wiki/FrequentlyAskedQuestions
* メンバー向けなので読まなくていい説

**Comment by pataiji** [comment]
* 読んでる https://github.com/rurema/doctree/wiki/FrequentlyAskedQuestions
* PublicComments がなくてかなしい

**Comment by pataiji** [comment]
* 読んだ https://github.com/rurema/doctree/wiki/FrequentlyAskedQuestions
* ProjectGoalの章をひたすら読んでたけど分量多いのでHowToJoinにスキップ

**Comment by pataiji** [comment]
* 読む https://github.com/rurema/doctree/wiki/HowToJoin
* コレを読む日を待ってた感

**Comment by pataiji** [comment]
* 参加方法読む
* メーリングリストに参加すればいいようで

**Comment by pataiji** [comment]
* アーカイブを見てみる
* 最後のメールでML will be closed soonって書いてあるんですが

**Comment by pataiji** [comment]
* ML登録する
* 何も考えずとりあえずメール送って登録した

**Comment by pataiji** [comment]
https://github.com/rurema/doctree/wiki/HowToJoin

HowToJoinの参加方法でMLへの参加が必要とあるが、2015/2/20のメールを最後に、MLの運用が終了している模様。
それ以後のプロジェクトへの参加方法が不明なので、困る。

**Comment by pataiji** [comment]
https://github.com/rurema/doctree/wiki/MailingList

上記MailingListのページで、
> プロジェクトに参加したい人は必ずメーリングリストに加入してください。

と記載されていますが、2015/02/20のメールを最後にMLの運用が終了しているように見受けられます。

プロジェクトに参加したいと思うのですが、どのような手順で参加すればいいでしょうか？
その後の参加方法がございましたら、ドキュメントの更新をお願いします。

**Comment by pataiji** [comment]
あとこれもPR送りたいす
https://github.com/rurema/doctree/issues/270

**Comment by pataiji** [comment]
* 読む https://github.com/rurema/doctree/wiki/HowToJoin#作業をはじめる
* 更新されてない感

**Comment by pataiji** [comment]
* BitClustの説明読む https://github.com/rurema/doctree/wiki/BitClust
* るりまオリジナルのツールか。メンテされてるのかな

**Comment by pataiji** [comment]
* 読んだ https://github.com/rurema/doctree/wiki/BitClust#使用方法
* Phase2WorkingSchemeのページが無いので使用方法がよくわからない.....

**Comment by pataiji** [comment]
* GitHub https://github.com/rurema/bitclust
* ここのREADMEにも有益な情報は書いていない

**Comment by pataiji** [comment]
調べてみました。

[`SecureRandom.hex`の実装](https://github.com/ruby/ruby/blob/ruby_2_3/lib/securerandom.rb#L118)
```ruby
def hex(n=nil)
  random_bytes(n).unpack("H*")[0]
end
```
---

```ruby
irb(main):008:0> "\x00".unpack("H*")[0]
=> "00"
irb(main):009:0> "\x01".unpack("H*")[0]
=> "01"
irb(main):010:0> "\x09".unpack("H*")[0]
=> "09"
irb(main):011:0> "\x88".unpack("H*")[0]
=> "88"
irb(main):012:0> "\xff".unpack("H*")[0]
=> "ff"
irb(main):013:0> "\xff\x00".unpack("H*")[0]
=> "ff00"
```

`random_bytes(n)`が必ずnサイズのバイト文字を返せば、`hex(n)`は必ずnの2倍のサイズの文字列を返しそうです。

[`SecureRandom.random_bytes`の説明](https://github.com/ruby/ruby/blob/ruby_2_3/lib/securerandom.rb#L85)には、
> The argument _n_ specifies the length of the result string.

とあるので、`SecureRandom.hex`は必ずnの2倍のサイズの文字列を返すことと思います。

こちらPull Request作成します。

**Comment by kou** [comment]
お疲れさまでした！
