### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: fjtkodama: Openstack_monasca: Work log

### ISSUE THREAD

**Issue by fjtkodama** [oss-gate/workshop#611]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tideri** [comment]
今日はよろしくお願いします

**Comment by Shinsa888** [comment]
本日はよろしくお願いします。

**Comment by fjtkodama** [comment]
よろしくお願いします

**Comment by fjtkodama** [comment]
monascaを利用する流れがかかれたページがみつからない

**Comment by fjtkodama** [comment]
インストールした後、チュートリアルがほしい

**Comment by fjtkodama** [comment]
MonascaのWiki 
  https://wiki.openstack.org/wiki/Monasca

**Comment by fjtkodama** [comment]
wikiの、Monitoringの項を確認。
　　Enablement and usage for monitoring the status of Monasca is under discussion. For more details see the link at, Monasca/Monitoring_Of_Monasca 
とあるので、まだ手順書は作成中のように見える。

https://wiki.openstack.org/wiki/Monasca/Monitoring_Of_Monasca
このページは、Monascaの仕様書のような内容が書かれている。

**Comment by fjtkodama** [comment]
![image](https://user-images.githubusercontent.com/32443412/31064764-6046798e-a77a-11e7-86a1-58d80bb82f78.png)

**Comment by fjtkodama** [comment]
フィードバックの対象：チュートリアルがほしい
今の状況：
1. 公式のチュートリアルがあるかわからない
2. なければ
　アラームの設定から検知までの流れを例で教えてほしい。

**Comment by fjtkodama** [comment]
目的：
Monasca 使用時のチュートリアルを見たい
理由：
https://wiki.openstack.org/wiki/Monasca
で、チュートリアルが見つからず、
使用方法がイメージできなかったため。


依頼：
チュートリアルの場所を教えてほしい。
無ければ、以下を満たすチュートリアルを
https://wiki.openstack.org/wiki/Monasca
においてほしい。


・
・
・

**Comment by fjtkodama** [comment]
Would you tell me where the tutorial of Monasca is?
If it does not exist, it is helpful for us to add the tutorial on wiki page.

理由：
https://wiki.openstack.org/wiki/Monasca
をみても、ユーザ目線でGUIを用いた使用方法がイメージできなかったため。

依頼：
チュートリアルの場所を教えてほしい。
無ければ、以下を満たすチュートリアルを
https://wiki.openstack.org/wiki/Monasca
においてほしい。

・アラームの作成（監視サーバの決定・監視データの設定）
・通知方法の設定
・発生時の例

**Comment by tideri** [comment]
http://lists.openstack.org/cgi-bin/mailman/listinfo/openstack-dev

**Comment by tideri** [comment]
http://lists.openstack.org/pipermail/openstack-dev/

**Comment by fjtkodama** [comment]
Status: Openstack の コミュニティにフィードバックを送付済み。掲載待ち。

Openstackのフィードバックは、Openstack-devのML宛にメールを送る必要があったが、
 社外メール送信の許可がされていなかったため、失敗した。
先ほど、申請をしてメールを送りました。

**Comment by fjtkodama** [comment]
Fujitsu EST (Germany)から、個別メール来ました。
別製品で使ってるから資料を送ってくれるそうです。
事情を相談して、資料をもらって、コミュニティからいったん取り下げようと考えています。

**Comment by fjtkodama** [comment]
Hi Witek,


Thank you for giving me a useful information.

I just started learning openstack monasca.
When I was reading the Wiki document first time, It was hard to understand how I start using it.
So, I sent this opinion for helping other newbie.

I'll try to use and learn monasca in reference to your information.

I understood that the documentation was improving now. 
and I would like to help to implove that to more useful.


Best regards,
T. Kodama

**Comment by fjtkodama** [comment]
Hi Witek-san,


Thank you for helping me at openstack-dev community,
and I appreciate your concern.

I'm sorry but I didn't know CMM and it was based on Monasca.
I just started learning about monasca.
After your mail, I found CMM manual in Fujitsu web site.
I will read it to understand monasca more.
If I need to more information, I will ask you and Silke-san to send some documents.


As my background, 
Now, I am evaluating server products in my work.
Recently, we are trying to test and evaluate servers under openstack environment.

In order to understand openstack more,
I joined openstack community,
and I asked a question about the document.

I'm concerned with server monitoring service for using evaluation. 
So, I started learning about monasca.

I might evaluate some product using Monasca as a future.
Going forward, I will send bug reports to community when I would find some bugs during my evaluation.


Best regards,
Takeyuki Kodama

**Comment by y-goto** [comment]
fjtkodama wrote...
-----
フィードバックに回答レスあり、レスに回答済み。

Fujitsu ESTのWitekさんから、Monascaの使い方について、記載箇所のレスをもらいました。
それを見て学習します、今後ドキュメントの改良に協力します。旨の返答をしました。

解決しましたので、issueをcloseねがいます。
よろしくお願いします。
-----

**Comment by y-goto** [comment]
お疲れさまでした。

公開ドキュメントを読んでみて、また分かりにくい箇所があれば、改善するよう提案して見てください。
