### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: echi-no: postgres: Work log

### ISSUE THREAD

**Issue by echi-no** [oss-gate/workshop#612]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by osanai-hisashi** [comment]
大丈夫です！

**Comment by ihara-noriyuki** [comment]
よろしくお願いします。

**Comment by echi-no** [comment]
ドキュメントを探します。

**Comment by echi-no** [comment]
日本語ドキュメントが見つかった。
https://www.postgresql.jp/document/9.6/html/
英語サイトがいいのか。.jpだからこのままでいいのか。

**Comment by echi-no** [comment]
英語サイトを見つけた。
https://www.postgresql.org/

**Comment by echi-no** [comment]
英語サイトを確認する。

**Comment by echi-no** [comment]
Documentation を見つけた。
中に日本語サイトが連携されていた。
https://www.postgresql.jp/document/9.6/html/

**Comment by echi-no** [comment]
インストールしてみる

**Comment by echi-no** [comment]
VMにつなぐ。

**Comment by echi-no** [comment]
FJWANにつなぐ

**Comment by echi-no** [comment]
VMにログイン完了

**Comment by echi-no** [comment]
GNU makeのバージョンが3.8以上必要らしい。
make --version　を実行してみる。

**Comment by echi-no** [comment]
# make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu

大丈夫なようだ。

**Comment by echi-no** [comment]
ソースコードの入手を以下に従って行う
https://www.postgresql.jp/document/9.6/html/install-getsource.html

**Comment by echi-no** [comment]
ソースコードの入手は英語サイトでおこなうらしい
linux版を選択。
https://www.postgresql.org/download/linux/redhat/

**Comment by echi-no** [comment]
マニュアルには以下を入手とある。
「postgresql-9.6.4.tar.gzまたはpostgresql-9.6.4.tar.bz2という名前のファイルを入手」
バージョンを選択するが、ダウンロードするものが見つからない。

**Comment by echi-no** [comment]
yumインストールが表示される。
yum install https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm

**Comment by echi-no** [comment]
ダウンロードページからの探し方が間違っていた。
マニュアルにはソースからインストールのとして
https://www.postgresql.org/download/
へリンクされていた。
バイナリとソースが同じページに表示されていると思ってしまった。
ただしくは、別途ソースのページを選択する。
https://www.postgresql.org/ftp/source/

**Comment by echi-no** [comment]
ソースをダウンロード　9.6.5　を選択。

**Comment by echi-no** [comment]
ファイルをアップロード。展開する。

**Comment by echi-no** [comment]
./configure　を実行する。
以下でためしてみる。

cd /root/postgresql-9.6.5
./configure

**Comment by echi-no** [comment]
実行してみた。以下が実行結果。

# ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking which template to use... linux
checking whether to build with 64-bit integer date/time support... yes
checking whether NLS is wanted... no
checking for default port number... 5432
checking for block size... 8kB
checking for segment size... 1GB
checking for WAL block size... 8kB
checking for WAL segment size... 16MB
checking for gcc... no
checking for cc... no
configure: error: in `/root/postgresql-9.6.5':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

**Comment by echi-no** [comment]
gcc ccがなかった。

**Comment by echi-no** [comment]
yum install gcc　を実行。

**Comment by echi-no** [comment]
再度　./configure　を実行してみる。

**Comment by echi-no** [comment]
以下のメッセージが出力

checking for library containing readline... no
configure: error: readline library not found
If you have readline already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-readline to disable readline support.

**Comment by echi-no** [comment]
readline library　が入っているか確認する。が確認方法がわからないので調べる。

**Comment by echi-no** [comment]
確認方法が見つからないがインストール手順が見つかったので入れる。
yum install readline readline-devel

**Comment by echi-no** [comment]
再度　./configure　を実行してみる。

**Comment by echi-no** [comment]
インストールについて、マニュアルには以下の記載がされている。（https://www.postgresql.jp/document/9.6/html/tutorial-install.html）

「1.1. インストール
自身でPostgreSQLをインストールする場合は、インストール手順を16章 ソースコードからインストールで確認してください。 そしてインストールが完了してから、本書に戻ってきてください。」

ソースコードのダウンロード先にはインストール用バイナリも公開されているが、ソースコードからの手順のみ記載されており、バイナリからの導入には触れていない。また、yumコマンドなどによる導入にも触れていない。

複数の導入方法について記載があると使用者にとってわかりやすいと思う。

**Comment by echi-no** [comment]
以下マニュアル「1.1. インストールについて」
https://www.postgresql.jp/document/9.6/html/tutorial-install.html
ソースコードからのインストール手順のみ記載されているが、バイナリ、yumコマンドによるインストール手順も記載されていると使用者にわかりやすいと思う。

**Comment by echi-no** [comment]
マニュアルのインストール記載について以下を参照しました。

PostgreSQL 9.6.4文書
1.1. インストール
https://www.postgresql.jp/document/9.6/html/tutorial-install.html
「自身でPostgreSQLをインストールする場合は、インストール手順を16章 ソースコードからインストールで確認してください。 そしてインストールが完了してから、本書に戻ってきてください。」

そのため、ソースコードのダウンロード先をとしてリンクをたどり以下を参照したところ
https://www.postgresql.org/download/
ソースコードとは別にインストール用バイナリも公開されているようでした。

マニュアルには、バイナリからのインストールについても記載されておりましたでしょうか。
もし公開されていれば手順を教えていただければと思います。
また公開されていないようであれば、バイナリからの手順を記載いただけるとよりわかりやすいと思います。

**Comment by echi-no** [comment]
インストールマニュアルに従って、初めてPostgreSQL 9.6.4をインストールしていますが
以下の箇所で疑問に思いました。

マニュアルのインストール記載について以下を参照しました。
PostgreSQL 9.6.4文書
1.1. インストール
https://www.postgresql.jp/document/9.6/html/tutorial-install.html
「自身でPostgreSQLをインストールする場合は、インストール手順を16章 ソースコードからインストールで確認してください。 そしてインストールが完了してから、本書に戻ってきてください。」

そのため、ソースコードのダウンロード先をとしてリンクをたどり以下を参照したところ
https://www.postgresql.org/download/
ソースコードとは別にインストール用バイナリも公開されているようでした。

マニュアルついて、バイナリからのインストールについて記載場所を教えていただければと
思います。

またソースコードからのインストールとバイナリからのインストールの手順の選択箇所が
あると、初心者にもよりわかりやすいと思います。

**Comment by osanai-hisashi** [comment]
インストールマニュアルに従って、初めてPostgreSQL 9.6.4をインストールしています。
バイナリからのインストール方法について記載されているドキュメントがあれば、
教えていただけないでしょうか？

マニュアルのインストール記載について以下を参照しました。
PostgreSQL 9.6.4文書
1.1. インストール
https://www.postgresql.jp/document/9.6/html/tutorial-install.html
「自身でPostgreSQLをインストールする場合は、インストール手順を16章 ソースコードからインストールで確認してください。 そしてインストールが完了してから、本書に戻ってきてください。」

そのため、ソースコードのダウンロード先をとしてリンクをたどり以下を参照したところ
https://www.postgresql.org/download/
ソースコードとは別にインストール用バイナリも公開されているようでした。

**Comment by echi-no** [comment]
Following the installation manual, I installed PostgreSQL 9.6 for the first time.
Please tell me the documentation on how to install from binary.

About the installation description of the manual I referred to the following.
PostgreSQL 9.6.5 Documentation
1.1. Installation
https://www.postgresql.jp/document/9.6/html/tutorial-install.html
"If you are installing PostgreSQL yourself, then refer to this guide when the installation is complete. Be sure to follow closely the section about setting up the appropriate environment variables."

For that reason I have looked up below for the source code download destination.
https://www.postgresql.org/download/

Apart from the source code, binaries for installation were also released and linked to binaries.

We propose to be a link to the source, or to mention the installation procedure of the binary to "1.1. Installation".

**Comment by osanai-hisashi** [comment]
確認しました。グーグル先生で確認し問題がなければ、投稿されると良いかと思います。

Hi folks,
I am a beginner of PostgreSQL. I installed PostgreSQL 9.6 with the following installation manual.
Could you please teach me on how to install it from binaries.
PostgreSQL 9.6.5 Documentation: https://www.postgresql.jp/document/9.6/html/tutorial-install.html

I referred to the following description of the manual.
1.1 Installation
"If you are installing PostgreSQL yourself, then refer to this guide when the installation is complete. Be sure to follow closely the section about setting up the appropriate environment variables."

For that reason I have looked up below for the source code download destination.
https://www.postgresql.org/download/

The installation binaries are also released in the link in addition to the source code.
I would like to propose to be a link to the source, or to mention the installation procedure of the binary to "1.1. Installation".

Best regards,
Noriyuki

**Comment by echi-no** [comment]
御連絡遅くなりましたが、フィードバックは実施済みです。
Issueをcloseいただければと存じます。

**Comment by y-goto** [comment]
お疲れさまでした。
返事がかえってくるのを期待しましょう。

proxy設定等については分かりにくくて申し訳ありませんでした。
今後の案内など改善していきたいと思います。
