### ISSUE TITLE
OSS Gate Workshop: Fujitsu: 2017-10-02: ihara-noriyuki: FFmpeg: Work log

### ISSUE THREAD

**Issue by ihara-noriyuki** [oss-gate/workshop#613]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by osanai-hisashi** [comment]
大丈夫です！

**Comment by echi-no** [comment]
よろしくお願いいたします。

**Comment by ihara-noriyuki** [comment]
よろしくお願いします。

**Comment by ihara-noriyuki** [comment]
FFmpegを初心者がインストールする手順が簡単にわかると良いと思う。

公式ホームページをアクセスして、インストール手順書を探したが見つからない。
ダウンロードボタンはTopページにあってわかりやすい。
ダウンロードしたものをどのようにインストールすると良いか公式ホームページから見つけられねかった。
ダウンロードしたものをコンパイルやインストールする手順が、同じページに記載またはリンクされていると
次に行うことがわかって良いと思う。
また、メニューにクイックインストールガイドのリンクがあると見つけやすい

**Comment by ihara-noriyuki** [comment]
FFmpegのバイナリーからのインストール手順を”http://ffmpeg.org/”で見つけやすく出来ないでしょうか？

私はCentOS 7.2 x64にインストールを行うつもりで、初めて”http://ffmpeg.org/”にアクセスしました。
私はFFmpegをインストールするために、コンパイル済みのバイナリでインストールを行うつもりでした。
但し、コンパイル済みのバイナリおよびそのインストール手順を見つけることができませんでした。

ダウンロードしたものの、コンパイルやインストールする手順がダウンロードのページに記載またはリンクされていると、次に何をすべきかわかりやすくなると思う。

**Comment by osanai-hisashi** [comment]
FFmpegの初心者です。
FFmpegの環境を構築するために、バイナリからのインストールに関する
ドキュメントを下記サイトで探しましたが、見つけられませんでした。
どこに記載されているか教えていただけないでしょうか？

といった内容を記載した上で、
ダウンロードしたものの、コンパイルやインストールする手順がダウンロードのページに記載またはリンクされていると、次に何をすべきかわかりやすくなると思う。
を具体的なURL等を含めて記載すると良いと思います。

**Comment by ihara-noriyuki** [comment]
FFmpegの初心者です。
FFmpegの環境を構築するために、バイナリからのインストールに関する
 ドキュメントを下記サイトで探しましたが、見つけられませんでした。
どこに記載されているか教えていただけないでしょうか？
http://ffmpeg.org/documentation.html

また、下記サイトの”Get the packages”のLinuxの部分にインストールに関するドキュメントの
リンクもあると良いと思います。
http://ffmpeg.org/download.html

**Comment by ihara-noriyuki** [comment]
FFmpegの初心者です。
FFmpegの環境を構築するために、パッケージからのインストールに関する ドキュメントを下記サイトで探しましたが、見つけられませんでした。
インストールドキュメントがどこにあるか教えていただけないでしょうか？
http://ffmpeg.org/documentation.html

また、下記サイトの”Get the packages”のLinuxの部分にパッケージのインストールドキュメントの リンクもあると、私のような初心者でも導入しやすくなると思います。
http://ffmpeg.org/download.html
 


I am a beginner of FFmpeg.
In order to build the environment of FFmpeg, I searched the following site for installation documentation from package, but I could not find it.
Could you tell me where the installation document is?
http://ffmpeg.org/ documentation.html

Also, if there is a link to the package installation document in the Linux part of "Get the packages" below, I think that even beginners like me will be able to introduce it.
http://ffmpeg.org/download.html

**Comment by osanai-hisashi** [comment]
Hi folks,

<ここに本文>

Best regards,
xxxx

**Comment by osanai-hisashi** [comment]
補足コメントです。

Could you tell me where the installation document is?
http://ffmpeg.org/ documentation.html
上記のURLに空白が入っているので、削除されると良いかと思います。

**Comment by osanai-hisashi** [comment]
アンケートの回答方法は、下記urlにあります。
https://github.com/oss-gate/workshop/tree/master/tutorial/retrospectives

% git add beginner-xxx.yaml
% git checkout -b ank
% git commit -m"アンケート提出"
% git push origin ank

その後、githubにブラウザで自分のforkしたリポジトリにアクセスすると
pull requestができるようになっているかと思います。
