### ISSUE TITLE
OSS Gateワークショップ 2016-06-11: kawakubox : dotenv : 作業ログ

### ISSUE THREAD

**Issue by kawakubox** [oss-gate/workshop#62]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by kawakubox** [comment]
* [dotenv](https://github.com/bkeepers/dotenv) の README 読む
* 英文読めるか

**Comment by kawakubox** [comment]
* README の Installation みてみた
* Rails 用の Install とか、 PoRuby 用とかあったんで、今回は Rails 絡めないで進めるんで、 PoRuby 用をじっくり読む

備考:  余談だけど、 branch の build faild してる。

<img width="235" alt="2016-06-11 11 15 01" src="https://cloud.githubusercontent.com/assets/1255116/15982550/cfb9a288-2fc5-11e6-99b5-161583d9e5e2.png">

**Comment by kawakubox** [comment]
* 実際に Install してみる
* `$ bundle init` してから Gemfile に追記して実行する

**Comment by kawakubox** [comment]
* ↑README上は、bundler 使ってなかったので、訂正
* gem install する

備考

```
[kawakubox] ~/Workspace/ossws % gem install dotenv
Fetching: dotenv-2.1.1.gem (100%)
Successfully installed dotenv-2.1.1
1 gem installed
```

**Comment by kawakubox** [comment]
* 最小のサンプルを書いて動かしてみる
* `sample.rb` を実行、何事もなく終了。これだと設定読み込めているのかどうかはわからない、、、

備考

```ruby
require 'dotenv'

Dotenv.load
```

```shell
$ ruby sample.rb
```

**Comment by kawakubox** [comment]
* Instlllation に rake の記載のある
* どうやら、 `task :mytask => :dotenv do` で読み込めるようになるらしい

**Comment by kawakubox** [comment]
* Usage のセクションを読む
* your `.env` がどうのとあるんで、オレオレ `.env` 作っとく

**Comment by kawakubox** [comment]
* `.env` ファイルにマルチラインもできるようなので、追加しとく
* とりま追加してみた

備考

```.env
GITHUB_PR_TEMPLATE="## Description\n## Issue"
```

**Comment by kawakubox** [comment]
* `.env` にコマンドの埋め込みの説明
* まじか、試す

**Comment by kawakubox** [comment]
* 現在時刻の設定を追加
* 環境変数名は `TODAY` にしようと思ったけど、 `NOW` 変更

備考

```.env
NOW=$(date)
```

**Comment by kawakubox** [comment]
* `ENV['xxxxx']` で読み込めるので、console に出力してみる
* puts すればいいかな

**Comment by kawakubox** [comment]
* sample.rb 実行
* おっ、出た♪

備考

```shell
[kawakubox] ~/Workspace/ossws % ruby sample.rb
kawakubox
## Description
## Issue
2016年 6月11日 土曜日 11時44分15秒 JST
```

**Comment by kawakubox** [comment]
* `.env` のコメントアウトは `#`
* これも追記して試す

備考

```.env
GITHUB_ACCOUNT=kawakubox
GITHUB_PR_TEMPLATE="## Description\n## Issue"
# COMMENT_OUT_ENV=This is comment out
NOW=$(date)
```

**Comment by kawakubox** [comment]
* コメントアウトされているはずの設定を読みだしてみる
* エラーでそうな気もするが、、、、

**Comment by kawakubox** [comment]
* ↑の実行結果
* エラーは出なかったが、空行が増えた

備考

```
[kawakubox] ~/Workspace/ossws % ruby sample.rb
kawakubox
## Description
## Issue
2016年 6月11日 土曜日 11時50分39秒 JST

```

**Comment by kawakubox** [comment]
* ちょっと寄り道、最後に出力するとわかりづらいので、出力位置変えてみた
* 期待通りの結果！

備考

```sample.rb
puts ENV['GITHUB_ACCOUNT']
puts ENV['GITHUB_PR_TEMPLATE']
puts ENV['COMMENT_OUT_ENV']   # <-- ここに挿しこむ
puts ENV['NOW']
```

```
$ ruby sample.rb

[kawakubox] ~/Workspace/ossws % ruby sample.rb
kawakubox
## Description
## Issue

2016年 6月11日 土曜日 11時54分25秒 JST
```

**Comment by kawakubox** [comment]
* ここまでで、気になっているポイント、`master` ブランチの直近の build が fail している点

**Comment by kawakubox** [comment]
- `master` ブランチの build が fail している。
- [TravisCI の結果](https://travis-ci.org/bkeepers/dotenv/builds/128441596)を見ると `Ruby: rbx-2`, `Ruby: jruby-head` が fail になっている。
- `Ruby: jruby-head` は Allowed Failures となっているので、見過ごせるとしても、 `Ruby: rbx-2` はどうにかしたいと思う。

**Comment by kawakubox** [comment]
* `Ruby: rbx-2` でコケているけど、そもそも `rbx-2` って何かを調べる

**Comment by kawakubox** [comment]
* build fail 問題を追いかけてみると、すでに [Pull Request](https://github.com/bkeepers/dotenv/pull/255) が投げられていることが判明
* これ以上することないので、PRに 👍  つけといた

**Comment by kawakubox** [comment]
* PoRuby での導入手順に bundler 利用しているケースを追加してみるとかはいけるのかな

**Comment by kawakubox** [comment]
* for Developer

> 昨今、Plain old Ruby な環境でも `bundler` を利用した開発が主流だと思われるので、Installation に bundler の利用ケースを README に提示してはいかがだろうか？

**Comment by kawakubox** [comment]
* 存在しない環境変数を参照した際の戻り値 (nil) は、どこぞのドキュメントに書いてるのか？
* 期待するのは、ENVがruby自体の機能なので、そちらにあればOK

**Comment by kawakubox** [comment]
- dotenv をキチンと導入できているかどうかが不安
- console に出力する最小限のコードがあると installation セクションが終わっていることを確認ができると思う
- 例えば、 rbenv 使って 2.3.0 いれたら、 `$ ruby -v` を実行してみるとか

**Comment by kawakubox** [comment]
### 開発者向け Issue テキスト案

> Installation のセクションを読んで、キチンと導入できているかどうかが不安だった。
> セクションの最後に install 確認できるようなミニマムなサンプルコードがあると、心が軽くなると思う。

**Comment by kawakubox** [comment]
> I felt uneasy when I read the README in Installation and Usage section.
> I looks good and there is a minimum code to make sure that you are able to properly install.

**Comment by kawakubox** [comment]
#### Summary

I read README in Installation and Usage section, whether it can be properly introduced was anxiety.

#### Detail

I did you make sure to run the code in the Usage as sample.rb, but since nothing is displayed on the console, I did not know whether it is normal Install.

```
# sample.rb
require 'dotenv'
Dotenv.load

$ ruby sample.rb
```

If there is a sample code that can last to check in the console of the section, better become such a feel.

For example, what about feeling like the following?

```
# .env
FOO=foo

# sample.rb
require 'dotenv'
Dotenv.load
p ENV['FOO']
p ENV['BAR']

$ ruby sample.rb
"foo"
nil
```

**Comment by kou** [comment]
お疲れさまでした！
