### ISSUE TITLE
OSS Gate Workshop: PHPConf2017: 2017-10-08: suzukieita: Laravel: Work log

### ISSUE THREAD

**Issue by suzukieita** [oss-gate/workshop#625]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ryo-utsunomiya** [comment]
サポーターです。よろしくお願いします！

**Comment by Taka-Hirayama** [comment]
よろしくお願いします。

**Comment by sashiyama** [comment]
宜しくお願いいたします。

**Comment by satoryu** [comment]
よろしくお願いしますー

**Comment by sezemiadmin** [comment]
レポーターです！よろしくお願いします！

**Comment by ykagata** [comment]
よろしくお願いします。

**Comment by suzukieita** [comment]
「Laravel」で検索して、公式サイトを探す。

**Comment by suzukieita** [comment]
https://laravel.com/

**Comment by suzukieita** [comment]
トップページにはLaravelの説明が載ってるだけみたいなので、headerのDocumentaionを見てみる。
https://laravel.com/docs/5.5

**Comment by suzukieita** [comment]
そうするとinstallationのページが出てきた。
Laravel Homestead　が highly recommended となっているので、見てみる。
https://laravel.com/docs/5.5/homestead

**Comment by suzukieita** [comment]
どうやらVagrant Boxが提供されているようだ。
だが、Windowsの場合には赤い背景でいろいろ注意書きが書かれていて面倒くさそう。
しかも、Ubuntuで提供されている。。。
自分のVagrant環境でやったほうが楽そうだが、折角なのでこのまま試してみよう

**Comment by suzukieita** [comment]
First stepでvirtual box やvagrantをインストールしろと言われた。
ローカルではすでに入っているはずなので確認する。

**Comment by suzukieita** [comment]
バージョン確認しようと思ったけど、確認の仕方がよくわからなかったので、
vagrant box add laravel/homestead
を試してしまう。

**Comment by suzukieita** [comment]
ダウンロードできそう。
ただ、時間が10分ほどかかってします。

**Comment by suzukieita** [comment]
Documentを読んでいたら、vagrant up する前にいろいろ設定が必要みたい。
ローカルの任意のディレクトリに laravel_practice というディレクトリを作って、そこで作業をする。

**Comment by suzukieita** [comment]
そこで git clone https://github.com/laravel/homestead.git Homestead
でrepositoryをクローンしてくる。

**Comment by suzukieita** [comment]
バージョンを確認する。
cd Homestead

**Comment by suzukieita** [comment]
GitHub Release Page　https://github.com/laravel/homestead/releasesで調べて、最新のバージョンにする。
git checkout v6.2.2

**Comment by suzukieita** [comment]
インストール手順にしたがい、bashから init.bat を実行しようとしたができなかったので、
コマンドプロンプトから init.bat を実行、ymlファイルが生成された。

**Comment by suzukieita** [comment]
yamlはデフォルトでOKそうなのでそのままいく。
hostsを編集する。

**Comment by suzukieita** [comment]
管理者権限でメモ帳を開き、
C:\Windows\System32\drivers\etc\hosts
の中に
192.168.10.10  homestead.app
を追記した。

**Comment by suzukieita** [comment]
満を持しての vagrant up
どうかいってくれ。。。

**Comment by suzukieita** [comment]
どうやらOKそうだったので、 vagrant ssh で入る。

**Comment by suzukieita** [comment]
Launching The Vagrant Box
Once you have edited the Homestead.yaml to your liking, run the vagrant up command from your Homestead directory. Vagrant will boot the virtual machine and automatically configure your shared folders and Nginx sites.

To destroy the machine, you may use the vagrant destroy --force command.

このセクションが終わった後に、別の説明が始まってしまい、何をすればよいかわからなくなる。
installationに戻る？

**Comment by suzukieita** [comment]
folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/public

で「Code」というディレクトリを作ったが、元のinstallationに戻ると　laravel new blog　のコマンドを要求される。
そうすると /home/vagrant/blog/publicが作られ、
http://homestead.app/
で見ようとしても見れなくなる。
インストール手順書が分かれているせいで、よくわからなくなっている。

**Comment by suzukieita** [comment]
Laravelを初めてインストールして動かそうとした人です。

Homesteadを使うといいと書いてあったので、手順に従ってインストールしました。
ただ
1. Launching The Vagrant Box の後に補足的な説明が続いていて、vagrant up をした後に何をすればよいか分からなくなる。
2. Homestead.yaml　の設定で /home/vagrant/Code/public で設定したがこの{Code}の部分にプロジェクト名が入らなけらばいけないのに、公式手順書では laravel new blog コマンドを実行すると /home/vagrant/blog/public になってしまい、ディレクトリがずれてしまってhttp://homestead.app/　からLaravelの画面が見えない。

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
