### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: hayashier: libinjection: Work log

### ISSUE THREAD

**Issue by hayashier** [oss-gate/workshop#627]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by taaatk** [comment]
こみやまです！

**Comment by piroor** [comment]
サポーターのPiroです！

**Comment by junichirojp** [comment]
こんにちは。

**Comment by kenhys** [comment]
サポーターの kenhys です。

**Comment by sezemiadmin** [comment]
レポーターです！よろしくお願いします！

**Comment by msfukui** [comment]
よろしくお願いします！

**Comment by hayashier** [comment]
GitHubアカウント

**Comment by hayashier** [comment]
トップのREADMEに従ってgit clone
git clone https://github.com/client9/libinjection.git

**Comment by hayashier** [comment]
cd libinjection 
CHANGELOG			install-sh
CHANGELOG.md			lua
COPYING				make-ci.sh
Makefile			misc
README.md			php
RELEASE-HOWTO.md		python
configure-clang-asan.sh		run-clang-asan.sh
configure-clang.sh		run-gcov-samples.sh
configure-gcc-hardened.sh	run-gcov-unittests.sh
configure-gcov.sh		src
configure-gprof.sh		tags.sh
data				test-gprof.sh
go				tests
 (git)-[master]-:~/workspace/tmp/libinjection/ gcc -Wall -Wextra examples.c libinjection_sqli.c
clang: error: no such file or directory: 'examples.c'
clang: error: no such file or directory: 'libinjection_sqli.c'
clang: error: no input files

**Comment by hayashier** [comment]
READMEのコンパイルに従って実行したが、1行目でいきなりエラー
src/以下に実際のソースが入ってると思い、src以下に移動して実行するもエラー。
examples.cを実際にディレクトリにあったexample1.cに変更すると、コンパイルが通った。

**Comment by hayashier** [comment]
(git)-[master]-:~/workspace/tmp/libinjection/src/ gcc -Wall -Wextra examples1.c libinjection_sqli.c
clang: error: no such file or directory: 'examples1.c'
 (git)-[master]-:~/workspace/tmp/libinjection/src/ gcc -Wall -Wextra example1.c libinjection_sqli.c 

a.outが生成

**Comment by hayashier** [comment]
ドキュメントにあったSQL Injectionのコマンドは実行できた

 (git)-[master]-:~/workspace/tmp/libinjection/src/ ./a.out "-1' and 1=1 union/* foo */select load_file('/etc/passwd')--"
sqli with fingerprint of 's&1UE'

**Comment by hayashier** [comment]
libinjectionをより使いやすく精度を上げたいと思っています。

**Comment by hayashier** [comment]
libinjectionをGoogleで検索して、辿り着いたGithubのページにたどり着きました。トップのREADMEに従ってgit clone git clone https://github.com/client9/libinjection.gitをして、以下のコマンドを実行

```
$ gcc -Wall -Wextra examples.c libinjection_sqli.c
clang: error: no such file or directory: 'examples.c'
```

すると、エラーが出て、src/以下を見てみると、ソースが置いてあったので、こちらに移動してコンパイルすることを前提に実行するものだと推測して実行しても、再度エラー。

src/以下を見てみると、examples.cと似たような名前のexample1.cがあったので、ファイル名を変更して、コンパイルを実行すると通り、a.outというファイルが生成されていることを確認。

**Comment by hayashier** [comment]
サポーターの方から指摘から頂き、examples.cはコマンドのすぐ上にかかれているサンプルコードのことではという話があり、実際にexamples.cとして保存して実行するとコンパイルが通った。
コマンドを実行しても同じ実行結果となった。

**Comment by hayashier** [comment]
[思ったこと]
- インストールコマンドがsrc/以下に暗黙の前提で書かれていたので明示的に移動して実行するということが書かれていたら嬉しかった
- コマンド中にあったexamples.cがすぐ上にあったサンプルコードの事だと思われたが、はじめ見た時にわからなかったので、書かれていたら嬉しかった

**Comment by hayashier** [comment]
最初に以下のコマンドでcloneしてくる。

```
git clone git clone https://github.com/client9/libinjection.git 
```
READMEのコンパイル手順に従って、以下のコマンドをディレクトリ直下ですぐに実行

```
$ gcc -Wall -Wextra examples.c libinjection_sqli.c
```

すると、コンパイルが成功することを期待したが、以下のエラーが出力。

```
clang: error: no such file or directory: 'examples.c'
clang: error: no such file or directory: 'libinjection_sqli.c'
clang: error: no input files
```


どうやったら出来るかと思い、libinjection_sqli.cを探すと、src/ディレクトリ以下存在。
src/ディレクトリ以下に移動して、再度実行すると、エラー。

```
clang: error: no such file or directory: 'examples.c'
```

サポーターの方から指摘を頂き、examples.cはコンパイル実行コマンドすぐ上にかかれているサンプルコードのことではと言われてsrc/ディレクトリ以下にファイルを作成してみた。再度コンパイルを実行すると通って、a.outが生成。

実行結果もREADMEの結果通りだった。

```
$  ./a.out "-1' and 1=1 union/* foo */select load_file('/etc/passwd')--"
sqli detected with fingerprint of 's&1UE'
```

**Comment by hayashier** [comment]
# Steps to reproduce
最初に以下のコマンドでcloneしてくる。

```
git clone git clone https://github.com/client9/libinjection.git 
```

READMEのコンパイル手順に従って、以下のコマンドをディレクトリ直下ですぐに実行

```
$ gcc -Wall -Wextra examples.c libinjection_sqli.c
```

すると、コンパイルが成功することを期待したが、以下のエラーが出力。

```
clang: error: no such file or directory: 'examples.c'
clang: error: no such file or directory: 'libinjection_sqli.c'
clang: error: no input files
```

どうやったら出来るかと思い、libinjection_sqli.cを探すと、src/ディレクトリ以下存在。
src/ディレクトリ以下に移動して、再度実行すると、エラー。

```
clang: error: no such file or directory: 'examples.c'
```

examples.cはコンパイル実行コマンドすぐ上にかかれているサンプルコードのことではということで、src/ディレクトリ以下にファイルを作成してみた。再度コンパイルを実行すると通って、a.outが生成。

実行結果もREADMEの結果通りだった。

```
$  ./a.out "-1' and 1=1 union/* foo */select load_file('/etc/passwd')--"
sqli detected with fingerprint of 's&1UE'
```

# Expected Result
つまらずにコンパイルを実行して、コマンドの実行結果もREADMEのドキュメント通りの結果になる。

# Actual Result
コンパイルで2回つまづいた。

**Comment by hayashier** [comment]
# Idea
Simple exampleの説明をもう少し親切の方が初心者にとって良いと思いました。

具体的には、コンパイルのコマンドの実行例に書かれているファイル名が、サンプルコードのことだという旨の記述と、コマンドの実行場所がsrc/以下だということが書かれているとつまずかずに実行出来て良いと思った。もしくは、ソースコードが置かれているsrc/以下とは別にサンプルコードを置いて実行できるような手順の用意とドキュメントに記載があると嬉しいと思いました。

**Comment by hayashier** [comment]
# Idea
The description of  "Simple example" should be more informative for beginner.

More specifically, README should represent "examples.c " file written in examples of compile procedure as above sample code.

具体的には、コンパイルのコマンドの実行例に書かれているファイル名が、サンプルコードのことだという旨の記述と、コマンドの実行場所がsrc/以下だということが書かれているとつまずかずに実行出来て良いと思った。もしくは、ソースコードが置かれているsrc/以下とは別にサンプルコードを置いて実行できるような手順の用意とドキュメントに記載があると嬉しいと思いました。


# Steps to reproduce
最初に以下のコマンドでcloneしてくる。

```
$ git clone git clone https://github.com/client9/libinjection.git 
```

READMEのコンパイル手順に従って、以下のコマンドをディレクトリ直下ですぐに実行

```
$ gcc -Wall -Wextra examples.c libinjection_sqli.c
```

すると、コンパイルが成功することを期待したが、以下のエラーが出力。

```
clang: error: no such file or directory: 'examples.c'
clang: error: no such file or directory: 'libinjection_sqli.c'
clang: error: no input files
```

どうやったら出来るかと思い、libinjection_sqli.cを探すと、src/ディレクトリ以下存在。
src/ディレクトリ以下に移動して、再度実行すると、エラー。

```
clang: error: no such file or directory: 'examples.c'
```

examples.cはコンパイル実行コマンドすぐ上にかかれているサンプルコードのことではということで、src/ディレクトリ以下にファイルを作成してみた。再度コンパイルを実行すると通って、a.outが生成。

実行結果もREADMEの結果通りだった。

```
$  ./a.out "-1' and 1=1 union/* foo */select load_file('/etc/passwd')--"
sqli detected with fingerprint of 's&1UE'
```

# Expected Result
つまらずにコンパイルを実行して、コマンドの実行結果もREADMEのドキュメント通りの結果になる。

# Actual Result
コンパイルで2回つまづいた。

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
