### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: msfukui: silex: Work log

### ISSUE THREAD

**Issue by msfukui** [oss-gate/workshop#628]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by junichirojp** [comment]
silexってなんですか？

**Comment by kenhys** [comment]
サポーターの kenhys です。

**Comment by taaatk** [comment]
こみやまです！

**Comment by piroor** [comment]
サポーターのPiroです！

**Comment by hayashier** [comment]
林です！

**Comment by msfukui** [comment]
@junichirojp php のマイクロ・Web フレームワークです。
https://github.com/silexphp/Silex

**Comment by msfukui** [comment]
まずは最新のドキュメントを眺めるところから始めます。

**Comment by msfukui** [comment]
ここが最新っぽいです。
https://silex.symfony.com/doc/2.0/

**Comment by msfukui** [comment]
Introduction があるので、そこからまずは手元で試してみることにします。

**Comment by msfukui** [comment]
PHP の環境が手元にないことを思い出したので、そこを作るところから..。

**Comment by msfukui** [comment]
vagrant の環境が壊れていた..。repair しよう..。だいぶつらい。

**Comment by msfukui** [comment]
PC 再起動したら、とりあえず動いた! よかった..。そして恥ずかしい..。

**Comment by msfukui** [comment]
PHP の開発環境って、どうやって構築するのが正解なのかな..。

取り合えず、ContOS7 上でのセットアップ方法から調べてみる。

**Comment by msfukui** [comment]
もはや CentOS でのインストールは、公式マニュアルには書かれていない模様..。

http://php.net/manual/ja/install.php

**Comment by msfukui** [comment]
ここCentOS系を使っている身としては、大変あった方がよい気持ち..。

**Comment by msfukui** [comment]
yum のレポジトリは epel 上だとある模様。

**Comment by msfukui** [comment]
ここをまずはターゲットにしてみるとよいかもしれない。

**Comment by msfukui** [comment]
他のディストリビューションのインストール方法を眺めてみよう。

**Comment by msfukui** [comment]
debian 系の場合

http://php.net/manual/ja/install.unix.debian.php

これの yum 版があればとりあえずことは足りそうに思える。

**Comment by msfukui** [comment]
そもそも公式でサポートされているものかどうか、ということで切り分けてマニュアルに書くか書かないかが明確に決まっているようなので、yum でとってくる php のバージョンをそもそも最新にしてあげる活動が必要なのかもしれない。

debian 系のマニュアルの先頭に以下の記述がある。

```
警告
サードパーティが作った非公式のビルドについてはここではサポートしていません。 何かバグを見つけた場合は、 » ダウンロードページ から取得した最新のビルドでそれが再現するかを確認し、 再現しない場合は Debian チームにバグ報告をお願いします。
```

**Comment by msfukui** [comment]
CentOS 系でそもそも何が入るのか、確認してみる。

```
$ yum search php
```

**Comment by msfukui** [comment]
こうなった。5.4 で止まっている。

```
========================================================================================================================
 Package                     アーキテクチャー       バージョン                            リポジトリー             容量
========================================================================================================================
インストール中:
 php                         x86_64                 5.4.16-42.el7                         base                    1.4 M
依存性関連でのインストールをします:
 apr                         x86_64                 1.4.8-3.el7                           base                    103 k
 apr-util                    x86_64                 1.5.2-6.el7                           base                     92 k
 httpd                       x86_64                 2.4.6-67.el7.centos.2                 updates                 2.7 M
 httpd-tools                 x86_64                 2.4.6-67.el7.centos.2                 updates                  88 k
 libzip                      x86_64                 0.10.1-8.el7                          base                     48 k
 mailcap                     noarch                 2.1.41-2.el7                          base                     31 k
 php-cli                     x86_64                 5.4.16-42.el7                         base                    2.7 M
 php-common                  x86_64                 5.4.16-42.el7                         base                    564 k

トランザクションの要約
========================================================================================================================
インストール  1 パッケージ (+8 個の依存関係のパッケージ)
```

**Comment by msfukui** [comment]
php7 はなかった。

```
[ ~]$ sudo yum install php7
読み込んだプラグイン:fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.fairway.ne.jp
 * extras: mirror.fairway.ne.jp
 * updates: mirror.fairway.ne.jp
パッケージ php7 は利用できません。
エラー: 何もしません
```

**Comment by msfukui** [comment]
epel centos7 php で google さんに聞くと、他の人は epel を使ってインストールしているっぽい。

https://www.google.co.id/search?q=epel+centos7+php&oq=epel+centos7+php&aqs=chrome..69i57j0l2.8275j0j7&sourceid=chrome&ie=UTF-8

このあたり同じような記事がヒットする。

https://qiita.com/ozawan/items/caf6e7ddec7c6b31f01e

https://qiita.com/inakadegaebal/items/b57cf10339978d638305

**Comment by msfukui** [comment]
公式の人がどう考えているのかをもうちょっと知りたい。

公式マニュアルの issue を眺めてみたい。調べてみる。

**Comment by msfukui** [comment]
というかそもそも silex に php の環境を整える手順がないのはちょっとつらいのではないか。

introduction の中に、環境がない人向けの簡易な準備手順があると、導入がしやすそうに思える。

リンクでもいいが、その場合は、公式の手順に rhel 系の手順がない点をフォローしたい。

**Comment by msfukui** [comment]
もう一度、intro をよく眺めてみる。

**Comment by msfukui** [comment]
PHP の公式マニュアルに、RHEL系の場合のインストール手順が書かれていないので、これをフィードバックしたい。

**Comment by msfukui** [comment]
フィードバックの情報をまずは出しきる様にする。

* PHP の Web アプリケーションを作成する場合に RHEL 系の Linux ディストリビューションを使っているが、PHP の公式マニュアルのインストール手順 http://php.net/manual/ja/install.unix.php には環境構築手順の記載がない。

* そのOSを使っている人の環境構築のハードルを下げたい。

* Debian系や他のOSの構築手順は説明があるので、RHEL 系のディストリビューション用にも章を一つ新しく立てて、インストールの手順を追加したい。

* CentOS7 だと、標準のyumコマンドでインストールされるPHPが5.4なので、そちらは使わないことを推奨しつつ、まずは 7.1 のコードを自身でコンパイルする手順にすることとしたい。

**Comment by msfukui** [comment]
isuue を出すためにまとめる。
--
新規にPHPの開発環境を構築しようとしたところ、CentOS7 上で利用したかったのですが、公式のPHPの「インストールと設定」には、CentOS7 についての環境構築手順の記載がなく、利用までの敷居が高いように思いました。
それなりに利用者の多いディストリビューションで、他に困っている利用者も多いと思いますので、できれば公式マニュアルに CentOS7 の場合の環境構築の手順を別に章を立てて追加できればと考えています。

**Comment by msfukui** [comment]
PHP の公式マニュアルへのフィードバック方法を調べてみる。

**Comment by msfukui** [comment]
http://php.net/manual/ja/about.howtohelp.php

この辺りから眺めてみる。

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
