### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: taaatk: PHPドキュメント: Work log

### ISSUE THREAD

**Issue by taaatk** [oss-gate/workshop#629]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hayashier** [comment]
Hi

**Comment by piroor** [comment]
サポーターのPiroです！

**Comment by hayashier** [comment]
林です。お願いします！

**Comment by kenhys** [comment]
サポーターの kenhys です。

**Comment by msfukui** [comment]
PHP ドキュメントって、充実してますよね。
よろしくお願いします。

**Comment by junichirojp** [comment]
よろしくです

**Comment by taaatk** [comment]
eccubeで検索

**Comment by taaatk** [comment]
ダウンロードしようとした！

**Comment by taaatk** [comment]
https://www.ec-cube.net/download/

**Comment by taaatk** [comment]
ログインページが開いた！

**Comment by taaatk** [comment]
https://www.ec-cube.net/download/login.php?download_index=0&transactionid=a6a769fda8ca3c1321db2d42d528667c7c85cf02

**Comment by taaatk** [comment]
登録完了！

**Comment by taaatk** [comment]
マイページ開いた
https://www.ec-cube.net/mypage/
インストールするには。。。

**Comment by taaatk** [comment]
ダウンロードが見つからず
トップページに戻って再びダウンロードボタンをおす
手間？

**Comment by taaatk** [comment]
FTPでアップロード

**Comment by taaatk** [comment]
会社で構築したことがある

**Comment by taaatk** [comment]
指示受けた、今度は自分で

**Comment by taaatk** [comment]
方針変えてみた！
eccubeで検索してgithub開いた！
https://github.com/EC-CUBE/ec-cube

**Comment by taaatk** [comment]
http://taatk.sakura.ne.jp/test/html/でアクセス
そしたら、セットアップページが開く

**Comment by taaatk** [comment]
データベースでSQLite選んだら勝手にDB作ってくれた。。。

**Comment by taaatk** [comment]
http://taatk.sakura.ne.jp/test/html/admin/
構築完了

**Comment by taaatk** [comment]
html/install.php は、インストール完了後にファイルを削除してください
このダイアログでてきたけど。。。
勝手に消してくれないのかなこれ。。。

**Comment by taaatk** [comment]
とりあえず、テストで商品登録してみる

**Comment by taaatk** [comment]
画像のアイコンクリックしたけど反応せず。
「ファイルのアップロード」を押さないと開けなかった。

**Comment by taaatk** [comment]
登録できた。
登録が完了しました。ダイアログのあとに、確認用に商品個別ページへのリンクがあるといいな。

**Comment by taaatk** [comment]
てか、管理画面から別タブでページに飛べる機能が欲しいなと思う。

**Comment by taaatk** [comment]
> 登録できた。
> 登録が完了しました。ダイアログのあとに、確認用に商品個別ページへのリンクがあるといいな。

対象者…初めてECサイトを構築する人
商品登録して、詳細へのページで確認しようとしたとき、自分でURLにアクセスする必要がある。
商品ページの確認方法がわからない。
導線がない。
もっと簡単に登録したものを確認できるといいな。

**Comment by taaatk** [comment]
# 概要
* 初めてEC-CUBEを利用する人が、商品を初めて登録する際に商品ページの確認方法が分からないため、別途URLを入力して確認していく必要がある。
* 保存した直後に商品ページへの導線があれば、登録内容を簡単に確認できてよいのではと思った。

# 再現手順
* インストール手順に従ってEC-CUBEをインストールする
* 管理画面を開く (/html/admin/)
* 商品管理から商品登録を押し、登録画面を開く
* 登録情報を入力し「商品を登録」ボタンを押し、製品を登録する

# 実際の結果
* 「登録が完了しました。」ダイアログが出現する

# 期待される結果
* 「登録が完了しました。」ダイアログの後ろに、「登録内容を確認する」という文字列リンクがある
* リンクをクリックすると、別タブで商品詳細のページに移動する

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
