### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: ykagata: CakePHP: Work log

### ISSUE THREAD

**Issue by ykagata** [oss-gate/workshop#630]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sashiyama** [comment]
宜しくお願いいたします。

**Comment by satoryu** [comment]
よろしくお願いしますー

**Comment by ryo-utsunomiya** [comment]
サポーターです。よろしくお願いします！

**Comment by Taka-Hirayama** [comment]
向かいに座っています。よろしくお願いします。

**Comment by suzukieita** [comment]
対角線の人です。よろしくおねがいします！

**Comment by ykagata** [comment]
まずは CakePHP の最新の安定板をインストールします。

**Comment by ykagata** [comment]
インストール手順を調べる。公式サイトを開く。 https://cakephp.org/jp

**Comment by ykagata** [comment]
ドキュメント > Book を開く。 https://book.cakephp.org/3.0/en/index.html

**Comment by ykagata** [comment]
日本語にする。

**Comment by ykagata** [comment]
はじめに > クイックスタートガイドを開く。 https://book.cakephp.org/3.0/ja/quickstart.html

**Comment by ykagata** [comment]
「クイックスタートガイド」はインストール手順でなくアプリケーション作成のチュートリアルだった。
とりあえずこのまま進める。

**Comment by ykagata** [comment]
> 必要なもの:
> 
> データベースサーバー。このチュートリアルでは MySQL サーバーを使います。 データベースを作成するための SQL の知識が必要です。CakePHP は、それを前提としています。 MySQL を使用するとき、 PHP で pdo_mysql が有効になっていることを確認してください。
> 基礎的な PHP の知識。

開発環境に MySQL が入っていない。

**Comment by ykagata** [comment]
開発環境（CentOS7）に MySQL をインストールする手順を Google 検索で探す。

**Comment by ykagata** [comment]
https://centossrv.com/mysql.shtml

> ※CentOS7はMariaDBを参照（CentOS7より標準DBがMySQLからMariaDBへ切り替えられた）

**Comment by ykagata** [comment]
MariaDB サーバをインストールする。

```
$ sudo yum install mariadb-server
```

**Comment by ykagata** [comment]
開発環境に MySQL を導入する手順について参考情報があればよかった。

**Comment by ykagata** [comment]
公式チュートリアルを読んで MySQL の導入に迷わないために：

* 導入手順の参考情報へリンクを張る
* より導入手順の簡単な DBMS （SQLite など）を使う  
…MySQL に依存する機能の説明があるなど、チュートリアルの展開によっては影響が大きいかもしれない。
* チュートリアルのための Vagrant Box を提供する  
…Box 作成の手間がかかる

**Comment by ykagata** [comment]
CakePHP のドキュメントにフィードバックする手順を調べる。

はじめに > 貢献 を開く。 https://book.cakephp.org/3.0/ja/contributing/documentation.html#

**Comment by ykagata** [comment]
> ドキュメントへの貢献の方法はシンプルです。 ファイルは https://github.com/cakephp/docs にホストされています。

**Comment by ykagata** [comment]
GitHub でドキュメントの当該ページを探す。 https://github.com/cakephp/docs/blob/3.0/ja/tutorials-and-examples/bookmarks/intro.rst

**Comment by ykagata** [comment]
日本語記事へ直接フィードバックしてよいのか、英語記事へフィードバックすべきか迷う。

doc の README を読む。 https://github.com/cakephp/docs

**Comment by ykagata** [comment]
読んだがよくわからない。

**Comment by ykagata** [comment]
わからないので、いきなり Pull Request することは控えて、issue を送ることにする。

**Comment by ykagata** [comment]
リンクを張ってもらうべき参考情報を探す。

MySQL の公式サイトを開く。 https://www.mysql.com/jp/

**Comment by ykagata** [comment]
ドキュメント > MySQL Reference Manual を開く。 https://dev.mysql.com/doc/refman/5.7/en/

**Comment by ykagata** [comment]
Installing and Upgrading MySQL を開く。 https://dev.mysql.com/doc/refman/5.7/en/installing.html

**Comment by ykagata** [comment]
どの環境へのインストール手順を参考情報とするか検討する。CakePHP チュートリアルやドキュメントがどのような環境を前提としているか調べる。

**Comment by ykagata** [comment]
CakePHP のドキュメントに具体的な対象環境の指定は見当たらなかった。

ただ、 `bake` コマンドの説明でディレクトリの区切り文字に `/` を使っているところを見ると、暗に Linux を対象としているらしい。

https://book.cakephp.org/3.0/ja/bake/usage.html

> `bin/cake bake` を引数無しで実行すると可能なタスクを表示できます。

**Comment by ykagata** [comment]
Installing and Upgrading MySQL から、Linux 環境で MySQL を立ち上げる簡便な手順を探す。

**Comment by ykagata** [comment]
Installing MySQL on Linux を開く。

https://dev.mysql.com/doc/refman/5.7/en/linux-installation.html

**Comment by ykagata** [comment]
Linux にも環境ごとに複数の手順がある。

手元の CentOS7 について、ここにある手順で環境の立ち上げが実際にできるか確かめる。

Installing MySQL on Linux Using the MySQL Yum Repository を開く。

https://dev.mysql.com/doc/refman/5.7/en/linux-installation-yum-repo.html

**Comment by ykagata** [comment]
> Go to the Download MySQL Yum Repository page (http://dev.mysql.com/downloads/repo/yum/) in the MySQL Developer Zone.

http://dev.mysql.com/downloads/repo/yum/ を開く。

**Comment by ykagata** [comment]
MySQL のバージョンも複数から選択できるもよう。

最新 GA の MySQL5.7 にしたい。

**Comment by ykagata** [comment]
MySQL5.7 をインストールするつもりで A Quick Guide to Using the MySQL Yum Repository を開く。

https://dev.mysql.com/doc/mysql-yum-repo-quick-guide/en/

**Comment by ykagata** [comment]
> a. Go to the download page for MySQL Yum repository at http://dev.mysql.com/downloads/repo/yum/.
> 
> b. Select and download the release package for your platform.

Red Hat Enterprise Linux 7 / Oracle Linux 7 (Architecture Independent), RPM Package を Download するボタンを押すと、以下の URL に移動した。

https://dev.mysql.com/downloads/file/?id=470281

**Comment by ykagata** [comment]
"Login" や "Sign Up" のボタンの下に、 "No thanks, just start my download." というリンクがあった。リンク先が .rpm ファイルになっているので、この URL をコピーする。

**Comment by ykagata** [comment]
https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm

**Comment by ykagata** [comment]
A Quick Guide to Using the MySQL Yum Repository に戻る。

> c. Install the downloaded release package with the following command, replacing platform-and-version-specific-package-name with the name of the downloaded package:
> 
> shell> sudo rpm -Uvh platform-and-version-specific-package-name.rpm

**Comment by ykagata** [comment]
以下のコマンドを実行する。

```
$ sudo rpm -Uvh https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
```

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
