### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: Taka-Hirayama: Laravel: Work log

### ISSUE THREAD

**Issue by Inazo-Nitobe** [oss-gate/workshop#631]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ryo-utsunomiya** [comment]
サポーターです。よろしくお願いします！

**Comment by suzukieita** [comment]
右端の人です。よろしくおねがいします！

**Comment by ykagata** [comment]
よろしくお願いします。

**Comment by sashiyama** [comment]
宜しくお願いいたします。

**Comment by satoryu** [comment]
よろしくお願いしますー

**Comment by Taka-Hirayama** [comment]
ひとまず公式ドキュメントは開いている。
https://laravel.com

日本語訳が無いか探したい。

**Comment by Taka-Hirayama** [comment]
日本語約はLaravel公式では現状作成されていない。
日本人の有志が作成している日本語役のサイトがある。
https://readouble.com/laravel/
最新のLTSであるLaravel5.5の訳が完成していない。

日本語訳のドキュメントが出ないかという質問をフィードバックとして投げてみるのも一つか？

とりあえず英語サイト確認しながら
最新LTSの5.5の開発環境をセットアップしたい。

**Comment by Taka-Hirayama** [comment]
公式サイトに
https://laravel.com/docs/5.5

**Comment by Taka-Hirayama** [comment]
Before launching your Homestead environment, you must install VirtualBox 5.1, VMWare, or Parallels as well as Vagrant. All of these software packages provide easy-to-use visual installers for all popular operating systems.

Homestead を使う前にVirtualBoxとVagrantをインストールしておかないといけないと書いてあるが、
それぞれインストール済み。引き続きドキュメントの手順を確認していく。

**Comment by Taka-Hirayama** [comment]
Installing The Homestead Vagrant Box

Once VirtualBox / VMware and Vagrant have been installed, you should add the laravel/homestead box to your Vagrant installation using the following command in your terminal. It will take a few minutes to download the box, depending on your Internet connection speed:

vagrant box add laravel/homestead

公式の手順に沿ってhomesteadのvagrant boxをダウンロードする。
10分前後かかる見込み。

**Comment by Taka-Hirayama** [comment]
今回はHomesteadで環境の構築をしているが、
Homesteadを使わずに一つ一つ必要なソフトをインストールして構築した際に、
環境がrequirementsを満たしているかどうか確認するチェックスクリプトが欲しい。
というのもフィードバックとして上げられるかもしれない。

**Comment by Taka-Hirayama** [comment]
homesteadのダウンロードは完了。
日本語サイトはバージョン5.4の記述になるが、
5.5と同様の手順になるため、分かりやすい日本語のサイトを参考に
以降はHomestead環境を構築する。

https://readouble.com/laravel/5.4/ja/homestead.html

**Comment by Taka-Hirayama** [comment]
Homesteadのインストール

cd ~
git clone https://github.com/laravel/homestead.git Homestead

ホームディレクトリに初期化のための環境？をチェックアウトする。

**Comment by Taka-Hirayama** [comment]
You should check out a tagged version of Homestead since the master branch may not always be stable. You can find the latest stable version on the GitHub Release Page:

masterが自分が利用しようとしているlaravelのバージョンをサポートしているか分からない。
なので、どんなブランチがあるかをまず確かめる。

hirayamatakaakinoMacBook-Pro:Homestead hirayamatakaaki$ git branch -a
* master
  remotes/origin/2.0
  remotes/origin/HEAD -> origin/master
  remotes/origin/feature/switch-to-localhost
  remotes/origin/master

**Comment by Taka-Hirayama** [comment]
ドキュメントにしたがって、以下のコマンド入力

git checkout v6.2.2

**Comment by Taka-Hirayama** [comment]
Once you have cloned the Homestead repository, run the bash init.sh command from the Homestead directory to create the Homestead.yaml configuration file. The Homestead.yaml file will be placed in the Homestead directory:

// Mac / Linux...
bash init.sh

// Windows...
init.bat

手順に沿ってinit.shを実行する。

**Comment by Taka-Hirayama** [comment]
The provider key in your Homestead.yaml file indicates which Vagrant provider should be used: virtualbox, vmware_fusion, vmware_workstation, or parallels. You may set this to the provider you prefer:

vi Homestead.yml
====
provider: virtualbox

自分はvirtualboxをインストールしているので、デフォルトの設定で問題なし。

**Comment by Taka-Hirayama** [comment]
The folders property of the Homestead.yaml file lists all of the folders you wish to share with your Homestead environment. As files within these folders are changed, they will be kept in sync between your local machine and the Homestead environment. You may configure as many shared folders as necessary:

folders:
    - map: ~/code
      to: /home/vagrant/code

vagrantとホスト側の同期ディレクトリにホーム直下に名前を指定したディレクトリを設定するように
デフォルトだと記載されているが、これだと1個しかホスト側にディレクトリを持てない。
デフォルトでこういった記述になっているのは如何なものかという気がしないでも無い。

**Comment by Taka-Hirayama** [comment]
If you are only creating a few sites, this generic mapping will work just fine. However, as the number of sites continue to grow, you may begin to experience performance problems. This problem can be painfully apparent on low-end machines or projects that contain a very large number of files. If you are experiencing this issue, try mapping every project to its own Vagrant folder:

複数プロジェクトを持つなら、mapするディレクトリを指定するようにとのこと。
folders:
    - map: ~/code/project1
      to: /home/vagrant/code/project1

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
