### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: @sashiyama: faker: Work log

### ISSUE THREAD

**Issue by sashiyama** [oss-gate/workshop#632]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by satoryu** [comment]
よろしくお願いしますー

**Comment by ryo-utsunomiya** [comment]
サポーターです。よろしくお願いします！

**Comment by suzukieita** [comment]
向かいの人です。よろしくおねがいします！

**Comment by ykagata** [comment]
よろしくお願いします。

**Comment by sashiyama** [comment]
公式ドキュメントを開く (https://github.com/stympy/faker)

**Comment by sashiyama** [comment]
インストール方法を見る( https://github.com/stympy/faker#installing )

**Comment by sashiyama** [comment]
インストールを以下のコマンドで行う
`rbenv exec gem install faker`

**Comment by sashiyama** [comment]
使い方を見る ( https://github.com/stympy/faker#usage )

**Comment by sashiyama** [comment]
使い方を参照しながらirbで動かす

**Comment by sashiyama** [comment]
公式ドキュメントの使い方を見ながら以下のコマンドを打つ
```
require `faker`
```
すると以下のエラーが発生
```
Errno::ENOENT: No such file or directory - faker
	from (irb):1:in ``'
```
なので、バッククォートではなくシングルクォートで囲んで実行

**Comment by sashiyama** [comment]
シングルクォーテーションで囲んで実行した場合、正しく読み込むことができた。
次に使い方を見ながら、以下を実行
```
irb(main):004:0> Faker::Name.name
=> "Ara Mraz"
irb(main):005:0> Faker::Internet.email
=> "justine@mosciskiwindler.co"
```
正常に動作した

**Comment by sashiyama** [comment]
バッククォートで正常に読み込めなかった理由を調べる

**Comment by sashiyama** [comment]
rubyのドキュメント(https://docs.ruby-lang.org/ja/latest/doc/spec=2fliteral.html)を見たところバッククォートで囲まれた文字列は、コマンドとして実行される
Usageからコピペして
```
require `faker`
```
を行うとエラーが発生する

**Comment by sashiyama** [comment]
以上はruby 2.4.1の環境で実行した。
別のバージョンでは動作するのかを確認する。(サンプルとして、2.2.4、2.3.4で動作させてみる)

**Comment by sashiyama** [comment]
2.3.4でも同様のエラーが発生
```
irb(main):003:0> require `faker`
Errno::ENOENT: No such file or directory - faker
	from (irb):3:in ``'
```

**Comment by sashiyama** [comment]
2.2.4でも同様のエラーが発生
```
irb(main):001:0> require `faker`
Errno::ENOENT: No such file or directory - faker
	from (irb):1:in ``'
```

**Comment by sashiyama** [comment]
やはりシングルクォートだと成功する
```
irb(main):002:0> require 'faker'
=> true
```

**Comment by sashiyama** [comment]
以上より、READMEのUsageをコピペで実行していくとエラーが発生すると考えられる

**Comment by sashiyama** [comment]
CONTRIBUTING.md( https://github.com/stympy/faker/blob/master/CONTRIBUTING.md )を見ながら以上のエラーをまとめていく

**Comment by sashiyama** [comment]
1. Fork the repo. とあるのでリポジトリをforkする

**Comment by sashiyama** [comment]
2. Run the tests. We only take pull requests with passing tests, and it's great to know that you have a clean slate: bundle && bundle exec rake
上記に従い、テストを実行

**Comment by sashiyama** [comment]
全てのテストをパスすることを確認

**Comment by sashiyama** [comment]
PRをsubmitした( https://github.com/stympy/faker/pull/1040 )

**Comment by sashiyama** [comment]
Usage以下の動作確認をしていく

**Comment by sashiyama** [comment]
以下のコマンドを実行
```
irb(main):004:0> Faker::Name.unique.name
=> "Ezra Kling"
```
正常に動作

**Comment by sashiyama** [comment]
以下を実行するとエラーが発生する
```
irb(main):029:0> Faker::Name.unique + ((1..1000).to_a).sample
NoMethodError: undefined method `+' for Faker::Name:Class
	from /Users/nijimac056/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faker-1.8.4/lib/faker.rb:185:in `method_missing'
	from /Users/nijimac056/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faker-1.8.4/lib/helpers/unique_generator.rb:11:in `public_send'
	from /Users/nijimac056/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faker-1.8.4/lib/helpers/unique_generator.rb:11:in `block in method_missing'
	from /Users/nijimac056/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faker-1.8.4/lib/helpers/unique_generator.rb:10:in `times'
	from /Users/nijimac056/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faker-1.8.4/lib/helpers/unique_generator.rb:10:in `method_missing'
	from (irb):29
	from /Users/nijimac056/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```
Faker::Name.uniqueに`+`methodが定義されていない

**Comment by sashiyama** [comment]
Faker::Nameのuniqueの定義場所を参照( https://github.com/stympy/faker/blob/master/lib/faker.rb )
UniqueGeneratorインスタンスが返されていたので、UniqueGeneratorの定義場所も参照( https://github.com/stympy/faker/blob/fbe20839ca533de1b6ec79de0c9ffcb2213d7f79/lib/helpers/unique_generator.rb )

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
