### ISSUE TITLE
OSS Gate Workshop: PHPCon2017: 2017-10-08: junichirojp: CakePHP Plugin, Bootstrap-UI : Work log

### ISSUE THREAD

**Issue by junichirojp** [oss-gate/workshop#633]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kenhys** [comment]
サポーターの kenhys です。

**Comment by msfukui** [comment]
Bootstrap-UI すごい！

**Comment by hayashier** [comment]
林です。お願いします！

**Comment by piroor** [comment]
サポーターのPiroです！

**Comment by taaatk** [comment]
こみやまです！

**Comment by junichirojp** [comment]
説明聞いて、CakePHPのプラグインの過去にあったバグ（？）を直してみたいね。

**Comment by junichirojp** [comment]
説明聞いて、CakePHPのプラグインの過去にあったバグ（？）を直してみたい。

**Comment by junichirojp** [comment]
確か名前はbootstrap UI

**Comment by junichirojp** [comment]
composer のjsonにあるやつがターゲットや。

**Comment by junichirojp** [comment]
これ。
"friendsofcake/bootstrap-ui": "~0.5",

**Comment by junichirojp** [comment]
url https://github.com/FriendsOfCake/bootstrap-ui

**Comment by junichirojp** [comment]
過去のコードは挙動怪しかったけど、今はどうかわからないからちょっとチェックしてみよう。

**Comment by junichirojp** [comment]
前はこれやるとレイアウトの変更がコントローラーレベルで制御できなかった。

https://github.com/FriendsOfCake/bootstrap-ui#appview-setup

**Comment by junichirojp** [comment]
リリースバージョンをチェックしよう

**Comment by junichirojp** [comment]
今使ってるバージョン : "version": "v0.6.1",

**Comment by junichirojp** [comment]
公式の最新バージョン 1.2.1
https://github.com/FriendsOfCake/bootstrap-ui/releases

**Comment by junichirojp** [comment]
直っているのかチェックしよう

**Comment by junichirojp** [comment]
自分のサイトのバージョンを上げてみて確認しよう

**Comment by junichirojp** [comment]
自分の環境はcomposerでインストールしたから、場合によっては他の依存関係で最新バージョンにあげられないかも。

**Comment by junichirojp** [comment]
packegistに、requires (dev) phpunit/phpunit: <6.0 ってのがあって、これが自分の環境にない疑惑。

https://packagist.org/packages/friendsofcake/bootstrap-ui

**Comment by junichirojp** [comment]
特定のプラグインのみバージョンアップするコマンドをチェック

**Comment by junichirojp** [comment]
検索キーワード「composer update plugin」

**Comment by junichirojp** [comment]
公式サイト見つけたのでそれをチェック

https://getcomposer.org/doc/articles/plugins.md

**Comment by junichirojp** [comment]
これじゃない

**Comment by junichirojp** [comment]
サイト内検索で「update」をチェック

**Comment by junichirojp** [comment]
これっぽいので読み込む

https://getcomposer.org/doc/03-cli.md#update

**Comment by junichirojp** [comment]
これだね。

php composer.phar update vendor/package vendor/package2

**Comment by junichirojp** [comment]
自分の環境にログインしてコマンドを叩いてみよう

**Comment by junichirojp** [comment]
ちょっと怖いので以下のコマンドあってるか再確認

php composer.phar update vendor/friendsofcake/

**Comment by junichirojp** [comment]
念のため --dry-run つけてシュミレーションしよう。

**Comment by junichirojp** [comment]
エラーメッセージ見て、多分コマンド間違ったので以下でもう一度トライ。

エラーメッセージ：Package "vendor/friendsofcake/" listed for update is not installed. Ignoring.

php composer.phar update vendor/friendsofcake/bootstrap-ui --dry-run

**Comment by junichirojp** [comment]
あ、エラーメッセージじゃなくてnoticeです。

**Comment by junichirojp** [comment]
余計なことをせず、まずはCakePHPを新しくインストールしよう。

**Comment by junichirojp** [comment]
そのあとに公式のuiをインストールしよう。

**Comment by junichirojp** [comment]
https://github.com/FriendsOfCake/bootstrap-ui#installing-using-composer

**Comment by junichirojp** [comment]
久しぶりにインストールの方法を確認。

https://book.cakephp.org/3.0/ja/installation.html

**Comment by junichirojp** [comment]
公式のマニュアルはいきなりサーバ内のコマンドの話が始まるので、自分の仮想環境を使おう。
これって開発環境を自分で準備できない人はいきなりお断りな状況になってる気がする。

**Comment by junichirojp** [comment]
自分の環境使えばどうにかなるけど、そもそもカタカナ多いし初心者お断り感が否めない。
なんか初心者の頃に初めて触ったCakePHP2系とは全然違うようになってる。

**Comment by junichirojp** [comment]
そういえば、php ってコマンド前提の文化になったのかな。
僕が新しいサイト作るときは必ずコマンドベースだから何も思わなかったけど、
今改めて手順見てくとちょっと難しくないかな。

**Comment by junichirojp** [comment]
virtualboxのファイル削除しちゃってたので、以下を見て入れ直す。

**Comment by junichirojp** [comment]
https://coodip.com/articles/3534#VirtualBox

**Comment by junichirojp** [comment]
既存のプロセスが動いているので再インストールでワーニング出た。

**Comment by junichirojp** [comment]
のでPCを再起動してしまおう。

**Comment by junichirojp** [comment]
いや、起動中の仮想サーバ落とした方が良さそう。
立ち上げてたの忘れてた。

**Comment by junichirojp** [comment]
やっぱり一度再起動しよう。

**Comment by junichirojp** [comment]
アドバイスもらって仮想環境ではなくローカルのホスト環境に構築しようと思ったけど、
phpの拡張プラグインなくてcomposerが途中でコマンドエラー吐いて終了するので、
やはりローカルのホスト環境に構築するのはちょいと敷居が高い。

**Comment by kou** [comment]
お疲れ様でした！
ぜひ第2回もやりたいので[Gitter](https://gitter.im/oss-gate/tokyo-php)で相談しましょう！

12月5日（火）の夜にここ3ヶ月くらいのOSS Gateの活動をふりかえる機会があります。
[OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)

ふりかえる材料としてPHPカンファレンス2017内で実施したOSS Gateワークショップ参加者が感じたことがあると助かるので、ぜひ12月5日までに https://github.com/oss-gate/retrospective/issues/new から感じたことを登録してください。「よかったこと」、「困ったこと」という分類で書いていますが、分類は気にせずに感じたことを書いてもらえれば大丈夫です。あとで、こっちでまとめて https://github.com/oss-gate/retrospective/projects/4 から見えるようにします。

これからも引き続きOSSの開発に参加していきましょう！
