### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-11-18: okiohashi: anemone: Work log

### ISSUE THREAD

**Issue by okiohashi** [oss-gate/workshop#640]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tshkh8** [comment]
本日のメンターをする大澤です！
よろしくお願いします

**Comment by okiohashi** [comment]
よろしくおねがいします！

**Comment by okiohashi** [comment]
- Githubのページを見た　https://github.com/chriskite/anemone/blob/next/README.rdoc
- Githubにのっているリンクを参照したけれどつながらなかった　anemone.rubyforge.org
- Googleで「anemone ruby」で検索したらhttps://rubygems.org/gems/anemone/versions/0.7.2が見つかった

**Comment by okiohashi** [comment]
`$ gem install anemone`を実行
gem installはできたが使い方がわからない...

**Comment by okiohashi** [comment]
anemone.rubyforge.org  がつながらなかったのでGithubのコミットログを調べたところ6年間更新されていなかった

**Comment by okiohashi** [comment]
メンテナンスされていないので他のOSSに変えることにしました。
