### ISSUE TITLE
 OSS Gate Workshop: Osaka: 2017-11-18: natsumi: nokogiri: Work log

### ISSUE THREAD

**Issue by 723gt** [oss-gate/workshop#641]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by gh640** [comment]
@723gt よろしくお願いします。

**Comment by gh640** [comment]
Ruby gem の Nokogiri を対象にされるとのことですね。

- 公式ページ: http://www.nokogiri.org/
- リポジトリ: https://github.com/sparklemotion/nokogiri
- rubydoc.info: http://www.rubydoc.info/github/sparklemotion/nokogiri

**Comment by 723gt** [comment]
よろしくお願いします！

**Comment by gh640** [comment]
ライセンスを確認されました。 MIT ライセンスでした。

- https://github.com/sparklemotion/nokogiri/blob/master/LICENSE.md

**Comment by 723gt** [comment]
最新版のインストール方法  
公式リポじ土地
```  
git clone git@github.com:sparklemotion/nokogiri.git

**Comment by 723gt** [comment]
最新版を手元に落とす  
[リポジトリ](https://github.com/sparklemotion/nokogiri)
```  
git clone git@github.com:sparklemotion/nokogiri.git  
```   
ビルドするために依存のライブラリをインストールする  
```  
cd nokogiri  
bundle install
```  
ビルドする  
```  
bundle exec rake  
```  

メモ: 
bundle のバージョン 1.14.6
Ruby のバージョン 2.4.1.

**Comment by 723gt** [comment]
ローカルへのインストール  
```  
gem install nokogiri -- --use-system-libraries
```
確認
```
gem list -local | grep nokogiri  
```
1.8.1がアレば成功

**Comment by 723gt** [comment]
公式のREADMEに書いてある通りのサンプルプログラムで  
正常に動作をするの確認

**Comment by 723gt** [comment]
動作環境: macOS Sierra 10.12.6

**Comment by gh640** [comment]
動作上気になる問題点はないため改善点を探し中です。

**Comment by 723gt** [comment]
READMEでローカルでのテスト実行方法が明確になっていないので
issuesに書き込む

**Comment by gh640** [comment]
issue のレポート方法について調べています・・・

- https://github.com/sparklemotion/nokogiri/blob/master/CONTRIBUTING.md
- http://www.nokogiri.org/tutorials/getting_help.html

**Comment by 723gt** [comment]
ドキュメント周りの規約をしっかり作って欲しい

**Comment by gh640** [comment]
イシューを作られました 🎉 

- https://github.com/sparklemotion/nokogiri/issues/1691

**Comment by 723gt** [comment]
バグレポートについては書いて有ることがドキュメントについてはないことをコメントしました

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by ShinjiEnoki** [comment]
現状は、テストが手元で実行する方法がわからない、ということなのですね？

**Comment by ShinjiEnoki** [comment]
それはどこで聞けばいいのだろう？と思いました。
現状わかっているチャネルがissue, MLなら、どちらかで聞いちゃってもよいかも...

**Comment by gh640** [comment]
いったん完了なので 2 つめに・・・

**Comment by 723gt** [comment]
vue.jsの日本語ドキュメントhttps://github.com/vuejs/jp.vuejs.org
の修正点を探して行こうと思います

**Comment by 723gt** [comment]
https://vuejs.org/v2/guide/instance.html#Data-and-Methods  
でhtmlを書かないとTrueではなくfalseになるのでhtmlを書くことを明記する

**Comment by gh640** [comment]
@723gt たとえば、 PR の説明文のイメージを私も考えてみました。

> その後に続く JS コードを問題なく動かすには id `example` の要素が HTML 内にあることが前提になっていると思います。
> 
> その HTML コードを追加するとよりわかりやすくなると思います。

> It's supposed that there's an element with id `example` in the html file for the JavaScript code to work.
> 
> So I believe it's better to put the expected html code before the JavaScript code.
> 
> Thank you in advance.

**Comment by 723gt** [comment]
[PR投げました！](https://github.com/vuejs/vuejs.org/pull/1285)

**Comment by gh640** [comment]
> https://vuejs.org/v2/guide/instance.html#Data-and-Methods
> でhtmlを書かないとTrueではなくfalseになるのでhtmlを書くことを明記する

いいポイントですね！

確かに、読む側はコードブロックをメインで読むので、コードが動作する前提が地の文で説明されているだけだとわかりにくいですね。

**Comment by ogom** [comment]
おつかれさまでした！

直近の大阪で開催されるOSS Gateのイベントは以下のとおりです！

3月10日: [大阪ワークショップ](https://oss-gate.doorkeeper.jp/events/69160)

是非よかったらまた参加してみてください！
