### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-11-18: hightensan: gmplot: Work log

### ISSUE THREAD

**Issue by hightensan** [oss-gate/workshop#643]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hightensan** [comment]
"""pip install gmplot"""　実行

**Comment by hightensan** [comment]
juster notebook で環境設定

**Comment by hightensan** [comment]
import gmplot
gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 16)
gmap.draw("mymap.html")

**Comment by hightensan** [comment]
READMEが不親切

**Comment by hightensan** [comment]
<img width="1680" alt="mymap html" src="https://user-images.githubusercontent.com/2528608/32977094-ea899810-cc69-11e7-8d06-560225a5aec6.png">

**Comment by hightensan** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-543e83674ab7> in <module>()
      4 import os
      5 
----> 6 from .color_dicts import mpl_color_map, html_color_codes
      7 
      8 

ValueError: Attempted relative import in non-package

**Comment by hightensan** [comment]
from .color_dicts import mpl_color_map, html_color_codes
-> from color_dicts import mpl_color_map, html_color_codes
でエラーが出なくなった

**Comment by hightensan** [comment]
<img width="1680" alt="gmplot gmplot python" src="https://user-images.githubusercontent.com/2528608/32977236-a22d13c8-cc6c-11e7-957b-d2bc6aac88ab.png">

**Comment by hightensan** [comment]
scatter_path = ([37.424435, 37.424417, 37.424417, 37.424554, 37.424775, 37.425099, 37.425235, 37.425082, 37.424656, 37.423957, 37.422952, 37.421759, 37.420447, 37.419135, 37.417822, 37.417209],
                    [-122.142048, -122.141275, -122.140503, -122.139688, -122.138872, -122.138078, -122.137241, -122.136405, -122.135568, -122.134731, -122.133894, -122.133057, -122.13222, -122.131383, -122.130557, -122.129999])
    mymap.scatter(scatter_path[0], scatter_path[1], c='r', marker=True)

<img width="1680" alt="scatter" src="https://user-images.githubusercontent.com/2528608/32977273-5095adf8-cc6d-11e7-8d7c-bae3726b3bfd.png">

**Comment by yukihirop** [comment]
MACの機能？のホットコーナーを使うと、デスクトップに移動しやすくなりますよ！
https://support.apple.com/kb/PH25524?locale=ja_JP&viewlocale=ja_JP

**Comment by hightensan** [comment]
```python
path = [(37.429, 37.428, 37.427, 37.427, 37.427),
             (-122.145, -122.145, -122.145, -122.146, -122.146)]
path2 = [[i+.01 for i in path[0]], [i+.02 for i in path[1]]]
path3 = [(37.433302 , 37.431257 , 37.427644 , 37.430303), (-122.14488, -122.133121, -122.137799, -122.148743)]
path4 = [(37.423074, 37.422700, 37.422410, 37.422188, 37.422274, 37.422495, 37.422962, 37.423552, 37.424387, 37.425920, 37.425937),
         (-122.150288, -122.149794, -122.148936, -122.148142, -122.146747, -122.14561, -122.144773, -122.143936, -122.142992, -122.147863, -122.145953)]
mymap.heatmap(path4[0], path4[1], threshold=10, radius=40)
mymap.heatmap(path3[0], path3[1], threshold=10, radius=40, dissipating=False, gradient=[(30,30,30,0), (30,30,30,1), (50, 50, 50, 1)])
```

<img width="1680" alt="heatmap" src="https://user-images.githubusercontent.com/2528608/32977303-ecc961ec-cc6d-11e7-97e8-5c4876931208.png">

**Comment by yukihirop** [comment]
実行できたらメソッドの引数の値を変えて実行して動きを理解していきたいですね！

**Comment by hightensan** [comment]
```python
mymap.heatmap(path4[0], path4[1], threshold=10, radius=40)
mymap.heatmap(path3[0], path3[1], threshold=10, radius=40, dissipating=False, gradient=[(30,30,30,0), (300,300,300,1), (50, 50, 50, 1)])
```
<img width="1680" alt="2017-11-18 14 41 04" src="https://user-images.githubusercontent.com/2528608/32977326-934c9b2e-cc6e-11e7-978b-f8cba7c751ff.png">

**Comment by hightensan** [comment]
```python
mymap.heatmap(path4[0], path4[1], threshold=10, radius=40)
mymap.heatmap(path3[0], path3[1], threshold=10, radius=40, dissipating=False, gradient=[(30,30,30,1), (30,30,30,0)])
```
<img width="1680" alt="2017-11-18 14 43 37" src="https://user-images.githubusercontent.com/2528608/32977339-f0d90bf6-cc6e-11e7-96f2-16502ca143b3.png">

**Comment by hightensan** [comment]
```
gradient=[(r, g, b, a)] # a: 不透明度
```

**Comment by tshkh8** [comment]
振り返りを担当した大澤です。

作業内容はしっかりメモにかけているので、
あとは、これから何をするか、とか
作業中に感じたこととかもメモするとよいと思います！

**Comment by yukihirop** [comment]
プルリクエストを送るに当たって、まずここにPR ディスクリプションを描いてもらいます。

**Comment by hightensan** [comment]
python==ver.2.7.11
gmplot==1.2.0

```python
python ./gmplot/gmplot.py
```

Traceback (most recent call last):
File "gmplot.py", line 6, in 
from .color_dicts import mpl_color_map, html_color_codes
ValueError: Attempted relative import in non-package

**Comment by yukihirop** [comment]
railsでissue作成する時のテンプレートとか書き方の参考になります。

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**Comment by hightensan** [comment]
gmplot リポジトリをfork & clone

**Comment by yukihirop** [comment]
[memo]
ghqコマンドを使う事で`ghq get hightensan/gmplot` って感じでクローンできたりもします。
https://github.com/motemen/ghq

[memo]
tigってコマンドを使うと、git操作がやりやすくなったりします。
https://github.com/jonas/tig

一次情報だけ乗っけてますが、qiitaとかで記事を探して見るとイメージがわかるかもしれません。

**Comment by hightensan** [comment]
git checkout -b fix_color_dicts_import_error

**Comment by hightensan** [comment]
```bash
git add .
git commit -m 'remove "."color_dicts'
```

**Comment by hightensan** [comment]
system(icloud) に cloneしたらwrite errorが起きる

**Comment by hightensan** [comment]
local環境上(デスクトップ上)で作業
```bash
$ git clone https://github.com/vgm64/gmplot.git
$ cd gmplot
$ git checkout -b fix_color_dicts_import_error
```
gmplot.pyを編集

```bash
git add .
git commit -m 'remove . from .color_dicts'
# git remote get-url origin
git push --set-upstream origin fix_color_dicts_import_error
```

**Comment by hightensan** [comment]
git status でまだcommitされていない操作を確認
git log でcommit logを確認

**Comment by hightensan** [comment]
プルリクエストURL
https://github.com/vgm64/gmplot/pull/54

**Comment by yukihirop** [comment]
[memo]
ターミナルは`iterm2`を使った方がいいかもしれません。

**Comment by yukihirop** [comment]
[memo]
リポジトリで`t`を押して検索モードにして、`CONTRIBUTE.md`がないかどうかを調べる癖をつけたがいいと教えました。

**Comment by yukihirop** [comment]
実際に何かOSSを作り始める際に役に立つであろう事の情報共有

[memo]
進捗管理には、PivotalTrackerとかが使えます

[memo]
反省会とかでみんなで問題共有をする際は、treloが使えますよ

**Comment by ogom** [comment]
おつかれさまでした！

直近の大阪で開催されるOSS Gateのイベントは以下のとおりです！

3月10日: [大阪ワークショップ](https://oss-gate.doorkeeper.jp/events/69160)

是非よかったらまた参加してみてください！
