### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-11-18: mu2in: riot.github.io: Work log

### ISSUE THREAD

**Issue by mu2in** [oss-gate/workshop#644]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mu2in** [comment]
ライセンスの確認
https://github.com/riot/riot.github.io/blob/master/license.md
→MITだった

**Comment by mu2in** [comment]
https://opensource.org/licenses/alphabetical
→MITライセンスはOSSであることを確認しました

**Comment by ShinjiEnoki** [comment]
こんにちは。今日はよろしくお願いします

**Comment by mu2in** [comment]
よろしくお願いします 👍

**Comment by mu2in** [comment]
http://riotjs.com/
の「試す」が日本語化されてないので対応したい。

**Comment by mu2in** [comment]
ソースの場所
https://github.com/riot/riot.github.io/

**Comment by mu2in** [comment]
日本語設定ファイルがなぜか2つある？？
https://github.com/riot/riot.github.io/tree/master/ja
https://github.com/riot/riot.github.io/tree/master/v2/ja
今使われているのはv2なのか？

**Comment by mu2in** [comment]
最新のブランチは3.7.4だが、日本語化が終わっているのは3.0.0
他の言語は2.x.x系のため、v2配下に置いているみたい

**Comment by mu2in** [comment]
メニューのリンクはどこに記述されているか確認する

**Comment by mu2in** [comment]
ヘッダーのリンク発見
https://github.com/riot/riot.github.io/blob/master/_layouts/ja.html

**Comment by mu2in** [comment]
`<a href="/play/">試す</a>` のリンクを確認

**Comment by mu2in** [comment]
`<a href="/play/">試す</a>` のリンクを確認

**Comment by mu2in** [comment]
git で誤って上書きしたindex.mdファイルを戻す
`git checkout index.md`

**Comment by mu2in** [comment]
playのディレクトリをja配下にコピーして、
日本語化できそうな部分を日本語化する

**Comment by mu2in** [comment]
とりあえず動かしてみたいので、README.mdを読んだところ、
Jekyllで動いていることがわかった。

**Comment by mu2in** [comment]
検証用にDockerイメージを落としてきて、動くか試してみる
```
export JEKYLL_VERSION=3.5
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  jekyll build
```
参考： https://github.com/envygeeks/jekyll-docker

**Comment by mu2in** [comment]
公式イメージなのになぜかうまく動かなかった

**Comment by mu2in** [comment]
Docker使いたいので以下でもう一度試してみる
https://arkuuu.de/blog/jekyll-development-docker

**Comment by mu2in** [comment]
Docker上のローカルサーバーでJekyllを使ってデプロイできた。

**Comment by mu2in** [comment]
動作確認でタブのリンク先が英語のままなので、変更する

**Comment by mu2in** [comment]
貢献ガイドラインを見つけた！
https://github.com/riot/examples/blob/gh-pages/CONTRIBUTING.md

（いま気づいた）

**Comment by mu2in** [comment]
翻訳したページのプルリクエストを投げました。
https://github.com/riot/riot.github.io/pull/193

**Comment by gh640** [comment]
ご説明いただきありがとうございました。細かくメモを取られていて、ご説明もわかりやすかったのでとてもいいと思いました！

お話に上がったポイントをメモさせていただきます。

- PR を出した後どのように処理されていくのかを知っておくといいかもしれません。ドキュメントの日本語訳の場合は日本の方が内容もレビューする場合と、外国の方が日本語の中身はチェックせずマージされる場合とがあります。
- リポジトリのコントリビュータ一覧や、閉じられたイシュー、閉じられた PR を見ると、リポジトリの活動がわかります。

**Comment by ogom** [comment]
おつかれさまでした！

直近の大阪で開催されるOSS Gateのイベントは以下のとおりです！

3月10日: [大阪ワークショップ](https://oss-gate.doorkeeper.jp/events/69160)

是非よかったらまた参加してみてください！
