### ISSUE TITLE
 OSS Gate Workshop: Osaka: 2017-11-18:tetrapod117:beautifulsoup4: Work log

### ISSUE THREAD

**Issue by tetrapod117** [oss-gate/workshop#646]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
hello, daddygongonです．よろしく．

**Comment by tetrapod117** [comment]
https://pypi.python.org/pypi/beautifulsoup4に記載あり。

**Comment by tetrapod117** [comment]
http://kondou.com/BS4/
日本語のドキュメントです

**Comment by daddygongon** [comment]
「スープの作成」でつまづいています．index.htmlをBeautifulSaopにする？？

**Comment by daddygongon** [comment]
* 日本語のドキュメントと，英語のドキュメントで記述が違う．
* warningが消えた．
* どこにpull requestがだせるか．

**Comment by tetrapod117** [comment]
https://www.crummy.com/software/BeautifulSoup/bs4/doc/
英語版のドキュメントではQuick Startのソースコードが
'''python
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc,"html.parser")
'''

となっているが、日本語版では
```python
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc)
```
となっていて、日本語版ではwarningが出る

**Comment by daddygongon** [comment]
この文書は Beautiful Soup 4.2.0 Documentation の日本語訳です。”Beautiful Soup”を”ビューティフルソープ”と読んでしまう英語が苦手でちょっぴりHな後輩のために翻訳しました。

誤訳やわかりづらいところを見つけたり、なにかご意見があるときには、近藤茂徳()までご連絡ください。
となってますね．．．どうしましょう．

**Comment by daddygongon** [comment]
連絡先は絵でした．

**Comment by daddygongon** [comment]
日本語訳の連絡先が絵でumekomareteいます．

**Comment by tetrapod117** [comment]
soup.find_allやsoup.get_textの検証をしています。

**Comment by tetrapod117** [comment]
バグ探しはやりたいことをやっていたら自ずと見つかる

**Comment by gh640** [comment]
コードは

https://www.crummy.com/software/BeautifulSoup/bs4/download/

などにあるとのことですが、貢献する方法などがよくわからない、とのことでしたね。

引き続きがんばってください :)

**Comment by tetrapod117** [comment]
ありがとうございます。
とりあえず、BeautifulSoupの第2引数について、日本語ドキュメントの翻訳者の方にメールを送ってみます。

**Comment by tetrapod117** [comment]
Webページの内容をBeautifulSoupを使って、取得する方法が英語のドキュメントにも記載されていないので、それを追加してもらうようにメッセージを送るのもありかもしれない。

**Comment by tetrapod117** [comment]
##メールの下書き

https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 
英語版のドキュメントではQuick Startのソースコードが
```python
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc,"html.parser")
```
となっていますが、 
http://kondou.com/BS4/
日本語版のクイックスタートでは
```python
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc)
```
となっていて、関数BeautifulSoupの第2引数がないため、「UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.」というwarningが出てしまいます。
実行自体には問題ないのですが、日本語ドキュメントが更新されていないため、自分の周辺では自分を含めて3人がXXXしています。

**Comment by daddygongon** [comment]
##メールの下書き
https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 
英語版のドキュメントではQuick Startのソースコードが
```
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc,"html.parser")
となっていますが、 
http://kondou.com/BS4/
日本語版のクイックスタートでは

from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc)
となっていて、関数BeautifulSoupの第2引数がないため、「UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.」というwarningが出てしまいます。
実行自体には問題ないのですが、日本語ドキュメントが更新されていないため、自分の周辺では自分を含めて3人がXXXしています。

**Comment by daddygongon** [comment]
##メールの下書き
bs4の日本語の提供ありがとうございます．英語苦手なんで助かります．
すこし気になる点があったので，指摘させいただきます．

https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 
英語版のドキュメントではQuick Startのソースコードが
```
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc,"html.parser")
```
となっていますが、 
http://kondou.com/BS4/
日本語版のクイックスタートでは
```
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc)
```
となっていて、関数BeautifulSoupの第2引数がないため、
```
「UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.」
```
というwarningが出てしまいます。
実行自体には問題ないのですが、自分の周辺では自分を含めて3人が困惑しちゃいました．
えっと，日本語で始める人には便利なんですが，ドキュメントの頭あたりでのちょっとした
ワーニングなんで，気になって後のドキュメントの信頼性に疑問を抱いてしまうかもしれません．
もし，お時間がありましたら，修正していただきますようお願い申し上げます．

**Comment by daddygongon** [comment]
> UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

**Comment by tetrapod117** [comment]
* メール下書き

 BeautifulSoup4のマニュアルの日本語版の提供ありがとうございます。英語苦手なので参考にさせていただいています。
そこで、すこし気になる点があったので、指摘させいただきます。

BeautifulSoup4の英語版のドキュメントQuick Startのソースコードでは
https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 

```Python
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc,"html.parser")
```
となっているのですが、 

日本語版のクイックスタートでは
http://kondou.com/BS4/

```Python
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc)
```
となっていて、関数BeautifulSoupの第2引数がないため、

>UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

というwarningが出てしまいます。
実行自体には問題ないのですが、自分の周辺では自分を含めて3人が実行の際に困惑してしまいました。
日本語で始める人にとっては便利なんですが，ドキュメントの頭でのちょっとしたワーニングなんで，気になって後のドキュメントの信頼性に疑問を抱いてしまうかもしれません。
もし、お時間がありましたら、修正していただきますようお願い申し上げます。

**Comment by tetrapod117** [comment]
* BeautifulSoup4の日本語版ドキュメントの修正依頼
というタイトルでメールを送信しました。

**Comment by tetrapod117** [comment]
>Webページの内容をBeautifulSoupを使って、取得する方法が英語のドキュメントにも記載されていないので、それを追加してもらうようにメッセージを送るのもありかもしれない。

URLを開くPythonのモジュールはたくさんあるので、サンプルを置いたら、それしか使えないと思われてしまうかもしれないので、載せていない可能性がある。

**Comment by ogom** [comment]
おつかれさまでした！

直近の大阪で開催されるOSS Gateのイベントは以下のとおりです！

3月10日: [大阪ワークショップ](https://oss-gate.doorkeeper.jp/events/69160)

是非よかったらまた参加してみてください！
