### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-11-18: okiohashi: platformio-atom-ide-terminal : Work log

### ISSUE THREAD

**Issue by okiohashi** [oss-gate/workshop#647]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by okiohashi** [comment]
- Googleで「Atom」を検索
- https://atom.io/ のページにGithubへのリンクがあった https://github.com/atom/atom
- ライセンスはMITだった

**Comment by okiohashi** [comment]
- 開発対象をplatformio-atom-ide-terminal に変更
- Githubのページ https://github.com/platformio/platformio-atom-ide-terminal を見た
- フォーク元のterminal-plusのページ https://github.com/jeremyramin/terminal-plus をみたらMITライセンスだった

**Comment by okiohashi** [comment]
- AtomのSettings Installからplatformio-atom-ide-terminalを検索しインストール
- Usageに従って動作確認

**Comment by okiohashi** [comment]
- カーソルの種類の変え方がわからない

**Comment by daddygongon** [comment]
* atomのeditorでつかえるshellのplug in
* platformio-atom-ide-terminal
* installはできた．
* 気になったのは，
  * カーソルの種類をかえられない．．．
  * その記述が使い方には見当たらない．

**Comment by daddygongon** [comment]
面白そうですね．
https://github.com/platformio/platformio-atom-ide-terminal/blob/master/styles/themes.less
なんかに，cursorだけでなく，themesのselectができそうです．そんな便利の機能があるのならば，その記述が抜けているのは残念ですよね．

**Comment by okiohashi** [comment]
- Settingsでカラーテーマを変更するとカーソルの種類が変わるかもしれないのでテーマを変えてみたがカーソルは変わらなかった
- カーソルの変更機能はないみたい
- カーソルの種類を設定しているファイルを探したが見つからない

**Comment by okiohashi** [comment]
質問
- ターミナルの入力エリアのカーソルの種類を変更したいが、そのやり方がわからない

調べたこと
- Settingsでカラーテーマを変更するとカーソルの種類が変わるかもしれないのでテーマを変えてみたがカーソルは変わらなかった
- カーソルの種類を設定しているファイルを探したが見つからない
- カーソルのスタイルを定義する記述`.terminal-cursor`が`styles/themes`の各テーマにあった
- .terminal-cursorが適用されている部分が見つからない

**Comment by okiohashi** [comment]
質問内容

入力エリアのカーソルの種類を変更したいのですがどうすればいいでしょうか？
Settingsでカーソルの種類を変更する項目がないか探しましたが、ありませんでした。
Settingsでカラーテーマを変更するとカーソルの種類が変わるかもしれないと思いテーマを変えてみたがカーソルは変わリませんでした。
カーソルの種類を定義しているファイルを探したが見つかりませんでした。
カーソルのスタイルを定義する記述`.terminal-cursorがstyles/themes`の各テーマにあるのがみつかりましたが、`.terminal-cursor`が適用されている記述が見つかりませんでした。

**Comment by okiohashi** [comment]
- GithubのIssueで「cursor」と検索し類似のIssueがないか調べた
- 同じことを聞いているIssueがあった　https://github.com/platformio/platformio-atom-ide-terminal/issues/226
- 解決方法としてはブロックの高さもしくは幅をスタイルで指定することで変更できるようにしている

**Comment by okiohashi** [comment]
やりたいこと
- カーソルの変更をプラグインのSettings内でGUIでできるようにしたい
- iTerm2のカーソル設定のようにラジオボタンで選べるようにしたい

**Comment by okiohashi** [comment]
Issueに書く内容

テキスト入力エリアのカーソルの種類をSettings内で変更できるようにしたいです。
例えば、下の画像のようにラジオボタンで選択できるといいと思います
<image src=https://user-images.githubusercontent.com/20331021/32978108-a2e8a932-cc7e-11e7-8eda-340d6a1aad7d.jpg width="40%">

**Comment by okiohashi** [comment]
It's better to be able to change the type of cursor within "Settings" like the image below.
<image src=https://user-images.githubusercontent.com/20331021/32978108-a2e8a932-cc7e-11e7-8eda-340d6a1aad7d.jpg width="40%">

**Comment by okiohashi** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/413

**Comment by ogom** [comment]
おつかれさまでした！

直近の大阪で開催されるOSS Gateのイベントは以下のとおりです！

3月10日: [大阪ワークショップ](https://oss-gate.doorkeeper.jp/events/69160)

是非よかったらまた参加してみてください！
