### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: cocoeyes02: anaconda: Work log

### ISSUE THREAD

**Issue by cocoeyes02** [oss-gate/workshop#667]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by swamp09** [comment]
サポーターの沼田です。
よろしくお願いします！

**Comment by cocoeyes02** [comment]
よろしくお願いします！
LICENSEを確認
https://github.com/ChimeraCoder/anaconda/blob/master/LICENSE

**Comment by cocoeyes02** [comment]
まずはREADME.mdを眺めてみる

**Comment by cocoeyes02** [comment]
README.mdの文章中にリンク切れが存在する

**Comment by cocoeyes02** [comment]
リンク切れの箇所をblameで見ると、更新が5年前なのでその間にURLが変わっていた可能性がありそう

**Comment by cocoeyes02** [comment]
リンク切れと正しいURLっぽいもののまとめ

誤：https://developer.twitter.com/docs/rate-limiting/1.1
正?：https://developer.twitter.com/en/docs/basics/rate-limiting

誤：https://developer.twitter.com/docs/api/1.1
正?：https://developer.twitter.com/en/docs/api-reference-index

**Comment by cocoeyes02** [comment]
ソースコードのコメントに書いてあるURLにもリンク切れURLがたくさんある

**Comment by cocoeyes02** [comment]
このコメントにあるURLのリンク切れが他に影響しているか判断する
方針としては、
* 実装に影響しているかどうかソースを読み解く
* 他のissueを見て見る

**Comment by cocoeyes02** [comment]
関連したissue、Pull Requestはなさそう

**Comment by cocoeyes02** [comment]
実装もぱっと見では問題ないように見える

**Comment by cocoeyes02** [comment]
色々なファイルに書いてあるURLがリンク切れしている趣旨のissueを投げれば良さそう

**Comment by cocoeyes02** [comment]
これはあっているというURLがあればその部分はPullRequestで出してあげる。
そうでない部分はリンク切れに対して正誤表を作成し、issueを立てて貼り付ける。
その後、開発者のコメントを待ち対応する。

**Comment by cocoeyes02** [comment]
ソースコードを更に読んでみての整理
* READMEのリンク切れはドメイン、エンドポイントを含めて違うリンク切れである
* ソースコードのコメントに書いてあるURLのリンク切れは複数パターンある
  * ドメイン、エンドポイントを含めて違うリンク切れ
  * エンドポイントのみが違うリンク切れ

**Comment by cocoeyes02** [comment]
ソースコードを1つ例でみて見る
``` go
//PutActivityWebhooks update webhook which reenables the webhook by setting its status to valid.
//https://dev.twitter.com/webhooks/reference/put/account_activity/webhooks
func (a TwitterApi) PutActivityWebhooks(v url.Values, webhookID string) (u interface{}, err error) {
	responseCh := make(chan response)
	a.queryQueue <- query{a.baseUrl + "/account_activity/webhooks/" + webhookID + ".json", v, &u, _PUT, responseCh}
	return u, (<-responseCh).err
}
```

* この実装だと、ドメイン変わっていてもエンドポイントが変わっていなければ問題なく動く
* ただし、エンドポイントが変わってしまうとこの関数自体が動かなくなる可能性がある

**Comment by cocoeyes02** [comment]
* 動作の方に影響があるかどうか判断するのは実際に使ってみないとわからないので、今回はリンク切れの報告のみに止める

**Comment by cocoeyes02** [comment]
* リンク切れしているURLとファイルのリストアップを始める

**Comment by cocoeyes02** [comment]
* 合っていそうなURLが分かっているものはプルリクを出す方針にする

**Comment by cocoeyes02** [comment]
プルリクを出した。ありがとうございました。
https://github.com/ChimeraCoder/anaconda/pull/227

**Comment by ishimoto-ttt** [comment]
https://gitlab.com/meno/dropzone/merge_requests/28

**Comment by knokmki612** [comment]
おつかれさまでした！
PRがマージされてますね！よかったです！！！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ 
* 1月27日: 東京ワークショップ

是非よかったらまた参加してみてください！
