### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: kanakumagai: slim-rails: Work log

### ISSUE THREAD

**Issue by kanakumagai** [oss-gate/workshop#669]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by okkez** [comment]
よろしくおねがいします！

**Comment by rtusys** [comment]
よろしくおねがいします！

**Comment by kanakumagai** [comment]
slim-rails gem で検索し、
https://rubygems.org/gems/slim-rails/versions/3.1.0
と

**Comment by kanakumagai** [comment]
slim-rails を導入するためにローカルにrailsプロジェクトを新規作成

**Comment by kanakumagai** [comment]
Gemfileに 'gem 'slim-rails'  と記述し、bundle installでslim-rails導入

**Comment by kanakumagai** [comment]
slim-ralisのドキュメント

**Comment by kanakumagai** [comment]
上記ドキュメントを読んでも何をするgemかよくわからない。
「slim-rails ドキュメント」で検索してみる。
https://github.com/slim-template/slim/blob/master/README.jp.md
一番上にslimのreadmeが出てくる。

**Comment by kanakumagai** [comment]
slim-railsのreadmeには
From the version 0.2.0, there is no need to include gem "slim" in your Gemfile.
とあるけど、slimに依存している。
`spec.add_runtime_dependency 'slim', ['~> 3.0']`

**Comment by kanakumagai** [comment]
slimとslim-railsの関係性をもう少しわかり易くしてほしい

**Comment by kanakumagai** [comment]
`From the version 0.2.0, there is no need to include gem "slim" in your Gemfile.`
この一文は6年以上前のバージョンに関する情報のため、削除したほうがよいと思う。

**Comment by kanakumagai** [comment]
slimのジェネレータを提供するgemなので、[slimのリンク](https://github.com/slim-template/slim)があると理解しやすい

**Comment by kanakumagai** [comment]
タイトル：TODO
READMEの下記の一文についてです。
`From the version 0.2.0, there is no need to include gem "slim" in your Gemfile.`
この文章は６年以上前のバージョンに関する情報であるため、削除すべきかと思います。



About the following sentence of README.
`From the version 0.2.0, there is no need to include gem "slim" in your Gemfile.`
This sentence is too old information.
You should delete it.

**Comment by kanakumagai** [comment]
About the following line of README.
From the version 0.2.0, there is no need to include gem "slim" in your Gemfile.
This line older than 6 years.
We can delete it.

**Comment by kanakumagai** [comment]
[PR出しました](https://github.com/slim-template/slim-rails/pull/150):bow:

**Comment by knokmki612** [comment]
おつかれさまでした！
古い記述を見つけたり、それに対してPRを出す流れなど分かりやすく、有意義な時間を過ごされているなと思いました！

**Comment by knokmki612** [comment]
おつかれさまでした！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ 
* 1月27日: 東京ワークショップ

是非よかったらまた参加してみてください！
