### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: NanaAruga: zendframework: Work log

### ISSUE THREAD

**Issue by NanaAruga** [oss-gate/workshop#672]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by uchan-nos** [comment]
よろしくお願いします！

**Comment by hyuraku** [comment]
本日はよろしくお願いします！

**Comment by knokmki612** [comment]
よろしくお願いします！

**Comment by NanaAruga** [comment]
Zendframeworkを選んだ。
まずは、OSSであることの確認を。。

GitHubで「Zendframework」で検索で
https://github.com/zendframework/zendframework
↓
https://github.com/zendframework/zendframework/blob/master/LICENSE.md
に「BSD 3-clause "New" or "Revised" License」の記載

https://opensource.org/licenses/alphabetical　に
「The 3-Clause BSD License」があるので問題ない。

**Comment by NanaAruga** [comment]
インストール手順を調べる。。

公式サイトは
Official Zend Framework repository https://framework.zend.com/

■Installのページ
https://framework.zend.com/downloads
を見つけたが、日本語のページがない？

Installation of Zend Framework is only a Composer command away:
→インストールにComposer コマンドが使えないとダメらしい。
　とりあえず、コマンド叩いてみたが自分の環境にない。

■「Composer」のリンクから
https://getcomposer.org/
（相変わらず英語ページ、日本語の公式ページはなさそう）
↓
Downloadページに行く
https://getcomposer.org/download/
「Windows Installer」があったのでダウンロードする。

**Comment by NanaAruga** [comment]
■Composerインストール
ダウンロードした「Composer-Setup.exe」を実行
→すべて「Next」（インストーラーの初期設定を変更しないで実行）

正常終了した。

**Comment by NanaAruga** [comment]
■Composerを動かす
実行結果は
_C:\Users\nana.aruga\Downloads>composer
'composer' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。_
※動かない

downloadページに、
_The installer will download composer for you and set up your PATH environment variable so you can simply call composer from any directory._
とあったので、PATH設定を見てみた。

_C:\Users\nana.aruga\AppData\Roaming\Composer\vendor\bin_
が追加されていた→しかしこのフォルダは作成されていない。

C:\Users\nana.aruga\AppData\Roaming\Composer\
までならフォルダがあるのでPATHをこれに変更して実行してみた。
→結果は同じ（動かない）

**Comment by NanaAruga** [comment]
■Composer再インストール
ダウンロードした「Composer-Setup.exe」を実行
途中でインストーラから「コマンドプロンプトを閉じろ」的メッセージが出たので、
cmdを閉じて再実行

■Composerを動かす
実行結果：
C:\Users\nana.aruga>composer -V
Composer version 1.5.2 2017-09-11 16:59:25

**Comment by NanaAruga** [comment]
■Zendframeworkインストール
https://framework.zend.com/downloads
の記載に従って実行

composer require zendframework/zendframework

実行結果：

C:\xampp\htdocs>composer require zendframework/zendframework
Using version ^3.0 for zendframework/zendframework
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 101 installs, 0 updates, 0 removals
  - Installing zendframework/zendxml (1.0.2): Downloading (100%)
  - Installing zendframework/zend-stdlib (3.1.0): Downloading (100%)
  - Installing zendframework/zend-eventmanager (3.2.0): Downloading (100%)
  - Installing zendframework/zend-code (3.1.0): Downloading (100%)
  - Installing zendframework/zend-server (2.7.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.11): Downloading (100%)
  - Installing zendframework/zend-math (3.0.0): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing container-interop/container-interop (1.2.0): Downloading (100%)
  - Installing zendframework/zend-validator (2.10.1): Downloading (100%)
  - Installing zendframework/zend-escaper (2.5.2): Downloading (100%)
  - Installing zendframework/zend-uri (2.5.2): Downloading (100%)
  - Installing zendframework/zend-loader (2.5.1): Downloading (100%)
  - Installing zendframework/zend-http (2.7.0): Downloading (100%)
  - Installing zendframework/zend-xmlrpc (2.6.1): Downloading (100%)
  - Installing zendframework/zend-json (3.0.0): Downloading (100%)
  - Installing zendframework/zend-xml2json (3.1.0): Downloading (100%)
  - Installing zendframework/zend-view (2.9.0): Downloading (100%)
  - Installing zendframework/zend-servicemanager (3.3.0): Downloading (100%)
  - Installing zendframework/zend-text (2.6.0): Downloading (100%)
  - Installing zendframework/zend-router (3.0.2): Downloading (100%)
  - Installing zendframework/zend-config (2.6.0): Downloading (100%)
  - Installing zendframework/zend-modulemanager (2.8.1): Downloading (100%)
  - Installing zendframework/zend-mvc (3.1.1): Downloading (100%)
  - Installing zendframework/zend-dom (2.6.0): Downloading (100%)
  - Installing zendframework/zend-console (2.6.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/global-state (2.0.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing sebastian/environment (3.1.0): Downloading (100%)
  - Installing sebastian/diff (2.0.1): Downloading (100%)
  - Installing sebastian/comparator (2.1.0): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (4.0.4): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.2): Downloading (100%)
  - Installing theseer/tokenizer (1.1.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (2.0.1): Downloading (100%)
  - Installing phpunit/php-code-coverage (5.2.3): Downloading (100%)
  - Installing webmozart/assert (1.2.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (4.1.1): Downloading (100%)
  - Installing phpspec/prophecy (1.7.3): Downloading (100%)
  - Installing phar-io/version (1.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.1): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing phpunit/phpunit (6.4.4): Downloading (100%)
  - Installing zendframework/zend-test (3.1.1): Downloading (100%)
  - Installing zendframework/zend-tag (2.6.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing http-interop/http-middleware (0.2.0): Downloading (100%)
  - Installing zendframework/zend-stratigility (1.3.3): Downloading (100%)
  - Installing zendframework/zend-soap (2.6.0): Downloading (100%)
  - Installing zendframework/zend-session (2.8.0): Downloading (100%)
  - Installing zendframework/zend-di (2.6.1): Downloading (100%)
  - Installing zendframework/zend-servicemanager-di (1.1.1): Downloading (100%)
  - Installing zendframework/zend-serializer (2.8.1): Downloading (100%)
  - Installing zendframework/zend-diactoros (1.6.1): Downloading (100%)
  - Installing zendframework/zend-psr7bridge (0.2.2): Downloading (100%)
  - Installing zendframework/zend-progressbar (2.5.2): Downloading (100%)
  - Installing zendframework/zend-permissions-rbac (2.5.1): Downloading (100%)
  - Installing zendframework/zend-permissions-acl (2.6.0): Downloading (100%)
  - Installing zendframework/zend-paginator (2.8.0): Downloading (100%)
  - Installing zendframework/zend-navigation (2.8.2): Downloading (100%)
  - Installing zendframework/zend-mvc-plugin-prg (1.0.0): Downloading (100%)
  - Installing zendframework/zend-authentication (2.5.3): Downloading (100%)
  - Installing zendframework/zend-mvc-plugin-identity (1.0.0): Downloading (100%)
  - Installing zendframework/zend-mvc-plugin-flashmessenger (1.0.0): Downloading (100%)
  - Installing zendframework/zend-filter (2.7.2): Downloading (100%)
  - Installing zendframework/zend-inputfilter (2.7.5): Downloading (100%)
  - Installing zendframework/zend-hydrator (2.3.1): Downloading (100%)
  - Installing zendframework/zend-form (2.10.2): Downloading (100%)
  - Installing zendframework/zend-mvc-plugin-fileprg (1.0.0): Downloading (100%)
  - Installing zendframework/zend-i18n (2.7.4): Downloading (100%)
  - Installing zendframework/zend-mvc-i18n (1.0.0): Downloading (100%)
  - Installing zendframework/zend-mvc-console (1.1.11): Downloading (100%)
  - Installing zendframework/zend-mime (2.6.1): Downloading (100%)
  - Installing zendframework/zend-memory (2.5.2): Downloading (100%)
  - Installing zendframework/zend-mail (2.8.0): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing zendframework/zend-log (2.9.2): Downloading (100%)
  - Installing zendframework/zend-json-server (3.0.0): Downloading (100%)
  - Installing zendframework/zend-i18n-resources (2.5.2): Downloading (100%)
  - Installing zendframework/zend-file (2.7.1): Downloading (100%)
  - Installing zendframework/zend-feed (2.8.0): Downloading (100%)
  - Installing zendframework/zend-debug (2.5.1): Downloading (100%)
  - Installing zendframework/zend-db (2.8.2): Downloading (100%)
  - Installing zendframework/zend-crypt (3.2.1): Downloading (100%)
  - Installing zendframework/zend-captcha (2.7.1): Downloading (100%)
  - Installing zendframework/zend-cache (2.7.2): Downloading (100%)
  - Installing zendframework/zend-barcode (2.6.0): Downloading (100%)
zendframework/zend-code suggests installing doctrine/annotations (Doctrine\Common\Annotations >=1.0 for annotation features)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
zendframework/zend-math suggests installing ext-gmp (If using the gmp functionality)
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 1.* to handle lazy initialization of services)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
zendframework/zend-session suggests installing mongodb/mongodb (If you want to use the MongoDB session save handler)
zendframework/zend-authentication suggests installing zendframework/zend-ldap (Zend\Ldap component)
zendframework/zend-form suggests installing zendframework/zendservice-recaptcha (in order to use the ReCaptcha form element)
zendframework/zend-i18n suggests installing ext-intl (Required for most features of Zend\I18n; included in default builds of PHP)
zendframework/zend-mail suggests installing ext-intl (Handle IDN in AddressList hostnames)
zendframework/zend-log suggests installing ext-mongo (mongo extension to use Mongo writer)
zendframework/zend-log suggests installing ext-mongodb (mongodb extension to use MongoDB writer)
zendframework/zend-debug suggests installing ext/xdebug (XDebug, for better backtrace output)
zendframework/zend-captcha suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha component)
zendframework/zend-cache suggests installing ext-apc (APC or compatible extension, to use the APC storage adapter)
zendframework/zend-cache suggests installing ext-apcu (APCU >= 5.1.0, to use the APCu storage adapter)
zendframework/zend-cache suggests installing ext-dba (DBA, to use the DBA storage adapter)
zendframework/zend-cache suggests installing ext-memcache (Memcache >= 2.0.0 to use the Memcache storage adapter)
zendframework/zend-cache suggests installing ext-memcached (Memcached >= 1.0.0 to use the Memcached storage adapter)
zendframework/zend-cache suggests installing ext-mongo (Mongo, to use MongoDb storage adapter)
zendframework/zend-cache suggests installing ext-redis (Redis, to use Redis storage adapter)
zendframework/zend-cache suggests installing ext-wincache (WinCache, to use the WinCache storage adapter)
zendframework/zend-cache suggests installing ext-xcache (XCache, to use the XCache storage adapter)
zendframework/zend-cache suggests installing mongofill/mongofill (Alternative to ext-mongo - a pure PHP implementation designed as a drop in replacement)
zendframework/zend-barcode suggests installing zendframework/zendpdf (ZendPdf component)
zendframework/zendframework suggests installing zendframework/zend-ldap (zend-ldap component ^2.7.1, if you need LDAP features)
Package http-interop/http-middleware is abandoned, you should avoid using it. Use http-interop/http-server-middleware instead.
Writing lock file
Generating autoload files

**Comment by NanaAruga** [comment]
■Zendframeworkインストール（２）
https://framework.zend.com/downloads
の記載に従って実行

composer require zendframework/zend-mvc

実行結果：

C:\xampp\htdocs>composer require zendframework/zend-mvc
Using version ^3.1 for zendframework/zend-mvc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package http-interop/http-middleware is abandoned, you should avoid using it. Use http-interop/http-server-middleware instead.
Writing lock file
Generating autoload files

**Comment by NanaAruga** [comment]
■アンインストールして、再インストール（Composer）

> Setup has changed your environment, but not all running programs will be aware of this. To use Composer fot the first time, you will have to do one of the following;
> 
> ・Open a new command windows.
> ・Close all File Explorer windows, then open a new command windows.
> ・Logoff and Logon again, then open a new command windows.
> 

のメッセージがインストール完了時に表示された。

**Comment by knokmki612** [comment]
https://framework.zend.com/manual/2.4/en/index.html

**Comment by NanaAruga** [comment]
■追加でパッケージをインストールしようとした。

実行コマンド：
composer require zendframework/zend-expressive

結果：
> Using version ^2.0 for zendframework/zend-expressive
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - zendframework/zend-stratigility 2.0.1 requires http-interop/http-middleware ^0.4.1 -> satisfiable by http-interop/http-middleware[0.4.1].
>     - zendframework/zend-expressive 2.0.5 requires http-interop/http-middleware ^0.4.1 -> satisfiable by http-interop/http-middleware[0.4.1].
>     - Conclusion: don't install http-interop/http-middleware 0.4.1
>     - Conclusion: don't install zendframework/zend-expressive 2.0.4
>     - Conclusion: don't install zendframework/zend-expressive 2.0.3
>     - Conclusion: don't install zendframework/zend-expressive 2.0.2
>     - Conclusion: don't install zendframework/zend-expressive 2.0.1
>     - Conclusion: remove zendframework/zend-stratigility 1.3.3
>     - Installation request for http-interop/http-middleware (locked at 0.2.0) -> satisfiable by http-interop/http-middleware[0.2.0].
>     - Installation request for zendframework/zend-expressive ^2.0 -> satisfiable by zendframework/zend-expressive[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
>     - Conclusion: don't install zendframework/zend-stratigility 1.3.3
>     - zendframework/zend-expressive 2.0.0 requires zendframework/zend-stratigility ^2.0.1 -> satisfiable by zendframework/zend-stratigility[2.0.1, 2.1.0, 2.1.1, 2.1.2].
>     - Can only install one of: zendframework/zend-stratigility[2.1.0, 1.3.3].
>     - Can only install one of: zendframework/zend-stratigility[2.1.1, 1.3.3].
>     - Can only install one of: zendframework/zend-stratigility[2.1.2, 1.3.3].
>     - Installation request for zendframework/zend-stratigility (locked at 1.3.3) -> satisfiable by zendframework/zend-stratigility[1.3.3].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by NanaAruga** [comment]
■報告したい内容（ざっくり日本語）

PHP 7.0.18環境でコンポーネントのインストールに失敗した。（zend-expressive-authentication-basic）

$ composer require zendframework/zend-expressive-authentication-basic
を実行したところ

>   [InvalidArgumentException]
>   Could not find package zendframework/zend-expressive-authentication-basic at any version matching your PHP version 7.0.18.0
> 
> 
> require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

という結果になった。

[version]
PHP：7.0.18
OS：Windows 10

**Comment by NanaAruga** [comment]
■英訳
Installation failed

[Execution]
composer require zendframework/zend-expressive-authentication-basic

[Execution environment]
PHP：7.0.18
OS：Windows 10

[Execution result]
  [InvalidArgumentException]
  Could not find package zendframework/zend-expressive-authentication-basic at any version matching your PHP version 7.0.18.0


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by knokmki612** [comment]
おつかれさまでした！このページは一旦closeしますが、このまま作業を続けても大丈夫です！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ: 
* 1月27日: 東京ワークショップ: 

12月の東京ミートアップに私も参加するので、もしよかったらミートアップで続きをするのも良いかもしれません！
今後もOSS Gateのイベントは開催されるので、是非また参加してみてください！
