### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: s-yama: fluentd: Work log

### ISSUE THREAD

**Issue by rtusys** [oss-gate/workshop#673]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by okkez** [comment]
よろしくおねがいします！

**Comment by rtusys** [comment]
nginxのltsv形式のlogをfluentdで使うために
nginxをインストール
`$ brew install nginx`
```
s-yamane-mac:~ s-yamane$ nginx -v
nginx version: nginx/1.12.2
```

**Comment by kaacun** [comment]
よろしくおねがいします！

**Comment by kanakumagai** [comment]
よろしくお願いいたします:bow:

**Comment by rtusys** [comment]
nginxの設定をする
`$ vim /usr/local/etc/nginx/nginx.conf`
以下を記述
```
log_format ltsv     "time:$time_iso8601"
                        "\thost:$remote_addr"
                        "\tforwardedfor:$http_x_forwarded_for"
                        "\treq:$request"
                        "\tstatus:$status"
                        "\tsize:$body_bytes_sent"
                        "\treferer:$http_referer"
                        "\tua:$http_user_agent"
                        "\treqtime:$request_time"
                        "\tcache:$upstream_http_x_cache"
                        "\truntime:$upstream_http_x_runtime"
                        "\tapptime:$upstream_response_time"
                        "\tvhost:$host"
                        "\tmethod:$request_method"
                        "\turi:$request_uri";
```

**Comment by rtusys** [comment]
access logの形式を指定
`access_log  logs/access.log  ltsv;`

**Comment by rtusys** [comment]
nginxを起動するために
`$ brew services start nginx`
すると、エラーになる。
```
$ nginx -t
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: [emerg] open() "/usr/local/Cellar/nginx/1.12.2_1/logs/access.log" failed (2: No such file or directory)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```
とのことなので、
`$ mkdir /usr/local/Cellar/nginx/1.12.2_1/logs`

**Comment by rtusys** [comment]
起動とlogを確認するために `localhost:8080` にアクセス
```
s-yamane-mac:~ s-yamane$ tail -f /usr/local/Cellar/nginx/1.12.2_1/logs/access.log
time:2017-11-25T11:30:31+09:00	host:127.0.0.1	forwardedfor:-	req:GET / HTTP/1.1	status:200	size:612	referer:-	ua:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36	reqtime:0.000	cache:-	runtime:-	apptime:-	vhost:localhost	method:GET	uri:/
time:2017-11-25T11:30:32+09:00	host:127.0.0.1	forwardedfor:-	req:GET /favicon.ico HTTP/1.1	status:404	size:571	referer:http://localhost:8080/	ua:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36	reqtime:0.000	cache:-	runtime:-	apptime:-	vhost:localhost	method:GET	uri:/favicon.ico
```
OK

**Comment by rtusys** [comment]
nginxはちゃんと動いているので、
Fluentdの設定を始める

**Comment by rtusys** [comment]
公式ページを探すために、「Fluentd」で検索
トップに公式ページを発見

**Comment by rtusys** [comment]
まずはOSSかどうかを確認するために、
公式ページのフッターからgithubにアクセス
issuesのページに飛ぶので、Codeに移動
README.mdに「License」記述を発見
https://github.com/fluent/fluentd#more-information

[License: Apache License, Version 2.0] だったので大丈夫

**Comment by rtusys** [comment]
インストールするために
まずはこれを読む
https://docs.fluentd.org/v0.14/articles/quickstart

**Comment by rtusys** [comment]
Step1: Installing FluentdにMac用の手順がなかったので、
[Install Fluentd from source](https://docs.fluentd.org/v0.14/articles/install-from-source)の方法でやってみる

**Comment by rtusys** [comment]
とりあえず手順に沿って
`$ git clone https://github.com/fluent/fluentd.git`

**Comment by rtusys** [comment]
Install Fluentd from source(https://docs.fluentd.org/v0.14/articles/install-from-source)によると
`“master” branch is now for v0.14 development.`
とのことなのでmasterブランチで作業していく

**Comment by rtusys** [comment]
[Install Fluentd from source](https://docs.fluentd.org/v0.14/articles/install-from-source) に沿って
`bundle install`
```
An error occurred while installing cool.io (1.5.3), and Bundler cannot continue.
Make sure that `gem install cool.io -v '1.5.3'` succeeds before bundling.
```
というエラーが発生
`$ vim mkmf.log` でlogを見ると
```
1: #include "ruby.h"
```
ruby.hが読み込めない。

**Comment by rtusys** [comment]
command line toolsをインストールしてない(Macを最近初期化した)ことを思い出して、インストールするために、以下へアクセス
https://developer.apple.com/download/more/

ログインして、「Command Line Tools」で検索
10.13用のインストーラーをDLしてインストール

**Comment by rtusys** [comment]
インストールが終わったので、再度 `$ bundle install`
無事通った

**Comment by rtusys** [comment]
[Install Fluentd from source](https://docs.fluentd.org/v0.14/articles/install-from-source) に沿って
`$ bundle exec rake build`

**Comment by rtusys** [comment]
[Install Fluentd from source](https://docs.fluentd.org/v0.14/articles/install-from-source) に沿って
xxxを部分を「0.14.24」に書き換えてgem install
`$ gem install pkg/fluentd-0.14.24.gem`

**Comment by rtusys** [comment]
成功
```
s-yamane-mac:fluentd s-yamane (master=)$ gem install pkg/fluentd-0.14.24.gem
Successfully installed fluentd-0.14.24
Parsing documentation for fluentd-0.14.24
Installing ri documentation for fluentd-0.14.24
Done installing documentation for fluentd after 10 seconds
1 gem installed
```

**Comment by rtusys** [comment]
[Install Fluentd by Ruby Gem](https://docs.fluentd.org/v0.14/articles/install-by-gem)
[Install Fluentd from source](https://docs.fluentd.org/v0.14/articles/install-from-source)
2つの手順にほとんど差がない。。
buildされてるgemをインストールするか、
sourceからgemをbuildしてインストールするかの違いしかない

**Comment by rtusys** [comment]
[Install Fluentd from source](https://docs.fluentd.org/v0.14/articles/install-from-source) 
Step-4: Run に進む

`$ fluentd --setup ./fluent`
`$ fluentd -c ./fluent/fluent.conf -vv &`
なんかいっぱいログが出る。

**Comment by rtusys** [comment]
`$ echo '{"json":"message"}' | fluent-cat debug.test`
すると
`$ fluentd -c ./fluent/fluent.conf -vv &` で出てきてたログに以下が出現
```
2017-11-25 12:15:27.068017000 +0900 debug.test: {"json":"message"}
```

**Comment by rtusys** [comment]
`$ fluentd -c ./fluent/fluent.conf -vv &` が何をしているかわからない(ビルドのログが出てる？とか思っちゃう)ので、
`$ echo '{"json":"message"}' | fluent-cat debug.test` これをいつやったらいいのか？別のターミナルからやるのか？ぱっと見不明。

書いといてほしい。

**Comment by rtusys** [comment]
殺し方が書いてなくて困る

**Comment by rtusys** [comment]
フッターの最下部にライセンスの記述があった。
もっと目立たせてくれても良くない？

**Comment by rtusys** [comment]
* Macの場合、 https://docs.fluentd.org/v0.14/articles/quickstart のどの方法が推奨されるのか知りたい。
  * そのページに、Command_Line_Toolsが必要だよ的な一言があると優しい。
  * Command_Line_Tools_macOS_10.13_for_Xcode_9.2_Beta.dmg での実行も可能なことを確認した。

* https://docs.fluentd.org/v0.14/articles/install-from-source と https://docs.fluentd.org/v0.14/articles/install-by-gem このページの `Run` の記述を変更した方が良いと思う。

現在の内容
```
$ fluentd --setup ./fluent
$ fluentd -c ./fluent/fluent.conf -vv &
$ echo '{"json":"message"}' | fluent-cat debug.test
``` 

* `$ fluentd -c ./fluent/fluent.conf -vv &` を実行すると何が表示されているのか？
* `$ echo '{"json":"message"}' | fluent-cat debug.test` はいつ実行するべきなのか？
* `&` を指定しているので、fluentdのプロセスを終了させる方法まで記述して欲しい。

**Comment by okkez** [comment]
https://github.com/fluent/fluentd-website

**Comment by okkez** [comment]
https://github.com/fluent/fluentd-docs

**Comment by rtusys** [comment]
日本語
ソース
英語
diff / PR

**Comment by rtusys** [comment]
QuickStartの変更について  
install-from-source.txt, install-by-gem.txt のRunの記述
* 現在の内容
```
$ fluentd --setup ./fluent
$ fluentd -c ./fluent/fluent.conf -vv &
$ echo '{"json":"message"}' | fluent-cat debug.test
``` 

* `$ fluentd -c ./fluent/fluent.conf -vv &`
  * 実行した時、ビルド中？いつ終わるの？となってしまった。
  * ログが出始めたら次に進んで良いことを明記したら良い。
  * `&` を指定しているので、fluentdのプロセスを終了させる方法まで記述して欲しい。
    * `$ pkill -f fluentd`

**Comment by rtusys** [comment]
PRタイトル
QuickStartの実行例の改善

**Comment by rtusys** [comment]
QuickStartの実行例の改善

実行例の `$ fluentd -c ./fluent/fluent.conf -vv &` の説明追加が必要。
初心者の自分で実行した時、ビルド中？いつ終わるの？となってしまった。
ログが出始めたら次に進んで良いことを明記したら良い。

最後に、Ctrl+Cだとプロセスが終わらないので、終了方法まで明記した方が良い。
例として`$ pkill -f fluentd`

**Comment by rtusys** [comment]
We can improve Run example.

We can add explanation of `$ fluentd -c ./fluent/fluent.conf -vv &`. When I run this command, I confused because this logs show me what? Is this building now? So, we promote users to next step.

Finally, We can't stop fluentd process by `Ctrl + C`. Let's write how to exit.
For example `$ pkill -f fluentd`

**Comment by rtusys** [comment]
PR送信しました。
https://github.com/fluent/fluentd-docs/pull/346

**Comment by knokmki612** [comment]
おつかれさまでした！

今後の `$ fluentd -c ./fluent/fluent.conf -vv &.` シェルの操作の知識で悩む必要がなくなって、とても意義深いと思いました！

**Comment by knokmki612** [comment]
PRマージされてましたね！良かったです！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ: 
* 1月27日: 東京ワークショップ: 

今後もOSS Gateのイベントは開催されるので、是非また参加してみてください！
