### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: ishimoto-ttt: DropzoneJS: Work log

### ISSUE THREAD

**Issue by ishimoto-ttt** [oss-gate/workshop#674]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by swamp09** [comment]
サポーターの沼田です。
よろしくお願いします！

**Comment by ishimoto-ttt** [comment]
公式ドキュメント見つけました。
https://github.com/webarata3/jQuery-file-upload
内容を確認します。

**Comment by ishimoto-ttt** [comment]
ライセンスの確認
README.mdの最下部に「MIT」と書いてあるので大丈夫。

**Comment by ishimoto-ttt** [comment]
jQueryのバージョンの確認
公式最新：3.2.1
プラグイン：3.1.0

最新版には対応してなさそうだけど、それほど古くもない。

**Comment by ishimoto-ttt** [comment]
バグ情報の確認
https://github.com/webarata3/jQuery-file-upload/issues
「作り直す」と1月上旬に書いたっきり特に更新がない

**Comment by ishimoto-ttt** [comment]
メンテナンスされてなさそうなので、変更します。
jQuery.file-upload
↓
DropzoneJS

**Comment by ishimoto-ttt** [comment]
公式サイトの確認
http://www.dropzonejs.com/
英語サイトみたい

**Comment by ishimoto-ttt** [comment]
ライセンスの確認
最下部に「MIT」と書いてあるので大丈夫！

**Comment by ishimoto-ttt** [comment]
サンプルページの確認
http://www.dropzonejs.com/examples/simple.html
取り消しボタンでエラーが出ているのは、簡易実装だから？

**Comment by ishimoto-ttt** [comment]
Installationをやってみます
GitLabからダウンロード
https://gitlab.com/meno/dropzone/-/jobs/38032186/artifacts/file/dist/dropzone.js

**Comment by okkez** [comment]
https://gitlab.com/meno/dropzone/blob/master/website/examples/simple.html

**Comment by ishimoto-ttt** [comment]
リンクの誘導が不適切
https://gitlab.com/meno/dropzone

■見出し
Examples
■現状
リンクでたらい回しにされている
①GitLab→②GitHub→③GitLab
■期待
①→③で遷移できる

**Comment by ishimoto-ttt** [comment]
リンク切れ？
https://gitlab.com/meno/dropzone
■見出し
Server side implementation
■対象URL
NodeJS with express(https://howtonode.org/really-simple-file-uploads)
■事象
Internal Server Error

**Comment by ishimoto-ttt** [comment]
リンク切れ2
https://gitlab.com/meno/dropzone
■見出し
Why another library?
■対象URL
I realize that there are←「are」(https://www.valums.com/)
■事象
Andris Valums
Software developer
Email: andrew (at) last name.com

**Comment by ishimoto-ttt** [comment]
A link is broken as well as "GitHub Wiki" and it

README.md

I want you to revise a link.

L 50
L 171
L 569
L 669

**Comment by ishimoto-ttt** [comment]
A link is broken as well as "GitHub Wiki" and it

README.md

①I want you to revise it from "GitHub" to a link of "GitLab".
L 50
L 569

②I want an accessible link to revise it.
L 171
L 669

**Comment by knokmki612** [comment]
おつかれさまでした！
このissueは一旦クローズしますが、引き続き作業にこちらのissueを使っても大丈夫です！
ミートアップでこの作業の続きをするのも良いかもしれません！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ 
* 1月27日: 東京ワークショップ

是非よかったらまた参加してみてください！
