### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: y-imaida: redmine_didyoumean: Work log

### ISSUE THREAD

**Issue by y-imaida** [oss-gate/workshop#675]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by y-imaida** [comment]
プラグインをインストールするためにGitHubのreadmeを確認した。
https://github.com/abahgat/redmine_didyoumean

**Comment by y-imaida** [comment]
プラグインの前提条件としてsphinxsearchをインストールする必要があるためその手順を確認した。
（readmeにはaptパッケージの記載しかなかったが、自分の環境がRHELであるため）
https://support.helpspot.com/index.php?pg=kb.page&id=480

**Comment by y-imaida** [comment]
redmine_didyoumeanのライセンスがGNU GPL v2であることを確認した。
readmeの「License」欄に記載あり
https://github.com/abahgat/redmine_didyoumean

**Comment by y-imaida** [comment]
sphinxsearchのインストールガイドに従って以下のコマンドを実行した。

# curl -L -o sphinx-2.2.6-1.rhel7.x86_64.rpm \
    http://sphinxsearch.com/files/sphinx-2.2.6-1.rhel7.x86_64.rpm
# yum install ./sphinx-2.2.6-1.rhel7.x86_64.rpm

**Comment by y-imaida** [comment]
sphinxsearchパッケージのインストールは正常に完了した

**Comment by y-imaida** [comment]
OS起動時にsearchdデーモンの起動設定を変更した。

```
# chkconfig searchd on
```

**Comment by y-imaida** [comment]
RHEL7でのsearchd起動設定の方法を確認するためsystemctl上のサービス一覧を確認したが、searchdに該当するサービス名を確認することができなかった

```
# systemctl list-unit-files -t service
```

**Comment by y-imaida** [comment]
RHEL7でsphinx

**Comment by y-imaida** [comment]
RHEL7環境ではchkconfigではなくsystemctlを使わなければいけないと思い込んでいたがガイドに記載されているとおりchkconfigコマンドで設定することができた。

**Comment by y-imaida** [comment]
didyoumeanプラグインをインストールするため以下のコマンドを実行

```
# cd /var/lib/redmine
# bundle exec rake ts:index
# bundle exec rake ts;start
```

**Comment by y-imaida** [comment]
bundleコマンドがインストールされていないためプラグインのインストールに失敗した

**Comment by y-imaida** [comment]
rootユーザーへスイッチする際に "sudo -s"ではなく、"sudo su -"とすることでbundleコマンドは実行できるようになった。
ただし、以下のエラーが出力されて "bundle exec rake ts:index"コマンドがエラーとなった。

```
# bundle exec rake ts:index
/var/lib/redmine/vendor/bundle/ruby/2.3.0/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: key "inodot" is duplicated and overwritten on line 466
rake aborted!
Don't know how to build task 'ts:index' (see --tasks)

(See full trace by running task with --trace)
```

**Comment by y-imaida** [comment]
エラーとなる原因をエラーメッセージを元にして検索した。

**Comment by y-imaida** [comment]
プラグインの前提となるライブラリの条件などをreadmeから確認したが記載がなかった

**Comment by y-imaida** [comment]
htmlentitiesのバージョン4.3.3で修正されているとのIssueがあった。

https://github.com/threedaymonk/htmlentities/issues/27

**Comment by y-imaida** [comment]
Gemfileを修正することで解決できるとの情報があった

http://www.redmine.org/issues/24271

**Comment by y-imaida** [comment]
Gemfileを修正後に再度 "bundle exec rake ts:index" を実行した結果、以下のエラーとなった。

```
# bundle exec rake ts:index
Could not find gem 'rbpdf (~> 1.19.1)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```

**Comment by y-imaida** [comment]
メッセージの内容にしたがって "bundle install" を実行した

**Comment by y-imaida** [comment]
再度 "bundle exec rake ts:index" を実行した結果、以下のエラーとなった。

```
# bundle exec rake ts:index
rake aborted!
Don't know how to build task 'ts:index' (see --tasks)

(See full trace by running task with --trace)
```

**Comment by knokmki612** [comment]
午前中おつかれさまでした！

1. "bundle exec rake ts:index" が動かない現象の解決方法がわかる
2. 原因がご自分のRedmineの環境にあるのか、didyoumeanのGemfileにあるのかがわかる
3. 適切な場所に"redmine_didyoumean"で"bundle exec rake ts:index" が動かない現象をレポートする

という流れなのかなと思いました！

**Comment by y-imaida** [comment]
そもそもプラグインのソースコードをサーバー上にクローンしていなかったことに気づいたため、クローンした後に再度手順を実行する

**Comment by y-imaida** [comment]
再度実行した結果以下のメッセージが出力されてエラーとなった。
MySQLへ接続する処理でエラーとなっているものと思われる。
自分の環境ではPostgreSQLを利用しているためMySQLの環境での確認が必要。

```
# bundle exec rake ts:index
rake aborted!
Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
/var/lib/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/var/lib/redmine/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/var/lib/redmine/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
＜以下省略＞
```

**Comment by y-imaida** [comment]
READMEの修正内容についてPullRequestを作成した

https://github.com/abahgat/redmine_didyoumean/pull/84

**Comment by kenhys** [comment]
お疲れ様でした。
フィードバックの取り組みをこれからも続けていってください！

**Comment by knokmki612** [comment]
おつかれさまでした！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ 
* 1月27日: 東京ワークショップ

是非よかったらまた参加してみてください！
