### ISSUE TITLE
 OSS Gate Workshop: Tokyo: 2017-11-25: takuya-kodama: nezumi: Work log

### ISSUE THREAD

**Issue by takuya-kodama** [oss-gate/workshop#676]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${TOKYO}: ${2017}-${11}-${25}: ${takuya-kodama}: ${nezumi}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by takuya-kodama** [comment]
ライセンスを確認　MITと記載されていたので問題なし。

**Comment by takuya-kodama** [comment]
ソースコードを読みます！

**Comment by takuya-kodama** [comment]
chromeにインストールして使ってみます。

**Comment by takuya-kodama** [comment]
公式サイトのUsageを見て使い方を確認

**Comment by takuya-kodama** [comment]
マイナビの[登録フォーム](https://tenshoku.mynavi.jp/centuserset/)で使ってみる

**Comment by takuya-kodama** [comment]
こちらが公式のURLです。
https://github.com/mugi-uno/nezumi

**Comment by takuya-kodama** [comment]
使ってみるとこんな感じ
<img width="1433" alt="2017-11-25 11 42 44" src="https://user-images.githubusercontent.com/21953622/33226630-d338b878-d1d5-11e7-83e7-c03775b2b533.png">

**Comment by takuya-kodama** [comment]
コピーしたコードがこちら
```
visit '/centuserset/'
visit '/centuserset/'
visit '/2017/10/nezumi-google-chrome%e3%81%ae%e3%83%95%e3%82%a9%e3%83%bc%e3%83%a0%e5%85%a5%e5%8a%9b%e3%81%8b%e3%82%89capybararspec%e5%af%be%e5%bf%9c%e3%81%ae%e3%83%86%e3%82%b9%e3%83%88%e3%82%b3%e3%83%bc%e3%83%89/'
visit '/centuserset/'
visit '/mugi-uno/nezumi'
find(:xpath, 'id("content")/div[@class="infoDetailScreen"]/form[1]/div[@class="grid"]/div[@class="form_table_entry"]/div[@class="tableBlock"]/table[@class="table mb15"]/tbody[1]/tr[@class=" input-row"]/td[1]/dl[@class="name"]/dd[1]/input[@class="inputTxt"]').set('テスト')
find(:xpath, 'id("content")/div[@class="infoDetailScreen"]/form[1]/div[@class="grid"]/div[@class="form_table_entry"]/div[@class="tableBlock"]/table[@class="table mb15"]/tbody[1]/tr[@class=" input-row"]/td[1]/dl[@class="name"]/dd[2]/input[@class="inputTxt"]').set('テスト')
fill_in 'birthYear', with: '2017'
find('span', text: /\A月\z/).click
fill_in 'birthMonth', with: '3'
fill_in 'birthDay', with: '9'
find(:xpath, 'id("content")/div[@class="infoDetailScreen"]/form[1]/div[@class="grid"]/div[@class="form_table_entry"]/div[@class="tableBlock"]/table[@class="table mb15"]/tbody[1]/tr[@class=" input-row"]/td[1]').click
check '男性'
fill_in 'login_id', with: 'test@test'
find_by_id('password').click
uncheck 'スカウトサービスを利用する'
fill_in 'password', with: '1111'
fill_in 'password_check', with: '1111'
find(:xpath, 'id("site_sister")/td[1]').click
uncheck '転職エージェントの非公開求人をチェックする（マイナビ転職エージェントサーチにも同時会員登録）'
find_by_id('birthMonth').click
```

**Comment by takuya-kodama** [comment]
実際にgenerateしたものをコピーするだけで、テストコードとして使えるのか気になるので新しいアプリケーションを作成して確認して見ます！

**Comment by takuya-kodama** [comment]
テストで使うためのサンプルフォームを作成中

**Comment by takuya-kodama** [comment]
text formの場合
- find(:xpath ~
- fill_in '', with: ''
のどちらかが生成されるが、選べたら良いなー

**Comment by knokmki612** [comment]
午前中お疲れ様でした！

* nezumiのリポジトリ自体の説明(ディレクトリごとの内容など)
* 動作(ビルド？)に必要なツールのバージョンの明記

などされていると良いかなという話でした！
動作するツールのバージョンについて、「自分はこのバージョンで動いたけど、どのバージョンから動く？」みたいな感じでissueで開発者に聞いてみて、そのごドキュメントに反映されると良さそうだと思いました！

**Comment by takuya-kodama** [comment]
検討中のフィードバック
- テストの動作に必要なツール（```gem```）, rubyのバージョンの明記
- nezumiの使い方の明記（```gif```では記載があったが、documentでもあった方がわかりやすい）
- 各repositoryの役割の明記

**Comment by takuya-kodama** [comment]
# Required version of ruby and gem files
When we use ```nezumi``` as a tool of generating test code for ```Capybara/RSpec```, it seems like that there are no description of requirements. added mention about the list of requirements to use ```nezumi``` like below , it would help us to use it easily. Thank you.

## Requirements
- Ruby 2.4.1 or higher
## The list of gem files  to use nezumi
```
  gem 'rails', '~> 5.1.4'
  gem 'capybara'
  gem 'poltergeist'
  gem 'rspec-rails'
```

**Comment by takuya-kodama** [comment]
プルリクエストを出しました。

https://github.com/mugi-uno/nezumi/pull/15

**Comment by kenhys** [comment]
お疲れ様でした。
これからもフィードバックの取り組みを続けていってください！

**Comment by knokmki612** [comment]
おつかれさまでした！
issueに質問への返信が来てますね！
このissueは一旦クローズしますが、引き続き作業にこちらのissueを使っても大丈夫です！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ 
* 1月27日: 東京ワークショップ

是非よかったらまた参加してみてください！
