### ISSUE TITLE
OSS Gate Workshop: Kumano-Ryo: 2017-12-09: myatake: Boostnote: Work log

### ISSUE THREAD

**Issue by myateke** [oss-gate/workshop#693]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by genya0407** [comment]
サポーターの三軒家です！！

**Comment by masayuki14** [comment]
進行役の森崎です！楽しんでいきましょう！

**Comment by myateke** [comment]
デスクトップ版は普段利用しているので、mobile版をみてみる。
https://github.com/BoostIO/boostnote-mobile

**Comment by myateke** [comment]
read me読みながらインストールする。

**Comment by myateke** [comment]
[Setting up React Native for Android](https://facebook.github.io/react-native/docs/android-setup.html#content)をみてみる
not foundだった。

**Comment by myateke** [comment]
https://facebook.github.io/react-native/
がオフィシャルだと思う。

**Comment by myateke** [comment]
https://facebook.github.io/react-native/docs/running-on-device-android.html#content
こちらもnot found

**Comment by myateke** [comment]
https://facebook.github.io/react-native/docs/running-on-device-ios.html#content
こちらもnot found

**Comment by myateke** [comment]
https://github.com/facebook/react-native
react-nativeのgithubをみてみる。

**Comment by myateke** [comment]
`react-native`コマンドが必要だと思うのでyarnでパッケージを検索する。
https://yarnpkg.com/ja/package/react-native
あったのでインストールする。

**Comment by myateke** [comment]
インストール実行結果
```
mbp:boostnote-mobile Masahiro$ yarn add react-native
yarn add v1.1.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native@0.51.0" has incorrect peer dependency "react@16.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 6 new dependencies.
├─ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
├─ babel-helper-explode-assignable-expression@6.24.1
├─ babel-plugin-syntax-exponentiation-operator@6.13.0
├─ babel-plugin-transform-exponentiation-operator@6.24.1
├─ metro-bundler@0.20.3
└─ react-native@0.51.0
✨  Done in 9.12s.
```

**Comment by myateke** [comment]
warningが出たが動くか試してみる

**Comment by myateke** [comment]
`react-native run-ios`の実行結果
mbp:boostnote-mobile Masahiro$ react-native run-ios
-bash: react-native: command not found
mbp:boostnote-mobile Masahiro$ 
コマンドが存在しない、とでた。

**Comment by myateke** [comment]
上記はpackage.jsonに定義していないためと思う。

**Comment by myateke** [comment]
`yarn start`で動くと期待し実行する。
結果
```
mbp:boostnote-mobile Masahiro$ yarn start
yarn run v1.1.0
$ node node_modules/react-native/local-cli/cli.js start
Scanning folders for symlinks in /Users/masahiro/boostnote-mobile/node_modules (8ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running Metro Bundler on port 8081.                                       │ 
 │                                                                            │ 
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own Metro Bundler  instance if you    │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/masahiro/boostnote-mobile 


Metro Bundler ready.

Loading dependency graph, done.
```

**Comment by myateke** [comment]
https://facebook.github.io/react-native/docs/getting-started.html#caveats
このリンク先が設定に関するドキュメントかもしれない。

**Comment by myateke** [comment]
ドキュメントによるとExpoのインストールが必要なよう。

**Comment by daddygongon** [comment]
西谷@関西学院大・理工です．よろしくお願いします．

**Comment by daddygongon** [comment]
boostnote-mobileのinstallなんだけれど，マニュアルがlink切れしてるよね．
その先のreact-nativeの定義ファイル見たナノがないので，動かない．
cloneしてきた状態で，そいつがあるといいんかな．

**Comment by myateke** [comment]
I followed the README and I found that the folloing links cannot be used. 
These are links.
```
- [Setting up React Native for Android](https://facebook.github.io/react-native/docs/android-setup.html#content)
- [Running app on Android Device](https://facebook.github.io/react-native/docs/running-on-device-android.html#content)
- [Running app on iOS Device](https://facebook.github.io/react-native/docs/running-on-device-ios.html#content)
```

**Comment by myateke** [comment]
issue 立てました。
https://github.com/BoostIO/boostnote-mobile/issues/129

**Comment by masayuki14** [comment]
お疲れ様でした。たてたIssueが修正されてますね。 お礼をそえてCloseしても良さそうです。

closeしますが、引き続きここを使っても大丈夫です！
https://gitter.im/oss-gate/devel で相談もできるのでOSS開発を継続していきましょう！

まだイベントはたってないですが、1月と3月に大阪でミートアップとワークショップを開催予定なので、よかったらまた参加してみてください！

**Comment by daddygongon** [comment]
お疲れ様でした．早速直されたようですが，まだ，masterには反映されてないようですね．
少し反応が悪いのかも．でも，おめでとうございます．OSSを使えるようにするのもこんな活動なんで，使いたかったら引き続きpushしましょう．

workshopはこれぐらいのサイズがいいですね．フォローする気がして，できて．．．

**Comment by myateke** [comment]
@masayuki14 @daddygongon @ShinjiEnoki @genya0407 
無事マージされました。
サポートありがとうございました。
