### ISSUE TITLE
 OSS Gate Workshop: Kumano-Ryo : 2017-12-09: shsm385: three.js: Work log

### ISSUE THREAD

**Issue by shsm385** [oss-gate/workshop#694]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
西谷@関西学院大・理工です．よろしくお願いします．

**Comment by genya0407** [comment]
サポーターの三軒家です！

**Comment by shsm385** [comment]
嶋田@京都産業大学・先端情報学研究科です.  よろしくお願いします.

**Comment by masayuki14** [comment]
進行役の森崎です！楽しんでいきましょう！

**Comment by shsm385** [comment]
まず, Three.jsの公式サイトに飛んで見る.
https://threejs.org/

**Comment by shsm385** [comment]
Three.js のexampleに飛んで見る.
普段使っているために, 最初の導入は省略

**Comment by shsm385** [comment]
sampleの中の intractive / lines を見てみる

**Comment by daddygongon** [comment]
interactive見ました．すごい高性能ですね．objectsにマウスポイントがoverlapすると判定して反応くれるんですね．

**Comment by shsm385** [comment]
実際いつもthree.jsを使っている際に思うのだが, 3D空間上のオブジェクトに対して当たり判定を取ってオブジェクトを出現させること等はメソッドが実装されていて簡単にできるが, オブジェクトの無い３D空間上になにかオブジェクトを出現させるといったメソッドがなく自分で射影変換等を駆使して実装しなければならないのが不便だと思う.

**Comment by daddygongon** [comment]
その記述があったサイトわかります？

**Comment by shsm385** [comment]
具体的な実装は他の方がブログ等にまとめておりますが
https://qiita.com/edo_m18/items/b8ade81f69fc3f37538e
といった形になっていたりします.

**Comment by shsm385** [comment]
もう少し具体的に実装したい内容としましては, 
マウス座標を３D空間上の座標に変換するといったメソッドが欲しいと考えます.

**Comment by daddygongon** [comment]
r88とr87でchange log

**Comment by daddygongon** [comment]
planeの中にありますかね．そんな3d空間の当たり判定．

**Comment by shsm385** [comment]
plane がありましたので中身を見てみます.

**Comment by daddygongon** [comment]
動いているので，boxをplaneに変えて動かしてみましょうか?

**Comment by shsm385** [comment]
そうですね、僕のほうでもやってみます.

**Comment by daddygongon** [comment]
よく似たコードをPlaneGeometryに発見！！

**Comment by shsm385** [comment]
Boxとplaneを同時に動かしました.

**Comment by daddygongon** [comment]
PlaneGeometry
intersectsはplaneでやる？
もう少し記述がほしいね．

**Comment by daddygongon** [comment]
JSの既約でCamelCaseなんかでclassか変数かが決まってるんでしょうね．

**Comment by shsm385** [comment]
当たり判定のとり方を実際にみるとRaycasterの中のintersectsObjectsで取得可能になるということがわかりました。

実際にメソッドで.intersectObject ( object, recursive )とobjectを与えた時にリストを取得できて
[ { distance, point, face, faceIndex, indices, object }, ... ]
といった内容になっている.
それによって原点とオブジェクトの位置関係がとれる.

実際にこれの簡単なサンプルを実装してみる.

**Comment by shsm385** [comment]
要望は出せるということを知りました

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by shsm385** [comment]
コメントまとめ

Three.jsを普段使っているものです.
その中で3D空間に関して座標をとりたいということがあり, 
THREE.Raycaster() の中の intersects.length を利用することで3Dオブジェクトに関する座標をしゅとくすることはできますが, 3D空間上のオブジェクトのない部分の座標を取りたいと考える事があり, スクリーン上のマウスポインタの位置を3D空間上の座標に変換してくれるといった機能が欲しいと思うのですが, 
そういった機能はありますでしょうか？
もし、なければ機能として実装していただけるでしょうか？

**Comment by shsm385** [comment]
Three.jsのissueに関してはバグとフューチャーリクエストに関してのみ載せて,質問に関しては
 stackoverflow に書く. 

バグを報告する際にはどのような環境かなどのチェックボックスがある.

**Comment by ShinjiEnoki** [comment]
フィーチャーリクエストも結構でてますね
https://github.com/mrdoob/three.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+Request%22
出しちゃって良いと思います！

**Comment by ShinjiEnoki** [comment]
スクリーンショットが取れるならイメージが伝わりやすいとは思います

**Comment by shsm385** [comment]
In development I would like to take 3D spatial coordinates.
By using intersects.length with THREE.Raycaster () you can get the mouse coordinates of the 3D object.

However, from the coordinates of the mouse, I want to obtain the spatial coordinates without objects in 3D space.

Therefore, we need a function to convert the position of the mouse pointer on the screen to the coordinates in 3D space.

**Comment by ShinjiEnoki** [comment]
コントリビュータのガイドライン
https://github.com/mrdoob/three.js/blob/dev/.github/CONTRIBUTING.md

**Comment by ShinjiEnoki** [comment]
お疲れ様です！
https://github.com/mrdoob/three.js/issues/12841

**Comment by shsm385** [comment]
ありがとうございます

**Comment by masayuki14** [comment]
お疲れ様でした。たてたIssueに回答がありますね！

closeしますが、引き続きここを使っても大丈夫です！
https://gitter.im/oss-gate/devel で相談もできるのでOSS開発を継続していきましょう！

まだイベントはたってないですが、1月と3月に大阪でミートアップとワークショップを開催予定なので、よかったらまた参加してみてください！

**Comment by daddygongon** [comment]
お疲れ様でした．課題を解決するのに使えそうな回答で，良かったですね．
お礼を言っとくといいかも．．
