### ISSUE TITLE
OSS Gate Workshop: Kumano-Ryo: 2017-12-09: masa-matsu: tensorflow: Work log

### ISSUE THREAD

**Issue by masa-matsu** [oss-gate/workshop#695]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by genya0407** [comment]
サポーターの三軒家です！！

**Comment by masa-matsu** [comment]
github で master から folk した

**Comment by masayuki14** [comment]
進行役の森崎です！楽しんでいきましょう！

**Comment by masa-matsu** [comment]
tensorflow stable branch をググった

**Comment by masa-matsu** [comment]
https://www.tensorflow.org/versions/ をみて、最新より一つ古いバージョン(r1.3)にする

**Comment by masa-matsu** [comment]
tensorflow/tensorflow.git をgithub から clone した

**Comment by masa-matsu** [comment]
github から Readme を確認開始、英語。

**Comment by masa-matsu** [comment]
Installing guid を発見
https://www.tensorflow.org/install/
ビルド済みの実効環境もあった。

**Comment by masa-matsu** [comment]
https://www.tensorflow.org/install/install_windows
CPU のみか、GPU がオプション→ノートPCにNVDIA載ってないので
TensorFlow with CPU support only を選択
インストール手段は、pip か anaconda があるうち、pip を選択

CPU+pip で。

**Comment by masa-matsu** [comment]
上記リンクを読み進める

* pip 
** if you install with native pip, users can run TensorFlow programs from any directory on the system.」
* conda
** In Anaconda, you may use conda to create a virtual environment. However, within Anaconda, we recommend installing TensorFlow with the pip install command, not with the conda install command.

インストール後と動作保証の面からやっぱりpip がよさそう

**Comment by masa-matsu** [comment]
自前のPCのPython バージョンに合わせて
Python 3.6.x 64-bit from python.org を選択

**Comment by masa-matsu** [comment]
上はPython のバージョンでした、、、。
パッケージは続く、解説による、PIP で引っ張ってくる
$ pip3 install --upgrade tensorflow

**Comment by masa-matsu** [comment]
pip3 が動かなかったので、conda に切り替える。
$ conda create -n tensorflow python=3.5
Python のバージョンは 3.5 が指定というわけでなさそうので、3.6 で試す。

**Comment by masa-matsu** [comment]
$ conda が、常用のterminal で動かない(パスが通ってない？)
anaconda prompt を使うことにする。

**Comment by masa-matsu** [comment]
$ conda create -n tensorflow python=3.5
$ activate tensorflow
$ pip install --ignore-installed --upgrade tensorflow 

上二つは環境設定、最終行でインストール
pip でのインストールをし忘れる。

**Comment by masa-matsu** [comment]
python shell で以下を実行
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> sess = tf.Session()
2017-12-09 14:40:30.316002: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
>>> print(sess.run(hello))
b'Hello, TensorFlow!'

うごいたけど、sess = tf.Session() に続くメッセージが気になる。後で確認。

**Comment by masa-matsu** [comment]
Getting Started を読み出す
https://www.tensorflow.org/get_started/get_started

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by masa-matsu** [comment]
こちらこそよろしくお願いします。

**Comment by ShinjiEnoki** [comment]
pipとanacondaが混じっているのはわかりにくいなら、分離する提案はありかもしれません

**Comment by ShinjiEnoki** [comment]
多言語対応できるなら、翻訳するよ！とか言ってみるとか？
相手のポリシーによりますけど

**Comment by daddygongon** [comment]
西谷@関西学院大・理工です．よろしくお願いします．
anacondaで入れると，conda promptで．．．
pipが混載．

**Comment by daddygongon** [comment]
anaconda || native pip
cmd.exeを普段使っているが，anaconda promptに切り替えるという記述がない．

**Comment by masa-matsu** [comment]
よろしくお願いします。

**Comment by masa-matsu** [comment]
https://www.tensorflow.org/install/install_windows
Windows のインストールガイダンスで、anaconda をインストールをしたあと
conda コマンドが常用のターミナルで通らない。
anaconda prompt でないと conda コマンドが通らない。
→  anaconda prompt の起動について説明がほしい

**Comment by masa-matsu** [comment]
Windows 10 で
Anaconda 5.0.1 For Windows (Python 3.6 version 64bit) をインストール
ターミナルから以下のコマンドを実行すると失敗する
```
＄ conda create -n tensorflow python=3.6
'conda' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルと
して認識されていません。
```
Anaconda Prompt を起動して同じコマンドを実行するとうまくいく。
```
＄ conda create -n tensorflow python=3.6
```

**Comment by daddygongon** [comment]
Hello,

When I tried to install TensorFlow via anaconda.

The target os is 'windows 10', and via anaconda 5.0.1 For Windows (Python 3.6 version 64bit).
After intall anaconda, from the dialy use terminal 'cmd.exe',
 $ conda create -n tensorflow python=3.6
but received an error message.

But from 'Anaconda Prompt' below 'Anaconda3' of 'start button' it works correctly.

Thus I recommend to include the following description,
 start  'Anaconda Prompt' below 'Anaconda3' of 'start button'
between the steps.

**Comment by masa-matsu** [comment]
ありがとうございました。issue のリンクです。
https://github.com/tensorflow/tensorflow/issues/15232

**Comment by masayuki14** [comment]
お疲れ様でした。たてたIssueに反応ありますね。テンプレートを埋めて続けてみてください。
https://gitter.im/oss-gate/devel で相談もできるのでOSS開発を継続していきましょう！

まだイベントはたってないですが、1月と3月に大阪でミートアップとワークショップを開催予定なので、よかったらまた参加してみてください！

closeしますが、引き続きここを使っても大丈夫です！

**Comment by masa-matsu** [comment]
ご指導ありがとうございました。
引き続き、tensorflowで作業をつづけますので、また、gitter ででも質問させてください。

なお、issue は close しました。
テンプレートを埋めようかと思いましたが、その後、別の方からの指摘もありスレ違いと思ったからです。
とはいえ、contributeへのモチは下がっていません。

イベントもできれば参加させていただきます、次お会いできることを楽しみに、はげみます。

ありがとうございました。

2017/12/11 午前11:03 "Masa" <notifications@github.com>:

お疲れ様でした。たてたIssueに反応ありますね。テンプレートを埋めて続けてみてください。
https://gitter.im/oss-gate/devel で相談もできるのでOSS開発を継続していきましょう！

まだイベントはたってないですが、1月と3月に大阪でミートアップとワークショップを開催予定なので、よかったらまた参加してみてください！

closeしますが、引き続きここを使っても大丈夫です！

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oss-gate/workshop/issues/695#issuecomment-350604465>,
or mute the thread

**Comment by daddygongon** [comment]
お疲れ様でした．それと，おめでとうございます．
まともな反応ですよね．それだけTensorFlowのprojectがwell-organizedされていることの証明ですね．
oss-gateもそうなっていくことを望みます．また，機会があればお話しましょう．
