### ISSUE TITLE
OSS Gate Workshop: MonotaRO: 2018-01-15: ytecjp: Apache Solr: Work log

### ISSUE THREAD

**Issue by ytecjp** [oss-gate/workshop#708]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by suzuki-kei** [comment]
サポーターやります！

**Comment by ytecjp** [comment]
Google で「Solr」と検索し、一番上の http://lucene.apache.org/solr/ にアクセスした。

**Comment by ytecjp** [comment]
ライセンスを確認した。
サイトの一番下に「Licensed under the Apache License, Version 2.0.」という表記がある。

**Comment by ytecjp** [comment]
公式サイトの Community のページ http://lucene.apache.org/solr/community.html から、GItHub にアクセスした。
https://github.com/apache/lucene-solr/ にリンクされていた。
この階層にはライセンスファイルはなかったが、 solr ディレクトリの中にライセンスファイルがあった。

**Comment by ytecjp** [comment]
動かし方を探した。
トップページに Documents はなかったが、 Resources に「Get Start」という記載があった。
 http://lucene.apache.org/solr/resources.html

**Comment by ytecjp** [comment]
Tutorials の Solr Quick Start があることがわかった。
http://lucene.apache.org/solr/guide/7_2/solr-tutorial.html

**Comment by ytecjp** [comment]
はじめに、環境の確認を行った。
Apache Solr runs on Java 8 or greater. という記載がある。 https://lucene.apache.org/solr/7_2_1/SYSTEM_REQUIREMENTS.html

**Comment by ytecjp** [comment]
Java 8 がローカルマシンにないので、インストールする必要がある。
「Java JDK」で検索して、一番上のURLにアクセスした。 http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html 
jdk-8u152-windows-x64.exe をダウンロードした。

**Comment by ytecjp** [comment]
「An Apache Solr release download. This tutorial is designed for Apache Solr 7.2.」に従い、ダウンロードページに移動した。
http://lucene.apache.org/solr/downloads.html

Latest のミラーを表示した。
http://www.apache.org/dyn/closer.lua/lucene/solr/7.2.1

一番上の
http://ftp.jaist.ac.jp/pub/apache/lucene/solr/7.2.1 
にアクセスした。

http://ftp.jaist.ac.jp/pub/apache/lucene/solr/7.2.1/solr-7.2.1.zip
をダウンロードした。

**Comment by ytecjp** [comment]
JDK のインストールをした。
exe をダブルクリックで起動し、ウィザードに従い、何も変更せずにインストールした。

**Comment by ytecjp** [comment]
solr-7.2.1.zip のダウンロードが完了した。
チュートリアルページが Windows 用であるか上に記載がなかったので、ページを確認したところ、Windowsでもできそうなことがわかったので、進める。

**Comment by ytecjp** [comment]
C:\usr\solr-7.2.1 に、Windows の展開ウィザードを使用して展開した。

**Comment by ytecjp** [comment]
C:\usr\solr-7.2.1\solr-7.2.1 に展開されてしまった。

**Comment by ytecjp** [comment]
http://lucene.apache.org/solr/guide/7_2/solr-tutorial.html#launch-solr-in-solrcloud-mode
に従い、起動した。

```
C:\>cd c:\usr\solr-7.2.1\solr-7.2.1

c:\usr\solr-7.2.1\solr-7.2.1>bin\solr.cmd start -e cloud

Welcome to the SolrCloud example!

This interactive session will help you launch a SolrCloud cluster on your local workstation.
To begin, how many Solr nodes would you like to run in your local cluster? (specify 1-4 nodes) [2]:
1
Ok, let's start up 1 Solr nodes for your example SolrCloud cluster.
Please enter the port for node1 [8983]:

Creating Solr home directory c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node1\solr

Starting up Solr on port 8983 using command:
"c:\usr\solr-7.2.1\solr-7.2.1\bin\solr.cmd" start -cloud -p 8983 -s "c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node1\solr"

Waiting up to 30 to see Solr running on port 8983
INFO  - 2018-01-15 19:42:47.903; org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider; Cluster at localhost:9983 ready

Now let's create a new collection for indexing documents in your 1-node cluster.
Please provide a name for your new collection: [gettingstarted]
Started Solr server on port 8983. Happy searching!
bin\solr.cmd start -e cloud
```

node の数を聞かれたので、1として、Enterを押した。
ポートについて聞かれたので、何も入れずに、Enterを押した。

**Comment by ytecjp** [comment]
Windows の「Windows セキュリティの重要な警告」のウィンドウが表示された。
名前： Java Platform SE binary
発行元： Oracle Corporation
パス： C:\program files\java\jre1.8.0_152\bin\java.exe
「アクセスを許可する」を選択した。

**Comment by ytecjp** [comment]
node を 1 としてしまったので、チュートリアルの説明から外れてしまった。
チュートリアルでは、2 となっていて、設定が続いていたが、そのままスキップした。

http://localhost:8983/solr/ にアクセスできることを確認した。
http://localhost:8983/solr/#/~cloud にアクセスしてもチュートリアルのような画面にならなかった。

**Comment by ytecjp** [comment]
一度、Ctrl+C で止めてみた。

**Comment by ytecjp** [comment]
もう一度、実行してみた。
しかし、「Oops! Looks like port 8983 is already being used by another process. Please choose a different port.」というエラーが出てしまった。
終了できていないみたい。

チュートリアルの中盤に、stop の方法が書いてあるようなので、試す。
```
c:\usr\solr-7.2.1\solr-7.2.1>bin\solr stop -all
Stopping Solr process 2144 running on port 8983
```

**Comment by ytecjp** [comment]
もう一度実行してみた。
```
c:\usr\solr-7.2.1\solr-7.2.1>bin\solr.cmd start -e cloud

Welcome to the SolrCloud example!

This interactive session will help you launch a SolrCloud cluster on your local workstation.
To begin, how many Solr nodes would you like to run in your local cluster? (specify 1-4 nodes) [2]:

Ok, let's start up 2 Solr nodes for your example SolrCloud cluster.
Please enter the port for node1 [8983]:

Please enter the port for node2 [7574]:

Solr home directory c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node1\solr already exists.
Cloning c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node1 into
   c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node2

Starting up Solr on port 8983 using command:
"c:\usr\solr-7.2.1\solr-7.2.1\bin\solr.cmd" start -cloud -p 8983 -s "c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node1\solr"

Waiting up to 30 to see Solr running on port 8983

Starting up Solr on port 7574 using command:
"c:\usr\solr-7.2.1\solr-7.2.1\bin\solr.cmd" start -cloud -p 7574 -s "c:\usr\solr-7.2.1\solr-7.2.1\example\cloud\node2\solr" -z localhost:9983

Waiting up to 30 to see Solr running on port 7574
Started Solr server on port 8983. Happy searching!
INFO  - 2018-01-15 19:54:48.158; org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider; Cluster at localhost:9983 ready

Now let's create a new collection for indexing documents in your 2-node cluster.
Please provide a name for your new collection: [gettingstarted]
Started Solr server on port 7574. Happy searching!

```

チュートリアルのように、実行できた。
が、微妙に違う。

http://localhost:8983/solr/ → 表示できた。
http://localhost:8983/solr/#/~cloud → チュートリアルにある表示ではなかった。

途中を見ると「Please provide a name for your new collection: [gettingstarted]」というプロンプトが出るはずだが、出ていない。

**Comment by ytecjp** [comment]
よく見たところ、出力は以下のようになっていた。
```
Now let's create a new collection for indexing documents in your 2-node cluster.
Please provide a name for your new collection: [gettingstarted]
Started Solr server on port 7574. Happy searching!

How many shards would you like to split gettingstarted into? [2]

How many replicas per shard would you like to create? [2]

Please choose a configuration for the gettingstarted collection, available options are:
_default or sample_techproducts_configs [_default]

Created collection 'gettingstarted' with 2 shard(s), 2 replica(s) with config-set 'gettingstarted'

Enabling auto soft-commits with maxTime 3 secs using the Config API

POSTing request to Config API: http://localhost:8983/solr/gettingstarted/config
{"set-property":{"updateHandler.autoSoftCommit.maxTime":"3000"}}
Successfully set-property updateHandler.autoSoftCommit.maxTime to 3000


SolrCloud example running, please visit: http://localhost:8983/solr


c:\usr\solr-7.2.1\solr-7.2.1>
```

よく確認したところ、チュートリアルと出力の行が入れ替わっていただけだった。
続きをEnterで進むことで、コマンドが完了した。
コマンド完了後に、ローカルURLにアクセスしたところ、チュートリアルと同じ管理画面結果となった。

**Comment by whosaysni** [comment]
ふりかえりさぽーとやります！

**Comment by ytecjp** [comment]
はまったポイント

- 対象OSとしてWindows があるかわからなかった
- ライセンスファイルへの到達が手間取った
- 出力行が入れ替わっていることに気づかなかった

**Comment by yoichi** [comment]
参加ありがとうございました。このissueはcloseしましたが、引き続きここにメモを残しながら作業しても大丈夫です！
