### ISSUE TITLE
OSS Gate Workshop: MonotaRO: 2018-01-15: YoshinoriKasamatsu: boto3: Work log

### ISSUE THREAD

**Issue by YoshinoriKasamatsu** [oss-gate/workshop#709]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by YoshinoriKasamatsu** [comment]
googleでboto3を検索、一番上が公式っぽい。

**Comment by whosaysni** [comment]
さぽーたーです

**Comment by YoshinoriKasamatsu** [comment]
ページの右上にgithubのリンクあり。

**Comment by YoshinoriKasamatsu** [comment]
githubにソースコードあり、LICENSEファイルでライセンス確認。
Apache License , Version 2.0だ。

**Comment by YoshinoriKasamatsu** [comment]
LICENSEファイル内にライセンスの詳細のurlのリンクあり。

**Comment by YoshinoriKasamatsu** [comment]
動かし方を確認。ソースコードにREADME.rstがあったのでみてみる。

**Comment by YoshinoriKasamatsu** [comment]
pipでインストールできる。実行してみる。
インストール成功。

**Comment by YoshinoriKasamatsu** [comment]
インストールログ
Collecting boto3
  Downloading boto3-1.5.14-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 830kB/s 
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./.local/lib/python3.6/site-packages (from boto3)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in ./.local/lib/python3.6/site-packages (from boto3)
Collecting botocore<1.9.0,>=1.8.28 (from boto3)
  Downloading botocore-1.8.28-py2.py3-none-any.whl (4.0MB)
    100% |████████████████████████████████| 4.0MB 396kB/s 
Requirement already satisfied: docutils>=0.10 in ./.local/lib/python3.6/site-packages (from botocore<1.9.0,>=1.8.28->boto3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.local/lib/python3.6/site-packages (from botocore<1.9.0,>=1.8.28->boto3)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.9.0,>=1.8.28->boto3)
Installing collected packages: botocore, boto3
  Found existing installation: botocore 1.5.43
    Uninstalling botocore-1.5.43:
      Successfully uninstalled botocore-1.5.43
Successfully installed boto3-1.5.14 botocore-1.8.28

**Comment by YoshinoriKasamatsu** [comment]
credentiansの作成をする。まず、すでにファイルがあるか確認。-> なし。
credentialsファイルの作成。一旦キーはなし。

**Comment by YoshinoriKasamatsu** [comment]
続いて、configファイルを作成~/.aws/config
一旦、内容はREADMEの通り
[default]
region=us-east-1

**Comment by YoshinoriKasamatsu** [comment]
Pythonのinterpreterで実行してみる。
途中でキーを入れていないが続けてみる。
エラーメッセージがでて、キーが無効であるというメッセージ

**Comment by YoshinoriKasamatsu** [comment]
キーの取得が必要であるとあればよかったかな。あと、成功と失敗のメッセージ例があれば良いかと思った。

**Comment by YoshinoriKasamatsu** [comment]
キーの取得をしてみる。

**Comment by YoshinoriKasamatsu** [comment]
aws.amazon.comにログインして、IAMロールからユーザーを作成して、認証情報からアクセスキーの作成をした。

**Comment by YoshinoriKasamatsu** [comment]
~/.aws/credentialsにキーを転記

**Comment by YoshinoriKasamatsu** [comment]
再度、interpriterで実行してみる。
今度はs3に保存していたファイルが表示された。

**Comment by YoshinoriKasamatsu** [comment]
開発の手順とテストの実行方法を確認する。

**Comment by YoshinoriKasamatsu** [comment]
git clone https://github.com/boto/boto3.gitを実行して、ソースを取得した。

**Comment by YoshinoriKasamatsu** [comment]
cd boto3
virtualenv venvを実行したが、virtualenvが入っていなかった。
`pyenv: virtualenv: command not found

The `virtualenv' command exists in these Python versions:
  2.7.13`

**Comment by YoshinoriKasamatsu** [comment]
コードマークアップ失敗...

**Comment by YoshinoriKasamatsu** [comment]
virtualenvの環境構築の方法を覚えていない...

**Comment by YoshinoriKasamatsu** [comment]
Python -Vで今の環境を確認
Python 3.6.0

**Comment by YoshinoriKasamatsu** [comment]
3で実行しているので、ないと言われてるかもしれないので、Python 2.7に切り替えてみる。
`pyenv global 2.7.13`

**Comment by YoshinoriKasamatsu** [comment]
再度実行してみる。
`New python executable in /Users/kasamatsu/.aws/boto3/boto3/venv/bin/python2.7
Also creating executable in /Users/kasamatsu/.aws/boto3/boto3/venv/bin/python
Installing setuptools, pip, wheel...done.`

**Comment by YoshinoriKasamatsu** [comment]
'. /venv/bin/activate'を実行
失敗した模様
'-bash: /venv/bin/activate: No such file or directory’

**Comment by YoshinoriKasamatsu** [comment]
タイポだったの再度実行
'. venv/bin/activate'
でうまくいった。

**Comment by YoshinoriKasamatsu** [comment]
awsのaccess keyとsecret access keyの認証情報が必要である事がreadmeにあればよかった。思った。

**Comment by yoichi** [comment]
後半戦よろしくお願いします！

**Comment by YoshinoriKasamatsu** [comment]
Quick Startの内容がAPIキー取得が前提なので、APIキーが要らないサンプルもあると良いと思った。
あと、今のサンプルコードだとS3にファイルがないとレスポンスがないので、レスポンスがある方がよい。

**Comment by yoichi** [comment]
サンプル通りやったときのエラー
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/collection.py", line 82, in __iter__
    for page in self.pages():
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/collection.py", line 160, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 270, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 335, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.
```

**Comment by YoshinoriKasamatsu** [comment]
README.rstをよりわかりやすくしてほしいです。
２つ報告したいことがあります。
１つめは、
https://github.com/boto/boto3/blob/develop/README.rst のQuick Startをやってみました。
下のコードの実行しました。
```>>> import boto3
>>> s3 = boto3.resource('s3')
>>> for bucket in s3.buckets.all():
        print(bucket.name)
```

下のエラーが出ました。
```

```

APIキーが必要だと調べて分かりましたが、APIキーが不要なサンプルがあれば良いと思います。
２つめは、APIキー取得後、~/.aws/credentialsに値を入れて、interpreterでサンプルを実行してみましたが、何も表示されませんでした。S3にファイルが何もない状態でも結果が出力されるサンプルのほうがよいかと思います。

提案として２つあります。
１つめは、
```
First, install the library and set a default region:
```
の次にAPIが要らないサンプルコードを差し込んでほしいです。
２つめは、
```
Next, set up credentials (in e.g. ~/.aws/credentials):
```
の説明としてIAMコンソールでAPIキーの取得が必要と注意書きがほしいです。

**Comment by YoshinoriKasamatsu** [comment]
README.rstをよりわかりやすくしてほしいです。
https://github.com/boto/boto3/blob/develop/README.rst のQuick Startをやってみました。
下のコードの実行しました。
```>>> import boto3
>>> s3 = boto3.resource('s3')
>>> for bucket in s3.buckets.all():
        print(bucket.name)
```
しかし、S3になにもファイルがなかったので何も表示されませんでした。
前提にかかわらずレスポンスのあるサンプルコードが示されているほうがよいと思います。

**Comment by YoshinoriKasamatsu** [comment]
https://github.com/boto/boto3/blob/develop/CONTRIBUTING.rst
を確認

**Comment by YoshinoriKasamatsu** [comment]
issueにすでにないか書いてあったので見てみる。

**Comment by YoshinoriKasamatsu** [comment]
https://github.com/boto/boto3/issues?utf8=%E2%9C%93&q=quick+start
で検索して、確認したがなさそう。

**Comment by YoshinoriKasamatsu** [comment]
README.rstをよりわかりやすくしてほしいです。
https://github.com/boto/boto3/blob/develop/README.rst のQuick Startをやってみました。
下のコードの実行しました。
```>>> import boto3
>>> s3 = boto3.resource('s3')
>>> for bucket in s3.buckets.all():
        print(bucket.name)
```
しかし、S3になにもファイルがなかったので何も表示されませんでした。
正常に実行できたのか分かりませんでした。
前提にかかわらずレスポンスのあるサンプルコードが示されているほうがよいと思います。
環境は以下の通りです。
python

**Comment by YoshinoriKasamatsu** [comment]
issueのタイトルを考える。
「Quick Startのサンプルをレスポンスのあるコードに変更してください。」

**Comment by yoichi** [comment]
参加ありがとうございました。このissueはcloseしましたが、引き続きここにメモを残しながら作業しても大丈夫です！
