### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-01-27: tomoyuki-nakabayashi: googletest: Work log

### ISSUE THREAD

**Issue by tomoyuki-nakabayashi** [oss-gate/workshop#714]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ashie** [comment]
隣のサポーターです。よろしくお願いします！

**Comment by tomoyuki-nakabayashi** [comment]
公式ドキュメントを読む。

https://github.com/google/googletest/tree/master/googletest/docs/Primer.md

**Comment by tomoyuki-nakabayashi** [comment]
Setting up a New Test Projectを読んで、セットアップする。

**Comment by tomoyuki-nakabayashi** [comment]
ビルドするために、レポジトリをcloneした。

https://github.com/google/googletest.git

**Comment by tomoyuki-nakabayashi** [comment]
公式おすすめのCMakeでビルドする。

cmake .

**Comment by tomoyuki-nakabayashi** [comment]
makeする。

make

**Comment by tomoyuki-nakabayashi** [comment]
ビルド完了した。

**Comment by tomoyuki-nakabayashi** [comment]
googletest/googletest/samplesを動かしてみる。

googletest/googletest/make下のMakefileをmakeする。
公式ドキュメントに手順がない？

**Comment by tomoyuki-nakabayashi** [comment]
サンプルのテストを動かす。

```
./sample1_unittest 
Running main() from gtest_main.cc
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from FactorialTest
[ RUN      ] FactorialTest.Negative
[       OK ] FactorialTest.Negative (0 ms)
[ RUN      ] FactorialTest.Zero
[       OK ] FactorialTest.Zero (0 ms)
[ RUN      ] FactorialTest.Positive
[       OK ] FactorialTest.Positive (0 ms)
[----------] 3 tests from FactorialTest (0 ms total)

[----------] 3 tests from IsPrimeTest
[ RUN      ] IsPrimeTest.Negative
[       OK ] IsPrimeTest.Negative (0 ms)
[ RUN      ] IsPrimeTest.Trivial
[       OK ] IsPrimeTest.Trivial (0 ms)
[ RUN      ] IsPrimeTest.Positive
[       OK ] IsPrimeTest.Positive (0 ms)
[----------] 3 tests from IsPrimeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (0 ms total)
[  PASSED  ] 6 tests.
```

**Comment by ashie** [comment]
> googletest/googletest/make下のMakefileをmakeする。
> 公式ドキュメントに手順がない？

一応以下のような記述はありますね

```
 If your build system is not on this list, you can take a look at make/Makefile to learn how Google Test should be compiled (basically you want to compile src/gtest-all.cc with GTEST_ROOT and GTEST_ROOT/include in the header search path, where GTEST_ROOT is the Google Test root directory).
```

**Comment by tomoyuki-nakabayashi** [comment]
CMakeでサンプルをビルドしたいが、やり方がわからないなう。

**Comment by tomoyuki-nakabayashi** [comment]
CMakeのオプションを与える方法を調査する。

**Comment by tomoyuki-nakabayashi** [comment]
公式ドキュメントの手順を進めていき、サンプルを動かそうとした。
しかし、サンプルをビルドする手順が、公式ドキュメントからは、わからない。

**Comment by ashie** [comment]
> googletest/googletest/make下のMakefileをmakeする。

こちらではサンプルの動かし方がわかったが

> 公式おすすめのCMakeでビルドする。

こちらでのサンプルのビルド&動かし方がわからないという話

**Comment by tomoyuki-nakabayashi** [comment]
CMakeList.txtの冒頭にあるコメントを読み、googletestのテストを動かそうする。

が、ctest --helpを実行しても、何を意味しているのかが、理解できない。

```
# To run the tests for Google Test itself on Linux, use 'make test' or
# ctest.  You can select which tests to run using 'ctest -R regex'.
# For more options, run 'ctest --help'
```

**Comment by tomoyuki-nakabayashi** [comment]
CMakeList.txtにそれっぽいオプション記述があるが、有効にする方法がわからない。

```
option(gtest_build_samples "Build gtest's sample programs." OFF)
```

**Comment by tomoyuki-nakabayashi** [comment]
CMakeオプションの使い方をgoogleる。

**Comment by tomoyuki-nakabayashi** [comment]
-D<オプション>=<ON/OFF>でオプションを切り替えるらしい。

```
cmake . -Dgtest_build_samples=ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tomoyuki/work/19.OSS-gate/googletest/googletest

make
[  7%] Built target gtest
Scanning dependencies of target sample9_unittest
[ 10%] Building CXX object CMakeFiles/sample9_unittest.dir/samples/sample9_unittest.cc.o
[ 14%] Linking CXX executable sample9_unittest
[ 14%] Built target sample9_unittest
Scanning dependencies of target sample10_unittest
[ 17%] Building CXX object CMakeFiles/sample10_unittest.dir/samples/sample10_unittest.cc.o
[ 21%] Linking CXX executable sample10_unittest
[ 21%] Built target sample10_unittest
[ 28%] Built target gtest_main
Scanning dependencies of target sample2_unittest
```

**Comment by tomoyuki-nakabayashi** [comment]
サンプルが動いた。

```
./sample2_unittest 
Running main() from gtest_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from MyString
[ RUN      ] MyString.DefaultConstructor
[       OK ] MyString.DefaultConstructor (0 ms)
[ RUN      ] MyString.ConstructorFromCString
[       OK ] MyString.ConstructorFromCString (0 ms)
[ RUN      ] MyString.CopyConstructor
[       OK ] MyString.CopyConstructor (0 ms)
[ RUN      ] MyString.Set
[       OK ] MyString.Set (0 ms)
[----------] 4 tests from MyString (0 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 4 tests.
```

**Comment by ashie** [comment]
↑ こういった手順が公式ドキュメントにあると、初めて使う人が入りやすそう

**Comment by tomoyuki-nakabayashi** [comment]
https://github.com/google/googletest/blob/master/googletest/README.md
を参考に、1つ自分で作ったテストを動かしたい。
まず、Using CMakeを読み進める。

**Comment by ashie** [comment]
普通、最初に見るのは

https://github.com/google/googletest

で、そこから、さあ始めようと最初に目につくのが

> Getting started information for Google Test is available in the Google Test Primer documentation.

> 公式ドキュメントを読む。
> 
> https://github.com/google/googletest/tree/master/googletest/docs/Primer.md

なのでそこを読み始めたが、cmakeでのサンプルの動かし方が書いておらず、迷子になった。
が、トップのREADME.mdをもう少し読み進めると以下のリンクがあり

> 実はビルド手順が書いてあった。 googletest/googletest/README.md

ここを読むとサンプルのビルド手順が書いてあった

**Comment by fkawa-play** [comment]
どのリンクを辿ればサンプルのビルド方法が分かるかを明確にする、というのが課題ですね。READMEの中にその記載を加えると良いと思います。

**Comment by fkawa-play** [comment]
細かい点ですが、コマンドを実行する場合はそのコマンドのバージョンをメモしておくと良いです。

**Comment by tomoyuki-nakabayashi** [comment]
cloneして1分でサンプルを動かしたい。

トップのREADMEから読んでいって、 Google Test Primerへのリンクを見つけたので辿った。
Primer.mdの中には、サンプルを動かす方法はなかった。
ここで少し迷子になった。

色々辿った結果、googletest/README.mdにたどり着いて、やっと、サンプルのビルド方法がわかった。

トップのREADMEのすぐ目につくところに、サンプルの動かし方の手順へのリンクが明示的に書かれていると、助かります。

**Comment by tomoyuki-nakabayashi** [comment]
# すぐにサンプルを動かせるリンクがあると親切

トップのREADMEから読んでいって、 Google Test Primerへのリンクを見つけたので辿った。
Primer.mdの中には、サンプルを動かす方法はなかった。
ここで少し迷子になった。

色々辿った結果、googletest/README.mdにたどり着いて、やっと、サンプルのビルド方法がわかった。ここを見るとサンプルが動かせることが書かれていると良い。

トップのREADMEのすぐ目につくところに、サンプルの動かし方の手順へのリンクが明示的に書かれていると、助かります。

**Comment by tomoyuki-nakabayashi** [comment]
# There should be a link to build and try samples immediately in the top README.md

When I start googletest, I read the top README from top to bottom. I found a link to Google Test Primer and followed the link.
But, Google Test Primer doesn't have the information to build and try samples.

I finally found googletest/README.md includes the information.
I feel the information should be written in the top README.md.

I suggest to add the above information in the below sentence.

> More detailed documentation for googletest (including build instructions) are in its interior googletest/README.md file.

**Comment by tomoyuki-nakabayashi** [comment]
# すぐにサンプルを動かせるリンクがあると親切

ユーザーがgoogletestを理解する際、最初にサンプルを動かすでしょう。
トップのREADMEには、次の一文がありますが、サンプルを試すことについての言及がありません。

> More detailed documentation for googletest (including build instructions) are in its interior googletest/README.md file.

色々辿った結果、googletest/README.mdにたどり着いて、やっと、サンプルのビルド方法がわかった。ここを見るとサンプルが動かせることがトップのREADMEに書かれていると良い。

**Comment by tomoyuki-nakabayashi** [comment]
# To build and try samples immediately, there might be a link in the top README.md

When a user starts googletest, he/she will try samples at first to understand.
The top README has the following sentence, but doesn't refer how to try samples.
 
> More detailed documentation for googletest (including build instructions) are in its interior googletest/README.md file.

I finally found googletest/README.md includes the information.
I feel it's kind if the information is written in the top README.md.

**Comment by tomoyuki-nakabayashi** [comment]
フィードバック出しました。
https://github.com/google/googletest/issues/1431

**Comment by ashie** [comment]
コード修正のとっかかりはtypoの修正が気楽でいいけど、codespellというコマンドを使うとtypoを見つけ易くていいよという話をした :D

**Comment by shiro615** [comment]
- ドキュメントには記載はないが経験上わかったところもちゃんとした手順をフィードバックすると良さそう
- 自分で動かしてみて詰まったところとサポーターのフィードバックをまとめてissueにしたのは良い
- 英語に翻訳する前に日本語でわかりやすく説明が書いてあったのが良い

**Comment by kenhys** [comment]
@tomoyuki-nakabayashi 

お疲れ様でした！
今度はぜひビギナーさんをサポートするサポーターとしての参加も検討してみてください。

https://qiita.com/tomoyuki-nakabayashi/items/7eac11d89de2d2da383a
「最初で最後の一歩にしない。」その意気込みをぜひ継続していってください！
