### ISSUE TITLE
 OSS Gate Workshop: Tokyo: 2018-01-27: matzryo: yasslab/railsguides.jp: Work log

### ISSUE THREAD

**Issue by matzryo** [oss-gate/workshop#715]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by matzryo** [comment]
目的: https://railsguides.jp/ の翻訳に貢献する

**Comment by matzryo** [comment]
公式ページの翻訳関連ページをみつける

rails guideで検索
翻訳に貢献するのページへとぶ

**Comment by matzryo** [comment]
README.mdを読む

ライセンスをみる。安心して更新できるかどうかを把握できる。プロプライエタリなライセンスだと、ソースコードみるのに契約が必要だったりする。=>貢献のハードルがあがる。
Githubなら、あまり心配しなくてよい。規約で決まっているので。
今回はCC BY-SA 4.0。ドキュメント系のライセンス。創作物、アート。

**Comment by matzryo** [comment]
README.mdを読む2

https://github.com/yasslab/railsguides.jp#rails%E3%82%AC%E3%82%A4%E3%83%89%E3%81%AE%E7%94%9F%E6%88%90%E6%96%B9%E6%B3%95

まずはローカルで動かしてみればいいのかな？
それから修正して、ローカルで変更を確認して、プルリクエスト送ればいいのかな。そこまでできるなら

**Comment by matzryo** [comment]
README.mdを読む3

https://github.com/yasslab/railsguides.jp#%E7%BF%BB%E8%A8%B3%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E7%B4%B0%E3%81%8B%E3%81%AA%E3%82%A2%E3%83%AC%E3%82%B3%E3%83%AC

なんだか複雑な仕組み…
とりあえず手元で動かしてみよう

**Comment by matzryo** [comment]
README.mdにしたがいコマンド実行、
rubyのバージョンが違うと怒られる

$ bundle exec rake assets:precompile
=> Your Ruby version is 2.4.3, but your Gemfile specified 2.4.1

rbenvで入れよう

**Comment by matzryo** [comment]
rbenvインストール

普段fishを使っているが、https://github.com/rbenv/rbenv#installation をコピペしたいので、bashを起動

**Comment by matzryo** [comment]
fishでfisherman を使ってrbenvを使おうとするも、うまくいかない。しかもテンパって記録を取るのを忘れる…

**Comment by matzryo** [comment]
bash -l
https://github.com/rbenv/ruby-build をhttps://github.com/rbenv/ruby-build#installation に従いインストール。
rbenv install 2.4.1

**Comment by swamp09** [comment]
https://github.com/yasslab/railsguides.jp#rails%E3%82%AC%E3%82%A4%E3%83%89%E3%81%AE%E7%94%9F%E6%88%90%E6%96%B9%E6%B3%95

環境構築に必要なRubyのバージョンなど、書いてあると良いかもしれないですね。

**Comment by matzryo** [comment]
$ bundle install --path vendor/bundle
mysql クライアントが無いと怒られる

mysql入れる
Arch Linux で選ばれている MySQL の実装は MariaDB ですとのこと
https://wiki.archlinux.jp/index.php/MySQL#.E3.82.A4.E3.83.B3.E3.82.B9.E3.83.88.E3.83.BC.E3.83.AB
$ sudo pacman -S mariadb

$ bundle install

**Comment by matzryo** [comment]
README.md

libev mysql postgresなどの依存関係
=> Railsの場合、書くときりがないので書かない

rubyのバージョン明記
=> Gemfileに書いてある。Gemfileを見てください、でリンク張るのはありかな。

bundle install
=> まあこれはあってもいいかな。というかそもそも、Pull Requestを出すために、環境を構築する手順があればいいかなあ。環境構築がコピペでできるようになればいいな

**Comment by matzryo** [comment]
mariadbとpostgresqlを入れて、bundle installは通った。

**Comment by matzryo** [comment]
とりあえずHTMLは生成してみたい。

https://github.com/yasslab/railsguides.jp#1-html%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E7%94%9F%E6%88%90-jekyll
でもbundle exec rake assets:precompileやると

```
[matsui@matz-arch railsguides.jp]$ bundle exec rake assets:precompile
Configuration file: /home/matsui/Documents/work/oss/railsguides.jp/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
           Cleaner: Nothing to do for ./_site.
           Cleaner: Nothing to do for ./guides/output/ja/.jekyll-metadata.
           Cleaner: Nothing to do for .sass-cache.
/home/matsui/.rbenv/versions/2.4.1/bin/ruby rails_guides.rb
Generating 3_2_release_notes.md as 3_2_release_notes.html
/home/matsui/Documents/work/oss/railsguides.jp/actionview/lib/action_view/template/handlers/erb.rb:69:in `valid_encoding': Your template was not saved as valid US-ASCII. Please either specify US-ASCII as the encoding for your template in your text editor, or mark the template with its encoding by inserting the following as the first line of the template: (ActionView::Template::Error)

# encoding: <name of correct encoding>.

The source of your template was:
```

**Comment by matzryo** [comment]
フィードバックポイント

プルリクエストを送るとき、https://github.com/yasslab/railsguides.jp#rails%E3%82%AC%E3%82%A4%E3%83%89%E3%81%AE%E7%94%9F%E6%88%90%E6%96%B9%E6%B3%95
には変更ずみコードの手元での確認方法の手順の記載があった。
その前に、手元で環境を構築する手順を想像する必要があった。
手元でまずは既存のHTMLを確認しよう、という手順の記載があると、迷いなく進められた。

**Comment by kenhys** [comment]
「手元で環境を構築する手順を想像する必要があった。」
よい気づきですね！
同じことをやろうとする人が迷いなく進められるようにしよう、というのはとてもよいです。

**Comment by matzryo** [comment]
https://github.com/yasslab/railsguides.jp/pull/607

**Comment by fkawa-play** [comment]
Feedback:

* 冒頭に  **目的** と **変更内容** を **簡潔に** 書くと読みやすいと思いました
* コマンド実行と結果については  ```　これで囲むと読みやすいです

**Comment by kenhys** [comment]
@matzryo 

お疲れ様でした！

今度はぜひビギナーさんをサポートするサポーターとしての参加も検討してみてください。
まだ自信がないなぁというのであれば、ビギナーとして継続的に参加するというのもよいです。
