### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-01-27: sndstudy: Hyperapp: Work log

### ISSUE THREAD

**Issue by sndstudy** [oss-gate/workshop#716]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sndstudy** [comment]
公式サイトを検索
https://hyperapp.js.org/

**Comment by swamp09** [comment]
よろしくお願いします。 ✋

**Comment by sndstudy** [comment]
ドキュメントにHello Worldがあったので実際に動かしてみる

https://github.com/hyperapp/hyperapp/blob/master/docs/hello-world.md

**Comment by sndstudy** [comment]
ドキュメントのHelloWorldに記載されているサンプルコードをコピペして動作する事を確認

**Comment by sndstudy** [comment]
開発者コンソールから操作して値が更新される事を確認

'main.up(1000)'

**Comment by sndstudy** [comment]
ドキュメントHelloWorldのStateを読む

**Comment by sndstudy** [comment]
Stateを読んだ

- イミュータブルなオブジェクト
- 状態を変更するにはアクションを定義してそこから変更する

**Comment by sndstudy** [comment]
Actionsを読んだ

setTimeoutを用いたコード例があったので実際に書いてみる

**Comment by sndstudy** [comment]
setTimeout用いたコードを実際に書いて動作を確認した

**Comment by sndstudy** [comment]
Viewを読んだ

- アプリケーションの状態が変わる度にViewの関数が呼び出される
- サンプルではConstになっているがViewの関数を書きかえればDOMの構造は変わるのだろうか?

**Comment by sndstudy** [comment]
Viewの関数を書き換えてDOM構造が変わるのか確認する

**Comment by sndstudy** [comment]
viewの関数をconstからvarに書き換えることでDOM構造が変化する事を確認

- action内にviewを書き換える処理を入れてあげれば変えられるかもしれない

**Comment by sndstudy** [comment]
action内でViewを更新しようと試みたが期待どうりの動作はしなかった

- DOM操作関連のドキュメントが無いか探してみる

**Comment by sndstudy** [comment]
Virtual DOMに関するドキュメントを発見した

https://github.com/hyperapp/hyperapp/blob/master/docs/advanced.md

**Comment by sndstudy** [comment]
Virtual DOMを返すComponentsの記載を発見

- ドキュメントに書いてあるソースコードでは情報が不足している? 
  - state.todosがどこで定義されているか分からない
- HelloWorldのドキュメントと比べて実装方法が異なる
  - HelloWorldはscriptタグにhyperappを読み込んでいる
  - ComponentsはImport文でhyperappを読み込んでいる（npmからhyperappを取得している）

**Comment by shiro615** [comment]
`Components` の書き方は `Hello World` と同じ書き方なのでコピペするだけで何かしらの結果が得られるとより良さそう

**Comment by sndstudy** [comment]
https://github.com/hyperapp/hyperapp/blob/master/docs/advanced.md 内の
lifecycle eventのリンクが切れている

**Comment by sndstudy** [comment]
こうだったら良い

- Componentsのサンプルコードを動かす方法を詳細に書いてほしい
  - npmでhyperappを使用する方法とCDNから取得する方法の2種類あればわかりやすい
  - ソースコードをコピぺするだけで動かせるサンプルがあればわかりやすい

**Comment by sndstudy** [comment]
伝えたい内容をまずは日本語で...

タイトル
→Advanced ConceptsのComponentsセクションに記載されているサンプルコードについて

本文
→ComponentsセクションのサンプルコードについてHelloWorldと同様にコピー&ペーストで
実行できるようにした方が良いと思います。

HelloWorldのサンプルコードはHyperappをscriptタグで読み込ませているが、ComponentsのサンプルコードではHyperappをimport文で読み込ませているのでHelloWorldと同様にコピー&ペーストで実行出来るサンプルコードを掲載して欲しいです。

**Comment by sndstudy** [comment]
ComponentsとTutorialsをHelloWorld同様にコピペで動かせるように出来たらうれしい。

**Comment by kenhys** [comment]
> 伝えたい内容をまずは日本語で...

そうですね。いきなり英語で書こうとせず、まとめられた段階で英語になおすというのはよいやりかたです。

**Comment by sndstudy** [comment]
なぜ?HelloWorldと同様にコピぺが良いのか

- HelloWorldがドキュメントの一番最初にあって、コピペで動作を確認できたからそれ以降のサンプルもコピペで動くと思っていた
  - 実際はHelloWorld以外はコピペで動かなかった
  - ドキュメントによってレベル感が異なっていた
  - レベル感を揃えることで困惑しなくなる

**Comment by sndstudy** [comment]
Google翻訳に一旦全部翻訳させてみる

タイトル
> Advanced ConceptsのComponentsセクションに記載されているサンプルコードについて

About the sample code in the Components section of Advanced Concepts

本文
> ComponentsセクションのサンプルコードについてHelloWorldと同様にコピー&ペーストで
実行できるようにした方が良いと思います。

About sample code in the Components section Copy and paste like HelloWorld
I think that it would be better to be able to run.

>HelloWorldがドキュメントの一番最初にあって、コピペで動作を確認できたからそれ以降のサンプルもコピペで動くと思っていた
実際はHelloWorld以外はコピペで動かなかった
ドキュメントによってレベル感が異なっていた
レベル感を揃えることで困惑しなくなる

Since HelloWorld was at the very beginning of the document and I was able to confirm the operation with Copy, I thought that the samples after that will also run with Copy

- Actually, except for HelloWorld, it did not work with Copy

- The sense of level was different depending on the document

- It will not be confused by aligning the level feeling

>HelloWorldのサンプルコードはHyperappをscriptタグで読み込ませているが、ComponentsのサンプルコードではHyperappをimport文で読み込ませているのでHelloWorldと同様にコピー&ペーストで実行出来るサンプルコードを掲載して欲しいです。

HelloWorld sample code has Hyperapp loaded by script tag, but since we are loading Hyperapp with import statement in Components sample code, please write sample code which can be executed by copy and paste just like HelloWorld.

**Comment by sndstudy** [comment]
タイトルを
サンプルソースコードの難易度を統一して欲しい
I want you to unify the difficulty of the sample source code
に変更してみる

**Comment by sndstudy** [comment]
タイトル
I want you to unify the difficulty of the sample source code

本文
About sample code in the Components section copy and paste like HelloWorld
I think that it would be better to be able to run.

Since HelloWorld was at the very beginning of the document and I was able to confirm the operation by copy and paste, I thought that the samples after that will also be copied and pasted.

- Actually, except Copy and Paste except HelloWorld did not work
- Different degrees of difficulty depending on document
- It becomes not confusing by aligning difficulty level

HelloWorld sample code has Hyperapp loaded by script tag, but since we are loading Hyperapp with import statement in Components sample code, please write sample code which can be executed by copy and paste just like HelloWorld.

**Comment by sndstudy** [comment]
プルリク
- https://github.com/hyperapp/hyperapp/pull/574

イシュー
- https://github.com/hyperapp/hyperapp/issues/573

**Comment by kenhys** [comment]
@sndstudy 

お疲れ様でした！

今度はぜひビギナーさんをサポートするサポーターとしての参加も検討してみてください！
まだ自信がないなぁというのであれば、ビギナーとして継続的に参加するというのもよいです。
