### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-01-27: masahiko: prometheus: Work log

### ISSUE THREAD

**Issue by masahikoub** [oss-gate/workshop#717]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by masahikoub** [comment]
prometheusのページを検索する

**Comment by masahikoub** [comment]
公式ページみつけた
https://github.com/prometheus/prometheus

**Comment by masahikoub** [comment]
README.mdを参照する
https://github.com/prometheus/prometheus/blob/master/README.md

**Comment by masahikoub** [comment]
Architecture overviewみた

**Comment by shiro615** [comment]
よろしくお願いします

**Comment by masahikoub** [comment]
Install情報を見る
https://github.com/prometheus/prometheus/blob/master/README.md#install

**Comment by masahikoub** [comment]
DOWNLOADセクションを見た
https://prometheus.io/download/

**Comment by masahikoub** [comment]
公式のInstallページにとんだ
手順を確認する
https://prometheus.io/docs/prometheus/latest/installation/

**Comment by masahikoub** [comment]
Using pre-compiled binaries　を参照する

**Comment by masahikoub** [comment]
仮想マシンを用意する

**Comment by masahikoub** [comment]
仮想マシンを用意する
ローカルで

**Comment by masahikoub** [comment]
ローかマシンにログイン
rootになった

**Comment by masahikoub** [comment]
バイナリをダウンロード中
https://github.com/prometheus/prometheus/releases/download/v2.1.0/prometheus-2.1.0.linux-amd64.tar.gz

**Comment by masahikoub** [comment]
ダウンロード完了
つぎどうする？

**Comment by masahikoub** [comment]
インストール終わった

**Comment by masahikoub** [comment]
つぎはgetting_started？
次にどこに行くかの案内がない
ページの順番も前に戻ってる
https://prometheus.io/docs/prometheus/latest/getting_started/

**Comment by masahikoub** [comment]
GETTING STARTEDページを参照する
https://prometheus.io/docs/prometheus/latest/getting_started/

**Comment by masahikoub** [comment]
ダウンロードしたパッケージを展開した

**Comment by masahikoub** [comment]
起動する前に設定を変更する
https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-itself

**Comment by masahikoub** [comment]
prometheus.ymlを編集する

**Comment by masahikoub** [comment]
編集おわり

**Comment by masahikoub** [comment]
prometheusを実行する

**Comment by ashie** [comment]
↑ドキュメントの動線が上から順番に実行していくだけで動かせるようになっているといいかも? （もしかしたらフィードバックポイント）

**Comment by ashie** [comment]
↑デーモンは動いたがWebブラウザでの確認はまだできていない
単に時間が無かったか、あるいは何か障害があったのか? という点では前者とのこと

**Comment by ashie** [comment]
おそらく、トップのREADME.mdからhttps://prometheus.io/docs/prometheus/latest/getting_started/へのリンクがあると、初めて使う人にとって親切そう。そういうpull requestなりissueを投げてあげると良さそう。

開発者本人は、自分がよくわかっているだけに意外と初めて使う人に対するそういう配慮ができていないことが多い。初心者視点でこうなっているといいよという情報を伝えてあげるのも、開発者に喜ばれることも多いです。

**Comment by masahikoub** [comment]
vagrantでうまくいかなかったのでAWSにインスタンス立てる

**Comment by masahikoub** [comment]
centos7

**Comment by masahikoub** [comment]
フィードバック整理

- Downloadしたあとの次のページがわからない
- Getting Started と Install のページの順番、逆の方がいいのでは
- README.mdに Getting Startedのリンクあった方がいいのでは

**Comment by masahikoub** [comment]
これにします
- README.mdに Getting Startedのリンクあった方がいいのでは

**Comment by masahikoub** [comment]
issueじゃなくて、フォーラムに投稿した
https://groups.google.com/forum/#!forum/prometheus-users

**Comment by masahikoub** [comment]
Getting Started と Install のページの順番、逆の方がいいのでは

**Comment by swamp09** [comment]
やってみた自分の感想が、フィードバックに直結していてすごく良いです！

**Comment by swamp09** [comment]
issue ではなく、フォーラムに投稿し直して方が良いかも…？

**Comment by kenhys** [comment]
@masahikoub 

お疲れ様でした！
今度はぜひビギナーさんをサポートするサポーターとしての参加も検討してみてください！
