### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-3-10: yposi: GitLab: Work log

### ISSUE THREAD

**Issue by yposi** [oss-gate/workshop#743]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tnir** [comment]
よろしくお願いいたします。

**Comment by y-goto** [comment]
よろしくお願いします。

**Comment by yposi** [comment]
GitLab を検索してみる

**Comment by yposi** [comment]
installationwを見つけたので読んでみる。
https://about.gitlab.com/installation/

**Comment by tnir** [comment]
@ogom さんが書かれた開発環境構築の記事があります（少し古めですけども）

https://qiita.com/ogomr/items/cc404bf9373408663b11

**Comment by yposi** [comment]
おっと!!Macで動かせない?!と思ったところtnirさんのフォローがありました。
Qiitaの記事を試してみます。

**Comment by tnir** [comment]
初回のgit cloneは時間かかるかもしれないですねー。

**Comment by tnir** [comment]
メインのレポジトリはこちらです: https://gitlab.com/gitlab-org/gitlab-ce

**Comment by yposi** [comment]
GitLabのforkのやりかたでメンターと確認しました。
GitLabにサインインするとforkボタンが表示される。

GitLabのアカウントを作成する際にGitHubのアカウントと連携した。

**Comment by yposi** [comment]
Forkってこんなに時間がかかるんだ...oh no

GitLabのforkドキュメントを見た。
https://docs.gitlab.com/ce/gitlab-basics/fork-project.html

ログインしていることが前提なのかな？

**Comment by tnir** [comment]
fork遅いのを[イシュー](https://gitlab.com/gitlab-org/gitlab-ce/issues)に上げていきたいので、何分かかったか情報を収集していきたいですね。

**Comment by yposi** [comment]
Fork: 18分

**Comment by tnir** [comment]
日本語へのトランスレーションはこちらで紹介されているGitLab.JP Slackの `#translations` チャンネルでやっています。

https://gitlab-jp.connpass.com/

**Comment by yposi** [comment]
中間報告、以下のコマンドを実行したところで待機中。あと少しー。
gdk install gitlab_repo=https://gitlab.com/[name]/gitlab-ce.git

**Comment by yposi** [comment]
無事にサーバー起動できました。
<img width="1680" alt="2018-03-10 15 20 46" src="https://user-images.githubusercontent.com/29177571/37239022-be5ff7ba-2476-11e8-9852-3a65b5e6e91f.png">

**Comment by tnir** [comment]
:tada:

**Comment by yposi** [comment]
サインイン後、に表示される「Learch more about GitLab」を
クリックしたら本番のドキュメントへアクセスするので勘違いしてEditしそうになった。
http://localhost:3000/dashboard/projects

何となく意図はわかる、GitLabにコミットするからよい？

**Comment by yposi** [comment]
ここから後半の作業

**Comment by yposi** [comment]
元案

## 機能追加案
プロジェクト -> MergeRequest の検索フィルターにファイル検索がしたい。
検索結果として「Open / Merged / Closed / ALL」に条件を付与して検索できるとなおよい。

## 背景
開発途中の同じファイルをMergeRequestから見つけることができると事前に気をつけることができるので嬉しい。
また、周辺知識をいじっている人がいないかをアナログのチャットで確認することがあり、機会的にやれたら幸せかな。

**Comment by yposi** [comment]
訳

## Title
Add Search files in Merge Request component.

## Description
Any members develop same files.
I'm glad that we check the files conflicting before merge.
And I want to eliminate unnecessary chat then take care of time.

## Proposal
About - Merge Request
・Add File Filter
・Divide Open, Merged, Closed and All as before

**Comment by yposi** [comment]
さきほど、ISSUEを投げました。
https://gitlab.com/gitlab-org/gitlab-ce/issues/44118

**Comment by tnir** [comment]
日本人からの似た機能要望イシューがありますので、こちらもご参考にしてみてください。

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/16492
