### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-3-10: yoshitaku-jp: redash: Work log

### ISSUE THREAD

**Issue by yoshitaku-jp** [oss-gate/workshop#744]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by y-goto** [comment]
よろしくお願いします。

**Comment by yoshitaku-jp** [comment]
よろしくおねがいします！

**Comment by yoshitaku-jp** [comment]
redashを調べてみる

**Comment by chigix** [comment]
サポーターです、よろしくお願いします。

**Comment by yoshitaku-jp** [comment]
よろしくおねがいします！

**Comment by yoshitaku-jp** [comment]
検索結果の一番上にredashのサイトが出てきた
https://redash.io

**Comment by yoshitaku-jp** [comment]
Get Startedがあったのでアクセスしてみる
ここに始めるための手順がありそう
https://redash.io/get-started/

**Comment by yoshitaku-jp** [comment]
Plug and PlayとOpen Sourceがあった
SETUP GUIDEと書いてあるので更に進んで見る
https://redash.io/help-onpremise/setup/setting-up-redash-instance.html

**Comment by yoshitaku-jp** [comment]
Setting up a Redash Instance
Create an Instanceとあって、AWS、Google Compute Engine、Docker Compose、Otherとあった

**Comment by yoshitaku-jp** [comment]
ローカルマシーンでおこなうのでDocker Composeを使うことにする
Docker Composeのインストールからやってみることにする

**Comment by yoshitaku-jp** [comment]
Docker Composeはインストール済みだった

**Comment by yoshitaku-jp** [comment]
developer guideにアクセスする

**Comment by yoshitaku-jp** [comment]
SetupにDocker Based Developer Installation Guide (recommended for beginners)とあったので、アクセスする

**Comment by yoshitaku-jp** [comment]
Developer Installation Guide (recommended for experienced developers)もあるが、
ビギナーなのでDocker Based Developer Installation Guide (recommended for beginners)を選択する

**Comment by yoshitaku-jp** [comment]
Docker Based Developer Installation Guideのsetup手順を開始する
https://redash.io/help-onpremise/dev/docker.html

**Comment by yoshitaku-jp** [comment]
docker-compose.ymlを書く必要があるが、何を書くかが見当たらない？

**Comment by yoshitaku-jp** [comment]
docker-compose.yml redashで検索してみる
githubが一番上にヒットする
この内容を使えば良さそう？
サイトの中にgithubへの[リンク](https://github.com/getredash/redash/blob/master/docker-compose.yml)が有ると嬉しい

**Comment by yoshitaku-jp** [comment]
github内のdocker-compose.ymlファイルの中身をコピー・アンド・ペーストし、
docker-compose.ymlを作成した

**Comment by yoshitaku-jp** [comment]
docker-compose upをしてみる

**Comment by yoshitaku-jp** [comment]
Creating network "redash_default" with the default driver
Building server
ERROR: Cannot locate specified Dockerfile: Dockerfile
が起きてしまった。

**Comment by yoshitaku-jp** [comment]
Create Databaseの
```
# Create tables
docker-compose run --rm server create_db
```
を実行してみる

**Comment by yoshitaku-jp** [comment]
Creating redash_redis_1    ... done
Creating redash_postgres_1 ... done
Building server
ERROR: Cannot locate specified Dockerfile: Dockerfile
が起きてしまった。

**Comment by yoshitaku-jp** [comment]
Cannot locate specified Dockerfile: Dockerfile
について、調べてみる

**Comment by yoshitaku-jp** [comment]
git clone git@github.com:getredash/redash.git
して、dockerファイルを含めてすべてをダウンロードする必要があるみたい？

**Comment by yoshitaku-jp** [comment]
git clone https://github.com/getredash/redash.git
でクローンした
git@github.com:getredash/redash.git
だとsshの設定が必要だった

普段はgithub desktopを使っているから出来ていた？

**Comment by yoshitaku-jp** [comment]
クローンが出来たので、改めてdocker-compose upをおこなう

**Comment by yoshitaku-jp** [comment]
dockerが立ち上がったのでhttp://localhost:5000した
```
sqlalchemy.exc.ProgrammingError
ProgrammingError: (psycopg2.ProgrammingError) relation "organizations" does not exist
LINE 2: FROM organizations 
             ^
 [SQL: 'SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings \nFROM organizations \nWHERE organizations.slug = %(slug_1)s \n LIMIT %(param_1)s'] [parameters: {'slug_1': 'default', 'param_1': 1}]
```
が出た

**Comment by chigix** [comment]
https://github.com/getredash/redash/issues/1480#issuecomment-274649755

@yoshitaku-jp  多分そこに書いてある問題と同じかも。

**Comment by yoshitaku-jp** [comment]
振り返り
コメントは編集できるので、後からでも追加すると良い

- docker-compose upをするためのgit cloneが必要なことが明記されていないことがコントリビュート出来るポイント
- New developer guideがあるので、そこに賛同するコメントをすることも良いこと

他の方の振り返り
フォークする時間を計測していた

**Comment by yoshitaku-jp** [comment]
報告をする
- 整理する
- 開発者にとってわかりやすくなるように編集
- 適切な場所に報告

**Comment by yoshitaku-jp** [comment]
まずは伝えたいことを整理する

**Comment by yoshitaku-jp** [comment]
- docker-compose upをするためのgit cloneが必要なことが明記されていないことがコントリビュート出来るポイント
こちらについて書いてみる

https://redash.io/help-onpremise/dev/docker.html

**Comment by yoshitaku-jp** [comment]
ページ内で
>### Setup
>### Create Docker Services
>Once you have the above setup, you need to create the Docker services:
>`docker-compose up`
>This will build the Docker images and fetch some prebuilt images and then start the services (Redash web server, worker, PostgreSQL and Redis). You can refer to the `docker-compose.yml` file to see the full configuration.

と記述してあるが、`docker-compose up`をする前に、
https://github.com/getredash/redashをクローンしてくることが書いていない

その記述がある方が、ビギナー向け記事としては良いと思うので、
そのことを追記した方がいい旨を書く

**Comment by yoshitaku-jp** [comment]
そもそもDocker Based Developer Installation Guide (recommended for beginners)ページの
recommended for beginnersが、誰を指しているのか。
本当の何もかもの初心者なのか、redashを使ったことがないだけでdockerについての知識はある人なのか
考える必要もあるのかも。

**Comment by yoshitaku-jp** [comment]
https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
の
Docker Compose
Make sure your current working directory is the root of this GitHub repository.
とあるので、
githubからcloneするか、dockerhubから落としてくるのかの議論があったが、
githubからcloneする方法のみを追記してほしい旨を伝えることにする

**Comment by yoshitaku-jp** [comment]
dockerでredashを使用するためには、ローカルに落としてくる必要がある
- GitHubからcloneする

GitHubからcloneする
```
git clone git@github.com:getredash/redash.git
cd redash/
docker-compose up
```
とすれば適切？

**Comment by yoshitaku-jp** [comment]
コマンドを一緒にした方がいいかと思ったが、
Create Docker Servicesの項にいれるのは適切ではないので、
git cloneをする 項を新しく作る
`git clone git@github.com:getredash/redash.git`
ほうがいい

**Comment by yoshitaku-jp** [comment]
ここからフィードバックする内容（日本語

## redashをクローンする
まずはredashをGitHubからクローンする

```
git clone git@github.com:getredash/redash.git
cd redash/
```

**Comment by yoshitaku-jp** [comment]
## Git Clone Redash
At the beginning clone Redash from GitHub
```
git clone git@github.com:getredash/redash.git
cd redash/
```

**Comment by yoshitaku-jp** [comment]
- 一番上のところはコマンドを書くわけではないので、一旦やめてみる
- 他の項目が動詞から始まっているので、動詞で初めてみる
    - Prepare The Source code とか
- 説明文も、コマンドを繰り返す必要がなく、何をするのかを簡潔に説明する
    - Firstly, you need to setup the source code directory from the official repository. とか

## Git Clone Redash
Firstly, you need to setup the source code directory from the official repository.
```
git clone git@github.com:getredash/redash.git
cd redash/
```

**Comment by yoshitaku-jp** [comment]
プルリクエストをしてみた
https://github.com/getredash/website/pull/65

**Comment by yoshitaku-jp** [comment]
- git プロトコルをあまり使うべきではない
    - httpsやsshのほうがいい
- なぜ必要になったのかの説明を書いたほうがいい
    - 人によっては聞かれる
- コミットメッセージをもっと伝わりやすく

今後
- push -fでプルリクエストを修正する

他の方の振り返り
- 日本語でちゃんと論理建ててみる
- 簡単な英語でいいからまずは伝わる英語で表現してみる
- 第二文系でまずは考える
    - 「です」「ます」調に近いから

**Comment by kou** [comment]
お疲れ様でした！
