### ISSUE TITLE
OSS Gate Workshop: osaka: 2018-03-10: takeoverjp: gitlab: Work log

### ISSUE THREAD

**Issue by takeoverjp** [oss-gate/workshop#747]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by murajun1978** [comment]
今日のサポーターですー 😄 
よろしくお願いしますー

**Comment by takeoverjp** [comment]
gitlabで検索してみる。
https://about.gitlab.com/

**Comment by takeoverjp** [comment]
contributeの仕方を知るために、Communityを見てみる。

**Comment by takeoverjp** [comment]
https://about.gitlab.com/community/

**Comment by takeoverjp** [comment]
ContributerとContributingは何が違うんだろう？

**Comment by takeoverjp** [comment]
Contributingを開いてみる。
https://about.gitlab.com/contributing/

**Comment by takeoverjp** [comment]
GitLab Development Kitなるものがあるらしい。
https://gitlab.com/gitlab-org/gitlab-development-kit

**Comment by takeoverjp** [comment]
ソースコードがダウンロードできるっぽい。

**Comment by takeoverjp** [comment]
でもリポジトリなのか不明。

**Comment by takeoverjp** [comment]
とりあえず、下記をダウンロード。
https://gitlab.com/gitlab-org/gitlab-development-kit/repository/master/archive.zip

**Comment by takeoverjp** [comment]
gitリポジトリじゃなかった…

**Comment by takeoverjp** [comment]
"Copy URL to Clipboard"を発見。
https://gitlab.com/gitlab-org/gitlab-development-kit.git

**Comment by takeoverjp** [comment]
git cloneしてみる
$ git clone https://gitlab.com/gitlab-org/gitlab-development-kit.git

**Comment by takeoverjp** [comment]
gitlab development kitのREADMEを見てみる。
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/README.md

**Comment by takeoverjp** [comment]
gitlab development kitに対するcontributeもあるのか…

```
Contributing` to GitLab Development Kit

Contributions are welcome, see CONTRIBUTING.md
for more details.
```

**Comment by takeoverjp** [comment]
git lab CEは、Community Editionの略。

**Comment by takeoverjp** [comment]
gitlab CEのforkの前に、GDKのセットアップをする。

**Comment by takeoverjp** [comment]
rubyのバージョン指定があるらしい。
```
The current gitlab-ce Ruby version installed with a Ruby version manager
(RVM, rbenv, chruby, etc.), DO NOT use the
system Ruby
```

**Comment by takeoverjp** [comment]
2.3.6
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/.ruby-version

**Comment by takeoverjp** [comment]
RVM, rbenv, chrubyのどれを使えばいいんだろう…

**Comment by takeoverjp** [comment]
rbenvで2.3.6をインストールしてみよう。

**Comment by takeoverjp** [comment]
sudo apt install rbenv

**Comment by takeoverjp** [comment]
```
$ rbenv init
$  echo 'eval "$(rbenv init -)"' >> ~/.bashrc
$ . ~/.bashrc
$ rbenv install 2.3.6
rbenv: no such command `install'
```
なぜ？？？

**Comment by takeoverjp** [comment]
rbenv install でググッて見る。
https://qiita.com/inouet/items/478f4228dbbcd442bfe8

$ rbenv install --list
rbenvのinstallサブコマンドが入っていない。

サポータの方から、rbenvのリンクを見てみたら？と助言をいただく。
https://github.com/rbenv/rbenv

**Comment by takeoverjp** [comment]
mac OS の手順しか、書かれていないので、ソースからインストールしてみる。

**Comment by takeoverjp** [comment]
さっきaptでいれたrbenvを消しておく

$ sudo apt remove rbenv

**Comment by takeoverjp** [comment]
$ rm -rf ~/.rbenv

$ git clone https://github.com/rbenv/rbenv.git ~/.rbenv

**Comment by takeoverjp** [comment]
> Optionally, try to compile dynamic bash extension to speed up rbenv. Don't worry if it fails; rbenv will still work normally:

と言われてもこけたら気になるよなー

**Comment by takeoverjp** [comment]
$ cd ~/.rbenv && src/configure && make -C src
自分の環境では、幸いビルドが成功した。

**Comment by takeoverjp** [comment]
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile

.bash_profileがデフォルトで読み込まれなかったので、.bashrcに下記を追加。
```
if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile
fi
```

**Comment by takeoverjp** [comment]
後ろに、.bashrcにやるべきと書いてあった…
```
Ubuntu Desktop note: Modify your ~/.bashrc instead of ~/.bash_profile.
```

**Comment by tnir** [comment]
Debian系でapt使ってrbenv入れないほうがいいってことなんですかね。

**Comment by takeoverjp** [comment]
$ ~/.rbenv/bin/rbenv init
$  echo 'eval "$(rbenv init -)"' >> ~/.bash_profile

**Comment by takeoverjp** [comment]
```
$ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /home/kondo/.rbenv/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: bash: 行 114: : コマンドが見つかりません
 ()
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/home/kondo/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

**Comment by tnir** [comment]
今日は 2018-03-11 でなく、 2018-03-10 かもしれないです。

**Comment by takeoverjp** [comment]
後ろにruby-build入れろって書いてあった…
(Optional) Install ruby-build, which provides the rbenv install command that simplifies the process of installing new Ruby versions.

**Comment by takeoverjp** [comment]
https://github.com/rbenv/ruby-build#readme

**Comment by takeoverjp** [comment]
@tnir ありがとうございます！修正しました！

**Comment by takeoverjp** [comment]
別のページ（wiki）に依存パッケージの情報が書かれている。
https://github.com/rbenv/ruby-build/wiki

$ sudo apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev

**Comment by takeoverjp** [comment]
```
mkdir -p "$(rbenv root)"/plugins
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
```

**Comment by takeoverjp** [comment]
$ rbenv install --list
うごいた！

**Comment by takeoverjp** [comment]
$ rbenv install 2.3.6
Installing ruby-2.3.6...
待ってる

**Comment by takeoverjp** [comment]
何したかったか忘れた

**Comment by takeoverjp** [comment]
Prepare Your Computerだった。
次は、`gem install bundler`

**Comment by takeoverjp** [comment]
ちょっと先読みしていると、git version 2.14.3以上が必要らしい。
Ubuntu 16.04のデフォルトだと、2.7.4にだった…

**Comment by takeoverjp** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md#ubuntu

```
# Add apt-add-repository helper script
sudo apt-get install software-properties-common python-software-properties
# This PPA contains an up-to-date version of Go
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install git postgresql postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ nodejs nodejs-legacy npm libre2-dev libkrb5-dev libsqlite3-dev golang-1.8-go ed pkg-config

```

**Comment by takeoverjp** [comment]
```
$ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
$ sudo gem install bundler
```

**Comment by takeoverjp** [comment]
次はSetUpGDK。
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md

**Comment by takeoverjp** [comment]
aptが終わらん

**Comment by tshkh8** [comment]
セットアップの際に、一般的な手順の後にubuntu用のセットアップ手順が載っているので、そこを見る前に作業をしてしまって、後からやり直しになってしまった。
なので、手順に、「ubuntuについては下を見ろ」のようなコメントがあれば今回のような失敗は避けられるかもしれません。
これは一つフィードバックポイントになるかと思います。

**Comment by tnir** [comment]
>  なので、手順に、「ubuntuについては下を見ろ」のようなコメントがあれば今回のような失敗は避けられるかもしれません。

https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md について、ですよね。私も昔は感じましたが、分かりやすい形にしていきたいですね。

**Comment by takeoverjp** [comment]
gem installで、システムにインストールされてしまっていたが、rbenv rehashしたらローカルに貼るようになった。

**Comment by takeoverjp** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md#ubuntu

[課題]
要件には、"Git version of 2.14.3 or higher"とあるが、Ubuntu 16.04で手順通り実行すると、2.7.4がインストールされてしまう。

[環境]
Ubuntu 16.04 amd64

[元の手順]
```
# Add apt-add-repository helper script
sudo apt-get install software-properties-common python-software-properties
# This PPA contains an up-to-date version of Go
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install git postgresql postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ nodejs nodejs-legacy npm libre2-dev libkrb5-dev libsqlite3-dev golang-1.8-go ed pkg-config
```

``` 
$ git --version
git version 2.7.4
```

[改善案]
```
# Add apt-add-repository helper script
sudo apt-get install software-properties-common python-software-properties
# This PPA contains an up-to-date version of Go
sudo add-apt-repository ppa:longsleep/golang-backports
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git postgresql postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ nodejs nodejs-legacy npm libre2-dev libkrb5-dev libsqlite3-dev golang-1.8-go ed pkg-config
```

``` 
$ git --version
git version 2.16.2
```

**Comment by takeoverjp** [comment]
[Summary]
  Add git PPA registry for Ubunt 16.04 on preparation docs.

[Reason]
  In "Prerequisites for all platforms", it requires "Git version of 2.14.3 or higher".
  However, I installed with the written ubuntu procedure, git 2.7.4 had been installed.

[Environment]
   Ubuntu 16.04 amd64

[Original]
```
# Add apt-add-repository helper script
sudo apt-get install software-properties-common python-software-properties
# This PPA contains an up-to-date version of Go
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install git postgresql postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ nodejs nodejs-legacy npm libre2-dev libkrb5-dev libsqlite3-dev golang-1.8-go ed pkg-config
```

``` 
$ git --version
git version 2.7.4
```

[After]
```
# Add apt-add-repository helper script
sudo apt-get install software-properties-common python-software-properties
# This PPA contains an up-to-date version of Go
sudo add-apt-repository ppa:longsleep/golang-backports
# This PPA contains an up-to-date version of git
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git postgresql postgresql-contrib libpq-dev redis-server libicu-dev cmake g++ nodejs nodejs-legacy npm libre2-dev libkrb5-dev libsqlite3-dev golang-1.8-go ed pkg-config
```

``` 
$ git --version
git version 2.16.2
```

**Comment by takeoverjp** [comment]
1st Contribution!!!
https://gitlab.com/gitlab-org/gitlab-development-kit/merge_requests/441

**Comment by takeoverjp** [comment]
セットアップ再開。
$ gdk init

**Comment by takeoverjp** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md

下記で、"Community Contribution"と表示されるはずが、"Accepting Merge Requests"と表示されている。

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#label-for-community-contributors-accepting-merge-requests

**Comment by tnir** [comment]
基本的には、[Community Contribution](https://gitlab.com/gitlab-org/gitlab-ce/issues?label_name=Community+Contribution)ラベルはCommunityから来たMerge Request(s)の管理用で、 [Accepting Merge Requests](https://gitlab.com/gitlab-org/gitlab-ce/issues?label_name=Accepting+Merge+Requests)ラベルはCommunityからMerge Request(s)を受け付けているIssue(s)用、という使い分けがあります。

なので、CONTRIBUTING.md読者のうちcommunity contributorsの方に、着手してほしいイシュー（のラベル）が[Accepting Merge Requests](https://gitlab.com/gitlab-org/gitlab-ce/issues?label_name=Accepting+Merge+Requests)なのだと思います。（分かりにくいですか？）

**Comment by takeoverjp** [comment]
@tnir 
ありがとうございます。
プルリクに"Community Contribution"ラベルをつけていただいたので、どーゆーいみかなーと思ってCONTRBUTING.mdを見て疑問になってしまいました。

**Comment by takeoverjp** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md#ubuntu

yarnのインストールが記載されていない。

**Comment by znz** [comment]
振り返りました。

**Comment by tnir** [comment]
Yarnについてはprerequisites:

https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md#prerequisites-for-all-platforms

に、コマンドでなく、日本語で書かれています。prerequisitesの一部も各種パッケージマネージャ（Homebrew, yum, apt etc.）でインストールする例もあり、分かりづらいですよね。

**Comment by takeoverjp** [comment]
そうなんですよね。共通部分とOSごとに書かれている部分とで、片方だけ書かれていたり両方に書かれていたりするので、迷いました。メンテナンスが大変なことはわかりますが、統一できればわかりやすくなりそうですね。

**Comment by tnir** [comment]
@takeoverjp はい。なので、全OSの部分の冒頭に `Please read the prerequisites for all platforms.` と書いているようです。非英語話者に対しても見落とされないようにするしかないですかね。

**Comment by yoichi** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/kansai です！
