### ISSUE TITLE
OSS Gate Workshop: osaka: 2018-03-10: honeniq: gitlab: Work log

### ISSUE THREAD

**Issue by honeniq** [oss-gate/workshop#748]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by znz** [comment]
よろしくお願いします。

**Comment by honeniq** [comment]
GitLabを使おうとしてみる
まずgitlabでぐぐる

**Comment by honeniq** [comment]
公式サイトっぽいのがあったので見てみる
https://about.gitlab.com/

**Comment by honeniq** [comment]
まず使うだけなので、ダウンロード的なリンクを探す

**Comment by honeniq** [comment]
一番上のメニューにInstallがあったのでここをみてみる
https://about.gitlab.com/installation/

**Comment by honeniq** [comment]
OSがUbuntu系なのでUbuntu用のインストーラを使う
https://about.gitlab.com/installation/#ubuntu

**Comment by honeniq** [comment]
インストール手順があったので上からやっていく
```
sudo apt-get update
sudo apt-get install -y curl openssh-server ca-certificates
\
```

**Comment by honeniq** [comment]
コマンドどっちもエラーなく完了

**Comment by honeniq** [comment]
次はPostfixを入れるらしい
```
sudo apt-get install -y postfix
```

**Comment by honeniq** [comment]
公式サイトの手順と同様に、TUIのウィザードが出てきた
OSを日本語化しているので「Internet Site」ではなく「インターネットサイト」を選ぶ

**Comment by honeniq** [comment]
ウィザードで「メール名」を聞かれたけど、今回は試しに使うので「example.com」にする
メール名はメールアドレスの@以降のことを指すらしい　ドメイン名？

**Comment by honeniq** [comment]
エラーなく完了

**Comment by honeniq** [comment]
GitLabのリポジトリを追加する・・・と思いきや、
リポジトリがEnterpriseEditionのものだったので中断してCommunityEditionをさがす

**Comment by honeniq** [comment]
CE or EEというリンクがあったので見てみる
https://about.gitlab.com/installation/ce-or-ee/?distro=ubuntu

**Comment by honeniq** [comment]
一番下に Install GitLab Community Edition. のリンクがあったので見てみる
https://about.gitlab.com/installation/ce-or-ee/?distro=ubuntu

**Comment by honeniq** [comment]
手順は同じなので、項番1を飛ばして2からはじめる
あらためてリポジトリの追加
```
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
```

**Comment by honeniq** [comment]
エラーなく完了

**Comment by honeniq** [comment]
気づいていなかったけど、メモリは4GB以上いるらしい

**Comment by honeniq** [comment]
続いてGitLabをインストールする
外部公開用URLを指定するらしいけど、ローカルで実行するのでローカルっぽいのにする
```
sudo EXTERNAL_URL="http://localhost" apt-get install gitlab-ce
```

**Comment by honeniq** [comment]
エラーでた

```
 sudo EXTERNAL_URL="http://localhost" apt-get install gitlab-ce
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
E: パッケージ gitlab-ce が見つかりません
```

**Comment by honeniq** [comment]
gitlabのパッケージを探してみる

```
 apt search gitlab
p   gitlab                          - git powered software platform to collabora
p   gitlab-shell                    - handles git commands for GitLab           
p   gitlab-workhorse                - unloads Git HTTP traffic from the GitLab R
p   gitlab-workhorse:i386           - unloads Git HTTP traffic from the GitLab R
p   python-gitlab                   - Python wrapper for the GitLab API (Python 
v   python2.7-gitlab                -                                           
p   python3-gitlab                  - Python wrapper for the GitLab API (Python 
p   ruby-gemnasium-gitlab-service   - Gemnasium service for Gitlab              
p   ruby-gitlab-emoji               - gem for emojis in GitLab                  
p   ruby-gitlab-flowdock-git-hook   - Git Post-Receive hook for Flowdock        
p   ruby-gitlab-git                 - Gitlab::Git library                       
p   ruby-omniauth-gitlab            - OAuth2 strategy for authenticating to GitL
```

**Comment by honeniq** [comment]
/etc/apt/sources.list.d/gitlab_gitlab-ce.list を見ると
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
```

となっていた。
Linux Mint用のパッケージはないので見つからなかった？

**Comment by honeniq** [comment]
Ubuntuのフリをしてみる

```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

# deb https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
# deb-src https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
```

**Comment by honeniq** [comment]
apt update した

**Comment by honeniq** [comment]
```
sudo EXTERNAL_URL="http://localhost" apt-get install gitlab-ce
```

をもう一回たたく

**Comment by honeniq** [comment]
いけたぽい
427MBダウンロードまち

**Comment by honeniq** [comment]
Chefががんばっている
正座してまつ

**Comment by honeniq** [comment]
ロゴでました

```
       *.                  *.
      ***                 ***
     *****               *****
    .******             *******
    ********            ********
   ,,,,,,,,,***********,,,,,,,,,
  ,,,,,,,,,,,*********,,,,,,,,,,,
  .,,,,,,,,,,,*******,,,,,,,,,,,,
      ,,,,,,,,,*****,,,,,,,,,.
         ,,,,,,,****,,,,,,
            .,,,***,,,,
                ,*,.
  


     _______ __  __          __
    / ____(_) /_/ /   ____ _/ /_
   / / __/ / __/ /   / __ `/ __ \
  / /_/ / / /_/ /___/ /_/ / /_/ /
  \____/_/\__/_____/\__,_/_.___/
  
```

**Comment by honeniq** [comment]
localhostみてみる

**Comment by honeniq** [comment]
GitLab開いた
ログイン画面になった

**Comment by honeniq** [comment]
公式ドキュメントにもどる
rootで入ったらいいのか

**Comment by honeniq** [comment]
まずはrootのパスワードを変更するらしい
New PasswordとConfirm new passwordをいれる

**Comment by honeniq** [comment]
rootでさっきのパスワードでログインしてみる

**Comment by honeniq** [comment]
入れた
トップページがでた

**Comment by honeniq** [comment]
公式ドキュメントによると、メールアドレスを登録せよとのこと

**Comment by honeniq** [comment]
アップデートの通知とかがくるみたい
必要ないので登録はしない

**Comment by honeniq** [comment]
インストール手順は完了したので、もう使えるのではないか

**Comment by honeniq** [comment]
ユーザーがrootだと気持ち悪いので、自分のを作る

**Comment by honeniq** [comment]
Add perpleかな？

**Comment by honeniq** [comment]
ぽい
honeniqユーザーをつくる

**Comment by honeniq** [comment]
Projects limitという設定値があった
初期値10万　そんなに作る？

**Comment by honeniq** [comment]
登録メールがくるのかな？

**Comment by honeniq** [comment]
こない

**Comment by honeniq** [comment]
postfixが送れていないのではないか

**Comment by honeniq** [comment]
```
 postqueue -p
-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
734C5C6F3D     2660 Sat Mar 10 14:15:51  gitlab@localhost
(connect to alt2.gmail-smtp-in.l.google.com[2607:f8b0:4001:c0e::1a]:25: Connection refused)
                                         honeniq@gmail.com

4C315C6F3A     7565 Sat Mar 10 14:10:22  gitlab@localhost
              (connect to example.com[93.184.216.34]:25: Connection timed out)
                                         admin@example.com

-- 9 Kbytes in 2 Requests.
```

**Comment by honeniq** [comment]
GMailが謎のMTAからのメールを蹴ったみたい　つらい

**Comment by honeniq** [comment]
rootからhoneniqユーザーのパスワードをリセットできたりしないか見てみる

**Comment by honeniq** [comment]
ユーザー情報のEditからパスワードを入力できそう

**Comment by honeniq** [comment]
変更できたぽい

**Comment by honeniq** [comment]
honeniqでログインしてみる
できた

**Comment by honeniq** [comment]
パスワードを変更しろと言われる
変更する

**Comment by honeniq** [comment]
新旧同じパスワードにしてみた
問題なく通った

**Comment by honeniq** [comment]
ログインもできた
これはOK？？

**Comment by honeniq** [comment]
Create a project　してみる

**Comment by honeniq** [comment]
hogeプロジェクト爆誕

**Comment by honeniq** [comment]
Publicにしてみる

**Comment by honeniq** [comment]
できた

**Comment by honeniq** [comment]
Pullする前にSSHキーを入れろとのこと

**Comment by honeniq** [comment]
add an SSH keyのリンクがオススメされているのでそちらを見る
http://localhost/profile/keys

**Comment by honeniq** [comment]
SSHキー入れる
~/.ssh/id_rsa.pub　の中身を貼り付ける

**Comment by honeniq** [comment]
入った
Fingerprintがでた

**Comment by honeniq** [comment]
これでPullできるはずなので、さっき作ったプロジェクトのページにもどる

**Comment by honeniq** [comment]
ページ左上のロゴからトップページにもどる

**Comment by honeniq** [comment]
プロジェクト一覧が見えているので、さっき作ったやつを選ぶ

**Comment by honeniq** [comment]
http://localhost/honeniq/hoge

**Comment by honeniq** [comment]
gitコマンド用のパスが載っているので、これをつかう
「git@localhost:honeniq/hoge.git」

**Comment by honeniq** [comment]
```
git clone git@localhost:honeniq/hoge.git
```

**Comment by honeniq** [comment]
SSH初回なのでGitLab側のキーをknown_hostにいれる
yes

**Comment by honeniq** [comment]
cloneでけた

**Comment by honeniq** [comment]
```
cd hoge
 ls -al
合計 12
drwxrwxr-x 3 honeniq honeniq 4096  3月 10 14:29 ./
drwxrwxr-x 3 honeniq honeniq 4096  3月 10 14:29 ../
drwxrwxr-x 7 honeniq honeniq 4096  3月 10 14:30 .git/
```

**Comment by honeniq** [comment]
空のリポジトリができた

**Comment by honeniq** [comment]
GitLabのプロジェクトページ、つくりたてのときはガイダンス的な手順がでてくる

**Comment by honeniq** [comment]
せっかくなので手順にしたがって、READMEを書いたりする

**Comment by honeniq** [comment]
```
touch README.md
nvim README.md
```

**Comment by honeniq** [comment]
```
git add README.md
git commit -m "add README"
```

**Comment by honeniq** [comment]
```
git push -u origin master

```

**Comment by honeniq** [comment]
プッシュできたぽい

**Comment by honeniq** [comment]
http://localhost/honeniq/hoge
ページ更新したらREADMEが反映されていた

**Comment by honeniq** [comment]
ちょっと設定画面とかみてみる

**Comment by honeniq** [comment]
rootユーザーで右上のアイコン　→　Setting

**Comment by honeniq** [comment]
これは個人設定の予感

**Comment by honeniq** [comment]
画面上部のスパナみたいなアイコンがあやしい
Admin areaだ

**Comment by murajun1978** [comment]
ドキュメントのURLとかあると、見直したときにわかりやすいと思います 😸

**Comment by honeniq** [comment]
ここまでまあまあ順調にきているけど、インストール手順でいきなり外部公開用URLとかPostfix用のドメイン名を指定させられるので、気楽に試したい人はウッとなるかもしれない

**Comment by murajun1978** [comment]
感情をoutputするのはGoodです 💯

**Comment by honeniq** [comment]
https://github.com/oss-gate/workshop/issues/748#issuecomment-372002805
ここでリポジトリを追加してるけど、Linux Mintの人も裏でUbuntuに変換して登録したりしてくれるといいかもしれない

**Comment by znz** [comment]
gitlab-runner だと linuxmint に対応しているようなので、 gitlab-ce の方も対応してもらえる可能性はありそう。
https://gitlab.com/gitlab-org/gitlab-runner/blob/d3052a006cac89bb2d751cb4484df9d7857a452d/Makefile

**Comment by honeniq** [comment]
## やってほしいこと

Linux MintはUbuntuファミリーなので、Ubuntu用のOmnibus Packageが選択されるようにしてほしい。


## 実行したコマンド
```
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
```

## 期待される動き
Linux Mintの環境でも、↑の結果で生成されるファイルが
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
```
となってほしい。


## 実際の動き
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
```
こう生成される。linuxmint用のパッケージは実際には存在しないので、aptでエラーになる

**Comment by honeniq** [comment]
## 概要

Linux Mintの環境で、
https://about.gitlab.com/installation/#ubuntu?version=ce
この手順にしたがってインストールを進めていたが、GitLabのAPTリポジトリを追加してインストールする際にパッケージが見つからずエラーになった。

Linux MintはUbuntuファミリーなので、Ubuntu用のOmnibus Packageが選択されるようにしてほしい。

## 環境

Linux Mint 18.2 Sonya

```
$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"
```


## 実行したコマンド

```
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
```


## 期待される動き
Linux Mintの環境でも、↑の結果で生成されるファイルが
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
```
となってほしい。


## 実際の動き
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
```
こう生成される。linuxmint用のパッケージは実際には存在しないので、``apt install gitlab-ce``でエラーになる

**Comment by honeniq** [comment]
悪戦苦闘して書いてみました


### Description

I followed the [installation method for ubuntu](https://about.gitlab.com/installation/#ubuntu?version=ce) on my Linux Mint machine.
When running ``apt-get install gitlab-ce'', apt couldn't find the package.

The script([script.deb.sh](https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh) detects ``${os}`` and ``${dist}`` params from ``/etc/lsb-release`` and generates ``/etc/apt/sources.list.d/gitlab_gitlab-ce.list``. But, these params different between Ubuntu and Linux Mint.

* Ubuntu 16.04
  * os: ubuntu
  * dist: xenial
* Linux Mint 18.2
  * os: linuxmint
  * dist: sonya

#### ``script.deb.sh`` results on Linux Mint

``/etc/apt/sources.list.d/gitlab_gitlab-ce.list``
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
```

It points a invalid path ``https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/``.


### Proposal

When Linux Mint, convert ``${os}`` and ``${dist}`` params to same as Ubuntu.

#### ``script.deb.sh`` expected results on Linux Mint

``/etc/apt/sources.list.d/gitlab_gitlab-ce.list``
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
```

### Links / references

I found similar issue [#24590](https://gitlab.com/gitlab-org/gitlab-ce/issues/24590), but it seems to be not active.

**Comment by honeniq** [comment]
# Installation method for Ubuntu should be running on Linux Mint too.

### Description

I followed the [installation method for ubuntu](https://about.gitlab.com/installation/#ubuntu?version=ce) on my Linux Mint machine.
When running ``apt-get install gitlab-ce'', apt couldn't find the package.

The script([script.deb.sh](https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh) detects ``${os}`` and ``${dist}`` params from ``/etc/lsb-release`` and generates ``/etc/apt/sources.list.d/gitlab_gitlab-ce.list``. But, these params different between Ubuntu and Linux Mint.

* Ubuntu 16.04
  * os: ubuntu
  * dist: xenial
* Linux Mint 18.2
  * os: linuxmint
  * dist: sonya

#### ``script.deb.sh`` results on Linux Mint

``/etc/apt/sources.list.d/gitlab_gitlab-ce.list``
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/ sonya main
```

It points a invalid path ``https://packages.gitlab.com/gitlab/gitlab-ce/linuxmint/``.


### Proposal

When Linux Mint, convert ``${os}`` and ``${dist}`` params to same as Ubuntu.

#### ``script.deb.sh`` expected results on Linux Mint

``/etc/apt/sources.list.d/gitlab_gitlab-ce.list``
```
# this file was generated by packages.gitlab.com for
# the repository at https://packages.gitlab.com/gitlab/gitlab-ce

deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main
```

After fix this, the method works on Linux Mint.


### Links / references

I found similar issue [#24590](https://gitlab.com/gitlab-org/gitlab-ce/issues/24590), but it seems to be inactive.

**Comment by honeniq** [comment]
Issue投げました！
https://gitlab.com/gitlab-org/gitlab-ce/issues/44120

**Comment by tnir** [comment]
FYI https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3273

**Comment by yoichi** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/kansai です！
