### ISSUE TITLE
OSS Gate Workshop: osaka: 2018-03-10: yasu43: GitLab: Work log

### ISSUE THREAD

**Issue by yasu43** [oss-gate/workshop#749]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by chimame** [comment]
メンターとしてお手伝いさせていただきます。よろしくお願いします！

**Comment by yasu43** [comment]
gitlab をググった
https://about.gitlab.com/

**Comment by yasu43** [comment]
https://about.gitlab.com/contributing/ を読む

**Comment by yasu43** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit
READMEを読む

**Comment by yasu43** [comment]
preparing computing読む
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md

**Comment by yasu43** [comment]
nstall OS X prerequisites using homebrewに書いてあるコマンドの通りインストールしてみる
`brew install git redis postgresql@9.6 libiconv icu4c pkg-config cmake nodejs go openssl node npm yarn coreutils re2`

**Comment by yasu43** [comment]
インストールしている間にSetupGDKを読む
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md

**Comment by yasu43** [comment]
bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include
でエラー
zsh: correct 'bundle' to '_bundle' [nyae]?

**Comment by yasu43** [comment]
エラー
zsh: command not found: bundle

**Comment by yasu43** [comment]
ruby bundlerがないのでうまくいかない

**Comment by yasu43** [comment]
bundl インストール
gem install bundler

**Comment by yasu43** [comment]
gem install gitlab-development-kit

**Comment by yasu43** [comment]
gdk init

**Comment by yasu43** [comment]
Install GDKを読む

**Comment by tnir** [comment]
> ruby bundlerがないのでうまくいかない

bundlerインストールについては、

```
3. Bundler, which you can install with gem install bundler
```

と書いてあって、コマンドになっていないので、注意が必要な状況ですね。

**Comment by yasu43** [comment]
gdk install

**Comment by yasu43** [comment]
エラー

The current working directory is not inside a gitlab-development-kit
installation. Use 'cd' to go to your gitlab-development-kit or create
a new one with 'gdk init'.

gdk init [DIRECTORY] # Default: /Users/yasu/gitlab-development-kit

**Comment by yasu43** [comment]
ディレクトリ移動して
gdk install

**Comment by yasu43** [comment]
インストールしてる間にPost-installationを読む

**Comment by yasu43** [comment]
まだインストールがかかりそうなのでHow to use GitLab Development Kitを読む
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/README.md

**Comment by yasu43** [comment]
複数のエラーが出た

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

An error occurred while installing nokogiri (1.8.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.2'` succeeds before bundling.

An error occurred while installing charlock_holmes (0.7.5), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.5'` succeeds before bundling.

An error occurred while installing pg (0.18.4), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.

An error occurred while installing re2 (1.1.1), and Bundler cannot continue.
Make sure that `gem install re2 -v '1.1.1'` succeeds before bundling.

An error occurred while installing sqlite3 (1.3.13), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.3.13'` succeeds before bundling.

**Comment by yasu43** [comment]
エラーメッセージにあるコマンドを実行してみる
bundle config build.nokogiri --use-system-libraries

**Comment by yasu43** [comment]
bundle install

**Comment by znz** [comment]
振り返りました。

**Comment by yasu43** [comment]
error: delegating constructors are permitted only in C++11

**Comment by yasu43** [comment]
ググって見つけたコマンドを試す
https://qiita.com/siso9to/items/8461ca7ebf0eba5eb8fa
bundle config --local build.charlock_holmes -- --with-cxxflags=-std=c++11

**Comment by yasu43** [comment]
もう一度
gdk install

**Comment by yasu43** [comment]
gem install pkg-config -v "~> 1.1"

**Comment by yasu43** [comment]
nokogiri単体でもインストールできなかったので
gem install nokogiri -- --use-system-libraries
実行

**Comment by chimame** [comment]
これで必要パッケージ入らないでしょうか？
```bash
$ brew install libxml2 libxslt libiconv
$ brew link --force libxml2
$ brew link --force libxslt
```

**Comment by yasu43** [comment]
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
Using pkg-config gem version 1.2.9
checking for libxml-2.0... yes
checking for libxslt... yes
checking for libexslt... yes
checking for xmlParseDoc() in libxml/parser.h... no
checking for xmlParseDoc() in -lxml2... no
checking for xmlParseDoc() in -llibxml2... no
-----
libxml2 is missing.  Please locate mkmf.log to investigate how it is failing.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by chimame** [comment]
これで！

```bash
gem install nokogiri -- --use-system-libraries --with-iconv-dir="$(brew --prefix libiconv)" --with-xml2-config="$(brew --prefix libxml2)/bin/xml2-config" --with-xslt-config="$(brew --prefix libxslt)/bin/xslt-config"
```

**Comment by chimame** [comment]
```bash
xcode-select --install
```

**Comment by yasu43** [comment]
"xcrun clang -o conftest -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17 -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I. -I/usr/local/Cellar/libxml2/2.9.7/include/libxml2 -I/usr/local/Cellar/libxslt/1.1.32/include -I/usr/local/Cellar/libxml2/2.9.7/include/libxml2 -I/usr/local/Cellar/libxslt/1.1.32/include -I/usr/local/Cellar/libxml2/2.9.7/include/libxml2 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -iwithsysroot /usr/local/libressl/include     conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L/usr/local/Cellar/libxml2/2.9.7/lib -L/usr/local/Cellar/libxslt/1.1.32/lib -L/usr/local/Cellar/libxml2/2.9.7/lib -L/usr/local/Cellar/libxslt/1.1.32/lib -L/usr/local/Cellar/libxml2/2.9.7/lib   -arch x86_64 -arch i386   -lxml2 -lxslt -lxml2 -lz -lpthread -liconv -lm -lexslt -lxslt -lxml2 -lz -lpthread -liconv -lm -lruby.2.3.0 -llibxml2  -lxml2 -lxslt -lxml2 -lz -lpthread -liconv -lm -lexslt -lxslt -lxml2 -lz -lpthread -liconv -lm -lpthread -ldl -lobjc  "
conftest.c:15:13: error: conflicting types for 'xmlParseDoc'
extern void xmlParseDoc();
            ^
/usr/local/Cellar/libxml2/2.9.7/include/libxml2/libxml/parser.h:842:3: note: previous declaration is here
                xmlParseDoc             (const xmlChar *cur);
                ^
conftest.c:16:27: error: too few arguments to function call, single argument 'cur' was not specified
int t(void) { xmlParseDoc(); return 0; }
              ~~~~~~~~~~~ ^
/usr/local/Cellar/libxml2/2.9.7/include/libxml2/libxml/parser.h:841:11: note: 'xmlParseDoc' declared here
XMLPUBFUN xmlDocPtr XMLCALL
          ^
2 errors generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <libxml/parser.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: extern void xmlParseDoc();
16: int t(void) { xmlParseDoc(); return 0; }
/* end */

--------------------

**Comment by yasu43** [comment]
/usr/local/Cellar/icu4c/59.1_1/include/unicode/char16ptr.h:90:19: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    Char16Ptr() = delete;
                  ^
/usr/local/Cellar/icu4c/59.1_1/include/unicode/char16ptr.h:198:24: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    ConstChar16Ptr() = delete;
                       ^
In file included from transliterator.cpp:5:
In file included from /usr/local/Cellar/icu4c/59.1_1/include/unicode/translit.h:25:
/usr/local/Cellar/icu4c/59.1_1/include/unicode/unistr.h:3025:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text)) {}
      ^~~~~~~~~~~~~
/usr/local/Cellar/icu4c/59.1_1/include/unicode/unistr.h:3087:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text), length) {}
      ^~~~~~~~~~~~~
/usr/local/Cellar/icu4c/59.1_1/include/unicode/unistr.h:3180:7: error: delegating constructors are permitted only in C++11
      UnicodeString(Char16Ptr(buffer), buffLength, buffCapacity) {}
      ^~~~~~~~~~~~~
2 warnings and 3 errors generated.
make[1]: *** [transliterator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-32554-jmdtkmcharlock_holmes-0.7.5/gems/charlock_holmes-0.7.5 for
inspection.
Results logged to
/var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-32554-jmdtkmcharlock_holmes-0.7.5/extensions/universal-darwin-17/2.3.0/charlock_holmes-0.7.5/gem_make.out

An error occurred while installing charlock_holmes (0.7.5), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.5'` succeeds before bundling.

In Gemfile:
  github-linguist was resolved to 5.3.3, which depends on
    charlock_holmes

**Comment by chimame** [comment]
これで入りますか？

```bash
gem install charlock_holmes -- --with-cxxflags=-std=c++11
```

**Comment by yasu43** [comment]
ERROR:  Error installing charlock_holmes:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180310-33463-h70jte.rb extconf.rb --with-cxxflags=-std=c++11
checking for main() in -licui18n... no
checking for main() in -licui18n... yes
checking for unicode/ucnv.h... yes
checking for main() in -lz... yes
checking for main() in -licuuc... yes
checking for main() in -licudata... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/charlock_holmes-0.7.5/mkmf.log

current directory: /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5/ext/charlock_holmes
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5/ext/charlock_holmes
make "DESTDIR="
compiling ext.c
compiling encoding_detector.c
compiling converter.c
compiling transliterator.cpp
In file included from transliterator.cpp:1:
In file included from ./common.h:9:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:368:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_ARCH "universal-"RUBY_PLATFORM_OS
                              ^
                               
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:369:35: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                  ^
                                   
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17/ruby/config.h:369:55: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define RUBY_PLATFORM "universal."RUBY_PLATFORM_CPU"-"RUBY_PLATFORM_OS
                                                      ^
                                                       
3 errors generated.
make: *** [transliterator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/charlock_holmes-0.7.5 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/charlock_holmes-0.7.5/gem_make.out

**Comment by chimame** [comment]
これでいけます？

```bash
sudo gem install charlock_holmes -- --with-icu-dir=/usr/local/opt/icu4c --with-cxxflags=\'-Wno-reserved-user-defined-literal -std=c++11\'
```

**Comment by yasu43** [comment]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /private/var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-x343qlpg-0.18.4/gems/pg-0.18.4/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180310-33801-qdx7gk.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/local/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib
	--with-pqlib
	--without-pqlib
	--with-libpqlib
	--without-libpqlib
	--with-ms/libpqlib
	--without-ms/libpqlib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-x343qlpg-0.18.4/extensions/universal-darwin-17/2.3.0/pg-0.18.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-x343qlpg-0.18.4/gems/pg-0.18.4 for inspection.
Results logged to /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-x343qlpg-0.18.4/extensions/universal-darwin-17/2.3.0/pg-0.18.4/gem_make.out

An error occurred while installing pg (0.18.4), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.

In Gemfile:
  peek-pg was resolved to 1.3.0, which depends on
    pg


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /private/var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-1mlkdzxre2-1.1.1/gems/re2-1.1.1/ext/re2
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180310-33801-1dfyqk6.rb extconf.rb
checking for main() in -lstdc++... yes
checking for stdint.h... yes
checking for rb_str_sublen()... yes
checking for main() in -lre2... yes
checking for re2 requires C++11 compiler... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-re2-dir
	--without-re2-dir
	--with-re2-include
	--without-re2-include=${re2-dir}/include
	--with-re2-lib
	--without-re2-lib=${re2-dir}/lib
	--with-stdc++lib
	--without-stdc++lib
	--with-re2lib
	--without-re2lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-1mlkdzxre2-1.1.1/extensions/universal-darwin-17/2.3.0/re2-1.1.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-1mlkdzxre2-1.1.1/gems/re2-1.1.1 for inspection.
Results logged to /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-1mlkdzxre2-1.1.1/extensions/universal-darwin-17/2.3.0/re2-1.1.1/gem_make.out

An error occurred while installing re2 (1.1.1), and Bundler cannot continue.
Make sure that `gem install re2 -v '1.1.1'` succeeds before bundling.

In Gemfile:
  re2


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /private/var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-2o32tnsqlite3-1.3.13/gems/sqlite3-1.3.13/ext/sqlite3
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180310-33801-1q580t0.rb extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-sqlite3-config
	--without-sqlite3-config
	--with-pkg-config
	--without-pkg-config
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib
	--with-pthreadlib
	--without-pthreadlib
	--with-sqlite3lib
	--without-sqlite3lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-2o32tnsqlite3-1.3.13/extensions/universal-darwin-17/2.3.0/sqlite3-1.3.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-2o32tnsqlite3-1.3.13/gems/sqlite3-1.3.13 for inspection.
Results logged to
/var/folders/5q/363x5sbx7nb4c8ylvf7fqtfw0000gn/T/bundler20180310-33801-2o32tnsqlite3-1.3.13/extensions/universal-darwin-17/2.3.0/sqlite3-1.3.13/gem_make.out

An error occurred while installing sqlite3 (1.3.13), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.3.13'` succeeds before bundling.

In Gemfile:
  rspec_profiling was resolved to 0.0.5, which depends on
    sqlite3
make: *** [.gitlab-bundle] Error 5

**Comment by chimame** [comment]
```bash
ARCHFLAGS="-arch x86_64" gem install pg
```

**Comment by yasu43** [comment]
必要なRubyのバージョンがhttps://gitlab.com/gitlab-org/gitlab-ce/blob/master/.ruby-version のリンク先に行かないとわからなかったのでリンク先に飛ばなくても表示してほしい。

install OS X prerequisites using homebrewにしたがってインストール

`$ brew install git redis postgresql@9.6 libiconv icu4c pkg-config cmake nodejs go openssl node npm yarn coreutils re2
$ bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include
`

`$ gem install gitlab-development-kit
$ gdk init
`

`$ gdk install
`

re2がエラーでインストールできず
Issue #317　https://gitlab.com/gitlab-org/gitlab-development-kit/issues/317
にたどり着いてRuby 2.3.6 が必要とわかった。
ドキュメントでリンク先に飛ばなくても必要なバージョンがわかるようにしてほしい。

**Comment by yoichi** [comment]
エラーが起きたときに入っていた ruby のバージョンも情報として添えておくとよいかも

**Comment by yasu43** [comment]
## Request to display it even if I did not go to the link

I did not know that the required Ruby version. Please displayed it even if I did not go to the link of https://gitlab.com/gitlab-org/gitlab-ce/blob/master/.ruby-version .

I installed it according to "Install OS X prerequisites using homebrew".
`$ brew install git redis postgresql@9.6 libiconv icu4c pkg-config cmake nodejs go openssl node npm yarn coreutils re2`
`$ bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include`

`$ gem install gitlab-development-kit $ gdk init`

`$ gdk install`

I couldn't install re2.
Then I found Issue #317 and Ruby required version for the first time.

**Comment by yasu43** [comment]
Enviroment
* macOS 10.13.3
* ruby 2.3.3

**Comment by daddygongon** [comment]
新崎さん，こんばんは．西谷です．解決できてよかったですね．まだやけど．

**Comment by yoichi** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/issues/329 見ました。

* フィードバックできたのよかったと思います 👍 
* 対象（どのページを直してほしいのか）を省略してしまってる気がしました。

**Comment by yoichi** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/kansai です！
