### ISSUE TITLE
OSS Gate Workshop: osaka: 2018-03-10: TasukuUehara: gitlab: Work log

### ISSUE THREAD

**Issue by TasukuUehara** [oss-gate/workshop#750]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daddygongon** [comment]
メンターの西谷＠関学・理工・情報科学です．よろしくお願いします．

**Comment by TasukuUehara** [comment]
gitlabを開く
https://about.gitlab.com/pricing/

contributingを開く
https://about.gitlab.com/contributing/

gitlab-development-kitを開く
https://gitlab.com/gitlab-org/gitlab-development-kit

READMEを読む。Prepare your computerを開く
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/prepare.md

Install OS X prerequisites using homebrewでインストールする

**Comment by TasukuUehara** [comment]
Set-up GDK を開く
GDKをインストールする
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md

**Comment by TasukuUehara** [comment]
Develop in a forkで失敗する
gdk install gitlab_repo=https://gitlab.com/uehara/gitlab-ce.git
support/set-gitlab-upstream

go: disabling cache (/Users/tasuku/Library/Caches/go-build) due to initialization failure: open /Users/tasuku/Library/Caches/go-build/log.txt: permission denied

sudo chown tasuku /Users/tasuku/Library/Caches/go-build/log.txtで対応した。

**Comment by TasukuUehara** [comment]
support/set-gitlab-upstream する

remote: Counting objects: 5278, done.
remote: Compressing objects: 100% (3194/3194), done.
remote: Total 5278 (delta 3252), reused 3290 (delta 1983)
Receiving objects: 100% (5278/5278), 3.55 MiB | 843.00 KiB/s, done.
Resolving deltas: 100% (3252/3252), done.
From https://gitlab.com/gitlab-org/gitlab-ce
 * branch                  master     -> FETCH_HEAD
 * [new branch]            master     -> upstream/master
Branch 'master' set up to track remote branch 'master' from 'upstream'.

**Comment by TasukuUehara** [comment]
gdk run でgitlabが立ち上がる

http://localhost:3000/users/sign_in で確認

**Comment by daddygongon** [comment]
うまくいってますね．どこまでやるかですね．
もうすこしinstallをつづけられたらどうですか？

**Comment by TasukuUehara** [comment]
root / 5iveL!fe でログインできる

**Comment by TasukuUehara** [comment]
新しいprojectをつくる

Command line instructionsのCreate a new repositoryでエラー
$ git clone ssh://tasuku@localhost:2222/root/oss-gate-uehara.git
Cloning into 'oss-gate-uehara'...
ssh: connect to host localhost port 2222: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by daddygongon** [comment]
これは，sshの設定なんですが，どこにinstructionありましたっけ．

**Comment by TasukuUehara** [comment]
ssh-keygenでssh-keyを作る
gitlabのUser Settings > SSH Keysでssh-keyを登録する

**Comment by TasukuUehara** [comment]
またエラー
git clone ssh://tasuku@localhost:2222/root/oss-gate-uehara.git
Cloning into 'oss-gate-uehara'...
ssh: connect to host localhost port 2222: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by TasukuUehara** [comment]
ポートの確認をする
$ lsof -i : 2222
lsof: unacceptable port specification in: -i :
lsof 4.89

**Comment by chimame** [comment]
振り返りました

**Comment by TasukuUehara** [comment]
gitlabのSSHについて
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/ssh.md

**Comment by TasukuUehara** [comment]
If you want to work on GitLab's SSH integration then uncomment the
'sshd:' line in your Procfile. Next time you start run or run app
you will get an unprivileged SSH daemon process running on
localhost:2222, integrated with gitlab-shell.

To change the host/port you need to edit openssh/sshd_config and
gitlab/config/gitlab.yml. If you are not working on GitLab SSH
integration we recommend that you leave the 'sshd:' line in the
Procfile commented out.

**Comment by TasukuUehara** [comment]
local 環境で実行して、New projectしたリポジトリをgit clone するとsshのエラーがでる。
マニュアルを探したがわかりにくい。

手順
1. gitlab-development-kitをインストールする
2. gdk run でgitlabを立ち上げる
3. root でログインする
4. New projectする
5. git cloneする

$ git clone ssh://tasuku@localhost:2222/root/oss-gate-uehara.git
Cloning into 'oss-gate-uehara'...
ssh: connect to host localhost port 2222: Connection refused
fatal: Could not read from remote repository.
Please make sure you have the correct access rights]
and the repository exists.

どきゅめんとを探す
[gitlab-development-kit]https://gitlab.com/gitlab-org/gitlab-development-kit
[Set-up GDK]https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md
[learn how to use GDK](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/README.md)
[SSH]https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/ssh.md
 にある。

ssh.md
If you want to work on GitLab's SSH integration then uncomment the
'sshd:' line in your Procfile.

Procfile をしゅうせいした。

**Comment by TasukuUehara** [comment]
learn how to use GDK
https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/README.md

**Comment by takeoverjp** [comment]
ここになげましたー
https://gitlab.com/gitlab-org/gitlab-development-kit/merge_requests

**Comment by daddygongon** [comment]
Dear sir

I have installed gdk locally and try to new repository to my local pc,
but I got an error on the ssh connections.
Finally I've found the solution, but the description on that is located at
very deep level.  The link level and the description of the manual should be revised.

### What I did
1. install gitlab-development-kit on Mac OS, High Sierra
1. gdk run
1. login as root
1. Make new project
1. git clone, and get the following error,
```
$ git clone ssh://tasuku@localhost:2222/root/oss-gate-uehara.git
Cloning into 'oss-gate-uehara'...
ssh: connect to host localhost port 2222: Connection refused
fatal: Could not read from remote repository.
Please make sure you have the correct access rights]
and the repository exists.
```

### Where is the document on ssh start:
The links to the document on ssh start is follows:
* [gitlab-development-kit](https://gitlab.com/gitlab-org/gitlab-development-kit)
* [Set-up GDK](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md)
* [learn how to use GDK](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/README.md)
* [SSH](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/ssh.md)

### The description on 'ssh.md'
The description on 'ssh.md' is follows:
```
If you want to work on GitLab's SSH integration then uncomment the
'sshd:' line in your Procfile.
```
The location of 'your Procfile' is also difficult to notice for the beginner.
Please notice 'gitloab-develpment-kit/Procfile' explicitly.

**Comment by daddygongon** [comment]
Ask revise on ssh.md

**Comment by daddygongon** [comment]
gitlab-development-kit](https://gitlab.com/gitlab-org/gitlab-development-kit)
Set-up GDK](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/set-up-gdk.md)
learn how to use GDK](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/README.md)
SSH](https://gitlab.com/gitlab-org/gitlab-development-kit/blob/master/doc/howto/ssh.md)

**Comment by TasukuUehara** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/issues/328

**Comment by tnir** [comment]
https://gitlab.com/gitlab-org/gitlab-development-kit/issues/328#note_63252400 コメントしました。

gitlab-org/gitlab-development-kitは開発者向けなので、個人的要望を挙げるだけだと対応されないままクローズされてしまうかもしれません。もしよろしければ、MRの形で出してもらえるとレビューしてもらえる確率が高まると思います。

**Comment by yoichi** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/kansai です！
