### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: 3nan3: memoist: Work log

### ISSUE THREAD

**Issue by 3nan3** [oss-gate/workshop#773]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Shintaro-s-b** [comment]
見ました

**Comment by 3nan3** [comment]
# memoist
https://github.com/matthewrudy/memoist

**Comment by 3nan3** [comment]
## Readmeを読む

### Usageを試す

とりあえず、普通に動かすだけ。

```
require 'memoist'
class Person
  extend Memoist

  def some_method
    Time.now
  end
  memoize :some_method
end

# ↓動作確認で自力追加
p Person.new.some_method
p Person.new.some_method
p Person.new.some_method
p Person.new.some_method
```

**Comment by 3nan3** [comment]
> You can even memoize method that takes arguments.

とのことなので、引数追加のサンプルも動かす
```rb
require 'memoist'
class Person
  extend Memoist

  def taxes_due(income)
    income * 0.40
  end
  memoize :taxes_due
end

# ↓動作確認で自力追加
p Person.new.taxes_due(1.0)
p Person.new.taxes_due(1.0)
p Person.new.taxes_due(1.5)
p Person.new.taxes_due(1.0)
```

**Comment by 3nan3** [comment]
## 確認方法のサンプルが無いのでは

動作確認のサンプルがないので、自力で書いてみたものの一度間違えてしまった。

サンプルに動作確認用のコードと、その実行結果を書いてあるとやさしいかも。

**Comment by 3nan3** [comment]
## issueを考える

README.mdに、実行結果のサンプルを乗せる

Usageを試していたが、正しくメモ化できているかどうか確認方法を書いておいたほうが良さそう。

e.g.
```rb
require 'memoist'

class Example
  extend Memoist

  def some_method
    puts "execute!"
    Time.now
  end
  memoize :some_method
end

example = Example.new
example.some_method # => execute!
example.some_method # => 
```

**Comment by 3nan3** [comment]
e.g.
```rb
require 'memoist'

class Example
  extend Memoist

  def some_method
    puts "execute!"
    Time.now
  end
  memoize :some_method
end

example = Example.new

example.some_method
# execute!
# => 2018-03-26 14:43:39 +0000

example.some_method
# => 2018-03-26 14:43:39 +0000
```

**Comment by 3nan3** [comment]
## 翻訳

Place sample code for execution in README.md

I was trying Usage, but I thought that it would be better to write how to check the operation of memoization.

e.g.
```rb
require 'memoist'

class Example
  extend Memoist

  def some_method
    puts "execute!"
    Time.now
  end
  memoize :some_method
end

example = Example.new

example.some_method
# execute!
# => 2018-03-26 14:43:39 +0000

example.some_method
# => 2018-03-26 14:43:39 +0000
```

**Comment by s-capybara** [comment]
I tried Usage and I thought ...

**Comment by 3nan3** [comment]
たしかに

**Comment by 3nan3** [comment]
I tried Usage and I thought that it would be better to write how to check the operation of memoization.

**Comment by 3nan3** [comment]
## プルリクを作ってみる

README.md に Contributing の項目があるので参考にします。

1. Fork it ( https://github.com/matthewrudy/memoist/fork )
1. Create your feature branch (git checkout -b my-new-feature)
1. Commit your changes (git commit -am 'Add some feature')
1. Push to the branch (git push origin my-new-feature)
1. Create new Pull Request

**Comment by 3nan3** [comment]
forkしました
https://github.com/3nan3/memoist

ローラルにcloneしました
```sh
git clone git@github.com:3nan3/memoist.git
```

**Comment by 3nan3** [comment]
featureブランチ作って、変更して追加してコミット

```sh
> git checkout -b feature/modify-readme
# 変更
> git add -p
> git diff --cached
diff --git a/README.md b/README.md
index 540ab25..4f42ebb 100644
--- a/README.md
+++ b/README.md
@@ -22,10 +22,20 @@ class Person
   extend Memoist
 
   def social_security
+    puts "execute!"
     decrypt_social_security
   end
   memoize :social_security
 end
+
+person = Person.new
+
+person.social_security
+# execute!
+# => (returns decrypt_social_security)
+
+person.social_security
+# => (returns the memoized value)
\```
 
 And person.social_security will only be calculated once.

> git commit -m "modify README.md"
```

**Comment by 3nan3** [comment]
> git remote -v
origin  git@github.com:3nan3/memoist.git (fetch)
origin  git@github.com:3nan3/memoist.git (push)
> git push origin feature/modify-readme
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 408 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To git@github.com:3nan3/memoist.git
 * [new branch]      feature/modify-readme -> feature/modify-readme

**Comment by 3nan3** [comment]
## プルリク作るぞ！！！

### Place sample code for execution in README.md

I tried to modify #72 in my own.
How do you think?

**Comment by 3nan3** [comment]
作りました
https://github.com/matthewrudy/memoist/pull/73

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
