### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: Aguri: UniRx: Work log

### ISSUE THREAD

**Issue by Aguri** [oss-gate/workshop#774]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Aguri** [comment]
https://github.com/neuecc/UniRx

READMEにしたがって、インストールする

**Comment by Aguri** [comment]
new Project 作ってUniRxをインストールする

**Comment by Aguri** [comment]
https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

The introduction to Reactive Programming you've been missing
を読む

**Comment by Aguri** [comment]
slackに貼られたリンクをみる

**Comment by Aguri** [comment]
RxJavaを検索する

**Comment by Aguri** [comment]
https://codezine.jp/article/detail/9570
一番上位に出て来たので、これを読む

**Comment by Aguri** [comment]
データとストリームとして扱うのは理解したけど、
普通のイベントリスナー使うのと何が違うのかよくわからない

**Comment by Aguri** [comment]
UniRx でダブルクリックの判定

**Comment by Aguri** [comment]
いいところを真似する

**Comment by Aguri** [comment]
https://github.com/neuecc/UniRx/issues/272

リリースタグを打ってないっぽい

**Comment by Aguri** [comment]
You also forget to add release tag

**Comment by s-capybara** [comment]
Release tag is missing. とかのほうがいいかも
"You forget" ってなんかすごく強い

**Comment by Aguri** [comment]
Release tag is missing

release tag update is stoped from version 5.5.0
Please add release tag

**Comment by Aguri** [comment]
これでどうだ

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
