### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: Shintaro-s-b: memoist: Work log

### ISSUE THREAD

**Issue by Shintaro-s-b** [oss-gate/workshop#775]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Shintaro-s-b** [comment]
RADME読むよ
https://github.com/matthewrudy/memoist#readme

**Comment by Shintaro-s-b** [comment]
https://ghit.me/repo/matthewrudy/memoist
証明書の有効期限がきれてるから、フィードバックする！

**Comment by Shintaro-s-b** [comment]
起きてる事象
：READMEに出ている、ghit.meが表示されない

なんで？
：ghit.meに設定されているSSL証明書の有効期限が切れていて、ブラウザからアクセスを行うと警告が出る状態になってしまっているため、リンク先が正常に表示されなくなっている

**Comment by Shintaro-s-b** [comment]
証明書の有効期限を確認するよ
openssl s_client -connect https://ghit.me < /dev/null 2> /dev/null | openssl x509 -text | grep Not

**Comment by Shintaro-s-b** [comment]
ghit meの管理者にも連絡したほうがいいんだけど、連絡先が見つからない

**Comment by Shintaro-s-b** [comment]
twitterで連絡取れないか探してみる

**Comment by Shintaro-s-b** [comment]
見つからない、もう諦めたい

**Comment by Shintaro-s-b** [comment]
とりあえず、リンク切れしてることだけ、このリポジトリの作者に伝える

**Comment by Shintaro-s-b** [comment]
自分の中では一旦まとめたから、報告用の文章作るよ

**Comment by Shintaro-s-b** [comment]
対応
：READMEの中から、該当リンクを一旦削除したほうがいいと思うよ

**Comment by Shintaro-s-b** [comment]
で、提案してみようかと思ってます

**Comment by Shintaro-s-b** [comment]
ghit.meの管理者を探して見たが、見つからなかった。

twitter上で探したり、ghit.meのホームから連絡先を探してが、見つからなかった。
https://ghit.me/

**Comment by Shintaro-s-b** [comment]
翻訳辛い、google先生ェ。。。

**Comment by Shintaro-s-b** [comment]
文章形式にして、翻訳してみる

Link(https://ghit.me/repo/matthewrudy/memoist) not displayed

Certificate on ghit.me is expired.
You should remove this link from README temporary.

**Comment by Shintaro-s-b** [comment]
<img width="994" alt="2018-03-26 14 43 05" src="https://user-images.githubusercontent.com/2055853/37888812-49933c54-3104-11e8-870a-acb68e2ca78a.png">

**Comment by Shintaro-s-b** [comment]
とりあえず、こんな感じでも伝わるかな？

**Comment by Shintaro-s-b** [comment]
I look for contact information on twitter, ghit.me's home.
But I could not find it.

**Comment by Shintaro-s-b** [comment]
Subject : Link(https://ghit.me/repo/matthewrudy/memoist) not displayed

Certificate on ghit.me is expired.
You should remove this link from README temporary.
I look for contact information of ghit.me on twitter, ghit.me's home.
But I could not find it.
<img width="994" alt="2018-03-26 14 43 05" src="https://user-images.githubusercontent.com/2055853/37889033-6f117ddc-3105-11e8-9e3d-aa78eb702388.png">

**Comment by Shintaro-s-b** [comment]
これでどうだろうか？

**Comment by Shintaro-s-b** [comment]
You should ~ だと、言葉が強そう。

**Comment by Shintaro-s-b** [comment]
How about remove this link from README temporary?

とか？

**Comment by s-capybara** [comment]
こんな感じ？

Subject : Link (https://ghit.me/repo/matthewrudy/memoist) is not displayed.

Certificate on ghit.me is expired.
It's better to contact the administrator of ghit.me, but I couldn't find contact information on ghit.me's site nor Twitter.
How about removing this link from README temporarily?

**Comment by Shintaro-s-b** [comment]
送った
https://github.com/matthewrudy/memoist/issues/71

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
