### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: samuimo: UniRx: Work log

### ISSUE THREAD

**Issue by samuimo** [oss-gate/workshop#777]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by samuimo** [comment]
公式サイトに行く
https://github.com/neuecc/UniRx

Google翻訳する
https://translate.google.com/translate?sl=en&tl=ja&js=y&prev=_t&hl=ja&ie=UTF-8&u=https%3A%2F%2Fgithub.com%2Fneuecc%2FUniRx&edit-text=&act=url

GithubからUniRxをclone
```
$ git clone git@github.com:neuecc/UniRx.git
```

**Comment by samuimo** [comment]
- Unityを起動する
  - `License Error`が発生
  `You are currently not signed in. Some options will be unavailable.`
  `Machine identification is invalid for current license.`
  `For more information see online help`
  `For assistance contact support@unity3d.com.`

**Comment by samuimo** [comment]
公式日本語ブログを読む
http://neue.cc/2014/08/23_476.html

**Comment by samuimo** [comment]
RxJavaのwikiがオススメらしいのでメモ
https://github.com/ReactiveX/RxJava/wiki

**Comment by samuimo** [comment]
- UnityにSign in
- Machine identificationをre-active
- `license management`でPERSONAL EDITIONを選択してOK
  - `I don't use Unity in a professional capacity`を選択してOK

**Comment by samuimo** [comment]
- `Quick and easy survey ;)`
  - `Take a couple of milliseconds to help us imporove the Unity engine!`
  - ↑日本語訳 `Unityエンジンを改善するために、数ミリ秒を要します！`
    - よく分からない
  - `Where are you located?`
    - Japan
  - 以下いろいろ答える
- `Thank you! :)`
  - `Start Using Unity`をクリック

**Comment by samuimo** [comment]
- UnityでProjectを新規作成
  - Project name : `UniRxSample2D`
  - Location : 適当
  - 2D
  - `Asset packages...`から2Dを選択

**Comment by samuimo** [comment]
- `Window` > `Asset Store`を選択してAsset Storeを開く
  - 何故かAsset Storeが表示されない

**Comment by samuimo** [comment]
- Unityのバージョン 5.3.5f1
  - 古い

**Comment by samuimo** [comment]
- ブラウザからAsset Storeにアクセス
  - https://assetstore.unity.com/packages/tools/unirx-reactive-extensions-for-unity-17276
  - 結局`Open in Unity`すると表示されない

**Comment by samuimo** [comment]
Unityをバージョンアップした方が良さそうなので、UnityHubを使って見る

**Comment by samuimo** [comment]
- UnityHubを使って新バージョンのunityをインストール
  - https://unity3d.com/jp/unity/beta-download
    - `Download Unity Hub`からダウンロード
  - `UnityHubSetup.dmg`を起動
    - 何故か起動しない

**Comment by samuimo** [comment]
- 直接`Disk Utility`から開く
  - 開けたので、インストール
- Unity Hubが起動できた！

**Comment by samuimo** [comment]
- `Unity 2017.3.1f1`のインストールを開始

**Comment by samuimo** [comment]
- Title
 - I want you to write Japanese version information at the top of README
- Comment
 - I want you to paste a Japanese version blog or a link to the presentation at the top of the README.
 I'm sorry I have a very detailed request, but would be appreciated.

**Comment by Aguri** [comment]
LGTM

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
