### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: ryosuke-otsuki: UniRx: Work log

### ISSUE THREAD

**Issue by ryosuke-otsuki** [oss-gate/workshop#778]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ryosuke-otsuki** [comment]
READMEを読む
https://github.com/neuecc/UniRx/blob/master/README.md

**Comment by ryosuke-otsuki** [comment]
Google翻訳する

**Comment by ryosuke-otsuki** [comment]
.NET Reactive ExtensionsをUnity向けに変更・拡張したものと知る。

**Comment by ryosuke-otsuki** [comment]
Unity2017以降での対応状況も知りたいと思う。
 
```
Supported platforms are PC/Mac/Android/iOS/WP8/WindowsStore/etc and the library is fully supported on both Unity 5 and 4.6.
```

**Comment by ryosuke-otsuki** [comment]
READMEを読みながら動かして見るため、プロジェクトを作ってAssetStoreからダウンロードする

```
Unity Version : unity5.6.0f3
```

**Comment by ryosuke-otsuki** [comment]
Plugins/UniRx/Examples/Sample12を開く

純粋にUIが見づらい

**Comment by ryosuke-otsuki** [comment]
インストール完了してサンプルの動作も一つ見たので、READMEのIntroductionに戻る。
Rxの良い記事が紹介されており、一応確認する。

The introduction to Reactive Programming you've been missing.

**Comment by ryosuke-otsuki** [comment]
長い・・・
今日の時間を考えて、一旦置く。

対応バージョンを確認しておきたかったので、そこを深く確認することに。
リリースノートを見る。

**Comment by ryosuke-otsuki** [comment]
AssetStoreのバージョンの方が進んでいる？
タグが管理をやめている？？

```
GitHub : Version 5.5.0
AssetStore : Version 5.7.0
```

**Comment by ryosuke-otsuki** [comment]
GitHub上にmasterともう一つのブランチしか無く、GitHubで開発を行っているのか疑問が残る
GitHubの最終更新は2017年12月に対して、AssetStoreは2018年1月に更新されている。

**Comment by ryosuke-otsuki** [comment]
READMEに記載されているBlogも更新が遅れている。
https://medium.com/@neuecc

AssetStoreから本リポジトリを探してみることにする。

**Comment by ryosuke-otsuki** [comment]
AssetStoreにも情報が無さそうなので、READMEを深く追ってみることにする。

**Comment by ryosuke-otsuki** [comment]
おそらくmasterがAssetStoreの最新と同じ(反映の時間差があったと思われる。)
ただ、Tagの打ち忘れ？でリリースノートの差分はある。

**Comment by ryosuke-otsuki** [comment]
Unity2017.3.0f3で動作確認を行ってみる。

これで問題なく動けばバージョン情報の更新をお願いするIssueかPRを出してみる。

**Comment by ryosuke-otsuki** [comment]
自動テストがないか探してみる。

**Comment by ryosuke-otsuki** [comment]
AssetStoreからのファイルにはテストコードが無いので、GitHubからクローンしてテストできるか徴する。

**Comment by ryosuke-otsuki** [comment]
UnityEditor上で、/Assets/Scripts/RuntimeUnitTestTookKit/UnitTest.unityを起動してRunAllTestした所パスした。

```
開発環境：
MacBook Pro (Retina, 15-inch, Mid 2015)
プロセッサ 2.8 GHz Intel Core i7
メモリ 16 GB 1600 MHz DDR3
Unity Version : 2017.3.0f3
```

**Comment by ryosuke-otsuki** [comment]
上記のBuildSetingsは「PC, Mac & Linux Standalone」

**Comment by ryosuke-otsuki** [comment]
「Android」・「iOS」でも確認。

**Comment by ryosuke-otsuki** [comment]
READMEの対応Unityバージョンを追加するIssueを立てることで進める。

**Comment by ryosuke-otsuki** [comment]
日本語バージョン

```
タイトル：
READMEの対応しているUnityバージョンを更新したい

内容：
READMEのUnityバージョンが5までしか記載されてないので、2017.xについても記載する。
```

**Comment by ryosuke-otsuki** [comment]
英語バージョン

```
タイトル：
Update supported Unity version in README

内容：
Just a minor thing but I thought I notify you.
Please also mention the support status of Unity 2017.x in README.

https://github.com/neuecc/UniRx/blob/master/README.md
https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/ReadMe.txt
```

**Comment by ryosuke-otsuki** [comment]
Issueを立てた

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
