### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: shin: zaif-ruby: Work log

### ISSUE THREAD

**Issue by begaborn** [oss-gate/workshop#779]
# 概要
zaif-rubyのREADME.mdの内容をもっとわかりやすく記載するための提案となります。

**Comment by sachaos** [comment]
👍

**Comment by begaborn** [comment]
zaif apiのruby版ラッパーがあるかさがそう！

**Comment by begaborn** [comment]
あった。こっちにあるぞ！
https://github.com/palon7/zaif-ruby

**Comment by begaborn** [comment]
READMEを読もう
https://github.com/palon7/zaif-ruby/blob/master/README.md

**Comment by begaborn** [comment]
Cloneしてサンプルつかってみようぜ
https://github.com/palon7/zaif-ruby

**Comment by begaborn** [comment]
```
$ mkdir work
work$ bundle init
Writing new Gemfile to /Users/hyounsub.shin/Developer/common/work/Gemfile

work$ ls
Gemfile

work$ vim Gemfile   // Gemfileに `gem 'zaif'`
work$ 
Gemfile

work$ bundle install
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.14.4
Installing zaif 0.0.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./vendor/bundle.
```

**Comment by begaborn** [comment]
サンプルを動かしてみよう

**Comment by begaborn** [comment]
ZAIF_KEY、ZAIF_SECRETのキーはどこで取得するかわりづらいかも

**Comment by begaborn** [comment]
Zaif API公式サイトにあるか探そう
https://corp.zaif.jp/api-docs/

**Comment by sachaos** [comment]
http://techbureau-api-document.readthedocs.io/ja/latest/index.html

**Comment by sachaos** [comment]
http://techbureau-api-document.readthedocs.io/ja/latest/oauth/1_common.html

**Comment by sachaos** [comment]
client_id | 9r88i445cef04c358dbc26db880f9d03 | アプリケーション基本情報登録時に発行されたクライアントIDを指定してください。 | Yes
-- | -- | -- | --
client_secret | 2a99cc45cef04c358dbc26db880f9d03 | アプリケーション基本情報登録時に発行されたクライアントシークレットを指定してください。 | Yes

**Comment by begaborn** [comment]
アクセスキーとシークレットは 「基本情報登録時」に発行されるのがわかった。
基本情報登録の手順は以下のリンクを参照！
https://corp.zaif.jp/beginner/#guide3

**Comment by begaborn** [comment]
発行する具体的な手順は公式ドキュメントに記載されてないが、
発行されたキーの確認方法に関して以下のドキュメントをみつけた。
https://corp.zaif.jp/info/8241/

**Comment by begaborn** [comment]
# まとめ

## サンプルコードについて
### PublicAPIの記載
PrivateAPIしか記載してなく、APIキーを発行しない限り気軽にサンプルを試せないと思います。
例えば、以下のようなサンプルがあれば、APIキーがなくても実行できると思っております。
``` ruby
Zaif::API.new                                                                                                                                                             
api.get_last_price('btc')
```

### ZAIF_KEY,  ZAIF_SECRET の意味について詳しく記載
大体の意味はわかりますが、 
```
ZAIF_KEY にアクセスキーを、 ZAIF_SECRETにシークレットキーを設定する
```
と説明したら、もっとわかりやすいと思っております。

ついでにアクセスキー及びシークレットキーの取得する方法、または確認する方法のリンク
```
・アクセスキー及びシークレットキー設定方法：ZAIFサイトから「基本情報登録」時に発行される。
・「基本情報登録」の手順：https://corp.zaif.jp/beginner/#guide3
・アクセスキー及びシークレットキー確認方法：https://corp.zaif.jp/api-docs/trade-api/
```

## ストリーミング機能がない
ZaifはストリーミングAPIを提供しているが、このコード上にストリーミングがない。

zaif-rubyに関してなんかする
https://github.com/palon7/zaif-ruby

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
