### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: s-capybara: memoist: Work log

### ISSUE THREAD

**Issue by s-capybara** [oss-gate/workshop#780]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by 3nan3** [comment]
👍

**Comment by s-capybara** [comment]
readme をよむ

**Comment by s-capybara** [comment]
https://github.com/matthewrudy/memoist

**Comment by s-capybara** [comment]
`ghit.me` の画像リンクが切れている
リンク先の画像の証明書が切れている（有効期限3日前）

**Comment by s-capybara** [comment]
Rails5対応しているんだろうかとちょっと思った

**Comment by s-capybara** [comment]
別にRails必須じゃなかった

**Comment by s-capybara** [comment]
`(reload)` 引数について言及があるのに直下のコードに載っていないので `Cmd-f` で検索して下に飛んでやっと見つけた

**Comment by s-capybara** [comment]
":" の使い方おかしい説

**Comment by s-capybara** [comment]
> When a sub-class overrides one of its parent's methods and you need to memoize both. Then you can use the :identifier parameter in order to help Memoist distinguish between the two.

文法があかん

**Comment by s-capybara** [comment]
```ruby
class Clock
  extend Memoist
  def now
     "The time now is #{Time.now.hour} o'clock and #{Time.now.min} minutes"
  end
  memoize :now
end

class AccurateClock < Clock
  extend Memoist
  def now
    "#{super} and #{Time.now.sec} seconds"
  end
  memoize :now, :identifier => :accurate_clock
end
```
実行結果例が欲しいと思った

**Comment by s-capybara** [comment]
よみおわった

**Comment by s-capybara** [comment]
イシュー読み漁る

**Comment by s-capybara** [comment]
Ruby2.1からは簡単な記法があるよ  
イシュー番号48

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
