### ISSUE TITLE
OSS Gateワークショップ2016-01-30: フィードバック

### ISSUE THREAD

**Issue by kou** [oss-gate/workshop#8]
このワークショップをよりよくするために気づいたことやアイディアを書く場所。

**Comment by kawahara** [comment]
Hello :+1:

**Comment by kawahara** [comment]
gitter もっと使うといいかも
URL共有などで。
https://gitter.im/oss-gate/workshop

**Comment by kohei-takata** [comment]
プロジェクトによっては、IssueやPRのお作法があることもあります。
それを確認することも手順に入れたらいいかもしれません。
[例:Node.jsのCONTRIBUTING.md](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md)

**Comment by kawahara** [comment]
英語、怖くないよ感。(Global な OSSへの貢献時)

**Comment by kou** [comment]
「参加者」と「メンター」という区分だとワークショップ参加者と「参加者」の区別をつけにくいので「参加者」じゃない呼び名にした方がよさそう。「チャレンジャー」とか？

**Comment by kou** [comment]
「スターター」？

**Comment by kou** [comment]
Gateにかけたなにかがいいのかなぁ。

**Comment by sezemiadmin** [comment]
多分次回もやってみてというところですが、進行役の人は他の方でもいけそうでしょうか。特定の人に負荷集中しそうではないとアンケートにはあったので (進行役が変わっても出来るということとは違いそうですが)

#### 意図
- 参加したメンターや参加者が次回自分で進行役が出来そうと思えると他でも開催しやすくなる
- 他のイベント内ワークショップや学内、企業内ワークショップなど開催しやすくなる

**Comment by sezemiadmin** [comment]
> 「スターター」？
:+1:

**Comment by kou** [comment]
> 進行役の人は他の方でもいけそうでしょうか。

最後のふりかえりのときにそういう話をしたんですけど、最終的にどうなったか覚えていないんですよねぇ。

だれか覚えています？

**Comment by y-goto** [comment]
全体的な、結論は出ていなかったはずです。

正直に言うと、私個人は、
「例えば今の段階で私がやっちゃうと、色々勝手なことして方向性が微妙にずれたりしないかなー？」と
心配にだったりしています。

今の方向性がもう少し固まってからのほうが良いかもしれませんが、どうでしょう？
そんな心配は杞憂ですかね？

**Comment by kou** [comment]
Gitterを使ってみようぜ！というタイミングを逃しましたね。。。

**Comment by kou** [comment]
`CONTRIBUTING.md`はうっすら入れておきました。
