### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-04-16: ka-s: Cocos2d-x: Work log

### ISSUE THREAD

**Issue by ka-s** [oss-gate/workshop#806]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ka-s** [comment]
ほげ

**Comment by yusi** [comment]
がんばれー

**Comment by kmb-ak** [comment]
🎉

**Comment by ka-s** [comment]
がんばるぞい

**Comment by ka-s** [comment]
とりあえずcocos2d-xで検索

**Comment by ka-s** [comment]
いろいろあるけどどうせ英語のタイトルのところだろうなぁ

**Comment by ka-s** [comment]
めっけ、ドメインが.orgだから間違い無いでしょう
http://www.cocos2d-x.org/

**Comment by ka-s** [comment]
(そういえばcocos creatorが産廃だという噂は本当なのだろうか・・・？トップページで推してるけど・・・

**Comment by ka-s** [comment]
とりあえず俺はこのv1.9.0 macってところをクリックするぜ！

**Comment by ka-s** [comment]
dlハジマタ

**Comment by ka-s** [comment]
思ったけど「read more」「v1.9.0 mac」... ってボタンの配置が謎だ・・・。

**Comment by ka-s** [comment]
なぜ押すべきボタン二つが斜めの配置なのだろうか・・・

**Comment by ka-s** [comment]
色が違うからわかりやすいけどね

**Comment by ka-s** [comment]
“CocosCreator_v1.9.0_20180313.dmg”は、開発元が未確認のため開けません。

なるほどな

**Comment by ka-s** [comment]
思ったけど、これオープンソースの方では無いのでは

**Comment by ka-s** [comment]
cocos2d-xとcocos creatorは別物・・・っ！

**Comment by ka-s** [comment]
productsページを見てみよう

**Comment by ka-s** [comment]
http://www.cocos2d-x.org/products

**Comment by ka-s** [comment]
Cocos2d-x is an open-source game framework
Cocos Creator is a complete package of game development tools
やっぱり違った

**Comment by ka-s** [comment]
じゃあこのページからcocos2d-xの方をdlだ！

**Comment by ka-s** [comment]
お、選択肢がいろいろある、とりあえずv3.16を選択

**Comment by ka-s** [comment]
思ったけど、cocos2d-xを求めてトップページにアクセスする人にとってこれは不親切では・・・？

**Comment by ka-s** [comment]
dl待ちなう

**Comment by ka-s** [comment]
解凍なう

**Comment by ka-s** [comment]
とりあえずディレクトリ開いた、readmeよも

**Comment by ka-s** [comment]
Git user attention
へー公式ページからじゃなくてgithubからも落とせるんだー(棒

**Comment by ka-s** [comment]
How to start a new game
これだ

**Comment by ka-s** [comment]
Run `setup.py`
なるほどこれを叩けば良いのだな！

**Comment by ka-s** [comment]
(業務で使ってるcocosの設定が書き換わってしまうのでやりません

**Comment by ka-s** [comment]
次は `cocos new MyGame -p com.your_company.mygame -l cpp -d NEW_PROJECTS_DIR` を叩けば良いのだな！

**Comment by ka-s** [comment]
そして `cocos run -p mac` を叩けば良いのだな！

**Comment by ka-s** [comment]
## 感じたことメモ
- `cocos new MyGame -p com.your_company.mygame -l cpp -d NEW_PROJECTS_DIR` が何をしてるかわからない。何か細かくオプションが付いているが・・・。
  - `cocos -h` とか叩いてもそれっぽいことは書いてない・・・。
  - これではただのおまじないになってしまう・・・。

**Comment by ka-s** [comment]
cocosコマンドのオプションがどこにあるか探してみよう

**Comment by ka-s** [comment]
とりあえずれあどめを見てみる

**Comment by ka-s** [comment]
Where to get helpのところにapiリファレンスがあった。
目的と違うけどとりあえず見てみよう

**Comment by ka-s** [comment]
http://cocos2d-x.org/docs/api-ref/cplusplus/v3x/

**Comment by ka-s** [comment]
お、wikiのリンクはっけーん
http://www.cocos2d-x.org/docs/cocos2d-x/en/

**Comment by ka-s** [comment]
それっぽいの見つけた・・・結構深いところにあったなぁ
http://www.cocos2d-x.org/docs/cocos2d-x/en/editors_and_tools/cocosCLTool.html

**Comment by ka-s** [comment]
でもこれリファレンスでは無いよなぁ

**Comment by ka-s** [comment]
え、本当にコマンドのリファレンス無いのでは・・・

**Comment by ka-s** [comment]
ちょっとggってみようか

**Comment by ka-s** [comment]
`cocos new --help` とかサブコマンドに対してヘルプしたらちゃんと出てきた！
`cocos -h` で出てくるexampleをよく読んでないだけだった・・・

**Comment by ka-s** [comment]
## 思っていること
リンクが切れている？おかしい？ので、直す。

**Comment by ka-s** [comment]
そもそも何がおかしいのか見てみる

**Comment by ka-s** [comment]
ここでリンクが消えてる！
https://github.com/cocos2d/cocos2d-x/pull/18644

でもなんで消したのかわからない・・・説明がなさすぎる・・・

**Comment by ka-s** [comment]
ここでリンクが消えてる！
https://github.com/cocos2d/cocos2d-x/pull/18644

でもなんで消えてるかわからない・・・説明が全然無い・・・

**Comment by ka-s** [comment]
とりあえずリンクを復活させるだけってわけには行かなそう。
issue立てて質問してみようかな

**Comment by ka-s** [comment]
あ、github内のリンクを貼ると向こうにも表示されちゃうのね！

**Comment by ka-s** [comment]
とりあえず似たissueが無いか検索しよう

**Comment by ka-s** [comment]
とりあえずチャットツールっぽい。
ってことは公式にはもう使わないと判断してリンクを消したのに消し切れてなかったってことかな。
ってことでリンクを完全に消したPRを出そう！

**Comment by ka-s** [comment]
>ここで英語の壁<

**Comment by ka-s** [comment]
## 整理
例のPRでは `webchat.freenode.net` の参照が消されている。
しかし、完全には消し切れていない。
なので、残っている参照を消しました。

**Comment by ka-s** [comment]
これを英語になおす

**Comment by ka-s** [comment]
ref:さっきのPR
This pull request deleted `webchat.freenode.net` link.
but, It has not been completely deleted.
so, I deleted the remaining links.

**Comment by ka-s** [comment]
最終的な文章

```
    Fix link in README

    In #18644, the link `webchat.freenode.net` was deleted.
    But, it has not been completely deleted.
    So, I deleted the remaining links.
```

**Comment by ka-s** [comment]
PR出したぞおおおおおおおお

**Comment by ka-s** [comment]
さて次は何をしようか

**Comment by ka-s** [comment]
今度は中身を直したいな

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！
