### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-04-16: nk16: twitter: Work log

### ISSUE THREAD

**Issue by nk16** [oss-gate/workshop#807]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tomotaka-yamasaki** [comment]
いえーい

**Comment by akihiro-nagai** [comment]
参上

**Comment by hokuto-tokutake** [comment]
wa-

**Comment by nk16** [comment]
使い方のサンプルを見た
https://github.com/sferik/twitter/tree/master/examples

**Comment by nk16** [comment]
Configurationを見た
https://github.com/sferik/twitter/blob/master/examples/Configuration.md#configuration

**Comment by nk16** [comment]
`gem install twitter` を実行

**Comment by nk16** [comment]
作業ディレクトリを作成
`mkdir twitter`

**Comment by nk16** [comment]
とりあえず `irb` を実行した。

**Comment by nk16** [comment]
Twitter にログインして、アカウントの認証キーを確認しようとした。そろそろタブを開きすぎて迷う。
https://twitter.com

**Comment by nk16** [comment]
Twitterのアカウント設定ではTwitterアプリの設定がないので、「twitter api access token」で検索して、以下のページを確認した。
https://developer.twitter.com/en/docs/basics/authentication/guides/access-tokens
https://apps.twitter.com

**Comment by hokuto-tokutake** [comment]
https://github.com/sferik/twitter/blob/master/CONTRIBUTING.md

**Comment by hokuto-tokutake** [comment]
> t authorize

**Comment by nk16** [comment]
`require 'twitter'` を記述する必要がある旨がREADMEにもDocumentationにも書いてないので、どこかに追記して明示したほうが良さそうです。

**Comment by nk16** [comment]
https://github.com/sferik/twitter/blob/master/CONTRIBUTING.md　を確認する。

`Write or edit documentation.` は受け付けている対象になりそうだ。

**Comment by nk16** [comment]
どこのブランチが最新なのか（どのブランチから切って、どのブランチにPRを送ればいいか）確認したい。

PRを見たところ、masterにどれも向いている…がContributionの方法にはそれが定義されていないようだ。

**Comment by nk16** [comment]
加えて、
https://github.com/sferik/twitter/blob/master/CONTRIBUTING.md#submitting-a-pull-request の中の以下のリンクが切れていた。

2. Create a topic branch.
11. Submit a pull request.

**Comment by nk16** [comment]
自分のアカウントへ fork を行った。

**Comment by nk16** [comment]
topicブランチの命名規則を探ってみたが、特に無かった。

ブランチの名前を 'add_require_to_readme' にした。

**Comment by nk16** [comment]
READ ME のうちどこに `require twitter` を記述すればいいか議論した。
examples ディレクトリ以下ではTwitter認証手順も省略されていて、簡潔にする方針のようだったので、READMEに一文追加する程度がちょうど良さそうだ。

**Comment by nk16** [comment]
`require` や `README` でクローズされた同様のPRが無いか確認したが、無さそうだ。

**Comment by nk16** [comment]
ほかのgemの `require` が記述されるタイミングを確認してみた。

sqliteなど、ほかのライブラリについても最初のサンプルコードに記述されていることが多そうだ。

**Comment by nk16** [comment]
どれを根拠にして、requireをついかすべきと説明するか検討する。

そこで、 http://sscce.org/ が根拠になるか確認してみる。

**Comment by nk16** [comment]
PRを出す時の説明根拠案

サンプルコードのSSCCE（ http://sscce.org/ ）のうち、Self Containedの部分と照らし合わせて、 `require` 文を追加したほうがいいと考えた。

また一方で、Shortさを保つため最初の一つに対してのみ追加した。

**Comment by nk16** [comment]
実際の操作に即して説明をしたほうがいいと指摘をいただきましたので、以下の形にしたいと思います。

READMEを順番に読み、最初にConfigurationを実行すると、 `uninitialized constant Twitter` と表示されてしまいます。

```
$ irb
irb(main):001:0> client = Twitter::REST::Client.new do |config|
irb(main):002:1*   config.consumer_key        = "YOUR_CONSUMER_KEY"
irb(main):003:1>   config.consumer_secret     = "YOUR_CONSUMER_SECRET"
irb(main):004:1>   config.access_token        = "YOUR_ACCESS_TOKEN"
irb(main):005:1>   config.access_token_secret = "YOUR_ACCESS_SECRET"
irb(main):006:1> end
NameError: uninitialized constant Twitter
	from (irb):1
	from /Users/nao.kono/.rbenv/versions/2.3.5/bin/irb:11:in `<main>'
irb(main):007:0> 
```

そこで `require twitter` を明示することで、サンプルコードがエラー無く進み、 Self contained になるようにしたいと思います。

**Comment by nk16** [comment]
I read README from the top, and execute configuration code at first, I encountered `uninitialized constant Twitter` as below.

```
 irb
irb(main):001:0> client = Twitter::REST::Client.new do |config|
irb(main):002:1*   config.consumer_key        = "YOUR_CONSUMER_KEY"
irb(main):003:1>   config.consumer_secret     = "YOUR_CONSUMER_SECRET"
irb(main):004:1>   config.access_token        = "YOUR_ACCESS_TOKEN"
irb(main):005:1>   config.access_token_secret = "YOUR_ACCESS_SECRET"
irb(main):006:1> end
NameError: uninitialized constant Twitter
	from (irb):1
	from /Users/nao.kono/.rbenv/versions/2.3.5/bin/irb:11:in `<main>'
irb(main):007:0> 
```

To avoid this problem, I added `require 'twitter'` code.

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！

**Comment by hokuto-tokutake** [comment]
私が報告することじゃないかもしれませんが、

https://github.com/sferik/twitter/pull/916

PR自体は出すとこまではできました

https://github.com/sferik/twitter/pulls?q=is%3Apr+is%3Aclosed

2017年11月以降の動きがないので、フィードバックが取り込まれるかという問題がありそうです
