### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-04-16: yusi: chromium: Work log

### ISSUE THREAD

**Issue by yusi** [oss-gate/workshop#810]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by ka-s** [comment]
1げっt

**Comment by kmb-ak** [comment]
🎉

**Comment by yusi** [comment]
chromiumで検索だー
https://www.google.co.jp/search?rlz=1C5CHFA_enJP734JP734&ei=3CvUWrXpJoiD8wWaqa_AAg&q=chrominium&oq=chrominium&gs_l=psy-ab.3...0.0.0.85650.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.Wa0DCFj3iw8

**Comment by yusi** [comment]
一番上は安定のWikipedia

**Comment by yusi** [comment]
ここが公式
https://www.chromium.org/

**Comment by yusi** [comment]
ChromiumOSはまた別。あたりまえだけど。

**Comment by yusi** [comment]
githubでなくてこっちが公式のソース置き場所。
https://chromium.googlesource.com/chromium/src.git

**Comment by yusi** [comment]
Githubにmirrorがある
https://github.com/chromium/chromium

**Comment by yusi** [comment]
今日はGithubの方みていこう

**Comment by yusi** [comment]
docs/README.md に各環境のビルド環境方法があるようだ。
Macなのでここかな。

Mac Build Instructions - MacOS 
https://github.com/chromium/chromium/blob/master/docs/mac_build_instructions.md

**Comment by yusi** [comment]
> A 64-bit Mac running 10.12+.
> Xcode 8+
> The OS X 10.12 SDK. Run

環境は上記のようだ。自分は10.13だけど大丈夫でしょ

**Comment by yusi** [comment]
まずはdepot_tools をもってこいとのこと

`git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git`

**Comment by yusi** [comment]
.zshrcに以下を掛けと。
> export PATH="$PATH:/path/to/depot_tools"
なので
`export PATH="~/git/depot_tools`
かな。

**Comment by yusi** [comment]
> Run the fetch tool from depot_tools to check out the code and its dependencies.
> $ fetch chromium

とのことだが、エラー

>Running: gclient root
Traceback (most recent call last):
  File "./fetch.py", line 306, in <module>
    sys.exit(main())
  File "./fetch.py", line 301, in main
    return run(options, spec, root)
  File "./fetch.py", line 287, in run
    if not options.force and checkout.exists():
  File "./fetch.py", line 86, in exists
    gclient_root = self.run_gclient('root', return_stdout=True).strip()
  File "./fetch.py", line 82, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "./fetch.py", line 69, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by yusi** [comment]
depot_toolsと同じディレクトリにchromiumディレクトリを作ってそこから
`../depot_tools/fetch chromium` で実行できた。

**Comment by yusi** [comment]
10GBあってDLが終わらない…

**Comment by yusi** [comment]
DiskFullにはならないことを確認。

**Comment by yusi** [comment]
まだDLおわってないけど、次のSetupを読む。
> Setting up the build
> Chromium uses Ninja as its main build tool along with a tool called GN to generate .ninja files. You > > can create any number of build directories with different configurations. To create a build directory:

Ninja…

**Comment by yusi** [comment]
GNコマンド
`gn gen out/Default`

**Comment by yusi** [comment]
まだDLが終わらないのでドキュメントの先を読む

**Comment by yusi** [comment]
.ninja に以下の設定でビルドが早くなるらしい
> is_debug = false
> is_component_build = true
> symbol_level = 0

**Comment by yusi** [comment]
30分まってV8のDLのあとで
> OSError: Execution failed with error: [Errno 2] No such file or directory.
> Check that None or cipd exist and have execution permission.
> 略
> subprocess.CalledProcessError: Command '('/usr/bin/python', '/Users/yuzo.shimamura/git/depot_tools/gclient.py', 'sync')' returned non-zero exit status 1

なので以下を実行
`gclient sync`

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！
