### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-04-16: Zepprix: chef-td-agent: Work log

### ISSUE THREAD

**Issue by Zepprix** [oss-gate/workshop#811]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kackyt** [comment]
(=ﾟωﾟ)ﾉ

**Comment by atakai** [comment]
(=ﾟωﾟ)ﾉ(=ﾟωﾟ)ﾉ

**Comment by Zepprix** [comment]
chefは今入ってるversionを使ってみよう
```zsh
> knife -v                                                                                                                                                                                                                                                                                   Chef: 12.0.3
```

**Comment by Zepprix** [comment]
chefを当てるインスタンスはEC2で用意できている
coobooksはどうしようかなー
出来るだけまっさらな状態でやりたい

**Comment by Zepprix** [comment]
chefのチュートリアルみたいなやつでお試しのcookbookないかなー

**Comment by Zepprix** [comment]
お、こんなのあったぞ
https://learn.chef.io/tracks/chef-on-aws#/

**Comment by Zepprix** [comment]
この辺りからやればいいかな
https://learn.chef.io/modules/learn-the-basics/rhel/aws/configure-a-resource#/

**Comment by Zepprix** [comment]
cookbook作る辺りからやってみる
https://learn.chef.io/modules/learn-the-basics/rhel/aws/make-your-recipe-more-manageable#/

**Comment by Zepprix** [comment]
chefのチュートリアルで終わっちゃうかも。
まあ、それもあり。

**Comment by Zepprix** [comment]
いくつか手順を飛ばしたので遡ってみる
https://learn.chef.io/modules/learn-the-basics/rhel/aws/configure-a-resource#/

**Comment by Zepprix** [comment]
- `Permission denied `とか書いてあったので、`sudo`をつけてみた
```zsh
 sudo chef-client --local-mode hello.rb                                                                  1   master 
Password:
/Users/kuniaki.moriya/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
[2018-04-16T14:29:05+09:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.0.3
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2018-04-16T14:29:23+09:00] WARN: Node kuniakimoriyanoMacBook-Pro.local has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/kuniaki.moriya/chef-repo-test/hello.rb
  * file[/tmp/motd] action create
    - create new file /tmp/motd
    - update content in file /tmp/motd from none to b94d27
    --- /tmp/motd       2018-04-16 14:29:23.000000000 +0900
    +++ /tmp/.motd20180416-44985-1bzezo3        2018-04-16 14:29:23.000000000 +0900
    @@ -1 +1,2 @@
    +hello world

Running handlers:
Running handlers complete
Chef Client finished, 1/1 resources updated in 8.288685 seconds
```

**Comment by kackyt** [comment]
```
ERROR: Permission denied @ rb_sysopen - /Users/kuniaki.moriya/.chef/local-mode-cache/cache/chef-client-running.pid
```
こいつで躓いてますね。

**Comment by Zepprix** [comment]
手順通りに実行していたら下記のコマンドで先ほどと同じエラー
```zsh
sudo chef-client --local-mode webserver.rb
```

**Comment by Zepprix** [comment]
手動でディレクトリを作って再実行してみた
```/var/www/html```

**Comment by Zepprix** [comment]
チュートリアルにはリンク貼ってなかったけど、ドキュメントはちゃんと存在する
https://docs.chef.io/ctl_chef_client.html

**Comment by Zepprix** [comment]
Learn Chef自体のgithubレポジトリはないみたいなので、chefのリポジトリにFBすれば良さそう
https://github.com/chef/chef

**Comment by Zepprix** [comment]
てか、そもそもmacで動かす想定のマニュアルはないのか？

**Comment by Zepprix** [comment]
Learn Chefでmac用のマニュアルはないか探してみる

**Comment by Zepprix** [comment]
そもそもlocalにどうやってchefを入れたんだけっけ？

**Comment by Zepprix** [comment]
brewとかで直接chefをインストールした記憶はない

**Comment by Zepprix** [comment]
iishin-cookbook内のgemfileで入れたっぽい
```ruby
gem "berkshelf", '~> 3.1'
gem 'knife-solo', '~> 0.4'
```

**Comment by Zepprix** [comment]
なら、gemで入れた場合のマニュアルを探してみる

**Comment by Zepprix** [comment]
そろそろ時間がないので、ここまでの内容をFBとしてまとめてみる

**Comment by Zepprix** [comment]
ひとまず 「Learn Chef Rally」に`chef`をgemで入れてmacで動かす場合のチュートリアルがぱっと見で見つからなかったのが気になった

**Comment by Zepprix** [comment]
今日はひとまずRedHat Enterprise Linux用のドキュメントをみて動かしていた

**Comment by Zepprix** [comment]
その結果、chefで自動的に作られるはずの`/var/www/html`ディレクトリが作られずエラーが発生した

**Comment by Zepprix** [comment]
localのchefのversionが古い(ver.12.0)のか、OSがmacだからなのかは検証できていない

**Comment by Zepprix** [comment]
あとはチュートリアル内でコマンドがオプションの説明等が省かれて登場していたので、https://docs.chef.io/のリンクが貼ってあると良いと思った

**Comment by Zepprix** [comment]
## issue案
タイトル: Learn Chef Rallyにドキュメントのリンクを貼る
説明: 
Learn Chef Rallyのチュートリアルで、各種コマンドがオプションの細かい解説などが省かれて紹介されている。例えば、以下のようなコマンドにて、そもそも`local-mode`とは何かは別途、DOCSで調べる必要がある
```zsh
sudo chef-client --local-mode webserver.rb
```

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！
