### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-04-16: atakai: ActiveAdmin: Work log

### ISSUE THREAD

**Issue by atakai** [oss-gate/workshop#812]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kackyt** [comment]
(=ﾟωﾟ)ﾉ

**Comment by Zepprix** [comment]
(=ﾟωﾟ)ﾉ(=ﾟωﾟ)ﾉ

**Comment by atakai** [comment]
READMEを確認しよう！
https://github.com/activeadmin/activeadmin/blob/master/README.md

**Comment by atakai** [comment]
GettingStartedのCheck out the docsリンクをたどろう！
https://activeadmin.info/0-installation.html

**Comment by atakai** [comment]
Railsが入っていることが前提のようなので、Railsから入れよう！
https://railsguides.jp/getting_started.html

**Comment by atakai** [comment]
/Users/akihide.takai/Repositories/oss-gate-test
を作成

**Comment by atakai** [comment]
ruby -v
ruby 2.3.5p376
チュートリアルが2.2.2以降対応とのことなので大丈夫そう！

**Comment by atakai** [comment]
sqlite3 --version
3.19.3
入っている！

**Comment by atakai** [comment]
gem install rails
5.2インストール中！

**Comment by atakai** [comment]
そこそこ時間がかかる

**Comment by atakai** [comment]
入った！

**Comment by atakai** [comment]
rails --version
Rails 5.2.0

**Comment by atakai** [comment]
ブログアプリケーションを作成する
rails new blog

**Comment by atakai** [comment]
作成完了！

**Comment by atakai** [comment]
cd blog

**Comment by atakai** [comment]
ls
atakai-mbp:blog akihide.takai$ ls
Gemfile		README.md	app		config		db		log		public		test		vendor
Gemfile.lock	Rakefile	bin		config.ru	lib		package.json	storage		tmp

**Comment by atakai** [comment]
rails server
ここにアクセス
http://localhost:3000/
Yay! You’re on Rails!

**Comment by atakai** [comment]
ここからactiveadminのインストールに進む！

**Comment by atakai** [comment]
vi config/routes.rb
エディタでconfig/routes.rbを開いてください。で、確認してみたが、
例示されている内容が、ローカルのconfig/routes.rbと異なっている。
日本語版だけこうなのか英語版を確認してみる。

**Comment by atakai** [comment]
http://guides.rubyonrails.org/getting_started.html
英語版を確認するとローカルのconfig/routes.rbと同一のものが例示されていた。
これについてフィードバックできないか方法を探す。

**Comment by atakai** [comment]
https://github.com/yasslab/railsguides.jp/pull/662/files
ここに既にnanophateさんによるプルリクが出ていたので、一旦スルー

**Comment by atakai** [comment]
と思ったが、プルリクで提案されている日本語訳が英語と食い違っているので、コメントをしようと思う

**Comment by atakai** [comment]
しかし、よくみてみるとWIPかつ翻訳が完了したかのチェックボックスがついてないので、一旦先に進む

**Comment by atakai** [comment]
root 'welcome#index'
をconfig/routes.rbに追加

**Comment by atakai** [comment]
http://localhost:3000/
がHello, Rails!
に変わっていることを確認！

**Comment by atakai** [comment]
5 アプリケーションの実装と実行
に進む

**Comment by atakai** [comment]
resources :articles

  root 'welcome#index'
をconfig/routes.rbに追加

**Comment by atakai** [comment]
bin/rails routes
でルート設定がされていることを確認！

**Comment by atakai** [comment]
http://localhost:3000/articles/new
を開くとRouting Errorになってしまった！

**Comment by kackyt** [comment]
バージョンが違うのが問題？

**Comment by atakai** [comment]
rails g controller articles
でしたすいませんw

**Comment by atakai** [comment]
def new
end
を追加

**Comment by atakai** [comment]
ActionController::UnknownFormat in ArticlesController#new
が出るようになった

**Comment by atakai** [comment]
vi app/views/articles/new.html.erb
でViewを作成！

**Comment by atakai** [comment]
vi app/controllers/articles_controller.rb
にcreateメソッドを追加！

**Comment by atakai** [comment]
render plain: params[:article].inspect
をcreateメソッドに追加！

**Comment by atakai** [comment]
5.4 Articleモデルを作成する

**Comment by atakai** [comment]
rails generate model Article title:string text:text
を実行！

**Comment by atakai** [comment]
bin/rails db:migrate
を実行！

**Comment by atakai** [comment]
コントローラーのcreateメソッドに
  @article = Article.new(params[:article])
 
  @article.save
  redirect_to @article
処理を追加！

**Comment by atakai** [comment]
@article = Article.new(params.require(:article).permit(:title, :text))
ストロングパラメーターを使うように変更！

**Comment by atakai** [comment]
def show
  @article = Article.find(params[:id])
end
を追加

**Comment by atakai** [comment]
app/views/articles/show.html.erb
を作成！

**Comment by atakai** [comment]
とりあえずコメントをつけれるようにするため
6 2番目のモデルを追加する
まで飛ぶ

**Comment by atakai** [comment]
rails generate model Comment commenter:string body:text article:references
を実行！

**Comment by atakai** [comment]
bin/rails db:migrate
を実行！

**Comment by atakai** [comment]
Articleモデルに下記を追加！
has_many :comments

**Comment by atakai** [comment]
config/routes.rbを書き換え
resources :articles do
  resources :comments
end

**Comment by atakai** [comment]
rails generate controller Comments
を実行！

**Comment by atakai** [comment]
app/views/articles/show.html.erb
を編集してコメントできるようにする！

**Comment by atakai** [comment]
app/controllers/comments_controller.rb
を編集してコメントを保存できるようにする！

**Comment by atakai** [comment]
app/views/articles/show.html.erb
を編集して記事ページにコメントを表示できるようにする！

**Comment by atakai** [comment]
フィードバックはRailsガイド日本語版が5.0までしか対応していなく、
config/routes.rbを編集する部分が5.2のファイル内容と違ってしまっていて、
まだ翻訳作業が進んでいないようなので、自分で翻訳してコメントで提案してみる！

**Comment by atakai** [comment]
コメント先はここ！
https://github.com/yasslab/railsguides.jp/pull/662/files

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！
