### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-04-23: TakanoriHosoya UnityIngameDebugConsole: Work log

### ISSUE THREAD

**Issue by TakanoriHosoya** [oss-gate/workshop#824]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by csouls** [comment]
💪

**Comment by TakanoriHosoya** [comment]
開始！

**Comment by apstndb** [comment]
LGTM

**Comment by TobiasGSmollett** [comment]
LGTM

**Comment by TakanoriHosoya** [comment]
READMEを読む
英語わからないので翻訳します

**Comment by TakanoriHosoya** [comment]
https://github.com/yasirkula/UnityIngameDebugConsole/blob/master/README.md

**Comment by TakanoriHosoya** [comment]
コマンドのところがよくわからなかった
日本語にしちゃったから？

**Comment by TakanoriHosoya** [comment]
英文に戻してみる

**Comment by TakanoriHosoya** [comment]
読むのもだけど、実際に動かしてみながら理解したくなったので動かすことにする

**Comment by TakanoriHosoya** [comment]
アセットストア
https://www.assetstore.unity3d.com/en/#!/content/68068

**Comment by TakanoriHosoya** [comment]
アセットストアの説明を読んでみた。（み忘れてた）
概要ぐらいでわかりやすかった。（箇条書きだったからかな）

**Comment by TakanoriHosoya** [comment]
Unity起動して、このバージョンで使えるのか？ってなってアセットストアをみた。
対象のUnityのバージョンがgithubのreadmeに書いてなかった。

**Comment by TakanoriHosoya** [comment]
対象バージョン以下だったので、それ以上のUnityを開いた

**Comment by TakanoriHosoya** [comment]
このプロジェクトを見つけたサイトに行ってみた
https://unitylist.com/
https://unitylist.com/p/24v/Unity-Ingame-Debug-Console
githubのreadmeが書いてある感じだが、連携されているのかな？
最新の情報だったら問題なさそうだけど

**Comment by TakanoriHosoya** [comment]
UnityのAssetStoreでDL

**Comment by TakanoriHosoya** [comment]
インストール完了したので、動かし方をもう一度確認してみる

**Comment by TakanoriHosoya** [comment]
GitHubの方が詳しい説明があったのでGitHubのreadmeをみる

**Comment by TakanoriHosoya** [comment]
https://github.com/yasirkula/UnityIngameDebugConsole/blob/master/README.md#how-to

>HOW TO
>Simply import IngameDebugConsole.unitypackage to your project and place IngameDebugConsole prefab to your scene. You may want to tweak the following settings:

これをやってみる

**Comment by TakanoriHosoya** [comment]
prefabを入れたらGameViewに出てきた

**Comment by TakanoriHosoya** [comment]
画面内で動かせた！便利。
動かせるってABOUTに書いてあった

**Comment by TakanoriHosoya** [comment]
エラーを出したいので、スクリプトを書いてみる

**Comment by TakanoriHosoya** [comment]
ボタンを押すとログに書き込むスクリプトを実行
```csharp
public void pushButton ()
{
	Debug.Log ("push");
}
```

①小さい表示物のログ件数がある状態
![image](https://user-images.githubusercontent.com/7413235/39108335-a5a45f46-4702-11e8-9fd1-980342765b8e.png)

②ダブルクリックして詳細を開く。
![image](https://user-images.githubusercontent.com/7413235/39108311-9099fad4-4702-11e8-9051-6dc578a1b8f3.png)

③×ボタンで詳細を閉じると、小さい表示物のログ件数が0になった。
![image](https://user-images.githubusercontent.com/7413235/39108293-798aaf0a-4702-11e8-87d8-6f5f7f073a74.png)

なので、
小さい表示物のログ件数は、未読件数ということがわかった。

**Comment by TakanoriHosoya** [comment]
ふと思ったが、
端末で見れる前提で進めていたけど、見えるか見えないかはどこにも書いてなかった。

**Comment by TakanoriHosoya** [comment]
小さい表示物=ポップアップと呼ぶことにする
未読件数の件で、readmeにポップアップの数字に関して説明がなかったので、書いてあったら実験しなくて済んだので書いておいて欲しかった

**Comment by TakanoriHosoya** [comment]
readmeにあったら、より便利なので追記した方がいいのではないか？という提案

ポップアップに表示されている数字ですが、
readmeに仕様が書いていなかったので、検証した結果、コンソールウィンドウに出力されるログの未読件数ということがわかりました。
未読件数が表示されるのは機能としてとても良いと感じました。
readmeにポップアップの仕様が書いてあった方がわかりやすいと思うので、追記していただきたいです。

**Comment by TakanoriHosoya** [comment]
ポップアップに表示されている数字の仕様が、readmeに書かれていなかった。
検証した結果、コンソールウィンドウに出力されるログの未読件数ということがわかりました。
未読件数が表示されるのは機能としてとても良いと感じました。
readmeにポップアップの仕様が書いてあった方がわかりやすいと思うので、追記していただきたいです。

---

The specification of the number displayed in the popup was not written in the readme.
As a result of verification, I understood that it is the number of unread logs output to the console window.
I felt that displaying unread counts is very good as a function.
I think that it would be easier to understand if the popup specification was written in the readme, so I would like to add it.

**Comment by TakanoriHosoya** [comment]
タイトル
Add document about the specification of pop-up, please

本文
The specification of the number displayed in the popup was not written in the readme.
As a result of verification, I understood that it is the number of unread logs output to the console window.
I felt that displaying unread counts is very good as a function.
I think that it would be easier to understand if the popup specification was written in the readme, so I would like to add it.

**Comment by TakanoriHosoya** [comment]
![image](https://user-images.githubusercontent.com/7413235/39110820-8f0d636c-470d-11e8-91e8-eae9c7d8bb2d.png)

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！
