### ISSUE TITLE
    OSS Gate Workshop: Akatsuki: 2018-04-23: ryuya.takahashi: Kemal: Work log

### ISSUE THREAD

**Issue by TobiasGSmollett** [oss-gate/workshop#825]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by csouls** [comment]
👀

**Comment by apstndb** [comment]
LGTM

**Comment by TakanoriHosoya** [comment]
みた！

**Comment by TobiasGSmollett** [comment]
まず最新のCrystalをインストールする

**Comment by TobiasGSmollett** [comment]
https://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html

**Comment by TobiasGSmollett** [comment]
前どこにCrystalをインストールしたのか忘れた

**Comment by TobiasGSmollett** [comment]
`which crystal`

**Comment by csouls** [comment]
`which crystal`  -> brew でインストールしたのか、普通に落としてインストールしたのか忘れた

**Comment by csouls** [comment]
前HomeBrew使う方法が書いてなくて、どちらだったか

**Comment by csouls** [comment]
brew でインストールされているかどうか試してみるコマンドは？ググってみる

**Comment by csouls** [comment]
[Homebrew使い方まとめ](https://qiita.com/vintersnow/items/fca0be79cdc28bd2f5e4) みて `brew list` 実行

**Comment by csouls** [comment]
`crystal-lang` あった！

**Comment by TobiasGSmollett** [comment]
```
) crystal --version
Crystal 0.24.2 (2018-03-10)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

**Comment by csouls** [comment]
https://github.com/crystal-lang/crystal/releases で最新かどうかをチェック

**Comment by csouls** [comment]
Crystalは1.0が出ていない新しい言語で、頻繁に更新があるので、最新を使ったほうが良いと思った

**Comment by csouls** [comment]
最新版が[公式サイト](https://crystal-lang.org/docs/installation/on_linux_using_linuxbrew.html) には書いてない...。
ここにバージョンが書いてあると嬉しい！

**Comment by csouls** [comment]
Homebrewの最新版ってどうやって更新されているか？
アップデートポリシーってどうなっているか？書いてあると嬉しいなぁ

**Comment by csouls** [comment]
https://brew.sh/ だとパッと見つからない？ https://docs.brew.sh/ 見てみる

**Comment by csouls** [comment]
https://docs.brew.sh/FAQ

**Comment by csouls** [comment]
https://docs.brew.sh/Versions も違う
多分Homebrewという団体が全てを管理しているわけじゃなさそう
世の中には無限にパッケージがあって、一つの組織が管理するのは現実的ではなさそうだな

**Comment by csouls** [comment]
Homebrewに登録されているはず！
使う人にとってはこれで十分、フレームワークの開発をする人向けの言語のバージョン管理方法は書いてないので。
Crystal の言語のステータスが開発中である。1.0 はこれで十分。
1.0 が出ているとしたら、  https://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html には
- CLIみたいな、REPLのインストール方法が書いてない
- バージョン指定で入れる方法が書いてない
- 最後のバージョン確認方法も書いてない

**Comment by TobiasGSmollett** [comment]
kemal 使う

**Comment by csouls** [comment]
(Crystalのインストールが終わったので)

**Comment by csouls** [comment]
で、Hello world をまず表示させてみたい

**Comment by csouls** [comment]
https://github.com/kemalcr/kemal のREADMEを読みつつ進める

**Comment by TobiasGSmollett** [comment]
crystal の使い方を忘れた
```
) crystal help
Usage: crystal [command] [switches] [program file] [--] [arguments]

Command:
    init                     generate a new project
    build                    build an executable
    deps                     install project dependencies
    docs                     generate documentation
    env                      print Crystal environment information
    eval                     eval code from args or standard input
    play                     starts crystal playground server
    run (default)            build and run program
    spec                     build and run specs (in spec directory)
    tool                     run a tool
    help, --help, -h         show this help
    version, --version, -v   show version
```

**Comment by csouls** [comment]
https://github.com/kemalcr/kemal#installation から始める

**Comment by csouls** [comment]
`crystal init app hello_world`

**Comment by TobiasGSmollett** [comment]
hello_world アプリ作る
```
) crystal init app hello_world
      create  hello_world/.gitignore
      create  hello_world/.editorconfig
      create  hello_world/LICENSE
      create  hello_world/README.md
      create  hello_world/.travis.yml
      create  hello_world/shard.yml
      create  hello_world/src/hello_world.cr
      create  hello_world/src/hello_world/version.cr
      create  hello_world/spec/spec_helper.cr
      create  hello_world/spec/hello_world_spec.cr
Initialized empty Git repository in /Users/ryuya.takahashi/Workspace/oss-gate/hello_world/.git/
```

**Comment by csouls** [comment]
(これはkemalのREADMEには書いてない)

**Comment by csouls** [comment]
https://github.com/kemalcr/kemal#super-simple-%EF%B8%8F
に書いてあるコードをコピペ

**Comment by csouls** [comment]
`crystal src/kemal_sample.cr` ではなく、 `crystal src/hello_world.cr`

**Comment by TobiasGSmollett** [comment]
`crystal deps.get` 忘れた
```
± crystal src/hello_world.cr
Error in src/hello_world.cr:2: while requiring "kemal": can't find file 'kemal' relative to '/Users/ryuya.takahashi/Workspace/oss-gate/hello_world/src'

require "kemal"
^
```

**Comment by csouls** [comment]
`crystal deps get` が必要っぽいが、 https://github.com/crystal-lang/crystal/issues/5510 消えてる！！

**Comment by TobiasGSmollett** [comment]
`crystal deps` 消えてた
https://github.com/crystal-lang/crystal/issues/5510

**Comment by TobiasGSmollett** [comment]
## 思ったこと
* crystal を初めて触る人が動かせるようなドキュメントになっていない
  * crystal-lang の Installation へのリンクが無い
  * 依存関係に従ってライブラリをダウンロードするコマンドが書いてない
  * 対応するcyrstalのバージョンが書いてない
  * プロジェクトを作るところが省略されている

**Comment by csouls** [comment]
http://kemalcr.com/guide/

**Comment by TobiasGSmollett** [comment]
## 大丈夫だったやつ
crystal-lang の Installation へのリンクが無い
依存関係に従ってライブラリをダウンロードするコマンドが書いてない
プロジェクトを作るところが省略されている

## 大丈夫じゃなかったやつ
対応するcyrstalのバージョンが書いてない

新しいリンクを追加することで、大丈夫だったやつは解決するが、大丈夫じゃなかったやつは解決しない。Crystal のバージョンを表すバッジがあればあとで追加したい。

**Comment by TobiasGSmollett** [comment]
バージョンを表すバッジを追加するというフィードバックは、一つのissueにするにはタスクの粒度が細かすぎるので、上と同じPRで書いた方が良さそうだ。

**Comment by TobiasGSmollett** [comment]
## 課題
Crystal をインストールして Kemal を動かそうとしたが、以下の3つの点がドキュメントにあると親切だと思った:
* Crystal の Installation へのリンク
* 依存するライブラリを取ってくるコマンド
* プロジェクトを作るコマンド

Kemal の公式ドキュメントの Getting Started にはこの3つが書かれていてわかりやすいので、そこへのリンクを追加した。

## 変更内容
Kemal 公式ドキュメントの Getting Started へのリンクを、 README.md の Installation に追加した。

**Comment by csouls** [comment]
似たようなFormatで書いているPRが無いか探してみた: no descption が結構あった
こういう感じだったら「今想像しているくらい丁寧にかけば伝わるであろう」と思った

**Comment by csouls** [comment]
https://github.com/kemalcr/kemal/pull/426 の書き方は良い

**Comment by TobiasGSmollett** [comment]
# Improve Installation in README
[Getting Started](http://kemalcr.com/guide/) in Kemal's official document is clear. Commands from installation of Crsytal-lang to application creation are not omitted. I added a link to Getting Started into Installation.

**Comment by TobiasGSmollett** [comment]
1. kemal を fork する
2. kemal を clone する
3. README.md 書き換える
4. 変更をプッシュする
5. PR にする

**Comment by TobiasGSmollett** [comment]
既にあったのでリポジトリ消す

**Comment by csouls** [comment]
2 と 3の間で、Branchを作る

**Comment by csouls** [comment]
と思ったけど、他の人のPRを見てブランチは`master`でも良いのではないかと思った。
もうちょっと周りのPRを見てみる

**Comment by csouls** [comment]
https://github.com/kemalcr/kemal/pull/427 は master to master だったけど、 https://github.com/kemalcr/kemal/pull/410 を見て、ブランチを切ることにした

**Comment by csouls** [comment]
🎉 🎉 🎉 https://github.com/kemalcr/kemal/pull/445

**Comment by kou** [comment]
お疲れ様でした！
この時間じゃないと取り組んじゃいけないわけではないので、引き続きやっていきましょう！
