### ISSUE TITLE
OSS Gate Workshop: fujitsu:2018-05-29: zhang.lei: qemu: Work log

### ISSUE THREAD

**Issue by raypadc** [oss-gate/workshop#839]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mikami3** [comment]
よろしくお願いします。

**Comment by raypadc** [comment]
qemuの公式サイトを探す。

**Comment by raypadc** [comment]
公式サイトを見つけました。
https://www.qemu.org/

**Comment by raypadc** [comment]
ライセンスを確認する。

**Comment by raypadc** [comment]
GNU General Public License, version 2であることを確認しました。
https://git.qemu.org/?p=qemu.git;a=blob;f=LICENSE;h=0e0b4b9553a5057ab29a20036e03ad113cfcb940;hb=HEAD

**Comment by raypadc** [comment]
qemuをlinxuにインストールする手順を探す。

**Comment by raypadc** [comment]
RHELの場合、以下の手順でできそう。
RHEL/CentOS: yum install qemu-kvm
https://www.qemu.org/download/#source

**Comment by raypadc** [comment]
インストールしてみる。

**Comment by raypadc** [comment]
ディスクのイメージ（linux.img）が必要そう。
https://qemu.weilnetz.de/doc/qemu-doc.html#pcsys_005fquickstart

**Comment by raypadc** [comment]
linux.imgを探して、download.

**Comment by raypadc** [comment]
manualに記載がなさそうなので、FAQなどをみてみる。

**Comment by raypadc** [comment]
そのまえにqemu-system-i386 コマンドはない？

**Comment by raypadc** [comment]
パスを通していないかんじではなさそうです。
どうもrpmにそのコマンドがないようです。
[ec2-user@ip-10-0-0-254 ~]$ rpm -qa|grep qemu
qemu-img-1.5.3-156.el7_5.2.x86_64
qemu-guest-agent-2.8.0-2.el7.x86_64
qemu-kvm-common-1.5.3-156.el7_5.2.x86_64
ipxe-roms-qemu-20170123-1.git4e85b27.el7_4.1.noarch
qemu-kvm-1.5.3-156.el7_5.2.x86_64
[ec2-user@ip-10-0-0-254 ~]$ rpm -ql qemu-kvm|grep i386
[ec2-user@ip-10-0-0-254 ~]$ rpm -ql qemu-kvm-common|grep i386
[ec2-user@ip-10-0-0-254 ~]$ rpm -ql qemu-img|grep i386
[ec2-user@ip-10-0-0-254 ~]$ rpm -ql qemu-guest-agent|grep i386
[ec2-user@ip-10-0-0-254 ~]$

**Comment by raypadc** [comment]
ソースコードをダウンロードして、grepをかけてみる。

**Comment by raypadc** [comment]
download & build　手順
https://www.qemu.org/download/

**Comment by raypadc** [comment]
wgetはない。
[ec2-user@ip-10-0-0-254 ~]$ wget https://download.qemu.org/qemu-2.12.0.tar.xz
-bash: wget: command not found

**Comment by raypadc** [comment]
wgetをインストールしたら、downloadできました。
以下の手順でまずソースコードを解凍する。
wget https://download.qemu.org/qemu-2.12.0.tar.xz
tar xvJf qemu-2.12.0.tar.xz
cd qemu-2.12.0
./configure
make

**Comment by raypadc** [comment]
.configを通すため、いろんなrpmをインストールしました。
とりあえず、configureが通りました。

**Comment by raypadc** [comment]
makeします。

**Comment by raypadc** [comment]
つぎにdisk.imgの作成。
以下のコマンドで作成できそう。
QEMU-IMG(1)                                                                  QEMU-IMG(1)

NAME
       qemu-img - QEMU disk image utility

SYNOPSIS
       usage: qemu-img command [command options]

DESCRIPTION
       qemu-img allows you to create, convert and modify images offline. It can handle
       all image formats supported by QEMU.

       Warning: Never use qemu-img to modify images in use by a running virtual machine
       or any other process; this may destroy the image. Also, be aware that querying an
       image that is being modified by another process may encounter inconsistent state.

**Comment by raypadc** [comment]
linux.imgを一応できたっぽい
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ man qemu-img
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ qemu-img create linux.img
qemu-img: linux.img: Image creation needs a size parameter
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ man qemu-img
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ qemu-img create linux.img 512MiB
qemu-img: Invalid image size specified! You may use k, M, G, T, P or E suffixes for
qemu-img: kilobytes, megabytes, gigabytes, terabytes, petabytes and exabytes.
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ qemu-img create linux.img 512M
Formatting 'linux.img', fmt=raw size=536870912

**Comment by raypadc** [comment]
起動できません。
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ ./i386-softmmu/qemu-system-i386 linux.img
WARNING: Image format was not specified for 'linux.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
VNC server running on ::1:5900
q^Cqemu-system-i386: terminating on signal 2

**Comment by raypadc** [comment]
bug報告の方法
https://www.qemu.org/contribute/

**Comment by raypadc** [comment]
diskのformatは変というエラーメッセージなので、format指定して、再作成
qemu-img create -f qcow2 linux.img 512M
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ file linux.img
linux.img: QEMU QCOW Image (v3), 536870912 bytes　←ただしそう。

**Comment by raypadc** [comment]
でも、起動しない。
[ec2-user@ip-10-0-0-254 qemu-2.12.0]$ ./i386-softmmu/qemu-system-i386 linux.img
VNC server running on ::1:5900

**Comment by raypadc** [comment]
./i386-softmmu/qemu-system-i386 -nographic linux.imgでやったら、とりあえず、boot シーケンスが走るようになった。が、起動しない。たぶん、imgが変。linux.imgをmountして、中身を確認すべきが、時間切れなので、投稿テーマを考えます。
iPXE 1.0.0+ (0600d) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE ELF MBOOT PXE bzImage Menu PXEXT

net0: 52:54:00:12:34:56 using 82540em on 0000:00:03.0 (open)
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
Configuring (net0 52:54:00:12:34:56)..... ok
net0: 10.0.2.15/255.255.255.0 gw 10.0.2.2
Nothing to boot: No such file or directory (http://ipxe.org/2d03e13b)
No more network devices

No bootable device.

**Comment by raypadc** [comment]
ユーザ用のmailinglistがありました。
過去投稿をみて、同じ質問があるかを確認する。
http://lists.nongnu.org/archive/html/qemu-discuss/

**Comment by raypadc** [comment]
検索キーワードは「 qemu-system-i386 」です。
同じ質問が見当たりません。

**Comment by raypadc** [comment]
@mikami3 日本語版の投稿文章を作成しましたので、ご確認ください。

- 環境
　x86_64
   Red Hat Enterprise Linux Server release 7.5 (Maipo)
- 問題
手順[1]通りにQEMUのpackageをインストールした後に、ユーザマニュアル[2]に従って、2.2章のQuick Startの通りにguest osを起動しようとしますが、qemu-system-i386 のコマンドがありません。手順は不足しているのでしょうか。ちなみに、qemu-2.12.0をdownloadして、ビルドしますとqemu-system-i386のバイナリができました。

インストールされたことを確認した
rpm -qa|grep qemu-kvm
qemu-kvm-common-1.5.3-156.el7_5.2.x86_64
qemu-kvm-1.5.3-156.el7_5.2.x86_64

guest osの起動でcommand not foundで失敗した
qemu-system-i386  linux.img
-bash: qemu-system-i386: command not found


[1]https://www.qemu.org/download/
[2]https://qemu.weilnetz.de/doc/qemu-doc.html

**Comment by raypadc** [comment]
以下の指摘を反映する
・箇条書きにする
・ちなみにの文章を削除する。

•環境
 x86_64
 Red Hat Enterprise Linux Server release 7.5 (Maipo)
•問題
 ユーザマニュアル[1]の2.2章のQuick Startの通りにコマンド[2]でguest osを起動できません。

・やったこと
手順[3]通りにQEMUのpackageをインストールした

インストールされたことを確認した
rpm -qa|grep qemu-kvm
 qemu-kvm-common-1.5.3-156.el7_5.2.x86_64
 qemu-kvm-1.5.3-156.el7_5.2.x86_64

- 質問

[1]https://qemu.weilnetz.de/doc/qemu-doc.html
[2]qemu-system-i386 linux.img
 -bash: qemu-system-i386: command not found

[2]https://www.qemu.org/download/

**Comment by raypadc** [comment]
Subjuctを考える。
挨拶分をいれる。

**Comment by raypadc** [comment]
Subject：qemu-system-i386 command not found

I am a beginner of QEMU. I want to run a guest OS on QEMU. 
 I executed command wroten on document of QEMU version 2.12.50 User Documentation[1] chapter 2.2, and failed by command not found. I haven't know what is the problem by reading documents of QEMU. I wish someone can help me to resolve this problme. Thanks.
qemu-system-i386 linux.img
-bash: qemu-system-i386: command not found

•Question
 why qemu-system-i386 command not found.


•What I have done
 Follow the guide[2] , I have installed QEMU package.
 rpm -qa|grep qemu-kvm
 qemu-kvm-common-1.5.3-156.el7_5.2.x86_64
 qemu-kvm-1.5.3-156.el7_5.2.x86_64


•Environment
 x86_64
 Red Hat Enterprise Linux Server release 7.5 (Maipo)


[1]https://qemu.weilnetz.de/doc/qemu-doc.html
 [2]https://www.qemu.org/download/

Best Regards,
 Lei Zhang zhang.lei@jp.fujitsu.com

**Comment by raypadc** [comment]
投稿先：qemu-discuss@nongnu.org
Using Qemu-discuss  
To post a message to all the list members, send email to qemu-discuss@nongnu.org.  
https://lists.nongnu.org/mailman/listinfo/qemu-discuss

**Comment by y-goto** [comment]
お疲れさまでした。環境の問題もあってMLへ投稿までは至りませんでしたが、コツはつかめたと思います。今後も頑張ってください。
本Issueはクローズします。
