### ISSUE TITLE
OSS Gateワークショップ 2016-7-30: MatsumotoHiroko: Rails: 作業ログ

### ISSUE THREAD

**Issue by MatsumotoHiroko** [oss-gate/workshop#84]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by MatsumotoHiroko** [comment]
* 作業：vagrantはあるがmacの中にはrailsが入っていないのでインストールする。
* 思っていること：まずはrailsの公式ホームページを確認する。googleで検索する

**Comment by MatsumotoHiroko** [comment]
作業：見つかった。 http://rubyonrails.org/
思っていること：documentを探せばインストール方法が書いてあるはず

**Comment by MatsumotoHiroko** [comment]
* 作業：guideの中にあった http://guides.rubyonrails.org/getting_started.html
* 思っていること：Start guideの手順通りにコマンドを叩けばインストールされるだろう

**Comment by MatsumotoHiroko** [comment]
* 作業：rubyのバージョンが2.2.2以上でないとダメだと書いてあるのでバージョンアップをする
* 思っていること：rubyの公式サイトに手順が書いてあるだろう

**Comment by MatsumotoHiroko** [comment]
* 作業：rubyの公式サイトでバージョンアップ方法を探す
* 思っていること：documentやguideなどの名前のページに手順が書いてあるだろう

**Comment by MatsumotoHiroko** [comment]
* 作業：Installing Rubyというページにインストール手順が書いてある https://www.ruby-lang.org/en/documentation/installation/
* 思っていること：macの項目通りに従えばインストールできるだろう

**Comment by MatsumotoHiroko** [comment]
* 作業：Installing Rubyというページにインストール手順が書いてある https://www.ruby-lang.org/en/documentation/installation/
* 思っていること：macの項目通りに従えばインストールできるだろう

**Comment by MatsumotoHiroko** [comment]
* 作業：自分のOSのバージョンはCapitanで、brewコマンドはOn OS X Yosemite and Mavericks, Ruby 2.0 is included. OS X Mountain Lion, Lion, and Snow Leopard ship with Ruby 1.8.7.　に対応とある https://www.ruby-lang.org/en/documentation/installation/#homebrew
* 思っていること：versionが古い。更新されていないので更新してほしい

**Comment by MatsumotoHiroko** [comment]
* 作業：brewコマンドを叩いたら
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
が発生したので、sudo権限でもう一度叩いてみる
* 思っていること：今度は動くだろう

**Comment by MatsumotoHiroko** [comment]
* 作業：brewのバージョンを調べ、古いかを調べる　brew --version
0.9.5　と出た
* 思っていること：全くアップデートしてないので古いのではないか

**Comment by MatsumotoHiroko** [comment]
* 作業：homebrewの公式サイトを探す
* 思っていること：バージョン情報が出ているはず

**Comment by MatsumotoHiroko** [comment]
* 作業：brew、rubyを最新にする
* 思っていること：そうしないとrails最新版をインストールできないため

**Comment by MatsumotoHiroko** [comment]
* 作業：  brew updateする
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/README.md#readme
* 思っていること：バージョンを最新にできるはず

**Comment by MatsumotoHiroko** [comment]
* 作業： brew update で　Homebrew 0.9.9 (git revision b999e; last commit 2016-07-29)　最新になったので、次はrubyをアップデート　brew install ruby
* 思っていること：アップデートされるはずだけど２つrubyが入ってしまいそう

**Comment by MatsumotoHiroko** [comment]
* 作業： brew install rubyは成功したが古いrubyが入っている。rubyのアンインストールをしよう
* 思っていること：グーグルで聞いてみれば情報があるはず

**Comment by MatsumotoHiroko** [comment]
* 作業： PATHなどは通っている。シェルを再起動したら新しいバージョンが使われるようになった
* 思っていること：そんな原因で詰まっていたのか・・・

**Comment by MatsumotoHiroko** [comment]
* 作業：Documentのissueを出すためにcontribution ガイドラインを読んだ　https://github.com/ruby/www.ruby-lang.org/wiki　
* 思っていること：コントリビューションにissueの出し方が書いてあるに違いない

**Comment by MatsumotoHiroko** [comment]
* 作業：proppose手順通りにissueを「Propose File Change」ボタンがない
https://github.com/ruby/www.ruby-lang.org/wiki　　How to propose a change　「Propose File Change」ボタンがない
* 思っていること：と思ったがありました

**Comment by MatsumotoHiroko** [comment]
* 作業：git push したら失敗をした
* 思っていること：リポジトリが異なった

 ```
git push origin instration_fix_osx
ERROR: Permission to ruby/www.ruby-lang.org.git denied to MatsumotoHiroko.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by MatsumotoHiroko** [comment]
* 作業：手元の変更を保持したい git diff --cached で実行した
* 思っていること：コミット済みのdiffを見るオプションの --chched を知らなかった

**Comment by MatsumotoHiroko** [comment]
* 作業：forkして自分用のリポジトリを用意したのでこちらをpullして変更分をpushする
* 思っていること：

**Comment by kou** [comment]
お疲れ様でした！

**Comment by MatsumotoHiroko** [comment]
* 作業： rubyのインストールドキュメントにCapitanが抜けていることを指摘したらfeedbackが来たので修正する https://github.com/ruby/www.ruby-lang.org/pull/1434
* 思っていること：英語・・・
