### ISSUE TITLE
OSS Gate Workshop: fujitsu: 2018-05-29: shimada123: Docker: Work log

### ISSUE THREAD

**Issue by shimada123** [oss-gate/workshop#840]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by f-higashi** [comment]
こんにちは

**Comment by shimada123** [comment]
Dockerの公式サイトを探す。：
https://www.docker.com/

**Comment by shimada123** [comment]
Dockerの公式マニュアルを探す：
https://docs.docker.com/

**Comment by shimada123** [comment]
インストールする、Docker editionsを選ぶ：
Community Edition

**Comment by shimada123** [comment]
プラットフォームを選ぶ：
・teraturmで、システム情報を確認
[ec2-user@ip-10-0-0-221 /]$ uname -a
Linux ip-10-0-0-221 4.14.33-51.37.amzn1.x86_64 #1 SMP Thu May 3 20:07:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shimada123** [comment]
[ec2-user@ip-10-0-0-221 /]$  cat /etc/system-release
Amazon Linux AMI release 2018.03

**Comment by shimada123** [comment]
・下記ブログより、redhat系のdistributionと判断→centosを使用する。
https://dev.classmethod.jp/cloud/aws/amazon-linux-centos-rhel-difference/

**Comment by shimada123** [comment]
・dockerが既に環境に入っているか確認する。
ec2-user@ip-10-0-0-221 /]$ docker version
-bash: docker: command not found

**Comment by shimada123** [comment]
・Install Docker CEを行う

**Comment by shimada123** [comment]
・Install using the repository>Set up the repositoryを進める

**Comment by shimada123** [comment]
・1.Install required packagesを実行：
$sudo yum install -y yum-utils \ device-mappter-persistent-data \ lvm2
・実行結果：
Loaded plugins: priorities, update-motd, upgrade-
              : helper
amzn-main                 | 2.1 kB     00:00
amzn-updates              | 2.5 kB     00:00
Package yum-utils-1.1.31-40.29.amzn1.noarch alrea                                                                                                                                            dy installed and latest version
No package  device-mappter-persistent-data availa                                                                                                                                            ble.
No package  lvm2 available.
Nothing to do

**Comment by shimada123** [comment]
→実行結果より、2つのパッケージがみつからない。
No package device-mappter-persistent-data availa ble.
No package lvm2 available.

**Comment by f-higashi** [comment]
aws ami に関しては、ここに記述されています。

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html

docker のマニュアルでは、awsを利用する場合、aws docker cloud service を利用する方法を提案しているようです

**Comment by shimada123** [comment]
フィードバックは以下を考えています。
・aws環境を使用する場合に、docker公式のマニュアルへ、awsを参照するようにしてください。

**Comment by shimada123** [comment]
フィードバックの前に、頂いたaws amiのインストール手順を実施します。
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html

**Comment by shimada123** [comment]
>To install Docker on an Amazon Linux instanceを進めます。

**Comment by shimada123** [comment]
1-2：実施済、
3.Update the installed packages and package cache on your instance.を下記の通り実行します。
・実行コマンド
>$sudo yum update -y
・実行結果：問題なく完了した。

Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main                                                                 | 2.1 kB  00:00:00
amzn-updates                                                              | 2.5 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package ntp.x86_64 0:4.2.6p5-44.36.amzn1 will be updated
---> Package ntp.x86_64 0:4.2.8p11-1.37.amzn1 will be an update
---> Package ntpdate.x86_64 0:4.2.6p5-44.36.amzn1 will be updated
---> Package ntpdate.x86_64 0:4.2.8p11-1.37.amzn1 will be an update
---> Package openssh.x86_64 0:7.4p1-11.68.amzn1 will be updated
---> Package openssh.x86_64 0:7.4p1-16.69.amzn1 will be an update
---> Package openssh-clients.x86_64 0:7.4p1-11.68.amzn1 will be updated
---> Package openssh-clients.x86_64 0:7.4p1-16.69.amzn1 will be an update
---> Package openssh-server.x86_64 0:7.4p1-11.68.amzn1 will be updated
---> Package openssh-server.x86_64 0:7.4p1-16.69.amzn1 will be an update
---> Package openssl.x86_64 1:1.0.2k-8.107.amzn1 will be updated
---> Package openssl.x86_64 1:1.0.2k-12.109.amzn1 will be an update
---> Package rpcbind.x86_64 0:0.2.0-13.9.amzn1 will be updated
---> Package rpcbind.x86_64 0:0.2.0-13.10.amzn1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================
 Package                 Arch           Version                       Repository            Size
=================================================================================================
Updating:
 ntp                     x86_64         4.2.8p11-1.37.amzn1           amzn-updates         1.0 M
 ntpdate                 x86_64         4.2.8p11-1.37.amzn1           amzn-updates          88 k
 openssh                 x86_64         7.4p1-16.69.amzn1             amzn-updates         639 k
 openssh-clients         x86_64         7.4p1-16.69.amzn1             amzn-updates         1.1 M
 openssh-server          x86_64         7.4p1-16.69.amzn1             amzn-updates         511 k
 openssl                 x86_64         1:1.0.2k-12.109.amzn1         amzn-updates         1.8 M
 rpcbind                 x86_64         0.2.0-13.10.amzn1             amzn-updates          56 k

Transaction Summary
=================================================================================================
Upgrade  7 Packages

・・・（省略）

Updated:
  ntp.x86_64 0:4.2.8p11-1.37.amzn1               ntpdate.x86_64 0:4.2.8p11-1.37.amzn1
  openssh.x86_64 0:7.4p1-16.69.amzn1             openssh-clients.x86_64 0:7.4p1-16.69.amzn1
  openssh-server.x86_64 0:7.4p1-16.69.amzn1      openssl.x86_64 1:1.0.2k-12.109.amzn1
  rpcbind.x86_64 0:0.2.0-13.10.amzn1

Complete!

**Comment by shimada123** [comment]
**4.Install the most recent Docker Community Edition package.**を下記のとおり実行します。

**Comment by shimada123** [comment]
**5.Start the Docker service.**を下記のとおり実行します。
・実行コマンド
```
$sudo service docker start
Starting cgconfig service:                                 [  OK  ]
Starting docker:        .                                  [  OK  ]
```

**Comment by shimada123** [comment]
**6.Add the ec2-user to the docker group so you can execute Docker commands without using sudo.** を下記のとおり実行します。
→問題なく動作しました。
・実行コマンド
```
$ sudo usermod -a -G docker ec2-user
```

**Comment by shimada123** [comment]
**7.Log out and log back in again to pick up the new docker group permissions.** を実行し、ターミナルを切断します。

**Comment by shimada123** [comment]
再度ターミナルに接続し、
**8.Verify that the ec2-user can run Docker commands without sudo.** を実行します。
→下記のとおり、sudoなしで実行することを確認しました。
・実行コマンド
```
$docker info
File: dir       Node: Top       This is the top of the INFO tree

  This (the Directory node) gives a menu of major topics.
  Typing "q" exits, "?" lists all Info commands, "d" returns here,
  "h" gives a primer for first-timers,
  "mEmacs<Return>" visits the Emacs topic, etc.
・・・(省略)
```

**Comment by shimada123** [comment]
上記までで、**To install Docker on an Amazon Linux instance**を完了しました。

**Comment by shimada123** [comment]
Dockerがインストールされたことを確認します。
→確認できました。
```
docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built: Tue Apr  3 23:37:44 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6/17.12.1-ce
  Built:        Tue Apr  3 23:38:52 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by shimada123** [comment]
以上で、OSS：Dockerに関する作業を終了し、
開発元へのフィードバック内容を考えます。
フィードバック点としては、検討していた、「aws環境を使用する場合に、docker公式のマニュアルへ、awsを参照するようにしてください。」にします。

**Comment by shimada123** [comment]
フィードバックを、dockerのissueとして登録しました。
https://github.com/docker/docker.github.io/issues/6774

**Comment by y-goto** [comment]
返事が来てますね。内容を確認して返事を考えてみるとよいでしょう。

**Comment by y-goto** [comment]
時間が経過したので本Issueはクローズします。今後も頑張ってください。
