### ISSUE TITLE
OSS Gate Workshop: fujitsu: 2018-05-29: izawatk: Selenium ide: Work log

### ISSUE THREAD

**Issue by izawatk** [oss-gate/workshop#841]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mikami3** [comment]
よろしくお願いします。

**Comment by izawatk** [comment]
利用手順を確認するために公式サイトを探す。

**Comment by izawatk** [comment]
公式サイトを検出
https://www.seleniumhq.org/

**Comment by izawatk** [comment]
ドキュメントはこちら
https://www.seleniumhq.org/docs/

**Comment by izawatk** [comment]
IDEのページあり
https://www.seleniumhq.org/docs/02_selenium_ide.jsp

**Comment by izawatk** [comment]
ライセンスを確認する
https://www.seleniumhq.org/about/license.jsp
Selenium関連はApache 2.0 Licenseとのこと

**Comment by izawatk** [comment]
導入は、ブラウザに対するプラグイン追加でいけそう。
FirefoxとChromeの記載あり。
PCにChromeが入っているので、インストールしてみる。

**Comment by izawatk** [comment]
"Installing the IDE"にChromeのアドオンのサイトへのリンクがあるため、
リンク先へ移動、"CHROMEに追加"ボタンを押した
https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd

**Comment by izawatk** [comment]
"Opening the IDE”に、右上にボタンが出るから押せとある

**Comment by izawatk** [comment]
Seと書いたボタンができたので押したら、IDEウィンドウが表示された

**Comment by izawatk** [comment]
ツールバーが表示された。記録・再生のボタンの説明があるのでできそう。

**Comment by izawatk** [comment]
動作確認
記録ボタンを押下し、
googleで"selenium ide"を検索し、Selenium IDEのサイトを開く動作を記録

**Comment by izawatk** [comment]
再生したが、検索ワードが入らない

**Comment by izawatk** [comment]
Yahooの検索で記録してみる

**Comment by izawatk** [comment]
以下の動作を記録、再生できた
Yahooの検索ワード入力"selenium"→Seleniumの公式サイトを開く→
SeleniumIDEのドキュメントのページを開く

**Comment by izawatk** [comment]
動作記録時、動作を認識すると、"click at"や"type"というポップアップが画面左下に表示されるが、
googleのサイトでの検索ワードを指定しても、ポップアップ表示がされず、
IDE側のCommandにも表示されない

**Comment by izawatk** [comment]
動作記録時、googleで検索ワード入力後、Enterキーで検索すると、操作が認識されないが、
Google検索ボタンをクリックすると、認識される

**Comment by mikami3** [comment]
Contributeについて確認しましょう。

**Comment by mikami3** [comment]
ポストする話に
https://github.com/SeleniumHQ/selenium-ide/issues/168
この issues は関係あるか読んでみてはどうでしょうか。

**Comment by izawatk** [comment]
googleの検索を記録時、Enterキーでの動作が記録されない

以下の動作を記録した。
・googleのサイトを開く(https://www.google.com/)
・検索窓に"selenium"を記入
・Enterキーで決定し、検索結果を表示

再生しても"selenium"の文字列が入力されず、検索が実行されない。
IDE側でも"open" と "click at"のCommandしか記録されていない。

また、動作記録時、googleで検索ワード入力後、Enterキーで決定ではなく、
"Google検索"ボタンをクリックすると、Commandで認識され、
文字列が入力され、検索が実行される。

他サイト（Yahoo）でも、Enterキーで文字列の決定がされていたため、
googleのサイトでも正しく動作が記録されるべき。

**Comment by izawatk** [comment]
https://github.com/oss-gate/workshop/issues/841#issuecomment-392660806
類似問題の情報ありがとうございます。確認します。
以下の問題も似ているようで確認します。
"sendKeys" ${KEY_ENTER} is mishandled at certain cases #151

**Comment by izawatk** [comment]
英語文書いてみました。

"type" command is not recorded at certain cases.

I recorded following action.

1. Open google.(https://www.google.com/)
2. Input "selenium" at search box.
3. Press Enter key.
   And search result is displayed.

When running the test case, "selenium" is not input and 
search result is not displayed.
Only "open" and "click at" command is recorded at IDE.

And then, we tried to click "Google Search" insted of pressing Enter key.
As a result, "type" command is recognized and search result is displayed.

We tested Other site(ex.yahoo), and the result is OK.
So I think pressing Enter key should be recognized.

**Comment by izawatk** [comment]
Chrome version: 66.0.3359.181
Selenium IDE version: 3.0.3

**Comment by izawatk** [comment]
投稿
https://github.com/SeleniumHQ/selenium-ide/issues/214

**Comment by y-goto** [comment]
回答が返ってきてますね。内容を確認して、それを受け入れるかどうか考えてみるとよいでしょう。

**Comment by y-goto** [comment]
時間が経過したので本Issueはクローズします。今後もこの調子で頑張ってください。
