### ISSUE TITLE
 OSS Gate Workshop: fujitsu: 2018-05-29: ume1087: WebGME: Work log

### ISSUE THREAD

**Issue by ume1087** [oss-gate/workshop#844]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kaakaa** [comment]
@ume1087 よろしくおねがいします～

**Comment by ume1087** [comment]
WebGMEで検索。
公式サイト↓
https://webgme.org/

**Comment by ume1087** [comment]
https://editor.webgme.org/docs/source/index.html
より
MIT license

**Comment by ume1087** [comment]
インストール↓
https://webgme.readthedocs.io/en/latest/

**Comment by ume1087** [comment]
Installing MongoDB (Ubuntu)
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
sudo apt-get update
sudo apt-get install -y mongodb-org

**Comment by ume1087** [comment]
Gitインストール
sudo apt-get install git

**Comment by ume1087** [comment]
Installing webgme-cli
https://webgme.readthedocs.io/en/latest/getting_started/creating_a_repository.html
npm install -g webgme-cli

**Comment by ume1087** [comment]
Creating a Repository
ubuntu@ip-10-0-0-173:~$ webgme init ossgate-test
Created project at /home/ubuntu/ossgate-test.

Start your WebGME app with 'webgme start' from the project root.
It is recommended to run 'npm init' from the within project to finish configuration.
ubuntu@ip-10-0-0-173:~$

**Comment by ume1087** [comment]
Start WebGME
$ cd ossgate-test
$ webgme start

**Comment by ume1087** [comment]
Installing the node_modules
$ de ossgate-test
$ npm install
$ npm install webgme

**Comment by ume1087** [comment]
Starting the server
npm start

**Comment by ume1087** [comment]
$ npm start
：
web server: http://127.0.0.1:8888 http://10.0.0.173:8888
：
http://10.0.0.173:8888にアクセスする必要があるが、
ここからはAWSプライベートアドレスにアクセスできない。
↓よって、
AWSのセキュリティグループでTCP/8888を許可してから
IEでhttp://18.182.20.46:8888にアクセスしてみたが、
期待通りに表示されない。

**Comment by ume1087** [comment]
そのため、
http://10.0.0.173:8888アクセスではうまくいくか試してみるために、
AWS内にWindowsインスタンスを作成中。

**Comment by ume1087** [comment]
AWS内のWindowsインスタンスから
IE: http://10.0.0.173:8888 表示できない。
Chrome: http://10.0.0.173:8888 表示できた。

以下のような記述が見つかった。
https://github.com/webgme/webgme#getting-started
Browser
We aim to support all the major modern browsers. However we recommend using Chrome for two reasons: manual testing is mostly done using chrome and all performance profiling is done against the V8 JavaScript Engine.

**Comment by ume1087** [comment]
Pluginがブラウザー上で動作しているのか、サーバ上で動作しているのかを、
Pluginのソースコードで判定する方法を知りたい。
↓英訳
Is there a way to decide
in a plugin source code
whether the plugin is running on browser or server?

**Comment by ume1087** [comment]
このようなissueを発行しました。
https://github.com/webgme/webgme/issues/1607

**Comment by y-goto** [comment]
回答が返ってきてますね。内容を確認しておきましょう。
また、お礼を言っておくとbetterですね。

**Comment by ume1087** [comment]
以下の文面でreplyしました。
（window variableにより、目的とする処理を実現できました）

Thanks for the reply.
I will check by WebGMEGlobal or window variable.

**Comment by y-goto** [comment]
お疲れ様でした。時間が立ったので、本Issueはクローズしていただきました。
最後のリプライできたのは大変よかったと思います。今後もこの調子で頑張ってください。
