### ISSUE TITLE
OSS Gateワークショップ 2016-07-30: ryu39: kakurenbo-puti: 作業ログ

### ISSUE THREAD

**Issue by ryu39** [oss-gate/workshop#85]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by ryu39** [comment]
* 作業 : まず対象のgemを使う環境を用意するため、Railsのアプリケーションが動く環境を構築する。Railsチュートリアルにそってやってみる。
* 思っていること : ここで詰まることはないはず..

**Comment by ryu39** [comment]
* 作業 : Railsチュートリアルは環境を用意するだけだと時間がかかりそうなので、rails本体のgithubのREADMEに従ってインストールしてみる。

**Comment by ryu39** [comment]
* 作業 : railsのREADMEに従ってインストールを行い、トップページの表示に成功した。

**Comment by ryu39** [comment]
* 作業 : railsのREADMEだとDBを使うところまで行かなかったので、Rails Guidesのチュートリアルに従って、サンプルアプリケーションをインストール、動かしてみる。
http://guides.rubyonrails.org/getting_started.html

**Comment by ryu39** [comment]
* 作業 : やりたいことをはじめるのに時間がかかりそうなので、scaffoldでMemberというモデル、コントローラー、ビューを一気に作成する。
bin/rails generate scaffold member name:string

**Comment by ryu39** [comment]
* 作業 : bin/rails migrateを実行し、画面からMemberを登録、更新削除していみる。

**Comment by ryu39** [comment]
* 作業 : kakurenbo-putiをインストールしてみる。https://github.com/alfa-jpn/kakurenbo-puti

**Comment by ryu39** [comment]
* 作業 : Gemfileに追記 -> bundle が問題なく成功したので、ドキュメントに従ってMemberモデルに論理削除用のカラムを追加してみる。
* 思っていること : 問題なく動くはず...

**Comment by ryu39** [comment]
* 思っていること : migrationファイル作った後でdb:migrateをやるのが暗黙の了解になっていそう。

**Comment by ryu39** [comment]
* 作業 : カラム追加ができたので、ドキュメントに従って、Modelクラスに変更を加える。

**Comment by ryu39** [comment]
* 作業 : 動かせる環境ができたっぽい。READMEに書いてあるメソッドを一通り動かしてみる。

**Comment by ryu39** [comment]
* 作業 : Advancedの項目はできなかったけど、各メソッドの実行は問題なく出来た。
以下の問題を解決したい。

```sql
irb(main):001:0> members = Member.all
  Member Load (1.2ms)  SELECT "members".* FROM "members"
=> #<ActiveRecord::Relation [#<Member id: 2, name: "aaa", created_at: "2016-07-30 02:58:54", updated_at: "2016-07-30 03:11:51", soft_destroyed_at: nil>, #<Member id: 3, name: "bbb", created_at: "2016-07-30 02:58:58", updated_at: "2016-07-30 02:58:58", soft_destroyed_at: nil>, #<Member id: 4, name: "ccc", created_at: "2016-07-30 02:59:03", updated_at: "2016-07-30 02:59:03", soft_destroyed_at: nil>]>
irb(main):002:0> members.reject(&:soft_destroyed?)
  Member Exists (0.2ms)  SELECT  1 AS one FROM "members" WHERE ("members"."id" NOT IN (SELECT "members"."id" FROM "members" WHERE "members"."soft_destroyed_at" IS NULL)) AND "members"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Member Exists (0.2ms)  SELECT  1 AS one FROM "members" WHERE ("members"."id" NOT IN (SELECT "members"."id" FROM "members" WHERE "members"."soft_destroyed_at" IS NULL)) AND "members"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  Member Exists (0.1ms)  SELECT  1 AS one FROM "members" WHERE ("members"."id" NOT IN (SELECT "members"."id" FROM "members" WHERE "members"."soft_destroyed_at" IS NULL)) AND "members"."id" = ? LIMIT ?  [["id", 4], ["LIMIT", 1]]
=> [#<Member id: 2, name: "aaa", created_at: "2016-07-30 02:58:54", updated_at: "2016-07-30 03:11:51", soft_destroyed_at: nil>, #<Member id: 3, name: "bbb", created_at: "2016-07-30 02:58:58", updated_at: "2016-07-30 02:58:58", soft_destroyed_at: nil>, #<Member id: 4, name: "ccc", created_at: "2016-07-30 02:59:03", updated_at: "2016-07-30 02:59:03", soft_destroyed_at: nil>]
```

**Comment by ryu39** [comment]
* 振り返りコメント : gem単体でテストできるはずなので、そちらの方から進めていくのもありだったかも。
-> テストコードも用意されているので、午後は単体でテストを動かすところからやってみる。

**Comment by ryu39** [comment]
* 作業 : gem単体でテストを動かしてみる。このリポジトリをforkして、ローカルにcloneしてやってみる。

**Comment by ryu39** [comment]
* 思ったこと : forkしてcloneすることができた。ただ、テストを動かす方法がわからない。gemの標準的な方法があるのかもしれないが、READMEに書いてあると親切かもしれない。

**Comment by ryu39** [comment]
* 作業 : Qiitaの記事をみて「bundle exec rake spec」を実行したが、テストが動かなかった。RSpecのサイトを見て、テストの動かし方を調べる。

**Comment by ryu39** [comment]
* 「bundle exec rspec」で実行したら多くのテストが失敗した。
* activerecordを5.0.0 -> 4.2.7に変更したら全てのテストが通った。

**Comment by ryu39** [comment]
見つけた問題

* READMEでマイグレーションファイルを追加した後にdb:migrateを実行しないといけないことがわからない。
* テストの動かし方がわからない。
* activerecordのバージョンが5.0.0だとテストが通らない。
* 「soft_destroyed?」メソッドが呼び出しのたびにDBにアクセスしていて、パフォーマンスに問題がありそう。

**Comment by ryu39** [comment]
* 見出しの大きさもおかしそう

**Comment by ryu39** [comment]
> READMEでマイグレーションファイルを追加した後にdb:migrateを実行しないといけないことがわからない。
上記に関してのPRを出した!! https://github.com/alfa-jpn/kakurenbo-puti/pull/13

**Comment by ryu39** [comment]
振り返りメモ

* なぜそう判断したのか、作業ログに残しておいたほうが良い。(Railsチュートリアルを使わない理由)
* commitは、複数のことを同時にやらないほうが良い。(db:migrateの追加、$を先頭に入れるは分けたほうが良い)

**Comment by ryu39** [comment]
* 出た情報はちゃんとPRに載せるとマージしやすい。Rails 5だと動かない、4だと動くときのターミナルに表示された情報などを載せる。Rails 4, 5両方で動くことを確認できていると非常に嬉しい。

**Comment by kou** [comment]
お疲れ様でした！

**Comment by ryu39** [comment]
> 見出しの大きさもおかしそう

こちらもプルリクを出しました。

**Comment by ryu39** [comment]
先日ビギナーとして参加した時のメモなどを自分のブログに記載しました。

https://www.hommax39.com/archives/213

今後のワークショップに生かしていただけると幸いです🙇

**Comment by kou** [comment]
ありがとうございます！活かします！

これをきっかけにこれからもOSSの開発に継続に参加することを期待しています！
またの参加もお待ちしています！
