### ISSUE TITLE
OSS Gateワークショップ 2016-07-30: wataru0225: rails: 作業ログ

### ISSUE THREAD

**Issue by wataru0225** [oss-gate/workshop#86]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by wataru0225** [comment]
* 作業：railsをgit cloneする
* 思っていること：ドキュメント通りに進めれば大丈夫だろう

**Comment by wataru0225** [comment]
* 作業：新しくブランチを作る
* 思っていること：テキトーなブランチ名でいいよね

**Comment by wataru0225** [comment]
* 作業：bundle install実行している(bundler入れるところから)
* 思っていること：VagrantfileあるならDockerfile欲しい。

**Comment by wataru0225** [comment]
* 作業：rails newする
* 思っていること：```--dev```をつけるといいらしい

**Comment by wataru0225** [comment]
* 作業：pgのインストールに失敗する
* 思っていること：postgresql のライブラリが必要らしい

**Comment by wataru0225** [comment]
* 作業：再度```bundle install```をする
* 思っていること：postgresql推奨なんですね。

**Comment by wataru0225** [comment]
* 作業：rails newする
* 思っていること：--devをつけるといいらしい

**Comment by wataru0225** [comment]
* 作業：rails new のオプションで--devの意味を調べる
* 思っていること：ドキュメントに書いてあるけど、何のためにつけるのかわからなかった。

**Comment by wataru0225** [comment]
* 作業：rails new のオプションで--edgeってつけるのもやってみた
* 思っていること：やって見てどういう動きか何となくわかった。

**Comment by wataru0225** [comment]
* 作業：scaffold作ってみる
* 思っていること：調べれば思い出す

**Comment by wataru0225** [comment]
* 作業：間違えて作ったcontrollerを消す
* 思っていること：調べれば思い出す

**Comment by wataru0225** [comment]
* 作業：DBを作る(sqlite3)
* 思っていること：調べれば思い出す

**Comment by wataru0225** [comment]
* 作業：sqlite3のコマンドを調べて見る
* 思っていること：sqlite3全然使ったことなかったので、ここで少し覚える

**Comment by wataru0225** [comment]
* 作業：migrationしたテーブルを確認した(sqlite3: .schema)
* 思っていること：初めてsqlite3使った。

**Comment by wataru0225** [comment]
* 作業：```rails s```する
* 思っていること：とりあえず動かしてみる

**Comment by wataru0225** [comment]
* やりたいこと： ActiveSupportに新しいメソッドを追加したい
* どのようなメソッドか： Enumrableクラスに配列内のハッシュをまとめて計算するメソッド。
ハッシュ内の特定のkey(代表キー)のvalueが一緒のハッシュを一つにして、それとは別のkey(ターゲットキー)は計算(合計値か平均値を出す)をして、(数値のみ、文字列不可)代表キーとターゲットキーに対して計算された結果をバリューに持つハッシュの配列を返り値にする。
代表キー(複数可)とターゲットキー(複数可)はメソッドの引数として指定する。

**Comment by kou** [comment]
お疲れ様でした！
