### ISSUE TITLE
OSS Gateワークショップ 2016-7-30: shiro615: chart-js-rails: 作業ログ

### ISSUE THREAD

**Issue by shiro615** [oss-gate/workshop#87]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by shiro615** [comment]
* 作業 rubyのドキュメントを探す
* 思っていること：どこだろう

**Comment by shiro615** [comment]
* 作業 ドキュメントを探す
* 思っていること：見つかった(https://github.com/coderbydesign/chart-js-rails)

**Comment by shiro615** [comment]
* 作業：ドキュメントを読む
* 思っていること：ドキュメントがシンプル

**Comment by shiro615** [comment]
* 作業：インストールしてみる
* 思っていること：Railsのサンプルアプリも立ち上げよう

**Comment by shiro615** [comment]
* 作業：インストールしてみる
* 思っていること：Railsのサンプルアプリも作る

**Comment by shiro615** [comment]
* 作業：chart-js-railsをインストールする
* 思っていること：Gemfileにgemを追加して application.jsから呼ぶだけ

**Comment by shiro615** [comment]
* 作業：ローカルにあるRails4.2.6で作ったアプリをrails5にアップデート
* 思っていること：依存関係で失敗しそう

**Comment by shiro615** [comment]
* 作業：アップデート時のエラーメッセージを読む
* 思っていること：railtiesのバージョン依存でエラーになっていそう

**Comment by shiro615** [comment]
* 作業 エラーメッセージを読む
* 思ったこと `quiet_assetsのrailties`のバージョンがrails5.0.0に対応していない?

```
quiet_assets was resolved to 1.1.0, which depends on
      railties (< 5.0, >= 3.1)
```

```
rails (= 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)
```

**Comment by shiro615** [comment]
* 作業：railties, '>= 3.1', '< 5.0' で指定されているのでなぜ5.0未満を指定しているのか理由を探す
* 思っていること：過去のコミット履歴を見る

**Comment by shiro615** [comment]
* 作業：railtiesのバージョンを指定しているコミットを見る
* 思っていること：5.0以上だとrails4が動かなくなるから指定しているよう

**Comment by shiro615** [comment]
* 作業：railtiesのバージョンを '>= 3.1'に変更
* 思っていること：ローカルのgemの中身を直接変更していいのか...

**Comment by shiro615** [comment]
* 作業：quiet_assetsのPRを見てみる
* 思っていること：誰かがRails5.0対応の改修をしようとしている?

**Comment by shiro615** [comment]
* 作業：quiet_assetsのコメントからsprockets-railsのPRを見てみる
* 思っていること：sprockets-railsにquiet_assetsが取り込まれた?

**Comment by shiro615** [comment]
* 作業：sprockets-railsの設定を変えることでquiet_assetsが使えるか確認
* 思っていること：

**Comment by shiro615** [comment]
* 作業：rails5だとquiet_assets使えなくなることをissueにまとめる
* 思っていること：quiet_assetsを使うためにsprockets-railsを使う

**Comment by shiro615** [comment]
* 作業：日本語でissueを書く
* 思っていること：英語はあとで書く

タイトル：quiet_assets install時の警告文追加のお願い

本文：
quiet_assetsはsprockets-railsで使えるようになったためbundle install時にそのむねを伝える警告文を出すのはどうでしょう。
また、現在のquiet_assetsだとRails5へのupdate時にrailtiesのバージョンが5.0未満のためupdateできないようです。

```
quiet_assets was resolved to 1.1.0, which depends on
      railties (< 5.0, >= 3.1)
```

```
rails (= 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)
```

**Comment by kou** [comment]
お疲れ様でした！
