### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-06-09: gk9t: Drupal: Work log

### ISSUE THREAD

**Issue by gk9t** [oss-gate/workshop#870]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by gk9t** [comment]
なかなか自分のテーマは決まらないのですが、日頃もどかしく思っている、Drupal８の開発に少しかかわれたらと思います。
遠くをみると、簡易的なグループウェア（スケジュールとメンバーメール、施設予約）とか
外部のアンケート機能のようなサイト構築ができるようになりたいです。

**Comment by gk9t** [comment]
Drupal(drupal.com)の公式サイトでライセンスをチェック。GPLライセンスでとりあえず問題ない。

**Comment by gk9t** [comment]
まずはやってみようということで、トップから、Tryページへ！
https://www.drupal.org/try-drupal
⇒ここから、本家！？AcquiaのFreeで試す！

**Comment by gk9t** [comment]
Acqireにいくと、自分の属性を選ぶよう促されたので、Technical Person（not expert）を選択。

**Comment by gk9t** [comment]
パスワードは、記号使えないようです。

**Comment by gk9t** [comment]
CreateApplicationで３~５分まつ。

**Comment by gk9t** [comment]
５分で終わりません。

**Comment by gk9t** [comment]
Configure Drupal Siteが無事でました！

**Comment by gk9t** [comment]
or
GotoApplication

となっていたので、GoTOApplicationに。
なにをしたらよいのか、よくわからず。
とりいそぎ、右上のGitInfoを見に行ったら、Gitのリポジトリの情報が出てきた。
とりあえず、ローカルにCloneを試みる。

**Comment by gk9t** [comment]
クローンの際、SourceTreeというGitのツールで、SSHキーがないというメッセージが出た。
Acuireサイトのアカウント情報で、SSHをインポートする画面があった。
SourceTreeの画面でSSHキーが作れそうなので、SourceTreeでSSHキーを作って、Acuireに取り込んでみます。

**Comment by gk9t** [comment]
作ったキーをペーストしてみたら、エラー。Lernmoreリンクを確認すると、
RSAキーの4096以上でないと、Acuire側が受け付けません。

**Comment by gk9t** [comment]
RSAを２通りためす(4096以上)。
通常のRSAとRSA（SSH-1）

しかし、Acuireで張り付けると、以前としてエラーに。
⇒他の手で調べよう！

**Comment by gk9t** [comment]
![image](https://user-images.githubusercontent.com/29291480/41188819-9fb3cdf8-6bfe-11e8-8c28-11b9d8027968.png)

**Comment by gk9t** [comment]
上のDevのリンクをクリックすると、Drupalのインストール画面が表示された。

**Comment by gk9t** [comment]
その後、ユーザー名とパスワードを求められる画面がでたが、該当するユーザー名とパスワードの心当たりない。

**Comment by gk9t** [comment]
Acquiaのテストサイトで無料サイトの再作成をい試みたのですが、
You aren't authorized to access this page.
If you should have access, you can file a support ticket.
という状態で止まってしまいました。

**Comment by gk9t** [comment]
別の無料サイトへ乗り換え。
https://www.drupal.org/home
から、TryDrupalのリンククリック。

**Comment by gk9t** [comment]
Pantheonをこころみる。
Deploying Drupal 8を実行
InstallDrupalを実行
インストールウィザードを進める

**Comment by gk9t** [comment]
ウィザードで必要事項を入力して、セットアップ完了。
テストサイトの初期画面が表示される。
ただし、日本語を選択したが、トップ画面では
No front page content has been created yet.
Follow the User Guide to start building your site.
と英語での注意書きが表示される。

**Comment by gk9t** [comment]
Account⇒SSH KeysでSSH
キーを登録

**Comment by gk9t** [comment]
SourceTreeというツールを使って、ローカルにGitCloneしようとしたら、NG。
あきらめて、UbuntuのGitで下記のコマンドを実行したところ、同じくNG.
どうやら、権限関連の問題のようだ。
git clone ssh://codeserver.dev.668cd82f-4c7a-41b4-9036-281bfe863542@codeserver.dev.668cd82f-4c7a-41b4-9036-281bfe863542.drush.in:2222/~/repository.git taku
Cloning into 'taku'...
ssh: connect to host codeserver.dev.668cd82f-4c7a-41b4-9036-281bfe863542.drush.in port 2222: Resource temporarily unavailable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by knokmki612** [comment]
当日おつかれさまでした！issueはクローズしますが、引き続きこのissueを使って作業しても大丈夫です！
