### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-06-09: mau34: numpy: Work log

### ISSUE THREAD

**Issue by mau34** [oss-gate/workshop#872]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by richardimaoka** [comment]
サポーターです

**Comment by mau34** [comment]
anacondaを用いて、環境構築を行った。
import numpy as npで通ったためOK

**Comment by mau34** [comment]
numpyはBSD License(http://www.numpy.org/)であることを確認

**Comment by mau34** [comment]
version確認
$ activate 20180609numpy
$ pip freeze
numpy==1.12.1

**Comment by mau34** [comment]
tutorial(https://github.com/numpy/numpy/blob/81b8ccbeff1b484a797f7c2297f8f3d52b2df037/doc/source/user/quickstart.rst)
をやってみたところ、結果が一致しない部分があった。
tutorial
>>> a.dtype.name
'int64'
>>> a.itemsize
8

実際の結果
>>> a.dtype.name
'int64'
>>> a.itemsize
8

Libraryのバージョンが古い可能性もあるため、最新のバージョンに切り替えて
再度動作させてみることにする。

**Comment by mau34** [comment]
numpyのアップデート
$ pip install numpy -U
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/21/06/a11c4b2e4f90c4f53c39b548a3f16eb644729048cf705ed71a7672d87338/numpy-1.14.4-cp36-none-win_amd64.whl (13.4MB)
    100% |████████████████████████████████| 13.4MB 61kB/s
Installing collected packages: numpy
  Found existing installation: numpy 1.12.1
    Uninstalling numpy-1.12.1:
      Successfully uninstalled numpy-1.12.1
Successfully installed numpy-1.14.4
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by richardimaoka** [comment]
pip freeze
numpy==1.14.3

:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>> a.shape
(3, 5)
>>> a.ndim
2
>>> a.dtype.name
'int64'
>>> a.itemsize
8
>>>

**Comment by mau34** [comment]
windows10,64bit実行
numpy=1.14.4
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a.dtype.name
'int32'
>>> a.itemsize
4

**Comment by mau34** [comment]
おそらく実行環境の違い(win/mac)によるものとみられる。

dtype.name/itemsizeは実質的に利用することはほぼないプロパティのため、
特に困ることはなさそう。

**Comment by hk220** [comment]
実行ができなかったり、結果が変だったりしたときは、公式のドキュメントに従ってもう一度セットアップを試してみるのがおすすめです！
それでも、改善しなければやった手順をあわせて「ドキュメントがおかしいぞ！」と issue を立てるチャンスになります。
OSS への貢献のはじめの入り口としておすすめです。

ご参考になれば嬉しいです。

**Comment by mau34** [comment]
Pythonを実行した際に、"on win32"と記載されていたことが分かったため、
これが原因の可能性がある。

公式で紹介(https://scipy.org/install.html)されていたAnacondaで再度インストールを
やり直して、再度確認してみる。

**Comment by richardimaoka** [comment]
https://stackoverflow.com/questions/37117571/where-does-anaconda-python-install-on-windows

**Comment by mau34** [comment]
anacondaで再インストールしたものの、"on win32"の表示は変わらない
おそらくanaconda側の問題とみられる
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a.shape
(3, 5)
>>> a.dtype.name
'int32'
>>> a.itemsize
4

**Comment by mau34** [comment]
Documentationに関する質問もissuesに載せてよいとみられる。
https://github.com/numpy/numpy/issues?q=is%3Aissue+doc+label%3A%2203+-+Documentation%22

03 - Documentationというラベルも付ければOKとみられる。

**Comment by mau34** [comment]
既設のissuesには同一のissuesがないとみられるため、投稿した。
https://github.com/numpy/numpy/issues/11289

**Comment by richardimaoka** [comment]
すばらしい、おめでとうございます！おつかれさまです。

**Comment by knokmki612** [comment]
おつかれさまでした！
