### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-06-09: ykitazono: Redmine: Work log

### ISSUE THREAD

**Issue by kitazono** [oss-gate/workshop#873]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by unasuke** [comment]
やっていきましょう :wink:

**Comment by kitazono** [comment]
日本語サイト(http://redmine.jp/)には貢献の仕方が書かれてなかったので、公式サイト(https://www.redmine.org/)にいく。

**Comment by kitazono** [comment]
インストールするためにhttp://redmine.jp/install/ を確認。

**Comment by kitazono** [comment]
http://www.redmine.org/projects/redmine/wiki/Download
でredmine-3.4.5.zipをダウンロードする。

**Comment by kitazono** [comment]
上の前に
http://redmine.jp/install/
から
動作環境
http://guide.redmine.jp/RedmineInstall/#Requirements
に飛んで、動作環境が問題ないことを確認し、
ダウンロードへ飛ぶ
http://guide.redmine.jp/RedmineInstall/#Requirements

**Comment by kitazono** [comment]
デスクトップにダウンロードした後、unzipで解凍。

**Comment by kitazono** [comment]
空のデータベースとユーザーの作成となっているので、
とりあえずMySQLの場合を試す。

**Comment by kitazono** [comment]
mysqlにログインしようとしたら、エラーが返ってきたぞ。
kitasono-no-MacBook-Air:Desktop zono$ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

**Comment by kitazono** [comment]
ドキュメントのコマンドを打つと、
kitasono-no-MacBook-Air:Desktop zono$ CREATE DATABASE redmine CHARACTER SET utf8mb4;
-bash: CREATE: command not found

**Comment by kitazono** [comment]
mysqlが入っているか確認したが、エラーが返ってくる。
kitasono-no-MacBook-Air:Desktop zono$ mysql -v
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

**Comment by kitazono** [comment]
MySQLの公式ドキュメントを見てみる。
https://www.mysql.com/jp/

**Comment by kitazono** [comment]
MySQLが自分のMacに入ってるか確認したい。

**Comment by kitazono** [comment]
MySQLの日本語サイトhttps://dev.mysql.com/doc/refman/5.6/ja/postinstallation.html を見て、
2.10 インストール後のセットアップとテストで自分のMacに入ってるか確認してみよう。

**Comment by kitazono** [comment]
読んでも良く分かんないぞ。

**Comment by kitazono** [comment]
とりあえずインストール手順を読んでみる。
https://dev.mysql.com/doc/refman/5.6/ja/osx-installation.html

**Comment by unasuke** [comment]
- [Defect #19344: MySQL 5.6: IssueNestedSetConcurrencyTest#test_concurrency : always fails - Redmine](http://www.redmine.org/issues/19344)
- [Feature #19395: Support MariaDB - Redmine](http://www.redmine.org/issues/19395)
- [Feature #17460: MySQL 5.7 support - Redmine](http://www.redmine.org/issues/17460)

**Comment by kitazono** [comment]
とりあえず、DBはPostgreSQL 8.3以降に方針転換してみる。

**Comment by kitazono** [comment]
自分のMACに入っているのはどうやって確認すればいいのか？

**Comment by kitazono** [comment]
PostgreSQLの公式サイトを探そう。

**Comment by kitazono** [comment]
https://www.postgresql.org/ が公式サイトのようだ。

**Comment by kitazono** [comment]
公式サイトから日本語版のリンクが貼ってあった
https://www.postgresql.jp/document/

**Comment by kitazono** [comment]
さあ始めましょう
https://www.postgresql.jp/document/10/html/tutorial-install.html
があったので見る。

**Comment by kitazono** [comment]
こんなことが書かれてるぞ。

> 使用しているオペレーティングシステム配布物内に含まれていたり、システム管理者がインストールしていたりしますので、PostgreSQLが既にサイトにインストールされている可能性があります。 そのような場合、オペレーティングシステムの文書やシステム管理者からPostgreSQLへのアクセス方法に関する情報を得なければなりません。

**Comment by kitazono** [comment]
PostgreSQLのバージョン確認方法が知りたい。

**Comment by kitazono** [comment]
googleで検索して
https://hacknote.jp/archives/1574/
を確認。

**Comment by kitazono** [comment]
入っているみたいだ。バージョンも対応している。

kitasono-no-MacBook-Air:Desktop zono$ psql --version
psql (PostgreSQL) 9.4.4

**Comment by kitazono** [comment]
Redmineを動かす環境はありそうだ。

**Comment by kitazono** [comment]
以下を実行したいのだけどどうすればいいの？

CREATE ROLE redmine LOGIN ENCRYPTED PASSWORD 'my_password' NOINHERIT VALID UNTIL 'infinity';
CREATE DATABASE redmine WITH ENCODING='UTF8' OWNER=redmine;

**Comment by kitazono** [comment]
以下コマンドでログインパスワードを打ったけどエラー。

kitasono-no-MacBook-Air:Desktop zono$ createdb mydb
Password: 
createdb: could not connect to database template1: FATAL:  password authentication failed for user "zono"

**Comment by kitazono** [comment]
パスワード無しでもダメ。

kitasono-no-MacBook-Air:Desktop zono$ createdb mydb
Password: 
Password: 
createdb: could not connect to database template1: fe_sendauth: no password supplied

**Comment by kitazono** [comment]
エラー文でgoogleで探したら、以下のドキュメントを見つけた。

https://lets.postgresql.jp/

**Comment by kitazono** [comment]
https://lets.postgresql.jp/documents/tutorial/macosx/1

Mac向けのドキュメントを見つけた。

**Comment by kitazono** [comment]
PostgreSQLの導入と初期設定
https://lets.postgresql.jp/documents/tutorial/introduction/1
に答えがないか探して見る。

**Comment by kitazono** [comment]
パスワードの問題をgoogleで探して見たら、pg_hba.confの情報が見つかるので、
公式のドキュメントを見てみる。

**Comment by kitazono** [comment]
良くわからなかったのでQiitaも見て見る。
https://qiita.com/yoh-nak/items/c1f009bdf24e5182f9b0

以下のように編集すると、パスワードなしでPostgreSQLにログインできそうだ。

sudo vim /Library/PostgreSQL/9.3/data/pg_hba.conf
local   all             all                                     trust

**Comment by kitazono** [comment]
kitasono-no-MacBook-Air:~ zono$ cd /Library/PostgreSQL/9.4/data/
-bash: cd: /Library/PostgreSQL/9.4/data/: Permission denied

ローカルユーザーだと権限がないみたい。

**Comment by kitazono** [comment]
DB作成再トライ。またエラーだ。

kitasono-no-MacBook-Air:~ zono$ createdb mydb
createdb: could not connect to database template1: FATAL:  role "zono" does not exist

**Comment by kitazono** [comment]
https://www.postgresql.jp/document/9.4/html/tutorial-createdb.html
を見るとアカウントが作成されていないようだ。

**Comment by kitazono** [comment]
https://www.postgresql.jp/document/9.4/html/tutorial-createdb.html

に以下の記載があったので、

> 管理者であれば、アカウントの作成方法に関して第20章を参照してください。 最初のユーザアカウントを作成するためには、PostgreSQLをインストールした時のオペレーティングシステムのユーザ（通常postgres）になる必要があります。 PostgreSQLユーザアカウントがオペレーティングシステムのユーザ名と異なる名前で用意されているかもしれません。 その場合は、PostgreSQLのユーザ名を指定するために、-Uスイッチを使用するか、PGUSER環境変数を設定する必要があります。
psql -U postgres

でようやくログインできた。

**Comment by kitazono** [comment]
https://lets.postgresql.jp/documents/tutorial/psql/1
でpsqlの終了の仕方を確認。以下で終了できた。
¥q

**Comment by kitazono** [comment]
http://guide.redmine.jp/RedmineInstall/#Requirements
の

以下の手順に行くまでが分からなかったので、報告してみよう。

> Step 2 - 空のデータベースとユーザーの作成
ここではデータベース名とユーザー名を redmine としますが、それ以外の名前に変えることもできます。

> MySQLの場合:
CREATE DATABASE redmine CHARACTER SET utf8mb4;
CREATE USER 'redmine'@'localhost' IDENTIFIED BY 'my_password';
GRANT ALL PRIVILEGES ON redmine.* TO 'redmine'@'localhost';

日本語のドキュメントは、英語ドキュメントの訳みたいなので、

http://www.redmine.org/projects/redmine/wiki/RedmineInstall

に報告するやり方を探してみる。

**Comment by kitazono** [comment]
報告の仕方が良く分からなかったので、とりあえず以下でユーザーを作成しログインしてみる。

http://www.redmine.org/projects/redmine/wiki/RedmineInstall

**Comment by unasuke** [comment]
> More newbie-helpful user-guide to setup database(MySQL, PostgreSQL)

とかですかねぇ？

**Comment by unasuke** [comment]
```
$ psql
> CREATE ROLE redmine LOGIN ENCRYPTED PASSWORD 'my_password' NOINHERIT VALID UNTIL 'infinity';
> CREATE DATABASE redmine WITH ENCODING='UTF8' OWNER=redmine;
```

**Comment by kitazono** [comment]
ドキュメントの優しくして欲しいというチケットをあげました。人生初です。

http://www.redmine.org/boards/1/topics/55327

**Comment by knokmki612** [comment]
おつかれさまでした！

issueはクローズしますが、引き続きこのissueを使って作業しても大丈夫です！

https://gitter.im/oss-gate/devel でチケットのやりとりをどうしていけばいいか相談するのも良いかもしれません！
