### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-06-09: mitomex: vuejs: Work log

### ISSUE THREAD

**Issue by mitomex** [oss-gate/workshop#874]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by uchan-nos** [comment]
今日のサポートをさせていただくuchan-nosです．よろしくお願いします！

**Comment by mitomex** [comment]
よろしくお願いします！

**Comment by mitomex** [comment]
[Vue.js の公式サイト](https://vuejs.org/) にある、GET STARTED をみながら導入していきます！

**Comment by mitomex** [comment]
まずは、 Vuejs が OSS かどうか確認する

**Comment by mitomex** [comment]
[Open Source Initiative](https://opensource.org/licenses/alphabetical) に OSS のライセンス一覧がある

**Comment by mitomex** [comment]
[Vuejs](https://vuejs.org/)

<img width="967" alt="screen_shot_2018-06-09_at_13_47_21" src="https://user-images.githubusercontent.com/826539/41187742-cab05d86-6beb-11e8-8dc6-6434d728bf87.png">

GitHub のリポジトリへ移動。

**Comment by mitomex** [comment]
https://github.com/vuejs/vue/blob/dev/LICENSE　を見ると、MIT になっていて、https://opensource.org/licenses/alphabetical の一覧に MIT があるので、 OSS であると確認

**Comment by mitomex** [comment]
https://vuejs.org/v2/guide/

からスタート

**Comment by mitomex** [comment]
JSFiddle を使うか、自分で index.html を用意するかあったので、自分で環境を用意していこう

**Comment by uchan-nos** [comment]
JSFiddle というのは，オンラインで JavaScript の実験・簡易な開発ができるオンラインエディタみたいなものらしい．

**Comment by mitomex** [comment]
`<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>` を書いて簡易で始められるらしい。

他にもインストール方法が、
https://vuejs.org/v2/guide/installation.html
このページにあるが、`vue-cli` を使ったインストールは、ビギナーには不向きらしい。

**Comment by mitomex** [comment]
https://vuejs.org/v2/guide/#Declarative-Rendering

ここからコードを実際に書き始める。HTML と JS にそれぞれ書いていくのねー

**Comment by mitomex** [comment]
ファイルにどう書いていくのかが、ちょっとわかりづらかったかなー

**Comment by mitomex** [comment]
`Open your browser’s JavaScript console (right now, on this page)`

と書いてあって、`this page` がまさにマニュアルのページのことだった！
てっきり自分が作っているページのことだと思ってしまった。。。

**Comment by mitomex** [comment]
v-if までやった。

`Go ahead and enter app3.seen = false in the console. You should see the message disappear.`

あったが、自分でコードを書いているので、自分のコードを変えてみたほうがわかりやすいかも。

**Comment by mitomex** [comment]
いきなりコンソールにいってしまうので。

**Comment by mitomex** [comment]
もしかしたら JSFiddle でやっている人と、自分でファイルを用意して進めている人でのやり方が微妙に違うのかも

**Comment by mitomex** [comment]
リンク切れもチェックしておくと、報告するポイントがあるかもと教えてもらった！

とくに Vuejs は更新が早いので、切れている可能性がある。

**Comment by mitomex** [comment]
今までやってきた、GET STARTED はドキュメントしてできがよかったので、初心者は避けたほうがよいと書かれていた Installation のほうをやってみよう！

GET STARTED には、中級者向けに・・・と書かれてしまっているので、ツッコミづらい・・・。

なので、ちょっと開発者向けの Installation のほうを読むことに。

**Comment by mitomex** [comment]
https://vuejs.org/v2/guide/installation.html

から実際にインストールを！

**Comment by mitomex** [comment]
vue を使うときに便利なツールがあるらしい

https://github.com/vuejs/vue-devtools#vue-devtools

**Comment by mitomex** [comment]
Chrome のエクステンションをインストール！

**Comment by mitomex** [comment]
Direct script は先ほどの get started と同じなのでスルー

**Comment by mitomex** [comment]
Installation の書き方がわかりづらかったー、って教えてもらえた！！

今の書き方だと

develop version か production version をインストールして、さらに CDN を・・・
みたいな流れになっていて、さらに NPM やら CLI とやるのかなっと思えてしまう。。。

**Comment by mitomex** [comment]
だし、そもそもインストールのところなのに、いきなり devtools の紹介が先にあるのはいかがなものか？

**Comment by mitomex** [comment]
インストールの方法

1.
2.
3.
4.

ってあって、その下に便利ツールがあるよって流れのほうが良いのかな？

**Comment by mitomex** [comment]
他のところは、どんな感じでインストールのところは書いているのだろう。。。

**Comment by mitomex** [comment]
日本語との差分を見てみるのもコントリビュートするきっかけになりやすい。
バージョンの確認とかしてみる。

**Comment by mitomex** [comment]
日本語：https://jp.vuejs.org/v2/guide/installation.html

**Comment by uchan-nos** [comment]
他の JS 系ライブラリのインストール方法の文書を参考にするのはいい案ですね！

**Comment by uchan-nos** [comment]
フィードバックネタを探すために，Installationページを取り敢えず最後まで読んでみる．

**Comment by mitomex** [comment]
んー、どうしよう、、、ツッコミどころがなく・・・。

**Comment by mitomex** [comment]
https://vuejs.org/v2/guide/single-file-components.html
にあった、`Bublé` という表記が `babel` の typo かと思ったら `Bublé` というのがあった！

https://github.com/Rich-Harris/buble

はじめて知った！

**Comment by mitomex** [comment]
とりあえず、Vuejs に Star をつけた！！

**Comment by mitomex** [comment]
Issue のテンプレートのかたちで Issue を書く方法（書くまでに確認する項目も）あった。

**Comment by mitomex** [comment]
コンパイルが必要なものだと、ローカルの環境によって実行できないことが多いらしい。
動かない環境を書いてあげるだけでも助けになる。

**Comment by mitomex** [comment]
```
<!--
IMPORTANT: Please use the following link to create a new issue:

  https://new-issue.vuejs.org/

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。
-->

<!--
Love vuejs? Please consider supporting us via Patreon or OpenCollective:
👉  https://www.patreon.com/evanyou
👉  https://opencollective.com/vuejs/donate
-->
```

↑　Vue の New Issue をクリックすると、テンプレートに参照URLがある。
https://new-issue.vuejs.org/
ここに入力してみる。

**Comment by mitomex** [comment]
- I am opening an issue for
  - vue
- This is a
  - Bug Report
- Issue title
  - Sponsor Links do not work.
- Version
  - ?
- Link to minimal reproduction
  - ?
- Steps to reproduce
  - ?
- What is expected?
  - Corporate websites are shown when I click the sponsor links.
- What is actually happening?
  - Sponsors via Open Collective's Gold links at README.md show me "not found" page. This also happens at BACKERS.md.
- Any additional comments? (optional)
  - ?

**Comment by mitomex** [comment]
https://github.com/vuejs/vue/issues/8329

こちらにて Issue を作成。

**Comment by mitomex** [comment]
New Issue 用のフォームが用意されていたが、今回みたいに README のリンク切れの報告がしづらかった。

**Comment by mitomex** [comment]
問題が発生しているコードが見れる JSFiddle のURLを入れる項目が必須になっていた。

**Comment by mitomex** [comment]
Issue の中にある、for beginner というラベルが付いているリポジトリがあったりする。それからやってみるのがやりやすい。

**Comment by knokmki612** [comment]
おつかれさまでした！

issueはクローズしますが、引き続きこのissueを使って作業しても大丈夫です！
