### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-06-09: takahirosawamura :docker: Work log

### ISSUE THREAD

**Issue by takahirosawamura** [oss-gate/workshop#876]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by takuya44kw** [comment]
一緒に検討しましょう

**Comment by takahirosawamura** [comment]
http://scikit-learn.org/stable/
BSD license

**Comment by takahirosawamura** [comment]
テーマをdockerに変更します。
変更理由：興味のあるプロジェクトでイメージしやすいので

https://www.docker.com/
https://www.docker.com/components-licenses
apache2.0(今回は本体なので)

**Comment by takahirosawamura** [comment]
このスライドでdockerへのcontributeの仕方を学ぶ
https://www.slideshare.net/Docker/docker-contributor-presentation-gopher-con

**Comment by takahirosawamura** [comment]
issueで貢献するときに参考にできそうなもの
- contributeのリンクが公式で見つけ辛かった部分を検索してslideshareで見つけた。
- コメント欄にわかった部分を書き記しことによって、次に探すときに理解しやすくする。
- 同じrepositoryで他の人の出しているissueを確認して参考にできそうなものをまとめていく。

**Comment by takahirosawamura** [comment]
今回issueとしてあげられそうな箇所
- 最近dockerの起動方法か何か？が新しくなったのでそこの部分で貢献できるかもしれない。
- dockerの日本語化プロジェクトで最新のバージョンに対して日本語化が追いついていないのでそこの部分で貢献できるかもしれない。
- docker本体や、ドキュメントに対して、dockerビギナーに対してのレクチェーやコンテンツ作成など色々な部分で貢献活動がなされているのでその部分で貢献できるかもしれない。

**Comment by takahirosawamura** [comment]
今回やろうとしていること
- dockerの日本語化プロジェクトで進んでいなさそうなところが結構あるのでそこをissueでだす。あるところはPull requestで出せるようにする。 
- 自分が触っていて課題に感じていて、客観的に考えて他の人も課題に感じていそうなところをissueかpull requestで出していく。
- 参考になりそうなところを作業ログにどんどん残していって、今後の参考になるベースを作っておく。

**Comment by takahirosawamura** [comment]
https://oss-gate.doorkeeper.jp/events/70312
おそらく作業が時間が17:30だと思うので、残りの作業時間2hから逆算して時間配分を考える。

1. 参考になるissue例(20分) 
2. 具体的に自分があげられそうなissue例(30分) 
3. 検討したissue(できればPR)を自分であげる。(1h)→残り10分で見直しをする。

**Comment by takahirosawamura** [comment]
振り返りの時間があったので時間配分変更
参考になるissue例(20分) 16:00
具体的に自分があげられそうなissue例(30分) 16:30
検討したissue(できればPR)を自分であげる。(50分)→残り10分で見直しをする。 17:20(issue/pull request) -> 17:30(見直し)

**Comment by takahirosawamura** [comment]
- 整理する
- 開発者にとってわかりあやすくなるように編集
- 適切な場所に報告

**Comment by takahirosawamura** [comment]
報告方針が見つからないので良さそうなものを真似する
https://github.com/zembutsu/docs.docker.jp/issues

**Comment by takahirosawamura** [comment]
## 参考になりそうなissue
- https://github.com/zembutsu/docs.docker.jp/issues/125
画像と合わせて提示するとよさそう

- https://github.com/zembutsu/docs.docker.jp/issues
拡張、bugなどlabelを貼るとよさそう
<img width="1095" alt="2018-06-09 15 58 48" src="https://user-images.githubusercontent.com/18510885/41188804-1b87be04-6bfe-11e8-923f-2a010da0de0d.png">

- 日本語版の修正プロジェクトはフォーマットがきっちりと整っているものがあまり多くなかったのでその部分はcontributing.mdみたいなのがあっても良いかもしれないなとは感じた。
- 修正前、修正後をきちんとまとめたものは良いなと感じた。
- 英語版のフォーマットを参考にして、日本語版の書き方のところに乗せて統一性を持たせても良いかもしれないとも感じた。

**Comment by takahirosawamura** [comment]
## issueを見渡していて感じたこと
- 日本語版の修正プロジェクトはフォーマットがきっちりと整っているものがあまり多くなかったのでその部分はcontributing.mdみたいなのがあっても良いかもしれないなとは感じた。
- 修正前、修正後をきちんとまとめたものは良いなと感じた。
- 英語版のフォーマットを参考にして、日本語版の書き方のところに乗せて統一性を持たせても良いかもしれないとも感じた。

**Comment by takahirosawamura** [comment]
プロジェクトとしての改善点
- issueでスクリーンショットで貼られるのはおかしい。
→リンクで飛べるようにしたほうが良い(やり方の参考がない)
- やり方の参考がない
→参考例を出した方が良いかも。

**Comment by takahirosawamura** [comment]
## 自分がissueとしてあげられそうなこと
- 最新バージョンに対して日本語化が追いついてないところの修正作業
- 日本語版のcontributionのフォーマットの整備
- typo

**Comment by takahirosawamura** [comment]
## docker日本語化プロジェクトに対して貢献できそうなところ
- 見た人がこのプロジェクトに対してすぐにPRを出せる雛形を作れそう。
- issueの出し方に統一感をだす。
- 自分でプロジェクトに関わっていて触りづらいところ
- 英語版と比べてまとまっていないところ。(contributing.md)

**Comment by takahirosawamura** [comment]
## docker日本語化プロジェクトPRフロー
1. このレポジトリをgit cloneする
 "git clone git@github.com:zembutsu/docs.docker.jp.git"

2. 自分のローカル環境でgit cloneしたものを編集して、
 "git commit -m ~~~"と"git push"する

 3. githubのページ上で変更分のpull requestを投げる。

 4. mergeされるのを待つ

<img width="1351" alt="2018-06-09 16 21 23" src="https://user-images.githubusercontent.com/18510885/41188936-5e85b672-6c01-11e8-969b-d10f7fcb04a8.png">

### 参考URL
https://qiita.com/samurairunner/items/7442521bce2d6ac9330b

**Comment by takahirosawamura** [comment]
## これを参考にissueとPRをだす。
今から出そうとしているissueの下書き
- title
日本語化プロジェクトにCONTRIBUTING.mdがない。
- 問題説明の本文
CONTRIBUTING.mdがないので、以下のような問題がある。
1. 全体のissueにまとまりがない。
2. 初めて関わる人がissueの出し方がわからない。

- 提案

 
上記の問題を改善できるようなCONTRIBUTING.mdをルート直下に配置する。

- 参考: 英語版のdocker docsプロジェクトのCONTRIBUTING.md
https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md

**Comment by takahirosawamura** [comment]
## PR用にだすissue
今から出そうとしているissueの下書き

title
日本語化プロジェクトにCONTRIBUTING.mdがない。
問題説明の本文
CONTRIBUTING.mdがないので、以下のような問題がある。
全体のPRにまとまりがない。
初めて関わる人PRの出し方がわからない。
提案
上記の問題を改善できるようなCONTRIBUTING.mdをルート直下に配置する。

参考: 英語版のdocker docsプロジェクトのCONTRIBUTING.md
https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md

**Comment by takahirosawamura** [comment]
今から出そうとしているissueの下書き
- title
日本語化プロジェクトにCONTRIBUTING.mdがない。
- 問題説明の本文
CONTRIBUTING.mdがないので、
gitを常用していないが、dockerを利用しているような人がドキュメントを読んでいて課題修正をしたい時にできない。 

### 提案
dockerを使用しているが、gitに慣れていない人がissueだけでなく、自分でPull Requestも出せるようになったら便利。
上記の問題を改善できるようなCONTRIBUTING.mdをルート直下に配置する。

- 参考: 英語版のdocker docsプロジェクトのCONTRIBUTING.md
https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md

**Comment by takahirosawamura** [comment]
CONTRIBUTING.mdがないため、
gitを常用していないが、dockerを利用しているような人がドキュメントを読んでいて課題修正をしたい時にできない。
### 提案
dockerを使用しているが、gitに慣れていない人がissueだけでなく、自分でPull Requestも出せるようになったら便利。

上記の問題を改善できるようなCONTRIBUTING.mdをルート直下に配置する。

参考: 英語版のdocker docsプロジェクトのCONTRIBUTING.md
https://github.com/docker/docker.github.io/blob/master/CONTRIBUTING.md

**Comment by takahirosawamura** [comment]
https://github.com/zembutsu/docs.docker.jp/blob/master/LICENSE

- contribution
https://github.com/docker/docker.github.io/blob/master/README.md

**Comment by takahirosawamura** [comment]
# 20180609 OSS Gateまとめ
## 今日良かったところ
- OSSに限られた時間の中でissueを出した。
- 作業の仕方とメモの残し方と考え方がわかった。
- メンターの人の関わっているプロジェクトと考え方と作業工程がわかった。
- OSSやる時に見る部分と、Licenseの扱い方と、メンテナの人が管理しやすいものがわかった。
- 同一プロジェクトにPR出し続けると、見てもらいやすいらしい。

## 反省点
- 先にやりたい部分を決めてたら、もうちょっとプロジェクト貢献をもっと深くできた。
- dockerは興味があるけど、メインをやるには普段golangをそこまで深く使っていなかったので、code readingの時間を考えるとそこまでできなかった。

## これからやること
- 自分の慣れ親しんだ開発言語で興味のあるOSSを探してContributeする。
- 次に参加する時に、やることと目標設定をして参加する。
- 今日学んだことのプロジェクトに加えて引き続きissueとPRをだす。
- プロジェクトに貢献できる部分をよく考えてContributionする。
- 普段使ってるtoolやlibraryなどにContributionする。

**Comment by takahirosawamura** [comment]
- チャット
- ワークショップ
- ブログに書く
- 周りの人に誘う

**Comment by knokmki612** [comment]
おつかれさまでした！ワークショップ自体のメモもしてくださりありがとうございます！

issueはクローズしますが、引き続きこのissueを使って作業しても大丈夫です！
