### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-6-9: mugayoshi: Scrapy: Work log

### ISSUE THREAD

**Issue by mugayoshi** [oss-gate/workshop#877]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yokotaso** [comment]
やっていくぞい

**Comment by yokotaso** [comment]
テストコードが動作するところまでできた。

**Comment by mugayoshi** [comment]
https://doc.scrapy.org/en/master/contributing.html
上のURLからテストコードを動かした．

**Comment by yokotaso** [comment]
OSSに貢献する経験をしてみようということで、Issuesを読み漁る
https://github.com/scrapy/scrapy/issues/

初心者向けのIssueのこれが簡単にできそうなので、簡単なコントリビューションをしてみよう
https://github.com/scrapy/scrapy/issues/3282

**Comment by yokotaso** [comment]
python2にはguppyというツールがあるが、python3だとmuppyというツールに置き換わるらしい
なので、python3とmuppyを組み合わせて、guppyとの動きを調べてみる
https://doc.scrapy.org/en/latest/topics/leaks.html#debugging-memory-leaks-with-guppy

**Comment by yokotaso** [comment]
muppyのインストールは `pip install Pympler`

**Comment by yokotaso** [comment]
PRのためのたたきのドキュメントを書いたのでhtmlを確認

**Comment by yokotaso** [comment]
Spihicsについて

http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-arbitrary-locations

**Comment by uchan-nos** [comment]
ミニレビュー完了

**Comment by yokotaso** [comment]
CIが落ちているので修正しよう。
https://travis-ci.org/scrapy/scrapy/jobs/390033394

**Comment by mugayoshi** [comment]
section title  と参照タグの間に空行が入っていなかったことが↑の原因だったので，修正し，再びcommit.

**Comment by mugayoshi** [comment]
↑はdocs/topis/leaks.rst のこと．

**Comment by mugayoshi** [comment]
このissue https://github.com/scrapy/scrapy/issues/2842 の再現コードを書く

**Comment by mugayoshi** [comment]
scrapy のドキュメント内に spiders という記述が何度も出てくるので，どんなものか調べる

**Comment by mugayoshi** [comment]
https://qiita.com/tamonoki/items/ce58ff209f8eae808162
↑の記事を読んだ．Spiderはクローリングするときの条件を記述しているオブジェクトだとわかった．

**Comment by mugayoshi** [comment]
https://github.com/scrapy/scrapy/pull/3284
今日実施したpull request です．

**Comment by mugayoshi** [comment]
issues で話されている内容をうまく理解できていない気がする．そのため，scrapy を使ってみて，どんな挙動をするのか，というイメージをつけることが このOSSに貢献するのに必要だと感じた．

**Comment by treby** [comment]
確認しました

**Comment by knokmki612** [comment]
おつかれさまでした！
