### ISSUE TITLE
OSS Gate Workshop: TOKYO: 2018-6-9: kuribo678: TBD: Work log

### ISSUE THREAD

**Issue by kuribo678** [oss-gate/workshop#878]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by treby** [comment]
よろしくおねがいします！

**Comment by kuribo678** [comment]
こちらこそ本日よろしくお願いします。

**Comment by kuribo678** [comment]
python scripy webサイトで調べる

**Comment by kuribo678** [comment]
pip コマンドが入っていなかったのでダウンロード

**Comment by kuribo678** [comment]
環境変数

**Comment by kuribo678** [comment]
python3 pip インストール調べる

**Comment by kuribo678** [comment]
パス確認完了

**Comment by kuribo678** [comment]
パス設定中　問題はパスを通しているという勘違いを起こしている　パス設定再度チャレンジ

**Comment by treby** [comment]
https://docs.python.jp/3/using/windows.html

**Comment by kuribo678** [comment]
現状のｐｃの状況ではpipを使う問題が解決できないので再度pythonをダウンロードしなおすことに決定

**Comment by kuribo678** [comment]
やっと環境の問題が解けた　python file ディレクトリーの移動により問題改善

**Comment by kuribo678** [comment]
pip コマンド使用成功　ファイルの場所がやはり問題だった

**Comment by kuribo678** [comment]
scrapy の使い方を今webページで確認中

**Comment by kuribo678** [comment]
pip  libxml2 のライブラリーが入っているかという問題

**Comment by kuribo678** [comment]
python 3.7 に問題があり　python3.6 ダウンロード

**Comment by kuribo678** [comment]
方向性の返還
python 3.7 をダウンロードしたがpip 動作の不良により足りないlibraryがあることが判明
libxml2がpython3.7だと入っておらずlibxml2のドキュメントの確認に移行

**Comment by kuribo678** [comment]
python 3.7 公式ドキュメントのlibxml2の情報が上がっていないか確認する

**Comment by kuribo678** [comment]
横田さんからのアドバイスを受け　行動修正

**Comment by kuribo678** [comment]
内容としてはpython3.7自体がやはり問題がありpython3.6のダウンロード

**Comment by kuribo678** [comment]
python ではpip-get.pyを動作することによってpipを使用することが可能

**Comment by yokotaso** [comment]
Linuxで利用するCヘッダーをifdef切らずに使っているので、pipかcpythonに報告するのがいいかも
https://github.com/pypa/pip/issues

**Comment by yokotaso** [comment]
mingwが前提のビルドになっているけど、 @kuribo678 の環境はVS Studioの環境のヘッダファイルを
見に行っていた。これが原因だと思います。

**Comment by treby** [comment]
cython/cython https://github.com/cython/cython

**Comment by kuribo678** [comment]
僕のisseuです。
https://github.com/cython/cython/issues/2318

**Comment by yokotaso** [comment]
cythonをビルドしたのと同じバージョンの
https://www.regentechlog.com/2014/04/13/build-python-package-on-windows/

**Comment by knokmki612** [comment]
おつかれさまでした！
