### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-06-09: syu-gaspard: glfw: Work log

### ISSUE THREAD

**Issue by syu-gaspard** [oss-gate/workshop#879]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hk220** [comment]
よろしくおねがいします！

**Comment by syu-gaspard** [comment]
よろしくお願いします。

**Comment by syu-gaspard** [comment]
公式HPから[Documentation]に進んで[Example Code]の[Get Started]に進んだがいきなり実装に入った。
インストール手順が先に来ると考えていたので驚いた。glfwのビルド手順が先にきた方が嬉しい。

**Comment by syu-gaspard** [comment]
glfwについてコードからビルドして使用を考えている。
公式に移動した
http://www.glfw.org/index.html
まずは公式HPのDocumentを見に行った

**Comment by syu-gaspard** [comment]
Documentに移動してGet Startedを開いたがサンプルの書き方から始まってしまった。
Githubに移動してビルド順があるか探してみよう
https://github.com/glfw/glfw

**Comment by syu-gaspard** [comment]
githubのreadmeを読み始めたらcode buildが記載されていた。
公式HPからでは探せなかった。。。

**Comment by hk220** [comment]
公式ドキュメントでライブラリどういれるねん！問題

**Comment by syu-gaspard** [comment]
公式TOPからDocumentationに進むとビルドまでの道がわかりづらいが
Downloadに進むとビルドへの筋道が書かれていた。

**Comment by syu-gaspard** [comment]
DownloadメニューにLinuxやMacのコンパイルへのリンクがあった。
http://www.glfw.org/docs/latest/compile.html

**Comment by syu-gaspard** [comment]
コンパイルしてみよう

**Comment by syu-gaspard** [comment]
MacでHomebrew使って入れるなら入れるコマンド書いてあるとありがたかったかな

**Comment by syu-gaspard** [comment]
Licenseはこれだった
GLFW is licensed under the zlib/libpng license.

**Comment by syu-gaspard** [comment]
商用にも使いやすいライセンスだった。

**Comment by syu-gaspard** [comment]
cmakeをhomebrewで入れた（使い方を知っていた以前にインストール済みだからわかったが知らなかったら困ったかもしれないHPに手順まで欲しい）

**Comment by syu-gaspard** [comment]
入れたらいかに飛べと飛んだ
Generating build files with CMake.

**Comment by syu-gaspard** [comment]
in-tree build, otherwise it is called an out-of-tree buildが示されていたので
out-of-tree buildを進める

**Comment by syu-gaspard** [comment]
mkdir build
cd build
cmake ..

makefileができた

**Comment by syu-gaspard** [comment]
ドキュメントよりCompiling the libraryに飛ぶ

**Comment by syu-gaspard** [comment]
makefileはできたが飛んだ先にはcompileしろの一言で終わっていた。
コマンドラインの例はないのかなと感じた

**Comment by syu-gaspard** [comment]
cmakeの後はmakeするものだと思ってとりあえずmakeして見た。

**Comment by syu-gaspard** [comment]
makeできた。

**Comment by syu-gaspard** [comment]
examples, src,testsが生成された

examlesを動かしてみる。

**Comment by syu-gaspard** [comment]
examplesでできたものが何なのか説明が見当たらない・・・どこかにある？
buildしたら何ができるのかわからない

**Comment by syu-gaspard** [comment]
examplesでできた成果物についてコードやアプリ名で予測はつくが何なのかdocumentから知りたい。

**Comment by syu-gaspard** [comment]
examplesは無事全て動いた。

**Comment by syu-gaspard** [comment]
testsも動かしてみる。
テスト目的がドキュメントからわからない。

**Comment by syu-gaspard** [comment]
サポーターコメント：OssではDocument部分について誰向けかによりリンクされているものは違うことは多い。

**Comment by syu-gaspard** [comment]
サポーターコメント：複数のコミュニティのライブラリが使われる場合はドキュメントは相手に任す方がいいケースも多い。追従できるかも課題。

**Comment by syu-gaspard** [comment]
GLFWの公式HPからDocumentationメニューから先頭のHTML documentationのリンクに飛べばビルドへの手順が示されていた。

**Comment by syu-gaspard** [comment]
CMakeへの導入のUsing CMakeについて各プラットフォームのpackaging systemへのリンクを貼ったらどうか。
http://www.glfw.org/docs/latest/compile_guide.html

**Comment by syu-gaspard** [comment]
http://www.glfw.org/docs/latest/compile_guide.html
コンパイルガイドのCMakeについて
CMakeを使ったビルド方法について各Platformで別れている。（Dependencies for Xcode on OS Xとか）
CMakeのインストール方法はいくつかのPackageToolを指定し簡単にインストールできるとだけ書いてある。
粒度を合わせて各プラットフォームに分けて書いた方がわかりやすいと感じた。

**Comment by syu-gaspard** [comment]
Contribute guideを探した。以下にあった。HPには無いのかな？
https://github.com/glfw/glfw

**Comment by hk220** [comment]
https://github.com/glfw/glfw/blob/master/docs/compile.dox
修正したいファイルはこれみたいですー

**Comment by syu-gaspard** [comment]
・修正したい感じを日本語で
CMakeをLinuxでインストール
CMakeをFreeBSDでインストール
CMakeをWindowsでインストール
CMakeをMacOSでインストール

・なぜ変えたいのか
DependenciesではBuild環境に応じた粒度で書かれているのにCMakeのインストールについては
全てのPlatformでまとめて書かれている。情報の粒度の違いがわかりづらい・導入に戸惑うと感じたため。

**Comment by hk220** [comment]
情報を階層化してみました！

・やりたいこと
compile.dox の Using CMake の情報の粒度を Dependencies と揃えたい。

例：
DependenciesではBuild環境に応じた粒度で書かれているのにCMakeのインストールについては
全てのPlatformでまとめて書かれていて粒度がそろっていない。

・困ったこと
OS X で glfw を使おうとしたときに、cmake をインストールする必要があることが分かったが、ドキュメントにかかれている方法のうち、どれをどのように使っていいのかわからない。

・どのように変えたいか
例：
Using CMake
CMakeをLinuxでインストール
CMakeをFreeBSDでインストール
CMakeをWindowsでインストール
CMakeをMacOSでインストール

**Comment by syu-gaspard** [comment]
フォローアップに参加

**Comment by syu-gaspard** [comment]
前回のワークショップでglfwについて指摘したいことを再度確認しました。

その中でCMakeのインストール手順の粒度が大雑把な点について実際に困ったか振り返りあまり困っていなかったと考えるようになった。

**Comment by syu-gaspard** [comment]
もともとはglfwのビルド手順に進むドキュメント無いと勘違いし不親切と考えていた。
実際にはビルドに進む手順はあり以下でいけた。
[TOP]→[Documentation]→[HTML documentation]

**Comment by syu-gaspard** [comment]
[TOP]→[HTML documentation]で良いのでは無いだろか。

**Comment by syu-gaspard** [comment]
・やりたいこと
TOPページから[HTML documentation](http://www.glfw.org/docs/latest/)に遷移できるようにし
[Compiling GLFW](http://www.glfw.org/docs/latest/compile_guide.html)へのアクセスを容易にしたい。

・現状
glfwをCompileしようとHPからDocumentationをたどると以下の遷移が必要。
[TOP]→[Documentation]→[HTML documentation]

・現状の問題点
glfwをCompileしようとHPを確認したところTOPページからリンクされている
[Documentation](http://www.glfw.org/documentation.html)→[Getting started]と遷移してしまい
ビルドページにたどり着けなかった。

また、[Documentation](http://www.glfw.org/documentation.html)の内容は
[TOP](http://www.glfw.org/)と[HTML documentation](http://www.glfw.org/docs/latest/)と
重複した内容なので省いても良いのではないでしょうか。

・変更案
[TOP]→[Documentation]→[HTML documentation]を
[TOP]→[HTML documentation]とする。

**Comment by knokmki612** [comment]
このページですね https://github.com/glfw/website/blob/master/documentation.md

**Comment by knokmki612** [comment]
変更するリンクはこの2箇所でしょうか

* https://github.com/glfw/glfw/blob/master/docs/header.html
* https://github.com/glfw/website/blob/master/_layouts/default.html

**Comment by knokmki612** [comment]
websiteリポジトリとglfwリポジトリに2つプルリクエストを出して、片方から参照する形でやってみましょう！

**Comment by syu-gaspard** [comment]
ありがとうございます。
進めて見ます。

**Comment by knokmki612** [comment]
おつかれさまでした！

issueはクローズしますが、引き続きこのissueを使って作業しても大丈夫です！
