### ISSUE TITLE
OSS Gateワークショップ 2016-7-30: ttw: ruby: 作業ログ

### ISSUE THREAD

**Issue by ttwo32** [oss-gate/workshop#88]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by ttwo32** [comment]
* 作業：Rubyをインストールしてみる
* 思っていること：まずは公式サイトを探してみよう。「ruby 公式」で探してみる。

**Comment by ttwo32** [comment]
* 作業：ドキュメントを見てみる。
* 思っていること：なんとなく手順が書いてありそう。

**Comment by ttwo32** [comment]
* 作業：インストールガイド発見！！したので見てみる。
* 思っていること：良い感じなリンク。

**Comment by ttwo32** [comment]
* 作業：OS Xのガイド発見したので見てみる。
* 思っていること：rbenvのリンクが一番上にあるのでrbenvから見るべきなのか？

**Comment by ttwo32** [comment]
* 作業：rbenvのインストールからやってみる。https://github.com/rbenv/rbenv
* 思っていること：githubのページのReaemeを読めば良いのかな？英語は少し苦手。。。。

**Comment by ttwo32** [comment]
* 作業：rbenv installationを発見したのでやってみる。https://github.com/rbenv/rbenv#installation
* 思っていること：とりあえず書いてあるコマンドをコピペ。

**Comment by ttwo32** [comment]
* 作業：rbenvインストールしてあるけど.bash_profileに$PATH追記したか確認してみる。cat ~/.bash_profile
* 思っていること：以前なんとなくやった気がスル。

**Comment by ttwo32** [comment]
* 作業：typeコマンドって何かわからないので調べる。「type command」で調べる。
* 思っていること：コマンド使ってないと忘れてしまう・・・。

**Comment by ttwo32** [comment]
* 作業：ITProのページ発見。http://itpro.nikkeibp.co.jp/article/COLUMN/20060227/230909/?rt=nocnt
* 思っていること：rbenvコマンドはfunctionであることがわかった。

**Comment by ttwo32** [comment]
* 作業：RVMのインストールをやってみる。https://www.ruby-lang.org/ja/documentation/installation/#rvm
* 思っていること：rvm.ioを見なさいということっぽい。

**Comment by ttwo32** [comment]
* 作業：名称が古いことに気づいた。OS XじゃなくてmacOS。https://ja.wikipedia.org/wiki/OS_X
* 思っていること：WWDC２０１６で変更されたの知らなかった。。。

**Comment by ttwo32** [comment]
* 作業：メンターへの説明
* 思っていること：初心者にはパッと見rbenvとか何かわからないのでいつになったらrubyがinstalされるのか分かりやすく書いた方が良さそう。

**Comment by ttwo32** [comment]
* 作業：メンターへの説明
* 思っていること：各インストール方法のリンクの横に簡単なオススメが書いていると良いと思いました。https://www.ruby-lang.org/ja/documentation/installation

**Comment by ttwo32** [comment]
* 作業：Ruby インストールガイドを修正するためにどこに連絡すれば良いのか探してみる。とりあえずGoogle カスタム検索で「ドキュメント　修正」で検索してみる。
* 思っていること：Ruby インストールガイドのページ（https://www.ruby-lang.org/ja/documentation/installation/）に、ドキュメントを修正したい時のために案内があると良いのではだろうか。

**Comment by ttwo32** [comment]
* 作業：Google カスタム検索で「ドキュメント　修正」で検索したけどわからなかったので、公式ドキュメントのトップページを見て、ドキュメント修正方法を探してみる。　https://www.ruby-lang.org/ja/documentation/
* 思っていること：ドキュメントのソースをバージョン管理している場所を知りたい。

**Comment by ttwo32** [comment]
* 作業：ドキュメントのトップページにもなかったのでコア開発ページを見てみる。https://www.ruby-lang.org/ja/dev/
* 思っていること：なかなか見つからない。

**Comment by ttwo32** [comment]
* 作業：ソースコードのリポジトリガイドのリンクがあったので見てみる。
* 思っていること：なんとなくここから辿れるかも。

**Comment by ttwo32** [comment]
* 作業：同じく公式サイトのドキュメント修正をしようとしていた方が、Github上のコントリビューションガイドを見つけたとのことなので聞いてみたところ、”このウェブサイトについて”（https://www.ruby-lang.org/ja/about/website/）から辿ったとのことなので、やってみる、
* 思っていること：人に聞けるのはありがたい。

**Comment by ttwo32** [comment]
* 作業：contribution instructions を見つけた！！のでクリック。
* 思っていること：またもや英語。オンライン英会話でも始めた方が良いのかと思ってしまう。

**Comment by ttwo32** [comment]
* 作業：the repository　リンクを見つけた！！　https://github.com/ruby/www.ruby-lang.org
* 思っていること：フォルダ構成を見ると国別に分かれているようだ。

**Comment by ttwo32** [comment]
* 作業：探していたページを見つけた!! Editで編集してみる。
https://github.com/ruby/www.ruby-lang.org/blob/master/ja/documentation/installation/index.md
* 思っていること：なんとかできそうだ。

**Comment by ttwo32** [comment]
* 作業：この文言を見ると書き込み権限がないみたいだ。forkして修正してpull requestすれば良いのかな。
「You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork ttwo32/www.ruby-lang.org, so you can send a pull request.」
* 思っていること：まずforkしてみよう。

**Comment by kou** [comment]
お疲れ様でした！

**Comment by ttwo32** [comment]
* 作業：メモ
* 思っていること：公式サイトのサイドバーにも貢献したい人むけのガイドを書いてあっても良いかなと思いました。
