### ISSUE TITLE
OSS Gateワークショップ 2016-07-30: tohaya0216: Rails5: 作業ログ

### ISSUE THREAD

**Issue by tohaya0216** [oss-gate/workshop#89]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by tohaya0216** [comment]
* 作業: Rails5 をインストールして、動かす
* 思っていること：環境の準備に手間取りそう・・・

**Comment by tohaya0216** [comment]
* 作業：ドキュメント、インストール手順を探す
* 思っていること：先ほどrails5でググったら、一番目に該当ページはヒットしなかった

**Comment by tohaya0216** [comment]
* 作業：ドキュメント探し(継続)
* 思っていること：英語のそれっぽいページにとんだが、リリース情報などのブログページだった http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/

**Comment by tohaya0216** [comment]
* 作業：ドキュメント探し(継続)。公式サイトにアクセス(http://rubyonrails.org/)
* 思っていること：　パッと見で、インストール手順などはみあたらず

**Comment by tohaya0216** [comment]
* 作業：オフィシャルサイトのトップメニューから、ガイドページへアクセスhttp://guides.rubyonrails.org/
* 思っていること：Getting Started with Railsとある。これをみればいけそう？

**Comment by tohaya0216** [comment]
* 作業： Getting started ....をみる(http://guides.rubyonrails.org/getting_started.html)
* 思っていること：英語でつらい

**Comment by tohaya0216** [comment]
* 作業：ガイドページをみる(継続)
* 思っていること：
「Right version of Development Kit, if you are using Windows.」とかいてある。windowsを使用しているので、この辺りをインストールする必要があるのか？（面倒）

**Comment by tohaya0216** [comment]
* 作業：Ruby インストーラーページ (http://rubyinstaller.org/downloads/)をみる
* 思っていること：2.2x以上とかいてあったはずなので、Ruby 2.3.1をいれてみるか。

**Comment by tohaya0216** [comment]
* 作業：Ruby 2.3.1をいれる。とりあえずダウンロード
* 思っていること：windows環境でruby使ったことなし。ちゃんと動くか不安

**Comment by tohaya0216** [comment]
* 作業：ダウンロードしたexeファイルを実行し、インストールする。
* 思っていること：

インストール先PATH: C:\Ruby23
チェックしたオプション：
* Rubyの実行ファイルへ環境変数PATHを設定する

「Tcll/Tkサポートをインストールする」ってなに？
=> マウスオーバーすると、GUI作成ツール～～と書いてあった。GUIは不要と思われるのでチェックしない

**Comment by tohaya0216** [comment]
* 作業：インストール実行
* 思っていること：特に問題なく完了したっぽい

**Comment by tohaya0216** [comment]
* 作業：フルパスで実行してみる
* 思っていること：
バージョン見れるため、パスが通ってないけい

```
>C:\Ruby23\bin\ruby.exe -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
```

**Comment by tohaya0216** [comment]
* 作業：コマンドプロンプト起動なおして実行
```
C:\Users\tohay_000>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
```
* 思っていること：とおってた。

**Comment by tohaya0216** [comment]
* 作業：Development Kit,をいれるために、ダウンロードページをさぐる
http://rubyinstaller.org/downloads/
* 思っていること：　windows環境でやろうとするといろいろ面倒

**Comment by tohaya0216** [comment]
* 作業：以下をダウンロード、インストールしてみる
For use with Ruby 2.0 and above (32bits version only):
    DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe
http://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

インストールパス：C:\Users\tohay_000\Downloads\
* 思っていること：
終わったけど、正常なのかどうかはよくわからず。

**Comment by tohaya0216** [comment]
* 作業：
http://guides.rubyonrails.org/getting_started.html
1 Guide Assumptionsの内容にそって、RubyGemページへアクセス。
* 思っていること：
なにかインストール必要かとおもったが、「which is installed with Ruby by default.」とのことなので特にインストールなど不要、のはず

**Comment by tohaya0216** [comment]
* 作業：SQLITE3ページへアクセス。インストール手順などを調査
https://www.sqlite.org/
* 思っていること：英語つらい

**Comment by tohaya0216** [comment]
* 作業：sqlite3 ダウンロードページへアクセス
https://www.sqlite.org/download.html
Precompiled Binaries for Windows　をいれようと思った。
自分のwindows環境が64bitかどうかいちおう確認

```
64-bit DLL (x64) for SQLite version 3.13.0.
(sha1: e1254b108e884e09552f8e57104724b5f756a6ce)
```
https://www.sqlite.org/2016/sqlite-dll-win64-x64-3130000.zip をダウンロード
* 思っていること：
linuxなら楽なのに。

**Comment by tohaya0216** [comment]
* 作業：ダウンロードしたファイルを展開

```
sqlite3.def
sqlite3.dll
```

* 思っていること：
これどうするの

**Comment by tohaya0216** [comment]
* 作業：別のファイルも落としてみる

https://www.sqlite.org/2016/sqlite-tools-win32-x86-3130000.zip
```
sqlite-tools-win32-x86-3130000.zip
(1.51 MiB)
```

```
A bundle of command-line tools for managing SQLite database files, including the command-line shell program, the sqldiff.exe program, and the sqlite3_analyzer.exe program.
(sha1: d74226e1cd38853f792266b221ae70c6c7b26835)
```
* 思っていること：
linuxなら楽なのに

**Comment by tohaya0216** [comment]
* 作業：　sqlite-tools-win32-x86-3130000.zip　のファイルを解凍
それっぽいexeファイルがあった。sqlite3.exeを実行してみたらそれっぽい画面がでてきた。
.tables をうって、エラーがおきず、適当な文字列をうったらエラーになったので、ちゃんとsqlite3が使えるぽい感じ。

```
sqlite3.exe
sqlite3_analyzer.exe
sqldiff.exe
```

* 思っていること：
PATHとおしたりも必要？？

**Comment by tohaya0216** [comment]
* 作業：再度railsのページのドキュメントを確認
http://guides.rubyonrails.org/getting_started.html
* 思っていること：
ここまでくるまでに長かった。windows環境面倒

**Comment by tohaya0216** [comment]
* 作業：　2.What is Rails?はとばして、3 Creating a New Rails Projectを上から順にながめる。
* 思っていること：
英語つらい

**Comment by tohaya0216** [comment]
* 作業：　3.1 Installing Railsに記載のコマンドを、コマンドプロンプトで試す。

```
C:\Users\tohay_000>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
```

```
C:\Users\tohay_000>sqlite3 --version
'sqlite3' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

* 思っていること：やはりパスを通す必要があった。

**Comment by tohaya0216** [comment]
* 作業：先ほどダウンロードしたsqlite3のディレクトリを、
C:\sqlite3
にコピー。PATHを通す。
* 思っていること：windows のPATHてどこで通すんだっけ

**Comment by tohaya0216** [comment]
* 作業: 報告する内容をまとめる（日本語で）
* 思っていること：
必要な情報をもりこんだ文章を書こう。

**Comment by tohaya0216** [comment]
* 作業: Railsのインストール手順についての改善要望を記載。

```
報告内容(日本語)

Windows8.1Proを使用しています。
※Rubyなど特にインストールされていないPCです。

今回、Windows環境にてRailsをインストールし、動作させたいと思い
http://guides.rubyonrails.org/getting_started.html
のページを参考にし手順を進めました。

ページ上部から読み進めていき、
・Rubyのインストール
・sqlite3のインストール
・PATHへの追加
などの手順を進めていきましたが、
ページ途中で「Rails Installer」というツールがあることに気が付きました。
http://railsinstaller.org/

「Getting Started」のもっと画面上部（たとえば、1 Guide Assumptionsでの文章内など)
でアナウンスしてもらえると、
Rails開発環境を作成したいユーザーにとって助かると思いますので、
ご検討をお願いします。
```

上記内容について、すでに同じような内容のissueがないかを調査する

* 思っていること：
ちゃんと英語にできるかどうか・・・。

**Comment by tohaya0216** [comment]
* 作業:　http://guides.rubyonrails.org/getting_started.html のFeedBackの項目をチェック
http://edgeguides.rubyonrails.org/
このページをチェックしろとのことなので、見てみる。

* 思っていること：英語つらい

**Comment by tohaya0216** [comment]
* 作業: edgeページ( http://edgeguides.rubyonrails.org/ ) を確認し、今回報告したい内容についての内容を確認
* 思っていること： 
特に変更など加えられていないことを確認

**Comment by tohaya0216** [comment]
* 作業:
https://github.com/rails/rails/issues に同様のトピックがあがってないかを確認する
* 思っていること：

**Comment by tohaya0216** [comment]
* 作業: issue をラベル：docsにて絞り込み
https://github.com/rails/rails/labels/docs
１ページ目では、同様の内容は発見できず
* 思っていること：

**Comment by tohaya0216** [comment]
* 作業:issuesを確認し、重複する内容がなかったため、New Issueページ ( https://github.com/rails/rails/issues/new ) へアクセス
* 思っていること：
以下テンプレートがデフォルトで記載されていた

```
### Steps to  #reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

```

**Comment by tohaya0216** [comment]
* 作業: New Issuesに記載する文章を英語で用意する
* 思っていること：
英語頑張る

**Comment by tohaya0216** [comment]
* 作業:issueを作成する際には、バグレポートのやりかたページ　 ( http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report ) をみろとのことなので、確認する

```
(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))
```

* 思っていること：

**Comment by tohaya0216** [comment]
* 作業: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report 
に記載されていたdocrails がわからなかったので、ググって以下ページに到着 
http://weblog.rubyonrails.org/2012/3/7/what-is-docrails/
* 思っていること：

**Comment by tohaya0216** [comment]
* 作業: 上記ページを確認し、特に投稿して問題ないかと思われるので、
テンプレートにそってNew Issueを記載する
* 思っていること：

**Comment by kou** [comment]
お疲れ様でした！
