### ISSUE TITLE
OSS Gateワークショップ 2016-7-30: Cherry: Perl: 作業ログ

### ISSUE THREAD

**Issue by shinji-kakimoto** [oss-gate/workshop#90]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by shinji-kakimoto** [comment]
* 作業:Perlの公式サイトに行こう。
* 思っていること：簡単にダウンロードできるやろ。

**Comment by shinji-kakimoto** [comment]
作業:Perlの「Download」を発見した
思っていること：クリックすれば簡単にダウンロードできるか

**Comment by shinji-kakimoto** [comment]
作業：MacOSには既にperlがInstallされていることを見つけた。
思っていること：ActiveState Perlってなんだろう

**Comment by shinji-kakimoto** [comment]
作業：Perlをsrcからコンパイルしよう
思っていること：どこにあるんだ。

**Comment by shinji-kakimoto** [comment]
作業：cpanからperlをinstallする手順を発見(http://www.cpan.org/src/README.html)
思っていること：これをやってみましょう。

**Comment by shinji-kakimoto** [comment]
作業：perlのinstall手順をやってみる。
思っていること：うまく動くかな。

**Comment by shinji-kakimoto** [comment]
作業:インストールで「 ./Configure -des -Dprefix=$HOME/localperl」を実行した。
思っていること:途中で実行が止まって、なんか問題があるかと思った。

**Comment by shinji-kakimoto** [comment]
作業:
思っていること:

**Comment by shinji-kakimoto** [comment]
作業:makeを実行
思っていること:どれくらい時間がかかるのだろうか？

**Comment by shinji-kakimoto** [comment]
作業:make終了して、make testを実行
思っていること:makeは5分くらいですよ。こっちははやそう

**Comment by shinji-kakimoto** [comment]
作業:make testを実行中
思っていること:「t/io/eintr .................................................... skipped」でskipがある

**Comment by shinji-kakimoto** [comment]
作業:make testを実行中
思っていること:「t/re/regexp_unicode_prop_thr .................................. skipped」はthrが飛ばされている。

**Comment by shinji-kakimoto** [comment]
作業:make testを実行中
思っていること:failedは発生していない。

**Comment by shinji-kakimoto** [comment]
作業:make testを完了
思っていること:all test successfulでした。よかった。
備考:かるくテスト結果をば。
All tests successful.
Elapsed: 735 sec
u=6.98  s=3.72  cu=384.77  cs=45.66  scripts=2243  tests=850199

**Comment by shinji-kakimoto** [comment]
作業:READMEを読む
思っていること:とりあえずinstall完了

**Comment by shinji-kakimoto** [comment]
作業:install 完了したと思われるものを起動してみる。>perl v
思っていること:どこにインストールされたのでしょうか？

**Comment by shinji-kakimoto** [comment]
作業:$HOME/localperlにinstallされていることを確認。
思っていること:「./Configure -des -Dprefix=$HOME/localperl」から
               localperlDirにinstallを見つけた。あたった。

**Comment by shinji-kakimoto** [comment]
作業:実行の仕方が分からない。
思っていること:もうしわけない、メンターさん。

**Comment by shinji-kakimoto** [comment]
作業:「./perl -v」で実行。
思っていること:できた
備考:パスが通ってない場合は明示する。

**Comment by shinji-kakimoto** [comment]
作業:  perldoc perlをREAD MEに実行
備考: ちゃんと読んでみよう。

**Comment by shinji-kakimoto** [comment]
作業:https://metacpan.org/release/Web-Scraperを使ってみる
思っていること:何かネタがあればよいな。

**Comment by shinji-kakimoto** [comment]
作業:https://metacpan.org/source/MIYAGAWA/Web-Scraper-0.38/READMEを読む
思っていること:まずはREADMEを読もう

**Comment by shinji-kakimoto** [comment]
作業: >./cpan Web::Scraperでインストール
思っていること:できるかな。cpanmのほうがよいけど。

**Comment by shinji-kakimoto** [comment]
作業:READMEにあるサンプルプログラムを動かしてみる
思っていること:The structure would resemble this (visually)。これはなんだろう。
備考:
syntax error at web_scraper.pl line 31, near ") {"
Execution of web_scraper.pl aborted due to compilation errors.

**Comment by shinji-kakimoto** [comment]
作業:miyagawaProductをサンプル実行して完了。
思っていること:全然問題なし。

**Comment by shinji-kakimoto** [comment]
作業:CPANからなんか探してみる
思っていること:みつかるか？

**Comment by shinji-kakimoto** [comment]
作業:cpan Task::Kenshoを実行
思っていること:Warningが発生中。
Warning: prerequisite Lingua::EN::Words2Nums 0 not found.

**Comment by shinji-kakimoto** [comment]
作業:https://metacpan.org/pod/WWW::Mechanizeのサンプルを実行
思っていること:動くかしら？

**Comment by shinji-kakimoto** [comment]
作業:WWW::Mechanizeのサンプルを修正して実行。
思っていること:どういう風な実行結果が期待されているのかしら？

**Comment by shinji-kakimoto** [comment]
作業:WWW::Mechanizeのサンプル例を分かり易くすることにした。
思っていること:どういうサンプルにすると分かり易くなるのだろうか？

**Comment by shinji-kakimoto** [comment]
作業:ブラウジングのストーリーを組み立てる
思っていること:作業を分割
備考
1.http://www.cpan.org/をget
2.検索フォームに「Mechanize」を実行する
3.リンクの一番目を取得。(おそらく、https://metacpan.org/pod/WWW::Mechanizeに飛ぶ)
4.文字を出力してみる

**Comment by kou** [comment]
お疲れ様でした！
