### ISSUE TITLE
OSS Gate Workshop: Toranomon: 2018-06-13: stmtstk: cti-python-stix2: Work log

### ISSUE THREAD

**Issue by stmtstk** [oss-gate/workshop#908]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shiracamus** [comment]
よろしくお願いします。

**Comment by stmtstk** [comment]
今後開発で使うであろう stix2 をハンドリングする python library をインストールしてみる。

https://github.com/oasis-open/cti-python-stix2

License は BSD 3-Clause "New" or "Revised" License

https://github.com/oasis-open/cti-python-stix2/blob/master/LICENSE

インストールを実施する

**Comment by stmtstk** [comment]
pip を update するも同じエラー
なので、まずは sudo apt-get update でリポジトリ更新。が、結果NG。

結局 Ubuntu のバージョンが古いからと判断。 18.04 amd64 を新規インストールしてから実行

> pip install stix2

>>> import stix2
>>> print stix2

動作を確認

**Comment by stmtstk** [comment]
python3 用の stix2 library が存在するかどうかインストールして確認。

> pip3 install stix2

インストール自体は成功

> python3

> python3
> Python 3.6.5 (default, Apr  1 2018, 05:46:30)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import stix2

python3 用もインストールを確認

**Comment by stmtstk** [comment]
usage に従い python3 interpreter で indicator を作成する

https://github.com/oasis-open/cti-python-stix2#usage

```
>>> from stix2 import Indicator
>>> indicator = Indicator(name="File hash for malware variant",
...                       labels=["malicious-activity"],
...                       pattern="[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']")
>>>
>>> print (indicator)
{
    "type": "indicator",
    "id": "indicator--43819e51-10f8-420d-8d08-ac3ccf204727",
    "created": "2018-06-13T03:09:44.409Z",
    "modified": "2018-06-13T03:09:44.409Z",
    "name": "File hash for malware variant",
    "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
    "valid_from": "2018-06-13T03:09:44.409651Z",
    "labels": [
        "malicious-activity"
    ]
}
```

正常動作確認

**Comment by ssyy201506** [comment]
READMEのサンプルコードが正常に動作しない点を issue で指摘するのは良いと思います

**Comment by stmtstk** [comment]
https://github.com/oasis-open/cti-python-stix2/blob/master/CONTRIBUTING.md#feedback

feedback については、 github で OK。
github 使えない場合はメーリングリストへ。とのことなので github で行う。

**Comment by stmtstk** [comment]
フィードバックポイント

README.rst 内の Usage に記載のサンプルプログラムが期待通りの動作をしない。
動作するような修正ポイントを見つけたので合わせて報告する。

**Comment by stmtstk** [comment]
編集 (日本語)

README.rst 内の Usage に記載の parser() のサンプルプログラムを pytyon3 インタプリタに copy & paste して動作させたところエラーが発生しました。

動作環境: Ubuntu 18.04 amd64
インタプリター: Python3

試したコード
```
from stix2 import parse

indicator = parse("""{
    "type": "indicator",
    "id": "indicator--dbcbd659-c927-4f9a-994f-0a2632274394",
    "created": "2017-09-26T23:33:39.829Z",
    "modified": "2017-09-26T23:33:39.829Z",
    "labels": [
        "malicious-activity"
    ],
    "name": "File hash for malware variant",
    "pattern": "[file:hashes.md5 =
    'd41d8cd98f00b204e9800998ecf8427e']",
    "valid_from": "2017-09-26T23:33:39.829952Z"
}""")
print(indicator)
```

得られた結果
```
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "/home/terrra/.local/lib/python3.6/site-packages/stix2/core.py", line 97, in parse
    obj = _get_dict(data)
  File "/home/terrra/.local/lib/python3.6/site-packages/stix2/utils.py", line 155, in _get_dict
    return json.loads(data)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 10 column 35 (char 306)
```

おそらく parse() の引数の json フォーマットに問題があるものと推測します。
line 番号より

```
    "pattern": "[file:hashes.md5 =
    'd41d8cd98f00b204e9800998ecf8427e']",
```

の pattern の値が複数行であったため、

```
    "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
```

のように修正したところ、以下のような期待された結果が得られました。

```
{
    "type": "indicator",
    "id": "indicator--dbcbd659-c927-4f9a-994f-0a2632274394",
    "created": "2017-09-26T23:33:39.829Z",
    "modified": "2017-09-26T23:33:39.829Z",
    "name": "File hash for malware variant",
    "pattern": "[file:hashes.md5 = 'd41d8cd98f00b204e9800998ecf8427e']",
    "valid_from": "2017-09-26T23:33:39.829952Z",
    "labels": [
        "malicious-activity"
    ]
}
```

"pattern" の値は複数行にわたる必要もないと考え、 README.rst を修正すべきと考えます。

**Comment by stmtstk** [comment]
README.rst を直接編集し、 merge することに。


Propose file change.

Title: 
Cannot execute sample code.

Description: 
I tried to execute sample code of parse() on python 2.7 and 3.0.
But It occured JSONDecodeError because "pattern" value of sample JSON  are described as multi-line. 
To ensure that sample code works, this value shuld be single-line.

**Comment by tdtds** [comment]
pythonの複数バージョンで試したのは良いですね。作者はどちらか一方でしか試していない場合も少なくないので。
