### ISSUE TITLE
OSS Gate Workshop: Toranomon: 2018-06-13: kotowarinone: thc-ipv6: Work log

### ISSUE THREAD

**Issue by kotowarinone** [oss-gate/workshop#909]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kotowarinone** [comment]
Issueを作成しました。

**Comment by kotowarinone** [comment]
業務上必要であり、また興味もあるため、 THC-IPv6 ツールを対象とします。
https://github.com/vanhauser-thc/thc-ipv6/blob/master/LICENSE

**Comment by kotowarinone** [comment]
ライセンスを確認します。
LICENSEファイルがあり、Affero GPL3でした。

**Comment by kotowarinone** [comment]
ダウンロードしてコンパイルします。
git clone https://github.com/vanhauser-thc/thc-ipv6.git

**Comment by kotowarinone** [comment]
INSTALL および README のファイルが存在します。
README ファイル内に BUILDING セクションがあり、インストールの仕方が端的に書いてあるようです。
一方、INSTALL ファイルのほうにもインストールの仕方が少し詳しく書いてありますが、INSTALLファイルは小さく、READMEに統合したほうがいいかもです。

**Comment by kotowarinone** [comment]
INSTALLに記載の通りにビルドします。
sudo apt-get install libpcap-dev libssl-dev 
問題なし。
sudo apt-get install libnetfilter-queue-dev 
問題なし。
make
-o fuzz_dhcps6 fuzz_dhcps6.c で Type Mismatch ( size_t → int )
-o fuzz_dhcpc6 fuzz_dhcpc6.c で Type Mismatch ( warning char * → unsigned int * )
-o fuzz_dhcpc6 fuzz_dhcpc6.c で Type Mismatch ( 'char *' → ‘unsigned int *’ )
-o connect6 connect6.c  で Type Mismatch (‘long unsigned int’ → ‘int’ )

**Comment by kotowarinone** [comment]
make install 
問題なし。

**Comment by kotowarinone** [comment]
manを検証
一部抜粋して、
 man parasite6
 man flood_router6
 man fake_router6
 man detect_sniffer6
は正常に動作しました。全確認は必要に応じて後程行います。

**Comment by kotowarinone** [comment]
コマンドを引数なしで実行して、表示されるヘルプが正しいか確認します。

**Comment by kotowarinone** [comment]
マニュアルの次のセクションには、
THE TOOLS
=========
として抜粋したコマンドが書いてあります。
最初に記載されている
- parasite6:
を確認し、実行してみます。

**Comment by kotowarinone** [comment]
parasite6 を誤ってroot権限なしで実行しましたが、特にエラーの通知なくコマンドが終了してしまい、root権限が必要であるという情報が表示されませんでした。マニュアルにもroot権限が必要だという記載はありません。
このツールの利用者はroot権限が必要であることを当然知っているものとしてよいとは思いますが、指定忘れの際に指定していないことを通知しないのは一瞬混乱が生じ、不便と感じました。

**Comment by kotowarinone** [comment]
root指定し忘れのケースと、適正に指定したケースでUIに差異がない。

ohhira@ohhira-VirtualBox:~$ parasite6 enp0s8
Remember to enable routing, you will denial service otherwise:
 =>  echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
Remember to prevent sending out ICMPv6 Redirect packets:
 =>  ip6tables -I OUTPUT -p icmpv6 --icmpv6-type redirect -j DROP
Started ICMP6 Neighbor Solitication Interceptor (Press Control-C to end) ...
ohhira@ohhira-VirtualBox:~$ sudo parasite6 enp0s8
Remember to enable routing, you will denial service otherwise:
 =>  echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
Remember to prevent sending out ICMPv6 Redirect packets:
 =>  ip6tables -I OUTPUT -p icmpv6 --icmpv6-type redirect -j DROP
Started ICMP6 Neighbor Solitication Interceptor (Press Control-C to end) ...
^Cohhira@ohhira-VirtualBox:~$ ls

**Comment by kotowarinone** [comment]
フィードバックポイント１、root指定忘れ対策がない
フィードバックポイント２、THC全コマンドのヘルプがない

**Comment by kotowarinone** [comment]
連絡の仕方を確認します。
READMEには連絡先がメールと書いてあるけど、Github上でもissueを受け付けているようだ。
両方を手段として許容する場合は、READMEに両方書いたほうが良いのではないか？

**Comment by kotowarinone** [comment]
連絡先について公式サイトを参照しようとしたが、https://www.thc.org/ は証明書に問題があり、しかも https://twitter.com/hackerschoice  にリダイレクトされる。
githubのissueも運用されており、最終の対応が昨年の11月であるため、そちらをそのまま使うようにします。

**Comment by kotowarinone** [comment]
■自分なりの言葉で

◆フィードバック１：
READMEにはフィードバック先としてメールアドレスが書いてある。
しかし、GitHub上のissueでも指摘できるとうれしいし、実際そのように運用されている。
だから、README にGitHubのプロジェクト名と、そこのissueでも受け付けることを記載してもらえると嬉しい。

◆フィードバック２：
あやまってrootの指定を忘れて parasite6 コマンドを実行すると、エラーメッセージがなくコマンドが終了する。
ユーザとしては内部でプロセスをforkしてテストパケットを送っているのかと誤解してしまう。
THCのユーザは当然root権限が必要なことを知っているだろうが、ミスで指定を忘れることがあり、その場合のエラーメッセージがあると混乱しなくてうれしい。

**Comment by kotowarinone** [comment]
●変更

PATCHES, BUGS, HINTS, etc.
==========================
Send them to vh (at) thc (dot) org (and add "antispam" to the subject line)
↓
PATCHES, BUGS, HINTS, etc.
==========================
Send them to vh (at) thc (dot) org (and add "antispam" to the subject line)
Also available Issue and Pull Request on GitHub.

●Commit Log コメント

Added recent contact information on GitHub

●Pull Request コメント

I propose you to add new contact way as the Issue and Pull Request on GitHub.

**Comment by shiracamus** [comment]
ドキュメント記載の連絡方法と実際の連絡方法に違いがあることに気付き、適切に反映依頼しているので、とてもいいと思います。
