### ISSUE TITLE
OSS Gate Workshop: Toranomon: 2018-06-13: ykoji8681: cti-stix-elevator: Work log

### ISSUE THREAD

**Issue by ykoji8681** [oss-gate/workshop#910]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by shiracamus** [comment]
よろしくお願いします

**Comment by ykoji8681** [comment]
oasisのcti-stix-elevatorに興味があるので試してみる
https://github.com/oasis-open/cti-stix-elevator

**Comment by ykoji8681** [comment]
Requirementsでpython-stixが必要なのでpipでインストール。

**Comment by ykoji8681** [comment]
pipがエラーとなり、--upgradeするようにとのメッセージが出たのでupgradeする。
だがupgradeするとimport mainでpipの起動に失敗することがあるらしい。その場合はrebootすることで対応する。

**Comment by ykoji8681** [comment]
python-stix, python-stix2, stix2-validator, pycountry, stixmarxをインストールした。
インストールはそれぞれへのリンクが張ってあるのでそこを参考にする。
python-stixのみ、モジュール名がstixなので間違えやすい。

**Comment by ykoji8681** [comment]
STIX 1.1.1をサポートするには、python-stixのバージョンを落とさなければならない。
現在主に使用しているSTIXは1.1.1が多いのでバージョンは落とすことにする。

**Comment by ykoji8681** [comment]
pythonのバージョンは、python2が2.7.12、python3が3.5.2なので問題ない。

**Comment by ykoji8681** [comment]
stix 1.1のサンプルを使い動作させる。以下のDomain Watchlistを使用
https://stix.mitre.org/language/version1.1.1/samples.html

**Comment by tdtds** [comment]
* STIX 1.1.1と1.2を同時にサポートしてほしいというリクエスト
* cli.pyのコマンドラインシンタックスをREDMEに追加

というフィードバックがありそうですね。

**Comment by ykoji8681** [comment]
フィードバック1：STIX 1.1.1とSTIX 1.2の両方を一つのプログラムで処理したいが、依存するpython-stixのバージョンによってどちらか片方しか処理できない。このstix-elevatorで両方をサポートするようにしてくれないか。

**Comment by ykoji8681** [comment]
フィードバック2: インストールすると、UsageのAs a Syntaxの中にあるcli.pyでなく、stix2_elevatorが実行できるようになった。stix2_elevatorのコマンドラインシンタックスとしてREADMEに記述すべきではないか。

**Comment by ykoji8681** [comment]
フィードバック2には以下で記述。
Title: Readme Modification
本文：
I have installed, but I cannot see "cli.py" in Usage.
It should be "stix2_elevator".

**Comment by ykoji8681** [comment]
Pull RequestのURL
https://github.com/oasis-open/cti-stix-elevator/pull/109

**Comment by ssyy201506** [comment]
実際にインストールしてみないと分からない点を指摘しており良いPRだと思います。
