### ISSUE TITLE
OSS Gateワークショップ 2016-07-30: caf2for4: Trac: 作業ログ

### ISSUE THREAD

**Issue by caf2for4** [oss-gate/workshop#92]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by caf2for4** [comment]
* 作業：オフィシャルサイトを探す
* 思っていること：英語読めない。。

備考：そういえばTrac-lightningってどうなってるんだっけ

**Comment by caf2for4** [comment]
* 作業：オフィシャルサイト見つけた https://trac.edgewall.org/
* 思っていること：なんか部分的に日本語なのは以前Trac入れて日本語化したせい？

**Comment by caf2for4** [comment]
* 作業：セットアップ方法を探す
* 思っていること：英語。。

**Comment by caf2for4** [comment]
* 作業：バージョンを決める→Trac1.0にした
* 思っていること：ちょっと入り口がわかりにくい

**Comment by caf2for4** [comment]
* 作業：Get started with the software! のTrac1.0から手順に入った
* 思っていること：長そう！

**Comment by caf2for4** [comment]
* 作業：インストーラ（しかもいろいろ）があった！
* 思っていること：もっとややこしいのを想像していたというか前は大変だった

**Comment by caf2for4** [comment]
* 作業：インストーラをダウンロード
* 思っていること：素直に落ちてきた

**Comment by caf2for4** [comment]
* 作業：とりあえずインストーラを実行
* 思っていること：Pythonまで入れてくれるんかい

**Comment by caf2for4** [comment]
* 作業：起動確認
* 思っていること：インストール終わったけどどこから起動するの？！

**Comment by caf2for4** [comment]
* 作業：いまさらインストール説明があったことに気づいた（指摘いただいた）
* 思っていること：インストーラの下にあったら気づかないよ！

**Comment by caf2for4** [comment]
* 作業：インストールガイドを読む https://trac.edgewall.org/wiki/TracInstall
* 思っていること：今度こそ長い

**Comment by caf2for4** [comment]
* 作業：インストールガイドのuse installerの項目を読む
* 思っていること：インストーラが何をしたのかさっぱりわからないぞ！

**Comment by caf2for4** [comment]
* 作業：もう一度インストーラから起動して内容を読む
* 思っていること：やはりたいしたことは書いてない

備考：Pythonの階層の下に何かできたので、確認してみよう
C:\Python\Python27

**Comment by caf2for4** [comment]
* 作業：インストーラのログを見てみる
* 思っていること：たいしたことは書いてない

**Comment by caf2for4** [comment]
* 作業:起動手順がないか探す
* 思っていること：手順的にはプロジェクトを作れになっていた https://trac.edgewall.org/wiki/TracInstall#CreatingaProjectEnvironment

**Comment by caf2for4** [comment]
* 作業:プロジェクトを作ってみる $ trac-admin /path/to/myproject initenv
* 思っていること：パス表記がWindowsじゃないのでWindowsどうするねん

**Comment by caf2for4** [comment]
* 作業:プロジェクトを作ってみる　とりあえず素直に入れる trac-admin C:\Trac\Projects\TestProject initenv
* 思っていること：なんかいろいろ出た たりないっぽい

備考：

```
C:\Users\chr>trac-admin C:\Trac\Projects\TestProject initenv
Traceback (most recent call last):
  File "C:\Python\Python27\Scripts\trac-admin-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 2912, in <module>

  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 2898, in _call_as
ide
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 2925, in _initial
ize_master_working_set
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 642, in _build_ma
ster
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 943, in require
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 830, in resolve
pkg_resources.DistributionNotFound: The 'Genshi>=0.6' distribution was not found
 and is required by Trac
```

**Comment by caf2for4** [comment]
* 作業:足りないものを探す まずGenshiがないといわれている
* 思っていること：あれ、入れてないんだっけ、他のPCだっけ？

**Comment by caf2for4** [comment]
* 作業:そもそも依存確認してなかった いろいろあるぞー
* 思っていること：まずそっちから片付けないと！

備考：
インストーラDLとインストールガイドリンクの下
‘‘‘
About the prerequisites for Trac 1.0.x ¶

Python 2.5, 2.6 or 2.7 (+​setuptools)
Genshi: ​0.7 (or ​0.6.1) (win32 installer available)
Babel: ​1.3 (or ​0.9.6, win32 installer available) needed for localizing Trac, otherwise optional. Note that it needs to be installed before Trac when installing the latter from source (.gz or .zip).
For Windows x64, there are no installers for Genshi and Babel so install them by using easy_install.
‘‘‘

**Comment by caf2for4** [comment]
* 作業:Genshiを入れよう
* 思っていること：の前にsetuptools入れないといけない気がする

**Comment by caf2for4** [comment]
* 作業:とりあえずsetuptoolsを入れる https://pypi.python.org/pypi/setuptools
* 思っていること：PowerShellのバージョンで入れ方が違うらしい

**Comment by caf2for4** [comment]
* 作業:ez_setup.pyをDLして実行する
* 思っていること：まだ終わらないぞー

備考：
これそのまま実行？Pythonから実行？

**Comment by caf2for4** [comment]
* 作業:ez_setup.pyを実行
* 思っていること：なんかエラー出た(流れて見えない)けどsetuptoolsは入ったっぽい

**Comment by caf2for4** [comment]
* 作業:セットアップは時間の関係で一旦中断して、インストーラが不親切な件を報告する
* 思っていること：インストーラは正常にに終了しているのに、依存で後に怒られるのは不便だ

**Comment by caf2for4** [comment]
自分語版

Windows32bit用のインストーラをDLしてきて実行したらインストール済みPythonの指定のみでインストールがエラーなしで完了
でもその後プロジェクト作成しようとしたら依存パッケージが足らん！と怒られたのでインストーラ側でチェックして注釈等出してくれるといいな！もしくはチェックツールがあるといいな！
（プロジェクト作成が成功するまで都度いろいろエラー出て確認してーは面倒）

**Comment by caf2for4** [comment]
インストーラ内もしくは別ツールで依存性の確認を事前にできないか

Windows7 32bitOS上でWindows installer (32-bit Python) のインストーラを実行したところ、Pythonのバージョン指定(Python2.7)をして正常終了したが、その後プロジェクト作成の際に依存パッケージの不足でエラーになった。
都度、依存性でエラーが出るのを追うのも大変なので、最初の段階で依存性のチェックを可能にできないか。
インストーラにチェックを含める、もしくは別途チェックツールがあればプロジェクト作成前のチェックが可能になる。

**Comment by caf2for4** [comment]
* 作業:投稿窓口を探す
* 思っていること：見つけた https://trac.edgewall.org/wiki/NewTicket

**Comment by caf2for4** [comment]
* 作業:投稿窓口に注意事項があったので読んだら、重複投稿がないからチェックしろ！といわれた
* 思っていること：チェックしよう

**Comment by caf2for4** [comment]
* 作業:重複投稿のチェック　キーワード：Dependencies check installer
* 思っていること：やっぱり英語わからないとだめだ。。ぐーぐる先生万歳。

**Comment by caf2for4** [comment]
* 作業:投稿方法の続きを読む ガイドライン： https://trac.edgewall.org/wiki/NewTicketGuidelines
* 思っていること：英語。。

備考：

**Comment by kou** [comment]
お疲れ様でした！

**Comment by caf2for4** [comment]
In the installer, can be the check of dependence ?

When executing the "Windows installer (32-bit Python)" on the Windows7 32bit OS, the installer was successfully completed.
However , an error has occurred in the lack of dependent package at the time of project creation.

Since to resolve each problem of the dependency takes also time and effort, can be the check of dependence in the installer?

```
C:\Users\xxx>trac-admin C:\Trac\Projects\TestProject initenv
Traceback (most recent call last):
  File "C:\Python\Python27\Scripts\trac-admin-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python\Python27\lib\site-packages\pkg_resources\__init__.py", line 3084, in <module>
    @_call_aside
  File "C:\Python\Python27\lib\site-packages\pkg_resources\__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "C:\Python\Python27\lib\site-packages\pkg_resources\__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Python\Python27\lib\site-packages\pkg_resources\__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "C:\Python\Python27\lib\site-packages\pkg_resources\__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python\Python27\lib\site-packages\pkg_resources\__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Genshi>=0.6' distribution was not found and is required by Trac
```

**Comment by caf2for4** [comment]
* 作業：新規のチケット作成 https://trac.edgewall.org/newticket?type=defect
* 思っていること：英語だと失礼に当たるかとか、文面が伝わるかとかわからなくていろいろ怖い

**Comment by caf2for4** [comment]
* 作業：チケット登録 https://trac.edgewall.org/ticket/12550#ticket
* 思っていること：怖いなーと思った挙句、案外あっさり出すタイプ

備考：とりあえずこれで返事待ち。
