### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2018-06-24: yyh-gl: Rubocop: Work log

### ISSUE THREAD

**Issue by yyh-gl** [oss-gate/workshop#920]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yyh-gl** [comment]
RubocopのサイトをGithubから探す

**Comment by yyh-gl** [comment]
Githubで「rubocop」検索

**Comment by yyh-gl** [comment]
スターの数が一番多いものをrubocopと思って開いた

**Comment by yyh-gl** [comment]
ロボコップ？のロゴが出てきたので正解かな

**Comment by yyh-gl** [comment]
サイト内検索で「liscence」を検索してライセンスを調べる

**Comment by yyh-gl** [comment]
https://opensource.org/licenses/alphabetical
でMITライセンスがあるか調べる→あった

**Comment by onk** [comment]
サポーターの @onk です。よろしくお願いします！

**Comment by yyh-gl** [comment]
https://github.com/rubocop-hq/rubocop
で動かし方を調べていく

**Comment by yyh-gl** [comment]
全部英語だけど
https://github.com/rubocop-hq/rubocop#installation
わかりやすそうなドキュメント

gemインストールから

**Comment by yyh-gl** [comment]
コード評価してくれるOSSなので
まずRubyの適当なコード作る

**Comment by yyh-gl** [comment]
`sample.rb` 作成
Bundleでやりたいので  `Gemfile`（中身↓）も作成
```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop', require: false
```

**Comment by yyh-gl** [comment]
`gem 'rubocop', require: false`
`require: false` ってなんだろう

**Comment by yyh-gl** [comment]
「ruby bundle require: false」で調べる

**Comment by yyh-gl** [comment]
検索画面上位に質問サイトの記事
質問サイトだったので、すぐに閉じたが、サポーターさんが答え載っていると教えてくださったので、再度見る

Gemfileで`require: false`することで、アプリ内で勝手にrequireされなくなる。
Rubocopは常に使いたいわけではなく、使いたいときにrequireしたいだけなので、
`require: false`

**Comment by yyh-gl** [comment]
https://github.com/rubocop-hq/rubocop#quickstart
クイックスタート
```
$ cd my/cool/ruby/project
$ rubocop
```

**Comment by yyh-gl** [comment]
`cd my/cool/ruby/project`
`bundle install`
`rubocop `

**Comment by yyh-gl** [comment]
↑を順に実行

**Comment by yyh-gl** [comment]
`rubocop` 実行結果↓

```
Inspecting 2 files
.C

Offenses:

Gemfile:3:8: C: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
source "https://rubygems.org"
       ^^^^^^^^^^^^^^^^^^^^^^
Gemfile:5:21: C: Layout/SpaceInsideBlockBraces: Space between { and | missing.
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
                    ^^

2 files inspected, 2 offenses detected
```

読み方がよくわからない

**Comment by yyh-gl** [comment]
けど、動いたっぽい

**Comment by yyh-gl** [comment]
offenses 違反あり！
直してみる

**Comment by yyh-gl** [comment]
Gemfile内の
`source "https://rubygems.org"`
を
`source 'https://rubygems.org'`
に直したら

```
$ rubocop
Inspecting 2 files
.C

Offenses:

Gemfile:5:21: C: Layout/SpaceInsideBlockBraces: Space between { and | missing.
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
                    ^^

2 files inspected, 1 offense detected
```

**Comment by yyh-gl** [comment]
`git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }` を
`git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }` に直したら

```
$ rubocop
Inspecting 2 files
..

2 files inspected, no offenses detected
```
全部クリア！

**Comment by yyh-gl** [comment]
`bundle exec` をつければ `bundler` でインストールしたGemを実行できる
単純に`rubocop`だとシステムにインストールしてるやつが動作するので、動作が変わる可能性あり。気をつけないといけない。

**Comment by yyh-gl** [comment]
`gem list` の結果 `rubocop (0.57.2, 0.54.0)`
`bundle list`の結果 `rubocop (0.57.2)
でバージョンいっしょだったので
```
$ bundle exec rubocop
Inspecting 2 files
..

2 files inspected, no offenses detected
```
結果も同じ

**Comment by yyh-gl** [comment]
https://github.com/rubocop-hq/rubocop#official-manual
オフィシャルマニュアルを見て動かしてみる

**Comment by yyh-gl** [comment]
http://docs.rubocop.org/en/latest/basic_usage/
「Basic」とあるので、とりあえず見てみる

**Comment by yyh-gl** [comment]
`$ bundle exec rubocop -a`
を使えば自動でおかしいところを修正してくれる

**Comment by yyh-gl** [comment]
ルール的なのはどこで決めるんだろう

**Comment by yyh-gl** [comment]
「rubocpo ルール」検索
https://blog.onk.ninja/2015/10/27/rubocop-getting-started
@onk さん出てきた！

**Comment by yyh-gl** [comment]
`config/default.yml`
これはrailsの話かな？

**Comment by yyh-gl** [comment]
公式サイトの検索欄で`default.yml`を調べる
http://docs.rubocop.org/en/latest/search.html?q=default.yml

**Comment by yyh-gl** [comment]
gem内にもconfigがあるらしい

**Comment by yyh-gl** [comment]
`gem config` と調べても出ない

**Comment by yyh-gl** [comment]
gem内のconfigにある`default.yml`がデフォルトのルール

**Comment by yyh-gl** [comment]
http://docs.rubocop.org/en/latest/configuration/

`inherit_from: ../.rubocop.yml`

↑こうかいてあったので、`.rubocop.yml` を探していたがだ、
プロジェクト内に`.rubocop.yml`自作するだけでオリジナルのルールを作れる

**Comment by yyh-gl** [comment]
`.rubocop.yml`を変更したら
```
Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 10
```
1行を許容lengthが変更された

**Comment by yyh-gl** [comment]
chacheに関するページがあるけどどこで使っているんだろう

**Comment by yyh-gl** [comment]
トップに書いてあった
```
Large projects containing hundreds or even thousands of files can take a really long time to inspect, but RuboCop has functionality to mitigate this problem. There's a caching mechanism that stores information about offenses found in inspected files.
```

時短

**Comment by yyh-gl** [comment]
マニュアルを上から読んでいってみる
次は Extensions

**Comment by yyh-gl** [comment]
rubocop-rspec - RSpec-specific analysis
こんなのもあるのか
https://github.com/rubocop-hq/rubocop-rspec

**Comment by yyh-gl** [comment]
ミニ振り返り

https://github.com/oss-gate/workshop/issues/920#issuecomment-399728855

どういったルールがあるかも分からない状況だと、
試してみるときにどういったサンプルプログラムを作ればいいのか分からないから
サンプルプログラムがあったら嬉しい

**Comment by yyh-gl** [comment]
ミニ振り返り

https://github.com/oss-gate/workshop/issues/920#issuecomment-399729343

bundler知らない人に不親切

**Comment by yyh-gl** [comment]
RubocopはRuby初心者がRubyの一般的なコーディング規約を学ぶのにも適していると思った。
しかし、現状のRubocopインストール手順は初心者にとっては少し不親切なところがある。
・Bundlerに関する記述
・レポートの見方
・サンプルプログラムがない（こういったコードはこの規約に引っかかるといったことが分からない）

**Comment by yyh-gl** [comment]
初心者が設定ファイルを見ても、どれについての設定なのか分かりづらい。
サンプルプログラムがあれば、どういったコーディングスタイルが好まれないのかが分かりやすくなるので理解も助けられたと思うので、サンプルが欲しい。

**Comment by onk** [comment]
rubocop、今ではほとんどの cop にサンプルが揃っているんです。
例えば `Style/StringLiterals` cop についてはココにあります。
http://www.rubocop.org/en/latest/cops_style/#stylestringliterals

なので rubocop の出力結果から、このサンプルに辿り着けなかったのが悪いのではと思いました。

もしくはコーディングスタイルの方へのリンクがあれば良かったのでは、ということで、
デフォルトで `--display-style-guid` のオプションが有効になっていれば、という提案は有用そうです。

**Comment by yyh-gl** [comment]
RubocopはRuby初心者がRubyの一般的なコーディング規約を学ぶのにも適していると思った。
私が初めてRubocopを触ったとき、
[installation](https://github.com/rubocop-hq/rubocop#installation)から始め、
[Quickstart](https://github.com/rubocop-hq/rubocop#quickstart)をやった。
しかし、`$ bundle exec rubocop` を実行したとき、出てきたレポートの見方が分からず、どこが良くないコードなのか全く検討がつかなかった。
[公式サイト](http://docs.rubocop.org/en/latest/basic_usage/)を参照したが、そこでもレポートの見方を見つけることができなかった。
なので、現状のRubocopドキュメントには下記のように、初心者にとって少し不親切なところがあると感じた。
・レポートの見方（初心者にもわかるような説明）
```
特に `.C` の見方が分からない。
$ bundle exec rubocop --no-display-cop-names
Inspecting 2 files
.C
```
・サンプルプログラムがない（こういったコードはこの規約に引っかかるから、こうすればいいよというのを見たい）
（・Bundleコマンドに関する記述）

**Comment by yyh-gl** [comment]
なので、
・初心者にも分かるようなレポートの見方を説明するページ
・サンプルプログラムへの導線を明確にする
がほしいと思った。

**Comment by yyh-gl** [comment]
https://github.com/rubocop-hq/rubocop/issues/6045

英語にするの大変

**Comment by yyh-gl** [comment]
rubocop-hq/rubocop#6045

issue上げ終わりました！

**Comment by yyh-gl** [comment]
プルリク完了
CIが動く👷

**Comment by masayuki14** [comment]
お疲れ様でした。詳しくていいIssueですし、反応ありますね。
Closeしますが https://gitter.im/oss-gate/devel で相談もできるのでOSS開発を継続していきましょう！
