### ISSUE TITLE
OSS Gate Workshop: Kyoto: 2018-06-24: ichihara-3: digdag: Work log

### ISSUE THREAD

**Issue by ichihara-3** [oss-gate/workshop#921]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kyamaguchi81** [comment]
New Issue作成おめでとうございます:tada:
よろしくおねがいします:smile:

**Comment by ichihara-3** [comment]
よろしくお願いします！

**Comment by ichihara-3** [comment]
ライセンス探すときにgithubはみつけた

https://github.com/treasure-data/digdag/blob/master/LICENSE

**Comment by ichihara-3** [comment]
readmeを見る

https://github.com/treasure-data/digdag

**Comment by ichihara-3** [comment]
日本語がほしい

**Comment by ichihara-3** [comment]
```
Documentation
Please check digdag.io for installation & user manual.
```
ドキュメントがあるらしい
https://www.digdag.io/

**Comment by ichihara-3** [comment]
しっかりしてそう

使い方はどこだろう

**Comment by ichihara-3** [comment]
install はどこだろう

トップページinstallで検索->ない
downloadはある

**Comment by ichihara-3** [comment]
アドバイス: README メインで進めたほうがよいのでは

ー＞ READMWにはdigdag.ioを見ろと書いてある

READMEで完結できないんだ

**Comment by ichihara-3** [comment]
いったんREADMEを読んで見る

Developmentの項目

**Comment by ichihara-3** [comment]
nodebrew , homebrewのやり方しか書いてない @ requirements

Windows勢涙目

**Comment by ichihara-3** [comment]
linuxも書いてない

りんご用のみ

**Comment by ichihara-3** [comment]
Windows版での入れ方を探って、PullRequestをつくることを目標にしてみる

**Comment by ichihara-3** [comment]
digdagの開発用のrequirementsっぽい

どちらにせよ、maxでしか貢献できない感じになってる

**Comment by ichihara-3** [comment]
```
Prerequirements
JDK 8
Node.js 8.x
Installing Node.js using nodebrew:

$ curl -L git.io/nodebrew | perl - setup
$ echo 'export PATH=$HOME/.nodebrew/current/bin:$PATH' >> ~/.bashrc
$ source ~/.bashrc
$ nodebrew install-binary v8.x
$ nodebrew use v8.x
Installing Node.js using Homebrew on Mac OS X:

$ brew install node
Python 3
sphinx
sphinx_rtd_theme
recommonmark
```

必要なもの
JDK8
Node.js 8.x
Python 3
sphinx
sphinx_rtd_theme
でよい?

**Comment by ichihara-3** [comment]
まずjdk

入れたような入れてないような
「jdk インストール　確認 windows」で確認する

**Comment by ichihara-3** [comment]
https://java.com/ja/download/help/version_manual.xml

**Comment by ichihara-3** [comment]
![image](https://user-images.githubusercontent.com/23014016/41816124-91dc2c4c-77b7-11e8-98c9-e05e8872831d.png)

**Comment by ichihara-3** [comment]
![image](https://user-images.githubusercontent.com/23014016/41816128-b5f1446e-77b7-11e8-8379-a09e4b962ce4.png)

**Comment by ichihara-3** [comment]
jdkじゃなくてjreかも

**Comment by ichihara-3** [comment]
一回落としてきてしまうほうが早そう

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by ichihara-3** [comment]
jdk-8u171-windows-x64.exe　落としてきた
インストールする

**Comment by ichihara-3** [comment]
node.jsの入れ方調べた
https://nodejs.org/ja/

**Comment by ichihara-3** [comment]
node.jsはトップページから入れられて便利

ダウンロードする
node-v8.11.3-x64.msi

**Comment by ichihara-3** [comment]
インストーラを実行: node-v8.11.3-x64.msi

**Comment by ichihara-3** [comment]
待っている間にpythonのバージョン見た
python --version
Python 3.5.2

**Comment by ichihara-3** [comment]
sphinx
sphinx_rtd_theme
recommonmark
はたぶんすべてpythonのライブラリ。

pip3で入れればいいと思うが不親切
バージョンも書いてない

**Comment by ichihara-3** [comment]
```
> pip3 install sphinx
```

**Comment by ichihara-3** [comment]
へいこうでやってたjavaとnode.jsのインストール終わった

**Comment by ichihara-3** [comment]
cloneする
(git bash使う)
```
$ git clone https://github.com/treasure-data/digdag.git
Cloning into 'digdag'...
remote: Counting objects: 194958, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 194958 (delta 46), reused 75 (delta 33), pack-reused 194857
Receiving objects: 100% (194958/194958), 54.52 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (161362/161362), done.
Checking out files: 100% (1245/1245), done.
```

**Comment by ichihara-3** [comment]
Mac 用として考えても、JDKとかPython3の入れ方は書いてない
せめて公式へのリンクがあればやりやすくなるのに

**Comment by ichihara-3** [comment]
次やることがわからないのでとりあえずtestってやってみる
たぶん入ったことのテストになるのでは

**Comment by ichihara-3** [comment]
gradlewというファイルの中身見たらシェルだった
https://github.com/treasure-data/digdag/blob/master/gradlew

Windowsだと基本動かない

**Comment by ichihara-3** [comment]
gradlew.bat がある　これ使えばWindowsでもできるのでは？

https://github.com/treasure-data/digdag/blob/master/gradlew.bat

**Comment by ichihara-3** [comment]
ちょっとやってみる

```
>cd digdag
>.\gradlew.bat
Downloading https://services.gradle.org/distributions/gradle-4.8-bin.zip
........................................................................
```
なんかダウンロード始めた ...!

**Comment by ichihara-3** [comment]
gradle daemonなるものがうごきはじめた
誰だお前
https://www.google.co.jp/search?q=gradle&oq=gradle+&aqs=chrome..69i57j69i60l2j0l3.3239j0j7&sourceid=chrome&ie=UTF-8

**Comment by ichihara-3** [comment]
https://gradle.org/

ビルドツールらしい

**Comment by ichihara-3** [comment]
ツール自体はちゃんと動いていそう
ドキュメントが追いついてないのかな

**Comment by ichihara-3** [comment]
引数無しで走らせたのに気づいた

結果出てる
```
Welcome to Gradle 4.8.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 5m 29s
1 actionable task: 1 executed
```

ドキュメント
> ./gradlew check
やったこと
> .\gradlew.bat check
先にビルドしちゃったか

**Comment by ichihara-3** [comment]
www.digdag.io/じゃなくてhttp://docs.digdag.io/　にGet Started書いてあった

http://docs.digdag.io/getting_started.html
直リンしてほしい

**Comment by ichihara-3** [comment]
on Windowsって書いてあった
http://docs.digdag.io/getting_started.html#on-windows

**Comment by ichihara-3** [comment]
## フィードバックしたいこと
* Windowsでのインストール方法を探したけど、しばらく見つけられなかった
* http://docs.digdag.io/getting_started.html#on-windows でやっとみつけた
* READMEにgetting started へのリンクを書くとよいのでは

**Comment by ichihara-3** [comment]
CONTRIBUTE.md の類がなさそう

他のissueをみてみよう
https://github.com/treasure-data/digdag/issues

**Comment by ichihara-3** [comment]
特にフォーマットはなさそう

英語で文章かければ行けるのでは

**Comment by ichihara-3** [comment]
英語考える

title:  How about add a link to docs.digdag.io to  README
description:

I tried to search the way installing digdag on Windows10 around https://github.com/treasure-data/digdag and could not find the way for a while.
I think that the link to www.digdag.io in https://github.com/treasure-data/digdag#Documentation is ambiguous if you are beginner and you want to install digdag first time.
To link docs.digdag.io directly will make the instruction more clear.

**Comment by masayuki14** [comment]
おめでとうございます！

**Comment by ichihara-3** [comment]
PullRequest作成してみる
forkしてclone https://github.com/ichihara-3/digdag

**Comment by ichihara-3** [comment]
https://github.com/treasure-data/digdag/pull/812

初 oss Pull Request

**Comment by ichihara-3** [comment]
アドバイスしてもらったこと

git remote に fork と もとのリポジトリを両方足すと良い
作法がいろいろあるが、
fork: origin
original: upstream にした
```
$ git remote add upstream https://github.com/treasure-data/digdag.git
$ git remote -v
origin  git@github.com:ichihara-3/digdag.git (fetch)
origin  git@github.com:ichihara-3/digdag.git (push)
upstream        https://github.com/treasure-data/digdag.git (fetch)
upstream        https://github.com/treasure-data/digdag.git (push)
```
* Pull Requestのタイトルやcommit メッセージには. つけないという作法がある
* Commitメッセージ一行目がタイトル、三行め以降が詳細説明
* Pull Requestに fix #{issueの番号}とすると紐づけて自動でcloseしてくれるようになる

**Comment by onk** [comment]
> Commitメッセージ

* 1行目に概要、2行目が空行、3行目以降に詳細を書くこと
* 大文字で初めてピリオドを含まないこと

等のお作法があるので、この辺をチラッと読んでおくと良いです。
https://chris.beams.io/posts/git-commit/

> Issue と紐付けるときのキーワード

GitHub の機能で、こんな感じ。 https://help.github.com/articles/closing-issues-using-keywords/

**Comment by ichihara-3** [comment]
CI動いてる
commitメッセージで \[ci skip\]と書いておくとスキップしてくれるとのこと
ドキュメント変更だけなのでスキップしても良かった。
知らなかった！

**Comment by hiroyuki-sato** [comment]
こんにちは、(コミッターではありませんが)DigdagへのPRありがとうございます。

* Digdagを使うだけなら、以下のコマンドで大丈夫だと思います。nodejsとかはインストール不要です。
* 開発環境を整えたいのであれば、WindowsよりはLinuxやMacの方がよいかもしれません。(Windowsで開発している人は少ないと思います。)
* オフィシャルな日本語リソースはありませんが、日本語関連の情報はこちらが参考になると思います。[ワークフローエンジンDigdagのまとめ](https://qiita.com/hiroysato/items/d0fe5e2d88c267413a82) (OSS Gateの趣旨とは外れますが今後Digdagを使う場合にご参照ください)

```
PowerShell -Command "& {Invoke-WebRequest https://dl.digdag.io/digdag-latest -OutFile digdag.bat}"
```

**Comment by ichihara-3** [comment]
@hiroyuki-sato 

こんにちは。PullRequestにコメントいただいた上、こちらにまでコメント頂きありがとうございます。

> Digdagを使うだけなら、以下のコマンドで大丈夫だと思います。nodejsとかはインストール不要です。

薄々そうかなと感じていましたが、やはりそうですよね。

> 開発環境を整えたいのであれば、WindowsよりはLinuxやMacの方がよいかもしれません。(Windowsで開発している人は少ないと思います。)

Windowsで開発している方は少ないのですね。私も普段はLinux メインでやっているのですが、Windowsでもできるのではと挑戦してみました。もう少しいじってみようと思います。

> 日本語関連の情報

ありがとうございます。是非参考にさせていただきます。

**Comment by ichihara-3** [comment]
修正してもらったのがマージされた！

doneなのでcloseします

**Comment by kyamaguchi81** [comment]
おめでとうございます〜:tada:

**Comment by masayuki14** [comment]
お疲れ様でした。PullRequestもマージされて素晴らしいですね！
https://gitter.im/oss-gate/devel で相談もできるので今後もOSS開発を継続していきましょう！
京都のOSS Gateメンバーも募集してますので、興味があれば是非参加してください。
https://github.com/oss-gate/members
