### ISSUE TITLE
OSS Gate Workshop: Kyoto : 2018-06-24: suehiro: LiVES: Work log

### ISSUE THREAD

**Issue by tsuehiro** [oss-gate/workshop#922]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Rei-HAYASHI** [comment]
サポーターの林です。宜しくお願いします！

**Comment by tsueihro** [comment]
末廣です
よろしくお願いします！

**Comment by tsueihro** [comment]
公式サイトは
http://lives-video.com/
ダウンロードのリンクから
http://lives-video.com/index.php?do=downloads#binaries
をダウンロードする。

**Comment by tsueihro** [comment]
事前にubuntuのソフトウェアマネージャからインストールをしてしまっていたので、最新と表示された。
ソフトウェアマネージャから削除をする。

**Comment by tsueihro** [comment]
実行結果
sudo apt install lives
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
提案パッケージ:
  libdv-bin mjpegtools
以下のパッケージが新たにインストールされます:
  lives
アップグレード: 0 個、新規インストール: 1 個、削除: 0 個、保留: 2 個。
916 kB 中 0 B のアーカイブを取得する必要があります。
この操作後に追加で 2,504 kB のディスク容量が消費されます。
以前に未選択のパッケージ lives を選択しています。
(データベースを読み込んでいます ... 現在 166661 個のファイルとディレクトリがインストールされています。)
.../lives_2.8.7-1_amd64.deb を展開する準備をしています ...
lives (2.8.7-1) を展開しています...
mime-support (3.60ubuntu1) のトリガを処理しています ...
desktop-file-utils (0.23-1ubuntu3.18.04.1) のトリガを処理しています ...
lives (2.8.7-1) を設定しています ...
man-db (2.8.3-2) のトリガを処理しています ...
gnome-menus (3.13.3-11ubuntu1) のトリガを処理しています ...
インストールされたようである。

**Comment by tsueihro** [comment]
初回起動でワーキングディレクトリの指定
/home/osc/livesprojects

**Comment by tsueihro** [comment]
上記操作の後、添付の画像のようになった。
![screenshot from 2018-06-24 14-02-13](https://user-images.githubusercontent.com/40378695/41816115-5b7d6aee-77b7-11e8-8deb-a5bab9fe3c48.png)

**Comment by tsueihro** [comment]
選択肢がわからないので、一旦キャンセルをしてみる。

**Comment by tsueihro** [comment]
元のワーキングディレクトリ指定画面に戻った。
よくある、ディレクトリがないけど作成する？　の確認だろうか。
引き続き、次へを押して、OKを押してみる。

**Comment by tsueihro** [comment]
環境チェック後の画面
mplayerを新しくしたほうが良いらしい...。
![screenshot from 2018-06-24 14-05-34](https://user-images.githubusercontent.com/40378695/41816134-c7985806-77b7-11e8-9f03-6d06f18aa6bb.png)

**Comment by tsueihro** [comment]
キャンセルを押して、mplayerを探す。
apt search mplayer

mplayer/bionic,now 2:1.3.0-7build2 amd64 [インストール済み、自動]
  movie player for Unix-like systems

これが古いと思われる。

**Comment by tsueihro** [comment]
sudo apt upgrade mplayer
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
mplayer はすでに最新バージョン (2:1.3.0-7build2) です。
mplayer は手動でインストールしたと設定されました。
アップグレードパッケージを検出しています... 完了
以下のパッケージはアップグレードされます:
  gnome-initial-setup im-config
アップグレード: 2 個、新規インストール: 0 個、削除: 0 個、保留: 0 個。
1,367 kB 中 0 B のアーカイブを取得する必要があります。
この操作後に追加で 4,096 B のディスク容量が消費されます。
続行しますか? [Y/n] y
(データベースを読み込んでいます ... 現在 166670 個のファイルとディレクトリがインストールされています。)
.../gnome-initial-setup_3.28.0-2ubuntu6.16.04.1_amd64.deb を展開する準備をしています ...
gnome-initial-setup (3.28.0-2ubuntu6.16.04.1) で (3.28.0-2ubuntu6 に) 上書き展開しています ...
.../im-config_0.34-1ubuntu1.2_all.deb を展開する準備をしています ...
im-config (0.34-1ubuntu1.2) で (0.34-1ubuntu1 に) 上書き展開しています ...
im-config (0.34-1ubuntu1.2) を設定しています ...
mime-support (3.60ubuntu1) のトリガを処理しています ...
desktop-file-utils (0.23-1ubuntu3.18.04.1) のトリガを処理しています ...
gnome-initial-setup (3.28.0-2ubuntu6.16.04.1) を設定しています ...
man-db (2.8.3-2) のトリガを処理しています ...
gnome-menus (3.13.3-11ubuntu1) のトリガを処理しています ...

更新された。

**Comment by tsueihro** [comment]
再度キャンセルを押して、環境チェック、、、と思ったのだが、キャンセルを押したらLiVESが終了した。
再度起動する。

**Comment by tsueihro** [comment]
再度起動したが、
https://github.com/oss-gate/workshop/issues/922#issuecomment-399729759
と同じ状態になった。
諦めて次へを押してみる。

**Comment by tsueihro** [comment]
音声入力先の選択で、
![screenshot from 2018-06-24 14-14-23](https://user-images.githubusercontent.com/40378695/41816172-f1ca63ca-77b8-11e8-9f45-d1c605c9304a.png)
と表示され、表示の通り、おすすめのPulseAudioを選んでみる。

**Comment by tsueihro** [comment]
このとき、私の端末では横幅が狭く、画面表示はキャンセルの「キャ」までしか表示されなかった。(改善点)

**Comment by tsueihro** [comment]
・クリップモードで起動
・マルチトラックモードで起動
で、マルチトラックモードを選び、完了を押したら、次のようなダイアログが出力された。
![screenshot from 2018-06-24 14-18-14](https://user-images.githubusercontent.com/40378695/41816195-7368f52c-77b9-11e8-81b0-206c26e21603.png)

**Comment by tsueihro** [comment]
OKしか押せないので、OKを押す。

**Comment by tsueihro** [comment]
LiVES(2.8.7)が起動したようである。

**Comment by tsueihro** [comment]
・VJ
・リアルタイムエフェクトマップ
から、Ctrl+1のキー割り当てを行う。
・「デフォルトのキーマップとして保存」をクリックすると、下記のような画面になった。
![screenshot from 2018-06-24 14-26-03](https://user-images.githubusercontent.com/40378695/41816246-d2abbfdc-77ba-11e8-8e76-15978841a988.png)

**Comment by tsueihro** [comment]
主にCtrl+数字キーでエフェクトを切り替えることができた。
Ctrl+0がエフェクトOFFになるようである。
このソフトを初めてきちんと実行できて嬉しい！(以前試行したときはうまく動作させられなかった)

**Comment by tsueihro** [comment]
・クリップ
から動画を変更し、正しく複数の動画の切り替えができた。

**Comment by tsueihro** [comment]
マルチトラックモードに変更をしてみる。
・編集
・マルチトラックモード
設定ダイアログが出るが、一旦デフォルトの設定のままOKを押してみる。

**Comment by tsueihro** [comment]
やはり、私の端末では画面のサイズが足りない。
![screenshot from 2018-06-24 14-41-10](https://user-images.githubusercontent.com/40378695/41816308-b2991f44-77bc-11e8-850c-d3b79cb49ab5.png)

**Comment by tsueihro** [comment]
・ツール
・外部ウィンドウのキャプチャ
にて、別ウィンドウの動画を扱えるようである。
これで、別の画面に表示している（中継などの）動画を表示することができそうだ。
![screenshot from 2018-06-24 14-41-10](https://user-images.githubusercontent.com/40378695/41816319-1b571c70-77bd-11e8-8d2a-cd1ec86da270.png)

**Comment by tsueihro** [comment]
下記に報告をした。
https://sourceforge.net/p/lives/discussion/217604/thread/f2788312/

**Comment by tsueihro** [comment]
昨日はありがとうございました！
更に、コメントを頂いていたので、引き続き対応をしたいと思います！

**Comment by masayuki14** [comment]
お疲れ様でした。報告にコメントついてますね。
なにかあれば https://gitter.im/oss-gate/devel で相談もできるの、今後も是非継続していきましょう。

京都のOSS Gateメンバーも募集してますので、興味があれば是非参加してください。
https://github.com/oss-gate/members

Closeしますが引き続き作業メモとしてここを使っても大丈夫です！
