### ISSUE TITLE
OSS Gate Workshop: ${KYOTO}: 2018-06-24:Swinch : tensorflow: Work log

### ISSUE THREAD

**Issue by Swinch** [oss-gate/workshop#923]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Swinch** [comment]
Dockerでインストールしてみる
docker run -it -p 8888:8888 tensorflow/tensorflow

**Comment by 21ma** [comment]
サポーターの西村です。よろしくお願いします！

**Comment by Swinch** [comment]
Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f7bc9640cbb14f8706fc26e83eb706fe4e6a60cda481a2f1
で止まっているように感じたけど、Dockerプロセスは既に動いていた。
読めば分かるが少し手間取った。。。

**Comment by Swinch** [comment]
英語で表記しているので読むのに時間がかかりそう。。。

**Comment by Swinch** [comment]
コマンドで動作確認するために、一度Dockerを止めてBashで再実行してみる。

docker run -it tensorflow/tensorflow bash

**Comment by 21ma** [comment]
実際に入力したコマンドの記録があるのはいいですね！

**Comment by Swinch** [comment]
OSに入った後にTensorFlowを実行する。
$ python

# Python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

実行結果
Hello, TensorFlow!

**Comment by Swinch** [comment]
実行環境は整ったので、次にチュートリアルを探す。
https://www.tensorflow.org/get_started/

**Comment by Swinch** [comment]
TensorFlow Linear Model Tutorial 
というチュートリアルを発見。試してみる。

**Comment by Swinch** [comment]
jupyter noteでINの内容を変更して、OUTの値が変わるか試してみる。
http://localhost:8888/notebooks/1_hello_tensorflow.ipynb

input1 = tf.constant([1.0, 1.0, 1.0, 1.0])
↓
input1 = tf.constant([2.0, 1.0, 1.0, 1.0])

result:  [3. 3. 3. 3.]
↓
result:  [4. 3. 3. 3.]

実行結果が変わったことを確認できたが、以下のエラーメッセージが表示された。
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

**Comment by Swinch** [comment]
先程のコードを再度実行してみた所エラーは消えた。
特に値を変更していないので原因はわからない。

**Comment by Swinch** [comment]
Dockerでインストールした時に参考にしたURL
https://www.tensorflow.org/install/install_mac#installing_with_docker

**Comment by Swinch** [comment]
TensorFlow公式サイトの以下URLでインストールを行った。
https://www.tensorflow.org/install/install_mac#installing_with_docker

その後、チュートリアルページでコードをダウンロードしようとした時に、
インストールしたDockerイメージにGitがインストールされておらず、
どうやってコードをDockerイメージに引き込むか方法がわからなかった。
https://www.tensorflow.org/tutorials/wide

**Comment by Swinch** [comment]
TensorFlow公式サイトの以下URLでインストールを行った。
https://www.tensorflow.org/install/install_mac#installing_with_docker

その後、チュートリアルページでコードをダウンロードしようとした時に、
インストールしたDockerイメージにGitがインストールされておらず、
どうやってコードをDockerイメージに引き込むか方法がわからなかった。
チュートリアルのURL
https://www.tensorflow.org/tutorials/wide

**Comment by Swinch** [comment]
他のIssueを確認したところ、
Issueのラベルに「type:docs」をつけておいたほうがよさそう。

**Comment by Swinch** [comment]
Issueの名前に「Documentetion」をつけると、相手に伝わりやすいかもしれない。

**Comment by Swinch** [comment]
Issueを作る。
タイトルと本文を作る。

**Comment by Swinch** [comment]
Dockerイメージでチュートリアルを始める時に感じたこと

**Comment by Swinch** [comment]
Dockerで実行環境を構築した環境で、チュートリアルを始めた時に困ったこと。

**Comment by Swinch** [comment]
Dockerで構築した環境で、チュートリアルを始めた時に困ったこと。

**Comment by Swinch** [comment]
実行環境
MacOS

環境のインストール方法
公式サイトに記載があった下記の内容を参考に、
docker run -it -p hostPort:containerPort TensorFlowImage

以下の内容を実行しました。
docker run -it -p 8888:8888 tensorflow/tensorflow

参考した公式のURL
https://www.tensorflow.org/install/install_mac#installing_with_docker

チュートリアルページ(https://www.tensorflow.org/tutorials/wide)で
コードをダウンロードしようとした時に、
インストールしたDockerイメージにGitがインストールされておらず、
どうやってコードをDockerイメージに引き込むか方法がわからなかった。

**Comment by masayuki14** [comment]
お疲れ様でした。途中参加ということで時間が足りなかった部分もありますが、
是非継続してIssueの作成までやってみましょう。
わからないことや不安なことがあれば、 https://gitter.im/oss-gate/devel で相談してみてください。
closeしますが、引き続きここを使っても大丈夫です！

OSS Gateメンバーも募集してますので、興味があれば是非参加してください。
https://github.com/oss-gate/members
