### ISSUE TITLE
OSS Gateワークショップ 2016-7-31: y0chan: vim: 作業ログ

### ISSUE THREAD

**Issue by y0chan** [oss-gate/workshop#93]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by y0chan** [comment]
* 作業：vimはすでにインストールされているが、インストールガイドを見てみる。
* 思っていること：.vimrcいじくってたら何かうまくいかないことがあったような。。。。。。

**Comment by y0chan** [comment]
* 作業：多分見つけた。http://www.vim.org/docs.php
* 思っていること：とりあえずインストールしてみる。ドキュメント通りに。

**Comment by y0chan** [comment]
* 作業：上のURLのダウンロードを踏んだ。Cocoa (MacVim)　ってがあるらしい。
* 思っていること：Cocoa (MacVim)をググってみます。

**Comment by y0chan** [comment]
* 作業：Cocoa (MacVim)ってのは普段使っているターミナルのvimではないらしい
http://blog.objc.jp/?p=1601
* 思っていること：vimだけどこれをつかったことないから、これをインストールしてみよう。これのgithubはこのurl
https://github.com/macvim-dev/macvim

**Comment by y0chan** [comment]
* 作業：さきのgithubの一番したに
- MacVim homepage http://macvim-dev.github.io/macvim
- Vim README https://github.com/macvim-dev/macvim/blob/master/README_vim.m
を発見。
 * 思っていること：まずはgithubじゃないのを読んで見る

**Comment by y0chan** [comment]
* 作業：読んでみたが、結局githubを読むことになる。リンクが全部githubだった。
* 思っていること：githubのどこ読めばよいだろう。

**Comment by y0chan** [comment]
* 作業：macのインスコだったらこのドキュメンとかな？https://github.com/macvim-dev/macvim/blob/master/READMEdir/README_mac.txt
* 思っていること：読んで実際にインストールしてみよう。

**Comment by y0chan** [comment]
* 作業：ちょっと詰まる。https://github.com/macvim-dev/macvim/blob/master/READMEdir/README_mac.txt　を読んでいる
* 思っていること：ドキュメントに書かれているHow to build and installを実行する前に上に書かれている
you just drag the app bundle into the directory you wish to
install in (usually `/Applications').
をやるのかな？

**Comment by y0chan** [comment]
* 作業：とりあえず先ほどのドキュメンを引き続き読んでいる。
* 思っていること：ドキュメンがわかりにくい。。。。How to build and installのとローカルにもっていったあとの手順は詳細に書かれているけど、初心者の私にはその前のthe usual configure/make steps to buildのやり方を詳細に同じドキュメントに書いていただけるとありがたい。github界では常識なのだろうか。。。

**Comment by y0chan** [comment]
* 作業：とりあえずローカルの/Users/y0/Applicationsでgit clone https://github.com/macvim-dev/macvim.gitをやってみましたら、ディレクトリがインスコできました。urlは右上のclone or downloadを押したら出てきた。
* 思っていること：この方法で正しいかな？ただしかったら。上のコマンドをドキュメントに書きたい。How to build and installをやってみます。

**Comment by y0chan** [comment]
* 作業：ドキュメント通りに./configure --helpやってみました。
* 思っていること：やってみましたが結局どれをつければいーのやら。

**Comment by y0chan** [comment]
* 作業：他のメンターの方と午前の振り返りをしました。
* 思っていること：ドキュメントがやはりわかりづらいこと。少し玄人向けなこと。これを改善する要望を出すのがよいかもしれない。

**Comment by y0chan** [comment]
* 作業：とりあえずドキュメントにあるフラッグをいれないで、./configureしてみた。

結果
略
xcodebuild -project MacVim/MacVim.xcodeproj MACOSX_DEPLOYMENT_TARGET=10.11
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [macvim] Error 1

と出た。Xcodeが入っていないことが原因みたいです。とりあえずXcodeを入れてみる。
* 思ったこと：初めてのビルドです。これでうまくいったらflagいれなくれも大丈夫ではないかと指摘できる？

**Comment by y0chan** [comment]
* 作業：App StoreからXcodeを入れてみる。
* 思ったこと: エラーをちゃんとみるのは大事。再認識。3.8GBもインストールしてごめんなさい。。。。。。。。

**Comment by y0chan** [comment]
* 作業：インストールしている間に今までのことをまとめてみる。

** テーマ
macvim/READMEdir/README_mac.txtのドキュメントのわかりにくいところの指摘
** 改善点1
MacVim uses the usual configure/make steps ~ 部分。文章だけでなく実際に実行するコマンドなどを書いてほしい。
** 改善点2
MacVim uses the usual configure/make steps ~ の文章とHow to build and installの部分。この２つの部分に関連性があるように思えてしまいます。ちゃんとこの２つは別のやり方だと区別がつくように書いて欲しい。
** 改善点3
How to build and installの一番最初にcd で場所を移動+git clone https://github.com/macvim-dev/macvim.gitをやることを書いて欲しい。」

*思ったこと：xcodeのインストールが長い。。

**Comment by y0chan** [comment]
* 作業：xcodeがインストールし終わったので、makeのリベンジ

結果
** BUILD SUCCEEDED **

となり成功。次にドキュメント通りに、open MacVim/build/Release/MacVim.appをやってみたら、下記のようなエラー。

エラー
~/A/macvim ❯❯❯ open src/MacVim/build/Release/MacVim.app
The window server could not be contacted.  open must be run with a user logged in at the console, either as that user or as root.

思ったこと：やるだけならフラグはつけないで良いのでは。とりあえずもう少しかな。

**Comment by y0chan** [comment]
* 作業：先のエラーの結果を調べると下記のblogが出た。
http://totutotu.hatenablog.com/entry/2015/07/26/tmuxでOSXのopenコマンド使えない

これ読む限り、tmuxでやるとエラーが出てしまうみたい。とりあえずtmuxをやめてただのzshでopenコマンドを叩いてみる。とうまくいった！

* 思ったこと：やはりやるだけならフラグつけなくてよいことが分かりました。tmuxは便利だから入れてみましたが、ブラックボックスになってます。ダメですね。

**Comment by y0chan** [comment]
* 作業：まとめてみる。ために、documentを読んでみる。
* 思ったこと：MacVim uses the usual configure/make steps to build the binary but instead of　〜の部分とHow to build and installを別の項目だと思っていたけど、違うみたい。同じことを説明しているみたい。

**Comment by y0chan** [comment]
* 作業：指摘したい点をまとめてみる。まずは日本語で、

** 指摘したい点1:
ドキュメントの追加

Run `./configure` in the `src/` directoryの前に、

$ cd 任意のディレクトリ
(usually `/Applications')

$ git clone https://github.com/macvim-dev/macvim.git

を追加して欲しい。

** 指摘したい点2
$ ./configure --with-features=huge \

のコマンド。フラッグをつけないでもよい。

* 思ったこと：フラグまわりがよくわからない。これが落ち着いたらいくつか試してみたい。

**Comment by y0chan** [comment]
* 作業：報告場所を探す。OSSによって報告場所は違うらしい。今回報告することろは、githubページの上にあるバーのissueでよさげ。

* 思ったこと：issueに色々投稿されている。これをパラ見すると人他の人がどんなノリで報告しているかがわかった。

**Comment by y0chan** [comment]
* 作業：issueを日本語で書いてみる。

タイトル：ドキュメント、macvim/READMEdir/README_mac.txt　への追加のお願い
内容：ドキュメントmacvim/READMEdir/README_mac.txtへ下記のコマンドを追加していただけないでしょうか。

文章　Run ./configure in the src/ directoryの前に、

cd  to working dir and

$ git clone https://github.com/macvim-dev/macvim.git

* 思いついたこと：
これでよいのだろうか。。

**Comment by kou** [comment]
お疲れ様でした！
