### ISSUE TITLE
OSS Gate Workshop: Osaka: 2018-06-30: ririkku: assertj-core: Work log

### ISSUE THREAD

**Issue by ririkku** [oss-gate/workshop#934]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by tshkh8** [comment]
よろしくおねがいします！

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by ririkku** [comment]
公式サイトのQuickStartをしてみる
http://joel-costigliola.github.io/assertj/assertj-core-quick-start.html

**Comment by ririkku** [comment]
AsserJCoreをやりたかったけど、「This guide is for the AssertJ core module. Quick start guides for other modules are here:」のGuavaを選択してやろうとしてた。これはAssertJのほかのモジュールっぽい

**Comment by ririkku** [comment]
Get AssertJ Core assertionsのgradle版をしてみる

**Comment by ririkku** [comment]
順番が前後したけど、ライセンスの確認。https://github.com/joel-costigliola/assertj-core/blob/master/licence-header.txtをみた。Apache License, Version 2.0だった。

**Comment by ririkku** [comment]
https://opensource.org/licenses/Apache-2.0

**Comment by ririkku** [comment]
build.gradleにtestCompile("org.assertj:assertj-core:3.10.0")を記載。versionはjava8以降のやつ。

**Comment by ririkku** [comment]
junitのversionは4.12

**Comment by ririkku** [comment]
2 - Add AssertJ methods static importをやる。

**Comment by ririkku** [comment]
static importを書くにはクラスが必要なので、SampleForOssGateTestクラスを作成した。

**Comment by ririkku** [comment]
Type assertThat followed by the object under test and a dot ... and any Java IDE code completion will show you all available assertions.
`assertThat(objectUnderTest). // code completion -> assertions specific to objectUnderTest`

https://translate.google.com/?hl=ja#auto/ja/Type%20assertThat%20followed%20by%20the%20object%20under%20test%20and%20a%20dot%20...%20and%20any%20Java%20IDE%20code%20completion%20will%20show%20you%20all%20available%20assertions.
によると、assertThatの後にテスト対象、続いてドットでIDEがアサーションを出してくれるよ、って書いてた。

**Comment by ririkku** [comment]
Code completion example for String assertions :
ってあるので、出してみる。

**Comment by ririkku** [comment]
IDEがCode completionの`contains`の出してくれた。
```
    @Test
    public void name() throws Exception {
        assertThat("Oss-Gate").contains("O");
    }
```

**Comment by ririkku** [comment]
依存関係を追加するときに、MavenかGradleかを意識することが無い人に取っては難しいかもしれない。
http://search.maven.org/#artifactdetails|org.assertj|assertj-core|3.10.0|bundle
ここを見ればわかるっぽいが、その気持ちがまだ理解出来ない。

**Comment by ririkku** [comment]
[AssertJ Guava assertionsのQuickStartをしてみる。](http://joel-costigliola.github.io/assertj/assertj-guava.html#quickstart)

**Comment by ririkku** [comment]
Guava assertions quickstart guide
1 - Add assertj-guava dependency to your project pom.xml
pomと書いてあるが、Mavenしか無理なのか？

**Comment by ririkku** [comment]
Gradleのやり方のリンクがあった。
[assertj-guava dependency declaration](http://search.maven.org/#artifactdetails|org.assertj|assertj-guava|3.2.0|bundle)
Gradleでやりたいので、試してみた。
`compile 'org.assertj:assertj-guava:3.2.0'`

**Comment by ririkku** [comment]
Guavaようのテストクラスを作成してみた。
SampleAssertjGuavaForOssGateTest

**Comment by ririkku** [comment]
2 - Statically import org.assertj.guava.api.Assertions.assertThat ...をやる。
Staticallyは静的という意味らしい。static importと表現しないのはなぜ何でしょう。

**Comment by ririkku** [comment]
Example :をコピペでコンパイルエラーだけど、
`import static`
'class XxxTest'
'public void test(){}'
が書いてあるとか、もう少し見やすく出来たのでは？

**Comment by ririkku** [comment]
```
import static org.assertj.guava.api.Assertions.assertThat;
import static org.assertj.guava.api.Assertions.entry;
```

```
   // Multimap assertions
        Multimap<String, String> actual = ArrayListMultimap.create();
        actual.putAll("Lakers", newArrayList("Kobe Bryant", "Magic Johnson", "Kareem Abdul Jabbar"));
        actual.putAll("Spurs", newArrayList("Tony Parker", "Tim Duncan", "Manu Ginobili"));

        assertThat(actual).containsKeys("Lakers", "Spurs");
        assertThat(actual).contains(entry("Lakers", "Kobe Bryant"), entry("Spurs", "Tim Duncan"));
```
import文を書いても、`ArrayListMultimap`がコンパイルエラーになる。Guava関係モジュールが取り込めていない可能性がある？

**Comment by ririkku** [comment]
プチ振り返りでのまとめ
CoreとGuava assertions のquickstart guideの書き口を合わせてみる？と言う話をした。(できるならHTMLを編集して投げてあげれば、向こうのコストは減るかも。)

**Comment by ririkku** [comment]
`ArrayListMultimap`がコンパイルエラーを解消するために、`compile 'com.google.guava:guava:25.1-jre'`を依存関係に入れてみる。

**Comment by ririkku** [comment]
追加したら、コンパイルエラーを解消できた。

**Comment by ririkku** [comment]
http://joel-costigliola.github.io/assertj/assertj-guava.html#quickstartのMavenしかない表記を
http://joel-costigliola.github.io/assertj/assertj-core-quick-start.htmlのGradleも記述している形に変えてみる。

**Comment by ShinjiEnoki** [comment]
いいですね。記述を分かりやすくして送ってみるのはよさそうです

**Comment by ririkku** [comment]
https://github.com/joel-costigliola/assertj

**Comment by ShinjiEnoki** [comment]
説明がありますが、意外にこのサイトの編集方法がわかりにくいですね。

**Comment by ririkku** [comment]
HTMLを編集したあと、コマンドにてHTMLを生成するようなので、
`./build-site.sh` を叩いたら

```
Build AssertJ Site ...
 
Generate assertj HTML files
-- generate ../assertj-core.html from assertj-core-template.html
-- generate ../assertj-news.html from assertj-news-template.html
-- generate ../assertj-guava.html from assertj-guava-template.html
-- generate ../assertj-assertions-generator.html from assertj-assertions-generator-template.html
-- generate ../assertj-swing-launch.html from assertj-swing-launch-template.html
-- generate ../assertj-core-conditions.html from assertj-core-conditions-template.html
-- generate ../index.html from index-template.html
-- generate ../assertj-swing-troubleshooting.html from assertj-swing-troubleshooting-template.html
-- generate ../assertj-swing-advanced.html from assertj-swing-advanced-template.html
-- generate ../assertj-core-converting-testng-assertions-to-assertj.html from assertj-core-converting-testng-assertions-to-assertj-template.html
-- generate ../assertj-db-features-highlight.html from assertj-db-features-highlight-template.html
-- generate ../assertj-swing.html from assertj-swing-template.html
-- generate ../assertj-core-migrating-from-fest.html from assertj-core-migrating-from-fest-template.html
-- generate ../assertj-db-news.html from assertj-db-news-template.html
-- generate ../assertj-swing-running.html from assertj-swing-running-template.html
-- generate ../assertj-swing-troubleshooting-screenshots.html from assertj-swing-troubleshooting-screenshots-template.html
-- generate ../assertj-neo4j.html from assertj-neo4j-template.html
-- generate ../assertj-core-features-highlight.html from assertj-core-features-highlight-template.html
-- generate ../assertj-help.html from assertj-help-template.html
-- generate ../assertj-core-quick-start.html from assertj-core-quick-start-template.html
-- generate ../assertj-core-converting-junit-assertions-to-assertj.html from assertj-core-converting-junit-assertions-to-assertj-template.html
-- generate ../assertj-swing-input.html from assertj-swing-input-template.html
-- generate ../assertj-core-custom-assertions.html from assertj-core-custom-assertions-template.html
-- generate ../assertj-assertions-generator-maven-plugin.html from assertj-assertions-generator-maven-plugin-template.html
-- generate ../assertj-swing-news.html from assertj-swing-news-template.html
-- generate ../assertj-swing-edt.html from assertj-swing-edt-template.html
-- generate ../assertj-db.html from assertj-db-template.html
-- generate ../assertj-db-concepts.html from assertj-db-concepts-template.html
-- generate ../assertj-core-news.html from assertj-core-news-template.html
-- generate ../assertj-swing-quick-start.html from assertj-swing-quick-start-template.html
-- generate ../assertj-swing-basics.html from assertj-swing-basics-template.html
-- generate ../assertj-swing-migrating.html from assertj-swing-migrating-template.html
-- generate ../assertj-swing-troubleshooting-lookups.html from assertj-swing-troubleshooting-lookups-template.html
-- generate ../assertj-joda-time.html from assertj-joda-time-template.html
-- generate ../assertj-swing-lookup.html from assertj-swing-lookup-template.html
-- generate ../assertj-swing-getting-started.html from assertj-swing-getting-started-template.html

Generating bootstrap.css ...
./generate-bootstrap-css.sh: line 4: lessc: command not found
Generating bootstrap.min.css ...
./generate-bootstrap-css.sh: line 6: lessc: command not found

Generating assertj.css ...
./generate-assertj-css.sh: line 4: lessc: command not found
Generating assertj.min.css ...
./generate-assertj-css.sh: line 6: lessc: command not found
```

`lessc: command not found` が出た。

**Comment by ShinjiEnoki** [comment]
http://joel-costigliola.github.io/assertj/assertj-help.html#assertj-build-site
にLESSファイルでスタイルを管理しているとありますね

**Comment by ririkku** [comment]
LESSと言うものを使用しているようなので、それが必要らしい。
[LESS](http://lesscss.org/) から`npm install -g less` でインストールしろと書いてあるのでインストールした。
```
/Users/kikukawaryoji/.nvm/versions/node/v8.9.3/bin/lessc -> /Users/kikukawaryoji/.nvm/versions/node/v8.9.3/lib/node_modules/less/bin/lessc
+ less@3.0.4
```

**Comment by ririkku** [comment]
`./build-site.sh` にてHTMLの生成には成功したけど、CSSがビルド出来ないので別の方法で解決する。

**Comment by ririkku** [comment]
https://github.com/joel-costigliola/assertj をフォークして、`assertj-guava-template.html` を[編集](https://github.com/ririkku/assertj/commit/fa544afb1beaac0d6794b48647843dc82011eb34)した。

**Comment by ririkku** [comment]
IntellijにてブラウザでGuavaのQuickStartを確認したら、MavenとGradleが二つ出ていた。

**Comment by ShinjiEnoki** [comment]
.DS_Storeができちゃう問題は、gitのコミットに含めないのがいいかもしれませんね。
http://matsudam.com/blog/entry/655

**Comment by ririkku** [comment]
コミットコメントを英語にするため、一旦日本語にしてみる。
assertj-guavaのquickstartドキュメントの、1 - Add assertj-guava dependency to your projectにgradle版を追加したのと、versionを指定した。

update assertj-guava-quickstart add project for gradle

**Comment by ririkku** [comment]
assertj-core-quickstartと同様にGradleの設定があった方がより見やすいよ！

As with assertj-core-quickstart it is easier to see if there is Gradle setting!

プルリクコメントを書いた

**Comment by ririkku** [comment]
[出したプルリク](https://github.com/joel-costigliola/assertj/pull/84)

**Comment by knokmki612** [comment]
おつかれさまでした！
