### ISSUE TITLE
OSS Gate Follow-up: Tokyo: 2018-07-02

### ISSUE THREAD

**Issue by knokmki612** [oss-gate/workshop#939]
ワークショップの続きをやるフォローアップというイベントの記録用issue

**Comment by swamp09** [comment]
よろしくお願いします。
今日は、出しているPRにフィードバックが来ているので、その対応をします。
https://github.com/sunspot/sunspot/pull/864

**Comment by syu-gaspard** [comment]
以下のissueについてフォローアップ参加しています。
https://github.com/oss-gate/workshop/issues/879

**Comment by yoshitaku-jp** [comment]
よろしくおねがいします

**Comment by knokmki612** [comment]
今回のビギナーの方は「もくもく会」という名前だとやっぱり来て大丈夫だろうかという思われたそうなので、「フォローアップ」という名前は大事だと話になった
