### ISSUE TITLE
OSS Gate Workshop: tokyo: 2018-09-08: mukaken: aws-cdk: Work log

### ISSUE THREAD

**Issue by mukaken** [oss-gate/workshop#944]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mukaken** [comment]
リポジトリ
https://github.com/awslabs/aws-cdk

**Comment by mukaken** [comment]
https://awslabs.github.io/aws-cdk/getting-started.html
を参考にインストールする。

npm install -g aws-cdk

**Comment by mukaken** [comment]
バージョンを確認する。

```shell
$ cdk --version
0.8.2 (build 934ca5f)
```

**Comment by mukaken** [comment]
空プロジェクトを作成する。

```
mkdir hello-cdk
cd hello-cdk
git init
npm init -y # creates package.json
```

**Comment by mukaken** [comment]
Add @aws-cdk/cdk as a Dependency

```
npm install @aws-cdk/cdk
```

**Comment by mukaken** [comment]
cdk.json を作成。

```
{
  "app": "node index.js"
}
```

**Comment by mukaken** [comment]
npm run build
で、コンパイルできてないのに、コンパイルが通ったような挙動になる。
エラーが出ない。

**Comment by mukaken** [comment]
npm run build でコンパイルできなかったのは、
以下の方法で解決できる。

https://github.com/oss-gate/workshop/issues/947#issuecomment-419614617

**Comment by haoling** [comment]
振り返りをやりました！
うまくいかなかったときのコマンドや結果なども作業メモに残すと、より良いメモになると思います！

**Comment by mukaken** [comment]
# 日本語でフィードバックを記載する

## タイトル
必要な TypeScript のバージョンを説明書に記載して下さい

## 修正してほしい内容
必要な TypeScript のバージョンを説明書に記載して欲しい。
「もしTypeScriptを使う場合は、このバージョンが必要」という項目をPrerequisites <https://awslabs.github.io/aws-cdk/getting-started.html#prerequisites> に追加してほしい。
理由は、TypeScriptを使う場合に、TypeScriptの、どのバージョンが必要か分からない。
TypeScript のバージョンが古いと、当プロジェクトのコマンドが動かない。

## エラー内容
Compile the Code <https://awslabs.github.io/aws-cdk/getting-started.html#compile-the-code> の項目の TypeScript タブで

$ npm run build

を実行すると、以下のエラーがでる。
---------------
$ npm run build

> hello-cdk@1.0.0 build /Users/XXX/oss-gate/hello-cdk
> tsc

error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-cdk@1.0.0 build: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-cdk@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXX/.npm/_logs/2018-09-08T06_10_04_986Z-debug.log
---------------

私の開発環境の TSC のバージョンは以下でした。
---------------
$ tsc --version
message TS6029: Version 1.5.3
---------------

## 解決方法
以下のコマンドで typescript をグローバルにインストールして、
tsc のバージョン 3.0.3 をインストールする。
---------------
$ npm install typescript -g
npm WARN rm not removing /usr/local/bin/tsc as it wasn't installed by /usr/local/lib/node_modules/typescript
npm WARN rm not removing /usr/local/bin/tsserver as it wasn't installed by /usr/local/lib/node_modules/typescript
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ typescript@3.0.3
updated 1 package in 2.179s
---------------

TSC のバージョンを確認する。
---------------
$ tsc -v
Version 3.0.3
---------------

コンパイルする。
---------------
$ npm run build

> hello-cdk@1.0.0 build /Users/XXX/oss-gate/hello-cdk
> tsc
---------------

コンパイルできている。
---------------
$ ls
cdk.json		index.ts		package-lock.json	tsconfig.json
index.js		node_modules		package.json
---------------

## 議論した事
* https://github.com/awslabs/aws-cdk には、TypeScriptを推薦しているわけではない。
「available for Java, JavaScript, and TypeScript.」と書かれているので、TypeScriptは一番優先度が低いかも?
* ユーザー観点で、AWSを使う人は、必ずしもTypeScriptに詳しいわけではない。
* デフォルトはJSなので、必ずTypeScript を使わなければいけないわけではない。

**Comment by tdtds** [comment]
次のワークショップが始まるのでいったんクローズしますね。
