### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-09-08: nico-hn: rurema: Work log

### ISSUE THREAD

**Issue by nico-hn** [oss-gate/workshop#946]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by haoling** [comment]
@haoling です。横にいるサポーターです。よろしくおねがいします。（本名は内緒でおねがいしますねｗ）

**Comment by nico-hn** [comment]
https://github.com/rurema/doctree/wiki/HowToJoin

https://github.com/rurema/doctree/wiki/HowToJoin#%E5%BF%85%E8%A6%81%E3%81%AA%E3%82%82%E3%81%AE
subversionlをインストール
1.8.7の最新版をインストール
「2.x.y の最新バージョンの Ruby 本体」
とあるが説明が若干曖昧？
→minor versionについては一式入れるという意味とは思うが...
2.0.0がローカルに入っていなかったので一応追加。

**Comment by nico-hn** [comment]
https://github.com/rurema/doctree/wiki/HowToJoin#%E5%8F%82%E5%8A%A0%E3%81%97%E3%81%9F%E5%BE%8C%E3%81%AE%E6%89%8B%E7%B6%9A%E3%81%8D
プロジェクト参加の手続きはいったん保留

**Comment by nico-hn** [comment]
https://github.com/rurema/doctree/wiki/HowToJoin#%E4%BD%9C%E6%A5%AD%E3%82%92%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B
1.Phase3WorkingScheme を読んで手順を覚える。
はプロジェクトのかなり初期段階の手順のようなのでいったん読み飛ばす。

**Comment by nico-hn** [comment]
BitClustの使い方
  https://github.com/rurema/doctree/wiki/BitClust
  を読む
  gem install bitclust-core bitclust-dev refe2
  https://bugs.ruby-lang.org/projects/rurema/wiki/Phase2WorkingScheme
  が参考になる、とあるがリンク切れ
→修正候補？
  doctreeから情報を取る際に使うらしいが、一端保留

**Comment by nico-hn** [comment]
https://github.com/rurema/doctree/wiki/HowToContribute
を読み始め

貢献の仕方は
https://github.com/rurema/doctree
へのpull requestでも良いとのこと。

**Comment by nico-hn** [comment]
https://github.com/rurema/doctree/wiki/Tutorial#2-%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E4%BD%9C%E6%88%90
を実行

**Comment by nico-hn** [comment]
https://github.com/rurema/doctree/wiki/Tutorial#31-github%E3%81%A7fork%E3%81%99%E3%82%8B
に従い
https://github.com/nico-hn/doctree
をフォーク

**Comment by nico-hn** [comment]
と思ったら、古いフォーク済みのレポジトリが存在？
→pull requestを投げていないタイポ修正あり
フォーク済みレポジトリはそのまま使う方向で作業
（rurema/doctreeの最新状態を取り込み）

**Comment by knokmki612** [comment]
ふりかえりました！
具体的に取り掛かる内容が出てきていて順調だと思いました！

**Comment by nico-hn** [comment]
見つかった要修正点ですが、

@param atime 最終アクセス時刻を [[c:Time]] か、起算時からの経過秒数を数値で指定します。
-@param utime 更新時刻を [[c:Time]] か、起算時からの経過秒数を数値で指定します。
+@param mtime 更新時刻を [[c:Time]] か、起算時からの経過秒数を数値で指定します。
@raise Errno::EXXX 変更に失敗した場合に発生します。

とutime→mtimeという修正のため、pull requestのコメントに何を書いていいのか迷ってしまいます。

**Comment by nico-hn** [comment]
修正箇所は
https://github.com/nico-hn/doctree/commit/b6cd76845e24b28d8441e1d450b08f465a445add
です。

**Comment by nico-hn** [comment]
いろいろアドバイスをいただいて以下の内容でpull request:

# Fix a typo about File#utime

https://github.com/rurema/doctree/blob/master/refm/api/src/_builtin/File#L651

でのmtimeに対応する

https://github.com/rurema/doctree/blob/master/refm/api/src/_builtin/File#L663

でのパラメータ名がutimeになっています。

当該のパラメータはmodification timeを表すはずですので、下がタイポではないかと思います。
以上の理由からutime→mtimeと修正しました。
(man (2) utime などとも一貫しています。)

いかがでしょうか。

**Comment by nico-hn** [comment]
準備段階で見つけたリンク先が見れない(403エラー)問題は
https://bugs.ruby-lang.org/projects/rurema/wiki/Phase2WorkingScheme
の他に
https://bugs.ruby-lang.org/projects/rurema/wiki/Phase1WorkingScheme
という関連ページもある模様。
ただし、こちらもエラー。

**Comment by nico-hn** [comment]
アーカイブを検索してみるが、見つからず。

https://web.archive.org/
https://megalodon.jp/
https://archive.is/
https://archive-it.org/

**Comment by znz** [comment]
るりまへの contribute ありがとうございます。

Phase2WorkingScheme と Phase1WorkingScheme は bugs.ruby-lang.org の管理者権限を使って一時的にアーカイブから戻してサルベージしました。

- https://github.com/rurema/doctree/wiki/Phase2WorkingScheme
- https://github.com/rurema/doctree/wiki/Phase1WorkingScheme

https://github.com/rurema/doctree/wiki/BitClust のリンクは変更しておきましたが、 Phase1WorkingScheme はどこからみつけたのでしょうか?
簡単に直せるリンクならついでに直しておきたいです。

**Comment by znz** [comment]
https://github.com/rurema/doctree/wiki/ProjectTimeLine のリンクも更新しました。

Wiki は古いままの情報も残っていて、ちゃんと整理されていないのですが、手をつける人がいないので、そのままになっているのが現状のようです。

**Comment by nico-hn** [comment]
> https://github.com/rurema/doctree/wiki/ProjectTimeLine
のリンクも更新しました。

中途半端な情報を拾って下さったこと、改めてお礼申し上げます。

 > Wiki は古いままの情報も残っていて、ちゃんと整理されていないのですが、

Wiki部分で貢献できるかは分かりませんが、るりまについては気付いた点を今後積極的に
フィードバックできればと思いますので、その際はまた宜しくお願い致します。

**Comment by tdtds** [comment]
次のワークショップが始まるのでいったんクローズしますね。
