### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-09-08: rednes: aws-cdk: Work log

### ISSUE THREAD

**Issue by rednes** [oss-gate/workshop#947]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: Tokyo: 2018-09-08: rednes: aws-cdk: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mukaken** [comment]
mukakenです。よろしくお願いします。

**Comment by rednes** [comment]
GitHubリポジトリ
https://github.com/awslabs/aws-cdk

**Comment by rednes** [comment]
これを見てインストールする
https://awslabs.github.io/aws-cdk/getting-started.html

**Comment by rednes** [comment]
インストールしてバージョン確認
```
$ npm install -g aws-cdk
$ cdk --version
0.8.2 (build 934ca5f)
```

**Comment by rednes** [comment]
`cdk-init` コマンドを使うと一発でできるらしいけど、step-by-stepで AWS CDK appを作ることにする。
普段TypeScriptつかっているんで、プログラムはTypeScriptを選択する。

**Comment by rednes** [comment]
コマンド実行して、`package.json` を作った。
```
$ mkdir hello-cdk
$ cd hello-cdk
$ git init
$ npm init -y # creates package.json
```

**Comment by rednes** [comment]
<package.json>
```
{
  "name": "hello-cdk",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by rednes** [comment]
コマンド実行して、tsconfig.jsonを作った
```
$ cat << EOF > tsconfig.json
{
    "compilerOptions": {
        "target": "es2018",
        "module": "commonjs"
    }
}
EOF
```

**Comment by rednes** [comment]
`Setup TypeScript build commands in package.json:` っていうのがよくわからなかったけど、scriptsブロックに追記して欲しそうだったのでtestの後ろに追記した。

**Comment by rednes** [comment]
<package.json>
```
{
  "name": "hello-cdk",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc",
    "watch": "tsc -w"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by rednes** [comment]
コマンドを実行して、AWS CDK core libraryをインストール。
```
$ npm install @aws-cdk/cdk @types/node
```

**Comment by rednes** [comment]
コマンドを実行して、index.tsを作成。
```
$ cat << EOF > index.ts
import cdk = require('@aws-cdk/cdk');

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);
    }
}

process.stdout.write(new MyApp(process.argv).run());
EOF
```

**Comment by rednes** [comment]
コマンドを実行して、ビルドしようとしたらエラー出た。
```
$ npm run build
sh: tsc: command not found
```

tscをグローバルインストールしてなかったので、tscをグローバルインストールする。
```
$ npm install tsc -g
```

再度ビルド実行、違うエラーが出る。
```
$ npm run build
error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
```

**Comment by rednes** [comment]
TypeScriptのバージョンを確認したところ、 `1.5.3` だった。
```
$ tsc -v
message TS6029: Version 1.5.3
```

tscのインストールが間違えてて、本当はtypescriptパッケージをグローバルインストールするべきだったのでインストールした。
```
$ npm install typescript -g
```

tscのバージョンを確認する。
```
$ tsc -v
Version 3.0.3
```

再度ビルド実行してうまくいった。
```
$ npm run build
```

**Comment by rednes** [comment]
コマンド実行して、cdk.jsonを作成。
```
$ cat << EOF > cdk.json
{
  "app": "node index.js"
}
EOF
```

**Comment by rednes** [comment]
index.tsにStackを追記した。
```
import cdk = require('@aws-cdk/cdk');

class MyStack extends cdk.Stack {
    constructor(parent: cdk.App, id: string, props?: cdk.StackProps) {
        super(parent, id, props);
    }
}

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);

        new MyStack(this, 'hello-cdk');
    }
}

process.stdout.write(new MyApp(process.argv).run());
```

**Comment by rednes** [comment]
コマンドを実行して、ビルドした。
```
$ npm run build
```

**Comment by rednes** [comment]
AWSのアクセスキー、シークレットキー、リージョンを環境変数に設定。
```
$ export AWS_ACCESS_KEY_ID=XXXX
$ export AWS_SECRET_ACCESS_KEY=XXXX
$ export AWS_DEFAULT_REGION=ap-northeast-1 
```

**Comment by rednes** [comment]
コマンドを実行してみたが、記載通りの出力にならない。
```
$ cdk ls -l
```
<< Expected >>
```
-
    name: hello-cdk
    environment:
        name: <your-account-id>/<your-default-region>
        account: '<your-account-id>'
        region: <your-default-region>
```
<< Actual >>
```
-
    name: hello-cdk
```

**Comment by rednes** [comment]
AWSのアクセスキー、シークレットキーが間違えていたので環境変数に再設定。
```
$ export AWS_ACCESS_KEY_ID=XXXX
$ export AWS_SECRET_ACCESS_KEY=XXXX
```

**Comment by rednes** [comment]
コマンドを実行して、記載通りの出力となった。
```
$ cdk ls -l
-
    name: hello-cdk
    environment:
        name: <your-account-id>/ap-northeast-1
        account: '<your-account-id>'
        region: ap-northeast-1
```

**Comment by rednes** [comment]
コマンドを実行して、パッケージをインストール。
```
$ npm install @aws-cdk/aws-s3
```

**Comment by rednes** [comment]
index.tsにS3 Bucketを追記。
```
import cdk = require('@aws-cdk/cdk');
import s3 = require('@aws-cdk/aws-s3');

class MyStack extends cdk.Stack {
    constructor(parent: cdk.App, id: string, props?: cdk.StackProps) {
        super(parent, id, props);
        
        new s3.Bucket(this, 'MyFirstBucket', {
            versioned: true
        });
    }
}

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);

        new MyStack(this, 'hello-cdk');
    }
}

process.stdout.write(new MyApp(process.argv).run());
```

**Comment by haoling** [comment]
振り返りをやりました！
見事なハマりポイントがあって、まさにフィードバックポイントだと思います。

**Comment by rednes** [comment]
【報告メモ】

https://awslabs.github.io/aws-cdk/getting-started.html

Getting Startedを参考にして、TypeScriptのAWS CDK appを作ろうとした。
`Compile the Code` セクションで、TypeScriptをビルドした時にエラーが出た。

```
$ npm run build
tsconfig.json(3,19): error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'esnext'.
```

tsconfig.jsonで、compilerOptionsのtargetをes2018に設定している。
と、いうことはTypeScriptがES2018に対応したバージョンでないといけない。

ES2018は多分これで対応している。(TypeScript 2.7以上)
https://github.com/Microsoft/TypeScript/issues/20342


自分の環境にインストールされているTypeScriptのバージョンは古かった。

```
$ tsc -v
Version 2.6.2
```

TypeScriptのバージョンを上げてビルドすることで解決した。

```
$ npm install typescript -g
$ tsc -v
Version 3.0.3
$ npm run build
```

PrerequisitesとしてTypeScriptのバージョンが何(2.7)以上が必要か記載してはいかがでしょうか。

**Comment by rednes** [comment]
【報告メモ（英語）】

# How about describing what TypeScript version (>=2.7.X) is required as Prerequisites?

https://awslabs.github.io/aws-cdk/getting-started.html

With reference to Getting Started, I tried to make TypeScript's AWS CDK app.
In the `Compile the Code` section, I got an error when building TypeScript.

```
$ npm run build
'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'esnext' for tsconfig.json (3,19): error TS 6046: Argument for ' .
```

In tsconfig.json, target of compilerOptions is set to ES2018.
Therefore, TypeScript needs to be a version supporting ES2018.

ES2018 is supported by TypeScript 2.7.
https://github.com/Microsoft/TypeScript/issues/20342


The version of TypeScript installed in my environment is old.

```
$ tsc -v
Version 2.6.2
```

It was solved by installing the latest TypeScript and building it.

```
$ npm install typescript -g
$ tsc -v
Version 3.0.3
$ npm run build
```

How about describing what TypeScript version (>=2.7.X) is required as Prerequisites?

**Comment by knokmki612** [comment]
ふりかえりました！

フィードバックする内容の経緯がよくわかるメモでしたし、フィードバックなされる内容も開発者に伝わりそうで気の利いた感じになっていると思います！

issue立てたらここで報告ください！

**Comment by tdtds** [comment]
次のワークショップが始まるのでいったんクローズしますね。
