### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-09-08: BanriIkku: FABOOLDesktop_opensource: Work log

### ISSUE THREAD

**Issue by BanriIkku** [oss-gate/workshop#948]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by haoling** [comment]
@haoling です。横にいるサポーターです。よろしくおねがいします。（本名は内緒でおねがいしますねｗ）

**Comment by BanriIkku** [comment]
## インストール作業
  * 公式HPのマニュアルを開く
https://www.smartdiys.com/manual/fabool-desktop-outline/
  * ２．FABOOL Desktopのインストールまで読み進める。
https://www.smartdiys.com/manual/fabool-desktop-registration/
そこのURLに乗っていたダウンロードリンクより、exeをダウンロードし、説明に従ってインストールした。
##  スリープ設定の解除
公式ドキュメントの指示に従い、スリープ設定を解除
https://www.tipsfound.com/windows10/03005

**Comment by BanriIkku** [comment]
## 起動時の初期設定
 *  使用するマシンを選択 し起動(Fabool Laser Mini 3.5Wを選択）

**Comment by BanriIkku** [comment]
## 使ってみた要望
* プリセット画像を選べるが、固定でなく追加したい。
下記ファイルのJSON?形式ファイルで保存しているようだ。
\\（インストールフォルダ)\FABOOLDesktop\data\ImgPreset.fdsi
* プリセットパラメータを選べるが、自分用の設定を追加したい。
下記ファイルのJSON?形式ファイルで保存しているようだ。
\\（インストールフォルダ)\FABOOLDesktop\data\PrmPreset.fdsp
 * 位置・大きさのダイアログは即時反映してほしい。
 * 画面拡大時の画面移動は、スクロールのみでマウスで動かせない。
 * イラストツールみたいに、どこを拡大しているかわかる全体画面ミニマップがあると良いのでは？
 * 線と線の接線まで近づける機能が欲しい。


## 別途公式が用意しているフォーラムに記載の要望
 * 閉じたパスに対しての塗り(フィル)の対応
 * 回数のカウンター(どこまで実行したか。実行時は0～100%表示でよく割らない）
 * Ｘ軸とＹ軸のそれぞれのキャリブレーションで補正値を設定できる機能（実加工サイズの補正用）
 * 文字を加工画面上での直入力したい。
 * 加工時の位置合わせに関して。位置決めに利用したいのでワンクリック照射機能
 * SVGではデータの色分けによりカットする／しないとか、カット条件などを変更できるが、これをＤＸＦでもできるようにしていただきたい。
 * 速度や強度、回数の一括入力機能
 * 加工開始すると一旦原点復帰してから加工するのは止めてほしい。
 * 加工するたびに加工中は離れるな、と叱られるが、じゃまです。メッセージを無くしてほしい。
 * 条件設定（速度とか出力とか）の数字が小さすぎます。もっと大きくしてください。
 * 加工完了時に音が鳴って終了を教えてくれる設定ができるようにならないでしょうか？

**Comment by BanriIkku** [comment]
## Web版の時からの気づいた違う点
* 現時点での照射が出来ない。
* 同一の線を増やせない。

**Comment by BanriIkku** [comment]
## 使ってみた要望
 * 画像取り込み時のラスタ画像２値化方式は、設定画面だがダイアログで選択できるようにすべきでは？
 * Ctrl+C,Ctrl+Vの標準的なコマンドをサポートしてほしい。
 * 選択画像がどのパラメータかわかるように、リストも協調できるようにしてほしい。

**Comment by BanriIkku** [comment]
## 不具合
Ver.1.4.5だと、LaserPowerとTimesが選択できなくなっている。

**Comment by knokmki612** [comment]
ふりかえりました！

**Comment by BanriIkku** [comment]
## その他気になった箇所
* githubに公開されているVerが1.4.4。公式より自動ダウンロードできるVerが1.4.5
https://github.com/smartDIYs/FABOOLDesktop_opensource
Ver.1.4.4の公開日が2018/08/08, Ver.14.5は2018/08/21
https://www.smartdiys.com/manual/fabool-desktop-releasenotes/

githubでのソースコードのコミットは2018/08/09で、最終の2018/08/21での変更は、コンパイル環境の情報修正のみ。

**Comment by BanriIkku** [comment]
## 報告
公式フォーラムへ要望という形で報告。

**Comment by tdtds** [comment]
次のワークショップが始まるのでいったんクローズしますね。
