### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-10-27: kanayama: language-ruby: Work log

### ISSUE THREAD

**Issue by Chinats** [oss-gate/workshop#978]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by monochromegane** [comment]
サポーターの三宅です，よろしくお願いします〜〜！！

**Comment by Chinats** [comment]
よろしくお願いします！

**Comment by Chinats** [comment]
atom/language-ruby
https://github.com/atom/language-ruby

**Comment by Chinats** [comment]
手元にcloneしました。

**Comment by Chinats** [comment]
specがあるけれども

rubyのminitestとかrailsのspecではなくて、拡張子が.coffeeのspec

動かし方がよくわからないのでちょっと調べてみる？

**Comment by Chinats** [comment]
調べてみた方が良さそう

実際に参加するのであればそのOSSの挙動は担保したコミットを。

**Comment by Chinats** [comment]
クローズしていないissueを見てみる

**Comment by Chinats** [comment]
https://github.com/atom/language-ruby/issues

**Comment by Chinats** [comment]
実際に解消した流れとかをおってみるために
クローズ済みで読み取りやすそうなissueを見てみる

**Comment by Chinats** [comment]
PR立てて直したissueと直さないでよかったものがある。

バグのように見えているけれど、Rubyのsyntaxなので対応しないけれど気になるよねと言う例
https://github.com/atom/language-ruby/issues/66

**Comment by Chinats** [comment]
`||`のハイライトの不具合のバクissueの例
https://github.com/atom/language-ruby/issues/214

実際に修正のコミットが取り込まれている
https://github.com/atom/language-ruby/labels/bug

**Comment by Chinats** [comment]
バグのissueを立てた人と修正した人は別人。

**Comment by Chinats** [comment]
PRも覗いてみる
https://github.com/atom/language-ruby/pulls

**Comment by Chinats** [comment]
コメントがたくさんあるPRを見てみる
https://github.com/atom/language-ruby/pull/224

**Comment by Chinats** [comment]
文化とか主にOSSを支えている人たちを読み取ることができるー。

**Comment by Chinats** [comment]
Atomのプラグインの作り方
自分がビルドして動かすところまでしてみる

**Comment by Chinats** [comment]
⬆️ローカル上で実際のAtomで確認できる状態を作る

**Comment by Chinats** [comment]
Atomのドキュメントを探す

**Comment by Chinats** [comment]
https://blog.github.com/2016-08-19-building-your-first-atom-plugin/

**Comment by Chinats** [comment]
コミュニティパッケージは、`.atom/packages`に、コアパッケージはAtomに組み込まれている。
と言うことがドキュメントから読み取れた。

コアパッケージについてのドキュメントを読みつつ
https://flight-manual.atom.io/hacking-atom/sections/maintaining-a-fork-of-a-core-package-in-atom-atom/

Atom本体をcloneして見てみる
https://github.com/atom/atom

**Comment by Chinats** [comment]
Atomに組み込まれている場所までたどり着いた
https://github.com/atom/language-ruby

**Comment by Chinats** [comment]
Atomに組み込まれている、ではなくて
Atomの配下に配置されていて、Atomをbuildするときに一緒にbuildされる

**Comment by Chinats** [comment]
手元でbuildする手順がこっちに書いてある
https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/

まずForkして

**Comment by Chinats** [comment]
cloneする

**Comment by Chinats** [comment]
`atom --dev {path-to-open}`
でdevモードでatomを起動することができる。

{path-to-open} はいつでも`atom/atom`では？
→ `atom --dev {path-to-open}`の`atom`でatomが起動している。{path-to-open}開きたいファイルないしフォルダを指定できる。

**Comment by Chinats** [comment]
`script/bootstrap`実行完了

**Comment by Chinats** [comment]
アプリケーションの下部にdev modeであることがわかるようにそっと表示してある。
dev modeひらけた！

**Comment by Chinats** [comment]
language-rubyが見当たらない

```
about				atom-light-ui			dalek				git-diff			language-rust-bundled		one-dark-ui
atom-dark-syntax		autoflow			deprecation-cop			go-to-line			line-ending-selector		one-light-syntax
atom-dark-ui			base16-tomorrow-dark-theme	dev-live-reload			grammar-selector		link				one-light-ui

```

**Comment by Chinats** [comment]
```
To load your package in development mode, create a symlink to it in ~/.atom/dev/packages. This occurs automatically when you clone the package with apm develop.
```
https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/


`~/.atom/dev/packages`にlanguage-rubyをcloneする

**Comment by Chinats** [comment]
# dev配下のlanguage-rubyを開発版で起動するための手順

## 1. 環境をリセット

Atomをuninstall

```
$ rm -rf ~/.atom`
$ rm /usr/local/bin/atom
$ rm /usr/local/bin/apm
```

## 2. Atomをinstall
https://atom.io/
DOWNLOADする

### language-rubyの挙動について
- preferenceのpackagesにデフォルトでinstallされている
- デフォルトでenableとなっている
![image](https://user-images.githubusercontent.com/17132564/47600555-d6e3b280-d9fd-11e8-8865-48103b1ad0fd.png)

- disableを選択すると無効になる（syntax hight lightが効いていないことが確認できる）
![image](https://user-images.githubusercontent.com/17132564/47600535-a26ff680-d9fd-11e8-8df9-f2ecf308bb43.png)

3.

**Comment by Chinats** [comment]
# ふりかえり

- 手順書の「そこは書いた方がいいんじゃ無い？」という種類のフィードバックもあり
- 常にメモを取りながら常に公式情報を見ながら実行
- 明日からできること
  - ユーザーとして動かす
  - 気になったことをまとめる
  - フィードバック

**Comment by Chinats** [comment]
手順についてもしかしたらフィードバックできるかもしれないポイントのめも

### 全体
- タイトルがわかりづらい・・・
現状: Hacking on Atom Core → Development environmentなど・・・

#### [Hacking on Atom Core](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/)
- 手順にatomコマンド→testコマンド→buildコマンドの順番で書いてある。atomコマンドを実行する前にbuildする必要があることがわかるように書いた方が良いのでは？
- 参照先やAtomとAtom Devの関係がわかるような図がある方が良いのでは？

#### [Contributing to Official Atom Packages](https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/)
- うまくリンクできると、develop packageであることがAtomの画面上から確認できることを記述した方が良いのでは？

**Comment by yoshitaku-jp** [comment]
今日はお疲れ様でした。ワークショップの中での貢献はできませんでしたが、明日からできることがリストアップされていていいと思います！今日やった作業メモを取っていくことや、分かりづらいことはないか目を光らせることは他のことでも役立つと思います！
わからないことがありましたらワークショップ以外の活動もありますので、そちらにも参加してみてください！本日は直接の担当ではありませんでしたが、少しでも貢献できていたら嬉しいです。ありがとうございました。

**Comment by Chinats** [comment]
普段使っていて特に不便やバグなど気になっていることが無いので、
何かフォローできないかissueを古いものから順番に見ていく作戦。

3つ4つ見たところで、類似のissueがあったらそちらに取り込む形でcloseされているものや、別件と合わせて対応中のものもあることを知る。


[50Wliu](https://github.com/50Wliu) さんがよく反応していらっしゃるのでフォローした。

**Comment by Chinats** [comment]
自分の環境の確認

```
$ atom --version
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.10
git 2.17.1
```
