### ISSUE TITLE
OSS Gate Workshop: Tokyo:  2018-10-27: EDAPIYO: jupyter notebook: Work log

### ISSUE THREAD

**Issue by EDAPIYO** [oss-gate/workshop#981]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yoshitaku-jp** [comment]
「よしたく」こと吉村です！
よろしくおねがいします！

**Comment by EDAPIYO** [comment]
宜しくお願いします。本名は中島ですw

**Comment by EDAPIYO** [comment]
インストール手順がAnaconda経由（強く推奨と記載）とpip経由二つあったが一番上に２通りあることが書いてなかった。
一番上に記載してあった方が分かりやすいはず。

**Comment by EDAPIYO** [comment]
Anaconda経由にてインストールができた。次は手順にそって以下を実施する
https://jupyter.readthedocs.io/en/latest/running.html#running

**Comment by EDAPIYO** [comment]
This will print some information about the notebook server in your terminal, including the URL of the web application (by default, http://localhost:8888):
と記載してあったが、実際には
http://localhost:8888/tree
がブラウザにて開かれた。

**Comment by EDAPIYO** [comment]
https://jupyter.readthedocs.io/en/latest/running.html#running
コマンドラインオプションの使い方は書いてあるが、そのあとどうするかの導線がなさそう

**Comment by EDAPIYO** [comment]
https://jupyter.readthedocs.io/en/latest/migrating.html
Nextとあったのでクリックしてみたが、Migrating from IPython Notebookが出てきた。
IPython Notebookは使っていないので自分にとっては関係のない項目だった

**Comment by EDAPIYO** [comment]
https://jupyter.readthedocs.io/en/latest/architecture/content-architecture.html
ここに「How IPython and Jupyter Notebook work」があった。
ここから動かせる？？

**Comment by EDAPIYO** [comment]
https://pythondatascience.plavox.info/python%E3%81%AE%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83/jupyter-notebook%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86

どうもIPythonNotebookが色々統合されてJupyter Notebookになった様子
だが初めて使おうとした人にIPythonの話をされても困ってしまう・・・

**Comment by EDAPIYO** [comment]
https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html
どうやって動かすかではなくどうやって動くかを説明していた
結局どうやって動かすのか・・•

**Comment by yoshitaku-jp** [comment]
別のところにもう少し使い方よりな物がありました。
https://jupyter-dashboards-layout.readthedocs.io/en/latest/index.html#

**Comment by EDAPIYO** [comment]
上記リンクにGitHubへの導線があった
https://github.com/jupyter/dashboards/blob/master/docs/source/index.rst

**Comment by EDAPIYO** [comment]
https://jupyter-dashboards-layout.readthedocs.io/en/latest/getting-started.html
最初のインストール手順と似たような記載が・・あった

**Comment by EDAPIYO** [comment]
以下の順で最初の使い方が記載してあった。
http://jupyter.org/index.html
→
http://jupyter.org/try
→
https://mybinder.org/v2/gh/ipython/ipython-in-depth/master?filepath=binder/Index.ipynb

インストールした後使い方のリンクがどこにいけば良いかわからなかった。
インストール後http://jupyter.org/tryにリンクがあればたどり着けたかも…

**Comment by EDAPIYO** [comment]
https://hub.mybinder.org/user/ipython-ipython-in-depth-hbm98l22/notebooks/examples/Notebook/Notebook%20Basics.ipynb#The-Notebook

辿っていくとhelp-> User Interface Tourがあるみたい
これを触ってみる

**Comment by EDAPIYO** [comment]
http://localhost:8888/notebooks/Untitled1test.ipynb
ツアーを初めてみるとファイル名変更のガイドでガイドが重なってファイル名の変更ができなかった

**Comment by EDAPIYO** [comment]
User Interface Tourはユーザインタフェースのツアーだけで結局どう使ったら良いのかわからなかった
Helpの中にNotebook Helpというのがあったので辿ってみるとそれっぽいのが出てきた。
http://nbviewer.jupyter.org/github/ipython/ipython/blob/3.x/examples/Notebook/Index.ipynb

**Comment by EDAPIYO** [comment]
Running Code
http://nbviewer.jupyter.org/github/ipython/ipython/blob/3.x/examples/Notebook/Running%20Code.ipynb
が見つかった。インストール後欲しかったのはここ・・・

**Comment by EDAPIYO** [comment]
フィードバックできそうなのは以下２点
・Anaconda経由とpip経由、２通りあることを一番最初に記載してほしかった
・インストール直後チュートリアルが触れる場所にリンクを張って欲しかった

以下経由で静的ホスティングされている様子なのでissueかpull requestすれば良いかも…？　
https://github.com/jupyter/jupyter.github.io

**Comment by monochromegane** [comment]
ふりかえりで話を聞かせてもらったサポーターの三宅です！
経緯がきちんとログに残っていてとてもわかりやすかったです！フィードバックネタもありそうなので午後もこの調子で頑張ってください！

**Comment by yoshitaku-jp** [comment]
https://engineers.connpass.com

https://kojirooooocks.hatenablog.com/entry/2018/09/21/223841

**Comment by EDAPIYO** [comment]
There are two kinds of installation methods, but when I accessed "http://jupyter.org/install", I can't notice it because there is no mention that at the top before installing.

It is easy to read by adding the following to the end of "Prerequisite: Python".
"There are two ways to install Jupyter Notebook, using Anaconda and with pip, but strongly recommend using Anaconda"

**Comment by EDAPIYO** [comment]
Jupyter Notebookをインストールするにあたって、pipを使ってインストールしたいと思っていたのですが、「http://jupyter.org/install」にアクセスした際、Using Anacondaが一番上にあり、pipを使う方法があることに気がつかずインストールしてしまいました。
このサイトの一番上にUsing Anacondaとwith pipの２つのインストール方法があることを記載して頂けると良いと思いました。

**Comment by yoshitaku-jp** [comment]
```
# Prerequisite: Python
While Jupyter runs code in many programming languages, Python is a requirement (Python 3.3 or greater, or Python 2.7) for installing the Jupyter Notebook itself.
```

```
Prerequisite: Python
While Jupyter runs code in many programming languages, Python is a requirement (Python 3.3 or greater, or Python 2.7) for installing the Jupyter Notebook itself.
- Installing Jupyter using Anaconda(**strongly recommend**)
- Installing Jupyter with pip
```

みたいに、例を載せるのも良いかもしれないですね！

**Comment by EDAPIYO** [comment]
I think it is better to mention that there are two ways to install by Anaconda or with pip at the end of the section "Prerequisite: Python" http://jupyter.org/install.

I wanted to install Jupyter Notebook, so I accessed the webpage.
I already installed Python. so, I wanted to install with pip.

However, after reading "Prerequisite: Python", since the next section was "Using Anaconda", I installed Anaconda. and I didn't notice the way of pip.

So, this is why I think it's better to mention two ways.

My idea is here:
Prerequisite: Python
While Jupyter runs code in many programming languages, Python is a requirement (Python 3.3 or greater, or Python 2.7) for installing the Jupyter Notebook itself.

Installing Jupyter using Anaconda(strongly recommend)
Installing Jupyter with pip

**Comment by yoshitaku-jp** [comment]
PRの出し方です
https://github.com/firstcontributions/first-contributions/blob/master/translations/README.ja.md

Hacktoberfestです
https://hacktoberfest.digitalocean.com

**Comment by yoshitaku-jp** [comment]
今日はお疲れ様でした。用事があり途中退室して申し訳ないです。
案内があったかも知れませんが、もくもく会など他にもコミュニティの活動がありますので、そちらでもお会いできたらと思います！ありがとうございました！

**Comment by EDAPIYO** [comment]
先日はありがとうございました。
なかなかはじめだすきっかけや全体の流れがつかめず躊躇していましたが、
今の自分でも参加できるきっかけがあるということが分かりましたし、
OSSに対する漠然とした恐怖心も取り除くことができたように思います。

今回で終わらず、継続して仕事の外で活動できれば、と思っています。
もくもく会も是非参加してみたいです。またお会いした際は是非よろしくお願いします。
