### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-10-27: olandy: visual studio code: Work log

### ISSUE THREAD

**Issue by olandy** [oss-gate/workshop#984]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Udomomo** [comment]
👍

**Comment by olandy** [comment]
コードを修正する系の貢献を次第場合は、それ用のガイドブックに則る必要があるらしい。
そのため、読んで見る
https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by olandy** [comment]
repositoryをクローンしてビルドを開始。以下の通り、gitコマンドごとドキュメントに書いてあるのでわかりやすかった。
git clone https://github.com/Microsoft/vscode.git

**Comment by olandy** [comment]
前提条件としての必要ツールがたくさんある。
* Git
* Node.JS
* Yarn
* Python
* C/C++ compiler tool chain
* Xcode 

以上が必要らしいので、インストールされていないNode.js,Yarn,Python,C++をインストールしていく

**Comment by olandy** [comment]
Node.JSをインストールしていく。
これについてはNode.jsダウンロードサイトへのリンクがあったが、バージョン管理ツールがあったほうがいいと思うので、ググってインストールしていく

**Comment by olandy** [comment]
Node.jsのバージョンについてドキュメントに 64bit, >= 8.12.0, < 9.0.0とあるので、指定されたバージョンのものをインストールする

**Comment by olandy** [comment]
次にYarnのインストールを行う。以下のインストールガイドに従えとあるので読み進めていく
https://yarnpkg.com/en/docs/install#mac-stable

**Comment by olandy** [comment]
Yarnのインストール
brew install yarn

**Comment by yoshitaku-jp** [comment]
フィードバックポイント

https://github.com/Microsoft/vscode/wiki/How-to-Contribute
の各ページへの飛ばし先を改善する必要あり？

- Pythonはv3がダメなのに、リンク先はv3のページになっている
    -  v2のページに変更しておく？
- node.jsのバージョンが指定されているなら、バージョン指定がされているコマンドを用意しておいてあげるのは？
- Yarnのmacインストール方法が2つあるなら、先に述べておく方法が親切では？
    - https://yarnpkg.com/en/docs/install#mac-stable

**Comment by olandy** [comment]
ガイドラインに習い既存のissueチケットに同様の内容がないか確認する

**Comment by olandy** [comment]
とりあえず手順に則って初issueを投げてみました
https://github.com/Microsoft/vscode/issues/61927
